{
  "abstract": [
    {
      "text": "Sent when the user selects one of a person’s properties.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:property:identifier:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbookui/documentation/AddressBookUI",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ABPeoplePickerNavigationControllerDelegate(im)peoplePickerNavigationController:shouldContinueAfterSelectingPerson:property:identifier:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "peoplePickerNavigationController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
        "text": "ABPeoplePickerNavigationController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "shouldContinueAfterSelectingPerson"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABRecordRef",
        "text": "ABRecord"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "property"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABPropertyID",
        "text": "ABPropertyID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "identifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABMultiValueIdentifier",
        "text": "ABMultiValueIdentifier"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Address Book UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:property:identifier:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "peoplePicker"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
              "text": "ABPeoplePickerNavigationController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "shouldContinueAfterSelectingPerson"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "person"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@ABRecordRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABRecordRef",
              "text": "ABRecord"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "property"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@ABPropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABPropertyID",
              "text": "ABPropertyID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "identifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@ABMultiValueIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABMultiValueIdentifier",
              "text": "ABMultiValueIdentifier"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The people-picker navigation controller with which the user interacted.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "peoplePicker"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The person whose contact information item the user selected.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "person"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The property the user selected.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "property"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identifier for the value the user selected if ",
                  "type": "text"
                },
                {
                  "code": "property",
                  "type": "codeVoice"
                },
                {
                  "text": " is a multivalue property; otherwise, ",
                  "type": "text"
                },
                {
                  "code": "kABMultiValueInvalidIdentifier",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "identifier"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to perform the action for the property selected and dismiss the picker. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to show the person in the picker.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called with an identifier. If you need an index, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AddressBook/ABMultiValueGetIndexForIdentifier(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to get the corresponding index.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbookui/documentation/AddressBookUI": {
      "abstract": [
        {
          "text": "Access users’ contacts and display them in a graphical interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book UI",
      "type": "topic",
      "url": "/documentation/addressbookui"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationController": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "ABPeoplePickerNavigationController",
          "type": "codeVoice"
        },
        {
          "text": " class (whose instances are known as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "people-picker navigation controllers",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ") implements a view controller that manages a set of views that allow the user to select a contact or one of its contact-information items from an address book.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPeoplePickerNavigationController"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerNavigationController"
        }
      ],
      "role": "symbol",
      "title": "ABPeoplePickerNavigationController",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontroller"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "ABPeoplePickerNavigationControllerDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol describes the interface ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " delegates must adopt to respond to people-picker user events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPeoplePickerNavigationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerNavigationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "ABPeoplePickerNavigationControllerDelegate",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:)": {
      "abstract": [
        {
          "text": "Called after a person has been selected by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
          "text": "ABPeoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController:didSelectPerson:"
        }
      ],
      "role": "symbol",
      "title": "peoplePickerNavigationController(_:didSelectPerson:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontroller(_:didselectperson:)"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:property:identifier:)": {
      "abstract": [
        {
          "text": "Called after a property has been selected by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
          "text": "ABPeoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "property"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyID",
          "text": "ABPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABMultiValueIdentifier",
          "text": "ABMultiValueIdentifier"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:property:identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController:didSelectPerson:property:identifier:"
        }
      ],
      "role": "symbol",
      "title": "peoplePickerNavigationController(_:didSelectPerson:property:identifier:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontroller(_:didselectperson:property:identifier:)"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)": {
      "abstract": [
        {
          "text": "Sent when the user selects a contact.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
          "text": "ABPeoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldContinueAfterSelectingPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:"
        }
      ],
      "role": "symbol",
      "title": "peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontroller(_:shouldcontinueafterselectingperson:)"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)": {
      "abstract": [
        {
          "text": "Sent when the user selects one of a person’s properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
          "text": "ABPeoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldContinueAfterSelectingPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "property"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyID",
          "text": "ABPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABMultiValueIdentifier",
          "text": "ABMultiValueIdentifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:property:identifier:"
        }
      ],
      "role": "symbol",
      "title": "peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontroller(_:shouldcontinueafterselectingperson:property:identifier:)"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationControllerDidCancel(_:)": {
      "abstract": [
        {
          "text": "Sent when the user taps Cancel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationControllerDidCancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
          "text": "ABPeoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationControllerDidCancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationControllerDidCancel:"
        }
      ],
      "role": "symbol",
      "title": "peoplePickerNavigationControllerDidCancel(_:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontrollerdidcancel(_:)"
    },
    "doc://com.apple.documentation/documentation/AddressBook/ABMultiValueGetIndexForIdentifier(_:_:)": {
      "abstract": [
        {
          "text": "Returns the location (within a multivalue property) of a value with a given identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValueGetIndexForIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "multiValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABMultiValueRef",
          "text": "ABMultiValue"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABMultiValueIdentifier",
          "text": "ABMultiValueIdentifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AddressBook/ABMultiValueGetIndexForIdentifier(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABMultiValueGetIndexForIdentifier(_:_:)",
      "type": "topic",
      "url": "/documentation/AddressBook/ABMultiValueGetIndexForIdentifier(_:_:)"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@ABMultiValueIdentifier": {
      "abstract": [
        {
          "text": "Identifies multivalue properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABMultiValueIdentifier"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@ABMultiValueIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABMultiValueIdentifier",
      "type": "topic",
      "url": "/documentation/AddressBook/ABMultiValueIdentifier"
    },
    "doc://com.externally.resolved.symbol/c:@T@ABPropertyID": {
      "abstract": [
        {
          "text": "Integer that identifies a record property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPropertyID"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@ABPropertyID",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABPropertyID",
      "type": "topic",
      "url": "/documentation/AddressBook/ABPropertyID"
    },
    "doc://com.externally.resolved.symbol/c:@T@ABRecordRef": {
      "abstract": [
        {
          "text": "A reference to an ABRecord object or any of its derivedopaque types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@ABRecordRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABRecord",
      "type": "topic",
      "url": "/documentation/AddressBook/ABRecord-swift.typealias"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-User-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationControllerDidCancel(_:)",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:)",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:property:identifier:)"
      ],
      "title": "Responding to User Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:property:identifier:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:property:identifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbookui/documentation/AddressBookUI",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-User-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationControllerDidCancel(_:)",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:)",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:property:identifier:)"
              ],
              "title": "Responding to User Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "peoplePickerNavigationController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
                    "text": "ABPeoplePickerNavigationController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "peoplePicker"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "shouldContinueAfterSelectingPerson:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@ABRecordRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABRecordRef",
                    "text": "ABRecordRef"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "person"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "property:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@ABPropertyID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABPropertyID",
                    "text": "ABPropertyID"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "identifier:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@ABMultiValueIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABMultiValueIdentifier",
                    "text": "ABMultiValueIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "identifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The people-picker navigation controller with which the user interacted.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "peoplePicker"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The person whose contact information item the user selected.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "person"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The property the user selected.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "property"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The identifier for the value the user selected if ",
                        "type": "text"
                      },
                      {
                        "code": "property",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is a multivalue property; otherwise, ",
                        "type": "text"
                      },
                      {
                        "code": "kABMultiValueInvalidIdentifier",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "identifier"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " to perform the action for the property selected and dismiss the picker. ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " to show the person in the picker.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:property:identifier:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:didSelectPerson:)/title",
          "value": "peoplePickerNavigationController:didSelectPerson:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:didSelectPerson:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationController:didSelectPerson:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)/title",
          "value": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:property:identifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:property:identifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@ABPropertyID/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@int32_t",
              "text": "int32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABPropertyID"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)/title",
          "value": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationControllerDidCancel(_:)/title",
          "value": "peoplePickerNavigationControllerDidCancel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationControllerDidCancel(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationControllerDidCancel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationController/title",
          "value": "ABPeoplePickerNavigationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerNavigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerNavigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate/title",
          "value": "ABPeoplePickerNavigationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerNavigationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerNavigationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@ABMultiValueIdentifier/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@int32_t",
              "text": "int32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABMultiValueIdentifier"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AddressBook~1ABMultiValueGetIndexForIdentifier(_:_:)/title",
          "value": "ABMultiValueGetIndexForIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AddressBook~1ABMultiValueGetIndexForIdentifier(_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFIndex",
              "text": "CFIndex"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABMultiValueGetIndexForIdentifier"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABMultiValueRef",
              "text": "ABMultiValueRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "multiValue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABMultiValueIdentifier",
              "text": "ABMultiValueIdentifier"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "identifier"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@ABRecordRef/title",
          "value": "ABRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@ABRecordRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABRecordRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:didSelectPerson:property:identifier:)/title",
          "value": "peoplePickerNavigationController:didSelectPerson:property:identifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:didSelectPerson:property:identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationController:didSelectPerson:property:identifier:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontroller(_:shouldcontinueafterselectingperson:property:identifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontroller(_:shouldcontinueafterselectingperson:property:identifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
