{
  "abstract": [
    {
      "text": "Creates an activation descriptor with the activation type you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCActivationDescriptor(cm)descriptorWithType:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "type"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MLCActivationType",
        "text": "MLCActivationType"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "descriptorWithType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(type:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "activationType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MLCActivationType",
              "text": "MLCActivationType"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A type of activation function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "activationType"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this initializer to create one of the following activation descriptors:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "f(x) = fabs(x)",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Absolute",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Activation type: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "f(x) = x * CDF(x)",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "GELU",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Activation type: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "f(x) = 0, if x <= -3",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Hard Swish",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "code": "f(x) = x, if x >= +3",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "f(x) = x * (x + 3)/6",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Activation type: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "f(x) = x",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Identity",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Activation type: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "f(x) = log(1 / (1 + exp(-x)))",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "LogSigmoid",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Activation type: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "f(x) = x / (1 + abs(x))",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Parametric Soft Sign",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Activation type: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softSign",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "f(x) = scale * (max(0, x) + min(0, α * (exp(x)−1)))",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", where:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "SELU",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "code": "α = 1.6732632423543772848170429916717",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "scale = 1.0507009873554804934193349852946",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Activation type: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "f(x) = 1 / (1 + e⁻ˣ)",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Sigmoid",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Activation type: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "f(x) = x - tanh(x)",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "TanhShrink",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Activation type: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanhShrink",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create an activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCActivationDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:)": {
      "abstract": [
        {
          "text": "Creates an activation descriptor with the activation type you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCActivationType",
          "text": "MLCActivationType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:"
        }
      ],
      "role": "symbol",
      "title": "init(type:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationdescriptor/init(type:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:)": {
      "abstract": [
        {
          "text": "Creates an activation descriptor with the activation type and parameter a that you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCActivationType",
          "text": "MLCActivationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:a:"
        }
      ],
      "role": "symbol",
      "title": "init(type:a:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationdescriptor/init(type:a:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:)": {
      "abstract": [
        {
          "text": "Creates an activation descriptor with the activation type and parameters a and b that you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCActivationType",
          "text": "MLCActivationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:a:b:"
        }
      ],
      "role": "symbol",
      "title": "init(type:a:b:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationdescriptor/init(type:a:b:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:c:)": {
      "abstract": [
        {
          "text": "Creates an activation descriptor with the activation type and parameters a, b, and c that you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCActivationType",
          "text": "MLCActivationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "c"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:c:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:a:b:c:"
        }
      ],
      "role": "symbol",
      "title": "init(type:a:b:c:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationdescriptor/init(type:a:b:c:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType": {
      "abstract": [
        {
          "text": "An activation type that you specify for an activation descriptor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCActivationType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationType"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute": {
      "abstract": [
        {
          "text": "An activation type that implements the absolute activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "absolute"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeAbsolute"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.absolute",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/absolute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu": {
      "abstract": [
        {
          "text": "An activation type that implements the gaussian error linear unit activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gelu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeGELU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.gelu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/gelu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish": {
      "abstract": [
        {
          "text": "An activation type that implements the hard swish activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardSwish"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeHardSwish"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.hardSwish",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/hardswish"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid": {
      "abstract": [
        {
          "text": "An activation type that implements the log sigmoid activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logSigmoid"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeLogSigmoid"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.logSigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/logsigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none": {
      "abstract": [
        {
          "text": "An activation type that implements the identity function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeNone"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.none",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/none"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu": {
      "abstract": [
        {
          "text": "An activation type that implements the scaled exponential linear unit activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSELU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.selu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/selu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid": {
      "abstract": [
        {
          "text": "An activation type that implements the sigmoid activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sigmoid"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSigmoid"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.sigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/sigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softSign": {
      "abstract": [
        {
          "text": "An activation type that implements the parametric soft sign activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softSign"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSoftSign"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.softSign",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/softsign"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanhShrink": {
      "abstract": [
        {
          "text": "An activation type that implements the hyperbolic tangent shrink activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tanhShrink"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanhShrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeTanhShrink"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.tanhShrink",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/tanhshrink"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Activation-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:c:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType"
      ],
      "title": "Creating Activation Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "descriptorWithType:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Activation-Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:c:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType"
              ],
              "title": "Creating Activation Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "descriptorWithType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MLCActivationType",
                    "text": "MLCActivationType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "activationType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A type of activation function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "activationType"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1softSign/title",
          "value": "MLCActivationTypeSoftSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1softSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSoftSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1sigmoid/title",
          "value": "MLCActivationTypeSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1sigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1tanhShrink/title",
          "value": "MLCActivationTypeTanhShrink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1tanhShrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeTanhShrink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1logSigmoid/title",
          "value": "MLCActivationTypeLogSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1logSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeLogSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1selu/title",
          "value": "MLCActivationTypeSELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1selu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1gelu/title",
          "value": "MLCActivationTypeGELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1gelu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeGELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor/title",
          "value": "MLCActivationDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1absolute/title",
          "value": "MLCActivationTypeAbsolute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1absolute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeAbsolute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1none/title",
          "value": "MLCActivationTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:)/title",
          "value": "descriptorWithType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardSwish/title",
          "value": "MLCActivationTypeHardSwish"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardSwish/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeHardSwish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType/title",
          "value": "MLCActivationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:b:)/title",
          "value": "descriptorWithType:a:b:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:b:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithType:a:b:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:)/title",
          "value": "descriptorWithType:a:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithType:a:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:b:c:)/title",
          "value": "descriptorWithType:a:b:c:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:b:c:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithType:a:b:c:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcactivationdescriptor/init(type:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcactivationdescriptor/init(type:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
