{
  "abstract": [
    {
      "text": "Constants that describe the method to use when searching text for words that match a string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UITextSearchMatchMethod",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WordMatchMethod"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WordMatchMethod"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UITextSearchOptions.WordMatchMethod"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WordMatchMethod"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction": {
      "abstract": [
        {
          "text": "An interaction that provides text finding and replacing operations using a system find panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIFindInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate": {
      "abstract": [
        {
          "text": "A delegate object that provides a session object to manage the search state for a find interaction and receives notifications of search session lifetimes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIFindInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession": {
      "abstract": [
        {
          "text": "An abstract base class that manages the state, presentation, and behavior for a search that the find interaction initiates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindSession"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the results summary the find panel UI includes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession.SearchResultDisplayStyle",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle": {
      "abstract": [
        {
          "text": "Constants that describe the style a find session uses to decorate the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchFoundTextStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchFoundTextStyle"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchFoundTextStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchfoundtextstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions": {
      "abstract": [
        {
          "text": "An object containing the configurable options for a text search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the method to use when searching text for words that match a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/contains": {
      "abstract": [
        {
          "text": "The word contains the search string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contains"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/contains",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchMatchMethodContains"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod.contains",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum/contains"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/fullWord": {
      "abstract": [
        {
          "text": "The word matches the search string exactly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullWord"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/fullWord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchMatchMethodFullWord"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod.fullWord",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum/fullword"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/startsWith": {
      "abstract": [
        {
          "text": "The word contains the search string as a prefix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startsWith"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/startsWith",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchMatchMethodStartsWith"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod.startsWith",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum/startswith"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-3wkjv": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s searchable objects to perform search operations and decorate the found text results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-3wkjv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "role": "symbol",
      "title": "UITextSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-3wkjv"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s searchable objects to perform search operations and decorate the found text results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession": {
      "abstract": [
        {
          "text": "A find session object that wraps a searchable object implementing the text-searching protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchingFindSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchingFindSession"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchingFindSession",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchingfindsession"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Find-and-replace",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-3wkjv",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
      ],
      "title": "Find and replace"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/contains",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/startsWith",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/fullWord"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextSearchMatchMethod"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/contains",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/startsWith",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/fullWord"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Find-and-replace",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
              ],
              "title": "Find and replace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITextSearchMatchMethod"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/title",
          "value": "UIFindSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/title",
          "value": "UIFindSessionSearchResultDisplayStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/title",
          "value": "UITextSearchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/title",
          "value": "UITextSearchMatchMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1fullWord/title",
          "value": "UITextSearchMatchMethodFullWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1fullWord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethodFullWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/title",
          "value": "UITextSearchingFindSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchingFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchingFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/title",
          "value": "UIFindInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/title",
          "value": "UIFindInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1contains/title",
          "value": "UITextSearchMatchMethodContains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1contains/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethodContains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/title",
          "value": "UITextSearchFoundTextStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchFoundTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchFoundTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1startsWith/title",
          "value": "UITextSearchMatchMethodStartsWith"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1startsWith/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethodStartsWith"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
