{
  "abstract": [
    {
      "text": "The method to use when searching text for matches to words.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/wordMatchMethod-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITextSearchOptions(py)wordMatchMethod",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "wordMatchMethod"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UITextSearchOptions",
        "text": "UITextSearchOptions"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UITextSearchMatchMethod",
        "text": "WordMatchMethod"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "wordMatchMethod"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "wordMatchMethod"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "wordMatchMethod"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextSearchOptions",
              "text": "UITextSearchOptions"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UITextSearchMatchMethod",
              "text": "WordMatchMethod"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions": {
      "abstract": [
        {
          "text": "An object containing the configurable options for a text search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the method to use when searching text for words that match a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/stringCompareOptions": {
      "abstract": [
        {
          "text": "The options to use in comparisons when searching text for matches to a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stringCompareOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSString",
          "text": "NSString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSStringCompareOptions",
          "text": "CompareOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/stringCompareOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringCompareOptions"
        }
      ],
      "role": "symbol",
      "title": "stringCompareOptions",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/stringcompareoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/wordMatchMethod-swift.property": {
      "abstract": [
        {
          "text": "The method to use when searching text for matches to words.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wordMatchMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextSearchOptions",
          "text": "UITextSearchOptions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITextSearchMatchMethod",
          "text": "WordMatchMethod"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/wordMatchMethod-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wordMatchMethod"
        }
      ],
      "role": "symbol",
      "title": "wordMatchMethod",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-searches",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/stringCompareOptions",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum"
      ],
      "title": "Configuring searches"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "wordMatchMethod"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wordMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-searches",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/stringCompareOptions",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum"
              ],
              "title": "Configuring searches"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UITextSearchMatchMethod",
                    "text": "UITextSearchMatchMethod"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "wordMatchMethod"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/title",
          "value": "UITextSearchMatchMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/title",
          "value": "UITextSearchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1stringCompareOptions/title",
          "value": "stringCompareOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1stringCompareOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stringCompareOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1wordMatchMethod-swift.property/title",
          "value": "wordMatchMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1wordMatchMethod-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wordMatchMethod"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
