{
  "abstract": [
    {
      "text": "Notifies observers that the preference pane should not be deselected.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneCancelUnselectNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSPreferencePaneCancelUnselectNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSPreferencePaneCancelUnselectNotification"
      }
    ],
    "modules": [
      {
        "name": "Preference Panes"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPreferencePaneCancelUnselectNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSPreferencePaneCancelUnselectNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPreferencePaneCancelUnselectNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Posted when ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is invoked with an argument of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " after ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/shouldUnselect",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " has returned a value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1507018-nspreferencepanecancelunselect": {
      "abstract": [
        {
          "text": "Notifies observers that the preference pane should not be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSPreferencePaneCancelUnselect"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1507018-nspreferencepanecancelunselect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPreferencePaneCancelUnselect",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1507018-nspreferencepanecancelunselect"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1507050-nspreferencepanedounselect": {
      "abstract": [
        {
          "text": "Notifies observers that the preference pane may be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSPreferencePaneDoUnselect"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1507050-nspreferencepanedounselect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPreferencePaneDoUnselect",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1507050-nspreferencepanedounselect"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1638126-nspreferenceprefpaneisavailable": {
      "abstract": [
        {
          "text": "Notifies observers that the system preferences app is available to display your preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSPreferencePrefPaneIsAvailable"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1638126-nspreferenceprefpaneisavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPreferencePrefPaneIsAvailable",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1638126-nspreferenceprefpaneisavailable"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1638128-nspreferencepaneupdatehelpmenu": {
      "abstract": [
        {
          "text": "Notifies observers that your help menu content changed. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSPreferencePaneUpdateHelpMenu"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1638128-nspreferencepaneupdatehelpmenu",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPreferencePaneUpdateHelpMenu",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1638128-nspreferencepaneupdatehelpmenu"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1638130-nspreferencepaneswitchtopane": {
      "abstract": [
        {
          "text": "Notifies observers that the user selected a new preference pane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSPreferencePaneSwitchToPane"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1638130-nspreferencepaneswitchtopane",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPreferencePaneSwitchToPane",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1638130-nspreferencepaneswitchtopane"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes": {
      "abstract": [
        {
          "text": "Integrate your app’s custom preferences into the System Preferences app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes",
      "kind": "symbol",
      "role": "collection",
      "title": "Preference Panes",
      "type": "topic",
      "url": "/documentation/preferencepanes"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)": {
      "abstract": [
        {
          "text": "Notifies the main application of the preference pane’s ability to be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toShouldUnselect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replyToShouldUnselect:"
        }
      ],
      "role": "symbol",
      "title": "reply(toShouldUnselect:)",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepane/reply(toshouldunselect:)"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/shouldUnselect": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the preference pane is able to be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldUnselect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPreferencePaneUnselectReply",
          "text": "NSPreferencePaneUnselectReply"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/shouldUnselect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldUnselect"
        }
      ],
      "role": "symbol",
      "title": "shouldUnselect",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepane/shouldunselect"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneCancelUnselectNotification": {
      "abstract": [
        {
          "text": "Notifies observers that the preference pane should not be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPreferencePaneCancelUnselectNotification"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneCancelUnselectNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPreferencePaneCancelUnselectNotification",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepanecancelunselectnotification"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneDoUnselectNotification": {
      "abstract": [
        {
          "text": "Notifies observers that the preference pane may be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPreferencePaneDoUnselectNotification"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneDoUnselectNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPreferencePaneDoUnselectNotification",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepanedounselectnotification"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneSwitchToPaneNotification": {
      "abstract": [
        {
          "text": "Notifies observers that the user selected a new preference pane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPreferencePaneSwitchToPaneNotification"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneSwitchToPaneNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPreferencePaneSwitchToPaneNotification",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneswitchtopanenotification"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater": {
      "abstract": [
        {
          "text": "Delay the deselection until the preference pane invokes ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unselectLater"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnselectLater"
        }
      ],
      "role": "symbol",
      "title": "NSPreferencePaneUnselectReply.unselectLater",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneunselectreply/unselectlater"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUpdateHelpMenuNotification": {
      "abstract": [
        {
          "text": "Notifies observers that your help menu content changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPreferencePaneUpdateHelpMenuNotification"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUpdateHelpMenuNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPreferencePaneUpdateHelpMenuNotification",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneupdatehelpmenunotification"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePrefPaneIsAvailableNotification": {
      "abstract": [
        {
          "text": "Notifies observers that the system preferences app is available to display your preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPreferencePrefPaneIsAvailableNotification"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePrefPaneIsAvailableNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPreferencePrefPaneIsAvailableNotification",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferenceprefpaneisavailablenotification"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1638126-nspreferenceprefpaneisavailable",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePrefPaneIsAvailableNotification",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1507050-nspreferencepanedounselect",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneDoUnselectNotification",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1507018-nspreferencepanecancelunselect",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1638130-nspreferencepaneswitchtopane",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneSwitchToPaneNotification",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1638128-nspreferencepaneupdatehelpmenu",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUpdateHelpMenuNotification"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectLater/title",
          "value": "NSUnselectLater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectLater/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnselectLater"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1reply(toShouldUnselect:)/title",
          "value": "replyToShouldUnselect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1reply(toShouldUnselect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replyToShouldUnselect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1shouldUnselect/title",
          "value": "shouldUnselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1shouldUnselect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldUnselect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/preferencepanes/nspreferencepanecancelunselectnotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
