{
  "abstract": [
    {
      "text": "The global help menu items associated with a preference pane.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuInfoPListKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSPrefPaneHelpMenuInfoPListKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPrefPaneHelpMenuInfoPListKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Preference Panes"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPrefPaneHelpMenuInfoPListKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSPrefPaneHelpMenuInfoPListKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPrefPaneHelpMenuInfoPListKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes": {
      "abstract": [
        {
          "text": "Integrate your app’s custom preferences into the System Preferences app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes",
      "kind": "symbol",
      "role": "collection",
      "title": "Preference Panes",
      "type": "topic",
      "url": "/documentation/preferencepanes"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuAnchorKey": {
      "abstract": [
        {
          "text": "The help book anchor to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrefPaneHelpMenuAnchorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuAnchorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrefPaneHelpMenuAnchorKey"
        }
      ],
      "role": "symbol",
      "title": "NSPrefPaneHelpMenuAnchorKey",
      "type": "topic",
      "url": "/documentation/preferencepanes/nsprefpanehelpmenuanchorkey"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuInfoPListKey": {
      "abstract": [
        {
          "text": "The global help menu items associated with a preference pane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrefPaneHelpMenuInfoPListKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuInfoPListKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrefPaneHelpMenuInfoPListKey"
        }
      ],
      "role": "symbol",
      "title": "NSPrefPaneHelpMenuInfoPListKey",
      "type": "topic",
      "url": "/documentation/preferencepanes/nsprefpanehelpmenuinfoplistkey"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuTitleKey": {
      "abstract": [
        {
          "text": "The title of a help menu item in a preference pane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrefPaneHelpMenuTitleKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuTitleKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrefPaneHelpMenuTitleKey"
        }
      ],
      "role": "symbol",
      "title": "NSPrefPaneHelpMenuTitleKey",
      "type": "topic",
      "url": "/documentation/preferencepanes/nsprefpanehelpmenutitlekey"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Help-Menu-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuTitleKey",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuAnchorKey"
      ],
      "title": "Help Menu Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrefPaneHelpMenuInfoPListKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrefPaneHelpMenuInfoPListKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Help-Menu-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuTitleKey",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPrefPaneHelpMenuAnchorKey"
              ],
              "title": "Help Menu Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPrefPaneHelpMenuInfoPListKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPrefPaneHelpMenuAnchorKey/title",
          "value": "NSPrefPaneHelpMenuAnchorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPrefPaneHelpMenuAnchorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrefPaneHelpMenuAnchorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPrefPaneHelpMenuInfoPListKey/title",
          "value": "NSPrefPaneHelpMenuInfoPListKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPrefPaneHelpMenuInfoPListKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrefPaneHelpMenuInfoPListKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPrefPaneHelpMenuTitleKey/title",
          "value": "NSPrefPaneHelpMenuTitleKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPrefPaneHelpMenuTitleKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrefPaneHelpMenuTitleKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/preferencepanes/nsprefpanehelpmenuinfoplistkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/preferencepanes/nsprefpanehelpmenuinfoplistkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
