{
  "abstract": [
    {
      "text": "Constants that indicate the preference pane’s availability to be deselected.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSPreferencePaneUnselectReply",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPreferencePaneUnselectReply"
      }
    ],
    "modules": [
      {
        "name": "Preference Panes"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPreferencePaneUnselectReply"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSPreferencePaneUnselectReply"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPreferencePaneUnselectReply"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes": {
      "abstract": [
        {
          "text": "Integrate your app’s custom preferences into the System Preferences app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes",
      "kind": "symbol",
      "role": "collection",
      "title": "Preference Panes",
      "type": "topic",
      "url": "/documentation/preferencepanes"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/didSelect()": {
      "abstract": [
        {
          "text": "Notifies the preference pane that the main app has just displayed the preference pane’s main view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/didSelect()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didSelect"
        }
      ],
      "role": "symbol",
      "title": "didSelect()",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepane/didselect()"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/didUnselect()": {
      "abstract": [
        {
          "text": "Notifies the preference pane that the main app has just stopped displaying the preference pane’s main view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didUnselect"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/didUnselect()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didUnselect"
        }
      ],
      "role": "symbol",
      "title": "didUnselect()",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepane/didunselect()"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/isSelected": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the preference pane is currently selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSelected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/isSelected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selected"
        }
      ],
      "role": "symbol",
      "title": "isSelected",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepane/isselected"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)": {
      "abstract": [
        {
          "text": "Notifies the main application of the preference pane’s ability to be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toShouldUnselect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replyToShouldUnselect:"
        }
      ],
      "role": "symbol",
      "title": "reply(toShouldUnselect:)",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepane/reply(toshouldunselect:)"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/shouldUnselect": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the preference pane is able to be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldUnselect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPreferencePaneUnselectReply",
          "text": "NSPreferencePaneUnselectReply"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/shouldUnselect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldUnselect"
        }
      ],
      "role": "symbol",
      "title": "shouldUnselect",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepane/shouldunselect"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/willSelect()": {
      "abstract": [
        {
          "text": "Notifies the preference pane that the main app is about to display the preference pane’s main view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willSelect"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/willSelect()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willSelect"
        }
      ],
      "role": "symbol",
      "title": "willSelect()",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepane/willselect()"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/willUnselect()": {
      "abstract": [
        {
          "text": "Notifies the preference pane that the main app is about to stop displaying the preference pane’s main view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willUnselect"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/willUnselect()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willUnselect"
        }
      ],
      "role": "symbol",
      "title": "willUnselect()",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepane/willunselect()"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply": {
      "abstract": [
        {
          "text": "Constants that indicate the preference pane’s availability to be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPreferencePaneUnselectReply"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPreferencePaneUnselectReply"
        }
      ],
      "role": "symbol",
      "title": "NSPreferencePaneUnselectReply",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneunselectreply"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneunselectreply/init(rawvalue:)"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectCancel": {
      "abstract": [
        {
          "text": "Cancel the deselection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unselectCancel"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnselectCancel"
        }
      ],
      "role": "symbol",
      "title": "NSPreferencePaneUnselectReply.unselectCancel",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneunselectreply/unselectcancel"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater": {
      "abstract": [
        {
          "text": "Delay the deselection until the preference pane invokes ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unselectLater"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnselectLater"
        }
      ],
      "role": "symbol",
      "title": "NSPreferencePaneUnselectReply.unselectLater",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneunselectreply/unselectlater"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectNow": {
      "abstract": [
        {
          "text": "Continue the deselection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unselectNow"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectNow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnselectNow"
        }
      ],
      "role": "symbol",
      "title": "NSPreferencePaneUnselectReply.unselectNow",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneunselectreply/unselectnow"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selecting-and-Deselecting-the-Preference-Pane",
      "generated": true,
      "identifiers": [
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/willSelect()",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/didSelect()",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/willUnselect()",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/didUnselect()",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/isSelected",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/shouldUnselect",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)"
      ],
      "title": "Selecting and Deselecting the Preference Pane"
    }
  ],
  "topicSections": [
    {
      "anchor": "Replies",
      "identifiers": [
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectCancel",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectNow",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater"
      ],
      "title": "Replies"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPreferencePaneUnselectReply"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPreferencePaneUnselectReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPreferencePaneUnselectReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Replies",
              "identifiers": [
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectCancel",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectNow",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater"
              ],
              "title": "Replies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selecting-and-Deselecting-the-Preference-Pane",
              "generated": true,
              "identifiers": [
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/willSelect()",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/didSelect()",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/willUnselect()",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/didUnselect()",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/isSelected",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/shouldUnselect",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)"
              ],
              "title": "Selecting and Deselecting the Preference Pane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPreferencePaneUnselectReply"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1willUnselect()/title",
          "value": "willUnselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1willUnselect()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willUnselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1didSelect()/title",
          "value": "didSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1didSelect()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1didUnselect()/title",
          "value": "didUnselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1didUnselect()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didUnselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectLater/title",
          "value": "NSUnselectLater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectLater/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnselectLater"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectNow/title",
          "value": "NSUnselectNow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectNow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnselectNow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1shouldUnselect/title",
          "value": "shouldUnselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1shouldUnselect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldUnselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply/title",
          "value": "NSPreferencePaneUnselectReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPreferencePaneUnselectReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPreferencePaneUnselectReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1isSelected/title",
          "value": "selected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1isSelected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectCancel/title",
          "value": "NSUnselectCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnselectCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1reply(toShouldUnselect:)/title",
          "value": "replyToShouldUnselect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1reply(toShouldUnselect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replyToShouldUnselect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1willSelect()/title",
          "value": "willSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1willSelect()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willSelect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/preferencepanes/nspreferencepaneunselectreply"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/preferencepanes/nspreferencepaneunselectreply"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
