{
  "abstract": [
    {
      "text": "A mode that adds a 3D position and orientation to sound by panning across the available output channels.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE",
        "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/alwaysUseChannelBased"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHASESpatializationMode@PHASESpatializationModeAlwaysUseChannelBased",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "alwaysUseChannelBased"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASESpatializationModeAlwaysUseChannelBased"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHASESpatializationMode.alwaysUseChannelBased"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "alwaysUseChannelBased"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The framework selects a channel layout for the output audio that’s compatible with the device’s channel configuration in Settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This mode applies the same effect regardless of the current output device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode": {
      "abstract": [
        {
          "text": "The manner in which PHASE outputs spatial audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESpatializationMode"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatializationMode"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatializationMode",
      "type": "topic",
      "url": "/documentation/phase/phasespatializationmode"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/alwaysUseBinaural": {
      "abstract": [
        {
          "text": "A mode that introduces special processing to replicate a realistic spatial listening experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alwaysUseBinaural"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/alwaysUseBinaural",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatializationModeAlwaysUseBinaural"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatializationMode.alwaysUseBinaural",
      "type": "topic",
      "url": "/documentation/phase/phasespatializationmode/alwaysusebinaural"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/alwaysUseChannelBased": {
      "abstract": [
        {
          "text": "A mode that adds a 3D position and orientation to sound by panning across the available output channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alwaysUseChannelBased"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/alwaysUseChannelBased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatializationModeAlwaysUseChannelBased"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatializationMode.alwaysUseChannelBased",
      "type": "topic",
      "url": "/documentation/phase/phasespatializationmode/alwaysusechannelbased"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/automatic": {
      "abstract": [
        {
          "text": "A mode that indicates that the framework chooses the spatialization mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatializationModeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatializationMode.automatic",
      "type": "topic",
      "url": "/documentation/phase/phasespatializationmode/automatic"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/automatic",
        "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/alwaysUseBinaural"
      ],
      "title": "Modes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASESpatializationModeAlwaysUseChannelBased"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatializationModeAlwaysUseChannelBased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE",
                "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Modes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/automatic",
                "doc://com.apple.phase/documentation/PHASE/PHASESpatializationMode/alwaysUseBinaural"
              ],
              "title": "Modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHASESpatializationModeAlwaysUseChannelBased"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode~1alwaysUseBinaural/title",
          "value": "PHASESpatializationModeAlwaysUseBinaural"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode~1alwaysUseBinaural/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatializationModeAlwaysUseBinaural"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode~1automatic/title",
          "value": "PHASESpatializationModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatializationModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode/title",
          "value": "PHASESpatializationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatializationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatializationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode~1alwaysUseChannelBased/title",
          "value": "PHASESpatializationModeAlwaysUseChannelBased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatializationMode~1alwaysUseChannelBased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatializationModeAlwaysUseChannelBased"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasespatializationmode/alwaysusechannelbased"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phasespatializationmode/alwaysusechannelbased"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
