{
  "abstract": [
    {
      "text": "The value for this key is an identifier of a registered ",
      "type": "text"
    },
    {
      "code": "NSValueTransformer",
      "type": "codeVoice"
    },
    {
      "text": " instance that is applied to the bound value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformerName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSValueTransformerNameBindingOption",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "valueTransformerName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSBindingOption",
        "text": "NSBindingOption"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSValueTransformerNameBindingOption"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "valueTransformerName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "valueTransformerName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSBindingOption",
              "text": "NSBindingOption"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingOption"
        }
      ],
      "role": "symbol",
      "title": "NSBindingOption",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsEditingMultipleValuesSelection": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the binding allows editing when the value represents a multiple selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsEditingMultipleValuesSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsEditingMultipleValuesSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAllowsEditingMultipleValuesSelectionBindingOption"
        }
      ],
      "role": "symbol",
      "title": "allowsEditingMultipleValuesSelection",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/allowseditingmultiplevaluesselection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsNullArgument": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the argument bindings allows passing argument values of ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsNullArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsNullArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAllowsNullArgumentBindingOption"
        }
      ],
      "role": "symbol",
      "title": "allowsNullArgument",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/allowsnullargument"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/alwaysPresentsApplicationModalAlerts": {
      "abstract": [
        {
          "text": "A number containing a Boolean value that determines if validation and error alert panels displayed as a result of this binding are displayed as application modal alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alwaysPresentsApplicationModalAlerts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/alwaysPresentsApplicationModalAlerts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAlwaysPresentsApplicationModalAlertsBindingOption"
        }
      ],
      "role": "symbol",
      "title": "alwaysPresentsApplicationModalAlerts",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/alwayspresentsapplicationmodalalerts"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEditable": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the editable state of the user interface item is automatically configured based on the controller’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conditionallySetsEditable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEditable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConditionallySetsEditableBindingOption"
        }
      ],
      "role": "symbol",
      "title": "conditionallySetsEditable",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/conditionallysetseditable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEnabled": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the enabled state of the user interface item is automatically configured based on the controller’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conditionallySetsEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConditionallySetsEnabledBindingOption"
        }
      ],
      "role": "symbol",
      "title": "conditionallySetsEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/conditionallysetsenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsHidden": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the hidden state of the user interface item is automatically configured based on the controller’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conditionallySetsHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConditionallySetsHiddenBindingOption"
        }
      ],
      "role": "symbol",
      "title": "conditionallySetsHidden",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/conditionallysetshidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/contentPlacementTag": {
      "abstract": [
        {
          "text": "A number that specifies the tag id of the popup menu item to replace with the content of the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentPlacementTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/contentPlacementTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSContentPlacementTagBindingOption"
        }
      ],
      "role": "symbol",
      "title": "contentPlacementTag",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/contentplacementtag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/continuouslyUpdatesValue": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines whether the value of the binding is updated as edits are made to the user interface item or is updated only when the user interface item resigns as the responder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuouslyUpdatesValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/continuouslyUpdatesValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSContinuouslyUpdatesValueBindingOption"
        }
      ],
      "role": "symbol",
      "title": "continuouslyUpdatesValue",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/continuouslyupdatesvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/createsSortDescriptor": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if a sort descriptor is created for a table column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createsSortDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/createsSortDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCreatesSortDescriptorBindingOption"
        }
      ],
      "role": "symbol",
      "title": "createsSortDescriptor",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/createssortdescriptor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/deletesObjectsOnRemove": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if an object is deleted from the managed context immediately upon being removed from a relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletesObjectsOnRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/deletesObjectsOnRemove",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeletesObjectsOnRemoveBindingsOption"
        }
      ],
      "role": "symbol",
      "title": "deletesObjectsOnRemove",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/deletesobjectsonremove"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayName": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object containing a human readable string to be displayed for a predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDisplayNameBindingOption"
        }
      ],
      "role": "symbol",
      "title": "displayName",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/displayname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayPattern": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies a format string used to construct the final value of a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayPattern"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDisplayPatternBindingOption"
        }
      ],
      "role": "symbol",
      "title": "displayPattern",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/displaypattern"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/handlesContentAsCompoundValue": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the content is treated as a compound value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handlesContentAsCompoundValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/handlesContentAsCompoundValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandlesContentAsCompoundValueBindingOption"
        }
      ],
      "role": "symbol",
      "title": "handlesContentAsCompoundValue",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/handlescontentascompoundvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/insertsNullPlaceholder": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if an additional item which represents ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " is inserted into a matrix or pop-up menu before the items in the content array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertsNullPlaceholder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/insertsNullPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInsertsNullPlaceholderBindingOption"
        }
      ],
      "role": "symbol",
      "title": "insertsNullPlaceholder",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/insertsnullplaceholder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/invokesSeparatelyWithArrayObjects": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines whether the specified selector is invoked with the array as the argument or is invoked repeatedly with each array item as an argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invokesSeparatelyWithArrayObjects"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/invokesSeparatelyWithArrayObjects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInvokesSeparatelyWithArrayObjectsBindingOption"
        }
      ],
      "role": "symbol",
      "title": "invokesSeparatelyWithArrayObjects",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/invokesseparatelywitharrayobjects"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformerName": {
      "abstract": [
        {
          "text": "The value for this key is an identifier of a registered ",
          "type": "text"
        },
        {
          "code": "NSValueTransformer",
          "type": "codeVoice"
        },
        {
          "text": " instance that is applied to the bound value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueTransformerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSValueTransformerNameBindingOption"
        }
      ],
      "role": "symbol",
      "title": "valueTransformerName",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/valuetransformername"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Binding-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsEditingMultipleValuesSelection",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsNullArgument",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/alwaysPresentsApplicationModalAlerts",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEditable",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsHidden",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/contentPlacementTag",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/continuouslyUpdatesValue",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/createsSortDescriptor",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/deletesObjectsOnRemove",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayName",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayPattern",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/handlesContentAsCompoundValue",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/insertsNullPlaceholder",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/invokesSeparatelyWithArrayObjects"
      ],
      "title": "Binding Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSValueTransformerNameBindingOption"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValueTransformerNameBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Binding-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsEditingMultipleValuesSelection",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsNullArgument",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/alwaysPresentsApplicationModalAlerts",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEditable",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsHidden",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/contentPlacementTag",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/continuouslyUpdatesValue",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/createsSortDescriptor",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/deletesObjectsOnRemove",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayName",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayPattern",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/handlesContentAsCompoundValue",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/insertsNullPlaceholder",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/invokesSeparatelyWithArrayObjects"
              ],
              "title": "Binding Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSBindingOption",
                    "text": "NSBindingOption"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSValueTransformerNameBindingOption"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsEnabled/title",
          "value": "NSConditionallySetsEnabledBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConditionallySetsEnabledBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1displayName/title",
          "value": "NSDisplayNameBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1displayName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisplayNameBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsHidden/title",
          "value": "NSConditionallySetsHiddenBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConditionallySetsHiddenBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1displayPattern/title",
          "value": "NSDisplayPatternBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1displayPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisplayPatternBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsEditable/title",
          "value": "NSConditionallySetsEditableBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsEditable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConditionallySetsEditableBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1invokesSeparatelyWithArrayObjects/title",
          "value": "NSInvokesSeparatelyWithArrayObjectsBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1invokesSeparatelyWithArrayObjects/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInvokesSeparatelyWithArrayObjectsBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1allowsEditingMultipleValuesSelection/title",
          "value": "NSAllowsEditingMultipleValuesSelectionBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1allowsEditingMultipleValuesSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAllowsEditingMultipleValuesSelectionBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1handlesContentAsCompoundValue/title",
          "value": "NSHandlesContentAsCompoundValueBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1handlesContentAsCompoundValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandlesContentAsCompoundValueBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1deletesObjectsOnRemove/title",
          "value": "NSDeletesObjectsOnRemoveBindingsOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1deletesObjectsOnRemove/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeletesObjectsOnRemoveBindingsOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1insertsNullPlaceholder/title",
          "value": "NSInsertsNullPlaceholderBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1insertsNullPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInsertsNullPlaceholderBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/title",
          "value": "NSBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1valueTransformerName/title",
          "value": "NSValueTransformerNameBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1valueTransformerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValueTransformerNameBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1contentPlacementTag/title",
          "value": "NSContentPlacementTagBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1contentPlacementTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSContentPlacementTagBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1createsSortDescriptor/title",
          "value": "NSCreatesSortDescriptorBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1createsSortDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCreatesSortDescriptorBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1continuouslyUpdatesValue/title",
          "value": "NSContinuouslyUpdatesValueBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1continuouslyUpdatesValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSContinuouslyUpdatesValueBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1alwaysPresentsApplicationModalAlerts/title",
          "value": "NSAlwaysPresentsApplicationModalAlertsBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1alwaysPresentsApplicationModalAlerts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlwaysPresentsApplicationModalAlertsBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1allowsNullArgument/title",
          "value": "NSAllowsNullArgumentBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1allowsNullArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAllowsNullArgumentBindingOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbindingoption/valuetransformername"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbindingoption/valuetransformername"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
