{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(affineTransform:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "simd",
    "externalID": "s:So13simd_float4x4a7SpatialE15affineTransformABSo19SPAffineTransform3Da_tcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "affineTransform"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SPAffineTransform3D",
        "text": "AffineTransform3D"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "renamed": "simd_float4x4.init(_:)",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(affineTransform:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "affineTransform"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@SPAffineTransform3D",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SPAffineTransform3D",
              "text": "AffineTransform3D"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_float4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init()": {
      "abstract": [
        {
          "text": "Creates a new matrix with uninitialized memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init()"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-3op4b": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SPAffineTransform3D",
          "text": "AffineTransform3D"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-3op4b",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(_:)-3op4b"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-4jrbw": {
      "abstract": [
        {
          "text": "Creates a new matrix from the specified SceneKit matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-4jrbw",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(_:)-4jrbw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-50sjs": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-50sjs",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(_:)-50sjs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-6pc85": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified scalar value on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-6pc85",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(_:)-6pc85"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-77vxr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SPPose3D",
          "text": "Pose3D"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-77vxr",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(_:)-77vxr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-7ig5g": {
      "abstract": [
        {
          "text": "Creates a new matrix from the specified quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-7ig5g",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(_:)-7ig5g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-9txnb": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SPProjectiveTransform3D",
          "text": "ProjectiveTransform3D"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-9txnb",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(_:)-9txnb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-q9z6": {
      "abstract": [
        {
          "text": "Creates a new matrix from the specified SceneKit matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-q9z6",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(_:)-q9z6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified vectors as columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(affineTransform:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "affineTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SPAffineTransform3D",
          "text": "AffineTransform3D"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(affineTransform:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(affineTransform:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(affinetransform:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(columns:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": "))"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(columns:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(columns:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(columns:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(diagonal:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified vector on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "diagonal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(diagonal:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(diagonal:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(diagonal:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(pose:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "pose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SPPose3D",
          "text": "Pose3D"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(pose:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(pose:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(pose:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(projectiveTransform:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "projectiveTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SPProjectiveTransform3D",
          "text": "ProjectiveTransform3D"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(projectiveTransform:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(projectiveTransform:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(projectivetransform:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(rows:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(rows:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rows:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4/init(rows:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@SA@SPAffineTransform3D": {
      "abstract": [
        {
          "text": "A 3D affine transformation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "AffineTransform3D"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@SPAffineTransform3D",
      "kind": "symbol",
      "role": "symbol",
      "title": "AffineTransform3D",
      "type": "topic",
      "url": "/documentation/spatial/affinetransform3d"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init()",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-6pc85",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(diagonal:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-50sjs",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-7ig5g",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-4jrbw",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-q9z6",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(columns:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(rows:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-3op4b",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-9txnb",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(_:)-77vxr",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(pose:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4/init(projectiveTransform:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x4/title",
          "value": "simd_float4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_float4x4/init(affinetransform:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
