{
  "abstract": [
    {
      "text": "The level for a modal panel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/modalPanel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSModalPanelWindowLevel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "modalPanel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSWindow",
        "text": "NSWindow"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSWindowLevel",
        "text": "Level"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSModalPanelWindowLevel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "modalPanel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "modalPanel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWindow",
              "text": "NSWindow"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSWindowLevel",
              "text": "Level"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct": {
      "abstract": [
        {
          "text": "The standard window levels in macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Level"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.Level",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/dock": {
      "abstract": [
        {
          "text": "The level for the dock.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/dock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDockWindowLevel"
        }
      ],
      "role": "symbol",
      "title": "dock",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct/dock"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/floating": {
      "abstract": [
        {
          "text": "Useful for floating palettes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/floating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFloatingWindowLevel"
        }
      ],
      "role": "symbol",
      "title": "floating",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct/floating"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/mainMenu": {
      "abstract": [
        {
          "text": "Reserved for the application’s main menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mainMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/mainMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMainMenuWindowLevel"
        }
      ],
      "role": "symbol",
      "title": "mainMenu",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct/mainmenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/modalPanel": {
      "abstract": [
        {
          "text": "The level for a modal panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modalPanel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/modalPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSModalPanelWindowLevel"
        }
      ],
      "role": "symbol",
      "title": "modalPanel",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct/modalpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/normal": {
      "abstract": [
        {
          "text": "The default level for ",
          "type": "text"
        },
        {
          "code": "NSWindow",
          "type": "codeVoice"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNormalWindowLevel"
        }
      ],
      "role": "symbol",
      "title": "normal",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct/normal"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/popUpMenu": {
      "abstract": [
        {
          "text": "The level for a pop-up menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popUpMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/popUpMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPopUpMenuWindowLevel"
        }
      ],
      "role": "symbol",
      "title": "popUpMenu",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct/popupmenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/screenSaver": {
      "abstract": [
        {
          "text": "The level for a screen saver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenSaver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/screenSaver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScreenSaverWindowLevel"
        }
      ],
      "role": "symbol",
      "title": "screenSaver",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct/screensaver"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/statusBar": {
      "abstract": [
        {
          "text": "The level for a status window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/statusBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStatusWindowLevel"
        }
      ],
      "role": "symbol",
      "title": "statusBar",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct/statusbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/submenu": {
      "abstract": [
        {
          "text": "Reserved for submenus. Synonymous with ",
          "type": "text"
        },
        {
          "code": "NSTornOffMenuWindowLevel",
          "type": "codeVoice"
        },
        {
          "text": ", which is preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "submenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/submenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSubmenuWindowLevel"
        }
      ],
      "role": "symbol",
      "title": "submenu",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct/submenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/tornOffMenu": {
      "abstract": [
        {
          "text": "The level for a torn-off menu. Synonymous with ",
          "type": "text"
        },
        {
          "code": "NSSubmenuWindowLevel",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tornOffMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/tornOffMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTornOffMenuWindowLevel"
        }
      ],
      "role": "symbol",
      "title": "tornOffMenu",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/level-swift.struct/tornoffmenu"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/dock",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/floating",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/mainMenu",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/normal",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/popUpMenu",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/screenSaver",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/statusBar",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/submenu",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/tornOffMenu"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSModalPanelWindowLevel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSModalPanelWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/dock",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/floating",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/mainMenu",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/normal",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/popUpMenu",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/screenSaver",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/statusBar",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/submenu",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct/tornOffMenu"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Level-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSWindowLevel",
                    "text": "NSWindowLevel"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSModalPanelWindowLevel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1screenSaver/title",
          "value": "NSScreenSaverWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1screenSaver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScreenSaverWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1mainMenu/title",
          "value": "NSMainMenuWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1mainMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMainMenuWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1modalPanel/title",
          "value": "NSModalPanelWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1modalPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSModalPanelWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1tornOffMenu/title",
          "value": "NSTornOffMenuWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1tornOffMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTornOffMenuWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1dock/title",
          "value": "NSDockWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1dock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDockWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1statusBar/title",
          "value": "NSStatusWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1statusBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct/title",
          "value": "NSWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1floating/title",
          "value": "NSFloatingWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1floating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFloatingWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1normal/title",
          "value": "NSNormalWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNormalWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1popUpMenu/title",
          "value": "NSPopUpMenuWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1popUpMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopUpMenuWindowLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1submenu/title",
          "value": "NSSubmenuWindowLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Level-swift.struct~1submenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSubmenuWindowLevel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindow/level-swift.struct/modalpanel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindow/level-swift.struct/modalpanel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
