{
  "abstract": [
    {
      "text": "Tells the delegate that the session has finished activating.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/session(_:activationDidCompleteWith:error:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)WCSessionDelegate(im)session:activationDidCompleteWithState:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "session"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)WCSession",
        "text": "WCSession"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "activationDidCompleteWith"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@WCSessionActivationState",
        "text": "WCSessionActivationState"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "error"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?)"
      }
    ],
    "modules": [
      {
        "name": "Watch Connectivity"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "session:activationDidCompleteWithState:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "session(_:activationDidCompleteWith:error:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "session"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WCSession",
              "text": "WCSession"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "activationDidCompleteWith"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "activationState"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@WCSessionActivationState",
              "text": "WCSessionActivationState"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The session object whose activation completed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The state of the session. Sessions normally move to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/activated",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " state upon success or the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/notActivated",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " state when there is an error. On iOS, the session may also move to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/inactive",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " state if there is data waiting to be delivered from a previous session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "activationState"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An error object indicating that a problem occurred or ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " if activation completed successfully. When the ",
                  "type": "text"
                },
                {
                  "code": "activationState",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter contains the value ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/notActivated",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", this parameter contains the error object describing the reason for the failure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You must implement this method to support asynchronous activation and quick watch switching. Your implementation should check the value of the ",
              "type": "text"
            },
            {
              "code": "activationState",
              "type": "codeVoice"
            },
            {
              "text": " parameter to see if communication with the counterpart app is possible. When the state is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/activated",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you may communicate normally with the other app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity": {
      "abstract": [
        {
          "text": "Implement two-way communication between an iOS app and its paired watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Watch Connectivity",
      "type": "topic",
      "url": "/documentation/watchconnectivity"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession": {
      "abstract": [
        {
          "text": "The object that initiates communication between a WatchKit extension and its companion iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCSession"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSession"
        }
      ],
      "role": "symbol",
      "title": "WCSession",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState": {
      "abstract": [
        {
          "text": "Constants indicating the activation state of a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCSessionActivationState"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSessionActivationState"
        }
      ],
      "role": "symbol",
      "title": "WCSessionActivationState",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessionactivationstate"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/activated": {
      "abstract": [
        {
          "text": "The session is active and the Watch app and iOS app may communicate with each other freely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activated"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/activated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSessionActivationStateActivated"
        }
      ],
      "role": "symbol",
      "title": "WCSessionActivationState.activated",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessionactivationstate/activated"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/inactive": {
      "abstract": [
        {
          "text": "The session was active but is transitioning to the deactivated state. The session’s delegate object may still receive data while in this state, but it is a programmer error to try to send data to the counterpart app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inactive"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/inactive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSessionActivationStateInactive"
        }
      ],
      "role": "symbol",
      "title": "WCSessionActivationState.inactive",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessionactivationstate/inactive"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/notActivated": {
      "abstract": [
        {
          "text": "The session is not activated. When in this state, no communication occurs between the Watch app and iOS app. It is a programmer error to try to send data to the counterpart app while in this state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notActivated"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/notActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSessionActivationStateNotActivated"
        }
      ],
      "role": "symbol",
      "title": "WCSessionActivationState.notActivated",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessionactivationstate/notactivated"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol that defines methods for receiving messages sent by a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSessionDelegate"
        }
      ],
      "role": "symbol",
      "title": "WCSessionDelegate",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessiondelegate"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/session(_:activationDidCompleteWith:error:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the session has finished activating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WCSession",
          "text": "WCSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "activationDidCompleteWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCSessionActivationState",
          "text": "WCSessionActivationState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/session(_:activationDidCompleteWith:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:activationDidCompleteWithState:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "session(_:activationDidCompleteWith:error:)",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessiondelegate/session(_:activationdidcompletewith:error:)"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/sessionDidBecomeInactive(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the session will stop communicating with the current Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionDidBecomeInactive"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WCSession",
          "text": "WCSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/sessionDidBecomeInactive(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sessionDidBecomeInactive:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sessionDidBecomeInactive(_:)",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessiondelegate/sessiondidbecomeinactive(_:)"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/sessionDidDeactivate(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the session has delivered all the data from the previous session, and that communication with the Apple Watch has ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionDidDeactivate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WCSession",
          "text": "WCSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/sessionDidDeactivate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sessionDidDeactivate:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sessionDidDeactivate(_:)",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessiondelegate/sessiondiddeactivate(_:)"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Session-Activation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/sessionDidBecomeInactive(_:)",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/sessionDidDeactivate(_:)"
      ],
      "title": "Managing Session Activation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "session:activationDidCompleteWithState:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:activationDidCompleteWithState:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Session-Activation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/sessionDidBecomeInactive(_:)",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/sessionDidDeactivate(_:)"
              ],
              "title": "Managing Session Activation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "session:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WCSession",
                    "text": "WCSession"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "session"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "activationDidCompleteWithState:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@WCSessionActivationState",
                    "text": "WCSessionActivationState"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "activationState"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The session object whose activation completed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "session"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The state of the session. Sessions normally move to the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/activated",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " state upon success or the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/notActivated",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " state when there is an error. On iOS, the session may also move to the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/inactive",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " state if there is data waiting to be delivered from a previous session.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "activationState"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An error object indicating that a problem occurred or ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if activation completed successfully. When the ",
                        "type": "text"
                      },
                      {
                        "code": "activationState",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter contains the value ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState/notActivated",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", this parameter contains the error object describing the reason for the failure.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate/title",
          "value": "WCSessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/title",
          "value": "WCSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState/title",
          "value": "WCSessionActivationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate~1sessionDidDeactivate(_:)/title",
          "value": "sessionDidDeactivate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate~1sessionDidDeactivate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sessionDidDeactivate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState~1activated/title",
          "value": "WCSessionActivationStateActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState~1activated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionActivationStateActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate~1session(_:activationDidCompleteWith:error:)/title",
          "value": "session:activationDidCompleteWithState:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate~1session(_:activationDidCompleteWith:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:activationDidCompleteWithState:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate~1sessionDidBecomeInactive(_:)/title",
          "value": "sessionDidBecomeInactive:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate~1sessionDidBecomeInactive(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sessionDidBecomeInactive:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState~1inactive/title",
          "value": "WCSessionActivationStateInactive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState~1inactive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionActivationStateInactive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState~1notActivated/title",
          "value": "WCSessionActivationStateNotActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState~1notActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionActivationStateNotActivated"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchconnectivity/wcsessiondelegate/session(_:activationdidcompletewith:error:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchconnectivity/wcsessiondelegate/session(_:activationdidcompletewith:error:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
