{
  "abstract": [
    {
      "text": "Tells the delegate that a data transfer operation has finished successfully or ended because of an error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/session(_:didFinish:error:)-8627b"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)WCSessionDelegate(im)session:didFinishUserInfoTransfer:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "session"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)WCSession",
        "text": "WCSession"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didFinish"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)WCSessionUserInfoTransfer",
        "text": "WCSessionUserInfoTransfer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "error"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?)"
      }
    ],
    "modules": [
      {
        "name": "Watch Connectivity"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "session:didFinishUserInfoTransfer:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "session(_:didFinish:error:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "session"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WCSession",
              "text": "WCSession"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didFinish"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "userInfoTransfer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionUserInfoTransfer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WCSessionUserInfoTransfer",
              "text": "WCSessionUserInfoTransfer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The session object of the current process.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object containing information about the data that was transferred.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "userInfoTransfer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An error object if a problem occurred.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The session object calls this method when a data transfer initiated by the current app finished, either successfully or unsuccessfully. Use this method to note that the transfer completed or to respond to errors, perhaps by trying to send the data again at a later time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called on a background thread of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity": {
      "abstract": [
        {
          "text": "Implement two-way communication between an iOS app and its paired watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Watch Connectivity",
      "type": "topic",
      "url": "/documentation/watchconnectivity"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession": {
      "abstract": [
        {
          "text": "The object that initiates communication between a WatchKit extension and its companion iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCSession"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSession"
        }
      ],
      "role": "symbol",
      "title": "WCSession",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsession"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol that defines methods for receiving messages sent by a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSessionDelegate"
        }
      ],
      "role": "symbol",
      "title": "WCSessionDelegate",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessiondelegate"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/session(_:didFinish:error:)-8627b": {
      "abstract": [
        {
          "text": "Tells the delegate that a data transfer operation has finished successfully or ended because of an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WCSession",
          "text": "WCSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinish"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WCSessionUserInfoTransfer",
          "text": "WCSessionUserInfoTransfer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/session(_:didFinish:error:)-8627b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didFinishUserInfoTransfer:error:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didFinish:error:)",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessiondelegate/session(_:didfinish:error:)-8627b"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/session(_:didReceiveUserInfo:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the session successfully received a data directory from its counterpart.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WCSession",
          "text": "WCSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveUserInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/session(_:didReceiveUserInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didReceiveUserInfo:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didReceiveUserInfo:)",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessiondelegate/session(_:didreceiveuserinfo:)"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionUserInfoTransfer": {
      "abstract": [
        {
          "text": "Information about in-progress data transfers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCSessionUserInfoTransfer"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionUserInfoTransfer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSessionUserInfoTransfer"
        }
      ],
      "role": "symbol",
      "title": "WCSessionUserInfoTransfer",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessionuserinfotransfer"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Data-Dictionary-Transfers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/session(_:didReceiveUserInfo:)"
      ],
      "title": "Managing Data Dictionary Transfers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "session:didFinishUserInfoTransfer:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didFinishUserInfoTransfer:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Data-Dictionary-Transfers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionDelegate/session(_:didReceiveUserInfo:)"
              ],
              "title": "Managing Data Dictionary Transfers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "session:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSession",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WCSession",
                    "text": "WCSession"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "session"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didFinishUserInfoTransfer:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionUserInfoTransfer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WCSessionUserInfoTransfer",
                    "text": "WCSessionUserInfoTransfer"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "userInfoTransfer"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The session object of the current process.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "session"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An object containing information about the data that was transferred.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "userInfoTransfer"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An error object if a problem occurred.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate~1session(_:didReceiveUserInfo:)/title",
          "value": "session:didReceiveUserInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate~1session(_:didReceiveUserInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didReceiveUserInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionUserInfoTransfer/title",
          "value": "WCSessionUserInfoTransfer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionUserInfoTransfer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionUserInfoTransfer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionUserInfoTransfer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionUserInfoTransfer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/title",
          "value": "WCSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate~1session(_:didFinish:error:)-8627b/title",
          "value": "session:didFinishUserInfoTransfer:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate~1session(_:didFinish:error:)-8627b/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didFinishUserInfoTransfer:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate/title",
          "value": "WCSessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchconnectivity/wcsessiondelegate/session(_:didfinish:error:)-8627b"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchconnectivity/wcsessiondelegate/session(_:didfinish:error:)-8627b"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
