{
  "abstract": [
    {
      "text": "An object that contains common types of data that the data detection system matches for a pasteboard.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DetectedValues"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DetectedValues"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIPasteboard.DetectedValues"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DetectedValues"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard": {
      "abstract": [
        {
          "text": "An object that helps a user share data from one place to another within your app, and from your app to other apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteboard"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboard"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues": {
      "abstract": [
        {
          "text": "An object that contains common types of data that the data detection system matches for a pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DetectedValues"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DetectedValues"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard.DetectedValues",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/calendarEvents": {
      "abstract": [
        {
          "text": "An array of calendar events that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarEvents"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchCalendarEvent",
          "text": "DDMatchCalendarEvent"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/calendarEvents",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarEvents",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/calendarevents"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/emailAddresses": {
      "abstract": [
        {
          "text": "An array of email addresses that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emailAddresses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchEmailAddress",
          "text": "DDMatchEmailAddress"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/emailAddresses",
      "kind": "symbol",
      "role": "symbol",
      "title": "emailAddresses",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/emailaddresses"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/flightNumbers": {
      "abstract": [
        {
          "text": "An array of flight numbers that the system data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flightNumbers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchFlightNumber",
          "text": "DDMatchFlightNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/flightNumbers",
      "kind": "symbol",
      "role": "symbol",
      "title": "flightNumbers",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/flightnumbers"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/links": {
      "abstract": [
        {
          "text": "An array of web links that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "links"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchLink",
          "text": "DDMatchLink"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/links",
      "kind": "symbol",
      "role": "symbol",
      "title": "links",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/links"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/moneyAmounts": {
      "abstract": [
        {
          "text": "An array of money amounts and currencies that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moneyAmounts"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchMoneyAmount",
          "text": "DDMatchMoneyAmount"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/moneyAmounts",
      "kind": "symbol",
      "role": "symbol",
      "title": "moneyAmounts",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/moneyamounts"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/number": {
      "abstract": [
        {
          "text": "A number that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "number"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/number",
      "kind": "symbol",
      "role": "symbol",
      "title": "number",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/number"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/patterns": {
      "abstract": [
        {
          "text": "A set of key paths that represent patterns that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patterns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/patterns",
      "kind": "symbol",
      "role": "symbol",
      "title": "patterns",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/patterns"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/phoneNumbers": {
      "abstract": [
        {
          "text": "An array of phone numbers that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneNumbers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchPhoneNumber",
          "text": "DDMatchPhoneNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/phoneNumbers",
      "kind": "symbol",
      "role": "symbol",
      "title": "phoneNumbers",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/phonenumbers"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/postalAddresses": {
      "abstract": [
        {
          "text": "An array of postal addresses that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalAddresses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchPostalAddress",
          "text": "DDMatchPostalAddress"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/postalAddresses",
      "kind": "symbol",
      "role": "symbol",
      "title": "postalAddresses",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/postaladdresses"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/probableWebSearch": {
      "abstract": [
        {
          "text": "A string that the data detection system identifies as a probable web search item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "probableWebSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/probableWebSearch",
      "kind": "symbol",
      "role": "symbol",
      "title": "probableWebSearch",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/probablewebsearch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/probableWebURL": {
      "abstract": [
        {
          "text": "A string that the data detection system identifies as a probable web URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "probableWebURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/probableWebURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "probableWebURL",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/probableweburl"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/shipmentTrackingNumbers": {
      "abstract": [
        {
          "text": "An array of parcel tracking numbers that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shipmentTrackingNumbers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchShipmentTrackingNumber",
          "text": "DDMatchShipmentTrackingNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/shipmentTrackingNumbers",
      "kind": "symbol",
      "role": "symbol",
      "title": "shipmentTrackingNumbers",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/shipmenttrackingnumbers"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern": {
      "abstract": [
        {
          "text": "An object that represents a pattern to detect for the pasteboard, such as a URL, text, or a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DetectionPattern"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DetectionPattern"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard.DetectionPattern",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectionpattern"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:completionHandler:)-23vwn": {
      "abstract": [
        {
          "text": "Requests that the data detection system identify the patterns that you specify for the pasteboard, and provide the patterns that it matches to your closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectPatterns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>, any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> ())"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:completionHandler:)-23vwn",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectPatterns(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectpatterns(for:completionhandler:)-23vwn"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:inItemSet:completionHandler:)-7ubl1": {
      "abstract": [
        {
          "text": "Requests that the data detection system identify the patterns that you specify for the pasteboard items, and provide the patterns that it matches to your closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectPatterns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "externalParam",
          "text": "inItemSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>], any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> ())"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:inItemSet:completionHandler:)-7ubl1",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectPatterns(for:inItemSet:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectpatterns(for:initemset:completionhandler:)-7ubl1"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:completionHandler:)-6adre": {
      "abstract": [
        {
          "text": "Requests that the data detection system identify the types of data that you specify for the pasteboard, and provide the values that it matches to your closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> ())"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:completionHandler:)-6adre",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectValues(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectvalues(for:completionhandler:)-6adre"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:inItemSet:completionHandler:)-pm9l": {
      "abstract": [
        {
          "text": "Requests that the data detection system identify the types of data that you specify for the pasteboard items, and provide the values that it matches to your closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "externalParam",
          "text": "inItemSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": "], any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> ())"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:inItemSet:completionHandler:)-pm9l",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectValues(for:inItemSet:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectvalues(for:initemset:completionhandler:)-pm9l"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedPatterns(for:)": {
      "abstract": [
        {
          "text": "Requests that the data detection system asynchronously identify the patterns that you specify for the pasteboard, and return the patterns that it matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectedPatterns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedPatterns(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectedPatterns(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedpatterns(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedPatterns(for:inItemSet:)": {
      "abstract": [
        {
          "text": "Requests that the data detection system asynchronously identify the patterns that you specify for the pasteboard items, and return the patterns that it matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectedPatterns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "externalParam",
          "text": "inItemSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedPatterns(for:inItemSet:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectedPatterns(for:inItemSet:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedpatterns(for:initemset:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedValues(for:)": {
      "abstract": [
        {
          "text": "Requests that the data detection system asynchronously identify the types of values that you specify for the pasteboard, and return the values that it matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectedValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedValues(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectedValues(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedValues(for:inItemSet:)": {
      "abstract": [
        {
          "text": "Requests that the data detection system asynchronously identify the types of values that you specify for the pasteboard item, and return the values that it matches for each pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectedValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "externalParam",
          "text": "inItemSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12UIPasteboardC5UIKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedValues(for:inItemSet:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectedValues(for:inItemSet:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues(for:initemset:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Detecting-patterns-of-content-in-pasteboard-items",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:completionHandler:)-23vwn",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedPatterns(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:inItemSet:completionHandler:)-7ubl1",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedPatterns(for:inItemSet:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:completionHandler:)-6adre",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedValues(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:inItemSet:completionHandler:)-pm9l",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectedValues(for:inItemSet:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern"
      ],
      "title": "Detecting patterns of content in pasteboard items"
    }
  ],
  "topicSections": [
    {
      "anchor": "Detected-patterns",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/patterns",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/probableWebSearch",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/probableWebURL"
      ],
      "title": "Detected patterns"
    },
    {
      "anchor": "Detected-values",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/calendarEvents",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/emailAddresses",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/flightNumbers",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/links",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/moneyAmounts",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/number",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/phoneNumbers",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/postalAddresses",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/shipmentTrackingNumbers"
      ],
      "title": "Detected values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern/title",
          "value": "UIPasteboardDetectionPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardDetectionPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardDetectionPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/title",
          "value": "UIPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboard"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipasteboard/detectedvalues"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
