{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/verticalSizeClass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIMutableTraits(py)verticalSizeClass",
    "fragments": [
      {
        "kind": "identifier",
        "text": "verticalSizeClass"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "verticalSizeClass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "verticalSizeClass"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceSizeClass",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIUserInterfaceSizeClass",
              "text": "UIUserInterfaceSizeClass"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "verticalSizeClass"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIMutableTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIMutableTraits",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/accessibilityContrast": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityContrast"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/accessibilityContrast",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityContrast",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/accessibilitycontrast"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/activeAppearance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "activeAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/activeAppearance",
      "kind": "symbol",
      "role": "symbol",
      "title": "activeAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/activeappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayGamut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "displayGamut"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayGamut",
      "kind": "symbol",
      "role": "symbol",
      "title": "displayGamut",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/displaygamut"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayScale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "displayScale"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayScale",
      "kind": "symbol",
      "role": "symbol",
      "title": "displayScale",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/displayscale"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/forceTouchCapability": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "forceTouchCapability"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/forceTouchCapability",
      "kind": "symbol",
      "role": "symbol",
      "title": "forceTouchCapability",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/forcetouchcapability"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/horizontalSizeClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "horizontalSizeClass"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/horizontalSizeClass",
      "kind": "symbol",
      "role": "symbol",
      "title": "horizontalSizeClass",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/horizontalsizeclass"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/imageDynamicRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imageDynamicRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/imageDynamicRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageDynamicRange",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/imagedynamicrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/layoutDirection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "layoutDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/layoutDirection",
      "kind": "symbol",
      "role": "symbol",
      "title": "layoutDirection",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/layoutdirection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/verticalSizeClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "verticalSizeClass"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/verticalSizeClass",
      "kind": "symbol",
      "role": "symbol",
      "title": "verticalSizeClass",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/verticalsizeclass"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitAccessibilityContrast"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitAccessibilityContrast",
      "type": "topic",
      "url": "/documentation/uikit/uitraitaccessibilitycontrast-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitActiveAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitActiveAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uitraitactiveappearance-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitDisplayGamut"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitDisplayGamut",
      "type": "topic",
      "url": "/documentation/uikit/uitraitdisplaygamut-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitDisplayScale"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitDisplayScale",
      "type": "topic",
      "url": "/documentation/uikit/uitraitdisplayscale-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitForceTouchCapability"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitForceTouchCapability",
      "type": "topic",
      "url": "/documentation/uikit/uitraitforcetouchcapability-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitHorizontalSizeClass"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitHorizontalSizeClass",
      "type": "topic",
      "url": "/documentation/uikit/uitraithorizontalsizeclass-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitImageDynamicRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitImageDynamicRange",
      "type": "topic",
      "url": "/documentation/uikit/uitraitimagedynamicrange-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceSizeClass": {
      "abstract": [
        {
          "text": "Constants that indicate the size class of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserInterfaceSizeClass"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceSizeClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceSizeClass"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceSizeClass",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacesizeclass"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defining-custom-traits",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/accessibilityContrast",
        "doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/activeAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayGamut",
        "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayScale",
        "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/forceTouchCapability",
        "doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/horizontalSizeClass",
        "doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/imageDynamicRange",
        "doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/layoutDirection"
      ],
      "title": "Defining custom traits"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceSizeClass/title",
          "value": "UIUserInterfaceSizeClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceSizeClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceSizeClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceSizeClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceSizeClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uimutabletraits-8l00o/verticalsizeclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
