{
  "abstract": [
    {
      "text": "Configures the instance of a view for Unified Payments Interface (UPI) device validation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messageui/documentation/MessageUI",
        "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController/setUPIVerificationCodeSendCompletion:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MFMessageComposeViewController(im)setUPIVerificationCodeSendCompletion:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "setUPIVerificationCodeSendCompletion:"
      }
    ],
    "modules": [
      {
        "name": "Message UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setUPIVerificationCodeSendCompletion:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setUPIVerificationCodeSendCompletion:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setUPIVerificationCodeSendCompletion:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "didSend"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block that’s invoked with a ",
                  "type": "text"
                },
                {
                  "code": "BOOL",
                  "type": "codeVoice"
                },
                {
                  "text": " to determine whether the message was sent. The send completion handler is invoked with ",
                  "type": "text"
                },
                {
                  "code": "YES",
                  "type": "codeVoice"
                },
                {
                  "text": " after the SMS successfully transmitted to the sender’s cellular carrier. If the SMS failed to send, the completion handler invoked with ",
                  "type": "text"
                },
                {
                  "code": "NO",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completion"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.upi-device-validation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " managed entitlement, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController/setUPIVerificationCodeSendCompletion:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " configures the instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with non-editable recipients and body fields.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController/setUPIVerificationCodeSendCompletion:",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method is only functional on devices with SMS capability and is only compatible with recipients that don’t use iMessage.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The system invokes the completion handler on the main thread. It only invokes the completion handler after the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewControllerDelegate/messageComposeViewController(_:didFinishWith:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method gets called if a person sends the transaction.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system calls the send completion handler with the transmission result of the message. The system won’t call the completion handler if:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The device doesn’t have SMS capability.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your app doesn’t have the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.upi-device-validation",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " entitlement.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The recipient can use iMessage or the person cancels the transaction.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following code snippet is an example of how you can create an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", configure it with a UPI verification phone number and generated token, and set a completion block indicating the use of the controller for UPI device enrollment:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "extension ViewController {",
            "    func presentMessageComposer() {",
            "        let composeController = MFMessageComposeViewController()",
            "        composeController.messageComposeDelegate = self",
            "        composeController.recipients = [\"+14081234567\"]",
            "        composeController.body = \"SomeDeviceVerificationCode123\"",
            "        composeController.setUPIVerificationCodeSendCompletion { result in",
            "            NSLog(\"UPI send callback - message sent: \\(result)\")",
            "        }",
            "        ",
            "        present(composeController, animated: true)",
            "    }"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The following code snippet is the same as the one above, but in Objective-C:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@implementation ViewController (MessageComposer)",
            "",
            "- (void)presentMessageComposer {",
            "    MFMessageComposeViewController *composeController = [[MFMessageComposeViewController alloc] init];",
            "    composeController.messageComposeDelegate = self;",
            "    composeController.recipients = @[@\"+14081234567\"];",
            "    composeController.body = @\"SomeDeviceVerificationCode123\";",
            "    [composeController setUPIVerificationCodeSendCompletion:^(BOOL result) {",
            "        NSLog(@\"UPI send callback - message sent: %@\", result ? @\"YES\" : @\"NO\");",
            "    }];",
            "}",
            "",
            "@end"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In addition, you need to use the existing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewControllerDelegate/messageComposeViewController(_:didFinishWith:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " delegate method to dismiss the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance because sending may take several seconds to complete. You can choose to allow people to continue interacting with your app or display a waiting UI. The following code snippet is an example of using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewControllerDelegate/messageComposeViewController(_:didFinishWith:)",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "extension ViewController: MFMessageComposeViewControllerDelegate {",
            "    func messageComposeViewController(_ controller: MFMessageComposeViewController, didFinishWith result: MessageComposeResult) {",
            "        NSLog(\"messageComposeViewController didFinishWithResult \\(result)\")",
            "        controller.dismiss(animated: true)",
            "    }",
            "}",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.upi-device-validation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can use Unified Payments Interface (UPI) device enrollment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.upi-device-validation",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.upi-device-validation",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.upi-device-validation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messageui/documentation/MessageUI": {
      "abstract": [
        {
          "text": "Create a user interface for composing email and text messages, so users can edit and send messages without leaving your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Message UI",
      "type": "topic",
      "url": "/documentation/messageui"
    },
    "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController": {
      "abstract": [
        {
          "text": "A standard view controller whose interface lets the user compose and send SMS or MMS messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MFMessageComposeViewController"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MFMessageComposeViewController"
        }
      ],
      "role": "symbol",
      "title": "MFMessageComposeViewController",
      "type": "topic",
      "url": "/documentation/messageui/mfmessagecomposeviewcontroller"
    },
    "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController/setUPIVerificationCodeSendCompletion:": {
      "abstract": [
        {
          "text": "Configures the instance of a view for Unified Payments Interface (UPI) device validation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setUPIVerificationCodeSendCompletion:"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController/setUPIVerificationCodeSendCompletion:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setUPIVerificationCodeSendCompletion:"
        }
      ],
      "role": "symbol",
      "title": "setUPIVerificationCodeSendCompletion:",
      "type": "topic",
      "url": "/documentation/messageui/mfmessagecomposeviewcontroller/setupiverificationcodesendcompletion:"
    },
    "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewControllerDelegate/messageComposeViewController(_:didFinishWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user finished composing the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageComposeViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MFMessageComposeViewController",
          "text": "MFMessageComposeViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MessageComposeResult",
          "text": "MessageComposeResult"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewControllerDelegate/messageComposeViewController(_:didFinishWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "messageComposeViewController:didFinishWithResult:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "messageComposeViewController(_:didFinishWith:)",
      "type": "topic",
      "url": "/documentation/messageui/mfmessagecomposeviewcontrollerdelegate/messagecomposeviewcontroller(_:didfinishwith:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewController/title",
          "value": "MFMessageComposeViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMessageComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMessageComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewControllerDelegate~1messageComposeViewController(_:didFinishWith:)/title",
          "value": "messageComposeViewController:didFinishWithResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewControllerDelegate~1messageComposeViewController(_:didFinishWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "messageComposeViewController:didFinishWithResult:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messageui/mfmessagecomposeviewcontroller/setupiverificationcodesendcompletion:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
