{
  "abstract": [
    {
      "text": "Convert your existing extension to a Safari web extension using Xcode’s command-line tool.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/converting-a-web-extension-for-safari"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Converting a web extension for Safari"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you create a web extension that works in a browser other than Safari, you can deploy it in Safari by using the Safari web extension converter. The converter:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Creates an Xcode project",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configures the Xcode project with a macOS app or iOS app that installs the extension in Safari",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configures a Safari web extension with your extension files in the Xcode project",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Run-the-converter",
          "level": 3,
          "text": "Run the converter",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To run the converter, open the Terminal app and run the ",
              "type": "text"
            },
            {
              "code": "xcrun",
              "type": "codeVoice"
            },
            {
              "text": " command with the ",
              "type": "text"
            },
            {
              "code": "safari-web-extension-converter",
              "type": "codeVoice"
            },
            {
              "text": " option, providing the path for your existing extension files.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "xcrun safari-web-extension-converter /path/to/extension"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If the converter needs more information, it asks you interactively, or you can provide the following command-line options:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Save the generated app and Xcode project to the file path.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--project-location",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Rebuild the existing Safari web extension Xcode project at the file path with different options or platforms. Use this option to add iOS to your existing macOS project.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--rebuild-project",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Use the value to name the generated app and the Xcode project.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--app-name",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Use the value as the bundle identifier for the generated app. This identifier is unique to your app in your developer account. A reverse-DNS-style identifier is recommended (for example, ",
                        "type": "text"
                      },
                      {
                        "code": "com.company.extensionName",
                        "type": "codeVoice"
                      },
                      {
                        "text": ").",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--bundle-identifier",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Use Swift in the generated app.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--swift",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Use Objective-C in the generated app.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--objc",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Create an iOS-only project.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--ios-only",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Create a macOS-only project.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--macos-only",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Copy the extension files into the generated project. If you don’t specify this parameter, the project references the original extension files.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--copy-resources",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Don’t open the generated Xcode project when complete.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--no-open",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Don’t show the confirmation prompt.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--no-prompt",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Overwrite the output directory, if one exists.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--force",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Print the help text.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "--help",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "By default, the converter creates a reference in the Xcode project to the resources in the path you provide. As a result, changes you make to the original extension update your converted Safari web extension and vice versa. If you prefer to keep your original and converted extensions separate, use the ",
                  "type": "text"
                },
                {
                  "code": "--copy-resources",
                  "type": "codeVoice"
                },
                {
                  "text": " option to make a copy of the original files.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "New Xcode projects require you to select either the Swift or Objective-C language for native development. For your Safari web extension, you may not need to make any native customizations at all because your extension uses the JavaScript, HTML, and CSS you provide. If you are unsure of which language to use, select Swift.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the converter runs interactively, it asks you to confirm your selections and gives you the opportunity to update them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Review-the-manifest-warnings",
          "level": 3,
          "text": "Review the manifest warnings",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The converter generates and opens your new Xcode project. The converter reports any manifest keys that the current version of Safari doesn’t support.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Warning: The following keys in your manifest.json are not supported by your ",
            "current version of Safari. If these are critical to your extension, you ",
            "should review your code to see if you need to make changes to support Safari:",
            "downloads",
            "offline_enabled",
            ""
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Review any reported exceptions, and see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.safariservices/documentation/SafariServices/assessing-your-safari-web-extension-s-browser-compatibility",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for details on how to resolve them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Build-and-run-your-converted-Safari-web-extension",
          "level": 3,
          "text": "Build and run your converted Safari web extension",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To see your converted extension in Safari, follow the instructions in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.safariservices/documentation/SafariServices/running-your-safari-web-extension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-iOS-to-your-existing-Xcode-project",
          "level": 3,
          "text": "Add iOS to your existing Xcode project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you have an existing Xcode project with a macOS Safari web extension, and you want to add support for iOS to it, use the converter with the ",
              "type": "text"
            },
            {
              "code": "--rebuild-project",
              "type": "codeVoice"
            },
            {
              "text": " option.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "xcrun safari-web-extension-converter --rebuild-project /path/to/myExtension/myExtension.xcodeproj"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Provide the path to your current extension’s Xcode project file (including the ",
              "type": "text"
            },
            {
              "code": "xcodeproj",
              "type": "codeVoice"
            },
            {
              "text": " file extension). The converter creates a new Xcode project with both macOS and iOS extensions from your existing project, and prints manifest warnings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/assessing-your-safari-web-extension-s-browser-compatibility": {
      "abstract": [
        {
          "text": "Review your Safari web extension implementation plan, manifest keys, and JavaScript API usage for compatibility with other browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/assessing-your-safari-web-extension-s-browser-compatibility",
      "kind": "article",
      "role": "article",
      "title": "Assessing your Safari web extension’s browser compatibility",
      "type": "topic",
      "url": "/documentation/safariservices/assessing-your-safari-web-extension-s-browser-compatibility"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/converting-a-safari-app-extension-to-a-safari-web-extension": {
      "abstract": [
        {
          "text": "Unify your web extensions and simplify development by sharing code with a Safari web extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/converting-a-safari-app-extension-to-a-safari-web-extension",
      "kind": "article",
      "role": "article",
      "title": "Converting a Safari app extension to a Safari web extension",
      "type": "topic",
      "url": "/documentation/safariservices/converting-a-safari-app-extension-to-a-safari-web-extension"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/running-your-safari-web-extension": {
      "abstract": [
        {
          "text": "Install and update your extension in Safari as you make changes in development.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/running-your-safari-web-extension",
      "kind": "article",
      "role": "article",
      "title": "Running your Safari web extension",
      "type": "topic",
      "url": "/documentation/safariservices/running-your-safari-web-extension"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions": {
      "abstract": [
        {
          "text": "Create web extensions that work in Safari and other browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Safari web extensions",
      "type": "topic",
      "url": "/documentation/safariservices/safari-web-extensions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Extension-conversions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/converting-a-safari-app-extension-to-a-safari-web-extension"
      ],
      "title": "Extension conversions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Extension-conversions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/converting-a-safari-app-extension-to-a-safari-web-extension"
              ],
              "title": "Extension conversions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/converting-a-web-extension-for-safari"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/converting-a-web-extension-for-safari"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
