{
  "abstract": [
    {
      "text": "Transfer bookmarks, saved passwords, and other information between browsers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/importing-data-exported-from-safari"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Importing data exported from Safari"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Starting in iOS 18.2, iPadOS 18.2, and visionOS 2.2, someone can export their browser data from Safari Settings in the Settings app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In macOS 15.2 and newer, they export their browser data by choosing File > Export in Safari.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On all platforms, Safari exports the data in a ZIP archive that contains a bookmarks file, a passwords file, a payment cards file, and for each profile the person creates in Safari one browser history file and one Safari extensions file.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The files have localized file names, in the ",
              "type": "text"
            },
            {
              "code": "en_US",
              "type": "codeVoice"
            },
            {
              "text": " locale their names are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "Bookmarks.html",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Bookmark data",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "Passwords.csv",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Passwords",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "History.json",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Browser history",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "PaymentCards.json",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Payment cards",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "code": "Extensions.json",
                        "type": "codeVoice"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Safari extensions",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "When someone creates multiple profiles, Safari exports the browser history and extension information for each profile into a separate file with the profile name as a filename suffix.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To import this data, create UI in your browser that someone uses to share the ZIP archive they export from Safari.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Unzip the file, and use the information in the sections below to interpret the contents that you load into your browser’s data model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your browser can also export its data in the same format for someone to import into Safari.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Import-bookmarks-and-Reading-List",
          "level": 3,
          "text": "Import bookmarks and Reading List",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Safari exports bookmarks in an HTML file using the ",
              "type": "text"
            },
            {
              "identifier": "https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa753582(v=vs.85)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The Reading List is a sub-folder with the identifier ",
              "type": "text"
            },
            {
              "code": "com.apple.ReadingList",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Import-Safari-passwords",
          "level": 3,
          "text": "Import Safari passwords",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Safari exports passwords in a comma-separated values (CSV) file that includes a titles row and contains the following columns:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A name for the saved password.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "Title",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A URL for the website that someone saved the password for.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "URL",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The username associated with the password.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "Username",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The saved password.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "Password",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Free-form notes that the person associated with the password.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "Notes",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A URL that uses the otpauth scheme and identifies the one-time passcode (OTP) generator that the website uses as a second factor with the password, for example, ",
                        "type": "text"
                      },
                      {
                        "code": "otpauth://totp?secret=ASDFA&algorithm=SHA1&digits=6&period=30",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "OTPAuth",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "anchor": "Understand-JSON-metadata",
          "level": 3,
          "text": "Understand JSON metadata",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Safari exports browser history, extensions, and payment cards as JSON files.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The top-level object in each file contains a ",
              "type": "text"
            },
            {
              "code": "metadata",
              "type": "codeVoice"
            },
            {
              "text": " key, whose value is a JSON object containing these keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that’s web browser name, which is ",
                        "type": "text"
                      },
                      {
                        "code": "Safari",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if someone exported the data from Safari on iOS, iPadOS, macOS, or visionOS; or ",
                        "type": "text"
                      },
                      {
                        "code": "Safari Technology Preview",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if someone exported the data from Safari Technology Preview on macOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "browser_name",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that’s the version of Safari that exported the data, for example ",
                        "type": "text"
                      },
                      {
                        "code": "18.2",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "browser_version",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that describes the data in the file; one of ",
                        "type": "text"
                      },
                      {
                        "code": "history",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", ",
                        "type": "text"
                      },
                      {
                        "code": "extensions",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", or ",
                        "type": "text"
                      },
                      {
                        "code": "payment_cards",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "data_type",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An integer that’s the UNIX timestamp (the number of microseconds since midnight in the UTC time zone on January 1, 1970) at which Safari exported the file.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "export_time_usec",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An integer that’s the version of the export schema.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "schema_version",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "anchor": "Import-browser-history",
          "level": 3,
          "text": "Import browser history",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The top-level object in the history JSON file contains a ",
              "type": "text"
            },
            {
              "code": "history",
              "type": "codeVoice"
            },
            {
              "text": " key, which has a value that is an array of objects representing websites that Safari visited.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Each object in the array contains these keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that’s the URL of the history item.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "url",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional string that, if present, is the title of the history item.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "title",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An integer that’s the UNIX timestamp in microseconds of the latest visit to the item.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "time_usec",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional string that, if present, is the URL of the next item in the redirect chain.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "destination_url",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional integer that’s present if ",
                        "type": "text"
                      },
                      {
                        "code": "destination_url",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is also present and is the UNIX timestamp (the number of microseconds since midnight UTC, January 1, 1970) of the next navigation in the redirect chain.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "destination_time_usec",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional string that, if present, is the URL of the previous item in the redirect chain.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "source_url",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional integer that’s present if ",
                        "type": "text"
                      },
                      {
                        "code": "source_url",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is also present and is the UNIX timestamp in microseconds of the previous navigation in the redirect chain.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "source_time_usec",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An integer that’s the number of visits the browser made to this item, and is always greater than or equal to ",
                        "type": "text"
                      },
                      {
                        "code": "1",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "visits_count",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional Boolean that’s ",
                        "type": "text"
                      },
                      {
                        "code": "true",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if Safari failed to load the site when someone most recently tried to access it; otherwise, it’s ",
                        "type": "text"
                      },
                      {
                        "code": "false",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "latest_visit_was_load_failure",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional Boolean that’s ",
                        "type": "text"
                      },
                      {
                        "code": "true",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if the last visit to this item used the HTTP ",
                        "type": "text"
                      },
                      {
                        "code": "GET",
                        "type": "codeVoice"
                      },
                      {
                        "text": " method; otherwise, it’s ",
                        "type": "text"
                      },
                      {
                        "code": "false",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "latest_visit_was_http_get",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "When the web server redirects Safari to a different URL, the history list contains all of the URLs in the chain of redirections.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Link items in the redirection chain by comparing the ",
              "type": "text"
            },
            {
              "code": "url",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "time_usec",
              "type": "codeVoice"
            },
            {
              "text": " fields in one history item with the ",
              "type": "text"
            },
            {
              "code": "destination_url",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "destination_time_usec",
              "type": "codeVoice"
            },
            {
              "text": " of the item that redirected Safari to it, and the ",
              "type": "text"
            },
            {
              "code": "source_url",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "source_time_usec",
              "type": "codeVoice"
            },
            {
              "text": " of the item that it redirected Safari to, for example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "...",
            "{",
            "   \"url\" : \"https://maps.apple.com/\",",
            "   \"time_usec\" : 1722367302951213,",
            "   \"destination_url\" : \"https://www.apple.com/maps/\",",
            "   \"destination_time_usec\" : 1722367302951310",
            "},",
            "{",
            "   \"url\" : \"https://www.apple.com/maps/\",",
            "   \"time_usec\" : 1722367302951310,",
            "   \"title\" : \"Maps - Apple\",",
            "   \"source_url\" : \"https://maps.apple.com/\",",
            "   \"source_time_usec\" : 1722367302951213",
            "},",
            "..."
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "anchor": "Import-payment-cards",
          "level": 3,
          "text": "Import payment cards",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The top-level object in the payment cards JSON file contains a ",
              "type": "text"
            },
            {
              "code": "payment_cards",
              "type": "codeVoice"
            },
            {
              "text": " key, which has a value that is an array of objects representing the payment cards the person stored in Safari.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Each object in the array contains these keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that is the payment card number.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "card_number",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional string that, if present, is the name the person gave to the payment card.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "card_name",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional string that, if present, is the name of the cardholder.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "cardholder_name",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional integer that, if present, is the month of the card’s expiration date.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "card_expiration_month",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional integer that, if present, is the year of the card’s expiration date.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "card_expiration_year",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional integer that, if present, is the UNIX timestamp of the most recent occasion the person used the payment card.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "card_last_used_time_usec",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "The object looks like this example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "  \"card_number\" : \"0000000000000000\",",
            "  \"card_name\" : \"My Bank Card\",",
            "  \"cardholder_name\" : \"Mei Chen\",",
            "  \"card_expiration_month\" : 11,",
            "  \"card_expiration_year\" : 2027,",
            "  \"card_last_used_time_usec\" : 1722730594744987",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "anchor": "Import-extension-information",
          "level": 3,
          "text": "Import extension information",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The top-level object in the extensions JSON file contains an ",
              "type": "text"
            },
            {
              "code": "extensions",
              "type": "codeVoice"
            },
            {
              "text": " key, which has a value that is an array of objects representing the Safari App Extensions, Safari Web Extensions, and Safari Content Blockers that the person installed and enabled in their Safari profile.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Each object in the array contains these keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that’s the bundle identifier of the extension followed by the Developer Team ID, for example ",
                        "type": "text"
                      },
                      {
                        "code": "com.example.great-app.browser-extension (AB67HSA2XZ)",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "composed_identifier",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that’s the name of the extension’s developer.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "developer_name",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that’s the display name of the extension.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "display_name",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A JSON object that contains information you use to discover the extension’s containing app in its marketplace, which for Safari extensions is the App Store or Mac App Store.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "marketplace_lookup",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "marketplace_lookup",
              "type": "codeVoice"
            },
            {
              "text": " object contains these keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that’s the identifier in the marketplace for the app that contains the Safari extension.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "store_identifier",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that, if present, is the bundle identifier of the Safari extension on iOS corresponding with this Safari extension on macOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ios_extension_bundle_identifier",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that, if present, is the bundle identifier of the iOS app corresponding with the macOS app that hosts this Safari extension.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ios_app_bundle_identifier",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that, if present, is the bundle identifier of the Safari extension on macOS corresponding with this Safari extension on iOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "macos_extension_bundle_identifier",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that, if present, is the bundle identifier of the macOS app corresponding with the iOS app that hosts this Safari extension.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "macos_app_bundle_identifier",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on bundle identifiers, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFBundleIdentifier",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CFBundleIdentifier"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationSession/CompletionHandler": {
      "abstract": [
        {
          "text": "The completion handler for an authentication session when the user cancels or finishes the login.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationSession/CompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "SFAuthenticationSession.CompletionHandler",
      "type": "topic",
      "url": "/documentation/safariservices/sfauthenticationsession/completionhandler"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariViewController": {
      "abstract": [
        {
          "text": "An object that provides a visible standard interface for browsing the web.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariViewController"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariViewController"
        }
      ],
      "role": "symbol",
      "title": "SFSafariViewController",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariviewcontroller"
    },
    "https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa753582(v=vs.85)": {
      "identifier": "https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa753582(v=vs.85)",
      "title": "Netscape Bookmarks file format",
      "titleInlineContent": [
        {
          "text": "Netscape Bookmarks file format",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa753582(v=vs.85)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Safari-content-in-your-app",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariViewController",
        "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationSession/CompletionHandler"
      ],
      "title": "Safari content in your app"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Safari-content-in-your-app",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariViewController",
                "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationSession/CompletionHandler"
              ],
              "title": "Safari content in your app"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAuthenticationSession~1CompletionHandler/title",
          "value": "SFAuthenticationCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAuthenticationSession~1CompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthenticationCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAuthenticationSession~1CompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthenticationCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariViewController/title",
          "value": "SFSafariViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/importing-data-exported-from-safari"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/importing-data-exported-from-safari"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
