{
  "abstract": [
    {
      "text": "Learn about enhancements to Safari Web Extensions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/modernizing-safari-web-extensions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Modernizing Safari Web Extensions"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC22 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc2022/10099/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before you run the sample code project in Xcode, open Safari and choose Develop > Allow Unsigned Extensions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "d43c0429a69e/ModernizingSafariWebExtensions.zip": {
      "checksum": "d43c0429a69e77bcf57db119bc25da4011f377e16ec671363d8f80728e721da2b6f09c0d5f09bb1d37dc53f0d0762b5c412d0a26181dbf879d852366d13e11bd",
      "identifier": "d43c0429a69e/ModernizingSafariWebExtensions.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/d43c0429a69e/ModernizingSafariWebExtensions.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/creating-a-safari-web-extension": {
      "abstract": [
        {
          "text": "Build a Safari web extension in Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/creating-a-safari-web-extension",
      "kind": "article",
      "role": "article",
      "title": "Creating a Safari web extension",
      "type": "topic",
      "url": "/documentation/safariservices/creating-a-safari-web-extension"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/developing-a-safari-web-extension": {
      "abstract": [
        {
          "text": "Customize and enhance web pages by building a Safari web extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/developing-a-safari-web-extension",
      "kind": "article",
      "role": "sampleCode",
      "title": "Developing a Safari Web Extension",
      "type": "topic",
      "url": "/documentation/safariservices/developing-a-safari-web-extension"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions": {
      "abstract": [
        {
          "text": "Create web extensions that work in Safari and other browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Safari web extensions",
      "type": "topic",
      "url": "/documentation/safariservices/safari-web-extensions"
    },
    "https://developer.apple.com/wwdc2022/10099/": {
      "identifier": "https://developer.apple.com/wwdc2022/10099/",
      "title": "10099: What’s new in Safari Web Extensions",
      "titleInlineContent": [
        {
          "text": "10099: What’s new in Safari Web Extensions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc2022/10099/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "d43c0429a69e/ModernizingSafariWebExtensions.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "New-extensions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/creating-a-safari-web-extension",
        "doc://com.apple.safariservices/documentation/SafariServices/developing-a-safari-web-extension"
      ],
      "title": "New extensions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "New-extensions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/creating-a-safari-web-extension",
                "doc://com.apple.safariservices/documentation/SafariServices/developing-a-safari-web-extension"
              ],
              "title": "New extensions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/modernizing-safari-web-extensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/modernizing-safari-web-extensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
