{
  "abstract": [
    {
      "text": "Build a Safari Extension that displays metadata using Open Graph.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/previewing-metadata-using-open-graph"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.14",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "13.2",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Previewing Metadata using Open Graph"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with the Tech Talks 2021 session ",
                  "type": "text"
                },
                {
                  "identifier": "http://developer.apple.com/tech-talks/110148",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "30a55aaa70fc/PreviewingMetadataUsingOpenGraph.zip": {
      "checksum": "30a55aaa70fc4fe852f8e92ee3c0e44f10208e8429d3d79ccf74bdd79c76bc537dbdd18ae127ee6aff1376fe38c3d51abcee43e10f3463ea345e7ab2e9764574",
      "identifier": "30a55aaa70fc/PreviewingMetadataUsingOpenGraph.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/30a55aaa70fc/PreviewingMetadataUsingOpenGraph.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/managing-safari-web-extension-permissions": {
      "abstract": [
        {
          "text": "Respect user privacy by setting appropriate permissions for your Safari web extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/managing-safari-web-extension-permissions",
      "kind": "article",
      "role": "article",
      "title": "Managing Safari web extension permissions",
      "type": "topic",
      "url": "/documentation/safariservices/managing-safari-web-extension-permissions"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions": {
      "abstract": [
        {
          "text": "Create web extensions that work in Safari and other browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Safari web extensions",
      "type": "topic",
      "url": "/documentation/safariservices/safari-web-extensions"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/updating-a-safari-web-extension": {
      "abstract": [
        {
          "text": "Add new features and fix bugs in your Safari web extension using Xcode tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/updating-a-safari-web-extension",
      "kind": "article",
      "role": "article",
      "title": "Updating a Safari web extension",
      "type": "topic",
      "url": "/documentation/safariservices/updating-a-safari-web-extension"
    },
    "http://developer.apple.com/tech-talks/110148": {
      "identifier": "http://developer.apple.com/tech-talks/110148",
      "title": "Build and deploy Safari Extensions for iOS",
      "titleInlineContent": [
        {
          "text": "Build and deploy Safari Extensions for iOS",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://developer.apple.com/tech-talks/110148"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "30a55aaa70fc/PreviewingMetadataUsingOpenGraph.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Extension-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/updating-a-safari-web-extension",
        "doc://com.apple.safariservices/documentation/SafariServices/managing-safari-web-extension-permissions"
      ],
      "title": "Extension updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Extension-updates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/updating-a-safari-web-extension",
                "doc://com.apple.safariservices/documentation/SafariServices/managing-safari-web-extension-permissions"
              ],
              "title": "Extension updates"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/previewing-metadata-using-open-graph"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/previewing-metadata-using-open-graph"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
