{
  "abstract": [
    {
      "text": "The domain used for Reading List errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/SSReadingList"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/reading-list-error-domain"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Reading List Error Domain"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SSReadingList": {
      "abstract": [
        {
          "text": "An object for adding items to a user’s Safari Reading List.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSReadingList"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SSReadingList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSReadingList"
        }
      ],
      "role": "symbol",
      "title": "SSReadingList",
      "type": "topic",
      "url": "/documentation/safariservices/ssreadinglist"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError/Code": {
      "abstract": [
        {
          "text": "Messages that describe a Safari Reading List error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SSReadingListError.Code",
      "type": "topic",
      "url": "/documentation/safariservices/ssreadinglisterror/code"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Safari Reading List errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SSReadingListErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SSReadingListErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SSReadingListErrorDomain",
      "type": "topic",
      "url": "/documentation/safariservices/ssreadinglisterrordomain"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError/Code"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListErrorDomain"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListErrorDomain"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SSReadingListError/Code"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingList/title",
          "value": "SSReadingList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSReadingList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSReadingList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingListError~1Code/title",
          "value": "SSReadingListErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingListError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSReadingListErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingListError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SSReadingListErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingListErrorDomain/title",
          "value": "SSReadingListErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SSReadingListErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SSReadingListErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/reading-list-error-domain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/reading-list-error-domain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
