{
  "abstract": [
    {
      "text": "Specify keys in your information property list file that provide information about your Safari app extension, UI, and permissions to the operating system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extensions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extension-information-property-list-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Safari app extension information property list keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Safari app extensions define keys that inform the operating system about your app extension’s capabilities and intents. Keys for app extensions follow a hierarchical structure, which each of the articles below describes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionViewController": {
      "abstract": [
        {
          "text": "The view controller for a popover associated with your app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariExtensionViewController"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariExtensionViewController"
        }
      ],
      "role": "symbol",
      "title": "SFSafariExtensionViewController",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionviewcontroller"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem": {
      "abstract": [
        {
          "text": "A proxy for a Safari app extension toolbar item in a Safari window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "SFSafariToolbarItem",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafaritoolbaritem"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-a-toolbar-item": {
      "abstract": [
        {
          "text": "Customize a toolbar item for your Safari app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-a-toolbar-item",
      "kind": "article",
      "role": "article",
      "title": "Adjusting settings for a toolbar item",
      "type": "topic",
      "url": "/documentation/safariservices/adjusting-settings-for-a-toolbar-item"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items": {
      "abstract": [
        {
          "text": "Customize contextual menu items for your Safari app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items",
      "kind": "article",
      "role": "article",
      "title": "Adjusting settings for contextual menu items",
      "type": "topic",
      "url": "/documentation/safariservices/adjusting-settings-for-contextual-menu-items"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/adjusting-website-access-permissions": {
      "abstract": [
        {
          "text": "Set website access permissions in a Safari app extension using information property list keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/adjusting-website-access-permissions",
      "kind": "article",
      "role": "article",
      "title": "Adjusting website access permissions",
      "type": "topic",
      "url": "/documentation/safariservices/adjusting-website-access-permissions"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extensions": {
      "abstract": [
        {
          "text": "Learn how Safari app extensions extend the web-browsing experience in Safari by leveraging web technologies and native code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Safari app extensions",
      "type": "topic",
      "url": "/documentation/safariservices/safari-app-extensions"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/setting-safari-app-extension-feature-keys": {
      "abstract": [
        {
          "text": "Set keys for permissions, scripts, style sheets, contextual menu items, and toolbar items in the information property list file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/setting-safari-app-extension-feature-keys",
      "kind": "article",
      "role": "article",
      "title": "Setting Safari app extension feature keys",
      "type": "topic",
      "url": "/documentation/safariservices/setting-safari-app-extension-feature-keys"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/using-content-script-and-style-sheet-keys": {
      "abstract": [
        {
          "text": "Learn about controlling style sheet and script injection with information property list keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-content-script-and-style-sheet-keys",
      "kind": "article",
      "role": "article",
      "title": "Using content script and style sheet keys",
      "type": "topic",
      "url": "/documentation/safariservices/using-content-script-and-style-sheet-keys"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys": {
      "abstract": [
        {
          "text": "Learn about adding contextual menu items and toolbar items to a Safari app extension with information property list keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys",
      "kind": "article",
      "role": "article",
      "title": "Using contextual menu and toolbar item keys",
      "type": "topic",
      "url": "/documentation/safariservices/using-contextual-menu-and-toolbar-item-keys"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/using-permissions-for-scripts-and-style-sheets": {
      "abstract": [
        {
          "text": "Learn about URL permissions for scripts and style sheets in a Safari app extension using information property list keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-permissions-for-scripts-and-style-sheets",
      "kind": "article",
      "role": "article",
      "title": "Using permissions for scripts and style sheets",
      "type": "topic",
      "url": "/documentation/safariservices/using-permissions-for-scripts-and-style-sheets"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/using-safari-app-extension-default-keys": {
      "abstract": [
        {
          "text": "Learn about the default keys in the information property list file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-safari-app-extension-default-keys",
      "kind": "article",
      "role": "article",
      "title": "Using Safari app extension default keys",
      "type": "topic",
      "url": "/documentation/safariservices/using-safari-app-extension-default-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "First-steps",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/using-safari-app-extension-default-keys"
      ],
      "title": "First steps"
    },
    {
      "anchor": "Access-and-permissions",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/setting-safari-app-extension-feature-keys",
        "doc://com.apple.safariservices/documentation/SafariServices/adjusting-website-access-permissions",
        "doc://com.apple.safariservices/documentation/SafariServices/using-permissions-for-scripts-and-style-sheets"
      ],
      "title": "Access and permissions"
    },
    {
      "anchor": "Conditional-scripts-and-style-sheet-injection",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/using-content-script-and-style-sheet-keys"
      ],
      "title": "Conditional scripts and style sheet injection"
    },
    {
      "anchor": "Contextual-menu-and-toolbar-items",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys",
        "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-a-toolbar-item",
        "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionViewController"
      ],
      "title": "Contextual menu and toolbar items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "First-steps",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/using-safari-app-extension-default-keys"
              ],
              "title": "First steps"
            },
            {
              "anchor": "Access-and-permissions",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/setting-safari-app-extension-feature-keys",
                "doc://com.apple.safariservices/documentation/SafariServices/adjusting-website-access-permissions",
                "doc://com.apple.safariservices/documentation/SafariServices/using-permissions-for-scripts-and-style-sheets"
              ],
              "title": "Access and permissions"
            },
            {
              "anchor": "Conditional-scripts-and-style-sheet-injection",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/using-content-script-and-style-sheet-keys"
              ],
              "title": "Conditional scripts and style sheet injection"
            },
            {
              "anchor": "Contextual-menu-and-toolbar-items",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys",
                "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-a-toolbar-item",
                "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionViewController"
              ],
              "title": "Contextual menu and toolbar items"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionViewController/title",
          "value": "SFSafariExtensionViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem/title",
          "value": "SFSafariToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariToolbarItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/safari-app-extension-information-property-list-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/safari-app-extension-information-property-list-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
