{
  "abstract": [
    {
      "text": "Set keys for permissions, scripts, style sheets, contextual menu items, and toolbar items in the information property list file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extensions",
        "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extension-information-property-list-keys"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/setting-safari-app-extension-feature-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Setting Safari app extension feature keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After selecting which default keys to use in your Safari app extension’s information property list file, select the appropriate feature keys to identify files and UI items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The table below lists the primary keys in the ",
              "type": "text"
            },
            {
              "code": "NSExtension",
              "type": "codeVoice"
            },
            {
              "text": " dictionary that are associated with Safari app extension features. For information on available subkeys, see the link in the primary key description.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Key",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "SFSafariContentScript",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Array",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "An array for adding content scripts to the extension. Each value in the array is a dictionary that provides the filename for a content script. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " For subkeys, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-content-script-and-style-sheet-keys",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "SFSafariContextMenu",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Array",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "An array for adding items to Safari’s context menu — the menu that appears when the user Control-clicks a webpage. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " For subkeys, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "SFSafariStyleSheet",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Array",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "An array for adding style sheets to the extension or to pages from a limited subset of URLs. Each value in the array is a dictionary that provides the filename for a content script. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " For subkeys, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-content-script-and-style-sheet-keys",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "SFSafariToolbarItem",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Dictionary",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "A dictionary for adding a toolbar item to Safari windows. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " For subkeys, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "SFSafariWebsiteAccess",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Dictionary",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "An optional dictionary that specifies which webpages the Safari app extension can access, if any. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " For details about configuring website access, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/adjusting-website-access-permissions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to the ",
              "type": "text"
            },
            {
              "code": "NSExtension",
              "type": "codeVoice"
            },
            {
              "text": " keys, the ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file includes an ",
              "type": "text"
            },
            {
              "code": "NSHumanReadableDescription",
              "type": "codeVoice"
            },
            {
              "text": " key for your Safari app extension. When you install the app extension, the string value of this key appears in Safari > Settings > Preferences as the example below shows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3897929",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items": {
      "abstract": [
        {
          "text": "Customize contextual menu items for your Safari app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items",
      "kind": "article",
      "role": "article",
      "title": "Adjusting settings for contextual menu items",
      "type": "topic",
      "url": "/documentation/safariservices/adjusting-settings-for-contextual-menu-items"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/adjusting-website-access-permissions": {
      "abstract": [
        {
          "text": "Set website access permissions in a Safari app extension using information property list keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/adjusting-website-access-permissions",
      "kind": "article",
      "role": "article",
      "title": "Adjusting website access permissions",
      "type": "topic",
      "url": "/documentation/safariservices/adjusting-website-access-permissions"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage": {
      "abstract": [
        {
          "text": "Add to or override styles by injecting CSS style sheets into webpages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage",
      "kind": "article",
      "role": "article",
      "title": "Injecting CSS style sheets into a webpage",
      "type": "topic",
      "url": "/documentation/safariservices/injecting-css-style-sheets-into-a-webpage"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extension-information-property-list-keys": {
      "abstract": [
        {
          "text": "Specify keys in your information property list file that provide information about your Safari app extension, UI, and permissions to the operating system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extension-information-property-list-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Safari app extension information property list keys",
      "type": "topic",
      "url": "/documentation/safariservices/safari-app-extension-information-property-list-keys"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extensions": {
      "abstract": [
        {
          "text": "Learn how Safari app extensions extend the web-browsing experience in Safari by leveraging web technologies and native code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/safari-app-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Safari app extensions",
      "type": "topic",
      "url": "/documentation/safariservices/safari-app-extensions"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/using-content-script-and-style-sheet-keys": {
      "abstract": [
        {
          "text": "Learn about controlling style sheet and script injection with information property list keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-content-script-and-style-sheet-keys",
      "kind": "article",
      "role": "article",
      "title": "Using content script and style sheet keys",
      "type": "topic",
      "url": "/documentation/safariservices/using-content-script-and-style-sheet-keys"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys": {
      "abstract": [
        {
          "text": "Learn about adding contextual menu items and toolbar items to a Safari app extension with information property list keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys",
      "kind": "article",
      "role": "article",
      "title": "Using contextual menu and toolbar item keys",
      "type": "topic",
      "url": "/documentation/safariservices/using-contextual-menu-and-toolbar-item-keys"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/using-permissions-for-scripts-and-style-sheets": {
      "abstract": [
        {
          "text": "Learn about URL permissions for scripts and style sheets in a Safari app extension using information property list keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-permissions-for-scripts-and-style-sheets",
      "kind": "article",
      "role": "article",
      "title": "Using permissions for scripts and style sheets",
      "type": "topic",
      "url": "/documentation/safariservices/using-permissions-for-scripts-and-style-sheets"
    },
    "media-3897929": {
      "alt": "A screenshot of the description that appears in Safari > Settings > Preferences when a user selects your extension. A heading reads My Extension 1.0 from FirstSafariExtensionApp. Below that, a description reads This is a Safari Extension. You should tell us what your extension does here. At the bottom is a button labeled Uninstall. ",
      "identifier": "media-3897929",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/231cabb59d94fbc04ffaa54d81f36828/media-3897929@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/59b9ea87911b16eb4d89a93060460fd5/media-3897929~dark@2x.png"
        }
      ]
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Access-and-permissions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/adjusting-website-access-permissions",
        "doc://com.apple.safariservices/documentation/SafariServices/using-permissions-for-scripts-and-style-sheets"
      ],
      "title": "Access and permissions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Access-and-permissions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/adjusting-website-access-permissions",
                "doc://com.apple.safariservices/documentation/SafariServices/using-permissions-for-scripts-and-style-sheets"
              ],
              "title": "Access and permissions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/setting-safari-app-extension-feature-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/setting-safari-app-extension-feature-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
