{
  "abstract": [
    {
      "text": "A string the system uses as a key in a user info dictionary to identify a profile identifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SFExtensionProfileKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SFExtensionProfileKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFExtensionProfileKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "SFExtensionProfileKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SFExtensionProfileKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.safariservices/documentation/SafariServices/passing-messages-between-safari-app-extensions-and-injected-scripts",
        "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-the-app-and-javascript-in-a-safari-web-extension"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey": {
      "abstract": [
        {
          "text": "A string the system uses as a key in a user info dictionary to identify a profile identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFExtensionProfileKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFExtensionProfileKey"
        }
      ],
      "role": "symbol",
      "title": "SFExtensionProfileKey",
      "type": "topic",
      "url": "/documentation/safariservices/sfextensionprofilekey"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandler": {
      "abstract": [
        {
          "text": "A base class that you subclass to handle events in your Safari app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariExtensionHandler"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariExtensionHandler"
        }
      ],
      "role": "symbol",
      "title": "SFSafariExtensionHandler",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandler"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling": {
      "abstract": [
        {
          "text": "A protocol for implementing event handling in a Safari app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariExtensionHandling"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariExtensionHandling"
        }
      ],
      "role": "symbol",
      "title": "SFSafariExtensionHandling",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionManager": {
      "abstract": [
        {
          "text": "A class that your app uses to find out the current state of a Safari app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariExtensionManager"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariExtensionManager"
        }
      ],
      "role": "symbol",
      "title": "SFSafariExtensionManager",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionmanager"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionState": {
      "abstract": [
        {
          "text": "The state of a Safari app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariExtensionState"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariExtensionState"
        }
      ],
      "role": "symbol",
      "title": "SFSafariExtensionState",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionstate"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPageProperties": {
      "abstract": [
        {
          "text": "An object that captures information about a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariPageProperties"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPageProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariPageProperties"
        }
      ],
      "role": "symbol",
      "title": "SFSafariPageProperties",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafaripageproperties"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/injecting-a-script-into-a-webpage": {
      "abstract": [
        {
          "text": "Inject a script that you write for a Safari app extension into a webpage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/injecting-a-script-into-a-webpage",
      "kind": "article",
      "role": "article",
      "title": "Injecting a script into a webpage",
      "type": "topic",
      "url": "/documentation/safariservices/injecting-a-script-into-a-webpage"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage": {
      "abstract": [
        {
          "text": "Add to or override styles by injecting CSS style sheets into webpages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage",
      "kind": "article",
      "role": "article",
      "title": "Injecting CSS style sheets into a webpage",
      "type": "topic",
      "url": "/documentation/safariservices/injecting-css-style-sheets-into-a-webpage"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-the-app-and-javascript-in-a-safari-web-extension": {
      "abstract": [
        {
          "text": "Communicate about events and share data between the containing app and JavaScript by using native messaging and app groups.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-the-app-and-javascript-in-a-safari-web-extension",
      "kind": "article",
      "role": "article",
      "title": "Messaging between the app and JavaScript in a Safari web extension",
      "type": "topic",
      "url": "/documentation/safariservices/messaging-between-the-app-and-javascript-in-a-safari-web-extension"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/passing-messages-between-safari-app-extensions-and-injected-scripts": {
      "abstract": [
        {
          "text": "Communicate between your Safari app extension and injected scripts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/passing-messages-between-safari-app-extensions-and-injected-scripts",
      "kind": "article",
      "role": "article",
      "title": "Passing messages between Safari app extensions and injected scripts",
      "type": "topic",
      "url": "/documentation/safariservices/passing-messages-between-safari-app-extensions-and-injected-scripts"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/using-injected-style-sheets-and-scripts": {
      "abstract": [
        {
          "text": "Learn how you can affect the appearance or behavior of a webpage by using injected style sheets and scripts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-injected-style-sheets-and-scripts",
      "kind": "article",
      "role": "article",
      "title": "Using injected style sheets and scripts",
      "type": "topic",
      "url": "/documentation/safariservices/using-injected-style-sheets-and-scripts"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Injected-style-sheets-and-scripts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/using-injected-style-sheets-and-scripts",
        "doc://com.apple.safariservices/documentation/SafariServices/injecting-a-script-into-a-webpage",
        "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage",
        "doc://com.apple.safariservices/documentation/SafariServices/passing-messages-between-safari-app-extensions-and-injected-scripts",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandler",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionManager",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionState",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPageProperties",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling"
      ],
      "title": "Injected style sheets and scripts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFExtensionProfileKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFExtensionProfileKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.safariservices/documentation/SafariServices"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Injected-style-sheets-and-scripts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/using-injected-style-sheets-and-scripts",
                "doc://com.apple.safariservices/documentation/SafariServices/injecting-a-script-into-a-webpage",
                "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage",
                "doc://com.apple.safariservices/documentation/SafariServices/passing-messages-between-safari-app-extensions-and-injected-scripts",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandler",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionManager",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionState",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPageProperties",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling"
              ],
              "title": "Injected style sheets and scripts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SFExtensionProfileKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionManager/title",
          "value": "SFSafariExtensionManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling/title",
          "value": "SFSafariExtensionHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandler/title",
          "value": "SFSafariExtensionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariPageProperties/title",
          "value": "SFSafariPageProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariPageProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariPageProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariPageProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariPageProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFExtensionProfileKey/title",
          "value": "SFExtensionProfileKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFExtensionProfileKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFExtensionProfileKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionState/title",
          "value": "SFSafariExtensionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/sfextensionprofilekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/sfextensionprofilekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
