{
  "abstract": [
    {
      "text": "A string the system uses as a key in a user info dictionary to identify a message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionMessageKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SFExtensionMessageKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SFExtensionMessageKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFExtensionMessageKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "SFExtensionMessageKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SFExtensionMessageKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-the-app-and-javascript-in-a-safari-web-extension"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionMessageKey": {
      "abstract": [
        {
          "text": "A string the system uses as a key in a user info dictionary to identify a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFExtensionMessageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionMessageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFExtensionMessageKey"
        }
      ],
      "role": "symbol",
      "title": "SFExtensionMessageKey",
      "type": "topic",
      "url": "/documentation/safariservices/sfextensionmessagekey"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey": {
      "abstract": [
        {
          "text": "A string the system uses as a key in a user info dictionary to identify a profile identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFExtensionProfileKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFExtensionProfileKey"
        }
      ],
      "role": "symbol",
      "title": "SFExtensionProfileKey",
      "type": "topic",
      "url": "/documentation/safariservices/sfextensionprofilekey"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/messaging-a-web-extension-s-native-app": {
      "abstract": [
        {
          "text": "Communicate between your Safari web extension and its containing app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/messaging-a-web-extension-s-native-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Messaging a Web Extension’s Native App",
      "type": "topic",
      "url": "/documentation/safariservices/messaging-a-web-extension-s-native-app"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-a-webpage-and-your-safari-web-extension": {
      "abstract": [
        {
          "text": "Configure your extension to enable messaging from webpages, and then update your extension to handle messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-a-webpage-and-your-safari-web-extension",
      "kind": "article",
      "role": "article",
      "title": "Messaging between a webpage and your Safari web extension",
      "type": "topic",
      "url": "/documentation/safariservices/messaging-between-a-webpage-and-your-safari-web-extension"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-the-app-and-javascript-in-a-safari-web-extension": {
      "abstract": [
        {
          "text": "Communicate about events and share data between the containing app and JavaScript by using native messaging and app groups.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-the-app-and-javascript-in-a-safari-web-extension",
      "kind": "article",
      "role": "article",
      "title": "Messaging between the app and JavaScript in a Safari web extension",
      "type": "topic",
      "url": "/documentation/safariservices/messaging-between-the-app-and-javascript-in-a-safari-web-extension"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Messaging",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-the-app-and-javascript-in-a-safari-web-extension",
        "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey",
        "doc://com.apple.safariservices/documentation/SafariServices/messaging-a-web-extension-s-native-app",
        "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-a-webpage-and-your-safari-web-extension"
      ],
      "title": "Messaging"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFExtensionMessageKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFExtensionMessageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.safariservices/documentation/SafariServices"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Messaging",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-the-app-and-javascript-in-a-safari-web-extension",
                "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey",
                "doc://com.apple.safariservices/documentation/SafariServices/messaging-a-web-extension-s-native-app",
                "doc://com.apple.safariservices/documentation/SafariServices/messaging-between-a-webpage-and-your-safari-web-extension"
              ],
              "title": "Messaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SFExtensionMessageKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFExtensionProfileKey/title",
          "value": "SFExtensionProfileKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFExtensionProfileKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFExtensionProfileKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFExtensionMessageKey/title",
          "value": "SFExtensionMessageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFExtensionMessageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFExtensionMessageKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/sfextensionmessagekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/sfextensionmessagekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
