{
  "abstract": [
    {
      "text": "A protocol for implementing event handling in a Safari app extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SFSafariExtensionHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SFSafariExtensionHandling"
      }
    ],
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFSafariExtensionHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "SFSafariExtensionHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey": {
      "abstract": [
        {
          "text": "A string the system uses as a key in a user info dictionary to identify a profile identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFExtensionProfileKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFExtensionProfileKey"
        }
      ],
      "role": "symbol",
      "title": "SFExtensionProfileKey",
      "type": "topic",
      "url": "/documentation/safariservices/sfextensionprofilekey"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariApplication/dispatchMessage(withName:toExtensionWithIdentifier:userInfo:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends a message to a Safari app extension, launching Safari if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatchMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toExtensionWithIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariApplication/dispatchMessage(withName:toExtensionWithIdentifier:userInfo:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatchMessageWithName:toExtensionWithIdentifier:userInfo:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "dispatchMessage(withName:toExtensionWithIdentifier:userInfo:completionHandler:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariapplication/dispatchmessage(withname:toextensionwithidentifier:userinfo:completionhandler:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandler": {
      "abstract": [
        {
          "text": "A base class that you subclass to handle events in your Safari app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariExtensionHandler"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariExtensionHandler"
        }
      ],
      "role": "symbol",
      "title": "SFSafariExtensionHandler",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandler"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling": {
      "abstract": [
        {
          "text": "A protocol for implementing event handling in a Safari app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariExtensionHandling"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariExtensionHandling"
        }
      ],
      "role": "symbol",
      "title": "SFSafariExtensionHandling",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/additionalRequestHeaders(for:completionHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "additionalRequestHeaders"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/additionalRequestHeaders(for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "additionalRequestHeadersForURL:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "additionalRequestHeaders(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/additionalrequestheaders(for:completionhandler:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/contentBlocker(withIdentifier:blockedResourcesWith:on:)": {
      "abstract": [
        {
          "text": "Tells the handler which resources a content blocker blocked on a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentBlocker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blockedResourcesWith"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariPage",
          "text": "SFSafariPage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/contentBlocker(withIdentifier:blockedResourcesWith:on:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentBlockerWithIdentifier:blockedResourcesWithURLs:onPage:"
        }
      ],
      "role": "symbol",
      "title": "contentBlocker(withIdentifier:blockedResourcesWith:on:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/contentblocker(withidentifier:blockedresourceswith:on:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/contextMenuItemSelected(withCommand:in:userInfo:)": {
      "abstract": [
        {
          "text": "A method the system calls when a user selects one of the app extension’s context menu items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextMenuItemSelected"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariPage",
          "text": "SFSafariPage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/contextMenuItemSelected(withCommand:in:userInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contextMenuItemSelectedWithCommand:inPage:userInfo:"
        }
      ],
      "role": "symbol",
      "title": "contextMenuItemSelected(withCommand:in:userInfo:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/contextmenuitemselected(withcommand:in:userinfo:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/messageReceived(withName:from:userInfo:)": {
      "abstract": [
        {
          "text": "A method the system calls when the extension receives a message from an injected script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageReceived"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariPage",
          "text": "SFSafariPage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/messageReceived(withName:from:userInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "messageReceivedWithName:fromPage:userInfo:"
        }
      ],
      "role": "symbol",
      "title": "messageReceived(withName:from:userInfo:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/messagereceived(withname:from:userinfo:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/messageReceivedFromContainingApp(withName:userInfo:)": {
      "abstract": [
        {
          "text": "A method the system calls when the extension receives a message from the extension’s containing app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageReceivedFromContainingApp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/messageReceivedFromContainingApp(withName:userInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "messageReceivedFromContainingAppWithName:userInfo:"
        }
      ],
      "role": "symbol",
      "title": "messageReceivedFromContainingApp(withName:userInfo:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/messagereceivedfromcontainingapp(withname:userinfo:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/page(_:willNavigateTo:)": {
      "abstract": [
        {
          "text": "A method the system calls when a webpage is about to navigate to a new URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "page"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariPage",
          "text": "SFSafariPage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willNavigateTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/page(_:willNavigateTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "page:willNavigateToURL:"
        }
      ],
      "role": "symbol",
      "title": "page(_:willNavigateTo:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/page(_:willnavigateto:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverDidClose(in:)": {
      "abstract": [
        {
          "text": "Tells the handler that the app extension’s popover was closed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverDidClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariWindow",
          "text": "SFSafariWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverDidClose(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverDidCloseInWindow:"
        }
      ],
      "role": "symbol",
      "title": "popoverDidClose(in:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/popoverdidclose(in:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverViewController()": {
      "abstract": [
        {
          "text": "Asks the handler to provide a popover view controller for display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverViewController"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariExtensionViewController",
          "text": "SFSafariExtensionViewController"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverViewController()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverViewController"
        }
      ],
      "role": "symbol",
      "title": "popoverViewController()",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/popoverviewcontroller()"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverWillShow(in:)": {
      "abstract": [
        {
          "text": "Tells the handler that the app extension’s popover is about to be opened.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverWillShow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariWindow",
          "text": "SFSafariWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverWillShow(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverWillShowInWindow:"
        }
      ],
      "role": "symbol",
      "title": "popoverWillShow(in:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/popoverwillshow(in:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/toolbarItemClicked(in:)": {
      "abstract": [
        {
          "text": "A method the system calls when a user clicks a toolbar item associated with the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarItemClicked"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariWindow",
          "text": "SFSafariWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/toolbarItemClicked(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbarItemClickedInWindow:"
        }
      ],
      "role": "symbol",
      "title": "toolbarItemClicked(in:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/toolbaritemclicked(in:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateContextMenuItem(withCommand:in:userInfo:validationHandler:)": {
      "abstract": [
        {
          "text": "Validates whether a particular contextual menu item should be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validateContextMenuItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariPage",
          "text": "SFSafariPage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "validationHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateContextMenuItem(withCommand:in:userInfo:validationHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateContextMenuItemWithCommand:inPage:userInfo:validationHandler:"
        }
      ],
      "role": "symbol",
      "title": "validateContextMenuItem(withCommand:in:userInfo:validationHandler:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/validatecontextmenuitem(withcommand:in:userinfo:validationhandler:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateToolbarItem(in:validationHandler:)": {
      "abstract": [
        {
          "text": "Determines if a toolbar menu item should be enabled or have badge text when browser state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validateToolbarItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariWindow",
          "text": "SFSafariWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "validationHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateToolbarItem(in:validationHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateToolbarItemInWindow:validationHandler:"
        }
      ],
      "role": "symbol",
      "title": "validateToolbarItem(in:validationHandler:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionhandling/validatetoolbaritem(in:validationhandler:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionManager": {
      "abstract": [
        {
          "text": "A class that your app uses to find out the current state of a Safari app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariExtensionManager"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariExtensionManager"
        }
      ],
      "role": "symbol",
      "title": "SFSafariExtensionManager",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionmanager"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionState": {
      "abstract": [
        {
          "text": "The state of a Safari app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariExtensionState"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariExtensionState"
        }
      ],
      "role": "symbol",
      "title": "SFSafariExtensionState",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariextensionstate"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPageProperties": {
      "abstract": [
        {
          "text": "An object that captures information about a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariPageProperties"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPageProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariPageProperties"
        }
      ],
      "role": "symbol",
      "title": "SFSafariPageProperties",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafaripageproperties"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/injecting-a-script-into-a-webpage": {
      "abstract": [
        {
          "text": "Inject a script that you write for a Safari app extension into a webpage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/injecting-a-script-into-a-webpage",
      "kind": "article",
      "role": "article",
      "title": "Injecting a script into a webpage",
      "type": "topic",
      "url": "/documentation/safariservices/injecting-a-script-into-a-webpage"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage": {
      "abstract": [
        {
          "text": "Add to or override styles by injecting CSS style sheets into webpages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage",
      "kind": "article",
      "role": "article",
      "title": "Injecting CSS style sheets into a webpage",
      "type": "topic",
      "url": "/documentation/safariservices/injecting-css-style-sheets-into-a-webpage"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/passing-messages-between-safari-app-extensions-and-injected-scripts": {
      "abstract": [
        {
          "text": "Communicate between your Safari app extension and injected scripts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/passing-messages-between-safari-app-extensions-and-injected-scripts",
      "kind": "article",
      "role": "article",
      "title": "Passing messages between Safari app extensions and injected scripts",
      "type": "topic",
      "url": "/documentation/safariservices/passing-messages-between-safari-app-extensions-and-injected-scripts"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/using-injected-style-sheets-and-scripts": {
      "abstract": [
        {
          "text": "Learn how you can affect the appearance or behavior of a webpage by using injected style sheets and scripts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/using-injected-style-sheets-and-scripts",
      "kind": "article",
      "role": "article",
      "title": "Using injected style sheets and scripts",
      "type": "topic",
      "url": "/documentation/safariservices/using-injected-style-sheets-and-scripts"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandler"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariApplication/dispatchMessage(withName:toExtensionWithIdentifier:userInfo:completionHandler:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Injected-style-sheets-and-scripts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/using-injected-style-sheets-and-scripts",
        "doc://com.apple.safariservices/documentation/SafariServices/injecting-a-script-into-a-webpage",
        "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage",
        "doc://com.apple.safariservices/documentation/SafariServices/passing-messages-between-safari-app-extensions-and-injected-scripts",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandler",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionManager",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionState",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPageProperties",
        "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey"
      ],
      "title": "Injected style sheets and scripts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Receiving-Messages-in-Your-App-Extension",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/messageReceived(withName:from:userInfo:)",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/messageReceivedFromContainingApp(withName:userInfo:)"
      ],
      "title": "Receiving Messages in Your App Extension"
    },
    {
      "anchor": "Responding-to-Context-Menu-Selections",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/contextMenuItemSelected(withCommand:in:userInfo:)",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateContextMenuItem(withCommand:in:userInfo:validationHandler:)"
      ],
      "title": "Responding to Context Menu Selections"
    },
    {
      "anchor": "Working-with-Toolbar-Items",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/toolbarItemClicked(in:)",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateToolbarItem(in:validationHandler:)"
      ],
      "title": "Working with Toolbar Items"
    },
    {
      "anchor": "Working-with-Popovers",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverViewController()",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverWillShow(in:)",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverDidClose(in:)"
      ],
      "title": "Working with Popovers"
    },
    {
      "anchor": "Working-with-Content-Blockers",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/contentBlocker(withIdentifier:blockedResourcesWith:on:)"
      ],
      "title": "Working with Content Blockers"
    },
    {
      "anchor": "Responding-to-Page-Navigation",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/page(_:willNavigateTo:)"
      ],
      "title": "Responding to Page Navigation"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/additionalRequestHeaders(for:completionHandler:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFSafariExtensionHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.safariservices/documentation/SafariServices"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Receiving-Messages-in-Your-App-Extension",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/messageReceived(withName:from:userInfo:)",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/messageReceivedFromContainingApp(withName:userInfo:)"
              ],
              "title": "Receiving Messages in Your App Extension"
            },
            {
              "anchor": "Responding-to-Context-Menu-Selections",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/contextMenuItemSelected(withCommand:in:userInfo:)",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateContextMenuItem(withCommand:in:userInfo:validationHandler:)"
              ],
              "title": "Responding to Context Menu Selections"
            },
            {
              "anchor": "Working-with-Toolbar-Items",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/toolbarItemClicked(in:)",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateToolbarItem(in:validationHandler:)"
              ],
              "title": "Working with Toolbar Items"
            },
            {
              "anchor": "Working-with-Popovers",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverViewController()",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverWillShow(in:)",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/popoverDidClose(in:)"
              ],
              "title": "Working with Popovers"
            },
            {
              "anchor": "Working-with-Content-Blockers",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/contentBlocker(withIdentifier:blockedResourcesWith:on:)"
              ],
              "title": "Working with Content Blockers"
            },
            {
              "anchor": "Responding-to-Page-Navigation",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/page(_:willNavigateTo:)"
              ],
              "title": "Responding to Page Navigation"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/additionalRequestHeaders(for:completionHandler:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandler"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariApplication/dispatchMessage(withName:toExtensionWithIdentifier:userInfo:completionHandler:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Injected-style-sheets-and-scripts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/using-injected-style-sheets-and-scripts",
                "doc://com.apple.safariservices/documentation/SafariServices/injecting-a-script-into-a-webpage",
                "doc://com.apple.safariservices/documentation/SafariServices/injecting-css-style-sheets-into-a-webpage",
                "doc://com.apple.safariservices/documentation/SafariServices/passing-messages-between-safari-app-extensions-and-injected-scripts",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandler",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionManager",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionState",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariPageProperties",
                "doc://com.apple.safariservices/documentation/SafariServices/SFExtensionProfileKey"
              ],
              "title": "Injected style sheets and scripts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SFSafariExtensionHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1additionalRequestHeaders(for:completionHandler:)/title",
          "value": "additionalRequestHeadersForURL:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1additionalRequestHeaders(for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "additionalRequestHeadersForURL:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandler/title",
          "value": "SFSafariExtensionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1toolbarItemClicked(in:)/title",
          "value": "toolbarItemClickedInWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1toolbarItemClicked(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toolbarItemClickedInWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1contextMenuItemSelected(withCommand:in:userInfo:)/title",
          "value": "contextMenuItemSelectedWithCommand:inPage:userInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1contextMenuItemSelected(withCommand:in:userInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contextMenuItemSelectedWithCommand:inPage:userInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1validateContextMenuItem(withCommand:in:userInfo:validationHandler:)/title",
          "value": "validateContextMenuItemWithCommand:inPage:userInfo:validationHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1validateContextMenuItem(withCommand:in:userInfo:validationHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateContextMenuItemWithCommand:inPage:userInfo:validationHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling/title",
          "value": "SFSafariExtensionHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFExtensionProfileKey/title",
          "value": "SFExtensionProfileKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFExtensionProfileKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFExtensionProfileKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariPageProperties/title",
          "value": "SFSafariPageProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariPageProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariPageProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariPageProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariPageProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1popoverViewController()/title",
          "value": "popoverViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1popoverViewController()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popoverViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariApplication~1dispatchMessage(withName:toExtensionWithIdentifier:userInfo:completionHandler:)/title",
          "value": "dispatchMessageWithName:toExtensionWithIdentifier:userInfo:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariApplication~1dispatchMessage(withName:toExtensionWithIdentifier:userInfo:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "dispatchMessageWithName:toExtensionWithIdentifier:userInfo:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionState/title",
          "value": "SFSafariExtensionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1contentBlocker(withIdentifier:blockedResourcesWith:on:)/title",
          "value": "contentBlockerWithIdentifier:blockedResourcesWithURLs:onPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1contentBlocker(withIdentifier:blockedResourcesWith:on:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentBlockerWithIdentifier:blockedResourcesWithURLs:onPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1popoverDidClose(in:)/title",
          "value": "popoverDidCloseInWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1popoverDidClose(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popoverDidCloseInWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1messageReceivedFromContainingApp(withName:userInfo:)/title",
          "value": "messageReceivedFromContainingAppWithName:userInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1messageReceivedFromContainingApp(withName:userInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "messageReceivedFromContainingAppWithName:userInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1page(_:willNavigateTo:)/title",
          "value": "page:willNavigateToURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1page(_:willNavigateTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "page:willNavigateToURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1messageReceived(withName:from:userInfo:)/title",
          "value": "messageReceivedWithName:fromPage:userInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1messageReceived(withName:from:userInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "messageReceivedWithName:fromPage:userInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionManager/title",
          "value": "SFSafariExtensionManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariExtensionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1validateToolbarItem(in:validationHandler:)/title",
          "value": "validateToolbarItemInWindow:validationHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1validateToolbarItem(in:validationHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateToolbarItemInWindow:validationHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1popoverWillShow(in:)/title",
          "value": "popoverWillShowInWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1popoverWillShow(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popoverWillShowInWindow:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/sfsafariextensionhandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/sfsafariextensionhandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
