{"topicSections":[{"anchor":"Controlling-Toolbar-Items","title":"Controlling Toolbar Items","identifiers":["doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setEnabled(_:withBadgeText:)","doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setBadgeText(_:)","doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setEnabled(_:)","doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setImage(_:)","doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setLabel(_:)"]},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/showPopover()"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"]}],"seeAlsoSections":[{"anchor":"Contextual-menu-and-toolbar-items","title":"Contextual menu and toolbar items","generated":true,"identifiers":["doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys","doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-a-toolbar-item","doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items","doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionViewController"]}],"variants":[{"paths":["/documentation/safariservices/sfsafaritoolbaritem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/safariservices/sfsafaritoolbaritem"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem"},"kind":"symbol","abstract":[{"type":"text","text":"A proxy for a Safari app extension toolbar item in a Safari window."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFSafariToolbarItem"}]}]},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Your app extension only uses this object when it wants to explicitly set the toolbar item state. Typically, other state changes occur automatically. Safari calls "},{"type":"reference","identifier":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateToolbarItem(in:validationHandler:)","isActive":true},{"type":"text","text":" on your app extension handler when changes, such as navigation to a webpage, could affect the state of the toolbar item."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.safariservices/documentation/SafariServices"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"SFSafariToolbarItem","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SFSafariToolbarItem","modules":[{"name":"Safari Services"}],"navigatorTitle":[{"text":"SFSafariToolbarItem","kind":"identifier"}],"platforms":[{"name":"macOS","deprecated":false,"introducedAt":"10.12","unavailable":false,"beta":false}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SFSafariToolbarItem","kind":"identifier"}]},"references":{"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","url":"/documentation/Swift/CustomDebugStringConvertible","type":"topic","title":"CustomDebugStringConvertible","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"role":"symbol"},"doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateToolbarItem(in:validationHandler:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validateToolbarItemInWindow:validationHandler:"}],"title":"validateToolbarItem(in:validationHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validateToolbarItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SFSafariWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariWindow"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"text":"Determines if a toolbar menu item should be enabled or have badge text when browser state changes.","type":"text"}],"url":"/documentation/safariservices/sfsafariextensionhandling/validatetoolbaritem(in:validationhandler:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionHandling/validateToolbarItem(in:validationHandler:)"},"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setImage(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage"},{"kind":"text","text":"?)"}],"kind":"symbol","url":"/documentation/safariservices/sfsafaritoolbaritem/setimage(_:)","title":"setImage(_:)","navigatorTitle":[{"kind":"identifier","text":"setImage:"}],"type":"topic","role":"symbol","abstract":[{"text":"Sets the image displayed in the toolbar button.","type":"text"}],"identifier":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setImage(_:)"},"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setEnabled(_:withBadgeText:)":{"navigatorTitle":[{"kind":"identifier","text":"setEnabled:withBadgeText:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withBadgeText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"url":"/documentation/safariservices/sfsafaritoolbaritem/setenabled(_:withbadgetext:)","title":"setEnabled(_:withBadgeText:)","deprecated":true,"identifier":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setEnabled(_:withBadgeText:)","abstract":[{"type":"text","text":"Sets the enabled state and the badge text for the toolbar item."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/showPopover()":{"identifier":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/showPopover()","navigatorTitle":[{"text":"showPopover","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showPopover","kind":"identifier"},{"text":"()","kind":"text"}],"title":"showPopover()","url":"/documentation/safariservices/sfsafaritoolbaritem/showpopover()","type":"topic","abstract":[]},"doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-a-toolbar-item":{"abstract":[{"type":"text","text":"Customize a toolbar item for your Safari app extension."}],"role":"article","type":"topic","kind":"article","url":"/documentation/safariservices/adjusting-settings-for-a-toolbar-item","identifier":"doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-a-toolbar-item","title":"Adjusting settings for a toolbar item"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","role":"overview"},"doc://com.externally.resolved.symbol/s:SQ":{"url":"/documentation/Swift/Equatable","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SQ","title":"Equatable","role":"symbol","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Equatable"}],"kind":"symbol"},"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setBadgeText(_:)":{"abstract":[{"text":"Sets the badge text for the toolbar item.","type":"text"}],"url":"/documentation/safariservices/sfsafaritoolbaritem/setbadgetext(_:)","title":"setBadgeText(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setBadgeText"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"setBadgeText:","kind":"identifier"}],"identifier":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setBadgeText(_:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","url":"/documentation/objectivec/nsobject","type":"topic","title":"NSObject","kind":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSObject","kind":"identifier"}],"role":"symbol"},"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFSafariToolbarItem"}],"identifier":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem","abstract":[{"type":"text","text":"A proxy for a Safari app extension toolbar item in a Safari window."}],"navigatorTitle":[{"kind":"identifier","text":"SFSafariToolbarItem"}],"title":"SFSafariToolbarItem","type":"topic","role":"symbol","kind":"symbol","url":"/documentation/safariservices/sfsafaritoolbaritem"},"doc://com.apple.safariservices/documentation/SafariServices":{"kind":"symbol","identifier":"doc://com.apple.safariservices/documentation/SafariServices","abstract":[{"type":"text","text":"Enable web views and services in your app."}],"title":"Safari Services","url":"/documentation/safariservices","type":"topic","role":"collection"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","abstract":[{"type":"text","text":"A protocol that objects adopt to provide functional copies of themselves."}],"kind":"symbol","type":"topic","title":"NSCopying","role":"symbol","url":"/documentation/foundation/nscopying","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCopying"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","url":"/documentation/objectivec/nsobjectprotocol","type":"topic","title":"NSObjectProtocol","kind":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","abstract":[{"type":"text","text":"A protocol that enables an object to be encoded and decoded for archiving and distribution."}],"kind":"symbol","type":"topic","title":"NSCoding","role":"symbol","url":"/documentation/foundation/nscoding","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}]},"doc://com.externally.resolved.symbol/s:SH":{"title":"Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","url":"/documentation/Swift/Hashable","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"type":"topic"},"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setLabel(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setLabel:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLabel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"/documentation/safariservices/sfsafaritoolbaritem/setlabel(_:)","title":"setLabel(_:)","identifier":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setLabel(_:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setEnabled(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEnabled"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","url":"/documentation/safariservices/sfsafaritoolbaritem/setenabled(_:)","title":"setEnabled(_:)","navigatorTitle":[{"text":"setEnabled:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Sets whether the toolbar item is enabled."}],"identifier":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setEnabled(_:)"},"doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys":{"identifier":"doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys","abstract":[{"type":"text","text":"Learn about adding contextual menu items and toolbar items to a Safari app extension with information property list keys."}],"title":"Using contextual menu and toolbar item keys","type":"topic","role":"article","kind":"article","url":"/documentation/safariservices/using-contextual-menu-and-toolbar-item-keys"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","url":"/documentation/Swift/CustomStringConvertible","type":"topic","title":"CustomStringConvertible","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomStringConvertible"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","title":"CVarArg","role":"symbol","abstract":[{"text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CVarArg"}],"kind":"symbol"},"doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items":{"identifier":"doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items","abstract":[{"type":"text","text":"Customize contextual menu items for your Safari app extension."}],"title":"Adjusting settings for contextual menu items","type":"topic","role":"article","kind":"article","url":"/documentation/safariservices/adjusting-settings-for-contextual-menu-items"},"doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SFSafariExtensionViewController","kind":"identifier"}],"identifier":"doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionViewController","abstract":[{"text":"The view controller for a popover associated with your app extension.","type":"text"}],"navigatorTitle":[{"text":"SFSafariExtensionViewController","kind":"identifier"}],"title":"SFSafariExtensionViewController","type":"topic","role":"symbol","kind":"symbol","url":"/documentation/safariservices/sfsafariextensionviewcontroller"},"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding":{"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","abstract":[{"type":"text","text":"A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks."}],"kind":"symbol","type":"topic","title":"NSSecureCoding","role":"symbol","url":"/documentation/foundation/nssecurecoding","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSSecureCoding"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"10.12","deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"op":"replace"},{"op":"replace","path":"/metadata/roleHeading","value":"Class"},{"op":"replace","path":"/metadata/title","value":"SFSafariToolbarItem"},{"op":"replace","path":"/metadata/symbolKind","value":"class"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"SFSafariToolbarItem","kind":"identifier"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"SFSafariToolbarItem"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.safariservices/documentation/SafariServices"]]}},{"op":"replace","path":"/topicSections","value":[{"anchor":"Controlling-Toolbar-Items","title":"Controlling Toolbar Items","identifiers":["doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setEnabled(_:withBadgeText:)","doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setBadgeText(_:)","doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setEnabled(_:)","doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setImage(_:)","doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/setLabel(_:)"]},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc://com.apple.safariservices/documentation/SafariServices/SFSafariToolbarItem/showPopover()"]}]},{"op":"replace","path":"/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"]}]},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.safariservices/documentation/SafariServices/using-contextual-menu-and-toolbar-item-keys","doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-a-toolbar-item","doc://com.apple.safariservices/documentation/SafariServices/adjusting-settings-for-contextual-menu-items","doc://com.apple.safariservices/documentation/SafariServices/SFSafariExtensionViewController"],"anchor":"Contextual-menu-and-toolbar-items","title":"Contextual menu and toolbar items"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SFSafariToolbarItem","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["macOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1validateToolbarItem(in:validationHandler:)/title","value":"validateToolbarItemInWindow:validationHandler:"},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionHandling~1validateToolbarItem(in:validationHandler:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateToolbarItemInWindow:validationHandler:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1setImage(_:)/title","value":"setImage:"},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1setImage(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setImage:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1setEnabled(_:withBadgeText:)/title","value":"setEnabled:withBadgeText:"},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1setEnabled(_:withBadgeText:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEnabled:withBadgeText:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1showPopover()/title","value":"showPopover"},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1showPopover()/fragments","value":[{"text":"- ","kind":"text"},{"text":"showPopover","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1setBadgeText(_:)/title","value":"setBadgeText:"},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1setBadgeText(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setBadgeText:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem/title","value":"SFSafariToolbarItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem/fragments","value":[{"kind":"identifier","text":"SFSafariToolbarItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem/navigatorTitle","value":[{"kind":"identifier","text":"SFSafariToolbarItem"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject"},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1setLabel(_:)/title","value":"setLabel:"},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1setLabel(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setLabel:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1setEnabled(_:)/title","value":"setEnabled:"},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariToolbarItem~1setEnabled(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setEnabled:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionViewController/title","value":"SFSafariExtensionViewController"},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionViewController/fragments","value":[{"kind":"identifier","text":"SFSafariExtensionViewController"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariExtensionViewController/navigatorTitle","value":[{"text":"SFSafariExtensionViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}