{
  "abstract": [
    {
      "text": "Let users install your extension on one device and then use and manage the extension on all their other iOS and macOS devices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/syncing-safari-web-extensions-across-devices-and-platforms"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Syncing Safari web extensions across devices and platforms"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Safari 15 or earlier, when a user wants to install your Safari web extension on multiple devices, they have to install your extension from the App Store and enable the extension in Safari Preferences on each device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In Safari 16 and later, when a user installs your Safari web extension on one device, they can install your extension on another device directly from Safari Extensions Preferences, without visiting the App Store. When a user enables or disables your extension on one device, the system syncs that change to the user’s other devices that have the web extension installed. The user can disable syncing for a specific device. Syncing works for all Safari web extensions and content blockers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the following circumstances, extensions automatically sync with no configuration:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your extension only works in either macOS or iOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your extension uses the same bundle identifier in both macOS and iOS. This is the default for a new Safari web extension you create or convert in Xcode.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If your extension has different bundle identifiers in macOS and iOS, turn on syncing by configuring your Xcode project for both macOS and iOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you provide your extension in both iOS and macOS, consider selling them together as one product to improve the purchasing experience for your users. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/universal-purchase/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Configure-your-macOS-app-and-extension",
          "level": 3,
          "text": "Configure your macOS app and extension",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In your Xcode project, configure your macOS app to refer to your iOS app to support extension syncing:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the top project item in the Project navigator pane.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the target for your macOS app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Info tab.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSAppBundleIdentifier",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " key to the Custom macOS Application Target Properties section.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify the bundle identifier of your corresponding iOS app as the value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Next, configure your macOS extension for syncing:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the target for your macOS extension.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Info tab.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSExtensionBundleIdentifier",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " key to the Custom macOS Bundle Target Properties section.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify the bundle identifier of your corresponding iOS extension as the value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The bundle identifiers for the iOS app and extension you specify must be from the same developer account as your macOS app and extension.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Configure-your-iOS-app-and-extension",
          "level": 3,
          "text": "Configure your iOS app and extension",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In your Xcode project, configure your iOS app to refer to your macOS app to support extension syncing:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the top project item in the Project navigator pane.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the target for your iOS app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Info tab.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSAppBundleIdentifier",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " key to the Custom iOS Target Properties section.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify the bundle identifier of your corresponding macOS app as the value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Next, configure your iOS extension for syncing:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the target for your iOS extension.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Info tab.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSExtensionBundleIdentifier",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " key to the iOS Target Properties section.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify the bundle identifier of your corresponding macOS extension.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The bundle identifiers for the macOS app and extension you specify must be from the same developer account as your iOS app and extension.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSAppBundleIdentifier": {
      "abstract": [
        {
          "text": "A string bundle ID that identifies the corresponding iOS app that contains a content blocker or Safari web extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSAppBundleIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "SFSafariCorrespondingIOSAppBundleIdentifier",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSAppBundleIdentifier"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSExtensionBundleIdentifier": {
      "abstract": [
        {
          "text": "A string bundle ID that identifies the corresponding content blocker extension or Safari web extension on iOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSExtensionBundleIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "SFSafariCorrespondingIOSExtensionBundleIdentifier",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSExtensionBundleIdentifier"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSAppBundleIdentifier": {
      "abstract": [
        {
          "text": "A string bundle ID that identifies the corresponding macOS app that contains a content blocker or Safari web extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSAppBundleIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "SFSafariCorrespondingMacOSAppBundleIdentifier",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSAppBundleIdentifier"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSExtensionBundleIdentifier": {
      "abstract": [
        {
          "text": "A string bundle ID that identifies the corresponding content blocker extension or Safari web extension on macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSExtensionBundleIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "SFSafariCorrespondingMacOSExtensionBundleIdentifier",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSExtensionBundleIdentifier"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/adopting-new-safari-web-extension-apis": {
      "abstract": [
        {
          "text": "Improve your web extension in Safari with a non-persistent background page and new tab-override customization.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/adopting-new-safari-web-extension-apis",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adopting New Safari Web Extension APIs",
      "type": "topic",
      "url": "/documentation/safariservices/adopting-new-safari-web-extension-apis"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/assessing-your-safari-web-extension-s-browser-compatibility": {
      "abstract": [
        {
          "text": "Review your Safari web extension implementation plan, manifest keys, and JavaScript API usage for compatibility with other browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/assessing-your-safari-web-extension-s-browser-compatibility",
      "kind": "article",
      "role": "article",
      "title": "Assessing your Safari web extension’s browser compatibility",
      "type": "topic",
      "url": "/documentation/safariservices/assessing-your-safari-web-extension-s-browser-compatibility"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/optimizing-your-web-extension-for-safari": {
      "abstract": [
        {
          "text": "Support Dark Mode, reduce memory and power usage, and ensure feature compatibility to improve your web extension experience in Safari and web apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/optimizing-your-web-extension-for-safari",
      "kind": "article",
      "role": "article",
      "title": "Optimizing your web extension for Safari",
      "type": "topic",
      "url": "/documentation/safariservices/optimizing-your-web-extension-for-safari"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions": {
      "abstract": [
        {
          "text": "Create web extensions that work in Safari and other browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Safari web extensions",
      "type": "topic",
      "url": "/documentation/safariservices/safari-web-extensions"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/troubleshooting-your-safari-web-extension": {
      "abstract": [
        {
          "text": "Use developer resources to investigate and resolve common problems with Safari web extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/troubleshooting-your-safari-web-extension",
      "kind": "article",
      "role": "article",
      "title": "Troubleshooting your Safari web extension",
      "type": "topic",
      "url": "/documentation/safariservices/troubleshooting-your-safari-web-extension"
    },
    "https://developer.apple.com/support/universal-purchase/": {
      "identifier": "https://developer.apple.com/support/universal-purchase/",
      "title": "Offering Universal Purchase",
      "titleInlineContent": [
        {
          "text": "Offering Universal Purchase",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/universal-purchase/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Extension-improvements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/optimizing-your-web-extension-for-safari",
        "doc://com.apple.safariservices/documentation/SafariServices/adopting-new-safari-web-extension-apis",
        "doc://com.apple.safariservices/documentation/SafariServices/assessing-your-safari-web-extension-s-browser-compatibility",
        "doc://com.apple.safariservices/documentation/SafariServices/troubleshooting-your-safari-web-extension"
      ],
      "title": "Extension improvements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Extension-improvements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/optimizing-your-web-extension-for-safari",
                "doc://com.apple.safariservices/documentation/SafariServices/adopting-new-safari-web-extension-apis",
                "doc://com.apple.safariservices/documentation/SafariServices/assessing-your-safari-web-extension-s-browser-compatibility",
                "doc://com.apple.safariservices/documentation/SafariServices/troubleshooting-your-safari-web-extension"
              ],
              "title": "Extension improvements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/syncing-safari-web-extensions-across-devices-and-platforms"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/syncing-safari-web-extensions-across-devices-and-platforms"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
