{
  "abstract": [
    {
      "text": "Add new features and fix bugs in your Safari web extension using Xcode tools.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/updating-a-safari-web-extension"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Updating a Safari web extension"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Update your Safari web extension by editing the generated files in your Xcode project to fix bugs, or by adding new source files to create new features.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you prefer to use another editor for your source files, or if you want to preserve your existing development workflow for your converted web extension, edit your source files in an external source editor and use Xcode to update your extension in Safari.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Add new features with web extension APIs that work across browsers. For more information, see Mozilla’s ",
              "type": "text"
            },
            {
              "identifier": "https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " documentation. For more information about web extension API compatibility in Safari, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.safariservices/documentation/SafariServices/assessing-your-safari-web-extension-s-browser-compatibility",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Share-your-extension-in-Safari-in-iOS",
          "level": 3,
          "text": "Share your extension in Safari in iOS",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Safari supports web extensions in iOS 15 and later. To update your existing Xcode project with a macOS Safari web extension to support iOS, use the converter tool with the ",
              "type": "text"
            },
            {
              "code": "--rebuild-project",
              "type": "codeVoice"
            },
            {
              "text": " option. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.safariservices/documentation/SafariServices/converting-a-web-extension-for-safari#Add-iOS-to-your-existing-Xcode-project",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Edit-existing-files-in-Xcode",
          "level": 3,
          "text": "Edit existing files in Xcode",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While Xcode is primarily for native development, it has built-in support for editing web source-code documents, including HTML, CSS, JavaScript, and JSON. In the Xcode Project navigator, select and edit the files you want to customize.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/creating-organizing-and-editing-source-files",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Edit-existing-files-in-an-external-editor",
          "level": 3,
          "text": "Edit existing files in an external editor",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you have an existing development workflow for your web extension, you can use another source editor for your HTML, CSS, and JavaScript extension files in the Resources group. Your changes are visible in Xcode when you save changes to your files.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To see and test your web extension changes in Safari, you need Xcode to build and package your extension updates in the macOS containing app, or to build and deploy your iOS containing app to a simulator or device:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For macOS, build and package your extension from Xcode by choosing Product > Build from the menu.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For iOS, build and deploy your extension from Xcode by choosing Product > Run from the menu.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.safariservices/documentation/SafariServices/running-your-safari-web-extension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your alternative source editor supports custom build commands, configure it to use ",
              "type": "text"
            },
            {
              "code": "xcodebuild",
              "type": "codeVoice"
            },
            {
              "text": " from the command line to build your extension’s macOS app container.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "xcodebuild -scheme HelloWorld\\ \\(macOS\\) build"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Run the ",
              "type": "text"
            },
            {
              "code": "xcodebuild",
              "type": "codeVoice"
            },
            {
              "text": " command from the top directory of your Xcode project, and replace the ",
              "type": "text"
            },
            {
              "code": "-scheme",
              "type": "codeVoice"
            },
            {
              "text": " parameter with the name of your Xcode project.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-new-files-to-your-Safari-web-extension",
          "level": 3,
          "text": "Add new files to your Safari web extension",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Add new sources files for new features or to refactor existing features. To add a new source file to your web extension:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the Xcode Project navigator, select the Resources folder.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose File > New > File, or Control-click the folder and choose New File.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode presents a list of templates for new source files. To add a new HTML, CSS, JavaScript, or JSON file:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the iOS or macOS platform option from the top list of platform choices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Scroll down to the Other section and select the Empty option. Click Next.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Name the file using the appropriate file extension for the file type you’re creating, and then click Create.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To add an existing source file or image file from another directory, see the section titled “Add Existing Source Files to Your Project” in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/creating-organizing-and-editing-source-files",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "When you add new files, make sure that you add the files to the correct target. A Safari web extension has two targets per platform: an app for that platform, and the Safari web extension for that platform. If you want your files included in your Safari web extension, add them to both extension targets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Xcode/creating-organizing-and-editing-source-files": {
      "abstract": [
        {
          "text": "Edit source files in Xcode and add Quick Help comments to improve your project’s maintainability.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/creating-organizing-and-editing-source-files",
      "kind": "article",
      "role": "article",
      "title": "Editing source files in Xcode",
      "type": "topic",
      "url": "/documentation/Xcode/creating-organizing-and-editing-source-files"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/assessing-your-safari-web-extension-s-browser-compatibility": {
      "abstract": [
        {
          "text": "Review your Safari web extension implementation plan, manifest keys, and JavaScript API usage for compatibility with other browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/assessing-your-safari-web-extension-s-browser-compatibility",
      "kind": "article",
      "role": "article",
      "title": "Assessing your Safari web extension’s browser compatibility",
      "type": "topic",
      "url": "/documentation/safariservices/assessing-your-safari-web-extension-s-browser-compatibility"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/converting-a-web-extension-for-safari#Add-iOS-to-your-existing-Xcode-project": {
      "abstract": [],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/converting-a-web-extension-for-safari#Add-iOS-to-your-existing-Xcode-project",
      "kind": "section",
      "title": "Add iOS to your existing Xcode project",
      "type": "topic",
      "url": "/documentation/safariservices/converting-a-web-extension-for-safari#Add-iOS-to-your-existing-Xcode-project"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/managing-safari-web-extension-permissions": {
      "abstract": [
        {
          "text": "Respect user privacy by setting appropriate permissions for your Safari web extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/managing-safari-web-extension-permissions",
      "kind": "article",
      "role": "article",
      "title": "Managing Safari web extension permissions",
      "type": "topic",
      "url": "/documentation/safariservices/managing-safari-web-extension-permissions"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/previewing-metadata-using-open-graph": {
      "abstract": [
        {
          "text": "Build a Safari Extension that displays metadata using Open Graph.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/previewing-metadata-using-open-graph",
      "kind": "article",
      "role": "sampleCode",
      "title": "Previewing Metadata using Open Graph",
      "type": "topic",
      "url": "/documentation/safariservices/previewing-metadata-using-open-graph"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/running-your-safari-web-extension": {
      "abstract": [
        {
          "text": "Install and update your extension in Safari as you make changes in development.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/running-your-safari-web-extension",
      "kind": "article",
      "role": "article",
      "title": "Running your Safari web extension",
      "type": "topic",
      "url": "/documentation/safariservices/running-your-safari-web-extension"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions": {
      "abstract": [
        {
          "text": "Create web extensions that work in Safari and other browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/safari-web-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Safari web extensions",
      "type": "topic",
      "url": "/documentation/safariservices/safari-web-extensions"
    },
    "https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions": {
      "identifier": "https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions",
      "title": "Browser Extensions",
      "titleInlineContent": [
        {
          "text": "Browser Extensions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Extension-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/managing-safari-web-extension-permissions",
        "doc://com.apple.safariservices/documentation/SafariServices/previewing-metadata-using-open-graph"
      ],
      "title": "Extension updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Extension-updates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/managing-safari-web-extension-permissions",
                "doc://com.apple.safariservices/documentation/SafariServices/previewing-metadata-using-open-graph"
              ],
              "title": "Extension updates"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/updating-a-safari-web-extension"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/updating-a-safari-web-extension"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
