{"metadata":{"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlStateDisabled","kind":"identifier"}],"modules":[{"name":"UIKit"}],"roleHeading":"Type Property","title":"disabled","externalID":"c:@E@UIControlState@UIControlStateDisabled","platforms":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false}],"role":"symbol"},"abstract":[{"text":"The disabled state of a control.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved"],"anchor":"Constants","title":"Constants","generated":true}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIControl","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","kind":"typeIdentifier","text":"UIControl"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIControlState","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","kind":"typeIdentifier","text":"State"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"User interactions with disabled control have no effect and the control draws itself with a dimmed appearance to reflect that it’s disabled. You can retrieve and set this value through the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/isEnabled","isActive":true},{"type":"text","text":" property."}]}]}],"variants":[{"paths":["/documentation/uikit/uicontrol/state-swift.struct/disabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uicontrol/state-swift.struct/disabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/isEnabled":{"navigatorTitle":[{"kind":"identifier","text":"enabled"}],"title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/isEnabled","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/isenabled","abstract":[{"type":"text","text":"A Boolean value indicating whether the control is in the enabled state."}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled":{"abstract":[{"text":"The disabled state of a control.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled","kind":"symbol","url":"/documentation/uikit/uicontrol/state-swift.struct/disabled","title":"disabled","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState"}],"type":"topic","navigatorTitle":[{"text":"UIControlStateDisabled","kind":"identifier"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl":{"navigatorTitle":[{"text":"UIControl","kind":"identifier"}],"title":"UIControl","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControl","kind":"identifier"}],"abstract":[{"type":"text","text":"The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions."}],"url":"/documentation/uikit/uicontrol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application":{"type":"topic","title":"application","abstract":[{"type":"text","text":"Additional control-state flags available for app use."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/application","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIControlStateApplication"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved":{"type":"topic","title":"reserved","abstract":[{"type":"text","text":"Control-state flags reserved for internal framework use."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/reserved","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reserved"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIControlStateReserved"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal":{"title":"normal","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState","text":"State"}],"navigatorTitle":[{"kind":"identifier","text":"UIControlStateNormal"}],"url":"/documentation/uikit/uicontrol/state-swift.struct/normal","abstract":[{"type":"text","text":"The normal, or default, state of a control where the control is enabled but neither selected nor highlighted."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted":{"type":"topic","title":"highlighted","abstract":[{"type":"text","text":"The highlighted state of a control."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/highlighted","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIControlStateHighlighted"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused":{"type":"topic","title":"focused","abstract":[{"type":"text","text":"The focused state of a control."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/focused","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"UIControlStateFocused","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"State"}],"title":"UIControl.State","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/state-swift.struct","abstract":[{"type":"text","text":"Constants describing the state of a control."}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected":{"type":"topic","url":"/documentation/uikit/uicontrol/state-swift.struct/selected","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected","kind":"symbol","navigatorTitle":[{"text":"UIControlStateSelected","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"}],"title":"selected","abstract":[{"type":"text","text":"The selected state of a control."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Enumeration Case","path":"/metadata/roleHeading"},{"op":"replace","value":"UIControlStateDisabled","path":"/metadata/title"},{"op":"replace","value":"case","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlStateDisabled"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved"],"anchor":"Constants"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"UIControlStateDisabled","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"enabled","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isEnabled/title"},{"value":[{"kind":"identifier","text":"enabled"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1isEnabled/fragments","op":"replace"},{"value":"UIControlStateDisabled","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1disabled/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIControlStateDisabled"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1disabled/fragments","op":"replace"},{"value":"UIControl","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title","op":"replace"},{"value":[{"text":"UIControl","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UIControl"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle","op":"replace"},{"value":"UIControlStateApplication","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1application/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIControlStateApplication"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1application/fragments","op":"replace"},{"value":"UIControlStateReserved","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1reserved/title","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1reserved/fragments","value":[{"text":"UIControlStateReserved","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1normal/title","value":"UIControlStateNormal"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1normal/fragments","value":[{"kind":"identifier","text":"UIControlStateNormal"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1highlighted/title","value":"UIControlStateHighlighted"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1highlighted/fragments","value":[{"kind":"identifier","text":"UIControlStateHighlighted"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1focused/title","value":"UIControlStateFocused"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1focused/fragments","value":[{"text":"UIControlStateFocused","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/title","value":"UIControlState"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/fragments","value":[{"kind":"identifier","text":"UIControlState"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/navigatorTitle","value":[{"kind":"identifier","text":"UIControlState"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1selected/title","value":"UIControlStateSelected"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1selected/fragments","value":[{"kind":"identifier","text":"UIControlStateSelected"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}