{"sections":[],"metadata":{"title":"focused","roleHeading":"Type Property","platforms":[{"unavailable":false,"introducedAt":"9.0","beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"introducedAt":"9.0","beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"13.1","beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"9.0","beta":false,"deprecated":false,"name":"tvOS"},{"unavailable":false,"introducedAt":"1.0","beta":false,"deprecated":false,"name":"visionOS"}],"modules":[{"name":"UIKit"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"focused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"navigatorTitle":[{"text":"UIControlStateFocused","kind":"identifier"}],"role":"symbol","externalID":"c:@E@UIControlState@UIControlStateFocused","symbolKind":"property"},"abstract":[{"type":"text","text":"The focused state of a control."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focused","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"inlineContent":[{"text":"In focus-based navigation systems, a control enters this state when it receives the focus. A focused control changes its appearance to indicate that it has focus, and this appearance differs from the appearance of the control when it’s highlighted or selected. Further interactions with the control can result in it also becoming highlighted or selected.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct"]]},"variants":[{"paths":["/documentation/uikit/uicontrol/state-swift.struct/focused"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uicontrol/state-swift.struct/focused"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIControl":{"navigatorTitle":[{"text":"UIControl","kind":"identifier"}],"title":"UIControl","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControl","kind":"identifier"}],"abstract":[{"type":"text","text":"The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions."}],"url":"/documentation/uikit/uicontrol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved":{"type":"topic","title":"reserved","abstract":[{"type":"text","text":"Control-state flags reserved for internal framework use."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/reserved","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reserved"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIControlStateReserved"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted":{"type":"topic","title":"highlighted","abstract":[{"type":"text","text":"The highlighted state of a control."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/highlighted","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIControlStateHighlighted"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected":{"type":"topic","url":"/documentation/uikit/uicontrol/state-swift.struct/selected","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected","kind":"symbol","navigatorTitle":[{"text":"UIControlStateSelected","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"}],"title":"selected","abstract":[{"type":"text","text":"The selected state of a control."}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"State"}],"title":"UIControl.State","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/state-swift.struct","abstract":[{"type":"text","text":"Constants describing the state of a control."}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application":{"type":"topic","title":"application","abstract":[{"type":"text","text":"Additional control-state flags available for app use."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/application","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIControlStateApplication"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled":{"abstract":[{"text":"The disabled state of a control.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled","kind":"symbol","url":"/documentation/uikit/uicontrol/state-swift.struct/disabled","title":"disabled","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState"}],"type":"topic","navigatorTitle":[{"text":"UIControlStateDisabled","kind":"identifier"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal":{"title":"normal","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier","text":"UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState","text":"State"}],"navigatorTitle":[{"kind":"identifier","text":"UIControlStateNormal"}],"url":"/documentation/uikit/uicontrol/state-swift.struct/normal","abstract":[{"type":"text","text":"The normal, or default, state of a control where the control is enabled but neither selected nor highlighted."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused":{"type":"topic","title":"focused","abstract":[{"type":"text","text":"The focused state of a control."}],"url":"/documentation/uikit/uicontrol/state-swift.struct/focused","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"UIControlStateFocused","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/focused"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"9.0"},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"9.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.1"},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false,"introducedAt":"9.0"},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Enumeration Case","path":"/metadata/roleHeading"},{"op":"replace","value":"UIControlStateFocused","path":"/metadata/title"},{"op":"replace","value":"case","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"UIControlStateFocused"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/highlighted","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/selected","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/application","doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/reserved"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"UIControlStateFocused","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title","value":"UIControl"},{"value":[{"kind":"identifier","text":"UIControl"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments"},{"value":[{"kind":"identifier","text":"UIControl"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle"},{"value":"UIControlStateReserved","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1reserved/title"},{"value":[{"kind":"identifier","text":"UIControlStateReserved"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1reserved/fragments"},{"value":"UIControlStateHighlighted","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1highlighted/title"},{"value":[{"text":"UIControlStateHighlighted","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1highlighted/fragments"},{"value":"UIControlStateSelected","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1selected/title"},{"value":[{"kind":"identifier","text":"UIControlStateSelected"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1selected/fragments"},{"value":"UIControlState","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/title"},{"value":[{"kind":"identifier","text":"UIControlState"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/fragments"},{"value":[{"text":"UIControlState","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/navigatorTitle"},{"value":"UIControlStateApplication","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1application/title"},{"value":[{"text":"UIControlStateApplication","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1application/fragments"},{"value":"UIControlStateDisabled","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1disabled/title"},{"value":[{"kind":"identifier","text":"UIControlStateDisabled"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1disabled/fragments"},{"value":"UIControlStateNormal","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1normal/title"},{"value":[{"text":"UIControlStateNormal","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1normal/fragments"},{"value":"UIControlStateFocused","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1focused/title"},{"value":[{"text":"UIControlStateFocused","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1focused/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}