{
  "abstract": [
    {
      "text": "An output texture that supports the correct depth texture usage options.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalfx/documentation/MetalFX",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTexture"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLFXSpatialScaler(py)outputTexture",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "outputTexture"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MTLTexture",
        "text": "MTLTexture"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "MetalFX"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "outputTexture"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "outputTexture"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "outputTexture"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLTexture",
              "text": "MTLTexture"
            },
            {
              "kind": "text",
              "text": ")? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The texture you set to this property must meet the following requirements:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The texture’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLResource/storageMode",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLStorageMode/private",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The texture’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTexture/usage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property uses ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureUsage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTextureUsage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " options as a minimum, and can use additional options.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The texture’s dimensions is equal to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputWidth",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputHeight",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Metal/MTLResource/storageMode": {
      "abstract": [
        {
          "text": "The location and access permissions of the resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storageMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStorageMode",
          "text": "MTLStorageMode"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLResource/storageMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "storageMode",
      "type": "topic",
      "url": "/documentation/Metal/MTLResource/storageMode"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLStorageMode/private": {
      "abstract": [
        {
          "text": "The resource is only available to the GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`private`"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLStorageMode/private",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLStorageMode.private",
      "type": "topic",
      "url": "/documentation/Metal/MTLStorageMode/private"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLTexture/usage": {
      "abstract": [
        {
          "text": "Options that determine how you can use the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTexture/usage",
      "kind": "symbol",
      "role": "symbol",
      "title": "usage",
      "type": "topic",
      "url": "/documentation/Metal/MTLTexture/usage"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLTextureUsage": {
      "abstract": [
        {
          "text": "An enumeration for the various options that determine how you can use a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTextureUsage",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLTextureUsage",
      "type": "topic",
      "url": "/documentation/Metal/MTLTextureUsage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalfx/documentation/MetalFX": {
      "abstract": [
        {
          "text": "Boost your Metal app’s performance by upscaling lower-resolution content to save GPU time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalFX",
      "type": "topic",
      "url": "/documentation/metalfx"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler": {
      "abstract": [
        {
          "text": "An upscaling effect that generates a higher resolution texture in a render pass by spatially analyzing an input texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScaler"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXSpatialScaler"
        }
      ],
      "role": "symbol",
      "title": "MTLFXSpatialScaler",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureUsage": {
      "abstract": [
        {
          "text": "The minimal texture usage options that your app’s input color texture must set to apply the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorTextureUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/colorTextureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorTextureUsage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorTextureUsage",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/colortextureusage"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputHeight": {
      "abstract": [
        {
          "text": "The height, in pixels, of the output color texture for the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputHeight"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputHeight",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/outputheight"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTexture": {
      "abstract": [
        {
          "text": "An output texture that supports the correct depth texture usage options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/outputtexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureUsage": {
      "abstract": [
        {
          "text": "The minimal texture usage options that your app’s output texture must set to apply the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputTextureUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputTextureUsage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputTextureUsage",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/outputtextureusage"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputWidth": {
      "abstract": [
        {
          "text": "The width, in pixels, of the output color texture for the spatial scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputWidth"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outputWidth",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxspatialscaler/outputwidth"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture": {
      "abstract": [
        {
          "text": "A resource that holds formatted image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLResource",
          "text": "MTLResource"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLTexture",
      "type": "topic",
      "url": "/documentation/Metal/MTLTexture"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-image-output",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureUsage"
      ],
      "title": "Configuring the image output"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "outputTexture"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalfx/documentation/MetalFX",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-image-output",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXSpatialScaler/outputTextureUsage"
              ],
              "title": "Configuring the image output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "retain"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)MTLTexture",
                    "text": "id<MTLTexture>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "outputTexture"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLTexture~1usage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLTextureUsage",
              "text": "MTLTextureUsage"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "usage"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1colorTextureUsage/title",
          "value": "colorTextureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1colorTextureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorTextureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLResource~1storageMode/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLStorageMode",
              "text": "MTLStorageMode"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "storageMode"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLTextureUsage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLTextureUsage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler/title",
          "value": "MTLFXSpatialScaler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXSpatialScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)MTLTexture/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLTexture"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLResource",
              "text": "MTLResource"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputTexture/title",
          "value": "outputTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputTextureUsage/title",
          "value": "outputTextureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputTextureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTextureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLStorageMode~1private/title",
          "value": "MTLStorageModePrivate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLStorageMode~1private/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStorageModePrivate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputHeight/title",
          "value": "outputHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputWidth/title",
          "value": "outputWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXSpatialScaler~1outputWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputWidth"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalfx/mtlfxspatialscaler/outputtexture"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalfx/mtlfxspatialscaler/outputtexture"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
