{
  "abstract": [
    {
      "text": "An object set to the most permissive sharing options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/standard"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CKAllowedSharingOptions(cpy)standardOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "standard"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKAllowedSharingOptions",
        "text": "CKAllowedSharingOptions"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "standardOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "standard"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "standard"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKAllowedSharingOptions",
              "text": "CKAllowedSharingOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "standardOptions",
              "type": "codeVoice"
            },
            {
              "text": " has ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantPermissionOptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " set to ",
              "type": "text"
            },
            {
              "code": "CKSharingParticipantPermissionOptionAny",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantAccessOptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " set to ",
              "type": "text"
            },
            {
              "code": "CKSharingParticipantAccessOptionAny",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions": {
      "abstract": [
        {
          "text": "An object that controls participant access and permission options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "role": "symbol",
      "title": "CKAllowedSharingOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantAccessOptions": {
      "abstract": [
        {
          "text": "The permission option the system uses to control whether a user can share publicly or privately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedParticipantAccessOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKSharingParticipantAccessOption",
          "text": "CKSharingParticipantAccessOption"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantAccessOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowedParticipantAccessOptions"
        }
      ],
      "role": "symbol",
      "title": "allowedParticipantAccessOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions/allowedparticipantaccessoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantPermissionOptions": {
      "abstract": [
        {
          "text": "The permission option the system uses to control whether a user can grant read-only or write access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedParticipantPermissionOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKSharingParticipantPermissionOption",
          "text": "CKSharingParticipantPermissionOption"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantPermissionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowedParticipantPermissionOptions"
        }
      ],
      "role": "symbol",
      "title": "allowedParticipantPermissionOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions/allowedparticipantpermissionoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/standard": {
      "abstract": [
        {
          "text": "An object set to the most permissive sharing options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKAllowedSharingOptions",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "standardOptions"
        }
      ],
      "role": "symbol",
      "title": "standard",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions/standard"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "standardOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "standardOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CKAllowedSharingOptions",
                    "text": "CKAllowedSharingOptions"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "standardOptions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/title",
          "value": "CKAllowedSharingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1allowedParticipantPermissionOptions/title",
          "value": "allowedParticipantPermissionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1allowedParticipantPermissionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedParticipantPermissionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1allowedParticipantAccessOptions/title",
          "value": "allowedParticipantAccessOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1allowedParticipantAccessOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedParticipantAccessOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1standard/title",
          "value": "standardOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "standardOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckallowedsharingoptions/standard"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckallowedsharingoptions/standard"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
