{
  "abstract": [
    {
      "text": "The presentation style for the view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.GroupActivities/documentation/GroupActivities",
        "doc://com.apple.GroupActivities/documentation/GroupActivities/GroupActivitySharingController-ybcy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.GroupActivities/documentation/GroupActivities/GroupActivitySharingController-ybcy/modalPresentationStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@M@_GroupActivities_UIKit@objc(cs)GroupActivitySharingController(py)modalPresentationStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "modalPresentationStyle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIModalPresentationStyle",
        "text": "UIModalPresentationStyle"
      }
    ],
    "modules": [
      {
        "name": "GroupActivities",
        "relatedModules": [
          "UIKit"
        ]
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "modalPresentationStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "override"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "dynamic"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "modalPresentationStyle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@UIModalPresentationStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIModalPresentationStyle",
              "text": "UIModalPresentationStyle"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property always sets the presentation style",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for the view controller to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIModalPresentationStyle/pageSheet",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.GroupActivities/documentation/GroupActivities": {
      "abstract": [
        {
          "text": "Create app-specific activities your users can share and experience together.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.GroupActivities/documentation/GroupActivities",
      "kind": "symbol",
      "role": "collection",
      "title": "Group Activities",
      "type": "topic",
      "url": "/documentation/groupactivities"
    },
    "doc://com.apple.GroupActivities/documentation/GroupActivities/GroupActivitySharingController-ybcy": {
      "abstract": [
        {
          "text": "An iOS view controller that displays the system interface for starting an",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "activity, and optionally starts a FaceTime call for that activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GroupActivitySharingController"
        }
      ],
      "identifier": "doc://com.apple.GroupActivities/documentation/GroupActivities/GroupActivitySharingController-ybcy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GroupActivitySharingController"
        }
      ],
      "role": "symbol",
      "title": "GroupActivitySharingController",
      "type": "topic",
      "url": "/documentation/groupactivities/groupactivitysharingcontroller-ybcy"
    },
    "doc://com.apple.GroupActivities/documentation/GroupActivities/GroupActivitySharingController-ybcy/modalPresentationStyle": {
      "abstract": [
        {
          "text": "The presentation style for the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modalPresentationStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIModalPresentationStyle",
          "text": "UIModalPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.GroupActivities/documentation/GroupActivities/GroupActivitySharingController-ybcy/modalPresentationStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "modalPresentationStyle",
      "type": "topic",
      "url": "/documentation/groupactivities/groupactivitysharingcontroller-ybcy/modalpresentationstyle"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIModalPresentationStyle/pageSheet": {
      "abstract": [
        {
          "text": "A presentation style that partially covers the underlying content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageSheet"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIModalPresentationStyle/pageSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIModalPresentationStyle.pageSheet",
      "type": "topic",
      "url": "/documentation/UIKit/UIModalPresentationStyle/pageSheet"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@UIModalPresentationStyle": {
      "abstract": [
        {
          "text": "Modal presentation styles available when presenting view controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIModalPresentationStyle"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@UIModalPresentationStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIModalPresentationStyle",
      "type": "topic",
      "url": "/documentation/UIKit/UIModalPresentationStyle"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@UIModalPresentationStyle/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIModalPresentationStyle"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIModalPresentationStyle~1pageSheet/title",
          "value": "UIModalPresentationPageSheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIModalPresentationStyle~1pageSheet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationPageSheet"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/groupactivities/groupactivitysharingcontroller-ybcy/modalpresentationstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
