{
  "abstract": [
    {
      "text": "The usage time of apps per category.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SRDeviceUsageReport(py)applicationUsageByCategory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "applicationUsageByCategory"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
        "text": "SRDeviceUsageReport"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
        "text": "CategoryKey"
      },
      {
        "kind": "text",
        "text": " : ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
        "text": "SRDeviceUsageReport"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRApplicationUsage",
        "text": "ApplicationUsage"
      },
      {
        "kind": "text",
        "text": "]]"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "applicationUsageByCategory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "applicationUsageByCategory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "applicationUsageByCategory"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
              "text": "SRDeviceUsageReport"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
              "text": "CategoryKey"
            },
            {
              "kind": "text",
              "text": " : ["
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
              "text": "SRDeviceUsageReport"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRApplicationUsage",
              "text": "ApplicationUsage"
            },
            {
              "kind": "text",
              "text": "]] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The framework interprets the category using the primary genre an app supplies in its ",
              "type": "text"
            },
            {
              "code": "iTunesMetadata.plist",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport": {
      "abstract": [
        {
          "text": "The frequency and relative duration that the user uses their device, particular Apple apps, or websites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage": {
      "abstract": [
        {
          "text": "An object that describes the user’s app activity over a period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ApplicationUsage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ApplicationUsage"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport.ApplicationUsage",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/applicationusage"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey": {
      "abstract": [
        {
          "text": "Categories of apps or websites that the user uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CategoryKey"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport.CategoryKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory": {
      "abstract": [
        {
          "text": "The usage time of apps per category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationUsageByCategory"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        },
        {
          "kind": "text",
          "text": " : ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRApplicationUsage",
          "text": "ApplicationUsage"
        },
        {
          "kind": "text",
          "text": "]]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationUsageByCategory"
        }
      ],
      "role": "symbol",
      "title": "applicationUsageByCategory",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/applicationusagebycategory"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Analyzing-App-Use",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey"
      ],
      "title": "Analyzing App Use"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "applicationUsageByCategory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationUsageByCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Analyzing-App-Use",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey"
              ],
              "title": "Analyzing App Use"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
                    "text": "NSDictionary<NSString *,NSArray<SRApplicationUsage *> *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "applicationUsageByCategory"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/title",
          "value": "SRDeviceUsageCategoryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/title",
          "value": "SRDeviceUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1applicationUsageByCategory/title",
          "value": "applicationUsageByCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1applicationUsageByCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationUsageByCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/title",
          "value": "SRApplicationUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRApplicationUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRApplicationUsage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srdeviceusagereport/applicationusagebycategory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srdeviceusagereport/applicationusagebycategory"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
