{
  "abstract": [
    {
      "text": "Categories of apps or websites that the user uses.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SensorKit",
    "externalID": "c:@T@SRDeviceUsageCategoryKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CategoryKey"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CategoryKey"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SRDeviceUsageReport.CategoryKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CategoryKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport": {
      "abstract": [
        {
          "text": "The frequency and relative duration that the user uses their device, particular Apple apps, or websites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage": {
      "abstract": [
        {
          "text": "An object that describes the user’s app activity over a period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ApplicationUsage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ApplicationUsage"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport.ApplicationUsage",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/applicationusage"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey": {
      "abstract": [
        {
          "text": "Categories of apps or websites that the user uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CategoryKey"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport.CategoryKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/books": {
      "abstract": [
        {
          "text": "An app category for reading books.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "books"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/books",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryBooks"
        }
      ],
      "role": "symbol",
      "title": "books",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/books"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/business": {
      "abstract": [
        {
          "text": "An app category for doing business.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "business"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/business",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryBusiness"
        }
      ],
      "role": "symbol",
      "title": "business",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/business"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/catalogs": {
      "abstract": [
        {
          "text": "An app category for reading catalogs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "catalogs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/catalogs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryCatalogs"
        }
      ],
      "role": "symbol",
      "title": "catalogs",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/catalogs"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/developerTools": {
      "abstract": [
        {
          "text": "An app category for creating apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "developerTools"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/developerTools",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryDeveloperTools"
        }
      ],
      "role": "symbol",
      "title": "developerTools",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/developertools"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/education": {
      "abstract": [
        {
          "text": "An app category for learning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "education"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/education",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryEducation"
        }
      ],
      "role": "symbol",
      "title": "education",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/education"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/entertainment": {
      "abstract": [
        {
          "text": "An app category for entertainment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entertainment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/entertainment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryEntertainment"
        }
      ],
      "role": "symbol",
      "title": "entertainment",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/entertainment"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/finance": {
      "abstract": [
        {
          "text": "An app category for finance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/finance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryFinance"
        }
      ],
      "role": "symbol",
      "title": "finance",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/finance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/foodAndDrink": {
      "abstract": [
        {
          "text": "An app category for dining.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foodAndDrink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/foodAndDrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryFoodAndDrink"
        }
      ],
      "role": "symbol",
      "title": "foodAndDrink",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/foodanddrink"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/games": {
      "abstract": [
        {
          "text": "An app category for gaming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "games"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/games",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryGames"
        }
      ],
      "role": "symbol",
      "title": "games",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/games"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/graphicsAndDesign": {
      "abstract": [
        {
          "text": "An app category for graphic design.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicsAndDesign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/graphicsAndDesign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryGraphicsAndDesign"
        }
      ],
      "role": "symbol",
      "title": "graphicsAndDesign",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/graphicsanddesign"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/healthAndFitness": {
      "abstract": [
        {
          "text": "An app category for health and fitness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "healthAndFitness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/healthAndFitness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryHealthAndFitness"
        }
      ],
      "role": "symbol",
      "title": "healthAndFitness",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/healthandfitness"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/init(rawvalue:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/kids": {
      "abstract": [
        {
          "text": "An app category for children.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kids"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/kids",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryKids"
        }
      ],
      "role": "symbol",
      "title": "kids",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/kids"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/lifestyle": {
      "abstract": [
        {
          "text": "An app category for lifestyle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lifestyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/lifestyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryLifestyle"
        }
      ],
      "role": "symbol",
      "title": "lifestyle",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/lifestyle"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/medical": {
      "abstract": [
        {
          "text": "An app category for healthcare.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/medical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryMedical"
        }
      ],
      "role": "symbol",
      "title": "medical",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/medical"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/miscellaneous": {
      "abstract": [
        {
          "text": "An app category for miscellaneous apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miscellaneous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/miscellaneous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryMiscellaneous"
        }
      ],
      "role": "symbol",
      "title": "miscellaneous",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/miscellaneous"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/music": {
      "abstract": [
        {
          "text": "An app category for music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "music"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/music",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryMusic"
        }
      ],
      "role": "symbol",
      "title": "music",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/music"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/navigation": {
      "abstract": [
        {
          "text": "An app category for navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/navigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryNavigation"
        }
      ],
      "role": "symbol",
      "title": "navigation",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/navigation"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/news": {
      "abstract": [
        {
          "text": "An app category for news.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "news"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/news",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryNews"
        }
      ],
      "role": "symbol",
      "title": "news",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/news"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/newsstand": {
      "abstract": [
        {
          "text": "An app category for Apple News.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newsstand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/newsstand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryNewsstand"
        }
      ],
      "role": "symbol",
      "title": "newsstand",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/newsstand"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/photoAndVideo": {
      "abstract": [
        {
          "text": "An app category for photography and film.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoAndVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/photoAndVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryPhotoAndVideo"
        }
      ],
      "role": "symbol",
      "title": "photoAndVideo",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/photoandvideo"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/productivity": {
      "abstract": [
        {
          "text": "An app category for productivity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/productivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryProductivity"
        }
      ],
      "role": "symbol",
      "title": "productivity",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/productivity"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/reference": {
      "abstract": [
        {
          "text": "An app category for reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/reference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryReference"
        }
      ],
      "role": "symbol",
      "title": "reference",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/reference"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/shopping": {
      "abstract": [
        {
          "text": "An app category for shopping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shopping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/shopping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryShopping"
        }
      ],
      "role": "symbol",
      "title": "shopping",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/shopping"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/socialNetworking": {
      "abstract": [
        {
          "text": "An app category for social networking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "socialNetworking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/socialNetworking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategorySocialNetworking"
        }
      ],
      "role": "symbol",
      "title": "socialNetworking",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/socialnetworking"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/sports": {
      "abstract": [
        {
          "text": "An app category for sports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sports"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/sports",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategorySports"
        }
      ],
      "role": "symbol",
      "title": "sports",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/sports"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/stickers": {
      "abstract": [
        {
          "text": "An app category for stickers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stickers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/stickers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryStickers"
        }
      ],
      "role": "symbol",
      "title": "stickers",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/stickers"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/travel": {
      "abstract": [
        {
          "text": "An app category for travel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "travel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/travel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryTravel"
        }
      ],
      "role": "symbol",
      "title": "travel",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/travel"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/utilities": {
      "abstract": [
        {
          "text": "An app category for utilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "utilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/utilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryUtilities"
        }
      ],
      "role": "symbol",
      "title": "utilities",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/utilities"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/weather": {
      "abstract": [
        {
          "text": "An app category for weather.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weather"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/weather",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryWeather"
        }
      ],
      "role": "symbol",
      "title": "weather",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/weather"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory": {
      "abstract": [
        {
          "text": "The usage time of apps per category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationUsageByCategory"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        },
        {
          "kind": "text",
          "text": " : ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRApplicationUsage",
          "text": "ApplicationUsage"
        },
        {
          "kind": "text",
          "text": "]]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationUsageByCategory"
        }
      ],
      "role": "symbol",
      "title": "applicationUsageByCategory",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/applicationusagebycategory"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Analyzing-App-Use",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage"
      ],
      "title": "Analyzing App Use"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Categories",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/books",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/business",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/catalogs",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/developerTools",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/education",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/entertainment",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/finance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/foodAndDrink",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/games",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/graphicsAndDesign",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/healthAndFitness",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/kids",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/lifestyle",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/medical",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/miscellaneous",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/music",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/navigation",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/news",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/newsstand",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/photoAndVideo",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/productivity",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/reference",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/shopping",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/socialNetworking",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/sports",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/stickers",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/travel",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/utilities",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/weather"
      ],
      "title": "Categories"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRDeviceUsageCategoryKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Categories",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/books",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/business",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/catalogs",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/developerTools",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/education",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/entertainment",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/finance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/foodAndDrink",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/games",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/graphicsAndDesign",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/healthAndFitness",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/kids",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/lifestyle",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/medical",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/miscellaneous",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/music",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/navigation",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/news",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/newsstand",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/photoAndVideo",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/productivity",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/reference",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/shopping",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/socialNetworking",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/sports",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/stickers",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/travel",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/utilities",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/weather"
              ],
              "title": "Categories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Analyzing-App-Use",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage"
              ],
              "title": "Analyzing App Use"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "SRDeviceUsageCategoryKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1business/title",
          "value": "SRDeviceUsageCategoryBusiness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1business/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryBusiness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1socialNetworking/title",
          "value": "SRDeviceUsageCategorySocialNetworking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1socialNetworking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategorySocialNetworking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1navigation/title",
          "value": "SRDeviceUsageCategoryNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1navigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1education/title",
          "value": "SRDeviceUsageCategoryEducation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1education/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryEducation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1foodAndDrink/title",
          "value": "SRDeviceUsageCategoryFoodAndDrink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1foodAndDrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryFoodAndDrink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1catalogs/title",
          "value": "SRDeviceUsageCategoryCatalogs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1catalogs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryCatalogs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/title",
          "value": "SRDeviceUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1miscellaneous/title",
          "value": "SRDeviceUsageCategoryMiscellaneous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1miscellaneous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryMiscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1productivity/title",
          "value": "SRDeviceUsageCategoryProductivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1productivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryProductivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1travel/title",
          "value": "SRDeviceUsageCategoryTravel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1travel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryTravel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1graphicsAndDesign/title",
          "value": "SRDeviceUsageCategoryGraphicsAndDesign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1graphicsAndDesign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryGraphicsAndDesign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1healthAndFitness/title",
          "value": "SRDeviceUsageCategoryHealthAndFitness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1healthAndFitness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryHealthAndFitness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1developerTools/title",
          "value": "SRDeviceUsageCategoryDeveloperTools"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1developerTools/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryDeveloperTools"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1music/title",
          "value": "SRDeviceUsageCategoryMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1music/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/title",
          "value": "SRApplicationUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRApplicationUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRApplicationUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1kids/title",
          "value": "SRDeviceUsageCategoryKids"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1kids/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKids"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1shopping/title",
          "value": "SRDeviceUsageCategoryShopping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1shopping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryShopping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1lifestyle/title",
          "value": "SRDeviceUsageCategoryLifestyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1lifestyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryLifestyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1games/title",
          "value": "SRDeviceUsageCategoryGames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1games/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryGames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1medical/title",
          "value": "SRDeviceUsageCategoryMedical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1medical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryMedical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1applicationUsageByCategory/title",
          "value": "applicationUsageByCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1applicationUsageByCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationUsageByCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1weather/title",
          "value": "SRDeviceUsageCategoryWeather"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1weather/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryWeather"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1news/title",
          "value": "SRDeviceUsageCategoryNews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1news/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryNews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1finance/title",
          "value": "SRDeviceUsageCategoryFinance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1finance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryFinance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1entertainment/title",
          "value": "SRDeviceUsageCategoryEntertainment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1entertainment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryEntertainment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/title",
          "value": "SRDeviceUsageCategoryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1newsstand/title",
          "value": "SRDeviceUsageCategoryNewsstand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1newsstand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryNewsstand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1photoAndVideo/title",
          "value": "SRDeviceUsageCategoryPhotoAndVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1photoAndVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryPhotoAndVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1stickers/title",
          "value": "SRDeviceUsageCategoryStickers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1stickers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryStickers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1utilities/title",
          "value": "SRDeviceUsageCategoryUtilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1utilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryUtilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1sports/title",
          "value": "SRDeviceUsageCategorySports"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1sports/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategorySports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1reference/title",
          "value": "SRDeviceUsageCategoryReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1reference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1books/title",
          "value": "SRDeviceUsageCategoryBooks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1books/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryBooks"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srdeviceusagereport/categorykey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srdeviceusagereport/categorykey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
