{
  "abstract": [
    {
      "text": "A service that uses an item provider’s contents to compose a message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/composeMessage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSSharingServiceNameComposeMessage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "composeMessage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSSharingService",
        "text": "NSSharingService"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSSharingServiceName",
        "text": "Name"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSharingServiceNameComposeMessage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "composeMessage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "composeMessage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSharingService",
              "text": "NSSharingService"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSSharingServiceName",
              "text": "Name"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService": {
      "abstract": [
        {
          "text": "An object that facilitates the sharing of content with social media services, or with apps like Mail or Safari.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingService"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingService"
        }
      ],
      "role": "symbol",
      "title": "NSSharingService",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name": {
      "abstract": [
        {
          "text": "Constants that describe the sharing services that macOS supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "role": "symbol",
      "title": "NSSharingService.Name",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToAperture": {
      "abstract": [
        {
          "text": "A service that shares an item provider’s contents with Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addToAperture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToAperture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameAddToAperture"
        }
      ],
      "role": "symbol",
      "title": "addToAperture",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/addtoaperture"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToIPhoto": {
      "abstract": [
        {
          "text": "A service that shares an item provider’s contents with iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addToIPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToIPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameAddToIPhoto"
        }
      ],
      "role": "symbol",
      "title": "addToIPhoto",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/addtoiphoto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToSafariReadingList": {
      "abstract": [
        {
          "text": "A service that shares an item provider’s contents with Safari’s Reading List.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addToSafariReadingList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToSafariReadingList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameAddToSafariReadingList"
        }
      ],
      "role": "symbol",
      "title": "addToSafariReadingList",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/addtosafarireadinglist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/cloudSharing": {
      "abstract": [
        {
          "text": "A service that shares an item provider’s contents with other iCloud users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudSharing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/cloudSharing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameCloudSharing"
        }
      ],
      "role": "symbol",
      "title": "cloudSharing",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/cloudsharing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/composeEmail": {
      "abstract": [
        {
          "text": "A service that uses an item provider’s contents to compose an email.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composeEmail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/composeEmail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameComposeEmail"
        }
      ],
      "role": "symbol",
      "title": "composeEmail",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/composeemail"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/composeMessage": {
      "abstract": [
        {
          "text": "A service that uses an item provider’s contents to compose a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composeMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/composeMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameComposeMessage"
        }
      ],
      "role": "symbol",
      "title": "composeMessage",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/composemessage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/sendViaAirDrop": {
      "abstract": [
        {
          "text": "A service that sends an item provider’s contents to another device using AirDrop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendViaAirDrop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/sendViaAirDrop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameSendViaAirDrop"
        }
      ],
      "role": "symbol",
      "title": "sendViaAirDrop",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/sendviaairdrop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsDesktopPicture": {
      "abstract": [
        {
          "text": "A service that sets the item provider’s contents as the current user’s desktop picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useAsDesktopPicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsDesktopPicture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameUseAsDesktopPicture"
        }
      ],
      "role": "symbol",
      "title": "useAsDesktopPicture",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/useasdesktoppicture"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sharing-Service-Names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToAperture",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToIPhoto",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToSafariReadingList",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/cloudSharing",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/composeEmail",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/sendViaAirDrop",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsDesktopPicture"
      ],
      "title": "Sharing Service Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSharingServiceNameComposeMessage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameComposeMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sharing-Service-Names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToAperture",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToIPhoto",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/addToSafariReadingList",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/cloudSharing",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/composeEmail",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/sendViaAirDrop",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsDesktopPicture"
              ],
              "title": "Sharing Service Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSSharingServiceName",
                    "text": "NSSharingServiceName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSSharingServiceNameComposeMessage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1useAsDesktopPicture/title",
          "value": "NSSharingServiceNameUseAsDesktopPicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1useAsDesktopPicture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameUseAsDesktopPicture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name/title",
          "value": "NSSharingServiceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/title",
          "value": "NSSharingService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1composeMessage/title",
          "value": "NSSharingServiceNameComposeMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1composeMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameComposeMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1cloudSharing/title",
          "value": "NSSharingServiceNameCloudSharing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1cloudSharing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameCloudSharing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1composeEmail/title",
          "value": "NSSharingServiceNameComposeEmail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1composeEmail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameComposeEmail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1sendViaAirDrop/title",
          "value": "NSSharingServiceNameSendViaAirDrop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1sendViaAirDrop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameSendViaAirDrop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1addToSafariReadingList/title",
          "value": "NSSharingServiceNameAddToSafariReadingList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1addToSafariReadingList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameAddToSafariReadingList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1addToAperture/title",
          "value": "NSSharingServiceNameAddToAperture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1addToAperture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameAddToAperture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1addToIPhoto/title",
          "value": "NSSharingServiceNameAddToIPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1addToIPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameAddToIPhoto"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssharingservice/name/composemessage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssharingservice/name/composemessage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
