{
  "abstract": [
    {
      "text": "Replaces the user’s ",
      "type": "text"
    },
    {
      "identifier": "http://www.linkedin.com/",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " profile image with the provided image.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This service is no longer included with the system.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsLinkedInProfileImage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSSharingServiceNameUseAsLinkedInProfileImage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "useAsLinkedInProfileImage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSSharingService",
        "text": "NSSharingService"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSSharingServiceName",
        "text": "Name"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSharingServiceNameUseAsLinkedInProfileImage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.8",
        "message": "This service is no longer included with the system.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "useAsLinkedInProfileImage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "useAsLinkedInProfileImage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSharingService",
              "text": "NSSharingService"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSSharingServiceName",
              "text": "Name"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService": {
      "abstract": [
        {
          "text": "An object that facilitates the sharing of content with social media services, or with apps like Mail or Safari.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingService"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingService"
        }
      ],
      "role": "symbol",
      "title": "NSSharingService",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name": {
      "abstract": [
        {
          "text": "Constants that describe the sharing services that macOS supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "role": "symbol",
      "title": "NSSharingService.Name",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postImageOnFlickr": {
      "abstract": [
        {
          "text": "Posts the image on ",
          "type": "text"
        },
        {
          "identifier": "http://www.flickr.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postImageOnFlickr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postImageOnFlickr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNamePostImageOnFlickr"
        }
      ],
      "role": "symbol",
      "title": "postImageOnFlickr",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/postimageonflickr"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnFacebook": {
      "abstract": [
        {
          "text": "Posts the content on ",
          "type": "text"
        },
        {
          "identifier": "http://www.facebook.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postOnFacebook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnFacebook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNamePostOnFacebook"
        }
      ],
      "role": "symbol",
      "title": "postOnFacebook",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/postonfacebook"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnLinkedIn": {
      "abstract": [
        {
          "text": "Posts the content on ",
          "type": "text"
        },
        {
          "identifier": "http://www.linkedin.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postOnLinkedIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnLinkedIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNamePostOnLinkedIn"
        }
      ],
      "role": "symbol",
      "title": "postOnLinkedIn",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/postonlinkedin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnSinaWeibo": {
      "abstract": [
        {
          "text": "Posts the content on a ",
          "type": "text"
        },
        {
          "identifier": "http://weibo.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", Chinese microblogging (weibo) website. Akin to a hybrid of Twitter and Facebook.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postOnSinaWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnSinaWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNamePostOnSinaWeibo"
        }
      ],
      "role": "symbol",
      "title": "postOnSinaWeibo",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/postonsinaweibo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnTencentWeibo": {
      "abstract": [
        {
          "text": "Posts the content on a ",
          "type": "text"
        },
        {
          "identifier": "http://t.qq.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", Chinese microblogging (weibo) website.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postOnTencentWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnTencentWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNamePostOnTencentWeibo"
        }
      ],
      "role": "symbol",
      "title": "postOnTencentWeibo",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/postontencentweibo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnTwitter": {
      "abstract": [
        {
          "text": "Posts the content on ",
          "type": "text"
        },
        {
          "identifier": "http://www.twitter.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postOnTwitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnTwitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNamePostOnTwitter"
        }
      ],
      "role": "symbol",
      "title": "postOnTwitter",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/postontwitter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnTudou": {
      "abstract": [
        {
          "text": "Posts the video on the video sharing service ",
          "type": "text"
        },
        {
          "identifier": "http://www.tudou.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", based in the People’s Republic of China.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postVideoOnTudou"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnTudou",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNamePostVideoOnTudou"
        }
      ],
      "role": "symbol",
      "title": "postVideoOnTudou",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/postvideoontudou"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnVimeo": {
      "abstract": [
        {
          "text": "Posts the video on the video sharing service ",
          "type": "text"
        },
        {
          "identifier": "http://www.vimeo.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postVideoOnVimeo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnVimeo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNamePostVideoOnVimeo"
        }
      ],
      "role": "symbol",
      "title": "postVideoOnVimeo",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/postvideoonvimeo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnYouku": {
      "abstract": [
        {
          "text": "Posts the video on the video sharing service ",
          "type": "text"
        },
        {
          "identifier": "http://www.youku.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", based in the People’s Republic of China.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postVideoOnYouku"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnYouku",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNamePostVideoOnYouku"
        }
      ],
      "role": "symbol",
      "title": "postVideoOnYouku",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/postvideoonyouku"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsFacebookProfileImage": {
      "abstract": [
        {
          "text": "Replaces the user’s ",
          "type": "text"
        },
        {
          "identifier": "http://www.facebook.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " profile image with the provided image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useAsFacebookProfileImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsFacebookProfileImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameUseAsFacebookProfileImage"
        }
      ],
      "role": "symbol",
      "title": "useAsFacebookProfileImage",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/useasfacebookprofileimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsLinkedInProfileImage": {
      "abstract": [
        {
          "text": "Replaces the user’s ",
          "type": "text"
        },
        {
          "identifier": "http://www.linkedin.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " profile image with the provided image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useAsLinkedInProfileImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsLinkedInProfileImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameUseAsLinkedInProfileImage"
        }
      ],
      "role": "symbol",
      "title": "useAsLinkedInProfileImage",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/useaslinkedinprofileimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsTwitterProfileImage": {
      "abstract": [
        {
          "text": "Replaces the user’s ",
          "type": "text"
        },
        {
          "identifier": "http://www.twitter.com/",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " profile image with the provided image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useAsTwitterProfileImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSharingService",
          "text": "NSSharingService"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSharingServiceName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsTwitterProfileImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServiceNameUseAsTwitterProfileImage"
        }
      ],
      "role": "symbol",
      "title": "useAsTwitterProfileImage",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice/name/useastwitterprofileimage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "http://t.qq.com/": {
      "identifier": "http://t.qq.com/",
      "title": "Tencent Weibo",
      "titleInlineContent": [
        {
          "text": "Tencent Weibo",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://t.qq.com/"
    },
    "http://weibo.com/": {
      "identifier": "http://weibo.com/",
      "title": "Sina Weibo",
      "titleInlineContent": [
        {
          "text": "Sina Weibo",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://weibo.com/"
    },
    "http://www.facebook.com/": {
      "identifier": "http://www.facebook.com/",
      "title": "Facebook",
      "titleInlineContent": [
        {
          "text": "Facebook",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.facebook.com/"
    },
    "http://www.flickr.com/": {
      "identifier": "http://www.flickr.com/",
      "title": "Flickr",
      "titleInlineContent": [
        {
          "text": "Flickr",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.flickr.com/"
    },
    "http://www.linkedin.com/": {
      "identifier": "http://www.linkedin.com/",
      "title": "LinkedIn",
      "titleInlineContent": [
        {
          "text": "LinkedIn",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.linkedin.com/"
    },
    "http://www.tudou.com/": {
      "identifier": "http://www.tudou.com/",
      "title": "Tudou",
      "titleInlineContent": [
        {
          "text": "Tudou",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.tudou.com/"
    },
    "http://www.twitter.com/": {
      "identifier": "http://www.twitter.com/",
      "title": "Twitter",
      "titleInlineContent": [
        {
          "text": "Twitter",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.twitter.com/"
    },
    "http://www.vimeo.com/": {
      "identifier": "http://www.vimeo.com/",
      "title": "Vimeo",
      "titleInlineContent": [
        {
          "text": "Vimeo",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.vimeo.com/"
    },
    "http://www.youku.com/": {
      "identifier": "http://www.youku.com/",
      "title": "Youku",
      "titleInlineContent": [
        {
          "text": "Youku",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.youku.com/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postImageOnFlickr",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnFacebook",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnLinkedIn",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnSinaWeibo",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnTencentWeibo",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnTwitter",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnTudou",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnVimeo",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnYouku",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsFacebookProfileImage",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsTwitterProfileImage"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSharingServiceNameUseAsLinkedInProfileImage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameUseAsLinkedInProfileImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postImageOnFlickr",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnFacebook",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnLinkedIn",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnSinaWeibo",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnTencentWeibo",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postOnTwitter",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnTudou",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnVimeo",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/postVideoOnYouku",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsFacebookProfileImage",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name/useAsTwitterProfileImage"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService/Name",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSSharingServiceName",
                    "text": "NSSharingServiceName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSSharingServiceNameUseAsLinkedInProfileImage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This service is no longer included with the system.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name/title",
          "value": "NSSharingServiceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postImageOnFlickr/title",
          "value": "NSSharingServiceNamePostImageOnFlickr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postImageOnFlickr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNamePostImageOnFlickr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postOnLinkedIn/title",
          "value": "NSSharingServiceNamePostOnLinkedIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postOnLinkedIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNamePostOnLinkedIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1useAsFacebookProfileImage/title",
          "value": "NSSharingServiceNameUseAsFacebookProfileImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1useAsFacebookProfileImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameUseAsFacebookProfileImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postVideoOnTudou/title",
          "value": "NSSharingServiceNamePostVideoOnTudou"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postVideoOnTudou/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNamePostVideoOnTudou"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1useAsLinkedInProfileImage/title",
          "value": "NSSharingServiceNameUseAsLinkedInProfileImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1useAsLinkedInProfileImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameUseAsLinkedInProfileImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postVideoOnVimeo/title",
          "value": "NSSharingServiceNamePostVideoOnVimeo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postVideoOnVimeo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNamePostVideoOnVimeo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postOnTwitter/title",
          "value": "NSSharingServiceNamePostOnTwitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postOnTwitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNamePostOnTwitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postOnFacebook/title",
          "value": "NSSharingServiceNamePostOnFacebook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postOnFacebook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNamePostOnFacebook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postOnSinaWeibo/title",
          "value": "NSSharingServiceNamePostOnSinaWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postOnSinaWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNamePostOnSinaWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/title",
          "value": "NSSharingService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postVideoOnYouku/title",
          "value": "NSSharingServiceNamePostVideoOnYouku"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postVideoOnYouku/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNamePostVideoOnYouku"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1useAsTwitterProfileImage/title",
          "value": "NSSharingServiceNameUseAsTwitterProfileImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1useAsTwitterProfileImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNameUseAsTwitterProfileImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postOnTencentWeibo/title",
          "value": "NSSharingServiceNamePostOnTencentWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService~1Name~1postOnTencentWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServiceNamePostOnTencentWeibo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssharingservice/name/useaslinkedinprofileimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssharingservice/name/useaslinkedinprofileimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
