{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID/kMIDIProtocol_2_0"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDIProtocolID@kMIDIProtocol_2_0",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kMIDIProtocol_2_0"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDIProtocol_2_0"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "kMIDIProtocol_2_0"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "kMIDIProtocol_2_0"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID": {
      "abstract": [
        {
          "text": "Specifies a MIDI protocol variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIProtocolID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIProtocolID"
        }
      ],
      "role": "symbol",
      "title": "MIDIProtocolID",
      "type": "topic",
      "url": "/documentation/coremidi/midiprotocolid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID/kMIDIProtocol_1_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kMIDIProtocol_1_0"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID/kMIDIProtocol_1_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMIDIProtocol_1_0",
      "type": "topic",
      "url": "/documentation/coremidi/midiprotocolid/kmidiprotocol_1_0"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID/kMIDIProtocol_2_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kMIDIProtocol_2_0"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID/kMIDIProtocol_2_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMIDIProtocol_2_0",
      "type": "topic",
      "url": "/documentation/coremidi/midiprotocolid/kmidiprotocol_2_0"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocol-Versions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID/kMIDIProtocol_1_0"
      ],
      "title": "Protocol Versions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/title",
          "value": "MIDIProtocolID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProtocolID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProtocolID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midiprotocolid/kmidiprotocol_2_0"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
