{
  "abstract": [
    {
      "text": "A value of ",
      "type": "text"
    },
    {
      "code": "0.0",
      "type": "codeVoice"
    },
    {
      "text": " is copied to the destination channel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/zero"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLTextureSwizzle@MTLTextureSwizzleZero",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "zero"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLTextureSwizzleZero"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLTextureSwizzle.zero"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "zero"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle": {
      "abstract": [
        {
          "text": "A set of options to choose from when creating a texture swizzle pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzle"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzle"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/alpha": {
      "abstract": [
        {
          "text": "The alpha channel of the source pixel is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.alpha",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/alpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/blue": {
      "abstract": [
        {
          "text": "The blue channel of the source pixel is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleBlue"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.blue",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/blue"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/green": {
      "abstract": [
        {
          "text": "The green channel of the source pixel is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleGreen"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.green",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/green"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/one": {
      "abstract": [
        {
          "text": "A value of ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": " is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "one"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/one",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleOne"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.one",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/one"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/red": {
      "abstract": [
        {
          "text": "The red channel of the source pixel is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleRed"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.red",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/red"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/zero": {
      "abstract": [
        {
          "text": "A value of ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zero"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/zero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleZero"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.zero",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/zero"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Swizzle-Channels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/alpha",
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/blue",
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/green",
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/red",
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/one"
      ],
      "title": "Specifying Swizzle Channels"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLTextureSwizzleZero"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Swizzle-Channels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/alpha",
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/blue",
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/green",
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/red",
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/one"
              ],
              "title": "Specifying Swizzle Channels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLTextureSwizzleZero"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1green/title",
          "value": "MTLTextureSwizzleGreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleGreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1blue/title",
          "value": "MTLTextureSwizzleBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1alpha/title",
          "value": "MTLTextureSwizzleAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1red/title",
          "value": "MTLTextureSwizzleRed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleRed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle/title",
          "value": "MTLTextureSwizzle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1zero/title",
          "value": "MTLTextureSwizzleZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1zero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1one/title",
          "value": "MTLTextureSwizzleOne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1one/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleOne"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtltextureswizzle/zero"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtltextureswizzle/zero"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
