{
  "abstract": [
    {
      "text": "Requests the extension to decode a video frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/decodeFrame(from:options:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MEVideoDecoder(im)decodeFrameFromSampleBuffer:options:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "decodeFrame"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "from"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMSampleBufferRef",
        "text": "CMSampleBuffer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MEDecodeFrameOptions",
        "text": "MEDecodeFrameOptions"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CVImageBufferRef",
        "text": "CVImageBuffer"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MEDecodeFrameStatus",
        "text": "MEDecodeFrameStatus"
      },
      {
        "kind": "text",
        "text": ", (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "decodeFrameFromSampleBuffer:options:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "decodeFrame(from:options:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "decodeFrame"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sampleBuffer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSampleBufferRef",
              "text": "CMSampleBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MEDecodeFrameOptions",
              "text": "MEDecodeFrameOptions"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CVImageBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVImageBufferRef",
              "text": "CVImageBuffer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MEDecodeFrameStatus",
              "text": "MEDecodeFrameStatus"
            },
            {
              "kind": "text",
              "text": ", (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "decodeFrame"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sampleBuffer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSampleBufferRef",
              "text": "CMSampleBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MEDecodeFrameOptions",
              "text": "MEDecodeFrameOptions"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CVImageBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVImageBufferRef",
              "text": "CVImageBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MEDecodeFrameStatus",
              "text": "MEDecodeFrameStatus"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sample buffer that contains one video frame.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sampleBuffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Specific decode options for the frame.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The completion block to execute when the decode operation finishes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method calls the completion handler for every sample buffer frame when decoding completes, but not necessarily in display order. The completion handler receives a decoded pixel buffer, a decode status that indicates a frame dropped, or an error. Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderPixelBufferManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to allocate an image buffer. If an error occurs that’s external to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MediaExtensionErrorDomain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/VideoToolbox/VTDecompressionSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " receives it as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/VideoToolbox/kVTVideoDecoderUnknownErr",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/VideoToolbox/VTDecompressionSession": {
      "abstract": [
        {
          "text": "A reference to a decompression session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/VideoToolbox/VTDecompressionSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTDecompressionSession",
      "type": "topic",
      "url": "/documentation/VideoToolbox/VTDecompressionSession"
    },
    "doc://com.apple.documentation/documentation/VideoToolbox/kVTVideoDecoderUnknownErr": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderUnknownErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/VideoToolbox/kVTVideoDecoderUnknownErr",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTVideoDecoderUnknownErr",
      "type": "topic",
      "url": "/documentation/VideoToolbox/kVTVideoDecoderUnknownErr"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions": {
      "abstract": [
        {
          "text": "An object that guides the video decoder operation on a per-frame basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEDecodeFrameOptions"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEDecodeFrameOptions"
        }
      ],
      "role": "symbol",
      "title": "MEDecodeFrameOptions",
      "type": "topic",
      "url": "/documentation/mediaextension/medecodeframeoptions"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameStatus": {
      "abstract": [
        {
          "text": "A type that represents a non-error status related to a frame decode operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEDecodeFrameStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEDecodeFrameStatus"
        }
      ],
      "role": "symbol",
      "title": "MEDecodeFrameStatus",
      "type": "topic",
      "url": "/documentation/mediaextension/medecodeframestatus"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder": {
      "abstract": [
        {
          "text": "A protocol that defines the requirements for a video decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEVideoDecoder"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEVideoDecoder"
        }
      ],
      "role": "symbol",
      "title": "MEVideoDecoder",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/canAccept(_:)": {
      "abstract": [
        {
          "text": "Asks the extension whether the decoder can decode frames with the format description that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canAccept"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/canAccept(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canAcceptFormatDescription:"
        }
      ],
      "role": "symbol",
      "title": "canAccept(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder/canaccept(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/decodeFrame(from:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Requests the extension to decode a video frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodeFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEDecodeFrameOptions",
          "text": "MEDecodeFrameOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MEDecodeFrameStatus",
          "text": "MEDecodeFrameStatus"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/decodeFrame(from:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decodeFrameFromSampleBuffer:options:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "decodeFrame(from:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder/decodeframe(from:options:completionhandler:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderPixelBufferManager": {
      "abstract": [
        {
          "text": "Describes pixel buffer requirements and creates new pixel buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEVideoDecoderPixelBufferManager"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderPixelBufferManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEVideoDecoderPixelBufferManager"
        }
      ],
      "role": "symbol",
      "title": "MEVideoDecoderPixelBufferManager",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoderpixelbuffermanager"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MediaExtensionErrorDomain": {
      "abstract": [
        {
          "text": "The domain of the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MediaExtensionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MediaExtensionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MediaExtensionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MediaExtensionErrorDomain",
      "type": "topic",
      "url": "/documentation/mediaextension/mediaextensionerrordomain"
    },
    "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef": {
      "abstract": [
        {
          "text": "A reference to a buffer of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSampleBuffer",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMSampleBuffer"
    },
    "doc://com.externally.resolved.symbol/c:@T@CVImageBufferRef": {
      "abstract": [
        {
          "text": "A reference to a Core Video image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CVImageBufferRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/CoreVideo/CVImageBuffer"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Decoding-frames",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/canAccept(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameStatus"
      ],
      "title": "Decoding frames"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "decodeFrameFromSampleBuffer:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "decodeFrameFromSampleBuffer:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Decoding-frames",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/canAccept(_:)",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameStatus"
              ],
              "title": "Decoding frames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "decodeFrameFromSampleBuffer:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMSampleBufferRef",
                    "text": "CMSampleBufferRef"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sampleBuffer"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "options:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MEDecodeFrameOptions",
                    "text": "MEDecodeFrameOptions"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CVImageBufferRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CVImageBufferRef",
                    "text": "CVImageBufferRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "imageBuffer"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MEDecodeFrameStatus",
                    "text": "MEDecodeFrameStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "decodeStatus"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A sample buffer that contains one video frame.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sampleBuffer"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specific decode options for the frame.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The completion block to execute when the decode operation finishes.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1decodeFrame(from:options:completionHandler:)/title",
          "value": "decodeFrameFromSampleBuffer:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1decodeFrame(from:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "decodeFrameFromSampleBuffer:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1VideoToolbox~1kVTVideoDecoderUnknownErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderUnknownErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1canAccept(_:)/title",
          "value": "canAcceptFormatDescription:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1canAccept(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canAcceptFormatDescription:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CVImageBufferRef/title",
          "value": "CVImageBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CVImageBufferRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVBufferRef",
              "text": "CVBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVImageBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameOptions/title",
          "value": "MEDecodeFrameOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodeFrameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodeFrameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMSampleBufferRef/title",
          "value": "CMSampleBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMSampleBufferRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@opaqueCMSampleBuffer",
              "text": "opaqueCMSampleBuffer"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoderPixelBufferManager/title",
          "value": "MEVideoDecoderPixelBufferManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoderPixelBufferManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoderPixelBufferManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoderPixelBufferManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoderPixelBufferManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameStatus/title",
          "value": "MEDecodeFrameStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodeFrameStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodeFrameStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1VideoToolbox~1VTDecompressionSession/title",
          "value": "VTDecompressionSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1VideoToolbox~1VTDecompressionSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@OpaqueVTDecompressionSession",
              "text": "OpaqueVTDecompressionSession"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MediaExtensionErrorDomain/title",
          "value": "MediaExtensionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MediaExtensionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MediaExtensionErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder/title",
          "value": "MEVideoDecoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/mevideodecoder/decodeframe(from:options:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/mevideodecoder/decodeframe(from:options:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
