{
  "abstract": [
    {
      "text": "The recommended number of threads for the decoder to use.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/recommendedThreadCount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MEVideoDecoder(py)recommendedThreadCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "recommendedThreadCount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "recommendedThreadCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "recommendedThreadCount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "recommendedThreadCount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system sets this property on the extension when ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/VideoToolbox",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sets ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/VideoToolbox/kVTDecompressionPropertyKey_ThreadCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on the hosting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/VideoToolbox/VTDecompressionSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/VideoToolbox"
    },
    "doc://com.apple.documentation/documentation/VideoToolbox/VTDecompressionSession": {
      "abstract": [
        {
          "text": "A reference to a decompression session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/VideoToolbox/VTDecompressionSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTDecompressionSession",
      "type": "topic",
      "url": "/documentation/VideoToolbox/VTDecompressionSession"
    },
    "doc://com.apple.documentation/documentation/VideoToolbox/kVTDecompressionPropertyKey_ThreadCount": {
      "abstract": [
        {
          "text": "The number of threads used by a codec or the suggested number of threads to use (optional).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ThreadCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/VideoToolbox/kVTDecompressionPropertyKey_ThreadCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_ThreadCount",
      "type": "topic",
      "url": "/documentation/VideoToolbox/kVTDecompressionPropertyKey_ThreadCount"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder": {
      "abstract": [
        {
          "text": "A protocol that defines the requirements for a video decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEVideoDecoder"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEVideoDecoder"
        }
      ],
      "role": "symbol",
      "title": "MEVideoDecoder",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/actualThreadCount": {
      "abstract": [
        {
          "text": "The actual number of threads the decoder uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actualThreadCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/actualThreadCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "actualThreadCount"
        }
      ],
      "role": "symbol",
      "title": "actualThreadCount",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder/actualthreadcount"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/contentHasInterframeDependencies": {
      "abstract": [
        {
          "text": "A Boolean that specifies whether the content has interframe dependencies, if the decoder knows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentHasInterframeDependencies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/contentHasInterframeDependencies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentHasInterframeDependencies"
        }
      ],
      "role": "symbol",
      "title": "contentHasInterframeDependencies",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder/contenthasinterframedependencies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/isReadyForMoreMediaData": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the readiness of the decoder to accept more sample buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isReadyForMoreMediaData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/isReadyForMoreMediaData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readyForMoreMediaData"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isReadyForMoreMediaData",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder/isreadyformoremediadata"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/pixelFormatsWithReducedResolutionDecodeSupport": {
      "abstract": [
        {
          "text": "Provides a list of output pixel formats where the decoder supports reduced resolution decoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelFormatsWithReducedResolutionDecodeSupport"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/pixelFormatsWithReducedResolutionDecodeSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelFormatsWithReducedResolutionDecodeSupport"
        }
      ],
      "role": "symbol",
      "title": "pixelFormatsWithReducedResolutionDecodeSupport",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder/pixelformatswithreducedresolutiondecodesupport"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/producesRAWOutput": {
      "abstract": [
        {
          "text": "Indicates whether the decoder produces RAW output which requires the use of a RAW processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "producesRAWOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/producesRAWOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "producesRAWOutput"
        }
      ],
      "role": "symbol",
      "title": "producesRAWOutput",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder/producesrawoutput"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/recommendedThreadCount": {
      "abstract": [
        {
          "text": "The recommended number of threads for the decoder to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recommendedThreadCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/recommendedThreadCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recommendedThreadCount"
        }
      ],
      "role": "symbol",
      "title": "recommendedThreadCount",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder/recommendedthreadcount"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/reducedResolution": {
      "abstract": [
        {
          "text": "A request to decode at a lower resolution than full-size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reducedResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/reducedResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reducedResolution"
        }
      ],
      "role": "symbol",
      "title": "reducedResolution",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder/reducedresolution"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/supportedPixelFormatsOrderedByQuality": {
      "abstract": [
        {
          "text": "Provides hints about quality tradeoffs between pixel formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedPixelFormatsOrderedByQuality"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/supportedPixelFormatsOrderedByQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedPixelFormatsOrderedByQuality"
        }
      ],
      "role": "symbol",
      "title": "supportedPixelFormatsOrderedByQuality",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder/supportedpixelformatsorderedbyquality"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-video-decoder",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/contentHasInterframeDependencies",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/actualThreadCount",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/supportedPixelFormatsOrderedByQuality",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/reducedResolution",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/pixelFormatsWithReducedResolutionDecodeSupport",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/producesRAWOutput",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/isReadyForMoreMediaData"
      ],
      "title": "Inspecting a video decoder"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "recommendedThreadCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recommendedThreadCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-video-decoder",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/contentHasInterframeDependencies",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/actualThreadCount",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/supportedPixelFormatsOrderedByQuality",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/reducedResolution",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/pixelFormatsWithReducedResolutionDecodeSupport",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/producesRAWOutput",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder/isReadyForMoreMediaData"
              ],
              "title": "Inspecting a video decoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "recommendedThreadCount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1supportedPixelFormatsOrderedByQuality/title",
          "value": "supportedPixelFormatsOrderedByQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1supportedPixelFormatsOrderedByQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedPixelFormatsOrderedByQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ThreadCount/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_ThreadCount"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1isReadyForMoreMediaData/title",
          "value": "readyForMoreMediaData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1isReadyForMoreMediaData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readyForMoreMediaData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1actualThreadCount/title",
          "value": "actualThreadCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1actualThreadCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "actualThreadCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1VideoToolbox~1VTDecompressionSession/title",
          "value": "VTDecompressionSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1VideoToolbox~1VTDecompressionSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@OpaqueVTDecompressionSession",
              "text": "OpaqueVTDecompressionSession"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1reducedResolution/title",
          "value": "reducedResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1reducedResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reducedResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder/title",
          "value": "MEVideoDecoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1producesRAWOutput/title",
          "value": "producesRAWOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1producesRAWOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "producesRAWOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1pixelFormatsWithReducedResolutionDecodeSupport/title",
          "value": "pixelFormatsWithReducedResolutionDecodeSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1pixelFormatsWithReducedResolutionDecodeSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelFormatsWithReducedResolutionDecodeSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1recommendedThreadCount/title",
          "value": "recommendedThreadCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1recommendedThreadCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recommendedThreadCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1contentHasInterframeDependencies/title",
          "value": "contentHasInterframeDependencies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder~1contentHasInterframeDependencies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentHasInterframeDependencies"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/mevideodecoder/recommendedthreadcount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/mevideodecoder/recommendedthreadcount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
