{
  "abstract": [
    {
      "text": "An error code that indicates the filter configuration is invalid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationInvalid"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEFilterManagerError@NEFilterManagerErrorConfigurationInvalid",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "configurationInvalid"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEFilterManagerErrorConfigurationInvalid"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEFilterManagerError.configurationInvalid"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configurationInvalid"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError": {
      "abstract": [
        {
          "text": "Error codes specific to filter managers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterManagerError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterManagerError"
        }
      ],
      "role": "symbol",
      "title": "NEFilterManagerError",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltermanagererror"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationCannotBeRemoved": {
      "abstract": [
        {
          "text": "An error code that indicates removing the configuration isn’t allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationCannotBeRemoved"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationCannotBeRemoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterManagerErrorConfigurationCannotBeRemoved"
        }
      ],
      "role": "symbol",
      "title": "NEFilterManagerError.configurationCannotBeRemoved",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltermanagererror/configurationcannotberemoved"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationDisabled": {
      "abstract": [
        {
          "text": "An error code that indicates the filter configuration isn’t enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationDisabled"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterManagerErrorConfigurationDisabled"
        }
      ],
      "role": "symbol",
      "title": "NEFilterManagerError.configurationDisabled",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltermanagererror/configurationdisabled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationInternalError": {
      "abstract": [
        {
          "text": "An error code that indicates an internal configuration error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationInternalError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationInternalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterManagerErrorConfigurationInternalError"
        }
      ],
      "role": "symbol",
      "title": "NEFilterManagerError.configurationInternalError",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltermanagererror/configurationinternalerror"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationInvalid": {
      "abstract": [
        {
          "text": "An error code that indicates the filter configuration is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationInvalid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterManagerErrorConfigurationInvalid"
        }
      ],
      "role": "symbol",
      "title": "NEFilterManagerError.configurationInvalid",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltermanagererror/configurationinvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationPermissionDenied": {
      "abstract": [
        {
          "text": "An error code that indicates the configuration lacks permission.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationPermissionDenied"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationPermissionDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterManagerErrorConfigurationPermissionDenied"
        }
      ],
      "role": "symbol",
      "title": "NEFilterManagerError.configurationPermissionDenied",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltermanagererror/configurationpermissiondenied"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationStale": {
      "abstract": [
        {
          "text": "An error code that indicates another process modfied the filter configuration since the last time the app loaded the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationStale"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationStale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterManagerErrorConfigurationStale"
        }
      ],
      "role": "symbol",
      "title": "NEFilterManagerError.configurationStale",
      "type": "topic",
      "url": "/documentation/networkextension/nefiltermanagererror/configurationstale"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationDisabled",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationStale",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationCannotBeRemoved",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationPermissionDenied",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationInternalError"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEFilterManagerErrorConfigurationInvalid"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterManagerErrorConfigurationInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationDisabled",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationStale",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationCannotBeRemoved",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationPermissionDenied",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterManagerError/configurationInternalError"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEFilterManagerErrorConfigurationInvalid"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError/title",
          "value": "NEFilterManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationInvalid/title",
          "value": "NEFilterManagerErrorConfigurationInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterManagerErrorConfigurationInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationDisabled/title",
          "value": "NEFilterManagerErrorConfigurationDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterManagerErrorConfigurationDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationInternalError/title",
          "value": "NEFilterManagerErrorConfigurationInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationInternalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterManagerErrorConfigurationInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationPermissionDenied/title",
          "value": "NEFilterManagerErrorConfigurationPermissionDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationPermissionDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterManagerErrorConfigurationPermissionDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationStale/title",
          "value": "NEFilterManagerErrorConfigurationStale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationStale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterManagerErrorConfigurationStale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationCannotBeRemoved/title",
          "value": "NEFilterManagerErrorConfigurationCannotBeRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterManagerError~1configurationCannotBeRemoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterManagerErrorConfigurationCannotBeRemoved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nefiltermanagererror/configurationinvalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nefiltermanagererror/configurationinvalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
