{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didGenerate:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"workoutSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"workoutSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutSession","text":"HKWorkoutSession","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didGenerate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutEvent","text":"HKWorkoutEvent","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The workout session associated with the event.","type":"text"}],"type":"paragraph"}],"name":"workoutSession"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The event that the system generated. For a list of possible values, see "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent"},{"type":"text","text":"."}]}],"name":"event"}]},{"kind":"mentions","mentions":["doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data"]},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"You can save the generated events and use them when creating a "},{"type":"reference","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkout","isActive":true},{"type":"text","text":" object for the session."}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"title":"Tracking workout sessions","generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didChangeTo:from:date:)","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didFailWithError:)","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didBeginActivityWith:date:)","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didEndActivityWith:date:)"],"anchor":"Tracking-workout-sessions"}],"metadata":{"modules":[{"name":"HealthKit"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)HKWorkoutSessionDelegate(im)workoutSession:didGenerateEvent:","symbolKind":"method","platforms":[{"introducedAt":"10.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"introducedAt":"10.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"13.1","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false,"name":"macOS"},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"},{"introducedAt":"3.0","deprecated":false,"unavailable":false,"beta":false,"name":"watchOS"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"workoutSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"HKWorkoutSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didGenerate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKWorkoutEvent","kind":"typeIdentifier","text":"HKWorkoutEvent"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"workoutSession:didGenerateEvent:"}],"role":"symbol","title":"workoutSession(_:didGenerate:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate"]]},"kind":"symbol","variants":[{"paths":["/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didgenerate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didgenerate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Tells the delegate that the system generated a workout event.","type":"text"}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didGenerate:)":{"abstract":[{"type":"text","text":"Tells the delegate that the system generated a workout event."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"workoutSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HKWorkoutSession","preciseIdentifier":"c:objc(cs)HKWorkoutSession"},{"text":", ","kind":"text"},{"text":"didGenerate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkoutEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutEvent"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didGenerate:)","title":"workoutSession(_:didGenerate:)","navigatorTitle":[{"text":"workoutSession:didGenerateEvent:","kind":"identifier"}],"url":"/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didgenerate:)","kind":"symbol","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent":{"url":"/documentation/healthkit/hkworkoutevent","title":"HKWorkoutEvent","abstract":[{"text":"An object representing an important event during a workout.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKWorkoutEvent"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutEvent"}],"role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data":{"role":"article","kind":"article","abstract":[{"type":"text","text":"Receive segments and distance samples during downhill skiing and snowboarding workout sessions."}],"url":"/documentation/healthkit/receiving-downhill-skiing-and-snowboarding-data","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data","title":"Receiving Downhill Skiing and Snowboarding Data"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkout":{"title":"HKWorkout","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKWorkout"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkout"}],"type":"topic","url":"/documentation/healthkit/hkworkout","abstract":[{"type":"text","text":"A workout sample that stores information about a single physical activity."}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkout"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutSessionDelegate"}],"type":"topic","url":"/documentation/healthkit/hkworkoutsessiondelegate","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate","role":"symbol","abstract":[{"text":"The session delegate protocol that defines an interface for receiving notifications about errors and changes in the workout session’s state.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSessionDelegate"}],"kind":"symbol","title":"HKWorkoutSessionDelegate"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didEndActivityWith:date:)":{"title":"workoutSession(_:didEndActivityWith:date:)","role":"symbol","navigatorTitle":[{"text":"workoutSession:didEndActivityWithConfiguration:date:","kind":"identifier"}],"type":"topic","url":"/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didendactivitywith:date:)","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didEndActivityWith:date:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"workoutSession"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)HKWorkoutSession","kind":"typeIdentifier","text":"HKWorkoutSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndActivityWith"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKWorkoutConfiguration","kind":"typeIdentifier","text":"HKWorkoutConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"date"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Tells the session that the current workout activity ended."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didChangeTo:from:date:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"workoutSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"HKWorkoutSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutSession"},{"text":", ","kind":"text"},{"text":"didChangeTo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkoutSessionState","kind":"typeIdentifier","preciseIdentifier":"c:@E@HKWorkoutSessionState"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@HKWorkoutSessionState","text":"HKWorkoutSessionState","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"date"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":")"}],"required":true,"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didChangeTo:from:date:)","url":"/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didchangeto:from:date:)","navigatorTitle":[{"kind":"identifier","text":"workoutSession:didChangeToState:fromState:date:"}],"kind":"symbol","title":"workoutSession(_:didChangeTo:from:date:)","abstract":[{"type":"text","text":"Tells the delegate that the session’s state changed."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession":{"type":"topic","url":"/documentation/healthkit/hkworkoutsession","title":"HKWorkoutSession","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A session that tracks the user’s workout on Apple Watch."}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSession"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutSession"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didFailWithError:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"workoutSession","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKWorkoutSession","text":"HKWorkoutSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"required":true,"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didFailWithError:)","url":"/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didfailwitherror:)","navigatorTitle":[{"text":"workoutSession:didFailWithError:","kind":"identifier"}],"kind":"symbol","title":"workoutSession(_:didFailWithError:)","abstract":[{"type":"text","text":"Tells the delegate that the session failed with an error."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didBeginActivityWith:date:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"workoutSession","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKWorkoutSession","text":"HKWorkoutSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didBeginActivityWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkoutConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutConfiguration"},{"text":", ","kind":"text"},{"text":"date","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didBeginActivityWith:date:)","url":"/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didbeginactivitywith:date:)","navigatorTitle":[{"text":"workoutSession:didBeginActivityWithConfiguration:date:","kind":"identifier"}],"kind":"symbol","title":"workoutSession(_:didBeginActivityWith:date:)","abstract":[{"type":"text","text":"Tells the delegate that a new workout session began."}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"17.0"},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"17.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"17.0"},{"beta":false,"name":"macOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false},{"beta":false,"name":"watchOS","introducedAt":"3.0","unavailable":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"path":"/metadata/title","op":"replace","value":"workoutSession:didGenerateEvent:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"workoutSession:didGenerateEvent:"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Tracking workout sessions","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didChangeTo:from:date:)","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didFailWithError:)","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didBeginActivityWith:date:)","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didEndActivityWith:date:)"],"anchor":"Tracking-workout-sessions","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"workoutSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutSession","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession","text":"HKWorkoutSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"workoutSession"},{"kind":"text","text":" "},{"kind":"identifier","text":"didGenerateEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutEvent","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent","text":"HKWorkoutEvent"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"workoutSession","content":[{"inlineContent":[{"type":"text","text":"The workout session associated with the event."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The event that the system generated. For a list of possible values, see "},{"type":"reference","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"event"}]},"path":"/primaryContentSections/1","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didGenerate:)/title","value":"workoutSession:didGenerateEvent:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didGenerate:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"workoutSession:didGenerateEvent:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/title","value":"HKWorkoutEvent"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/fragments","value":[{"text":"HKWorkoutEvent","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/navigatorTitle","value":[{"kind":"identifier","text":"HKWorkoutEvent"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/title","value":"HKWorkout"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/fragments","value":[{"kind":"identifier","text":"HKWorkout"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/navigatorTitle","value":[{"kind":"identifier","text":"HKWorkout"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate/title","value":"HKWorkoutSessionDelegate"},{"value":[{"kind":"identifier","text":"HKWorkoutSessionDelegate"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate/fragments","op":"replace"},{"value":[{"text":"HKWorkoutSessionDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate/navigatorTitle","op":"replace"},{"value":"workoutSession:didEndActivityWithConfiguration:date:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didEndActivityWith:date:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"workoutSession:didEndActivityWithConfiguration:date:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didEndActivityWith:date:)/fragments","op":"replace"},{"value":"workoutSession:didChangeToState:fromState:date:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didChangeTo:from:date:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"workoutSession:didChangeToState:fromState:date:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didChangeTo:from:date:)/fragments","op":"replace"},{"value":"HKWorkoutSession","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/title","op":"replace"},{"value":[{"kind":"identifier","text":"HKWorkoutSession"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"HKWorkoutSession"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/navigatorTitle","op":"replace"},{"value":"workoutSession:didFailWithError:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didFailWithError:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"workoutSession:didFailWithError:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didFailWithError:)/fragments","op":"replace"},{"value":"workoutSession:didBeginActivityWithConfiguration:date:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didBeginActivityWith:date:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"workoutSession:didBeginActivityWithConfiguration:date:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didBeginActivityWith:date:)/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}