{
  "abstract": [
    {
      "text": "Passes data from the remote workout session to the session delegate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didReceiveDataFromRemoteWorkoutSession:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)HKWorkoutSessionDelegate(im)workoutSession:didReceiveDataFromRemoteWorkoutSession:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "workoutSession"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKWorkoutSession",
        "text": "HKWorkoutSession"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didReceiveDataFromRemoteWorkoutSession"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DataV",
        "text": "Data"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "workoutSession:didReceiveDataFromRemoteWorkoutSession:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "workoutSession(_:didReceiveDataFromRemoteWorkoutSession:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "workoutSession"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "workoutSession"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKWorkoutSession",
              "text": "HKWorkoutSession"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didReceiveDataFromRemoteWorkoutSession"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "data"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DataV",
              "text": "Data"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The workout session that received the data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "workoutSession"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of data objects sent from the remote session. The array contains the data objects in the order the system received them.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "data"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this method to decode and use the data sent from the remote workout session. Your app can send data from either the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/mirrored",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/primary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " workout session.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "nonisolated func workoutSession(_ workoutSession: HKWorkoutSession, didReceiveDataFromRemoteWorkoutSession data: [Data]) {",
            "    for archivedData in data {",
            "        do {",
            "            let decoder = try NSKeyedUnarchiver(forReadingFrom: archivedData)",
            "            if let healthData = decoder.decodeObject() as? HealthData {",
            "                Task {",
            "                    await set(data: healthData)",
            "                }",
            "            }",
            "        }",
            "        catch {",
            "            // Handle the error here.",
            "            fatalError(\"*** An error occurred when trying to decode the incoming data: \\(archivedData) ***\")",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS, your app can go into the background and become suspended. When suspended, HealthKit gathers the data coming from the remote session. When the app resumes, HealthKit sends an array containing all the  data objects it has accumulated to this delegate method. The data objects in the array appear in the order that the local system received them. During the workout session, HealthKit wakes the iOS app periodically to deliver any cached data objects, but there might be several minutes between delegate calls.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On watchOS, the workout session keeps the app running even if it’s in the background; however, the system can temporarily suspend the app — for example, if the app uses an excessive amount of CPU in the background. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". While suspended, HealthKit caches the incoming data objects and delivers an array of data objects when the app resumes, just like in the iOS app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession": {
      "abstract": [
        {
          "text": "A session that tracks the user’s workout on Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSession"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSession"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSession",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsession"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate": {
      "abstract": [
        {
          "text": "The session delegate protocol that defines an interface for receiving notifications about errors and changes in the workout session’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionDelegate"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionDelegate",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessiondelegate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didDisconnectFromRemoteDeviceWithError:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the mirrored workout session disconnected from the primary session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutSession",
          "text": "HKWorkoutSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDisconnectFromRemoteDeviceWithError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didDisconnectFromRemoteDeviceWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workoutSession:didDisconnectFromRemoteDeviceWithError:"
        }
      ],
      "role": "symbol",
      "title": "workoutSession(_:didDisconnectFromRemoteDeviceWithError:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:diddisconnectfromremotedevicewitherror:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didReceiveDataFromRemoteWorkoutSession:)": {
      "abstract": [
        {
          "text": "Passes data from the remote workout session to the session delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutSession",
          "text": "HKWorkoutSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveDataFromRemoteWorkoutSession"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didReceiveDataFromRemoteWorkoutSession:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workoutSession:didReceiveDataFromRemoteWorkoutSession:"
        }
      ],
      "role": "symbol",
      "title": "workoutSession(_:didReceiveDataFromRemoteWorkoutSession:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didreceivedatafromremoteworkoutsession:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/mirrored": {
      "abstract": [
        {
          "text": "A mirrored session, running on the companion iOS device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mirrored"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/mirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionTypeMirrored"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionType.mirrored",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessiontype/mirrored"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/primary": {
      "abstract": [
        {
          "text": "A primary session running on watchOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primary"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType/primary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionTypePrimary"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionType.primary",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessiontype/primary"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions": {
      "abstract": [
        {
          "text": "Track a workout on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions",
      "kind": "article",
      "role": "article",
      "title": "Running workout sessions",
      "type": "topic",
      "url": "/documentation/healthkit/running-workout-sessions"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DataV": {
      "abstract": [
        {
          "text": "A byte buffer in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Data",
      "type": "topic",
      "url": "/documentation/foundation/data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-mirrored-sessions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didDisconnectFromRemoteDeviceWithError:)"
      ],
      "title": "Working with mirrored sessions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "workoutSession:didReceiveDataFromRemoteWorkoutSession:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workoutSession:didReceiveDataFromRemoteWorkoutSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-mirrored-sessions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didDisconnectFromRemoteDeviceWithError:)"
              ],
              "title": "Working with mirrored sessions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "workoutSession:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HKWorkoutSession",
                    "text": "HKWorkoutSession"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "workoutSession"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didReceiveDataFromRemoteWorkoutSession:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSData *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "data"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The workout session that received the data.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "workoutSession"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of data objects sent from the remote session. The array contains the data objects in the order the system received them.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "data"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType~1primary/title",
          "value": "HKWorkoutSessionTypePrimary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType~1primary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionTypePrimary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType~1mirrored/title",
          "value": "HKWorkoutSessionTypeMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType~1mirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionTypeMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didReceiveDataFromRemoteWorkoutSession:)/title",
          "value": "workoutSession:didReceiveDataFromRemoteWorkoutSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didReceiveDataFromRemoteWorkoutSession:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workoutSession:didReceiveDataFromRemoteWorkoutSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate/title",
          "value": "HKWorkoutSessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/title",
          "value": "HKWorkoutSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didDisconnectFromRemoteDeviceWithError:)/title",
          "value": "workoutSession:didDisconnectFromRemoteDeviceWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didDisconnectFromRemoteDeviceWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workoutSession:didDisconnectFromRemoteDeviceWithError:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didreceivedatafromremoteworkoutsession:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didreceivedatafromremoteworkoutsession:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
