{
  "abstract": [
    {
      "text": "The RSA-PSS certificate type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/RSAPSS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEVPNIKEv2CertificateType@NEVPNIKEv2CertificateTypeRSAPSS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "RSAPSS"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNIKEv2CertificateTypeRSAPSS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEVPNIKEv2CertificateType.RSAPSS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "RSAPSS"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType": {
      "abstract": [
        {
          "text": "An enumeration of certificate type values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2CertificateType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2CertificateType"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2CertificateType",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2certificatetype"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA256": {
      "abstract": [
        {
          "text": "The ECDSA with p-256 curve certificate type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDSA256"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2CertificateTypeECDSA256"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2CertificateType.ECDSA256",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2certificatetype/ecdsa256"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA384": {
      "abstract": [
        {
          "text": "The ECDSA with p-384 curve certificate type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDSA384"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2CertificateTypeECDSA384"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2CertificateType.ECDSA384",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2certificatetype/ecdsa384"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA521": {
      "abstract": [
        {
          "text": "The ECDSA with p-521 curve certificate type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ECDSA521"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA521",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2CertificateTypeECDSA521"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2CertificateType.ECDSA521",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2certificatetype/ecdsa521"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/RSA": {
      "abstract": [
        {
          "text": "The RSA certificate type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RSA"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/RSA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2CertificateTypeRSA"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2CertificateType.RSA",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2certificatetype/rsa"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/RSAPSS": {
      "abstract": [
        {
          "text": "The RSA-PSS certificate type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RSAPSS"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/RSAPSS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2CertificateTypeRSAPSS"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2CertificateType.RSAPSS",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2certificatetype/rsapss"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ed25519": {
      "abstract": [
        {
          "text": "The Edwards 25519 curve certificate type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ed25519"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ed25519",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2CertificateTypeEd25519"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2CertificateType.ed25519",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2certificatetype/ed25519"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Certificate-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/RSA",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA256",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA384",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA521",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ed25519"
      ],
      "title": "Certificate types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEVPNIKEv2CertificateTypeRSAPSS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateTypeRSAPSS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Certificate-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/RSA",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA256",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA384",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ECDSA521",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2CertificateType/ed25519"
              ],
              "title": "Certificate types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEVPNIKEv2CertificateTypeRSAPSS"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1ECDSA384/title",
          "value": "NEVPNIKEv2CertificateTypeECDSA384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1ECDSA384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateTypeECDSA384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1ECDSA256/title",
          "value": "NEVPNIKEv2CertificateTypeECDSA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1ECDSA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateTypeECDSA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1RSA/title",
          "value": "NEVPNIKEv2CertificateTypeRSA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1RSA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateTypeRSA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1ed25519/title",
          "value": "NEVPNIKEv2CertificateTypeEd25519"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1ed25519/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateTypeEd25519"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1ECDSA521/title",
          "value": "NEVPNIKEv2CertificateTypeECDSA521"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1ECDSA521/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateTypeECDSA521"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1RSAPSS/title",
          "value": "NEVPNIKEv2CertificateTypeRSAPSS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType~1RSAPSS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateTypeRSAPSS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType/title",
          "value": "NEVPNIKEv2CertificateType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2CertificateType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2CertificateType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2certificatetype/rsapss"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2certificatetype/rsapss"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
