{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSClient",
        "doc://FSKit/documentation/FSKit/FSModuleIdentity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSModuleIdentity/Identifiable-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Identifiable Implementations"
  },
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSClient": {
      "abstract": [
        {
          "text": "An interface for apps and daemons to interact with FSKit.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSClient"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSClient"
        }
      ],
      "role": "symbol",
      "title": "FSClient",
      "type": "topic",
      "url": "/documentation/fskit/fsclient"
    },
    "doc://FSKit/documentation/FSKit/FSModuleIdentity": {
      "abstract": [
        {
          "text": "An installed file system module.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSModuleIdentity"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSModuleIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSModuleIdentity"
        }
      ],
      "role": "symbol",
      "title": "FSModuleIdentity",
      "type": "topic",
      "url": "/documentation/fskit/fsmoduleidentity"
    },
    "doc://FSKit/documentation/FSKit/FSModuleIdentity/ID-swift.typealias": {
      "abstract": [
        {
          "text": "A type representing the stable identity of the entity associated with",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "an instance.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSModuleIdentity/ID-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "role": "symbol",
      "title": "FSModuleIdentity.ID",
      "type": "topic",
      "url": "/documentation/fskit/fsmoduleidentity/id-swift.typealias"
    },
    "doc://FSKit/documentation/FSKit/FSModuleIdentity/id-76bht": {
      "abstract": [
        {
          "text": "The stable identity of the entity associated with this instance.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSModuleIdentity/id-76bht",
      "kind": "symbol",
      "role": "symbol",
      "title": "id",
      "type": "topic",
      "url": "/documentation/fskit/fsmoduleidentity/id-76bht"
    },
    "doc://FSKit/documentation/FSKit/FSModuleIdentity/id-76nbc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SO",
          "text": "ObjectIdentifier"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSModuleIdentity/id-76nbc",
      "kind": "symbol",
      "role": "symbol",
      "title": "id",
      "type": "topic",
      "url": "/documentation/fskit/fsmoduleidentity/id-76nbc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSModuleIdentity/id-76bht",
        "doc://FSKit/documentation/FSKit/FSModuleIdentity/id-76nbc"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSModuleIdentity/ID-swift.typealias"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSModuleIdentity/title",
          "value": "FSModuleIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSModuleIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSModuleIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSModuleIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSModuleIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSClient/title",
          "value": "FSClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSClient"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsmoduleidentity/identifiable-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
