{
  "abstract": [
    {
      "text": "Identify the signs of a language exception, and address the crashes caused by uncaught",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "language exceptions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/debugging",
        "doc://com.apple.Xcode/documentation/Xcode/diagnosing-issues-using-crash-reports-and-device-logs",
        "doc://com.apple.Xcode/documentation/Xcode/identifying-the-cause-of-common-crashes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/addressing-language-exception-crashes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Addressing language exception crashes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Language exceptions, such as those from Objective-C, indicate programming errors",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "discovered at runtime, such as accessing an array with an index that’s out-of-bounds",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or not implementing a required method of a protocol. To determine whether a crash",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is due to a language exception, first confirm that the crash report contains this",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "pattern:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Exception Type:  EXC_CRASH (SIGABRT)",
            "Exception Codes: 0x0000000000000000, 0x0000000000000000",
            "Exception Note:  EXC_CORPSE_NOTIFY"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "A crash due to a language exception that isn’t caught has a ",
              "type": "text"
            },
            {
              "code": "Last Exception Backtrace",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in the crash report. Verify this backtrace is present to confirm the crash is due",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to a language exception.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Exception backtraces to the code throwing the exception aren’t provided for",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "C++ exceptions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Identify-the-API-throwing-the-exception",
          "level": 3,
          "text": "Identify the API throwing the exception",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In the ",
              "type": "text"
            },
            {
              "code": "Last Exception Backtrace",
              "type": "codeVoice"
            },
            {
              "text": ", the operating system records the full backtrace",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of function calls leading to the exception. This backtrace ends with frames that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "make it clear a language exception was thrown. Further down the backtrace, you’ll",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "find key information about what method threw the exception, and what part of your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "code called the method that threw the exception. For example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Last Exception Backtrace:",
            "0   CoreFoundation                    0x1bf596a48 __exceptionPreprocess + 220",
            "1   libobjc.A.dylib                   0x1bf2bdfa4 objc_exception_throw + 55",
            "2   CoreFoundation                    0x1bf49b0ec -[NSException raise] + 11",
            "3   Foundation                        0x1bf879170 -[NSObject+ 205168 (NSKeyValueCoding) setValue:forKey:] + 311",
            "4   UIKitCore                         0x1c2ffa0b4 -[UIViewController setValue:forKey:] + 99",
            "5   UIKitCore                         0x1c32c1234 -[UIRuntimeOutletConnection connect] + 123",
            "6   CoreFoundation                    0x1bf470f3c -[NSArray makeObjectsPerformSelector:] + 251",
            "7   UIKitCore                         0x1c32be3a4 -[UINib instantiateWithOwner:options:] + 1967",
            "8   UIKitCore                         0x1c3000f18 -[UIViewController _loadViewFromNibNamed:bundle:] + 363",
            "9   UIKitCore                         0x1c30019a4 -[UIViewController loadView] + 175",
            "10  UIKitCore                         0x1c3001c5c -[UIViewController loadViewIfRequired] + 171",
            "11  UIKitCore                         0x1c3002360 -[UIViewController view] + 27",
            "12  UIKitCore                         0x1c3017a98 -[UIViewController _setPresentationController:] + 107",
            "13  UIKitCore                         0x1c30108a4 -[UIViewController _presentViewController:modalSourceViewController:presentationController:animationController:interactionController:completion:] + 1343",
            "14  UIKitCore                         0x1c30122b8 -[UIViewController _presentViewController:withAnimationController:completion:] + 4255",
            "15  UIKitCore                         0x1c3014794 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 103",
            "16  UIKitCore                         0x1c3014c90 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 507",
            "17  UIKitCore                         0x1c30146e4 -[UIViewController _presentViewController:animated:completion:] + 195",
            "18  UIKitCore                         0x1c301494c -[UIViewController presentViewController:animated:completion:] + 159",
            "19  MyCoolApp                         0x104e8b1ac MyViewController.viewDidLoad() (in MyCoolApp) (MyViewController.swift:35)"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In this example backtrace, the operating system threw an exception in frames 0-2.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Frame 3 raised the exception because it couldn’t complete the connection of the ",
              "type": "text"
            },
            {
              "code": "@IBOutlet",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "properties defined in an Interface Builder file loaded into memory in frames 4-7.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Frames 8-17 show UIKit preparing to present this view defined in Interface Builder.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Frame 18 shows this crash started from the app calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/present(_:animated:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "called from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/viewDidLoad()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in frame 19. Frame 19 is a key piece of information for investigating this crash;",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "it tells you to determine which Interface Builder file contains the problem by inspecting",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the source code near line 35 in ",
              "type": "text"
            },
            {
              "code": "MyViewController.swift",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If the API throwing the exception is ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1418637-doesnotrecognizeselector",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ":,",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "the crash may be due to a zombie object. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.Xcode/documentation/Xcode/investigating-crashes-for-zombie-objects",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "for additional information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Check-the-exception-message",
          "level": 3,
          "text": "Check the exception message",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The uncaught exception handler provided by the operating system logs the exception",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "message to the console before terminating the process. If you reproduce a crash resulting",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "from a language exception with the Xcode debugger attached to your app, you can see",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "this message:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Application Specific Information:",
            "*** Terminating app due to uncaught exception 'NSUnknownKeyException', ",
            "    reason: '[<MyCoolApp.MyViewController 0x105510d50> setValue:forUndefinedKey:]: ",
            "    this class is not key value coding-compliant for the key refreshButton.'"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Continuing the example in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/addressing-language-exception-crashes#Identify-the-API-throwing-the-exception",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "this exception message fills in details not visible in the exception backtrace — the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Interface Builder file has an outlet named ",
              "type": "text"
            },
            {
              "code": "refreshButton",
              "type": "codeVoice"
            },
            {
              "text": ", but the ",
              "type": "text"
            },
            {
              "code": "MyViewController",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "class doesn’t declare an ",
              "type": "text"
            },
            {
              "code": "@IBOutlet",
              "type": "codeVoice"
            },
            {
              "text": " property by that name.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The crash report excludes the exception message for some errors to prevent disclosing private information about the person using the app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The crash report includes exception messages for many of the common cases of language exceptions your app generates through its use of framework APIs.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For more about these exceptions, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/reading-an-exception-message",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " apps have a default",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "exception handler that catches all language exceptions raised by code run from its",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "run loop. It logs the exception message and then allows the app to continue running.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "If you can reproduce a language exception crash, set an exception breakpoint to pause",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "execution and inspect your app’s state with Xcode’s debugger, as described in ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/xcode/mac/current/#/devfeaa874d0",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To automatically print the exception message when the exception breakpoint pauses",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "execution, add an action to the exception breakpoint that runs a debugger command:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "po $arg1"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "anchor": "Address-crashes-from-a-system-language-exception",
          "level": 3,
          "text": "Address crashes from a system language exception",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After identifying the operating system’s API throwing the exception, consult the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "documentation for that API to determine what conditions trigger the exception. Also",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "try to reproduce the crash with the Xcode debugger attached to get the additional",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "information about the exception in the console, using the frames in the backtrace",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "as a guide to the specific code you need to test.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you can’t reproduce the crash, use all of the thread backtraces (not just the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "exception backtrace) as clues about what your app was doing at the time it crashed,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and think about what that information says about your app’s state. Use those clues",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "as a starting point for addressing the crash.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Handle-language-exceptions-thrown-by-your-apps-code",
          "level": 3,
          "text": "Handle language exceptions thrown by your app’s code",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "64-bit versions of iOS and iPadOS use a zero-cost exception implementation, where",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "every function has additional data that describes how to unwind the stack, or exit",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "each stack frame, if a function throws an exception. If the thrown exception encounters",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a stack frame that doesn’t have unwind data, exception handling can’t proceed and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the process halts. There might be an exception handler further up the stack, but",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "without the unwind data for a frame, there’s no way to reach the exception handler",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "from the stack frame throwing the exception.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you find that exceptions thrown by your app within an exception handling domain",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "aren’t caught, verify that the build settings for your app and libraries allow the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "compiler to create the unwind tables:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Don’t specify the ",
                      "type": "text"
                    },
                    {
                      "code": "-no_compact_unwind",
                      "type": "codeVoice"
                    },
                    {
                      "text": " flag.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify the ",
                      "type": "text"
                    },
                    {
                      "code": "-funwind-tables",
                      "type": "codeVoice"
                    },
                    {
                      "text": " flag if you’re including plain C code.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/addressing-crashes-from-swift-runtime-errors": {
      "abstract": [
        {
          "text": "Identify the signs of a Swift runtime error, and address the crashes runtime errors",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "cause.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/addressing-crashes-from-swift-runtime-errors",
      "kind": "article",
      "role": "article",
      "title": "Addressing crashes from Swift runtime errors",
      "type": "topic",
      "url": "/documentation/xcode/addressing-crashes-from-swift-runtime-errors"
    },
    "doc://com.apple.Xcode/documentation/Xcode/addressing-language-exception-crashes#Identify-the-API-throwing-the-exception": {
      "abstract": [],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/addressing-language-exception-crashes#Identify-the-API-throwing-the-exception",
      "kind": "section",
      "title": "Identify the API throwing the exception",
      "type": "topic",
      "url": "/documentation/xcode/addressing-language-exception-crashes#Identify-the-API-throwing-the-exception"
    },
    "doc://com.apple.Xcode/documentation/Xcode/analyzing-a-crash-report": {
      "abstract": [
        {
          "text": "Identify clues in a crash report that help you diagnose problems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/analyzing-a-crash-report",
      "kind": "article",
      "role": "article",
      "title": "Analyzing a crash report",
      "type": "topic",
      "url": "/documentation/xcode/analyzing-a-crash-report"
    },
    "doc://com.apple.Xcode/documentation/Xcode/debugging": {
      "abstract": [
        {
          "text": "Identify and address issues in your app using the Xcode debugger, Xcode Organizer, Metal debugger, and Instruments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/debugging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Debugging",
      "type": "topic",
      "url": "/documentation/xcode/debugging"
    },
    "doc://com.apple.Xcode/documentation/Xcode/diagnosing-issues-using-crash-reports-and-device-logs": {
      "abstract": [
        {
          "text": "Use crash reports and device logs to debug app issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/diagnosing-issues-using-crash-reports-and-device-logs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Diagnosing issues using crash reports and device logs",
      "type": "topic",
      "url": "/documentation/xcode/diagnosing-issues-using-crash-reports-and-device-logs"
    },
    "doc://com.apple.Xcode/documentation/Xcode/identifying-the-cause-of-common-crashes": {
      "abstract": [
        {
          "text": "Find patterns in crash reports that identify common problems, and investigate the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "issue based on the pattern.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/identifying-the-cause-of-common-crashes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Identifying the cause of common crashes",
      "type": "topic",
      "url": "/documentation/xcode/identifying-the-cause-of-common-crashes"
    },
    "doc://com.apple.Xcode/documentation/Xcode/investigating-crashes-for-zombie-objects": {
      "abstract": [
        {
          "text": "Identify the signature of a zombie and investigate the cause of the crash.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/investigating-crashes-for-zombie-objects",
      "kind": "article",
      "role": "article",
      "title": "Investigating crashes for zombie objects",
      "type": "topic",
      "url": "/documentation/xcode/investigating-crashes-for-zombie-objects"
    },
    "doc://com.apple.Xcode/documentation/Xcode/reading-an-exception-message": {
      "abstract": [
        {
          "text": "Understand and address the common reasons apps crash.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/reading-an-exception-message",
      "kind": "article",
      "role": "article",
      "title": "Reading an exception message",
      "type": "topic",
      "url": "/documentation/xcode/reading-an-exception-message"
    },
    "doc://com.apple.documentation/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/AppKit"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIViewController/present(_:animated:completion:)": {
      "abstract": [
        {
          "text": "Presents a view controller modally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "viewControllerToPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "flag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")? = nil)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/present(_:animated:completion:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "present(_:animated:completion:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIViewController/present(_:animated:completion:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIViewController/viewDidLoad()": {
      "abstract": [
        {
          "text": "Called after the controller’s view is loaded into memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidLoad"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/viewDidLoad()",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewDidLoad()",
      "type": "topic",
      "url": "/documentation/UIKit/UIViewController/viewDidLoad()"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1418637-doesnotrecognizeselector": {
      "abstract": [
        {
          "text": "Handles messages the receiver doesn’t recognize.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "doesNotRecognizeSelector"
        },
        {
          "kind": "text",
          "text": "(Selector!)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1418637-doesnotrecognizeselector",
      "kind": "symbol",
      "role": "symbol",
      "title": "doesNotRecognizeSelector(_:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1418637-doesnotrecognizeselector"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://help.apple.com/xcode/mac/current/#/devfeaa874d0": {
      "identifier": "https://help.apple.com/xcode/mac/current/#/devfeaa874d0",
      "title": "Pause execution when events occur",
      "titleInlineContent": [
        {
          "text": "Pause",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "execution when events occur",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/xcode/mac/current/#/devfeaa874d0"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/analyzing-a-crash-report"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Runtime-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/addressing-crashes-from-swift-runtime-errors",
        "doc://com.apple.Xcode/documentation/Xcode/reading-an-exception-message"
      ],
      "title": "Runtime errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1viewDidLoad()/title",
          "value": "viewDidLoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1viewDidLoad()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "viewDidLoad"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11418637-doesnotrecognizeselector/title",
          "value": "doesNotRecognizeSelector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1present(_:animated:completion:)/title",
          "value": "presentViewController:animated:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1present(_:animated:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "presentViewController:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "viewControllerToPresent"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "animated:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "flag"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "completion:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)()) "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
