{
  "abstract": [
    {
      "text": "Identify the signature of an unresponsive app terminated by the watchdog, and address",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "the issue.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/debugging",
        "doc://com.apple.Xcode/documentation/Xcode/diagnosing-issues-using-crash-reports-and-device-logs",
        "doc://com.apple.Xcode/documentation/Xcode/identifying-the-cause-of-common-crashes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/addressing-watchdog-terminations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Addressing watchdog terminations"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Users expect apps to launch quickly, and are responsive to touches and gestures.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The operating system employs a watchdog that monitors launch times and app responsiveness,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and terminates unresponsive apps. Watchdog terminations use the code ",
              "type": "text"
            },
            {
              "code": "0x8badf00d",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "(pronounced “ate bad food”) in the Termination Reason of a crash report:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Exception Type:  EXC_CRASH (SIGKILL)",
            "Exception Codes: 0x0000000000000000, 0x0000000000000000",
            "Exception Note:  EXC_CORPSE_NOTIFY",
            "Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The watchdog terminates apps that block the main thread for a significant time. There",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "are many ways to block the main thread for an extended time, such as:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Synchronous networking",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Processing large amouts of data, such as large JSON files or 3D models",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Triggering lightweight migration for a large ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreData",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "store synchronously",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Analysis requests with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Vision",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To understand why blocking the main thread is an issue, consider the most common",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "example, loading data into the UI from a synchronous network call. If the main thread",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is busy with a network request, the system can’t handle UI events, such as multiple",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "scroll events, until after completing the network call. If the network call takes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a long time, there’s a significant time from when the user scrolls to when the app",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "responds to the scroll events. This makes the app feel unresponsive.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "addressing-watchdog-terminations-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Interpret-the-app-responsiveness-watchdog-information",
          "level": 3,
          "text": "Interpret the app responsiveness watchdog information",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When an app is slow to launch or respond to events, the termination information in",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the crash report contains important information about how the app spent its time.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, an iOS app that doesn’t render the UI quickly after launch has the following",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in the crash report:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Termination Description: SPRINGBOARD, ",
            "    scene-create watchdog transgression: application<com.example.MyCoolApp>:667",
            "    exhausted real (wall clock) time allowance of 19.97 seconds ",
            "    | ProcessVisibility: Foreground ",
            "    | ProcessState: Running ",
            "    | WatchdogEvent: scene-create ",
            "    | WatchdogVisibility: Foreground ",
            "    | WatchdogCPUStatistics: ( ",
            "    |  \"Elapsed total CPU time (seconds): 15.290 (user 15.290, system 0.000), 28% CPU\", ",
            "    |  \"Elapsed application CPU time (seconds): 0.367, 1% CPU\" ",
            "    | )"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "For readability, this example includes extra line breaks. In the original",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "crash report file for this example, the watchdog information is on fewer lines.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "When ",
              "type": "text"
            },
            {
              "code": "scene-create",
              "type": "codeVoice"
            },
            {
              "text": " appears in the ",
              "type": "text"
            },
            {
              "code": "Termination Description",
              "type": "codeVoice"
            },
            {
              "text": ", the app didn’t render",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the first frame of its UI to the screen within the allowed wall clock time. If ",
              "type": "text"
            },
            {
              "code": "scene-update",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "appears in the ",
              "type": "text"
            },
            {
              "code": "Termination Description",
              "type": "codeVoice"
            },
            {
              "text": " instead of ",
              "type": "text"
            },
            {
              "code": "scene-create",
              "type": "codeVoice"
            },
            {
              "text": ", the app didn’t",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "update its UI quick enough because the main thread is too busy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "code": "scene-create",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "scene-update",
                  "type": "codeVoice"
                },
                {
                  "text": " terminology used in the crash report",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "refers to any content drawn to the device’s screen. This terminology has no relation",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIScene",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " in a scene-based ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "Elapsed total CPU time",
              "type": "codeVoice"
            },
            {
              "text": " shows how much time the CPU ran for all processes on",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the system within the wall clock time. This CPU time, as well as the application",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "CPU time, is for the total CPU utilization across CPU cores, which can exceed 100%.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, if one CPU core is at 100% utilization and a second CPU core is at 20%",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "utilization, the total CPU utalization is 120%.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "Elapsed application CPU time",
              "type": "codeVoice"
            },
            {
              "text": " shows how much time the app spent running on the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "CPU within the wall clock time. If this number is at either extreme, it is a hint",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to the problem. If this number is high, the app is performing significant work across",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "all of its threads—the number aggregates all threads, and isn’t specific to the main",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "thread. If this number is low, the app is mostly idle, because it is waiting on system",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "resources, such as a network connection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Interpret-background-task-watchdog-information-watchOS",
          "level": 3,
          "text": "Interpret background task watchdog information (watchOS)",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to the app responsiveness watchdog, watchOS has a watchdog for background",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "tasks. In this example, an app didn’t complete handling a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchConnectivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "background task within the time allowance:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Termination Reason: CAROUSEL, WatchConnectivity watchdog transgression. ",
            "    Exhausted wall time allowance of 15.00 seconds.",
            "Termination Description: SPRINGBOARD,",
            "    CSLHandleBackgroundWCSessionAction watchdog transgression: xpcservice<com.example.MyCoolApp.watchkitapp.watchextension>:220:220 ",
            "    exhausted real (wall clock) time allowance of 15.00 seconds ",
            "    | <FBExtensionProcess: 0x16df02a0; xpcservice<com.example.MyCoolApp.watchkitapp.watchextension>:220:220; typeID: com.apple.watchkit> ",
            "      Elapsed total CPU time (seconds): 24.040 (user 24.040, system 0.000), 81% CPU ",
            "    | Elapsed application CPU time (seconds): 1.223, 6% CPU, lastUpdate 2020-01-20 11:56:01 +0000"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "For readability, this example includes extra line breaks. In the original",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "crash report file for this example, the watchdog information is on fewer lines.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Intrepret the information about wall clock time and CPU time as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/addressing-watchdog-terminations#Interpret-the-app-responsiveness-watchdog-information",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Identify-the-reason-the-watchdog-triggered",
          "level": 3,
          "text": "Identify the reason the watchdog triggered",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The backtraces are sometimes helpful in identifying what is taking so much time on",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the app’s main thread. For example, if an app uses synchronous networking on the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "main thread, networking functions are visible in the main thread’s backtrace.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Thread 0 name:  Dispatch queue: com.apple.main-thread",
            "Thread 0 Crashed:",
            "0   libsystem_kernel.dylib            0x00000001c22f8670 semaphore_wait_trap + 8",
            "1   libdispatch.dylib                 0x00000001c2195890 _dispatch_sema4_wait$VARIANT$mp + 24",
            "2   libdispatch.dylib                 0x00000001c2195ed4 _dispatch_semaphore_wait_slow + 140",
            "3   CFNetwork                         0x00000001c57d9d34 CFURLConnectionSendSynchronousRequest + 388",
            "4   CFNetwork                         0x00000001c5753988 +[NSURLConnection sendSynchronousRequest:returningResponse:error:] + 116  + 14728",
            "5   Foundation                        0x00000001c287821c -[NSString initWithContentsOfURL:usedEncoding:error:] + 256",
            "6   libswiftFoundation.dylib          0x00000001f7127284 NSString.__allocating_init+ 680580 (contentsOf:usedEncoding:) + 104",
            "7   libswiftFoundation.dylib          0x00000001f712738c String.init+ 680844 (contentsOf:) + 96",
            "8   MyCoolApp                         0x00000001009d31e0 ViewController.loadData() (in MyCoolApp) (ViewController.swift:21)"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "However, the main thread’s backtrace doesn’t always contain the source of the issue.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, imagine that your app needs exactly 4 seconds to complete a task out",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of a total allowed wall clock time of 5 seconds. When the watchdog terminates the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app after 5 seconds, the code that took 4 seconds won’t show up in the backtrace",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "because it completed, yet it consumed almost the entire time budget. The crash report",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instead records the backtrace frames of what the app was doing at the time the watchdog",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "terminated it, even though the recorded backtrace frames aren’t the source of the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "problem.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You may be able to use the information from all backtraces in the crash report to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "help identify where you are in the app’s launch process. By working backwards based",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on this information, you can identify what code already ran to narrow your investigation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to that code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition, profile your app’s performance during development to eliminate problems",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "before releasing the app, and monitor the app’s performance after the app is released.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/reducing-your-app-s-launch-time",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "provide more information on these techniques.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Identify-hidden-synchronous-networking-code",
          "level": 3,
          "text": "Identify hidden synchronous networking code",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Synchronous networking that blocks the main thread and leads to a watchdog termination",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "are sometimes hidden behind abstraction layers that mask the danger. The example",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "backtrace in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/addressing-watchdog-terminations#Identify-the-reason-the-watchdog-triggered",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "shows the app triggered the synchronous download by calling ",
              "type": "text"
            },
            {
              "code": "init(contentsOf:)",
              "type": "codeVoice"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with a ",
              "type": "text"
            },
            {
              "code": "https",
              "type": "codeVoice"
            },
            {
              "text": " URL, in frame 7. This API implicitly makes a synchronous network request",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "before returning from the initializer. Even if this initalizer completed quickly",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and wasn’t in the crash report, it still can contribute to a watchdog termination.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Other classes with an initalizer that takes a URL parameter, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/xmlparser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", behave in the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "same way.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Other common examples of hidden synchronous networking include the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SystemConfiguration/scnetworkreachability-g7d",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ",",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "the reachability API, operates synchronously by default. Seemingly innocuous functions",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "like ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SystemConfiguration/SCNetworkReachabilityGetFlags(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "can trigger a termination by the watchdog.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "DNS functions provided by BSD, like ",
                      "type": "text"
                    },
                    {
                      "code": "gethostbyname(_:)",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "gethostbyaddr(_:_:_:)",
                      "type": "codeVoice"
                    },
                    {
                      "text": ",",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "are never safe to call on the main thread. Functions like ",
                      "type": "text"
                    },
                    {
                      "code": "getnameinfo(_:_:_:_:_:_:_:)",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "and ",
                      "type": "text"
                    },
                    {
                      "code": "getaddrinfo(_:_:_:_:)",
                      "type": "codeVoice"
                    },
                    {
                      "text": " are only safe if you’re working exclusively with IP addresses",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "and not DNS names (that is, you specify ",
                      "type": "text"
                    },
                    {
                      "code": "AI_NUMERICHOST",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "NI_NUMERICHOST",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", respectively).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Synchronous networking issues depend a great deal on the network environment. If",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you always test your app in your office, where network connectivity is good, you’ll",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "never see this type of issue. However, once you start deploying your app to users—who",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "run apps in all sorts of network environments—synchronous networking problems become",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "common. In Xcode, you can simulate adverse network conditions to aid testing your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app under the conditions your users encounter. See ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/xcode/mac/current/#/dev308429d42",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Move-code-off-the-main-thread",
          "level": 3,
          "text": "Move code off the main thread",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Move all long-running code not essential to your app’s UI to a background queue.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "By moving this work to a background queue, the app’s main thread can complete the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app’s launch faster and process events quicker. Using a networking example, rather",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "than performing a synchronous network call on the main thread, move it to an asynchronous",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "background queue. By moving this work to a background queue, the main thread can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "process scroll events as they happen, allowing the app to be more responsive.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "addressing-watchdog-terminations-2",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the long-running code is from one of the system frameworks, determine whether",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the framework provides an alternate approach that moves the work off the main thread.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, consider loading a complex 3D model in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/RealityKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/RealityKit/Entity/loadAsync(contentsOf:withName:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instead of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/RealityKit/Entity/load(contentsOf:withName:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "which is synchronous. As a different example, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Vision",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "provides  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Vision/VNRequest/preferBackgroundProcessing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "which is a hint that the system should move processing of analysis requests off the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "main thread.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If networking code is contributing to your watchdog termination, consider these common",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "solutions:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Run your networking code asynchronously using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "This is the best solution. Asynchronous networking code has many advantages, including",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "accessing the network safely without having to worry about threads.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Instead of using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SystemConfiguration/scnetworkreachability-g7d",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ",",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Network/NWPathMonitor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to receive",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "updates when the network path changes. The system delivers updates on a queue that",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "you pass in when calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Network/NWPathMonitor/start(queue:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ",",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "so path updates function safely off the main thread.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Perform synchronous networking on a secondary thread. If it’s prohibitively difficult",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to run your networking code asynchronously, such as when using a large portable code",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "base that assumes synchronous networking, avoid the watchdog by running the synchronous",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "networking code on a secondary thread.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Resolving DNS manually isn’t recommended for most situations. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to have the system handle DNS resolution on your behalf. If it’s prohibitively difficult",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to switch and you continue to need to DNS addresses manually, use an asynchronous",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "API like ",
                      "type": "text"
                    },
                    {
                      "code": "CFHost",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or the APIs in ",
                      "type": "text"
                    },
                    {
                      "code": "<dns_sd.h>",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "addressing-watchdog-terminations-1": {
      "alt": "A timing diagram for the main thread showing UI scrolling events queued behind a long-running networking operation.",
      "identifier": "addressing-watchdog-terminations-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9358acb2a74668e16ec2237d70a571f5/addressing-watchdog-terminations-1@2x.png"
        }
      ]
    },
    "addressing-watchdog-terminations-2": {
      "alt": "A timing diagram with two threads, the main thread and a dispatch queue thread. The main thread uses the dispatch queue as an asynchronous thread for networking, allowing the main thread to handle scroll events while the network request is in progress. After the networking is complete, the resulting UI update is done on the main thread.",
      "identifier": "addressing-watchdog-terminations-2",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7a42f532e1752e43dece9417341fddc8/addressing-watchdog-terminations-2@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/addressing-watchdog-terminations#Identify-the-reason-the-watchdog-triggered": {
      "abstract": [],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/addressing-watchdog-terminations#Identify-the-reason-the-watchdog-triggered",
      "kind": "section",
      "title": "Identify the reason the watchdog triggered",
      "type": "topic",
      "url": "/documentation/xcode/addressing-watchdog-terminations#Identify-the-reason-the-watchdog-triggered"
    },
    "doc://com.apple.Xcode/documentation/Xcode/addressing-watchdog-terminations#Interpret-the-app-responsiveness-watchdog-information": {
      "abstract": [],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/addressing-watchdog-terminations#Interpret-the-app-responsiveness-watchdog-information",
      "kind": "section",
      "title": "Interpret the app responsiveness watchdog information",
      "type": "topic",
      "url": "/documentation/xcode/addressing-watchdog-terminations#Interpret-the-app-responsiveness-watchdog-information"
    },
    "doc://com.apple.Xcode/documentation/Xcode/analyzing-a-crash-report": {
      "abstract": [
        {
          "text": "Identify clues in a crash report that help you diagnose problems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/analyzing-a-crash-report",
      "kind": "article",
      "role": "article",
      "title": "Analyzing a crash report",
      "type": "topic",
      "url": "/documentation/xcode/analyzing-a-crash-report"
    },
    "doc://com.apple.Xcode/documentation/Xcode/debugging": {
      "abstract": [
        {
          "text": "Identify and address issues in your app using the Xcode debugger, Xcode Organizer, Metal debugger, and Instruments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/debugging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Debugging",
      "type": "topic",
      "url": "/documentation/xcode/debugging"
    },
    "doc://com.apple.Xcode/documentation/Xcode/diagnosing-issues-using-crash-reports-and-device-logs": {
      "abstract": [
        {
          "text": "Use crash reports and device logs to debug app issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/diagnosing-issues-using-crash-reports-and-device-logs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Diagnosing issues using crash reports and device logs",
      "type": "topic",
      "url": "/documentation/xcode/diagnosing-issues-using-crash-reports-and-device-logs"
    },
    "doc://com.apple.Xcode/documentation/Xcode/identifying-the-cause-of-common-crashes": {
      "abstract": [
        {
          "text": "Find patterns in crash reports that identify common problems, and investigate the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "issue based on the pattern.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/identifying-the-cause-of-common-crashes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Identifying the cause of common crashes",
      "type": "topic",
      "url": "/documentation/xcode/identifying-the-cause-of-common-crashes"
    },
    "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness": {
      "abstract": [
        {
          "text": "Create a user experience that feels responsive by removing hangs and hitches from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness",
      "kind": "article",
      "role": "article",
      "title": "Improving app responsiveness",
      "type": "topic",
      "url": "/documentation/xcode/improving-app-responsiveness"
    },
    "doc://com.apple.Xcode/documentation/Xcode/reducing-your-app-s-launch-time": {
      "abstract": [
        {
          "text": "Create a more responsive experience with your app by minimizing time spent in startup.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/reducing-your-app-s-launch-time",
      "kind": "article",
      "role": "article",
      "title": "Reducing your app’s launch time",
      "type": "topic",
      "url": "/documentation/xcode/reducing-your-app-s-launch-time"
    },
    "doc://com.apple.documentation/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/CoreData"
    },
    "doc://com.apple.documentation/documentation/Network/NWPathMonitor": {
      "abstract": [
        {
          "text": "An observer that you use to monitor and react to network changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWPathMonitor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network/NWPathMonitor",
      "kind": "symbol",
      "role": "symbol",
      "title": "NWPathMonitor",
      "type": "topic",
      "url": "/documentation/Network/NWPathMonitor"
    },
    "doc://com.apple.documentation/documentation/Network/NWPathMonitor/start(queue:)": {
      "abstract": [
        {
          "text": "Starts monitoring path changes, and sets a queue on which to deliver path events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network/NWPathMonitor/start(queue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "start(queue:)",
      "type": "topic",
      "url": "/documentation/Network/NWPathMonitor/start(queue:)"
    },
    "doc://com.apple.documentation/documentation/RealityKit": {
      "abstract": [
        {
          "text": "Simulate and render 3D content for use in your augmented reality apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit",
      "kind": "symbol",
      "role": "collection",
      "title": "RealityKit",
      "type": "topic",
      "url": "/documentation/RealityKit"
    },
    "doc://com.apple.documentation/documentation/RealityKit/Entity/load(contentsOf:withName:)": {
      "abstract": [
        {
          "text": "Returns an entity by synchronously loading it from a file URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentsOf"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "resourceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "? = nil) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation6EntityC",
          "text": "Entity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/Entity/load(contentsOf:withName:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "load(contentsOf:withName:)",
      "type": "topic",
      "url": "/documentation/RealityKit/Entity/load(contentsOf:withName:)"
    },
    "doc://com.apple.documentation/documentation/RealityKit/Entity/loadAsync(contentsOf:withName:)": {
      "abstract": [
        {
          "text": "Returns a load request that creates an entity by asynchronously loading it from a file URL and preserving the entity’s hierarchy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadAsync"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentsOf"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "resourceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "? = nil) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation11LoadRequestC",
          "text": "LoadRequest"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation6EntityC",
          "text": "Entity"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/Entity/loadAsync(contentsOf:withName:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadAsync(contentsOf:withName:)",
      "type": "topic",
      "url": "/documentation/RealityKit/Entity/loadAsync(contentsOf:withName:)"
    },
    "doc://com.apple.documentation/documentation/SystemConfiguration/SCNetworkReachabilityGetFlags(_:_:)": {
      "abstract": [
        {
          "text": "Determines if the specified network target is reachable using the current network configuration.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkReachabilityGetFlags"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkReachabilityRef",
          "text": "SCNetworkReachability"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SystemConfiguration/SCNetworkReachabilityGetFlags(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNetworkReachabilityGetFlags(_:_:)",
      "type": "topic",
      "url": "/documentation/SystemConfiguration/SCNetworkReachabilityGetFlags(_:_:)"
    },
    "doc://com.apple.documentation/documentation/SystemConfiguration/scnetworkreachability-g7d": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SystemConfiguration/scnetworkreachability-g7d",
      "kind": "article",
      "role": "article",
      "title": "SCNetworkReachability",
      "type": "topic",
      "url": "/documentation/SystemConfiguration/scnetworkreachability-g7d"
    },
    "doc://com.apple.documentation/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/UIKit"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIScene": {
      "abstract": [
        {
          "text": "An object that represents one instance of your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScene"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIScene",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIScene",
      "type": "topic",
      "url": "/documentation/UIKit/UIScene"
    },
    "doc://com.apple.documentation/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/Vision"
    },
    "doc://com.apple.documentation/documentation/Vision/VNRequest/preferBackgroundProcessing": {
      "abstract": [
        {
          "text": "A hint to minimize the resource burden of the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferBackgroundProcessing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Vision/VNRequest/preferBackgroundProcessing",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferBackgroundProcessing",
      "type": "topic",
      "url": "/documentation/Vision/VNRequest/preferBackgroundProcessing"
    },
    "doc://com.apple.documentation/documentation/WatchConnectivity": {
      "abstract": [
        {
          "text": "Implement two-way communication between an iOS app and its paired watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Watch Connectivity",
      "type": "topic",
      "url": "/documentation/WatchConnectivity"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdata": {
      "abstract": [
        {
          "text": "A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSData",
      "type": "topic",
      "url": "/documentation/foundation/nsdata"
    },
    "doc://com.apple.documentation/documentation/foundation/urlsession": {
      "abstract": [
        {
          "text": "An object that coordinates a group of related, network data transfer tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "URLSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession",
      "kind": "symbol",
      "role": "symbol",
      "title": "URLSession",
      "type": "topic",
      "url": "/documentation/foundation/urlsession"
    },
    "doc://com.apple.documentation/documentation/foundation/xmlparser": {
      "abstract": [
        {
          "text": "An event driven parser of XML documents (including DTD declarations).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "XMLParser"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/xmlparser",
      "kind": "symbol",
      "role": "symbol",
      "title": "XMLParser",
      "type": "topic",
      "url": "/documentation/foundation/xmlparser"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://help.apple.com/xcode/mac/current/#/dev308429d42": {
      "identifier": "https://help.apple.com/xcode/mac/current/#/dev308429d42",
      "title": "Test under adverse device conditions (iOS)",
      "titleInlineContent": [
        {
          "text": "Test under adverse device conditions",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "(iOS)",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/xcode/mac/current/#/dev308429d42"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/analyzing-a-crash-report"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Vision~1VNRequest~1preferBackgroundProcessing/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readwrite"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "preferBackgroundProcessing"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIScene/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIScene"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIResponder",
              "text": "UIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlsession/title",
          "value": "NSURLSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1xmlparser/title",
          "value": "NSXMLParser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SystemConfiguration~1SCNetworkReachabilityGetFlags(_:_:)/title",
          "value": "SCNetworkReachabilityGetFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SystemConfiguration~1SCNetworkReachabilityGetFlags(_:_:)/fragments",
          "value": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@Boolean",
              "text": "Boolean"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNetworkReachabilityGetFlags"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SCNetworkReachabilityRef",
              "text": "SCNetworkReachabilityRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "target"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
              "text": "SCNetworkReachabilityFlags"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdata/abstract",
          "value": [
            {
              "text": "A static byte buffer in memory.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
