{
  "abstract": [
    {
      "text": "Use universal links to link directly to content within your app and share data securely.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/projects-and-workspaces"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/allowing-apps-and-websites-to-link-to-your-content"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "collectionGroup",
    "title": "Allowing apps and websites to link to your content"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can connect to content deep inside your app with universal links. Users open",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app in a specified context, allowing them to accomplish their goals efficiently.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When users tap or click a universal link, the system redirects the link directly",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to your app without routing through the person’s default web browser or your website.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In addition, because",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "universal links are standard HTTP or HTTPS links, one URL works for both your website",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and your app. If the person hasn’t installed your app, the system opens the URL in",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "their default web browser, allowing your website to handle it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When someone installs your app, the system checks a file stored on your web server to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "verify that your website allows your app to open URLs on its behalf. Only you can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "store this file on your server, securing the association of your website and your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Support-universal-links",
          "level": 3,
          "text": "Support universal links",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Take the following steps to support universal links:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a two-way association between your app and your website and specify the",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "URLs that your app handles, as described in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.Xcode/documentation/Xcode/supporting-associated-domains",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Update your app delegate to respond to the user activity object the system provides",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "when a universal link routes to your app, as described in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.Xcode/documentation/Xcode/supporting-universal-links-in-your-app",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "With universal links, users open your app when they click links to your website within",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "their browser app and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WebKit/WKWebView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and when",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "they click links that result in a call to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/open(_:options:completionHandler:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "in iOS and tvOS",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKExtension/openSystemURL(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "in watchOS",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWorkspace/open(_:withApplicationAt:configuration:completionHandler:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " in",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "macOS",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/openURL",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "in SwiftUI",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If your app uses one of the above methods to open a universal link to your",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "website, the link won’t open in your app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "When a user browses your website in Safari and taps a universal link in the same",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "domain, the system opens that link in Safari, respecting the user’s most likely intent",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to continue within the browser. If the user taps a universal link in a different",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "domain, the system opens the link in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Communicate-with-other-apps",
          "level": 3,
          "text": "Communicate with other apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps can communicate through universal links. Supporting universal links allows other",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "apps to send small amounts of data directly to your app without using a third-party",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "server. ",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Define the parameters that your app handles within the URL query string. The following",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "example code for a photo library app specifies parameters that include the name of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "an album and the index of a photo to display.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "https://myphotoapp.example.com/albums?albumname=vacation&index=1",
            "https://myphotoapp.example.com/albums?albumname=wedding&index=17"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Other apps craft URLs based on your domain, path, and parameters and ask your app",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to open them by calling:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/open(_:options:completionHandler:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "method of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " in iOS",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "and tvOS",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKExtension/openSystemURL(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "method of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKExtension",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " in watchOS",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWorkspace/open(_:withApplicationAt:configuration:completionHandler:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "method of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWorkspace",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " in macOS",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/openURL",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "environment value in SwiftUI",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The calling app can ask the system to inform it when your app opens the URL.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In this example code, an app calls your universal link in iOS and tvOS:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if let appURL = URL(string: \"https://myphotoapp.example.com/albums?albumname=vacation&index=1\") {",
            "    UIApplication.shared.open(appURL) { success in",
            "        if success {",
            "            print(\"The URL was delivered successfully.\")",
            "        } else {",
            "            print(\"The URL failed to open.\")",
            "        }",
            "    }",
            "} else {",
            "    print(\"Invalid URL specified.\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In this example code, an app calls your universal link in watchOS:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if let appURL = URL(string: \"https://myphotoapp.example.com/albums?albumname=vacation&index=1\") {",
            "    WKExtension.shared().openSystemURL(appURL)",
            "} else {",
            "    print(\"Invalid URL specified.\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In this example code, an app calls your universal link in macOS:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if let appURL = URL(string: \"https://myphotoapp.example.com/albums?albumname=vacation&index=1\") {",
            "    let configuration = NSWorkspace.OpenConfiguration()",
            "    NSWorkspace.shared.open(appURL, configuration: configuration) { (app, error) in",
            "        guard error == nil else {",
            "            print(\"The URL failed to open.\")",
            "            return",
            "        }",
            "        print(\"The URL was delivered successfully.\")",
            "    }",
            "} else {",
            "    print(\"Invalid URL specified.\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on handling links within your app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/supporting-universal-links-in-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/defining-a-custom-url-scheme-for-your-app": {
      "abstract": [
        {
          "text": "Use specially formatted URLs to link to content within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/defining-a-custom-url-scheme-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Defining a custom URL scheme for your app",
      "type": "topic",
      "url": "/documentation/xcode/defining-a-custom-url-scheme-for-your-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/preparing-your-app-to-be-the-default-browser": {
      "abstract": [
        {
          "text": "Configure your browser app so users can set it as the default on their device",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "instead of Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/preparing-your-app-to-be-the-default-browser",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to be the default web browser",
      "type": "topic",
      "url": "/documentation/xcode/preparing-your-app-to-be-the-default-browser"
    },
    "doc://com.apple.Xcode/documentation/Xcode/projects-and-workspaces": {
      "abstract": [
        {
          "text": "Manage the code and resources you use to build apps, libraries, and other",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "software for Apple platforms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/projects-and-workspaces",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Projects and workspaces",
      "type": "topic",
      "url": "/documentation/xcode/projects-and-workspaces"
    },
    "doc://com.apple.Xcode/documentation/Xcode/supporting-associated-domains": {
      "abstract": [
        {
          "text": "Connect your app and a website to provide both a native app and a browser experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/supporting-associated-domains",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Supporting associated domains",
      "type": "topic",
      "url": "/documentation/xcode/supporting-associated-domains"
    },
    "doc://com.apple.Xcode/documentation/Xcode/supporting-universal-links-in-your-app": {
      "abstract": [
        {
          "text": "Prepare your app to respond to an incoming universal link.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/supporting-universal-links-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting universal links in your app",
      "type": "topic",
      "url": "/documentation/xcode/supporting-universal-links-in-your-app"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSWorkspace": {
      "abstract": [
        {
          "text": "A workspace that can launch other apps and perform a variety of file-handling services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWorkspace"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWorkspace",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWorkspace",
      "type": "topic",
      "url": "/documentation/AppKit/NSWorkspace"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSWorkspace/open(_:withApplicationAt:configuration:completionHandler:)": {
      "abstract": [
        {
          "text": "Opens one or more URLs asynchronously in the specified app using the provided options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "urls"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "withApplicationAt"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "applicationURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspace",
          "text": "NSWorkspace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWorkspaceOpenConfiguration",
          "text": "OpenConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRunningApplication",
          "text": "NSRunningApplication"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")? = nil)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSWorkspace/open(_:withApplicationAt:configuration:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "open(_:withApplicationAt:configuration:completionHandler:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSWorkspace/open(_:withApplicationAt:configuration:completionHandler:)"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/openURL": {
      "abstract": [
        {
          "text": "An action that opens a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI13OpenURLActionV",
          "text": "OpenURLAction"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/openURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "openURL",
      "type": "topic",
      "url": "/documentation/SwiftUI/EnvironmentValues/openURL"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps running in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplication",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplication"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplication/open(_:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Attempts to asynchronously open the resource at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIApplicationOpenExternalURLOptionsKey",
          "text": "OpenExternalURLOptionsKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "] = [:], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (@"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")? = nil)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/open(_:options:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "open(_:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplication/open(_:options:completionHandler:)"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKExtension": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for extension-based apps running in watchOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtension"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKExtension",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKExtension",
      "type": "topic",
      "url": "/documentation/WatchKit/WKExtension"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKExtension/openSystemURL(_:)": {
      "abstract": [
        {
          "text": "Opens the specified system URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openSystemURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKExtension/openSystemURL(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "openSystemURL(_:)",
      "type": "topic",
      "url": "/documentation/WatchKit/WKExtension/openSystemURL(_:)"
    },
    "doc://com.apple.documentation/documentation/WebKit/WKWebView": {
      "abstract": [
        {
          "text": "An object that displays interactive web content, such as for an in-app browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WebKit/WKWebView",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKWebView",
      "type": "topic",
      "url": "/documentation/WebKit/WKWebView"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Universal-links",
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/supporting-universal-links-in-your-app"
      ],
      "title": "Universal links"
    },
    {
      "anchor": "Associated-domains",
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/supporting-associated-domains"
      ],
      "title": "Associated domains"
    },
    {
      "anchor": "Custom-URLs",
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/defining-a-custom-url-scheme-for-your-app"
      ],
      "title": "Custom URLs"
    },
    {
      "anchor": "Default-apps",
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/preparing-your-app-to-be-the-default-browser"
      ],
      "title": "Default apps"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKExtension/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKExtension"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WebKit~1WKWebView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKWebView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSView",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplication/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIResponder",
              "text": "UIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplication~1open(_:options:completionHandler:)/title",
          "value": "openURL:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplication~1open(_:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "openURL:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURL",
              "text": "NSURL"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "url"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "completionHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:BFv(#b)",
              "text": "void (^)(_Bool)"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSWorkspace/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSWorkspace"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSWorkspace~1open(_:withApplicationAt:configuration:completionHandler:)/title",
          "value": "openURLs:withApplicationAtURL:configuration:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSWorkspace~1open(_:withApplicationAt:configuration:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "openURLs:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSURL *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "urls"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withApplicationAtURL:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURL",
              "text": "NSURL"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "applicationURL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configuration:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWorkspaceOpenConfiguration",
              "text": "NSWorkspaceOpenConfiguration"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "configuration"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "completionHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSRunningApplication",
              "text": "NSRunningApplication"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "app"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKExtension~1openSystemURL(_:)/title",
          "value": "openSystemURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKExtension~1openSystemURL(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "openSystemURL:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURL",
              "text": "NSURL"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "url"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
