{
  "abstract": [
    {
      "text": "Share user or app data among multiple instances of your app running on",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "different devices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/capabilities"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/configuring-icloud-services"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Configuring iCloud services"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As an app developer, you can use one or more iCloud services to securely store",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your users’ data on the iCloud servers and make it available across all",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of their iCloud-enabled devices, thereby providing a seamless experience",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "regardless of which device they use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode’s iCloud capability allows you to configure the following services:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Key-value storage provides your app with 1 MB of iCloud storage that can",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "contain up to 1024 key-value pairs, which is useful for syncing small amounts",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "of data, such as the user’s preferences. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsubiquitouskeyvaluestore",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "iCloud Documents allows your app to store data as files and sync those",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "files across devices, which is relevant if your app is already using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDocument",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSDocument",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/Chapters/DesigningForDocumentsIniCloud.html#//apple_ref/doc/uid/TP40012094-CH2",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "CloudKit allows your app to store structured objects and relationships in",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "remote databases and provides full control over those databases’ schemas. Users",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "can also choose to share their data with other iCloud users. You can use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CloudKit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "framework directly, or if your app uses Core Data to persist its data, leverage CloudKit to sync that data across devices. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "iCloud Documents and CloudKit both use ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "iCloud containers",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", although their",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "purpose differs depending on the service. For iCloud Documents, a container —",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "alternatively known as a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "ubiquity container",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " — serves as a local",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "representation of the corresponding iCloud storage and is a specialized",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "location on-disk where your app stores its files. For CloudKit, a container",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "isolates your app’s databases on the iCloud servers and manages their access",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and operations. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CloudKit/CKContainer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You can also use containers to share files and data between multiple apps",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "belonging to the same developer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before you can enable an iCloud service, follow the steps in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app#Add-a-capability",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "section of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to add the capability to your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app’s target, and select the iCloud capability from Xcode’s Capabilities",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "library. For watchOS apps with separate WatchKit extensions, add the capability",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to the WatchKit Extension target. To access a public iCloud database in your App Clip, add the capability to your App Clip target and be sure to read ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information about using iCloud services in your App Clip.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "icloud-services",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After you add the iCloud capability, Xcode updates your target’s entitlements",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "file to include the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-identifiers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "which is an array that comprises the containers you select. If Xcode",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "automatically manages your app’s signing, it also enables the iCloud capability",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for your app’s App ID in your developer account.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If you later remove the iCloud capability in Xcode, you must manually",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "update your App ID’s configuration in your developer account to disable iCloud.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Enable-one-or-more-iCloud-services",
          "level": 3,
          "text": "Enable one or more iCloud services",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Prior to using an iCloud service to sync your users’ data across their devices,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you must enable that service in Xcode to add the necessary entitlements to your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app’s entitlements file. Use the checkbox next to the service’s name in the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Services section of the iCloud capability to enable that service.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "key-value-storage",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Depending on the services you enable, Xcode adds the following additional",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "entitlements (if they’re not already present).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Service",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Entitlement",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Key-value storage",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "com.apple.developer.ubiquity-kvstore-identifier",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "iCloud Documents",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "com.apple.developer.icloud-services",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "com.apple.developer.ubiquity-container-identifiers",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "CloudKit",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "com.apple.developer.icloud-services",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ubiquity-kvstore-identifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.icloud-services",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Xcode automatically adds the Push Notifications capability to your",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "target if you enable the CloudKit service because CloudKit uses push",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "notifications to inform your app of server-side changes to your data. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CloudKit/remote-records",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Manage-your-apps-iCloud-containers",
          "level": 3,
          "text": "Manage your app’s iCloud containers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After adding the iCloud capability, Xcode retrieves any existing iCloud",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "containers from your developer account and displays them in the capability’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "configuration section. Use the Refresh button below the list to re-fetch your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "account’s iCloud containers at any time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "icloud-containers",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Enable one or more iCloud containers in the list using their checkboxes.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Conversely, uncheck a container’s checkbox to prevent your app from using it.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Xcode associates the selected iCloud containers with your app’s App ID in your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "developer account and makes the following changes to your app’s entitlements",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "file:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For apps that enable iCloud Documents, or both iCloud Documents and CloudKit,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Xcode updates the following entitlements to include the selected containers:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "code": "com.apple.developer.icloud-container-identifiers",
                              "type": "codeVoice"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "code": "com.apple.developer.ubiquity-container-identifiers",
                              "type": "codeVoice"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Xcode updates just the ",
                      "type": "text"
                    },
                    {
                      "code": "com.apple.developer.icloud-container-identifiers",
                      "type": "codeVoice"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "entitlement for apps that enable only CloudKit.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "To avoid breaking existing versions of your app that depend on the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "container association, Xcode doesn’t automatically dissociate a deselected",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "container from your App ID in your developer account.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To create a new iCloud container, perform the following steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Add button (+) below the iCloud containers list.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enter an iCloud container in the dialog that appears. You must begin the",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "container’s name with ",
                      "type": "text"
                    },
                    {
                      "code": "iCloud.",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and use a unique string in reverse DNS",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "notation.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click OK to save the new iCloud container.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "add-new-icloud-container",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode automatically registers the iCloud container in your developer account,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "adds it to your app’s entitlements file, and selects it in the list of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "containers, indicating that your app is now able to use the new container.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "selected-icloud-container",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After selecting the required containers, update your app to perform one or more",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For document-based apps, call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager/1411653-url",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to determine the location of your app’s ubiquity container.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For CloudKit apps, use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CloudKit/CKContainer/init(identifier:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to initialize an instance of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CloudKit/CKContainer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "that provides access to the container’s databases and executes operations",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "against those databases.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For Core Data apps that sync with CloudKit, use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreData/NSPersistentCloudKitContainerOptions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to configure your Core Data stack to use your new container.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Access-the-CloudKit-console",
          "level": 3,
          "text": "Access the CloudKit console",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your app enables the CloudKit service, use the web-based CloudKit Console to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "manage all aspects of your app’s iCloud containers, including the schemas for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "their databases, operation logs, and performance telemetry. For more",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CloudKit/managing-icloud-containers-with-cloudkit-database-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Follow these steps to access the CloudKit Console:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the CloudKit Console button below the list of containers in the iCloud",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "capability.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the browser window that opens, sign in to the CloudKit Console using the",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "same Apple Account as your developer account.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Alternatively, you can access the console directly at ",
              "type": "text"
            },
            {
              "identifier": "https://icloud.developer.apple.com",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "add-new-icloud-container": {
      "alt": "A screenshot of the Add a new container dialog that appears after you click the Add button. The dialog’s text explains that Xcode will create a new container if the named container doesn’t already exist, add it to your App ID, and add the new container to your app’s entitlements.",
      "identifier": "add-new-icloud-container",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/900cc747a92eb9a4f70dc8ad8d9233eb/add-new-icloud-container@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/29e79a607c021424ed580d4f70842200/add-new-icloud-container~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app": {
      "abstract": [
        {
          "text": "Configure your target to include and customize capabilities that provide access",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to Apple’s app services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding capabilities to your app",
      "type": "topic",
      "url": "/documentation/xcode/adding-capabilities-to-your-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app#Add-a-capability": {
      "abstract": [],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app#Add-a-capability",
      "kind": "section",
      "title": "Add a capability",
      "type": "topic",
      "url": "/documentation/xcode/adding-capabilities-to-your-app#Add-a-capability"
    },
    "doc://com.apple.Xcode/documentation/Xcode/capabilities": {
      "abstract": [
        {
          "text": "Enable services that Apple provides, such as In-App Purchase, Push Notifications,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Apple Pay, iCloud, and many others.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/capabilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Capabilities",
      "type": "topic",
      "url": "/documentation/xcode/capabilities"
    },
    "doc://com.apple.Xcode/documentation/Xcode/configuring-an-associated-domain": {
      "abstract": [
        {
          "text": "Create a two-way association between your app and your website to enable",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "universal links, Handoff, App Clips, and shared web credentials.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/configuring-an-associated-domain",
      "kind": "article",
      "role": "article",
      "title": "Configuring an associated domain",
      "type": "topic",
      "url": "/documentation/xcode/configuring-an-associated-domain"
    },
    "doc://com.apple.Xcode/documentation/Xcode/configuring-app-groups": {
      "abstract": [
        {
          "text": "Enable communication and data sharing between multiple installed apps created",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "by the same developer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/configuring-app-groups",
      "kind": "article",
      "role": "article",
      "title": "Configuring app groups",
      "type": "topic",
      "url": "/documentation/xcode/configuring-app-groups"
    },
    "doc://com.apple.documentation/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip": {
      "abstract": [
        {
          "text": "Review frameworks available to App Clips and identify functionality that makes a great App Clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip",
      "kind": "article",
      "role": "article",
      "title": "Choosing the right functionality for your App Clip",
      "type": "topic",
      "url": "/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSDocument": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for macOS documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSDocument",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDocument",
      "type": "topic",
      "url": "/documentation/AppKit/NSDocument"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-identifiers": {
      "abstract": [
        {
          "text": "The container identifiers for the iCloud production environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-identifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "iCloud Container Identifiers Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-identifiers"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.icloud-services": {
      "abstract": [
        {
          "text": "The iCloud services used by the app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.icloud-services",
      "kind": "symbol",
      "role": "symbol",
      "title": "iCloud Services Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.icloud-services"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ubiquity-kvstore-identifier": {
      "abstract": [
        {
          "text": "The container identifier to use for iCloud key-value storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.ubiquity-kvstore-identifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "iCloud Key-Value Store Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.ubiquity-kvstore-identifier"
    },
    "doc://com.apple.documentation/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/CloudKit"
    },
    "doc://com.apple.documentation/documentation/CloudKit/CKContainer": {
      "abstract": [
        {
          "text": "A conduit to your app’s databases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CloudKit/CKContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKContainer",
      "type": "topic",
      "url": "/documentation/CloudKit/CKContainer"
    },
    "doc://com.apple.documentation/documentation/CloudKit/CKContainer/init(identifier:)": {
      "abstract": [
        {
          "text": "Creates a container for the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "containerIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CloudKit/CKContainer/init(identifier:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(identifier:)",
      "type": "topic",
      "url": "/documentation/CloudKit/CKContainer/init(identifier:)"
    },
    "doc://com.apple.documentation/documentation/CloudKit/managing-icloud-containers-with-cloudkit-database-app": {
      "abstract": [
        {
          "text": "Inspect and modify the schema and data for your app’s iCloud container.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CloudKit/managing-icloud-containers-with-cloudkit-database-app",
      "kind": "article",
      "role": "article",
      "title": "Managing iCloud Containers with CloudKit Database App",
      "type": "topic",
      "url": "/documentation/CloudKit/managing-icloud-containers-with-cloudkit-database-app"
    },
    "doc://com.apple.documentation/documentation/CloudKit/remote-records": {
      "abstract": [
        {
          "text": "Use subscriptions and change tokens to efficiently manage modifications to remote records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CloudKit/remote-records",
      "kind": "article",
      "role": "article",
      "title": "Remote Records",
      "type": "topic",
      "url": "/documentation/CloudKit/remote-records"
    },
    "doc://com.apple.documentation/documentation/CoreData/NSPersistentCloudKitContainerOptions": {
      "abstract": [
        {
          "text": "An object that customizes how a store description aligns with a CloudKit database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainerOptions"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreData/NSPersistentCloudKitContainerOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentCloudKitContainerOptions",
      "type": "topic",
      "url": "/documentation/CoreData/NSPersistentCloudKitContainerOptions"
    },
    "doc://com.apple.documentation/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit": {
      "abstract": [
        {
          "text": "Back user interfaces with a local replica of a CloudKit private database.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit",
      "kind": "article",
      "role": "article",
      "title": "Mirroring a Core Data store with CloudKit",
      "type": "topic",
      "url": "/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIDocument": {
      "abstract": [
        {
          "text": "An abstract base class for managing discrete portions of your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDocument",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIDocument",
      "type": "topic",
      "url": "/documentation/UIKit/UIDocument"
    },
    "doc://com.apple.documentation/documentation/foundation/filemanager/1411653-url": {
      "abstract": [
        {
          "text": "Returns the URL for the iCloud container associated with the specified identifier and establishes access to that container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "forUbiquityContainerIdentifier"
        },
        {
          "kind": "text",
          "text": ": String?) -> URL?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager/1411653-url",
      "kind": "symbol",
      "role": "symbol",
      "title": "url(forUbiquityContainerIdentifier:)",
      "type": "topic",
      "url": "/documentation/foundation/filemanager/1411653-url"
    },
    "doc://com.apple.documentation/documentation/foundation/nsubiquitouskeyvaluestore": {
      "abstract": [
        {
          "text": "An iCloud-based container of key-value pairs you use to share data among instances of your app running on a user's connected devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSUbiquitousKeyValueStore"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsubiquitouskeyvaluestore",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUbiquitousKeyValueStore",
      "type": "topic",
      "url": "/documentation/foundation/nsubiquitouskeyvaluestore"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/Chapters/DesigningForDocumentsIniCloud.html#//apple_ref/doc/uid/TP40012094-CH2": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/Chapters/DesigningForDocumentsIniCloud.html#//apple_ref/doc/uid/TP40012094-CH2",
      "title": "Designing for Documents in iCloud",
      "titleInlineContent": [
        {
          "text": "Designing for Documents in iCloud",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/Chapters/DesigningForDocumentsIniCloud.html#//apple_ref/doc/uid/TP40012094-CH2"
    },
    "https://icloud.developer.apple.com": {
      "identifier": "https://icloud.developer.apple.com",
      "title": "icloud.developer.apple.com",
      "titleInlineContent": [
        {
          "text": "icloud.developer.apple.com",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://icloud.developer.apple.com"
    },
    "icloud-containers": {
      "alt": "A screenshot of the iCloud capability after you add it to your target. The Key-value storage, iCloud Documents, and CloudKit services are each in a disabled state. The containers list displays three fetched iCloud containers, none of which are in an enabled state.",
      "identifier": "icloud-containers",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1bb11a948f39306d683947272c12f550/icloud-containers@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ea96ef83e7bf47e38e6bca0f0d84c4d5/icloud-containers~dark@2x.png"
        }
      ]
    },
    "icloud-services": {
      "alt": "A screenshot of Xcode’s Capabilities library with a list of available capabilities on the left and an information pane on the right. The list shows a range of capabilities from iCloud to Network Extensions, and the iCloud capability is in a selected state. The text on the information pane explains that the iCloud storage APIs enable your apps to store data and documents in iCloud, keeping your apps up to date automatically, and providing your users with a consistent and seamless experience across their iCloud-enabled devices.",
      "identifier": "icloud-services",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8bcbe9e18681fa99d72a732b826ca708/icloud-services@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/011d97aaffd6698c11adf1aa818c1583/icloud-services~dark@2x.png"
        }
      ]
    },
    "key-value-storage": {
      "alt": "A screenshot of the iCloud capability after you add it to your target. The Key-value storage service is in an enabled state.",
      "identifier": "key-value-storage",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c0b9ac8ac16188b10123d3fc3488d6da/key-value-storage@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/dd2b9015656b5f32bc029e940260b2db/key-value-storage~dark@2x.png"
        }
      ]
    },
    "selected-icloud-container": {
      "alt": "A screenshot of the iCloud capability after you add it to your target. The iCloud Documents service is in an enabled state, and a single iCloud container is in a selected state.",
      "identifier": "selected-icloud-container",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/648730c820dfdb595f4d3da084d8f7bc/selected-icloud-container@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/63d4918bf3baa3923fb7963c8493f186/selected-icloud-container~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/configuring-an-associated-domain",
        "doc://com.apple.Xcode/documentation/Xcode/configuring-app-groups"
      ],
      "title": "Data management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1filemanager~11411653-url/title",
          "value": "URLForUbiquityContainerIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CloudKit~1CKContainer~1init(identifier:)/title",
          "value": "containerWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CloudKit~1CKContainer~1init(identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKContainer",
              "text": "CKContainer"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "containerWithIdentifier:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "containerIdentifier"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIDocument/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIDocument"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSDocument/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDocument"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreData~1NSPersistentCloudKitContainerOptions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerOptions"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CloudKit~1CKContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKContainer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
