{
  "abstract": [
    {
      "text": "Access the user’s Wallet to add, update, and display your app’s passes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/capabilities"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/configuring-wallet-support"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Configuring Wallet support"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Wallet app on iOS and watchOS allows users to organize their ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "passes",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " —",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "tickets, gift cards, loyalty cards, boarding passes, and the payment cards they",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "use with Apple Pay. By integrating with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PassKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app can access any related passes and allow the user to manage them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To use Wallet in your app, add the capability by configuring your app’s target",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in Xcode and, optionally, specify which pass types your app supports. Follow",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the instructions in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app#Add-a-capability",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "section of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When you reach the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Capabilities library, choose Wallet. For watchOS apps with separate WatchKit",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "extensions, add the capability to the WatchKit Extension’s target. The capability",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "isn’t available for macOS or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "tvOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "wallet",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After you add the Wallet capability, Xcode updates your target’s entitlements",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "file to include the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "— an array containing the single wildcard value ",
              "type": "text"
            },
            {
              "code": "$(TeamIdentifierPrefix)*",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This value allows your app to access passes of every pass type that you define",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in your developer account; use the configuration options of the capability to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "narrow the scope of accessible pass types to only those your app requires.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The capability fetches and displays the pass type identifiers you",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "register in your developer account; Xcode doesn’t provide a way to register them",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "locally. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/help/account/configure-app-capabilities/create-wallet-identifiers-and-certificates",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Restrict-your-app-to-a-subset-of-pass-types",
          "level": 3,
          "text": "Restrict your app to a subset of pass types",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To minimize potential security risks and help protect the user’s privacy,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "follow these steps to provide your app with access to only the pass type",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "identifiers it requires to function properly:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select your project in Xcode’s Project navigator.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the app’s target from the Targets list.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Signing & Capabilities tab in the project editor.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Find the Wallet capability.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the “Enable subset of pass types” option.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Xcode enables all pass type identifiers by default; disable individual",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "identifiers by unchecking their checkboxes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "subset-of-pass-types",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode updates the ",
              "type": "text"
            },
            {
              "code": "com.apple.developer.pass-type-identifiers",
              "type": "codeVoice"
            },
            {
              "text": " array in the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app’s entitlements file to include only the enabled pass type identifiers, and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "if present, removes the wildcard value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After enabling the required pass type identifiers, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PassKit/PKPassLibrary/passes()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PassKit/PKPassLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to retrieve the passes accessible to your app, or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to fetch a specific pass. For more information on creating, distributing, and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "updating passes, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WalletPasses",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app": {
      "abstract": [
        {
          "text": "Configure your target to include and customize capabilities that provide access",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to Apple’s app services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding capabilities to your app",
      "type": "topic",
      "url": "/documentation/xcode/adding-capabilities-to-your-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app#Add-a-capability": {
      "abstract": [],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app#Add-a-capability",
      "kind": "section",
      "title": "Add a capability",
      "type": "topic",
      "url": "/documentation/xcode/adding-capabilities-to-your-app#Add-a-capability"
    },
    "doc://com.apple.Xcode/documentation/Xcode/capabilities": {
      "abstract": [
        {
          "text": "Enable services that Apple provides, such as In-App Purchase, Push Notifications,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Apple Pay, iCloud, and many others.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/capabilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Capabilities",
      "type": "topic",
      "url": "/documentation/xcode/capabilities"
    },
    "doc://com.apple.Xcode/documentation/Xcode/configuring-apple-pay-support": {
      "abstract": [
        {
          "text": "Process payments in your app using the payment information the user stores on",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/configuring-apple-pay-support",
      "kind": "article",
      "role": "article",
      "title": "Configuring Apple Pay support",
      "type": "topic",
      "url": "/documentation/xcode/configuring-apple-pay-support"
    },
    "doc://com.apple.Xcode/documentation/Xcode/configuring-sign-in-with-apple": {
      "abstract": [
        {
          "text": "Allow users to create an account and sign in to your app with their Apple Account.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/configuring-sign-in-with-apple",
      "kind": "article",
      "role": "article",
      "title": "Configuring Sign in with Apple support",
      "type": "topic",
      "url": "/documentation/xcode/configuring-sign-in-with-apple"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers": {
      "abstract": [
        {
          "text": "A list of identifiers that specify pass types that your app can access in Wallet.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "Pass Type IDs Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers"
    },
    "doc://com.apple.documentation/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/PassKit"
    },
    "doc://com.apple.documentation/documentation/PassKit/PKPassLibrary": {
      "abstract": [
        {
          "text": "Provides an interface to the user’s library of passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibrary"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PassKit/PKPassLibrary",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKPassLibrary",
      "type": "topic",
      "url": "/documentation/PassKit/PKPassLibrary"
    },
    "doc://com.apple.documentation/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)": {
      "abstract": [
        {
          "text": "Returns the pass with the specified pass type identifier and serial number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPassTypeIdentifier"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "serialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "pass(withPassTypeIdentifier:serialNumber:)",
      "type": "topic",
      "url": "/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)"
    },
    "doc://com.apple.documentation/documentation/PassKit/PKPassLibrary/passes()": {
      "abstract": [
        {
          "text": "Returns the passes in the user’s pass library that the app can access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PassKit/PKPassLibrary/passes()",
      "kind": "symbol",
      "role": "symbol",
      "title": "passes()",
      "type": "topic",
      "url": "/documentation/PassKit/PKPassLibrary/passes()"
    },
    "doc://com.apple.documentation/documentation/WalletPasses": {
      "abstract": [
        {
          "text": "Create, distribute, and update passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WalletPasses",
      "kind": "symbol",
      "role": "collection",
      "title": "Wallet Passes",
      "type": "topic",
      "url": "/documentation/WalletPasses"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/help/account/configure-app-capabilities/create-wallet-identifiers-and-certificates": {
      "identifier": "https://developer.apple.com/help/account/configure-app-capabilities/create-wallet-identifiers-and-certificates",
      "title": "Create Wallet identifiers and certificates",
      "titleInlineContent": [
        {
          "text": "Create Wallet identifiers and certificates",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/account/configure-app-capabilities/create-wallet-identifiers-and-certificates"
    },
    "subset-of-pass-types": {
      "alt": "A screenshot of the Wallet capability after you add it to an app’s target. The Allow subset of pass types option is in an enabled state, as are two of the three listed pass type identifiers.",
      "identifier": "subset-of-pass-types",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d40f513c0ae43a77a40ec87f2187f868/subset-of-pass-types@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4db262d5359f842f8e3afde9ad76ea78/subset-of-pass-types~dark@2x.png"
        }
      ]
    },
    "wallet": {
      "alt": "A screenshot of Xcode’s Capabilities library. At the top is a filter button next to a search field that contains the placeholder text Capabilities. Below that, in the left pane, there’s a list of capabilities, such as Network Extensions, Siri, and Wallet. The Wallet capability is in a selected state. On the right, there’s an information pane that contains the text Wallet gives users a way to organize passes, tickets, gift cards, credit cards and loyalty cards. Use the PassKit framework APIs to display, add, or update items in your users’ Wallets.",
      "identifier": "wallet",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/82b23f93b839a1ee3d5d8904cf391802/wallet@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/85f6272f3e96853e1f51d1243109fb66/wallet~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Commerce",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/configuring-apple-pay-support",
        "doc://com.apple.Xcode/documentation/Xcode/configuring-sign-in-with-apple"
      ],
      "title": "Commerce"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PassKit~1PKPassLibrary~1pass(withPassTypeIdentifier:serialNumber:)/title",
          "value": "passWithPassTypeIdentifier:serialNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PassKit~1PKPassLibrary~1pass(withPassTypeIdentifier:serialNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKPass",
              "text": "PKPass"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "passWithPassTypeIdentifier:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "identifier"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "serialNumber:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "serialNumber"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PassKit~1PKPassLibrary/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PassKit~1PKPassLibrary~1passes()/title",
          "value": "passes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PassKit~1PKPassLibrary~1passes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<PKPass *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "passes"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
