{
  "abstract": [
    {
      "text": "Share keychain items between multiple apps belonging to the same developer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/capabilities"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/configuring-keychain-sharing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Configuring keychain sharing"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Sharing keychain items between multiple targets of the same app, or between",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "different apps that belong to the same developer, relies on the concept of an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "access group",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " — a collection of targets that all share a common keychain",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "group. When a particular target wants to make a keychain item accessible to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the rest of the access group, it specifies the shared keychain group when",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "writing that item to the keychain, which can be useful for apps that need to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "share account credentials and other sensitive information. For more",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/sharing-access-to-keychain-items-among-a-collection-of-apps",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before you make a keychain group accessible to your target, follow the steps",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app#Add-a-capability",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " section of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to add the Keychain Sharing capability to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that target. For watchOS apps with separate WatchKit extensions, add the capability",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to the WatchKit Extension target.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "keychain-sharing",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If not already present, Xcode updates your target’s entitlements file to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "include the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/keychain-access-groups",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "which is an array that contains each keychain group you specify.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Make-a-keychain-group-accessible-to-your-target",
          "level": 3,
          "text": "Make a keychain group accessible to your target",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you want two (or more) targets to share common keychain items, make the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "same keychain group accessible to both by following these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select your project in Xcode’s Project navigator.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the app’s target from the Targets list.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Signing & Capabilities tab in the project editor.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Find the Keychain Sharing capability.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Add (+) button below the Keychain Groups list.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Double-click the inserted keychain group to edit it.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enter a name for the keychain group: either the name of an existing group",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "that’s already in use by your other apps, or a brand new group. For new groups,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "use reverse DNS notation for the name.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Press the Return key to save the updated keychain group.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "keychain-groups",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Although not visible, Xcode prepends the name of each keychain group",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "with the ",
                  "type": "text"
                },
                {
                  "code": "$(AppIdentifierPrefix)",
                  "type": "codeVoice"
                },
                {
                  "text": " build variable, which it automatically",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "resolves at build time.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "After you make a keychain group accessible to your target, you can later revoke",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that access by selecting the appropriate keychain group and clicking the Remove",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "button (-) below the Keychain Groups list.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Keychain groups you specify are then available to use with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/keychain-services",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "APIs, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/SecItemAdd(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/SecItemCopyMatching(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Specify-the-default-keychain-group",
          "level": 3,
          "text": "Specify the default keychain group",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "During compilation, the system determines the canonical list of keychain groups",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "accessible to your app by concatenating the groups you specify with the app’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "unique application identifier and any App Groups you configure; the system",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "considers the first item in that list as the default keychain",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "group. If you omit the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/kSecAttrAccessGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "attribute when writing keychain items, the system automatically populates that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "attribute with the default keychain group, and therefore the order in which you",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "specify your keychain groups matters.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To change the order of your keychain groups, follow these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the Project navigator, Control-click your target’s entitlements file.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose Open As > Property List.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Expand the Keychain Access Groups key.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Drag the array’s nested items into your preferred order. Each item’s value",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "is the name of a keychain group.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "keychain-groups-plist",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After making changes to the order, choose File > Save to store those changes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and cause Xcode to update the order it displays the groups in the target’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Signing & Capabilities tab.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Although you can use an App Group to share keychain items, it can never",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "be the default keychain group because the app’s unique application identifier",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "always takes precedence.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app": {
      "abstract": [
        {
          "text": "Configure your target to include and customize capabilities that provide access",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to Apple’s app services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding capabilities to your app",
      "type": "topic",
      "url": "/documentation/xcode/adding-capabilities-to-your-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app#Add-a-capability": {
      "abstract": [],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/adding-capabilities-to-your-app#Add-a-capability",
      "kind": "section",
      "title": "Add a capability",
      "type": "topic",
      "url": "/documentation/xcode/adding-capabilities-to-your-app#Add-a-capability"
    },
    "doc://com.apple.Xcode/documentation/Xcode/capabilities": {
      "abstract": [
        {
          "text": "Enable services that Apple provides, such as In-App Purchase, Push Notifications,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Apple Pay, iCloud, and many others.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/capabilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Capabilities",
      "type": "topic",
      "url": "/documentation/xcode/capabilities"
    },
    "doc://com.apple.Xcode/documentation/Xcode/configuring-the-hardened-runtime": {
      "abstract": [
        {
          "text": "Protect the runtime integrity of your macOS app by restricting access to",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "sensitive resources and preventing common exploits.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/configuring-the-hardened-runtime",
      "kind": "article",
      "role": "article",
      "title": "Configuring the hardened runtime",
      "type": "topic",
      "url": "/documentation/xcode/configuring-the-hardened-runtime"
    },
    "doc://com.apple.Xcode/documentation/Xcode/configuring-the-macos-app-sandbox": {
      "abstract": [
        {
          "text": "Protect system resources and user data from compromised apps by restricting",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "access to the file system, network connections, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/configuring-the-macos-app-sandbox",
      "kind": "article",
      "role": "article",
      "title": "Configuring the macOS App Sandbox",
      "type": "topic",
      "url": "/documentation/xcode/configuring-the-macos-app-sandbox"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/keychain-access-groups": {
      "abstract": [
        {
          "text": "The identifiers for the keychain groups that the app may share items with.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/keychain-access-groups",
      "kind": "symbol",
      "role": "symbol",
      "title": "Keychain Access Groups Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/keychain-access-groups"
    },
    "doc://com.apple.documentation/documentation/Security/SecItemAdd(_:_:)": {
      "abstract": [
        {
          "text": "Adds one or more items to a keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "result"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/SecItemAdd(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecItemAdd(_:_:)",
      "type": "topic",
      "url": "/documentation/Security/SecItemAdd(_:_:)"
    },
    "doc://com.apple.documentation/documentation/Security/SecItemCopyMatching(_:_:)": {
      "abstract": [
        {
          "text": "Returns one or more keychain items that match a search query, or copies attributes of specific keychain items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecItemCopyMatching"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "query"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "result"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/SecItemCopyMatching(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecItemCopyMatching(_:_:)",
      "type": "topic",
      "url": "/documentation/Security/SecItemCopyMatching(_:_:)"
    },
    "doc://com.apple.documentation/documentation/Security/kSecAttrAccessGroup": {
      "abstract": [
        {
          "text": "A key with a value that’s a string indicating the access group the item is in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrAccessGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/kSecAttrAccessGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAttrAccessGroup",
      "type": "topic",
      "url": "/documentation/Security/kSecAttrAccessGroup"
    },
    "doc://com.apple.documentation/documentation/Security/keychain-services": {
      "abstract": [
        {
          "text": "Securely store small chunks of data on behalf of the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/keychain-services",
      "kind": "article",
      "role": "article",
      "title": "Keychain services",
      "type": "topic",
      "url": "/documentation/Security/keychain-services"
    },
    "doc://com.apple.documentation/documentation/Security/sharing-access-to-keychain-items-among-a-collection-of-apps": {
      "abstract": [
        {
          "text": "Enable apps to share keychain items with each other by adding the apps to an access group.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/sharing-access-to-keychain-items-among-a-collection-of-apps",
      "kind": "article",
      "role": "article",
      "title": "Sharing access to keychain items among a collection of apps",
      "type": "topic",
      "url": "/documentation/Security/sharing-access-to-keychain-items-among-a-collection-of-apps"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "keychain-groups": {
      "alt": "A screenshot of the Keychain Sharing capability after you add it to your target. The keychain groups list contains a single group.",
      "identifier": "keychain-groups",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/bc8d98c20389dfd854e14e1a17cf8cc0/keychain-groups@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3110f77f9bf8f879babac362fe272992/keychain-groups~dark@2x.png"
        }
      ]
    },
    "keychain-groups-plist": {
      "alt": "A screenshot of an app’s entitlements file open in Xcode’s plist editor. The Keychain Access Groups key is in an expanded state and contains two items, each representing a different keychain group.",
      "identifier": "keychain-groups-plist",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5c2ba158371103293a4c2e2ae4831446/keychain-groups-plist@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/066eb7fe78a17dd795aed55cd3d0fab1/keychain-groups-plist~dark@2x.png"
        }
      ]
    },
    "keychain-sharing": {
      "alt": "A screenshot of Xcode’s Capabilities library. The Keychain Sharing capability is in a selected state.",
      "identifier": "keychain-sharing",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/baeac8be2089a59935ee8ccb1b77a9fc/keychain-sharing@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8c4ec23bc3edf50290b2ba5b1022e078/keychain-sharing~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Security",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/configuring-the-hardened-runtime",
        "doc://com.apple.Xcode/documentation/Xcode/configuring-the-macos-app-sandbox"
      ],
      "title": "Security"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecItemAdd(_:_:)/title",
          "value": "SecItemAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecItemAdd(_:_:)/fragments",
          "value": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecItemAdd"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionaryRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attributes"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "result"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1kSecAttrAccessGroup/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSecAttrAccessGroup"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecItemCopyMatching(_:_:)/title",
          "value": "SecItemCopyMatching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecItemCopyMatching(_:_:)/fragments",
          "value": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecItemCopyMatching"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionaryRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "query"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "result"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
