{
  "abstract": [
    {
      "text": "Diagnose potential performance issues in your app during testing with the Thread Performance Checker tool in Xcode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/performance-and-metrics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/diagnosing-performance-issues-early"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Diagnosing performance issues early"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Identifying potential performance issues during development saves testing time later. Resolving performance",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "issues, such as priority inversions and non-UI work on the main thread, makes your app",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "responsive. Priority inversions occur when a low-priority thread blocks a higher-priority",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "thread, which can lead to an unresponsive app. Similarly, non-UI work, such as synchronous",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "networking or I/O on the main thread, can block the main thread for hundreds of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "milliseconds, which prevents people from interacting with your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Thread Performance Checker tool detects priority inversions and non-UI work on the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "main thread. It doesn’t require any recompilation. Use the Thread Performance Checker tool",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to detect, diagnose, and resolve performance issues.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Understand-the-detected-issues",
          "level": 3,
          "text": "Understand the detected issues",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Thread Performance Checker tool surfaces issues in the Issue navigator and the source editor. Read the diagnostic message carefully.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "diagnosing-performance-issues-early-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To understand the issue in depth, expand the backtrace of the issue in the Issue navigator.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "diagnosing-performance-issues-early-2",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The issues surfaced point to code in your project that can cause hangs. Hangs",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "occur when your app is unresponsive for hundreds of milliseconds. To learn more about hangs,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and the WWDC session video",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/videos/play/wwdc2021/10258/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Diagnose-and-resolve-priority-inversions",
          "level": 3,
          "text": "Diagnose and resolve priority inversions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you use concurrency primitives, such as",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/dispatch/1453087-dispatch_semaphore_wait",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/dispatch/1452794-dispatch_group_wait",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", in",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your code or invoke APIs that use them, your app is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "susceptible to priority inversions if there is a mismatch in the quality-of-service (QoS)",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "class of the dispatch queues your app uses. When you",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "use these primitives, the system can’t automatically propagate priority from the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "higher-priority thread to the lower-priority thread. You can take these precautions to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "avoid priority inversions in your code:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Don’t use ",
                      "type": "text"
                    },
                    {
                      "code": "dispatch_semaphore_wait",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "dispatch_group_wait",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "emulate synchronous behavior when calling an asynchronous",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "internal method or API. Remove the code if the underlying functionality is",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "unnecessary.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Ensure that the QoS of the waiting thread is the same as or lower than the QoS of",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "the signaling thread when a synchronous variant isn’t available.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Explicitly classify the QoS of the work when you create a",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Dispatch/dispatch-queue",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or an",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsoperationqueue",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The code in ",
              "type": "text"
            },
            {
              "code": "initiateBackgroundWork",
              "type": "codeVoice"
            },
            {
              "text": " below explicitly creates a dispatch queue with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "background QoS. ",
              "type": "text"
            },
            {
              "code": "doBackgroundWorkAsync",
              "type": "codeVoice"
            },
            {
              "text": " signals the completion of the background work it",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "does asynchronously at background QoS. After the background work completes, it updates",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the UI label on the main thread at ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Dispatch/DispatchQoS/userInteractive",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "QoS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func initiateBackgroundWork() {",
            "    let dispatchSemaphore = DispatchSemaphore(value: 0)",
            "    let backgroundQueue = DispatchQueue(label: \"background_queue\", ",
            "                                        qos: .background)",
            "    ",
            "    backgroundQueue.async {",
            "        // Perform work on a separate thread using the quality-of-service level ",
            "        // for background maintenance or cleanup tasks and signal when the work completes.",
            "       doBackgroundWorkAsync {",
            "           dispatchSemaphore.signal()",
            "       }",
            "       ",
            "       _ = dispatchSemaphore.wait(timeout: DispatchTime.distantFuture)",
            "       ",
            "       DispatchQueue.main.async { [weak self] in",
            "           self?.label.text = \"Background work completed\"",
            "       }",
            "    })",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To learn more about priority inversions and QoS, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/videos/play/wwdc2017/706/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Diagnose-and-eliminate-non-UI-work-on-the-main-thread",
          "level": 3,
          "text": "Diagnose and eliminate non-UI work on the main thread",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Long-running synchronous I/O and networking on the main thread can make your app unresponsive. For example, to perform",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "real-time capture, you instantiate an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and add",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "appropriate inputs and outputs. Invoking the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureSession/startRunning()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method of an ",
              "type": "text"
            },
            {
              "code": "AVCaptureSession",
              "type": "codeVoice"
            },
            {
              "text": " object on the main thread of your app can lead to hangs.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You can take these precautions to avoid non-UI work on the main thread:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Don’t synchronously read from or write to files and I/O devices on the main thread.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Instead, do the work on a separate serial dispatch queue, and notify the completion of I/O by enqueuing a block onto the main queue.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the asynchronous variant of an API that performs I/O to do that work off the main",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "thread.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Don’t perform synchronous networking on the main thread of your app. Instead, use an",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "asynchronous networking API, such as",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlsession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Disable-the-Thread-Performance-Checker-tool",
          "level": 3,
          "text": "Disable the Thread Performance Checker tool",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Thread Performance Checker tool is enabled by default for schemes that build an app",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in your project. To disable it, choose Product > Scheme > Edit Scheme to display the scheme editor. Select the Run",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "schemes, navigate to the Diagnostics section, and unselect the Thread Performance Checker tool checkbox.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "diagnosing-performance-issues-early-3",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to the Thread Performance Checker tool, always test your code using a comprehensive set of performance tests.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For more information about testing your code, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/testing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Thread Performance Checker tool is currently supported only on macOS and iOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Resolution of certain performance issues may require significant code refactoring or redesign of the underlying logic. To suppress the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "warning for issues you intend to address at a later time, set the ",
              "type": "text"
            },
            {
              "code": "PERFC_SUPPRESSION_FILE",
              "type": "codeVoice"
            },
            {
              "text": " environment variable to provide a list of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "classes and methods in a suppression file. The Thread Performance Checker tool only shows issues that don’t involve those classes and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "methods. Use the following format for your suppression file:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class:UIActivityViewController",
            "class:NSThread",
            "method:-[UIViewController view]",
            "method:readv"
          ],
          "syntax": "other",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "diagnosing-performance-issues-early-1": {
      "alt": "A screenshot of a Priority Inversion issue text in the source editor.",
      "identifier": "diagnosing-performance-issues-early-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cebd1e73a23e69cd03ffee45e99e962f/diagnosing-performance-issues-early-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/13170f031341180b2b63262f059fdc6b/diagnosing-performance-issues-early-1~dark@2x.png"
        }
      ]
    },
    "diagnosing-performance-issues-early-2": {
      "alt": "A screenshot of the expanded backdtrace in the Issue navigator.",
      "identifier": "diagnosing-performance-issues-early-2",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c26fbff407d8e560d6d2c51d61a62e11/diagnosing-performance-issues-early-2@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1f102be4a0dc3d8cd4a4dcb63d1f1400/diagnosing-performance-issues-early-2~dark@2x.png"
        }
      ]
    },
    "diagnosing-performance-issues-early-3": {
      "alt": "A screenshot of the Scheme Editor with the Thread Performance Checker checkbox selected.",
      "identifier": "diagnosing-performance-issues-early-3",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/982a500a5193deb7fde595751b084213/diagnosing-performance-issues-early-3@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3eb69223c6386ac3b89de76b483623c2/diagnosing-performance-issues-early-3~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/addressing-watchdog-terminations": {
      "abstract": [
        {
          "text": "Identify the signature of an unresponsive app terminated by the watchdog, and address",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the issue.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/addressing-watchdog-terminations",
      "kind": "article",
      "role": "article",
      "title": "Addressing watchdog terminations",
      "type": "topic",
      "url": "/documentation/xcode/addressing-watchdog-terminations"
    },
    "doc://com.apple.Xcode/documentation/Xcode/analyzing-responsiveness-issues-in-your-shipping-app": {
      "abstract": [
        {
          "text": "Identify responsiveness issues your users encounter, and use the hang and hitch data in Xcode Organizer to determine which issues are most important to fix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/analyzing-responsiveness-issues-in-your-shipping-app",
      "kind": "article",
      "role": "article",
      "title": "Analyzing responsiveness issues in your shipping app",
      "type": "topic",
      "url": "/documentation/xcode/analyzing-responsiveness-issues-in-your-shipping-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness": {
      "abstract": [
        {
          "text": "Create a user experience that feels responsive by removing hangs and hitches from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness",
      "kind": "article",
      "role": "article",
      "title": "Improving app responsiveness",
      "type": "topic",
      "url": "/documentation/xcode/improving-app-responsiveness"
    },
    "doc://com.apple.Xcode/documentation/Xcode/performance-and-metrics": {
      "abstract": [
        {
          "text": "Measure, investigate, and address the use of system resources and issues impacting performance using Instruments and Xcode Organizer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/performance-and-metrics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Performance and metrics",
      "type": "topic",
      "url": "/documentation/xcode/performance-and-metrics"
    },
    "doc://com.apple.Xcode/documentation/Xcode/reduce-terminations-in-your-app": {
      "abstract": [
        {
          "text": "Minimize how frequently the system stops your app by addressing common termination reasons.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/reduce-terminations-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Reducing terminations in your app",
      "type": "topic",
      "url": "/documentation/xcode/reduce-terminations-in-your-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/reducing-disk-writes": {
      "abstract": [
        {
          "text": "Improve your app’s responsiveness by optimizing how it writes data to permanent storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/reducing-disk-writes",
      "kind": "article",
      "role": "article",
      "title": "Reducing disk writes",
      "type": "topic",
      "url": "/documentation/xcode/reducing-disk-writes"
    },
    "doc://com.apple.Xcode/documentation/Xcode/reducing-your-app-s-launch-time": {
      "abstract": [
        {
          "text": "Create a more responsive experience with your app by minimizing time spent in startup.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/reducing-your-app-s-launch-time",
      "kind": "article",
      "role": "article",
      "title": "Reducing your app’s launch time",
      "type": "topic",
      "url": "/documentation/xcode/reducing-your-app-s-launch-time"
    },
    "doc://com.apple.Xcode/documentation/Xcode/testing": {
      "abstract": [
        {
          "text": "Develop and run tests to detect logic failures, UI problems, and performance regressions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/testing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Testing",
      "type": "topic",
      "url": "/documentation/xcode/testing"
    },
    "doc://com.apple.Xcode/documentation/Xcode/understanding-hangs-in-your-app": {
      "abstract": [
        {
          "text": "Determine the cause for delays in user interactions by examining the main thread and the main run loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/understanding-hangs-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Understanding hangs in your app",
      "type": "topic",
      "url": "/documentation/xcode/understanding-hangs-in-your-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/understanding-hitches-in-your-app": {
      "abstract": [
        {
          "text": "Determine the cause of interruptions in motion by examining the render loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/understanding-hitches-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Understanding hitches in your app",
      "type": "topic",
      "url": "/documentation/xcode/understanding-hitches-in-your-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/understanding-user-interface-responsiveness": {
      "abstract": [
        {
          "text": "Make your app more responsive by examining the event-handling and rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/understanding-user-interface-responsiveness",
      "kind": "article",
      "role": "article",
      "title": "Understanding user interface responsiveness",
      "type": "topic",
      "url": "/documentation/xcode/understanding-user-interface-responsiveness"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureSession": {
      "abstract": [
        {
          "text": "An object that configures capture behavior and coordinates the flow of data from input devices to capture outputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureSession",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureSession"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureSession/startRunning()": {
      "abstract": [
        {
          "text": "Starts the flow of data through the capture pipeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startRunning"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureSession/startRunning()",
      "kind": "symbol",
      "role": "symbol",
      "title": "startRunning()",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureSession/startRunning()"
    },
    "doc://com.apple.documentation/documentation/Dispatch/DispatchQoS/userInteractive": {
      "abstract": [
        {
          "text": "The quality-of-service class for user-interactive tasks, such as animations, event handling, or updates to your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInteractive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV",
          "text": "DispatchQoS"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Dispatch/DispatchQoS/userInteractive",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInteractive",
      "type": "topic",
      "url": "/documentation/Dispatch/DispatchQoS/userInteractive"
    },
    "doc://com.apple.documentation/documentation/Dispatch/dispatch-queue": {
      "abstract": [
        {
          "text": "An object that manages the execution of tasks serially or concurrently on your app’s main thread or on a background thread.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Dispatch/dispatch-queue",
      "kind": "article",
      "role": "article",
      "title": "Dispatch Queue",
      "type": "topic",
      "url": "/documentation/Dispatch/dispatch-queue"
    },
    "doc://com.apple.documentation/documentation/dispatch/1452794-dispatch_group_wait": {
      "abstract": [
        {
          "text": "Waits synchronously for the previously submitted block objects to finish; returns if the blocks do not complete before the specified timeout period has elapsed.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/dispatch/1452794-dispatch_group_wait",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_group_wait",
      "type": "topic",
      "url": "/documentation/dispatch/1452794-dispatch_group_wait"
    },
    "doc://com.apple.documentation/documentation/dispatch/1453087-dispatch_semaphore_wait": {
      "abstract": [
        {
          "text": "Waits for (decrements) a semaphore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/dispatch/1453087-dispatch_semaphore_wait",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_semaphore_wait",
      "type": "topic",
      "url": "/documentation/dispatch/1453087-dispatch_semaphore_wait"
    },
    "doc://com.apple.documentation/documentation/foundation/nsoperationqueue": {
      "abstract": [
        {
          "text": "A queue that regulates the execution of operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsoperationqueue",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOperationQueue",
      "type": "topic",
      "url": "/documentation/foundation/nsoperationqueue"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurlsession": {
      "abstract": [
        {
          "text": "An object that coordinates a group of related, network data transfer tasks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlsession",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURLSession",
      "type": "topic",
      "url": "/documentation/foundation/nsurlsession"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html",
      "title": "Energy Efficiency Guide for iOS Apps",
      "titleInlineContent": [
        {
          "text": "Energy Efficiency Guide for iOS",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Apps",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html"
    },
    "https://developer.apple.com/videos/play/wwdc2017/706/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2017/706/",
      "title": "Modernizing Grand Central Dispatch Usage",
      "titleInlineContent": [
        {
          "text": "Modernizing Grand Central Dispatch",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Usage",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2017/706/"
    },
    "https://developer.apple.com/videos/play/wwdc2021/10258/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2021/10258/",
      "title": "Understand and eliminate hangs from your app",
      "titleInlineContent": [
        {
          "text": "Understand and eliminate hangs from your app",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2021/10258/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/addressing-watchdog-terminations",
        "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Responsiveness",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/analyzing-responsiveness-issues-in-your-shipping-app",
        "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness",
        "doc://com.apple.Xcode/documentation/Xcode/understanding-user-interface-responsiveness",
        "doc://com.apple.Xcode/documentation/Xcode/understanding-hangs-in-your-app",
        "doc://com.apple.Xcode/documentation/Xcode/understanding-hitches-in-your-app",
        "doc://com.apple.Xcode/documentation/Xcode/reducing-your-app-s-launch-time",
        "doc://com.apple.Xcode/documentation/Xcode/reduce-terminations-in-your-app",
        "doc://com.apple.Xcode/documentation/Xcode/reducing-disk-writes"
      ],
      "title": "Responsiveness"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureSession~1startRunning()/title",
          "value": "startRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureSession~1startRunning()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "startRunning"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    },
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsoperationqueue/title",
          "value": "OperationQueue"
        },
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsoperationqueue/fragments",
          "value": [
            {
              "kind": "text",
              "text": "class "
            },
            {
              "kind": "identifier",
              "text": "OperationQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurlsession/title",
          "value": "URLSession"
        },
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurlsession/fragments",
          "value": [
            {
              "kind": "text",
              "text": "class "
            },
            {
              "kind": "identifier",
              "text": "URLSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
