{
  "abstract": [
    {
      "text": "Check whether your Metal app correctly reads and writes to memory by measuring the GPU’s memory bandwidth.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/debugging",
        "doc://com.apple.Xcode/documentation/Xcode/Metal-developer-workflows"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/Measuring-the-GPUs-use-of-memory-bandwidth"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Measuring the GPU’s use of memory bandwidth"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Instruments developer tool and the Metal debugger’s Performance timeline provide bandwidth counters (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/Analyzing-the-performance-of-your-Metal-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/Analyzing-Apple-GPU-performance-using-a-visual-timeline",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", respectively).",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The GPU bandwidth counters measure how much, in gigabytes per second, the GPU reads and writes, or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "accesses",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " memory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You may want your app to use a high amount of bandwidth for some activities",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "— such as copying data quickly to save time —",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and lower bandwidth for others to save energy or to let the CPU and other processes access memory.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If the GPU’s memory bandwidth usage is high when you don’t expect it to be, it may impede the CPU’s memory accesses.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can reduce a GPU’s memory bandwidth with the following strategies in your passes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Read only the data your pass needs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Write only the data that a subsequent pass needs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Load and store only the attachments that a render pass needs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create textures that use only the appropriate",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTextureUsage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " attributes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Metal can reduce your app’s memory bandwidth by optimizing the memory accesses to your textures that have the correct usage attributes.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To set a texture’s usage appropriately, configure an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTextureDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTextureDescriptor/usage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and create a texture with it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Buffer and texture operations can also increase your app’s memory bandwidth.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To check whether the limiter counters for buffer or texture operations are too high, and to learn what you can do to reduce their impact,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/Reducing-shader-bottlenecks",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Dependencies viewer in the Metal debugger can help you find opportunities to reduce memory bandwidth",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "in your render and compute passes. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.Xcode/documentation/Xcode/Analyzing-resource-dependencies",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Metal-Developer-Workflow-PageImage-card.png": {
      "alt": "Metal logo",
      "identifier": "Metal-Developer-Workflow-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/713b476e42e48070365a2abf70bc49b0/Metal-Developer-Workflow-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e226f618b21dde7899eba5de3bd4641a/Metal-Developer-Workflow-PageImage-card~dark@2x.png"
        }
      ]
    },
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/Analyzing-Apple-GPU-performance-using-a-visual-timeline": {
      "abstract": [
        {
          "text": "Locate performance issues using the Performance timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/Analyzing-Apple-GPU-performance-using-a-visual-timeline",
      "kind": "article",
      "role": "article",
      "title": "Analyzing Apple GPU performance using a visual timeline",
      "type": "topic",
      "url": "/documentation/xcode/analyzing-apple-gpu-performance-using-a-visual-timeline"
    },
    "doc://com.apple.Xcode/documentation/Xcode/Analyzing-resource-dependencies": {
      "abstract": [
        {
          "text": "Avoid unnecessary work in your Metal app by understanding the relationships between resources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/Analyzing-resource-dependencies",
      "kind": "article",
      "role": "article",
      "title": "Analyzing resource dependencies",
      "type": "topic",
      "url": "/documentation/xcode/analyzing-resource-dependencies"
    },
    "doc://com.apple.Xcode/documentation/Xcode/Analyzing-the-performance-of-your-Metal-app": {
      "abstract": [
        {
          "text": "Ensure consistent, smooth rendering by profiling your app’s frame time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/Analyzing-the-performance-of-your-Metal-app",
      "kind": "article",
      "role": "article",
      "title": "Analyzing the performance of your Metal app",
      "type": "topic",
      "url": "/documentation/xcode/analyzing-the-performance-of-your-metal-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/Finding-your-Metal-apps-GPU-occupancy": {
      "abstract": [
        {
          "text": "Understand the GPU usage for executing shaders by using occupancy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/Finding-your-Metal-apps-GPU-occupancy",
      "kind": "article",
      "role": "article",
      "title": "Finding your Metal app’s GPU occupancy",
      "type": "topic",
      "url": "/documentation/xcode/finding-your-metal-apps-gpu-occupancy"
    },
    "doc://com.apple.Xcode/documentation/Xcode/Metal-developer-workflows": {
      "abstract": [
        {
          "text": "Locate and fix issues related to your app’s use of the Metal API and GPU functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/Metal-developer-workflows",
      "images": [
        {
          "identifier": "Metal-Developer-Workflow-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal developer workflows",
      "type": "topic",
      "url": "/documentation/xcode/metal-developer-workflows"
    },
    "doc://com.apple.Xcode/documentation/Xcode/Reducing-shader-bottlenecks": {
      "abstract": [
        {
          "text": "Identify and minimize congestion points in a GPU’s subsystems by checking its limiter and utilization counters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/Reducing-shader-bottlenecks",
      "kind": "article",
      "role": "article",
      "title": "Reducing shader bottlenecks",
      "type": "topic",
      "url": "/documentation/xcode/reducing-shader-bottlenecks"
    },
    "doc://com.apple.Xcode/documentation/Xcode/debugging": {
      "abstract": [
        {
          "text": "Identify and address issues in your app using the Xcode debugger, Xcode Organizer, Metal debugger, and Instruments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/debugging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Debugging",
      "type": "topic",
      "url": "/documentation/xcode/debugging"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLTextureDescriptor": {
      "abstract": [
        {
          "text": "An object that you use to configure new Metal texture objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTextureDescriptor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTextureDescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLTextureDescriptor",
      "type": "topic",
      "url": "/documentation/Metal/MTLTextureDescriptor"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLTextureDescriptor/usage": {
      "abstract": [
        {
          "text": "Options that determine how you can use the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTextureDescriptor/usage",
      "kind": "symbol",
      "role": "symbol",
      "title": "usage",
      "type": "topic",
      "url": "/documentation/Metal/MTLTextureDescriptor/usage"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLTextureUsage": {
      "abstract": [
        {
          "text": "An enumeration for the various options that determine how you can use a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTextureUsage",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLTextureUsage",
      "type": "topic",
      "url": "/documentation/Metal/MTLTextureUsage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Counters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/Finding-your-Metal-apps-GPU-occupancy",
        "doc://com.apple.Xcode/documentation/Xcode/Reducing-shader-bottlenecks"
      ],
      "title": "Counters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLTextureUsage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLTextureUsage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLTextureDescriptor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLTextureDescriptor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLTextureDescriptor~1usage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readwrite"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLTextureUsage",
              "text": "MTLTextureUsage"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "usage"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
