{
  "abstract": [
    {
      "text": "Create a more responsive experience with your app by minimizing time spent in startup.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/performance-and-metrics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/reducing-your-app-s-launch-time"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Reducing your app’s launch time"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A user’s first experience with an app is the wait while it launches. The OS indicates",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the app is launching with a splash screen on iOS and an icon bouncing in Dock on macOS.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The app needs to be ready to help the user with a task as soon as possible. An app that takes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "too long to launch may frustrate the user, and on iOS, the watchdog will terminate it if",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "it takes too long. Typically, users launch an app many times in a day if it’s part of their",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "regular workflow, and a long launch time causes delays in performing a task.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the user taps an app’s icon on their Home screen, iOS prepares the app for launch",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "before handing control over to the app process. The app then runs code to get ready",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to draw its UI to the screen. Even after the app’s UI is visible, the app may still",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "be preparing content or replacing an interstitial interface (for example, a loading",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "spinner) with the final controls. Each of these steps contributes to the total perceived",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "launch time of the app, and you can take steps to reduce their duration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Understand-app-activations",
          "level": 3,
          "text": "Understand app activations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "activation",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " happens when a user clicks on your icon or otherwise goes back to your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On iOS, an activation can either be a launch or a resume. A ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "launch",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is when the process needs to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "start, and a resume is when your app already had a process alive, even if suspended. A ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "resume",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "generally much faster, and the work to optimize a launch and resume differs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On macOS, the system will not terminate your process as part of normal use. An activation may",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "require the system to bring in memory from the compressor, swap, and re-render.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Understand-cold-and-warm-launch",
          "level": 3,
          "text": "Understand cold and warm launch",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app activation varies significantly depending on previous actions on the device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, on iOS, if you swipe back to the home screen and immediately re-enter the app, that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is the fastest activation possible. It’s also likely to be a resume. When the system determines that a launch",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is required, it is commonly referred to as a “warm launch.”",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Conversely, if a user just played a memory-intensive game, and they then re-enter your app, for example, it",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "may be significantly slower than your average activation. On iOS, your app typically was evicted from",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "memory to allow the foreground application more memory. Frameworks and daemons that your app depends",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on to launch might also require re-launching and paging in from disk. This scenario, or a launch",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "immediately after boot, is often referred to as a “cold launch.”",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Think of warm and cold launches as a spectrum. In real use, your users will experience",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a range of performance based on the state of the device. This spectrum is why testing",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in a variety of conditions is essential to predicting your real world performance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Gather-metrics-about-your-apps-launch-time",
          "level": 3,
          "text": "Gather metrics about your app’s launch time",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Variations in launching mean that understanding how your app is operating in the field can be challenging.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For iOS apps, use the Launch Time pane in the Xcode Organizer to view the number of milliseconds between the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "user tapping your icon and when your first screen is drawn, after the static splash",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "screen. Use the filters to check launch times on different",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "devices and for the typical (50th percentile) and longest (90th percentile) times.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Compare the launch time of the current release with a previous one by clicking on the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "bar in the graph for the desired release.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "reducing-your-app-s-launch-time-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.documentation/documentation/MetricKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " reports the time to resume the application in addition to the launch",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "time. ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/metrickit/mxapplaunchmetric",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " contains a histogram of your launch and resume times for the previous day.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Identify-areas-of-launch-time-improvement",
          "level": 3,
          "text": "Identify areas of launch time improvement",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To determine which processes take up time when your iOS app launches, use the Launches pane in the Xcode Organizer. The report area displays an ordered list of the longest running functions that the system calls when your app starts in the same row as the percentage of the launch time the process takes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Clicking a report in the Report List shows the function that ran along with its respective stack trace. The Inspector includes more details, specifically:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "iOS version",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Device model",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Total launch time for the log that includes this signature",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Number of received logs",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "14-day reporting trend",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Prioritize reducing launch times by using the percent of time spent metric, as well as information on the operating system and the impacted device types. Identify the code responsible for the increase in app launch time by using the function signature for a specific report in the Report List and the corresponding stack trace. After updating the code and verifying the fix, mark the report as resolved.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "reducing-your-app-s-launch-time-6",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Profile-your-apps-launch-time",
          "level": 3,
          "text": "Profile your app’s launch time",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Once you know how long it takes your app to launch, you need to know why it takes that long.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Profiling your app’s code is a way to gather the data you need about where your app spends",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "its time. During the profiling process, ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/instruments/mac/current/#/dev7b09c84f5",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " gathers information about what methods",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app called and how much time it spent executing them. Use this data to identify",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "potential bottlenecks or issues in your code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Profile your app in Instruments by using the App Launch template. During your launch,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Instruments gathers a time profile and thread-state",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "trace. Use the time profile to identify the code your app is running during launch.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use the thread-state trace to find times when threads are active or blocked, and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "discover the reasons that threads are blocked.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Profile your app’s launch time in different situations to see how these factors affect",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the experience. Here are some examples of different situations to test:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Switch the device on, unlock it for the first time, and then launch your app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Force quit your app, and then launch it. The system will terminate your app process, and",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "the system will perform a warm launch.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you open other apps and then launch yours, the system partially evicts your app and its dependencies",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "This mirrors a common user workflow.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use a very large app — for example, one that works with many graphical resources",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "or live camera input — and then launch your app. The system will likely terminate your app’s process",
                      "type": "text"
                    },
                    {
                      "text": "\n",
                      "type": "text"
                    },
                    {
                      "text": "terminated, which means the system needs to page in many of the app’s dependencies during your next launch.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "reducing-your-app-s-launch-time-2",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "UIKit draws views and handles user events on the main thread, so that thread must",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "be available to draw the first frame when the app has finished launching. In the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Instruments thread trace, time that the main thread spends running or preempted is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "time that it cannot draw views or respond to user input events.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For a different view of app launch, profile the app using the Time Profile template.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The App Life Cycle timeline divides activity during app launch into process initialization,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "UIKit initialization, UIKit initial scene rendering, and initial frame rendering.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "reducing-your-app-s-launch-time-3",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Reduce-dependencies-on-external-frameworks-and-dynamic-libraries",
          "level": 3,
          "text": "Reduce dependencies on external frameworks and dynamic libraries",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before any of your code runs, the system must find and load your app’s executable and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "any libraries on which it depends.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The dynamic loader (",
              "type": "text"
            },
            {
              "code": "dyld",
              "type": "codeVoice"
            },
            {
              "text": ") loads the app’s executable file, and examines the Mach",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "load commands in the executable to find frameworks and dynamic libraries that the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app needs. It then loads each of the frameworks into memory, and resolves dynamic",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "symbols in the executable to point to the appropriate addresses in the dynamic libraries.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each additional third-party framework that your app loads adds to the launch time. Although ",
              "type": "text"
            },
            {
              "code": "dyld",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "caches a lot of this work in a launch closure when the user installs the app, the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "size of the launch closure and the amount of work done after loading it still depend",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on the number and sizes of the libraries loaded. You can reduce your app’s launch",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "time by limiting the number of 3rd party frameworks you embed. Frameworks that you import or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "add to your app’s Linked Frameworks and Libraries setting in the Target editor",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in Xcode count toward this number. Built-in frameworks, like CoreFoundation, have",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a much lower impact on launch, because they use shared memory with other processes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that use the same framework.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Use-mergeable-dynamic-libraries",
          "level": 3,
          "text": "Use mergeable dynamic libraries",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Xcode 15 or later, you can use mergeable dynamic libraries to get app launch times",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "similar to static linking in release builds, without losing dynamically linked build times",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in debug builds. Mergeable dynamic libraries include extra metadata so that Xcode",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "can merge the library into another binary. For more information on mergable libraries,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/configuring-your-project-to-use-mergeable-libraries",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Remove-or-reduce-the-static-initializers-in-your-code",
          "level": 3,
          "text": "Remove or reduce the static initializers in your code",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Certain code in an app must run before iOS runs your app’s ",
              "type": "text"
            },
            {
              "code": "main()",
              "type": "codeVoice"
            },
            {
              "text": " function, adding",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to the launch time. This code includes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "C++ static constructors.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Objective-C ",
                      "type": "text"
                    },
                    {
                      "code": "+load",
                      "type": "codeVoice"
                    },
                    {
                      "text": " methods defined in classes or categories.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Functions marked with the clang attribute ",
                      "type": "text"
                    },
                    {
                      "code": "__attribute__((constructor))",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Any function linked into the ",
                      "type": "text"
                    },
                    {
                      "code": "__DATA,__mod_init_func",
                      "type": "codeVoice"
                    },
                    {
                      "text": " section of an app or framework",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "binary.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Where possible, move the code to a later stage of the app’s life cycle, after the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app has finished launching but before the results of the work are needed. In Instruments,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the dyld Activity instrument measures the time your app spends running static initializers",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and reports other useful metrics to help you speed up your app’s launch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Move-expensive-tasks-out-of-your-app-delegate",
          "level": 3,
          "text": "Move expensive tasks out of your app delegate",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Audit your initialization code to delay expensive work. The system",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "calls methods of your app delegate during the launch cycle to give you time to perform",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "required tasks. These methods execute synchronously on the main thread, and the launch",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "cycle doesn’t finish until both methods return successfully. As a result, any expensive",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "tasks you perform from the methods delay the completion of that launch cycle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "UIKit initializes an instance of your app delegate class (the class that conforms",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "protocol) and sends it the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:willFinishLaunchingWithOptions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "messages. UIKit sends these messages on the main thread, and time spent executing",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "code in these methods increases your app’s launch time. Do only the work necessary",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to prepare your app’s initial display in these methods; defer other tasks to more",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "appropriate times in the app’s life cycle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Defer synchronization of the data model with a network service until the app is running,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "if it makes sense to show stale content to the user while the content is being refreshed.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Move the synchronization to an asynchronous background queue. Register a background",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "task to fetch updates from the network service, to reduce both the staleness of data",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on launch and the amount of work needed to bring it up to date.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Initialize nonview functionality, such as persistent storage and location services,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on first use rather than on app launch. Retrieve only the data necessary to display",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app’s initial view. Pay attention to whether your app is restoring state, and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "prepare the data needed to display the view that’s being restored. If no state is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "being restored, prepare only the default initial view. For example, a photo gallery",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app might show a collection of image thumbnails by default and let a user pick a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "photo to get a detailed view. If the app is launching with no restored state, it",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "only needs to show a placeholder for a screenful of thumbnails and fill them in with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "real image thumbnails once the app has finished launching. It doesn’t need to load",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the full, detailed images until the user taps one of the thumbnails.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Initialize a restricted subset of the app’s behavior that’s known to be viable on",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "initial launch. For example, a task manager app can let the user create a new task",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on launch, even if the app hasn’t yet retrieved all of the user’s existing tasks",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "from its persistent storage or network service.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Reduce-the-complexity-of-your-initial-views",
          "level": 3,
          "text": "Reduce the complexity of your initial views",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode Organizer and MetricKit both use the time to first frame as the measurement",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of launch time, including the time required to draw the views that are displayed",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on that first frame. You can only modify the view hierarchy on the main thread; therefore, a more complicated view hierarchy with more views takes longer to render than a simple hierarchy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Reducing the complexity of your app’s initial view improves the load time, as does",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "replacing custom views that override ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/draw(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with standard views. Where you need custom drawing, pay attention to the rectangle",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "passed to ",
              "type": "text"
            },
            {
              "code": "draw(_:)",
              "type": "codeVoice"
            },
            {
              "text": " and only render parts of the view within that rectangle. Doing",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "so avoids decoding images and computing colors, coordinates, and drawing commands",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in parts of the view that aren’t rendered to the screen.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Track-additional-startup-activities",
          "level": 3,
          "text": "Track additional startup activities",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The launch-time metric measures the time from the user tapping the app icon on their",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Home screen to the app drawing its first frame to the screen. Drawing the ",
              "type": "text"
            },
            {
              "code": "default.png",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or launch-screen storyboard happens during this time, and its appearance doesn’t",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "end the launch-time counter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app still has to run code after it has drawn its first frame, but before",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the user can begin using the app, that time doesn’t contribute to the launch-time",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "metric. Extra startup activities still contribute to the user’s perception of the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app’s responsiveness. For example, if your app renders a document after opening,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the user will likely wait on the document to render and perceive it as part",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of your launch time, even though the system will end the launch measurement while",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you show a loading icon.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To track additional startup activities, create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/OSLog",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "object in your app with the category ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/OSLog/Category/pointsOfInterest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "os_signpost",
              "type": "codeVoice"
            },
            {
              "text": " function to record the beginning and end of your app’s preparation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "tasks, as shown in the following example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class ViewController: UIViewController {",
            "    static let startupActivities:StaticString = \"Startup Activities\"",
            "    let poiLog = OSLog(subsystem: \"com.example.CocoaPictures\", category: .pointsOfInterest)",
            "",
            "    override func viewDidAppear() {",
            "        super.viewDidAppear()",
            "        os_signpost(.begin, log: self.poiLog, name: ViewController.startupActivities)",
            "        // do work to prepare the view",
            "        os_signpost(.end, log: self.poiLog, name: ViewController.startupActivities)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In Instruments, Points of Interest displays the os_signposts in its timeline. You can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "use this information to correlate activity in your app with the app’s additional",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "startup tasks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "reducing-your-app-s-launch-time-5",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/analyzing-responsiveness-issues-in-your-shipping-app": {
      "abstract": [
        {
          "text": "Identify responsiveness issues your users encounter, and use the hang and hitch data in Xcode Organizer to determine which issues are most important to fix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/analyzing-responsiveness-issues-in-your-shipping-app",
      "kind": "article",
      "role": "article",
      "title": "Analyzing responsiveness issues in your shipping app",
      "type": "topic",
      "url": "/documentation/xcode/analyzing-responsiveness-issues-in-your-shipping-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/configuring-your-project-to-use-mergeable-libraries": {
      "abstract": [
        {
          "text": "Use mergeable dynamic libraries to get app launch times similar to static linking in release builds, without losing dynamically linked build times in debug builds.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/configuring-your-project-to-use-mergeable-libraries",
      "kind": "article",
      "role": "article",
      "title": "Configuring your project to use mergeable libraries",
      "type": "topic",
      "url": "/documentation/xcode/configuring-your-project-to-use-mergeable-libraries"
    },
    "doc://com.apple.Xcode/documentation/Xcode/diagnosing-performance-issues-early": {
      "abstract": [
        {
          "text": "Diagnose potential performance issues in your app during testing with the Thread Performance Checker tool in Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/diagnosing-performance-issues-early",
      "kind": "article",
      "role": "article",
      "title": "Diagnosing performance issues early",
      "type": "topic",
      "url": "/documentation/xcode/diagnosing-performance-issues-early"
    },
    "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness": {
      "abstract": [
        {
          "text": "Create a user experience that feels responsive by removing hangs and hitches from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness",
      "kind": "article",
      "role": "article",
      "title": "Improving app responsiveness",
      "type": "topic",
      "url": "/documentation/xcode/improving-app-responsiveness"
    },
    "doc://com.apple.Xcode/documentation/Xcode/performance-and-metrics": {
      "abstract": [
        {
          "text": "Measure, investigate, and address the use of system resources and issues impacting performance using Instruments and Xcode Organizer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/performance-and-metrics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Performance and metrics",
      "type": "topic",
      "url": "/documentation/xcode/performance-and-metrics"
    },
    "doc://com.apple.Xcode/documentation/Xcode/reduce-terminations-in-your-app": {
      "abstract": [
        {
          "text": "Minimize how frequently the system stops your app by addressing common termination reasons.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/reduce-terminations-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Reducing terminations in your app",
      "type": "topic",
      "url": "/documentation/xcode/reduce-terminations-in-your-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/reducing-disk-writes": {
      "abstract": [
        {
          "text": "Improve your app’s responsiveness by optimizing how it writes data to permanent storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/reducing-disk-writes",
      "kind": "article",
      "role": "article",
      "title": "Reducing disk writes",
      "type": "topic",
      "url": "/documentation/xcode/reducing-disk-writes"
    },
    "doc://com.apple.Xcode/documentation/Xcode/understanding-hangs-in-your-app": {
      "abstract": [
        {
          "text": "Determine the cause for delays in user interactions by examining the main thread and the main run loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/understanding-hangs-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Understanding hangs in your app",
      "type": "topic",
      "url": "/documentation/xcode/understanding-hangs-in-your-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/understanding-hitches-in-your-app": {
      "abstract": [
        {
          "text": "Determine the cause of interruptions in motion by examining the render loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/understanding-hitches-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Understanding hitches in your app",
      "type": "topic",
      "url": "/documentation/xcode/understanding-hitches-in-your-app"
    },
    "doc://com.apple.Xcode/documentation/Xcode/understanding-user-interface-responsiveness": {
      "abstract": [
        {
          "text": "Make your app more responsive by examining the event-handling and rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/understanding-user-interface-responsiveness",
      "kind": "article",
      "role": "article",
      "title": "Understanding user interface responsiveness",
      "type": "topic",
      "url": "/documentation/xcode/understanding-user-interface-responsiveness"
    },
    "doc://com.apple.documentation/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/MetricKit"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate": {
      "abstract": [
        {
          "text": "A set of methods to manage shared behaviors for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplicationDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationDelegate",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the launch process is almost done and the app is almost ready to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishLaunchingWithOptions"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIApplicationLaunchOptionsKey",
          "text": "LaunchOptionsKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]? = nil) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:didFinishLaunchingWithOptions:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:willFinishLaunchingWithOptions:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the launch process has begun but that state restoration hasn’t occured.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willFinishLaunchingWithOptions"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIApplicationLaunchOptionsKey",
          "text": "LaunchOptionsKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]? = nil) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:willFinishLaunchingWithOptions:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:willFinishLaunchingWithOptions:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:willFinishLaunchingWithOptions:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIView/draw(_:)": {
      "abstract": [
        {
          "text": "Draws the view’s image within the passed-in rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/draw(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "draw(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIView/draw(_:)"
    },
    "doc://com.apple.documentation/documentation/os/OSLog": {
      "abstract": [
        {
          "text": "A container of related log messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLog"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/OSLog",
      "kind": "symbol",
      "role": "symbol",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/os/OSLog"
    },
    "doc://com.apple.documentation/documentation/os/OSLog/Category/pointsOfInterest": {
      "abstract": [
        {
          "text": "The category you use to log signposts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointsOfInterest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_os_log",
          "text": "OSLog"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So9OS_os_logC0B0E8CategoryV",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/OSLog/Category/pointsOfInterest",
      "kind": "symbol",
      "role": "symbol",
      "title": "pointsOfInterest",
      "type": "topic",
      "url": "/documentation/os/OSLog/Category/pointsOfInterest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/documentation/metrickit/mxapplaunchmetric": {
      "identifier": "https://developer.apple.com/documentation/metrickit/mxapplaunchmetric",
      "title": "MXAppLaunchMetric",
      "titleInlineContent": [
        {
          "text": "MXAppLaunchMetric",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/metrickit/mxapplaunchmetric"
    },
    "https://help.apple.com/instruments/mac/current/#/dev7b09c84f5": {
      "identifier": "https://help.apple.com/instruments/mac/current/#/dev7b09c84f5",
      "title": "Instruments",
      "titleInlineContent": [
        {
          "text": "Instruments",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/instruments/mac/current/#/dev7b09c84f5"
    },
    "reducing-your-app-s-launch-time-1": {
      "alt": "Screenshot of the Launch Time metric pane in the Xcode Organizer. From left to right is the list of metrics and reports, the metric UI with a bar graph showing the launch time over the last 8 app versions, the selected version bar highlighted in the graph, and the comparison data for the selected and latest versions on the right side. ",
      "identifier": "reducing-your-app-s-launch-time-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/631e3c55db2b5606763b801cd454caa0/reducing-your-app-s-launch-time-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/68d90f8d6790c95ea1e954211d07fac2/reducing-your-app-s-launch-time-1~dark@2x.png"
        }
      ]
    },
    "reducing-your-app-s-launch-time-2": {
      "alt": "Image showing a thread-state trace in Instruments, and a description of a blocked thread.",
      "identifier": "reducing-your-app-s-launch-time-2",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/06d851d843a5ad7bffdab22f3a5e7bd2/reducing-your-app-s-launch-time-2.png"
        }
      ]
    },
    "reducing-your-app-s-launch-time-3": {
      "alt": "Image showing the App Life Cycle timeline in Instruments.",
      "identifier": "reducing-your-app-s-launch-time-3",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/48270584ea3ff3fdd6bc250cd4bb8446/reducing-your-app-s-launch-time-3.png"
        }
      ]
    },
    "reducing-your-app-s-launch-time-5": {
      "alt": "Screenshot showing the Points of Interest instrument, with a timeline of regions beginning and ending during an app’s additional startup activities.",
      "identifier": "reducing-your-app-s-launch-time-5",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8af771222ac18b46017898a01ec66e51/reducing-your-app-s-launch-time-5@2x.png"
        }
      ]
    },
    "reducing-your-app-s-launch-time-6": {
      "alt": "Screenshot of the Launches pane in the Xcode Organizer. From left to right, the Report List which is a list of functions taking the most time to run as a percentage, the corresponding call stack for the function selected in the Report List, and launch log details and statistics including the 14-day reporting trend.",
      "identifier": "reducing-your-app-s-launch-time-6",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8c4c973b049c9dedaaf57d8dd1e23e37/reducing-your-app-s-launch-time-6@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/95b4758aa4d837640f4477ff2f97c3f6/reducing-your-app-s-launch-time-6~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responsiveness",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Xcode/documentation/Xcode/analyzing-responsiveness-issues-in-your-shipping-app",
        "doc://com.apple.Xcode/documentation/Xcode/improving-app-responsiveness",
        "doc://com.apple.Xcode/documentation/Xcode/understanding-user-interface-responsiveness",
        "doc://com.apple.Xcode/documentation/Xcode/understanding-hangs-in-your-app",
        "doc://com.apple.Xcode/documentation/Xcode/understanding-hitches-in-your-app",
        "doc://com.apple.Xcode/documentation/Xcode/diagnosing-performance-issues-early",
        "doc://com.apple.Xcode/documentation/Xcode/reduce-terminations-in-your-app",
        "doc://com.apple.Xcode/documentation/Xcode/reducing-disk-writes"
      ],
      "title": "Responsiveness"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIApplicationDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFinishLaunchingWithOptions:)/title",
          "value": "application:didFinishLaunchingWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFinishLaunchingWithOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didFinishLaunchingWithOptions:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "launchOptions"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1draw(_:)/title",
          "value": "drawRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1draw(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "drawRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGRect",
              "text": "CGRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willFinishLaunchingWithOptions:)/title",
          "value": "application:willFinishLaunchingWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willFinishLaunchingWithOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "willFinishLaunchingWithOptions:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "launchOptions"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
