{
  "abstract": [
    {
      "text": "Repeatably gather metrics on the performance of your code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode/documentation/Xcode",
        "doc://com.apple.Xcode/documentation/Xcode/testing"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode/documentation/Xcode/writing-and-running-performance-tests"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Writing and running performance tests"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "People perceive responsiveness and efficiency as positive contributions to an app’s experience. Use performance tests to record metrics on the performance critical parts of your code, and discover when the performance regresses below an acceptable baseline.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-test-target",
          "level": 3,
          "text": "Create a test target",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Performance tests use the same ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework to validate code behavior. Create a test target in your Xcode project that you can add behavior and performance tests to. To learn how to add a new target to your project, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/configuring-a-new-target-in-your-project",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-a-test-case-class-and-performance-test-methods",
          "level": 3,
          "text": "Add a test case class and performance test methods",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You organize performance tests into test case classes, which are subclasses of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For information on creating test case classes and test methods, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest/defining-test-cases-and-test-methods",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A performance test method is a method on a test case class with a name that starts with ",
              "type": "text"
            },
            {
              "code": "test",
              "type": "codeVoice"
            },
            {
              "text": ", no arguments, and no return value. The performance test calls one of the following methods to instruct XCTest to record metrics on your code’s performance:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Records the default performance metrics for the duration of execution of the block argument, using the default measure options.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(_:)",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Records the specified performance metrics, either for the duration of execution of the block argument, or, if you pass ",
                        "type": "text"
                      },
                      {
                        "code": "false",
                        "type": "codeVoice"
                      },
                      {
                        "text": " for the ",
                        "type": "text"
                      },
                      {
                        "code": "automaticallyStartMeasuring",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter, between calls to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/startMeasuring()",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/stopMeasuring()",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " within the block argument.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Records the specified metrics for the duration of execution of the block argument, using the default measure options.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(metrics:block:)",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Records the specified metrics, either for the duration of execution of the block argument or between calls to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/startMeasuring()",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/stopMeasuring()",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " within the block argument, depending on the specified measure options.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(metrics:options:block:)",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Records the default metrics, either for the duration of execution of the block argument or between calls to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/startMeasuring()",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/stopMeasuring()",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " within the block argument, depending on the specified measure options.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(options:block:)",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "anchor": "Determine-the-performance-metrics-to-record",
          "level": 3,
          "text": "Determine the performance metrics to record",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default behavior for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(options:block:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is to record the time spent in the measured code, in seconds. Change the default set of metrics collected by performance test methods in a test case class by overriding ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/defaultPerformanceMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/defaultMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Use a different measurement function from the list above to record different metrics in a specific test.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information on the available metrics and on implementing your own metrics, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTMetric",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-your-scheme-and-test-plan-for-accurate-performance-measurements",
          "level": 3,
          "text": "Configure your scheme and test plan for accurate performance measurements",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode uses test plans you create in your Xcode project to determine which tests to run for a scheme, and how to configure the tests. To ensure that you’re gathering real-world behavior metrics for your app, configure the performance test plan so it replicates the conditions under which the code runs on device. Configure your scheme to build for testing using the Release build configuration, and turn off the “Debug executable” setting.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Configure your test plan to disable code coverage and the runtime sanitization options. For more information on configuring test plans, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/organizing-tests-to-improve-feedback",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Run-your-performance-test-method",
          "level": 3,
          "text": "Run your performance test method",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Run your performance tests in the same way that you run tests to verify code behavior, as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/running-tests-and-interpreting-results",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In addition to the test outcome status icon in the source editor gutter next to the test method definition, Xcode shows an icon in the editor gutter next to any call to the performance measurement functions listed above. This icon is in one of the following states, depending on the outcome of the performance measurement:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Performance measurement status icon",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "check-gray.png",
                      "type": "image"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "A gray icon with a checkmark indicates that the recorded metrics were compared with the baseline value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "dot-gray.png",
                      "type": "image"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "A gray icon with a dot indicates that no baseline value was recorded for XCTest to compare the recorded metrics against.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Click the performance measurement outcome icon to view a graph of the most recent values for the metrics recorded in the test, along with the average (mean) value for each metric recorded, as shown in the figure below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "performance-tests-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-a-baseline-and-tolerance",
          "level": 3,
          "text": "Set a baseline and tolerance",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Define the threshold value for the recorded metrics in a performance test by setting a baseline value and maximum standard deviation. The test fails if the recorded metric is worse than the baseline value by more than the maximum standard deviation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To set the baseline value for a performance test’s metric, follow these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In Xcode, click the icon next to the performance measurement function call in the test to open the performance report overlay.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click Set Baseline.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can subsequently change the baseline value by doing the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In Xcode, click the icon next to the performance measurement function call in the test to open the performance report overlay.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click Edit.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enter a new baseline value, or click Accept to use the current average recorded value as the new baseline.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enter a value in the Max STDDEV field to define the maximum standard deviation of the recorded metric from the baseline.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click Save.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Diagnose-a-failing-performance-test",
          "level": 3,
          "text": "Diagnose a failing performance test",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If a test fails, you can find out more details about why the test failed by Control-clicking the icon in the editor gutter next to the failing test, and choosing “Profile [the test’s name]” to open the test in Instruments. Alternatively, navigate to the failing test in the Xcode test navigator, Control-click it, and choose “Profile [the test’s name]”.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information on how performance tests fit into an overall life cycle of improving your app’s performance, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Xcode/documentation/Xcode/improving-your-app-s-performance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Xcode-PageImage-card.png": {
      "alt": "The Xcode logo on a blue gradient background.",
      "identifier": "Xcode-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc63eacd8f7f660388b46204d1d9bbcb/Xcode-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/62dba87d5f60ec96eb48882c9dff86d8/Xcode-PageImage-card~dark@2x.png"
        }
      ]
    },
    "check-gray.png": {
      "alt": "A gray-filled rounded diamond-shaped icon that contains a checkmark.",
      "identifier": "check-gray.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0419cbd83dc3329cf41ba12285d0b28c/check-gray@2x.png"
        }
      ]
    },
    "doc://com.apple.Xcode/documentation/Xcode": {
      "abstract": [
        {
          "text": "Build, test, and submit your app with Apple’s integrated development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode",
      "images": [
        {
          "identifier": "Xcode-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "Xcode",
      "type": "topic",
      "url": "/documentation/xcode"
    },
    "doc://com.apple.Xcode/documentation/Xcode/configuring-a-new-target-in-your-project": {
      "abstract": [
        {
          "text": "Configure your project to build a new product, and add the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "code and resources the product requires.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/configuring-a-new-target-in-your-project",
      "kind": "article",
      "role": "article",
      "title": "Configuring a new target in your project",
      "type": "topic",
      "url": "/documentation/xcode/configuring-a-new-target-in-your-project"
    },
    "doc://com.apple.Xcode/documentation/Xcode/improving-your-app-s-performance": {
      "abstract": [
        {
          "text": "Model, measure, and boost the performance of your app by using a continuous-improvement",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "cycle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/improving-your-app-s-performance",
      "kind": "article",
      "role": "article",
      "title": "Improving your app’s performance",
      "type": "topic",
      "url": "/documentation/xcode/improving-your-app-s-performance"
    },
    "doc://com.apple.Xcode/documentation/Xcode/organizing-tests-to-improve-feedback": {
      "abstract": [
        {
          "text": "Control the information you receive from your tests at different stages in the software engineering process by creating and configuring test plans.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/organizing-tests-to-improve-feedback",
      "kind": "article",
      "role": "article",
      "title": "Improving code assessment by organizing tests into test plans",
      "type": "topic",
      "url": "/documentation/xcode/organizing-tests-to-improve-feedback"
    },
    "doc://com.apple.Xcode/documentation/Xcode/running-tests-and-interpreting-results": {
      "abstract": [
        {
          "text": "Determine whether your project’s code behaves as you expect by running tests and understanding the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/running-tests-and-interpreting-results",
      "kind": "article",
      "role": "article",
      "title": "Running tests and interpreting results",
      "type": "topic",
      "url": "/documentation/xcode/running-tests-and-interpreting-results"
    },
    "doc://com.apple.Xcode/documentation/Xcode/testing": {
      "abstract": [
        {
          "text": "Develop and run tests to detect logic failures, UI problems, and performance regressions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode/documentation/Xcode/testing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Testing",
      "type": "topic",
      "url": "/documentation/xcode/testing"
    },
    "doc://com.apple.documentation/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/XCTest"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTMetric": {
      "abstract": [
        {
          "text": "A protocol that defines the methods that objects must provide when gathering metrics during performance tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTMetric"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCopying",
          "text": "NSCopying"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTMetric",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTMetric",
      "type": "topic",
      "url": "/documentation/XCTest/XCTMetric"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTestCase": {
      "abstract": [
        {
          "text": "The primary class for defining test cases, test methods, and performance tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTestCase",
      "type": "topic",
      "url": "/documentation/XCTest/XCTestCase"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTestCase/defaultMetrics": {
      "abstract": [
        {
          "text": "An array of default metrics the test uses to record performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultMetrics"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        },
        {
          "kind": "text",
          "text": "] { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/defaultMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultMetrics",
      "type": "topic",
      "url": "/documentation/XCTest/XCTestCase/defaultMetrics"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTestCase/defaultPerformanceMetrics": {
      "abstract": [
        {
          "text": "An array of default performance metrics the test records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultPerformanceMetrics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCTPerformanceMetric",
          "text": "XCTPerformanceMetric"
        },
        {
          "kind": "text",
          "text": "] { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/defaultPerformanceMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultPerformanceMetrics",
      "type": "topic",
      "url": "/documentation/XCTest/XCTestCase/defaultPerformanceMetrics"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(_:)": {
      "abstract": [
        {
          "text": "Measures the performance of a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "measure(_:)",
      "type": "topic",
      "url": "/documentation/XCTest/XCTestCase/measure(_:)"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(metrics:block:)": {
      "abstract": [
        {
          "text": "Records the selected metrics for a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "metrics"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(metrics:block:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "measure(metrics:block:)",
      "type": "topic",
      "url": "/documentation/XCTest/XCTestCase/measure(metrics:block:)"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(metrics:options:block:)": {
      "abstract": [
        {
          "text": "Records the selected metrics, using the specified measurement options, for a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "metrics"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
          "text": "XCTMeasureOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(metrics:options:block:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "measure(metrics:options:block:)",
      "type": "topic",
      "url": "/documentation/XCTest/XCTestCase/measure(metrics:options:block:)"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(options:block:)": {
      "abstract": [
        {
          "text": "Records the performance, using the specified measurement options, for a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
          "text": "XCTMeasureOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measure(options:block:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "measure(options:block:)",
      "type": "topic",
      "url": "/documentation/XCTest/XCTestCase/measure(options:block:)"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)": {
      "abstract": [
        {
          "text": "Measures the performance of a block of code, optionally deferring the starting point for measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measureMetrics"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "metrics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCTPerformanceMetric",
          "text": "XCTPerformanceMetric"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "automaticallyStartMeasuring"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "measureMetrics(_:automaticallyStartMeasuring:for:)",
      "type": "topic",
      "url": "/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTestCase/startMeasuring()": {
      "abstract": [
        {
          "text": "Starts recording performance metrics within a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMeasuring"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/startMeasuring()",
      "kind": "symbol",
      "role": "symbol",
      "title": "startMeasuring()",
      "type": "topic",
      "url": "/documentation/XCTest/XCTestCase/startMeasuring()"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCTestCase/stopMeasuring()": {
      "abstract": [
        {
          "text": "Ends recording performance metrics within a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopMeasuring"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCTestCase/stopMeasuring()",
      "kind": "symbol",
      "role": "symbol",
      "title": "stopMeasuring()",
      "type": "topic",
      "url": "/documentation/XCTest/XCTestCase/stopMeasuring()"
    },
    "doc://com.apple.documentation/documentation/XCTest/defining-test-cases-and-test-methods": {
      "abstract": [
        {
          "text": "Add test cases and test methods to a test target to confirm that your code performs as expected.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/defining-test-cases-and-test-methods",
      "kind": "article",
      "role": "article",
      "title": "Defining Test Cases and Test Methods",
      "type": "topic",
      "url": "/documentation/XCTest/defining-test-cases-and-test-methods"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "dot-gray.png": {
      "alt": "A gray-filled rounded diamond-shaped icon that contains a dot.",
      "identifier": "dot-gray.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9d3b9995998afb2edbf4b33ceb32a7a8/dot-gray@2x.png"
        }
      ]
    },
    "performance-tests-1": {
      "alt": "A screenshot of the performance report overlay in Xcode. A graph shows the most recent values for the metrics gathered, and the average value, baseline value, and accepted maximum standard deviation are reported.",
      "identifier": "performance-tests-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/02845637cecf45c9156f839889c9b930/performance-tests-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/966fadaf809bcfd9c4761e5ea209d38e/performance-tests-1~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1stopMeasuring()/title",
          "value": "stopMeasuring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1stopMeasuring()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "stopMeasuring"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1startMeasuring()/title",
          "value": "startMeasuring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1startMeasuring()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "startMeasuring"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1defaultMetrics/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<id<XCTMetric>>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "defaultMetrics"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1measure(options:block:)/title",
          "value": "measureWithOptions:block:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1measure(options:block:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "measureWithOptions:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
              "text": "XCTMeasureOptions"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "block:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)()) "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1measure(metrics:options:block:)/title",
          "value": "measureWithMetrics:options:block:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1measure(metrics:options:block:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "measureWithMetrics:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<id<XCTMetric>>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "metrics"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
              "text": "XCTMeasureOptions"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "block:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)()) "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1defaultPerformanceMetrics/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSString *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "defaultPerformanceMetrics"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1measure(metrics:block:)/title",
          "value": "measureWithMetrics:block:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1measure(metrics:block:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "measureWithMetrics:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<id<XCTMetric>>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "metrics"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "block:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)()) "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1measureMetrics(_:automaticallyStartMeasuring:for:)/title",
          "value": "measureMetrics:automaticallyStartMeasuring:forBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1measureMetrics(_:automaticallyStartMeasuring:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "measureMetrics:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSString *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "metrics"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "automaticallyStartMeasuring:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "automaticallyStartMeasuring"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "forBlock:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)()) "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1measure(_:)/title",
          "value": "measureBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase~1measure(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "measureBlock:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)()) "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTestCase/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTestCase"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTest",
              "text": "XCTest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCTMetric/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTMetric"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSCopying",
              "text": "NSCopying"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
