{
  "abstract": [
    {
      "text": "Error codes for instantiation operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pushtotalk/documentation/PushToTalk",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PTInstantiationError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Push to Talk"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PTInstantiationError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk": {
      "abstract": [
        {
          "text": "Display the system user interface for your app’s Push to Talk services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk",
      "kind": "symbol",
      "role": "collection",
      "title": "Push to Talk",
      "type": "topic",
      "url": "/documentation/pushtotalk"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a channel error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelError"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelError"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for channel operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelErrorDomain": {
      "abstract": [
        {
          "text": "A string representation of the channel error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PTChannelErrorDomain",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerrordomain"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an instantiation error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTInstantiationError"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationError"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for instantiation operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/instantiationAlreadyInProgress": {
      "abstract": [
        {
          "text": "An instantiation error that indicates there’s already an in-flight instantiation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instantiationAlreadyInProgress"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/instantiationAlreadyInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorInstantiationAlreadyInProgress"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.instantiationAlreadyInProgress",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/instantiationalreadyinprogress"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/invalidPlatform": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the API isn’t available on the simulator or macOS devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPlatform"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/invalidPlatform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorInvalidPlatform"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.invalidPlatform",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/invalidplatform"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingBackgroundMode": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the app doesn’t have the background mode in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingBackgroundMode"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingBackgroundMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorMissingBackgroundMode"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.missingBackgroundMode",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/missingbackgroundmode"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingEntitlement": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the app is missing the entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingEntitlement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorMissingEntitlement"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.missingEntitlement",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/missingentitlement"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingPushServerEnvironment": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the app doesn’t have the push notification capability in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPushServerEnvironment"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingPushServerEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorMissingPushServerEnvironment"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.missingPushServerEnvironment",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/missingpushserverenvironment"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An instantiation error that indicates an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.unknown",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/unknown"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationErrorDomain": {
      "abstract": [
        {
          "text": "A string representation of the instantiation error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationErrorDomain",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Push-to-Talk-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelErrorDomain",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationErrorDomain"
      ],
      "title": "Push to Talk errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/unknown",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/invalidPlatform",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingBackgroundMode",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingPushServerEnvironment",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingEntitlement",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/instantiationAlreadyInProgress"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PTInstantiationError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pushtotalk/documentation/PushToTalk"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-codes",
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/unknown",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/invalidPlatform",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingBackgroundMode",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingPushServerEnvironment",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingEntitlement",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/instantiationAlreadyInProgress"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Push-to-Talk-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelErrorDomain",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationErrorDomain"
              ],
              "title": "Push to Talk errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PTInstantiationError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/title",
          "value": "PTInstantiationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationErrorDomain/title",
          "value": "PTInstantiationErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingEntitlement/title",
          "value": "PTInstantiationErrorMissingEntitlement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingEntitlement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorMissingEntitlement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1unknown/title",
          "value": "PTInstantiationErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1instantiationAlreadyInProgress/title",
          "value": "PTInstantiationErrorInstantiationAlreadyInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1instantiationAlreadyInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorInstantiationAlreadyInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelErrorDomain/title",
          "value": "PTChannelErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingBackgroundMode/title",
          "value": "PTInstantiationErrorMissingBackgroundMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingBackgroundMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorMissingBackgroundMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/title",
          "value": "PTChannelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1invalidPlatform/title",
          "value": "PTInstantiationErrorInvalidPlatform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1invalidPlatform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorInvalidPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingPushServerEnvironment/title",
          "value": "PTInstantiationErrorMissingPushServerEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingPushServerEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorMissingPushServerEnvironment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
