{
  "abstract": [
    {
      "text": "An instantiation error that indicates the app doesn’t have the push notification capability in an enabled state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pushtotalk/documentation/PushToTalk",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/missingPushServerEnvironment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC20PTInstantiationErrorLeV28missingPushServerEnvironmentSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "missingPushServerEnvironment"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC20PTInstantiationErrorLeV",
        "text": "PTInstantiationError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PTInstantiationError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Push to Talk"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "missingPushServerEnvironment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "missingPushServerEnvironment"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC20PTInstantiationErrorLeV",
              "text": "PTInstantiationError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PTInstantiationError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk": {
      "abstract": [
        {
          "text": "Display the system user interface for your app’s Push to Talk services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk",
      "kind": "symbol",
      "role": "collection",
      "title": "Push to Talk",
      "type": "topic",
      "url": "/documentation/pushtotalk"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an instantiation error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTInstantiationError"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationError"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for instantiation operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/instantiationAlreadyInProgress": {
      "abstract": [
        {
          "text": "An instantiation error that indicates there’s already an in-flight instantiation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instantiationAlreadyInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20PTInstantiationErrorLeV",
          "text": "PTInstantiationError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTInstantiationError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/instantiationAlreadyInProgress",
      "kind": "symbol",
      "role": "symbol",
      "title": "instantiationAlreadyInProgress",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/instantiationalreadyinprogress"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/invalidPlatform": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the API isn’t available on the simulator or macOS devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPlatform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20PTInstantiationErrorLeV",
          "text": "PTInstantiationError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTInstantiationError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/invalidPlatform",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidPlatform",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/invalidplatform"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/missingBackgroundMode": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the app doesn’t have the background mode in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingBackgroundMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20PTInstantiationErrorLeV",
          "text": "PTInstantiationError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTInstantiationError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/missingBackgroundMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingBackgroundMode",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/missingbackgroundmode"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/missingEntitlement": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the app is missing the entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20PTInstantiationErrorLeV",
          "text": "PTInstantiationError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTInstantiationError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/missingEntitlement",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingEntitlement",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/missingentitlement"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/missingPushServerEnvironment": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the app doesn’t have the push notification capability in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPushServerEnvironment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20PTInstantiationErrorLeV",
          "text": "PTInstantiationError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTInstantiationError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/missingPushServerEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingPushServerEnvironment",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/missingpushserverenvironment"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "An instantiation error that indicates an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20PTInstantiationErrorLeV",
          "text": "PTInstantiationError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTInstantiationError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/unknown",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/invalidPlatform",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/missingBackgroundMode",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/missingEntitlement",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/instantiationAlreadyInProgress"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/title",
          "value": "PTInstantiationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pushtotalk/ptinstantiationerror-swift.struct/missingpushserverenvironment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
