{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error",
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code/RawRepresentable-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Background Tasks"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "RawRepresentable Implementations"
  },
  "references": {
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks": {
      "abstract": [
        {
          "text": "Request the system to launch your app in the background to run tasks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks",
      "kind": "symbol",
      "role": "collection",
      "title": "Background Tasks",
      "type": "topic",
      "url": "/documentation/backgroundtasks"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler": {
      "abstract": [
        {
          "text": "A class for scheduling task requests that launch your app in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGTaskScheduler"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGTaskScheduler"
        }
      ],
      "role": "symbol",
      "title": "BGTaskScheduler",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgtaskscheduler"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error": {
      "abstract": [
        {
          "text": "The Errors for the ",
          "type": "text"
        },
        {
          "code": "BGTaskSchedulerError",
          "type": "codeVoice"
        },
        {
          "text": " domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "BGTaskScheduler.Error",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgtaskscheduler/error"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code": {
      "abstract": [
        {
          "text": "An enumeration of the task scheduling errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "BGTaskScheduler.Error.Code",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgtaskscheduler/error/code"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code/hash(into:)": {
      "abstract": [],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": " and ",
            "type": "text"
          },
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hash"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "into"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6HasherV",
          "text": "Hasher"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code/hash(into:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "hash(into:)",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgtaskscheduler/error/code/hash(into:)"
    },
    "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code/hashValue": {
      "abstract": [],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": " and ",
            "type": "text"
          },
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hashValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code/hashValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "hashValue",
      "type": "topic",
      "url": "/documentation/backgroundtasks/bgtaskscheduler/error/code/hashvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code/hashValue"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.backgroundtasks/documentation/BackgroundTasks/BGTaskScheduler/Error/Code/hash(into:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskScheduler~1Error~1Code/title",
          "value": "BGTaskSchedulerErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskScheduler~1Error~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskSchedulerErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskScheduler~1Error~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskSchedulerErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskScheduler/title",
          "value": "BGTaskScheduler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskScheduler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskScheduler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundtasks~1documentation~1BackgroundTasks~1BGTaskScheduler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskScheduler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/backgroundtasks/bgtaskscheduler/error/code/rawrepresentable-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
