{
  "abstract": [
    {
      "text": "An image to display on devices running in a 1x resolution mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits/screenScale1x"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TVTopShelfItemImageTraits@TVTopShelfItemImageTraitScreenScale1x",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "screenScale1x"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)TVTopShelfItem",
        "text": "TVTopShelfItem"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@TVTopShelfItemImageTraits",
        "text": "ImageTraits"
      }
    ],
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVTopShelfItemImageTraitScreenScale1x"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "screenScale1x"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "screenScale1x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)TVTopShelfItem",
              "text": "TVTopShelfItem"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@TVTopShelfItemImageTraits",
              "text": "ImageTraits"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem": {
      "abstract": [
        {
          "text": "An item that uses an image to represent a movie, show, or other content in the top shelf.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVTopShelfItem"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfItem"
        }
      ],
      "role": "symbol",
      "title": "TVTopShelfItem",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfitem"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits": {
      "abstract": [
        {
          "text": "Constants describing the image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImageTraits"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImageTraits"
        }
      ],
      "role": "symbol",
      "title": "TVTopShelfItem.ImageTraits",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfitem/imagetraits"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits/screenScale1x": {
      "abstract": [
        {
          "text": "An image to display on devices running in a 1x resolution mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenScale1x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfItem",
          "text": "TVTopShelfItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfItemImageTraits",
          "text": "ImageTraits"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits/screenScale1x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfItemImageTraitScreenScale1x"
        }
      ],
      "role": "symbol",
      "title": "screenScale1x",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfitem/imagetraits/screenscale1x"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits/screenScale2x": {
      "abstract": [
        {
          "text": "A high-resolution image to display on devices running in a 2x resolution mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenScale2x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfItem",
          "text": "TVTopShelfItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfItemImageTraits",
          "text": "ImageTraits"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits/screenScale2x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfItemImageTraitScreenScale2x"
        }
      ],
      "role": "symbol",
      "title": "screenScale2x",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfitem/imagetraits/screenscale2x"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Traits",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits/screenScale2x"
      ],
      "title": "Image Traits"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVTopShelfItemImageTraitScreenScale1x"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfItemImageTraitScreenScale1x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvservices/documentation/TVServices",
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-Traits",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfItem/ImageTraits/screenScale2x"
              ],
              "title": "Image Traits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "TVTopShelfItemImageTraitScreenScale1x"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfItem~1ImageTraits~1screenScale2x/title",
          "value": "TVTopShelfItemImageTraitScreenScale2x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfItem~1ImageTraits~1screenScale2x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfItemImageTraitScreenScale2x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfItem~1ImageTraits/title",
          "value": "TVTopShelfItemImageTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfItem~1ImageTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfItemImageTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfItem~1ImageTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfItemImageTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfItem~1ImageTraits~1screenScale1x/title",
          "value": "TVTopShelfItemImageTraitScreenScale1x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfItem~1ImageTraits~1screenScale1x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfItemImageTraitScreenScale1x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfItem/title",
          "value": "TVTopShelfItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/tvtopshelfitem/imagetraits/screenscale1x"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvservices/tvtopshelfitem/imagetraits/screenscale1x"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
