{
  "abstract": [
    {
      "text": "Identifies the clear action icon.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/clear"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UISearchBarIcon@UISearchBarIconClear",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "clear"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISearchBarIconClear"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UISearchBar.Icon.clear"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "clear"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, the corresponding icon is a circle containing an X.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar": {
      "abstract": [
        {
          "text": "A specialized view for receiving search-related information from the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchBar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchBar"
        }
      ],
      "role": "symbol",
      "title": "UISearchBar",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon": {
      "abstract": [
        {
          "text": "Constants to identify the icons used in the search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Icon"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Icon"
        }
      ],
      "role": "symbol",
      "title": "UISearchBar.Icon",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/icon"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/bookmark": {
      "abstract": [
        {
          "text": "Identifies the bookmarks icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bookmark"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/bookmark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchBarIconBookmark"
        }
      ],
      "role": "symbol",
      "title": "UISearchBar.Icon.bookmark",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/icon/bookmark"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/clear": {
      "abstract": [
        {
          "text": "Identifies the clear action icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clear"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/clear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchBarIconClear"
        }
      ],
      "role": "symbol",
      "title": "UISearchBar.Icon.clear",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/icon/clear"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/resultsList": {
      "abstract": [
        {
          "text": "Identifies the results list icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultsList"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/resultsList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchBarIconResultsList"
        }
      ],
      "role": "symbol",
      "title": "UISearchBar.Icon.resultsList",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/icon/resultslist"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/search": {
      "abstract": [
        {
          "text": "Identifies the search icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchBarIconSearch"
        }
      ],
      "role": "symbol",
      "title": "UISearchBar.Icon.search",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/icon/search"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/search",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/bookmark",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/resultsList"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISearchBarIconClear"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarIconClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/search",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/bookmark",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/Icon/resultsList"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UISearchBarIconClear"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title",
          "value": "UISearchBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon~1search/title",
          "value": "UISearchBarIconSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarIconSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon~1bookmark/title",
          "value": "UISearchBarIconBookmark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon~1bookmark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarIconBookmark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon~1resultsList/title",
          "value": "UISearchBarIconResultsList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon~1resultsList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarIconResultsList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon~1clear/title",
          "value": "UISearchBarIconClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon~1clear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarIconClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon/title",
          "value": "UISearchBarIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1Icon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarIcon"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisearchbar/icon/clear"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisearchbar/icon/clear"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
