{
  "abstract": [
    {
      "text": "The types of search completions to include.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/resultTypes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKLocalSearchCompleter(py)resultTypes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resultTypes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKLocalSearchCompleter",
        "text": "MKLocalSearchCompleter"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MKLocalSearchCompleterResultType",
        "text": "ResultType"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "resultTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "resultTypes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resultTypes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKLocalSearchCompleter",
              "text": "MKLocalSearchCompleter"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MKLocalSearchCompleterResultType",
              "text": "ResultType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter": {
      "abstract": [
        {
          "text": "A utility object for generating a list of completion strings based on a partial search string that you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLocalSearchCompleter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLocalSearchCompleter"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum": {
      "abstract": [
        {
          "text": "Constants indicating the types of search completions to return.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FilterType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FilterType"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter.FilterType",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/filtertype-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType": {
      "abstract": [
        {
          "text": "Options that indicate types of search completions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResultType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResultType"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter.ResultType",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/resulttype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/addressFilter": {
      "abstract": [
        {
          "text": "A filter that lists which address options to include or exclude in search results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/addressFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addressFilter"
        }
      ],
      "role": "symbol",
      "title": "addressFilter",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/addressfilter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/filterType-swift.property": {
      "abstract": [
        {
          "text": "The filter options for the search results.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filterType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLocalSearchCompleter",
          "text": "MKLocalSearchCompleter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKSearchCompletionFilterType",
          "text": "FilterType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/filterType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filterType"
        }
      ],
      "role": "symbol",
      "title": "filterType",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/filtertype-swift.property"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/pointOfInterestFilter": {
      "abstract": [
        {
          "text": "A filter that lists point of interest categories to include or exclude in the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointOfInterestFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKPointOfInterestFilter",
          "text": "MKPointOfInterestFilter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/pointOfInterestFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointOfInterestFilter"
        }
      ],
      "role": "symbol",
      "title": "pointOfInterestFilter",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/pointofinterestfilter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/queryFragment": {
      "abstract": [
        {
          "text": "The search string that you want completions for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryFragment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/queryFragment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queryFragment"
        }
      ],
      "role": "symbol",
      "title": "queryFragment",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/queryfragment"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/region": {
      "abstract": [
        {
          "text": "The region that defines the geographic scope of the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "region"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKCoordinateRegion",
          "text": "MKCoordinateRegion"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/region",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "region"
        }
      ],
      "role": "symbol",
      "title": "region",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/region"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/regionPriority": {
      "abstract": [
        {
          "text": "A value that indicates the importance of the configured region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionPriority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKLocalSearchRegionPriority",
          "text": "MKLocalSearchRegionPriority"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/regionPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regionPriority"
        }
      ],
      "role": "symbol",
      "title": "regionPriority",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/regionpriority"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/resultTypes": {
      "abstract": [
        {
          "text": "The types of search completions to include.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLocalSearchCompleter",
          "text": "MKLocalSearchCompleter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKLocalSearchCompleterResultType",
          "text": "ResultType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/resultTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resultTypes"
        }
      ],
      "role": "symbol",
      "title": "resultTypes",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/resulttypes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-query-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/addressFilter",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/queryFragment",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/region",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/regionPriority",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/pointOfInterestFilter",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/filterType-swift.property",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType"
      ],
      "title": "Specifying the query attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "resultTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resultTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-the-query-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/addressFilter",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/queryFragment",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/region",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/regionPriority",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/pointOfInterestFilter",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/filterType-swift.property",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType"
              ],
              "title": "Specifying the query attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MKLocalSearchCompleterResultType",
                    "text": "MKLocalSearchCompleterResultType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "resultTypes"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1region/title",
          "value": "region"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1region/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "region"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1queryFragment/title",
          "value": "queryFragment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1queryFragment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "queryFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/title",
          "value": "MKLocalSearchCompleter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1resultTypes/title",
          "value": "resultTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1resultTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resultTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1regionPriority/title",
          "value": "regionPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1regionPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regionPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1pointOfInterestFilter/title",
          "value": "pointOfInterestFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1pointOfInterestFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointOfInterestFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1filterType-swift.property/title",
          "value": "filterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1filterType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "filterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum/title",
          "value": "MKSearchCompletionFilterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSearchCompletionFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSearchCompletionFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1addressFilter/title",
          "value": "addressFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1addressFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addressFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/title",
          "value": "MKLocalSearchCompleterResultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleterResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleterResultType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mklocalsearchcompleter/resulttypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mklocalsearchcompleter/resulttypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
