{
  "abstract": [
    {
      "text": "A prepopulated shipping address.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/shippingContact"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKPaymentRequest(py)shippingContact",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shippingContact"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PKContact",
        "text": "PKContact"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "shippingContact"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "shippingContact"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shippingContact"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContact",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKContact",
              "text": "PKContact"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.passkit/documentation/PassKit/displaying-a-read-only-pickup-address"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you have an up-to-date shipping address on file, you can set this property to that address. This shipping address appears in the payment sheet. When the framework presents the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the user can either keep the address you specified or enter a different address.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Note that a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContact",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that represents a shipping contact contains information for only the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContact/postalAddress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContact/emailAddress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContact/phoneNumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. The framework sets all other properties in the object to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKContact": {
      "abstract": [
        {
          "text": "An object that encapsulates contact information needed for billing and shipping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKContact"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKContact"
        }
      ],
      "role": "symbol",
      "title": "PKContact",
      "type": "topic",
      "url": "/documentation/passkit/pkcontact"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKContact/emailAddress": {
      "abstract": [
        {
          "text": "The contact’s email address, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if the contact’s email is not needed for the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emailAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContact/emailAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emailAddress"
        }
      ],
      "role": "symbol",
      "title": "emailAddress",
      "type": "topic",
      "url": "/documentation/passkit/pkcontact/emailaddress"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKContact/phoneNumber": {
      "abstract": [
        {
          "text": "The contact’s telephone number, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if the contact’s phone number is not needed for the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNPhoneNumber",
          "text": "CNPhoneNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContact/phoneNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "phoneNumber"
        }
      ],
      "role": "symbol",
      "title": "phoneNumber",
      "type": "topic",
      "url": "/documentation/passkit/pkcontact/phonenumber"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKContact/postalAddress": {
      "abstract": [
        {
          "text": "The contact’s full postal address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNPostalAddress",
          "text": "CNPostalAddress"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContact/postalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postalAddress"
        }
      ],
      "role": "symbol",
      "title": "postalAddress",
      "type": "topic",
      "url": "/documentation/passkit/pkcontact/postaladdress"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController": {
      "abstract": [
        {
          "text": "An object that presents a sheet that prompts the user to authorize a payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentAuthorizationViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentAuthorizationViewController"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentAuthorizationViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentauthorizationviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest": {
      "abstract": [
        {
          "text": "An object that represents a request for payment, including details about payment-processing capabilities, the payment amount, and shipping information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/billingContact": {
      "abstract": [
        {
          "text": "A prepopulated billing address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billingContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKContact",
          "text": "PKContact"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/billingContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "billingContact"
        }
      ],
      "role": "symbol",
      "title": "billingContact",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest/billingcontact"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/shippingContact": {
      "abstract": [
        {
          "text": "A prepopulated shipping address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shippingContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKContact",
          "text": "PKContact"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/shippingContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shippingContact"
        }
      ],
      "role": "symbol",
      "title": "shippingContact",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentrequest/shippingcontact"
    },
    "doc://com.apple.passkit/documentation/PassKit/displaying-a-read-only-pickup-address": {
      "abstract": [
        {
          "text": "Configure a payment request to display a read-only pickup address on the payment sheet.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/displaying-a-read-only-pickup-address",
      "kind": "article",
      "role": "article",
      "title": "Displaying a Read-Only Pickup Address",
      "type": "topic",
      "url": "/documentation/passkit/displaying-a-read-only-pickup-address"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-known-contact-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/billingContact",
        "doc://com.apple.passkit/documentation/PassKit/PKContact"
      ],
      "title": "Providing known contact information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "shippingContact"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shippingContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-known-contact-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentRequest/billingContact",
                "doc://com.apple.passkit/documentation/PassKit/PKContact"
              ],
              "title": "Providing known contact information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContact",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PKContact",
                    "text": "PKContact"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "shippingContact"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContact/title",
          "value": "PKContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContact/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContact~1postalAddress/title",
          "value": "postalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContact~1postalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest/title",
          "value": "PKPaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1shippingContact/title",
          "value": "shippingContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1shippingContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shippingContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1billingContact/title",
          "value": "billingContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentRequest~1billingContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "billingContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContact~1phoneNumber/title",
          "value": "phoneNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContact~1phoneNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "phoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewController/title",
          "value": "PKPaymentAuthorizationViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentAuthorizationViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentAuthorizationViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContact~1emailAddress/title",
          "value": "emailAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContact~1emailAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emailAddress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentrequest/shippingcontact"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentrequest/shippingcontact"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
