{
  "abstract": [
    {
      "text": "The error codes that may be passed in an error object for the Bluetooth picker completion block.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EABluetoothAccessoryPickerErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "External Accessory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "EABluetoothAccessoryPickerError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory": {
      "abstract": [
        {
          "text": "Communicate with accessories that connect to a device with the Apple Lightning connector, or with Bluetooth wireless technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory",
      "kind": "symbol",
      "role": "collection",
      "title": "External Accessory",
      "type": "topic",
      "url": "/documentation/externalaccessory"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAAccessoryManager/showBluetoothAccessoryPicker(withNameFilter:completion:)": {
      "abstract": [
        {
          "text": "Displays an alert that allows the user to pair the device with a Bluetooth accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showBluetoothAccessoryPicker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withNameFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@EABluetoothAccessoryPickerCompletion",
          "text": "EABluetoothAccessoryPickerCompletion"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAAccessoryManager/showBluetoothAccessoryPicker(withNameFilter:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showBluetoothAccessoryPickerWithNameFilter:completion:"
        }
      ],
      "role": "symbol",
      "title": "showBluetoothAccessoryPicker(withNameFilter:completion:)",
      "type": "topic",
      "url": "/documentation/externalaccessory/eaaccessorymanager/showbluetoothaccessorypicker(withnamefilter:completion:)"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerCompletion": {
      "abstract": [
        {
          "text": "The completion block for the Bluetooth picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerCompletion"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerCompletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerCompletion"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerCompletion",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickercompletion"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError": {
      "abstract": [
        {
          "text": "Error codes returned by the Bluetooth accessory picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerError"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerError"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerError",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererror"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code": {
      "abstract": [
        {
          "text": "The error codes that may be passed in an error object for the Bluetooth picker completion block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerError.Code",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererror/code"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/alreadyConnected": {
      "abstract": [
        {
          "text": "The specified accessory was already connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyConnected"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/alreadyConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerAlreadyConnected"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerError.Code.alreadyConnected",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererror/code/alreadyconnected"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererror/code/init(rawvalue:)"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultCancelled": {
      "abstract": [
        {
          "text": "The user canceled the picker alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultCancelled"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerResultCancelled"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerError.Code.resultCancelled",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererror/code/resultcancelled"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultFailed": {
      "abstract": [
        {
          "text": "Selecting an accessory failed for an unknown reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultFailed"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerResultFailed"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerError.Code.resultFailed",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererror/code/resultfailed"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultNotFound": {
      "abstract": [
        {
          "text": "The specified accessory could not be found, perhaps because it was turned off prior to connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultNotFound"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerResultNotFound"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerError.Code.resultNotFound",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererror/code/resultnotfound"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerErrorDomain": {
      "abstract": [
        {
          "text": "The domain for errors passed to a Bluetooth picker completion block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerErrorDomain",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presenting-the-Bluetooth-Picker",
      "generated": true,
      "identifiers": [
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAAccessoryManager/showBluetoothAccessoryPicker(withNameFilter:completion:)",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerCompletion",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerErrorDomain"
      ],
      "title": "Presenting the Bluetooth Picker"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/alreadyConnected",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultNotFound",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultCancelled",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultFailed"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EABluetoothAccessoryPickerErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/alreadyConnected",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultNotFound",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultCancelled",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code/resultFailed"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presenting-the-Bluetooth-Picker",
              "generated": true,
              "identifiers": [
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAAccessoryManager/showBluetoothAccessoryPicker(withNameFilter:completion:)",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerCompletion",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerErrorDomain"
              ],
              "title": "Presenting the Bluetooth Picker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "EABluetoothAccessoryPickerErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAAccessoryManager~1showBluetoothAccessoryPicker(withNameFilter:completion:)/title",
          "value": "showBluetoothAccessoryPickerWithNameFilter:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAAccessoryManager~1showBluetoothAccessoryPicker(withNameFilter:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showBluetoothAccessoryPickerWithNameFilter:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code~1resultCancelled/title",
          "value": "EABluetoothAccessoryPickerResultCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code~1resultCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerResultCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code~1alreadyConnected/title",
          "value": "EABluetoothAccessoryPickerAlreadyConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code~1alreadyConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerAlreadyConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code~1resultFailed/title",
          "value": "EABluetoothAccessoryPickerResultFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code~1resultFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerResultFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code/title",
          "value": "EABluetoothAccessoryPickerErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerCompletion/title",
          "value": "EABluetoothAccessoryPickerCompletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerCompletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerCompletion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerErrorDomain/title",
          "value": "EABluetoothAccessoryPickerErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code~1resultNotFound/title",
          "value": "EABluetoothAccessoryPickerResultNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code~1resultNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerResultNotFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/externalaccessory/eabluetoothaccessorypickererror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/externalaccessory/eabluetoothaccessorypickererror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
