{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/c-language-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "C-Language Symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_advertise_descriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_advertise_descriptor"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_advertise_descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_advertise_descriptor"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_advertise_descriptor",
      "type": "topic",
      "url": "/documentation/network/os_nw_advertise_descriptor"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_browse_descriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_browse_descriptor"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_browse_descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_browse_descriptor"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_browse_descriptor",
      "type": "topic",
      "url": "/documentation/network/os_nw_browse_descriptor"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_browse_result": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_browse_result"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_browse_result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_browse_result"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_browse_result",
      "type": "topic",
      "url": "/documentation/network/os_nw_browse_result"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_browser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_browser"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_browser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_browser"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_browser",
      "type": "topic",
      "url": "/documentation/network/os_nw_browser"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_connection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_connection"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_connection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_connection"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_connection",
      "type": "topic",
      "url": "/documentation/network/os_nw_connection"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_connection_group": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_connection_group"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_connection_group",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_connection_group"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_connection_group",
      "type": "topic",
      "url": "/documentation/network/os_nw_connection_group"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_content_context": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_content_context"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_content_context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_content_context"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_content_context",
      "type": "topic",
      "url": "/documentation/network/os_nw_content_context"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_data_transfer_report": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_data_transfer_report"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_data_transfer_report",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_data_transfer_report"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_data_transfer_report",
      "type": "topic",
      "url": "/documentation/network/os_nw_data_transfer_report"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_endpoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_endpoint"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_endpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_endpoint"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_endpoint",
      "type": "topic",
      "url": "/documentation/network/os_nw_endpoint"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_error": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_error"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_error"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_error",
      "type": "topic",
      "url": "/documentation/network/os_nw_error"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_establishment_report": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_establishment_report"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_establishment_report",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_establishment_report"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_establishment_report",
      "type": "topic",
      "url": "/documentation/network/os_nw_establishment_report"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_ethernet_channel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_ethernet_channel"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_ethernet_channel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_ethernet_channel"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_ethernet_channel",
      "type": "topic",
      "url": "/documentation/network/os_nw_ethernet_channel"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_framer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_framer"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_framer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_framer"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_framer",
      "type": "topic",
      "url": "/documentation/network/os_nw_framer"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_group_descriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_group_descriptor"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_group_descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_group_descriptor"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_group_descriptor",
      "type": "topic",
      "url": "/documentation/network/os_nw_group_descriptor"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_interface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_interface"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_interface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_interface"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_interface",
      "type": "topic",
      "url": "/documentation/network/os_nw_interface"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_listener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_listener"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_listener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_listener"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_listener",
      "type": "topic",
      "url": "/documentation/network/os_nw_listener"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_object": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_object"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_object",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_object"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_object",
      "type": "topic",
      "url": "/documentation/network/os_nw_object"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_parameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_parameters"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_parameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_parameters"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_parameters",
      "type": "topic",
      "url": "/documentation/network/os_nw_parameters"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_path": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_path"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_path",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_path"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_path",
      "type": "topic",
      "url": "/documentation/network/os_nw_path"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_path_monitor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_path_monitor"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_path_monitor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_path_monitor"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_path_monitor",
      "type": "topic",
      "url": "/documentation/network/os_nw_path_monitor"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_privacy_context": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_privacy_context"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_privacy_context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_privacy_context"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_privacy_context",
      "type": "topic",
      "url": "/documentation/network/os_nw_privacy_context"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_protocol_definition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_protocol_definition"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_protocol_definition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_protocol_definition"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_protocol_definition",
      "type": "topic",
      "url": "/documentation/network/os_nw_protocol_definition"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_protocol_metadata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_protocol_metadata"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_protocol_metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_protocol_metadata"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_protocol_metadata",
      "type": "topic",
      "url": "/documentation/network/os_nw_protocol_metadata"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_protocol_options": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_protocol_options"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_protocol_options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_protocol_options"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_protocol_options",
      "type": "topic",
      "url": "/documentation/network/os_nw_protocol_options"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_protocol_stack": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_protocol_stack"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_protocol_stack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_protocol_stack"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_protocol_stack",
      "type": "topic",
      "url": "/documentation/network/os_nw_protocol_stack"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_proxy_config": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_proxy_config"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_proxy_config",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_proxy_config"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_proxy_config",
      "type": "topic",
      "url": "/documentation/network/os_nw_proxy_config"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_relay_hop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_relay_hop"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_relay_hop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_relay_hop"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_relay_hop",
      "type": "topic",
      "url": "/documentation/network/os_nw_relay_hop"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_resolution_report": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_resolution_report"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_resolution_report",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_resolution_report"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_resolution_report",
      "type": "topic",
      "url": "/documentation/network/os_nw_resolution_report"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_resolver_config": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_resolver_config"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_resolver_config",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_resolver_config"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_resolver_config",
      "type": "topic",
      "url": "/documentation/network/os_nw_resolver_config"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_txt_record": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_txt_record"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_txt_record",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_txt_record"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_txt_record",
      "type": "topic",
      "url": "/documentation/network/os_nw_txt_record"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_ws_request": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_ws_request"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_ws_request",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_ws_request"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_ws_request",
      "type": "topic",
      "url": "/documentation/network/os_nw_ws_request"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_ws_response": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_ws_response"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_ws_response",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_ws_response"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_ws_response",
      "type": "topic",
      "url": "/documentation/network/os_nw_ws_response"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a browser is able to discover services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_state_t": {
      "abstract": [
        {
          "text": "States that indicate whether you can use a connection group to send and receive messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a connection can be used to send and receive data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a data transfer report is collected yet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_type_t": {
      "abstract": [
        {
          "text": "The type of a network endpoint, such as a host or a service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_type_t"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_type_t",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_type_t"
    },
    "doc://com.apple.network/documentation/Network/nw_error_domain_t": {
      "abstract": [
        {
          "text": "The error domain for errors used by the Network framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_error_domain_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_error_domain_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_error_domain_t"
        }
      ],
      "role": "symbol",
      "title": "nw_error_domain_t",
      "type": "topic",
      "url": "/documentation/network/nw_error_domain_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t": {
      "abstract": [
        {
          "text": "States indicating whether an Ethernet channel is able to send and receive frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_start_result_t": {
      "abstract": [
        {
          "text": "Results that you send to indicate the disposition of your protocol after the start handler is invoked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_start_result_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_start_result_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_start_result_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_start_result_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_start_result_t"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_type_t": {
      "abstract": [
        {
          "text": "Types of network interfaces, based on their link layer media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_type_t"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_type_t",
      "type": "topic",
      "url": "/documentation/network/nw_interface_type_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t": {
      "abstract": [
        {
          "text": "Flag values for Explicit Congestion Notifications in IP packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_ecn_flag_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t": {
      "abstract": [
        {
          "text": "Types of local addresses that can be selected, such as temporary or stable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_local_address_preference_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_local_address_preference_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_local_address_preference_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_local_address_preference_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_version_t": {
      "abstract": [
        {
          "text": "IP versions to require on connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_version_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_version_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_version_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_version_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_version_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a listener is able to accept incoming connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_multipath_service_t": {
      "abstract": [
        {
          "text": "Modes in which a connection can support multipath protocols.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_multipath_service_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_multipath_service_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_multipath_service_t"
        }
      ],
      "role": "symbol",
      "title": "nw_multipath_service_t",
      "type": "topic",
      "url": "/documentation/network/nw_multipath_service_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t": {
      "abstract": [
        {
          "text": "Options for configuring how expired DNS answers should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_expired_dns_behavior_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_expired_dns_behavior_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_expired_dns_behavior_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_expired_dns_behavior_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_status_t": {
      "abstract": [
        {
          "text": "Status values indicating whether a path can be used by connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_status_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_status_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_status_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_status_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_status_t"
    },
    "doc://com.apple.network/documentation/Network/nw_report_resolution_protocol_t": {
      "abstract": [
        {
          "text": "A set of transport protocols connections use for DNS resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_report_resolution_protocol_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_report_resolution_protocol_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_report_resolution_protocol_t"
        }
      ],
      "role": "symbol",
      "title": "nw_report_resolution_protocol_t",
      "type": "topic",
      "url": "/documentation/network/nw_report_resolution_protocol_t"
    },
    "doc://com.apple.network/documentation/Network/nw_report_resolution_source_t": {
      "abstract": [
        {
          "text": "Sources that may provide DNS responses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_report_resolution_source_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_report_resolution_source_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_report_resolution_source_t"
        }
      ],
      "role": "symbol",
      "title": "nw_report_resolution_source_t",
      "type": "topic",
      "url": "/documentation/network/nw_report_resolution_source_t"
    },
    "doc://com.apple.network/documentation/Network/nw_service_class_t": {
      "abstract": [
        {
          "text": "Levels of service quality that can be used with a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_service_class_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_service_class_t"
        }
      ],
      "role": "symbol",
      "title": "nw_service_class_t",
      "type": "topic",
      "url": "/documentation/network/nw_service_class_t"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t": {
      "abstract": [
        {
          "text": "Status values describing what kind of value is stored in a TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_find_key_t",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_find_key_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_t": {
      "abstract": [
        {
          "text": "Types of codes used upon closing a WebSocket connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_opcode_t": {
      "abstract": [
        {
          "text": "Types of messages that you send and receive on a WebSocket connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_opcode_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_opcode_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_opcode_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_opcode_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_opcode_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_response_status_t": {
      "abstract": [
        {
          "text": "Status values that are sent with a WebSocket server response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_response_status_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_response_status_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_response_status_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_response_status_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_response_status_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_version_t": {
      "abstract": [
        {
          "text": "Supported versions of the WebSocket protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_version_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_version_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_version_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_version_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_version_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "C-Network-Structures",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_group_state_t",
        "doc://com.apple.network/documentation/Network/nw_browser_state_t",
        "doc://com.apple.network/documentation/Network/nw_connection_state_t",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t",
        "doc://com.apple.network/documentation/Network/nw_endpoint_type_t",
        "doc://com.apple.network/documentation/Network/nw_error_domain_t",
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t",
        "doc://com.apple.network/documentation/Network/nw_framer_start_result_t",
        "doc://com.apple.network/documentation/Network/nw_interface_type_t",
        "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t",
        "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t",
        "doc://com.apple.network/documentation/Network/nw_ip_version_t",
        "doc://com.apple.network/documentation/Network/nw_listener_state_t",
        "doc://com.apple.network/documentation/Network/nw_multipath_service_t",
        "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t",
        "doc://com.apple.network/documentation/Network/nw_path_status_t",
        "doc://com.apple.network/documentation/Network/nw_report_resolution_protocol_t",
        "doc://com.apple.network/documentation/Network/nw_report_resolution_source_t",
        "doc://com.apple.network/documentation/Network/nw_service_class_t",
        "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_t",
        "doc://com.apple.network/documentation/Network/nw_ws_opcode_t",
        "doc://com.apple.network/documentation/Network/nw_ws_response_status_t",
        "doc://com.apple.network/documentation/Network/nw_ws_version_t"
      ],
      "title": "C Network Structures"
    },
    {
      "anchor": "C-Network-Protocols",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/OS_nw_advertise_descriptor",
        "doc://com.apple.network/documentation/Network/OS_nw_browse_descriptor",
        "doc://com.apple.network/documentation/Network/OS_nw_browse_result",
        "doc://com.apple.network/documentation/Network/OS_nw_browser",
        "doc://com.apple.network/documentation/Network/OS_nw_connection",
        "doc://com.apple.network/documentation/Network/OS_nw_connection_group",
        "doc://com.apple.network/documentation/Network/OS_nw_content_context",
        "doc://com.apple.network/documentation/Network/OS_nw_data_transfer_report",
        "doc://com.apple.network/documentation/Network/OS_nw_endpoint",
        "doc://com.apple.network/documentation/Network/OS_nw_error",
        "doc://com.apple.network/documentation/Network/OS_nw_establishment_report",
        "doc://com.apple.network/documentation/Network/OS_nw_ethernet_channel",
        "doc://com.apple.network/documentation/Network/OS_nw_framer",
        "doc://com.apple.network/documentation/Network/OS_nw_group_descriptor",
        "doc://com.apple.network/documentation/Network/OS_nw_interface",
        "doc://com.apple.network/documentation/Network/OS_nw_listener",
        "doc://com.apple.network/documentation/Network/OS_nw_object",
        "doc://com.apple.network/documentation/Network/OS_nw_parameters",
        "doc://com.apple.network/documentation/Network/OS_nw_path",
        "doc://com.apple.network/documentation/Network/OS_nw_path_monitor",
        "doc://com.apple.network/documentation/Network/OS_nw_privacy_context",
        "doc://com.apple.network/documentation/Network/OS_nw_protocol_definition",
        "doc://com.apple.network/documentation/Network/OS_nw_protocol_metadata",
        "doc://com.apple.network/documentation/Network/OS_nw_protocol_options",
        "doc://com.apple.network/documentation/Network/OS_nw_protocol_stack",
        "doc://com.apple.network/documentation/Network/OS_nw_proxy_config",
        "doc://com.apple.network/documentation/Network/OS_nw_relay_hop",
        "doc://com.apple.network/documentation/Network/OS_nw_resolution_report",
        "doc://com.apple.network/documentation/Network/OS_nw_resolver_config",
        "doc://com.apple.network/documentation/Network/OS_nw_txt_record",
        "doc://com.apple.network/documentation/Network/OS_nw_ws_request",
        "doc://com.apple.network/documentation/Network/OS_nw_ws_response"
      ],
      "title": "C Network Protocols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_stack/title",
          "value": "OS_nw_protocol_stack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_stack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_stack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_stack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_stack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_resolution_report/title",
          "value": "OS_nw_resolution_report"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_resolution_report/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_resolution_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_resolution_report/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_resolution_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_data_transfer_report/title",
          "value": "OS_nw_data_transfer_report"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_data_transfer_report/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_data_transfer_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_data_transfer_report/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_data_transfer_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browser/title",
          "value": "OS_nw_browser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_source_t/title",
          "value": "nw_report_resolution_source_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_source_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_source_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_source_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_source_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_t/title",
          "value": "nw_connection_group_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_status_t/title",
          "value": "nw_ws_response_status_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_status_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_status_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_relay_hop/title",
          "value": "OS_nw_relay_hop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_relay_hop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_relay_hop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_relay_hop/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_relay_hop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection/title",
          "value": "OS_nw_connection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_establishment_report/title",
          "value": "OS_nw_establishment_report"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_establishment_report/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_establishment_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_establishment_report/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_establishment_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_opcode_t/title",
          "value": "nw_ws_opcode_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_opcode_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_opcode_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_opcode_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_opcode_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path/title",
          "value": "OS_nw_path"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_framer/title",
          "value": "OS_nw_framer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_framer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_framer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_framer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_framer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_t/title",
          "value": "nw_ethernet_channel_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_advertise_descriptor/title",
          "value": "OS_nw_advertise_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_advertise_descriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_advertise_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_advertise_descriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_advertise_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_protocol_t/title",
          "value": "nw_report_resolution_protocol_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_protocol_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_protocol_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_protocol_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_protocol_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_t/title",
          "value": "nw_parameters_expired_dns_behavior_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_expired_dns_behavior_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_expired_dns_behavior_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_endpoint/title",
          "value": "OS_nw_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_endpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_endpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_resolver_config/title",
          "value": "OS_nw_resolver_config"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_resolver_config/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_resolver_config"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_resolver_config/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_resolver_config"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_listener/title",
          "value": "OS_nw_listener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_listener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_listener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_listener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_listener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/title",
          "value": "nw_ip_ecn_flag_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ws_request/title",
          "value": "OS_nw_ws_request"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ws_request/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_ws_request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ws_request/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_ws_request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection_group/title",
          "value": "OS_nw_connection_group"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection_group/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection_group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection_group/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection_group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_content_context/title",
          "value": "OS_nw_content_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_content_context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_content_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_content_context/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_content_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path_monitor/title",
          "value": "OS_nw_path_monitor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path_monitor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_path_monitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path_monitor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_path_monitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_error/title",
          "value": "OS_nw_error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_error/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_state_t/title",
          "value": "nw_data_transfer_report_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_proxy_config/title",
          "value": "OS_nw_proxy_config"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_proxy_config/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_proxy_config"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_proxy_config/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_proxy_config"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_interface/title",
          "value": "OS_nw_interface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_interface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_interface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_type_t/title",
          "value": "nw_endpoint_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_error_domain_t/title",
          "value": "nw_error_domain_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_error_domain_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_error_domain_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_error_domain_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_error_domain_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_privacy_context/title",
          "value": "OS_nw_privacy_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_privacy_context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_privacy_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_privacy_context/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_privacy_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_t/title",
          "value": "nw_browser_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_start_result_t/title",
          "value": "nw_framer_start_result_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_start_result_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_start_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_start_result_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_start_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_t/title",
          "value": "nw_listener_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_version_t/title",
          "value": "nw_ws_version_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_version_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_version_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_t/title",
          "value": "nw_service_class_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_options/title",
          "value": "OS_nw_protocol_options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_options/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/title",
          "value": "nw_ip_version_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_service_t/title",
          "value": "nw_multipath_service_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_service_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_service_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_service_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_service_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_t/title",
          "value": "nw_txt_record_find_key_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_txt_record/title",
          "value": "OS_nw_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_txt_record/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_txt_record/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_group_descriptor/title",
          "value": "OS_nw_group_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_group_descriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_group_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_group_descriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_group_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/title",
          "value": "nw_ip_local_address_preference_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_local_address_preference_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_local_address_preference_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ethernet_channel/title",
          "value": "OS_nw_ethernet_channel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ethernet_channel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_ethernet_channel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ethernet_channel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_ethernet_channel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ws_response/title",
          "value": "OS_nw_ws_response"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ws_response/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_ws_response"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ws_response/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_ws_response"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_metadata/title",
          "value": "OS_nw_protocol_metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_type_t/title",
          "value": "nw_interface_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_descriptor/title",
          "value": "OS_nw_browse_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_descriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browse_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_descriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browse_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_t/title",
          "value": "nw_connection_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/title",
          "value": "nw_path_status_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_object/title",
          "value": "OS_nw_object"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_object/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_object/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_parameters/title",
          "value": "OS_nw_parameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_parameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_parameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_result/title",
          "value": "OS_nw_browse_result"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_result/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browse_result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_result/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browse_result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_definition/title",
          "value": "OS_nw_protocol_definition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_definition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_definition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_t/title",
          "value": "nw_ws_close_code_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/c-language-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
