{
  "abstract": [
    {
      "text": "Configure Internet Protocol options on connections.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.network/documentation/Network/ip-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IP Options"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/framer-protocol-options": {
      "abstract": [
        {
          "text": "Create custom protocols to frame applications messages over a connection.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/framer-protocol-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Framer Protocol Options",
      "type": "topic",
      "url": "/documentation/network/framer-protocol-options"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_create_metadata()": {
      "abstract": [
        {
          "text": "Initializes an IP packet configuration with default settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_create_metadata"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_create_metadata()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_create_metadata"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_create_metadata()",
      "type": "topic",
      "url": "/documentation/network/nw_ip_create_metadata()"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t": {
      "abstract": [
        {
          "text": "Flag values for Explicit Congestion Notifications in IP packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_ecn_flag_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t": {
      "abstract": [
        {
          "text": "Types of local addresses that can be selected, such as temporary or stable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_local_address_preference_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_local_address_preference_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_local_address_preference_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_local_address_preference_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_ecn_flag(_:)": {
      "abstract": [
        {
          "text": "Checks the Explicit Congestion Notification flag value received on an IP packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_ecn_flag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_ecn_flag_t",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_ecn_flag(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_ecn_flag"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_get_ecn_flag(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_get_ecn_flag(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)": {
      "abstract": [
        {
          "text": "Access the time at which a packet was received, in nanoseconds, based on ",
          "type": "text"
        },
        {
          "code": "CLOCK_MONOTONIC_RAW",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_receive_time"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_receive_time"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_get_receive_time(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_get_receive_time(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_service_class(_:)": {
      "abstract": [
        {
          "text": "Accesses a specific service class to mark on an IP packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_service_class"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_service_class(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_service_class"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_get_service_class(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_get_service_class(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_ecn_flag(_:_:)": {
      "abstract": [
        {
          "text": "Sets a specific Explicit Congestion Notification flag value to set on an IP packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_set_ecn_flag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_ecn_flag_t",
          "text": "nw_ip_ecn_flag_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_ecn_flag(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_set_ecn_flag"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_set_ecn_flag(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_set_ecn_flag(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_service_class(_:_:)": {
      "abstract": [
        {
          "text": "Sets a specific service class to mark on an IP packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_set_service_class"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_service_class(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_set_service_class"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_set_service_class(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_set_service_class(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_calculate_receive_time(_:_:)": {
      "abstract": [
        {
          "text": "Configures a connection to deliver receive timestamps for IP packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_calculate_receive_time"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_calculate_receive_time(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_calculate_receive_time"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_calculate_receive_time(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_calculate_receive_time(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_disable_fragmentation(_:_:)": {
      "abstract": [
        {
          "text": "Configures a connection to disable fragmentation on outbound packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_disable_fragmentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_disable_fragmentation(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_disable_fragmentation"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_disable_fragmentation(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_disable_fragmentation(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_hop_limit(_:_:)": {
      "abstract": [
        {
          "text": "Configures the default hop limit for packets generated by a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_hop_limit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_hop_limit(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_hop_limit"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_hop_limit(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_hop_limit(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_local_address_preference(_:_:)": {
      "abstract": [
        {
          "text": "Configures a connection to prefer certain types of local addresses, such as temporary or stable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_local_address_preference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_local_address_preference_t",
          "text": "nw_ip_local_address_preference_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_local_address_preference(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_local_address_preference"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_local_address_preference(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_local_address_preference(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_use_minimum_mtu(_:_:)": {
      "abstract": [
        {
          "text": "Configures a connection to use the minimum MTU value, which is 1280 bytes for IPv6.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_use_minimum_mtu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_use_minimum_mtu(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_use_minimum_mtu"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_use_minimum_mtu(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_use_minimum_mtu(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_version(_:_:)": {
      "abstract": [
        {
          "text": "Sets a required IP version to disable all other versions for a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_version"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_version_t",
          "text": "nw_ip_version_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_version(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_version"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_version(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_version(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_version_t": {
      "abstract": [
        {
          "text": "IP versions to require on connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_version_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_version_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_version_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_version_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_version_t"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_copy_ip_definition()": {
      "abstract": [
        {
          "text": "Accesses the system definition of the Internet Protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_ip_definition"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_copy_ip_definition()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_ip_definition"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_copy_ip_definition()",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_copy_ip_definition()"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_ip(_:)": {
      "abstract": [
        {
          "text": "Checks whether a metadata object represents an IP packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_ip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_ip(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_ip"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_metadata_is_ip(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_metadata_is_ip(_:)"
    },
    "doc://com.apple.network/documentation/Network/quic-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the QUIC transport protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/quic-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QUIC Options",
      "type": "topic",
      "url": "/documentation/network/quic-options"
    },
    "doc://com.apple.network/documentation/Network/tcp-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the Transmission Control Protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/tcp-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TCP Options",
      "type": "topic",
      "url": "/documentation/network/tcp-options"
    },
    "doc://com.apple.network/documentation/Network/tls-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use Transport Layer Security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/tls-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TLS Options",
      "type": "topic",
      "url": "/documentation/network/tls-options"
    },
    "doc://com.apple.network/documentation/Network/udp-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the User Datagram Protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/udp-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UDP Options",
      "type": "topic",
      "url": "/documentation/network/udp-options"
    },
    "doc://com.apple.network/documentation/Network/websocket-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use WebSocket.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/websocket-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebSocket Options",
      "type": "topic",
      "url": "/documentation/network/websocket-options"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/tcp-options",
        "doc://com.apple.network/documentation/Network/tls-options",
        "doc://com.apple.network/documentation/Network/quic-options",
        "doc://com.apple.network/documentation/Network/udp-options",
        "doc://com.apple.network/documentation/Network/websocket-options",
        "doc://com.apple.network/documentation/Network/framer-protocol-options"
      ],
      "title": "Network Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-IP-Packets",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ip_create_metadata()",
        "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_ip(_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_ecn_flag(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_ecn_flag(_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t",
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_service_class(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_service_class(_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)"
      ],
      "title": "Handling IP Packets"
    },
    {
      "anchor": "Configuring-IP-Connections",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_copy_ip_definition()",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_version(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_version_t",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_calculate_receive_time(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_hop_limit(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_use_minimum_mtu(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_disable_fragmentation(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_local_address_preference(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t"
      ],
      "title": "Configuring IP Connections"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_disable_fragmentation(_:_:)/title",
          "value": "nw_ip_options_set_disable_fragmentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_disable_fragmentation(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_disable_fragmentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_ip_definition()/title",
          "value": "nw_protocol_copy_ip_definition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_ip_definition()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_copy_ip_definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_ecn_flag(_:)/title",
          "value": "nw_ip_metadata_get_ecn_flag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_ecn_flag(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_get_ecn_flag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/title",
          "value": "nw_ip_local_address_preference_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_local_address_preference_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_local_address_preference_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/title",
          "value": "nw_ip_version_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_set_ecn_flag(_:_:)/title",
          "value": "nw_ip_metadata_set_ecn_flag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_set_ecn_flag(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_set_ecn_flag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_calculate_receive_time(_:_:)/title",
          "value": "nw_ip_options_set_calculate_receive_time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_calculate_receive_time(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_calculate_receive_time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_local_address_preference(_:_:)/title",
          "value": "nw_ip_options_set_local_address_preference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_local_address_preference(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_local_address_preference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_create_metadata()/title",
          "value": "nw_ip_create_metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_create_metadata()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_create_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_service_class(_:)/title",
          "value": "nw_ip_metadata_get_service_class"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_service_class(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_get_service_class"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/title",
          "value": "nw_ip_ecn_flag_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_hop_limit(_:_:)/title",
          "value": "nw_ip_options_set_hop_limit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_hop_limit(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_hop_limit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_set_service_class(_:_:)/title",
          "value": "nw_ip_metadata_set_service_class"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_set_service_class(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_set_service_class"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_use_minimum_mtu(_:_:)/title",
          "value": "nw_ip_options_set_use_minimum_mtu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_use_minimum_mtu(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_use_minimum_mtu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_version(_:_:)/title",
          "value": "nw_ip_options_set_version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_version(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_ip(_:)/title",
          "value": "nw_protocol_metadata_is_ip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_ip(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_metadata_is_ip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_receive_time(_:)/title",
          "value": "nw_ip_metadata_get_receive_time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_receive_time(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_get_receive_time"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/ip-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
