{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.network/documentation/Network/network-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Network Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/network-constants": {
      "abstract": [
        {
          "text": "Access Network framework constants used in C.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/network-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Constants",
      "type": "topic",
      "url": "/documentation/network/network-constants"
    },
    "doc://com.apple.network/documentation/Network/network-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.network/documentation/Network/network-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Data Types",
      "type": "topic",
      "url": "/documentation/network/network-data-types"
    },
    "doc://com.apple.network/documentation/Network/network-functions": {
      "abstract": [
        {
          "text": "Access Network framework functions used in C.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/network-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Functions",
      "type": "topic",
      "url": "/documentation/network/network-functions"
    },
    "doc://com.apple.network/documentation/Network/network-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.network/documentation/Network/network-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Macros",
      "type": "topic",
      "url": "/documentation/network/network-macros"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_t",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_t"
    },
    "doc://com.apple.network/documentation/Network/nw_multipath_version_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_multipath_version_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_multipath_version_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_multipath_version_t"
        }
      ],
      "role": "symbol",
      "title": "nw_multipath_version_t",
      "type": "topic",
      "url": "/documentation/network/nw_multipath_version_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_unsatisfied_reason_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_unsatisfied_reason_t"
    },
    "doc://com.apple.network/documentation/Network/nw_quic_stream_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_quic_stream_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_quic_stream_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_quic_stream_type_t"
        }
      ],
      "role": "symbol",
      "title": "nw_quic_stream_type_t",
      "type": "topic",
      "url": "/documentation/network/nw_quic_stream_type_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/network-constants",
        "doc://com.apple.network/documentation/Network/network-functions",
        "doc://com.apple.network/documentation/Network/network-data-types",
        "doc://com.apple.network/documentation/Network/network-macros"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_t",
        "doc://com.apple.network/documentation/Network/nw_multipath_version_t",
        "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_t",
        "doc://com.apple.network/documentation/Network/nw_quic_stream_type_t"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_t/title",
          "value": "nw_path_unsatisfied_reason_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_t/title",
          "value": "nw_quic_stream_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_quic_stream_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_quic_stream_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_t/title",
          "value": "nw_interface_radio_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_version_t/title",
          "value": "nw_multipath_version_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_version_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_version_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_version_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/network-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
