{
  "abstract": [
    {
      "text": "Access Network framework constants used in C.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/network-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Network Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/NW_FRAMER_CREATE_FLAGS_DEFAULT": {
      "abstract": [
        {
          "text": "A constant flag value that indicates that the default framer protocol behavior should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NW_FRAMER_CREATE_FLAGS_DEFAULT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/NW_FRAMER_CREATE_FLAGS_DEFAULT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NW_FRAMER_CREATE_FLAGS_DEFAULT"
        }
      ],
      "role": "symbol",
      "title": "NW_FRAMER_CREATE_FLAGS_DEFAULT",
      "type": "topic",
      "url": "/documentation/network/nw_framer_create_flags_default"
    },
    "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER": {
      "abstract": [
        {
          "text": "A sentinel value that indicates that no wakeup should be delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NW_FRAMER_WAKEUP_TIME_FOREVER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NW_FRAMER_WAKEUP_TIME_FOREVER"
        }
      ],
      "role": "symbol",
      "title": "NW_FRAMER_WAKEUP_TIME_FOREVER",
      "type": "topic",
      "url": "/documentation/network/nw_framer_wakeup_time_forever"
    },
    "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT": {
      "abstract": [
        {
          "text": "A static value that indicates that inbound connections should not be limited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
        }
      ],
      "role": "symbol",
      "title": "NW_LISTENER_INFINITE_CONNECTION_LIMIT",
      "type": "topic",
      "url": "/documentation/network/nw_listener_infinite_connection_limit"
    },
    "doc://com.apple.network/documentation/Network/NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE"
        }
      ],
      "role": "symbol",
      "title": "NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE",
      "type": "topic",
      "url": "/documentation/network/nw_quic_connection_default_keepalive"
    },
    "doc://com.apple.network/documentation/Network/network-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.network/documentation/Network/network-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Data Types",
      "type": "topic",
      "url": "/documentation/network/network-data-types"
    },
    "doc://com.apple.network/documentation/Network/network-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.network/documentation/Network/network-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Enumerations",
      "type": "topic",
      "url": "/documentation/network/network-enumerations"
    },
    "doc://com.apple.network/documentation/Network/network-functions": {
      "abstract": [
        {
          "text": "Access Network framework functions used in C.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/network-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Functions",
      "type": "topic",
      "url": "/documentation/network/network-functions"
    },
    "doc://com.apple.network/documentation/Network/network-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.network/documentation/Network/network-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Macros",
      "type": "topic",
      "url": "/documentation/network/network-macros"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_state_waiting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_state_waiting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_browser_state_t",
          "text": "nw_browser_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_state_waiting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_state_waiting"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_state_waiting",
      "type": "topic",
      "url": "/documentation/network/nw_browser_state_waiting"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_cdma": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_cdma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_cdma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_cdma"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_cdma",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_cdma"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_mmw": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_endc_mmw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_mmw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_endc_mmw"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_endc_mmw",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_endc_mmw"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_sub6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_endc_sub6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_sub6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_endc_sub6"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_endc_sub6",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_endc_sub6"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_evdo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_evdo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_evdo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_evdo"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_evdo",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_evdo"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_gsm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_gsm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_gsm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_gsm"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_gsm",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_gsm"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_lte": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_lte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_lte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_lte"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_lte",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_lte"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_mmw": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_nr_sa_mmw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_mmw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_nr_sa_mmw"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_nr_sa_mmw",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_nr_sa_mmw"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_sub6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_nr_sa_sub6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_sub6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_nr_sa_sub6"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_nr_sa_sub6",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_nr_sa_sub6"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_wcdma": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_wcdma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_wcdma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_wcdma"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_wcdma",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_wcdma"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_unknown"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_unknown",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_unknown"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_a": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_a"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_wifi_a",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_wifi_a"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_ac": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_ac"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_ac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_ac"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_wifi_ac",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_wifi_ac"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_ax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_ax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_ax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_ax"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_wifi_ax",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_wifi_ax"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_b": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_b"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_wifi_b",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_wifi_b"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_g": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_g"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_g"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_wifi_g",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_wifi_g"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_n": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_n"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_wifi_n"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_wifi_n",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_wifi_n"
    },
    "doc://com.apple.network/documentation/Network/nw_multipath_version_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_multipath_version_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_multipath_version_t",
          "text": "nw_multipath_version_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_multipath_version_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_multipath_version_0"
        }
      ],
      "role": "symbol",
      "title": "nw_multipath_version_0",
      "type": "topic",
      "url": "/documentation/network/nw_multipath_version_0"
    },
    "doc://com.apple.network/documentation/Network/nw_multipath_version_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_multipath_version_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_multipath_version_t",
          "text": "nw_multipath_version_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_multipath_version_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_multipath_version_1"
        }
      ],
      "role": "symbol",
      "title": "nw_multipath_version_1",
      "type": "topic",
      "url": "/documentation/network/nw_multipath_version_1"
    },
    "doc://com.apple.network/documentation/Network/nw_multipath_version_unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_multipath_version_unspecified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_multipath_version_t",
          "text": "nw_multipath_version_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_multipath_version_unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_multipath_version_unspecified"
        }
      ],
      "role": "symbol",
      "title": "nw_multipath_version_unspecified",
      "type": "topic",
      "url": "/documentation/network/nw_multipath_version_unspecified"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_persistent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_expired_dns_behavior_persistent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_parameters_expired_dns_behavior_t",
          "text": "nw_parameters_expired_dns_behavior_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_persistent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_expired_dns_behavior_persistent"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_expired_dns_behavior_persistent",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_expired_dns_behavior_persistent"
    },
    "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_cellular_denied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_cellular_denied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_path_unsatisfied_reason_t",
          "text": "nw_path_unsatisfied_reason_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_cellular_denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_cellular_denied"
        }
      ],
      "role": "symbol",
      "title": "nw_path_unsatisfied_reason_cellular_denied",
      "type": "topic",
      "url": "/documentation/network/nw_path_unsatisfied_reason_cellular_denied"
    },
    "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_local_network_denied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_local_network_denied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_path_unsatisfied_reason_t",
          "text": "nw_path_unsatisfied_reason_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_local_network_denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_local_network_denied"
        }
      ],
      "role": "symbol",
      "title": "nw_path_unsatisfied_reason_local_network_denied",
      "type": "topic",
      "url": "/documentation/network/nw_path_unsatisfied_reason_local_network_denied"
    },
    "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_not_available": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_not_available"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_path_unsatisfied_reason_t",
          "text": "nw_path_unsatisfied_reason_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_not_available",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_not_available"
        }
      ],
      "role": "symbol",
      "title": "nw_path_unsatisfied_reason_not_available",
      "type": "topic",
      "url": "/documentation/network/nw_path_unsatisfied_reason_not_available"
    },
    "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_vpn_inactive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_vpn_inactive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_path_unsatisfied_reason_t",
          "text": "nw_path_unsatisfied_reason_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_vpn_inactive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_vpn_inactive"
        }
      ],
      "role": "symbol",
      "title": "nw_path_unsatisfied_reason_vpn_inactive",
      "type": "topic",
      "url": "/documentation/network/nw_path_unsatisfied_reason_vpn_inactive"
    },
    "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_wifi_denied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_wifi_denied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_path_unsatisfied_reason_t",
          "text": "nw_path_unsatisfied_reason_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_wifi_denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_wifi_denied"
        }
      ],
      "role": "symbol",
      "title": "nw_path_unsatisfied_reason_wifi_denied",
      "type": "topic",
      "url": "/documentation/network/nw_path_unsatisfied_reason_wifi_denied"
    },
    "doc://com.apple.network/documentation/Network/nw_quic_stream_type_bidirectional": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_quic_stream_type_bidirectional"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_quic_stream_type_t",
          "text": "nw_quic_stream_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_quic_stream_type_bidirectional",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_quic_stream_type_bidirectional"
        }
      ],
      "role": "symbol",
      "title": "nw_quic_stream_type_bidirectional",
      "type": "topic",
      "url": "/documentation/network/nw_quic_stream_type_bidirectional"
    },
    "doc://com.apple.network/documentation/Network/nw_quic_stream_type_datagram": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_quic_stream_type_datagram"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_quic_stream_type_t",
          "text": "nw_quic_stream_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_quic_stream_type_datagram",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_quic_stream_type_datagram"
        }
      ],
      "role": "symbol",
      "title": "nw_quic_stream_type_datagram",
      "type": "topic",
      "url": "/documentation/network/nw_quic_stream_type_datagram"
    },
    "doc://com.apple.network/documentation/Network/nw_quic_stream_type_unidirectional": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_quic_stream_type_unidirectional"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_quic_stream_type_t",
          "text": "nw_quic_stream_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_quic_stream_type_unidirectional",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_quic_stream_type_unidirectional"
        }
      ],
      "role": "symbol",
      "title": "nw_quic_stream_type_unidirectional",
      "type": "topic",
      "url": "/documentation/network/nw_quic_stream_type_unidirectional"
    },
    "doc://com.apple.network/documentation/Network/nw_quic_stream_type_unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_quic_stream_type_unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_quic_stream_type_t",
          "text": "nw_quic_stream_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_quic_stream_type_unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_quic_stream_type_unknown"
        }
      ],
      "role": "symbol",
      "title": "nw_quic_stream_type_unknown",
      "type": "topic",
      "url": "/documentation/network/nw_quic_stream_type_unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/network-functions",
        "doc://com.apple.network/documentation/Network/network-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/NW_FRAMER_CREATE_FLAGS_DEFAULT",
        "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER",
        "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT",
        "doc://com.apple.network/documentation/Network/NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE",
        "doc://com.apple.network/documentation/Network/nw_browser_state_waiting",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_cdma",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_mmw",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_sub6",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_evdo",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_gsm",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_lte",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_mmw",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_sub6",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_wcdma",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_unknown",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_a",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_ac",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_ax",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_b",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_g",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_wifi_n",
        "doc://com.apple.network/documentation/Network/nw_multipath_version_0",
        "doc://com.apple.network/documentation/Network/nw_multipath_version_1",
        "doc://com.apple.network/documentation/Network/nw_multipath_version_unspecified",
        "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_persistent",
        "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_cellular_denied",
        "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_local_network_denied",
        "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_not_available",
        "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_vpn_inactive",
        "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_wifi_denied",
        "doc://com.apple.network/documentation/Network/nw_quic_stream_type_bidirectional",
        "doc://com.apple.network/documentation/Network/nw_quic_stream_type_datagram",
        "doc://com.apple.network/documentation/Network/nw_quic_stream_type_unidirectional",
        "doc://com.apple.network/documentation/Network/nw_quic_stream_type_unknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/NW_FRAMER_CREATE_FLAGS_DEFAULT",
                "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER",
                "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT",
                "doc://com.apple.network/documentation/Network/NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/network-enumerations",
                "doc://com.apple.network/documentation/Network/network-functions",
                "doc://com.apple.network/documentation/Network/network-data-types",
                "doc://com.apple.network/documentation/Network/network-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_ac/title",
          "value": "nw_interface_radio_type_wifi_ac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_ac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_wifi_ac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_evdo/title",
          "value": "nw_interface_radio_type_cell_evdo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_evdo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_evdo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_vpn_inactive/title",
          "value": "nw_path_unsatisfied_reason_vpn_inactive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_vpn_inactive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_vpn_inactive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_datagram/title",
          "value": "nw_quic_stream_type_datagram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_datagram/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_quic_stream_type_datagram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_nr_sa_sub6/title",
          "value": "nw_interface_radio_type_cell_nr_sa_sub6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_nr_sa_sub6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_nr_sa_sub6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_endc_mmw/title",
          "value": "nw_interface_radio_type_cell_endc_mmw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_endc_mmw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_endc_mmw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_LISTENER_INFINITE_CONNECTION_LIMIT/title",
          "value": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_LISTENER_INFINITE_CONNECTION_LIMIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_a/title",
          "value": "nw_interface_radio_type_wifi_a"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_a/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_wifi_a"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE/title",
          "value": "NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_local_network_denied/title",
          "value": "nw_path_unsatisfied_reason_local_network_denied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_local_network_denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_local_network_denied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_waiting/title",
          "value": "nw_browser_state_waiting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_waiting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_waiting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_version_unspecified/title",
          "value": "nw_multipath_version_unspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_version_unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_version_unspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_g/title",
          "value": "nw_interface_radio_type_wifi_g"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_wifi_g"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_unidirectional/title",
          "value": "nw_quic_stream_type_unidirectional"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_unidirectional/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_quic_stream_type_unidirectional"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_unknown/title",
          "value": "nw_interface_radio_type_unknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_unknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_persistent/title",
          "value": "nw_parameters_expired_dns_behavior_persistent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_persistent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_expired_dns_behavior_persistent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_cdma/title",
          "value": "nw_interface_radio_type_cell_cdma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_cdma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_cdma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_cellular_denied/title",
          "value": "nw_path_unsatisfied_reason_cellular_denied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_cellular_denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_cellular_denied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_gsm/title",
          "value": "nw_interface_radio_type_cell_gsm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_gsm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_gsm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_lte/title",
          "value": "nw_interface_radio_type_cell_lte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_lte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_lte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_bidirectional/title",
          "value": "nw_quic_stream_type_bidirectional"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_bidirectional/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_quic_stream_type_bidirectional"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_FRAMER_WAKEUP_TIME_FOREVER/title",
          "value": "NW_FRAMER_WAKEUP_TIME_FOREVER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_FRAMER_WAKEUP_TIME_FOREVER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NW_FRAMER_WAKEUP_TIME_FOREVER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_unknown/title",
          "value": "nw_quic_stream_type_unknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_quic_stream_type_unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_quic_stream_type_unknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_nr_sa_mmw/title",
          "value": "nw_interface_radio_type_cell_nr_sa_mmw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_nr_sa_mmw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_nr_sa_mmw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_FRAMER_CREATE_FLAGS_DEFAULT/title",
          "value": "NW_FRAMER_CREATE_FLAGS_DEFAULT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_FRAMER_CREATE_FLAGS_DEFAULT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NW_FRAMER_CREATE_FLAGS_DEFAULT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_version_1/title",
          "value": "nw_multipath_version_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_version_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_version_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_wcdma/title",
          "value": "nw_interface_radio_type_cell_wcdma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_wcdma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_wcdma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_version_0/title",
          "value": "nw_multipath_version_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_version_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_version_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_b/title",
          "value": "nw_interface_radio_type_wifi_b"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_b/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_wifi_b"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_n/title",
          "value": "nw_interface_radio_type_wifi_n"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_wifi_n"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_endc_sub6/title",
          "value": "nw_interface_radio_type_cell_endc_sub6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_endc_sub6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_endc_sub6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_ax/title",
          "value": "nw_interface_radio_type_wifi_ax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_wifi_ax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_wifi_ax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_wifi_denied/title",
          "value": "nw_path_unsatisfied_reason_wifi_denied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_wifi_denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_wifi_denied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_not_available/title",
          "value": "nw_path_unsatisfied_reason_not_available"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_not_available/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_not_available"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/network-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/network-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
