{
  "abstract": [
    {
      "text": "A service description used to discover Bonjour services.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_browse_descriptor_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_browse_descriptor_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_browse_descriptor_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_browse_descriptor_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_browse_descriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_browse_descriptor",
              "text": "OS_nw_browse_descriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_browse_descriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_browse_descriptor"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_browse_descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_browse_descriptor"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_browse_descriptor",
      "type": "topic",
      "url": "/documentation/network/os_nw_browse_descriptor"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t": {
      "abstract": [
        {
          "text": "A description used to advertise the Bonjour service that a listener provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a service descriptor used to discover a Bonjour service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_create_bonjour_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_create_bonjour_service"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_create_bonjour_service(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_create_bonjour_service(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)": {
      "abstract": [
        {
          "text": "Accesses the Bonjour service domain set on a browse descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_domain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_domain"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_bonjour_service_domain(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_bonjour_service_domain(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)": {
      "abstract": [
        {
          "text": "Accesses the Bonjour service type set on a browse descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_type"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_bonjour_service_type(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_bonjour_service_type(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)": {
      "abstract": [
        {
          "text": "Checks if the browse descriptor requires including associated TXT records with all results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_include_txt_record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_include_txt_record"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_include_txt_record(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_include_txt_record(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)": {
      "abstract": [
        {
          "text": "Requires including associated TXT records with all results generated for this service descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_set_include_txt_record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_set_include_txt_record"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_set_include_txt_record(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_set_include_txt_record(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t": {
      "abstract": [
        {
          "text": "A service description used to discover Bonjour services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_t": {
      "abstract": [
        {
          "text": "Flags describing ways in which discovered services can change between specific results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t": {
      "abstract": [
        {
          "text": "A handler that enumerates the interfaces associated with a discovered service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_enumerate_interface_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_enumerate_interface_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_enumerate_interface_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_enumerate_interface_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_t": {
      "abstract": [
        {
          "text": "A discovered service and metadata about the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers updates about discovered services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_browse_results_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_browse_results_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_browse_results_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_browse_results_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers browser state updates with associated errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_t": {
      "abstract": [
        {
          "text": "An object you use to browse for available network services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives Boolean state updates from a connection, such as viability and better path state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_boolean_event_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_boolean_event_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_boolean_event_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_boolean_event_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_new_connection_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_new_connection_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_new_connection_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_new_connection_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives inbound messages from members of the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_receive_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_receive_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_receive_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_receive_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t": {
      "abstract": [
        {
          "text": "A completion to notify you when data has been processed and sent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_completion_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_completion_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_send_completion_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_send_completion_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives connection group state updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_t": {
      "abstract": [
        {
          "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers network path updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_path_event_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_path_event_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_path_event_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_path_event_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_receive_completion_t": {
      "abstract": [
        {
          "text": "A completion handler that indicates when content has been received by the connection, or that an error was encountered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_receive_completion_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_receive_completion_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_receive_completion_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_receive_completion_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_receive_completion_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_change_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_t",
        "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_browser_t",
        "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_t",
        "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_receive_completion_t"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Browse-Descriptors",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)"
      ],
      "title": "Creating Browse Descriptors"
    },
    {
      "anchor": "Inspecting-Browse-Descriptors",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)"
      ],
      "title": "Inspecting Browse Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_browse_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Browse-Descriptors",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)"
              ],
              "title": "Creating Browse Descriptors"
            },
            {
              "anchor": "Inspecting-Browse-Descriptors",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)",
                "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)",
                "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)"
              ],
              "title": "Inspecting Browse Descriptors"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_browse_descriptor",
                    "text": "NSObject<OS_nw_browse_descriptor>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_browse_descriptor_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/title",
          "value": "nw_browse_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/title",
          "value": "nw_connection_boolean_event_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_boolean_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_boolean_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/title",
          "value": "nw_browse_descriptor_create_bonjour_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_create_bonjour_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/title",
          "value": "nw_browse_descriptor_set_include_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_set_include_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/title",
          "value": "nw_browser_browse_results_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_browse_results_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_browse_results_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title",
          "value": "nw_browser_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_completion_t/title",
          "value": "nw_connection_receive_completion_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_completion_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_receive_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_completion_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_receive_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_descriptor/title",
          "value": "OS_nw_browse_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_descriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browse_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_descriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browse_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/title",
          "value": "nw_connection_group_receive_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/title",
          "value": "nw_browse_result_change_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/title",
          "value": "nw_connection_group_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/title",
          "value": "nw_connection_group_new_connection_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_new_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_new_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/title",
          "value": "nw_connection_group_send_completion_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/title",
          "value": "nw_browse_result_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/title",
          "value": "nw_browse_descriptor_get_include_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_include_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/title",
          "value": "nw_browser_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/title",
          "value": "nw_browse_result_enumerate_interface_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_enumerate_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_enumerate_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/title",
          "value": "nw_browse_descriptor_get_bonjour_service_domain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_bonjour_service_domain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/title",
          "value": "nw_browse_descriptor_get_bonjour_service_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_bonjour_service_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/title",
          "value": "nw_advertise_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/title",
          "value": "nw_connection_path_event_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_path_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_path_event_handler_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_browse_descriptor_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_browse_descriptor_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
