{
  "abstract": [
    {
      "text": "The service was no longer discovered over a certain interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_browse_result_change_interface_removed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@nw_browse_result_change_invalid@nw_browse_result_change_interface_removed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_browse_result_change_interface_removed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_browse_result_change_interface_removed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "nw_browse_result_change_interface_removed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_interface_removed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_identical": {
      "abstract": [
        {
          "text": "The compared services are identical.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_identical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_identical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_identical"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_identical",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_identical"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_interface_added": {
      "abstract": [
        {
          "text": "The service was discovered over a new interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_interface_added"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_interface_added",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_interface_added"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_interface_added",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_interface_added"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_interface_removed": {
      "abstract": [
        {
          "text": "The service was no longer discovered over a certain interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_interface_removed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_interface_removed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_interface_removed"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_interface_removed",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_interface_removed"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_invalid": {
      "abstract": [
        {
          "text": "The comparison was invallid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_invalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_invalid"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_invalid",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_invalid"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_result_added": {
      "abstract": [
        {
          "text": "A new service was discovered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_result_added"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_result_added",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_result_added"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_result_added",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_result_added"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_result_removed": {
      "abstract": [
        {
          "text": "A previously discovered service was removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_result_removed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_result_removed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_result_removed"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_result_removed",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_result_removed"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_txt_record_changed": {
      "abstract": [
        {
          "text": "The service’s associated TXT record changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_txt_record_changed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_txt_record_changed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_txt_record_changed"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_txt_record_changed",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_txt_record_changed"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Browse-Result-Change-Flags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_browse_result_change_invalid",
        "doc://com.apple.network/documentation/Network/nw_browse_result_change_identical",
        "doc://com.apple.network/documentation/Network/nw_browse_result_change_result_added",
        "doc://com.apple.network/documentation/Network/nw_browse_result_change_result_removed",
        "doc://com.apple.network/documentation/Network/nw_browse_result_change_txt_record_changed",
        "doc://com.apple.network/documentation/Network/nw_browse_result_change_interface_added"
      ],
      "title": "Browse Result Change Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_browse_result_change_interface_removed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_interface_removed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Browse-Result-Change-Flags",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_browse_result_change_invalid",
                "doc://com.apple.network/documentation/Network/nw_browse_result_change_identical",
                "doc://com.apple.network/documentation/Network/nw_browse_result_change_result_added",
                "doc://com.apple.network/documentation/Network/nw_browse_result_change_result_removed",
                "doc://com.apple.network/documentation/Network/nw_browse_result_change_txt_record_changed",
                "doc://com.apple.network/documentation/Network/nw_browse_result_change_interface_added"
              ],
              "title": "Browse Result Change Flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "nw_browse_result_change_interface_removed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_interface_added/title",
          "value": "nw_browse_result_change_interface_added"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_interface_added/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_interface_added"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_interface_removed/title",
          "value": "nw_browse_result_change_interface_removed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_interface_removed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_interface_removed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_txt_record_changed/title",
          "value": "nw_browse_result_change_txt_record_changed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_txt_record_changed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_txt_record_changed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_result_removed/title",
          "value": "nw_browse_result_change_result_removed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_result_removed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_result_removed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_result_added/title",
          "value": "nw_browse_result_change_result_added"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_result_added/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_result_added"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_identical/title",
          "value": "nw_browse_result_change_identical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_identical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_identical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_invalid/title",
          "value": "nw_browse_result_change_invalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_invalid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_browse_result_change_interface_removed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_browse_result_change_interface_removed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
