{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.network/documentation/Network"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.network/documentation/Network/nw_browse_result_t"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_result_t"}],"modules":[{"name":"Network"}],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_result_t"}],"title":"nw_browse_result_t","platforms":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"12.0","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"12.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.0","unavailable":false},{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"10.14","unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"introducedAt":"12.0","unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false},{"beta":false,"name":"watchOS","deprecated":false,"introducedAt":"6.0","unavailable":false}],"externalID":"c:@T@nw_browse_result_t","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias"},"topicSections":[{"identifiers":["doc://com.apple.network/documentation/Network/nw_browse_result_copy_endpoint(_:)","doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interfaces(_:_:)","doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t","doc://com.apple.network/documentation/Network/nw_browse_result_get_interfaces_count(_:)"],"anchor":"Evaluating-Browser-Results","title":"Evaluating Browser Results"},{"identifiers":["doc://com.apple.network/documentation/Network/nw_browse_result_copy_txt_record_object(_:)","doc://com.apple.network/documentation/Network/nw_txt_record_t"],"anchor":"Handling-TXT-Records","title":"Handling TXT Records"},{"identifiers":["doc://com.apple.network/documentation/Network/nw_browse_result_get_changes(_:_:)","doc://com.apple.network/documentation/Network/nw_browse_result_change_t"],"anchor":"Tracking-Result-Changes","title":"Tracking Result Changes"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t","doc://com.apple.network/documentation/Network/nw_browse_descriptor_t","doc://com.apple.network/documentation/Network/nw_browse_result_change_t","doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t","doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t","doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t","doc://com.apple.network/documentation/Network/nw_browser_t","doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t","doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t","doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t","doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t","doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t","doc://com.apple.network/documentation/Network/nw_connection_group_t","doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t","doc://com.apple.network/documentation/Network/nw_connection_receive_completion_t"],"anchor":"Data-Types","generated":true,"title":"Data Types"}],"kind":"symbol","sections":[],"variants":[{"paths":["/documentation/network/nw_browse_result_t"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/network/nw_browse_result_t"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_t","kind":"identifier"},{"text":" = any ","kind":"text"},{"text":"OS_nw_browse_result","identifier":"doc://com.apple.network/documentation/Network/OS_nw_browse_result","preciseIdentifier":"c:objc(pl)OS_nw_browse_result","kind":"typeIdentifier"}]}]}],"abstract":[{"text":"A discovered service and metadata about the service.","type":"text"}],"references":{"doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t":{"role":"symbol","type":"topic","title":"nw_connection_group_new_connection_handler_t","abstract":[],"identifier":"doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_group_new_connection_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_group_new_connection_handler_t","navigatorTitle":[{"text":"nw_connection_group_new_connection_handler_t","kind":"identifier"}]},"doc://com.apple.network/documentation/Network/nw_browse_result_get_changes(_:_:)":{"kind":"symbol","title":"nw_browse_result_get_changes(_:_:)","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_get_changes(_:_:)","navigatorTitle":[{"text":"nw_browse_result_get_changes","kind":"identifier"}],"url":"/documentation/network/nw_browse_result_get_changes(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_get_changes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_browse_result_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_result_t"},{"text":"?, ","kind":"text"},{"text":"nw_browse_result_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_result_t"},{"text":"?) -> ","kind":"text"},{"text":"nw_browse_result_change_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_result_change_t"}],"type":"topic","abstract":[{"type":"text","text":"Compares two discovered services and calculates changes between them."}]},"doc://com.apple.network/documentation/Network/nw_browse_result_copy_txt_record_object(_:)":{"type":"topic","identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_copy_txt_record_object(_:)","url":"/documentation/network/nw_browse_result_copy_txt_record_object(_:)","abstract":[{"type":"text","text":"Accesses the TXT record associated with a discovered service."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_result_copy_txt_record_object"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"nw_browse_result_t","preciseIdentifier":"c:@T@nw_browse_result_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"nw_txt_record_t","preciseIdentifier":"c:@T@nw_txt_record_t"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_browse_result_copy_txt_record_object"}],"title":"nw_browse_result_copy_txt_record_object(_:)","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_connection_receive_completion_t":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"nw_connection_receive_completion_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_receive_completion_t","abstract":[{"type":"text","text":"A completion handler that indicates when content has been received by the connection, or that an error was encountered."}],"type":"topic","title":"nw_connection_receive_completion_t","kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_connection_receive_completion_t","navigatorTitle":[{"text":"nw_connection_receive_completion_t","kind":"identifier"}]},"doc://com.apple.network/documentation/Network/nw_browse_result_copy_endpoint(_:)":{"abstract":[{"type":"text","text":"The discovered service endpoint."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_result_copy_endpoint"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"nw_browse_result_t","preciseIdentifier":"c:@T@nw_browse_result_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"nw_endpoint_t","preciseIdentifier":"c:@T@nw_endpoint_t"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_browse_result_copy_endpoint"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_copy_endpoint(_:)","type":"topic","title":"nw_browse_result_copy_endpoint(_:)","url":"/documentation/network/nw_browse_result_copy_endpoint(_:)","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_browse_result_t":{"type":"topic","role":"symbol","abstract":[{"text":"A discovered service and metadata about the service.","type":"text"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_t","kind":"identifier"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_t","title":"nw_browse_result_t","navigatorTitle":[{"text":"nw_browse_result_t","kind":"identifier"}],"url":"/documentation/network/nw_browse_result_t"},"doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t":{"role":"symbol","type":"topic","title":"nw_browse_result_enumerate_interface_t","abstract":[{"text":"A handler that enumerates the interfaces associated with a discovered service.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_enumerate_interface_t","kind":"identifier"}],"url":"/documentation/network/nw_browse_result_enumerate_interface_t","navigatorTitle":[{"text":"nw_browse_result_enumerate_interface_t","kind":"identifier"}]},"doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_group_send_completion_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A completion to notify you when data has been processed and sent."}],"navigatorTitle":[{"text":"nw_connection_group_send_completion_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_group_send_completion_t","kind":"symbol","title":"nw_connection_group_send_completion_t"},"doc://com.apple.network/documentation/Network/OS_nw_browse_result":{"role":"symbol","title":"OS_nw_browse_result","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OS_nw_browse_result","kind":"identifier"}],"url":"/documentation/network/os_nw_browse_result","identifier":"doc://com.apple.network/documentation/Network/OS_nw_browse_result","navigatorTitle":[{"text":"OS_nw_browse_result","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A description used to advertise the Bonjour service that a listener provides."}],"navigatorTitle":[{"text":"nw_advertise_descriptor_t","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_t","kind":"symbol","title":"nw_advertise_descriptor_t"},"doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_group_receive_handler_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A handler that receives inbound messages from members of the group."}],"navigatorTitle":[{"text":"nw_connection_group_receive_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_group_receive_handler_t","kind":"symbol","title":"nw_connection_group_receive_handler_t"},"doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_group_state_changed_handler_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A handler that receives connection group state updates."}],"navigatorTitle":[{"text":"nw_connection_group_state_changed_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_group_state_changed_handler_t","kind":"symbol","title":"nw_connection_group_state_changed_handler_t"},"doc://com.apple.network/documentation/Network/nw_browse_result_get_interfaces_count(_:)":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_get_interfaces_count(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_get_interfaces_count","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_browse_result_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_result_t"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"/documentation/network/nw_browse_result_get_interfaces_count(_:)","kind":"symbol","navigatorTitle":[{"text":"nw_browse_result_get_interfaces_count","kind":"identifier"}],"role":"symbol","type":"topic","title":"nw_browse_result_get_interfaces_count(_:)","abstract":[{"text":"Accesses the number of interfaces associated with a discovered service.","type":"text"}]},"doc://com.apple.network/documentation/Network/nw_browser_t":{"url":"/documentation/network/nw_browser_t","abstract":[{"type":"text","text":"An object you use to browse for available network services."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browser_t"}],"kind":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_browser_t","title":"nw_browser_t","navigatorTitle":[{"kind":"identifier","text":"nw_browser_t"}]},"doc://com.apple.network/documentation/Network/nw_txt_record_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_txt_record_t","title":"nw_txt_record_t","abstract":[{"type":"text","text":"A dictionary representing a TXT record in a DNS packet."}],"kind":"symbol","navigatorTitle":[{"text":"nw_txt_record_t","kind":"identifier"}],"url":"/documentation/network/nw_txt_record_t","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_txt_record_t","kind":"identifier"}]},"doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interfaces(_:_:)":{"abstract":[{"text":"Enumerates the list of interfaces on which the service was discovered.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_result_enumerate_interfaces"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"nw_browse_result_t","preciseIdentifier":"c:@T@nw_browse_result_t"},{"kind":"text","text":", ("},{"kind":"typeIdentifier","text":"nw_interface_t","preciseIdentifier":"c:@T@nw_interface_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"nw_browse_result_enumerate_interfaces(_:_:)","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interfaces(_:_:)","url":"/documentation/network/nw_browse_result_enumerate_interfaces(_:_:)","navigatorTitle":[{"kind":"identifier","text":"nw_browse_result_enumerate_interfaces"}]},"doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t":{"role":"symbol","type":"topic","title":"nw_browser_state_changed_handler_t","abstract":[{"text":"A handler that delivers browser state updates with associated errors.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browser_state_changed_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_browser_state_changed_handler_t","navigatorTitle":[{"text":"nw_browser_state_changed_handler_t","kind":"identifier"}]},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_descriptor_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A service description used to discover Bonjour services."}],"navigatorTitle":[{"text":"nw_browse_descriptor_t","kind":"identifier"}],"url":"/documentation/network/nw_browse_descriptor_t","kind":"symbol","title":"nw_browse_descriptor_t"},"doc://com.apple.network/documentation/Network/nw_connection_group_t":{"navigatorTitle":[{"kind":"identifier","text":"nw_connection_group_t"}],"identifier":"doc://com.apple.network/documentation/Network/nw_connection_group_t","abstract":[{"type":"text","text":"An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_connection_group_t"}],"title":"nw_connection_group_t","type":"topic","url":"/documentation/network/nw_connection_group_t","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t":{"role":"symbol","type":"topic","title":"nw_browser_browse_results_changed_handler_t","abstract":[{"text":"A handler that delivers updates about discovered services.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browser_browse_results_changed_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_browser_browse_results_changed_handler_t","navigatorTitle":[{"text":"nw_browser_browse_results_changed_handler_t","kind":"identifier"}]},"doc://com.apple.network/documentation/Network/nw_browse_result_change_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_change_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_change_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Flags describing ways in which discovered services can change between specific results."}],"navigatorTitle":[{"text":"nw_browse_result_change_t","kind":"identifier"}],"url":"/documentation/network/nw_browse_result_change_t","kind":"symbol","title":"nw_browse_result_change_t"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","role":"overview","abstract":[{"text":"","type":"text"}],"title":"Technologies"},"doc://com.apple.network/documentation/Network":{"title":"Network","abstract":[{"text":"Create network connections to send and receive data using transport and security protocols.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network","role":"collection","url":"/documentation/network","kind":"symbol","type":"topic"},"doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_boolean_event_handler_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A handler that receives Boolean state updates from a connection, such as viability and better path state."}],"navigatorTitle":[{"text":"nw_connection_boolean_event_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_boolean_event_handler_t","kind":"symbol","title":"nw_connection_boolean_event_handler_t"},"doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_path_event_handler_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A handler that delivers network path updates."}],"navigatorTitle":[{"text":"nw_connection_path_event_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_path_event_handler_t","kind":"symbol","title":"nw_connection_path_event_handler_t"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"12.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"12.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.14"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"12.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"6.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Type Alias"},{"value":"nw_browse_result_t","path":"/metadata/title","op":"replace"},{"value":"typealias","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"nw_browse_result_t","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"nw_browse_result_t","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.network/documentation/Network"]]},"path":"/hierarchy","op":"replace"},{"value":[{"anchor":"Evaluating-Browser-Results","title":"Evaluating Browser Results","identifiers":["doc://com.apple.network/documentation/Network/nw_browse_result_copy_endpoint(_:)","doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interfaces(_:_:)","doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t","doc://com.apple.network/documentation/Network/nw_browse_result_get_interfaces_count(_:)"]},{"anchor":"Handling-TXT-Records","title":"Handling TXT Records","identifiers":["doc://com.apple.network/documentation/Network/nw_browse_result_copy_txt_record_object(_:)","doc://com.apple.network/documentation/Network/nw_txt_record_t"]},{"anchor":"Tracking-Result-Changes","title":"Tracking Result Changes","identifiers":["doc://com.apple.network/documentation/Network/nw_browse_result_get_changes(_:_:)","doc://com.apple.network/documentation/Network/nw_browse_result_change_t"]}],"path":"/topicSections","op":"replace"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSObject<OS_nw_browse_result>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_nw_browse_result"},{"kind":"text","text":" * "},{"kind":"identifier","text":"nw_browse_result_t"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"nw_connection_group_new_connection_handler_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/title","op":"replace"},{"value":[{"text":"nw_connection_group_new_connection_handler_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"nw_connection_group_new_connection_handler_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/navigatorTitle","op":"replace"},{"value":"nw_browse_result_get_changes","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_get_changes(_:_:)/title","op":"replace"},{"value":[{"text":"nw_browse_result_get_changes","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_get_changes(_:_:)/fragments","op":"replace"},{"value":"nw_browse_result_copy_txt_record_object","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_copy_txt_record_object(_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browse_result_copy_txt_record_object"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_copy_txt_record_object(_:)/fragments","op":"replace"},{"value":"nw_connection_receive_completion_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_completion_t/title","op":"replace"},{"value":[{"text":"nw_connection_receive_completion_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_completion_t/fragments","op":"replace"},{"value":[{"text":"nw_connection_receive_completion_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_completion_t/navigatorTitle","op":"replace"},{"value":"nw_browse_result_copy_endpoint","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_copy_endpoint(_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browse_result_copy_endpoint"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_copy_endpoint(_:)/fragments","op":"replace"},{"value":"nw_browse_result_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/title","op":"replace"},{"value":[{"text":"nw_browse_result_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/fragments","op":"replace"},{"value":[{"text":"nw_browse_result_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/navigatorTitle","op":"replace"},{"value":"nw_browse_result_enumerate_interface_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browse_result_enumerate_interface_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browse_result_enumerate_interface_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/navigatorTitle","op":"replace"},{"value":"nw_connection_group_send_completion_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/title","op":"replace"},{"value":[{"text":"nw_connection_group_send_completion_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/fragments","op":"replace"},{"value":[{"text":"nw_connection_group_send_completion_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/navigatorTitle","op":"replace"},{"value":"OS_nw_browse_result","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_result/title","op":"replace"},{"value":[{"kind":"identifier","text":"OS_nw_browse_result"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_result/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OS_nw_browse_result"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_result/navigatorTitle","op":"replace"},{"value":"nw_advertise_descriptor_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_advertise_descriptor_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/fragments","op":"replace"},{"value":[{"text":"nw_advertise_descriptor_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/navigatorTitle","op":"replace"},{"value":"nw_connection_group_receive_handler_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/title","op":"replace"},{"value":[{"text":"nw_connection_group_receive_handler_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"nw_connection_group_receive_handler_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/navigatorTitle","op":"replace"},{"value":"nw_connection_group_state_changed_handler_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/title","op":"replace"},{"value":[{"text":"nw_connection_group_state_changed_handler_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/fragments","op":"replace"},{"value":[{"text":"nw_connection_group_state_changed_handler_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/navigatorTitle","op":"replace"},{"value":"nw_browse_result_get_interfaces_count","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_get_interfaces_count(_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browse_result_get_interfaces_count"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_get_interfaces_count(_:)/fragments","op":"replace"},{"value":"nw_browser_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title","op":"replace"},{"value":[{"text":"nw_browser_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browser_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle","op":"replace"},{"value":"nw_txt_record_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_t/title","op":"replace"},{"value":[{"text":"nw_txt_record_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_t/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"nw_txt_record_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_t/navigatorTitle","op":"replace"},{"value":"nw_browse_result_enumerate_interfaces","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interfaces(_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browse_result_enumerate_interfaces"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interfaces(_:_:)/fragments","op":"replace"},{"value":"nw_browser_state_changed_handler_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/title","op":"replace"},{"value":[{"text":"nw_browser_state_changed_handler_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browser_state_changed_handler_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/navigatorTitle","op":"replace"},{"value":"nw_browse_descriptor_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browse_descriptor_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/fragments","op":"replace"},{"value":[{"text":"nw_browse_descriptor_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/navigatorTitle","op":"replace"},{"value":"nw_connection_group_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_connection_group_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"nw_connection_group_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle","op":"replace"},{"value":"nw_browser_browse_results_changed_handler_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browser_browse_results_changed_handler_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browser_browse_results_changed_handler_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/navigatorTitle","op":"replace"},{"value":"nw_browse_result_change_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/title","op":"replace"},{"value":[{"text":"nw_browse_result_change_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"nw_browse_result_change_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/navigatorTitle","op":"replace"},{"value":"nw_connection_boolean_event_handler_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_connection_boolean_event_handler_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/fragments","op":"replace"},{"value":[{"text":"nw_connection_boolean_event_handler_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/navigatorTitle","op":"replace"},{"value":"nw_connection_path_event_handler_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/title","op":"replace"},{"value":[{"kind":"identifier","text":"nw_connection_path_event_handler_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/fragments","op":"replace"},{"value":[{"text":"nw_connection_path_event_handler_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"diffAvailability":{"minor":{"change":"modified","platform":"Xcode","versions":["16.2","16.3 beta 2"]},"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}