{"abstract":[{"text":"The discovered service endpoint.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_copy_endpoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"nw_browse_result_t","preciseIdentifier":"c:@T@nw_browse_result_t","identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_t","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"nw_endpoint_t","preciseIdentifier":"c:@T@nw_endpoint_t","identifier":"doc://com.apple.network/documentation/Network/nw_endpoint_t","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}],"seeAlsoSections":[{"generated":true,"anchor":"Functions","title":"Functions","identifiers":["doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)"]}],"identifier":{"url":"doc://com.apple.network/documentation/Network/nw_browse_result_copy_endpoint(_:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_copy_endpoint","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@nw_browse_result_t","text":"nw_browse_result_t","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@nw_endpoint_t","text":"nw_endpoint_t","kind":"typeIdentifier"}],"role":"symbol","title":"nw_browse_result_copy_endpoint(_:)","navigatorTitle":[{"text":"nw_browse_result_copy_endpoint","kind":"identifier"}],"platforms":[{"deprecated":false,"name":"iOS","introducedAt":"13.0","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","introducedAt":"13.0","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"unavailable":false},{"deprecated":false,"name":"macOS","introducedAt":"10.15","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","introducedAt":"13.0","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false},{"deprecated":false,"name":"watchOS","introducedAt":"6.0","beta":false,"unavailable":false}],"symbolKind":"func","externalID":"c:@F@nw_browse_result_copy_endpoint","roleHeading":"Function","modules":[{"name":"Network"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/network/nw_browse_result_copy_endpoint(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/network/nw_browse_result_copy_endpoint(_:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.network/documentation/Network"]]},"references":{"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)","abstract":[{"type":"text","text":"Initializes a service descriptor used to discover a Bonjour service."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_create_bonjour_service"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_create_bonjour_service"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">, "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?) -> "},{"preciseIdentifier":"c:@T@nw_browse_descriptor_t","kind":"typeIdentifier","text":"nw_browse_descriptor_t"}],"url":"/documentation/network/nw_browse_descriptor_create_bonjour_service(_:_:)","title":"nw_browse_descriptor_create_bonjour_service(_:_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)":{"type":"topic","abstract":[{"text":"Initializes a Bonjour service to advertise.","type":"text"}],"navigatorTitle":[{"text":"nw_advertise_descriptor_create_bonjour_service","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)","title":"nw_advertise_descriptor_create_bonjour_service(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_create_bonjour_service","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_set_no_auto_rename"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","kind":"typeIdentifier","text":"nw_advertise_descriptor_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_set_no_auto_rename"}],"kind":"symbol","title":"nw_advertise_descriptor_set_no_auto_rename(_:_:)","url":"/documentation/network/nw_advertise_descriptor_set_no_auto_rename(_:_:)","role":"symbol","abstract":[{"type":"text","text":"Sets a Boolean to indicate whether the service prohibits automatic renaming in the event of a name conflict."}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_get_application_service_name"}],"abstract":[],"kind":"symbol","type":"topic","url":"/documentation/network/nw_advertise_descriptor_get_application_service_name(_:)","title":"nw_advertise_descriptor_get_application_service_name(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_get_application_service_name"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"nw_advertise_descriptor_t","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">?"}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_create_application_service"}],"url":"/documentation/network/nw_browse_descriptor_create_application_service(_:)","title":"nw_browse_descriptor_create_application_service(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_create_application_service"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t","text":"nw_browse_descriptor_t"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)":{"kind":"symbol","title":"nw_advertise_descriptor_set_txt_record_object(_:_:)","type":"topic","abstract":[{"text":"Sets the TXT record to advertise with the service.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_set_txt_record_object","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"text":", ","kind":"text"},{"text":"nw_txt_record_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_txt_record_t"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"nw_advertise_descriptor_set_txt_record_object","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_set_txt_record_object(_:_:)","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)":{"abstract":[{"type":"text","text":"Accesses the Bonjour service type set on a browse descriptor."}],"kind":"symbol","title":"nw_browse_descriptor_get_bonjour_service_type(_:)","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_type"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_browse_descriptor_t","kind":"typeIdentifier","text":"nw_browse_descriptor_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_type"}],"role":"symbol","url":"/documentation/network/nw_browse_descriptor_get_bonjour_service_type(_:)"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_get_include_txt_record"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_get_include_txt_record"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t","text":"nw_browse_descriptor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)","title":"nw_browse_descriptor_get_include_txt_record(_:)","abstract":[{"type":"text","text":"Checks if the browse descriptor requires including associated TXT records with all results."}],"role":"symbol","url":"/documentation/network/nw_browse_descriptor_get_include_txt_record(_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_create_application_service","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","text":"nw_advertise_descriptor_t","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"nw_advertise_descriptor_create_application_service","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)","title":"nw_advertise_descriptor_create_application_service(_:)","type":"topic","url":"/documentation/network/nw_advertise_descriptor_create_application_service(_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)":{"type":"topic","abstract":[{"text":"Accesses the TXT record to advertise with the service.","type":"text"}],"navigatorTitle":[{"text":"nw_advertise_descriptor_copy_txt_record_object","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_copy_txt_record_object(_:)","title":"nw_advertise_descriptor_copy_txt_record_object(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_copy_txt_record_object","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"text":") -> ","kind":"text"},{"text":"nw_txt_record_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_txt_record_t"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)"},"doc://com.apple.network/documentation/Network/nw_browse_result_t":{"type":"topic","role":"symbol","abstract":[{"text":"A discovered service and metadata about the service.","type":"text"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_t","kind":"identifier"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_t","title":"nw_browse_result_t","navigatorTitle":[{"text":"nw_browse_result_t","kind":"identifier"}],"url":"/documentation/network/nw_browse_result_t"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)":{"kind":"symbol","title":"nw_advertise_descriptor_set_txt_record(_:_:_:)","type":"topic","role":"symbol","url":"/documentation/network/nw_advertise_descriptor_set_txt_record(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_set_txt_record"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_set_txt_record"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","kind":"typeIdentifier","text":"nw_advertise_descriptor_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SV","kind":"typeIdentifier","text":"UnsafeRawPointer"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)","abstract":[{"type":"text","text":"Sets the TXT record as a raw buffer to advertise with the service."}]},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"nw_browse_descriptor_get_application_service_name","kind":"identifier"}],"url":"/documentation/network/nw_browse_descriptor_get_application_service_name(_:)","title":"nw_browse_descriptor_get_application_service_name(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_descriptor_get_application_service_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_browse_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t"},{"text":") -> ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)"},"doc://com.apple.network/documentation/Network":{"title":"Network","abstract":[{"text":"Create network connections to send and receive data using transport and security protocols.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network","role":"collection","url":"/documentation/network","kind":"symbol","type":"topic"},"doc://com.apple.network/documentation/Network/nw_endpoint_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_endpoint_t","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_endpoint_t","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"nw_endpoint_t"}],"type":"topic","url":"/documentation/network/nw_endpoint_t","title":"nw_endpoint_t","kind":"symbol","role":"symbol","abstract":[{"text":"A local or remote endpoint in a network connection.","type":"text"}]},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)":{"kind":"symbol","title":"nw_browse_descriptor_set_include_txt_record(_:_:)","type":"topic","abstract":[{"type":"text","text":"Requires including associated TXT records with all results generated for this service descriptor."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_set_include_txt_record"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_browse_descriptor_t","kind":"typeIdentifier","text":"nw_browse_descriptor_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_set_include_txt_record"}],"url":"/documentation/network/nw_browse_descriptor_set_include_txt_record(_:_:)","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","role":"overview","abstract":[{"text":"","type":"text"}],"title":"Technologies"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)","kind":"symbol","abstract":[{"type":"text","text":"Accesses the Bonjour service domain set on a browse descriptor."}],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_domain"}],"title":"nw_browse_descriptor_get_bonjour_service_domain(_:)","type":"topic","url":"/documentation/network/nw_browse_descriptor_get_bonjour_service_domain(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_domain"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t","text":"nw_browse_descriptor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">?"}]},"doc://com.apple.network/documentation/Network/nw_browse_result_copy_endpoint(_:)":{"abstract":[{"type":"text","text":"The discovered service endpoint."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_result_copy_endpoint"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"nw_browse_result_t","preciseIdentifier":"c:@T@nw_browse_result_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"nw_endpoint_t","preciseIdentifier":"c:@T@nw_endpoint_t"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_browse_result_copy_endpoint"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_copy_endpoint(_:)","type":"topic","title":"nw_browse_result_copy_endpoint(_:)","url":"/documentation/network/nw_browse_result_copy_endpoint(_:)","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)":{"title":"nw_advertise_descriptor_get_no_auto_rename(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_get_no_auto_rename"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","kind":"typeIdentifier","text":"nw_advertise_descriptor_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)","url":"/documentation/network/nw_advertise_descriptor_get_no_auto_rename(_:)","abstract":[{"type":"text","text":"Checks whether the service prohibits automatic renaming in the event of a name conflict."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_get_no_auto_rename"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"10.15","unavailable":false,"beta":false,"name":"macOS"},{"deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS"},{"deprecated":false,"introducedAt":"6.0","unavailable":false,"beta":false,"name":"watchOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Function"},{"path":"/metadata/title","op":"replace","value":"nw_browse_result_copy_endpoint"},{"path":"/metadata/symbolKind","op":"replace","value":"func"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"nw_browse_result_copy_endpoint","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.network/documentation/Network"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"typeIdentifier","text":"nw_endpoint_t","identifier":"doc://com.apple.network/documentation/Network/nw_endpoint_t","preciseIdentifier":"c:@T@nw_endpoint_t"},{"kind":"text","text":" "},{"text":"nw_browse_result_copy_endpoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_browse_result_t","preciseIdentifier":"c:@T@nw_browse_result_t","identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":");","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"nw_browse_descriptor_create_bonjour_service","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/title"},{"op":"replace","value":[{"text":"nw_browse_descriptor_create_bonjour_service","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_create_bonjour_service","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_bonjour_service(_:_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_advertise_descriptor_create_bonjour_service"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_bonjour_service(_:_:_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_set_no_auto_rename","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_no_auto_rename(_:_:)/title"},{"op":"replace","value":[{"text":"nw_advertise_descriptor_set_no_auto_rename","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_no_auto_rename(_:_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_get_application_service_name","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_application_service_name(_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_advertise_descriptor_get_application_service_name"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_application_service_name(_:)/fragments"},{"op":"replace","value":"nw_browse_descriptor_create_application_service","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_application_service(_:)/title"},{"op":"replace","value":[{"text":"nw_browse_descriptor_create_application_service","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_application_service(_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_set_txt_record_object","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record_object(_:_:)/title"},{"op":"replace","value":[{"text":"nw_advertise_descriptor_set_txt_record_object","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record_object(_:_:)/fragments"},{"op":"replace","value":"nw_browse_descriptor_get_bonjour_service_type","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/title"},{"op":"replace","value":[{"text":"nw_browse_descriptor_get_bonjour_service_type","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/fragments"},{"op":"replace","value":"nw_browse_descriptor_get_include_txt_record","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/title"},{"op":"replace","value":[{"text":"nw_browse_descriptor_get_include_txt_record","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_create_application_service","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_application_service(_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_advertise_descriptor_create_application_service"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_application_service(_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_copy_txt_record_object","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_copy_txt_record_object(_:)/title"},{"op":"replace","value":[{"text":"nw_advertise_descriptor_copy_txt_record_object","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_copy_txt_record_object(_:)/fragments"},{"op":"replace","value":"nw_browse_result_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_browse_result_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"nw_browse_result_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/navigatorTitle"},{"op":"replace","value":"nw_advertise_descriptor_set_txt_record","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record(_:_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_advertise_descriptor_set_txt_record"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record(_:_:_:)/fragments"},{"op":"replace","value":"nw_browse_descriptor_get_application_service_name","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_application_service_name(_:)/title"},{"op":"replace","value":[{"text":"nw_browse_descriptor_get_application_service_name","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_application_service_name(_:)/fragments"},{"op":"replace","value":"nw_endpoint_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_endpoint_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"nw_endpoint_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/navigatorTitle"},{"op":"replace","value":"nw_browse_descriptor_set_include_txt_record","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/title"},{"op":"replace","value":[{"text":"nw_browse_descriptor_set_include_txt_record","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/fragments"},{"op":"replace","value":"nw_browse_descriptor_get_bonjour_service_domain","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/title"},{"op":"replace","value":[{"text":"nw_browse_descriptor_get_bonjour_service_domain","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/fragments"},{"op":"replace","value":"nw_browse_result_copy_endpoint","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_copy_endpoint(_:)/title"},{"op":"replace","value":[{"text":"nw_browse_result_copy_endpoint","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_copy_endpoint(_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_get_no_auto_rename","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_no_auto_rename(_:)/title"},{"op":"replace","value":[{"text":"nw_advertise_descriptor_get_no_auto_rename","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_no_auto_rename(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}