{
  "abstract": [
    {
      "text": "An object you use to browse for available network services.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_browser_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_browser_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_browser_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_browser_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_browser_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_browser",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_browser",
              "text": "OS_nw_browser"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSBonjourServices": {
      "abstract": [
        {
          "text": "Bonjour service types browsed by the app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSBonjourServices",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBonjourServices",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSBonjourServices"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the local network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLocalNetworkUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_browser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_browser"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_browser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_browser"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_browser",
      "type": "topic",
      "url": "/documentation/network/os_nw_browser"
    },
    "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework": {
      "abstract": [
        {
          "text": "Build a simple ",
          "type": "text"
        },
        {
          "code": "netcat",
          "type": "codeVoice"
        },
        {
          "text": " tool that establishes network connections and transfers data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing netcat with Network Framework",
      "type": "topic",
      "url": "/documentation/network/implementing-netcat-with-network-framework"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t": {
      "abstract": [
        {
          "text": "A service description used to discover Bonjour services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_t": {
      "abstract": [
        {
          "text": "A discovered service and metadata about the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers updates about discovered services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_browse_results_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_browse_results_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_browse_results_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_browse_results_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_cancel(_:)": {
      "abstract": [
        {
          "text": "Stops browsing for services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_cancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browser_t",
          "text": "nw_browser_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_cancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_cancel"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_cancel(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browser_cancel(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_copy_browse_descriptor(_:)": {
      "abstract": [
        {
          "text": "Accesses the service descriptor with which the browser was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_copy_browse_descriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browser_t",
          "text": "nw_browser_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_copy_browse_descriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_copy_browse_descriptor"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_copy_browse_descriptor(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browser_copy_browse_descriptor(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_copy_parameters(_:)": {
      "abstract": [
        {
          "text": "Accesses the parameters with which the browser was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_copy_parameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browser_t",
          "text": "nw_browser_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_copy_parameters(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_copy_parameters"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_copy_parameters(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browser_copy_parameters(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_create(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a browser with a type of service to discover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browser_t",
          "text": "nw_browser_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_create(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_create"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_create(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browser_create(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_set_browse_results_changed_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets the handler to receive updates about discovered services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_set_browse_results_changed_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browser_t",
          "text": "nw_browser_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browser_browse_results_changed_handler_t",
          "text": "nw_browser_browse_results_changed_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_set_browse_results_changed_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_set_browse_results_changed_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_set_browse_results_changed_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browser_set_browse_results_changed_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_set_queue(_:_:)": {
      "abstract": [
        {
          "text": "Sets the queue on which all browser events will be delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_set_queue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browser_t",
          "text": "nw_browser_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_set_queue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_set_queue"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_set_queue(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browser_set_queue(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_set_state_changed_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to receive browser state updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_set_state_changed_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browser_t",
          "text": "nw_browser_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browser_state_changed_handler_t",
          "text": "nw_browser_state_changed_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_set_state_changed_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_set_state_changed_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_set_state_changed_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browser_set_state_changed_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_start(_:)": {
      "abstract": [
        {
          "text": "Starts browsing for services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browser_t",
          "text": "nw_browser_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_start(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_start"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_start(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browser_start(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers browser state updates with associated errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a browser is able to discover services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_t": {
      "abstract": [
        {
          "text": "An object you use to browse for available network services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_t": {
      "abstract": [
        {
          "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_t": {
      "abstract": [
        {
          "text": "A bidirectional data connection between a local endpoint and a remote endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t": {
      "abstract": [
        {
          "text": "An object you use to send and receive custom Ethernet frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_t": {
      "abstract": [
        {
          "text": "An object you use to listen for incoming network connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSBonjourServices",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Browsing-for-Services",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_browser_create(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t",
        "doc://com.apple.network/documentation/Network/nw_browser_set_queue(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_browser_start(_:)",
        "doc://com.apple.network/documentation/Network/nw_browser_set_browse_results_changed_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_t"
      ],
      "title": "Browsing for Services"
    },
    {
      "anchor": "Managing-Browsers",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_browser_set_state_changed_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_browser_state_t",
        "doc://com.apple.network/documentation/Network/nw_browser_cancel(_:)"
      ],
      "title": "Managing Browsers"
    },
    {
      "anchor": "Inspecting-Browsers",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_browser_copy_browse_descriptor(_:)",
        "doc://com.apple.network/documentation/Network/nw_browser_copy_parameters(_:)"
      ],
      "title": "Inspecting Browsers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_browser_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSBonjourServices",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Browsing-for-Services",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_browser_create(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t",
                "doc://com.apple.network/documentation/Network/nw_browser_set_queue(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_browser_start(_:)",
                "doc://com.apple.network/documentation/Network/nw_browser_set_browse_results_changed_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
                "doc://com.apple.network/documentation/Network/nw_browse_result_t"
              ],
              "title": "Browsing for Services"
            },
            {
              "anchor": "Managing-Browsers",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_browser_set_state_changed_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
                "doc://com.apple.network/documentation/Network/nw_browser_state_t",
                "doc://com.apple.network/documentation/Network/nw_browser_cancel(_:)"
              ],
              "title": "Managing Browsers"
            },
            {
              "anchor": "Inspecting-Browsers",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_browser_copy_browse_descriptor(_:)",
                "doc://com.apple.network/documentation/Network/nw_browser_copy_parameters(_:)"
              ],
              "title": "Inspecting Browsers"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Connections-and-Listeners",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework",
                "doc://com.apple.network/documentation/Network/nw_connection_t",
                "doc://com.apple.network/documentation/Network/nw_listener_t",
                "doc://com.apple.network/documentation/Network/nw_connection_group_t",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t"
              ],
              "title": "Connections and Listeners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_browser",
                    "text": "NSObject<OS_nw_browser>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_browser_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_copy_browse_descriptor(_:)/title",
          "value": "nw_browser_copy_browse_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_copy_browse_descriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_copy_browse_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/title",
          "value": "nw_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browser/title",
          "value": "OS_nw_browser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/title",
          "value": "nw_connection_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title",
          "value": "nw_browser_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_create(_:_:)/title",
          "value": "nw_browser_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_create(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_start(_:)/title",
          "value": "nw_browser_start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_start(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_set_queue(_:_:)/title",
          "value": "nw_browser_set_queue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_set_queue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_set_queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/title",
          "value": "nw_browse_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/title",
          "value": "nw_browser_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_set_browse_results_changed_handler(_:_:)/title",
          "value": "nw_browser_set_browse_results_changed_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_set_browse_results_changed_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_set_browse_results_changed_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_set_state_changed_handler(_:_:)/title",
          "value": "nw_browser_set_state_changed_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_set_state_changed_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_set_state_changed_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_t/title",
          "value": "nw_browser_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/title",
          "value": "nw_browser_browse_results_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_browse_results_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_browse_results_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/title",
          "value": "nw_ethernet_channel_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_copy_parameters(_:)/title",
          "value": "nw_browser_copy_parameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_copy_parameters(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_copy_parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_cancel(_:)/title",
          "value": "nw_browser_cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_cancel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/title",
          "value": "nw_browse_result_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_browser_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_browser_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
