{
  "abstract": [
    {
      "text": "A bidirectional data connection between a local endpoint and a remote endpoint.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_connection_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_connection_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_connection_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_connection_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_connection_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_connection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_connection",
              "text": "OS_nw_connection"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_connection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_connection"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_connection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_connection"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_connection",
      "type": "topic",
      "url": "/documentation/network/os_nw_connection"
    },
    "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework": {
      "abstract": [
        {
          "text": "Build a simple ",
          "type": "text"
        },
        {
          "code": "netcat",
          "type": "codeVoice"
        },
        {
          "text": " tool that establishes network connections and transfers data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing netcat with Network Framework",
      "type": "topic",
      "url": "/documentation/network/implementing-netcat-with-network-framework"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_t": {
      "abstract": [
        {
          "text": "An object you use to browse for available network services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_access_establishment_report(_:_:_:)": {
      "abstract": [
        {
          "text": "Requests a copy of the connection’s establishment report once the connection is in the ready state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_access_establishment_report"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_establishment_report_access_block_t",
          "text": "nw_establishment_report_access_block_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_access_establishment_report(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_access_establishment_report"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_access_establishment_report(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_access_establishment_report(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_batch(_:_:)": {
      "abstract": [
        {
          "text": "Defines a block in which calls to send and receive are processed as a batch to improve performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_batch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_batch(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_batch"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_batch(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_batch(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives Boolean state updates from a connection, such as viability and better path state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_boolean_event_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_boolean_event_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_boolean_event_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_boolean_event_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_cancel(_:)": {
      "abstract": [
        {
          "text": "Cancels the connection and gracefully disconnects any established network protocols.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_cancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_cancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_cancel"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_cancel(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_cancel(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_cancel_current_endpoint(_:)": {
      "abstract": [
        {
          "text": "Causes the current endpoint to be rejected, allowing the connection to try another resolved address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_cancel_current_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_cancel_current_endpoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_cancel_current_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_cancel_current_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_cancel_current_endpoint(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_copy_current_path(_:)": {
      "abstract": [
        {
          "text": "Accesses the network path the connection is using.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_copy_current_path"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_copy_current_path(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_copy_current_path"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_copy_current_path(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_copy_current_path(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_copy_description(_:)": {
      "abstract": [
        {
          "text": "Copies the description of the connection as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_copy_description"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_copy_description(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_copy_description"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_copy_description(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_copy_description(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_copy_endpoint(_:)": {
      "abstract": [
        {
          "text": "Accesses the endpoint with which the connection was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_copy_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_copy_endpoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_copy_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_copy_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_copy_endpoint(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_copy_parameters(_:)": {
      "abstract": [
        {
          "text": "Accesses the parameters with which the connection was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_copy_parameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_copy_parameters(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_copy_parameters"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_copy_parameters(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_copy_parameters(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_copy_protocol_metadata(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the connection-wide metadata for a specific protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_copy_protocol_metadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_copy_protocol_metadata(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_copy_protocol_metadata"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_copy_protocol_metadata(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_copy_protocol_metadata(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_create(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a new connection to a remote endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_create(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_create"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_create(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_create(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_create_new_data_transfer_report(_:)": {
      "abstract": [
        {
          "text": "Begins a new data transfer report, which can later be collected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_create_new_data_transfer_report"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_create_new_data_transfer_report(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_create_new_data_transfer_report"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_create_new_data_transfer_report(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_create_new_data_transfer_report(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_force_cancel(_:)": {
      "abstract": [
        {
          "text": "Cancels the connection and immediately disconnects any established network protocols.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_force_cancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_force_cancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_force_cancel"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_force_cancel(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_force_cancel(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_get_maximum_datagram_size(_:)": {
      "abstract": [
        {
          "text": "Accesses the maximum size of a datagram message that can be sent on a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_get_maximum_datagram_size"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_get_maximum_datagram_size(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_get_maximum_datagram_size"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_get_maximum_datagram_size(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_get_maximum_datagram_size(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_t": {
      "abstract": [
        {
          "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers network path updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_path_event_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_path_event_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_path_event_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_path_event_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_receive(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Schedules a single receive completion handler, with a range indicating how many bytes the handler can receive at one time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_receive"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_receive_completion_t",
          "text": "nw_connection_receive_completion_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_receive(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_receive"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_receive(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_receive(_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_receive_completion_t": {
      "abstract": [
        {
          "text": "A completion handler that indicates when content has been received by the connection, or that an error was encountered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_receive_completion_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_receive_completion_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_receive_completion_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_receive_completion_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_receive_completion_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_receive_message(_:_:)": {
      "abstract": [
        {
          "text": "Schedules a single receive completion handler for a complete message, as opposed to a range of bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_receive_message"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_receive_completion_t",
          "text": "nw_connection_receive_completion_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_receive_message(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_receive_message"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_receive_message(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_receive_message(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_restart(_:)": {
      "abstract": [
        {
          "text": "Restarts a connection that is in the waiting state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_restart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_restart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_restart"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_restart(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_restart(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_send(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sends data on a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_send"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "dispatch_data_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_content_context_t",
          "text": "nw_content_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_send_completion_t",
          "text": "nw_connection_send_completion_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_send(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_send"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_send(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_send(_:_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_send_completion_t": {
      "abstract": [
        {
          "text": "A completion handler that indicates when the connection has finished processing sent content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_send_completion_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_send_completion_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_send_completion_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_send_completion_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_send_completion_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_set_better_path_available_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler that receives updates when an alternative network path is preferred over the current path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_set_better_path_available_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_boolean_event_handler_t",
          "text": "nw_connection_boolean_event_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_set_better_path_available_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_set_better_path_available_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_set_better_path_available_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_set_better_path_available_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_set_path_changed_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler that receives network path updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_set_path_changed_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_path_event_handler_t",
          "text": "nw_connection_path_event_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_set_path_changed_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_set_path_changed_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_set_path_changed_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_set_path_changed_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_set_queue(_:_:)": {
      "abstract": [
        {
          "text": "Sets the queue on which all connection events are delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_set_queue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_set_queue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_set_queue"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_set_queue(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_set_queue(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_set_state_changed_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to receive connection state updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_set_state_changed_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_state_changed_handler_t",
          "text": "nw_connection_state_changed_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_set_state_changed_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_set_state_changed_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_set_state_changed_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_set_state_changed_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_set_viability_changed_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler that receives updates when data can be sent and received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_set_viability_changed_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_boolean_event_handler_t",
          "text": "nw_connection_boolean_event_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_set_viability_changed_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_set_viability_changed_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_set_viability_changed_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_set_viability_changed_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_start(_:)": {
      "abstract": [
        {
          "text": "Starts establishing a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_start(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_start"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_start(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_start(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers connection state updates with associated errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a connection can be used to send and receive data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_t": {
      "abstract": [
        {
          "text": "A bidirectional data connection between a local endpoint and a remote endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_t"
    },
    "doc://com.apple.network/documentation/Network/nw_content_context_t": {
      "abstract": [
        {
          "text": "A representation of a message to send or receive, containing protocol metadata and send properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_content_context_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_content_context_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_content_context_t"
        }
      ],
      "role": "symbol",
      "title": "nw_content_context_t",
      "type": "topic",
      "url": "/documentation/network/nw_content_context_t"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_t": {
      "abstract": [
        {
          "text": "A report that provides metrics about data being sent and received on a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_t"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_t",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_t"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_access_block_t": {
      "abstract": [
        {
          "text": "A block that delivers a connection’s establishment report when it’s in the ready state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_access_block_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_access_block_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_access_block_t"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_access_block_t",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_access_block_t"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_t": {
      "abstract": [
        {
          "text": "A report that provides metrics about how a connection was established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_t"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_t",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t": {
      "abstract": [
        {
          "text": "An object you use to send and receive custom Ethernet frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_t": {
      "abstract": [
        {
          "text": "An object you use to listen for incoming network connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-Connections",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_create(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_set_queue(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_start(_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_restart(_:)"
      ],
      "title": "Creating Connections"
    },
    {
      "anchor": "Handling-State-Updates",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_state_t",
        "doc://com.apple.network/documentation/Network/nw_connection_set_state_changed_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_state_changed_handler_t"
      ],
      "title": "Handling State Updates"
    },
    {
      "anchor": "Sending-and-Receiving-Data",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_send(_:_:_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_send_completion_t",
        "doc://com.apple.network/documentation/Network/nw_content_context_t",
        "doc://com.apple.network/documentation/Network/nw_connection_receive(_:_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_receive_completion_t",
        "doc://com.apple.network/documentation/Network/nw_connection_receive_message(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_batch(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_get_maximum_datagram_size(_:)"
      ],
      "title": "Sending and Receiving Data"
    },
    {
      "anchor": "Canceling-Connections",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_cancel(_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_force_cancel(_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_cancel_current_endpoint(_:)"
      ],
      "title": "Canceling Connections"
    },
    {
      "anchor": "Handling-Path-Updates",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_copy_current_path(_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_set_path_changed_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_set_viability_changed_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_set_better_path_available_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t"
      ],
      "title": "Handling Path Updates"
    },
    {
      "anchor": "Collecting-Connection-Metrics",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_establishment_report_t",
        "doc://com.apple.network/documentation/Network/nw_connection_access_establishment_report(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_establishment_report_access_block_t",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_t",
        "doc://com.apple.network/documentation/Network/nw_connection_create_new_data_transfer_report(_:)"
      ],
      "title": "Collecting Connection Metrics"
    },
    {
      "anchor": "Copying-Connection-State",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_copy_protocol_metadata(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_copy_endpoint(_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_copy_parameters(_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_copy_description(_:)"
      ],
      "title": "Copying Connection State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_connection_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Connections",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_create(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_set_queue(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_start(_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_restart(_:)"
              ],
              "title": "Creating Connections"
            },
            {
              "anchor": "Handling-State-Updates",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_state_t",
                "doc://com.apple.network/documentation/Network/nw_connection_set_state_changed_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_state_changed_handler_t"
              ],
              "title": "Handling State Updates"
            },
            {
              "anchor": "Sending-and-Receiving-Data",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_send(_:_:_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_send_completion_t",
                "doc://com.apple.network/documentation/Network/nw_content_context_t",
                "doc://com.apple.network/documentation/Network/nw_connection_receive(_:_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_receive_completion_t",
                "doc://com.apple.network/documentation/Network/nw_connection_receive_message(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_batch(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_get_maximum_datagram_size(_:)"
              ],
              "title": "Sending and Receiving Data"
            },
            {
              "anchor": "Canceling-Connections",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_cancel(_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_force_cancel(_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_cancel_current_endpoint(_:)"
              ],
              "title": "Canceling Connections"
            },
            {
              "anchor": "Handling-Path-Updates",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_copy_current_path(_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_set_path_changed_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t",
                "doc://com.apple.network/documentation/Network/nw_connection_set_viability_changed_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_set_better_path_available_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t"
              ],
              "title": "Handling Path Updates"
            },
            {
              "anchor": "Collecting-Connection-Metrics",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_establishment_report_t",
                "doc://com.apple.network/documentation/Network/nw_connection_access_establishment_report(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_establishment_report_access_block_t",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_t",
                "doc://com.apple.network/documentation/Network/nw_connection_create_new_data_transfer_report(_:)"
              ],
              "title": "Collecting Connection Metrics"
            },
            {
              "anchor": "Copying-Connection-State",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_copy_protocol_metadata(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_copy_endpoint(_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_copy_parameters(_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_copy_description(_:)"
              ],
              "title": "Copying Connection State"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Connections-and-Listeners",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework",
                "doc://com.apple.network/documentation/Network/nw_listener_t",
                "doc://com.apple.network/documentation/Network/nw_browser_t",
                "doc://com.apple.network/documentation/Network/nw_connection_group_t",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t"
              ],
              "title": "Connections and Listeners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_connection",
                    "text": "NSObject<OS_nw_connection>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_connection_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/title",
          "value": "nw_connection_path_event_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_path_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_path_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_copy_current_path(_:)/title",
          "value": "nw_connection_copy_current_path"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_copy_current_path(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_copy_current_path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title",
          "value": "nw_browser_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_restart(_:)/title",
          "value": "nw_connection_restart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_restart(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_restart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_set_viability_changed_handler(_:_:)/title",
          "value": "nw_connection_set_viability_changed_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_set_viability_changed_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_set_viability_changed_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_create(_:_:)/title",
          "value": "nw_connection_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_create(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_message(_:_:)/title",
          "value": "nw_connection_receive_message"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_message(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_receive_message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_copy_description(_:)/title",
          "value": "nw_connection_copy_description"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_copy_description(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_copy_description"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_cancel(_:)/title",
          "value": "nw_connection_cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_cancel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_access_establishment_report(_:_:_:)/title",
          "value": "nw_connection_access_establishment_report"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_access_establishment_report(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_access_establishment_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_set_better_path_available_handler(_:_:)/title",
          "value": "nw_connection_set_better_path_available_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_set_better_path_available_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_set_better_path_available_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/title",
          "value": "nw_connection_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_copy_protocol_metadata(_:_:)/title",
          "value": "nw_connection_copy_protocol_metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_copy_protocol_metadata(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_copy_protocol_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_copy_endpoint(_:)/title",
          "value": "nw_connection_copy_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_copy_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_copy_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection/title",
          "value": "OS_nw_connection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_completion_t/title",
          "value": "nw_connection_receive_completion_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_completion_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_receive_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive_completion_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_receive_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_set_queue(_:_:)/title",
          "value": "nw_connection_set_queue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_set_queue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_set_queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_t/title",
          "value": "nw_data_transfer_report_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_changed_handler_t/title",
          "value": "nw_connection_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_force_cancel(_:)/title",
          "value": "nw_connection_force_cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_force_cancel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_force_cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_copy_parameters(_:)/title",
          "value": "nw_connection_copy_parameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_copy_parameters(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_copy_parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_get_maximum_datagram_size(_:)/title",
          "value": "nw_connection_get_maximum_datagram_size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_get_maximum_datagram_size(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_get_maximum_datagram_size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_content_context_t/title",
          "value": "nw_content_context_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_content_context_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_content_context_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_content_context_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_content_context_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_send_completion_t/title",
          "value": "nw_connection_send_completion_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_send_completion_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_send_completion_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive(_:_:_:_:)/title",
          "value": "nw_connection_receive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_receive(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_receive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/title",
          "value": "nw_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_batch(_:_:)/title",
          "value": "nw_connection_batch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_batch(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_batch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_t/title",
          "value": "nw_connection_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_set_state_changed_handler(_:_:)/title",
          "value": "nw_connection_set_state_changed_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_set_state_changed_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_set_state_changed_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_access_block_t/title",
          "value": "nw_establishment_report_access_block_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_access_block_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_access_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_access_block_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_access_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_t/title",
          "value": "nw_establishment_report_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_create_new_data_transfer_report(_:)/title",
          "value": "nw_connection_create_new_data_transfer_report"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_create_new_data_transfer_report(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_create_new_data_transfer_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_start(_:)/title",
          "value": "nw_connection_start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_start(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_set_path_changed_handler(_:_:)/title",
          "value": "nw_connection_set_path_changed_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_set_path_changed_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_set_path_changed_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/title",
          "value": "nw_ethernet_channel_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_cancel_current_endpoint(_:)/title",
          "value": "nw_connection_cancel_current_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_cancel_current_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_cancel_current_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_send(_:_:_:_:_:)/title",
          "value": "nw_connection_send"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_send(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_send"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/title",
          "value": "nw_connection_boolean_event_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_boolean_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_boolean_event_handler_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_connection_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_connection_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
