{
  "abstract": [
    {
      "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_connection_group_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_connection_group_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_connection_group_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_connection_group_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_connection_group_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_connection_group",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_connection_group",
              "text": "OS_nw_connection_group"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_connection_group": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_connection_group"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_connection_group",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_connection_group"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_connection_group",
      "type": "topic",
      "url": "/documentation/network/os_nw_connection_group"
    },
    "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework": {
      "abstract": [
        {
          "text": "Build a simple ",
          "type": "text"
        },
        {
          "code": "netcat",
          "type": "codeVoice"
        },
        {
          "text": " tool that establishes network connections and transfers data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing netcat with Network Framework",
      "type": "topic",
      "url": "/documentation/network/implementing-netcat-with-network-framework"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_t": {
      "abstract": [
        {
          "text": "An object you use to browse for available network services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_cancel(_:)": {
      "abstract": [
        {
          "text": "Cancels the connection group object and leaves the network group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_cancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_cancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_cancel"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_cancel(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_cancel(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_copy_descriptor(_:)": {
      "abstract": [
        {
          "text": "Accesses the descriptor of the group you use to initialize the connection group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_descriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_group_descriptor_t",
          "text": "nw_group_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_copy_descriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_descriptor"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_copy_descriptor(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_copy_descriptor(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_copy_local_endpoint_for_message(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the local address and port you use to receive the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_local_endpoint_for_message"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_content_context_t",
          "text": "nw_content_context_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_copy_local_endpoint_for_message(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_local_endpoint_for_message"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_copy_local_endpoint_for_message(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_copy_local_endpoint_for_message(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_copy_parameters(_:)": {
      "abstract": [
        {
          "text": "Accesses the parameters with which you initialize the connection group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_parameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_copy_parameters(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_parameters"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_copy_parameters(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_copy_parameters(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_copy_path_for_message(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the network path on which you receive the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_path_for_message"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_content_context_t",
          "text": "nw_content_context_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_copy_path_for_message(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_path_for_message"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_copy_path_for_message(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_copy_path_for_message(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_copy_remote_endpoint_for_message(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the endpoint that originates the message you receive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_remote_endpoint_for_message"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_content_context_t",
          "text": "nw_content_context_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_copy_remote_endpoint_for_message(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_remote_endpoint_for_message"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_copy_remote_endpoint_for_message(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_copy_remote_endpoint_for_message(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_create(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a new connection group with a group identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_group_descriptor_t",
          "text": "nw_group_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_create(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_create"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_create(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_create(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_extract_connection_for_message(_:_:)": {
      "abstract": [
        {
          "text": "Converts a message you receive from an endpoint into a connection object that you use for long-term communication with that endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_extract_connection_for_message"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_content_context_t",
          "text": "nw_content_context_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_extract_connection_for_message(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_extract_connection_for_message"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_extract_connection_for_message(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_extract_connection_for_message(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives inbound messages from members of the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_receive_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_receive_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_receive_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_receive_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_reply(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sends a reply to the specific endpoint that originates a group message you receive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_reply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_content_context_t",
          "text": "nw_content_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_content_context_t",
          "text": "nw_content_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "dispatch_data_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_reply(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_reply"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_reply(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_reply(_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t": {
      "abstract": [
        {
          "text": "A completion to notify you when data has been processed and sent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_completion_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_completion_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_send_completion_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_send_completion_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_send_message(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sends data to the entire group, or to a specific member of the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_message"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "dispatch_data_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_content_context_t",
          "text": "nw_content_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_send_completion_t",
          "text": "nw_connection_group_send_completion_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_send_message(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_message"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_send_message(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_send_message(_:_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_set_queue(_:_:)": {
      "abstract": [
        {
          "text": "Sets the queue on which you handle connection group events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_set_queue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_set_queue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_set_queue"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_set_queue(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_set_queue(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_set_receive_handler(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler that receives inbound messages from members of the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_set_receive_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_receive_handler_t",
          "text": "nw_connection_group_receive_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_set_receive_handler(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_set_receive_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_set_receive_handler(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_set_receive_handler(_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_set_state_changed_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler that receives connection group state updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_set_state_changed_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_state_changed_handler_t",
          "text": "nw_connection_group_state_changed_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_set_state_changed_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_set_state_changed_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_set_state_changed_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_set_state_changed_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_start(_:)": {
      "abstract": [
        {
          "text": "Joins the group and registers to receive messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_start(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_start"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_start(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_start(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives connection group state updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_state_t": {
      "abstract": [
        {
          "text": "States that indicate whether you can use a connection group to send and receive messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_t": {
      "abstract": [
        {
          "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_t": {
      "abstract": [
        {
          "text": "A bidirectional data connection between a local endpoint and a remote endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t": {
      "abstract": [
        {
          "text": "An object you use to send and receive custom Ethernet frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_t"
    },
    "doc://com.apple.network/documentation/Network/nw_group_descriptor_add_endpoint(_:_:)": {
      "abstract": [
        {
          "text": "Adds a multicast address endpoint you specify to define an extra IP multicast group to join.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_group_descriptor_add_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_group_descriptor_t",
          "text": "nw_group_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_group_descriptor_add_endpoint(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_group_descriptor_add_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_group_descriptor_add_endpoint(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_group_descriptor_add_endpoint(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_group_descriptor_create_multicast(_:)": {
      "abstract": [
        {
          "text": "Creates group descriptor you use to join an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_group_descriptor_create_multicast"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_group_descriptor_t",
          "text": "nw_group_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_group_descriptor_create_multicast(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_group_descriptor_create_multicast"
        }
      ],
      "role": "symbol",
      "title": "nw_group_descriptor_create_multicast(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_group_descriptor_create_multicast(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_group_descriptor_enumerate_endpoints(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to list all endpoints added to the group descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_group_descriptor_enumerate_endpoints"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_group_descriptor_t",
          "text": "nw_group_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_group_descriptor_enumerate_endpoints(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_group_descriptor_enumerate_endpoints"
        }
      ],
      "role": "symbol",
      "title": "nw_group_descriptor_enumerate_endpoints(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_group_descriptor_enumerate_endpoints(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_group_descriptor_enumerate_endpoints_block_t": {
      "abstract": [
        {
          "text": "A handler that lists all endpoints added to the group descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_group_descriptor_enumerate_endpoints_block_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_group_descriptor_enumerate_endpoints_block_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_group_descriptor_enumerate_endpoints_block_t"
        }
      ],
      "role": "symbol",
      "title": "nw_group_descriptor_enumerate_endpoints_block_t",
      "type": "topic",
      "url": "/documentation/network/nw_group_descriptor_enumerate_endpoints_block_t"
    },
    "doc://com.apple.network/documentation/Network/nw_group_descriptor_t": {
      "abstract": [
        {
          "text": "A type that defines a group of endpoints with which you can communicate, such as a multicast group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_group_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_group_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_group_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_group_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_group_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_t": {
      "abstract": [
        {
          "text": "An object you use to listen for incoming network connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Establishing-Group-Connectivity",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_group_create(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_group_descriptor_create_multicast(_:)",
        "doc://com.apple.network/documentation/Network/nw_group_descriptor_t",
        "doc://com.apple.network/documentation/Network/nw_group_descriptor_add_endpoint(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_group_descriptor_enumerate_endpoints(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_group_descriptor_enumerate_endpoints_block_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_set_queue(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_group_start(_:)"
      ],
      "title": "Establishing Group Connectivity"
    },
    {
      "anchor": "Sending-and-Receiving-Group-Messages",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_group_set_receive_handler(_:_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_copy_remote_endpoint_for_message(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_group_copy_local_endpoint_for_message(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_group_copy_path_for_message(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_group_reply(_:_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_group_extract_connection_for_message(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_group_send_message(_:_:_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t"
      ],
      "title": "Sending and Receiving Group Messages"
    },
    {
      "anchor": "Managing-Groups",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_group_set_state_changed_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_state_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_cancel(_:)"
      ],
      "title": "Managing Groups"
    },
    {
      "anchor": "Inspecting-Groups",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_group_copy_descriptor(_:)",
        "doc://com.apple.network/documentation/Network/nw_connection_group_copy_parameters(_:)"
      ],
      "title": "Inspecting Groups"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Establishing-Group-Connectivity",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_group_create(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_group_descriptor_create_multicast(_:)",
                "doc://com.apple.network/documentation/Network/nw_group_descriptor_t",
                "doc://com.apple.network/documentation/Network/nw_group_descriptor_add_endpoint(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_group_descriptor_enumerate_endpoints(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_group_descriptor_enumerate_endpoints_block_t",
                "doc://com.apple.network/documentation/Network/nw_connection_group_set_queue(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_start(_:)"
              ],
              "title": "Establishing Group Connectivity"
            },
            {
              "anchor": "Sending-and-Receiving-Group-Messages",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_group_set_receive_handler(_:_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
                "doc://com.apple.network/documentation/Network/nw_connection_group_copy_remote_endpoint_for_message(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_copy_local_endpoint_for_message(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_copy_path_for_message(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_reply(_:_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_extract_connection_for_message(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_send_message(_:_:_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t"
              ],
              "title": "Sending and Receiving Group Messages"
            },
            {
              "anchor": "Managing-Groups",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_group_set_state_changed_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
                "doc://com.apple.network/documentation/Network/nw_connection_group_state_t",
                "doc://com.apple.network/documentation/Network/nw_connection_group_cancel(_:)"
              ],
              "title": "Managing Groups"
            },
            {
              "anchor": "Inspecting-Groups",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_group_copy_descriptor(_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_copy_parameters(_:)"
              ],
              "title": "Inspecting Groups"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Connections-and-Listeners",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework",
                "doc://com.apple.network/documentation/Network/nw_connection_t",
                "doc://com.apple.network/documentation/Network/nw_listener_t",
                "doc://com.apple.network/documentation/Network/nw_browser_t",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t"
              ],
              "title": "Connections and Listeners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_connection_group",
                    "text": "NSObject<OS_nw_connection_group>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_connection_group_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/title",
          "value": "nw_ethernet_channel_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_cancel(_:)/title",
          "value": "nw_connection_group_cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_cancel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/title",
          "value": "nw_connection_group_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/title",
          "value": "nw_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_add_endpoint(_:_:)/title",
          "value": "nw_group_descriptor_add_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_add_endpoint(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_group_descriptor_add_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_create_multicast(_:)/title",
          "value": "nw_group_descriptor_create_multicast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_create_multicast(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_group_descriptor_create_multicast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_set_receive_handler(_:_:_:_:)/title",
          "value": "nw_connection_group_set_receive_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_set_receive_handler(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_set_receive_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_t/title",
          "value": "nw_connection_group_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/title",
          "value": "nw_connection_group_receive_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_path_for_message(_:_:)/title",
          "value": "nw_connection_group_copy_path_for_message"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_path_for_message(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_copy_path_for_message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_parameters(_:)/title",
          "value": "nw_connection_group_copy_parameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_parameters(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_copy_parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_create(_:_:)/title",
          "value": "nw_connection_group_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_create(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_set_state_changed_handler(_:_:)/title",
          "value": "nw_connection_group_set_state_changed_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_set_state_changed_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_set_state_changed_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title",
          "value": "nw_browser_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_enumerate_endpoints(_:_:)/title",
          "value": "nw_group_descriptor_enumerate_endpoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_enumerate_endpoints(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_group_descriptor_enumerate_endpoints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_t/title",
          "value": "nw_group_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_group_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_group_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_local_endpoint_for_message(_:_:)/title",
          "value": "nw_connection_group_copy_local_endpoint_for_message"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_local_endpoint_for_message(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_copy_local_endpoint_for_message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_extract_connection_for_message(_:_:)/title",
          "value": "nw_connection_group_extract_connection_for_message"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_extract_connection_for_message(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_extract_connection_for_message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/title",
          "value": "nw_connection_group_send_completion_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_set_queue(_:_:)/title",
          "value": "nw_connection_group_set_queue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_set_queue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_set_queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_descriptor(_:)/title",
          "value": "nw_connection_group_copy_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_descriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_copy_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_message(_:_:_:_:_:)/title",
          "value": "nw_connection_group_send_message"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_message(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/title",
          "value": "nw_connection_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_enumerate_endpoints_block_t/title",
          "value": "nw_group_descriptor_enumerate_endpoints_block_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_enumerate_endpoints_block_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_group_descriptor_enumerate_endpoints_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_group_descriptor_enumerate_endpoints_block_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_group_descriptor_enumerate_endpoints_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_remote_endpoint_for_message(_:_:)/title",
          "value": "nw_connection_group_copy_remote_endpoint_for_message"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_remote_endpoint_for_message(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_copy_remote_endpoint_for_message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_start(_:)/title",
          "value": "nw_connection_group_start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_start(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection_group/title",
          "value": "OS_nw_connection_group"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection_group/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection_group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection_group/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection_group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_reply(_:_:_:_:)/title",
          "value": "nw_connection_group_reply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_reply(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_reply"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_connection_group_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_connection_group_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
