{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_connection_group_reinsert_extracted_connection(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_connection_group_reinsert_extracted_connection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_connection_group_reinsert_extracted_connection"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_connection_group_t",
        "text": "nw_connection_group_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_connection_t",
        "text": "nw_connection_t"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_connection_group_reinsert_extracted_connection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_connection_group_reinsert_extracted_connection(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_connection_group_reinsert_extracted_connection"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "group"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_connection_group_t",
              "text": "nw_connection_group_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_connection_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_connection_t",
              "text": "nw_connection_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)": {
      "abstract": [
        {
          "text": "Accesses the TXT record to advertise with the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_copy_txt_record_object"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_copy_txt_record_object"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_copy_txt_record_object(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_copy_txt_record_object(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_create_application_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_create_application_service"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_create_application_service(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_create_application_service(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)": {
      "abstract": [
        {
          "text": "Initializes a Bonjour service to advertise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_create_bonjour_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_create_bonjour_service"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_create_bonjour_service(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_get_application_service_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_get_application_service_name"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_get_application_service_name(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_get_application_service_name(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)": {
      "abstract": [
        {
          "text": "Checks whether the service prohibits automatic renaming in the event of a name conflict.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_get_no_auto_rename"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_get_no_auto_rename"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_get_no_auto_rename(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_get_no_auto_rename(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)": {
      "abstract": [
        {
          "text": "Sets a Boolean to indicate whether the service prohibits automatic renaming in the event of a name conflict.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_no_auto_rename"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_no_auto_rename"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_set_no_auto_rename(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_set_no_auto_rename(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the TXT record as a raw buffer to advertise with the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_txt_record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_txt_record"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_set_txt_record(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_set_txt_record(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)": {
      "abstract": [
        {
          "text": "Sets the TXT record to advertise with the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_txt_record_object"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_txt_record_object"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_set_txt_record_object(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_set_txt_record_object(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_create_application_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_create_application_service"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_create_application_service(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_create_application_service(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a service descriptor used to discover a Bonjour service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_create_bonjour_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_create_bonjour_service"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_create_bonjour_service(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_create_bonjour_service(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_application_service_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_application_service_name"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_application_service_name(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_application_service_name(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)": {
      "abstract": [
        {
          "text": "Accesses the Bonjour service domain set on a browse descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_domain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_domain"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_bonjour_service_domain(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_bonjour_service_domain(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)": {
      "abstract": [
        {
          "text": "Accesses the Bonjour service type set on a browse descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_type"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_bonjour_service_type(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_bonjour_service_type(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)": {
      "abstract": [
        {
          "text": "Checks if the browse descriptor requires including associated TXT records with all results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_include_txt_record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_include_txt_record"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_include_txt_record(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_include_txt_record(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)": {
      "abstract": [
        {
          "text": "Requires including associated TXT records with all results generated for this service descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_set_include_txt_record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_set_include_txt_record"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_set_include_txt_record(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_set_include_txt_record(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_copy_protocol_metadata(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_protocol_metadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_copy_protocol_metadata(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_protocol_metadata"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_copy_protocol_metadata(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_copy_protocol_metadata(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_copy_protocol_metadata_for_message(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_protocol_metadata_for_message"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_content_context_t",
          "text": "nw_content_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_copy_protocol_metadata_for_message(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_copy_protocol_metadata_for_message"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_copy_protocol_metadata_for_message(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_copy_protocol_metadata_for_message(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_extract_connection(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_extract_connection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_extract_connection(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_extract_connection"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_extract_connection(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_extract_connection(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_reinsert_extracted_connection(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_reinsert_extracted_connection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_reinsert_extracted_connection(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_reinsert_extracted_connection"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_reinsert_extracted_connection(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_reinsert_extracted_connection(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_set_new_connection_handler(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_set_new_connection_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_t",
          "text": "nw_connection_group_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_group_new_connection_handler_t",
          "text": "nw_connection_group_new_connection_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_set_new_connection_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_set_new_connection_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_set_new_connection_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_set_new_connection_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_t": {
      "abstract": [
        {
          "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_t": {
      "abstract": [
        {
          "text": "A bidirectional data connection between a local endpoint and a remote endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_t"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_path_radio_type(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_path_radio_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_path_radio_type(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_path_radio_type"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_path_radio_type(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_path_radio_type(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_copy_txt_record(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_copy_txt_record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_copy_txt_record(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_copy_txt_record"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_copy_txt_record(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_copy_txt_record(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_get_signature(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_signature"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_get_signature(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_signature"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_get_signature(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_get_signature(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_create_with_parameters(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_create_with_parameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_create_with_parameters(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_create_with_parameters"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_create_with_parameters(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_create_with_parameters(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_get_maximum_payload_size(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_get_maximum_payload_size"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
          "text": "nw_ethernet_channel_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_get_maximum_payload_size(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_get_maximum_payload_size"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_get_maximum_payload_size(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_get_maximum_payload_size(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_copy_options(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_copy_options"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_copy_options(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_copy_options"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_copy_options(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_copy_options(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_options_copy_object_value(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_options_copy_object_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_options_copy_object_value(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_options_copy_object_value"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_options_copy_object_value(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_options_copy_object_value(_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_connection_group_reinsert_extracted_connection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_reinsert_extracted_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)",
                "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)",
                "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)",
                "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_copy_protocol_metadata(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_copy_protocol_metadata_for_message(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_extract_connection(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_connection_group_set_new_connection_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_path_radio_type(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_copy_txt_record(_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_get_signature(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_create_with_parameters(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_get_maximum_payload_size(_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_copy_options(_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_options_copy_object_value(_:_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:b",
                    "text": "bool"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_connection_group_reinsert_extracted_connection"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_connection_group_t",
                    "text": "nw_connection_group_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "group"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_connection_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_connection_t",
                    "text": "nw_connection_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "connection"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_path_radio_type(_:_:)/title",
          "value": "nw_data_transfer_report_get_path_radio_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_path_radio_type(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_path_radio_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_get_maximum_payload_size(_:)/title",
          "value": "nw_ethernet_channel_get_maximum_payload_size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_get_maximum_payload_size(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_get_maximum_payload_size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_create_with_parameters(_:_:_:)/title",
          "value": "nw_ethernet_channel_create_with_parameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_create_with_parameters(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_create_with_parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_application_service_name(_:)/title",
          "value": "nw_browse_descriptor_get_application_service_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_application_service_name(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_application_service_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/title",
          "value": "nw_connection_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/title",
          "value": "nw_browse_descriptor_get_bonjour_service_domain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_bonjour_service_domain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_signature(_:_:)/title",
          "value": "nw_endpoint_get_signature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_signature(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_get_signature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_application_service(_:)/title",
          "value": "nw_browse_descriptor_create_application_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_application_service(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_create_application_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_bonjour_service(_:_:_:)/title",
          "value": "nw_advertise_descriptor_create_bonjour_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_bonjour_service(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_create_bonjour_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/title",
          "value": "nw_browse_descriptor_set_include_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_set_include_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_application_service(_:)/title",
          "value": "nw_advertise_descriptor_create_application_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_application_service(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_create_application_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/title",
          "value": "nw_browse_descriptor_create_bonjour_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_create_bonjour_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_protocol_metadata_for_message(_:_:_:)/title",
          "value": "nw_connection_group_copy_protocol_metadata_for_message"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_protocol_metadata_for_message(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_copy_protocol_metadata_for_message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_no_auto_rename(_:_:)/title",
          "value": "nw_advertise_descriptor_set_no_auto_rename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_no_auto_rename(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_set_no_auto_rename"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_options_copy_object_value(_:_:)/title",
          "value": "nw_framer_options_copy_object_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_options_copy_object_value(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_options_copy_object_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/title",
          "value": "nw_browse_descriptor_get_bonjour_service_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_bonjour_service_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_no_auto_rename(_:)/title",
          "value": "nw_advertise_descriptor_get_no_auto_rename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_no_auto_rename(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_get_no_auto_rename"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_copy_txt_record_object(_:)/title",
          "value": "nw_advertise_descriptor_copy_txt_record_object"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_copy_txt_record_object(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_copy_txt_record_object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_copy_options(_:)/title",
          "value": "nw_framer_copy_options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_copy_options(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_copy_options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record_object(_:_:)/title",
          "value": "nw_advertise_descriptor_set_txt_record_object"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record_object(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_set_txt_record_object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_set_new_connection_handler(_:_:)/title",
          "value": "nw_connection_group_set_new_connection_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_set_new_connection_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_set_new_connection_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/title",
          "value": "nw_browse_descriptor_get_include_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_include_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_extract_connection(_:_:_:)/title",
          "value": "nw_connection_group_extract_connection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_extract_connection(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_extract_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_reinsert_extracted_connection(_:_:)/title",
          "value": "nw_connection_group_reinsert_extracted_connection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_reinsert_extracted_connection(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_reinsert_extracted_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_copy_txt_record(_:)/title",
          "value": "nw_endpoint_copy_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_copy_txt_record(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_copy_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_application_service_name(_:)/title",
          "value": "nw_advertise_descriptor_get_application_service_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_application_service_name(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_get_application_service_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record(_:_:_:)/title",
          "value": "nw_advertise_descriptor_set_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_set_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_protocol_metadata(_:_:)/title",
          "value": "nw_connection_group_copy_protocol_metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_copy_protocol_metadata(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_copy_protocol_metadata"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_connection_group_reinsert_extracted_connection(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_connection_group_reinsert_extracted_connection(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
