{
  "abstract": [
    {
      "text": "A report that provides metrics about data being sent and received on a connection.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_data_transfer_report_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_data_transfer_report_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_data_transfer_report_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_data_transfer_report_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_data_transfer_report",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_data_transfer_report",
              "text": "OS_nw_data_transfer_report"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_data_transfer_report": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_data_transfer_report"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_data_transfer_report",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_data_transfer_report"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_data_transfer_report",
      "type": "topic",
      "url": "/documentation/network/os_nw_data_transfer_report"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t": {
      "abstract": [
        {
          "text": "A description used to advertise the Bonjour service that a listener provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t": {
      "abstract": [
        {
          "text": "A service description used to discover Bonjour services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_t": {
      "abstract": [
        {
          "text": "Flags describing ways in which discovered services can change between specific results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t": {
      "abstract": [
        {
          "text": "A handler that enumerates the interfaces associated with a discovered service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_enumerate_interface_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_enumerate_interface_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_enumerate_interface_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_enumerate_interface_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_t": {
      "abstract": [
        {
          "text": "A discovered service and metadata about the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers updates about discovered services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_browse_results_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_browse_results_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_browse_results_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_browse_results_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers browser state updates with associated errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_t": {
      "abstract": [
        {
          "text": "An object you use to browse for available network services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives Boolean state updates from a connection, such as viability and better path state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_boolean_event_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_boolean_event_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_boolean_event_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_boolean_event_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_new_connection_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_new_connection_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_new_connection_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_new_connection_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives inbound messages from members of the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_receive_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_receive_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_receive_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_receive_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t": {
      "abstract": [
        {
          "text": "A completion to notify you when data has been processed and sent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_completion_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_completion_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_send_completion_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_send_completion_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives connection group state updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_t": {
      "abstract": [
        {
          "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers network path updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_path_event_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_path_event_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_path_event_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_path_event_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_collect(_:_:_:)": {
      "abstract": [
        {
          "text": "Stops an outstanding data transfer report and calculates the results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_collect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_collect_block_t",
          "text": "nw_data_transfer_report_collect_block_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_collect(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_collect"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_collect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_collect(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_collect_block_t": {
      "abstract": [
        {
          "text": "A block that is delivered when a data transfer report is fully collected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_collect_block_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_collect_block_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_collect_block_t"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_collect_block_t",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_collect_block_t"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_copy_path_interface(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the network interface the path used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_copy_path_interface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_copy_path_interface(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_copy_path_interface"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_copy_path_interface(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_copy_path_interface(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_duration_milliseconds(_:)": {
      "abstract": [
        {
          "text": "Checks the duration of the data transfer report, from when it was started to when it was collected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_duration_milliseconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_duration_milliseconds(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_duration_milliseconds"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_duration_milliseconds(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_duration_milliseconds(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_path_count(_:)": {
      "abstract": [
        {
          "text": "Checks the number of valid paths in the report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_path_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_path_count(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_path_count"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_path_count(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_path_count(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_application_byte_count(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the number of bytes the connection delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_received_application_byte_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_application_byte_count(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_received_application_byte_count"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_received_application_byte_count(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_received_application_byte_count(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_ip_packet_count(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the number of IP packets the connection received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_received_ip_packet_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_ip_packet_count(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_received_ip_packet_count"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_received_ip_packet_count(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_received_ip_packet_count(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_byte_count(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the number of bytes the transport protocol delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_received_transport_byte_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_byte_count(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_received_transport_byte_count"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_received_transport_byte_count(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_received_transport_byte_count(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_duplicate_byte_count(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the number of duplicated bytes the transport protocol detected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_received_transport_duplicate_byte_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_duplicate_byte_count(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_received_transport_duplicate_byte_count"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_received_transport_duplicate_byte_count(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_received_transport_duplicate_byte_count(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_out_of_order_byte_count(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the number of bytes the transport protocol received out of order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_received_transport_out_of_order_byte_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_out_of_order_byte_count(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_received_transport_out_of_order_byte_count"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_received_transport_out_of_order_byte_count(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_received_transport_out_of_order_byte_count(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_application_byte_count(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the number of bytes sent on the connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_sent_application_byte_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_application_byte_count(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_sent_application_byte_count"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_sent_application_byte_count(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_sent_application_byte_count(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_ip_packet_count(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the number of IP packets the connection sent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_sent_ip_packet_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_ip_packet_count(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_sent_ip_packet_count"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_sent_ip_packet_count(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_sent_ip_packet_count(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_transport_byte_count(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the number of bytes sent into the transport protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_sent_transport_byte_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_transport_byte_count(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_sent_transport_byte_count"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_sent_transport_byte_count(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_sent_transport_byte_count(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_transport_retransmitted_byte_count(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the number of bytes the transport protocol retransmitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_sent_transport_retransmitted_byte_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_transport_retransmitted_byte_count(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_sent_transport_retransmitted_byte_count"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_sent_transport_retransmitted_byte_count(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_sent_transport_retransmitted_byte_count(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_state(_:)": {
      "abstract": [
        {
          "text": "Checks whether a data transfer report is collected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_state"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_data_transfer_report_state_t",
          "text": "nw_data_transfer_report_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_state(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_state"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_state(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_state(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_minimum_rtt_milliseconds(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the minimum round-trip time the transport protocol measured, in milliseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_transport_minimum_rtt_milliseconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_minimum_rtt_milliseconds(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_transport_minimum_rtt_milliseconds"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_transport_minimum_rtt_milliseconds(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_transport_minimum_rtt_milliseconds(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_rtt_variance(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the variance of the round-trip time the transport protocol measured.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_transport_rtt_variance"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_rtt_variance(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_transport_rtt_variance"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_transport_rtt_variance(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_transport_rtt_variance(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the smoothed round-trip time the transport protocol measured, in milliseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_data_transfer_report_t",
          "text": "nw_data_transfer_report_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a data transfer report is collected yet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_t": {
      "abstract": [
        {
          "text": "A report that provides metrics about data being sent and received on a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_t"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_t",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_change_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_t",
        "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_browser_t",
        "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_t",
        "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Collecting-Reports",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_collect(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_collect_block_t",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_state(_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t"
      ],
      "title": "Collecting Reports"
    },
    {
      "anchor": "Identifying-Paths",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_path_count(_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_duration_milliseconds(_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_copy_path_interface(_:_:)"
      ],
      "title": "Identifying Paths"
    },
    {
      "anchor": "Inspecting-Application-Metrics",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_application_byte_count(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_application_byte_count(_:_:)"
      ],
      "title": "Inspecting Application Metrics"
    },
    {
      "anchor": "Inspecting-Transport-Metrics",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_byte_count(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_duplicate_byte_count(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_out_of_order_byte_count(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_transport_byte_count(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_transport_retransmitted_byte_count(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_minimum_rtt_milliseconds(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_rtt_variance(_:_:)"
      ],
      "title": "Inspecting Transport Metrics"
    },
    {
      "anchor": "Inspecting-Packet-Metrics",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_ip_packet_count(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_ip_packet_count(_:_:)"
      ],
      "title": "Inspecting Packet Metrics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_data_transfer_report_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Collecting-Reports",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_collect(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_collect_block_t",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_state(_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t"
              ],
              "title": "Collecting Reports"
            },
            {
              "anchor": "Identifying-Paths",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_path_count(_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_duration_milliseconds(_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_copy_path_interface(_:_:)"
              ],
              "title": "Identifying Paths"
            },
            {
              "anchor": "Inspecting-Application-Metrics",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_application_byte_count(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_application_byte_count(_:_:)"
              ],
              "title": "Inspecting Application Metrics"
            },
            {
              "anchor": "Inspecting-Transport-Metrics",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_byte_count(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_duplicate_byte_count(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_transport_out_of_order_byte_count(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_transport_byte_count(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_transport_retransmitted_byte_count(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_minimum_rtt_milliseconds(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_transport_rtt_variance(_:_:)"
              ],
              "title": "Inspecting Transport Metrics"
            },
            {
              "anchor": "Inspecting-Packet-Metrics",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_received_ip_packet_count(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_get_sent_ip_packet_count(_:_:)"
              ],
              "title": "Inspecting Packet Metrics"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_data_transfer_report",
                    "text": "NSObject<OS_nw_data_transfer_report>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_data_transfer_report_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/title",
          "value": "nw_connection_path_event_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_path_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_path_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/title",
          "value": "nw_connection_boolean_event_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_boolean_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_boolean_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_received_transport_byte_count(_:_:)/title",
          "value": "nw_data_transfer_report_get_received_transport_byte_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_received_transport_byte_count(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_received_transport_byte_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_duration_milliseconds(_:)/title",
          "value": "nw_data_transfer_report_get_duration_milliseconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_duration_milliseconds(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_duration_milliseconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_received_application_byte_count(_:_:)/title",
          "value": "nw_data_transfer_report_get_received_application_byte_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_received_application_byte_count(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_received_application_byte_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/title",
          "value": "nw_connection_group_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/title",
          "value": "nw_browser_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/title",
          "value": "nw_browse_result_change_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_t/title",
          "value": "nw_data_transfer_report_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/title",
          "value": "nw_browse_result_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_state_t/title",
          "value": "nw_data_transfer_report_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/title",
          "value": "nw_connection_group_send_completion_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_sent_ip_packet_count(_:_:)/title",
          "value": "nw_data_transfer_report_get_sent_ip_packet_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_sent_ip_packet_count(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_sent_ip_packet_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_received_ip_packet_count(_:_:)/title",
          "value": "nw_data_transfer_report_get_received_ip_packet_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_received_ip_packet_count(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_received_ip_packet_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_state(_:)/title",
          "value": "nw_data_transfer_report_get_state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_state(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_received_transport_out_of_order_byte_count(_:_:)/title",
          "value": "nw_data_transfer_report_get_received_transport_out_of_order_byte_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_received_transport_out_of_order_byte_count(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_received_transport_out_of_order_byte_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/title",
          "value": "nw_connection_group_receive_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_sent_transport_byte_count(_:_:)/title",
          "value": "nw_data_transfer_report_get_sent_transport_byte_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_sent_transport_byte_count(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_sent_transport_byte_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds(_:_:)/title",
          "value": "nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_transport_smoothed_rtt_milliseconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_collect(_:_:_:)/title",
          "value": "nw_data_transfer_report_collect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_collect(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_collect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_collect_block_t/title",
          "value": "nw_data_transfer_report_collect_block_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_collect_block_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_collect_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_collect_block_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_collect_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_copy_path_interface(_:_:)/title",
          "value": "nw_data_transfer_report_copy_path_interface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_copy_path_interface(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_copy_path_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/title",
          "value": "nw_connection_group_new_connection_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_new_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_new_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_transport_minimum_rtt_milliseconds(_:_:)/title",
          "value": "nw_data_transfer_report_get_transport_minimum_rtt_milliseconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_transport_minimum_rtt_milliseconds(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_transport_minimum_rtt_milliseconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/title",
          "value": "nw_browser_browse_results_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_browse_results_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_browse_results_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/title",
          "value": "nw_browse_result_enumerate_interface_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_enumerate_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_enumerate_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_path_count(_:)/title",
          "value": "nw_data_transfer_report_get_path_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_path_count(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_path_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_data_transfer_report/title",
          "value": "OS_nw_data_transfer_report"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_data_transfer_report/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_data_transfer_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_data_transfer_report/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_data_transfer_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/title",
          "value": "nw_advertise_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_received_transport_duplicate_byte_count(_:_:)/title",
          "value": "nw_data_transfer_report_get_received_transport_duplicate_byte_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_received_transport_duplicate_byte_count(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_received_transport_duplicate_byte_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title",
          "value": "nw_browser_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_sent_application_byte_count(_:_:)/title",
          "value": "nw_data_transfer_report_get_sent_application_byte_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_sent_application_byte_count(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_sent_application_byte_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/title",
          "value": "nw_browse_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_transport_rtt_variance(_:_:)/title",
          "value": "nw_data_transfer_report_get_transport_rtt_variance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_transport_rtt_variance(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_transport_rtt_variance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_sent_transport_retransmitted_byte_count(_:_:)/title",
          "value": "nw_data_transfer_report_get_sent_transport_retransmitted_byte_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_get_sent_transport_retransmitted_byte_count(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_get_sent_transport_retransmitted_byte_count"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_data_transfer_report_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_data_transfer_report_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
