{
  "abstract": [
    {
      "text": "Sends a single Ethernet frame over a channel to a specific Ethernet address.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send(_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_ethernet_channel_send",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_ethernet_channel_send"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
        "text": "nw_ethernet_channel_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "dispatch_data_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt16V",
        "text": "UInt16"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5UInt8V",
        "text": "UInt8"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_ethernet_channel_send_completion_t",
        "text": "nw_ethernet_channel_send_completion_t"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_ethernet_channel_send"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_ethernet_channel_send(_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_send"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ethernet_channel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
              "text": "nw_ethernet_channel_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "content"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "dispatch_data_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vlan_tag"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt16V",
              "text": "UInt16"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "remote_address"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send_completion_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_ethernet_channel_send_completion_t",
              "text": "nw_ethernet_channel_send_completion_t"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)": {
      "abstract": [
        {
          "text": "Accesses the TXT record to advertise with the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_copy_txt_record_object"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_copy_txt_record_object"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_copy_txt_record_object(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_copy_txt_record_object(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_create_application_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_create_application_service"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_create_application_service(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_create_application_service(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)": {
      "abstract": [
        {
          "text": "Initializes a Bonjour service to advertise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_create_bonjour_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_create_bonjour_service"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_create_bonjour_service(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_get_application_service_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_get_application_service_name"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_get_application_service_name(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_get_application_service_name(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)": {
      "abstract": [
        {
          "text": "Checks whether the service prohibits automatic renaming in the event of a name conflict.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_get_no_auto_rename"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_get_no_auto_rename"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_get_no_auto_rename(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_get_no_auto_rename(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)": {
      "abstract": [
        {
          "text": "Sets a Boolean to indicate whether the service prohibits automatic renaming in the event of a name conflict.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_no_auto_rename"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_no_auto_rename"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_set_no_auto_rename(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_set_no_auto_rename(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the TXT record as a raw buffer to advertise with the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_txt_record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_txt_record"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_set_txt_record(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_set_txt_record(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)": {
      "abstract": [
        {
          "text": "Sets the TXT record to advertise with the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_txt_record_object"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_set_txt_record_object"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_set_txt_record_object(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_set_txt_record_object(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_create_application_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_create_application_service"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_create_application_service(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_create_application_service(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a service descriptor used to discover a Bonjour service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_create_bonjour_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_create_bonjour_service"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_create_bonjour_service(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_create_bonjour_service(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_application_service_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_application_service_name"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_application_service_name(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_application_service_name(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)": {
      "abstract": [
        {
          "text": "Accesses the Bonjour service domain set on a browse descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_domain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_domain"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_bonjour_service_domain(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_bonjour_service_domain(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)": {
      "abstract": [
        {
          "text": "Accesses the Bonjour service type set on a browse descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_bonjour_service_type"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_bonjour_service_type(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_bonjour_service_type(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)": {
      "abstract": [
        {
          "text": "Checks if the browse descriptor requires including associated TXT records with all results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_include_txt_record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_get_include_txt_record"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_get_include_txt_record(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_get_include_txt_record(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)": {
      "abstract": [
        {
          "text": "Requires including associated TXT records with all results generated for this service descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_set_include_txt_record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_browse_descriptor_t",
          "text": "nw_browse_descriptor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_set_include_txt_record"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_set_include_txt_record(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_set_include_txt_record(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_address_t": {
      "abstract": [
        {
          "text": "A 48-bit Ethernet address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_address_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_address_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_address_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_address_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_address_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sends a single Ethernet frame over a channel to a specific Ethernet address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_send"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
          "text": "nw_ethernet_channel_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "dispatch_data_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_send_completion_t",
          "text": "nw_ethernet_channel_send_completion_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_send"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_send(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_send(_:_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send_completion_t": {
      "abstract": [
        {
          "text": "A handler that indicates when an Ethernet frame has been sent, or if an error was encountered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_send_completion_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send_completion_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_send_completion_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_send_completion_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_send_completion_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t": {
      "abstract": [
        {
          "text": "An object you use to send and receive custom Ethernet frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_t"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5UInt8V": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt8",
      "type": "topic",
      "url": "/documentation/Swift/UInt8"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt16V": {
      "abstract": [
        {
          "text": "A 16-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt16",
      "type": "topic",
      "url": "/documentation/Swift/UInt16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_ethernet_channel_send"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_send"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_ethernet_channel_send"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
                    "text": "nw_ethernet_channel_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "ethernet_channel"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@dispatch_data_t",
                    "text": "dispatch_data_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "content"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vlan_tag"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_address_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_ethernet_address_t",
                    "text": "nw_ethernet_address_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "remote_address"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send_completion_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_ethernet_channel_send_completion_t",
                    "text": "nw_ethernet_channel_send_completion_t"
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/title",
          "value": "nw_browse_descriptor_get_bonjour_service_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_bonjour_service_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/title",
          "value": "nw_browse_descriptor_get_include_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_include_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/title",
          "value": "nw_browse_descriptor_create_bonjour_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_create_bonjour_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_copy_txt_record_object(_:)/title",
          "value": "nw_advertise_descriptor_copy_txt_record_object"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_copy_txt_record_object(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_copy_txt_record_object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_send_completion_t/title",
          "value": "nw_ethernet_channel_send_completion_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_send_completion_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_send_completion_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_address_t/title",
          "value": "nw_ethernet_address_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_address_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_address_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_address_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_address_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/title",
          "value": "nw_browse_descriptor_set_include_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_set_include_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_bonjour_service(_:_:_:)/title",
          "value": "nw_advertise_descriptor_create_bonjour_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_bonjour_service(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_create_bonjour_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record_object(_:_:)/title",
          "value": "nw_advertise_descriptor_set_txt_record_object"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record_object(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_set_txt_record_object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/title",
          "value": "nw_ethernet_channel_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_no_auto_rename(_:)/title",
          "value": "nw_advertise_descriptor_get_no_auto_rename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_no_auto_rename(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_get_no_auto_rename"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_application_service(_:)/title",
          "value": "nw_browse_descriptor_create_application_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_application_service(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_create_application_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_application_service(_:)/title",
          "value": "nw_advertise_descriptor_create_application_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_application_service(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_create_application_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_application_service_name(_:)/title",
          "value": "nw_browse_descriptor_get_application_service_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_application_service_name(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_application_service_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_send(_:_:_:_:_:)/title",
          "value": "nw_ethernet_channel_send"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_send(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_send"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/title",
          "value": "nw_browse_descriptor_get_bonjour_service_domain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_get_bonjour_service_domain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_application_service_name(_:)/title",
          "value": "nw_advertise_descriptor_get_application_service_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_application_service_name(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_get_application_service_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record(_:_:_:)/title",
          "value": "nw_advertise_descriptor_set_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_set_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_no_auto_rename(_:_:)/title",
          "value": "nw_advertise_descriptor_set_no_auto_rename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_no_auto_rename(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_set_no_auto_rename"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_ethernet_channel_send(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_ethernet_channel_send(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
