{
  "abstract": [
    {
      "text": "A local or remote endpoint in a network connection.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_endpoint_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_endpoint_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_endpoint_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_endpoint_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_endpoint_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_endpoint_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_endpoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_endpoint",
              "text": "OS_nw_endpoint"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_endpoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_endpoint"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_endpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_endpoint"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_endpoint",
      "type": "topic",
      "url": "/documentation/network/os_nw_endpoint"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_copy_address_string(_:)": {
      "abstract": [
        {
          "text": "Copies the address of an endpoint as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_copy_address_string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_copy_address_string(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_copy_address_string"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_copy_address_string(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_copy_address_string(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_copy_port_string(_:)": {
      "abstract": [
        {
          "text": "Copies the port of an endpoint as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_copy_port_string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_copy_port_string(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_copy_port_string"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_copy_port_string(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_copy_port_string(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_create_address(_:)": {
      "abstract": [
        {
          "text": "Creates a network endpoint with an address structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_create_address"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@sockaddr",
          "text": "sockaddr"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_create_address(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_create_address"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_create_address(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_create_address(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_create_bonjour_service(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a network endpoint with a Bonjour service name, type, and domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_create_bonjour_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_create_bonjour_service(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_create_bonjour_service"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_create_bonjour_service(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_create_bonjour_service(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_create_host(_:_:)": {
      "abstract": [
        {
          "text": "Creates a network endpoint with a hostname and port, where the hostname may be interpreted as an IP address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_create_host"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_create_host(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_create_host"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_create_host(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_create_host(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_create_url(_:)": {
      "abstract": [
        {
          "text": "Creates a network endpoint with a URL string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_create_url"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_create_url(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_create_url"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_create_url(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_create_url(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_get_address(_:)": {
      "abstract": [
        {
          "text": "Accesses the address structure stored in an address endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_address"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@sockaddr",
          "text": "sockaddr"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_get_address(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_address"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_get_address(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_get_address(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_domain(_:)": {
      "abstract": [
        {
          "text": "Accesses the Bonjour service domain stored in an endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_bonjour_service_domain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_domain(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_bonjour_service_domain"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_get_bonjour_service_domain(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_get_bonjour_service_domain(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_name(_:)": {
      "abstract": [
        {
          "text": "Accesses the Bonjour service name stored in an endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_bonjour_service_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_name(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_bonjour_service_name"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_get_bonjour_service_name(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_get_bonjour_service_name(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_type(_:)": {
      "abstract": [
        {
          "text": "Accesses the Bonjour service type stored in an endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_bonjour_service_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_type(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_bonjour_service_type"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_get_bonjour_service_type(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_get_bonjour_service_type(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_get_hostname(_:)": {
      "abstract": [
        {
          "text": "Accesses the hostname stored in an endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_hostname"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_get_hostname(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_hostname"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_get_hostname(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_get_hostname(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_get_port(_:)": {
      "abstract": [
        {
          "text": "Accesses the port stored in an endpoint, in host-byte order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_port"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_get_port(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_port"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_get_port(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_get_port(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_get_type(_:)": {
      "abstract": [
        {
          "text": "Accesses the type of a endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_endpoint_type_t",
          "text": "nw_endpoint_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_get_type(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_type"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_get_type(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_get_type(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_get_url(_:)": {
      "abstract": [
        {
          "text": "Accesses the URL string stored in an endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_url"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_get_url(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_get_url"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_get_url(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_get_url(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_t": {
      "abstract": [
        {
          "text": "A local or remote endpoint in a network connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_t"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_t",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_t"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_type_t": {
      "abstract": [
        {
          "text": "The type of a network endpoint, such as a host or a service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_type_t"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_type_t",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_type_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_t": {
      "abstract": [
        {
          "text": "An object that stores the protocols to use for connections, options for sending data, and network path constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Endpoint-Types",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_endpoint_type_t",
        "doc://com.apple.network/documentation/Network/nw_endpoint_get_type(_:)"
      ],
      "title": "Endpoint Types"
    },
    {
      "anchor": "Host-Endpoints",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_endpoint_create_host(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_endpoint_get_hostname(_:)",
        "doc://com.apple.network/documentation/Network/nw_endpoint_get_port(_:)",
        "doc://com.apple.network/documentation/Network/nw_endpoint_copy_port_string(_:)"
      ],
      "title": "Host Endpoints"
    },
    {
      "anchor": "Address-Endpoints",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_endpoint_create_address(_:)",
        "doc://com.apple.network/documentation/Network/nw_endpoint_get_address(_:)",
        "doc://com.apple.network/documentation/Network/nw_endpoint_copy_address_string(_:)",
        "doc://com.apple.network/documentation/Network/nw_endpoint_copy_port_string(_:)"
      ],
      "title": "Address Endpoints"
    },
    {
      "anchor": "Bonjour-Service-Endpoints",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_endpoint_create_bonjour_service(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_name(_:)",
        "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_type(_:)",
        "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_domain(_:)"
      ],
      "title": "Bonjour Service Endpoints"
    },
    {
      "anchor": "URL-Endpoints",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_endpoint_create_url(_:)",
        "doc://com.apple.network/documentation/Network/nw_endpoint_get_url(_:)"
      ],
      "title": "URL Endpoints"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_endpoint_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Endpoint-Types",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_endpoint_type_t",
                "doc://com.apple.network/documentation/Network/nw_endpoint_get_type(_:)"
              ],
              "title": "Endpoint Types"
            },
            {
              "anchor": "Host-Endpoints",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_endpoint_create_host(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_get_hostname(_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_get_port(_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_copy_port_string(_:)"
              ],
              "title": "Host Endpoints"
            },
            {
              "anchor": "Address-Endpoints",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_endpoint_create_address(_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_get_address(_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_copy_address_string(_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_copy_port_string(_:)"
              ],
              "title": "Address Endpoints"
            },
            {
              "anchor": "Bonjour-Service-Endpoints",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_endpoint_create_bonjour_service(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_name(_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_type(_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_get_bonjour_service_domain(_:)"
              ],
              "title": "Bonjour Service Endpoints"
            },
            {
              "anchor": "URL-Endpoints",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_endpoint_create_url(_:)",
                "doc://com.apple.network/documentation/Network/nw_endpoint_get_url(_:)"
              ],
              "title": "URL Endpoints"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_parameters_t"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_endpoint",
                    "text": "NSObject<OS_nw_endpoint>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_endpoint_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_create_address(_:)/title",
          "value": "nw_endpoint_create_address"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_create_address(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_create_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_bonjour_service_name(_:)/title",
          "value": "nw_endpoint_get_bonjour_service_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_bonjour_service_name(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_get_bonjour_service_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_port(_:)/title",
          "value": "nw_endpoint_get_port"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_port(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_get_port"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_url(_:)/title",
          "value": "nw_endpoint_get_url"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_url(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_get_url"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_type(_:)/title",
          "value": "nw_endpoint_get_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_type(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_get_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_endpoint/title",
          "value": "OS_nw_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_endpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_endpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_bonjour_service_domain(_:)/title",
          "value": "nw_endpoint_get_bonjour_service_domain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_bonjour_service_domain(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_get_bonjour_service_domain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_create_url(_:)/title",
          "value": "nw_endpoint_create_url"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_create_url(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_create_url"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_copy_address_string(_:)/title",
          "value": "nw_endpoint_copy_address_string"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_copy_address_string(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_copy_address_string"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_hostname(_:)/title",
          "value": "nw_endpoint_get_hostname"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_hostname(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_get_hostname"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_bonjour_service_type(_:)/title",
          "value": "nw_endpoint_get_bonjour_service_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_bonjour_service_type(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_get_bonjour_service_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_copy_port_string(_:)/title",
          "value": "nw_endpoint_copy_port_string"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_copy_port_string(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_copy_port_string"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_create_host(_:_:)/title",
          "value": "nw_endpoint_create_host"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_create_host(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_create_host"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/title",
          "value": "nw_endpoint_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/title",
          "value": "nw_parameters_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_address(_:)/title",
          "value": "nw_endpoint_get_address"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_get_address(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_get_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_type_t/title",
          "value": "nw_endpoint_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_create_bonjour_service(_:_:_:)/title",
          "value": "nw_endpoint_create_bonjour_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_create_bonjour_service(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_create_bonjour_service"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_endpoint_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_endpoint_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
