{
  "abstract": [
    {
      "text": "A report that provides metrics about how a connection was established.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_establishment_report_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_establishment_report_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_establishment_report_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_establishment_report_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_establishment_report_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_establishment_report_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_establishment_report",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_establishment_report",
              "text": "OS_nw_establishment_report"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_establishment_report": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_establishment_report"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_establishment_report",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_establishment_report"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_establishment_report",
      "type": "topic",
      "url": "/documentation/network/os_nw_establishment_report"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t": {
      "abstract": [
        {
          "text": "A description used to advertise the Bonjour service that a listener provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t": {
      "abstract": [
        {
          "text": "A service description used to discover Bonjour services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_t": {
      "abstract": [
        {
          "text": "Flags describing ways in which discovered services can change between specific results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t": {
      "abstract": [
        {
          "text": "A handler that enumerates the interfaces associated with a discovered service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_enumerate_interface_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_enumerate_interface_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_enumerate_interface_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_enumerate_interface_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_t": {
      "abstract": [
        {
          "text": "A discovered service and metadata about the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers updates about discovered services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_browse_results_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_browse_results_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_browse_results_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_browse_results_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers browser state updates with associated errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_t": {
      "abstract": [
        {
          "text": "An object you use to browse for available network services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives Boolean state updates from a connection, such as viability and better path state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_boolean_event_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_boolean_event_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_boolean_event_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_boolean_event_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_new_connection_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_new_connection_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_new_connection_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_new_connection_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives inbound messages from members of the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_receive_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_receive_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_receive_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_receive_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t": {
      "abstract": [
        {
          "text": "A completion to notify you when data has been processed and sent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_completion_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_completion_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_send_completion_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_send_completion_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives connection group state updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_t": {
      "abstract": [
        {
          "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers network path updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_path_event_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_path_event_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_path_event_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_path_event_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_copy_proxy_endpoint(_:)": {
      "abstract": [
        {
          "text": "Accesses the endpoint of the proxy the connection used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_copy_proxy_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_establishment_report_t",
          "text": "nw_establishment_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_copy_proxy_endpoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_copy_proxy_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_copy_proxy_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_copy_proxy_endpoint(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_protocols(_:_:)": {
      "abstract": [
        {
          "text": "Iterates a list of protocol handshakes in order from first completed to last completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_enumerate_protocols"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_establishment_report_t",
          "text": "nw_establishment_report_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_protocols(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_enumerate_protocols"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_enumerate_protocols(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_enumerate_protocols(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_resolution_reports(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_enumerate_resolution_reports"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_establishment_report_t",
          "text": "nw_establishment_report_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolution_report_t",
          "text": "nw_resolution_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_resolution_reports(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_enumerate_resolution_reports"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_enumerate_resolution_reports(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_enumerate_resolution_reports(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_resolutions(_:_:)": {
      "abstract": [
        {
          "text": "Iterates a list of resolution steps performed during connection establishment, in order from first resolved to last resolved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_enumerate_resolutions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_establishment_report_t",
          "text": "nw_establishment_report_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_report_resolution_source_t",
          "text": "nw_report_resolution_source_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_resolutions(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_enumerate_resolutions"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_enumerate_resolutions(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_enumerate_resolutions(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_get_attempt_started_after_milliseconds(_:)": {
      "abstract": [
        {
          "text": "Accesses the time between the call to start and the beginning of the successful connection attempt, in milliseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_get_attempt_started_after_milliseconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_establishment_report_t",
          "text": "nw_establishment_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_get_attempt_started_after_milliseconds(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_get_attempt_started_after_milliseconds"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_get_attempt_started_after_milliseconds(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_get_attempt_started_after_milliseconds(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_get_duration_milliseconds(_:)": {
      "abstract": [
        {
          "text": "Checks the total duration of the successful connection establishment attempt, from the preparing state to the ready state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_get_duration_milliseconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_establishment_report_t",
          "text": "nw_establishment_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_get_duration_milliseconds(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_get_duration_milliseconds"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_get_duration_milliseconds(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_get_duration_milliseconds(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_get_previous_attempt_count(_:)": {
      "abstract": [
        {
          "text": "Checks the number of attempts made before the successful attempt, when the connection moved from the preparing state back to the waiting state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_get_previous_attempt_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_establishment_report_t",
          "text": "nw_establishment_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_get_previous_attempt_count(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_get_previous_attempt_count"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_get_previous_attempt_count(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_get_previous_attempt_count(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_get_proxy_configured(_:)": {
      "abstract": [
        {
          "text": "Checks whether a proxy was configured on the connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_get_proxy_configured"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_establishment_report_t",
          "text": "nw_establishment_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_get_proxy_configured(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_get_proxy_configured"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_get_proxy_configured(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_get_proxy_configured(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_get_used_proxy(_:)": {
      "abstract": [
        {
          "text": "Checks whether the connection used a proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_get_used_proxy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_establishment_report_t",
          "text": "nw_establishment_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_get_used_proxy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_get_used_proxy"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_get_used_proxy(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_get_used_proxy(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_establishment_report_t": {
      "abstract": [
        {
          "text": "A report that provides metrics about how a connection was established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_establishment_report_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_establishment_report_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_establishment_report_t"
        }
      ],
      "role": "symbol",
      "title": "nw_establishment_report_t",
      "type": "topic",
      "url": "/documentation/network/nw_establishment_report_t"
    },
    "doc://com.apple.network/documentation/Network/nw_report_protocol_enumerator_t": {
      "abstract": [
        {
          "text": "A block used to enumerate protocol handshakes performed during connection establishment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_report_protocol_enumerator_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_report_protocol_enumerator_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_report_protocol_enumerator_t"
        }
      ],
      "role": "symbol",
      "title": "nw_report_protocol_enumerator_t",
      "type": "topic",
      "url": "/documentation/network/nw_report_protocol_enumerator_t"
    },
    "doc://com.apple.network/documentation/Network/nw_report_resolution_enumerator_t": {
      "abstract": [
        {
          "text": "A block used to enumerate resolution steps performed during connection establishment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_report_resolution_enumerator_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_report_resolution_enumerator_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_report_resolution_enumerator_t"
        }
      ],
      "role": "symbol",
      "title": "nw_report_resolution_enumerator_t",
      "type": "topic",
      "url": "/documentation/network/nw_report_resolution_enumerator_t"
    },
    "doc://com.apple.network/documentation/Network/nw_report_resolution_protocol_t": {
      "abstract": [
        {
          "text": "A set of transport protocols connections use for DNS resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_report_resolution_protocol_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_report_resolution_protocol_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_report_resolution_protocol_t"
        }
      ],
      "role": "symbol",
      "title": "nw_report_resolution_protocol_t",
      "type": "topic",
      "url": "/documentation/network/nw_report_resolution_protocol_t"
    },
    "doc://com.apple.network/documentation/Network/nw_report_resolution_report_enumerator_t": {
      "abstract": [
        {
          "text": "Iterates a list of resolution steps, as ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.network/documentation/Network/nw_resolution_report_t",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects, performed during connection establishment, in order from first resolved to last resolved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_report_resolution_report_enumerator_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_report_resolution_report_enumerator_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_report_resolution_report_enumerator_t"
        }
      ],
      "role": "symbol",
      "title": "nw_report_resolution_report_enumerator_t",
      "type": "topic",
      "url": "/documentation/network/nw_report_resolution_report_enumerator_t"
    },
    "doc://com.apple.network/documentation/Network/nw_report_resolution_source_t": {
      "abstract": [
        {
          "text": "Sources that may provide DNS responses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_report_resolution_source_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_report_resolution_source_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_report_resolution_source_t"
        }
      ],
      "role": "symbol",
      "title": "nw_report_resolution_source_t",
      "type": "topic",
      "url": "/documentation/network/nw_report_resolution_source_t"
    },
    "doc://com.apple.network/documentation/Network/nw_resolution_report_copy_preferred_endpoint(_:)": {
      "abstract": [
        {
          "text": "Accesses the resolved endpoint that the connection used for its first connection attempt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolution_report_copy_preferred_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolution_report_t",
          "text": "nw_resolution_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolution_report_copy_preferred_endpoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolution_report_copy_preferred_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_resolution_report_copy_preferred_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolution_report_copy_preferred_endpoint(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolution_report_copy_successful_endpoint(_:)": {
      "abstract": [
        {
          "text": "Accesses the resolved endpoint that led to the established connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolution_report_copy_successful_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolution_report_t",
          "text": "nw_resolution_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolution_report_copy_successful_endpoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolution_report_copy_successful_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_resolution_report_copy_successful_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolution_report_copy_successful_endpoint(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolution_report_get_endpoint_count(_:)": {
      "abstract": [
        {
          "text": "Accesses the number of endpoints resolved in this step.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolution_report_get_endpoint_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolution_report_t",
          "text": "nw_resolution_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolution_report_get_endpoint_count(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolution_report_get_endpoint_count"
        }
      ],
      "role": "symbol",
      "title": "nw_resolution_report_get_endpoint_count(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolution_report_get_endpoint_count(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolution_report_get_milliseconds(_:)": {
      "abstract": [
        {
          "text": "Accesses the duration of this resolution step, from when the query was issued to when the response was complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolution_report_get_milliseconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolution_report_t",
          "text": "nw_resolution_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolution_report_get_milliseconds(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolution_report_get_milliseconds"
        }
      ],
      "role": "symbol",
      "title": "nw_resolution_report_get_milliseconds(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolution_report_get_milliseconds(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolution_report_get_protocol(_:)": {
      "abstract": [
        {
          "text": "Accesses the transport protocol your connection used for DNS resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolution_report_get_protocol"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolution_report_t",
          "text": "nw_resolution_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_report_resolution_protocol_t",
          "text": "nw_report_resolution_protocol_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolution_report_get_protocol(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolution_report_get_protocol"
        }
      ],
      "role": "symbol",
      "title": "nw_resolution_report_get_protocol(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolution_report_get_protocol(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolution_report_get_source(_:)": {
      "abstract": [
        {
          "text": "Accesses the source of the DNS response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolution_report_get_source"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolution_report_t",
          "text": "nw_resolution_report_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_report_resolution_source_t",
          "text": "nw_report_resolution_source_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolution_report_get_source(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolution_report_get_source"
        }
      ],
      "role": "symbol",
      "title": "nw_resolution_report_get_source(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolution_report_get_source(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolution_report_t": {
      "abstract": [
        {
          "text": "A description of a single DNS resolution step.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolution_report_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolution_report_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolution_report_t"
        }
      ],
      "role": "symbol",
      "title": "nw_resolution_report_t",
      "type": "topic",
      "url": "/documentation/network/nw_resolution_report_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_change_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_t",
        "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_browser_t",
        "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_t",
        "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-Connection-Attempts",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_establishment_report_get_duration_milliseconds(_:)",
        "doc://com.apple.network/documentation/Network/nw_establishment_report_get_previous_attempt_count(_:)",
        "doc://com.apple.network/documentation/Network/nw_establishment_report_get_attempt_started_after_milliseconds(_:)"
      ],
      "title": "Inspecting Connection Attempts"
    },
    {
      "anchor": "Inspecting-Resolution",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_resolution_reports(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_report_resolution_report_enumerator_t",
        "doc://com.apple.network/documentation/Network/nw_resolution_report_t",
        "doc://com.apple.network/documentation/Network/nw_resolution_report_get_milliseconds(_:)",
        "doc://com.apple.network/documentation/Network/nw_resolution_report_get_source(_:)",
        "doc://com.apple.network/documentation/Network/nw_report_resolution_source_t",
        "doc://com.apple.network/documentation/Network/nw_resolution_report_get_protocol(_:)",
        "doc://com.apple.network/documentation/Network/nw_report_resolution_protocol_t",
        "doc://com.apple.network/documentation/Network/nw_resolution_report_copy_successful_endpoint(_:)",
        "doc://com.apple.network/documentation/Network/nw_resolution_report_copy_preferred_endpoint(_:)",
        "doc://com.apple.network/documentation/Network/nw_resolution_report_get_endpoint_count(_:)",
        "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_resolutions(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_report_resolution_enumerator_t"
      ],
      "title": "Inspecting Resolution"
    },
    {
      "anchor": "Inspecting-Protocol-Handshakes",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_protocols(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_report_protocol_enumerator_t"
      ],
      "title": "Inspecting Protocol Handshakes"
    },
    {
      "anchor": "Checking-for-Proxies",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_establishment_report_get_proxy_configured(_:)",
        "doc://com.apple.network/documentation/Network/nw_establishment_report_get_used_proxy(_:)",
        "doc://com.apple.network/documentation/Network/nw_establishment_report_copy_proxy_endpoint(_:)"
      ],
      "title": "Checking for Proxies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_establishment_report_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-Connection-Attempts",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_establishment_report_get_duration_milliseconds(_:)",
                "doc://com.apple.network/documentation/Network/nw_establishment_report_get_previous_attempt_count(_:)",
                "doc://com.apple.network/documentation/Network/nw_establishment_report_get_attempt_started_after_milliseconds(_:)"
              ],
              "title": "Inspecting Connection Attempts"
            },
            {
              "anchor": "Inspecting-Resolution",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_resolution_reports(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_report_resolution_report_enumerator_t",
                "doc://com.apple.network/documentation/Network/nw_resolution_report_t",
                "doc://com.apple.network/documentation/Network/nw_resolution_report_get_milliseconds(_:)",
                "doc://com.apple.network/documentation/Network/nw_resolution_report_get_source(_:)",
                "doc://com.apple.network/documentation/Network/nw_report_resolution_source_t",
                "doc://com.apple.network/documentation/Network/nw_resolution_report_get_protocol(_:)",
                "doc://com.apple.network/documentation/Network/nw_report_resolution_protocol_t",
                "doc://com.apple.network/documentation/Network/nw_resolution_report_copy_successful_endpoint(_:)",
                "doc://com.apple.network/documentation/Network/nw_resolution_report_copy_preferred_endpoint(_:)",
                "doc://com.apple.network/documentation/Network/nw_resolution_report_get_endpoint_count(_:)",
                "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_resolutions(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_report_resolution_enumerator_t"
              ],
              "title": "Inspecting Resolution"
            },
            {
              "anchor": "Inspecting-Protocol-Handshakes",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_establishment_report_enumerate_protocols(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_report_protocol_enumerator_t"
              ],
              "title": "Inspecting Protocol Handshakes"
            },
            {
              "anchor": "Checking-for-Proxies",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_establishment_report_get_proxy_configured(_:)",
                "doc://com.apple.network/documentation/Network/nw_establishment_report_get_used_proxy(_:)",
                "doc://com.apple.network/documentation/Network/nw_establishment_report_copy_proxy_endpoint(_:)"
              ],
              "title": "Checking for Proxies"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_establishment_report",
                    "text": "NSObject<OS_nw_establishment_report>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_establishment_report_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_get_previous_attempt_count(_:)/title",
          "value": "nw_establishment_report_get_previous_attempt_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_get_previous_attempt_count(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_get_previous_attempt_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/title",
          "value": "nw_browse_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_copy_proxy_endpoint(_:)/title",
          "value": "nw_establishment_report_copy_proxy_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_copy_proxy_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_copy_proxy_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_get_used_proxy(_:)/title",
          "value": "nw_establishment_report_get_used_proxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_get_used_proxy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_get_used_proxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_enumerate_resolution_reports(_:_:)/title",
          "value": "nw_establishment_report_enumerate_resolution_reports"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_enumerate_resolution_reports(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_enumerate_resolution_reports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title",
          "value": "nw_browser_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_get_attempt_started_after_milliseconds(_:)/title",
          "value": "nw_establishment_report_get_attempt_started_after_milliseconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_get_attempt_started_after_milliseconds(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_get_attempt_started_after_milliseconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_get_protocol(_:)/title",
          "value": "nw_resolution_report_get_protocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_get_protocol(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolution_report_get_protocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_enumerate_resolutions(_:_:)/title",
          "value": "nw_establishment_report_enumerate_resolutions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_enumerate_resolutions(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_enumerate_resolutions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/title",
          "value": "nw_connection_path_event_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_path_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_path_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_get_duration_milliseconds(_:)/title",
          "value": "nw_establishment_report_get_duration_milliseconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_get_duration_milliseconds(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_get_duration_milliseconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_t/title",
          "value": "nw_resolution_report_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolution_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolution_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_source_t/title",
          "value": "nw_report_resolution_source_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_source_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_source_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_source_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_source_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/title",
          "value": "nw_connection_group_new_connection_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_new_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_new_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_get_milliseconds(_:)/title",
          "value": "nw_resolution_report_get_milliseconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_get_milliseconds(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolution_report_get_milliseconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/title",
          "value": "nw_browse_result_enumerate_interface_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_enumerate_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_enumerate_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/title",
          "value": "nw_connection_group_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_get_source(_:)/title",
          "value": "nw_resolution_report_get_source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_get_source(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolution_report_get_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_t/title",
          "value": "nw_establishment_report_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/title",
          "value": "nw_connection_group_send_completion_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/title",
          "value": "nw_browser_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_enumerator_t/title",
          "value": "nw_report_resolution_enumerator_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_enumerator_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_enumerator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_enumerator_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_enumerator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_get_proxy_configured(_:)/title",
          "value": "nw_establishment_report_get_proxy_configured"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_get_proxy_configured(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_get_proxy_configured"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/title",
          "value": "nw_connection_boolean_event_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_boolean_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_boolean_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/title",
          "value": "nw_browse_result_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_enumerate_protocols(_:_:)/title",
          "value": "nw_establishment_report_enumerate_protocols"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_establishment_report_enumerate_protocols(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_establishment_report_enumerate_protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_get_endpoint_count(_:)/title",
          "value": "nw_resolution_report_get_endpoint_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_get_endpoint_count(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolution_report_get_endpoint_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_copy_preferred_endpoint(_:)/title",
          "value": "nw_resolution_report_copy_preferred_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_copy_preferred_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolution_report_copy_preferred_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_protocol_t/title",
          "value": "nw_report_resolution_protocol_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_protocol_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_protocol_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_protocol_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_protocol_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_copy_successful_endpoint(_:)/title",
          "value": "nw_resolution_report_copy_successful_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolution_report_copy_successful_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolution_report_copy_successful_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/title",
          "value": "nw_browse_result_change_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/title",
          "value": "nw_browser_browse_results_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_browse_results_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_browse_results_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/title",
          "value": "nw_connection_group_receive_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/title",
          "value": "nw_advertise_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_protocol_enumerator_t/title",
          "value": "nw_report_protocol_enumerator_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_protocol_enumerator_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_protocol_enumerator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_protocol_enumerator_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_protocol_enumerator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_report_enumerator_t/title",
          "value": "nw_report_resolution_report_enumerator_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_report_enumerator_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_report_enumerator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_report_resolution_report_enumerator_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_report_resolution_report_enumerator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_establishment_report/title",
          "value": "OS_nw_establishment_report"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_establishment_report/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_establishment_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_establishment_report/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_establishment_report"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_establishment_report_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_establishment_report_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
