{
  "abstract": [
    {
      "text": "An object you use to send and receive custom Ethernet frames.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_ethernet_channel_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_ethernet_channel_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_ethernet_channel_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_ethernet_channel_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_ethernet_channel",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_ethernet_channel",
              "text": "OS_nw_ethernet_channel"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use Ethernet channels to send and receive custom Ethernet frame types over an interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Creating Ethernet channels requires the ",
              "type": "text"
            },
            {
              "code": "com.apple.developer.networking.custom-protocol",
              "type": "codeVoice"
            },
            {
              "text": " entitlement.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_ethernet_channel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_ethernet_channel"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_ethernet_channel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_ethernet_channel"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_ethernet_channel",
      "type": "topic",
      "url": "/documentation/network/os_nw_ethernet_channel"
    },
    "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework": {
      "abstract": [
        {
          "text": "Build a simple ",
          "type": "text"
        },
        {
          "code": "netcat",
          "type": "codeVoice"
        },
        {
          "text": " tool that establishes network connections and transfers data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing netcat with Network Framework",
      "type": "topic",
      "url": "/documentation/network/implementing-netcat-with-network-framework"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_t": {
      "abstract": [
        {
          "text": "An object you use to browse for available network services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_t": {
      "abstract": [
        {
          "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_t": {
      "abstract": [
        {
          "text": "A bidirectional data connection between a local endpoint and a remote endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_address_t": {
      "abstract": [
        {
          "text": "A 48-bit Ethernet address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_address_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_address_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_address_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_address_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_address_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_cancel(_:)": {
      "abstract": [
        {
          "text": "Unregisters the channel from the interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_cancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
          "text": "nw_ethernet_channel_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_cancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_cancel"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_cancel(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_cancel(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_create(_:_:)": {
      "abstract": [
        {
          "text": "Initializes an Ethernet channel on a specific interface with a custom Ethernet type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_create(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_create"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_create(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_create(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_receive_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers inbound Ethernet frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_receive_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_receive_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_receive_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_receive_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_receive_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sends a single Ethernet frame over a channel to a specific Ethernet address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_send"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
          "text": "nw_ethernet_channel_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "dispatch_data_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_send_completion_t",
          "text": "nw_ethernet_channel_send_completion_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_send"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_send(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_send(_:_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send_completion_t": {
      "abstract": [
        {
          "text": "A handler that indicates when an Ethernet frame has been sent, or if an error was encountered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_send_completion_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send_completion_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_send_completion_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_send_completion_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_send_completion_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_queue(_:_:)": {
      "abstract": [
        {
          "text": "Sets the queue on which all channel events are delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_set_queue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
          "text": "nw_ethernet_channel_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_queue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_set_queue"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_set_queue(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_set_queue(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_receive_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to receive inbound Ethernet frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_set_receive_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
          "text": "nw_ethernet_channel_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_receive_handler_t",
          "text": "nw_ethernet_channel_receive_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_receive_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_set_receive_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_set_receive_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_set_receive_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_state_changed_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to receive channel state updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_set_state_changed_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
          "text": "nw_ethernet_channel_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_state_changed_handler_t",
          "text": "nw_ethernet_channel_state_changed_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_state_changed_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_set_state_changed_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_set_state_changed_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_set_state_changed_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_start(_:)": {
      "abstract": [
        {
          "text": "Starts the process of registering the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ethernet_channel_t",
          "text": "nw_ethernet_channel_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_start(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_start"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_start(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_start(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers Ethernet channel state updates with associated errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t": {
      "abstract": [
        {
          "text": "States indicating whether an Ethernet channel is able to send and receive frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t": {
      "abstract": [
        {
          "text": "An object you use to send and receive custom Ethernet frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_t": {
      "abstract": [
        {
          "text": "An object you use to listen for incoming network connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Managing-Ethernet-Channels",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_create(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_queue(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_start(_:)",
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_cancel(_:)"
      ],
      "title": "Managing Ethernet Channels"
    },
    {
      "anchor": "Handling-State-Updates",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_state_changed_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t"
      ],
      "title": "Handling State Updates"
    },
    {
      "anchor": "Sending-and-Receiving-Ethernet-Frames",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send(_:_:_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send_completion_t",
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_receive_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_receive_handler_t",
        "doc://com.apple.network/documentation/Network/nw_ethernet_address_t"
      ],
      "title": "Sending and Receiving Ethernet Frames"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_ethernet_channel_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Ethernet-Channels",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_create(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_queue(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_start(_:)",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_cancel(_:)"
              ],
              "title": "Managing Ethernet Channels"
            },
            {
              "anchor": "Handling-State-Updates",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_state_changed_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_changed_handler_t",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t"
              ],
              "title": "Handling State Updates"
            },
            {
              "anchor": "Sending-and-Receiving-Ethernet-Frames",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send(_:_:_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_send_completion_t",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_set_receive_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_receive_handler_t",
                "doc://com.apple.network/documentation/Network/nw_ethernet_address_t"
              ],
              "title": "Sending and Receiving Ethernet Frames"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Connections-and-Listeners",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework",
                "doc://com.apple.network/documentation/Network/nw_connection_t",
                "doc://com.apple.network/documentation/Network/nw_listener_t",
                "doc://com.apple.network/documentation/Network/nw_browser_t",
                "doc://com.apple.network/documentation/Network/nw_connection_group_t"
              ],
              "title": "Connections and Listeners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_ethernet_channel",
                    "text": "NSObject<OS_nw_ethernet_channel>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_ethernet_channel_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/title",
          "value": "nw_connection_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title",
          "value": "nw_browser_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_create(_:_:)/title",
          "value": "nw_ethernet_channel_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_create(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_send_completion_t/title",
          "value": "nw_ethernet_channel_send_completion_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_send_completion_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_send_completion_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/title",
          "value": "nw_ethernet_channel_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_send(_:_:_:_:_:)/title",
          "value": "nw_ethernet_channel_send"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_send(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_send"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_changed_handler_t/title",
          "value": "nw_ethernet_channel_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_address_t/title",
          "value": "nw_ethernet_address_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_address_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_address_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_address_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_address_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_start(_:)/title",
          "value": "nw_ethernet_channel_start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_start(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_set_state_changed_handler(_:_:)/title",
          "value": "nw_ethernet_channel_set_state_changed_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_set_state_changed_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_set_state_changed_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_cancel(_:)/title",
          "value": "nw_ethernet_channel_cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_cancel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_receive_handler_t/title",
          "value": "nw_ethernet_channel_receive_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_receive_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_receive_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_set_queue(_:_:)/title",
          "value": "nw_ethernet_channel_set_queue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_set_queue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_set_queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_set_receive_handler(_:_:)/title",
          "value": "nw_ethernet_channel_set_receive_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_set_receive_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_set_receive_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_t/title",
          "value": "nw_ethernet_channel_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ethernet_channel/title",
          "value": "OS_nw_ethernet_channel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ethernet_channel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_ethernet_channel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ethernet_channel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_ethernet_channel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/title",
          "value": "nw_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_ethernet_channel_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_ethernet_channel_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
