{
  "abstract": [
    {
      "text": "Dynamically adds another protocol that will run above your protocol after your protocol calls ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_mark_ready(_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_framer_prepend_application_protocol(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_framer_prepend_application_protocol",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_framer_prepend_application_protocol"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_framer_t",
        "text": "nw_framer_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_protocol_options_t",
        "text": "nw_protocol_options_t"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_framer_prepend_application_protocol"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_framer_prepend_application_protocol(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_framer_prepend_application_protocol"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "framer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_framer_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_framer_t",
              "text": "nw_framer_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "protocol_options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_options_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_protocol_options_t",
              "text": "nw_protocol_options_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_cleanup_handler_t": {
      "abstract": [
        {
          "text": "A handler that tells your protocol to clean up all allocations before being deallocated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_cleanup_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_cleanup_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_cleanup_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_cleanup_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_cleanup_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_mark_failed_with_error(_:_:)": {
      "abstract": [
        {
          "text": "Indicates to a connection that your protocol has encountered an error, or has gracefully closed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_mark_failed_with_error"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_mark_failed_with_error(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_mark_failed_with_error"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_mark_failed_with_error(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_mark_failed_with_error(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_mark_ready(_:)": {
      "abstract": [
        {
          "text": "Indicates to a connection that your protocol’s handshake is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_mark_ready"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_mark_ready(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_mark_ready"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_mark_ready(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_mark_ready(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_prepend_application_protocol(_:_:)": {
      "abstract": [
        {
          "text": "Dynamically adds another protocol that will run above your protocol after your protocol calls ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.network/documentation/Network/nw_framer_mark_ready(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_prepend_application_protocol"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_prepend_application_protocol(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_prepend_application_protocol"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_prepend_application_protocol(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_prepend_application_protocol(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_set_cleanup_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a block to handle the final cleanup of allocations made by your protocol instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_set_cleanup_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_cleanup_handler_t",
          "text": "nw_framer_cleanup_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_set_cleanup_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_set_cleanup_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_set_cleanup_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_set_cleanup_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_set_stop_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a block to handle when the connection is being closed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_set_stop_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_stop_handler_t",
          "text": "nw_framer_stop_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_set_stop_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_set_stop_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_set_stop_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_set_stop_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_stop_handler_t": {
      "abstract": [
        {
          "text": "A handler that requests that your protocol send any final messages to close the connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_stop_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_stop_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_stop_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_stop_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_stop_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_t": {
      "abstract": [
        {
          "text": "An object that represents a single instance of your custom protocol running in a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_t"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_options_t": {
      "abstract": [
        {
          "text": "The abstract superclass for configuring the options of a network protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_options_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_options_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_options_t"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_options_t",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_options_t"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Instance-Lifetime",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_framer_mark_ready(_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_mark_failed_with_error(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_set_stop_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_stop_handler_t",
        "doc://com.apple.network/documentation/Network/nw_framer_set_cleanup_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_cleanup_handler_t"
      ],
      "title": "Managing Instance Lifetime"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_framer_prepend_application_protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_prepend_application_protocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Instance-Lifetime",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_framer_mark_ready(_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_mark_failed_with_error(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_set_stop_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_stop_handler_t",
                "doc://com.apple.network/documentation/Network/nw_framer_set_cleanup_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_cleanup_handler_t"
              ],
              "title": "Managing Instance Lifetime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:b",
                    "text": "bool"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_framer_prepend_application_protocol"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_framer_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_framer_t",
                    "text": "nw_framer_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "framer"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_options_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_protocol_options_t",
                    "text": "nw_protocol_options_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "protocol_options"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_options_t/title",
          "value": "nw_protocol_options_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_options_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_options_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_mark_failed_with_error(_:_:)/title",
          "value": "nw_framer_mark_failed_with_error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_mark_failed_with_error(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_mark_failed_with_error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_set_cleanup_handler(_:_:)/title",
          "value": "nw_framer_set_cleanup_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_set_cleanup_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_set_cleanup_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_mark_ready(_:)/title",
          "value": "nw_framer_mark_ready"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_mark_ready(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_mark_ready"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_cleanup_handler_t/title",
          "value": "nw_framer_cleanup_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_cleanup_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_cleanup_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_cleanup_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_cleanup_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_t/title",
          "value": "nw_framer_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_stop_handler_t/title",
          "value": "nw_framer_stop_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_stop_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_stop_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_stop_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_stop_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_set_stop_handler(_:_:)/title",
          "value": "nw_framer_set_stop_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_set_stop_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_set_stop_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_prepend_application_protocol(_:_:)/title",
          "value": "nw_framer_prepend_application_protocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_prepend_application_protocol(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_prepend_application_protocol"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_framer_prepend_application_protocol(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_framer_prepend_application_protocol(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
