{
  "abstract": [
    {
      "text": "Accesses the local endpoint of the connection in which your protocol is running.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_framer_copy_local_endpoint(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_framer_copy_local_endpoint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_framer_copy_local_endpoint"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_framer_t",
        "text": "nw_framer_t"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_endpoint_t",
        "text": "nw_endpoint_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_framer_copy_local_endpoint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_framer_copy_local_endpoint(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_framer_copy_local_endpoint"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "framer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_framer_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_framer_t",
              "text": "nw_framer_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_endpoint_t",
              "text": "nw_endpoint_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_t": {
      "abstract": [
        {
          "text": "A local or remote endpoint in a network connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_t"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_t",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_t"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_copy_local_endpoint(_:)": {
      "abstract": [
        {
          "text": "Accesses the local endpoint of the connection in which your protocol is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_copy_local_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_copy_local_endpoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_copy_local_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_copy_local_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_copy_local_endpoint(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_copy_parameters(_:)": {
      "abstract": [
        {
          "text": "Accesses the parameters of the connection in which your protocol is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_copy_parameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_copy_parameters(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_copy_parameters"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_copy_parameters(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_copy_parameters(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_copy_remote_endpoint(_:)": {
      "abstract": [
        {
          "text": "Accesses the remote endpoint of the connection in which your protocol is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_copy_remote_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_copy_remote_endpoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_copy_remote_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_copy_remote_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_copy_remote_endpoint(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_t": {
      "abstract": [
        {
          "text": "An object that represents a single instance of your custom protocol running in a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_framer_copy_remote_endpoint(_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_copy_parameters(_:)"
      ],
      "title": "Inspecting Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_framer_copy_local_endpoint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_copy_local_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_framer_copy_remote_endpoint(_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_copy_parameters(_:)"
              ],
              "title": "Inspecting Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_endpoint_t",
                    "text": "nw_endpoint_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_framer_copy_local_endpoint"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_framer_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_framer_t",
                    "text": "nw_framer_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "framer"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_copy_remote_endpoint(_:)/title",
          "value": "nw_framer_copy_remote_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_copy_remote_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_copy_remote_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_t/title",
          "value": "nw_framer_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_copy_local_endpoint(_:)/title",
          "value": "nw_framer_copy_local_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_copy_local_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_copy_local_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/title",
          "value": "nw_endpoint_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_copy_parameters(_:)/title",
          "value": "nw_framer_copy_parameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_copy_parameters(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_copy_parameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_framer_copy_local_endpoint(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_framer_copy_local_endpoint(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
