{
  "abstract": [
    {
      "text": "Requests that a block be executed on the connection’s internal scheduling context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_framer_async(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_framer_async",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_framer_async"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_framer_t",
        "text": "nw_framer_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_framer_block_t",
        "text": "nw_framer_block_t"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_framer_async"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_framer_async(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_framer_async"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "framer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_framer_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_framer_t",
              "text": "nw_framer_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "async_block"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_framer_block_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_framer_block_t",
              "text": "nw_framer_block_t"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You should call this if you need to call any framer functions but are in another scheduling context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER": {
      "abstract": [
        {
          "text": "A sentinel value that indicates that no wakeup should be delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NW_FRAMER_WAKEUP_TIME_FOREVER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NW_FRAMER_WAKEUP_TIME_FOREVER"
        }
      ],
      "role": "symbol",
      "title": "NW_FRAMER_WAKEUP_TIME_FOREVER",
      "type": "topic",
      "url": "/documentation/network/nw_framer_wakeup_time_forever"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_async(_:_:)": {
      "abstract": [
        {
          "text": "Requests that a block be executed on the connection’s internal scheduling context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_async"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_block_t",
          "text": "nw_framer_block_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_async(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_async"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_async(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_async(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_block_t": {
      "abstract": [
        {
          "text": "A block to be invoked asynchronously on your framer protocol’s scheduling context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_block_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_block_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_block_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_block_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_block_t"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_schedule_wakeup(_:_:)": {
      "abstract": [
        {
          "text": "Requests that the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.network/documentation/Network/nw_framer_wakeup_handler_t",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " be called on your protocol at a specific time in the future.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_schedule_wakeup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_schedule_wakeup(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_schedule_wakeup"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_schedule_wakeup(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_schedule_wakeup(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_set_wakeup_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to receive scheduled wakeup events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_set_wakeup_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_wakeup_handler_t",
          "text": "nw_framer_wakeup_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_set_wakeup_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_set_wakeup_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_set_wakeup_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_set_wakeup_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_t": {
      "abstract": [
        {
          "text": "An object that represents a single instance of your custom protocol running in a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_t"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_wakeup_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers a scheduled wakeup event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_wakeup_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_wakeup_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_wakeup_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_wakeup_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_wakeup_handler_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Asynchronous-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_framer_schedule_wakeup(_:_:)",
        "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER",
        "doc://com.apple.network/documentation/Network/nw_framer_set_wakeup_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_wakeup_handler_t",
        "doc://com.apple.network/documentation/Network/nw_framer_block_t"
      ],
      "title": "Handling Asynchronous Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_framer_async"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_async"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Asynchronous-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_framer_schedule_wakeup(_:_:)",
                "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER",
                "doc://com.apple.network/documentation/Network/nw_framer_set_wakeup_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_wakeup_handler_t",
                "doc://com.apple.network/documentation/Network/nw_framer_block_t"
              ],
              "title": "Handling Asynchronous Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_framer_async"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_framer_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_framer_t",
                    "text": "nw_framer_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "framer"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_framer_block_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_framer_block_t",
                    "text": "nw_framer_block_t"
                  },
                  {
                    "kind": "internalParam",
                    "text": "async_block"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_block_t/title",
          "value": "nw_framer_block_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_block_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_block_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_t/title",
          "value": "nw_framer_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_FRAMER_WAKEUP_TIME_FOREVER/title",
          "value": "NW_FRAMER_WAKEUP_TIME_FOREVER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_FRAMER_WAKEUP_TIME_FOREVER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NW_FRAMER_WAKEUP_TIME_FOREVER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_set_wakeup_handler(_:_:)/title",
          "value": "nw_framer_set_wakeup_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_set_wakeup_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_set_wakeup_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_async(_:_:)/title",
          "value": "nw_framer_async"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_async(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_async"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_wakeup_handler_t/title",
          "value": "nw_framer_wakeup_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_wakeup_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_wakeup_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_wakeup_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_wakeup_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_schedule_wakeup(_:_:)/title",
          "value": "nw_framer_schedule_wakeup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_schedule_wakeup(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_schedule_wakeup"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_framer_async(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_framer_async(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
