{
  "abstract": [
    {
      "text": "Sets an NSObject value to be stored in a framer message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_framer_message_set_object_value(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_framer_message_set_object_value",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_framer_message_set_object_value"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_framer_message_t",
        "text": "nw_framer_message_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5CChara",
        "text": "CChar"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_framer_message_set_object_value"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_framer_message_set_object_value(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_framer_message_set_object_value"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "message"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_framer_message_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_framer_message_t",
              "text": "nw_framer_message_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_message_access_value(_:_:_:)": {
      "abstract": [
        {
          "text": "Accesses a custom value stored in a framer message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_message_access_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_message_t",
          "text": "nw_framer_message_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_message_access_value(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_message_access_value"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_message_access_value(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_message_access_value(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_message_copy_object_value(_:_:)": {
      "abstract": [
        {
          "text": "Accesses an NSObject value stored in a framer message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_message_copy_object_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_message_t",
          "text": "nw_framer_message_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_message_copy_object_value(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_message_copy_object_value"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_message_copy_object_value(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_message_copy_object_value(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_message_create(_:)": {
      "abstract": [
        {
          "text": "Initializes an empty message from within a framer implementation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_message_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_t",
          "text": "nw_framer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_message_t",
          "text": "nw_framer_message_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_message_create(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_message_create"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_message_create(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_message_create(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_message_dispose_value_t": {
      "abstract": [
        {
          "text": "A handler that’s invoked when your custom value needs to be released due to a message being released or the value being replaced.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_message_dispose_value_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_message_dispose_value_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_message_dispose_value_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_message_dispose_value_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_message_dispose_value_t"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_message_set_object_value(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets an NSObject value to be stored in a framer message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_message_set_object_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_message_t",
          "text": "nw_framer_message_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_message_set_object_value(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_message_set_object_value"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_message_set_object_value(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_message_set_object_value(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_message_set_value(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a value to be stored in a framer message, with a completion to call to disposed the stored value when the message is released.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_message_set_value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_message_t",
          "text": "nw_framer_message_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_message_dispose_value_t",
          "text": "nw_framer_message_dispose_value_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_message_set_value(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_message_set_value"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_message_set_value(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_message_set_value(_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_message_t": {
      "abstract": [
        {
          "text": "A message for a custom protocol, in which you can store arbitrary key-value pairs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_message_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_message_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_message_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_message_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_message_t"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_protocol_create_message(_:)": {
      "abstract": [
        {
          "text": "Initializes an empty message for a custom framer definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_protocol_create_message"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_framer_message_t",
          "text": "nw_framer_message_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_protocol_create_message(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_protocol_create_message"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_protocol_create_message(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_framer_protocol_create_message(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_framer_message(_:)": {
      "abstract": [
        {
          "text": "Checks if a metadata object represents a custom framer protocol message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_framer_message"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_framer_message(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_framer_message"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_metadata_is_framer_message(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_metadata_is_framer_message(_:)"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C ‘char’ type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-Framer-Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_framer_message_t",
        "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_framer_message(_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_protocol_create_message(_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_message_create(_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_message_set_value(_:_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_message_dispose_value_t",
        "doc://com.apple.network/documentation/Network/nw_framer_message_access_value(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_framer_message_copy_object_value(_:_:)"
      ],
      "title": "Customizing Framer Messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_framer_message_set_object_value"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_message_set_object_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-Framer-Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_framer_message_t",
                "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_framer_message(_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_protocol_create_message(_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_message_create(_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_message_set_value(_:_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_message_dispose_value_t",
                "doc://com.apple.network/documentation/Network/nw_framer_message_access_value(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_framer_message_copy_object_value(_:_:)"
              ],
              "title": "Customizing Framer Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_framer_message_set_object_value"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_framer_message_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_framer_message_t",
                    "text": "nw_framer_message_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "message"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:C",
                    "text": "char"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "key"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_t/title",
          "value": "nw_framer_message_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_message_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_message_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_create(_:)/title",
          "value": "nw_framer_message_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_create(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_message_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_access_value(_:_:_:)/title",
          "value": "nw_framer_message_access_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_access_value(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_message_access_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_set_value(_:_:_:_:)/title",
          "value": "nw_framer_message_set_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_set_value(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_message_set_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_framer_message(_:)/title",
          "value": "nw_protocol_metadata_is_framer_message"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_framer_message(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_metadata_is_framer_message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_set_object_value(_:_:_:)/title",
          "value": "nw_framer_message_set_object_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_set_object_value(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_message_set_object_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_protocol_create_message(_:)/title",
          "value": "nw_framer_protocol_create_message"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_protocol_create_message(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_protocol_create_message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_copy_object_value(_:_:)/title",
          "value": "nw_framer_message_copy_object_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_copy_object_value(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_message_copy_object_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_dispose_value_t/title",
          "value": "nw_framer_message_dispose_value_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_dispose_value_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_message_dispose_value_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_message_dispose_value_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_message_dispose_value_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_framer_message_set_object_value(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_framer_message_set_object_value(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
