{
  "abstract": [
    {
      "text": "Configures a connection to deliver receive timestamps for IP packets.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_ip_options_set_calculate_receive_time(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_ip_options_set_calculate_receive_time",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_ip_options_set_calculate_receive_time"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_protocol_options_t",
        "text": "nw_protocol_options_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_ip_options_set_calculate_receive_time"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_ip_options_set_calculate_receive_time(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_calculate_receive_time"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_options_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_protocol_options_t",
              "text": "nw_protocol_options_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "calculate_receive_time"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t": {
      "abstract": [
        {
          "text": "Types of local addresses that can be selected, such as temporary or stable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_local_address_preference_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_local_address_preference_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_local_address_preference_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_local_address_preference_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)": {
      "abstract": [
        {
          "text": "Access the time at which a packet was received, in nanoseconds, based on ",
          "type": "text"
        },
        {
          "code": "CLOCK_MONOTONIC_RAW",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_receive_time"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_receive_time"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_get_receive_time(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_get_receive_time(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_calculate_receive_time(_:_:)": {
      "abstract": [
        {
          "text": "Configures a connection to deliver receive timestamps for IP packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_calculate_receive_time"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_calculate_receive_time(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_calculate_receive_time"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_calculate_receive_time(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_calculate_receive_time(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_disable_fragmentation(_:_:)": {
      "abstract": [
        {
          "text": "Configures a connection to disable fragmentation on outbound packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_disable_fragmentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_disable_fragmentation(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_disable_fragmentation"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_disable_fragmentation(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_disable_fragmentation(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_hop_limit(_:_:)": {
      "abstract": [
        {
          "text": "Configures the default hop limit for packets generated by a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_hop_limit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_hop_limit(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_hop_limit"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_hop_limit(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_hop_limit(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_local_address_preference(_:_:)": {
      "abstract": [
        {
          "text": "Configures a connection to prefer certain types of local addresses, such as temporary or stable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_local_address_preference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_local_address_preference_t",
          "text": "nw_ip_local_address_preference_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_local_address_preference(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_local_address_preference"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_local_address_preference(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_local_address_preference(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_use_minimum_mtu(_:_:)": {
      "abstract": [
        {
          "text": "Configures a connection to use the minimum MTU value, which is 1280 bytes for IPv6.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_use_minimum_mtu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_use_minimum_mtu(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_use_minimum_mtu"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_use_minimum_mtu(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_use_minimum_mtu(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_options_set_version(_:_:)": {
      "abstract": [
        {
          "text": "Sets a required IP version to disable all other versions for a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_version"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_version_t",
          "text": "nw_ip_version_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_options_set_version(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_options_set_version"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_options_set_version(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_options_set_version(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_version_t": {
      "abstract": [
        {
          "text": "IP versions to require on connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_version_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_version_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_version_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_version_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_version_t"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_copy_ip_definition()": {
      "abstract": [
        {
          "text": "Accesses the system definition of the Internet Protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_ip_definition"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_copy_ip_definition()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_ip_definition"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_copy_ip_definition()",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_copy_ip_definition()"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_options_t": {
      "abstract": [
        {
          "text": "The abstract superclass for configuring the options of a network protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_options_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_options_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_options_t"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_options_t",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_options_t"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Configuring-IP-Connections",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_copy_ip_definition()",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_version(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_version_t",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_hop_limit(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_use_minimum_mtu(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_disable_fragmentation(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_options_set_local_address_preference(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t"
      ],
      "title": "Configuring IP Connections"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_ip_options_set_calculate_receive_time"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_calculate_receive_time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Configuring-IP-Connections",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_protocol_copy_ip_definition()",
                "doc://com.apple.network/documentation/Network/nw_ip_options_set_version(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ip_version_t",
                "doc://com.apple.network/documentation/Network/nw_ip_options_set_hop_limit(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ip_options_set_use_minimum_mtu(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ip_options_set_disable_fragmentation(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ip_options_set_local_address_preference(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t"
              ],
              "title": "Configuring IP Connections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_ip_options_set_calculate_receive_time"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_options_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_protocol_options_t",
                    "text": "nw_protocol_options_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:b",
                    "text": "bool"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "calculate_receive_time"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_local_address_preference(_:_:)/title",
          "value": "nw_ip_options_set_local_address_preference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_local_address_preference(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_local_address_preference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_ip_definition()/title",
          "value": "nw_protocol_copy_ip_definition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_ip_definition()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_copy_ip_definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/title",
          "value": "nw_ip_version_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_disable_fragmentation(_:_:)/title",
          "value": "nw_ip_options_set_disable_fragmentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_disable_fragmentation(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_disable_fragmentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_calculate_receive_time(_:_:)/title",
          "value": "nw_ip_options_set_calculate_receive_time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_calculate_receive_time(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_calculate_receive_time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_receive_time(_:)/title",
          "value": "nw_ip_metadata_get_receive_time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_receive_time(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_get_receive_time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_options_t/title",
          "value": "nw_protocol_options_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_options_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_options_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_hop_limit(_:_:)/title",
          "value": "nw_ip_options_set_hop_limit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_hop_limit(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_hop_limit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/title",
          "value": "nw_ip_local_address_preference_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_local_address_preference_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_local_address_preference_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_use_minimum_mtu(_:_:)/title",
          "value": "nw_ip_options_set_use_minimum_mtu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_use_minimum_mtu(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_use_minimum_mtu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_version(_:_:)/title",
          "value": "nw_ip_options_set_version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_options_set_version(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_options_set_version"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_ip_options_set_calculate_receive_time(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_ip_options_set_calculate_receive_time(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
