{
  "abstract": [
    {
      "text": "Flag values for Explicit Congestion Notifications in IP packets.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@nw_ip_ecn_flag_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_ip_ecn_flag_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_ip_ecn_flag_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "nw_ip_ecn_flag_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a browser is able to discover services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_state_t": {
      "abstract": [
        {
          "text": "States that indicate whether you can use a connection group to send and receive messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a connection can be used to send and receive data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a data transfer report is collected yet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_data_transfer_report_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_data_transfer_report_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_data_transfer_report_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_type_t": {
      "abstract": [
        {
          "text": "The type of a network endpoint, such as a host or a service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_type_t"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_type_t",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_type_t"
    },
    "doc://com.apple.network/documentation/Network/nw_error_domain_t": {
      "abstract": [
        {
          "text": "The error domain for errors used by the Network framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_error_domain_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_error_domain_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_error_domain_t"
        }
      ],
      "role": "symbol",
      "title": "nw_error_domain_t",
      "type": "topic",
      "url": "/documentation/network/nw_error_domain_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t": {
      "abstract": [
        {
          "text": "States indicating whether an Ethernet channel is able to send and receive frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_framer_start_result_t": {
      "abstract": [
        {
          "text": "Results that you send to indicate the disposition of your protocol after the start handler is invoked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_framer_start_result_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_framer_start_result_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_framer_start_result_t"
        }
      ],
      "role": "symbol",
      "title": "nw_framer_start_result_t",
      "type": "topic",
      "url": "/documentation/network/nw_framer_start_result_t"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_type_t": {
      "abstract": [
        {
          "text": "Types of network interfaces, based on their link layer media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_type_t"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_type_t",
      "type": "topic",
      "url": "/documentation/network/nw_interface_type_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ce": {
      "abstract": [
        {
          "text": "Congestion Experienced.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_ce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_ecn_flag_t",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_ce"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_ecn_flag_ce",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_ce"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ect_0": {
      "abstract": [
        {
          "text": "ECN Capable Transport (flag 0).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_ect_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_ecn_flag_t",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ect_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_ect_0"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_ecn_flag_ect_0",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_ect_0"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ect_1": {
      "abstract": [
        {
          "text": "ECN Capable Transport (flag 1).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_ect_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_ecn_flag_t",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ect_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_ect_1"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_ecn_flag_ect_1",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_ect_1"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_non_ect": {
      "abstract": [
        {
          "text": "Non-ECN Capable Transport.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_non_ect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_ecn_flag_t",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_non_ect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_non_ect"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_ecn_flag_non_ect",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_non_ect"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t": {
      "abstract": [
        {
          "text": "Flag values for Explicit Congestion Notifications in IP packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_ecn_flag_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_t/init(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_t/init(rawvalue:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_t/rawvalue"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t": {
      "abstract": [
        {
          "text": "Types of local addresses that can be selected, such as temporary or stable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_local_address_preference_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_local_address_preference_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_local_address_preference_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_local_address_preference_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_version_t": {
      "abstract": [
        {
          "text": "IP versions to require on connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_version_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_version_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_version_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_version_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_version_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a listener is able to accept incoming connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_multipath_service_t": {
      "abstract": [
        {
          "text": "Modes in which a connection can support multipath protocols.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_multipath_service_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_multipath_service_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_multipath_service_t"
        }
      ],
      "role": "symbol",
      "title": "nw_multipath_service_t",
      "type": "topic",
      "url": "/documentation/network/nw_multipath_service_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t": {
      "abstract": [
        {
          "text": "Options for configuring how expired DNS answers should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_expired_dns_behavior_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_expired_dns_behavior_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_expired_dns_behavior_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_expired_dns_behavior_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_status_t": {
      "abstract": [
        {
          "text": "Status values indicating whether a path can be used by connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_status_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_status_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_status_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_status_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_status_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "C-Network-Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_connection_group_state_t",
        "doc://com.apple.network/documentation/Network/nw_browser_state_t",
        "doc://com.apple.network/documentation/Network/nw_connection_state_t",
        "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t",
        "doc://com.apple.network/documentation/Network/nw_endpoint_type_t",
        "doc://com.apple.network/documentation/Network/nw_error_domain_t",
        "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t",
        "doc://com.apple.network/documentation/Network/nw_framer_start_result_t",
        "doc://com.apple.network/documentation/Network/nw_interface_type_t",
        "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t",
        "doc://com.apple.network/documentation/Network/nw_ip_version_t",
        "doc://com.apple.network/documentation/Network/nw_listener_state_t",
        "doc://com.apple.network/documentation/Network/nw_multipath_service_t",
        "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t",
        "doc://com.apple.network/documentation/Network/nw_path_status_t"
      ],
      "title": "C Network Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "ECN-Flags",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_non_ect",
        "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ect_0",
        "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ect_1",
        "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ce"
      ],
      "title": "ECN Flags"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t/init(_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t/rawValue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_ip_ecn_flag_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "ECN-Flags",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_non_ect",
                "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ect_0",
                "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ect_1",
                "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_ce"
              ],
              "title": "ECN Flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "C-Network-Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_connection_group_state_t",
                "doc://com.apple.network/documentation/Network/nw_browser_state_t",
                "doc://com.apple.network/documentation/Network/nw_connection_state_t",
                "doc://com.apple.network/documentation/Network/nw_data_transfer_report_state_t",
                "doc://com.apple.network/documentation/Network/nw_endpoint_type_t",
                "doc://com.apple.network/documentation/Network/nw_error_domain_t",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_state_t",
                "doc://com.apple.network/documentation/Network/nw_framer_start_result_t",
                "doc://com.apple.network/documentation/Network/nw_interface_type_t",
                "doc://com.apple.network/documentation/Network/nw_ip_local_address_preference_t",
                "doc://com.apple.network/documentation/Network/nw_ip_version_t",
                "doc://com.apple.network/documentation/Network/nw_listener_state_t",
                "doc://com.apple.network/documentation/Network/nw_multipath_service_t",
                "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t",
                "doc://com.apple.network/documentation/Network/nw_path_status_t"
              ],
              "title": "C Network Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_ip_ecn_flag_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_type_t/title",
          "value": "nw_endpoint_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_state_t/title",
          "value": "nw_data_transfer_report_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_data_transfer_report_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_data_transfer_report_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_service_t/title",
          "value": "nw_multipath_service_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_service_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_service_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_service_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_service_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_ect_0/title",
          "value": "nw_ip_ecn_flag_ect_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_ect_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_ect_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_start_result_t/title",
          "value": "nw_framer_start_result_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_start_result_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_start_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_framer_start_result_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_framer_start_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_ect_1/title",
          "value": "nw_ip_ecn_flag_ect_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_ect_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_ect_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_t/title",
          "value": "nw_browser_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_t/title",
          "value": "nw_parameters_expired_dns_behavior_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_expired_dns_behavior_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_expired_dns_behavior_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_ce/title",
          "value": "nw_ip_ecn_flag_ce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_ce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_ce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_non_ect/title",
          "value": "nw_ip_ecn_flag_non_ect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_non_ect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_non_ect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/title",
          "value": "nw_ip_ecn_flag_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/title",
          "value": "nw_path_status_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/title",
          "value": "nw_ip_version_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_version_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_t/title",
          "value": "nw_connection_group_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_t/title",
          "value": "nw_listener_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_t/title",
          "value": "nw_ethernet_channel_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_t/title",
          "value": "nw_connection_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_error_domain_t/title",
          "value": "nw_error_domain_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_error_domain_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_error_domain_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_error_domain_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_error_domain_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_type_t/title",
          "value": "nw_interface_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/title",
          "value": "nw_ip_local_address_preference_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_local_address_preference_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_local_address_preference_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_local_address_preference_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_ip_ecn_flag_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_ip_ecn_flag_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
