{
  "abstract": [
    {
      "text": "Initializes an IP packet configuration with default settings.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_ip_create_metadata()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_ip_create_metadata",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_ip_create_metadata"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
        "text": "nw_protocol_metadata_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_ip_create_metadata"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_ip_create_metadata()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_ip_create_metadata"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_metadata_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
              "text": "nw_protocol_metadata_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_create_metadata()": {
      "abstract": [
        {
          "text": "Initializes an IP packet configuration with default settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_create_metadata"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_create_metadata()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_create_metadata"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_create_metadata()",
      "type": "topic",
      "url": "/documentation/network/nw_ip_create_metadata()"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t": {
      "abstract": [
        {
          "text": "Flag values for Explicit Congestion Notifications in IP packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_ecn_flag_t",
      "type": "topic",
      "url": "/documentation/network/nw_ip_ecn_flag_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_ecn_flag(_:)": {
      "abstract": [
        {
          "text": "Checks the Explicit Congestion Notification flag value received on an IP packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_ecn_flag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_ecn_flag_t",
          "text": "nw_ip_ecn_flag_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_ecn_flag(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_ecn_flag"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_get_ecn_flag(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_get_ecn_flag(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)": {
      "abstract": [
        {
          "text": "Access the time at which a packet was received, in nanoseconds, based on ",
          "type": "text"
        },
        {
          "code": "CLOCK_MONOTONIC_RAW",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_receive_time"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_receive_time"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_get_receive_time(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_get_receive_time(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_service_class(_:)": {
      "abstract": [
        {
          "text": "Accesses a specific service class to mark on an IP packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_service_class"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_service_class(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_get_service_class"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_get_service_class(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_get_service_class(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_ecn_flag(_:_:)": {
      "abstract": [
        {
          "text": "Sets a specific Explicit Congestion Notification flag value to set on an IP packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_set_ecn_flag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ip_ecn_flag_t",
          "text": "nw_ip_ecn_flag_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_ecn_flag(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_set_ecn_flag"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_set_ecn_flag(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_set_ecn_flag(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_service_class(_:_:)": {
      "abstract": [
        {
          "text": "Sets a specific service class to mark on an IP packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_set_service_class"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_service_class(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ip_metadata_set_service_class"
        }
      ],
      "role": "symbol",
      "title": "nw_ip_metadata_set_service_class(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ip_metadata_set_service_class(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_ip(_:)": {
      "abstract": [
        {
          "text": "Checks whether a metadata object represents an IP packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_ip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_ip(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_ip"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_metadata_is_ip(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_metadata_is_ip(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_metadata_t": {
      "abstract": [
        {
          "text": "The abstract superclass for specifying metadata about a network protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_metadata_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_t"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_metadata_t",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_metadata_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-IP-Packets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_ip(_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_ecn_flag(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_ecn_flag(_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t",
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_service_class(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_service_class(_:)",
        "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)"
      ],
      "title": "Handling IP Packets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_ip_create_metadata"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_create_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-IP-Packets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_ip(_:)",
                "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_ecn_flag(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_ecn_flag(_:)",
                "doc://com.apple.network/documentation/Network/nw_ip_ecn_flag_t",
                "doc://com.apple.network/documentation/Network/nw_ip_metadata_set_service_class(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_service_class(_:)",
                "doc://com.apple.network/documentation/Network/nw_ip_metadata_get_receive_time(_:)"
              ],
              "title": "Handling IP Packets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_metadata_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
                    "text": "nw_protocol_metadata_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_ip_create_metadata"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_ip(_:)/title",
          "value": "nw_protocol_metadata_is_ip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_ip(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_metadata_is_ip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_service_class(_:)/title",
          "value": "nw_ip_metadata_get_service_class"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_service_class(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_get_service_class"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_ecn_flag(_:)/title",
          "value": "nw_ip_metadata_get_ecn_flag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_ecn_flag(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_get_ecn_flag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/title",
          "value": "nw_ip_ecn_flag_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_ecn_flag_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_ecn_flag_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_receive_time(_:)/title",
          "value": "nw_ip_metadata_get_receive_time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_get_receive_time(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_get_receive_time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_create_metadata()/title",
          "value": "nw_ip_create_metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_create_metadata()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_create_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_t/title",
          "value": "nw_protocol_metadata_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_metadata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_metadata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_set_service_class(_:_:)/title",
          "value": "nw_ip_metadata_set_service_class"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_set_service_class(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_set_service_class"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_set_ecn_flag(_:_:)/title",
          "value": "nw_ip_metadata_set_ecn_flag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ip_metadata_set_ecn_flag(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ip_metadata_set_ecn_flag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_ip_create_metadata()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_ip_create_metadata()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
