{
  "abstract": [
    {
      "text": "An interface that a network connection uses to send and receive data.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_interface_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_interface_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_interface_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_interface_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_interface_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_interface",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_interface",
              "text": "OS_nw_interface"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_interface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_interface"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_interface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_interface"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_interface",
      "type": "topic",
      "url": "/documentation/network/os_nw_interface"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_get_index(_:)": {
      "abstract": [
        {
          "text": "Accesses the system interface index associated with the interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_get_index"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_get_index(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_get_index"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_get_index(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_interface_get_index(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_get_name(_:)": {
      "abstract": [
        {
          "text": "Accesses the name of the interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_get_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_get_name(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_get_name"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_get_name(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_interface_get_name(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_get_type(_:)": {
      "abstract": [
        {
          "text": "Accesses the type of the interface, such as Wi-Fi or Loopback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_get_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_type_t",
          "text": "nw_interface_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_get_type(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_get_type"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_get_type(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_interface_get_type(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_t": {
      "abstract": [
        {
          "text": "An interface that a network connection uses to send and receive data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_t"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_t",
      "type": "topic",
      "url": "/documentation/network/nw_interface_t"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_type_t": {
      "abstract": [
        {
          "text": "Types of network interfaces, based on their link layer media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_type_t"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_type_t",
      "type": "topic",
      "url": "/documentation/network/nw_interface_type_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_t": {
      "abstract": [
        {
          "text": "An observer that you use to monitor and react to network changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_t": {
      "abstract": [
        {
          "text": "An object that contains information about the properties of the network that a connection uses, or that are available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Network-Interface-Types",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_interface_type_t"
      ],
      "title": "Network Interface Types"
    },
    {
      "anchor": "Inspecting-Interfaces",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_interface_get_type(_:)",
        "doc://com.apple.network/documentation/Network/nw_interface_get_name(_:)",
        "doc://com.apple.network/documentation/Network/nw_interface_get_index(_:)"
      ],
      "title": "Inspecting Interfaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_interface_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Network-Interface-Types",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_interface_type_t"
              ],
              "title": "Network Interface Types"
            },
            {
              "anchor": "Inspecting-Interfaces",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_interface_get_type(_:)",
                "doc://com.apple.network/documentation/Network/nw_interface_get_name(_:)",
                "doc://com.apple.network/documentation/Network/nw_interface_get_index(_:)"
              ],
              "title": "Inspecting Interfaces"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Paths-and-Interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_t",
                "doc://com.apple.network/documentation/Network/nw_path_monitor_t"
              ],
              "title": "Paths and Interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_interface",
                    "text": "NSObject<OS_nw_interface>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_interface_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/title",
          "value": "nw_path_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_get_name(_:)/title",
          "value": "nw_interface_get_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_get_name(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_get_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/title",
          "value": "nw_interface_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_get_type(_:)/title",
          "value": "nw_interface_get_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_get_type(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_get_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_type_t/title",
          "value": "nw_interface_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_t/title",
          "value": "nw_path_monitor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_interface/title",
          "value": "OS_nw_interface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_interface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_interface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_get_index(_:)/title",
          "value": "nw_interface_get_index"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_get_index(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_get_index"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_interface_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_interface_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
