{
  "abstract": [
    {
      "text": "An object you use to listen for incoming network connections.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_listener_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_listener_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_listener_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_listener_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_listener_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_listener",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_listener",
              "text": "OS_nw_listener"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSBonjourServices": {
      "abstract": [
        {
          "text": "Bonjour service types browsed by the app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSBonjourServices",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBonjourServices",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSBonjourServices"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the local network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLocalNetworkUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT": {
      "abstract": [
        {
          "text": "A static value that indicates that inbound connections should not be limited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
        }
      ],
      "role": "symbol",
      "title": "NW_LISTENER_INFINITE_CONNECTION_LIMIT",
      "type": "topic",
      "url": "/documentation/network/nw_listener_infinite_connection_limit"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_listener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_listener"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_listener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_listener"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_listener",
      "type": "topic",
      "url": "/documentation/network/os_nw_listener"
    },
    "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework": {
      "abstract": [
        {
          "text": "Build a simple ",
          "type": "text"
        },
        {
          "code": "netcat",
          "type": "codeVoice"
        },
        {
          "text": " tool that establishes network connections and transfers data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing netcat with Network Framework",
      "type": "topic",
      "url": "/documentation/network/implementing-netcat-with-network-framework"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t": {
      "abstract": [
        {
          "text": "A description used to advertise the Bonjour service that a listener provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_t": {
      "abstract": [
        {
          "text": "An object you use to browse for available network services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_t": {
      "abstract": [
        {
          "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_t": {
      "abstract": [
        {
          "text": "A bidirectional data connection between a local endpoint and a remote endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t": {
      "abstract": [
        {
          "text": "An object you use to send and receive custom Ethernet frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ethernet_channel_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ethernet_channel_t",
      "type": "topic",
      "url": "/documentation/network/nw_ethernet_channel_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_advertised_endpoint_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that indicates changes to the service endpoints being advertised as they are added and removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_advertised_endpoint_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_advertised_endpoint_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_advertised_endpoint_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_advertised_endpoint_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_advertised_endpoint_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_cancel(_:)": {
      "abstract": [
        {
          "text": "Stops listening for inbound connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_cancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_cancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_cancel"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_cancel(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_cancel(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_create(_:)": {
      "abstract": [
        {
          "text": "Initializes a network listener, which will select a random port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_create(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_create"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_create(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_create(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_create_with_connection(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a network listener to receive new streams on a multiplexed connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_create_with_connection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_connection_t",
          "text": "nw_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_create_with_connection(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_create_with_connection"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_create_with_connection(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_create_with_connection(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_create_with_port(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a network listener with a specified local port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_create_with_port"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_create_with_port(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_create_with_port"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_create_with_port(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_create_with_port(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_get_new_connection_limit(_:)": {
      "abstract": [
        {
          "text": "Checks the remaining number of inbound connections to deliver before rejecting connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_get_new_connection_limit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_get_new_connection_limit(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_get_new_connection_limit"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_get_new_connection_limit(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_get_new_connection_limit(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_get_port(_:)": {
      "abstract": [
        {
          "text": "The port on which the listener can accept connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_get_port"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_get_port(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_get_port"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_get_port(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_get_port(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_new_connection_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers inbound connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_new_connection_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_new_connection_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_new_connection_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_new_connection_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_new_connection_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_set_advertise_descriptor(_:_:)": {
      "abstract": [
        {
          "text": "Sets a Bonjour service that advertises the listener on the local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_set_advertise_descriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_advertise_descriptor_t",
          "text": "nw_advertise_descriptor_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_set_advertise_descriptor(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_set_advertise_descriptor"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_set_advertise_descriptor(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_set_advertise_descriptor(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_set_advertised_endpoint_changed_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler that receives updates for the service endpoint being advertised.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_set_advertised_endpoint_changed_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_advertised_endpoint_changed_handler_t",
          "text": "nw_listener_advertised_endpoint_changed_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_set_advertised_endpoint_changed_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_set_advertised_endpoint_changed_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_set_advertised_endpoint_changed_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_set_advertised_endpoint_changed_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_set_new_connection_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler that receives inbound connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_set_new_connection_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_new_connection_handler_t",
          "text": "nw_listener_new_connection_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_set_new_connection_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_set_new_connection_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_set_new_connection_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_set_new_connection_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_set_new_connection_limit(_:_:)": {
      "abstract": [
        {
          "text": "Resets the number of inbound connections to deliver before rejecting connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_set_new_connection_limit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_set_new_connection_limit(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_set_new_connection_limit"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_set_new_connection_limit(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_set_new_connection_limit(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_set_queue(_:_:)": {
      "abstract": [
        {
          "text": "Sets the queue on which all listener events are delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_set_queue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_set_queue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_set_queue"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_set_queue(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_set_queue(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_set_state_changed_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to receive listener state updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_set_state_changed_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_state_changed_handler_t",
          "text": "nw_listener_state_changed_handler_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_set_state_changed_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_set_state_changed_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_set_state_changed_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_set_state_changed_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_start(_:)": {
      "abstract": [
        {
          "text": "Registers for listening for inbound connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_listener_t",
          "text": "nw_listener_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_start(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_start"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_start(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_listener_start(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers listener state updates with associated errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a listener is able to accept incoming connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_state_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_state_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_state_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_state_t"
    },
    "doc://com.apple.network/documentation/Network/nw_listener_t": {
      "abstract": [
        {
          "text": "An object you use to listen for incoming network connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_listener_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_listener_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_listener_t"
        }
      ],
      "role": "symbol",
      "title": "nw_listener_t",
      "type": "topic",
      "url": "/documentation/network/nw_listener_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-Listeners",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_listener_create(_:)",
        "doc://com.apple.network/documentation/Network/nw_listener_create_with_port(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_listener_create_with_connection(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_listener_set_queue(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_listener_start(_:)",
        "doc://com.apple.network/documentation/Network/nw_listener_get_port(_:)",
        "doc://com.apple.network/documentation/Network/nw_listener_cancel(_:)"
      ],
      "title": "Creating Listeners"
    },
    {
      "anchor": "Receiving-Connections",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_listener_set_new_connection_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_listener_new_connection_handler_t",
        "doc://com.apple.network/documentation/Network/nw_listener_set_new_connection_limit(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_listener_get_new_connection_limit(_:)",
        "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT"
      ],
      "title": "Receiving Connections"
    },
    {
      "anchor": "Advertising-Bonjour-Services",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSBonjourServices",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription",
        "doc://com.apple.network/documentation/Network/nw_listener_set_advertise_descriptor(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
        "doc://com.apple.network/documentation/Network/nw_listener_set_advertised_endpoint_changed_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_listener_advertised_endpoint_changed_handler_t"
      ],
      "title": "Advertising Bonjour Services"
    },
    {
      "anchor": "Handling-State-Updates",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_listener_set_state_changed_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_listener_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_listener_state_t"
      ],
      "title": "Handling State Updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_listener_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Listeners",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_listener_create(_:)",
                "doc://com.apple.network/documentation/Network/nw_listener_create_with_port(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_listener_create_with_connection(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_listener_set_queue(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_listener_start(_:)",
                "doc://com.apple.network/documentation/Network/nw_listener_get_port(_:)",
                "doc://com.apple.network/documentation/Network/nw_listener_cancel(_:)"
              ],
              "title": "Creating Listeners"
            },
            {
              "anchor": "Receiving-Connections",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_listener_set_new_connection_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_listener_new_connection_handler_t",
                "doc://com.apple.network/documentation/Network/nw_listener_set_new_connection_limit(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_listener_get_new_connection_limit(_:)",
                "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT"
              ],
              "title": "Receiving Connections"
            },
            {
              "anchor": "Advertising-Bonjour-Services",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSBonjourServices",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocalNetworkUsageDescription",
                "doc://com.apple.network/documentation/Network/nw_listener_set_advertise_descriptor(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
                "doc://com.apple.network/documentation/Network/nw_listener_set_advertised_endpoint_changed_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_listener_advertised_endpoint_changed_handler_t"
              ],
              "title": "Advertising Bonjour Services"
            },
            {
              "anchor": "Handling-State-Updates",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_listener_set_state_changed_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_listener_state_changed_handler_t",
                "doc://com.apple.network/documentation/Network/nw_listener_state_t"
              ],
              "title": "Handling State Updates"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Connections-and-Listeners",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/implementing-netcat-with-network-framework",
                "doc://com.apple.network/documentation/Network/nw_connection_t",
                "doc://com.apple.network/documentation/Network/nw_browser_t",
                "doc://com.apple.network/documentation/Network/nw_connection_group_t",
                "doc://com.apple.network/documentation/Network/nw_ethernet_channel_t"
              ],
              "title": "Connections and Listeners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_listener",
                    "text": "NSObject<OS_nw_listener>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_listener_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_advertise_descriptor(_:_:)/title",
          "value": "nw_listener_set_advertise_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_advertise_descriptor(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_set_advertise_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_queue(_:_:)/title",
          "value": "nw_listener_set_queue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_queue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_set_queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_t/title",
          "value": "nw_listener_state_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_state_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_new_connection_handler_t/title",
          "value": "nw_listener_new_connection_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_new_connection_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_new_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_new_connection_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_new_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_listener/title",
          "value": "OS_nw_listener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_listener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_listener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_listener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_listener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_create_with_port(_:_:)/title",
          "value": "nw_listener_create_with_port"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_create_with_port(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_create_with_port"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_advertised_endpoint_changed_handler_t/title",
          "value": "nw_listener_advertised_endpoint_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_advertised_endpoint_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_advertised_endpoint_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_advertised_endpoint_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_advertised_endpoint_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_LISTENER_INFINITE_CONNECTION_LIMIT/title",
          "value": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_LISTENER_INFINITE_CONNECTION_LIMIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_start(_:)/title",
          "value": "nw_listener_start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_start(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_get_port(_:)/title",
          "value": "nw_listener_get_port"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_get_port(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_get_port"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title",
          "value": "nw_browser_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/title",
          "value": "nw_connection_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/title",
          "value": "nw_listener_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_new_connection_handler(_:_:)/title",
          "value": "nw_listener_set_new_connection_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_new_connection_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_set_new_connection_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_create(_:)/title",
          "value": "nw_listener_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_create(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_advertised_endpoint_changed_handler(_:_:)/title",
          "value": "nw_listener_set_advertised_endpoint_changed_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_advertised_endpoint_changed_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_set_advertised_endpoint_changed_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_state_changed_handler(_:_:)/title",
          "value": "nw_listener_set_state_changed_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_state_changed_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_set_state_changed_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_get_new_connection_limit(_:)/title",
          "value": "nw_listener_get_new_connection_limit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_get_new_connection_limit(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_get_new_connection_limit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/title",
          "value": "nw_ethernet_channel_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ethernet_channel_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ethernet_channel_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_cancel(_:)/title",
          "value": "nw_listener_cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_cancel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/title",
          "value": "nw_advertise_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_create_with_connection(_:_:)/title",
          "value": "nw_listener_create_with_connection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_create_with_connection(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_create_with_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_changed_handler_t/title",
          "value": "nw_listener_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_new_connection_limit(_:_:)/title",
          "value": "nw_listener_set_new_connection_limit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_listener_set_new_connection_limit(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_listener_set_new_connection_limit"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_listener_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_listener_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
