{"abstract":[{"type":"text","text":"A block that enumerates the interfaces available to a path."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/network/nw_path_enumerate_interfaces_block_t"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/network/nw_path_enumerate_interfaces_block_t"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces_block_t"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_path_enumerate_interfaces_block_t"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","identifier":"doc://com.apple.network/documentation/Network/nw_interface_t","preciseIdentifier":"c:@T@nw_interface_t","text":"nw_interface_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"Return true to continue enumerating, or false to stop enumerating.","type":"text"}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.network/documentation/Network"]]},"kind":"symbol","metadata":{"roleHeading":"Type Alias","externalID":"c:@T@nw_path_enumerate_interfaces_block_t","role":"symbol","title":"nw_path_enumerate_interfaces_block_t","navigatorTitle":[{"text":"nw_path_enumerate_interfaces_block_t","kind":"identifier"}],"platforms":[{"name":"iOS","beta":false,"introducedAt":"12.0","unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"introducedAt":"12.0","unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"13.0","unavailable":false,"deprecated":false},{"name":"macOS","beta":false,"introducedAt":"10.14","unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"introducedAt":"12.0","unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false},{"name":"watchOS","beta":false,"introducedAt":"6.0","unavailable":false,"deprecated":false}],"modules":[{"name":"Network"}],"symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_path_enumerate_interfaces_block_t","kind":"identifier"}]},"seeAlsoSections":[{"generated":true,"title":"Data Types","identifiers":["doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t","doc://com.apple.network/documentation/Network/nw_browse_descriptor_t","doc://com.apple.network/documentation/Network/nw_browse_result_change_t","doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t","doc://com.apple.network/documentation/Network/nw_browse_result_t","doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t","doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t","doc://com.apple.network/documentation/Network/nw_browser_t","doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t","doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t","doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t","doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t","doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t","doc://com.apple.network/documentation/Network/nw_connection_group_t","doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t"],"anchor":"Data-Types"}],"references":{"doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_boolean_event_handler_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A handler that receives Boolean state updates from a connection, such as viability and better path state."}],"navigatorTitle":[{"text":"nw_connection_boolean_event_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_boolean_event_handler_t","kind":"symbol","title":"nw_connection_boolean_event_handler_t"},"doc://com.apple.network/documentation/Network/nw_browse_result_t":{"type":"topic","role":"symbol","abstract":[{"text":"A discovered service and metadata about the service.","type":"text"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_t","kind":"identifier"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_t","title":"nw_browse_result_t","navigatorTitle":[{"text":"nw_browse_result_t","kind":"identifier"}],"url":"/documentation/network/nw_browse_result_t"},"doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t":{"role":"symbol","type":"topic","title":"nw_browse_result_enumerate_interface_t","abstract":[{"text":"A handler that enumerates the interfaces associated with a discovered service.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_enumerate_interface_t","kind":"identifier"}],"url":"/documentation/network/nw_browse_result_enumerate_interface_t","navigatorTitle":[{"text":"nw_browse_result_enumerate_interface_t","kind":"identifier"}]},"doc://com.apple.network/documentation/Network":{"title":"Network","abstract":[{"text":"Create network connections to send and receive data using transport and security protocols.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network","role":"collection","url":"/documentation/network","kind":"symbol","type":"topic"},"doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_path_event_handler_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A handler that delivers network path updates."}],"navigatorTitle":[{"text":"nw_connection_path_event_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_path_event_handler_t","kind":"symbol","title":"nw_connection_path_event_handler_t"},"doc://com.apple.network/documentation/Network/nw_browse_result_change_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_result_change_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_result_change_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Flags describing ways in which discovered services can change between specific results."}],"navigatorTitle":[{"text":"nw_browse_result_change_t","kind":"identifier"}],"url":"/documentation/network/nw_browse_result_change_t","kind":"symbol","title":"nw_browse_result_change_t"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_descriptor_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A service description used to discover Bonjour services."}],"navigatorTitle":[{"text":"nw_browse_descriptor_t","kind":"identifier"}],"url":"/documentation/network/nw_browse_descriptor_t","kind":"symbol","title":"nw_browse_descriptor_t"},"doc://com.apple.network/documentation/Network/nw_browser_t":{"url":"/documentation/network/nw_browser_t","abstract":[{"type":"text","text":"An object you use to browse for available network services."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browser_t"}],"kind":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_browser_t","title":"nw_browser_t","navigatorTitle":[{"kind":"identifier","text":"nw_browser_t"}]},"doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_group_state_changed_handler_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A handler that receives connection group state updates."}],"navigatorTitle":[{"text":"nw_connection_group_state_changed_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_group_state_changed_handler_t","kind":"symbol","title":"nw_connection_group_state_changed_handler_t"},"doc://com.apple.network/documentation/Network/nw_connection_group_t":{"navigatorTitle":[{"kind":"identifier","text":"nw_connection_group_t"}],"identifier":"doc://com.apple.network/documentation/Network/nw_connection_group_t","abstract":[{"type":"text","text":"An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_connection_group_t"}],"title":"nw_connection_group_t","type":"topic","url":"/documentation/network/nw_connection_group_t","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t":{"role":"symbol","type":"topic","title":"nw_browser_state_changed_handler_t","abstract":[{"text":"A handler that delivers browser state updates with associated errors.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browser_state_changed_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_browser_state_changed_handler_t","navigatorTitle":[{"text":"nw_browser_state_changed_handler_t","kind":"identifier"}]},"doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t":{"role":"symbol","type":"topic","title":"nw_browser_browse_results_changed_handler_t","abstract":[{"text":"A handler that delivers updates about discovered services.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browser_browse_results_changed_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_browser_browse_results_changed_handler_t","navigatorTitle":[{"text":"nw_browser_browse_results_changed_handler_t","kind":"identifier"}]},"doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t":{"role":"symbol","type":"topic","title":"nw_connection_group_new_connection_handler_t","abstract":[],"identifier":"doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_group_new_connection_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_group_new_connection_handler_t","navigatorTitle":[{"text":"nw_connection_group_new_connection_handler_t","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","role":"overview","abstract":[{"text":"","type":"text"}],"title":"Technologies"},"doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_group_receive_handler_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A handler that receives inbound messages from members of the group."}],"navigatorTitle":[{"text":"nw_connection_group_receive_handler_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_group_receive_handler_t","kind":"symbol","title":"nw_connection_group_receive_handler_t"},"doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces_block_t":{"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_path_enumerate_interfaces_block_t"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"nw_path_enumerate_interfaces_block_t"}],"identifier":"doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces_block_t","url":"/documentation/network/nw_path_enumerate_interfaces_block_t","abstract":[{"type":"text","text":"A block that enumerates the interfaces available to a path."}],"title":"nw_path_enumerate_interfaces_block_t","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"symbol","type":"topic","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Bool"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"title":"Bool","url":"/documentation/Swift/Bool"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A description used to advertise the Bonjour service that a listener provides."}],"navigatorTitle":[{"text":"nw_advertise_descriptor_t","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_t","kind":"symbol","title":"nw_advertise_descriptor_t"},"doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t":{"identifier":"doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_connection_group_send_completion_t","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A completion to notify you when data has been processed and sent."}],"navigatorTitle":[{"text":"nw_connection_group_send_completion_t","kind":"identifier"}],"url":"/documentation/network/nw_connection_group_send_completion_t","kind":"symbol","title":"nw_connection_group_send_completion_t"},"doc://com.apple.network/documentation/Network/nw_interface_t":{"type":"topic","url":"/documentation/network/nw_interface_t","abstract":[{"type":"text","text":"An interface that a network connection uses to send and receive data."}],"role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_interface_t","title":"nw_interface_t","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_interface_t"}],"navigatorTitle":[{"kind":"identifier","text":"nw_interface_t"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"introducedAt":"12.0","unavailable":false,"deprecated":false,"name":"iOS"},{"beta":false,"introducedAt":"12.0","unavailable":false,"deprecated":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"introducedAt":"10.14","unavailable":false,"deprecated":false,"name":"macOS"},{"beta":false,"introducedAt":"12.0","unavailable":false,"deprecated":false,"name":"tvOS"},{"beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS"},{"beta":false,"introducedAt":"6.0","unavailable":false,"deprecated":false,"name":"watchOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Type Alias","op":"replace","path":"/metadata/roleHeading"},{"value":"nw_path_enumerate_interfaces_block_t","op":"replace","path":"/metadata/title"},{"value":"typealias","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"nw_path_enumerate_interfaces_block_t"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"nw_path_enumerate_interfaces_block_t","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.network/documentation/Network"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:BFb(#*Q$objc(cs)NSObjectobjc(pl)OS_nw_interface)","text":"_Bool (^)(NSObject<OS_nw_interface> *)"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_path_enumerate_interfaces_block_t"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/title","value":"nw_connection_boolean_event_handler_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/fragments","value":[{"text":"nw_connection_boolean_event_handler_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_connection_boolean_event_handler_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/title","value":"nw_browse_result_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/fragments","value":[{"text":"nw_browse_result_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_browse_result_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/title","value":"nw_browse_result_enumerate_interface_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/fragments","value":[{"kind":"identifier","text":"nw_browse_result_enumerate_interface_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/navigatorTitle","value":[{"text":"nw_browse_result_enumerate_interface_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/title","value":"nw_connection_path_event_handler_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/fragments","value":[{"kind":"identifier","text":"nw_connection_path_event_handler_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_connection_path_event_handler_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/title","value":"nw_browse_result_change_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/fragments","value":[{"kind":"identifier","text":"nw_browse_result_change_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_browse_result_change_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/title","value":"nw_browse_descriptor_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/fragments","value":[{"text":"nw_browse_descriptor_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_browse_descriptor_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title","value":"nw_browser_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments","value":[{"kind":"identifier","text":"nw_browser_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle","value":[{"text":"nw_browser_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/title","value":"nw_connection_group_state_changed_handler_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/fragments","value":[{"kind":"identifier","text":"nw_connection_group_state_changed_handler_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/navigatorTitle","value":[{"text":"nw_connection_group_state_changed_handler_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title","value":"nw_connection_group_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments","value":[{"kind":"identifier","text":"nw_connection_group_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_connection_group_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/title","value":"nw_browser_state_changed_handler_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/fragments","value":[{"kind":"identifier","text":"nw_browser_state_changed_handler_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_browser_state_changed_handler_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/title","value":"nw_browser_browse_results_changed_handler_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/fragments","value":[{"text":"nw_browser_browse_results_changed_handler_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/navigatorTitle","value":[{"text":"nw_browser_browse_results_changed_handler_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/title","value":"nw_connection_group_new_connection_handler_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/fragments","value":[{"kind":"identifier","text":"nw_connection_group_new_connection_handler_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/navigatorTitle","value":[{"text":"nw_connection_group_new_connection_handler_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/title","value":"nw_connection_group_receive_handler_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/fragments","value":[{"text":"nw_connection_group_receive_handler_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/navigatorTitle","value":[{"text":"nw_connection_group_receive_handler_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_interfaces_block_t/title","value":"nw_path_enumerate_interfaces_block_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_interfaces_block_t/fragments","value":[{"text":"nw_path_enumerate_interfaces_block_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_interfaces_block_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_path_enumerate_interfaces_block_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/title","value":"nw_advertise_descriptor_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/fragments","value":[{"kind":"identifier","text":"nw_advertise_descriptor_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_advertise_descriptor_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/title","value":"nw_connection_group_send_completion_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/fragments","value":[{"kind":"identifier","text":"nw_connection_group_send_completion_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/navigatorTitle","value":[{"text":"nw_connection_group_send_completion_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/title","value":"nw_interface_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/fragments","value":[{"kind":"identifier","text":"nw_interface_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_interface_t"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}