{
  "abstract": [
    {
      "text": "A block to configure protocol options during the creation of a parameters object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_parameters_configure_protocol_block_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_parameters_configure_protocol_block_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_parameters_configure_protocol_block_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_parameters_configure_protocol_block_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_parameters_configure_protocol_block_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_parameters_configure_protocol_block_t"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_options_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_protocol_options_t",
              "text": "nw_protocol_options_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Passing in a block allows you to customize how a protocol will behave in a connection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to use the default configuration for a protocol, pass NW_PARAMETERS_DEFAULT_CONFIGURATION.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to disable a protocol (such as TLS), pass NW_PARAMETERS_DISABLE_PROTOCOL. Not all protocols can be disabled.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_configure_protocol_block_t": {
      "abstract": [
        {
          "text": "A block to configure protocol options during the creation of a parameters object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_configure_protocol_block_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_configure_protocol_block_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_configure_protocol_block_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_configure_protocol_block_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_configure_protocol_block_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_copy(_:)": {
      "abstract": [
        {
          "text": "Peforms a deep copy of a parameters object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_copy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_copy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_copy"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_copy(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_copy(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_create()": {
      "abstract": [
        {
          "text": "Initializes parameters for connections, listeners, and browsers with no protocols specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_create"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_create()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_create"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_create()",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_create()"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_create_custom_ip(_:_:)": {
      "abstract": [
        {
          "text": "Initializes parameters for connections and listeners using a custom IP protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_create_custom_ip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_configure_protocol_block_t",
          "text": "nw_parameters_configure_protocol_block_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_create_custom_ip(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_create_custom_ip"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_create_custom_ip(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_create_custom_ip(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_create_quic(_:)": {
      "abstract": [
        {
          "text": "Initializes parameters for QUIC connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_create_quic"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_configure_protocol_block_t",
          "text": "nw_parameters_configure_protocol_block_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_create_quic(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_create_quic"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_create_quic(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_create_quic(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_create_secure_tcp(_:_:)": {
      "abstract": [
        {
          "text": "Initializes parameters for TLS or TCP connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_create_secure_tcp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_configure_protocol_block_t",
          "text": "nw_parameters_configure_protocol_block_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_configure_protocol_block_t",
          "text": "nw_parameters_configure_protocol_block_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_create_secure_tcp(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_create_secure_tcp"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_create_secure_tcp(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_create_secure_tcp(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_create_secure_udp(_:_:)": {
      "abstract": [
        {
          "text": "Initializes parameters for DTLS or UDP connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_create_secure_udp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_configure_protocol_block_t",
          "text": "nw_parameters_configure_protocol_block_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_configure_protocol_block_t",
          "text": "nw_parameters_configure_protocol_block_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_create_secure_udp(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_create_secure_udp"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_create_secure_udp(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_create_secure_udp(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_options_t": {
      "abstract": [
        {
          "text": "The abstract superclass for configuring the options of a network protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_options_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_options_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_options_t"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_options_t",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_options_t"
    },
    "doc://com.apple.network/documentation/Network/tcp-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the Transmission Control Protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/tcp-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TCP Options",
      "type": "topic",
      "url": "/documentation/network/tcp-options"
    },
    "doc://com.apple.network/documentation/Network/tls-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use Transport Layer Security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/tls-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TLS Options",
      "type": "topic",
      "url": "/documentation/network/tls-options"
    },
    "doc://com.apple.network/documentation/Network/udp-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the User Datagram Protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/udp-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UDP Options",
      "type": "topic",
      "url": "/documentation/network/udp-options"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/tcp-options",
        "doc://com.apple.network/documentation/Network/tls-options",
        "doc://com.apple.network/documentation/Network/udp-options"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Creating-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_parameters_create_secure_tcp(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_create_secure_udp(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_create_quic(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_create()",
        "doc://com.apple.network/documentation/Network/nw_parameters_create_custom_ip(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_copy(_:)"
      ],
      "title": "Creating Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_parameters_configure_protocol_block_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_configure_protocol_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_configure_protocol_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/tcp-options",
                "doc://com.apple.network/documentation/Network/tls-options",
                "doc://com.apple.network/documentation/Network/udp-options"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Creating-Parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_parameters_create_secure_tcp(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_create_secure_udp(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_create_quic(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_create()",
                "doc://com.apple.network/documentation/Network/nw_parameters_create_custom_ip(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_copy(_:)"
              ],
              "title": "Creating Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#*Q$objc(cs)NSObjectobjc(pl)OS_nw_protocol_options)",
                    "text": "void (^)(NSObject<OS_nw_protocol_options> *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_parameters_configure_protocol_block_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_create_quic(_:)/title",
          "value": "nw_parameters_create_quic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_create_quic(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_create_quic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_copy(_:)/title",
          "value": "nw_parameters_copy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_copy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_copy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_configure_protocol_block_t/title",
          "value": "nw_parameters_configure_protocol_block_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_configure_protocol_block_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_configure_protocol_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_configure_protocol_block_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_configure_protocol_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_create_secure_udp(_:_:)/title",
          "value": "nw_parameters_create_secure_udp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_create_secure_udp(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_create_secure_udp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_create_custom_ip(_:_:)/title",
          "value": "nw_parameters_create_custom_ip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_create_custom_ip(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_create_custom_ip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_create_secure_tcp(_:_:)/title",
          "value": "nw_parameters_create_secure_tcp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_create_secure_tcp(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_create_secure_tcp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_options_t/title",
          "value": "nw_protocol_options_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_options_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_options_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_create()/title",
          "value": "nw_parameters_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_create()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_create"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_parameters_configure_protocol_block_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_parameters_configure_protocol_block_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
