{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_not_available"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@nw_path_unsatisfied_reason_t@nw_path_unsatisfied_reason_not_available",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_path_unsatisfied_reason_not_available"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@nw_path_unsatisfied_reason_t",
        "text": "nw_path_unsatisfied_reason_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_path_unsatisfied_reason_not_available"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "nw_path_unsatisfied_reason_not_available"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_not_available"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@nw_path_unsatisfied_reason_t",
              "text": "nw_path_unsatisfied_reason_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/NW_FRAMER_CREATE_FLAGS_DEFAULT": {
      "abstract": [
        {
          "text": "A constant flag value that indicates that the default framer protocol behavior should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NW_FRAMER_CREATE_FLAGS_DEFAULT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/NW_FRAMER_CREATE_FLAGS_DEFAULT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NW_FRAMER_CREATE_FLAGS_DEFAULT"
        }
      ],
      "role": "symbol",
      "title": "NW_FRAMER_CREATE_FLAGS_DEFAULT",
      "type": "topic",
      "url": "/documentation/network/nw_framer_create_flags_default"
    },
    "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER": {
      "abstract": [
        {
          "text": "A sentinel value that indicates that no wakeup should be delivered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NW_FRAMER_WAKEUP_TIME_FOREVER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NW_FRAMER_WAKEUP_TIME_FOREVER"
        }
      ],
      "role": "symbol",
      "title": "NW_FRAMER_WAKEUP_TIME_FOREVER",
      "type": "topic",
      "url": "/documentation/network/nw_framer_wakeup_time_forever"
    },
    "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT": {
      "abstract": [
        {
          "text": "A static value that indicates that inbound connections should not be limited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
        }
      ],
      "role": "symbol",
      "title": "NW_LISTENER_INFINITE_CONNECTION_LIMIT",
      "type": "topic",
      "url": "/documentation/network/nw_listener_infinite_connection_limit"
    },
    "doc://com.apple.network/documentation/Network/NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE"
        }
      ],
      "role": "symbol",
      "title": "NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE",
      "type": "topic",
      "url": "/documentation/network/nw_quic_connection_default_keepalive"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_state_waiting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_state_waiting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_browser_state_t",
          "text": "nw_browser_state_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_state_waiting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_state_waiting"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_state_waiting",
      "type": "topic",
      "url": "/documentation/network/nw_browser_state_waiting"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_cdma": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_cdma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_cdma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_cdma"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_cdma",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_cdma"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_mmw": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_endc_mmw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_mmw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_endc_mmw"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_endc_mmw",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_endc_mmw"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_sub6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_endc_sub6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_sub6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_endc_sub6"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_endc_sub6",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_endc_sub6"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_evdo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_evdo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_evdo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_evdo"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_evdo",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_evdo"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_gsm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_gsm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_gsm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_gsm"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_gsm",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_gsm"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_lte": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_lte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_lte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_lte"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_lte",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_lte"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_mmw": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_nr_sa_mmw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_mmw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_nr_sa_mmw"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_nr_sa_mmw",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_nr_sa_mmw"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_sub6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_nr_sa_sub6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_sub6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_nr_sa_sub6"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_nr_sa_sub6",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_nr_sa_sub6"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_wcdma": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_wcdma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_wcdma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_cell_wcdma"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_cell_wcdma",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_cell_wcdma"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_radio_type_unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_radio_type_t",
          "text": "nw_interface_radio_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_radio_type_unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_radio_type_unknown"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_radio_type_unknown",
      "type": "topic",
      "url": "/documentation/network/nw_interface_radio_type_unknown"
    },
    "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_not_available": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_not_available"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_path_unsatisfied_reason_t",
          "text": "nw_path_unsatisfied_reason_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_not_available",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_not_available"
        }
      ],
      "role": "symbol",
      "title": "nw_path_unsatisfied_reason_not_available",
      "type": "topic",
      "url": "/documentation/network/nw_path_unsatisfied_reason_not_available"
    },
    "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_unsatisfied_reason_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_unsatisfied_reason_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_unsatisfied_reason_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/NW_FRAMER_CREATE_FLAGS_DEFAULT",
        "doc://com.apple.network/documentation/Network/NW_FRAMER_WAKEUP_TIME_FOREVER",
        "doc://com.apple.network/documentation/Network/NW_LISTENER_INFINITE_CONNECTION_LIMIT",
        "doc://com.apple.network/documentation/Network/NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE",
        "doc://com.apple.network/documentation/Network/nw_browser_state_waiting",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_cdma",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_mmw",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_endc_sub6",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_evdo",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_gsm",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_lte",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_mmw",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_nr_sa_sub6",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_cell_wcdma",
        "doc://com.apple.network/documentation/Network/nw_interface_radio_type_unknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_path_unsatisfied_reason_not_available"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_not_available"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network",
                "doc://com.apple.network/documentation/Network/nw_path_unsatisfied_reason_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "nw_path_unsatisfied_reason_not_available"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_nr_sa_mmw/title",
          "value": "nw_interface_radio_type_cell_nr_sa_mmw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_nr_sa_mmw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_nr_sa_mmw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE/title",
          "value": "NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NW_QUIC_CONNECTION_DEFAULT_KEEPALIVE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_nr_sa_sub6/title",
          "value": "nw_interface_radio_type_cell_nr_sa_sub6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_nr_sa_sub6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_nr_sa_sub6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_LISTENER_INFINITE_CONNECTION_LIMIT/title",
          "value": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_LISTENER_INFINITE_CONNECTION_LIMIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NW_LISTENER_INFINITE_CONNECTION_LIMIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_evdo/title",
          "value": "nw_interface_radio_type_cell_evdo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_evdo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_evdo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_endc_mmw/title",
          "value": "nw_interface_radio_type_cell_endc_mmw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_endc_mmw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_endc_mmw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_t/title",
          "value": "nw_path_unsatisfied_reason_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_waiting/title",
          "value": "nw_browser_state_waiting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_waiting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_waiting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_not_available/title",
          "value": "nw_path_unsatisfied_reason_not_available"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_unsatisfied_reason_not_available/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_unsatisfied_reason_not_available"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_gsm/title",
          "value": "nw_interface_radio_type_cell_gsm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_gsm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_gsm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_wcdma/title",
          "value": "nw_interface_radio_type_cell_wcdma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_wcdma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_wcdma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_FRAMER_WAKEUP_TIME_FOREVER/title",
          "value": "NW_FRAMER_WAKEUP_TIME_FOREVER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_FRAMER_WAKEUP_TIME_FOREVER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NW_FRAMER_WAKEUP_TIME_FOREVER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_lte/title",
          "value": "nw_interface_radio_type_cell_lte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_lte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_lte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_endc_sub6/title",
          "value": "nw_interface_radio_type_cell_endc_sub6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_endc_sub6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_endc_sub6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_unknown/title",
          "value": "nw_interface_radio_type_unknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_unknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_cdma/title",
          "value": "nw_interface_radio_type_cell_cdma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_radio_type_cell_cdma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_radio_type_cell_cdma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_FRAMER_CREATE_FLAGS_DEFAULT/title",
          "value": "NW_FRAMER_CREATE_FLAGS_DEFAULT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1NW_FRAMER_CREATE_FLAGS_DEFAULT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NW_FRAMER_CREATE_FLAGS_DEFAULT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_path_unsatisfied_reason_not_available"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_path_unsatisfied_reason_not_available"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
