{"kind":"symbol","seeAlsoSections":[{"anchor":"Functions","generated":true,"title":"Functions","identifiers":["doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_path_has_dns","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"path","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"nw_path_t","preciseIdentifier":"c:@T@nw_path_t","kind":"typeIdentifier","identifier":"doc://com.apple.network/documentation/Network/nw_path_t"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Checks whether the path has a DNS server configured."}],"identifier":{"url":"doc://com.apple.network/documentation/Network/nw_path_has_dns(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/network/nw_path_has_dns(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/network/nw_path_has_dns(_:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.network/documentation/Network"]]},"metadata":{"roleHeading":"Function","externalID":"c:@F@nw_path_has_dns","platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"12.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"12.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"10.14","beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"introducedAt":"12.0","beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false},{"unavailable":false,"introducedAt":"5.0","beta":false,"deprecated":false,"name":"watchOS"}],"modules":[{"name":"Network"}],"role":"symbol","title":"nw_path_has_dns(_:)","navigatorTitle":[{"text":"nw_path_has_dns","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_path_has_dns","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_path_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_path_t"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"func"},"references":{"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_create_application_service"}],"url":"/documentation/network/nw_browse_descriptor_create_application_service(_:)","title":"nw_browse_descriptor_create_application_service(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_create_application_service"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t","text":"nw_browse_descriptor_t"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)"},"doc://com.apple.network/documentation/Network":{"title":"Network","abstract":[{"text":"Create network connections to send and receive data using transport and security protocols.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network","role":"collection","url":"/documentation/network","kind":"symbol","type":"topic"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)","kind":"symbol","abstract":[{"type":"text","text":"Accesses the Bonjour service domain set on a browse descriptor."}],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_domain"}],"title":"nw_browse_descriptor_get_bonjour_service_domain(_:)","type":"topic","url":"/documentation/network/nw_browse_descriptor_get_bonjour_service_domain(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_domain"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t","text":"nw_browse_descriptor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">?"}]},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)":{"kind":"symbol","title":"nw_browse_descriptor_set_include_txt_record(_:_:)","type":"topic","abstract":[{"type":"text","text":"Requires including associated TXT records with all results generated for this service descriptor."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_set_include_txt_record"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_browse_descriptor_t","kind":"typeIdentifier","text":"nw_browse_descriptor_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_set_include_txt_record"}],"url":"/documentation/network/nw_browse_descriptor_set_include_txt_record(_:_:)","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_get_include_txt_record"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_get_include_txt_record"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t","text":"nw_browse_descriptor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)","title":"nw_browse_descriptor_get_include_txt_record(_:)","abstract":[{"type":"text","text":"Checks if the browse descriptor requires including associated TXT records with all results."}],"role":"symbol","url":"/documentation/network/nw_browse_descriptor_get_include_txt_record(_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)":{"type":"topic","abstract":[{"text":"Accesses the TXT record to advertise with the service.","type":"text"}],"navigatorTitle":[{"text":"nw_advertise_descriptor_copy_txt_record_object","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_copy_txt_record_object(_:)","title":"nw_advertise_descriptor_copy_txt_record_object(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_copy_txt_record_object","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"text":") -> ","kind":"text"},{"text":"nw_txt_record_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_txt_record_t"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_set_no_auto_rename"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","kind":"typeIdentifier","text":"nw_advertise_descriptor_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_set_no_auto_rename"}],"kind":"symbol","title":"nw_advertise_descriptor_set_no_auto_rename(_:_:)","url":"/documentation/network/nw_advertise_descriptor_set_no_auto_rename(_:_:)","role":"symbol","abstract":[{"type":"text","text":"Sets a Boolean to indicate whether the service prohibits automatic renaming in the event of a name conflict."}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)":{"title":"nw_advertise_descriptor_get_no_auto_rename(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_get_no_auto_rename"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","kind":"typeIdentifier","text":"nw_advertise_descriptor_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)","url":"/documentation/network/nw_advertise_descriptor_get_no_auto_rename(_:)","abstract":[{"type":"text","text":"Checks whether the service prohibits automatic renaming in the event of a name conflict."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_get_no_auto_rename"}],"role":"symbol"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)":{"type":"topic","abstract":[{"text":"Initializes a Bonjour service to advertise.","type":"text"}],"navigatorTitle":[{"text":"nw_advertise_descriptor_create_bonjour_service","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)","title":"nw_advertise_descriptor_create_bonjour_service(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_create_bonjour_service","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)":{"kind":"symbol","title":"nw_advertise_descriptor_set_txt_record(_:_:_:)","type":"topic","role":"symbol","url":"/documentation/network/nw_advertise_descriptor_set_txt_record(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_set_txt_record"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_set_txt_record"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","kind":"typeIdentifier","text":"nw_advertise_descriptor_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SV","kind":"typeIdentifier","text":"UnsafeRawPointer"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)","abstract":[{"type":"text","text":"Sets the TXT record as a raw buffer to advertise with the service."}]},"doc://com.apple.network/documentation/Network/nw_path_has_dns(_:)":{"abstract":[{"text":"Checks whether the path has a DNS server configured.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network/nw_path_has_dns(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_path_has_dns"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_path_t","text":"nw_path_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"/documentation/network/nw_path_has_dns(_:)","type":"topic","title":"nw_path_has_dns(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_path_has_dns"}]},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)","abstract":[{"type":"text","text":"Initializes a service descriptor used to discover a Bonjour service."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_create_bonjour_service"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_create_bonjour_service"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">, "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?) -> "},{"preciseIdentifier":"c:@T@nw_browse_descriptor_t","kind":"typeIdentifier","text":"nw_browse_descriptor_t"}],"url":"/documentation/network/nw_browse_descriptor_create_bonjour_service(_:_:)","title":"nw_browse_descriptor_create_bonjour_service(_:_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_create_application_service","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","text":"nw_advertise_descriptor_t","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"nw_advertise_descriptor_create_application_service","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)","title":"nw_advertise_descriptor_create_application_service(_:)","type":"topic","url":"/documentation/network/nw_advertise_descriptor_create_application_service(_:)"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)":{"abstract":[{"type":"text","text":"Accesses the Bonjour service type set on a browse descriptor."}],"kind":"symbol","title":"nw_browse_descriptor_get_bonjour_service_type(_:)","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_type"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_browse_descriptor_t","kind":"typeIdentifier","text":"nw_browse_descriptor_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_type"}],"role":"symbol","url":"/documentation/network/nw_browse_descriptor_get_bonjour_service_type(_:)"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"symbol","type":"topic","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Bool"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"title":"Bool","url":"/documentation/Swift/Bool"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"nw_browse_descriptor_get_application_service_name","kind":"identifier"}],"url":"/documentation/network/nw_browse_descriptor_get_application_service_name(_:)","title":"nw_browse_descriptor_get_application_service_name(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_descriptor_get_application_service_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_browse_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t"},{"text":") -> ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_get_application_service_name"}],"abstract":[],"kind":"symbol","type":"topic","url":"/documentation/network/nw_advertise_descriptor_get_application_service_name(_:)","title":"nw_advertise_descriptor_get_application_service_name(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_get_application_service_name"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"nw_advertise_descriptor_t","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">?"}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)":{"kind":"symbol","title":"nw_advertise_descriptor_set_txt_record_object(_:_:)","type":"topic","abstract":[{"text":"Sets the TXT record to advertise with the service.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_set_txt_record_object","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"text":", ","kind":"text"},{"text":"nw_txt_record_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_txt_record_t"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"nw_advertise_descriptor_set_txt_record_object","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_set_txt_record_object(_:_:)","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","role":"overview","abstract":[{"text":"","type":"text"}],"title":"Technologies"},"doc://com.apple.network/documentation/Network/nw_path_t":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_path_t","kind":"identifier"}],"abstract":[{"text":"An object that contains information about the properties of the network that a connection uses, or that are available to your app.","type":"text"}],"navigatorTitle":[{"text":"nw_path_t","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_path_t","title":"nw_path_t","type":"topic","url":"/documentation/network/nw_path_t"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"introducedAt":"12.0","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"12.0","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"13.1","beta":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"10.14","beta":false,"unavailable":false,"name":"macOS"},{"deprecated":false,"introducedAt":"12.0","beta":false,"unavailable":false,"name":"tvOS"},{"unavailable":false,"introducedAt":"1.0","beta":false,"deprecated":false,"name":"visionOS"},{"unavailable":false,"introducedAt":"5.0","beta":false,"deprecated":false,"name":"watchOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Function","op":"replace"},{"path":"/metadata/title","value":"nw_path_has_dns","op":"replace"},{"path":"/metadata/symbolKind","value":"func","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"nw_path_has_dns","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.network/documentation/Network"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"bool"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_path_has_dns"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.network/documentation/Network/nw_path_t","preciseIdentifier":"c:@T@nw_path_t","kind":"typeIdentifier","text":"nw_path_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"path"},{"kind":"text","text":");"}]}],"kind":"declarations"},"op":"replace"},{"value":"nw_browse_descriptor_create_application_service","op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_application_service(_:)/title"},{"value":[{"text":"nw_browse_descriptor_create_application_service","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_application_service(_:)/fragments"},{"value":"nw_browse_descriptor_get_bonjour_service_domain","op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/title"},{"value":[{"text":"nw_browse_descriptor_get_bonjour_service_domain","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/fragments"},{"value":"nw_browse_descriptor_set_include_txt_record","op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/title"},{"value":[{"kind":"identifier","text":"nw_browse_descriptor_set_include_txt_record"}],"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/fragments"},{"value":"nw_browse_descriptor_get_include_txt_record","op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/title"},{"value":[{"kind":"identifier","text":"nw_browse_descriptor_get_include_txt_record"}],"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/fragments"},{"value":"nw_advertise_descriptor_copy_txt_record_object","op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_copy_txt_record_object(_:)/title"},{"value":[{"kind":"identifier","text":"nw_advertise_descriptor_copy_txt_record_object"}],"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_copy_txt_record_object(_:)/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_no_auto_rename(_:_:)/title","value":"nw_advertise_descriptor_set_no_auto_rename"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_no_auto_rename(_:_:)/fragments","value":[{"kind":"identifier","text":"nw_advertise_descriptor_set_no_auto_rename"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_no_auto_rename(_:)/title","value":"nw_advertise_descriptor_get_no_auto_rename"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_no_auto_rename(_:)/fragments","value":[{"text":"nw_advertise_descriptor_get_no_auto_rename","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_bonjour_service(_:_:_:)/title","value":"nw_advertise_descriptor_create_bonjour_service"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_bonjour_service(_:_:_:)/fragments","value":[{"text":"nw_advertise_descriptor_create_bonjour_service","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record(_:_:_:)/title","value":"nw_advertise_descriptor_set_txt_record"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record(_:_:_:)/fragments","value":[{"kind":"identifier","text":"nw_advertise_descriptor_set_txt_record"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_has_dns(_:)/title","value":"nw_path_has_dns"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_has_dns(_:)/fragments","value":[{"text":"nw_path_has_dns","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/title","value":"nw_browse_descriptor_create_bonjour_service"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/fragments","value":[{"kind":"identifier","text":"nw_browse_descriptor_create_bonjour_service"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_application_service(_:)/title","value":"nw_advertise_descriptor_create_application_service"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_application_service(_:)/fragments","value":[{"text":"nw_advertise_descriptor_create_application_service","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/title","value":"nw_browse_descriptor_get_bonjour_service_type"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/fragments","value":[{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_type"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_application_service_name(_:)/title","value":"nw_browse_descriptor_get_application_service_name"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_application_service_name(_:)/fragments","value":[{"text":"nw_browse_descriptor_get_application_service_name","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_application_service_name(_:)/title","value":"nw_advertise_descriptor_get_application_service_name"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_application_service_name(_:)/fragments","value":[{"text":"nw_advertise_descriptor_get_application_service_name","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record_object(_:_:)/title","value":"nw_advertise_descriptor_set_txt_record_object"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record_object(_:_:)/fragments","value":[{"kind":"identifier","text":"nw_advertise_descriptor_set_txt_record_object"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/title","value":"nw_path_t"},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/fragments","value":[{"kind":"identifier","text":"nw_path_t"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/navigatorTitle","value":[{"kind":"identifier","text":"nw_path_t"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}