{
  "abstract": [
    {
      "text": "Sets a flag that indicates whether the network request originates from the developer or the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_parameters_set_attribution(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_parameters_set_attribution",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_parameters_set_attribution"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_parameters_t",
        "text": "nw_parameters_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@nw_parameters_attribution_t",
        "text": "nw_parameters_attribution_t"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_parameters_set_attribution"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_parameters_set_attribution(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_parameters_set_attribution"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "parameters"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_parameters_t",
              "text": "nw_parameters_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attribution"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@nw_parameters_attribution_t",
              "text": "nw_parameters_attribution_t"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The network parameters to update.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "parameters"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An indication of whether the network request comes from the developer or from the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attribution"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.network/documentation/Network/inspecting-app-activity-data",
        "doc://com.apple.network/documentation/Network/indicating-the-source-of-network-activity"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t set this flag, the system assumes a value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t/developer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Use this default value for any network request that your app makes that isn’t explicitly from the user. This includes requests that you make to your own server, even when you load user data. It also includes links that the user selects, but that you modify in any way — including by adding HTTP headers — before loading the content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Set this value to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t/user",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " only for requests that the user explicitly makes, like when the user enters a URL or taps or clicks a URL that they can read, and only if your app loads and displays the data without altering the request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/indicating-the-source-of-network-activity": {
      "abstract": [
        {
          "text": "Control whether the App Privacy Report attributes network traffic to the app or to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/indicating-the-source-of-network-activity",
      "kind": "article",
      "role": "article",
      "title": "Indicating the source of network activity",
      "type": "topic",
      "url": "/documentation/network/indicating-the-source-of-network-activity"
    },
    "doc://com.apple.network/documentation/Network/inspecting-app-activity-data": {
      "abstract": [
        {
          "text": "Verify that your app accesses only the user data and network resources that you expect it to access.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/inspecting-app-activity-data",
      "kind": "article",
      "role": "article",
      "title": "Inspecting app activity data",
      "type": "topic",
      "url": "/documentation/network/inspecting-app-activity-data"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t": {
      "abstract": [
        {
          "text": "The entities that can make a network request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_attribution_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_attribution_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_attribution_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_attribution_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t/developer": {
      "abstract": [
        {
          "text": "A developer-initiated network request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "developer"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t/developer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_attribution_developer"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_attribution_t.developer",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_attribution_t/developer"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t/user": {
      "abstract": [
        {
          "text": "The user explicitly directs the app to make a network request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "user"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t/user",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_attribution_user"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_attribution_t.user",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_attribution_t/user"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_get_attribution(_:)": {
      "abstract": [
        {
          "text": "Gets a flag that indicates whether the network request originates from the developer or the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_get_attribution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@nw_parameters_attribution_t",
          "text": "nw_parameters_attribution_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_get_attribution(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_get_attribution"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_get_attribution(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_get_attribution(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_attribution(_:_:)": {
      "abstract": [
        {
          "text": "Sets a flag that indicates whether the network request originates from the developer or the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_attribution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@nw_parameters_attribution_t",
          "text": "nw_parameters_attribution_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_attribution(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_attribution"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_attribution(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_attribution(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_t": {
      "abstract": [
        {
          "text": "An object that stores the protocols to use for connections, options for sending data, and network path constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Traffic-Attribution",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/inspecting-app-activity-data",
        "doc://com.apple.network/documentation/Network/indicating-the-source-of-network-activity",
        "doc://com.apple.network/documentation/Network/nw_parameters_get_attribution(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t"
      ],
      "title": "Traffic Attribution"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_parameters_set_attribution"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_attribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Traffic-Attribution",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/inspecting-app-activity-data",
                "doc://com.apple.network/documentation/Network/indicating-the-source-of-network-activity",
                "doc://com.apple.network/documentation/Network/nw_parameters_get_attribution(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t"
              ],
              "title": "Traffic Attribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_parameters_set_attribution"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_parameters_t",
                    "text": "nw_parameters_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "parameters"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@nw_parameters_attribution_t",
                    "text": "nw_parameters_attribution_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "attribution"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The network parameters to update.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "parameters"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An indication of whether the network request comes from the developer or from the user.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "attribution"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_attribution_t/title",
          "value": "nw_parameters_attribution_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_attribution_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_attribution_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_attribution_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_attribution_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_attribution_t~1developer/title",
          "value": "nw_parameters_attribution_developer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_attribution_t~1developer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_attribution_developer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_attribution(_:_:)/title",
          "value": "nw_parameters_set_attribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_attribution(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_attribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_attribution_t~1user/title",
          "value": "nw_parameters_attribution_user"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_attribution_t~1user/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_attribution_user"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_attribution(_:)/title",
          "value": "nw_parameters_get_attribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_attribution(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_get_attribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/title",
          "value": "nw_parameters_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_parameters_set_attribution(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_parameters_set_attribution(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
