{
  "abstract": [
    {
      "text": "An observer that you use to monitor and react to network changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_path_monitor_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_path_monitor_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_path_monitor_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_path_monitor_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_path_monitor_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_path_monitor_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_path_monitor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_path_monitor",
              "text": "OS_nw_path_monitor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_path_monitor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_path_monitor"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_path_monitor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_path_monitor"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_path_monitor",
      "type": "topic",
      "url": "/documentation/network/os_nw_path_monitor"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_t": {
      "abstract": [
        {
          "text": "An interface that a network connection uses to send and receive data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_t"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_t",
      "type": "topic",
      "url": "/documentation/network/nw_interface_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_cancel(_:)": {
      "abstract": [
        {
          "text": "Stops receiving network path updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_cancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_monitor_t",
          "text": "nw_path_monitor_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_cancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_cancel"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_cancel(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_cancel(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_cancel_handler_t": {
      "abstract": [
        {
          "text": "A handler that indicates when a monitor has been cancelled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_cancel_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_cancel_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_cancel_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_cancel_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_cancel_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_create()": {
      "abstract": [
        {
          "text": "Initializes a path monitor to observe all available interface types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_create"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_monitor_t",
          "text": "nw_path_monitor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_create()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_create"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_create()",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_create()"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_create_with_type(_:)": {
      "abstract": [
        {
          "text": "Initializes a path monitor to observe a specific interface type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_create_with_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_type_t",
          "text": "nw_interface_type_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_monitor_t",
          "text": "nw_path_monitor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_create_with_type(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_create_with_type"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_create_with_type(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_create_with_type(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_prohibit_interface_type(_:_:)": {
      "abstract": [
        {
          "text": "Prohibit a path monitor from using a specific interface type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_prohibit_interface_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_monitor_t",
          "text": "nw_path_monitor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_type_t",
          "text": "nw_interface_type_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_prohibit_interface_type(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_prohibit_interface_type"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_prohibit_interface_type(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_prohibit_interface_type(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_set_cancel_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to determine when a monitor is fully cancelled and will no longer deliver events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_set_cancel_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_monitor_t",
          "text": "nw_path_monitor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_monitor_cancel_handler_t",
          "text": "nw_path_monitor_cancel_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_set_cancel_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_set_cancel_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_set_cancel_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_set_cancel_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_set_queue(_:_:)": {
      "abstract": [
        {
          "text": "Sets a queue on which to deliver path events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_set_queue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_monitor_t",
          "text": "nw_path_monitor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_set_queue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_set_queue"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_set_queue(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_set_queue(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_set_update_handler(_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to receive network path updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_set_update_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_monitor_t",
          "text": "nw_path_monitor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_monitor_update_handler_t",
          "text": "nw_path_monitor_update_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_set_update_handler(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_set_update_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_set_update_handler(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_set_update_handler(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_start(_:)": {
      "abstract": [
        {
          "text": "Starts monitoring path changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_monitor_t",
          "text": "nw_path_monitor_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_start(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_start"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_start(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_start(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_t": {
      "abstract": [
        {
          "text": "An observer that you use to monitor and react to network changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_update_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers network path updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_update_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_update_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_update_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_update_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_update_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_t": {
      "abstract": [
        {
          "text": "An object that contains information about the properties of the network that a connection uses, or that are available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-Path-Monitors",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_path_monitor_create()",
        "doc://com.apple.network/documentation/Network/nw_path_monitor_create_with_type(_:)",
        "doc://com.apple.network/documentation/Network/nw_path_monitor_prohibit_interface_type(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_path_monitor_set_queue(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_path_monitor_start(_:)"
      ],
      "title": "Creating Path Monitors"
    },
    {
      "anchor": "Handling-Path-Updates",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_path_monitor_set_update_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_path_monitor_update_handler_t"
      ],
      "title": "Handling Path Updates"
    },
    {
      "anchor": "Canceling-Path-Monitors",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_path_monitor_cancel(_:)",
        "doc://com.apple.network/documentation/Network/nw_path_monitor_set_cancel_handler(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_path_monitor_cancel_handler_t"
      ],
      "title": "Canceling Path Monitors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_path_monitor_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Path-Monitors",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_monitor_create()",
                "doc://com.apple.network/documentation/Network/nw_path_monitor_create_with_type(_:)",
                "doc://com.apple.network/documentation/Network/nw_path_monitor_prohibit_interface_type(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_path_monitor_set_queue(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_path_monitor_start(_:)"
              ],
              "title": "Creating Path Monitors"
            },
            {
              "anchor": "Handling-Path-Updates",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_monitor_set_update_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_path_monitor_update_handler_t"
              ],
              "title": "Handling Path Updates"
            },
            {
              "anchor": "Canceling-Path-Monitors",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_monitor_cancel(_:)",
                "doc://com.apple.network/documentation/Network/nw_path_monitor_set_cancel_handler(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_path_monitor_cancel_handler_t"
              ],
              "title": "Canceling Path Monitors"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Paths-and-Interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_t",
                "doc://com.apple.network/documentation/Network/nw_interface_t"
              ],
              "title": "Paths and Interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_path_monitor",
                    "text": "NSObject<OS_nw_path_monitor>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_path_monitor_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_cancel(_:)/title",
          "value": "nw_path_monitor_cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_cancel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_set_cancel_handler(_:_:)/title",
          "value": "nw_path_monitor_set_cancel_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_set_cancel_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_set_cancel_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_create()/title",
          "value": "nw_path_monitor_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_create()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_create_with_type(_:)/title",
          "value": "nw_path_monitor_create_with_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_create_with_type(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_create_with_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_update_handler_t/title",
          "value": "nw_path_monitor_update_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_update_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_update_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_update_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_update_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/title",
          "value": "nw_path_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_start(_:)/title",
          "value": "nw_path_monitor_start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_start(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_t/title",
          "value": "nw_path_monitor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path_monitor/title",
          "value": "OS_nw_path_monitor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path_monitor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_path_monitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path_monitor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_path_monitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_prohibit_interface_type(_:_:)/title",
          "value": "nw_path_monitor_prohibit_interface_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_prohibit_interface_type(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_prohibit_interface_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_set_update_handler(_:_:)/title",
          "value": "nw_path_monitor_set_update_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_set_update_handler(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_set_update_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_cancel_handler_t/title",
          "value": "nw_path_monitor_cancel_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_cancel_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_cancel_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_cancel_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_cancel_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_set_queue(_:_:)/title",
          "value": "nw_path_monitor_set_queue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_set_queue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_set_queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/title",
          "value": "nw_interface_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_path_monitor_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_path_monitor_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
