{
  "abstract": [
    {
      "text": "A proxy configuration for Relays, Oblivious HTTP, HTTP CONNECT, or SOCKSv5.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_proxy_config_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_proxy_config_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_proxy_config_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_proxy_config_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_proxy_config_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_proxy_config_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_proxy_config",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_proxy_config",
              "text": "OS_nw_proxy_config"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_proxy_config": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_proxy_config"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_proxy_config",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_proxy_config"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_proxy_config",
      "type": "topic",
      "url": "/documentation/network/os_nw_proxy_config"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_add_proxy(_:_:)": {
      "abstract": [
        {
          "text": "Applies a proxy configuration to all connections associated with this context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_add_proxy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_add_proxy(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_add_proxy"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_add_proxy(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_add_proxy(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_clear_proxies(_:)": {
      "abstract": [
        {
          "text": "Clears out any proxies added using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_add_proxy(_:_:)",
          "isActive": true,
          "type": "reference"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_clear_proxies"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_clear_proxies(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_clear_proxies"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_clear_proxies(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_clear_proxies(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_create_http_connect(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a legacy HTTP CONNECT configuration for a proxy server accessible using HTTP/1.1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_http_connect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_create_http_connect(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_http_connect"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_create_http_connect(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_create_http_connect(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_create_oblivious_http(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Initializes an Oblivious HTTP proxy configuration using a relay and a gateway.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_oblivious_http"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_relay_hop_t",
          "text": "nw_relay_hop_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_create_oblivious_http(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_oblivious_http"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_create_oblivious_http(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_create_oblivious_http(_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_create_relay(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a proxy configuration with one or two relay hops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_relay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_relay_hop_t",
          "text": "nw_relay_hop_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_relay_hop_t",
          "text": "nw_relay_hop_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_create_relay(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_relay"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_create_relay(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_create_relay(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_create_socksv5(_:)": {
      "abstract": [
        {
          "text": "Initializes a SOCKSv5 proxy configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_socksv5"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_create_socksv5(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_socksv5"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_create_socksv5(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_create_socksv5(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_get_failover_allowed(_:)": {
      "abstract": [
        {
          "text": "Checks if a proxy configuration allows failover to non-proxied connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_get_failover_allowed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_get_failover_allowed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_get_failover_allowed"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_get_failover_allowed(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_get_failover_allowed(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_set_failover_allowed(_:_:)": {
      "abstract": [
        {
          "text": "Configures whether or not a proxy configuration allows failover to non-proxied connections. Failover isn’t allowed by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_set_failover_allowed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_set_failover_allowed(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_set_failover_allowed"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_set_failover_allowed(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_set_failover_allowed(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_set_username_and_password(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a username and password to use as authentication for a proxy configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_set_username_and_password"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_set_username_and_password(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_set_username_and_password"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_set_username_and_password(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_set_username_and_password(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_t": {
      "abstract": [
        {
          "text": "A proxy configuration for Relays, Oblivious HTTP, HTTP CONNECT, or SOCKSv5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_t"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_t",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_t"
    },
    "doc://com.apple.network/documentation/Network/nw_relay_hop_t": {
      "abstract": [
        {
          "text": "A single relay server you can chain together with other servers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_relay_hop_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_relay_hop_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_relay_hop_t"
        }
      ],
      "role": "symbol",
      "title": "nw_relay_hop_t",
      "type": "topic",
      "url": "/documentation/network/nw_relay_hop_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Proxies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_privacy_context_add_proxy(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_privacy_context_clear_proxies(_:)"
      ],
      "title": "Configuring Proxies"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Proxy-Configurations",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_proxy_config_create_relay(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_relay_hop_t",
        "doc://com.apple.network/documentation/Network/nw_proxy_config_create_oblivious_http(_:_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_proxy_config_create_http_connect(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_proxy_config_create_socksv5(_:)"
      ],
      "title": "Creating Proxy Configurations"
    },
    {
      "anchor": "Customizing-Proxy-Behavior",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_proxy_config_set_failover_allowed(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_proxy_config_set_username_and_password(_:_:_:)"
      ],
      "title": "Customizing Proxy Behavior"
    },
    {
      "anchor": "Inspecting-Proxies",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_proxy_config_get_failover_allowed(_:)"
      ],
      "title": "Inspecting Proxies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_proxy_config_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Proxy-Configurations",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_proxy_config_create_relay(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_relay_hop_t",
                "doc://com.apple.network/documentation/Network/nw_proxy_config_create_oblivious_http(_:_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_proxy_config_create_http_connect(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_proxy_config_create_socksv5(_:)"
              ],
              "title": "Creating Proxy Configurations"
            },
            {
              "anchor": "Customizing-Proxy-Behavior",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_proxy_config_set_failover_allowed(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_proxy_config_set_username_and_password(_:_:_:)"
              ],
              "title": "Customizing Proxy Behavior"
            },
            {
              "anchor": "Inspecting-Proxies",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_proxy_config_get_failover_allowed(_:)"
              ],
              "title": "Inspecting Proxies"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Proxies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_privacy_context_add_proxy(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_privacy_context_clear_proxies(_:)"
              ],
              "title": "Configuring Proxies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_proxy_config",
                    "text": "NSObject<OS_nw_proxy_config>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_proxy_config_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_relay_hop_t/title",
          "value": "nw_relay_hop_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_relay_hop_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_relay_hop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_relay_hop_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_relay_hop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_http_connect(_:_:)/title",
          "value": "nw_proxy_config_create_http_connect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_http_connect(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_create_http_connect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_socksv5(_:)/title",
          "value": "nw_proxy_config_create_socksv5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_socksv5(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_create_socksv5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_oblivious_http(_:_:_:_:)/title",
          "value": "nw_proxy_config_create_oblivious_http"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_oblivious_http(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_create_oblivious_http"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_proxy_config/title",
          "value": "OS_nw_proxy_config"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_proxy_config/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_proxy_config"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_proxy_config/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_proxy_config"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_relay(_:_:)/title",
          "value": "nw_proxy_config_create_relay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_relay(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_create_relay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_clear_proxies(_:)/title",
          "value": "nw_privacy_context_clear_proxies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_clear_proxies(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_clear_proxies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_set_username_and_password(_:_:_:)/title",
          "value": "nw_proxy_config_set_username_and_password"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_set_username_and_password(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_set_username_and_password"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_t/title",
          "value": "nw_proxy_config_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_get_failover_allowed(_:)/title",
          "value": "nw_proxy_config_get_failover_allowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_get_failover_allowed(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_get_failover_allowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_set_failover_allowed(_:_:)/title",
          "value": "nw_proxy_config_set_failover_allowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_set_failover_allowed(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_set_failover_allowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_add_proxy(_:_:)/title",
          "value": "nw_privacy_context_add_proxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_add_proxy(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_add_proxy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_proxy_config_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_proxy_config_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
