{
  "abstract": [
    {
      "text": "Associates a privacy context with any connections or listeners that use the parameters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_parameters_set_privacy_context(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_parameters_set_privacy_context",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_parameters_set_privacy_context"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_parameters_t",
        "text": "nw_parameters_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_privacy_context_t",
        "text": "nw_privacy_context_t"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_parameters_set_privacy_context"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_parameters_set_privacy_context(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_parameters_set_privacy_context"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "parameters"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_parameters_t",
              "text": "nw_parameters_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "privacy_context"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_privacy_context_t",
              "text": "nw_privacy_context_t"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_privacy_context(_:_:)": {
      "abstract": [
        {
          "text": "Associates a privacy context with any connections or listeners that use the parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_privacy_context"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_privacy_context(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_privacy_context"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_privacy_context(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_privacy_context(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_t": {
      "abstract": [
        {
          "text": "An object that stores the protocols to use for connections, options for sending data, and network path constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_t"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_t": {
      "abstract": [
        {
          "text": "An object that defines the privacy requirements for a set of connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_t"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_t",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Privacy-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_privacy_context_t"
      ],
      "title": "Configuring Privacy Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_parameters_set_privacy_context"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_privacy_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Privacy-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_privacy_context_t"
              ],
              "title": "Configuring Privacy Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_parameters_set_privacy_context"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_parameters_t",
                    "text": "nw_parameters_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "parameters"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_privacy_context_t",
                    "text": "nw_privacy_context_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "privacy_context"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/title",
          "value": "nw_parameters_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_t/title",
          "value": "nw_privacy_context_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_privacy_context(_:_:)/title",
          "value": "nw_parameters_set_privacy_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_privacy_context(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_privacy_context"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_parameters_set_privacy_context(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_parameters_set_privacy_context(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
