{
  "abstract": [
    {
      "text": "An object that defines the privacy requirements for a set of connections.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_privacy_context_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_privacy_context_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_privacy_context_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_privacy_context_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_privacy_context_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_privacy_context_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_privacy_context",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_privacy_context",
              "text": "OS_nw_privacy_context"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "NW_DEFAULT_PRIVACY_CONTEXT",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " to specify the default shared privacy context that applies to all connections that do not use a custom context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_privacy_context": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_privacy_context"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_privacy_context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_privacy_context"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_privacy_context",
      "type": "topic",
      "url": "/documentation/network/os_nw_privacy_context"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_privacy_context(_:_:)": {
      "abstract": [
        {
          "text": "Associates a privacy context with any connections or listeners that use the parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_privacy_context"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_privacy_context(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_privacy_context"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_privacy_context(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_privacy_context(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_add_proxy(_:_:)": {
      "abstract": [
        {
          "text": "Applies a proxy configuration to all connections associated with this context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_add_proxy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_add_proxy(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_add_proxy"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_add_proxy(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_add_proxy(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_clear_proxies(_:)": {
      "abstract": [
        {
          "text": "Clears out any proxies added using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_add_proxy(_:_:)",
          "isActive": true,
          "type": "reference"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_clear_proxies"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_clear_proxies(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_clear_proxies"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_clear_proxies(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_clear_proxies(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_create(_:)": {
      "abstract": [
        {
          "text": "Initializes a privacy context with a description string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_create(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_create"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_create(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_create(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_disable_logging(_:)": {
      "abstract": [
        {
          "text": "Disables system logging of connection activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_disable_logging"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_disable_logging(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_disable_logging"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_disable_logging(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_disable_logging(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_flush_cache(_:)": {
      "abstract": [
        {
          "text": "Flushes all cached data, such as TLS session state, created by connections associated with the privacy context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_flush_cache"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_flush_cache(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_flush_cache"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_flush_cache(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_flush_cache(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_require_encrypted_name_resolution(_:_:_:)": {
      "abstract": [
        {
          "text": "Requires that any DNS name resolution for connections associated with this context use encrypted transports, such as TLS or HTTPS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_require_encrypted_name_resolution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolver_config_t",
          "text": "nw_resolver_config_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_require_encrypted_name_resolution(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_require_encrypted_name_resolution"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_require_encrypted_name_resolution(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_require_encrypted_name_resolution(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_t": {
      "abstract": [
        {
          "text": "An object that defines the privacy requirements for a set of connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_t"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_t",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_t"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_t": {
      "abstract": [
        {
          "text": "A proxy configuration for Relays, Oblivious HTTP, HTTP CONNECT, or SOCKSv5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_t"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_t",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_t"
    },
    "doc://com.apple.network/documentation/Network/nw_resolver_config_add_server_address(_:_:)": {
      "abstract": [
        {
          "text": "Provides a well-known DNS server address to use instead of looking up the address dynamically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolver_config_add_server_address"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolver_config_t",
          "text": "nw_resolver_config_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolver_config_add_server_address(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolver_config_add_server_address"
        }
      ],
      "role": "symbol",
      "title": "nw_resolver_config_add_server_address(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolver_config_add_server_address(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolver_config_create_https(_:)": {
      "abstract": [
        {
          "text": "Initializes a DNS-over-HTTPS resolver configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolver_config_create_https"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolver_config_t",
          "text": "nw_resolver_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolver_config_create_https(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolver_config_create_https"
        }
      ],
      "role": "symbol",
      "title": "nw_resolver_config_create_https(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolver_config_create_https(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolver_config_create_tls(_:)": {
      "abstract": [
        {
          "text": "Initializes a DNS-over-TLS resolver configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolver_config_create_tls"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolver_config_t",
          "text": "nw_resolver_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolver_config_create_tls(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolver_config_create_tls"
        }
      ],
      "role": "symbol",
      "title": "nw_resolver_config_create_tls(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolver_config_create_tls(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolver_config_t": {
      "abstract": [
        {
          "text": "A DNS server configuration that uses TLS or HTTPS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolver_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolver_config_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolver_config_t"
        }
      ],
      "role": "symbol",
      "title": "nw_resolver_config_t",
      "type": "topic",
      "url": "/documentation/network/nw_resolver_config_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Privacy-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_parameters_set_privacy_context(_:_:)"
      ],
      "title": "Configuring Privacy Settings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-Custom-Privacy-Settings",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_privacy_context_create(_:)",
        "doc://com.apple.network/documentation/Network/nw_privacy_context_disable_logging(_:)",
        "doc://com.apple.network/documentation/Network/nw_privacy_context_flush_cache(_:)"
      ],
      "title": "Configuring Custom Privacy Settings"
    },
    {
      "anchor": "Requiring-Encrypted-DNS",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_privacy_context_require_encrypted_name_resolution(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_resolver_config_t",
        "doc://com.apple.network/documentation/Network/nw_resolver_config_create_https(_:)",
        "doc://com.apple.network/documentation/Network/nw_resolver_config_create_tls(_:)",
        "doc://com.apple.network/documentation/Network/nw_resolver_config_add_server_address(_:_:)"
      ],
      "title": "Requiring Encrypted DNS"
    },
    {
      "anchor": "Configuring-Proxies",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_privacy_context_add_proxy(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_privacy_context_clear_proxies(_:)",
        "doc://com.apple.network/documentation/Network/nw_proxy_config_t"
      ],
      "title": "Configuring Proxies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_privacy_context_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-Custom-Privacy-Settings",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_privacy_context_create(_:)",
                "doc://com.apple.network/documentation/Network/nw_privacy_context_disable_logging(_:)",
                "doc://com.apple.network/documentation/Network/nw_privacy_context_flush_cache(_:)"
              ],
              "title": "Configuring Custom Privacy Settings"
            },
            {
              "anchor": "Requiring-Encrypted-DNS",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_privacy_context_require_encrypted_name_resolution(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_resolver_config_t",
                "doc://com.apple.network/documentation/Network/nw_resolver_config_create_https(_:)",
                "doc://com.apple.network/documentation/Network/nw_resolver_config_create_tls(_:)",
                "doc://com.apple.network/documentation/Network/nw_resolver_config_add_server_address(_:_:)"
              ],
              "title": "Requiring Encrypted DNS"
            },
            {
              "anchor": "Configuring-Proxies",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_privacy_context_add_proxy(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_privacy_context_clear_proxies(_:)",
                "doc://com.apple.network/documentation/Network/nw_proxy_config_t"
              ],
              "title": "Configuring Proxies"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Privacy-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_parameters_set_privacy_context(_:_:)"
              ],
              "title": "Configuring Privacy Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_privacy_context",
                    "text": "NSObject<OS_nw_privacy_context>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_privacy_context_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_disable_logging(_:)/title",
          "value": "nw_privacy_context_disable_logging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_disable_logging(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_disable_logging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_create_https(_:)/title",
          "value": "nw_resolver_config_create_https"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_create_https(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_create_https"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_privacy_context(_:_:)/title",
          "value": "nw_parameters_set_privacy_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_privacy_context(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_privacy_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_create_tls(_:)/title",
          "value": "nw_resolver_config_create_tls"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_create_tls(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_create_tls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_add_proxy(_:_:)/title",
          "value": "nw_privacy_context_add_proxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_add_proxy(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_add_proxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_clear_proxies(_:)/title",
          "value": "nw_privacy_context_clear_proxies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_clear_proxies(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_clear_proxies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_add_server_address(_:_:)/title",
          "value": "nw_resolver_config_add_server_address"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_add_server_address(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_add_server_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_t/title",
          "value": "nw_proxy_config_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_privacy_context/title",
          "value": "OS_nw_privacy_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_privacy_context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_privacy_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_privacy_context/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_privacy_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_flush_cache(_:)/title",
          "value": "nw_privacy_context_flush_cache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_flush_cache(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_flush_cache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_require_encrypted_name_resolution(_:_:_:)/title",
          "value": "nw_privacy_context_require_encrypted_name_resolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_require_encrypted_name_resolution(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_require_encrypted_name_resolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_t/title",
          "value": "nw_resolver_config_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_create(_:)/title",
          "value": "nw_privacy_context_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_create(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_t/title",
          "value": "nw_privacy_context_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_privacy_context_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_privacy_context_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
