{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.network/documentation/Network"]]},"abstract":[{"type":"text","text":"Checks whether a path can be used by connections."}],"seeAlsoSections":[{"anchor":"Functions","title":"Functions","identifiers":["doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)","doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)","doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_path_get_status","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"path","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"nw_path_t","kind":"typeIdentifier","identifier":"doc://com.apple.network/documentation/Network/nw_path_t","preciseIdentifier":"c:@T@nw_path_t"},{"text":") -> ","kind":"text"},{"text":"nw_path_status_t","kind":"typeIdentifier","identifier":"doc://com.apple.network/documentation/Network/nw_path_status_t","preciseIdentifier":"c:@EA@nw_path_status_t"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"Network"}],"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"12.0","name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"12.0","name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.14","name":"macOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"12.0","name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"1.0","name":"visionOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"5.0","name":"watchOS"}],"title":"nw_path_get_status(_:)","symbolKind":"func","navigatorTitle":[{"text":"nw_path_get_status","kind":"identifier"}],"roleHeading":"Function","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_path_get_status","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@nw_path_t","text":"nw_path_t","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@EA@nw_path_status_t","text":"nw_path_status_t","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@F@nw_path_get_status"},"variants":[{"paths":["/documentation/network/nw_path_get_status(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/network/nw_path_get_status(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.network/documentation/Network/nw_path_get_status(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_create_application_service"}],"url":"/documentation/network/nw_browse_descriptor_create_application_service(_:)","title":"nw_browse_descriptor_create_application_service(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_create_application_service"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t","text":"nw_browse_descriptor_t"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_application_service(_:)"},"doc://com.apple.network/documentation/Network":{"title":"Network","abstract":[{"text":"Create network connections to send and receive data using transport and security protocols.","type":"text"}],"identifier":"doc://com.apple.network/documentation/Network","role":"collection","url":"/documentation/network","kind":"symbol","type":"topic"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"nw_browse_descriptor_get_application_service_name","kind":"identifier"}],"url":"/documentation/network/nw_browse_descriptor_get_application_service_name(_:)","title":"nw_browse_descriptor_get_application_service_name(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_browse_descriptor_get_application_service_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_browse_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t"},{"text":") -> ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_application_service_name(_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_set_no_auto_rename"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","kind":"typeIdentifier","text":"nw_advertise_descriptor_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_set_no_auto_rename"}],"kind":"symbol","title":"nw_advertise_descriptor_set_no_auto_rename(_:_:)","url":"/documentation/network/nw_advertise_descriptor_set_no_auto_rename(_:_:)","role":"symbol","abstract":[{"type":"text","text":"Sets a Boolean to indicate whether the service prohibits automatic renaming in the event of a name conflict."}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_no_auto_rename(_:_:)"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_domain(_:)","kind":"symbol","abstract":[{"type":"text","text":"Accesses the Bonjour service domain set on a browse descriptor."}],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_domain"}],"title":"nw_browse_descriptor_get_bonjour_service_domain(_:)","type":"topic","url":"/documentation/network/nw_browse_descriptor_get_bonjour_service_domain(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_domain"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t","text":"nw_browse_descriptor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">?"}]},"doc://com.apple.network/documentation/Network/nw_path_status_t":{"role":"symbol","abstract":[{"text":"Status values indicating whether a path can be used by connections.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_path_status_t","title":"nw_path_status_t","type":"topic","navigatorTitle":[{"text":"nw_path_status_t","kind":"identifier"}],"url":"/documentation/network/nw_path_status_t","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_path_status_t","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","role":"overview","abstract":[{"text":"","type":"text"}],"title":"Technologies"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)":{"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_create_bonjour_service(_:_:)","abstract":[{"type":"text","text":"Initializes a service descriptor used to discover a Bonjour service."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_create_bonjour_service"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_create_bonjour_service"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">, "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?) -> "},{"preciseIdentifier":"c:@T@nw_browse_descriptor_t","kind":"typeIdentifier","text":"nw_browse_descriptor_t"}],"url":"/documentation/network/nw_browse_descriptor_create_bonjour_service(_:_:)","title":"nw_browse_descriptor_create_bonjour_service(_:_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_create_application_service","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","text":"nw_advertise_descriptor_t","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"nw_advertise_descriptor_create_application_service","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_application_service(_:)","title":"nw_advertise_descriptor_create_application_service(_:)","type":"topic","url":"/documentation/network/nw_advertise_descriptor_create_application_service(_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)":{"kind":"symbol","title":"nw_advertise_descriptor_set_txt_record_object(_:_:)","type":"topic","abstract":[{"text":"Sets the TXT record to advertise with the service.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_set_txt_record_object","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"text":", ","kind":"text"},{"text":"nw_txt_record_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_txt_record_t"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"nw_advertise_descriptor_set_txt_record_object","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_set_txt_record_object(_:_:)","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record_object(_:_:)","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_path_t":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_path_t","kind":"identifier"}],"abstract":[{"text":"An object that contains information about the properties of the network that a connection uses, or that are available to your app.","type":"text"}],"navigatorTitle":[{"text":"nw_path_t","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_path_t","title":"nw_path_t","type":"topic","url":"/documentation/network/nw_path_t"},"doc://com.apple.network/documentation/Network/nw_path_get_status(_:)":{"type":"topic","title":"nw_path_get_status(_:)","abstract":[{"type":"text","text":"Checks whether a path can be used by connections."}],"navigatorTitle":[{"text":"nw_path_get_status","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_path_get_status(_:)","kind":"symbol","url":"/documentation/network/nw_path_get_status(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_path_get_status","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_path_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_path_t"},{"text":") -> ","kind":"text"},{"text":"nw_path_status_t","kind":"typeIdentifier","preciseIdentifier":"c:@EA@nw_path_status_t"}]},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)":{"kind":"symbol","title":"nw_advertise_descriptor_set_txt_record(_:_:_:)","type":"topic","role":"symbol","url":"/documentation/network/nw_advertise_descriptor_set_txt_record(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_set_txt_record"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_set_txt_record"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","kind":"typeIdentifier","text":"nw_advertise_descriptor_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SV","kind":"typeIdentifier","text":"UnsafeRawPointer"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_set_txt_record(_:_:_:)","abstract":[{"type":"text","text":"Sets the TXT record as a raw buffer to advertise with the service."}]},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_get_include_txt_record"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_get_include_txt_record"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_browse_descriptor_t","text":"nw_browse_descriptor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_include_txt_record(_:)","title":"nw_browse_descriptor_get_include_txt_record(_:)","abstract":[{"type":"text","text":"Checks if the browse descriptor requires including associated TXT records with all results."}],"role":"symbol","url":"/documentation/network/nw_browse_descriptor_get_include_txt_record(_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)":{"type":"topic","abstract":[{"text":"Initializes a Bonjour service to advertise.","type":"text"}],"navigatorTitle":[{"text":"nw_advertise_descriptor_create_bonjour_service","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)","title":"nw_advertise_descriptor_create_bonjour_service(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_create_bonjour_service","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_create_bonjour_service(_:_:_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_get_application_service_name"}],"abstract":[],"kind":"symbol","type":"topic","url":"/documentation/network/nw_advertise_descriptor_get_application_service_name(_:)","title":"nw_advertise_descriptor_get_application_service_name(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_get_application_service_name"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"nw_advertise_descriptor_t","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">?"}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_application_service_name(_:)","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)":{"abstract":[{"type":"text","text":"Accesses the Bonjour service type set on a browse descriptor."}],"kind":"symbol","title":"nw_browse_descriptor_get_bonjour_service_type(_:)","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_get_bonjour_service_type(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_type"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_browse_descriptor_t","kind":"typeIdentifier","text":"nw_browse_descriptor_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_type"}],"role":"symbol","url":"/documentation/network/nw_browse_descriptor_get_bonjour_service_type(_:)"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)":{"title":"nw_advertise_descriptor_get_no_auto_rename(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_advertise_descriptor_get_no_auto_rename"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_advertise_descriptor_t","kind":"typeIdentifier","text":"nw_advertise_descriptor_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_get_no_auto_rename(_:)","url":"/documentation/network/nw_advertise_descriptor_get_no_auto_rename(_:)","abstract":[{"type":"text","text":"Checks whether the service prohibits automatic renaming in the event of a name conflict."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nw_advertise_descriptor_get_no_auto_rename"}],"role":"symbol"},"doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)":{"kind":"symbol","title":"nw_browse_descriptor_set_include_txt_record(_:_:)","type":"topic","abstract":[{"type":"text","text":"Requires including associated TXT records with all results generated for this service descriptor."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_browse_descriptor_set_include_txt_record"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_browse_descriptor_t","kind":"typeIdentifier","text":"nw_browse_descriptor_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"nw_browse_descriptor_set_include_txt_record"}],"url":"/documentation/network/nw_browse_descriptor_set_include_txt_record(_:_:)","identifier":"doc://com.apple.network/documentation/Network/nw_browse_descriptor_set_include_txt_record(_:_:)","role":"symbol"},"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)":{"type":"topic","abstract":[{"text":"Accesses the TXT record to advertise with the service.","type":"text"}],"navigatorTitle":[{"text":"nw_advertise_descriptor_copy_txt_record_object","kind":"identifier"}],"url":"/documentation/network/nw_advertise_descriptor_copy_txt_record_object(_:)","title":"nw_advertise_descriptor_copy_txt_record_object(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nw_advertise_descriptor_copy_txt_record_object","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nw_advertise_descriptor_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_advertise_descriptor_t"},{"text":") -> ","kind":"text"},{"text":"nw_txt_record_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@nw_txt_record_t"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.network/documentation/Network/nw_advertise_descriptor_copy_txt_record_object(_:)"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS","introducedAt":"12.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"12.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS","introducedAt":"10.14"},{"unavailable":false,"beta":false,"deprecated":false,"name":"tvOS","introducedAt":"12.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"watchOS","introducedAt":"5.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Function"},{"path":"/metadata/title","op":"replace","value":"nw_path_get_status"},{"path":"/metadata/symbolKind","op":"replace","value":"func"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"nw_path_get_status","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.network/documentation/Network"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"preciseIdentifier":"c:@EA@nw_path_status_t","kind":"typeIdentifier","text":"nw_path_status_t","identifier":"doc://com.apple.network/documentation/Network/nw_path_status_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"nw_path_get_status"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@nw_path_t","kind":"typeIdentifier","text":"nw_path_t","identifier":"doc://com.apple.network/documentation/Network/nw_path_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"path"},{"kind":"text","text":");"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]}},{"op":"replace","value":"nw_browse_descriptor_create_application_service","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_application_service(_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_browse_descriptor_create_application_service"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_application_service(_:)/fragments"},{"op":"replace","value":"nw_browse_descriptor_get_application_service_name","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_application_service_name(_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_browse_descriptor_get_application_service_name"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_application_service_name(_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_set_no_auto_rename","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_no_auto_rename(_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_advertise_descriptor_set_no_auto_rename"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_no_auto_rename(_:_:)/fragments"},{"op":"replace","value":"nw_browse_descriptor_get_bonjour_service_domain","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_browse_descriptor_get_bonjour_service_domain"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_domain(_:)/fragments"},{"op":"replace","value":"nw_path_status_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_path_status_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"nw_path_status_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/navigatorTitle"},{"op":"replace","value":"nw_browse_descriptor_create_bonjour_service","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/title"},{"op":"replace","value":[{"text":"nw_browse_descriptor_create_bonjour_service","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_create_bonjour_service(_:_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_create_application_service","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_application_service(_:)/title"},{"op":"replace","value":[{"text":"nw_advertise_descriptor_create_application_service","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_application_service(_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_set_txt_record_object","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record_object(_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_advertise_descriptor_set_txt_record_object"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record_object(_:_:)/fragments"},{"op":"replace","value":"nw_path_t","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_path_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"nw_path_t"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/navigatorTitle"},{"op":"replace","value":"nw_path_get_status","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_get_status(_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_path_get_status"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_get_status(_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_set_txt_record","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record(_:_:_:)/title"},{"op":"replace","value":[{"text":"nw_advertise_descriptor_set_txt_record","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_set_txt_record(_:_:_:)/fragments"},{"op":"replace","value":"nw_browse_descriptor_get_include_txt_record","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/title"},{"op":"replace","value":[{"text":"nw_browse_descriptor_get_include_txt_record","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_include_txt_record(_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_create_bonjour_service","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_bonjour_service(_:_:_:)/title"},{"op":"replace","value":[{"text":"nw_advertise_descriptor_create_bonjour_service","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_create_bonjour_service(_:_:_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_get_application_service_name","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_application_service_name(_:)/title"},{"op":"replace","value":[{"text":"nw_advertise_descriptor_get_application_service_name","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_application_service_name(_:)/fragments"},{"op":"replace","value":"nw_browse_descriptor_get_bonjour_service_type","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/title"},{"op":"replace","value":[{"text":"nw_browse_descriptor_get_bonjour_service_type","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_get_bonjour_service_type(_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_get_no_auto_rename","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_no_auto_rename(_:)/title"},{"op":"replace","value":[{"text":"nw_advertise_descriptor_get_no_auto_rename","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_get_no_auto_rename(_:)/fragments"},{"op":"replace","value":"nw_browse_descriptor_set_include_txt_record","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"nw_browse_descriptor_set_include_txt_record"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_set_include_txt_record(_:_:)/fragments"},{"op":"replace","value":"nw_advertise_descriptor_copy_txt_record_object","path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_copy_txt_record_object(_:)/title"},{"op":"replace","value":[{"text":"nw_advertise_descriptor_copy_txt_record_object","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_copy_txt_record_object(_:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}