{
  "abstract": [
    {
      "text": "A block that allows inspection of a list of interfaces.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_parameters_iterate_interfaces_block_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_parameters_iterate_interfaces_block_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_parameters_iterate_interfaces_block_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_parameters_iterate_interfaces_block_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_parameters_iterate_interfaces_block_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_parameters_iterate_interfaces_block_t"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_interface_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_interface_t",
              "text": "nw_interface_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Return true to continue iterating, or false to stop iterating.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_t": {
      "abstract": [
        {
          "text": "An interface that a network connection uses to send and receive data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_t"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_t",
      "type": "topic",
      "url": "/documentation/network/nw_interface_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_clear_prohibited_interface_types(_:)": {
      "abstract": [
        {
          "text": "Removes all prohibited interface types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_clear_prohibited_interface_types"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_clear_prohibited_interface_types(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_clear_prohibited_interface_types"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_clear_prohibited_interface_types(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_clear_prohibited_interface_types(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_copy_local_endpoint(_:)": {
      "abstract": [
        {
          "text": "Accesses the local IP address and port used for connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_copy_local_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_copy_local_endpoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_copy_local_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_copy_local_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_copy_local_endpoint(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_copy_required_interface(_:)": {
      "abstract": [
        {
          "text": "Accesses the interface required on connections, listeners, and browsers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_copy_required_interface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_copy_required_interface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_copy_required_interface"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_copy_required_interface(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_copy_required_interface(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_get_prohibit_constrained(_:)": {
      "abstract": [
        {
          "text": "Checks if connections, listeners, and browsers are prevented from using network paths marked as constrained by Low Data Mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_get_prohibit_constrained"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_get_prohibit_constrained(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_get_prohibit_constrained"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_get_prohibit_constrained(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_get_prohibit_constrained(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_get_prohibit_expensive(_:)": {
      "abstract": [
        {
          "text": "Checks if connections, listeners, and browsers are prevented from using network paths marked as expensive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_get_prohibit_expensive"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_get_prohibit_expensive(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_get_prohibit_expensive"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_get_prohibit_expensive(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_get_prohibit_expensive(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_get_required_interface_type(_:)": {
      "abstract": [
        {
          "text": "Accesses the interface type required on connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_get_required_interface_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_type_t",
          "text": "nw_interface_type_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_get_required_interface_type(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_get_required_interface_type"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_get_required_interface_type(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_get_required_interface_type(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_iterate_interface_types_block_t": {
      "abstract": [
        {
          "text": "A block that allows inspection of a list of interface types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_iterate_interface_types_block_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_iterate_interface_types_block_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_iterate_interface_types_block_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_iterate_interface_types_block_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_iterate_interface_types_block_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_iterate_interfaces_block_t": {
      "abstract": [
        {
          "text": "A block that allows inspection of a list of interfaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_iterate_interfaces_block_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_iterate_interfaces_block_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_iterate_interfaces_block_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_iterate_interfaces_block_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_iterate_interfaces_block_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_iterate_prohibited_interface_types(_:_:)": {
      "abstract": [
        {
          "text": "Examines the list of prohibited interface types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_iterate_prohibited_interface_types"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_type_t",
          "text": "nw_interface_type_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_iterate_prohibited_interface_types(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_iterate_prohibited_interface_types"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_iterate_prohibited_interface_types(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_iterate_prohibited_interface_types(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_prohibit_interface(_:_:)": {
      "abstract": [
        {
          "text": "Prevents connections and listeners from using a specific interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_prohibit_interface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_prohibit_interface(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_prohibit_interface"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_prohibit_interface(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_prohibit_interface(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_prohibit_interface_type(_:_:)": {
      "abstract": [
        {
          "text": "Prevents connections, listeners, and browsers from using a specific interface type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_prohibit_interface_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_type_t",
          "text": "nw_interface_type_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_prohibit_interface_type(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_prohibit_interface_type"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_prohibit_interface_type(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_prohibit_interface_type(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_require_interface(_:_:)": {
      "abstract": [
        {
          "text": "Sets a specific interface to require on connections, listeners, and browsers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_require_interface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_require_interface(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_require_interface"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_require_interface(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_require_interface(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_local_endpoint(_:_:)": {
      "abstract": [
        {
          "text": "Sets a specific local IP address and port to use for connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_local_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_local_endpoint(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_local_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_local_endpoint(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_local_endpoint(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_prohibit_constrained(_:_:)": {
      "abstract": [
        {
          "text": "Prevents connections, listeners, and browsers from using network paths marked as constrained by Low Data Mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_prohibit_constrained"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_prohibit_constrained(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_prohibit_constrained"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_prohibit_constrained(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_prohibit_constrained(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_prohibit_expensive(_:_:)": {
      "abstract": [
        {
          "text": "Prevents connections, listeners, and browsers from using network paths marked as expensive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_prohibit_expensive"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_prohibit_expensive(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_prohibit_expensive"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_prohibit_expensive(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_prohibit_expensive(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_required_interface_type(_:_:)": {
      "abstract": [
        {
          "text": "Sets an interface type to require on connections and listeners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_required_interface_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_type_t",
          "text": "nw_interface_type_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_required_interface_type(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_required_interface_type"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_required_interface_type(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_required_interface_type(_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selecting-Paths",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_parameters_set_required_interface_type(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_get_required_interface_type(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_require_interface(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_copy_required_interface(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_set_local_endpoint(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_copy_local_endpoint(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_set_prohibit_constrained(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_get_prohibit_constrained(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_set_prohibit_expensive(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_get_prohibit_expensive(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_prohibit_interface_type(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_clear_prohibited_interface_types(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_iterate_prohibited_interface_types(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_iterate_interface_types_block_t",
        "doc://com.apple.network/documentation/Network/nw_parameters_prohibit_interface(_:_:)"
      ],
      "title": "Selecting Paths"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_parameters_iterate_interfaces_block_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_iterate_interfaces_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_iterate_interfaces_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selecting-Paths",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_parameters_set_required_interface_type(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_get_required_interface_type(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_require_interface(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_copy_required_interface(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_set_local_endpoint(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_copy_local_endpoint(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_set_prohibit_constrained(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_get_prohibit_constrained(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_set_prohibit_expensive(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_get_prohibit_expensive(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_prohibit_interface_type(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_clear_prohibited_interface_types(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_iterate_prohibited_interface_types(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_iterate_interface_types_block_t",
                "doc://com.apple.network/documentation/Network/nw_parameters_prohibit_interface(_:_:)"
              ],
              "title": "Selecting Paths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFb(#*Q$objc(cs)NSObjectobjc(pl)OS_nw_interface)",
                    "text": "_Bool (^)(NSObject<OS_nw_interface> *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_parameters_iterate_interfaces_block_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_prohibit_interface(_:_:)/title",
          "value": "nw_parameters_prohibit_interface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_prohibit_interface(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_prohibit_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_prohibit_expensive(_:)/title",
          "value": "nw_parameters_get_prohibit_expensive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_prohibit_expensive(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_get_prohibit_expensive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_iterate_interfaces_block_t/title",
          "value": "nw_parameters_iterate_interfaces_block_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_iterate_interfaces_block_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_iterate_interfaces_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_iterate_interfaces_block_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_iterate_interfaces_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_prohibit_constrained(_:)/title",
          "value": "nw_parameters_get_prohibit_constrained"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_prohibit_constrained(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_get_prohibit_constrained"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_require_interface(_:_:)/title",
          "value": "nw_parameters_require_interface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_require_interface(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_require_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_iterate_interface_types_block_t/title",
          "value": "nw_parameters_iterate_interface_types_block_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_iterate_interface_types_block_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_iterate_interface_types_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_iterate_interface_types_block_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_iterate_interface_types_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_required_interface_type(_:)/title",
          "value": "nw_parameters_get_required_interface_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_required_interface_type(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_get_required_interface_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_iterate_prohibited_interface_types(_:_:)/title",
          "value": "nw_parameters_iterate_prohibited_interface_types"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_iterate_prohibited_interface_types(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_iterate_prohibited_interface_types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_copy_local_endpoint(_:)/title",
          "value": "nw_parameters_copy_local_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_copy_local_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_copy_local_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_prohibit_expensive(_:_:)/title",
          "value": "nw_parameters_set_prohibit_expensive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_prohibit_expensive(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_prohibit_expensive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_required_interface_type(_:_:)/title",
          "value": "nw_parameters_set_required_interface_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_required_interface_type(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_required_interface_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/title",
          "value": "nw_interface_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_local_endpoint(_:_:)/title",
          "value": "nw_parameters_set_local_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_local_endpoint(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_local_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_prohibit_interface_type(_:_:)/title",
          "value": "nw_parameters_prohibit_interface_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_prohibit_interface_type(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_prohibit_interface_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_clear_prohibited_interface_types(_:)/title",
          "value": "nw_parameters_clear_prohibited_interface_types"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_clear_prohibited_interface_types(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_clear_prohibited_interface_types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_copy_required_interface(_:)/title",
          "value": "nw_parameters_copy_required_interface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_copy_required_interface(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_copy_required_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_prohibit_constrained(_:_:)/title",
          "value": "nw_parameters_set_prohibit_constrained"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_prohibit_constrained(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_prohibit_constrained"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_parameters_iterate_interfaces_block_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_parameters_iterate_interfaces_block_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
