{
  "abstract": [
    {
      "text": "An object that contains information about the properties of the network that a connection uses, or that are available to your app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_path_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_path_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_path_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_path_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_path_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_path_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_path",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_path",
              "text": "OS_nw_path"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_path": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_path"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_path",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_path"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_path",
      "type": "topic",
      "url": "/documentation/network/os_nw_path"
    },
    "doc://com.apple.network/documentation/Network/nw_interface_t": {
      "abstract": [
        {
          "text": "An interface that a network connection uses to send and receive data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_interface_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_interface_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_interface_t"
        }
      ],
      "role": "symbol",
      "title": "nw_interface_t",
      "type": "topic",
      "url": "/documentation/network/nw_interface_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_copy_effective_local_endpoint(_:)": {
      "abstract": [
        {
          "text": "Accesses the local endpoint in use by a connection’s network path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_copy_effective_local_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_copy_effective_local_endpoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_copy_effective_local_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_path_copy_effective_local_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_copy_effective_local_endpoint(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_copy_effective_remote_endpoint(_:)": {
      "abstract": [
        {
          "text": "Accesses the remote endpoint in use by a connection’s network path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_copy_effective_remote_endpoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_copy_effective_remote_endpoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_copy_effective_remote_endpoint"
        }
      ],
      "role": "symbol",
      "title": "nw_path_copy_effective_remote_endpoint(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_copy_effective_remote_endpoint(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_enumerate_gateways(_:_:)": {
      "abstract": [
        {
          "text": "Enumerates the list of gateways configured on the interfaces available to a path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_enumerate_gateways"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_enumerate_gateways(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_enumerate_gateways"
        }
      ],
      "role": "symbol",
      "title": "nw_path_enumerate_gateways(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_enumerate_gateways(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_enumerate_gateways_block_t": {
      "abstract": [
        {
          "text": "A block that enumerates the gateways configured on the interfaces available to a path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_enumerate_gateways_block_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_enumerate_gateways_block_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_enumerate_gateways_block_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_enumerate_gateways_block_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_enumerate_gateways_block_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces(_:_:)": {
      "abstract": [
        {
          "text": "Enumerates the list of all interfaces available to the path, in order of preference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_enumerate_interfaces"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_enumerate_interfaces"
        }
      ],
      "role": "symbol",
      "title": "nw_path_enumerate_interfaces(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_enumerate_interfaces(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces_block_t": {
      "abstract": [
        {
          "text": "A block that enumerates the interfaces available to a path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_enumerate_interfaces_block_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces_block_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_enumerate_interfaces_block_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_enumerate_interfaces_block_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_enumerate_interfaces_block_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_get_status(_:)": {
      "abstract": [
        {
          "text": "Checks whether a path can be used by connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_get_status"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_path_status_t",
          "text": "nw_path_status_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_get_status(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_get_status"
        }
      ],
      "role": "symbol",
      "title": "nw_path_get_status(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_get_status(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_has_dns(_:)": {
      "abstract": [
        {
          "text": "Checks whether the path has a DNS server configured.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_has_dns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_has_dns(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_has_dns"
        }
      ],
      "role": "symbol",
      "title": "nw_path_has_dns(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_has_dns(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_has_ipv4(_:)": {
      "abstract": [
        {
          "text": "Checks whether the path can route IPv4 traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_has_ipv4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_has_ipv4(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_has_ipv4"
        }
      ],
      "role": "symbol",
      "title": "nw_path_has_ipv4(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_has_ipv4(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_has_ipv6(_:)": {
      "abstract": [
        {
          "text": "Checks whether the path can route IPv6 traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_has_ipv6"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_has_ipv6(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_has_ipv6"
        }
      ],
      "role": "symbol",
      "title": "nw_path_has_ipv6(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_has_ipv6(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_is_constrained(_:)": {
      "abstract": [
        {
          "text": "Checks whether the path uses an interface in Low Data Mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_is_constrained"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_is_constrained(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_is_constrained"
        }
      ],
      "role": "symbol",
      "title": "nw_path_is_constrained(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_is_constrained(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_is_equal(_:_:)": {
      "abstract": [
        {
          "text": "Compares if two paths are identical.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_is_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_is_equal(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_is_equal"
        }
      ],
      "role": "symbol",
      "title": "nw_path_is_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_is_equal(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_is_expensive(_:)": {
      "abstract": [
        {
          "text": "Checks whether the path uses an interface that is considered expensive, such as Cellular or a Personal Hotspot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_is_expensive"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_is_expensive(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_is_expensive"
        }
      ],
      "role": "symbol",
      "title": "nw_path_is_expensive(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_is_expensive(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_path_monitor_t": {
      "abstract": [
        {
          "text": "An observer that you use to monitor and react to network changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_monitor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_monitor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_monitor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_monitor_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_monitor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_status_t": {
      "abstract": [
        {
          "text": "Status values indicating whether a path can be used by connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_status_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_status_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_status_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_status_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_status_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_t": {
      "abstract": [
        {
          "text": "An object that contains information about the properties of the network that a connection uses, or that are available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_t"
        }
      ],
      "role": "symbol",
      "title": "nw_path_t",
      "type": "topic",
      "url": "/documentation/network/nw_path_t"
    },
    "doc://com.apple.network/documentation/Network/nw_path_uses_interface_type(_:_:)": {
      "abstract": [
        {
          "text": "Checks if connections using the path may send traffic over a specific interface type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_path_uses_interface_type"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_path_t",
          "text": "nw_path_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_interface_type_t",
          "text": "nw_interface_type_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_path_uses_interface_type(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_path_uses_interface_type"
        }
      ],
      "role": "symbol",
      "title": "nw_path_uses_interface_type(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_path_uses_interface_type(_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Checking-Path-Availability",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_path_get_status(_:)",
        "doc://com.apple.network/documentation/Network/nw_path_status_t"
      ],
      "title": "Checking Path Availability"
    },
    {
      "anchor": "Inspecting-Interfaces",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_path_uses_interface_type(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces_block_t",
        "doc://com.apple.network/documentation/Network/nw_path_enumerate_gateways(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_path_enumerate_gateways_block_t"
      ],
      "title": "Inspecting Interfaces"
    },
    {
      "anchor": "Checking-Path-Capabilities",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_path_has_ipv4(_:)",
        "doc://com.apple.network/documentation/Network/nw_path_has_ipv6(_:)",
        "doc://com.apple.network/documentation/Network/nw_path_has_dns(_:)",
        "doc://com.apple.network/documentation/Network/nw_path_is_constrained(_:)",
        "doc://com.apple.network/documentation/Network/nw_path_is_expensive(_:)"
      ],
      "title": "Checking Path Capabilities"
    },
    {
      "anchor": "Comparing-Paths",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_path_is_equal(_:_:)"
      ],
      "title": "Comparing Paths"
    },
    {
      "anchor": "Inspecting-Connected-Paths",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_path_copy_effective_local_endpoint(_:)",
        "doc://com.apple.network/documentation/Network/nw_path_copy_effective_remote_endpoint(_:)"
      ],
      "title": "Inspecting Connected Paths"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_path_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Checking-Path-Availability",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_get_status(_:)",
                "doc://com.apple.network/documentation/Network/nw_path_status_t"
              ],
              "title": "Checking Path Availability"
            },
            {
              "anchor": "Inspecting-Interfaces",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_uses_interface_type(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_path_enumerate_interfaces_block_t",
                "doc://com.apple.network/documentation/Network/nw_path_enumerate_gateways(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_path_enumerate_gateways_block_t"
              ],
              "title": "Inspecting Interfaces"
            },
            {
              "anchor": "Checking-Path-Capabilities",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_has_ipv4(_:)",
                "doc://com.apple.network/documentation/Network/nw_path_has_ipv6(_:)",
                "doc://com.apple.network/documentation/Network/nw_path_has_dns(_:)",
                "doc://com.apple.network/documentation/Network/nw_path_is_constrained(_:)",
                "doc://com.apple.network/documentation/Network/nw_path_is_expensive(_:)"
              ],
              "title": "Checking Path Capabilities"
            },
            {
              "anchor": "Comparing-Paths",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_is_equal(_:_:)"
              ],
              "title": "Comparing Paths"
            },
            {
              "anchor": "Inspecting-Connected-Paths",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_copy_effective_local_endpoint(_:)",
                "doc://com.apple.network/documentation/Network/nw_path_copy_effective_remote_endpoint(_:)"
              ],
              "title": "Inspecting Connected Paths"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Paths-and-Interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_path_monitor_t",
                "doc://com.apple.network/documentation/Network/nw_interface_t"
              ],
              "title": "Paths and Interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_path",
                    "text": "NSObject<OS_nw_path>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_path_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path/title",
          "value": "OS_nw_path"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_path/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_is_expensive(_:)/title",
          "value": "nw_path_is_expensive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_is_expensive(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_is_expensive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_copy_effective_local_endpoint(_:)/title",
          "value": "nw_path_copy_effective_local_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_copy_effective_local_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_copy_effective_local_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_gateways(_:_:)/title",
          "value": "nw_path_enumerate_gateways"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_gateways(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_enumerate_gateways"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_interfaces(_:_:)/title",
          "value": "nw_path_enumerate_interfaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_interfaces(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_enumerate_interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_has_ipv6(_:)/title",
          "value": "nw_path_has_ipv6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_has_ipv6(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_has_ipv6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_gateways_block_t/title",
          "value": "nw_path_enumerate_gateways_block_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_gateways_block_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_enumerate_gateways_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_gateways_block_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_enumerate_gateways_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/title",
          "value": "nw_path_status_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_status_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_uses_interface_type(_:_:)/title",
          "value": "nw_path_uses_interface_type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_uses_interface_type(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_uses_interface_type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_copy_effective_remote_endpoint(_:)/title",
          "value": "nw_path_copy_effective_remote_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_copy_effective_remote_endpoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_copy_effective_remote_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/title",
          "value": "nw_interface_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_interface_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_has_ipv4(_:)/title",
          "value": "nw_path_has_ipv4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_has_ipv4(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_has_ipv4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_interfaces_block_t/title",
          "value": "nw_path_enumerate_interfaces_block_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_interfaces_block_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_enumerate_interfaces_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_enumerate_interfaces_block_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_enumerate_interfaces_block_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_has_dns(_:)/title",
          "value": "nw_path_has_dns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_has_dns(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_has_dns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/title",
          "value": "nw_path_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_t/title",
          "value": "nw_path_monitor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_monitor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_monitor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_is_equal(_:_:)/title",
          "value": "nw_path_is_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_is_equal(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_is_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_is_constrained(_:)/title",
          "value": "nw_path_is_constrained"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_is_constrained(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_is_constrained"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_get_status(_:)/title",
          "value": "nw_path_get_status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_path_get_status(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_path_get_status"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_path_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_path_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
