{
  "abstract": [
    {
      "text": "Allows reusing local addresses and ports across connections.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_parameters_set_reuse_local_address(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_parameters_set_reuse_local_address",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_parameters_set_reuse_local_address"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_parameters_t",
        "text": "nw_parameters_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_parameters_set_reuse_local_address"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_parameters_set_reuse_local_address(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_parameters_set_reuse_local_address"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "parameters"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_parameters_t",
              "text": "nw_parameters_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "reuse_local_address"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_multipath_service_t": {
      "abstract": [
        {
          "text": "Modes in which a connection can support multipath protocols.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_multipath_service_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_multipath_service_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_multipath_service_t"
        }
      ],
      "role": "symbol",
      "title": "nw_multipath_service_t",
      "type": "topic",
      "url": "/documentation/network/nw_multipath_service_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t": {
      "abstract": [
        {
          "text": "Options for configuring how expired DNS answers should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_expired_dns_behavior_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_expired_dns_behavior_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_expired_dns_behavior_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_expired_dns_behavior_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_get_expired_dns_behavior(_:)": {
      "abstract": [
        {
          "text": "Checks the behavior for how expired DNS answers should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_get_expired_dns_behavior"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_parameters_expired_dns_behavior_t",
          "text": "nw_parameters_expired_dns_behavior_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_get_expired_dns_behavior(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_get_expired_dns_behavior"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_get_expired_dns_behavior(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_get_expired_dns_behavior(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_get_fast_open_enabled(_:)": {
      "abstract": [
        {
          "text": "Checks if sending application data with protocol handshakes is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_get_fast_open_enabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_get_fast_open_enabled(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_get_fast_open_enabled"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_get_fast_open_enabled(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_get_fast_open_enabled(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_get_multipath_service(_:)": {
      "abstract": [
        {
          "text": "Checks if multipath is enabled on a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_get_multipath_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_multipath_service_t",
          "text": "nw_multipath_service_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_get_multipath_service(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_get_multipath_service"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_get_multipath_service(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_get_multipath_service(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_get_prefer_no_proxy(_:)": {
      "abstract": [
        {
          "text": "Checks if proxies are ignored by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_get_prefer_no_proxy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_get_prefer_no_proxy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_get_prefer_no_proxy"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_get_prefer_no_proxy(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_get_prefer_no_proxy(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_get_service_class(_:)": {
      "abstract": [
        {
          "text": "Checks the level of service quality used for connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_get_service_class"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_get_service_class(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_get_service_class"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_get_service_class(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_get_service_class(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_requires_dnssec_validation(_:)": {
      "abstract": [
        {
          "text": "Checks whether a connection requires DNSSEC validation when resolving endpoints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_requires_dnssec_validation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_requires_dnssec_validation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_requires_dnssec_validation"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_requires_dnssec_validation(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_requires_dnssec_validation(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_expired_dns_behavior(_:_:)": {
      "abstract": [
        {
          "text": "Sets the behavior for how expired DNS answers should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_expired_dns_behavior"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_parameters_expired_dns_behavior_t",
          "text": "nw_parameters_expired_dns_behavior_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_expired_dns_behavior(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_expired_dns_behavior"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_expired_dns_behavior(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_expired_dns_behavior(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_fast_open_enabled(_:_:)": {
      "abstract": [
        {
          "text": "Enables sending application data with protocol handshakes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_fast_open_enabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_fast_open_enabled(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_fast_open_enabled"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_fast_open_enabled(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_fast_open_enabled(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_multipath_service(_:_:)": {
      "abstract": [
        {
          "text": "Enables multipath protocols to allow connections to use multiple interfaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_multipath_service"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_multipath_service_t",
          "text": "nw_multipath_service_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_multipath_service(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_multipath_service"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_multipath_service(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_multipath_service(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_prefer_no_proxy(_:_:)": {
      "abstract": [
        {
          "text": "Sets a Boolean that indicates that connections should ignore proxies when they are enabled on the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_prefer_no_proxy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_prefer_no_proxy(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_prefer_no_proxy"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_prefer_no_proxy(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_prefer_no_proxy(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_requires_dnssec_validation(_:_:)": {
      "abstract": [
        {
          "text": "Determines whether a connection requires DNSSEC validation when resolving endpoints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_requires_dnssec_validation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_requires_dnssec_validation(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_requires_dnssec_validation"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_requires_dnssec_validation(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_requires_dnssec_validation(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_reuse_local_address(_:_:)": {
      "abstract": [
        {
          "text": "Allows reusing local addresses and ports across connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_reuse_local_address"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_reuse_local_address(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_reuse_local_address"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_reuse_local_address(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_reuse_local_address(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_service_class(_:_:)": {
      "abstract": [
        {
          "text": "Sets a level of service quality to use for connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_service_class"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_service_class(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_service_class"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_service_class(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_service_class(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_t": {
      "abstract": [
        {
          "text": "An object that stores the protocols to use for connections, options for sending data, and network path constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_t"
    },
    "doc://com.apple.network/documentation/Network/nw_service_class_t": {
      "abstract": [
        {
          "text": "Levels of service quality that can be used with a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_service_class_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_service_class_t"
        }
      ],
      "role": "symbol",
      "title": "nw_service_class_t",
      "type": "topic",
      "url": "/documentation/network/nw_service_class_t"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-Connection-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_parameters_set_multipath_service(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_get_multipath_service(_:)",
        "doc://com.apple.network/documentation/Network/nw_multipath_service_t",
        "doc://com.apple.network/documentation/Network/nw_parameters_set_service_class(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_get_service_class(_:)",
        "doc://com.apple.network/documentation/Network/nw_service_class_t",
        "doc://com.apple.network/documentation/Network/nw_parameters_set_fast_open_enabled(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_get_fast_open_enabled(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_set_expired_dns_behavior(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_get_expired_dns_behavior(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t",
        "doc://com.apple.network/documentation/Network/nw_parameters_set_requires_dnssec_validation(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_requires_dnssec_validation(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_set_prefer_no_proxy(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_get_prefer_no_proxy(_:)"
      ],
      "title": "Customizing Connection Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_parameters_set_reuse_local_address"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_reuse_local_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-Connection-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_parameters_set_multipath_service(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_get_multipath_service(_:)",
                "doc://com.apple.network/documentation/Network/nw_multipath_service_t",
                "doc://com.apple.network/documentation/Network/nw_parameters_set_service_class(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_get_service_class(_:)",
                "doc://com.apple.network/documentation/Network/nw_service_class_t",
                "doc://com.apple.network/documentation/Network/nw_parameters_set_fast_open_enabled(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_get_fast_open_enabled(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_set_expired_dns_behavior(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_get_expired_dns_behavior(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_expired_dns_behavior_t",
                "doc://com.apple.network/documentation/Network/nw_parameters_set_requires_dnssec_validation(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_requires_dnssec_validation(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_set_prefer_no_proxy(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_get_prefer_no_proxy(_:)"
              ],
              "title": "Customizing Connection Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_parameters_set_reuse_local_address"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_parameters_t",
                    "text": "nw_parameters_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "parameters"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:b",
                    "text": "bool"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "reuse_local_address"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_service_class(_:_:)/title",
          "value": "nw_parameters_set_service_class"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_service_class(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_service_class"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_fast_open_enabled(_:)/title",
          "value": "nw_parameters_get_fast_open_enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_fast_open_enabled(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_get_fast_open_enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_service_class(_:)/title",
          "value": "nw_parameters_get_service_class"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_service_class(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_get_service_class"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_t/title",
          "value": "nw_parameters_expired_dns_behavior_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_expired_dns_behavior_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_expired_dns_behavior_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_expired_dns_behavior_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_multipath_service(_:)/title",
          "value": "nw_parameters_get_multipath_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_multipath_service(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_get_multipath_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_fast_open_enabled(_:_:)/title",
          "value": "nw_parameters_set_fast_open_enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_fast_open_enabled(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_fast_open_enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/title",
          "value": "nw_parameters_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_expired_dns_behavior(_:_:)/title",
          "value": "nw_parameters_set_expired_dns_behavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_expired_dns_behavior(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_expired_dns_behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_prefer_no_proxy(_:_:)/title",
          "value": "nw_parameters_set_prefer_no_proxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_prefer_no_proxy(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_prefer_no_proxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_requires_dnssec_validation(_:_:)/title",
          "value": "nw_parameters_set_requires_dnssec_validation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_requires_dnssec_validation(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_requires_dnssec_validation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_reuse_local_address(_:_:)/title",
          "value": "nw_parameters_set_reuse_local_address"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_reuse_local_address(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_reuse_local_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_prefer_no_proxy(_:)/title",
          "value": "nw_parameters_get_prefer_no_proxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_prefer_no_proxy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_get_prefer_no_proxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_t/title",
          "value": "nw_service_class_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_service_t/title",
          "value": "nw_multipath_service_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_service_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_service_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_multipath_service_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_multipath_service_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_expired_dns_behavior(_:)/title",
          "value": "nw_parameters_get_expired_dns_behavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_expired_dns_behavior(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_get_expired_dns_behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_multipath_service(_:_:)/title",
          "value": "nw_parameters_set_multipath_service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_multipath_service(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_multipath_service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_requires_dnssec_validation(_:)/title",
          "value": "nw_parameters_requires_dnssec_validation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_requires_dnssec_validation(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_requires_dnssec_validation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_parameters_set_reuse_local_address(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_parameters_set_reuse_local_address(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
