{
  "abstract": [
    {
      "text": "Adds a reference count to a Network.framework object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.network/documentation/Network/nw_retain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_retain",
    "fragments": [
      {
        "kind": "identifier",
        "text": "nw_retain"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_retain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_retain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "nw_retain"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "obj"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/os/1524246-os_retain": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/1524246-os_retain",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_retain",
      "type": "topic",
      "url": "/documentation/os/1524246-os_retain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_object_t": {
      "abstract": [
        {
          "text": "The generic type for objects in the Network framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_object_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_object_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_object_t"
        }
      ],
      "role": "symbol",
      "title": "nw_object_t",
      "type": "topic",
      "url": "/documentation/network/nw_object_t"
    },
    "doc://com.apple.network/documentation/Network/nw_release": {
      "abstract": [
        {
          "text": "Releases a reference count on a Network.framework object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "nw_release"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_release",
      "kind": "symbol",
      "role": "symbol",
      "title": "nw_release",
      "type": "topic",
      "url": "/documentation/network/nw_release"
    },
    "doc://com.apple.network/documentation/Network/nw_retain": {
      "abstract": [
        {
          "text": "Adds a reference count to a Network.framework object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "nw_retain"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_retain",
      "kind": "symbol",
      "role": "symbol",
      "title": "nw_retain",
      "type": "topic",
      "url": "/documentation/network/nw_retain"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/os/1524246-os_retain"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Memory-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_release",
        "doc://com.apple.network/documentation/Network/nw_object_t"
      ],
      "title": "Memory Management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_object_t/title",
          "value": "nw_object_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_object_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_object_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_object_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_retain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
