{
  "abstract": [
    {
      "text": "Initializes a DNS-over-TLS resolver configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_resolver_config_create_tls(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@nw_resolver_config_create_tls",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_resolver_config_create_tls"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_endpoint_t",
        "text": "nw_endpoint_t"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@nw_resolver_config_t",
        "text": "nw_resolver_config_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_resolver_config_create_tls"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "nw_resolver_config_create_tls(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_resolver_config_create_tls"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "server_endpoint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_endpoint_t",
              "text": "nw_endpoint_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_resolver_config_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_resolver_config_t",
              "text": "nw_resolver_config_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The hostname of the provided endpoint will be used to validate the TLS certificate of the server. See ",
                  "type": "text"
                },
                {
                  "identifier": "https://tools.ietf.org/html/rfc7858",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for more details.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "server_endpoint"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_endpoint_t": {
      "abstract": [
        {
          "text": "A local or remote endpoint in a network connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_endpoint_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_endpoint_t"
        }
      ],
      "role": "symbol",
      "title": "nw_endpoint_t",
      "type": "topic",
      "url": "/documentation/network/nw_endpoint_t"
    },
    "doc://com.apple.network/documentation/Network/nw_privacy_context_require_encrypted_name_resolution(_:_:_:)": {
      "abstract": [
        {
          "text": "Requires that any DNS name resolution for connections associated with this context use encrypted transports, such as TLS or HTTPS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_privacy_context_require_encrypted_name_resolution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_privacy_context_t",
          "text": "nw_privacy_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolver_config_t",
          "text": "nw_resolver_config_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_privacy_context_require_encrypted_name_resolution(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_privacy_context_require_encrypted_name_resolution"
        }
      ],
      "role": "symbol",
      "title": "nw_privacy_context_require_encrypted_name_resolution(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_privacy_context_require_encrypted_name_resolution(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolver_config_add_server_address(_:_:)": {
      "abstract": [
        {
          "text": "Provides a well-known DNS server address to use instead of looking up the address dynamically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolver_config_add_server_address"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolver_config_t",
          "text": "nw_resolver_config_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolver_config_add_server_address(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolver_config_add_server_address"
        }
      ],
      "role": "symbol",
      "title": "nw_resolver_config_add_server_address(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolver_config_add_server_address(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolver_config_create_https(_:)": {
      "abstract": [
        {
          "text": "Initializes a DNS-over-HTTPS resolver configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolver_config_create_https"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolver_config_t",
          "text": "nw_resolver_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolver_config_create_https(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolver_config_create_https"
        }
      ],
      "role": "symbol",
      "title": "nw_resolver_config_create_https(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolver_config_create_https(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolver_config_create_tls(_:)": {
      "abstract": [
        {
          "text": "Initializes a DNS-over-TLS resolver configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolver_config_create_tls"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_resolver_config_t",
          "text": "nw_resolver_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolver_config_create_tls(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolver_config_create_tls"
        }
      ],
      "role": "symbol",
      "title": "nw_resolver_config_create_tls(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_resolver_config_create_tls(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_resolver_config_t": {
      "abstract": [
        {
          "text": "A DNS server configuration that uses TLS or HTTPS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_resolver_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_resolver_config_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_resolver_config_t"
        }
      ],
      "role": "symbol",
      "title": "nw_resolver_config_t",
      "type": "topic",
      "url": "/documentation/network/nw_resolver_config_t"
    },
    "https://tools.ietf.org/html/rfc7858": {
      "identifier": "https://tools.ietf.org/html/rfc7858",
      "title": "RFC 7858",
      "titleInlineContent": [
        {
          "text": "RFC 7858",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://tools.ietf.org/html/rfc7858"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Requiring-Encrypted-DNS",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_privacy_context_require_encrypted_name_resolution(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_resolver_config_t",
        "doc://com.apple.network/documentation/Network/nw_resolver_config_create_https(_:)",
        "doc://com.apple.network/documentation/Network/nw_resolver_config_add_server_address(_:_:)"
      ],
      "title": "Requiring Encrypted DNS"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_resolver_config_create_tls"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_create_tls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Requiring-Encrypted-DNS",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_privacy_context_require_encrypted_name_resolution(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_resolver_config_t",
                "doc://com.apple.network/documentation/Network/nw_resolver_config_create_https(_:)",
                "doc://com.apple.network/documentation/Network/nw_resolver_config_add_server_address(_:_:)"
              ],
              "title": "Requiring Encrypted DNS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_resolver_config_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_resolver_config_t",
                    "text": "nw_resolver_config_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_resolver_config_create_tls"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.network/documentation/Network/nw_endpoint_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@nw_endpoint_t",
                    "text": "nw_endpoint_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "server_endpoint"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The hostname of the provided endpoint will be used to validate the TLS certificate of the server. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "https://tools.ietf.org/html/rfc7858",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for more details.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "server_endpoint"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/title",
          "value": "nw_endpoint_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_endpoint_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_endpoint_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_create_tls(_:)/title",
          "value": "nw_resolver_config_create_tls"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_create_tls(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_create_tls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_create_https(_:)/title",
          "value": "nw_resolver_config_create_https"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_create_https(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_create_https"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_t/title",
          "value": "nw_resolver_config_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_add_server_address(_:_:)/title",
          "value": "nw_resolver_config_add_server_address"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_resolver_config_add_server_address(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_resolver_config_add_server_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_require_encrypted_name_resolution(_:_:_:)/title",
          "value": "nw_privacy_context_require_encrypted_name_resolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_privacy_context_require_encrypted_name_resolution(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_privacy_context_require_encrypted_name_resolution"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_resolver_config_create_tls(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_resolver_config_create_tls(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
