{
  "abstract": [
    {
      "text": "A single relay server you can chain together with other servers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_relay_hop_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_relay_hop_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_relay_hop_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_relay_hop_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_relay_hop_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_relay_hop_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_relay_hop",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_relay_hop",
              "text": "OS_nw_relay_hop"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Relay servers are secure HTTP proxies that allow proxying TCP traffic using the ",
              "type": "text"
            },
            {
              "code": "CONNECT",
              "type": "codeVoice"
            },
            {
              "text": " method and UDP traffic using the ",
              "type": "text"
            },
            {
              "code": "connect-udp",
              "type": "codeVoice"
            },
            {
              "text": " protocol defined in ",
              "type": "text"
            },
            {
              "identifier": "https://www.rfc-editor.org/rfc/rfc9298.html",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_relay_hop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_relay_hop"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_relay_hop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_relay_hop"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_relay_hop",
      "type": "topic",
      "url": "/documentation/network/os_nw_relay_hop"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_create_http_connect(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a legacy HTTP CONNECT configuration for a proxy server accessible using HTTP/1.1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_http_connect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_create_http_connect(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_http_connect"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_create_http_connect(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_create_http_connect(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_create_oblivious_http(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Initializes an Oblivious HTTP proxy configuration using a relay and a gateway.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_oblivious_http"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_relay_hop_t",
          "text": "nw_relay_hop_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_create_oblivious_http(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_oblivious_http"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_create_oblivious_http(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_create_oblivious_http(_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_create_relay(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a proxy configuration with one or two relay hops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_relay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_relay_hop_t",
          "text": "nw_relay_hop_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_relay_hop_t",
          "text": "nw_relay_hop_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_create_relay(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_relay"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_create_relay(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_create_relay(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_proxy_config_create_socksv5(_:)": {
      "abstract": [
        {
          "text": "Initializes a SOCKSv5 proxy configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_socksv5"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_proxy_config_t",
          "text": "nw_proxy_config_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_proxy_config_create_socksv5(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_proxy_config_create_socksv5"
        }
      ],
      "role": "symbol",
      "title": "nw_proxy_config_create_socksv5(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_proxy_config_create_socksv5(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_relay_hop_add_additional_http_header_field(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an HTTP header name and value pair to send as part of ",
          "type": "text"
        },
        {
          "code": "CONNECT",
          "type": "codeVoice"
        },
        {
          "text": " requests to the relay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_relay_hop_add_additional_http_header_field"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_relay_hop_t",
          "text": "nw_relay_hop_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_relay_hop_add_additional_http_header_field(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_relay_hop_add_additional_http_header_field"
        }
      ],
      "role": "symbol",
      "title": "nw_relay_hop_add_additional_http_header_field(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_relay_hop_add_additional_http_header_field(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_relay_hop_create(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a configuration for a secure relay accessible using HTTP/3, with an optional HTTP/2 fallback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_relay_hop_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_endpoint_t",
          "text": "nw_endpoint_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_relay_hop_t",
          "text": "nw_relay_hop_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_relay_hop_create(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_relay_hop_create"
        }
      ],
      "role": "symbol",
      "title": "nw_relay_hop_create(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_relay_hop_create(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_relay_hop_t": {
      "abstract": [
        {
          "text": "A single relay server you can chain together with other servers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_relay_hop_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_relay_hop_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_relay_hop_t"
        }
      ],
      "role": "symbol",
      "title": "nw_relay_hop_t",
      "type": "topic",
      "url": "/documentation/network/nw_relay_hop_t"
    },
    "https://www.rfc-editor.org/rfc/rfc9298.html": {
      "identifier": "https://www.rfc-editor.org/rfc/rfc9298.html",
      "title": "RFC 9298",
      "titleInlineContent": [
        {
          "text": "RFC 9298",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.rfc-editor.org/rfc/rfc9298.html"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Proxy-Configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_proxy_config_create_relay(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_proxy_config_create_oblivious_http(_:_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_proxy_config_create_http_connect(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_proxy_config_create_socksv5(_:)"
      ],
      "title": "Creating Proxy Configurations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-Relay-Hops",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_relay_hop_create(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_relay_hop_add_additional_http_header_field(_:_:_:)"
      ],
      "title": "Configuring Relay Hops"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_relay_hop_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_relay_hop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_relay_hop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-Relay-Hops",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_relay_hop_create(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_relay_hop_add_additional_http_header_field(_:_:_:)"
              ],
              "title": "Configuring Relay Hops"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Proxy-Configurations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_proxy_config_create_relay(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_proxy_config_create_oblivious_http(_:_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_proxy_config_create_http_connect(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_proxy_config_create_socksv5(_:)"
              ],
              "title": "Creating Proxy Configurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_relay_hop",
                    "text": "NSObject<OS_nw_relay_hop>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_relay_hop_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_http_connect(_:_:)/title",
          "value": "nw_proxy_config_create_http_connect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_http_connect(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_create_http_connect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_relay_hop_t/title",
          "value": "nw_relay_hop_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_relay_hop_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_relay_hop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_relay_hop_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_relay_hop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_socksv5(_:)/title",
          "value": "nw_proxy_config_create_socksv5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_socksv5(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_create_socksv5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_relay(_:_:)/title",
          "value": "nw_proxy_config_create_relay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_relay(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_create_relay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_relay_hop_create(_:_:_:)/title",
          "value": "nw_relay_hop_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_relay_hop_create(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_relay_hop_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_oblivious_http(_:_:_:_:)/title",
          "value": "nw_proxy_config_create_oblivious_http"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_proxy_config_create_oblivious_http(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_proxy_config_create_oblivious_http"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_relay_hop/title",
          "value": "OS_nw_relay_hop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_relay_hop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_relay_hop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_relay_hop/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_relay_hop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_relay_hop_add_additional_http_header_field(_:_:_:)/title",
          "value": "nw_relay_hop_add_additional_http_header_field"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_relay_hop_add_additional_http_header_field(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_relay_hop_add_additional_http_header_field"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_relay_hop_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_relay_hop_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
