{
  "abstract": [
    {
      "text": "Responsive user-data traffic.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_service_class_responsive_data"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@nw_service_class_t@nw_service_class_responsive_data",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_service_class_responsive_data"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@nw_service_class_t",
        "text": "nw_service_class_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_service_class_responsive_data"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "nw_service_class_responsive_data"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_service_class_responsive_data"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_service_class_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@nw_service_class_t",
              "text": "nw_service_class_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_service_class_background": {
      "abstract": [
        {
          "text": "Bulk traffic, or traffic that can be deprioritized behind foreground traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_service_class_background"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_service_class_background",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_service_class_background"
        }
      ],
      "role": "symbol",
      "title": "nw_service_class_background",
      "type": "topic",
      "url": "/documentation/network/nw_service_class_background"
    },
    "doc://com.apple.network/documentation/Network/nw_service_class_best_effort": {
      "abstract": [
        {
          "text": "Default priority traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_service_class_best_effort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_service_class_best_effort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_service_class_best_effort"
        }
      ],
      "role": "symbol",
      "title": "nw_service_class_best_effort",
      "type": "topic",
      "url": "/documentation/network/nw_service_class_best_effort"
    },
    "doc://com.apple.network/documentation/Network/nw_service_class_interactive_video": {
      "abstract": [
        {
          "text": "Interactive video traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_service_class_interactive_video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_service_class_interactive_video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_service_class_interactive_video"
        }
      ],
      "role": "symbol",
      "title": "nw_service_class_interactive_video",
      "type": "topic",
      "url": "/documentation/network/nw_service_class_interactive_video"
    },
    "doc://com.apple.network/documentation/Network/nw_service_class_interactive_voice": {
      "abstract": [
        {
          "text": "Interactive voice traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_service_class_interactive_voice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_service_class_interactive_voice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_service_class_interactive_voice"
        }
      ],
      "role": "symbol",
      "title": "nw_service_class_interactive_voice",
      "type": "topic",
      "url": "/documentation/network/nw_service_class_interactive_voice"
    },
    "doc://com.apple.network/documentation/Network/nw_service_class_responsive_data": {
      "abstract": [
        {
          "text": "Responsive user-data traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_service_class_responsive_data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_service_class_responsive_data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_service_class_responsive_data"
        }
      ],
      "role": "symbol",
      "title": "nw_service_class_responsive_data",
      "type": "topic",
      "url": "/documentation/network/nw_service_class_responsive_data"
    },
    "doc://com.apple.network/documentation/Network/nw_service_class_signaling": {
      "abstract": [
        {
          "text": "Signaling control traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_service_class_signaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_service_class_t",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_service_class_signaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_service_class_signaling"
        }
      ],
      "role": "symbol",
      "title": "nw_service_class_signaling",
      "type": "topic",
      "url": "/documentation/network/nw_service_class_signaling"
    },
    "doc://com.apple.network/documentation/Network/nw_service_class_t": {
      "abstract": [
        {
          "text": "Levels of service quality that can be used with a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_service_class_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_service_class_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_service_class_t"
        }
      ],
      "role": "symbol",
      "title": "nw_service_class_t",
      "type": "topic",
      "url": "/documentation/network/nw_service_class_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Service-classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_service_class_best_effort",
        "doc://com.apple.network/documentation/Network/nw_service_class_background",
        "doc://com.apple.network/documentation/Network/nw_service_class_interactive_video",
        "doc://com.apple.network/documentation/Network/nw_service_class_interactive_voice",
        "doc://com.apple.network/documentation/Network/nw_service_class_signaling"
      ],
      "title": "Service classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_service_class_responsive_data"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_responsive_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network",
                "doc://com.apple.network/documentation/Network/nw_service_class_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Service-classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_service_class_best_effort",
                "doc://com.apple.network/documentation/Network/nw_service_class_background",
                "doc://com.apple.network/documentation/Network/nw_service_class_interactive_video",
                "doc://com.apple.network/documentation/Network/nw_service_class_interactive_voice",
                "doc://com.apple.network/documentation/Network/nw_service_class_signaling"
              ],
              "title": "Service classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "nw_service_class_responsive_data"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_best_effort/title",
          "value": "nw_service_class_best_effort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_best_effort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_best_effort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_responsive_data/title",
          "value": "nw_service_class_responsive_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_responsive_data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_responsive_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_t/title",
          "value": "nw_service_class_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_interactive_video/title",
          "value": "nw_service_class_interactive_video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_interactive_video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_interactive_video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_interactive_voice/title",
          "value": "nw_service_class_interactive_voice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_interactive_voice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_interactive_voice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_signaling/title",
          "value": "nw_service_class_signaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_signaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_signaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_background/title",
          "value": "nw_service_class_background"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_service_class_background/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_service_class_background"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_service_class_responsive_data"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_service_class_responsive_data"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
