{
  "abstract": [
    {
      "text": "A dictionary representing a TXT record in a DNS packet.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_txt_record_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@nw_txt_record_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_txt_record_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_txt_record_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "nw_txt_record_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_txt_record_t"
            },
            {
              "kind": "text",
              "text": " = any "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/OS_nw_txt_record",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)OS_nw_txt_record",
              "text": "OS_nw_txt_record"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_txt_record": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_txt_record"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_txt_record",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_txt_record"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_txt_record",
      "type": "topic",
      "url": "/documentation/network/os_nw_txt_record"
    },
    "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t": {
      "abstract": [
        {
          "text": "A description used to advertise the Bonjour service that a listener provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_advertise_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_advertise_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_advertise_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t": {
      "abstract": [
        {
          "text": "A service description used to discover Bonjour services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_descriptor_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_descriptor_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_descriptor_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_change_t": {
      "abstract": [
        {
          "text": "Flags describing ways in which discovered services can change between specific results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_change_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_change_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_change_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_change_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t": {
      "abstract": [
        {
          "text": "A handler that enumerates the interfaces associated with a discovered service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_enumerate_interface_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_enumerate_interface_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_enumerate_interface_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_enumerate_interface_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browse_result_t": {
      "abstract": [
        {
          "text": "A discovered service and metadata about the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browse_result_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browse_result_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browse_result_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browse_result_t",
      "type": "topic",
      "url": "/documentation/network/nw_browse_result_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers updates about discovered services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_browse_results_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_browse_results_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_browse_results_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_browse_results_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers browser state updates with associated errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_browser_t": {
      "abstract": [
        {
          "text": "An object you use to browse for available network services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_browser_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_browser_t"
        }
      ],
      "role": "symbol",
      "title": "nw_browser_t",
      "type": "topic",
      "url": "/documentation/network/nw_browser_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives Boolean state updates from a connection, such as viability and better path state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_boolean_event_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_boolean_event_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_boolean_event_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_boolean_event_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_new_connection_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_new_connection_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_new_connection_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_new_connection_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives inbound messages from members of the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_receive_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_receive_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_receive_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_receive_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t": {
      "abstract": [
        {
          "text": "A completion to notify you when data has been processed and sent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_completion_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_send_completion_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_send_completion_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_send_completion_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t": {
      "abstract": [
        {
          "text": "A handler that receives connection group state updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_changed_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_state_changed_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_state_changed_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_state_changed_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_group_t": {
      "abstract": [
        {
          "text": "An object you use to communicate with a group of endpoints, such as an IP multicast group on a local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_group_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_group_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_group_t"
    },
    "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers network path updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_path_event_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_connection_path_event_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_connection_path_event_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_connection_path_event_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_access_bytes(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the raw bytes contained within a TXT record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_access_bytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_access_bytes_t",
          "text": "nw_txt_record_access_bytes_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_access_bytes(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_access_bytes"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_access_bytes(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_access_bytes(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_access_bytes_t": {
      "abstract": [
        {
          "text": "A block that provides access to the raw bytes of a TXT record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_access_bytes_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_access_bytes_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_access_bytes_t"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_access_bytes_t",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_access_bytes_t"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_access_key(_:_:_:)": {
      "abstract": [
        {
          "text": "Accesses the value for a specific key in a TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_access_key"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_access_key_t",
          "text": "nw_txt_record_access_key_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_access_key(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_access_key"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_access_key(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_access_key(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_access_key_t": {
      "abstract": [
        {
          "text": "A block that returns a value in a TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_access_key_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_access_key_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_access_key_t"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_access_key_t",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_access_key_t"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_applier_t": {
      "abstract": [
        {
          "text": "A block that iterates over values and keys in a TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_applier_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_applier_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_applier_t"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_applier_t",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_applier_t"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_apply(_:_:)": {
      "abstract": [
        {
          "text": "Iterates through all keys in a TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_apply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_applier_t",
          "text": "nw_txt_record_applier_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_apply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_apply"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_apply(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_apply(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_copy(_:)": {
      "abstract": [
        {
          "text": "Performs a deep copy of a TXT record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_copy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_copy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_copy"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_copy(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_copy(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_create_dictionary()": {
      "abstract": [
        {
          "text": "Initializes a TXT record as a dictionary of strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_create_dictionary"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_create_dictionary()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_create_dictionary"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_create_dictionary()",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_create_dictionary()"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_create_with_bytes(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a TXT record with raw bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_create_with_bytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_create_with_bytes(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_create_with_bytes"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_create_with_bytes(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_create_with_bytes(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_find_key(_:_:)": {
      "abstract": [
        {
          "text": "Checks the status of value associated with a key in a TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_txt_record_find_key_t",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_find_key(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_find_key(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t": {
      "abstract": [
        {
          "text": "Status values describing what kind of value is stored in a TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_find_key_t",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_find_key_t"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_get_key_count(_:)": {
      "abstract": [
        {
          "text": "Accesses the number of keys stored in the TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_get_key_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_get_key_count(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_get_key_count"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_get_key_count(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_get_key_count(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_is_dictionary(_:)": {
      "abstract": [
        {
          "text": "Checks whether a TXT record conforms to a dictionary format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_is_dictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_is_dictionary(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_is_dictionary"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_is_dictionary(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_is_dictionary(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_is_equal(_:_:)": {
      "abstract": [
        {
          "text": "Checks whether two TXT records are equivalent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_is_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_is_equal(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_is_equal"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_is_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_is_equal(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_remove_key(_:_:)": {
      "abstract": [
        {
          "text": "Removes a data value in a TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_remove_key"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_remove_key(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_remove_key"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_remove_key(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_remove_key(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_set_key(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a data value in a TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_set_key"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_txt_record_t",
          "text": "nw_txt_record_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_set_key(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_set_key"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_set_key(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_set_key(_:_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_t": {
      "abstract": [
        {
          "text": "A dictionary representing a TXT record in a DNS packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_t"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_t",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_advertise_descriptor_t",
        "doc://com.apple.network/documentation/Network/nw_browse_descriptor_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_change_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_enumerate_interface_t",
        "doc://com.apple.network/documentation/Network/nw_browse_result_t",
        "doc://com.apple.network/documentation/Network/nw_browser_browse_results_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_browser_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_browser_t",
        "doc://com.apple.network/documentation/Network/nw_connection_boolean_event_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_new_connection_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_receive_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_send_completion_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_state_changed_handler_t",
        "doc://com.apple.network/documentation/Network/nw_connection_group_t",
        "doc://com.apple.network/documentation/Network/nw_connection_path_event_handler_t"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-TXT-Records",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_txt_record_create_dictionary()",
        "doc://com.apple.network/documentation/Network/nw_txt_record_create_with_bytes(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_txt_record_copy(_:)",
        "doc://com.apple.network/documentation/Network/nw_txt_record_set_key(_:_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_txt_record_remove_key(_:_:)"
      ],
      "title": "Creating TXT Records"
    },
    {
      "anchor": "Examining-TXT-Records",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_txt_record_is_dictionary(_:)",
        "doc://com.apple.network/documentation/Network/nw_txt_record_get_key_count(_:)",
        "doc://com.apple.network/documentation/Network/nw_txt_record_apply(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_txt_record_applier_t",
        "doc://com.apple.network/documentation/Network/nw_txt_record_access_key(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_txt_record_access_key_t",
        "doc://com.apple.network/documentation/Network/nw_txt_record_find_key(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t",
        "doc://com.apple.network/documentation/Network/nw_txt_record_is_equal(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_txt_record_access_bytes(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_txt_record_access_bytes_t"
      ],
      "title": "Examining TXT Records"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_txt_record_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-TXT-Records",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_txt_record_create_dictionary()",
                "doc://com.apple.network/documentation/Network/nw_txt_record_create_with_bytes(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_txt_record_copy(_:)",
                "doc://com.apple.network/documentation/Network/nw_txt_record_set_key(_:_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_txt_record_remove_key(_:_:)"
              ],
              "title": "Creating TXT Records"
            },
            {
              "anchor": "Examining-TXT-Records",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_txt_record_is_dictionary(_:)",
                "doc://com.apple.network/documentation/Network/nw_txt_record_get_key_count(_:)",
                "doc://com.apple.network/documentation/Network/nw_txt_record_apply(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_txt_record_applier_t",
                "doc://com.apple.network/documentation/Network/nw_txt_record_access_key(_:_:_:)",
                "doc://com.apple.network/documentation/Network/nw_txt_record_access_key_t",
                "doc://com.apple.network/documentation/Network/nw_txt_record_find_key(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t",
                "doc://com.apple.network/documentation/Network/nw_txt_record_is_equal(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_txt_record_access_bytes(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_txt_record_access_bytes_t"
              ],
              "title": "Examining TXT Records"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_nw_txt_record",
                    "text": "NSObject<OS_nw_txt_record>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "nw_txt_record_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/title",
          "value": "nw_browse_result_change_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_change_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_change_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_access_key_t/title",
          "value": "nw_txt_record_access_key_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_access_key_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_access_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_access_key_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_access_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/title",
          "value": "nw_browse_result_enumerate_interface_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_enumerate_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_enumerate_interface_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_enumerate_interface_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/title",
          "value": "nw_advertise_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_advertise_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_advertise_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/title",
          "value": "nw_browse_descriptor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_descriptor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_descriptor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/title",
          "value": "nw_browser_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_set_key(_:_:_:_:)/title",
          "value": "nw_txt_record_set_key"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_set_key(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_set_key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/title",
          "value": "nw_connection_group_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_t/title",
          "value": "nw_txt_record_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/title",
          "value": "nw_browse_result_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browse_result_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browse_result_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_access_bytes(_:_:)/title",
          "value": "nw_txt_record_access_bytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_access_bytes(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_access_bytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/title",
          "value": "nw_browser_browse_results_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_browse_results_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_browse_results_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_browse_results_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/title",
          "value": "nw_connection_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/title",
          "value": "nw_connection_path_event_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_path_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_path_event_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_path_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/title",
          "value": "nw_browser_state_changed_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_browser_state_changed_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_browser_state_changed_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/title",
          "value": "nw_connection_group_send_completion_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_send_completion_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_send_completion_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_t/title",
          "value": "nw_txt_record_find_key_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key(_:_:)/title",
          "value": "nw_txt_record_find_key"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_is_dictionary(_:)/title",
          "value": "nw_txt_record_is_dictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_is_dictionary(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_is_dictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_remove_key(_:_:)/title",
          "value": "nw_txt_record_remove_key"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_remove_key(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_remove_key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_is_equal(_:_:)/title",
          "value": "nw_txt_record_is_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_is_equal(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_is_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/title",
          "value": "nw_connection_boolean_event_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_boolean_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_boolean_event_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_boolean_event_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_copy(_:)/title",
          "value": "nw_txt_record_copy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_copy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_copy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_access_bytes_t/title",
          "value": "nw_txt_record_access_bytes_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_access_bytes_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_access_bytes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_access_bytes_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_access_bytes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/title",
          "value": "nw_connection_group_new_connection_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_new_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_new_connection_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_new_connection_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_create_with_bytes(_:_:)/title",
          "value": "nw_txt_record_create_with_bytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_create_with_bytes(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_create_with_bytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_apply(_:_:)/title",
          "value": "nw_txt_record_apply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_apply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_apply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_txt_record/title",
          "value": "OS_nw_txt_record"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_txt_record/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_txt_record/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_txt_record"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_create_dictionary()/title",
          "value": "nw_txt_record_create_dictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_create_dictionary()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_create_dictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_applier_t/title",
          "value": "nw_txt_record_applier_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_applier_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_applier_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_applier_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_applier_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/title",
          "value": "nw_connection_group_receive_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_connection_group_receive_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_connection_group_receive_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_get_key_count(_:)/title",
          "value": "nw_txt_record_get_key_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_get_key_count(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_get_key_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_access_key(_:_:_:)/title",
          "value": "nw_txt_record_access_key"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_access_key(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_access_key"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_txt_record_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_txt_record_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
