{
  "abstract": [
    {
      "text": "The key is present and has an empty associated value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_empty_value"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@nw_txt_record_find_key_t@nw_txt_record_find_key_empty_value",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_txt_record_find_key_empty_value"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@nw_txt_record_find_key_t",
        "text": "nw_txt_record_find_key_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_txt_record_find_key_empty_value"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "nw_txt_record_find_key_empty_value"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_empty_value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@nw_txt_record_find_key_t",
              "text": "nw_txt_record_find_key_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_empty_value": {
      "abstract": [
        {
          "text": "The key is present and has an empty associated value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_empty_value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_txt_record_find_key_t",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_empty_value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_empty_value"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_find_key_empty_value",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_find_key_empty_value"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_invalid": {
      "abstract": [
        {
          "text": "The key is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_invalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_txt_record_find_key_t",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_invalid"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_find_key_invalid",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_find_key_invalid"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_no_value": {
      "abstract": [
        {
          "text": "The key is present but has no associated value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_no_value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_txt_record_find_key_t",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_no_value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_no_value"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_find_key_no_value",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_find_key_no_value"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_non_empty_value": {
      "abstract": [
        {
          "text": "The key has an associated value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_non_empty_value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_txt_record_find_key_t",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_non_empty_value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_non_empty_value"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_find_key_non_empty_value",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_find_key_non_empty_value"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_not_present": {
      "abstract": [
        {
          "text": "The key is not present in the dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_not_present"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_txt_record_find_key_t",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_not_present",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_not_present"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_find_key_not_present",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_find_key_not_present"
    },
    "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t": {
      "abstract": [
        {
          "text": "Status values describing what kind of value is stored in a TXT record dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_txt_record_find_key_t"
        }
      ],
      "role": "symbol",
      "title": "nw_txt_record_find_key_t",
      "type": "topic",
      "url": "/documentation/network/nw_txt_record_find_key_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Key-Value-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_invalid",
        "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_not_present",
        "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_no_value",
        "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_non_empty_value"
      ],
      "title": "Key Value Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_txt_record_find_key_empty_value"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_empty_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network",
                "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Key-Value-Status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_invalid",
                "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_not_present",
                "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_no_value",
                "doc://com.apple.network/documentation/Network/nw_txt_record_find_key_non_empty_value"
              ],
              "title": "Key Value Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "nw_txt_record_find_key_empty_value"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_not_present/title",
          "value": "nw_txt_record_find_key_not_present"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_not_present/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_not_present"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_t/title",
          "value": "nw_txt_record_find_key_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_no_value/title",
          "value": "nw_txt_record_find_key_no_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_no_value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_no_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_non_empty_value/title",
          "value": "nw_txt_record_find_key_non_empty_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_non_empty_value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_non_empty_value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_invalid/title",
          "value": "nw_txt_record_find_key_invalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_invalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_empty_value/title",
          "value": "nw_txt_record_find_key_empty_value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_txt_record_find_key_empty_value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_txt_record_find_key_empty_value"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_txt_record_find_key_empty_value"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_txt_record_find_key_empty_value"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
