{
  "abstract": [
    {
      "text": "An endpoint is terminating the connection because it received a type of data it cannot accept.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/nw_ws_close_code_unsupported_data"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@nw_ws_close_code_t@nw_ws_close_code_unsupported_data",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nw_ws_close_code_unsupported_data"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
        "text": "nw_ws_close_code_t"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "nw_ws_close_code_unsupported_data"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "nw_ws_close_code_unsupported_data"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_unsupported_data"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
              "text": "nw_ws_close_code_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_abnormal_closure": {
      "abstract": [
        {
          "text": "This value is reserved for local errors and indicates that no Close message was received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_abnormal_closure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_abnormal_closure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_abnormal_closure"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_abnormal_closure",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_abnormal_closure"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_going_away": {
      "abstract": [
        {
          "text": "An endpoint is no longer available, such as when a server is down.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_going_away"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_going_away",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_going_away"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_going_away",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_going_away"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_internal_server_error": {
      "abstract": [
        {
          "text": "The server is terminating the connection because it encountered an unexpected condition that prevented it from fulfilling the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_internal_server_error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_internal_server_error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_internal_server_error"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_internal_server_error",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_internal_server_error"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_invalid_frame_payload_data": {
      "abstract": [
        {
          "text": "An endpoint is terminating the connection because it received data within a message that was inconsistent with the message type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_invalid_frame_payload_data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_invalid_frame_payload_data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_invalid_frame_payload_data"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_invalid_frame_payload_data",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_invalid_frame_payload_data"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_mandatory_extension": {
      "abstract": [
        {
          "text": "The WebSocket client expected the server to negotiate one or more extensions that were not negotiated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_mandatory_extension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_mandatory_extension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_mandatory_extension"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_mandatory_extension",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_mandatory_extension"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_message_too_big": {
      "abstract": [
        {
          "text": "An endpoint is terminating the connection because it received a message that is too big for it to process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_message_too_big"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_message_too_big",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_message_too_big"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_message_too_big",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_message_too_big"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_no_status_received": {
      "abstract": [
        {
          "text": "This value is reserved for local errors and indicates that no Close code was received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_no_status_received"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_no_status_received",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_no_status_received"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_no_status_received",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_no_status_received"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_normal_closure": {
      "abstract": [
        {
          "text": "A normal closure occurred with no errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_normal_closure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_normal_closure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_normal_closure"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_normal_closure",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_normal_closure"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_policy_violation": {
      "abstract": [
        {
          "text": "An endpoint is terminating the connection because it received a message that violates its policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_policy_violation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_policy_violation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_policy_violation"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_policy_violation",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_policy_violation"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_protocol_error": {
      "abstract": [
        {
          "text": "An endpoint is terminating the connection due to a protocol error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_protocol_error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_protocol_error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_protocol_error"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_protocol_error",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_protocol_error"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_t": {
      "abstract": [
        {
          "text": "Types of codes used upon closing a WebSocket connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_tls_handshake": {
      "abstract": [
        {
          "text": "This value is reserved for local errors and indicates that the TLS handshake failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_tls_handshake"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_tls_handshake",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_tls_handshake"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_tls_handshake",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_tls_handshake"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_unsupported_data": {
      "abstract": [
        {
          "text": "An endpoint is terminating the connection because it received a type of data it cannot accept.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_unsupported_data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_unsupported_data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_unsupported_data"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_unsupported_data",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_unsupported_data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defined-Close-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_normal_closure",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_going_away",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_protocol_error",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_no_status_received",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_abnormal_closure",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_invalid_frame_payload_data",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_policy_violation",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_message_too_big",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_mandatory_extension",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_internal_server_error",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_tls_handshake"
      ],
      "title": "Defined Close Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "nw_ws_close_code_unsupported_data"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_unsupported_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Defined-Close-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_normal_closure",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_going_away",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_protocol_error",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_no_status_received",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_abnormal_closure",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_invalid_frame_payload_data",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_policy_violation",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_message_too_big",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_mandatory_extension",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_internal_server_error",
                "doc://com.apple.network/documentation/Network/nw_ws_close_code_tls_handshake"
              ],
              "title": "Defined Close Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "nw_ws_close_code_unsupported_data"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_normal_closure/title",
          "value": "nw_ws_close_code_normal_closure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_normal_closure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_normal_closure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_abnormal_closure/title",
          "value": "nw_ws_close_code_abnormal_closure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_abnormal_closure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_abnormal_closure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_message_too_big/title",
          "value": "nw_ws_close_code_message_too_big"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_message_too_big/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_message_too_big"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_invalid_frame_payload_data/title",
          "value": "nw_ws_close_code_invalid_frame_payload_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_invalid_frame_payload_data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_invalid_frame_payload_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_policy_violation/title",
          "value": "nw_ws_close_code_policy_violation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_policy_violation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_policy_violation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_internal_server_error/title",
          "value": "nw_ws_close_code_internal_server_error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_internal_server_error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_internal_server_error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_going_away/title",
          "value": "nw_ws_close_code_going_away"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_going_away/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_going_away"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_tls_handshake/title",
          "value": "nw_ws_close_code_tls_handshake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_tls_handshake/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_tls_handshake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_mandatory_extension/title",
          "value": "nw_ws_close_code_mandatory_extension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_mandatory_extension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_mandatory_extension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_unsupported_data/title",
          "value": "nw_ws_close_code_unsupported_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_unsupported_data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_unsupported_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_no_status_received/title",
          "value": "nw_ws_close_code_no_status_received"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_no_status_received/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_no_status_received"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_t/title",
          "value": "nw_ws_close_code_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_protocol_error/title",
          "value": "nw_ws_close_code_protocol_error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_protocol_error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_protocol_error"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/nw_ws_close_code_unsupported_data"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/nw_ws_close_code_unsupported_data"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
