{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/OS_nw_protocol_metadata"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)OS_nw_protocol_metadata",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OS_nw_protocol_metadata"
      }
    ],
    "modules": [
      {
        "name": "Network"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OS_nw_protocol_metadata"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "OS_nw_protocol_metadata"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_metadata"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_advertise_descriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_advertise_descriptor"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_advertise_descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_advertise_descriptor"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_advertise_descriptor",
      "type": "topic",
      "url": "/documentation/network/os_nw_advertise_descriptor"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_browse_descriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_browse_descriptor"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_browse_descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_browse_descriptor"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_browse_descriptor",
      "type": "topic",
      "url": "/documentation/network/os_nw_browse_descriptor"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_browse_result": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_browse_result"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_browse_result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_browse_result"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_browse_result",
      "type": "topic",
      "url": "/documentation/network/os_nw_browse_result"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_browser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_browser"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_browser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_browser"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_browser",
      "type": "topic",
      "url": "/documentation/network/os_nw_browser"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_connection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_connection"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_connection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_connection"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_connection",
      "type": "topic",
      "url": "/documentation/network/os_nw_connection"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_connection_group": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_connection_group"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_connection_group",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_connection_group"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_connection_group",
      "type": "topic",
      "url": "/documentation/network/os_nw_connection_group"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_content_context": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_content_context"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_content_context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_content_context"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_content_context",
      "type": "topic",
      "url": "/documentation/network/os_nw_content_context"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_data_transfer_report": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_data_transfer_report"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_data_transfer_report",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_data_transfer_report"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_data_transfer_report",
      "type": "topic",
      "url": "/documentation/network/os_nw_data_transfer_report"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_endpoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_endpoint"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_endpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_endpoint"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_endpoint",
      "type": "topic",
      "url": "/documentation/network/os_nw_endpoint"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_error": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_error"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_error"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_error",
      "type": "topic",
      "url": "/documentation/network/os_nw_error"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_establishment_report": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_establishment_report"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_establishment_report",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_establishment_report"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_establishment_report",
      "type": "topic",
      "url": "/documentation/network/os_nw_establishment_report"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_ethernet_channel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_ethernet_channel"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_ethernet_channel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_ethernet_channel"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_ethernet_channel",
      "type": "topic",
      "url": "/documentation/network/os_nw_ethernet_channel"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_framer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_framer"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_framer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_framer"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_framer",
      "type": "topic",
      "url": "/documentation/network/os_nw_framer"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_group_descriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_group_descriptor"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_group_descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_group_descriptor"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_group_descriptor",
      "type": "topic",
      "url": "/documentation/network/os_nw_group_descriptor"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_interface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_interface"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_interface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_interface"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_interface",
      "type": "topic",
      "url": "/documentation/network/os_nw_interface"
    },
    "doc://com.apple.network/documentation/Network/OS_nw_protocol_metadata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_nw_protocol_metadata"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/OS_nw_protocol_metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_nw_protocol_metadata"
        }
      ],
      "role": "symbol",
      "title": "OS_nw_protocol_metadata",
      "type": "topic",
      "url": "/documentation/network/os_nw_protocol_metadata"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OS_nw_protocol_metadata"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.network/documentation/Network"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/OS_nw_advertise_descriptor",
                "doc://com.apple.network/documentation/Network/OS_nw_browse_descriptor",
                "doc://com.apple.network/documentation/Network/OS_nw_browse_result",
                "doc://com.apple.network/documentation/Network/OS_nw_browser",
                "doc://com.apple.network/documentation/Network/OS_nw_connection",
                "doc://com.apple.network/documentation/Network/OS_nw_connection_group",
                "doc://com.apple.network/documentation/Network/OS_nw_content_context",
                "doc://com.apple.network/documentation/Network/OS_nw_data_transfer_report",
                "doc://com.apple.network/documentation/Network/OS_nw_endpoint",
                "doc://com.apple.network/documentation/Network/OS_nw_error",
                "doc://com.apple.network/documentation/Network/OS_nw_establishment_report",
                "doc://com.apple.network/documentation/Network/OS_nw_ethernet_channel",
                "doc://com.apple.network/documentation/Network/OS_nw_framer",
                "doc://com.apple.network/documentation/Network/OS_nw_group_descriptor",
                "doc://com.apple.network/documentation/Network/OS_nw_interface"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OS_nw_protocol_metadata"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_error/title",
          "value": "OS_nw_error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_error/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_group_descriptor/title",
          "value": "OS_nw_group_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_group_descriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_group_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_group_descriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_group_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_data_transfer_report/title",
          "value": "OS_nw_data_transfer_report"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_data_transfer_report/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_data_transfer_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_data_transfer_report/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_data_transfer_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ethernet_channel/title",
          "value": "OS_nw_ethernet_channel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ethernet_channel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_ethernet_channel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_ethernet_channel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_ethernet_channel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_advertise_descriptor/title",
          "value": "OS_nw_advertise_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_advertise_descriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_advertise_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_advertise_descriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_advertise_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_framer/title",
          "value": "OS_nw_framer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_framer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_framer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_framer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_framer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection_group/title",
          "value": "OS_nw_connection_group"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection_group/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection_group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection_group/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection_group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browser/title",
          "value": "OS_nw_browser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_result/title",
          "value": "OS_nw_browse_result"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_result/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browse_result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_result/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browse_result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_establishment_report/title",
          "value": "OS_nw_establishment_report"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_establishment_report/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_establishment_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_establishment_report/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_establishment_report"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection/title",
          "value": "OS_nw_connection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_connection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_connection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_descriptor/title",
          "value": "OS_nw_browse_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_descriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browse_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_browse_descriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_browse_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_endpoint/title",
          "value": "OS_nw_endpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_endpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_endpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_interface/title",
          "value": "OS_nw_interface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_interface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_interface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_metadata/title",
          "value": "OS_nw_protocol_metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_protocol_metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_protocol_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_content_context/title",
          "value": "OS_nw_content_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_content_context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_content_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1OS_nw_content_context/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_nw_content_context"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/os_nw_protocol_metadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/os_nw_protocol_metadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
