{
  "abstract": [
    {
      "text": "Configure parameters related to user privacy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/privacy-management"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Privacy Management"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/creating-an-identity-for-local-network-tls": {
      "abstract": [
        {
          "text": "Learn how to create and use a digital identity in your application for local network TLS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/creating-an-identity-for-local-network-tls",
      "kind": "article",
      "role": "article",
      "title": "Creating an Identity for Local Network TLS",
      "type": "topic",
      "url": "/documentation/network/creating-an-identity-for-local-network-tls"
    },
    "doc://com.apple.network/documentation/Network/indicating-the-source-of-network-activity": {
      "abstract": [
        {
          "text": "Control whether the App Privacy Report attributes network traffic to the app or to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/indicating-the-source-of-network-activity",
      "kind": "article",
      "role": "article",
      "title": "Indicating the source of network activity",
      "type": "topic",
      "url": "/documentation/network/indicating-the-source-of-network-activity"
    },
    "doc://com.apple.network/documentation/Network/inspecting-app-activity-data": {
      "abstract": [
        {
          "text": "Verify that your app accesses only the user data and network resources that you expect it to access.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/inspecting-app-activity-data",
      "kind": "article",
      "role": "article",
      "title": "Inspecting app activity data",
      "type": "topic",
      "url": "/documentation/network/inspecting-app-activity-data"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t": {
      "abstract": [
        {
          "text": "The entities that can make a network request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_attribution_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_attribution_t"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_attribution_t",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_attribution_t"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_get_attribution(_:)": {
      "abstract": [
        {
          "text": "Gets a flag that indicates whether the network request originates from the developer or the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_get_attribution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@nw_parameters_attribution_t",
          "text": "nw_parameters_attribution_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_get_attribution(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_get_attribution"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_get_attribution(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_get_attribution(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_parameters_set_attribution(_:_:)": {
      "abstract": [
        {
          "text": "Sets a flag that indicates whether the network request originates from the developer or the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_set_attribution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@nw_parameters_attribution_t",
          "text": "nw_parameters_attribution_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_parameters_set_attribution(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_parameters_set_attribution"
        }
      ],
      "role": "symbol",
      "title": "nw_parameters_set_attribution(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_parameters_set_attribution(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/security-options": {
      "abstract": [
        {
          "text": "Configure security options for TLS handshakes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/security-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Security Options",
      "type": "topic",
      "url": "/documentation/network/security-options"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Security-and-Privacy",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/security-options",
        "doc://com.apple.network/documentation/Network/creating-an-identity-for-local-network-tls"
      ],
      "title": "Network Security and Privacy"
    }
  ],
  "topicSections": [
    {
      "anchor": "Traffic-Attribution",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/inspecting-app-activity-data",
        "doc://com.apple.network/documentation/Network/indicating-the-source-of-network-activity",
        "doc://com.apple.network/documentation/Network/nw_parameters_set_attribution(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_get_attribution(_:)",
        "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t"
      ],
      "title": "Traffic Attribution"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Traffic-Attribution",
              "identifiers": [
                "doc://com.apple.network/documentation/Network/inspecting-app-activity-data",
                "doc://com.apple.network/documentation/Network/indicating-the-source-of-network-activity",
                "doc://com.apple.network/documentation/Network/nw_parameters_set_attribution(_:_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_get_attribution(_:)",
                "doc://com.apple.network/documentation/Network/nw_parameters_attribution_t"
              ],
              "title": "Traffic Attribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Network-Security-and-Privacy",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/security-options",
                "doc://com.apple.network/documentation/Network/creating-an-identity-for-local-network-tls"
              ],
              "title": "Network Security and Privacy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_attribution_t/title",
          "value": "nw_parameters_attribution_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_attribution_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_attribution_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_attribution_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_attribution_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_attribution(_:)/title",
          "value": "nw_parameters_get_attribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_get_attribution(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_get_attribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_attribution(_:_:)/title",
          "value": "nw_parameters_set_attribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_parameters_set_attribution(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_parameters_set_attribution"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/privacy-management"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/privacy-management"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
