{
  "abstract": [
    {
      "text": "Learn about the available third-party network debugging tools.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/taking-advantage-of-third-party-network-debugging-tools"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Taking Advantage of Third-Party Network Debugging Tools"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "iOS and macOS have built-in network debugging tools (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/url_loading_system/analyzing_http_traffic_with_instruments",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.network/documentation/Network/choosing-a-network-debugging-tool",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), but you may also want to take advantage of the third-party tools discussed here.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Information about products not manufactured by Apple is provided without recommendation or endorsement. Apple assumes no responsibility with regard to the selection, performance, or use of third-party products. ",
                  "type": "text"
                },
                {
                  "identifier": "https://support.apple.com/en-us/HT201777",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for additional information. Other company and product names may be trademarks of their respective owners.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Debugging-HTTP-Proxies",
          "level": 3,
          "text": "Debugging HTTP Proxies",
          "type": "heading"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A debugging HTTP proxy that enables a developer to view all of the HTTP and HTTPS traffic between their machine and the internet.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "https://www.charlesproxy.com/",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A free and open source interactive debugging HTTP proxy. The name stands for ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "machine-in-the-middle proxy",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "https://mitmproxy.org/",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "anchor": "macOS-Apps",
          "level": 3,
          "text": "macOS Apps",
          "type": "heading"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A simple and powerful network traffic analyzer for macOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "https://www.iwaxx.com/debookee/",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A network troubleshooting toolkit for debugging internet service problems and optimizing performance.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "http://www.sustworks.com/site/prod_ipmx_overview.html",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A free and open source packet analyzer that supports macOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "https://www.wireshark.org",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "anchor": "Command-Line-Tools",
          "level": 3,
          "text": "Command-Line Tools",
          "type": "heading"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A program that records data transmitted as part of TCP connections (flows), and stores the data in a way that’s convenient for protocol analysis or debugging.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "http://www.circlemud.org/jelson/software/tcpflow/",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An open source tool for analyzing the TCP connections in a packet trace.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "http://tcptrace.org/",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/url_loading_system/analyzing_http_traffic_with_instruments": {
      "abstract": [
        {
          "text": "Measure HTTP-based network performance and usage of your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/url_loading_system/analyzing_http_traffic_with_instruments",
      "kind": "article",
      "role": "article",
      "title": "Analyzing HTTP traffic with Instruments",
      "type": "topic",
      "url": "/documentation/foundation/url_loading_system/analyzing_http_traffic_with_instruments"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/choosing-a-network-debugging-tool": {
      "abstract": [
        {
          "text": "Decide which tool works best for your network debugging problem.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/choosing-a-network-debugging-tool",
      "kind": "article",
      "role": "article",
      "title": "Choosing a Network Debugging Tool",
      "type": "topic",
      "url": "/documentation/network/choosing-a-network-debugging-tool"
    },
    "doc://com.apple.network/documentation/Network/debugging-http-server-side-errors": {
      "abstract": [
        {
          "text": "Understand HTTP server-side errors and how to debug them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/debugging-http-server-side-errors",
      "kind": "article",
      "role": "article",
      "title": "Debugging HTTP Server-Side Errors",
      "type": "topic",
      "url": "/documentation/network/debugging-http-server-side-errors"
    },
    "doc://com.apple.network/documentation/Network/debugging-https-problems-with-cfnetwork-diagnostic-logging": {
      "abstract": [
        {
          "text": "Use CFNetwork diagnostic logging to investigate HTTP and HTTPS problems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/debugging-https-problems-with-cfnetwork-diagnostic-logging",
      "kind": "article",
      "role": "article",
      "title": "Debugging HTTPS Problems with CFNetwork Diagnostic Logging",
      "type": "topic",
      "url": "/documentation/network/debugging-https-problems-with-cfnetwork-diagnostic-logging"
    },
    "doc://com.apple.network/documentation/Network/recording-a-packet-trace": {
      "abstract": [
        {
          "text": "Learn how to record a low-level trace of network traffic.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/recording-a-packet-trace",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Recording a Packet Trace",
      "type": "topic",
      "url": "/documentation/network/recording-a-packet-trace"
    },
    "doc://com.apple.network/documentation/Network/testing-and-debugging-l4s-in-your-app": {
      "abstract": [
        {
          "text": "Learn how to verify your app on an L4S-capable host and network to improve your app’s responsiveness.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/testing-and-debugging-l4s-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Testing and Debugging L4S in Your App",
      "type": "topic",
      "url": "/documentation/network/testing-and-debugging-l4s-in-your-app"
    },
    "http://tcptrace.org/": {
      "identifier": "http://tcptrace.org/",
      "title": "tcptrace",
      "titleInlineContent": [
        {
          "text": "tcptrace",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://tcptrace.org/"
    },
    "http://www.circlemud.org/jelson/software/tcpflow/": {
      "identifier": "http://www.circlemud.org/jelson/software/tcpflow/",
      "title": "tcpflow",
      "titleInlineContent": [
        {
          "text": "tcpflow",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.circlemud.org/jelson/software/tcpflow/"
    },
    "http://www.sustworks.com/site/prod_ipmx_overview.html": {
      "identifier": "http://www.sustworks.com/site/prod_ipmx_overview.html",
      "title": "IPNetMonitorX",
      "titleInlineContent": [
        {
          "text": "IPNetMonitorX",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.sustworks.com/site/prod_ipmx_overview.html"
    },
    "https://mitmproxy.org/": {
      "identifier": "https://mitmproxy.org/",
      "title": "mitmproxy",
      "titleInlineContent": [
        {
          "text": "mitmproxy",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://mitmproxy.org/"
    },
    "https://support.apple.com/en-us/HT201777": {
      "identifier": "https://support.apple.com/en-us/HT201777",
      "title": "Contact the vendor",
      "titleInlineContent": [
        {
          "text": "Contact the vendor",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/en-us/HT201777"
    },
    "https://www.charlesproxy.com/": {
      "identifier": "https://www.charlesproxy.com/",
      "title": "Charles HTTP Proxy",
      "titleInlineContent": [
        {
          "text": "Charles HTTP Proxy",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.charlesproxy.com/"
    },
    "https://www.iwaxx.com/debookee/": {
      "identifier": "https://www.iwaxx.com/debookee/",
      "title": "Debookee",
      "titleInlineContent": [
        {
          "text": "Debookee",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.iwaxx.com/debookee/"
    },
    "https://www.wireshark.org": {
      "identifier": "https://www.wireshark.org",
      "title": "Wireshark",
      "titleInlineContent": [
        {
          "text": "Wireshark",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.wireshark.org"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Debugging",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/choosing-a-network-debugging-tool",
        "doc://com.apple.network/documentation/Network/debugging-http-server-side-errors",
        "doc://com.apple.network/documentation/Network/debugging-https-problems-with-cfnetwork-diagnostic-logging",
        "doc://com.apple.network/documentation/Network/recording-a-packet-trace",
        "doc://com.apple.network/documentation/Network/testing-and-debugging-l4s-in-your-app"
      ],
      "title": "Network Debugging"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Network-Debugging",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/choosing-a-network-debugging-tool",
                "doc://com.apple.network/documentation/Network/debugging-http-server-side-errors",
                "doc://com.apple.network/documentation/Network/debugging-https-problems-with-cfnetwork-diagnostic-logging",
                "doc://com.apple.network/documentation/Network/recording-a-packet-trace",
                "doc://com.apple.network/documentation/Network/testing-and-debugging-l4s-in-your-app"
              ],
              "title": "Network Debugging"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/taking-advantage-of-third-party-network-debugging-tools"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/taking-advantage-of-third-party-network-debugging-tools"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
