{
  "abstract": [
    {
      "text": "Configure options for connections that use the Transmission Control Protocol.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.network/documentation/Network/tcp-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "TCP Options"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/framer-protocol-options": {
      "abstract": [
        {
          "text": "Create custom protocols to frame applications messages over a connection.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/framer-protocol-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Framer Protocol Options",
      "type": "topic",
      "url": "/documentation/network/framer-protocol-options"
    },
    "doc://com.apple.network/documentation/Network/ip-options": {
      "abstract": [
        {
          "text": "Configure Internet Protocol options on connections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/ip-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IP Options",
      "type": "topic",
      "url": "/documentation/network/ip-options"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_copy_tcp_definition()": {
      "abstract": [
        {
          "text": "Accesses the system definition of the Transport Control Protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_tcp_definition"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_copy_tcp_definition()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_tcp_definition"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_copy_tcp_definition()",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_copy_tcp_definition()"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_tcp(_:)": {
      "abstract": [
        {
          "text": "Checks whether a metadata object contains TCP connection state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_tcp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_tcp(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_tcp"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_metadata_is_tcp(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_metadata_is_tcp(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_create_options()": {
      "abstract": [
        {
          "text": "Initializes a default set of TCP connection options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_create_options"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_create_options()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_create_options"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_create_options()",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_create_options()"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_get_available_receive_buffer(_:)": {
      "abstract": [
        {
          "text": "Accesses the number of available bytes in the TCP receive buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_get_available_receive_buffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_get_available_receive_buffer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_get_available_receive_buffer"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_get_available_receive_buffer(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_get_available_receive_buffer(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_get_available_send_buffer(_:)": {
      "abstract": [
        {
          "text": "Accesses the number of available bytes in the TCP send buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_get_available_send_buffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_get_available_send_buffer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_get_available_send_buffer"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_get_available_send_buffer(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_get_available_send_buffer(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_connection_timeout(_:_:)": {
      "abstract": [
        {
          "text": "Sets the number of seconds that TCP waits before timing out its handshake.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_connection_timeout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_connection_timeout(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_connection_timeout"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_connection_timeout(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_connection_timeout(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_disable_ack_stretching(_:_:)": {
      "abstract": [
        {
          "text": "Disables TCP acknowledgment stretching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_disable_ack_stretching"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_disable_ack_stretching(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_disable_ack_stretching"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_disable_ack_stretching(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_disable_ack_stretching(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_disable_ecn(_:_:)": {
      "abstract": [
        {
          "text": "Disables negotiation of Explicit Congestion Notification markings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_disable_ecn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_disable_ecn(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_disable_ecn"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_disable_ecn(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_disable_ecn(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_enable_fast_open(_:_:)": {
      "abstract": [
        {
          "text": "Enables TCP Fast Open on a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_enable_fast_open"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_enable_fast_open(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_enable_fast_open"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_enable_fast_open(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_enable_fast_open(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_enable_keepalive(_:_:)": {
      "abstract": [
        {
          "text": "Enables TCP keepalives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_enable_keepalive"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_enable_keepalive(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_enable_keepalive"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_enable_keepalive(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_enable_keepalive(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_keepalive_count(_:_:)": {
      "abstract": [
        {
          "text": "Sets the number of keepalive probes that TCP sends before terminating the connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_keepalive_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_keepalive_count(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_keepalive_count"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_keepalive_count(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_keepalive_count(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_keepalive_idle_time(_:_:)": {
      "abstract": [
        {
          "text": "Sets the number of seconds of idleness that TCP waits before sending keepalive probes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_keepalive_idle_time"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_keepalive_idle_time(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_keepalive_idle_time"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_keepalive_idle_time(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_keepalive_idle_time(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_keepalive_interval(_:_:)": {
      "abstract": [
        {
          "text": "Sets the number of seconds that TCP waits between sending keepalive probes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_keepalive_interval"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_keepalive_interval(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_keepalive_interval"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_keepalive_interval(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_keepalive_interval(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_maximum_segment_size(_:_:)": {
      "abstract": [
        {
          "text": "Sets TCP’s maximum segment size in bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_maximum_segment_size"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_maximum_segment_size(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_maximum_segment_size"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_maximum_segment_size(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_maximum_segment_size(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_no_delay(_:_:)": {
      "abstract": [
        {
          "text": "Disables Nagle’s algorithm for TCP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_no_delay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_no_delay(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_no_delay"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_no_delay(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_no_delay(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_no_options(_:_:)": {
      "abstract": [
        {
          "text": "Sets TCP into no-options mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_no_options"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_no_options(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_no_options"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_no_options(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_no_options(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_no_push(_:_:)": {
      "abstract": [
        {
          "text": "Sets TCP into no-push mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_no_push"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_no_push(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_no_push"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_no_push(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_no_push(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_persist_timeout(_:_:)": {
      "abstract": [
        {
          "text": "Sets the TCP persist timeout in seconds, as defined by RFC 6429.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_persist_timeout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_persist_timeout(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_persist_timeout"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_persist_timeout(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_persist_timeout(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_retransmit_connection_drop_time(_:_:)": {
      "abstract": [
        {
          "text": "Sets the number of seconds that TCP waits between retransmission attempts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_retransmit_connection_drop_time"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_retransmit_connection_drop_time(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_retransmit_connection_drop_time"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_retransmit_connection_drop_time(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_retransmit_connection_drop_time(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tcp_options_set_retransmit_fin_drop(_:_:)": {
      "abstract": [
        {
          "text": "Causes TCP to drop its connection after not receiving an ACK after a FIN.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_retransmit_fin_drop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tcp_options_set_retransmit_fin_drop(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tcp_options_set_retransmit_fin_drop"
        }
      ],
      "role": "symbol",
      "title": "nw_tcp_options_set_retransmit_fin_drop(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tcp_options_set_retransmit_fin_drop(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/quic-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the QUIC transport protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/quic-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QUIC Options",
      "type": "topic",
      "url": "/documentation/network/quic-options"
    },
    "doc://com.apple.network/documentation/Network/tls-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use Transport Layer Security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/tls-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TLS Options",
      "type": "topic",
      "url": "/documentation/network/tls-options"
    },
    "doc://com.apple.network/documentation/Network/udp-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the User Datagram Protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/udp-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UDP Options",
      "type": "topic",
      "url": "/documentation/network/udp-options"
    },
    "doc://com.apple.network/documentation/Network/websocket-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use WebSocket.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/websocket-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebSocket Options",
      "type": "topic",
      "url": "/documentation/network/websocket-options"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/tls-options",
        "doc://com.apple.network/documentation/Network/quic-options",
        "doc://com.apple.network/documentation/Network/udp-options",
        "doc://com.apple.network/documentation/Network/ip-options",
        "doc://com.apple.network/documentation/Network/websocket-options",
        "doc://com.apple.network/documentation/Network/framer-protocol-options"
      ],
      "title": "Network Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-TCP-Connections",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_copy_tcp_definition()",
        "doc://com.apple.network/documentation/Network/nw_tcp_create_options()"
      ],
      "title": "Creating TCP Connections"
    },
    {
      "anchor": "Customizing-TCP-Options",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_enable_fast_open(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_maximum_segment_size(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_no_delay(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_no_options(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_no_push(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_retransmit_fin_drop(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_disable_ack_stretching(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_disable_ecn(_:_:)"
      ],
      "title": "Customizing TCP Options"
    },
    {
      "anchor": "Configuring-Keepalives",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_enable_keepalive(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_keepalive_idle_time(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_keepalive_count(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_keepalive_interval(_:_:)"
      ],
      "title": "Configuring Keepalives"
    },
    {
      "anchor": "Setting-Timeouts",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_connection_timeout(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_retransmit_connection_drop_time(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_options_set_persist_timeout(_:_:)"
      ],
      "title": "Setting Timeouts"
    },
    {
      "anchor": "Inspecting-TCP-State",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_tcp(_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_get_available_send_buffer(_:)",
        "doc://com.apple.network/documentation/Network/nw_tcp_get_available_receive_buffer(_:)"
      ],
      "title": "Inspecting TCP State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_tcp_definition()/title",
          "value": "nw_protocol_copy_tcp_definition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_tcp_definition()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_copy_tcp_definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_get_available_send_buffer(_:)/title",
          "value": "nw_tcp_get_available_send_buffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_get_available_send_buffer(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_get_available_send_buffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_keepalive_count(_:_:)/title",
          "value": "nw_tcp_options_set_keepalive_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_keepalive_count(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_keepalive_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_retransmit_fin_drop(_:_:)/title",
          "value": "nw_tcp_options_set_retransmit_fin_drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_retransmit_fin_drop(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_retransmit_fin_drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_persist_timeout(_:_:)/title",
          "value": "nw_tcp_options_set_persist_timeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_persist_timeout(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_persist_timeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_no_delay(_:_:)/title",
          "value": "nw_tcp_options_set_no_delay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_no_delay(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_no_delay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_no_options(_:_:)/title",
          "value": "nw_tcp_options_set_no_options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_no_options(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_no_options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_retransmit_connection_drop_time(_:_:)/title",
          "value": "nw_tcp_options_set_retransmit_connection_drop_time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_retransmit_connection_drop_time(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_retransmit_connection_drop_time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_no_push(_:_:)/title",
          "value": "nw_tcp_options_set_no_push"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_no_push(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_no_push"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_keepalive_idle_time(_:_:)/title",
          "value": "nw_tcp_options_set_keepalive_idle_time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_keepalive_idle_time(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_keepalive_idle_time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_enable_keepalive(_:_:)/title",
          "value": "nw_tcp_options_set_enable_keepalive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_enable_keepalive(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_enable_keepalive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_enable_fast_open(_:_:)/title",
          "value": "nw_tcp_options_set_enable_fast_open"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_enable_fast_open(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_enable_fast_open"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_connection_timeout(_:_:)/title",
          "value": "nw_tcp_options_set_connection_timeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_connection_timeout(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_connection_timeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_maximum_segment_size(_:_:)/title",
          "value": "nw_tcp_options_set_maximum_segment_size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_maximum_segment_size(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_maximum_segment_size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_get_available_receive_buffer(_:)/title",
          "value": "nw_tcp_get_available_receive_buffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_get_available_receive_buffer(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_get_available_receive_buffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_disable_ecn(_:_:)/title",
          "value": "nw_tcp_options_set_disable_ecn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_disable_ecn(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_disable_ecn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_disable_ack_stretching(_:_:)/title",
          "value": "nw_tcp_options_set_disable_ack_stretching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_disable_ack_stretching(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_disable_ack_stretching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_create_options()/title",
          "value": "nw_tcp_create_options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_create_options()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_create_options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_keepalive_interval(_:_:)/title",
          "value": "nw_tcp_options_set_keepalive_interval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tcp_options_set_keepalive_interval(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tcp_options_set_keepalive_interval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_tcp(_:)/title",
          "value": "nw_protocol_metadata_is_tcp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_tcp(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_metadata_is_tcp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/tcp-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
