{
  "abstract": [
    {
      "text": "Learn how to verify your app on an L4S-capable host and network to improve your app’s responsiveness.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.network/documentation/Network/testing-and-debugging-l4s-in-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Testing and Debugging L4S in Your App"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With Low Latency, Low Loss, and Scalable Throughput (L4S) applications can have both low network delays and high throughput. L4S benefits most applications, such as conversational audio/video apps, interactive apps with dynamic content, interactive video, live streaming, cloud or online gaming, and virtual or augmented reality. In any end-to-end path from client to server (or server to client), there’s one slowest link at any moment of time, called the bottleneck. When the sender’s rate is higher than the bottleneck link rate, a queue builds up at the bottleneck, leading to increased delays and eventual loss, which tells the sender it needs to slow down.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "L4S uses an Explicit Congestion Notification (ECN) mechanism to give early warning of congestion at the bottleneck link by marking a Congestion Experienced (CE) codepoint in the IP header of packets. After receiving the packets, the receiver echoes this congestion information to the sender in the acknowledgement (ACK) packets of the transport protocol. The sender uses this congestion feedback to reduce its sending rate to avoid delay at the bottleneck. L4S requires implementation updates at end devices as well as on the network bottleneck. Beginning with iOS 17 and iPadOS 17, Apple supports L4S on its platforms for some users, for the QUIC and TCP networking stacks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Turn-on-L4S-on-Apple-Devices",
          "level": 3,
          "text": "Turn on L4S on Apple Devices",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apple’s QUIC implementation fully supports L4S, whereas Apple’s TCP implementation supports only the receiver-side L4S. Apple’s FaceTime application also supports L4S. As L4S may not be enabled for all users, turn on L4S support for QUIC, TCP, and FaceTime on iOS and iPadOS devices by turning on L4S in Developer settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4225936",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On macOS, enable L4S by using the following command in Terminal:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "defaults write -g network_enable_l4s -bool true"
          ],
          "syntax": "shell",
          "type": "codeListing"
        },
        {
          "anchor": "Confirm-an-Apple-Device-Sends-ECT1-for-QUIC",
          "level": 3,
          "text": "Confirm an Apple Device Sends ECT(1) for QUIC",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sending device indicates that it’s L4S capable by setting the ECN-Capable Transport (ECT) codepoint to 01, known as ECT(1).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To confirm that your Apple device is L4S capable, take a packet capture using Wireshark, and look for ECT(1) in the IP header of transmitted packets as shown below. Some networks bleach (zero) the ECN field. Apple’s stack performs validation in the beginning of the connection to test for bleaching. If bleaching is detected, Apple’s stack doesn’t use ECN and, therefore, L4S for such connections. Look for ECT(1) in at least 10–20 sent packets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4225937",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because Apple’s QUIC stack always provides ECN feedback when the device acts as a receiver, you don’t need to confirm ECT(1) on Apple devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Confirm-an-Apple-Device-Negotiated-Accurate-ECN-for-TCP",
          "level": 3,
          "text": "Confirm an Apple Device Negotiated Accurate ECN for TCP",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When L4S is enabled for the TCP receiver side, an Apple device negotiates Accurate ECN during the three-way handshake with the server, which is essential to provide the detailed congestion feedback an L4S sender needs. The Accurate ECN protocol uses two ways to provide feedback:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "TCP header flags that indicate the number of packets arriving with a CE codepoint in their IP-ECN field. AE, CWR, and ECE (ACE) are the three flags that convey Accurate ECN information.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Accurate ECN TCP options that provide feedback about the number of bytes arriving with one of the three ECN code points: ECT(1), ECT(0), and CE.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Apple’s TCP implementation provides both types of feedback. To confirm that Apple’s implementation negotiated Accurate ECN in the three-way handshake, take a packet capture on the device, and look in the synchronize (SYN) packet for the flags set as shown in the figure below. You need the latest version of Wireshark to parse the new Accurate ECN feedback in TCP.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4225943",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Then, to check how the server responded to this request, check if TCP flags are set on the synchronize-acknowledge (SYN-ACK) packet as below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4225940",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the last ACK packet of the three-way handshake, Apple’s implementation adds the Accurate ECN TCP option in addition to setting the ACE header flags.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After the negotiation is complete, the server may send data packets. If it supports L4S sender-side behavior, the server indicates that it’s L4S capable by setting the ECT codepoint to 01. You can check for ECT(1) in the client-side packet capture by looking at packets from the server to the client. As some networks may inconsistently affect the ECN field, check at least 10–20 packets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4225939",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To verify that your Apple device echoes Accurate ECN feedback, look at the ACE flags and Accurate ECN options because some of these fields change as more packets arrive. Note that the ACE flags use only 3 bits to count the number of CE packets, so they reset to 0 each time 8 CE packets arrive.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4225942",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-Your-App-Against-Third-Party-QUIC-Server-Implementations",
          "level": 3,
          "text": "Test Your App Against Third-Party QUIC Server Implementations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your app uses QUIC and your Content Delivery Network (CDN) provider (for example, Amazon CloudFront or Cloudflare quiche) or some other third-party library provides your server-side implementation, work with that provider. The server implementation needs to support L4S for both its sending and receiving sides, similar to the client. But if your server supports only ECN (it can receive L4S traffic), you can test uploading use cases from Apple devices to your server.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To test for sending-side support, follow the steps described above for Apple devices. To test for receiver-side support, take a packet capture on your server. Because QUIC is an encrypted protocol, you need Transport Layer Security (TLS) keys to decrypt and view the QUIC header. The steps to decrypt QUIC packets for Cloudflare’s quiche stack are described below. Contact your server provider for other stacks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Below are the instructions to decrypt QUIC for quiche.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the following lines to your server application:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "code": [
            "if let Some(keylog_path) = std::env::var_os(\"SSLKEYLOGFILE\") {",
            "    let file = std::fs::OpenOptions::new()",
            "        .create(true)",
            "        .append(true)",
            "        .open(keylog_path)",
            "        .unwrap();",
            "",
            "    keylog = Some(file);",
            "",
            "    config.log_keys();",
            "}"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the ",
                      "type": "text"
                    },
                    {
                      "code": "SSLKEYLOGFILE",
                      "type": "codeVoice"
                    },
                    {
                      "text": " environment variable.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "start": 2,
          "type": "orderedList"
        },
        {
          "code": [
            "export SSLKEYLOGFILE=/tmp/keys.log"
          ],
          "syntax": "shell",
          "type": "codeListing"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Restart your server application. Each new session key is logged in the file created in step 2.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Perform a Wireshark capture. Using a filter for User Datagram Protocol (UDP) packets is optional.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In Wireshark Preferences > Protocols > TLS, select the ",
                      "type": "text"
                    },
                    {
                      "code": "SSLKEYLOGFILE",
                      "type": "codeVoice"
                    },
                    {
                      "text": " as the TLS secret log file in the (Pre)-Master-Secret log filename field.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "start": 3,
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4225969",
              "type": "image"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "6. In Wireshark, select any packet with an ACK_ECN frame. Then, in the packet details view below under QUIC, look at the ECT counts. If the ECT counts are nonzero, then your server supports ECN and is capable of being an L4S server.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4225970",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-L4S-on-a-Linux-TCP-Implementation",
          "level": 3,
          "text": "Test L4S on a Linux TCP Implementation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Currently, a publicly available implementation for Linux TCP supports L4S. ",
              "type": "text"
            },
            {
              "identifier": "https://github.com/L4STeam/linux",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " describes the various patches that were developed for L4S and instructions to install such a kernel.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Check both the client-side and server-side packet captures because faulty networks may bleach (zero) the IP-ECN field or remove certain TCP headers. Similar to on the client side, take a packet capture on the server side. Look at the IP-ECN field in the direction from the server to the client, the TCP Accurate ECN flags, and the AccECN TCP option fields.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-If-Your-Network-Supports-ECN-and-L4S",
          "level": 3,
          "text": "Test If Your Network Supports ECN and L4S",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There are two aspects to verifying that if your network supports L4S.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "First, check that your network doesn’t change the ECN field or drop packets that have ECN bits set. Compare packet captures at the client and the server, and check if packets the client sends with ECN marking in the IP header are received at the server with ECN marking. Any of the following ECN field transitions are valid, where the left side is the sender and the right side is the receiver:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Not-ECT → Not-ECT",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "ECT1 → ECT1",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "ECT0 → ECT0",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "ECT1 → CE",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "ECT0 → CE",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "CE → CE",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If you see any other transition, it means that network doesn’t support ECN correctly. To check which hop of your network doesn’t support ECN correctly, you can use Tracebox. Here is an example usage:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "sudo tracebox -v -p \"ip{ecn=1}/udp{dst=33451}\" apple.com"
          ],
          "syntax": "shell",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Every line in the Tracebox output shows a hop and packet headers that were modified before they reached that hop. This helps you identify the hop that modified ECN bits on the packet. For example, in the output below, ",
              "type": "text"
            },
            {
              "code": "IP::ExpCongestionNot (1 → 0)",
              "type": "codeVoice"
            },
            {
              "text": " on the third line means that hop 2 bleached the ECN bit (from 1→0) because hop 3 received a packet with modified ECN bits.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "1: a.b.c.d 0ms IP::CheckSum (0x45bf → 0x6d97)",
            "2: e.f.h.g 1ms IP::TTL (2 → 1) IP::CheckSum (0x44bf → 0x6d97)",
            "3: h.i.j.k 3ms IP::ExpCongestionNot (1 → 0) IP::TTL (3 → 1) IP::CheckSum (0x6ec0 → 0x9879)"
          ],
          "syntax": null,
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The second aspect is to check if your network bottleneck supports L4S queue management. Most bottleneck links use a traditional tail-drop queue, which keeps buffering packets until the queue is full and then drops packets at the tail end of the queue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Active Queue Management (AQM) has been deployed at some bottlenecks. It drops selected packets earlier in the buffer, which keeps the queue shorter and leaves the rest of the buffer empty for bursts. After ECN was standardized, some networks implemented what is now known as Classic ECN AQM. Classic ECN AQM is an advance over a tail-drop queue, but it reduces network delays to a limited extent. With L4S, the sender and the network can use L4S ECN to reduce queuing delays even further. In most cases, a network bottleneck that supports L4S AQM can reduce the worst 1 percent of queuing delays by about 10 times compared to Classic ECN AQM.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To verify that your network bottleneck supports L4S, run the following test:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Start an L4S flow and a non-L4S flow together in the direction (upload or download) you want to test, running them long enough to be sure to saturate the bottleneck. Consider using two devices, one with L4S turned on and the other with L4S turned off.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Take a packet capture at the receiver, and check if there are non-zero CE counts in the IP header of received packets as shown below.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4241170",
              "type": "image"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "3. If you can’t take a packet capture at the receiver, you can verify the CE counts in the ACK header at the sender. The figure below shows how QUIC formats the ACK header.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4241169",
              "type": "image"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "4. The screenshot below for TCP shows both CE counts in ACE flags and byte counts for ECT(1), CE, and ECT(0) in Accurate ECN options.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4241168",
              "type": "image"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "5. If there are no CE marks for either flow, your network bottleneck doesn’t support either Classic ECN AQM or L4S AQM.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "6. If either flow has CE marks, measure the round-trip time (or alternatively, the one way delay) of each flow. If both L4S and non-L4S flow have the same round-trip time, your network bottleneck likely supports classic ECN AQM. If the L4S flow has a lower round-trip time than the non-L4S flow, your network bottleneck likely supports L4S AQM.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Ensure-Low-Latency-and-Low-Loss-on-Your-Network",
          "level": 3,
          "text": "Ensure Low Latency and Low Loss on Your Network",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you’re a network operator, you can take a couple of actions to provide low latency and low loss to your users.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Check that your network configuration doesn’t bleach, alter, or block ECN traffic because doing any of these actions may harm the traffic. However, your network might be accidentally doing it while it’s trying to zero the Differentiated Services Codepoint (DSCP) because both the Diffserv and ECN fields are in the same IP header byte. You can fix this in your code or ask your equipment provider to provide a bug fix that zeros only the DSCP portion (bytes 8-13).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            " 0                   1                   2                   3",
            " 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1",
            "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+",
            "|Version|  IHL  |   DSCP    |ECN|         Total Length          |"
          ],
          "syntax": null,
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To allow your users to get even lower latency, consider deploying L4S-capable queue management. An example of an L4S AQM is IETF-standardized ",
              "type": "text"
            },
            {
              "identifier": "https://datatracker.ietf.org/doc/rfc9332",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Another alternative is Per-Flow Queue L4S AQM.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/choosing-a-network-debugging-tool": {
      "abstract": [
        {
          "text": "Decide which tool works best for your network debugging problem.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/choosing-a-network-debugging-tool",
      "kind": "article",
      "role": "article",
      "title": "Choosing a Network Debugging Tool",
      "type": "topic",
      "url": "/documentation/network/choosing-a-network-debugging-tool"
    },
    "doc://com.apple.network/documentation/Network/debugging-http-server-side-errors": {
      "abstract": [
        {
          "text": "Understand HTTP server-side errors and how to debug them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/debugging-http-server-side-errors",
      "kind": "article",
      "role": "article",
      "title": "Debugging HTTP Server-Side Errors",
      "type": "topic",
      "url": "/documentation/network/debugging-http-server-side-errors"
    },
    "doc://com.apple.network/documentation/Network/debugging-https-problems-with-cfnetwork-diagnostic-logging": {
      "abstract": [
        {
          "text": "Use CFNetwork diagnostic logging to investigate HTTP and HTTPS problems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/debugging-https-problems-with-cfnetwork-diagnostic-logging",
      "kind": "article",
      "role": "article",
      "title": "Debugging HTTPS Problems with CFNetwork Diagnostic Logging",
      "type": "topic",
      "url": "/documentation/network/debugging-https-problems-with-cfnetwork-diagnostic-logging"
    },
    "doc://com.apple.network/documentation/Network/recording-a-packet-trace": {
      "abstract": [
        {
          "text": "Learn how to record a low-level trace of network traffic.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/recording-a-packet-trace",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Recording a Packet Trace",
      "type": "topic",
      "url": "/documentation/network/recording-a-packet-trace"
    },
    "doc://com.apple.network/documentation/Network/taking-advantage-of-third-party-network-debugging-tools": {
      "abstract": [
        {
          "text": "Learn about the available third-party network debugging tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/taking-advantage-of-third-party-network-debugging-tools",
      "kind": "article",
      "role": "article",
      "title": "Taking Advantage of Third-Party Network Debugging Tools",
      "type": "topic",
      "url": "/documentation/network/taking-advantage-of-third-party-network-debugging-tools"
    },
    "https://datatracker.ietf.org/doc/rfc9332": {
      "identifier": "https://datatracker.ietf.org/doc/rfc9332",
      "title": "Dual-Queue Coupled AQM",
      "titleInlineContent": [
        {
          "text": "Dual-Queue Coupled AQM",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://datatracker.ietf.org/doc/rfc9332"
    },
    "https://github.com/L4STeam/linux": {
      "identifier": "https://github.com/L4STeam/linux",
      "title": "This Linux repository",
      "titleInlineContent": [
        {
          "text": "This Linux repository",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://github.com/L4STeam/linux"
    },
    "media-4225936": {
      "alt": null,
      "identifier": "media-4225936",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0dbddc44800f42c6b312258d9de33a0c/media-4225936@2x.png"
        }
      ]
    },
    "media-4225937": {
      "alt": null,
      "identifier": "media-4225937",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6c81b9001fd2da289793c397b6179cdf/media-4225937@2x.png"
        }
      ]
    },
    "media-4225939": {
      "alt": null,
      "identifier": "media-4225939",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c6646351351003937460fe4d01e956f2/media-4225939@2x.png"
        }
      ]
    },
    "media-4225940": {
      "alt": null,
      "identifier": "media-4225940",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/acab774efabed5154c6d6335dce08c44/media-4225940@2x.png"
        }
      ]
    },
    "media-4225942": {
      "alt": null,
      "identifier": "media-4225942",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1c2c811615d9562841f9fa7299e7c933/media-4225942@2x.png"
        }
      ]
    },
    "media-4225943": {
      "alt": null,
      "identifier": "media-4225943",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fa5220dbadbf2b769eced63310be06bd/media-4225943@2x.png"
        }
      ]
    },
    "media-4225969": {
      "alt": null,
      "identifier": "media-4225969",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8cbc8fdad80345633d34a8719b27ccfd/media-4225969@2x.png"
        }
      ]
    },
    "media-4225970": {
      "alt": null,
      "identifier": "media-4225970",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e322cf90620195fa7da546a103559512/media-4225970@2x.png"
        }
      ]
    },
    "media-4241168": {
      "alt": null,
      "identifier": "media-4241168",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/206dfc625e83595d05abbb7fcc14ad93/media-4241168@2x.png"
        }
      ]
    },
    "media-4241169": {
      "alt": null,
      "identifier": "media-4241169",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ce7174a9a475afa38718cc92229ceb3d/media-4241169@2x.png"
        }
      ]
    },
    "media-4241170": {
      "alt": null,
      "identifier": "media-4241170",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/f1836f82070bc2fb94fd2c931591cd03/media-4241170@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Debugging",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/choosing-a-network-debugging-tool",
        "doc://com.apple.network/documentation/Network/debugging-http-server-side-errors",
        "doc://com.apple.network/documentation/Network/debugging-https-problems-with-cfnetwork-diagnostic-logging",
        "doc://com.apple.network/documentation/Network/recording-a-packet-trace",
        "doc://com.apple.network/documentation/Network/taking-advantage-of-third-party-network-debugging-tools"
      ],
      "title": "Network Debugging"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Network-Debugging",
              "generated": true,
              "identifiers": [
                "doc://com.apple.network/documentation/Network/choosing-a-network-debugging-tool",
                "doc://com.apple.network/documentation/Network/debugging-http-server-side-errors",
                "doc://com.apple.network/documentation/Network/debugging-https-problems-with-cfnetwork-diagnostic-logging",
                "doc://com.apple.network/documentation/Network/recording-a-packet-trace",
                "doc://com.apple.network/documentation/Network/taking-advantage-of-third-party-network-debugging-tools"
              ],
              "title": "Network Debugging"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/testing-and-debugging-l4s-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/network/testing-and-debugging-l4s-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
