{
  "abstract": [
    {
      "text": "Configure options for connections that use Transport Layer Security.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.network/documentation/Network/tls-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "TLS Options"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/framer-protocol-options": {
      "abstract": [
        {
          "text": "Create custom protocols to frame applications messages over a connection.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/framer-protocol-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Framer Protocol Options",
      "type": "topic",
      "url": "/documentation/network/framer-protocol-options"
    },
    "doc://com.apple.network/documentation/Network/ip-options": {
      "abstract": [
        {
          "text": "Configure Internet Protocol options on connections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/ip-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IP Options",
      "type": "topic",
      "url": "/documentation/network/ip-options"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_copy_tls_definition()": {
      "abstract": [
        {
          "text": "Accesses the system definition of the Transport Layer Security protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_tls_definition"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_copy_tls_definition()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_tls_definition"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_copy_tls_definition()",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_copy_tls_definition()"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_tls(_:)": {
      "abstract": [
        {
          "text": "Checks whether a metadata object contains TLS connection state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_tls"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_tls(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_tls"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_metadata_is_tls(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_metadata_is_tls(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tls_copy_sec_protocol_metadata(_:)": {
      "abstract": [
        {
          "text": "Accesses the result of the TLS handshake.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tls_copy_sec_protocol_metadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sec_protocol_metadata_t",
          "text": "sec_protocol_metadata_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tls_copy_sec_protocol_metadata(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tls_copy_sec_protocol_metadata"
        }
      ],
      "role": "symbol",
      "title": "nw_tls_copy_sec_protocol_metadata(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tls_copy_sec_protocol_metadata(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tls_copy_sec_protocol_options(_:)": {
      "abstract": [
        {
          "text": "Accesses the handshake security options TLS will use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tls_copy_sec_protocol_options"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sec_protocol_options_t",
          "text": "sec_protocol_options_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tls_copy_sec_protocol_options(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tls_copy_sec_protocol_options"
        }
      ],
      "role": "symbol",
      "title": "nw_tls_copy_sec_protocol_options(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_tls_copy_sec_protocol_options(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_tls_create_options()": {
      "abstract": [
        {
          "text": "Initializes a default set of TLS connection options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_tls_create_options"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_tls_create_options()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_tls_create_options"
        }
      ],
      "role": "symbol",
      "title": "nw_tls_create_options()",
      "type": "topic",
      "url": "/documentation/network/nw_tls_create_options()"
    },
    "doc://com.apple.network/documentation/Network/quic-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the QUIC transport protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/quic-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QUIC Options",
      "type": "topic",
      "url": "/documentation/network/quic-options"
    },
    "doc://com.apple.network/documentation/Network/tcp-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the Transmission Control Protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/tcp-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TCP Options",
      "type": "topic",
      "url": "/documentation/network/tcp-options"
    },
    "doc://com.apple.network/documentation/Network/udp-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the User Datagram Protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/udp-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UDP Options",
      "type": "topic",
      "url": "/documentation/network/udp-options"
    },
    "doc://com.apple.network/documentation/Network/websocket-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use WebSocket.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/websocket-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebSocket Options",
      "type": "topic",
      "url": "/documentation/network/websocket-options"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/tcp-options",
        "doc://com.apple.network/documentation/Network/quic-options",
        "doc://com.apple.network/documentation/Network/udp-options",
        "doc://com.apple.network/documentation/Network/ip-options",
        "doc://com.apple.network/documentation/Network/websocket-options",
        "doc://com.apple.network/documentation/Network/framer-protocol-options"
      ],
      "title": "Network Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-TLS-Connections",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_copy_tls_definition()",
        "doc://com.apple.network/documentation/Network/nw_tls_create_options()",
        "doc://com.apple.network/documentation/Network/nw_tls_copy_sec_protocol_options(_:)"
      ],
      "title": "Creating TLS Connections"
    },
    {
      "anchor": "Inspecting-TLS-State",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_tls(_:)",
        "doc://com.apple.network/documentation/Network/nw_tls_copy_sec_protocol_metadata(_:)"
      ],
      "title": "Inspecting TLS State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tls_copy_sec_protocol_options(_:)/title",
          "value": "nw_tls_copy_sec_protocol_options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tls_copy_sec_protocol_options(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tls_copy_sec_protocol_options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_tls_definition()/title",
          "value": "nw_protocol_copy_tls_definition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_tls_definition()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_copy_tls_definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_tls(_:)/title",
          "value": "nw_protocol_metadata_is_tls"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_tls(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_metadata_is_tls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tls_create_options()/title",
          "value": "nw_tls_create_options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tls_create_options()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tls_create_options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tls_copy_sec_protocol_metadata(_:)/title",
          "value": "nw_tls_copy_sec_protocol_metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_tls_copy_sec_protocol_metadata(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_tls_copy_sec_protocol_metadata"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/tls-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
