{
  "abstract": [
    {
      "text": "Configure options for connections that use the User Datagram Protocol.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.network/documentation/Network/udp-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "UDP Options"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/framer-protocol-options": {
      "abstract": [
        {
          "text": "Create custom protocols to frame applications messages over a connection.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/framer-protocol-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Framer Protocol Options",
      "type": "topic",
      "url": "/documentation/network/framer-protocol-options"
    },
    "doc://com.apple.network/documentation/Network/ip-options": {
      "abstract": [
        {
          "text": "Configure Internet Protocol options on connections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/ip-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IP Options",
      "type": "topic",
      "url": "/documentation/network/ip-options"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_copy_udp_definition()": {
      "abstract": [
        {
          "text": "Accesses the system definition of the User Datagram Protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_udp_definition"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_copy_udp_definition()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_udp_definition"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_copy_udp_definition()",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_copy_udp_definition()"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_udp(_:)": {
      "abstract": [
        {
          "text": "Checks whether a metadata object represents a UDP datagram.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_udp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_udp(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_udp"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_metadata_is_udp(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_metadata_is_udp(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_udp_create_metadata()": {
      "abstract": [
        {
          "text": "Initializes a default UDP message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_udp_create_metadata"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_udp_create_metadata()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_udp_create_metadata"
        }
      ],
      "role": "symbol",
      "title": "nw_udp_create_metadata()",
      "type": "topic",
      "url": "/documentation/network/nw_udp_create_metadata()"
    },
    "doc://com.apple.network/documentation/Network/nw_udp_create_options()": {
      "abstract": [
        {
          "text": "Initializes a default set of UDP connection options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_udp_create_options"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_udp_create_options()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_udp_create_options"
        }
      ],
      "role": "symbol",
      "title": "nw_udp_create_options()",
      "type": "topic",
      "url": "/documentation/network/nw_udp_create_options()"
    },
    "doc://com.apple.network/documentation/Network/nw_udp_options_set_prefer_no_checksum(_:_:)": {
      "abstract": [
        {
          "text": "Configures the connection to not send UDP checksums.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_udp_options_set_prefer_no_checksum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_udp_options_set_prefer_no_checksum(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_udp_options_set_prefer_no_checksum"
        }
      ],
      "role": "symbol",
      "title": "nw_udp_options_set_prefer_no_checksum(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_udp_options_set_prefer_no_checksum(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/quic-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the QUIC transport protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/quic-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QUIC Options",
      "type": "topic",
      "url": "/documentation/network/quic-options"
    },
    "doc://com.apple.network/documentation/Network/tcp-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the Transmission Control Protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/tcp-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TCP Options",
      "type": "topic",
      "url": "/documentation/network/tcp-options"
    },
    "doc://com.apple.network/documentation/Network/tls-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use Transport Layer Security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/tls-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TLS Options",
      "type": "topic",
      "url": "/documentation/network/tls-options"
    },
    "doc://com.apple.network/documentation/Network/websocket-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use WebSocket.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/websocket-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "WebSocket Options",
      "type": "topic",
      "url": "/documentation/network/websocket-options"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/tcp-options",
        "doc://com.apple.network/documentation/Network/tls-options",
        "doc://com.apple.network/documentation/Network/quic-options",
        "doc://com.apple.network/documentation/Network/ip-options",
        "doc://com.apple.network/documentation/Network/websocket-options",
        "doc://com.apple.network/documentation/Network/framer-protocol-options"
      ],
      "title": "Network Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-UDP-Connections",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_copy_udp_definition()",
        "doc://com.apple.network/documentation/Network/nw_udp_create_options()"
      ],
      "title": "Creating UDP Connections"
    },
    {
      "anchor": "Customizing-UDP-Connections",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_udp_options_set_prefer_no_checksum(_:_:)"
      ],
      "title": "Customizing UDP Connections"
    },
    {
      "anchor": "Sending-UDP-Messages",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_udp(_:)",
        "doc://com.apple.network/documentation/Network/nw_udp_create_metadata()"
      ],
      "title": "Sending UDP Messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_udp_create_metadata()/title",
          "value": "nw_udp_create_metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_udp_create_metadata()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_udp_create_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_udp_options_set_prefer_no_checksum(_:_:)/title",
          "value": "nw_udp_options_set_prefer_no_checksum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_udp_options_set_prefer_no_checksum(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_udp_options_set_prefer_no_checksum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_udp_create_options()/title",
          "value": "nw_udp_create_options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_udp_create_options()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_udp_create_options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_udp_definition()/title",
          "value": "nw_protocol_copy_udp_definition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_udp_definition()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_copy_udp_definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_udp(_:)/title",
          "value": "nw_protocol_metadata_is_udp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_udp(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_metadata_is_udp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/udp-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
