{
  "abstract": [
    {
      "text": "Configure options for connections that use WebSocket.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.network/documentation/Network"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.network/documentation/Network/websocket-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Network"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "WebSocket Options"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.network/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/network"
    },
    "doc://com.apple.network/documentation/Network/framer-protocol-options": {
      "abstract": [
        {
          "text": "Create custom protocols to frame applications messages over a connection.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/framer-protocol-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Framer Protocol Options",
      "type": "topic",
      "url": "/documentation/network/framer-protocol-options"
    },
    "doc://com.apple.network/documentation/Network/ip-options": {
      "abstract": [
        {
          "text": "Configure Internet Protocol options on connections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/ip-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IP Options",
      "type": "topic",
      "url": "/documentation/network/ip-options"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_copy_ws_definition()": {
      "abstract": [
        {
          "text": "Accesses the system definition of the WebSocket protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_ws_definition"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_definition_t",
          "text": "nw_protocol_definition_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_copy_ws_definition()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_copy_ws_definition"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_copy_ws_definition()",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_copy_ws_definition()"
    },
    "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_ws(_:)": {
      "abstract": [
        {
          "text": "Checks whether a metadata object represents a WebSocket message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_ws"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_ws(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_protocol_metadata_is_ws"
        }
      ],
      "role": "symbol",
      "title": "nw_protocol_metadata_is_ws(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_protocol_metadata_is_ws(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_additional_header_enumerator_t": {
      "abstract": [
        {
          "text": "A block that enumerates additional HTTP headers in a WebSocket client request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_additional_header_enumerator_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_additional_header_enumerator_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_additional_header_enumerator_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_additional_header_enumerator_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_additional_header_enumerator_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_client_request_handler_t": {
      "abstract": [
        {
          "text": "A handler that delivers inbound client handshake requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_client_request_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_client_request_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_client_request_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_client_request_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_client_request_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_close_code_t": {
      "abstract": [
        {
          "text": "Types of codes used upon closing a WebSocket connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_close_code_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_close_code_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_close_code_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_close_code_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_create_metadata(_:)": {
      "abstract": [
        {
          "text": "Initializes a WebSocket message with a specific type code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_create_metadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_opcode_t",
          "text": "nw_ws_opcode_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_create_metadata(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_create_metadata"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_create_metadata(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_create_metadata(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_create_options(_:)": {
      "abstract": [
        {
          "text": "Initializes a default set of WebSocket connection options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_create_options"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_version_t",
          "text": "nw_ws_version_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_create_options(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_create_options"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_create_options(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_create_options(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_metadata_copy_server_response(_:)": {
      "abstract": [
        {
          "text": "Accesses the WebSocket server’s response sent during the handshake.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_metadata_copy_server_response"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ws_response_t",
          "text": "nw_ws_response_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_metadata_copy_server_response(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_metadata_copy_server_response"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_metadata_copy_server_response(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_metadata_copy_server_response(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_metadata_get_close_code(_:)": {
      "abstract": [
        {
          "text": "Accesses the close code on a WebSocket message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_metadata_get_close_code"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_metadata_get_close_code(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_metadata_get_close_code"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_metadata_get_close_code(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_metadata_get_close_code(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_metadata_get_opcode(_:)": {
      "abstract": [
        {
          "text": "Checks the type code on a WebSocket message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_metadata_get_opcode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_opcode_t",
          "text": "nw_ws_opcode_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_metadata_get_opcode(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_metadata_get_opcode"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_metadata_get_opcode(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_metadata_get_opcode(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_metadata_set_close_code(_:_:)": {
      "abstract": [
        {
          "text": "Sets a close code on a WebSocket message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_metadata_set_close_code"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_close_code_t",
          "text": "nw_ws_close_code_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_metadata_set_close_code(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_metadata_set_close_code"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_metadata_set_close_code(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_metadata_set_close_code(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_metadata_set_pong_handler(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler on a Ping message to be invoked when the corresponding Pong message is received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_metadata_set_pong_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_metadata_t",
          "text": "nw_protocol_metadata_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ws_pong_handler_t",
          "text": "nw_ws_pong_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_metadata_set_pong_handler(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_metadata_set_pong_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_metadata_set_pong_handler(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_metadata_set_pong_handler(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_opcode_t": {
      "abstract": [
        {
          "text": "Types of messages that you send and receive on a WebSocket connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_opcode_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_opcode_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_opcode_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_opcode_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_opcode_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_options_add_additional_header(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds additional HTTP header fields to be sent by the client during the WebSocket handshake.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_options_add_additional_header"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_options_add_additional_header(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_options_add_additional_header"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_options_add_additional_header(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_options_add_additional_header(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_options_add_subprotocol(_:_:)": {
      "abstract": [
        {
          "text": "Adds to the list of supported application protocols that will be presented to a WebSocket server during connection establishment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_options_add_subprotocol"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_options_add_subprotocol(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_options_add_subprotocol"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_options_add_subprotocol(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_options_add_subprotocol(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_options_set_auto_reply_ping(_:_:)": {
      "abstract": [
        {
          "text": "Configures the connection to automatically reply to Ping messages instead of delivering them to you.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_options_set_auto_reply_ping"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_options_set_auto_reply_ping(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_options_set_auto_reply_ping"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_options_set_auto_reply_ping(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_options_set_auto_reply_ping(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_options_set_client_request_handler(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a handler to react to as a server to inbound WebSocket client handshakes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_options_set_client_request_handler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ws_client_request_handler_t",
          "text": "nw_ws_client_request_handler_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_options_set_client_request_handler(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_options_set_client_request_handler"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_options_set_client_request_handler(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_options_set_client_request_handler(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_options_set_maximum_message_size(_:_:)": {
      "abstract": [
        {
          "text": "Sets the maximum allowed message size, in bytes, to be received by the WebSocket connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_options_set_maximum_message_size"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_options_set_maximum_message_size(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_options_set_maximum_message_size"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_options_set_maximum_message_size(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_options_set_maximum_message_size(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_options_set_skip_handshake(_:_:)": {
      "abstract": [
        {
          "text": "Specifies whether the WebSocket protocol skips its handshake and begins framing data once the underlying connection is established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_options_set_skip_handshake"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_protocol_options_t",
          "text": "nw_protocol_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_options_set_skip_handshake(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_options_set_skip_handshake"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_options_set_skip_handshake(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_options_set_skip_handshake(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_pong_handler_t": {
      "abstract": [
        {
          "text": "A handler that indicates that a Pong message has been received for a previously sent Ping message, or that an error was encountered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_pong_handler_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_pong_handler_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_pong_handler_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_pong_handler_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_pong_handler_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_request_enumerate_additional_headers(_:_:)": {
      "abstract": [
        {
          "text": "Enumerates additional HTTP headers in a WebSocket message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_request_enumerate_additional_headers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ws_request_t",
          "text": "nw_ws_request_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_request_enumerate_additional_headers(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_request_enumerate_additional_headers"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_request_enumerate_additional_headers(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_request_enumerate_additional_headers(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_request_enumerate_subprotocols(_:_:)": {
      "abstract": [
        {
          "text": "Enumerates the supported subprotocols in a WebSocket message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_request_enumerate_subprotocols"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ws_request_t",
          "text": "nw_ws_request_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_request_enumerate_subprotocols(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_request_enumerate_subprotocols"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_request_enumerate_subprotocols(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_request_enumerate_subprotocols(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_request_t": {
      "abstract": [
        {
          "text": "A WebSocket handshake request sent from a client to a server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_request_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_request_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_request_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_request_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_request_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_response_add_additional_header(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an additional HTTP header to a WebSocket server response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_response_add_additional_header"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ws_response_t",
          "text": "nw_ws_response_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_response_add_additional_header(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_response_add_additional_header"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_response_add_additional_header(_:_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_response_add_additional_header(_:_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_response_create(_:_:)": {
      "abstract": [
        {
          "text": "Initializes a WebSocket server response with a status and selected subprotocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_response_create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_response_status_t",
          "text": "nw_ws_response_status_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ws_response_t",
          "text": "nw_ws_response_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_response_create(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_response_create"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_response_create(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_response_create(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_response_enumerate_additional_headers(_:_:)": {
      "abstract": [
        {
          "text": "Enumerates the additional HTTP headers in a WebSocket server response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_response_enumerate_additional_headers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ws_response_t",
          "text": "nw_ws_response_t"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_response_enumerate_additional_headers(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_response_enumerate_additional_headers"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_response_enumerate_additional_headers(_:_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_response_enumerate_additional_headers(_:_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_response_get_selected_subprotocol(_:)": {
      "abstract": [
        {
          "text": "Accesses the selected subprotocol in a WebSocket server response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_response_get_selected_subprotocol"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ws_response_t",
          "text": "nw_ws_response_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_response_get_selected_subprotocol(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_response_get_selected_subprotocol"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_response_get_selected_subprotocol(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_response_get_selected_subprotocol(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_response_get_status(_:)": {
      "abstract": [
        {
          "text": "Accesses the status of a WebSocket server response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_response_get_status"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_ws_response_t",
          "text": "nw_ws_response_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@nw_ws_response_status_t",
          "text": "nw_ws_response_status_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_response_get_status(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_response_get_status"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_response_get_status(_:)",
      "type": "topic",
      "url": "/documentation/network/nw_ws_response_get_status(_:)"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_response_status_t": {
      "abstract": [
        {
          "text": "Status values that are sent with a WebSocket server response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_response_status_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_response_status_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_response_status_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_response_status_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_response_status_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_response_t": {
      "abstract": [
        {
          "text": "A WebSocket handshake reponse sent from a server to a client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_response_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_response_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_response_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_response_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_response_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_subprotocol_enumerator_t": {
      "abstract": [
        {
          "text": "A block that enumerates the supported subprotocols in a WebSocket client request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_subprotocol_enumerator_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_subprotocol_enumerator_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_subprotocol_enumerator_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_subprotocol_enumerator_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_subprotocol_enumerator_t"
    },
    "doc://com.apple.network/documentation/Network/nw_ws_version_t": {
      "abstract": [
        {
          "text": "Supported versions of the WebSocket protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_ws_version_t"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/nw_ws_version_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nw_ws_version_t"
        }
      ],
      "role": "symbol",
      "title": "nw_ws_version_t",
      "type": "topic",
      "url": "/documentation/network/nw_ws_version_t"
    },
    "doc://com.apple.network/documentation/Network/quic-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the QUIC transport protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/quic-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QUIC Options",
      "type": "topic",
      "url": "/documentation/network/quic-options"
    },
    "doc://com.apple.network/documentation/Network/tcp-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the Transmission Control Protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/tcp-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TCP Options",
      "type": "topic",
      "url": "/documentation/network/tcp-options"
    },
    "doc://com.apple.network/documentation/Network/tls-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use Transport Layer Security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/tls-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TLS Options",
      "type": "topic",
      "url": "/documentation/network/tls-options"
    },
    "doc://com.apple.network/documentation/Network/udp-options": {
      "abstract": [
        {
          "text": "Configure options for connections that use the User Datagram Protocol.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.network/documentation/Network/udp-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UDP Options",
      "type": "topic",
      "url": "/documentation/network/udp-options"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.network/documentation/Network/tcp-options",
        "doc://com.apple.network/documentation/Network/tls-options",
        "doc://com.apple.network/documentation/Network/quic-options",
        "doc://com.apple.network/documentation/Network/udp-options",
        "doc://com.apple.network/documentation/Network/ip-options",
        "doc://com.apple.network/documentation/Network/framer-protocol-options"
      ],
      "title": "Network Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-WebSocket-Connections",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_copy_ws_definition()",
        "doc://com.apple.network/documentation/Network/nw_ws_create_options(_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_version_t",
        "doc://com.apple.network/documentation/Network/nw_ws_options_set_auto_reply_ping(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_options_set_maximum_message_size(_:_:)"
      ],
      "title": "Creating WebSocket Connections"
    },
    {
      "anchor": "Configuring-Client-Handshakes",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ws_options_add_additional_header(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_options_add_subprotocol(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_options_set_skip_handshake(_:_:)"
      ],
      "title": "Configuring Client Handshakes"
    },
    {
      "anchor": "Handling-WebSocket-Messages",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_protocol_metadata_is_ws(_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_create_metadata(_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_metadata_get_opcode(_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_opcode_t",
        "doc://com.apple.network/documentation/Network/nw_ws_metadata_set_close_code(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_metadata_get_close_code(_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_close_code_t",
        "doc://com.apple.network/documentation/Network/nw_ws_metadata_set_pong_handler(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_pong_handler_t",
        "doc://com.apple.network/documentation/Network/nw_ws_metadata_copy_server_response(_:)"
      ],
      "title": "Handling WebSocket Messages"
    },
    {
      "anchor": "Handling-Server-Handshakes",
      "identifiers": [
        "doc://com.apple.network/documentation/Network/nw_ws_options_set_client_request_handler(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_client_request_handler_t",
        "doc://com.apple.network/documentation/Network/nw_ws_request_t",
        "doc://com.apple.network/documentation/Network/nw_ws_request_enumerate_subprotocols(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_subprotocol_enumerator_t",
        "doc://com.apple.network/documentation/Network/nw_ws_request_enumerate_additional_headers(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_additional_header_enumerator_t",
        "doc://com.apple.network/documentation/Network/nw_ws_response_t",
        "doc://com.apple.network/documentation/Network/nw_ws_response_create(_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_response_status_t",
        "doc://com.apple.network/documentation/Network/nw_ws_response_add_additional_header(_:_:_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_response_get_status(_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_response_get_selected_subprotocol(_:)",
        "doc://com.apple.network/documentation/Network/nw_ws_response_enumerate_additional_headers(_:_:)"
      ],
      "title": "Handling Server Handshakes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_ws_definition()/title",
          "value": "nw_protocol_copy_ws_definition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_copy_ws_definition()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_copy_ws_definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_status_t/title",
          "value": "nw_ws_response_status_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_status_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_status_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_get_status(_:)/title",
          "value": "nw_ws_response_get_status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_get_status(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_get_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_metadata_set_pong_handler(_:_:_:)/title",
          "value": "nw_ws_metadata_set_pong_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_metadata_set_pong_handler(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_metadata_set_pong_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_additional_header_enumerator_t/title",
          "value": "nw_ws_additional_header_enumerator_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_additional_header_enumerator_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_additional_header_enumerator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_additional_header_enumerator_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_additional_header_enumerator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_add_additional_header(_:_:_:)/title",
          "value": "nw_ws_response_add_additional_header"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_add_additional_header(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_add_additional_header"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_metadata_copy_server_response(_:)/title",
          "value": "nw_ws_metadata_copy_server_response"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_metadata_copy_server_response(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_metadata_copy_server_response"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_set_auto_reply_ping(_:_:)/title",
          "value": "nw_ws_options_set_auto_reply_ping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_set_auto_reply_ping(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_options_set_auto_reply_ping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_create_metadata(_:)/title",
          "value": "nw_ws_create_metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_create_metadata(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_create_metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_opcode_t/title",
          "value": "nw_ws_opcode_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_opcode_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_opcode_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_opcode_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_opcode_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_create(_:_:)/title",
          "value": "nw_ws_response_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_create(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_request_t/title",
          "value": "nw_ws_request_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_request_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_request_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_request_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_request_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_request_enumerate_additional_headers(_:_:)/title",
          "value": "nw_ws_request_enumerate_additional_headers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_request_enumerate_additional_headers(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_request_enumerate_additional_headers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_t/title",
          "value": "nw_ws_close_code_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_close_code_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_close_code_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_add_additional_header(_:_:_:)/title",
          "value": "nw_ws_options_add_additional_header"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_add_additional_header(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_options_add_additional_header"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_metadata_set_close_code(_:_:)/title",
          "value": "nw_ws_metadata_set_close_code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_metadata_set_close_code(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_metadata_set_close_code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_version_t/title",
          "value": "nw_ws_version_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_version_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_version_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_metadata_get_opcode(_:)/title",
          "value": "nw_ws_metadata_get_opcode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_metadata_get_opcode(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_metadata_get_opcode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_client_request_handler_t/title",
          "value": "nw_ws_client_request_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_client_request_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_client_request_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_client_request_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_client_request_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_set_client_request_handler(_:_:_:)/title",
          "value": "nw_ws_options_set_client_request_handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_set_client_request_handler(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_options_set_client_request_handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_set_skip_handshake(_:_:)/title",
          "value": "nw_ws_options_set_skip_handshake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_set_skip_handshake(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_options_set_skip_handshake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_t/title",
          "value": "nw_ws_response_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_ws(_:)/title",
          "value": "nw_protocol_metadata_is_ws"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_protocol_metadata_is_ws(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_protocol_metadata_is_ws"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_add_subprotocol(_:_:)/title",
          "value": "nw_ws_options_add_subprotocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_add_subprotocol(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_options_add_subprotocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_enumerate_additional_headers(_:_:)/title",
          "value": "nw_ws_response_enumerate_additional_headers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_enumerate_additional_headers(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_enumerate_additional_headers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_get_selected_subprotocol(_:)/title",
          "value": "nw_ws_response_get_selected_subprotocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_response_get_selected_subprotocol(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_response_get_selected_subprotocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_pong_handler_t/title",
          "value": "nw_ws_pong_handler_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_pong_handler_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_pong_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_pong_handler_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_pong_handler_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_request_enumerate_subprotocols(_:_:)/title",
          "value": "nw_ws_request_enumerate_subprotocols"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_request_enumerate_subprotocols(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_request_enumerate_subprotocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_metadata_get_close_code(_:)/title",
          "value": "nw_ws_metadata_get_close_code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_metadata_get_close_code(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_metadata_get_close_code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_subprotocol_enumerator_t/title",
          "value": "nw_ws_subprotocol_enumerator_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_subprotocol_enumerator_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_subprotocol_enumerator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_subprotocol_enumerator_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_subprotocol_enumerator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_set_maximum_message_size(_:_:)/title",
          "value": "nw_ws_options_set_maximum_message_size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_options_set_maximum_message_size(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_options_set_maximum_message_size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_create_options(_:)/title",
          "value": "nw_ws_create_options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.network~1documentation~1Network~1nw_ws_create_options(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nw_ws_create_options"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/network/websocket-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
