{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messageui/documentation/MessageUI",
        "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction/none"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MFMailComposeControllerDeferredAction@MFMailComposeControllerDeferredActionNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "none"
      }
    ],
    "modules": [
      {
        "name": "Message UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MFMailComposeControllerDeferredActionNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MFMailComposeControllerDeferredAction.none"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "none"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messageui/documentation/MessageUI": {
      "abstract": [
        {
          "text": "Create a user interface for composing email and text messages, so users can edit and send messages without leaving your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Message UI",
      "type": "topic",
      "url": "/documentation/messageui"
    },
    "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MFMailComposeControllerDeferredAction"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MFMailComposeControllerDeferredAction"
        }
      ],
      "role": "symbol",
      "title": "MFMailComposeControllerDeferredAction",
      "type": "topic",
      "url": "/documentation/messageui/mfmailcomposecontrollerdeferredaction"
    },
    "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MFMailComposeControllerDeferredActionNone"
        }
      ],
      "role": "symbol",
      "title": "MFMailComposeControllerDeferredAction.none",
      "type": "topic",
      "url": "/documentation/messageui/mfmailcomposecontrollerdeferredaction/none"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MFMailComposeControllerDeferredActionNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMailComposeControllerDeferredActionNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.messageui/documentation/MessageUI",
                "doc://com.apple.messageui/documentation/MessageUI/MFMailComposeControllerDeferredAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MFMailComposeControllerDeferredActionNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeControllerDeferredAction~1none/title",
          "value": "MFMailComposeControllerDeferredActionNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeControllerDeferredAction~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMailComposeControllerDeferredActionNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeControllerDeferredAction/title",
          "value": "MFMailComposeControllerDeferredAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeControllerDeferredAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMailComposeControllerDeferredAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMailComposeControllerDeferredAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMailComposeControllerDeferredAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messageui/mfmailcomposecontrollerdeferredaction/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messageui/mfmailcomposecontrollerdeferredaction/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
