{
  "abstract": [
    {
      "text": "Returns the visible rows for the table or outline.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVisibleRows()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAccessibility(im)accessibilityVisibleRows",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessibilityVisibleRows"
      },
      {
        "kind": "text",
        "text": "() -> ["
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessibilityVisibleRows()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityVisibleRows"
            },
            {
              "kind": "text",
              "text": "() -> ["
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "]?"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityColumnHeaderUIElements()": {
      "abstract": [
        {
          "text": "Returns the column header accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityColumnHeaderUIElements"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityColumnHeaderUIElements()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityColumnHeaderUIElements()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitycolumnheaderuielements()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityColumnTitles()": {
      "abstract": [
        {
          "text": "Returns the column titles for the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityColumnTitles"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityColumnTitles()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityColumnTitles()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitycolumntitles()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityColumns()": {
      "abstract": [
        {
          "text": "Returns the column accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityColumns"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityColumns()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityColumns()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitycolumns()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHeader()": {
      "abstract": [
        {
          "text": "Returns the header for the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityHeader"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHeader()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityHeader()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityheader()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityIndex()": {
      "abstract": [
        {
          "text": "Returns the index of the row or column that the accessibility element represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityIndex"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityIndex()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityIndex()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityindex()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityRowHeaderUIElements()": {
      "abstract": [
        {
          "text": "Returns the row header accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityRowHeaderUIElements"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityRowHeaderUIElements()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityRowHeaderUIElements()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityrowheaderuielements()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityRows()": {
      "abstract": [
        {
          "text": "Returns the row accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityRows"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityRows()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityRows()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityrows()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVisibleRows()": {
      "abstract": [
        {
          "text": "Returns the visible rows for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityVisibleRows"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVisibleRows()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityVisibleRows()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityvisiblerows()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/isAccessibilityExpanded()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that determines whether the accessibility element is in an expanded state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAccessibilityExpanded"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/isAccessibilityExpanded()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "isAccessibilityExpanded()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/isaccessibilityexpanded()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityColumnHeaderUIElements(_:)": {
      "abstract": [
        {
          "text": "Sets the column header accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityColumnHeaderUIElements"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityColumnHeaderUIElements(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityColumnHeaderUIElements(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilitycolumnheaderuielements(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityColumnTitles(_:)": {
      "abstract": [
        {
          "text": "Sets the column titles for the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityColumnTitles"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityColumnTitles(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityColumnTitles(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilitycolumntitles(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityColumns(_:)": {
      "abstract": [
        {
          "text": "Sets the column accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityColumns"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityColumns(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityColumns(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilitycolumns(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityExpanded(_:)": {
      "abstract": [
        {
          "text": "Sets a Boolean value that determines whether accessibility element is in an expanded state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityExpanded"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityExpanded(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityExpanded(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityexpanded(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHeader(_:)": {
      "abstract": [
        {
          "text": "Sets the header for the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHeader(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityHeader(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityheader(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityIndex(_:)": {
      "abstract": [
        {
          "text": "Sets the index of the row or column that the accessibility element represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityIndex(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityIndex(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityindex(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityRowHeaderUIElements(_:)": {
      "abstract": [
        {
          "text": "Sets the row header accessibility elements for the table or outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityRowHeaderUIElements"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityRowHeaderUIElements(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityRowHeaderUIElements(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityrowheaderuielements(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Table-and-Outline-Views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityColumnHeaderUIElements()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityColumnHeaderUIElements(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityColumns()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityColumns(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityColumnTitles()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityColumnTitles(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/isAccessibilityExpanded()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityExpanded(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHeader()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHeader(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityIndex()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityIndex(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityRowHeaderUIElements()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityRowHeaderUIElements(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityRows()"
      ],
      "title": "Configuring Table and Outline Views"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibilityprotocol/accessibilityvisiblerows()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
