{
  "abstract": [
    {
      "text": "Returns the decrement button for the stepper accessibility element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityDecrementButton()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAccessibility(im)accessibilityDecrementButton",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessibilityDecrementButton"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessibilityDecrementButton()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityDecrementButton"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityDecrementButton()": {
      "abstract": [
        {
          "text": "Returns the decrement button for the stepper accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityDecrementButton"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityDecrementButton()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityDecrementButton()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitydecrementbutton()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityIncrementButton()": {
      "abstract": [
        {
          "text": "Returns the increment button for the stepper accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityIncrementButton"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityIncrementButton()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityIncrementButton()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityincrementbutton()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityPerformDecrement()": {
      "abstract": [
        {
          "text": "Decrements the accessibility element’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityPerformDecrement"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityPerformDecrement()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityPerformDecrement"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityPerformDecrement()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityperformdecrement()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityPerformDelete()": {
      "abstract": [
        {
          "text": "Deletes the accessibility element’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityPerformDelete"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityPerformDelete()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityPerformDelete"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityPerformDelete()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityperformdelete()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityPerformIncrement()": {
      "abstract": [
        {
          "text": "Increments the accessibility element’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityPerformIncrement"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityPerformIncrement()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityPerformIncrement"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityPerformIncrement()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityperformincrement()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityDecrementButton(_:)": {
      "abstract": [
        {
          "text": "Sets the decrement button for the stepper accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityDecrementButton"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityDecrementButton(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityDecrementButton(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilitydecrementbutton(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityIncrementButton(_:)": {
      "abstract": [
        {
          "text": "Sets the increment button for the stepper accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityIncrementButton"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityIncrementButton(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityIncrementButton(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityincrementbutton(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Incrementing-Decrementing-and-Deleting-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityIncrementButton()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityIncrementButton(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityDecrementButton(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityPerformIncrement()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityPerformDecrement()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityPerformDelete()"
      ],
      "title": "Incrementing, Decrementing, and Deleting Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityPerformIncrement()/title",
          "value": "accessibilityPerformIncrement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityPerformIncrement()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityPerformIncrement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityPerformDelete()/title",
          "value": "accessibilityPerformDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityPerformDelete()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityPerformDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityPerformDecrement()/title",
          "value": "accessibilityPerformDecrement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityPerformDecrement()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityPerformDecrement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibilityprotocol/accessibilitydecrementbutton()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
