{
  "abstract": [
    {
      "text": "Returns the drag handle elements for the layout item element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHandles()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAccessibility(im)accessibilityHandles",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessibilityHandles"
      },
      {
        "kind": "text",
        "text": "() -> ["
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessibilityHandles()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityHandles"
            },
            {
              "kind": "text",
              "text": "() -> ["
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "]?"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHandles()": {
      "abstract": [
        {
          "text": "Returns the drag handle elements for the layout item element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityHandles"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHandles()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityHandles()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityhandles()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHorizontalUnitDescription()": {
      "abstract": [
        {
          "text": "Returns the description of the layout area’s horizontal units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityHorizontalUnitDescription"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHorizontalUnitDescription()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityHorizontalUnitDescription()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityhorizontalunitdescription()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHorizontalUnits()": {
      "abstract": [
        {
          "text": "Returns the units that the layout area uses for horizontal values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityHorizontalUnits"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSAccessibilityUnits",
          "text": "NSAccessibilityUnits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHorizontalUnits()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityHorizontalUnits()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityhorizontalunits()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutPoint(forScreenPoint:)": {
      "abstract": [
        {
          "text": "Converts the provided point in screen coordinates to a point in the layout area’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLayoutPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forScreenPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutPoint(forScreenPoint:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityLayoutPointForScreenPoint:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityLayoutPoint(forScreenPoint:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitylayoutpoint(forscreenpoint:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutSize(forScreenSize:)": {
      "abstract": [
        {
          "text": "Converts the provided size in screen coordinates to a size in the layout area’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLayoutSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forScreenSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutSize(forScreenSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityLayoutSizeForScreenSize:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityLayoutSize(forScreenSize:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitylayoutsize(forscreensize:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenPoint(forLayoutPoint:)": {
      "abstract": [
        {
          "text": "Converts the provided point in the layout area’s coordinates to a point in the screen’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityScreenPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLayoutPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenPoint(forLayoutPoint:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityScreenPointForLayoutPoint:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityScreenPoint(forLayoutPoint:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityscreenpoint(forlayoutpoint:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenSize(forLayoutSize:)": {
      "abstract": [
        {
          "text": "Converts the provided size in the layout area’s coordinates to a size in the screen’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityScreenSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLayoutSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenSize(forLayoutSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityScreenSizeForLayoutSize:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityScreenSize(forLayoutSize:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityscreensize(forlayoutsize:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVerticalUnitDescription()": {
      "abstract": [
        {
          "text": "Returns the description of the layout area’s vertical units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityVerticalUnitDescription"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVerticalUnitDescription()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityVerticalUnitDescription()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityverticalunitdescription()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVerticalUnits()": {
      "abstract": [
        {
          "text": "Returns the units that the layout area uses for vertical values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityVerticalUnits"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSAccessibilityUnits",
          "text": "NSAccessibilityUnits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVerticalUnits()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityVerticalUnits()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityverticalunits()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHandles(_:)": {
      "abstract": [
        {
          "text": "Sets the drag handle accessibility elements for the layout item element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityHandles"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHandles(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityHandles(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityhandles(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHorizontalUnitDescription(_:)": {
      "abstract": [
        {
          "text": "Sets the description of the layout area’s horizontal units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityHorizontalUnitDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHorizontalUnitDescription(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityHorizontalUnitDescription(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityhorizontalunitdescription(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHorizontalUnits(_:)": {
      "abstract": [
        {
          "text": "Sets the units that the layout area uses for horizontal values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityHorizontalUnits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSAccessibilityUnits",
          "text": "NSAccessibilityUnits"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHorizontalUnits(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityHorizontalUnits(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityhorizontalunits(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityVerticalUnitDescription(_:)": {
      "abstract": [
        {
          "text": "Sets the description of the layout area’s vertical units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityVerticalUnitDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityVerticalUnitDescription(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityVerticalUnitDescription(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityverticalunitdescription(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityVerticalUnits(_:)": {
      "abstract": [
        {
          "text": "Sets the units that the layout area uses for vertical values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityVerticalUnits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSAccessibilityUnits",
          "text": "NSAccessibilityUnits"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityVerticalUnits(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityVerticalUnits(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityverticalunits(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Layout",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHandles(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHorizontalUnits()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHorizontalUnits(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityHorizontalUnitDescription()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityHorizontalUnitDescription(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVerticalUnits()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityVerticalUnits(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVerticalUnitDescription()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityVerticalUnitDescription(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutPoint(forScreenPoint:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityLayoutSize(forScreenSize:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenPoint(forLayoutPoint:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityScreenSize(forLayoutSize:)"
      ],
      "title": "Configuring Layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityScreenSize(forLayoutSize:)/title",
          "value": "accessibilityScreenSizeForLayoutSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityScreenSize(forLayoutSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityScreenSizeForLayoutSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityLayoutSize(forScreenSize:)/title",
          "value": "accessibilityLayoutSizeForScreenSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityLayoutSize(forScreenSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLayoutSizeForScreenSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityScreenPoint(forLayoutPoint:)/title",
          "value": "accessibilityScreenPointForLayoutPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityScreenPoint(forLayoutPoint:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityScreenPointForLayoutPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityLayoutPoint(forScreenPoint:)/title",
          "value": "accessibilityLayoutPointForScreenPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol~1accessibilityLayoutPoint(forScreenPoint:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLayoutPointForScreenPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibilityprotocol/accessibilityhandles()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
