{
  "abstract": [
    {
      "text": "Sets the accessibility element’s parent in the accessibility hierarchy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityParent(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAccessibility(im)setAccessibilityParent:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setAccessibilityParent"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setAccessibilityParent(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setAccessibilityParent"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "accessibilityParent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityChildren()": {
      "abstract": [
        {
          "text": "Returns the child accessibility elements in the accessibility hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityChildren"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityChildren()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityChildren()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitychildren()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityChildrenInNavigationOrder()": {
      "abstract": [
        {
          "text": "Returns the array of child accessibility elements in order for linear navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityChildrenInNavigationOrder"
        },
        {
          "kind": "text",
          "text": "() -> [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSAccessibilityElement",
          "text": "NSAccessibilityElementProtocol"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityChildrenInNavigationOrder()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityChildrenInNavigationOrder()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitychildreninnavigationorder()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityParent()": {
      "abstract": [
        {
          "text": "Returns the accessibility element’s parent in the accessibility hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityParent"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityParent()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityParent()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityparent()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilitySelectedChildren()": {
      "abstract": [
        {
          "text": "Returns the accessibility element’s currently selected children.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySelectedChildren"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilitySelectedChildren()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilitySelectedChildren()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityselectedchildren()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityTopLevelUIElement()": {
      "abstract": [
        {
          "text": "Returns the top-level element that contains the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityTopLevelUIElement"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityTopLevelUIElement()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityTopLevelUIElement()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitytopleveluielement()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVisibleChildren()": {
      "abstract": [
        {
          "text": "Returns the accessibility element’s visible child accessibility elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityVisibleChildren"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVisibleChildren()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityVisibleChildren()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilityvisiblechildren()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityChildren(_:)": {
      "abstract": [
        {
          "text": "Sets the child accessibility elements in the accessibility hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityChildren"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityChildren(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityChildren(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilitychildren(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityChildrenInNavigationOrder(_:)": {
      "abstract": [
        {
          "text": "Sets the array of child accessibility elements in order for linear navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityChildrenInNavigationOrder"
        },
        {
          "kind": "text",
          "text": "([any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSAccessibilityElement",
          "text": "NSAccessibilityElementProtocol"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityChildrenInNavigationOrder(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityChildrenInNavigationOrder(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilitychildreninnavigationorder(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityParent(_:)": {
      "abstract": [
        {
          "text": "Sets the accessibility element’s parent in the accessibility hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityParent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityParent(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityParent(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityparent(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilitySelectedChildren(_:)": {
      "abstract": [
        {
          "text": "Sets the accessibility element’s currently selected children.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilitySelectedChildren"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilitySelectedChildren(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilitySelectedChildren(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityselectedchildren(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityTopLevelUIElement(_:)": {
      "abstract": [
        {
          "text": "Sets the top-level element that contains the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityTopLevelUIElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityTopLevelUIElement(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityTopLevelUIElement(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilitytopleveluielement(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityVisibleChildren(_:)": {
      "abstract": [
        {
          "text": "Sets the accessibility element’s visible child accessibility elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityVisibleChildren"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityVisibleChildren(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityVisibleChildren(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityvisiblechildren(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-Relationships",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityChildren()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityChildren(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityChildrenInNavigationOrder()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityChildrenInNavigationOrder(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityParent()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilitySelectedChildren()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilitySelectedChildren(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityTopLevelUIElement()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityTopLevelUIElement(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityVisibleChildren()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityVisibleChildren(_:)"
      ],
      "title": "Determining Relationships"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibilityprotocol/setaccessibilityparent(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
