{
  "abstract": [
    {
      "text": "Creates a new Apple Pay Later visual merchandising widget view with the shopping cart amount and currency you specify.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Apple Pay Later is deprecated.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPayLaterView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPayLaterView/init(amount:currency:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "PassKit",
    "externalID": "s:So14PKPayLaterViewC7PassKitE6amount8currencyABSo9NSDecimala_10Foundation6LocaleV8CurrencyVtcfc",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "amount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@NSDecimal",
        "text": "Decimal"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "currency"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation6LocaleV",
        "text": "Locale"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation6LocaleV8CurrencyV",
        "text": "Currency"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(amount:currency:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "amount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@NSDecimal",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@NSDecimal",
              "text": "Decimal"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "currency"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation6LocaleV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation6LocaleV",
              "text": "Locale"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation6LocaleV8CurrencyV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation6LocaleV8CurrencyV",
              "text": "Currency"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The customer’s shopping cart or item pricing.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "amount"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "https://www.iso.org/iso-4217-currency-codes.html",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " currency code for the country or region of the merchant’s principle place of business.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "currency"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPayLaterView": {
      "abstract": [
        {
          "text": "A view that displays the Apple Pay Later visual merchandising widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPayLaterView"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPayLaterView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPayLaterView"
        }
      ],
      "role": "symbol",
      "title": "PKPayLaterView",
      "type": "topic",
      "url": "/documentation/passkit/pkpaylaterview"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPayLaterView/init(amount:currency:)": {
      "abstract": [
        {
          "text": "Creates a new Apple Pay Later visual merchandising widget view with the shopping cart amount and currency you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "amount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@NSDecimal",
          "text": "Decimal"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "currency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV8CurrencyV",
          "text": "Currency"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPayLaterView/init(amount:currency:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(amount:currency:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpaylaterview/init(amount:currency:)"
    },
    "doc://com.externally.resolved.symbol/c:@SA@NSDecimal": {
      "abstract": [
        {
          "text": "A structure representing a base-10 number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Decimal"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@NSDecimal",
      "kind": "symbol",
      "role": "symbol",
      "title": "Decimal",
      "type": "topic",
      "url": "/documentation/foundation/decimal"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation6LocaleV": {
      "abstract": [
        {
          "text": "Information about linguistic, cultural, and technological conventions for use in formatting data for presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Locale"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation6LocaleV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Locale",
      "type": "topic",
      "url": "/documentation/foundation/locale"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation6LocaleV8CurrencyV": {
      "abstract": [
        {
          "text": "A type that represents the currency system used by a locale, like dollars or euros.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Locale.Currency"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation6LocaleV8CurrencyV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Locale.Currency",
      "type": "topic",
      "url": "/documentation/foundation/locale/currency"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "https://www.iso.org/iso-4217-currency-codes.html": {
      "identifier": "https://www.iso.org/iso-4217-currency-codes.html",
      "title": "ISO-4217",
      "titleInlineContent": [
        {
          "text": "ISO-4217",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.iso.org/iso-4217-currency-codes.html"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterView/title",
          "value": "PKPayLaterView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPayLaterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPayLaterView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaylaterview/init(amount:currency:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
