{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/coreaudiotypes-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/2962796-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/4278542-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/4278542-anonymous",
      "kind": "article",
      "role": "article",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/4278542-anonymous"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-stream-basic-description-flags": {
      "abstract": [
        {
          "text": "The standard format flags for an audio stream basic description.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-stream-basic-description-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Stream Basic Description Flags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audio-stream-basic-description-flags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/coreaudiotypes-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/coreaudiotypes-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreAudioTypes Enumerations",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/coreaudiotypes-enumerations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-stream-basic-description-flags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/4278542-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/2962796-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/2962796-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
