{
  "abstract": [
    {
      "text": "The standard format flags for an audio stream basic description.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/coreaudiotypes-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-stream-basic-description-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Stream Basic Description Flags"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the fields describe the complete layout of the sample data in the buffers that the description represents, whereas, typically, an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioBufferList",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " represents those buffers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "However, when a description has the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " flag, the audio buffer list has a different structure and semantic. In this case, the description fields describe the format of one of the audio buffers in the list, and each audio buffer in the list has a single (mono) channel of audio data. Then the description’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription/mChannelsPerFrame",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " indicates the total number of audio buffers in the audio buffer list, and each buffer contains one channel. This is primarily for use with the audio unit and audio converter representation of this list, and not the audio hardware usage.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/2962796-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/2962796-anonymous",
      "kind": "article",
      "role": "article",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/2962796-anonymous"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/4278542-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/4278542-anonymous",
      "kind": "article",
      "role": "article",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/4278542-anonymous"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioBuffer": {
      "abstract": [
        {
          "text": "A structure that holds a buffer of audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioBuffer"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioBuffer"
        }
      ],
      "role": "symbol",
      "title": "AudioBuffer",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiobuffer"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioBufferList": {
      "abstract": [
        {
          "text": "A structure that stores a variable-length array of audio buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioBufferList"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioBufferList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioBufferList"
        }
      ],
      "role": "symbol",
      "title": "AudioBufferList",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiobufferlist"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription": {
      "abstract": [
        {
          "text": "A format specification for an audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamBasicDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreambasicdescription"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription/mChannelsPerFrame": {
      "abstract": [
        {
          "text": "The number of channels in each frame of audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mChannelsPerFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription/mChannelsPerFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mChannelsPerFrame"
        }
      ],
      "role": "symbol",
      "title": "mChannelsPerFrame",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreambasicdescription/mchannelsperframe"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/coreaudiotypes-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/coreaudiotypes-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CoreAudioTypes Enumerations",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/coreaudiotypes-enumerations"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 16-bit native endian signed integer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_16BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_16BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_16BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_16bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 20-bit native endian signed integer data aligned high in 24 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_20BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_20BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_20BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_20bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 24-bit native endian signed integer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_24BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_24BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_24BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_24bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 32-bit native endian signed integer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_32BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_32BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_32BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_32bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits is with the high or low bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsAlignedHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsAlignedHigh"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsAlignedHigh",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisalignedhigh"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is big or little endian.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsBigEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsBigEndian"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsBigEndian",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisbigendian"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is floating point or integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsFloat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsFloat",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisfloat"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved": {
      "abstract": [
        {
          "text": "A flag that indicates whether the samples for each channel or frame are continguously located, and whether the layout of the channels or frames is end-to-end.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonInterleaved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonInterleaved"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsNonInterleaved",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisnoninterleaved"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable": {
      "abstract": [
        {
          "text": "A flag that indicates the format is nonmixable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonMixable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonMixable"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsNonMixable",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisnonmixable"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits occupy the entire available bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsPacked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsPacked"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsPacked",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagispacked"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is signed or unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsSignedInteger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsSignedInteger"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsSignedInteger",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagissignedinteger"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear": {
      "abstract": [
        {
          "text": "A flag that indicates whether all the flags are clear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsAreAllClear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsAreAllClear"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagsAreAllClear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagsareallclear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits is with the high or low bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsAlignedHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsAlignedHigh"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsAlignedHigh",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisalignedhigh"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is big or little endian.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsBigEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsBigEndian"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsBigEndian",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisbigendian"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsFloat": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is floating point or integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsFloat"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsFloat",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisfloat"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonInterleaved": {
      "abstract": [
        {
          "text": "A flag that indicates whether the samples for each channel or frame are continguously located, and whether the layout of the channels or frames is end-to-end.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsNonInterleaved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonInterleaved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsNonInterleaved"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsNonInterleaved",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisnoninterleaved"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonMixable": {
      "abstract": [
        {
          "text": "A flag that indicates the format is nonmixable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsNonMixable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonMixable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsNonMixable"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsNonMixable",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisnonmixable"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsPacked": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits occupy the entire available bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsPacked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsPacked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsPacked"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsPacked",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagispacked"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsSignedInteger": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is signed or unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsSignedInteger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsSignedInteger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsSignedInteger"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsSignedInteger",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagissignedinteger"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsAreAllClear": {
      "abstract": [
        {
          "text": "A flag that indicates whether all the flags are clear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsAreAllClear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsAreAllClear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsAreAllClear"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagsAreAllClear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagsareallclear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionMask": {
      "abstract": [
        {
          "text": "A flag that indicates the sample fraction mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsSampleFractionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsSampleFractionMask"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagsSampleFractionMask",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagssamplefractionmask"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionShift": {
      "abstract": [
        {
          "text": "A flag that indicates the bit position of the PCM flag’s 6-bit bitfield.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsSampleFractionShift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionShift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsSampleFractionShift"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagsSampleFractionShift",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagssamplefractionshift"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/2962796-anonymous",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/4278542-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsFloat",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonInterleaved",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonMixable",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsPacked",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsSignedInteger",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsAreAllClear",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionMask",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionShift"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsFloat",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonInterleaved",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonMixable",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsPacked",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsSignedInteger",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsAreAllClear",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionMask",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionShift"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_32BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_32BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_32BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_32BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription~1mChannelsPerFrame/title",
          "value": "mChannelsPerFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription~1mChannelsPerFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mChannelsPerFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsNonInterleaved/title",
          "value": "kLinearPCMFormatFlagIsNonInterleaved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsNonInterleaved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsNonInterleaved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_24BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_24BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_24BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_24BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsSampleFractionMask/title",
          "value": "kLinearPCMFormatFlagsSampleFractionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsSampleFractionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagsSampleFractionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/title",
          "value": "AudioStreamBasicDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamBasicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamBasicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsFloat/title",
          "value": "kAudioFormatFlagIsFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsBigEndian/title",
          "value": "kAudioFormatFlagIsBigEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsBigEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsBigEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsFloat/title",
          "value": "kLinearPCMFormatFlagIsFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsPacked/title",
          "value": "kAudioFormatFlagIsPacked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsPacked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsPacked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsAlignedHigh/title",
          "value": "kLinearPCMFormatFlagIsAlignedHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsAlignedHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsAlignedHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsSignedInteger/title",
          "value": "kLinearPCMFormatFlagIsSignedInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsSignedInteger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsSignedInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonInterleaved/title",
          "value": "kAudioFormatFlagIsNonInterleaved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonInterleaved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsNonInterleaved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonMixable/title",
          "value": "kAudioFormatFlagIsNonMixable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonMixable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsNonMixable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsSignedInteger/title",
          "value": "kAudioFormatFlagIsSignedInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsSignedInteger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsSignedInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsBigEndian/title",
          "value": "kLinearPCMFormatFlagIsBigEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsBigEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsBigEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsSampleFractionShift/title",
          "value": "kLinearPCMFormatFlagsSampleFractionShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsSampleFractionShift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagsSampleFractionShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioBuffer/title",
          "value": "AudioBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsPacked/title",
          "value": "kLinearPCMFormatFlagIsPacked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsPacked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsPacked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_20BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_20BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_20BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_20BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsNonMixable/title",
          "value": "kLinearPCMFormatFlagIsNonMixable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsNonMixable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsNonMixable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsAreAllClear/title",
          "value": "kLinearPCMFormatFlagsAreAllClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsAreAllClear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagsAreAllClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsAreAllClear/title",
          "value": "kAudioFormatFlagsAreAllClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsAreAllClear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagsAreAllClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsAlignedHigh/title",
          "value": "kAudioFormatFlagIsAlignedHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsAlignedHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsAlignedHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioBufferList/title",
          "value": "AudioBufferList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioBufferList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBufferList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioBufferList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioBufferList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_16BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_16BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_16BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_16BitSourceData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audio-stream-basic-description-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audio-stream-basic-description-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
