{
  "abstract": [
    {
      "text": "Identifiers for supported audio formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-identifiers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Format Identifiers"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these identifiers to test for the presence of audio codecs on a system. If a given codec is present, you can use its identifier to specify that codec for data encoding or decoding, according to the capabilities of the codec. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreAudio",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags": {
      "abstract": [
        {
          "text": "A type definition for audio format flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audioformatflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID": {
      "abstract": [
        {
          "text": "A type definition for audio format identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatID"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatID",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audioformatid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription": {
      "abstract": [
        {
          "text": "A format specification for an audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamBasicDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreambasicdescription"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription": {
      "abstract": [
        {
          "text": "A value that describes a packet in a buffer of audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamPacketDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamPacketDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamPacketDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreampacketdescription"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID": {
      "abstract": [
        {
          "text": "Constants that define the type of MPEG-4 audio data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPEG4ObjectID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPEG4ObjectID"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-flags": {
      "abstract": [
        {
          "text": "Commonly used combinations of data format flags for an audio stream description.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Flags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audio-format-flags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormat60958AC3": {
      "abstract": [
        {
          "text": "A key that specifies the AC-3 codec, which provides data packaged for transport over an IEC 60958-compliant digital audio interface, and uses standard flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormat60958AC3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormat60958AC3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormat60958AC3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormat60958AC3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformat60958ac3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAC3": {
      "abstract": [
        {
          "text": "A key that specifies the AC-3 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAC3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAC3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAC3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAC3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatac3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAES3": {
      "abstract": [
        {
          "text": "A key that specifies the codec defined by the AES3-2003 standard, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAES3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAES3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAES3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAES3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformataes3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatALaw": {
      "abstract": [
        {
          "text": "A key that specifies the A-law 2:1 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatALaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatALaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatALaw"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatALaw",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatalaw"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR": {
      "abstract": [
        {
          "text": "A key that specifies the Adaptive Multi-Rate (AMR) narrow band speech codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAMR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAMR"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAMR",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatamr"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR_WB": {
      "abstract": [
        {
          "text": "A key that specifies the AMR Wideband speech codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAMR_WB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR_WB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAMR_WB"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAMR_WB",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatamr_wb"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleIMA4": {
      "abstract": [
        {
          "text": "A key that specifies Apple’s implementation of the IMA 4:1 ADPCM codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAppleIMA4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleIMA4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAppleIMA4"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAppleIMA4",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatappleima4"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleLossless": {
      "abstract": [
        {
          "text": "A key that specifies the Apple Lossless codec, and uses flags to indicate the bit depth of the source material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAppleLossless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleLossless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAppleLossless"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAppleLossless",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatapplelossless"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAudible": {
      "abstract": [
        {
          "text": "A key that specifies the codec for Audible audio books, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAudible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAudible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAudible"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAudible",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformataudible"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatDVIIntelIMA": {
      "abstract": [
        {
          "text": "A key that specifies the codec defined by DVI/Intel IMA ADPCM - ACM code 17, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatDVIIntelIMA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatDVIIntelIMA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatDVIIntelIMA"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatDVIIntelIMA",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatdviintelima"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatEnhancedAC3": {
      "abstract": [
        {
          "text": "A key that specifies the Enhanced AC-3 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatEnhancedAC3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatEnhancedAC3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatEnhancedAC3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatEnhancedAC3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatenhancedac3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFLAC": {
      "abstract": [
        {
          "text": "A key that specifies the Free Lossless Audio Codec (FLAC), and uses flags to indicate the bit depth of the source material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFLAC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFLAC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFLAC"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFLAC",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflac"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatLinearPCM": {
      "abstract": [
        {
          "text": "A key that specifies the linear PCM codec, and uses the standard flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatLinearPCM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatLinearPCM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatLinearPCM"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatLinearPCM",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatlinearpcm"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE3": {
      "abstract": [
        {
          "text": "A key that specifies the MACE 3:1 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMACE3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMACE3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMACE3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmace3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE6": {
      "abstract": [
        {
          "text": "A key that specifies the MACE C:1 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMACE6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMACE6"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMACE6",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmace6"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMIDIStream": {
      "abstract": [
        {
          "text": "A key that specifies the MIDI stream codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMIDIStream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMIDIStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMIDIStream"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMIDIStream",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmidistream"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 AAC Low Complexity codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4AAC",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4aac"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 Enhanced Low Delay AAC codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_ELD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_ELD"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4AAC_ELD",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4aac_eld"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD_SBR": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 Enhanced Low Delay AAC codec with a spectral band replication (SBR) extension layer, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_ELD_SBR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD_SBR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_ELD_SBR"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4AAC_ELD_SBR",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4aac_eld_sbr"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD_V2": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 Enhanced Low Delay AAC version 2 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_ELD_V2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD_V2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_ELD_V2"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4AAC_ELD_V2",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4aac_eld_v2"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_HE": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 High-Efficiency AAC codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_HE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_HE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_HE"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4AAC_HE",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4aac_he"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_HE_V2": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 High-Efficiency AAC version 2 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_HE_V2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_HE_V2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_HE_V2"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4AAC_HE_V2",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4aac_he_v2"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_LD": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 Low Delay AAC codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_LD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_LD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_LD"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4AAC_LD",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4aac_ld"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_Spatial": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 Spatial Audio Coding codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_Spatial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_Spatial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4AAC_Spatial"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4AAC_Spatial",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4aac_spatial"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4CELP": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 CELP codec, and uses flags to indicate the specific kind of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4CELP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4CELP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4CELP"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4CELP",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4celp"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4HVXC": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 HVXC codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4HVXC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4HVXC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4HVXC"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4HVXC",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4hvxc"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4TwinVQ": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 TwinVQ codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4TwinVQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4TwinVQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4TwinVQ"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4TwinVQ",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4twinvq"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGD_USAC": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-D Unified Speech and Audio Coding codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEGD_USAC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGD_USAC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEGD_USAC"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEGD_USAC",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpegd_usac"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer1": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-1/2, Layer I audio codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEGLayer1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEGLayer1"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEGLayer1",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeglayer1"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer2": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-1/2, Layer II audio codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEGLayer2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEGLayer2"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEGLayer2",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeglayer2"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer3": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-1/2, Layer III audio codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEGLayer3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEGLayer3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEGLayer3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeglayer3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMicrosoftGSM": {
      "abstract": [
        {
          "text": "A key that specifies the Microsoft GSM 6.10 - ACM code 49 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMicrosoftGSM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMicrosoftGSM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMicrosoftGSM"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMicrosoftGSM",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmicrosoftgsm"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatOpus": {
      "abstract": [
        {
          "text": "A key that specifies the Opus codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatOpus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatOpus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatOpus"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatOpus",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatopus"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatParameterValueStream": {
      "abstract": [
        {
          "text": "A key that specifies the A side-chain of float 32 data that an audio unit provides for sending high-density parameter value control information, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatParameterValueStream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatParameterValueStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatParameterValueStream"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatParameterValueStream",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatparametervaluestream"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQDesign": {
      "abstract": [
        {
          "text": "A key that specifies the QDesign music codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatQDesign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQDesign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatQDesign"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatQDesign",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatqdesign"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQDesign2": {
      "abstract": [
        {
          "text": "A key that specifies the QDesign 2 music codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatQDesign2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQDesign2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatQDesign2"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatQDesign2",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatqdesign2"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQUALCOMM": {
      "abstract": [
        {
          "text": "A key that specifies the Qualcomm PureVoice codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatQUALCOMM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQUALCOMM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatQUALCOMM"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatQUALCOMM",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatqualcomm"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatTimeCode": {
      "abstract": [
        {
          "text": "A key that specifies the A stream of audio timestamp structures, and uses audio timestamp flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatTimeCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatTimeCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatTimeCode"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatTimeCode",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformattimecode"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatULaw": {
      "abstract": [
        {
          "text": "A key that specifies the μ-Law 2:1 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatULaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatULaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatULaw"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatULaw",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatulaw"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatiLBC": {
      "abstract": [
        {
          "text": "A key that specifies the internet Low Bitrate Codec (iLBC) narrow band speech codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatiLBC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatiLBC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatiLBC"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatiLBC",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatilbc"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioStreamAnyRate": {
      "abstract": [
        {
          "text": "A value that indicates that an audio stream can use any sample rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamAnyRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioStreamAnyRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamAnyRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamAnyRate",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiostreamanyrate"
    },
    "doc://com.apple.documentation/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/CoreAudio"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Streams",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-flags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioStreamAnyRate",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID"
      ],
      "title": "Streams"
    }
  ],
  "topicSections": [
    {
      "anchor": "Format-identifiers",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormat60958AC3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAC3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAES3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatALaw",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR_WB",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleIMA4",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleLossless",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAudible",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatDVIIntelIMA",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatEnhancedAC3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFLAC",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatLinearPCM",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE6",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMIDIStream",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD_SBR",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD_V2",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_HE",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_HE_V2",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_LD",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_Spatial",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4CELP",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4HVXC",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4TwinVQ",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGD_USAC",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer1",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer2",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMicrosoftGSM",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatOpus",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatParameterValueStream",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQDesign",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQDesign2",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQUALCOMM",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatTimeCode",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatULaw",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatiLBC"
      ],
      "title": "Format identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Format-identifiers",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormat60958AC3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAC3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAES3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatALaw",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR_WB",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleIMA4",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleLossless",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAudible",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatDVIIntelIMA",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatEnhancedAC3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFLAC",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatLinearPCM",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE6",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMIDIStream",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD_SBR",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_ELD_V2",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_HE",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_HE_V2",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_LD",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4AAC_Spatial",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4CELP",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4HVXC",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4TwinVQ",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGD_USAC",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer1",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer2",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEGLayer3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMicrosoftGSM",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatOpus",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatParameterValueStream",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQDesign",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQDesign2",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatQUALCOMM",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatTimeCode",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatULaw",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatiLBC"
              ],
              "title": "Format identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEGLayer1/title",
          "value": "kAudioFormatMPEGLayer1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEGLayer1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEGLayer1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAudible/title",
          "value": "kAudioFormatAudible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAudible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAudible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/title",
          "value": "AudioFormatFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEGLayer2/title",
          "value": "kAudioFormatMPEGLayer2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEGLayer2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEGLayer2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_Spatial/title",
          "value": "kAudioFormatMPEG4AAC_Spatial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_Spatial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4AAC_Spatial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_HE/title",
          "value": "kAudioFormatMPEG4AAC_HE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_HE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4AAC_HE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatALaw/title",
          "value": "kAudioFormatALaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatALaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatALaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatTimeCode/title",
          "value": "kAudioFormatTimeCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatTimeCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatTimeCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_ELD_V2/title",
          "value": "kAudioFormatMPEG4AAC_ELD_V2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_ELD_V2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4AAC_ELD_V2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEGLayer3/title",
          "value": "kAudioFormatMPEGLayer3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEGLayer3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEGLayer3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFLAC/title",
          "value": "kAudioFormatFLAC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFLAC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFLAC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAC3/title",
          "value": "kAudioFormatAC3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAC3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAC3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4CELP/title",
          "value": "kAudioFormatMPEG4CELP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4CELP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4CELP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_ELD/title",
          "value": "kAudioFormatMPEG4AAC_ELD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_ELD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4AAC_ELD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAMR/title",
          "value": "kAudioFormatAMR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAMR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAMR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAppleLossless/title",
          "value": "kAudioFormatAppleLossless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAppleLossless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAppleLossless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/title",
          "value": "MPEG4ObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC/title",
          "value": "kAudioFormatMPEG4AAC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4AAC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_ELD_SBR/title",
          "value": "kAudioFormatMPEG4AAC_ELD_SBR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_ELD_SBR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4AAC_ELD_SBR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatQDesign2/title",
          "value": "kAudioFormatQDesign2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatQDesign2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatQDesign2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMACE3/title",
          "value": "kAudioFormatMACE3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMACE3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMACE3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatULaw/title",
          "value": "kAudioFormatULaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatULaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatULaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioStreamAnyRate/title",
          "value": "kAudioStreamAnyRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioStreamAnyRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamAnyRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAMR_WB/title",
          "value": "kAudioFormatAMR_WB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAMR_WB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAMR_WB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/title",
          "value": "AudioFormatID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatQDesign/title",
          "value": "kAudioFormatQDesign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatQDesign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatQDesign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/title",
          "value": "AudioStreamBasicDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamBasicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamBasicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormat60958AC3/title",
          "value": "kAudioFormat60958AC3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormat60958AC3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormat60958AC3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatLinearPCM/title",
          "value": "kAudioFormatLinearPCM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatLinearPCM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatLinearPCM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatOpus/title",
          "value": "kAudioFormatOpus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatOpus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatOpus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatDVIIntelIMA/title",
          "value": "kAudioFormatDVIIntelIMA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatDVIIntelIMA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatDVIIntelIMA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_HE_V2/title",
          "value": "kAudioFormatMPEG4AAC_HE_V2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_HE_V2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4AAC_HE_V2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAES3/title",
          "value": "kAudioFormatAES3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAES3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAES3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAppleIMA4/title",
          "value": "kAudioFormatAppleIMA4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAppleIMA4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAppleIMA4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatEnhancedAC3/title",
          "value": "kAudioFormatEnhancedAC3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatEnhancedAC3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatEnhancedAC3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatiLBC/title",
          "value": "kAudioFormatiLBC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatiLBC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatiLBC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_LD/title",
          "value": "kAudioFormatMPEG4AAC_LD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4AAC_LD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4AAC_LD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEGD_USAC/title",
          "value": "kAudioFormatMPEGD_USAC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEGD_USAC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEGD_USAC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4TwinVQ/title",
          "value": "kAudioFormatMPEG4TwinVQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4TwinVQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4TwinVQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMIDIStream/title",
          "value": "kAudioFormatMIDIStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMIDIStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMIDIStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4HVXC/title",
          "value": "kAudioFormatMPEG4HVXC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4HVXC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4HVXC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatQUALCOMM/title",
          "value": "kAudioFormatQUALCOMM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatQUALCOMM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatQUALCOMM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMACE6/title",
          "value": "kAudioFormatMACE6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMACE6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMACE6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMicrosoftGSM/title",
          "value": "kAudioFormatMicrosoftGSM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMicrosoftGSM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMicrosoftGSM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/title",
          "value": "AudioStreamPacketDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamPacketDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamPacketDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatParameterValueStream/title",
          "value": "kAudioFormatParameterValueStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatParameterValueStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatParameterValueStream"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audio-format-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audio-format-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
