{
  "abstract": [
    {
      "text": "The supported channel bitmaps to use when defining channel layouts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioChannelBitmap",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioChannelBitmap"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioChannelBitmap"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.11",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AudioChannelBitmap"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioChannelBitmap"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap": {
      "abstract": [
        {
          "text": "The supported channel bitmaps to use when defining channel layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelBitmap"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelBitmap",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Center": {
      "abstract": [
        {
          "text": "The center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_Center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_Center"
        }
      ],
      "role": "symbol",
      "title": "bit_Center",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_center"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterSurround": {
      "abstract": [
        {
          "text": "The center surround channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_CenterSurround"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterSurround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_CenterSurround"
        }
      ],
      "role": "symbol",
      "title": "bit_CenterSurround",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_centersurround"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopFront": {
      "abstract": [
        {
          "text": "The top-front center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_CenterTopFront"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopFront",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_CenterTopFront"
        }
      ],
      "role": "symbol",
      "title": "bit_CenterTopFront",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_centertopfront"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopMiddle": {
      "abstract": [
        {
          "text": "The top-middle center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_CenterTopMiddle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopMiddle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_CenterTopMiddle"
        }
      ],
      "role": "symbol",
      "title": "bit_CenterTopMiddle",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_centertopmiddle"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopRear": {
      "abstract": [
        {
          "text": "The top-right center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_CenterTopRear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopRear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_CenterTopRear"
        }
      ],
      "role": "symbol",
      "title": "bit_CenterTopRear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_centertoprear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LFEScreen": {
      "abstract": [
        {
          "text": "The Low Frequency Effects (LFE) screen channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_LFEScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LFEScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_LFEScreen"
        }
      ],
      "role": "symbol",
      "title": "bit_LFEScreen",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_lfescreen"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Left": {
      "abstract": [
        {
          "text": "The left channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_Left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_Left"
        }
      ],
      "role": "symbol",
      "title": "bit_Left",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_left"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftCenter": {
      "abstract": [
        {
          "text": "The left center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_LeftCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_LeftCenter"
        }
      ],
      "role": "symbol",
      "title": "bit_LeftCenter",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_leftcenter"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftSurround": {
      "abstract": [
        {
          "text": "The left surround channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_LeftSurround"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftSurround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_LeftSurround"
        }
      ],
      "role": "symbol",
      "title": "bit_LeftSurround",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_leftsurround"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftSurroundDirect": {
      "abstract": [
        {
          "text": "The left surround direct channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_LeftSurroundDirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftSurroundDirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_LeftSurroundDirect"
        }
      ],
      "role": "symbol",
      "title": "bit_LeftSurroundDirect",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_leftsurrounddirect"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopFront": {
      "abstract": [
        {
          "text": "The left-top front channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_LeftTopFront"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopFront",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_LeftTopFront"
        }
      ],
      "role": "symbol",
      "title": "bit_LeftTopFront",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_lefttopfront"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopMiddle": {
      "abstract": [
        {
          "text": "The left-top middle channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_LeftTopMiddle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopMiddle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_LeftTopMiddle"
        }
      ],
      "role": "symbol",
      "title": "bit_LeftTopMiddle",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_lefttopmiddle"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopRear": {
      "abstract": [
        {
          "text": "The left-top rear channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_LeftTopRear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopRear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_LeftTopRear"
        }
      ],
      "role": "symbol",
      "title": "bit_LeftTopRear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_lefttoprear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Right": {
      "abstract": [
        {
          "text": "The right channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_Right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_Right"
        }
      ],
      "role": "symbol",
      "title": "bit_Right",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_right"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightCenter": {
      "abstract": [
        {
          "text": "The right center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightCenter"
        }
      ],
      "role": "symbol",
      "title": "bit_RightCenter",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_rightcenter"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurround": {
      "abstract": [
        {
          "text": "The rIght surround channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightSurround"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightSurround"
        }
      ],
      "role": "symbol",
      "title": "bit_RightSurround",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_rightsurround"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurroundDirect": {
      "abstract": [
        {
          "text": "The right surround direct channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightSurroundDirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurroundDirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightSurroundDirect"
        }
      ],
      "role": "symbol",
      "title": "bit_RightSurroundDirect",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_rightsurrounddirect"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopFront": {
      "abstract": [
        {
          "text": "The top-front front channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightTopFront"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopFront",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightTopFront"
        }
      ],
      "role": "symbol",
      "title": "bit_RightTopFront",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_righttopfront"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopMiddle": {
      "abstract": [
        {
          "text": "The top-middle right channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightTopMiddle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopMiddle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightTopMiddle"
        }
      ],
      "role": "symbol",
      "title": "bit_RightTopMiddle",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_righttopmiddle"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopRear": {
      "abstract": [
        {
          "text": "The top-rear right channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightTopRear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopRear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightTopRear"
        }
      ],
      "role": "symbol",
      "title": "bit_RightTopRear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_righttoprear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackCenter": {
      "abstract": [
        {
          "text": "The top-back center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_TopBackCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_TopBackCenter"
        }
      ],
      "role": "symbol",
      "title": "bit_TopBackCenter",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_topbackcenter"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackLeft": {
      "abstract": [
        {
          "text": "The top-back left channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_TopBackLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_TopBackLeft"
        }
      ],
      "role": "symbol",
      "title": "bit_TopBackLeft",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_topbackleft"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackRight": {
      "abstract": [
        {
          "text": "The top-back right channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_TopBackRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_TopBackRight"
        }
      ],
      "role": "symbol",
      "title": "bit_TopBackRight",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_topbackright"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopCenterSurround": {
      "abstract": [
        {
          "text": "The top center surround channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_TopCenterSurround"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopCenterSurround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_TopCenterSurround"
        }
      ],
      "role": "symbol",
      "title": "bit_TopCenterSurround",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_topcentersurround"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightCenter": {
      "abstract": [
        {
          "text": "The vertical height center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_VerticalHeightCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_VerticalHeightCenter"
        }
      ],
      "role": "symbol",
      "title": "bit_VerticalHeightCenter",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_verticalheightcenter"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightLeft": {
      "abstract": [
        {
          "text": "The vertical height left channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_VerticalHeightLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_VerticalHeightLeft"
        }
      ],
      "role": "symbol",
      "title": "bit_VerticalHeightLeft",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_verticalheightleft"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightRight": {
      "abstract": [
        {
          "text": "The vertical height right channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_VerticalHeightRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_VerticalHeightRight"
        }
      ],
      "role": "symbol",
      "title": "bit_VerticalHeightRight",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_verticalheightright"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates an audio channel bitmap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/init(rawvalue:)"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelBitmap": {
      "abstract": [
        {
          "text": "If ",
          "type": "text"
        },
        {
          "code": "mChannelLayoutTag",
          "type": "codeVoice"
        },
        {
          "text": " is set to ",
          "type": "text"
        },
        {
          "code": "kAudioChannelLayoutTag_UseChannelBitmap",
          "type": "codeVoice"
        },
        {
          "text": ", this field is the channel-use bitmap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mChannelBitmap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelBitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mChannelBitmap"
        }
      ],
      "role": "symbol",
      "title": "mChannelBitmap",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellayout/mchannelbitmap"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelDescriptions": {
      "abstract": [
        {
          "text": "A variable length array of ",
          "type": "text"
        },
        {
          "code": "mNumberChannelDescription",
          "type": "codeVoice"
        },
        {
          "text": " elements that describes a layout. If the ",
          "type": "text"
        },
        {
          "code": "mChannelLayoutTag",
          "type": "codeVoice"
        },
        {
          "text": " field is set to ",
          "type": "text"
        },
        {
          "code": "kAudioChannelLayoutTag_UseChannelDescriptions",
          "type": "codeVoice"
        },
        {
          "text": ", use this field to describe the layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mChannelDescriptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioChannelDescription",
          "text": "AudioChannelDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelDescriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mChannelDescriptions"
        }
      ],
      "role": "symbol",
      "title": "mChannelDescriptions",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellayout/mchanneldescriptions"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelLayoutTag": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "AudioChannelLayoutTag",
          "type": "codeVoice"
        },
        {
          "text": " value that indicates the layout. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-layout-tags",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mChannelLayoutTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelLayoutTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mChannelLayoutTag"
        }
      ],
      "role": "symbol",
      "title": "mChannelLayoutTag",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellayout/mchannellayouttag"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mNumberChannelDescriptions": {
      "abstract": [
        {
          "text": "The number of items in the ",
          "type": "text"
        },
        {
          "code": "mChannelDescriptions",
          "type": "codeVoice"
        },
        {
          "text": " array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mNumberChannelDescriptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mNumberChannelDescriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mNumberChannelDescriptions"
        }
      ],
      "role": "symbol",
      "title": "mNumberChannelDescriptions",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellayout/mnumberchanneldescriptions"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag": {
      "abstract": [
        {
          "text": "Identifies a previously-defined channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelLayoutTag",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellayouttag"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag_GetNumberOfChannels(_:)": {
      "abstract": [
        {
          "text": "Retrieves the number of channels from an audio channel layout tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag_GetNumberOfChannels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag_GetNumberOfChannels(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag_GetNumberOfChannels"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelLayoutTag_GetNumberOfChannels(_:)",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellayouttag_getnumberofchannels(_:)"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-layout-tags": {
      "abstract": [
        {
          "text": "The identifiers that represent audio channel layouts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-layout-tags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Channel Layout Tags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audio-channel-layout-tags"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelBitmap",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelDescriptions",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelLayoutTag",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-layout-tags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mNumberChannelDescriptions",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag_GetNumberOfChannels(_:)"
      ],
      "title": "Accessing the Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Left",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Left",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftCenter",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftSurround",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftSurroundDirect",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopFront",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopMiddle",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopRear",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackLeft",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightLeft"
      ],
      "title": "Left"
    },
    {
      "anchor": "Center",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Center",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterSurround",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopFront",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopMiddle",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopRear",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackCenter",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopCenterSurround",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightCenter"
      ],
      "title": "Center"
    },
    {
      "anchor": "Right",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Right",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightCenter",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurround",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurroundDirect",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopFront",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopMiddle",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopRear",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackRight",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightRight"
      ],
      "title": "Right"
    },
    {
      "anchor": "Low-Frequency-Effects",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LFEScreen"
      ],
      "title": "Low-Frequency Effects"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioChannelBitmap"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Left",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Left",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftCenter",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftSurround",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftSurroundDirect",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopFront",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopMiddle",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LeftTopRear",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackLeft",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightLeft"
              ],
              "title": "Left"
            },
            {
              "anchor": "Center",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Center",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterSurround",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopFront",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopMiddle",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopRear",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackCenter",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopCenterSurround",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightCenter"
              ],
              "title": "Center"
            },
            {
              "anchor": "Right",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Right",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightCenter",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurround",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurroundDirect",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopFront",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopMiddle",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopRear",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackRight",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightRight"
              ],
              "title": "Right"
            },
            {
              "anchor": "Low-Frequency-Effects",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_LFEScreen"
              ],
              "title": "Low-Frequency Effects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelBitmap",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelDescriptions",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mChannelLayoutTag",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayout/mNumberChannelDescriptions",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag_GetNumberOfChannels(_:)"
              ],
              "title": "Accessing the Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioChannelBitmap"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopBackCenter/title",
          "value": "kAudioChannelBit_TopBackCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopBackCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_TopBackCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopFront/title",
          "value": "kAudioChannelBit_CenterTopFront"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopFront/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_CenterTopFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftSurroundDirect/title",
          "value": "kAudioChannelBit_LeftSurroundDirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftSurroundDirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_LeftSurroundDirect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightCenter/title",
          "value": "kAudioChannelBit_RightCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/title",
          "value": "AudioChannelLayoutTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopMiddle/title",
          "value": "kAudioChannelBit_CenterTopMiddle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopMiddle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_CenterTopMiddle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_Left/title",
          "value": "kAudioChannelBit_Left"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_Left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_Left"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopBackLeft/title",
          "value": "kAudioChannelBit_TopBackLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopBackLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_TopBackLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_Center/title",
          "value": "kAudioChannelBit_Center"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_Center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_Center"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag_GetNumberOfChannels(_:)/title",
          "value": "AudioChannelLayoutTag_GetNumberOfChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag_GetNumberOfChannels(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag_GetNumberOfChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightSurroundDirect/title",
          "value": "kAudioChannelBit_RightSurroundDirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightSurroundDirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightSurroundDirect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopBackRight/title",
          "value": "kAudioChannelBit_TopBackRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopBackRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_TopBackRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterSurround/title",
          "value": "kAudioChannelBit_CenterSurround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterSurround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_CenterSurround"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopFront/title",
          "value": "kAudioChannelBit_RightTopFront"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopFront/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightTopFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap/title",
          "value": "AudioChannelBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_VerticalHeightRight/title",
          "value": "kAudioChannelBit_VerticalHeightRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_VerticalHeightRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_VerticalHeightRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayout~1mNumberChannelDescriptions/title",
          "value": "mNumberChannelDescriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayout~1mNumberChannelDescriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mNumberChannelDescriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftSurround/title",
          "value": "kAudioChannelBit_LeftSurround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftSurround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_LeftSurround"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_VerticalHeightLeft/title",
          "value": "kAudioChannelBit_VerticalHeightLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_VerticalHeightLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_VerticalHeightLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LFEScreen/title",
          "value": "kAudioChannelBit_LFEScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LFEScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_LFEScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftTopFront/title",
          "value": "kAudioChannelBit_LeftTopFront"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftTopFront/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_LeftTopFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayout~1mChannelLayoutTag/title",
          "value": "mChannelLayoutTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayout~1mChannelLayoutTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayout~1mChannelDescriptions/title",
          "value": "mChannelDescriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayout~1mChannelDescriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mChannelDescriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftTopMiddle/title",
          "value": "kAudioChannelBit_LeftTopMiddle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftTopMiddle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_LeftTopMiddle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftCenter/title",
          "value": "kAudioChannelBit_LeftCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_LeftCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_VerticalHeightCenter/title",
          "value": "kAudioChannelBit_VerticalHeightCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_VerticalHeightCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_VerticalHeightCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopMiddle/title",
          "value": "kAudioChannelBit_RightTopMiddle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopMiddle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightTopMiddle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftTopRear/title",
          "value": "kAudioChannelBit_LeftTopRear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_LeftTopRear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_LeftTopRear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayout~1mChannelBitmap/title",
          "value": "mChannelBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayout~1mChannelBitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mChannelBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopRear/title",
          "value": "kAudioChannelBit_CenterTopRear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopRear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_CenterTopRear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopRear/title",
          "value": "kAudioChannelBit_RightTopRear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopRear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightTopRear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_Right/title",
          "value": "kAudioChannelBit_Right"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_Right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_Right"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightSurround/title",
          "value": "kAudioChannelBit_RightSurround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightSurround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightSurround"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopCenterSurround/title",
          "value": "kAudioChannelBit_TopCenterSurround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopCenterSurround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_TopCenterSurround"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochannelbitmap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochannelbitmap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
