{
  "abstract": [
    {
      "text": "Commonly used combinations of data format flags for an audio stream description.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Format Flags"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Prefer using fixed-point formats in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PackageDescription/Platform/iOS",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and floating-point formats in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/PackageDescription/Platform/macOS",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags": {
      "abstract": [
        {
          "text": "A type definition for audio format flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audioformatflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID": {
      "abstract": [
        {
          "text": "A type definition for audio format identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatID"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatID",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audioformatid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription": {
      "abstract": [
        {
          "text": "A format specification for an audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamBasicDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreambasicdescription"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription": {
      "abstract": [
        {
          "text": "A value that describes a packet in a buffer of audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamPacketDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamPacketDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamPacketDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreampacketdescription"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID": {
      "abstract": [
        {
          "text": "Constants that define the type of MPEG-4 audio data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPEG4ObjectID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPEG4ObjectID"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for supported audio formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Identifiers",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audio-format-identifiers"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 16-bit native endian signed integer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_16BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_16BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_16BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_16bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 20-bit native endian signed integer data aligned high in 24 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_20BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_20BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_20BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_20bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 24-bit native endian signed integer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_24BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_24BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_24BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_24bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 32-bit native endian signed integer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_32BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_32BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_32BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_32bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits is with the high or low bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsAlignedHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsAlignedHigh"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsAlignedHigh",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisalignedhigh"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is big or little endian.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsBigEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsBigEndian"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsBigEndian",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisbigendian"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is floating point or integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsFloat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsFloat",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisfloat"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved": {
      "abstract": [
        {
          "text": "A flag that indicates whether the samples for each channel or frame are continguously located, and whether the layout of the channels or frames is end-to-end.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonInterleaved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonInterleaved"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsNonInterleaved",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisnoninterleaved"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable": {
      "abstract": [
        {
          "text": "A flag that indicates the format is nonmixable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonMixable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonMixable"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsNonMixable",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisnonmixable"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits occupy the entire available bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsPacked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsPacked"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsPacked",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagispacked"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is signed or unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsSignedInteger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsSignedInteger"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsSignedInteger",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagissignedinteger"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear": {
      "abstract": [
        {
          "text": "A flag that indicates whether all the flags are clear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsAreAllClear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsAreAllClear"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagsAreAllClear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagsareallclear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAudioUnitCanonical": {
      "abstract": [
        {
          "text": "The flags for the canonical audio unit and processing sample type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsAudioUnitCanonical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAudioUnitCanonical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsAudioUnitCanonical"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagsAudioUnitCanonical",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagsaudiounitcanonical"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsCanonical": {
      "abstract": [
        {
          "text": "The set of flags for the canonical input-output audio sample type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsCanonical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsCanonical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsCanonical"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagsCanonical",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagscanonical"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeEndian": {
      "abstract": [
        {
          "text": "A flag that specifies whether the format is big endian, depending on the endianness of the processor at build time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsNativeEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsNativeEndian"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagsNativeEndian",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagsnativeendian"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeFloatPacked": {
      "abstract": [
        {
          "text": "The flags for the canonical format of fully packed, native endian floating-point data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsNativeFloatPacked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeFloatPacked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsNativeFloatPacked"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagsNativeFloatPacked",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagsnativefloatpacked"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioStreamAnyRate": {
      "abstract": [
        {
          "text": "A value that indicates that an audio stream can use any sample rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamAnyRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioStreamAnyRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamAnyRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamAnyRate",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiostreamanyrate"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits is with the high or low bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsAlignedHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsAlignedHigh"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsAlignedHigh",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisalignedhigh"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is big or little endian.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsBigEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsBigEndian"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsBigEndian",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisbigendian"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsFloat": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is floating point or integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsFloat"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsFloat",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisfloat"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonInterleaved": {
      "abstract": [
        {
          "text": "A flag that indicates whether the samples for each channel or frame are continguously located, and whether the layout of the channels or frames is end-to-end.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsNonInterleaved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonInterleaved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsNonInterleaved"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsNonInterleaved",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisnoninterleaved"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonMixable": {
      "abstract": [
        {
          "text": "A flag that indicates the format is nonmixable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsNonMixable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonMixable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsNonMixable"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsNonMixable",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisnonmixable"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsPacked": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits occupy the entire available bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsPacked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsPacked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsPacked"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsPacked",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagispacked"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsSignedInteger": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is signed or unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsSignedInteger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsSignedInteger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsSignedInteger"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsSignedInteger",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagissignedinteger"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsAreAllClear": {
      "abstract": [
        {
          "text": "A flag that indicates whether all the flags are clear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsAreAllClear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsAreAllClear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsAreAllClear"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagsAreAllClear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagsareallclear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionMask": {
      "abstract": [
        {
          "text": "A flag that indicates the sample fraction mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsSampleFractionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsSampleFractionMask"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagsSampleFractionMask",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagssamplefractionmask"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionShift": {
      "abstract": [
        {
          "text": "A flag that indicates the bit position of the PCM flag’s 6-bit bitfield.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsSampleFractionShift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionShift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagsSampleFractionShift"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagsSampleFractionShift",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagssamplefractionshift"
    },
    "doc://com.apple.documentation/documentation/PackageDescription/Platform/iOS": {
      "abstract": [
        {
          "text": "The iOS platform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:18PackageDescription8PlatformV",
          "text": "Platform"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PackageDescription/Platform/iOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "iOS",
      "type": "topic",
      "url": "/documentation/PackageDescription/Platform/iOS"
    },
    "doc://com.apple.documentation/documentation/PackageDescription/Platform/macOS": {
      "abstract": [
        {
          "text": "The macOS platform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:18PackageDescription8PlatformV",
          "text": "Platform"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PackageDescription/Platform/macOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "macOS",
      "type": "topic",
      "url": "/documentation/PackageDescription/Platform/macOS"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Streams",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-identifiers",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioStreamAnyRate",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID"
      ],
      "title": "Streams"
    }
  ],
  "topicSections": [
    {
      "anchor": "Format-flags",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeEndian",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeFloatPacked",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsFloat",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonInterleaved",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonMixable",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsPacked",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsSignedInteger",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsAreAllClear",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionMask",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionShift",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAudioUnitCanonical",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsCanonical"
      ],
      "title": "Format flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Format-flags",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeEndian",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeFloatPacked",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsFloat",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonInterleaved",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsNonMixable",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsPacked",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsSignedInteger",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsAreAllClear",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionMask",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagsSampleFractionShift",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAudioUnitCanonical",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsCanonical"
              ],
              "title": "Format flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/title",
          "value": "AudioStreamBasicDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamBasicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamBasicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_16BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_16BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_16BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_16BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/title",
          "value": "AudioStreamPacketDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamPacketDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamPacketDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/title",
          "value": "AudioFormatFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonInterleaved/title",
          "value": "kAudioFormatFlagIsNonInterleaved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonInterleaved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsNonInterleaved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsNonInterleaved/title",
          "value": "kLinearPCMFormatFlagIsNonInterleaved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsNonInterleaved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsNonInterleaved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsSignedInteger/title",
          "value": "kAudioFormatFlagIsSignedInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsSignedInteger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsSignedInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsSignedInteger/title",
          "value": "kLinearPCMFormatFlagIsSignedInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsSignedInteger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsSignedInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/title",
          "value": "AudioFormatID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsNonMixable/title",
          "value": "kLinearPCMFormatFlagIsNonMixable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsNonMixable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsNonMixable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonMixable/title",
          "value": "kAudioFormatFlagIsNonMixable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonMixable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsNonMixable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsAreAllClear/title",
          "value": "kAudioFormatFlagsAreAllClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsAreAllClear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagsAreAllClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsBigEndian/title",
          "value": "kLinearPCMFormatFlagIsBigEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsBigEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsBigEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsAudioUnitCanonical/title",
          "value": "kAudioFormatFlagsAudioUnitCanonical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsAudioUnitCanonical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagsAudioUnitCanonical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_24BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_24BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_24BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_24BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_20BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_20BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_20BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_20BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/title",
          "value": "MPEG4ObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_32BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_32BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_32BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_32BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsSampleFractionShift/title",
          "value": "kLinearPCMFormatFlagsSampleFractionShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsSampleFractionShift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagsSampleFractionShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsFloat/title",
          "value": "kLinearPCMFormatFlagIsFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsCanonical/title",
          "value": "kAudioFormatFlagsCanonical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsCanonical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagsCanonical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsNativeFloatPacked/title",
          "value": "kAudioFormatFlagsNativeFloatPacked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsNativeFloatPacked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagsNativeFloatPacked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsSampleFractionMask/title",
          "value": "kLinearPCMFormatFlagsSampleFractionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsSampleFractionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagsSampleFractionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsPacked/title",
          "value": "kLinearPCMFormatFlagIsPacked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsPacked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsPacked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsNativeEndian/title",
          "value": "kAudioFormatFlagsNativeEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsNativeEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagsNativeEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioStreamAnyRate/title",
          "value": "kAudioStreamAnyRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioStreamAnyRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamAnyRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsAlignedHigh/title",
          "value": "kLinearPCMFormatFlagIsAlignedHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsAlignedHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsAlignedHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsBigEndian/title",
          "value": "kAudioFormatFlagIsBigEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsBigEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsBigEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsFloat/title",
          "value": "kAudioFormatFlagIsFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsAreAllClear/title",
          "value": "kLinearPCMFormatFlagsAreAllClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagsAreAllClear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagsAreAllClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsAlignedHigh/title",
          "value": "kAudioFormatFlagIsAlignedHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsAlignedHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsAlignedHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsPacked/title",
          "value": "kAudioFormatFlagIsPacked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsPacked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsPacked"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audio-format-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audio-format-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
