{
  "abstract": [
    {
      "text": "Used in the ",
      "type": "text"
    },
    {
      "code": "mChannelFlags",
      "type": "codeVoice"
    },
    {
      "text": " field of an ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " structure.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-coordinates"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio Channel Coordinates"
  },
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex": {
      "abstract": [
        {
          "text": "Indexes the fields of the ",
          "type": "text"
        },
        {
          "code": "mCoordinates",
          "type": "codeVoice"
        },
        {
          "text": " array in an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelCoordinateIndex"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelCoordinateIndex"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelCoordinateIndex",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Azimuth": {
      "abstract": [
        {
          "text": "For spherical coordinates, ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " is front center, positive is right, negative is left, and measurements are in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinates_Azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelCoordinateIndex",
          "text": "AudioChannelCoordinateIndex"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Azimuth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelCoordinates_Azimuth"
        }
      ],
      "role": "symbol",
      "title": "coordinates_Azimuth",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_azimuth"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Distance": {
      "abstract": [
        {
          "text": "For spherical coordinates, distance is radially from the center. The units are specified by the ",
          "type": "text"
        },
        {
          "code": "mChannelFlags",
          "type": "codeVoice"
        },
        {
          "text": " field of the ",
          "type": "text"
        },
        {
          "code": "AudioChannelDescription",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinates_Distance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelCoordinateIndex",
          "text": "AudioChannelCoordinateIndex"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Distance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelCoordinates_Distance"
        }
      ],
      "role": "symbol",
      "title": "coordinates_Distance",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_distance"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Elevation": {
      "abstract": [
        {
          "text": "For spherical coordinates, ",
          "type": "text"
        },
        {
          "code": "+90",
          "type": "codeVoice"
        },
        {
          "text": " is zenith, ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " is horizontal, ",
          "type": "text"
        },
        {
          "code": "-90",
          "type": "codeVoice"
        },
        {
          "text": " is nadir, and measurements are in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinates_Elevation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelCoordinateIndex",
          "text": "AudioChannelCoordinateIndex"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Elevation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelCoordinates_Elevation"
        }
      ],
      "role": "symbol",
      "title": "coordinates_Elevation",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelcoordinateindex/coordinates_elevation"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription": {
      "abstract": [
        {
          "text": "A structure that describes a channel of audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochanneldescription"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelFlags": {
      "abstract": [
        {
          "text": "The audio channel flags that indicate how to interpret the channel coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mChannelFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelFlags",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mChannelFlags"
        }
      ],
      "role": "symbol",
      "title": "mChannelFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochanneldescription/mchannelflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelLabel": {
      "abstract": [
        {
          "text": "A label that describes the audio channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mChannelLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mChannelLabel"
        }
      ],
      "role": "symbol",
      "title": "mChannelLabel",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochanneldescription/mchannellabel"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mCoordinates": {
      "abstract": [
        {
          "text": "The coordinates that specify a precise speaker location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mCoordinates"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mCoordinates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mCoordinates"
        }
      ],
      "role": "symbol",
      "title": "mCoordinates",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochanneldescription/mcoordinates"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags": {
      "abstract": [
        {
          "text": "Constants that define the audio channel flags of an audio channel description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/kAudioChannelFlags_AllOff": {
      "abstract": [
        {
          "text": "All flags are clear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioChannelFlags_AllOff"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/kAudioChannelFlags_AllOff",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioChannelFlags_AllOff",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags/kaudiochannelflags_alloff"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/meters": {
      "abstract": [
        {
          "text": "A flag that indicates that unit values are in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelFlags",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/meters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelFlags_Meters"
        }
      ],
      "role": "symbol",
      "title": "meters",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags/meters"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/rectangularCoordinates": {
      "abstract": [
        {
          "text": "A flag that indicates the channel uses the speaker position’s cartesian coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectangularCoordinates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelFlags",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/rectangularCoordinates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelFlags_RectangularCoordinates"
        }
      ],
      "role": "symbol",
      "title": "rectangularCoordinates",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags/rectangularcoordinates"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/sphericalCoordinates": {
      "abstract": [
        {
          "text": "A flag that indicates the channel uses the speaker position’s spherical coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sphericalCoordinates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelFlags",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/sphericalCoordinates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelFlags_SphericalCoordinates"
        }
      ],
      "role": "symbol",
      "title": "sphericalCoordinates",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags/sphericalcoordinates"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel": {
      "abstract": [
        {
          "text": "Identifies how an audio data channel is to be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelLabel"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelLabel",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellabel"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-labels": {
      "abstract": [
        {
          "text": "Channel labels for use in the ",
          "type": "text"
        },
        {
          "code": "mChannelLabel",
          "type": "codeVoice"
        },
        {
          "text": " field of an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-labels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Channel Labels",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audio-channel-labels"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelFlags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelLabel",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mCoordinates",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-labels"
      ],
      "title": "Accessing the Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Coordinates",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Azimuth",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Distance",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Elevation"
      ],
      "title": "Coordinates"
    },
    {
      "anchor": "Flags",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/rectangularCoordinates",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/sphericalCoordinates",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/meters"
      ],
      "title": "Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Coordinates",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Azimuth",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Distance",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelCoordinateIndex/coordinates_Elevation"
              ],
              "title": "Coordinates"
            },
            {
              "anchor": "Flags",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/kAudioChannelFlags_AllOff",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/rectangularCoordinates",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/sphericalCoordinates",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/meters"
              ],
              "title": "Flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelFlags",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelLabel",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mCoordinates",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags"
              ],
              "title": "Accessing the Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLabel/title",
          "value": "AudioChannelLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex/title",
          "value": "AudioChannelCoordinateIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelCoordinateIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelCoordinateIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Azimuth/title",
          "value": "kAudioChannelCoordinates_Azimuth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Azimuth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelCoordinates_Azimuth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1meters/title",
          "value": "kAudioChannelFlags_Meters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1meters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelFlags_Meters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Distance/title",
          "value": "kAudioChannelCoordinates_Distance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Distance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelCoordinates_Distance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mChannelLabel/title",
          "value": "mChannelLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mChannelLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mChannelLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription/title",
          "value": "AudioChannelDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mChannelFlags/title",
          "value": "mChannelFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mChannelFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mChannelFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mCoordinates/title",
          "value": "mCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mCoordinates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mCoordinates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags/title",
          "value": "AudioChannelFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Elevation/title",
          "value": "kAudioChannelCoordinates_Elevation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelCoordinateIndex~1coordinates_Elevation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelCoordinates_Elevation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1sphericalCoordinates/title",
          "value": "kAudioChannelFlags_SphericalCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1sphericalCoordinates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelFlags_SphericalCoordinates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1rectangularCoordinates/title",
          "value": "kAudioChannelFlags_RectangularCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1rectangularCoordinates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelFlags_RectangularCoordinates"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audio-channel-coordinates"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audio-channel-coordinates"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
