{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/coreaudiotypes-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CoreAudioTypes Enumerations"
  },
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/2962796-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/2962796-anonymous",
      "kind": "article",
      "role": "article",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/2962796-anonymous"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/4278542-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/4278542-anonymous",
      "kind": "article",
      "role": "article",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/4278542-anonymous"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/CA_PREFER_FIXED_POINT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CA_PREFER_FIXED_POINT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/CA_PREFER_FIXED_POINT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CA_PREFER_FIXED_POINT"
        }
      ],
      "role": "symbol",
      "title": "CA_PREFER_FIXED_POINT",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/ca_prefer_fixed_point"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-stream-basic-description-flags": {
      "abstract": [
        {
          "text": "The standard format flags for an audio stream basic description.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-stream-basic-description-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Stream Basic Description Flags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audio-stream-basic-description-flags"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-stream-basic-description-flags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/2962796-anonymous",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/4278542-anonymous"
      ],
      "title": "Enumerations"
    },
    {
      "anchor": "Global-variables",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/CA_PREFER_FIXED_POINT"
      ],
      "title": "Global variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Global-variables",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/CA_PREFER_FIXED_POINT"
              ],
              "title": "Global variables"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1CA_PREFER_FIXED_POINT/title",
          "value": "CA_PREFER_FIXED_POINT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1CA_PREFER_FIXED_POINT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CA_PREFER_FIXED_POINT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/coreaudiotypes-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/coreaudiotypes-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
