{
  "abstract": [
    {
      "text": "The beginning value for a reserved range of layout tags.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_BeginReserved"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioChannelLayoutTag_UseChannelDescriptions@kAudioChannelLayoutTag_BeginReserved",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioChannelLayoutTag_BeginReserved"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
        "text": "AudioChannelLayoutTag"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioChannelLayoutTag_BeginReserved"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.14",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "5.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioChannelLayoutTag_BeginReserved"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_BeginReserved"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
              "text": "AudioChannelLayoutTag"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The values in the range between ",
              "type": "text"
            },
            {
              "code": "kAudioChannelLayoutTag_BeginReserved",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_EndReserved",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " are for future Apple use. Do not create layout tags that fall in the range created by these values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag": {
      "abstract": [
        {
          "text": "Identifies a previously-defined channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelLayoutTag",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellayouttag"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_BeginReserved": {
      "abstract": [
        {
          "text": "The beginning value for a reserved range of layout tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_BeginReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_BeginReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_BeginReserved"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_BeginReserved",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_beginreserved"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_EndReserved": {
      "abstract": [
        {
          "text": "The ending value for a reserved range of layout tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_EndReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_EndReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_EndReserved"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_EndReserved",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_endreserved"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reserved-Tag-Range",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_EndReserved"
      ],
      "title": "Reserved Tag Range"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioChannelLayoutTag_BeginReserved"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_BeginReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reserved-Tag-Range",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_EndReserved"
              ],
              "title": "Reserved Tag Range"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioChannelLayoutTag_BeginReserved"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_BeginReserved/title",
          "value": "kAudioChannelLayoutTag_BeginReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_BeginReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_BeginReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/title",
          "value": "AudioChannelLayoutTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_EndReserved/title",
          "value": "kAudioChannelLayoutTag_EndReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_EndReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_EndReserved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudiochannellayouttag_beginreserved"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudiochannellayouttag_beginreserved"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
