{
  "abstract": [
    {
      "text": "A key that specifies the MPEG-4 TwinVQ codec, and uses no flags.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4TwinVQ"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioFormatLinearPCM@kAudioFormatMPEG4TwinVQ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioFormatMPEG4TwinVQ"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioFormatID",
        "text": "AudioFormatID"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioFormatMPEG4TwinVQ"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioFormatMPEG4TwinVQ"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4TwinVQ"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioFormatID",
              "text": "AudioFormatID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID": {
      "abstract": [
        {
          "text": "A type definition for audio format identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatID"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatID",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audioformatid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormat60958AC3": {
      "abstract": [
        {
          "text": "A key that specifies the AC-3 codec, which provides data packaged for transport over an IEC 60958-compliant digital audio interface, and uses standard flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormat60958AC3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormat60958AC3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormat60958AC3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormat60958AC3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformat60958ac3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAC3": {
      "abstract": [
        {
          "text": "A key that specifies the AC-3 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAC3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAC3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAC3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAC3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatac3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAES3": {
      "abstract": [
        {
          "text": "A key that specifies the codec defined by the AES3-2003 standard, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAES3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAES3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAES3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAES3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformataes3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatALaw": {
      "abstract": [
        {
          "text": "A key that specifies the A-law 2:1 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatALaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatALaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatALaw"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatALaw",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatalaw"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR": {
      "abstract": [
        {
          "text": "A key that specifies the Adaptive Multi-Rate (AMR) narrow band speech codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAMR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAMR"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAMR",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatamr"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR_WB": {
      "abstract": [
        {
          "text": "A key that specifies the AMR Wideband speech codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAMR_WB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR_WB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAMR_WB"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAMR_WB",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatamr_wb"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleIMA4": {
      "abstract": [
        {
          "text": "A key that specifies Apple’s implementation of the IMA 4:1 ADPCM codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAppleIMA4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleIMA4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAppleIMA4"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAppleIMA4",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatappleima4"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleLossless": {
      "abstract": [
        {
          "text": "A key that specifies the Apple Lossless codec, and uses flags to indicate the bit depth of the source material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAppleLossless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleLossless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAppleLossless"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAppleLossless",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatapplelossless"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAudible": {
      "abstract": [
        {
          "text": "A key that specifies the codec for Audible audio books, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatAudible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAudible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatAudible"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatAudible",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformataudible"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatDVIIntelIMA": {
      "abstract": [
        {
          "text": "A key that specifies the codec defined by DVI/Intel IMA ADPCM - ACM code 17, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatDVIIntelIMA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatDVIIntelIMA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatDVIIntelIMA"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatDVIIntelIMA",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatdviintelima"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatEnhancedAC3": {
      "abstract": [
        {
          "text": "A key that specifies the Enhanced AC-3 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatEnhancedAC3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatEnhancedAC3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatEnhancedAC3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatEnhancedAC3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatenhancedac3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFLAC": {
      "abstract": [
        {
          "text": "A key that specifies the Free Lossless Audio Codec (FLAC), and uses flags to indicate the bit depth of the source material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFLAC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFLAC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFLAC"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFLAC",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflac"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatLinearPCM": {
      "abstract": [
        {
          "text": "A key that specifies the linear PCM codec, and uses the standard flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatLinearPCM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatLinearPCM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatLinearPCM"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatLinearPCM",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatlinearpcm"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE3": {
      "abstract": [
        {
          "text": "A key that specifies the MACE 3:1 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMACE3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMACE3"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMACE3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmace3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE6": {
      "abstract": [
        {
          "text": "A key that specifies the MACE C:1 codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMACE6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMACE6"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMACE6",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmace6"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4TwinVQ": {
      "abstract": [
        {
          "text": "A key that specifies the MPEG-4 TwinVQ codec, and uses no flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4TwinVQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatID",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMPEG4TwinVQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatMPEG4TwinVQ"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatMPEG4TwinVQ",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatmpeg4twinvq"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormat60958AC3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAC3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAES3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatALaw",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR_WB",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleIMA4",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleLossless",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAudible",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatDVIIntelIMA",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatEnhancedAC3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFLAC",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatLinearPCM",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE6"
      ],
      "title": "Format identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioFormatMPEG4TwinVQ"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4TwinVQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormat60958AC3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAC3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAES3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatALaw",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAMR_WB",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleIMA4",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAppleLossless",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatAudible",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatDVIIntelIMA",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatEnhancedAC3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFLAC",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatLinearPCM",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatMACE6"
              ],
              "title": "Format identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioFormatMPEG4TwinVQ"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAppleLossless/title",
          "value": "kAudioFormatAppleLossless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAppleLossless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAppleLossless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4TwinVQ/title",
          "value": "kAudioFormatMPEG4TwinVQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMPEG4TwinVQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMPEG4TwinVQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/title",
          "value": "AudioFormatID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMACE6/title",
          "value": "kAudioFormatMACE6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMACE6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMACE6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatEnhancedAC3/title",
          "value": "kAudioFormatEnhancedAC3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatEnhancedAC3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatEnhancedAC3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatALaw/title",
          "value": "kAudioFormatALaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatALaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatALaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatLinearPCM/title",
          "value": "kAudioFormatLinearPCM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatLinearPCM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatLinearPCM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatDVIIntelIMA/title",
          "value": "kAudioFormatDVIIntelIMA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatDVIIntelIMA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatDVIIntelIMA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAMR/title",
          "value": "kAudioFormatAMR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAMR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAMR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFLAC/title",
          "value": "kAudioFormatFLAC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFLAC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFLAC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAES3/title",
          "value": "kAudioFormatAES3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAES3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAES3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAC3/title",
          "value": "kAudioFormatAC3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAC3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAC3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAppleIMA4/title",
          "value": "kAudioFormatAppleIMA4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAppleIMA4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAppleIMA4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAMR_WB/title",
          "value": "kAudioFormatAMR_WB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAMR_WB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAMR_WB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormat60958AC3/title",
          "value": "kAudioFormat60958AC3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormat60958AC3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormat60958AC3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMACE3/title",
          "value": "kAudioFormatMACE3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatMACE3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatMACE3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAudible/title",
          "value": "kAudioFormatAudible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatAudible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatAudible"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudioformatmpeg4twinvq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudioformatmpeg4twinvq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
