{
  "abstract": [
    {
      "text": "A matrix-encoded stereo stream.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MatrixStereo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioChannelLayoutTag_UseChannelDescriptions@kAudioChannelLayoutTag_MatrixStereo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioChannelLayoutTag_MatrixStereo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
        "text": "AudioChannelLayoutTag"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioChannelLayoutTag_MatrixStereo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioChannelLayoutTag_MatrixStereo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MatrixStereo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
              "text": "AudioChannelLayoutTag"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your channels must be laid out in the following order:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Left matrix total",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Right matrix total",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag": {
      "abstract": [
        {
          "text": "Identifies a previously-defined channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelLayoutTag",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellayouttag"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Ambisonic_B_Format": {
      "abstract": [
        {
          "text": "An ambisonic B-format audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Ambisonic_B_Format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Ambisonic_B_Format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Ambisonic_B_Format"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_Ambisonic_B_Format",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_ambisonic_b_format"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Binaural": {
      "abstract": [
        {
          "text": "A binaural stereo audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Binaural"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Binaural",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Binaural"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_Binaural",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_binaural"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Cube": {
      "abstract": [
        {
          "text": "A cubic audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Cube"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Cube",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Cube"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_Cube",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cube"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Hexagonal": {
      "abstract": [
        {
          "text": "A hexagonal audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Hexagonal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Hexagonal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Hexagonal"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_Hexagonal",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_hexagonal"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MatrixStereo": {
      "abstract": [
        {
          "text": "A matrix-encoded stereo stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MatrixStereo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MatrixStereo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MatrixStereo"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MatrixStereo",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_matrixstereo"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MidSide": {
      "abstract": [
        {
          "text": "A middle and side channel audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MidSide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MidSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MidSide"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MidSide",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_midside"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Mono": {
      "abstract": [
        {
          "text": "A standard monophonic stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Mono"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Mono",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Mono"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_Mono",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mono"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Octagonal": {
      "abstract": [
        {
          "text": "An octagonal audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Octagonal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Octagonal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Octagonal"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_Octagonal",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_octagonal"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Pentagonal": {
      "abstract": [
        {
          "text": "A pentalgonal audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Pentagonal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Pentagonal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Pentagonal"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_Pentagonal",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_pentagonal"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Quadraphonic": {
      "abstract": [
        {
          "text": "A quadraphonic audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Quadraphonic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Quadraphonic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Quadraphonic"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_Quadraphonic",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_quadraphonic"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Stereo": {
      "abstract": [
        {
          "text": "A standard stereophonic stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Stereo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Stereo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_Stereo"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_Stereo",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_stereo"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_StereoHeadphones": {
      "abstract": [
        {
          "text": "A standard stereo stream; headphone playback implied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_StereoHeadphones"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_StereoHeadphones",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_StereoHeadphones"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_StereoHeadphones",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_stereoheadphones"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelBitmap": {
      "abstract": [
        {
          "text": "A bitmap that defines the layout mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_UseChannelBitmap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelBitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_UseChannelBitmap"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_UseChannelBitmap",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_usechannelbitmap"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelDescriptions": {
      "abstract": [
        {
          "text": "An array of audio channel description structures that defines the layout mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_UseChannelDescriptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelDescriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_UseChannelDescriptions"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_UseChannelDescriptions",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_usechanneldescriptions"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_XY": {
      "abstract": [
        {
          "text": "A coincident, angled microphone pair.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_XY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_XY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_XY"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_XY",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_xy"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-Layouts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelDescriptions",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelBitmap",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Mono",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Stereo",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_StereoHeadphones",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MidSide",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_XY",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Binaural",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Ambisonic_B_Format",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Quadraphonic",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Pentagonal",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Hexagonal",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Octagonal",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Cube"
      ],
      "title": "General Layouts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioChannelLayoutTag_MatrixStereo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MatrixStereo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-Layouts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelDescriptions",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_UseChannelBitmap",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Mono",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Stereo",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_StereoHeadphones",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MidSide",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_XY",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Binaural",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Ambisonic_B_Format",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Quadraphonic",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Pentagonal",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Hexagonal",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Octagonal",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_Cube"
              ],
              "title": "General Layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioChannelLayoutTag_MatrixStereo"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Ambisonic_B_Format/title",
          "value": "kAudioChannelLayoutTag_Ambisonic_B_Format"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Ambisonic_B_Format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_Ambisonic_B_Format"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_XY/title",
          "value": "kAudioChannelLayoutTag_XY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_XY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_XY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Quadraphonic/title",
          "value": "kAudioChannelLayoutTag_Quadraphonic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Quadraphonic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_Quadraphonic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Cube/title",
          "value": "kAudioChannelLayoutTag_Cube"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Cube/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_Cube"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Binaural/title",
          "value": "kAudioChannelLayoutTag_Binaural"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Binaural/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_Binaural"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MatrixStereo/title",
          "value": "kAudioChannelLayoutTag_MatrixStereo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MatrixStereo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MatrixStereo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Stereo/title",
          "value": "kAudioChannelLayoutTag_Stereo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Stereo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_Stereo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/title",
          "value": "AudioChannelLayoutTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Mono/title",
          "value": "kAudioChannelLayoutTag_Mono"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Mono/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_Mono"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Pentagonal/title",
          "value": "kAudioChannelLayoutTag_Pentagonal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Pentagonal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_Pentagonal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Octagonal/title",
          "value": "kAudioChannelLayoutTag_Octagonal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Octagonal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_Octagonal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_UseChannelBitmap/title",
          "value": "kAudioChannelLayoutTag_UseChannelBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_UseChannelBitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_UseChannelBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_UseChannelDescriptions/title",
          "value": "kAudioChannelLayoutTag_UseChannelDescriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_UseChannelDescriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_UseChannelDescriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_StereoHeadphones/title",
          "value": "kAudioChannelLayoutTag_StereoHeadphones"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_StereoHeadphones/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_StereoHeadphones"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MidSide/title",
          "value": "kAudioChannelLayoutTag_MidSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MidSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MidSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Hexagonal/title",
          "value": "kAudioChannelLayoutTag_Hexagonal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_Hexagonal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_Hexagonal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudiochannellayouttag_matrixstereo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudiochannellayouttag_matrixstereo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
