{
  "abstract": [
    {
      "text": "5 channels, L R Rls Rrs C",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_E"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioChannelLayoutTag_UseChannelDescriptions@kAudioChannelLayoutTag_MPEG_5_0_E",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioChannelLayoutTag_MPEG_5_0_E"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
        "text": "AudioChannelLayoutTag"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioChannelLayoutTag_MPEG_5_0_E"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioChannelLayoutTag_MPEG_5_0_E"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_0_E"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
              "text": "AudioChannelLayoutTag"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag": {
      "abstract": [
        {
          "text": "Identifies a previously-defined channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelLayoutTag",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellayouttag"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_1_0": {
      "abstract": [
        {
          "text": "An MPEG 1-channel audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_1_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_1_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_1_0"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_1_0",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_1_0"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_2_0": {
      "abstract": [
        {
          "text": "An MPEG 2-channel audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_2_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_2_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_2_0"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_2_0",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_2_0"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_3_0_A": {
      "abstract": [
        {
          "text": "An MPEG 3-channel, configuration A, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_3_0_A"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_3_0_A",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_3_0_A"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_3_0_A",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_3_0_a"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_3_0_B": {
      "abstract": [
        {
          "text": "An MPEG 3-channel, configuration B, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_3_0_B"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_3_0_B",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_3_0_B"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_3_0_B",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_3_0_b"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_4_0_A": {
      "abstract": [
        {
          "text": "An MPEG 4-channel, configuration A, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_4_0_A"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_4_0_A",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_4_0_A"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_4_0_A",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_4_0_a"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_4_0_B": {
      "abstract": [
        {
          "text": "An MPEG 4-channel, configuration B, audio layout",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_4_0_B"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_4_0_B",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_4_0_B"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_4_0_B",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_4_0_b"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_A": {
      "abstract": [
        {
          "text": "An MPEG 5-channel, configuration A, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_0_A"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_A",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_0_A"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_5_0_A",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_0_a"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_B": {
      "abstract": [
        {
          "text": "An MPEG 5-channel, configuration B, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_0_B"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_B",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_0_B"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_5_0_B",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_0_b"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_C": {
      "abstract": [
        {
          "text": "An MPEG 5-channel, configuration C, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_0_C"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_C",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_0_C"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_5_0_C",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_0_c"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_D": {
      "abstract": [
        {
          "text": "An MPEG 5-channel, configuration D, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_0_D"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_0_D"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_5_0_D",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_0_d"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_E": {
      "abstract": [
        {
          "text": "5 channels, L R Rls Rrs C",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_0_E"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_E",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_0_E"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_5_0_E",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_0_e"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_A": {
      "abstract": [
        {
          "text": "An MPEG 5.1-channel, configuration A, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_1_A"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_A",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_1_A"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_5_1_A",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_1_a"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_B": {
      "abstract": [
        {
          "text": "An MPEG 5.1-channel, configuration B, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_1_B"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_B",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_1_B"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_5_1_B",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_1_b"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_C": {
      "abstract": [
        {
          "text": "An MPEG 5.1-channel, configuration C, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_1_C"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_C",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_1_C"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_5_1_C",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_1_c"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_D": {
      "abstract": [
        {
          "text": "An MPEG 5.1-channel, configuration D, audio layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_1_D"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_1_D"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_5_1_D",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_1_d"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_E": {
      "abstract": [
        {
          "text": "6 channels, L R Rls Rrs C LFE",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_1_E"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_E",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_MPEG_5_1_E"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_MPEG_5_1_E",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_1_e"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "MPEG-Defined-Layouts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_1_0",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_2_0",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_3_0_A",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_3_0_B",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_4_0_A",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_4_0_B",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_A",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_B",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_C",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_D",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_A",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_B",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_C",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_D",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_E"
      ],
      "title": "MPEG Defined Layouts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_0_E"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_0_E"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "MPEG-Defined-Layouts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_1_0",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_2_0",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_3_0_A",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_3_0_B",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_4_0_A",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_4_0_B",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_A",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_B",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_C",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_0_D",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_A",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_B",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_C",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_D",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_MPEG_5_1_E"
              ],
              "title": "MPEG Defined Layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioChannelLayoutTag_MPEG_5_0_E"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_1_E/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_1_E"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_1_E/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_1_E"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_4_0_A/title",
          "value": "kAudioChannelLayoutTag_MPEG_4_0_A"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_4_0_A/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_4_0_A"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_0_E/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_0_E"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_0_E/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_0_E"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_1_C/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_1_C"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_1_C/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_1_C"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_3_0_A/title",
          "value": "kAudioChannelLayoutTag_MPEG_3_0_A"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_3_0_A/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_3_0_A"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_0_C/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_0_C"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_0_C/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_0_C"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_0_B/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_0_B"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_0_B/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_0_B"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/title",
          "value": "AudioChannelLayoutTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_1_B/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_1_B"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_1_B/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_1_B"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_0_A/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_0_A"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_0_A/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_0_A"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_2_0/title",
          "value": "kAudioChannelLayoutTag_MPEG_2_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_2_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_2_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_1_0/title",
          "value": "kAudioChannelLayoutTag_MPEG_1_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_1_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_1_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_0_D/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_0_D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_0_D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_0_D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_4_0_B/title",
          "value": "kAudioChannelLayoutTag_MPEG_4_0_B"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_4_0_B/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_4_0_B"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_1_D/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_1_D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_1_D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_1_D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_3_0_B/title",
          "value": "kAudioChannelLayoutTag_MPEG_3_0_B"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_3_0_B/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_3_0_B"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_1_A/title",
          "value": "kAudioChannelLayoutTag_MPEG_5_1_A"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_MPEG_5_1_A/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_MPEG_5_1_A"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_0_e"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudiochannellayouttag_mpeg_5_0_e"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
