{
  "abstract": [
    {
      "text": "Right surround channel; or for WAVE (.wav) files, back right.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_RightSurround"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioChannelLabel_Unknown@kAudioChannelLabel_RightSurround",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioChannelLabel_RightSurround"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioChannelLabel",
        "text": "AudioChannelLabel"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioChannelLabel_RightSurround"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioChannelLabel_RightSurround"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_RightSurround"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioChannelLabel",
              "text": "AudioChannelLabel"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel": {
      "abstract": [
        {
          "text": "Identifies how an audio data channel is to be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelLabel"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelLabel",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellabel"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_W": {
      "abstract": [
        {
          "text": "First order Ambisonic channel W.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_Ambisonic_W"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_W",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_Ambisonic_W"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_Ambisonic_W",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_ambisonic_w"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_X": {
      "abstract": [
        {
          "text": "First order Ambisonic channel X.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_Ambisonic_X"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_X",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_Ambisonic_X"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_Ambisonic_X",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_ambisonic_x"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_Y": {
      "abstract": [
        {
          "text": "First order Ambisonic channel Y.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_Ambisonic_Y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_Y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_Ambisonic_Y"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_Ambisonic_Y",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_ambisonic_y"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_Z": {
      "abstract": [
        {
          "text": "First order Ambisonic channel Z.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_Ambisonic_Z"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_Z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_Ambisonic_Z"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_Ambisonic_Z",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_ambisonic_z"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BeginReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_BeginReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BeginReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_BeginReserved"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_BeginReserved",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_beginreserved"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BinauralLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_BinauralLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BinauralLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_BinauralLeft"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_BinauralLeft",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_binauralleft"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BinauralRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_BinauralRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BinauralRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_BinauralRight"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_BinauralRight",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_binauralright"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Center": {
      "abstract": [
        {
          "text": "Center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_Center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_Center"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_Center",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_center"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterBottom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterBottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterBottom"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_CenterBottom",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_centerbottom"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterSurround": {
      "abstract": [
        {
          "text": "Center surround channel; or for WAVE (.wav) files, back center or rear surround.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterSurround"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterSurround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterSurround"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_CenterSurround",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_centersurround"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterSurroundDirect": {
      "abstract": [
        {
          "text": "Back center, non diffuse channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterSurroundDirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterSurroundDirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterSurroundDirect"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_CenterSurroundDirect",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_centersurrounddirect"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopFront": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterTopFront"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopFront",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterTopFront"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_CenterTopFront",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_centertopfront"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopMiddle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterTopMiddle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopMiddle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterTopMiddle"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_CenterTopMiddle",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_centertopmiddle"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopRear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterTopRear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopRear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_CenterTopRear"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_CenterTopRear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_centertoprear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_ClickTrack": {
      "abstract": [
        {
          "text": "Click track channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_ClickTrack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_ClickTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_ClickTrack"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_ClickTrack",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_clicktrack"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_RightSurround": {
      "abstract": [
        {
          "text": "Right surround channel; or for WAVE (.wav) files, back right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_RightSurround"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_RightSurround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLabel_RightSurround"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLabel_RightSurround",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellabel_rightsurround"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Labels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_W",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_X",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_Y",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_Z",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BeginReserved",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BinauralLeft",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BinauralRight",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Center",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterBottom",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterSurround",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterSurroundDirect",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopFront",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopMiddle",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopRear",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_ClickTrack"
      ],
      "title": "Labels"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioChannelLabel_RightSurround"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_RightSurround"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Labels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_W",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_X",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_Y",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Ambisonic_Z",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BeginReserved",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BinauralLeft",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_BinauralRight",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_Center",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterBottom",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterSurround",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterSurroundDirect",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopFront",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopMiddle",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_CenterTopRear",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLabel_ClickTrack"
              ],
              "title": "Labels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioChannelLabel_RightSurround"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_BeginReserved/title",
          "value": "kAudioChannelLabel_BeginReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_BeginReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_BeginReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLabel/title",
          "value": "AudioChannelLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterSurround/title",
          "value": "kAudioChannelLabel_CenterSurround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterSurround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_CenterSurround"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_Ambisonic_W/title",
          "value": "kAudioChannelLabel_Ambisonic_W"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_Ambisonic_W/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_Ambisonic_W"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_Center/title",
          "value": "kAudioChannelLabel_Center"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_Center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_Center"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterTopRear/title",
          "value": "kAudioChannelLabel_CenterTopRear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterTopRear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_CenterTopRear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_Ambisonic_X/title",
          "value": "kAudioChannelLabel_Ambisonic_X"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_Ambisonic_X/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_Ambisonic_X"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterSurroundDirect/title",
          "value": "kAudioChannelLabel_CenterSurroundDirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterSurroundDirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_CenterSurroundDirect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterTopFront/title",
          "value": "kAudioChannelLabel_CenterTopFront"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterTopFront/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_CenterTopFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterTopMiddle/title",
          "value": "kAudioChannelLabel_CenterTopMiddle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterTopMiddle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_CenterTopMiddle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterBottom/title",
          "value": "kAudioChannelLabel_CenterBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_CenterBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_CenterBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_ClickTrack/title",
          "value": "kAudioChannelLabel_ClickTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_ClickTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_ClickTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_BinauralRight/title",
          "value": "kAudioChannelLabel_BinauralRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_BinauralRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_BinauralRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_Ambisonic_Y/title",
          "value": "kAudioChannelLabel_Ambisonic_Y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_Ambisonic_Y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_Ambisonic_Y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_RightSurround/title",
          "value": "kAudioChannelLabel_RightSurround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_RightSurround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_RightSurround"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_BinauralLeft/title",
          "value": "kAudioChannelLabel_BinauralLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_BinauralLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_BinauralLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_Ambisonic_Z/title",
          "value": "kAudioChannelLabel_Ambisonic_Z"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLabel_Ambisonic_Z/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLabel_Ambisonic_Z"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudiochannellabel_rightsurround"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudiochannellabel_rightsurround"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
