{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_9"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioChannelLayoutTag_UseChannelDescriptions@kAudioChannelLayoutTag_CICP_9",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioChannelLayoutTag_CICP_9"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
        "text": "AudioChannelLayoutTag"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioChannelLayoutTag_CICP_9"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioChannelLayoutTag_CICP_9"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_9"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
              "text": "AudioChannelLayoutTag"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag": {
      "abstract": [
        {
          "text": "Identifies a previously-defined channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLayoutTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelLayoutTag",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellayouttag"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_1"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_1",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_1"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_10": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_10"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_10",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_10"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_11": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_11"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_11",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_11"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_11",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_11"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_12": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_12"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_12"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_12",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_12"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_13": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_13",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_13"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_13",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_13"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_14": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_14"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_14",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_14"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_14",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_14"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_15": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_15"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_15",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_15"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_15",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_15"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_16"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_16",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_16"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_17": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_17"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_17",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_17"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_17",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_17"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_2"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_2",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_2"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_3"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_3",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_3"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_4"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_4",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_4"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_5"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_5",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_5"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_6"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_6",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_6"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_7"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_7"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_7",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_7"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_9": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_9"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_CICP_9"
        }
      ],
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_CICP_9",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_9"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "CICP",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_1",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_2",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_3",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_4",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_5",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_6",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_7",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_10",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_11",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_12",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_13",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_14",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_15",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_16",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_17"
      ],
      "title": "CICP"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioChannelLayoutTag_CICP_9"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_9"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "CICP",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_1",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_2",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_3",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_4",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_5",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_6",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_7",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_10",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_11",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_12",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_13",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_14",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_15",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_16",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioChannelLayoutTag_CICP_17"
              ],
              "title": "CICP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioChannelLayoutTag_CICP_9"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_11/title",
          "value": "kAudioChannelLayoutTag_CICP_11"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_11/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_11"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_9/title",
          "value": "kAudioChannelLayoutTag_CICP_9"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_9"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_16/title",
          "value": "kAudioChannelLayoutTag_CICP_16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_6/title",
          "value": "kAudioChannelLayoutTag_CICP_6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_7/title",
          "value": "kAudioChannelLayoutTag_CICP_7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_17/title",
          "value": "kAudioChannelLayoutTag_CICP_17"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_17/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_17"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_4/title",
          "value": "kAudioChannelLayoutTag_CICP_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_13/title",
          "value": "kAudioChannelLayoutTag_CICP_13"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_13/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_13"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_1/title",
          "value": "kAudioChannelLayoutTag_CICP_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_3/title",
          "value": "kAudioChannelLayoutTag_CICP_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_12/title",
          "value": "kAudioChannelLayoutTag_CICP_12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/title",
          "value": "AudioChannelLayoutTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLayoutTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLayoutTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_2/title",
          "value": "kAudioChannelLayoutTag_CICP_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_10/title",
          "value": "kAudioChannelLayoutTag_CICP_10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_15/title",
          "value": "kAudioChannelLayoutTag_CICP_15"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_15/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_15"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_14/title",
          "value": "kAudioChannelLayoutTag_CICP_14"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_14/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_14"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_5/title",
          "value": "kAudioChannelLayoutTag_CICP_5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_CICP_5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_CICP_5"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_9"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudiochannellayouttag_cicp_9"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
