{
  "abstract": [
    {
      "text": "A flag that indicates the format is nonmixable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioFormatFlagIsFloat@kAudioFormatFlagIsNonMixable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioFormatFlagIsNonMixable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioFormatFlags",
        "text": "AudioFormatFlags"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioFormatFlagIsNonMixable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioFormatFlagIsNonMixable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsNonMixable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioFormatFlags",
              "text": "AudioFormatFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Only use this flag when interacting with the stream format information of the hardware abstraction layer (HAL). It isn’t a valid flag for any other use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags": {
      "abstract": [
        {
          "text": "A type definition for audio format flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audioformatflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 16-bit native endian signed integer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_16BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_16BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_16BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_16bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 20-bit native endian signed integer data aligned high in 24 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_20BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_20BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_20BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_20bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 24-bit native endian signed integer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_24BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_24BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_24BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_24bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData": {
      "abstract": [
        {
          "text": "A flag that indicates Apple Lossless data sourced from 32-bit native endian signed integer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_32BitSourceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAppleLosslessFormatFlag_32BitSourceData"
        }
      ],
      "role": "symbol",
      "title": "kAppleLosslessFormatFlag_32BitSourceData",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kapplelosslessformatflag_32bitsourcedata"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits is with the high or low bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsAlignedHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsAlignedHigh"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsAlignedHigh",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisalignedhigh"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is big or little endian.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsBigEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsBigEndian"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsBigEndian",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisbigendian"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is floating point or integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsFloat"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsFloat",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisfloat"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved": {
      "abstract": [
        {
          "text": "A flag that indicates whether the samples for each channel or frame are continguously located, and whether the layout of the channels or frames is end-to-end.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonInterleaved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonInterleaved"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsNonInterleaved",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisnoninterleaved"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable": {
      "abstract": [
        {
          "text": "A flag that indicates the format is nonmixable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonMixable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonMixable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsNonMixable"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsNonMixable",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagisnonmixable"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits occupy the entire available bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsPacked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsPacked"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsPacked",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagispacked"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is signed or unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsSignedInteger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagIsSignedInteger"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagIsSignedInteger",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagissignedinteger"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear": {
      "abstract": [
        {
          "text": "A flag that indicates whether all the flags are clear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsAreAllClear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsAreAllClear"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagsAreAllClear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagsareallclear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeEndian": {
      "abstract": [
        {
          "text": "A flag that specifies whether the format is big endian, depending on the endianness of the processor at build time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsNativeEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsNativeEndian"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagsNativeEndian",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagsnativeendian"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeFloatPacked": {
      "abstract": [
        {
          "text": "The flags for the canonical format of fully packed, native endian floating-point data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsNativeFloatPacked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeFloatPacked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioFormatFlagsNativeFloatPacked"
        }
      ],
      "role": "symbol",
      "title": "kAudioFormatFlagsNativeFloatPacked",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudioformatflagsnativefloatpacked"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh": {
      "abstract": [
        {
          "text": "A flag that indicates whether placement of the sample bits is with the high or low bits of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsAlignedHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsAlignedHigh"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsAlignedHigh",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisalignedhigh"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian": {
      "abstract": [
        {
          "text": "A flag that indicates whether the format is big or little endian.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsBigEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioFormatFlags",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLinearPCMFormatFlagIsBigEndian"
        }
      ],
      "role": "symbol",
      "title": "kLinearPCMFormatFlagIsBigEndian",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/klinearpcmformatflagisbigendian"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-flags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeEndian",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeFloatPacked",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian"
      ],
      "title": "Format flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioFormatFlagIsNonMixable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsNonMixable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-flags",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_16BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_20BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_24BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAppleLosslessFormatFlag_32BitSourceData",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsAlignedHigh",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsBigEndian",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsFloat",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsNonInterleaved",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsPacked",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagIsSignedInteger",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsAreAllClear",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeEndian",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioFormatFlagsNativeFloatPacked",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsAlignedHigh",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kLinearPCMFormatFlagIsBigEndian"
              ],
              "title": "Format flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioFormatFlagIsNonMixable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsNativeFloatPacked/title",
          "value": "kAudioFormatFlagsNativeFloatPacked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsNativeFloatPacked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagsNativeFloatPacked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_24BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_24BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_24BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_24BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_16BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_16BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_16BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_16BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_32BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_32BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_32BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_32BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsAlignedHigh/title",
          "value": "kAudioFormatFlagIsAlignedHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsAlignedHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsAlignedHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsNativeEndian/title",
          "value": "kAudioFormatFlagsNativeEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsNativeEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagsNativeEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsAlignedHigh/title",
          "value": "kLinearPCMFormatFlagIsAlignedHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsAlignedHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsAlignedHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/title",
          "value": "AudioFormatFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsFloat/title",
          "value": "kAudioFormatFlagIsFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsSignedInteger/title",
          "value": "kAudioFormatFlagIsSignedInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsSignedInteger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsSignedInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonMixable/title",
          "value": "kAudioFormatFlagIsNonMixable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonMixable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsNonMixable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsPacked/title",
          "value": "kAudioFormatFlagIsPacked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsPacked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsPacked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_20BitSourceData/title",
          "value": "kAppleLosslessFormatFlag_20BitSourceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAppleLosslessFormatFlag_20BitSourceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAppleLosslessFormatFlag_20BitSourceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsBigEndian/title",
          "value": "kAudioFormatFlagIsBigEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsBigEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsBigEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsBigEndian/title",
          "value": "kLinearPCMFormatFlagIsBigEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kLinearPCMFormatFlagIsBigEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLinearPCMFormatFlagIsBigEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonInterleaved/title",
          "value": "kAudioFormatFlagIsNonInterleaved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagIsNonInterleaved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagIsNonInterleaved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsAreAllClear/title",
          "value": "kAudioFormatFlagsAreAllClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioFormatFlagsAreAllClear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioFormatFlagsAreAllClear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudioformatflagisnonmixable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/kaudioformatflagisnonmixable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
