{
  "abstract": [
    {
      "text": "Constants that define the type of MPEG-4 audio data.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Deprecated in Mac OS X 10.5.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPEG4ObjectID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MPEG4ObjectID"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPEG4ObjectID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.11",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MPEG4ObjectID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags": {
      "abstract": [
        {
          "text": "A type definition for audio format flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audioformatflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID": {
      "abstract": [
        {
          "text": "A type definition for audio format identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioFormatID"
        }
      ],
      "role": "symbol",
      "title": "AudioFormatID",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audioformatid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription": {
      "abstract": [
        {
          "text": "A format specification for an audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamBasicDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreambasicdescription"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription": {
      "abstract": [
        {
          "text": "A value that describes a packet in a buffer of audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamPacketDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamPacketDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamPacketDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreampacketdescription"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID": {
      "abstract": [
        {
          "text": "Constants that define the type of MPEG-4 audio data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPEG4ObjectID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPEG4ObjectID"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LC": {
      "abstract": [
        {
          "text": "A constant that specifies lossless coding, which provides compression with no loss of quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAC_LC"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_LC"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.AAC_LC",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_lc"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LTP": {
      "abstract": [
        {
          "text": "A constant that specifies long-term prediction, which reduces redundancy in a coded signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAC_LTP"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_LTP"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.AAC_LTP",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_ltp"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SBR": {
      "abstract": [
        {
          "text": "A constant that specifies spectral band replication, which reconstructs high-frequency content from lower frequencies and side information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAC_SBR"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SBR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_SBR"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.AAC_SBR",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_sbr"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SSR": {
      "abstract": [
        {
          "text": "A constant that specifies scalable sampling rate, which provides different sampling frequencies for different targets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAC_SSR"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SSR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_SSR"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.AAC_SSR",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_ssr"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/CELP": {
      "abstract": [
        {
          "text": "A constant that specifies code-excited linear prediction, which is a narrow-band/wide-band speech codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CELP"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/CELP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_CELP"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.CELP",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/celp"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/HVXC": {
      "abstract": [
        {
          "text": "A constant that specifies harmonic vector excitation coding, which is a very-low bit-rate parametric speech codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HVXC"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/HVXC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_HVXC"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.HVXC",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/hvxc"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Main": {
      "abstract": [
        {
          "text": "A constant that specifies advanced audio coding, which is the basic MPEG-4 technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aac_Main"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Main",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_Main"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.aac_Main",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_main"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Scalable": {
      "abstract": [
        {
          "text": "A constant that specifies scalable lossless coding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aac_Scalable"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Scalable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_Scalable"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.aac_Scalable",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_scalable"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/init(rawvalue:)"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/twinVQ": {
      "abstract": [
        {
          "text": "A constant that specifies transform-domain weighted interleaved vector quantization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "twinVQ"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/twinVQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_TwinVQ"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.twinVQ",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/twinvq"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-flags": {
      "abstract": [
        {
          "text": "Commonly used combinations of data format flags for an audio stream description.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Flags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audio-format-flags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for supported audio formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Identifiers",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audio-format-identifiers"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioStreamAnyRate": {
      "abstract": [
        {
          "text": "A value that indicates that an audio stream can use any sample rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamAnyRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioStreamAnyRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamAnyRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamAnyRate",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/kaudiostreamanyrate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Streams",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-flags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-format-identifiers",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioStreamAnyRate"
      ],
      "title": "Streams"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LC",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LTP",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Main",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SBR",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SSR",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Scalable",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/CELP",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/HVXC",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/twinVQ"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPEG4ObjectID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LC",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LTP",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Main",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SBR",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SSR",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Scalable",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/CELP",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/HVXC",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/twinVQ"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Streams",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamBasicDescription",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatFlags",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioFormatID",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/kAudioStreamAnyRate"
              ],
              "title": "Streams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MPEG4ObjectID"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:L",
                    "text": "long"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Deprecated in Mac OS X 10.5.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioStreamAnyRate/title",
          "value": "kAudioStreamAnyRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1kAudioStreamAnyRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamAnyRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_SSR/title",
          "value": "kMPEG4Object_AAC_SSR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_SSR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_SSR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1twinVQ/title",
          "value": "kMPEG4Object_TwinVQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1twinVQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_TwinVQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1CELP/title",
          "value": "kMPEG4Object_CELP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1CELP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_CELP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1aac_Scalable/title",
          "value": "kMPEG4Object_AAC_Scalable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1aac_Scalable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_Scalable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/title",
          "value": "MPEG4ObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_LTP/title",
          "value": "kMPEG4Object_AAC_LTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_LTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_LTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_SBR/title",
          "value": "kMPEG4Object_AAC_SBR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_SBR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_SBR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/title",
          "value": "AudioStreamBasicDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamBasicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamBasicDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamBasicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/title",
          "value": "AudioFormatID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1aac_Main/title",
          "value": "kMPEG4Object_AAC_Main"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1aac_Main/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_Main"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1HVXC/title",
          "value": "kMPEG4Object_HVXC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1HVXC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_HVXC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/title",
          "value": "AudioStreamPacketDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamPacketDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamPacketDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/title",
          "value": "AudioFormatFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioFormatFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioFormatFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_LC/title",
          "value": "kMPEG4Object_AAC_LC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_LC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_LC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/mpeg4objectid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/mpeg4objectid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
