{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlyphProperty","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}],"topicSections":[{"anchor":"Glyph-properties","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/null","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/controlCharacter","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/elastic","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/nonBaseCharacter"],"title":"Glyph properties"},{"anchor":"Initializers","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/init(rawValue:)"],"title":"Initializers"}],"variants":[{"paths":["/documentation/uikit/nslayoutmanager/glyphproperty"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/nslayoutmanager/glyphproperty"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager"]]},"seeAlsoSections":[{"anchor":"Accessing-glyphs","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/getGlyphs(in:glyphs:properties:characterIndexes:bidiLevels:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/cgGlyph(at:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/cgGlyph(at:isValidIndex:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/setGlyphs(_:properties:characterIndexes:font:forGlyphRange:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/characterIndexForGlyph(at:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/glyphIndexForCharacter(at:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/isValidGlyphIndex(_:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/numberOfGlyphs","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/propertyForGlyph(at:)"],"generated":true,"title":"Accessing glyphs"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty"},"kind":"symbol","relationshipsSections":[{"type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP","doc://com.externally.resolved.symbol/s:s9OptionSetP","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP","doc://com.externally.resolved.symbol/s:s10SetAlgebraP"],"title":"Conforms To","kind":"relationships"}],"abstract":[{"type":"text","text":"Glyph properties."}],"metadata":{"extendedModule":"UIKit","navigatorTitle":[{"kind":"identifier","text":"GlyphProperty"}],"modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlyphProperty"}],"roleHeading":"Structure","title":"NSLayoutManager.GlyphProperty","symbolKind":"struct","externalID":"c:@E@NSGlyphProperty","role":"symbol","platforms":[{"introducedAt":"7.0","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"7.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false}]},"references":{"doc://com.externally.resolved.symbol/s:s10SetAlgebraP":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SetAlgebra"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Element","preciseIdentifier":"s:s10SetAlgebraP7ElementQa"},{"kind":"text","text":"> : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s25ExpressibleByArrayLiteralP","text":"ExpressibleByArrayLiteral"}],"identifier":"doc://com.externally.resolved.symbol/s:s10SetAlgebraP","role":"symbol","title":"SetAlgebra","url":"/documentation/Swift/SetAlgebra","abstract":[{"type":"text","text":"A type that provides mathematical set operations."}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/characterIndexForGlyph(at:)":{"url":"/documentation/uikit/nslayoutmanager/characterindexforglyph(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"characterIndexForGlyph","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns the index in the text storage for the first character of the specified glyph."}],"kind":"symbol","navigatorTitle":[{"text":"characterIndexForGlyphAtIndex:","kind":"identifier"}],"type":"topic","role":"symbol","title":"characterIndexForGlyph(at:)","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/characterIndexForGlyph(at:)"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/setGlyphs(_:properties:characterIndexes:font:forGlyphRange:)":{"kind":"symbol","url":"/documentation/uikit/nslayoutmanager/setglyphs(_:properties:characterindexes:font:forglyphrange:)","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/setGlyphs(_:properties:characterIndexes:font:forGlyphRange:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setGlyphs"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CGGlyph","preciseIdentifier":"c:@T@CGGlyph"},{"text":">, ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSLayoutManager","preciseIdentifier":"c:objc(cs)NSLayoutManager","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"GlyphProperty","preciseIdentifier":"c:@E@NSGlyphProperty","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"characterIndexes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":">, ","kind":"text"},{"text":"font","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":", ","kind":"text"},{"text":"forGlyphRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Stores the initial glyphs and glyph properties for a character range.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"setGlyphs:properties:characterIndexes:font:forGlyphRange:","kind":"identifier"}],"title":"setGlyphs(_:properties:characterIndexes:font:forGlyphRange:)"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutManager","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that coordinates the layout and display of text characters."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager","role":"symbol","url":"/documentation/uikit/nslayoutmanager","kind":"symbol","navigatorTitle":[{"text":"NSLayoutManager","kind":"identifier"}],"type":"topic","title":"NSLayoutManager"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/controlCharacter":{"role":"symbol","url":"/documentation/uikit/nslayoutmanager/glyphproperty/controlcharacter","abstract":[{"text":"A glyph representing a control character.","type":"text"}],"type":"topic","title":"controlCharacter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSLayoutManager","kind":"typeIdentifier","text":"NSLayoutManager"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSGlyphProperty","kind":"typeIdentifier","text":"GlyphProperty"}],"navigatorTitle":[{"kind":"identifier","text":"NSGlyphPropertyControlCharacter"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/controlCharacter","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlyphProperty"}],"url":"/documentation/uikit/nslayoutmanager/glyphproperty","navigatorTitle":[{"kind":"identifier","text":"GlyphProperty"}],"title":"NSLayoutManager.GlyphProperty","abstract":[{"text":"Glyph properties.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP":{"kind":"symbol","abstract":[{"text":"A type that can be initialized using an array literal.","type":"text"}],"url":"/documentation/Swift/ExpressibleByArrayLiteral","identifier":"doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP","title":"ExpressibleByArrayLiteral","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressibleByArrayLiteral"}]},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/init(rawValue:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/init(rawValue:)","type":"topic","url":"/documentation/uikit/nslayoutmanager/glyphproperty/init(rawvalue:)","role":"symbol","title":"init(rawValue:)","abstract":[{"type":"text","text":"Creates a new instance with the specified raw value."}]},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","role":"symbol","url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/isValidGlyphIndex(_:)":{"url":"/documentation/uikit/nslayoutmanager/isvalidglyphindex(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValidGlyphIndex"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/isValidGlyphIndex(_:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"isValidGlyphIndex:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Indicates whether the specified index refers to a valid glyph."}],"title":"isValidGlyphIndex(_:)"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/numberOfGlyphs":{"navigatorTitle":[{"kind":"identifier","text":"numberOfGlyphs"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/numberOfGlyphs","abstract":[{"type":"text","text":"The number of glyphs in the layout manager."}],"kind":"symbol","role":"symbol","url":"/documentation/uikit/nslayoutmanager/numberofglyphs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfGlyphs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"numberOfGlyphs","type":"topic"},"doc://com.externally.resolved.symbol/s:SY":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/null":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"null","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutManager","kind":"typeIdentifier","text":"NSLayoutManager"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSGlyphProperty","kind":"typeIdentifier","text":"GlyphProperty"}],"url":"/documentation/uikit/nslayoutmanager/glyphproperty/null","navigatorTitle":[{"kind":"identifier","text":"NSGlyphPropertyNull"}],"title":"null","abstract":[{"type":"text","text":"The null glyph, which the layout manager ignores."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/null"},"doc://com.externally.resolved.symbol/s:s9OptionSetP":{"role":"symbol","url":"/documentation/Swift/OptionSet","abstract":[{"text":"A type that presents a mathematical set interface to a bit set.","type":"text"}],"type":"topic","title":"OptionSet","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionSet","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SY","text":"RawRepresentable","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s10SetAlgebraP","text":"SetAlgebra","kind":"typeIdentifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s9OptionSetP","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/cgGlyph(at:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CGGlyphAtIndex:"}],"abstract":[{"type":"text","text":"Returns the glyph at the specified index."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/cgGlyph(at:)","title":"cgGlyph(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgGlyph"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGGlyph","preciseIdentifier":"c:@T@CGGlyph"}],"kind":"symbol","url":"/documentation/uikit/nslayoutmanager/cgglyph(at:)"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/cgGlyph(at:isValidIndex:)":{"url":"/documentation/uikit/nslayoutmanager/cgglyph(at:isvalidindex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgGlyph"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"isValidIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"ObjCBool","preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"text":"CGGlyph","preciseIdentifier":"c:@T@CGGlyph","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/cgGlyph(at:isValidIndex:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"CGGlyphAtIndex:isValidIndex:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Returns the glyph at the specified index along with information about whether the glyph index is valid.","type":"text"}],"title":"cgGlyph(at:isValidIndex:)"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/glyphIndexForCharacter(at:)":{"kind":"symbol","url":"/documentation/uikit/nslayoutmanager/glyphindexforcharacter(at:)","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/glyphIndexForCharacter(at:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"glyphIndexForCharacter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"text":"Returns the index of the first glyph of the character at the specified index.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"glyphIndexForCharacterAtIndex:"}],"title":"glyphIndexForCharacter(at:)"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/getGlyphs(in:glyphs:properties:characterIndexes:bidiLevels:)":{"navigatorTitle":[{"text":"getGlyphsInRange:glyphs:properties:characterIndexes:bidiLevels:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/getGlyphs(in:glyphs:properties:characterIndexes:bidiLevels:)","abstract":[{"type":"text","text":"Fills a passed-in buffer with a sequence of glyphs."}],"kind":"symbol","role":"symbol","url":"/documentation/uikit/nslayoutmanager/getglyphs(in:glyphs:properties:characterindexes:bidilevels:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGlyphs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"text":"NSRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"glyphs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CGGlyph","preciseIdentifier":"c:@T@CGGlyph","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"properties","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSLayoutManager","preciseIdentifier":"c:objc(cs)NSLayoutManager"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GlyphProperty","preciseIdentifier":"c:@E@NSGlyphProperty"},{"kind":"text","text":">?, "},{"text":"characterIndexes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">?, ","kind":"text"},{"text":"bidiLevels","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"getGlyphs(in:glyphs:properties:characterIndexes:bidiLevels:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/elastic":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elastic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutManager","preciseIdentifier":"c:objc(cs)NSLayoutManager"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GlyphProperty","preciseIdentifier":"c:@E@NSGlyphProperty"}],"url":"/documentation/uikit/nslayoutmanager/glyphproperty/elastic","navigatorTitle":[{"kind":"identifier","text":"NSGlyphPropertyElastic"}],"title":"elastic","abstract":[{"type":"text","text":"A glyph with a changeable width, such as a white space character."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/elastic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/nonBaseCharacter":{"url":"/documentation/uikit/nslayoutmanager/glyphproperty/nonbasecharacter","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/nonBaseCharacter","role":"symbol","navigatorTitle":[{"text":"NSGlyphPropertyNonBaseCharacter","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonBaseCharacter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSLayoutManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutManager"},{"text":".","kind":"text"},{"text":"GlyphProperty","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSGlyphProperty"}],"type":"topic","title":"nonBaseCharacter","kind":"symbol","abstract":[{"text":"A glyph that combines several properties.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/propertyForGlyph(at:)":{"navigatorTitle":[{"text":"propertyForGlyphAtIndex:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/propertyForGlyph(at:)","abstract":[{"type":"text","text":"Returns the glyph property of the glyph at the specified index."}],"kind":"symbol","role":"symbol","url":"/documentation/uikit/nslayoutmanager/propertyforglyph(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyForGlyph"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSLayoutManager","preciseIdentifier":"c:objc(cs)NSLayoutManager","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"GlyphProperty","preciseIdentifier":"c:@E@NSGlyphProperty","kind":"typeIdentifier"}],"title":"propertyForGlyph(at:)","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"abstract":[{"type":"text","text":"Describes an integer."}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSInteger","kind":"identifier"}],"role":"symbol","title":"NSInteger","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"7.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"7.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"beta":false,"unavailable":false,"deprecated":false,"name":"tvOS"},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration"},{"op":"replace","path":"/metadata/title","value":"NSGlyphProperty"},{"op":"replace","path":"/metadata/symbolKind","value":"enum"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"NSGlyphProperty","kind":"identifier"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"text":"NSGlyphProperty","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]}},{"op":"replace","path":"/topicSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/null","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/controlCharacter","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/elastic","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/nonBaseCharacter"],"anchor":"Glyph-properties","title":"Glyph properties"}]},{"op":"replace","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/getGlyphs(in:glyphs:properties:characterIndexes:bidiLevels:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/cgGlyph(at:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/cgGlyph(at:isValidIndex:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/setGlyphs(_:properties:characterIndexes:font:forGlyphRange:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/characterIndexForGlyph(at:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/glyphIndexForCharacter(at:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/isValidGlyphIndex(_:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/numberOfGlyphs","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/propertyForGlyph(at:)"],"title":"Accessing glyphs","anchor":"Accessing-glyphs","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSGlyphProperty"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1characterIndexForGlyph(at:)/title","op":"replace","value":"characterIndexForGlyphAtIndex:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1characterIndexForGlyph(at:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"characterIndexForGlyphAtIndex:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1setGlyphs(_:properties:characterIndexes:font:forGlyphRange:)/title","op":"replace","value":"setGlyphs:properties:characterIndexes:font:forGlyphRange:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1setGlyphs(_:properties:characterIndexes:font:forGlyphRange:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setGlyphs:properties:characterIndexes:font:forGlyphRange:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/title","op":"replace","value":"NSLayoutManager"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutManager"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/navigatorTitle","op":"replace","value":[{"text":"NSLayoutManager","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1controlCharacter/title","op":"replace","value":"NSGlyphPropertyControlCharacter"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1controlCharacter/fragments","op":"replace","value":[{"text":"NSGlyphPropertyControlCharacter","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty/title","op":"replace","value":"NSGlyphProperty"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty/fragments","op":"replace","value":[{"kind":"identifier","text":"NSGlyphProperty"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty/navigatorTitle","op":"replace","value":[{"text":"NSGlyphProperty","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1isValidGlyphIndex(_:)/title","op":"replace","value":"isValidGlyphIndex:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1isValidGlyphIndex(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isValidGlyphIndex:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1numberOfGlyphs/title","op":"replace","value":"numberOfGlyphs"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1numberOfGlyphs/fragments","op":"replace","value":[{"kind":"identifier","text":"numberOfGlyphs"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1null/title","op":"replace","value":"NSGlyphPropertyNull"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1null/fragments","op":"replace","value":[{"kind":"identifier","text":"NSGlyphPropertyNull"}]},{"value":"CGGlyphAtIndex:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1cgGlyph(at:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"CGGlyphAtIndex:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1cgGlyph(at:)/fragments"},{"value":"CGGlyphAtIndex:isValidIndex:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1cgGlyph(at:isValidIndex:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"CGGlyphAtIndex:isValidIndex:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1cgGlyph(at:isValidIndex:)/fragments"},{"value":"glyphIndexForCharacterAtIndex:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1glyphIndexForCharacter(at:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"glyphIndexForCharacterAtIndex:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1glyphIndexForCharacter(at:)/fragments"},{"value":"getGlyphsInRange:glyphs:properties:characterIndexes:bidiLevels:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1getGlyphs(in:glyphs:properties:characterIndexes:bidiLevels:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGlyphsInRange:glyphs:properties:characterIndexes:bidiLevels:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1getGlyphs(in:glyphs:properties:characterIndexes:bidiLevels:)/fragments"},{"value":"NSGlyphPropertyElastic","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1elastic/title"},{"value":[{"kind":"identifier","text":"NSGlyphPropertyElastic"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1elastic/fragments"},{"value":"NSGlyphPropertyNonBaseCharacter","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1nonBaseCharacter/title"},{"value":[{"text":"NSGlyphPropertyNonBaseCharacter","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1nonBaseCharacter/fragments"},{"value":"propertyForGlyphAtIndex:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1propertyForGlyph(at:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"propertyForGlyphAtIndex:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1propertyForGlyph(at:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}