{"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/usedRect(for:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Related-Documentation","identifiers":["doc://com.apple.documentation/documentation/AppKit/NSTextContainer/containerSize"],"title":"Related Documentation"},{"anchor":"Managing-the-text-containers","generated":true,"title":"Managing the text containers","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainers","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/addTextContainer(_:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/insertTextContainer(_:at:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/removeTextContainer(at:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/setTextContainer(_:forGlyphRange:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainerChangedGeometry(_:)","doc://com.apple.documentation/documentation/AppKit/NSLayoutManager/textContainerChangedTextView(_:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainer(forGlyphAt:effectiveRange:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainer(forGlyphAt:effectiveRange:withoutAdditionalLayout:)"]}],"sections":[],"abstract":[{"text":"Returns the bounding rectangle for the glyphs in the specified text container.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager"]]},"metadata":{"modules":[{"name":"UIKit"}],"title":"usedRect(for:)","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"usedRectForTextContainer:","kind":"identifier"}],"externalID":"c:objc(cs)NSLayoutManager(im)usedRectForTextContainer:","platforms":[{"beta":false,"introducedAt":"7.0","name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"7.0","name":"iPadOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"NSTextContainer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTextContainer"},{"text":") -> ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/NSTextContainer","text":"NSTextContainer","preciseIdentifier":"c:objc(cs)NSTextContainer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@S@CGRect","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Returns the text container’s currently used area, which determines the size that the view would need to be in order to display all the glyphs that are currently laid out in the container. This causes neither glyph generation nor layout.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Used rectangles are always in container coordinates."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/uikit/nslayoutmanager/usedrect(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/nslayoutmanager/usedrect(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.documentation/documentation/AppKit/NSLayoutManager/textContainerChangedTextView(_:)":{"title":"textContainerChangedTextView(_:)","url":"/documentation/AppKit/NSLayoutManager/textContainerChangedTextView(_:)","abstract":[{"text":"Updates the information necessary to manage text view objects for the specified text container.","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/AppKit/NSLayoutManager/textContainerChangedTextView(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textContainerChangedTextView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"container","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTextContainer","text":"NSTextContainer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainer(forGlyphAt:effectiveRange:withoutAdditionalLayout:)":{"kind":"symbol","abstract":[{"text":"Returns the text container that manages the layout for the specified glyph.","type":"text"}],"title":"textContainer(forGlyphAt:effectiveRange:withoutAdditionalLayout:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textContainer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forGlyphAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"effectiveRange","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRangePointer","text":"NSRangePointer","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"withoutAdditionalLayout","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTextContainer","text":"NSTextContainer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainer(forGlyphAt:effectiveRange:withoutAdditionalLayout:)","navigatorTitle":[{"text":"textContainerForGlyphAtIndex:effectiveRange:withoutAdditionalLayout:","kind":"identifier"}],"url":"/documentation/uikit/nslayoutmanager/textcontainer(forglyphat:effectiverange:withoutadditionallayout:)","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutManager","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that coordinates the layout and display of text characters."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager","role":"symbol","url":"/documentation/uikit/nslayoutmanager","kind":"symbol","navigatorTitle":[{"text":"NSLayoutManager","kind":"identifier"}],"type":"topic","title":"NSLayoutManager"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/usedRect(for:)":{"kind":"symbol","abstract":[{"text":"Returns the bounding rectangle for the glyphs in the specified text container.","type":"text"}],"title":"usedRect(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usedRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTextContainer","text":"NSTextContainer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/usedRect(for:)","navigatorTitle":[{"text":"usedRectForTextContainer:","kind":"identifier"}],"url":"/documentation/uikit/nslayoutmanager/usedrect(for:)","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/AppKit/NSTextContainer/containerSize":{"identifier":"doc://com.apple.documentation/documentation/AppKit/NSTextContainer/containerSize","abstract":[{"text":"The size of the text container’s bounding rectangle.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSSize","text":"NSSize","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"type":"topic","role":"symbol","url":"/documentation/AppKit/NSTextContainer/containerSize","title":"containerSize"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/addTextContainer(_:)":{"kind":"symbol","abstract":[{"text":"Appends the specified text container to the series of text containers where the layout manager arranges text.","type":"text"}],"title":"addTextContainer(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTextContainer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTextContainer","text":"NSTextContainer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/addTextContainer(_:)","navigatorTitle":[{"text":"addTextContainer:","kind":"identifier"}],"url":"/documentation/uikit/nslayoutmanager/addtextcontainer(_:)","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainerChangedGeometry(_:)":{"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainerChangedGeometry(_:)","role":"symbol","title":"textContainerChangedGeometry(_:)","url":"/documentation/uikit/nslayoutmanager/textcontainerchangedgeometry(_:)","navigatorTitle":[{"kind":"identifier","text":"textContainerChangedGeometry:"}],"abstract":[{"text":"Invalidates the layout information, and possibly glyphs, for the specified text container and all subsequent text container objects.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textContainerChangedGeometry"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTextContainer","text":"NSTextContainer"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/removeTextContainer(at:)":{"kind":"symbol","abstract":[{"text":"Removes the text container at the specified index and invalidates the layout as necessary.","type":"text"}],"title":"removeTextContainer(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeTextContainer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/removeTextContainer(at:)","navigatorTitle":[{"text":"removeTextContainerAtIndex:","kind":"identifier"}],"url":"/documentation/uikit/nslayoutmanager/removetextcontainer(at:)","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSTextContainer":{"url":"/documentation/uikit/nstextcontainer","identifier":"doc://com.apple.uikit/documentation/UIKit/NSTextContainer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSTextContainer"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSTextContainer"}],"type":"topic","title":"NSTextContainer","kind":"symbol","abstract":[{"type":"text","text":"A region where text layout occurs."}]},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainers":{"navigatorTitle":[{"text":"textContainers","kind":"identifier"}],"title":"textContainers","url":"/documentation/uikit/nslayoutmanager/textcontainers","abstract":[{"text":"The current text containers of the layout manager.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainers","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textContainers"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTextContainer","text":"NSTextContainer","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/setTextContainer(_:forGlyphRange:)":{"kind":"symbol","abstract":[{"text":"Associates a text container with the specified range of glyphs.","type":"text"}],"title":"setTextContainer(_:forGlyphRange:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTextContainer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTextContainer","text":"NSTextContainer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forGlyphRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/setTextContainer(_:forGlyphRange:)","navigatorTitle":[{"text":"setTextContainer:forGlyphRange:","kind":"identifier"}],"url":"/documentation/uikit/nslayoutmanager/settextcontainer(_:forglyphrange:)","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainer(forGlyphAt:effectiveRange:)":{"kind":"symbol","abstract":[{"text":"Returns the text container that manages the layout for the specified glyph, causing layout to happen as necessary.","type":"text"}],"title":"textContainer(forGlyphAt:effectiveRange:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textContainer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forGlyphAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"effectiveRange","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRangePointer","text":"NSRangePointer","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTextContainer","text":"NSTextContainer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainer(forGlyphAt:effectiveRange:)","navigatorTitle":[{"text":"textContainerForGlyphAtIndex:effectiveRange:","kind":"identifier"}],"url":"/documentation/uikit/nslayoutmanager/textcontainer(forglyphat:effectiverange:)","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/insertTextContainer(_:at:)":{"navigatorTitle":[{"text":"insertTextContainer:atIndex:","kind":"identifier"}],"title":"insertTextContainer(_:at:)","url":"/documentation/uikit/nslayoutmanager/inserttextcontainer(_:at:)","abstract":[{"text":"Inserts a text container at the specified index in the list of text containers.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/insertTextContainer(_:at:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertTextContainer"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTextContainer","text":"NSTextContainer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:@S@CGRect":{"identifier":"doc://com.externally.resolved.symbol/c:@S@CGRect","abstract":[{"text":"A structure that contains the location and dimensions of a rectangle.","type":"text"}],"title":"CGRect","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGRect"}],"role":"symbol","url":"/documentation/corefoundation/cgrect","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"7.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"introducedAt":"7.0","unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"introducedAt":"13.1","unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"usedRectForTextContainer:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"usedRectForTextContainer:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.documentation/documentation/AppKit/NSTextContainer/containerSize"]},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainers","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/addTextContainer(_:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/insertTextContainer(_:at:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/removeTextContainer(at:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/setTextContainer(_:forGlyphRange:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainerChangedGeometry(_:)","doc://com.apple.documentation/documentation/AppKit/NSLayoutManager/textContainerChangedTextView(_:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainer(forGlyphAt:effectiveRange:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/textContainer(forGlyphAt:effectiveRange:withoutAdditionalLayout:)"],"title":"Managing the text containers","generated":true,"anchor":"Managing-the-text-containers"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@S@CGRect","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"identifier","text":"usedRectForTextContainer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/NSTextContainer","text":"NSTextContainer","preciseIdentifier":"c:objc(cs)NSTextContainer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"container"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSLayoutManager~1textContainerChangedTextView(_:)/title","value":"textContainerChangedTextView:","op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSLayoutManager~1textContainerChangedTextView(_:)/fragments","value":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"textContainerChangedTextView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTextContainer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTextContainer"},{"text":" *) ","kind":"text"},{"text":"container","kind":"internalParam"},{"text":";","kind":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1textContainer(forGlyphAt:effectiveRange:withoutAdditionalLayout:)/title","value":"textContainerForGlyphAtIndex:effectiveRange:withoutAdditionalLayout:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1textContainer(forGlyphAt:effectiveRange:withoutAdditionalLayout:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"textContainerForGlyphAtIndex:effectiveRange:withoutAdditionalLayout:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/title","value":"NSLayoutManager","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/fragments","value":[{"kind":"identifier","text":"NSLayoutManager"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/navigatorTitle","value":[{"text":"NSLayoutManager","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1usedRect(for:)/title","value":"usedRectForTextContainer:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1usedRect(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"usedRectForTextContainer:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTextContainer~1containerSize/fragments","value":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSSize","preciseIdentifier":"c:@T@NSSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerSize"},{"kind":"text","text":";"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1addTextContainer(_:)/title","value":"addTextContainer:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1addTextContainer(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTextContainer:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1textContainerChangedGeometry(_:)/title","value":"textContainerChangedGeometry:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1textContainerChangedGeometry(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"textContainerChangedGeometry:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1removeTextContainer(at:)/title","value":"removeTextContainerAtIndex:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1removeTextContainer(at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeTextContainerAtIndex:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer/title","value":"NSTextContainer","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer/fragments","value":[{"text":"NSTextContainer","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer/navigatorTitle","value":[{"text":"NSTextContainer","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1textContainers/title","value":"textContainers","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1textContainers/fragments","value":[{"text":"textContainers","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1setTextContainer(_:forGlyphRange:)/title","value":"setTextContainer:forGlyphRange:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1setTextContainer(_:forGlyphRange:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setTextContainer:forGlyphRange:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1textContainer(forGlyphAt:effectiveRange:)/title","value":"textContainerForGlyphAtIndex:effectiveRange:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1textContainer(forGlyphAt:effectiveRange:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textContainerForGlyphAtIndex:effectiveRange:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1insertTextContainer(_:at:)/title","value":"insertTextContainer:atIndex:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1insertTextContainer(_:at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertTextContainer:atIndex:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}