{"identifier":{"url":"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserDidFinish(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","seeAlsoSections":[{"anchor":"Selecting-Calendars","generated":true,"title":"Selecting Calendars","identifiers":["doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserSelectionDidChange(_:)","doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserDidCancel(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Sent when a user selects one or more calendars.","type":"text"}],"variants":[{"paths":["/documentation/eventkitui/ekcalendarchooserdelegate/calendarchooserdidfinish(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/eventkitui/ekcalendarchooserdelegate/calendarchooserdidfinish(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calendarChooserDidFinish"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)EKCalendarChooser","kind":"typeIdentifier","text":"EKCalendarChooser"},{"kind":"text","text":")"}],"title":"calendarChooserDidFinish(_:)","platforms":[{"introducedAt":"4.0","beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"introducedAt":"4.0","beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"introducedAt":"13.0","beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"1.0","beta":false,"deprecated":false,"name":"visionOS","unavailable":false}],"modules":[{"name":"EventKit UI"}],"externalID":"c:objc(pl)EKCalendarChooserDelegate(im)calendarChooserDidFinish:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"calendarChooserDidFinish:"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.eventkitui/documentation/EventKitUI","doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calendarChooserDidFinish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"calendarChooser","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser","text":"EKCalendarChooser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EKCalendarChooser"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"calendarChooser","content":[{"inlineContent":[{"text":"The calendar chooser that sent this message.","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserDidCancel(_:)":{"identifier":"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserDidCancel(_:)","role":"symbol","title":"calendarChooserDidCancel(_:)","navigatorTitle":[{"text":"calendarChooserDidCancel:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calendarChooserDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EKCalendarChooser","preciseIdentifier":"c:objc(cs)EKCalendarChooser","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/eventkitui/ekcalendarchooserdelegate/calendarchooserdidcancel(_:)","kind":"symbol","type":"topic","abstract":[{"text":"Sent when the user cancels a calendar selection.","type":"text"}]},"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate":{"identifier":"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate","role":"symbol","title":"EKCalendarChooserDelegate","navigatorTitle":[{"kind":"identifier","text":"EKCalendarChooserDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EKCalendarChooserDelegate"}],"url":"/documentation/eventkitui/ekcalendarchooserdelegate","kind":"symbol","type":"topic","abstract":[{"text":"Methods a calendar chooser’s delegate may use to receive notifications.","type":"text"}]},"doc://com.apple.eventkitui/documentation/EventKitUI":{"title":"EventKit UI","url":"/documentation/eventkitui","kind":"symbol","abstract":[{"text":"Display an interface for viewing, selecting, and editing calendar events and reminders.","type":"text"}],"role":"collection","type":"topic","identifier":"doc://com.apple.eventkitui/documentation/EventKitUI"},"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EKCalendarChooser"}],"title":"EKCalendarChooser","abstract":[{"text":"A view controller for determining whether a user may select one or more calendars.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EKCalendarChooser"}],"identifier":"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser","url":"/documentation/eventkitui/ekcalendarchooser"},"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserDidFinish(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"calendarChooserDidFinish:"}],"title":"calendarChooserDidFinish(_:)","abstract":[{"text":"Sent when a user selects one or more calendars.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calendarChooserDidFinish"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)EKCalendarChooser","kind":"typeIdentifier","text":"EKCalendarChooser"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserDidFinish(_:)","url":"/documentation/eventkitui/ekcalendarchooserdelegate/calendarchooserdidfinish(_:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","title":"Technologies","url":"/documentation/technologies","kind":"technologies","type":"topic","abstract":[{"text":"","type":"text"}]},"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserSelectionDidChange(_:)":{"identifier":"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserSelectionDidChange(_:)","role":"symbol","title":"calendarChooserSelectionDidChange(_:)","navigatorTitle":[{"text":"calendarChooserSelectionDidChange:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calendarChooserSelectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EKCalendarChooser","preciseIdentifier":"c:objc(cs)EKCalendarChooser","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/eventkitui/ekcalendarchooserdelegate/calendarchooserselectiondidchange(_:)","kind":"symbol","type":"topic","abstract":[{"text":"Sent when a user changes the selection.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","deprecated":false,"introducedAt":"4.0","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"4.0","beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.0","beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"calendarChooserDidFinish:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"calendarChooserDidFinish:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.eventkitui/documentation/EventKitUI","doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"op":"replace","value":[{"anchor":"Selecting-Calendars","title":"Selecting Calendars","generated":true,"identifiers":["doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserSelectionDidChange(_:)","doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDelegate/calendarChooserDidCancel(_:)"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"calendarChooserDidFinish:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EKCalendarChooser","kind":"typeIdentifier","identifier":"doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser","preciseIdentifier":"c:objc(cs)EKCalendarChooser"},{"text":" *) ","kind":"text"},{"text":"calendarChooser","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The calendar chooser that sent this message.","type":"text"}],"type":"paragraph"}],"name":"calendarChooser"}]},"path":"/primaryContentSections/1","op":"replace"},{"op":"replace","value":"calendarChooserDidCancel:","path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDelegate~1calendarChooserDidCancel(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"calendarChooserDidCancel:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDelegate~1calendarChooserDidCancel(_:)/fragments"},{"op":"replace","value":"EKCalendarChooserDelegate","path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDelegate/title"},{"op":"replace","value":[{"kind":"identifier","text":"EKCalendarChooserDelegate"}],"path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDelegate/fragments"},{"op":"replace","value":[{"text":"EKCalendarChooserDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDelegate/navigatorTitle"},{"op":"replace","value":"EKCalendarChooser","path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser/title"},{"op":"replace","value":[{"kind":"identifier","text":"EKCalendarChooser"}],"path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"EKCalendarChooser"}],"path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser/navigatorTitle"},{"op":"replace","value":"calendarChooserDidFinish:","path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDelegate~1calendarChooserDidFinish(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calendarChooserDidFinish:"}],"path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDelegate~1calendarChooserDidFinish(_:)/fragments"},{"op":"replace","value":"calendarChooserSelectionDidChange:","path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDelegate~1calendarChooserSelectionDidChange(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"calendarChooserSelectionDidChange:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDelegate~1calendarChooserSelectionDidChange(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}