{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/init(rawValue:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So39NINearbyObjectVerticalDirectionEstimateV8rawValueABSgSi_tcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "rawValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(rawValue:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "rawValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject": {
      "abstract": [
        {
          "text": "Location information for a peer device in an interaction session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NINearbyObject"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NINearbyObject"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum": {
      "abstract": [
        {
          "text": "Estimations of a nearby object’s vertical position in relation to the user’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VerticalDirectionEstimate"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VerticalDirectionEstimate"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject.VerticalDirectionEstimate",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject/title",
          "value": "NINearbyObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum/title",
          "value": "NINearbyObjectVerticalDirectionEstimate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum/init(rawvalue:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
