{
  "abstract": [
    {
      "text": "An indication that the nearby object resides at an equivalent vertical location as the user’s device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/same"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NINearbyObjectVerticalDirectionEstimate@NINearbyObjectVerticalDirectionEstimateSame",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "same"
      }
    ],
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NINearbyObjectVerticalDirectionEstimateSame"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NINearbyObject.VerticalDirectionEstimate.same"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "same"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject": {
      "abstract": [
        {
          "text": "Location information for a peer device in an interaction session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NINearbyObject"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NINearbyObject"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum": {
      "abstract": [
        {
          "text": "Estimations of a nearby object’s vertical position in relation to the user’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VerticalDirectionEstimate"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VerticalDirectionEstimate"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject.VerticalDirectionEstimate",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/above": {
      "abstract": [
        {
          "text": "An indication that the nearby object resides at a higher vertical location than the user’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "above"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/above",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NINearbyObjectVerticalDirectionEstimateAbove"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject.VerticalDirectionEstimate.above",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum/above"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/aboveOrBelow": {
      "abstract": [
        {
          "text": "An indication that the nearby object doesn’t reside at the same vertical location as the user’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aboveOrBelow"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/aboveOrBelow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NINearbyObjectVerticalDirectionEstimateAboveOrBelow"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject.VerticalDirectionEstimate.aboveOrBelow",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum/aboveorbelow"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/below": {
      "abstract": [
        {
          "text": "An indication that the nearby object resides at a lower vertical location than the user’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "below"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/below",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NINearbyObjectVerticalDirectionEstimateBelow"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject.VerticalDirectionEstimate.below",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum/below"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/same": {
      "abstract": [
        {
          "text": "An indication that the nearby object resides at an equivalent vertical location as the user’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "same"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/same",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NINearbyObjectVerticalDirectionEstimateSame"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject.VerticalDirectionEstimate.same",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum/same"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/unknown": {
      "abstract": [
        {
          "text": "An indication that the nearby object resides at an unknown vertical location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NINearbyObjectVerticalDirectionEstimateUnknown"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject.VerticalDirectionEstimate.unknown",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Relative-vertical-location",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/unknown",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/above",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/below",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/aboveOrBelow"
      ],
      "title": "Relative vertical location"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NINearbyObjectVerticalDirectionEstimateSame"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimateSame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Relative-vertical-location",
              "generated": true,
              "identifiers": [
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/unknown",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/above",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/below",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum/aboveOrBelow"
              ],
              "title": "Relative vertical location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NINearbyObjectVerticalDirectionEstimateSame"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum~1below/title",
          "value": "NINearbyObjectVerticalDirectionEstimateBelow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum~1below/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimateBelow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject/title",
          "value": "NINearbyObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum~1aboveOrBelow/title",
          "value": "NINearbyObjectVerticalDirectionEstimateAboveOrBelow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum~1aboveOrBelow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimateAboveOrBelow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum~1unknown/title",
          "value": "NINearbyObjectVerticalDirectionEstimateUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimateUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum/title",
          "value": "NINearbyObjectVerticalDirectionEstimate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum~1same/title",
          "value": "NINearbyObjectVerticalDirectionEstimateSame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum~1same/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimateSame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum~1above/title",
          "value": "NINearbyObjectVerticalDirectionEstimateAbove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum~1above/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimateAbove"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum/same"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum/same"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
