{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskunmountoptions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskmountoptions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskmountoptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/diskarbitration/anonymous-kdadiskmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskoptions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskoptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/diskarbitration/anonymous-kdadiskoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Enumerations",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-enumerations"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskUnmountOptionDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskUnmountOptionDefault"
        }
      ],
      "role": "symbol",
      "title": "kDADiskUnmountOptionDefault",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskunmountoptiondefault"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionForce": {
      "abstract": [
        {
          "text": "Unmount the volume even if files are still active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskUnmountOptionForce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionForce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskUnmountOptionForce"
        }
      ],
      "role": "symbol",
      "title": "kDADiskUnmountOptionForce",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskunmountoptionforce"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionWhole": {
      "abstract": [
        {
          "text": "Unmount the volumes tied to the whole disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskUnmountOptionWhole"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionWhole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskUnmountOptionWhole"
        }
      ],
      "role": "symbol",
      "title": "kDADiskUnmountOptionWhole",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskunmountoptionwhole"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskmountoptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskoptions"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionDefault",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionForce",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionWhole"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionDefault",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionForce",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskUnmountOptionWhole"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskmountoptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskoptions"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskUnmountOptionDefault/title",
          "value": "kDADiskUnmountOptionDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskUnmountOptionDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskUnmountOptionDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskUnmountOptionWhole/title",
          "value": "kDADiskUnmountOptionWhole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskUnmountOptionWhole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskUnmountOptionWhole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskUnmountOptionForce/title",
          "value": "kDADiskUnmountOptionForce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskUnmountOptionForce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskUnmountOptionForce"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/anonymous-kdadiskunmountoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/anonymous-kdadiskunmountoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
