{
  "abstract": [
    {
      "text": "Type of the callback function used by DARegisterDiskDisappearedCallback().",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDisappearedCallback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@DADiskDisappearedCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DADiskDisappearedCallback"
      }
    ],
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DADiskDisappearedCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "DADiskDisappearedCallback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DADiskDisappearedCallback"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADisk",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DADiskRef",
              "text": "DADisk"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A disk object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "disk"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The user-defined context parameter given to the registration function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADisk": {
      "abstract": [
        {
          "text": "Type of a reference to DADisk instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADisk"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADisk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADisk"
        }
      ],
      "role": "symbol",
      "title": "DADisk",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadisk"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskAppearedCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskAppearedCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskAppearedCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskAppearedCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskAppearedCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskAppearedCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskappearedcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskClaim().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskClaimCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskClaimCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskClaimCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskclaimcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimReleaseCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskClaim().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskClaimReleaseCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimReleaseCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskClaimReleaseCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskClaimReleaseCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskclaimreleasecallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDescriptionChangedCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskDescriptionChangedCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskDescriptionChangedCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDescriptionChangedCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskDescriptionChangedCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskDescriptionChangedCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskdescriptionchangedcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDisappearedCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskDisappearedCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskDisappearedCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDisappearedCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskDisappearedCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskDisappearedCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskdisappearedcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectApprovalCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskEjectApprovalCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskEjectApprovalCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectApprovalCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskEjectApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskEjectApprovalCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskejectapprovalcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskEject().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskEjectCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskEjectCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskEjectCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskejectcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskMountApprovalCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountApprovalCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountApprovalCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountapprovalcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskMount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskPeekCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskPeekCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskPeekCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskPeekCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskPeekCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskPeekCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskpeekcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskRename().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskRenameCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskRenameCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskRenameCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskrenamecallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountApprovalCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskUnmountApprovalCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnmountApprovalCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountApprovalCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnmountApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnmountApprovalCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunmountapprovalcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskUnmount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnmountCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnmountCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnmountCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunmountcallback"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Callbacks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskAppearedCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimReleaseCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDescriptionChangedCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectApprovalCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskPeekCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountApprovalCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountCallback"
      ],
      "title": "Callbacks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DADiskDisappearedCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskDisappearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskDisappearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Callbacks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskAppearedCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimReleaseCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDescriptionChangedCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectApprovalCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskPeekCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountApprovalCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountCallback"
              ],
              "title": "Callbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fv(#*$@S@__DADisk#*v)",
                    "text": "void (*)(struct __DADisk *, void *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DADiskDisappearedCallback"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountApprovalCallback/title",
          "value": "DADiskMountApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountApprovalCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountApprovalCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskPeekCallback/title",
          "value": "DADiskPeekCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskPeekCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskPeekCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskPeekCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskPeekCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountApprovalCallback/title",
          "value": "DADiskUnmountApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountApprovalCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountApprovalCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectCallback/title",
          "value": "DADiskEjectCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEjectCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEjectCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameCallback/title",
          "value": "DADiskRenameCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimReleaseCallback/title",
          "value": "DADiskClaimReleaseCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimReleaseCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaimReleaseCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimReleaseCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaimReleaseCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountCallback/title",
          "value": "DADiskUnmountCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDisappearedCallback/title",
          "value": "DADiskDisappearedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDisappearedCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskDisappearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDisappearedCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskDisappearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimCallback/title",
          "value": "DADiskClaimCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaimCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaimCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskAppearedCallback/title",
          "value": "DADiskAppearedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskAppearedCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskAppearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskAppearedCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskAppearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectApprovalCallback/title",
          "value": "DADiskEjectApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectApprovalCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEjectApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectApprovalCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEjectApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountCallback/title",
          "value": "DADiskMountCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDescriptionChangedCallback/title",
          "value": "DADiskDescriptionChangedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDescriptionChangedCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskDescriptionChangedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDescriptionChangedCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskDescriptionChangedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADisk/title",
          "value": "DADiskRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADisk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADisk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/dadiskdisappearedcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/dadiskdisappearedcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
