{
  "abstract": [
    {
      "text": "Obtains the BSD device name for the specified disk.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetBSDName(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@DADiskGetBSDName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DADiskGetBSDName"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DADiskRef",
        "text": "DADisk"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5CChara",
        "text": "CChar"
      },
      {
        "kind": "text",
        "text": ">?"
      }
    ],
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DADiskGetBSDName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "DADiskGetBSDName(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DADiskGetBSDName"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "disk"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADisk",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DADiskRef",
              "text": "DADisk"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The DADisk for which to obtain the BSD device name.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "disk"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The disk’s BSD device name.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The BSD device name can be used with opendev() to open the BSD device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADisk": {
      "abstract": [
        {
          "text": "Type of a reference to DADisk instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADisk"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADisk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADisk"
        }
      ],
      "role": "symbol",
      "title": "DADisk",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadisk"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyDescription(_:)": {
      "abstract": [
        {
          "text": "Obtains the Disk Arbitration description of the specified disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskCopyDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyDescription(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskCopyDescription"
        }
      ],
      "role": "symbol",
      "title": "DADiskCopyDescription(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskcopydescription(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyIOMedia(_:)": {
      "abstract": [
        {
          "text": "Obtains the I/O Kit media object for the specified disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskCopyIOMedia"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@io_service_t",
          "text": "io_service_t"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyIOMedia(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskCopyIOMedia"
        }
      ],
      "role": "symbol",
      "title": "DADiskCopyIOMedia(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskcopyiomedia(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyWholeDisk(_:)": {
      "abstract": [
        {
          "text": "Obtain the associated whole disk object for the specified disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskCopyWholeDisk"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyWholeDisk(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskCopyWholeDisk"
        }
      ],
      "role": "symbol",
      "title": "DADiskCopyWholeDisk(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskcopywholedisk(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromBSDName(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskCreateFromBSDName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromBSDName(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskCreateFromBSDName"
        }
      ],
      "role": "symbol",
      "title": "DADiskCreateFromBSDName(_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskcreatefrombsdname(_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromIOMedia(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskCreateFromIOMedia"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@io_service_t",
          "text": "io_service_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromIOMedia(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskCreateFromIOMedia"
        }
      ],
      "role": "symbol",
      "title": "DADiskCreateFromIOMedia(_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskcreatefromiomedia(_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromVolumePath(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskCreateFromVolumePath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromVolumePath(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskCreateFromVolumePath"
        }
      ],
      "role": "symbol",
      "title": "DADiskCreateFromVolumePath(_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskcreatefromvolumepath(_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetBSDName(_:)": {
      "abstract": [
        {
          "text": "Obtains the BSD device name for the specified disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskGetBSDName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetBSDName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskGetBSDName"
        }
      ],
      "role": "symbol",
      "title": "DADiskGetBSDName(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskgetbsdname(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the type identifier of all DADisk instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "DADiskGetTypeID()",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskgettypeid()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C ‘char’ type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyDescription(_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyIOMedia(_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyWholeDisk(_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromBSDName(_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromIOMedia(_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromVolumePath(_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetTypeID()"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DADiskGetBSDName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskGetBSDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyDescription(_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyIOMedia(_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCopyWholeDisk(_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromBSDName(_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromIOMedia(_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskCreateFromVolumePath(_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetTypeID()"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:C",
                    "text": "char"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "DADiskGetBSDName"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADisk",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DADiskRef",
                    "text": "DADiskRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "disk"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The DADisk for which to obtain the BSD device name.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "disk"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The disk’s BSD device name.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskGetTypeID()/title",
          "value": "DADiskGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCopyDescription(_:)/title",
          "value": "DADiskCopyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCopyDescription(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskCopyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCopyWholeDisk(_:)/title",
          "value": "DADiskCopyWholeDisk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCopyWholeDisk(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskCopyWholeDisk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADisk/title",
          "value": "DADiskRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADisk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADisk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCreateFromVolumePath(_:_:_:)/title",
          "value": "DADiskCreateFromVolumePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCreateFromVolumePath(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskCreateFromVolumePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCreateFromIOMedia(_:_:_:)/title",
          "value": "DADiskCreateFromIOMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCreateFromIOMedia(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskCreateFromIOMedia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCopyIOMedia(_:)/title",
          "value": "DADiskCopyIOMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCopyIOMedia(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskCopyIOMedia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCreateFromBSDName(_:_:_:)/title",
          "value": "DADiskCreateFromBSDName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskCreateFromBSDName(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskCreateFromBSDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskGetBSDName(_:)/title",
          "value": "DADiskGetBSDName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskGetBSDName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskGetBSDName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/dadiskgetbsdname(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/dadiskgetbsdname(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
