{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DADissenter.h"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See the Overview section above for header-level documentation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "anchor": "Included-Headers",
          "level": 3,
          "text": "Included Headers",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<mach/error.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<CoreFoundation/CoreFoundation.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenter": {
      "abstract": [
        {
          "text": "Type of a reference to DADissenter instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADissenter"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADissenter"
        }
      ],
      "role": "symbol",
      "title": "DADissenter",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadissenter"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterCreate(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new dissenter object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADissenterCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DAReturn",
          "text": "DAReturn"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADissenterRef",
          "text": "DADissenter"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterCreate(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADissenterCreate"
        }
      ],
      "role": "symbol",
      "title": "DADissenterCreate(_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadissentercreate(_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterGetStatus(_:)": {
      "abstract": [
        {
          "text": "Obtains the return code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADissenterGetStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADissenterRef",
          "text": "DADissenter"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DAReturn",
          "text": "DAReturn"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterGetStatus(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADissenterGetStatus"
        }
      ],
      "role": "symbol",
      "title": "DADissenterGetStatus(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadissentergetstatus(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterGetStatusString(_:)": {
      "abstract": [
        {
          "text": "Obtains the return code string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADissenterGetStatusString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADissenterRef",
          "text": "DADissenter"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterGetStatusString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADissenterGetStatusString"
        }
      ],
      "role": "symbol",
      "title": "DADissenterGetStatusString(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadissentergetstatusstring(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADisk.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadisk-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DASession.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dasession-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Constants",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-constants"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Data Types",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-data-types"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Enumerations",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-enumerations"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Functions",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-functions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h": {
      "abstract": [
        {
          "text": "Register for mount/unmount notifications, and block mount/unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-h"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Miscellaneous",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterCreate(_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterGetStatus(_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterGetStatusString(_:)"
      ],
      "title": "Miscellaneous"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenter"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterCreate(_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterGetStatus(_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenterGetStatusString(_:)"
              ],
              "title": "Miscellaneous"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADissenter"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADissenterGetStatus(_:)/title",
          "value": "DADissenterGetStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADissenterGetStatus(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADissenterGetStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADissenter/title",
          "value": "DADissenterRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADissenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADissenterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADissenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADissenterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADissenterCreate(_:_:_:)/title",
          "value": "DADissenterCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADissenterCreate(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADissenterCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADissenterGetStatusString(_:)/title",
          "value": "DADissenterGetStatusString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADissenterGetStatusString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADissenterGetStatusString"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/dadissenter-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/dadissenter-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
