{
  "abstract": [
    {
      "text": "Options for DADiskClaim().",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskclaimoptions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DADiskClaimOptions"
  },
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions": {
      "abstract": [
        {
          "text": "Options for DADiskMount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions": {
      "abstract": [
        {
          "text": "Options for DADiskRename().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskRenameOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskRenameOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskRenameOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskrenameoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions": {
      "abstract": [
        {
          "text": "Options for DADiskUnmount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnmountOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnmountOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnmountOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions": {
      "abstract": [
        {
          "text": "Options for DADiskEject().",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADiskEjectOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskejectoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h": {
      "abstract": [
        {
          "text": "Register for mount/unmount notifications, and block mount/unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/global-variables": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/global-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Global Variables",
      "type": "topic",
      "url": "/documentation/diskarbitration/global-variables"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskClaimOptionDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskClaimOptionDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskClaimOptionDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskClaimOptionDefault"
        }
      ],
      "role": "symbol",
      "title": "kDADiskClaimOptionDefault",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskclaimoptiondefault"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/global-variables",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskClaimOptionDefault"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskClaimOptionDefault"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/global-variables",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/title",
          "value": "DADiskRenameOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/title",
          "value": "DADiskUnmountOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskClaimOptionDefault/title",
          "value": "kDADiskClaimOptionDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskClaimOptionDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskClaimOptionDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/title",
          "value": "DADiskMountOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/dadiskclaimoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/dadiskclaimoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
