{
  "abstract": [
    {
      "text": "Registers a callback function to be called whenever a volume is to be mounted.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskMountApprovalCallback(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@DARegisterDiskMountApprovalCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DARegisterDiskMountApprovalCallback"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DASessionRef",
        "text": "DASession"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DADiskMountApprovalCallback",
        "text": "DADiskMountApprovalCallback"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DARegisterDiskMountApprovalCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "DARegisterDiskMountApprovalCallback(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DARegisterDiskMountApprovalCallback"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DASession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DASessionRef",
              "text": "DASession"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "match"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "callback"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DADiskMountApprovalCallback",
              "text": "DADiskMountApprovalCallback"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The session object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The disk description keys to match. Pass NULL for all disk objects.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "match"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The callback function to call when a volume is to be mounted.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "callback"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The user-defined context parameter to pass to the callback function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaim(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Claims the specified disk object for exclusive use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskClaim"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskClaimOptions",
          "text": "DADiskClaimOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskClaimReleaseCallback",
          "text": "DADiskClaimReleaseCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskClaimCallback",
          "text": "DADiskClaimCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaim(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskClaim"
        }
      ],
      "role": "symbol",
      "title": "DADiskClaim(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskclaim(_:_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEject(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Ejects the specified disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskEject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskEjectOptions",
          "text": "DADiskEjectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskEjectCallback",
          "text": "DADiskEjectCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEject(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskEject"
        }
      ],
      "role": "symbol",
      "title": "DADiskEject(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskeject(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetOptions(_:)": {
      "abstract": [
        {
          "text": "Obtains the options for the specified disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskGetOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskOptions",
          "text": "DADiskOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskGetOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskGetOptions(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskgetoptions(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskIsClaimed(_:)": {
      "abstract": [
        {
          "text": "Reports whether or not the disk is claimed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskIsClaimed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskIsClaimed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskIsClaimed"
        }
      ],
      "role": "symbol",
      "title": "DADiskIsClaimed(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskisclaimed(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMount(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Mounts the volume at the specified disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskMountOptions",
          "text": "DADiskMountOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskMountCallback",
          "text": "DADiskMountCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMount(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMount"
        }
      ],
      "role": "symbol",
      "title": "DADiskMount(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmount(_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskMountApprovalCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountApprovalCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountApprovalCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountapprovalcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountWithArguments(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Mounts the volume at the specified disk object, with the specified mount options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountWithArguments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskMountOptions",
          "text": "DADiskMountOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskMountCallback",
          "text": "DADiskMountCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?>?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountWithArguments(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountWithArguments"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountWithArguments(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountwitharguments(_:_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRename(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Renames the volume at the specified disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskRename"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRenameOptions",
          "text": "DADiskRenameOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRenameCallback",
          "text": "DADiskRenameCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRename(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskRename"
        }
      ],
      "role": "symbol",
      "title": "DADiskRename(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskrename(_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskSetOptions(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the options for the specified disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskSetOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskOptions",
          "text": "DADiskOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DAReturn",
          "text": "DAReturn"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskSetOptions(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskSetOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskSetOptions(_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadisksetoptions(_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnclaim(_:)": {
      "abstract": [
        {
          "text": "Unclaims the specified disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnclaim"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnclaim(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnclaim"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnclaim(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunclaim(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmount(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Unmounts the volume at the specified disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnmount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskUnmountOptions",
          "text": "DADiskUnmountOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskUnmountCallback",
          "text": "DADiskUnmountCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmount(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnmount"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnmount(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunmount(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskAppearedCallback(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a disk has appeared.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskAppearedCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskAppearedCallback",
          "text": "DADiskAppearedCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskAppearedCallback(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskAppearedCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskAppearedCallback(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskappearedcallback(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a disk description has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskDescriptionChangedCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskDescriptionChangedCallback",
          "text": "DADiskDescriptionChangedCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskDescriptionChangedCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskdescriptionchangedcallback(_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDisappearedCallback(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a disk has disappeared.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskDisappearedCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskDisappearedCallback",
          "text": "DADiskDisappearedCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDisappearedCallback(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskDisappearedCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskDisappearedCallback(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskdisappearedcallback(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskEjectApprovalCallback(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a volume is to be ejected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskEjectApprovalCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskEjectApprovalCallback",
          "text": "DADiskEjectApprovalCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskEjectApprovalCallback(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskEjectApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskEjectApprovalCallback(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskejectapprovalcallback(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskMountApprovalCallback(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a volume is to be mounted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskMountApprovalCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskMountApprovalCallback",
          "text": "DADiskMountApprovalCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskMountApprovalCallback(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskMountApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskMountApprovalCallback(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskmountapprovalcallback(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskPeekCallback(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a disk has been probed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskPeekCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskPeekCallback",
          "text": "DADiskPeekCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskPeekCallback(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskPeekCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskPeekCallback(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskpeekcallback(_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DASession": {
      "abstract": [
        {
          "text": "Type of a reference to DASession instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DASession"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DASession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DASession"
        }
      ],
      "role": "symbol",
      "title": "DASession",
      "type": "topic",
      "url": "/documentation/diskarbitration/dasession"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaim(_:_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEject(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetOptions(_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskIsClaimed(_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMount(_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountWithArguments(_:_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRename(_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskSetOptions(_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnclaim(_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmount(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskAppearedCallback(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDisappearedCallback(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskEjectApprovalCallback(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskPeekCallback(_:_:_:_:_:)"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DARegisterDiskMountApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskMountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaim(_:_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEject(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetOptions(_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskIsClaimed(_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMount(_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountWithArguments(_:_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRename(_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskSetOptions(_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnclaim(_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmount(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskAppearedCallback(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDisappearedCallback(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskEjectApprovalCallback(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskPeekCallback(_:_:_:_:_:)"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DARegisterDiskMountApprovalCallback"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DASession",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DASessionRef",
                    "text": "DASessionRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "session"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "match"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DADiskMountApprovalCallback",
                    "text": "DADiskMountApprovalCallback"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "callback"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "context"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The session object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "session"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The disk description keys to match. Pass NULL for all disk objects.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "match"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The callback function to call when a volume is to be mounted.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "callback"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The user-defined context parameter to pass to the callback function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "context"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountApprovalCallback/title",
          "value": "DADiskMountApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountApprovalCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountApprovalCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountWithArguments(_:_:_:_:_:_:)/title",
          "value": "DADiskMountWithArguments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountWithArguments(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountWithArguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRename(_:_:_:_:_:)/title",
          "value": "DADiskRename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRename(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRename"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskSetOptions(_:_:_:)/title",
          "value": "DADiskSetOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskSetOptions(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskSetOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskMountApprovalCallback(_:_:_:_:)/title",
          "value": "DARegisterDiskMountApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskMountApprovalCallback(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskMountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnclaim(_:)/title",
          "value": "DADiskUnclaim"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnclaim(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnclaim"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskAppearedCallback(_:_:_:_:)/title",
          "value": "DARegisterDiskAppearedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskAppearedCallback(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskAppearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskPeekCallback(_:_:_:_:_:)/title",
          "value": "DARegisterDiskPeekCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskPeekCallback(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskPeekCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmount(_:_:_:_:)/title",
          "value": "DADiskUnmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmount(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskEjectApprovalCallback(_:_:_:_:)/title",
          "value": "DARegisterDiskEjectApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskEjectApprovalCallback(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskEjectApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskDisappearedCallback(_:_:_:_:)/title",
          "value": "DARegisterDiskDisappearedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskDisappearedCallback(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskDisappearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)/title",
          "value": "DARegisterDiskDescriptionChangedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskDescriptionChangedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskIsClaimed(_:)/title",
          "value": "DADiskIsClaimed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskIsClaimed(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskIsClaimed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEject(_:_:_:_:)/title",
          "value": "DADiskEject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEject(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaim(_:_:_:_:_:_:)/title",
          "value": "DADiskClaim"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaim(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaim"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DASession/title",
          "value": "DASessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DASession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DASessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DASession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DASessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskGetOptions(_:)/title",
          "value": "DADiskGetOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskGetOptions(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskGetOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMount(_:_:_:_:_:)/title",
          "value": "DADiskMount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMount(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/daregisterdiskmountapprovalcallback(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/daregisterdiskmountapprovalcallback(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
