{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DiskArbitration Data Types"
  },
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAApprovalSessionRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DAApprovalSessionRef"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAApprovalSessionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "DAApprovalSessionRef",
      "type": "topic",
      "url": "/documentation/diskarbitration/daapprovalsessionref"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimOptions": {
      "abstract": [
        {
          "text": "Options for DADiskClaim().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskClaimOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskClaimOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskClaimOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskclaimoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectOptions": {
      "abstract": [
        {
          "text": "Options for DADiskEject().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskEjectOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskEjectOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskEjectOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskejectoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions": {
      "abstract": [
        {
          "text": "Options for DADiskMount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskOptions": {
      "abstract": [
        {
          "text": "Options for DADiskGetOptions() and DADiskSetOptions().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions": {
      "abstract": [
        {
          "text": "Options for DADiskRename().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskRenameOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskRenameOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskRenameOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskrenameoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions": {
      "abstract": [
        {
          "text": "Options for DADiskUnmount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnmountOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnmountOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnmountOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAReturn": {
      "abstract": [
        {
          "text": "A return code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DAReturn"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DAReturn"
        }
      ],
      "role": "symbol",
      "title": "DAReturn",
      "type": "topic",
      "url": "/documentation/diskarbitration/dareturn"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADisk.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadisk-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADissenter.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadissenter-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DASession.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dasession-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Constants",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-constants"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Enumerations",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-enumerations"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Functions",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-functions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h": {
      "abstract": [
        {
          "text": "Register for mount/unmount notifications, and block mount/unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-h"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAReturn"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAApprovalSessionRef",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAReturn"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskOptions/title",
          "value": "DADiskOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DAReturn/title",
          "value": "DAReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DAReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DAReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DAReturn/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DAReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/title",
          "value": "DADiskUnmountOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/title",
          "value": "DADiskMountOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/title",
          "value": "DADiskRenameOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectOptions/title",
          "value": "DADiskEjectOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEjectOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEjectOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimOptions/title",
          "value": "DADiskClaimOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaimOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaimOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/diskarbitration-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/diskarbitration-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
