{
  "abstract": [
    {
      "text": "Register for mount/unmount notifications, and block mount/unmount events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DiskArbitration.h"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See the Overview section above for header-level documentation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "anchor": "Included-Headers",
          "level": 3,
          "text": "Included Headers",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<CoreFoundation/CoreFoundation.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<DiskArbitration/DADisk.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<DiskArbitration/DADissenter.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<DiskArbitration/DASession.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskAppearedCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskAppearedCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskAppearedCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskAppearedCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskAppearedCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskAppearedCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskappearedcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaim(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Claims the specified disk object for exclusive use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskClaim"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskClaimOptions",
          "text": "DADiskClaimOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskClaimReleaseCallback",
          "text": "DADiskClaimReleaseCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskClaimCallback",
          "text": "DADiskClaimCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaim(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskClaim"
        }
      ],
      "role": "symbol",
      "title": "DADiskClaim(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskclaim(_:_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskClaim().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskClaimCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskClaimCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskClaimCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskclaimcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimReleaseCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskClaim().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskClaimReleaseCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimReleaseCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskClaimReleaseCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskClaimReleaseCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskclaimreleasecallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDescriptionChangedCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskDescriptionChangedCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskDescriptionChangedCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDescriptionChangedCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskDescriptionChangedCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskDescriptionChangedCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskdescriptionchangedcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDisappearedCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskDisappearedCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskDisappearedCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDisappearedCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskDisappearedCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskDisappearedCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskdisappearedcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEject(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Ejects the specified disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskEject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskEjectOptions",
          "text": "DADiskEjectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskEjectCallback",
          "text": "DADiskEjectCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEject(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskEject"
        }
      ],
      "role": "symbol",
      "title": "DADiskEject(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskeject(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectApprovalCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskEjectApprovalCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskEjectApprovalCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectApprovalCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskEjectApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskEjectApprovalCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskejectapprovalcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskEject().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskEjectCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskEjectCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskEjectCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskejectcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetOptions(_:)": {
      "abstract": [
        {
          "text": "Obtains the options for the specified disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskGetOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskOptions",
          "text": "DADiskOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskGetOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskGetOptions(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskgetoptions(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskIsClaimed(_:)": {
      "abstract": [
        {
          "text": "Reports whether or not the disk is claimed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskIsClaimed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskIsClaimed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskIsClaimed"
        }
      ],
      "role": "symbol",
      "title": "DADiskIsClaimed(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskisclaimed(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMount(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Mounts the volume at the specified disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskMountOptions",
          "text": "DADiskMountOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskMountCallback",
          "text": "DADiskMountCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMount(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMount"
        }
      ],
      "role": "symbol",
      "title": "DADiskMount(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmount(_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskMountApprovalCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountApprovalCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountApprovalCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountapprovalcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskMount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions": {
      "abstract": [
        {
          "text": "Options for DADiskMount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountWithArguments(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Mounts the volume at the specified disk object, with the specified mount options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountWithArguments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskMountOptions",
          "text": "DADiskMountOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskMountCallback",
          "text": "DADiskMountCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?>?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountWithArguments(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountWithArguments"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountWithArguments(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountwitharguments(_:_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskPeekCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskPeekCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskPeekCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskPeekCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskPeekCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskPeekCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskpeekcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRename(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Renames the volume at the specified disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskRename"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRenameOptions",
          "text": "DADiskRenameOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRenameCallback",
          "text": "DADiskRenameCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRename(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskRename"
        }
      ],
      "role": "symbol",
      "title": "DADiskRename(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskrename(_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskRename().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskRenameCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskRenameCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskRenameCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskrenamecallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions": {
      "abstract": [
        {
          "text": "Options for DADiskRename().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskRenameOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskRenameOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskRenameOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskrenameoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskSetOptions(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the options for the specified disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskSetOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskOptions",
          "text": "DADiskOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DAReturn",
          "text": "DAReturn"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskSetOptions(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskSetOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskSetOptions(_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadisksetoptions(_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnclaim(_:)": {
      "abstract": [
        {
          "text": "Unclaims the specified disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnclaim"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnclaim(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnclaim"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnclaim(_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunclaim(_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmount(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Unmounts the volume at the specified disk object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnmount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskRef",
          "text": "DADisk"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskUnmountOptions",
          "text": "DADiskUnmountOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskUnmountCallback",
          "text": "DADiskUnmountCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmount(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnmount"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnmount(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunmount(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountApprovalCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DARegisterDiskUnmountApprovalCallback().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnmountApprovalCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountApprovalCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnmountApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnmountApprovalCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunmountapprovalcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountCallback": {
      "abstract": [
        {
          "text": "Type of the callback function used by DADiskUnmount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnmountCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnmountCallback"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnmountCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunmountcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions": {
      "abstract": [
        {
          "text": "Options for DADiskUnmount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnmountOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnmountOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnmountOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskAppearedCallback(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a disk has appeared.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskAppearedCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskAppearedCallback",
          "text": "DADiskAppearedCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskAppearedCallback(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskAppearedCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskAppearedCallback(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskappearedcallback(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a disk description has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskDescriptionChangedCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskDescriptionChangedCallback",
          "text": "DADiskDescriptionChangedCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskDescriptionChangedCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskdescriptionchangedcallback(_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDisappearedCallback(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a disk has disappeared.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskDisappearedCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskDisappearedCallback",
          "text": "DADiskDisappearedCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDisappearedCallback(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskDisappearedCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskDisappearedCallback(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskdisappearedcallback(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskEjectApprovalCallback(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a volume is to be ejected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskEjectApprovalCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskEjectApprovalCallback",
          "text": "DADiskEjectApprovalCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskEjectApprovalCallback(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskEjectApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskEjectApprovalCallback(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskejectapprovalcallback(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskMountApprovalCallback(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a volume is to be mounted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskMountApprovalCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskMountApprovalCallback",
          "text": "DADiskMountApprovalCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskMountApprovalCallback(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskMountApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskMountApprovalCallback(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskmountapprovalcallback(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskPeekCallback(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a disk has been probed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskPeekCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskPeekCallback",
          "text": "DADiskPeekCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskPeekCallback(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskPeekCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskPeekCallback(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskpeekcallback(_:_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskUnmountApprovalCallback(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers a callback function to be called whenever a volume is to be unmounted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DARegisterDiskUnmountApprovalCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DADiskUnmountApprovalCallback",
          "text": "DADiskUnmountApprovalCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskUnmountApprovalCallback(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DARegisterDiskUnmountApprovalCallback"
        }
      ],
      "role": "symbol",
      "title": "DARegisterDiskUnmountApprovalCallback(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daregisterdiskunmountapprovalcallback(_:_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAUnregisterApprovalCallback": {
      "abstract": [
        {
          "text": "Unregisters a registered callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DAUnregisterApprovalCallback"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAUnregisterApprovalCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "DAUnregisterApprovalCallback",
      "type": "topic",
      "url": "/documentation/diskarbitration/daunregisterapprovalcallback"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAUnregisterCallback(_:_:_:)": {
      "abstract": [
        {
          "text": "Unregisters a registered callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DAUnregisterCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DASessionRef",
          "text": "DASession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAUnregisterCallback(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DAUnregisterCallback"
        }
      ],
      "role": "symbol",
      "title": "DAUnregisterCallback(_:_:_:)",
      "type": "topic",
      "url": "/documentation/diskarbitration/daunregistercallback(_:_:_:)"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADisk.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadisk-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskclaimoptions": {
      "abstract": [
        {
          "text": "Options for DADiskClaim().",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskclaimoptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADiskClaimOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskclaimoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions": {
      "abstract": [
        {
          "text": "Options for DADiskEject().",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADiskEjectOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskejectoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADissenter.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadissenter-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DASession.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dasession-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Constants",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-constants"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Data Types",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-data-types"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Enumerations",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-enumerations"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Functions",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-functions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/global-variables": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/global-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Global Variables",
      "type": "topic",
      "url": "/documentation/diskarbitration/global-variables"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Miscellaneous",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaim(_:_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEject(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetOptions(_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskIsClaimed(_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMount(_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountWithArguments(_:_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRename(_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskSetOptions(_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnclaim(_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmount(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskAppearedCallback(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDisappearedCallback(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskEjectApprovalCallback(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskMountApprovalCallback(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskPeekCallback(_:_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskUnmountApprovalCallback(_:_:_:_:)",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAUnregisterCallback(_:_:_:)"
      ],
      "title": "Miscellaneous"
    },
    {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "anchor": "Callbacks",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskAppearedCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimReleaseCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDescriptionChangedCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDisappearedCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectApprovalCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskPeekCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountApprovalCallback",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountCallback"
      ],
      "title": "Callbacks"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/global-variables",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskclaimoptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaim(_:_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEject(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskGetOptions(_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskIsClaimed(_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMount(_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountWithArguments(_:_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRename(_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskSetOptions(_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnclaim(_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmount(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskAppearedCallback(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskDisappearedCallback(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskEjectApprovalCallback(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskMountApprovalCallback(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskPeekCallback(_:_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DARegisterDiskUnmountApprovalCallback(_:_:_:_:)",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAUnregisterApprovalCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DAUnregisterCallback(_:_:_:)"
              ],
              "title": "Miscellaneous"
            },
            {
              "abstract": [
                {
                  "text": "See the Overview section above for header-level documentation.",
                  "type": "text"
                }
              ],
              "anchor": "Callbacks",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskAppearedCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskClaimReleaseCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDescriptionChangedCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskDisappearedCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectApprovalCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskEjectCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountApprovalCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskPeekCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountApprovalCallback",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountCallback"
              ],
              "title": "Callbacks"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/global-variables",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskclaimoptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDescriptionChangedCallback/title",
          "value": "DADiskDescriptionChangedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDescriptionChangedCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskDescriptionChangedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDescriptionChangedCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskDescriptionChangedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountApprovalCallback/title",
          "value": "DADiskUnmountApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountApprovalCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountApprovalCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskEjectApprovalCallback(_:_:_:_:)/title",
          "value": "DARegisterDiskEjectApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskEjectApprovalCallback(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskEjectApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmount(_:_:_:_:)/title",
          "value": "DADiskUnmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmount(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskSetOptions(_:_:_:)/title",
          "value": "DADiskSetOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskSetOptions(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskSetOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameCallback/title",
          "value": "DADiskRenameCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskIsClaimed(_:)/title",
          "value": "DADiskIsClaimed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskIsClaimed(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskIsClaimed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimReleaseCallback/title",
          "value": "DADiskClaimReleaseCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimReleaseCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaimReleaseCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimReleaseCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaimReleaseCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/title",
          "value": "DADiskRenameOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountCallback/title",
          "value": "DADiskMountCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskAppearedCallback(_:_:_:_:)/title",
          "value": "DARegisterDiskAppearedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskAppearedCallback(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskAppearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DAUnregisterCallback(_:_:_:)/title",
          "value": "DAUnregisterCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DAUnregisterCallback(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DAUnregisterCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaim(_:_:_:_:_:_:)/title",
          "value": "DADiskClaim"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaim(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaim"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountWithArguments(_:_:_:_:_:_:)/title",
          "value": "DADiskMountWithArguments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountWithArguments(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountWithArguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnclaim(_:)/title",
          "value": "DADiskUnclaim"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnclaim(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnclaim"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskPeekCallback/title",
          "value": "DADiskPeekCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskPeekCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskPeekCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskPeekCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskPeekCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountCallback/title",
          "value": "DADiskUnmountCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectApprovalCallback/title",
          "value": "DADiskEjectApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectApprovalCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEjectApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectApprovalCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEjectApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountApprovalCallback/title",
          "value": "DADiskMountApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountApprovalCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountApprovalCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEject(_:_:_:_:)/title",
          "value": "DADiskEject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEject(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskGetOptions(_:)/title",
          "value": "DADiskGetOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskGetOptions(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskGetOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)/title",
          "value": "DARegisterDiskDescriptionChangedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskDescriptionChangedCallback(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskDescriptionChangedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/title",
          "value": "DADiskMountOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectCallback/title",
          "value": "DADiskEjectCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEjectCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskEjectCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskEjectCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMount(_:_:_:_:_:)/title",
          "value": "DADiskMount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMount(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskDisappearedCallback(_:_:_:_:)/title",
          "value": "DARegisterDiskDisappearedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskDisappearedCallback(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskDisappearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskUnmountApprovalCallback(_:_:_:_:)/title",
          "value": "DARegisterDiskUnmountApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskUnmountApprovalCallback(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskUnmountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskMountApprovalCallback(_:_:_:_:)/title",
          "value": "DARegisterDiskMountApprovalCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskMountApprovalCallback(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskMountApprovalCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskAppearedCallback/title",
          "value": "DADiskAppearedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskAppearedCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskAppearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskAppearedCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskAppearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/title",
          "value": "DADiskUnmountOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimCallback/title",
          "value": "DADiskClaimCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaimCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskClaimCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskClaimCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskPeekCallback(_:_:_:_:_:)/title",
          "value": "DARegisterDiskPeekCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DARegisterDiskPeekCallback(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DARegisterDiskPeekCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRename(_:_:_:_:_:)/title",
          "value": "DADiskRename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRename(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRename"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDisappearedCallback/title",
          "value": "DADiskDisappearedCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDisappearedCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskDisappearedCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskDisappearedCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskDisappearedCallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/diskarbitration-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/diskarbitration-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
