{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "role": "collectionGroup",
    "title": "DiskArbitration Enumerations"
  },
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskmountoptions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskmountoptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/diskarbitration/anonymous-kdadiskmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskoptions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskoptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/diskarbitration/anonymous-kdadiskoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskunmountoptions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskunmountoptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/diskarbitration/anonymous-kdadiskunmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADisk.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadisk-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADissenter.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadissenter-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DASession.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dasession-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Constants",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-constants"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Data Types",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-data-types"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Functions",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-functions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h": {
      "abstract": [
        {
          "text": "Register for mount/unmount notifications, and block mount/unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-h"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskunmountoptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskmountoptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskoptions"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskunmountoptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskmountoptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/anonymous-kdadiskoptions"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/diskarbitration-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/diskarbitration-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
