{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DiskArbitration Constants"
  },
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADisk.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadisk-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADissenter.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadissenter-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DASession.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/dasession-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Data Types",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-data-types"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Enumerations",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-enumerations"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration Functions",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-functions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h": {
      "abstract": [
        {
          "text": "Register for mount/unmount notifications, and block mount/unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/err_local_diskarbitration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "err_local_diskarbitration"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/err_local_diskarbitration",
      "kind": "symbol",
      "role": "symbol",
      "title": "err_local_diskarbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration/err_local_diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionBusNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionBusNameKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionBusNameKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionbusnamekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusPathKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionBusPathKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusPathKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionBusPathKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionBusPathKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionbuspathkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceGUIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceGUIDKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceGUIDKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceGUIDKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceGUIDKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondeviceguidkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceInternalKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceInternalKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceInternalKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceInternalKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceInternalKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondeviceinternalkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceModelKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceModelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceModelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceModelKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceModelKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondevicemodelkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDevicePathKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDevicePathKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDevicePathKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDevicePathKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDevicePathKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondevicepathkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceProtocolKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceProtocolKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceProtocolKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceProtocolKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceProtocolKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondeviceprotocolkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceRevisionKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceRevisionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceRevisionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceRevisionKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceRevisionKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondevicerevisionkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceTDMLockedKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceTDMLockedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceTDMLockedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceTDMLockedKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceTDMLockedKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondevicetdmlockedkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceUnitKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceUnitKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceUnitKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceUnitKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceUnitKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondeviceunitkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceVendorKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceVendorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceVendorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceVendorKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceVendorKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondevicevendorkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMajorKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDMajorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMajorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDMajorKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaBSDMajorKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediabsdmajorkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMinorKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDMinorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMinorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDMinorKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaBSDMinorKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediabsdminorkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDNameKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaBSDNameKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediabsdnamekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDUnitKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDUnitKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDUnitKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDUnitKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaBSDUnitKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediabsdunitkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBlockSizeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBlockSizeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBlockSizeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBlockSizeKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaBlockSizeKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediablocksizekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaContentKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaContentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaContentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaContentKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaContentKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediacontentkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEjectableKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaEjectableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEjectableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaEjectableKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaEjectableKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediaejectablekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEncryptedKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaEncryptedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEncryptedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaEncryptedKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaEncryptedKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediaencryptedkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEncryptionDetailKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaEncryptionDetailKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEncryptionDetailKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaEncryptionDetailKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaEncryptionDetailKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediaencryptiondetailkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaIconKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaIconKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaIconKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaIconKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaIconKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediaiconkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaKindKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaKindKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaKindKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaKindKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaKindKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediakindkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaLeafKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaLeafKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaLeafKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaLeafKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaLeafKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmedialeafkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaNameKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaNameKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmedianamekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaPathKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaPathKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaPathKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaPathKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaPathKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediapathkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaRemovableKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaRemovableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaRemovableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaRemovableKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaRemovableKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediaremovablekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaSizeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaSizeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaSizeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaSizeKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaSizeKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediasizekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaTypeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaTypeKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediatypekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaUUIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaUUIDKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaUUIDKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaUUIDKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaUUIDKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediauuidkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaWholeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaWholeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaWholeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaWholeKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaWholeKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediawholekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaWritableKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaWritableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaWritableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaWritableKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaWritableKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediawritablekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeKindKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeKindKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeKindKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeKindKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionVolumeKindKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionvolumekindkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeMountableKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeMountableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeMountableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeMountableKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionVolumeMountableKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionvolumemountablekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeNameKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionVolumeNameKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionvolumenamekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeNetworkKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeNetworkKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeNetworkKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeNetworkKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionVolumeNetworkKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionvolumenetworkkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumePathKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumePathKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumePathKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumePathKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionVolumePathKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionvolumepathkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeTypeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionVolumeTypeKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionvolumetypekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeUUIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeUUIDKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeUUIDKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionVolumeUUIDKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionVolumeUUIDKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionvolumeuuidkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusNameKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusPathKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceGUIDKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceInternalKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceModelKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDevicePathKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceProtocolKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceRevisionKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceUnitKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceVendorKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMajorKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMinorKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDNameKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDUnitKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBlockSizeKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaContentKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEjectableKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaIconKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaKindKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaLeafKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaNameKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaPathKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaRemovableKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaSizeKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaTypeKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaUUIDKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaWholeKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaWritableKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeKindKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeMountableKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeNameKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeNetworkKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumePathKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeTypeKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeUUIDKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceTDMLockedKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEncryptedKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEncryptionDetailKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusNameKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusPathKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceGUIDKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceInternalKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceModelKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDevicePathKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceProtocolKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceRevisionKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceUnitKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceVendorKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMajorKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMinorKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDNameKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDUnitKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBlockSizeKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaContentKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEjectableKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaIconKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaKindKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaLeafKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaNameKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaPathKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaRemovableKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaSizeKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaTypeKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaUUIDKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaWholeKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaWritableKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeKindKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeMountableKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeNameKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeNetworkKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumePathKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeTypeKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionVolumeUUIDKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceTDMLockedKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEncryptedKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaEncryptionDetailKey"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/err_local_diskarbitration"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadisk-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadissenter-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dasession-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-enumerations",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-functions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaEjectableKey/title",
          "value": "kDADiskDescriptionMediaEjectableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaEjectableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaEjectableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeNetworkKey/title",
          "value": "kDADiskDescriptionVolumeNetworkKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeNetworkKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionVolumeNetworkKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaTypeKey/title",
          "value": "kDADiskDescriptionMediaTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeUUIDKey/title",
          "value": "kDADiskDescriptionVolumeUUIDKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeUUIDKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionVolumeUUIDKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceInternalKey/title",
          "value": "kDADiskDescriptionDeviceInternalKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceInternalKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceInternalKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDMinorKey/title",
          "value": "kDADiskDescriptionMediaBSDMinorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDMinorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaBSDMinorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeKindKey/title",
          "value": "kDADiskDescriptionVolumeKindKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeKindKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionVolumeKindKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceGUIDKey/title",
          "value": "kDADiskDescriptionDeviceGUIDKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceGUIDKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceGUIDKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceUnitKey/title",
          "value": "kDADiskDescriptionDeviceUnitKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceUnitKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceUnitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDUnitKey/title",
          "value": "kDADiskDescriptionMediaBSDUnitKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDUnitKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaBSDUnitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaWholeKey/title",
          "value": "kDADiskDescriptionMediaWholeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaWholeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaWholeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaSizeKey/title",
          "value": "kDADiskDescriptionMediaSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaSizeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaSizeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaEncryptedKey/title",
          "value": "kDADiskDescriptionMediaEncryptedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaEncryptedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaEncryptedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaNameKey/title",
          "value": "kDADiskDescriptionMediaNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaRemovableKey/title",
          "value": "kDADiskDescriptionMediaRemovableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaRemovableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaRemovableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeNameKey/title",
          "value": "kDADiskDescriptionVolumeNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionVolumeNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaWritableKey/title",
          "value": "kDADiskDescriptionMediaWritableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaWritableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaWritableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeMountableKey/title",
          "value": "kDADiskDescriptionVolumeMountableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeMountableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionVolumeMountableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionBusNameKey/title",
          "value": "kDADiskDescriptionBusNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionBusNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionBusNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaUUIDKey/title",
          "value": "kDADiskDescriptionMediaUUIDKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaUUIDKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaUUIDKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaPathKey/title",
          "value": "kDADiskDescriptionMediaPathKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaPathKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaPathKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDMajorKey/title",
          "value": "kDADiskDescriptionMediaBSDMajorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDMajorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaBSDMajorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaLeafKey/title",
          "value": "kDADiskDescriptionMediaLeafKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaLeafKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaLeafKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceRevisionKey/title",
          "value": "kDADiskDescriptionDeviceRevisionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceRevisionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceRevisionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaIconKey/title",
          "value": "kDADiskDescriptionMediaIconKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaIconKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaIconKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaKindKey/title",
          "value": "kDADiskDescriptionMediaKindKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaKindKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaKindKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDNameKey/title",
          "value": "kDADiskDescriptionMediaBSDNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaBSDNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaEncryptionDetailKey/title",
          "value": "kDADiskDescriptionMediaEncryptionDetailKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaEncryptionDetailKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaEncryptionDetailKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDevicePathKey/title",
          "value": "kDADiskDescriptionDevicePathKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDevicePathKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDevicePathKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeTypeKey/title",
          "value": "kDADiskDescriptionVolumeTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumeTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionVolumeTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaContentKey/title",
          "value": "kDADiskDescriptionMediaContentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaContentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaContentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceTDMLockedKey/title",
          "value": "kDADiskDescriptionDeviceTDMLockedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceTDMLockedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceTDMLockedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceVendorKey/title",
          "value": "kDADiskDescriptionDeviceVendorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceVendorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceVendorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceModelKey/title",
          "value": "kDADiskDescriptionDeviceModelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceModelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceModelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceProtocolKey/title",
          "value": "kDADiskDescriptionDeviceProtocolKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceProtocolKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceProtocolKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBlockSizeKey/title",
          "value": "kDADiskDescriptionMediaBlockSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBlockSizeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaBlockSizeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionBusPathKey/title",
          "value": "kDADiskDescriptionBusPathKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionBusPathKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionBusPathKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumePathKey/title",
          "value": "kDADiskDescriptionVolumePathKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionVolumePathKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionVolumePathKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/diskarbitration-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/diskarbitration-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
