{
  "abstract": [
    {
      "text": "A return code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/enum_(unnamed)-3ky11"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DAReturn"
  },
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBadArgument": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnBadArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBadArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnBadArgument"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnBadArgument",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnbadargument"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBusy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnBusy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBusy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnBusy"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnBusy",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnbusy"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnError"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnError",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnerror"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnExclusiveAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnExclusiveAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnExclusiveAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnExclusiveAccess"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnExclusiveAccess",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnexclusiveaccess"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNoResources": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNoResources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNoResources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNoResources"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNoResources",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnoresources"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotFound"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotFound",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotfound"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotMounted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotMounted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotMounted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotMounted"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotMounted",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotmounted"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPermitted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotPermitted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPermitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotPermitted"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotPermitted",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotpermitted"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPrivileged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotPrivileged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPrivileged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotPrivileged"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotPrivileged",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotprivileged"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotReady": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotReady"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotReady",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotReady"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotReady",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotready"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotWritable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnNotWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnNotWritable"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnNotWritable",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnnotwritable"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnSuccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnSuccess"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnSuccess",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnsuccess"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnUnsupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDAReturnUnsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDAReturnUnsupported"
        }
      ],
      "role": "symbol",
      "title": "kDAReturnUnsupported",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdareturnunsupported"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBadArgument",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBusy",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnError",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnExclusiveAccess",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNoResources",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotFound",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotMounted",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPermitted",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPrivileged",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotReady",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotWritable",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnSuccess",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnUnsupported"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBadArgument",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnBusy",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnError",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnExclusiveAccess",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNoResources",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotFound",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotMounted",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPermitted",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotPrivileged",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotReady",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnNotWritable",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnSuccess",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDAReturnUnsupported"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnBusy/title",
          "value": "kDAReturnBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnBusy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotPermitted/title",
          "value": "kDAReturnNotPermitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotPermitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotPermitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotMounted/title",
          "value": "kDAReturnNotMounted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotMounted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotMounted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnError/title",
          "value": "kDAReturnError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotPrivileged/title",
          "value": "kDAReturnNotPrivileged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotPrivileged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotPrivileged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotWritable/title",
          "value": "kDAReturnNotWritable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotWritable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotReady/title",
          "value": "kDAReturnNotReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotReady/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNoResources/title",
          "value": "kDAReturnNoResources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNoResources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNoResources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnUnsupported/title",
          "value": "kDAReturnUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnExclusiveAccess/title",
          "value": "kDAReturnExclusiveAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnExclusiveAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnExclusiveAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotFound/title",
          "value": "kDAReturnNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnSuccess/title",
          "value": "kDAReturnSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnBadArgument/title",
          "value": "kDAReturnBadArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDAReturnBadArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDAReturnBadArgument"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/enum_(unnamed)-3ky11"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/enum_(unnamed)-3ky11"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
