{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/global-variables"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Global Variables"
  },
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions": {
      "abstract": [
        {
          "text": "Options for DADiskMount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskMountOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskMountOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskMountOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions": {
      "abstract": [
        {
          "text": "Options for DADiskRename().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskRenameOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskRenameOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskRenameOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskrenameoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions": {
      "abstract": [
        {
          "text": "Options for DADiskUnmount().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DADiskUnmountOptions"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DADiskUnmountOptions"
        }
      ],
      "role": "symbol",
      "title": "DADiskUnmountOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskunmountoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskclaimoptions": {
      "abstract": [
        {
          "text": "Options for DADiskClaim().",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskclaimoptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADiskClaimOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskclaimoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions": {
      "abstract": [
        {
          "text": "Options for DADiskEject().",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DADiskEjectOptions",
      "type": "topic",
      "url": "/documentation/diskarbitration/dadiskejectoptions"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h": {
      "abstract": [
        {
          "text": "Register for mount/unmount notifications, and block mount/unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/diskarbitration-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DiskArbitration.h",
      "type": "topic",
      "url": "/documentation/diskarbitration/diskarbitration-h"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchMediaUnformatted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMatchMediaUnformatted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchMediaUnformatted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMatchMediaUnformatted"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMatchMediaUnformatted",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmatchmediaunformatted"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchMediaWhole": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMatchMediaWhole"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchMediaWhole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMatchMediaWhole"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMatchMediaWhole",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmatchmediawhole"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchVolumeMountable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMatchVolumeMountable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchVolumeMountable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMatchVolumeMountable"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMatchVolumeMountable",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmatchvolumemountable"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchVolumeUnrecognized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMatchVolumeUnrecognized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchVolumeUnrecognized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMatchVolumeUnrecognized"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMatchVolumeUnrecognized",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmatchvolumeunrecognized"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionWatchVolumeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionWatchVolumeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionWatchVolumeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionWatchVolumeName"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionWatchVolumeName",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionwatchvolumename"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionWatchVolumePath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionWatchVolumePath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionWatchVolumePath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionWatchVolumePath"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionWatchVolumePath",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionwatchvolumepath"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskclaimoptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchMediaUnformatted",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchMediaWhole",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchVolumeMountable",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchVolumeUnrecognized",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionWatchVolumeName",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionWatchVolumePath"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchMediaUnformatted",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchMediaWhole",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchVolumeMountable",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMatchVolumeUnrecognized",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionWatchVolumeName",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionWatchVolumePath"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskclaimoptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/dadiskejectoptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskMountOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskRenameOptions",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/DADiskUnmountOptions"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionWatchVolumeName/title",
          "value": "kDADiskDescriptionWatchVolumeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionWatchVolumeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionWatchVolumeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMatchMediaUnformatted/title",
          "value": "kDADiskDescriptionMatchMediaUnformatted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMatchMediaUnformatted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMatchMediaUnformatted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/title",
          "value": "DADiskUnmountOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskUnmountOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskUnmountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMatchVolumeMountable/title",
          "value": "kDADiskDescriptionMatchVolumeMountable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMatchVolumeMountable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMatchVolumeMountable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMatchMediaWhole/title",
          "value": "kDADiskDescriptionMatchMediaWhole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMatchMediaWhole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMatchMediaWhole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMatchVolumeUnrecognized/title",
          "value": "kDADiskDescriptionMatchVolumeUnrecognized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMatchVolumeUnrecognized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMatchVolumeUnrecognized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/title",
          "value": "DADiskMountOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskMountOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskMountOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/title",
          "value": "DADiskRenameOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1DADiskRenameOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DADiskRenameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionWatchVolumePath/title",
          "value": "kDADiskDescriptionWatchVolumePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionWatchVolumePath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionWatchVolumePath"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/global-variables"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/global-variables"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
