{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaKindKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kDADiskDescriptionMediaKindKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kDADiskDescriptionMediaKindKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Disk Arbitration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kDADiskDescriptionMediaKindKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kDADiskDescriptionMediaKindKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaKindKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.diskarbitration/documentation/DiskArbitration": {
      "abstract": [
        {
          "text": "Provides mechanisms to register and block disk mount or unmount events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration",
      "kind": "symbol",
      "role": "collection",
      "title": "Disk Arbitration",
      "type": "topic",
      "url": "/documentation/diskarbitration"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionBusNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionBusNameKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionBusNameKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionbusnamekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusPathKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionBusPathKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusPathKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionBusPathKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionBusPathKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionbuspathkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceGUIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceGUIDKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceGUIDKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceGUIDKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceGUIDKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondeviceguidkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceInternalKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceInternalKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceInternalKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceInternalKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceInternalKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondeviceinternalkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceModelKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceModelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceModelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceModelKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceModelKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondevicemodelkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDevicePathKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDevicePathKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDevicePathKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDevicePathKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDevicePathKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondevicepathkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceProtocolKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceProtocolKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceProtocolKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceProtocolKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceProtocolKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondeviceprotocolkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceRevisionKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceRevisionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceRevisionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceRevisionKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceRevisionKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondevicerevisionkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceUnitKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceUnitKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceUnitKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceUnitKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceUnitKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondeviceunitkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceVendorKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceVendorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceVendorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionDeviceVendorKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionDeviceVendorKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptiondevicevendorkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMajorKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDMajorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMajorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDMajorKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaBSDMajorKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediabsdmajorkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMinorKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDMinorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMinorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDMinorKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaBSDMinorKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediabsdminorkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDNameKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaBSDNameKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediabsdnamekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDUnitKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDUnitKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDUnitKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBSDUnitKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaBSDUnitKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediabsdunitkey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBlockSizeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBlockSizeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBlockSizeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaBlockSizeKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaBlockSizeKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediablocksizekey"
    },
    "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaKindKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaKindKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaKindKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDADiskDescriptionMediaKindKey"
        }
      ],
      "role": "symbol",
      "title": "kDADiskDescriptionMediaKindKey",
      "type": "topic",
      "url": "/documentation/diskarbitration/kdadiskdescriptionmediakindkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusNameKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusPathKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceGUIDKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceInternalKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceModelKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDevicePathKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceProtocolKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceRevisionKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceUnitKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceVendorKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMajorKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMinorKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDNameKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDUnitKey",
        "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBlockSizeKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kDADiskDescriptionMediaKindKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaKindKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusNameKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionBusPathKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceGUIDKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceInternalKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceModelKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDevicePathKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceProtocolKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceRevisionKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceUnitKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionDeviceVendorKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMajorKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDMinorKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDNameKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBSDUnitKey",
                "doc://com.apple.diskarbitration/documentation/DiskArbitration/kDADiskDescriptionMediaBlockSizeKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kDADiskDescriptionMediaKindKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceRevisionKey/title",
          "value": "kDADiskDescriptionDeviceRevisionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceRevisionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceRevisionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDNameKey/title",
          "value": "kDADiskDescriptionMediaBSDNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaBSDNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBlockSizeKey/title",
          "value": "kDADiskDescriptionMediaBlockSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBlockSizeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaBlockSizeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceGUIDKey/title",
          "value": "kDADiskDescriptionDeviceGUIDKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceGUIDKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceGUIDKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceUnitKey/title",
          "value": "kDADiskDescriptionDeviceUnitKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceUnitKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceUnitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceModelKey/title",
          "value": "kDADiskDescriptionDeviceModelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceModelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceModelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceProtocolKey/title",
          "value": "kDADiskDescriptionDeviceProtocolKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceProtocolKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceProtocolKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceVendorKey/title",
          "value": "kDADiskDescriptionDeviceVendorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceVendorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceVendorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDMinorKey/title",
          "value": "kDADiskDescriptionMediaBSDMinorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDMinorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaBSDMinorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceInternalKey/title",
          "value": "kDADiskDescriptionDeviceInternalKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDeviceInternalKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDeviceInternalKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDUnitKey/title",
          "value": "kDADiskDescriptionMediaBSDUnitKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDUnitKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaBSDUnitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDMajorKey/title",
          "value": "kDADiskDescriptionMediaBSDMajorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaBSDMajorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaBSDMajorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaKindKey/title",
          "value": "kDADiskDescriptionMediaKindKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionMediaKindKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionMediaKindKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionBusPathKey/title",
          "value": "kDADiskDescriptionBusPathKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionBusPathKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionBusPathKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDevicePathKey/title",
          "value": "kDADiskDescriptionDevicePathKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionDevicePathKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionDevicePathKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionBusNameKey/title",
          "value": "kDADiskDescriptionBusNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.diskarbitration~1documentation~1DiskArbitration~1kDADiskDescriptionBusNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDADiskDescriptionBusNameKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/diskarbitration/kdadiskdescriptionmediakindkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/diskarbitration/kdadiskdescriptionmediakindkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
