{
  "abstract": [
    {
      "text": "No action is required.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.identitylookup/documentation/IdentityLookup",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/none"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ILClassificationAction@ILClassificationActionNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "none"
      }
    ],
    "modules": [
      {
        "name": "SMS and Call Reporting"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ILClassificationActionNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ILClassificationAction.none"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "none"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The extension just dismisses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup": {
      "abstract": [
        {
          "text": "Create app extensions to manage and report unwanted SMS messages and spam calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup",
      "kind": "symbol",
      "role": "collection",
      "title": "SMS and Call Reporting",
      "type": "topic",
      "url": "/documentation/identitylookup"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction": {
      "abstract": [
        {
          "text": "The actions the system can take in response to the reported communication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILClassificationAction"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationAction"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationAction",
      "type": "topic",
      "url": "/documentation/identitylookup/ilclassificationaction"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/none": {
      "abstract": [
        {
          "text": "No action is required.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationActionNone"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationAction.none",
      "type": "topic",
      "url": "/documentation/identitylookup/ilclassificationaction/none"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportJunk": {
      "abstract": [
        {
          "text": "The system should report the communication as junk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportJunk"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportJunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationActionReportJunk"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationAction.reportJunk",
      "type": "topic",
      "url": "/documentation/identitylookup/ilclassificationaction/reportjunk"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportJunkAndBlockSender": {
      "abstract": [
        {
          "text": "The system should report the communication as junk and add the number to the system’s block list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportJunkAndBlockSender"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportJunkAndBlockSender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationActionReportJunkAndBlockSender"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationAction.reportJunkAndBlockSender",
      "type": "topic",
      "url": "/documentation/identitylookup/ilclassificationaction/reportjunkandblocksender"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportNotJunk": {
      "abstract": [
        {
          "text": "The system should report that the communication is not junk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportNotJunk"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportNotJunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationActionReportNotJunk"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationAction.reportNotJunk",
      "type": "topic",
      "url": "/documentation/identitylookup/ilclassificationaction/reportnotjunk"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController": {
      "abstract": [
        {
          "text": "The superclass for an Unwanted Communication Reporting extension’s principal view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILClassificationUIExtensionViewController"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationUIExtensionViewController"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationUIExtensionViewController",
      "type": "topic",
      "url": "/documentation/identitylookupui/ilclassificationuiextensionviewcontroller"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportJunk",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportJunkAndBlockSender",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportNotJunk"
      ],
      "title": "Classifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ILClassificationActionNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationActionNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.identitylookup/documentation/IdentityLookup",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportJunk",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportJunkAndBlockSender",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILClassificationAction/reportNotJunk"
              ],
              "title": "Classifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ILClassificationActionNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController/title",
          "value": "ILClassificationUIExtensionViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationUIExtensionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationUIExtensionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction~1none/title",
          "value": "ILClassificationActionNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationActionNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction~1reportJunk/title",
          "value": "ILClassificationActionReportJunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction~1reportJunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationActionReportJunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction~1reportJunkAndBlockSender/title",
          "value": "ILClassificationActionReportJunkAndBlockSender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction~1reportJunkAndBlockSender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationActionReportJunkAndBlockSender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction~1reportNotJunk/title",
          "value": "ILClassificationActionReportNotJunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction~1reportNotJunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationActionReportNotJunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction/title",
          "value": "ILClassificationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILClassificationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/identitylookup/ilclassificationaction/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/identitylookup/ilclassificationaction/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
