{
  "abstract": [
    {
      "text": "An object that lays out the content of pages according to the kind of content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printFormatter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIPrintInteractionController(py)printFormatter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "printFormatter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIPrintFormatter",
        "text": "UIPrintFormatter"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "printFormatter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "printFormatter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "printFormatter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIPrintFormatter",
              "text": "UIPrintFormatter"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Assign to this property an instance of one of the concrete subclasses of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ": ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This object is released at the end of the print job.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you set this property, ",
              "type": "text"
            },
            {
              "code": "UIPrintInteractionController",
              "type": "codeVoice"
            },
            {
              "text": " sets the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printingItems",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printingItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printPageRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". (Only one of these properties can be set for a print job.)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If this property is set and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/showsPageRange",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "—and if the formatter represents content of more than one page—the printing options include the control for selecting a page range.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter": {
      "abstract": [
        {
          "text": "An object that lays out HTML text for a multipage print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMarkupTextPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMarkupTextPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UIMarkupTextPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uimarkuptextprintformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter": {
      "abstract": [
        {
          "text": "An abstract base class for print formatters, which are objects that lay out custom printable content that can cross page boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UIPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController": {
      "abstract": [
        {
          "text": "A user interface that manages the printing of documents, images, and other printable content in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintInteractionController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInteractionController"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInteractionController",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printFormatter": {
      "abstract": [
        {
          "text": "An object that lays out the content of pages according to the kind of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printFormatter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintFormatter",
          "text": "UIPrintFormatter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printFormatter"
        }
      ],
      "role": "symbol",
      "title": "printFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontroller/printformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printPageRenderer": {
      "abstract": [
        {
          "text": "An object that draws pages of printable content when UIKit requests it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printPageRenderer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintPageRenderer",
          "text": "UIPrintPageRenderer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printPageRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printPageRenderer"
        }
      ],
      "role": "symbol",
      "title": "printPageRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontroller/printpagerenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printingItem": {
      "abstract": [
        {
          "text": "A single ready-to-print object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printingItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printingItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printingItem"
        }
      ],
      "role": "symbol",
      "title": "printingItem",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontroller/printingitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printingItems": {
      "abstract": [
        {
          "text": "An array of ready-to-print objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printingItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printingItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printingItems"
        }
      ],
      "role": "symbol",
      "title": "printingItems",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontroller/printingitems"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/showsPageRange": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the printing options include a page-range control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPageRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/showsPageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsPageRange"
        }
      ],
      "role": "symbol",
      "title": "showsPageRange",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontroller/showspagerange"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter": {
      "abstract": [
        {
          "text": "An object that lays out plain text for printing, possibly over multiple pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISimpleTextPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISimpleTextPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UISimpleTextPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uisimpletextprintformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter": {
      "abstract": [
        {
          "text": "An object that lays out the drawn content of a view for printing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UIViewPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uiviewprintformatter"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-the-source-of-printable-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printingItem",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printingItems",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printPageRenderer"
      ],
      "title": "Providing the source of printable content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "printFormatter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-the-source-of-printable-content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printingItem",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printingItems",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printPageRenderer"
              ],
              "title": "Providing the source of printable content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIPrintFormatter",
                    "text": "UIPrintFormatter"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "printFormatter"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1printingItem/title",
          "value": "printingItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1printingItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISimpleTextPrintFormatter/title",
          "value": "UISimpleTextPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISimpleTextPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISimpleTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISimpleTextPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISimpleTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMarkupTextPrintFormatter/title",
          "value": "UIMarkupTextPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMarkupTextPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMarkupTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMarkupTextPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMarkupTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPrintFormatter/title",
          "value": "UIViewPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController/title",
          "value": "UIPrintInteractionController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInteractionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInteractionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1printingItems/title",
          "value": "printingItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1printingItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printingItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter/title",
          "value": "UIPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1printFormatter/title",
          "value": "printFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1printFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1showsPageRange/title",
          "value": "showsPageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1showsPageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsPageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1printPageRenderer/title",
          "value": "printPageRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1printPageRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printPageRenderer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiprintinteractioncontroller/printformatter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiprintinteractioncontroller/printformatter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
