{
  "abstract": [
    {
      "text": "A variable that describes how a face landmarks request orders or enumerates the resulting features.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest/constellation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNDetectFaceLandmarksRequest(py)constellation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "constellation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@VNRequestFaceLandmarksConstellation",
        "text": "VNRequestFaceLandmarksConstellation"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "constellation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "constellation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "constellation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VNRequestFaceLandmarksConstellation",
              "text": "VNRequestFaceLandmarksConstellation"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set this variable to one of the supported constellation types detailed in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellationNotDefined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that finds facial features like eyes and mouth in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectFaceLandmarksRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectFaceLandmarksRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectFaceLandmarksRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacelandmarksrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest/constellation": {
      "abstract": [
        {
          "text": "A variable that describes how a face landmarks request orders or enumerates the resulting features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constellation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VNRequestFaceLandmarksConstellation",
          "text": "VNRequestFaceLandmarksConstellation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest/constellation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constellation"
        }
      ],
      "role": "symbol",
      "title": "constellation",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacelandmarksrequest/constellation"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation": {
      "abstract": [
        {
          "text": "An enumeration of face landmarks in a constellation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellationNotDefined": {
      "abstract": [
        {
          "text": "An undefined constellation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constellationNotDefined"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellationNotDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellationNotDefined"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation.constellationNotDefined",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation/constellationnotdefined"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Locating-Face-Landmarks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation"
      ],
      "title": "Locating Face Landmarks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "constellation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "constellation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Locating-Face-Landmarks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation"
              ],
              "title": "Locating Face Landmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@VNRequestFaceLandmarksConstellation",
                    "text": "VNRequestFaceLandmarksConstellation"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "constellation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest~1constellation/title",
          "value": "constellation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest~1constellation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "constellation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest/title",
          "value": "VNDetectFaceLandmarksRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceLandmarksRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceLandmarksRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation/title",
          "value": "VNRequestFaceLandmarksConstellation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellationNotDefined/title",
          "value": "VNRequestFaceLandmarksConstellationNotDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellationNotDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellationNotDefined"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vndetectfacelandmarksrequest/constellation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vndetectfacelandmarksrequest/constellation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
