{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "SecAsn1 is not supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/SecAsn1PubKeyInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/SecAsn1PubKeyInfo/init(algorithm:subjectPublicKey:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So17SecAsn1PubKeyInfoa9algorithm013subjectPublicD0ABSo0aB5AlgIda_So9cssm_dataVtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "algorithm"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SecAsn1AlgId",
        "text": "SecAsn1AlgId"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "subjectPublicKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecAsn1Item",
        "text": "SecAsn1Item"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.0",
        "message": "SecAsn1 is not supported",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(algorithm:subjectPublicKey:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "algorithm"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecAsn1AlgId",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SecAsn1AlgId",
              "text": "SecAsn1AlgId"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "subjectPublicKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/SecAsn1Item",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecAsn1Item",
              "text": "SecAsn1Item"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/SecAsn1AlgId": {
      "abstract": [
        {
          "text": "A structure identifying an ASN.1 algorithm by its OID, and its corresponding parameters.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAsn1AlgId"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAsn1AlgId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAsn1AlgId"
        }
      ],
      "role": "symbol",
      "title": "SecAsn1AlgId",
      "type": "topic",
      "url": "/documentation/security/secasn1algid"
    },
    "doc://com.apple.security/documentation/Security/SecAsn1Item": {
      "abstract": [
        {
          "text": "A structure holding DER encoded data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAsn1Item"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAsn1Item",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAsn1Item"
        }
      ],
      "role": "symbol",
      "title": "SecAsn1Item",
      "type": "topic",
      "url": "/documentation/security/secasn1item"
    },
    "doc://com.apple.security/documentation/Security/SecAsn1PubKeyInfo": {
      "abstract": [
        {
          "text": "A structure containing a public key and its associated algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecAsn1PubKeyInfo"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAsn1PubKeyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecAsn1PubKeyInfo"
        }
      ],
      "role": "symbol",
      "title": "SecAsn1PubKeyInfo",
      "type": "topic",
      "url": "/documentation/security/secasn1pubkeyinfo"
    },
    "doc://com.apple.security/documentation/Security/SecAsn1PubKeyInfo/init(algorithm:subjectPublicKey:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "algorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SecAsn1AlgId",
          "text": "SecAsn1AlgId"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subjectPublicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecAsn1Item",
          "text": "SecAsn1Item"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecAsn1PubKeyInfo/init(algorithm:subjectPublicKey:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(algorithm:subjectPublicKey:)",
      "type": "topic",
      "url": "/documentation/security/secasn1pubkeyinfo/init(algorithm:subjectpublickey:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAsn1Item/title",
          "value": "SecAsn1Item"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAsn1Item/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAsn1Item"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAsn1Item/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAsn1Item"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAsn1AlgId/title",
          "value": "SecAsn1AlgId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAsn1AlgId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAsn1AlgId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAsn1AlgId/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAsn1AlgId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAsn1PubKeyInfo/title",
          "value": "SecAsn1PubKeyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAsn1PubKeyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAsn1PubKeyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecAsn1PubKeyInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecAsn1PubKeyInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/secasn1pubkeyinfo/init(algorithm:subjectpublickey:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
