{
  "abstract": [
    {
      "text": "The accuracy of the magnetic field calibration is medium.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/medium"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CMMagneticFieldCalibrationAccuracy@CMMagneticFieldCalibrationAccuracyMedium",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "medium"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMMagneticFieldCalibrationAccuracyMedium"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CMMagneticFieldCalibrationAccuracy.medium"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "medium"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy": {
      "abstract": [
        {
          "text": "Indicates the calibration accuracy of a magnetic field estimate",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracy"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/high": {
      "abstract": [
        {
          "text": "The accuracy of the magnetic field calibration is high.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracyHigh"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy.high",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/high"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/low": {
      "abstract": [
        {
          "text": "The accuracy of the magnetic field calibration is low.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracyLow"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy.low",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/low"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/medium": {
      "abstract": [
        {
          "text": "The accuracy of the magnetic field calibration is medium.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracyMedium"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy.medium",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/medium"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/uncalibrated": {
      "abstract": [
        {
          "text": "The magnetic field estimate is not calibrated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uncalibrated"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/uncalibrated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagneticFieldCalibrationAccuracyUncalibrated"
        }
      ],
      "role": "symbol",
      "title": "CMMagneticFieldCalibrationAccuracy.uncalibrated",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/uncalibrated"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/uncalibrated",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/low",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/high"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMMagneticFieldCalibrationAccuracyMedium"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracyMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/uncalibrated",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/low",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMagneticFieldCalibrationAccuracy/high"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CMMagneticFieldCalibrationAccuracyMedium"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1low/title",
          "value": "CMMagneticFieldCalibrationAccuracyLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracyLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1medium/title",
          "value": "CMMagneticFieldCalibrationAccuracyMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracyMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1high/title",
          "value": "CMMagneticFieldCalibrationAccuracyHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracyHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1uncalibrated/title",
          "value": "CMMagneticFieldCalibrationAccuracyUncalibrated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy~1uncalibrated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracyUncalibrated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy/title",
          "value": "CMMagneticFieldCalibrationAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagneticFieldCalibrationAccuracy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagneticFieldCalibrationAccuracy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmmagneticfieldcalibrationaccuracy/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
