{
  "abstract": [
    {
      "text": "An object that provides the app with status updates while a sensitive content check",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "occurs for a video.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis",
        "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer",
        "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer/VideoAnalysisHandler"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer/VideoAnalysisHandler/progress"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So21SCSensitivityAnalyzerC24SensitiveContentAnalysisE05VideoE7HandlerC8progressSo10NSProgressCvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "progress"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSProgress",
        "text": "Progress"
      }
    ],
    "modules": [
      {
        "name": "SensitiveContentAnalysis"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "progress"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "final"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "progress"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSProgress",
              "text": "Progress"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis": {
      "abstract": [
        {
          "text": "Provide a safer experience in your app by detecting and alerting users to nudity",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "in images and videos before displaying them onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis",
      "kind": "symbol",
      "role": "collection",
      "title": "SensitiveContentAnalysis",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis"
    },
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer": {
      "abstract": [
        {
          "text": "An object that analyzes media for sensitive content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCSensitivityAnalyzer"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCSensitivityAnalyzer"
        }
      ],
      "role": "symbol",
      "title": "SCSensitivityAnalyzer",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis/scsensitivityanalyzer"
    },
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer/VideoAnalysisHandler": {
      "abstract": [
        {
          "text": "An object that checks if a video contains sensitive content and provides status updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VideoAnalysisHandler"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer/VideoAnalysisHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VideoAnalysisHandler"
        }
      ],
      "role": "symbol",
      "title": "SCSensitivityAnalyzer.VideoAnalysisHandler",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis/scsensitivityanalyzer/videoanalysishandler"
    },
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer/VideoAnalysisHandler/progress": {
      "abstract": [
        {
          "text": "An object that provides the app with status updates while a sensitive content check",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "occurs for a video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer/VideoAnalysisHandler/progress",
      "kind": "symbol",
      "role": "symbol",
      "title": "progress",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis/scsensitivityanalyzer/videoanalysishandler/progress"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress": {
      "abstract": [
        {
          "text": "An object that conveys ongoing progress to the user for a specified task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress",
      "kind": "symbol",
      "role": "symbol",
      "title": "Progress",
      "type": "topic",
      "url": "/documentation/foundation/progress"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSProgress/title",
          "value": "NSProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalyzer/title",
          "value": "SCSensitivityAnalyzer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalyzer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCSensitivityAnalyzer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalyzer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCSensitivityAnalyzer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensitivecontentanalysis/scsensitivityanalyzer/videoanalysishandler/progress"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
