{
  "abstract": [
    {
      "text": "The activity identifier associated with the entry.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.oslog/documentation/OSLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/activityIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)OSLogEntryFromProcess(py)activityIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "activityIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@os_activity_id_t",
        "text": "os_activity_id_t"
      }
    ],
    "modules": [
      {
        "name": "OSLog"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "activityIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "activityIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "activityIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@os_activity_id_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@os_activity_id_t",
              "text": "os_activity_id_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.oslog/documentation/OSLog": {
      "abstract": [
        {
          "text": "A unified logging system for the reading of historical data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog",
      "kind": "symbol",
      "role": "collection",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/oslog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess": {
      "abstract": [
        {
          "text": "A protocol that defines subclasses containing metadata about a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryFromProcess"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryFromProcess"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryFromProcess",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryfromprocess"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/activityIdentifier": {
      "abstract": [
        {
          "text": "The activity identifier associated with the entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@os_activity_id_t",
          "text": "os_activity_id_t"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/activityIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityIdentifier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "activityIdentifier",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryfromprocess/activityidentifier"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/process": {
      "abstract": [
        {
          "text": "The name of the process that made the entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "process"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/process",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "process"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "process",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryfromprocess/process"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/processIdentifier": {
      "abstract": [
        {
          "text": "The process identifier that made the entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/processIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processIdentifier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "processIdentifier",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryfromprocess/processidentifier"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/sender": {
      "abstract": [
        {
          "text": "The name of the binary image that made the entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/sender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sender"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sender",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryfromprocess/sender"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/threadIdentifier": {
      "abstract": [
        {
          "text": "The identifier of the thread that made the entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "threadIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/threadIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "threadIdentifier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "threadIdentifier",
      "type": "topic",
      "url": "/documentation/oslog/oslogentryfromprocess/threadidentifier"
    },
    "doc://com.externally.resolved.symbol/c:@T@os_activity_id_t": {
      "abstract": [
        {
          "text": "A number that uniquely identifies an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typedef"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint64_t",
          "text": "uint64_t"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_activity_id_t"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@os_activity_id_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_id_t",
      "type": "topic",
      "url": "/documentation/os/os_activity_id_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-the-Process-Source",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/process",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/processIdentifier",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/sender",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/threadIdentifier"
      ],
      "title": "Identifying the Process Source"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "activityIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.oslog/documentation/OSLog",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-the-Process-Source",
              "generated": true,
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/process",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/processIdentifier",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/sender",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryFromProcess/threadIdentifier"
              ],
              "title": "Identifying the Process Source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@os_activity_id_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@os_activity_id_t",
                    "text": "os_activity_id_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "activityIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess~1sender/title",
          "value": "sender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess~1sender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/title",
          "value": "OSLogEntryFromProcess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryFromProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryFromProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess~1activityIdentifier/title",
          "value": "activityIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess~1activityIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess~1threadIdentifier/title",
          "value": "threadIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess~1threadIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "threadIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess~1processIdentifier/title",
          "value": "processIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess~1processIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "processIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess~1process/title",
          "value": "process"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryFromProcess~1process/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "process"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/oslog/oslogentryfromprocess/activityidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/oslog/oslogentryfromprocess/activityidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
