{
  "abstract": [
    {
      "text": "The VM is saving its state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VZVirtualMachineState@VZVirtualMachineStateSaving",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "saving"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VZVirtualMachineStateSaving"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "VZVirtualMachine.State.saving"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "saving"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine": {
      "abstract": [
        {
          "text": "An object that manages the overall state and configuration of your VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtualMachine"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachine"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum": {
      "abstract": [
        {
          "text": "The execution states of the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error": {
      "abstract": [
        {
          "text": "The VM encountered an unrecoverable error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateError"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.error",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/error"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused": {
      "abstract": [
        {
          "text": "The framework has paused a started VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paused"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStatePaused"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.paused",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/paused"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing": {
      "abstract": [
        {
          "text": "The VM is pausing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pausing"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStatePausing"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.pausing",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/pausing"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring": {
      "abstract": [
        {
          "text": "The VM is restoring from a saved state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoring"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateRestoring"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.restoring",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/restoring"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming": {
      "abstract": [
        {
          "text": "The VM is resuming from a paused state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resuming"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateResuming"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.resuming",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/resuming"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running": {
      "abstract": [
        {
          "text": "The VM is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "running"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateRunning"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.running",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/running"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving": {
      "abstract": [
        {
          "text": "The VM is saving its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saving"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateSaving"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.saving",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/saving"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting": {
      "abstract": [
        {
          "text": "The VM is configuring the hardware preparing to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "starting"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateStarting"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.starting",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/starting"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped": {
      "abstract": [
        {
          "text": "The VM isn’t running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopped"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateStopped"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.stopped",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/stopped"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping": {
      "abstract": [
        {
          "text": "The VM is stopping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopping"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateStopping"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.stopping",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/stopping"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "States",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing"
      ],
      "title": "States"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZVirtualMachineStateSaving"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateSaving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "States",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing"
              ],
              "title": "States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "VZVirtualMachineStateSaving"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1running/title",
          "value": "VZVirtualMachineStateRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1running/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1error/title",
          "value": "VZVirtualMachineStateError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopping/title",
          "value": "VZVirtualMachineStateStopping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateStopping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopped/title",
          "value": "VZVirtualMachineStateStopped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateStopped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1paused/title",
          "value": "VZVirtualMachineStatePaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1paused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStatePaused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/title",
          "value": "VZVirtualMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1saving/title",
          "value": "VZVirtualMachineStateSaving"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1saving/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateSaving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/title",
          "value": "VZVirtualMachineState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1starting/title",
          "value": "VZVirtualMachineStateStarting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1starting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateStarting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1restoring/title",
          "value": "VZVirtualMachineStateRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1restoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1resuming/title",
          "value": "VZVirtualMachineStateResuming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1resuming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateResuming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1pausing/title",
          "value": "VZVirtualMachineStatePausing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1pausing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStatePausing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzvirtualmachine/state-swift.enum/saving"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzvirtualmachine/state-swift.enum/saving"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
