{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopped","kind":"identifier"}],"navigatorTitle":[{"text":"VZVirtualMachineStateStopped","kind":"identifier"}],"modules":[{"name":"Virtualization"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"11.0","name":"macOS"}],"title":"VZVirtualMachine.State.stopped","externalID":"c:@E@VZVirtualMachineState@VZVirtualMachineStateStopped"},"kind":"symbol","sections":[],"abstract":[{"text":"The VM isn’t running.","type":"text"}],"variants":[{"paths":["/documentation/virtualization/vzvirtualmachine/state-swift.enum/stopped"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/virtualization/vzvirtualmachine/state-swift.enum/stopped"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping"],"title":"States","anchor":"States"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"stopped","kind":"identifier"}],"languages":["swift"]}]},{"kind":"mentions","mentions":["doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine"]},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"This state is the initial state of the virtual machine.","type":"text"}]}]}],"references":{"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error":{"title":"VZVirtualMachine.State.error","navigatorTitle":[{"text":"VZVirtualMachineStateError","kind":"identifier"}],"url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum/error","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"abstract":[{"text":"The VM encountered an unrecoverable error.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped","navigatorTitle":[{"kind":"identifier","text":"VZVirtualMachineStateStopped"}],"title":"VZVirtualMachine.State.stopped","url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum/stopped","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The VM isn’t running."}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping":{"abstract":[{"type":"text","text":"The VM is stopping."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopping","kind":"identifier"}],"role":"symbol","type":"topic","title":"VZVirtualMachine.State.stopping","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping","url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum/stopping","kind":"symbol","navigatorTitle":[{"text":"VZVirtualMachineStateStopping","kind":"identifier"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running":{"abstract":[{"type":"text","text":"The VM is running."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"running","kind":"identifier"}],"role":"symbol","type":"topic","title":"VZVirtualMachine.State.running","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running","url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum/running","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VZVirtualMachineStateRunning"}]},"doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine":{"abstract":[{"type":"text","text":"Download a macOS restore image and install it in a new VM."}],"title":"Installing macOS on a Virtual Machine","identifier":"doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine","kind":"article","url":"/documentation/virtualization/installing-macos-on-a-virtual-machine","type":"topic","role":"article"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The VM is saving its state."}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving","type":"topic","url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum/saving","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"saving"}],"title":"VZVirtualMachine.State.saving","navigatorTitle":[{"kind":"identifier","text":"VZVirtualMachineStateSaving"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZVirtualMachine"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine","abstract":[{"type":"text","text":"An object that manages the overall state and configuration of your VM."}],"role":"symbol","title":"VZVirtualMachine","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VZVirtualMachine"}],"url":"/documentation/virtualization/vzvirtualmachine"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused":{"navigatorTitle":[{"text":"VZVirtualMachineStatePaused","kind":"identifier"}],"url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum/paused","abstract":[{"text":"The framework has paused a started VM.","type":"text"}],"kind":"symbol","title":"VZVirtualMachine.State.paused","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"paused"}],"role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused","type":"topic"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing":{"title":"VZVirtualMachine.State.pausing","navigatorTitle":[{"text":"VZVirtualMachineStatePausing","kind":"identifier"}],"url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum/pausing","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pausing","kind":"identifier"}],"abstract":[{"text":"The VM is pausing.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum":{"abstract":[{"type":"text","text":"The execution states of the VM."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"State","kind":"identifier"}],"role":"symbol","type":"topic","title":"VZVirtualMachine.State","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum","url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum","kind":"symbol","navigatorTitle":[{"text":"State","kind":"identifier"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring":{"navigatorTitle":[{"kind":"identifier","text":"VZVirtualMachineStateRestoring"}],"url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum/restoring","abstract":[{"type":"text","text":"The VM is restoring from a saved state."}],"kind":"symbol","title":"VZVirtualMachine.State.restoring","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"restoring"}],"role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring","type":"topic"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting":{"navigatorTitle":[{"kind":"identifier","text":"VZVirtualMachineStateStarting"}],"url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum/starting","abstract":[{"type":"text","text":"The VM is configuring the hardware preparing to run."}],"kind":"symbol","title":"VZVirtualMachine.State.starting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"starting"}],"role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting","type":"topic"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming":{"navigatorTitle":[{"kind":"identifier","text":"VZVirtualMachineStateResuming"}],"url":"/documentation/virtualization/vzvirtualmachine/state-swift.enum/resuming","abstract":[{"type":"text","text":"The VM is resuming from a paused state."}],"kind":"symbol","title":"VZVirtualMachine.State.resuming","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resuming"}],"role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"name":"macOS","introducedAt":"11.0","deprecated":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"VZVirtualMachineStateStopped","path":"/metadata/title","op":"replace"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"VZVirtualMachineStateStopped"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"States","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping"],"generated":true,"title":"States"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"VZVirtualMachineStateStopped","kind":"identifier"}],"platforms":["macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1error/title","value":"VZVirtualMachineStateError","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1error/fragments","value":[{"kind":"identifier","text":"VZVirtualMachineStateError"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopped/title","value":"VZVirtualMachineStateStopped","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopped/fragments","value":[{"kind":"identifier","text":"VZVirtualMachineStateStopped"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopping/title","value":"VZVirtualMachineStateStopping","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopping/fragments","value":[{"text":"VZVirtualMachineStateStopping","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1running/title","value":"VZVirtualMachineStateRunning","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1running/fragments","value":[{"text":"VZVirtualMachineStateRunning","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1saving/title","value":"VZVirtualMachineStateSaving","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1saving/fragments","value":[{"kind":"identifier","text":"VZVirtualMachineStateSaving"}],"op":"replace"},{"op":"replace","value":"VZVirtualMachine","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/title"},{"op":"replace","value":[{"kind":"identifier","text":"VZVirtualMachine"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"VZVirtualMachine"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/navigatorTitle"},{"op":"replace","value":"VZVirtualMachineStatePaused","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1paused/title"},{"op":"replace","value":[{"text":"VZVirtualMachineStatePaused","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1paused/fragments"},{"op":"replace","value":"VZVirtualMachineStatePausing","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1pausing/title"},{"op":"replace","value":[{"text":"VZVirtualMachineStatePausing","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1pausing/fragments"},{"op":"replace","value":"VZVirtualMachineState","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/title"},{"op":"replace","value":[{"kind":"identifier","text":"VZVirtualMachineState"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/fragments"},{"op":"replace","value":[{"text":"VZVirtualMachineState","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/navigatorTitle"},{"op":"replace","value":"VZVirtualMachineStateRestoring","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1restoring/title"},{"op":"replace","value":[{"kind":"identifier","text":"VZVirtualMachineStateRestoring"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1restoring/fragments"},{"op":"replace","value":"VZVirtualMachineStateStarting","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1starting/title"},{"op":"replace","value":[{"kind":"identifier","text":"VZVirtualMachineStateStarting"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1starting/fragments"},{"op":"replace","value":"VZVirtualMachineStateResuming","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1resuming/title"},{"op":"replace","value":[{"kind":"identifier","text":"VZVirtualMachineStateResuming"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1resuming/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}