{
  "abstract": [
    {
      "text": "The user’s daily goal for exercise time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/exerciseTimeGoal"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKActivitySummary(py)exerciseTimeGoal",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "exerciseTimeGoal"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKQuantity",
        "text": "HKQuantity"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "exerciseTimeGoal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "exerciseTimeGoal"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "exerciseTimeGoal"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKQuantity",
              "text": "HKQuantity"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object for this property must use time units.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivityMoveMode": {
      "abstract": [
        {
          "text": "Constants that specify the value measured by the Move ring on the user’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivityMoveMode"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivityMoveMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivityMoveMode"
        }
      ],
      "role": "symbol",
      "title": "HKActivityMoveMode",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitymovemode"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary": {
      "abstract": [
        {
          "text": "An object that contains the move, exercise, and stand data for a given day.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivitySummary"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivitySummary"
        }
      ],
      "role": "symbol",
      "title": "HKActivitySummary",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activeEnergyBurned": {
      "abstract": [
        {
          "text": "The amount of active energy the user burned during the specified day.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeEnergyBurned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activeEnergyBurned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activeEnergyBurned"
        }
      ],
      "role": "symbol",
      "title": "activeEnergyBurned",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/activeenergyburned"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activeEnergyBurnedGoal": {
      "abstract": [
        {
          "text": "The user’s daily goal for active energy burned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeEnergyBurnedGoal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activeEnergyBurnedGoal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activeEnergyBurnedGoal"
        }
      ],
      "role": "symbol",
      "title": "activeEnergyBurnedGoal",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/activeenergyburnedgoal"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activityMoveMode": {
      "abstract": [
        {
          "text": "The move mode that they system used for this activity summary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityMoveMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKActivityMoveMode",
          "text": "HKActivityMoveMode"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activityMoveMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityMoveMode"
        }
      ],
      "role": "symbol",
      "title": "activityMoveMode",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/activitymovemode"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleExerciseTime": {
      "abstract": [
        {
          "text": "The amount of time that the user has spent exercising during the specified day.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleExerciseTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleExerciseTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleExerciseTime"
        }
      ],
      "role": "symbol",
      "title": "appleExerciseTime",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/appleexercisetime"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleExerciseTimeGoal": {
      "abstract": [
        {
          "text": "The user’s daily exercise goal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleExerciseTimeGoal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleExerciseTimeGoal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleExerciseTimeGoal"
        }
      ],
      "role": "symbol",
      "title": "appleExerciseTimeGoal",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/appleexercisetimegoal"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleMoveTime": {
      "abstract": [
        {
          "text": "The amount of time the user spent performing activities that involve full-body movements during the specified day.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleMoveTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleMoveTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleMoveTime"
        }
      ],
      "role": "symbol",
      "title": "appleMoveTime",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/applemovetime"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleMoveTimeGoal": {
      "abstract": [
        {
          "text": "The user’s daily goal for move time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleMoveTimeGoal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleMoveTimeGoal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleMoveTimeGoal"
        }
      ],
      "role": "symbol",
      "title": "appleMoveTimeGoal",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/applemovetimegoal"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleStandHours": {
      "abstract": [
        {
          "text": "The number hours in the specified day during which the user has stood and moved for at least a minute per hour.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleStandHours"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleStandHours",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleStandHours"
        }
      ],
      "role": "symbol",
      "title": "appleStandHours",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/applestandhours"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleStandHoursGoal": {
      "abstract": [
        {
          "text": "The user’s daily goal for stand hours.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleStandHoursGoal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleStandHoursGoal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleStandHoursGoal"
        }
      ],
      "role": "symbol",
      "title": "appleStandHoursGoal",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/applestandhoursgoal"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/dateComponents(for:)": {
      "abstract": [
        {
          "text": "Date components that uniquely identify the day represented by the summary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateComponents"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8CalendarV",
          "text": "Calendar"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/dateComponents(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dateComponentsForCalendar:"
        }
      ],
      "role": "symbol",
      "title": "dateComponents(for:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/datecomponents(for:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/exerciseTimeGoal": {
      "abstract": [
        {
          "text": "The user’s daily goal for exercise time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exerciseTimeGoal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/exerciseTimeGoal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exerciseTimeGoal"
        }
      ],
      "role": "symbol",
      "title": "exerciseTimeGoal",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/exercisetimegoal"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/standHoursGoal": {
      "abstract": [
        {
          "text": "The user’s daily goal for stand hours.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standHoursGoal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/standHoursGoal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "standHoursGoal"
        }
      ],
      "role": "symbol",
      "title": "standHoursGoal",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary/standhoursgoal"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleStandHour": {
      "abstract": [
        {
          "text": "Categories that the system used to indicate whether the user stood during the sample’s duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleStandHour"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleStandHour",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleStandHour"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueAppleStandHour",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueapplestandhour"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity": {
      "abstract": [
        {
          "text": "An object that stores a value for a given unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantity"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-summarys-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activityMoveMode",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivityMoveMode",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activeEnergyBurned",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activeEnergyBurnedGoal",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleMoveTime",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleMoveTimeGoal",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleExerciseTime",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleExerciseTimeGoal",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleStandHours",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/standHoursGoal",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleStandHoursGoal",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleStandHour",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/dateComponents(for:)"
      ],
      "title": "Accessing the summary’s data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "exerciseTimeGoal"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exerciseTimeGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-summarys-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activityMoveMode",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivityMoveMode",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activeEnergyBurned",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/activeEnergyBurnedGoal",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleMoveTime",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleMoveTimeGoal",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleExerciseTime",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleExerciseTimeGoal",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleStandHours",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/standHoursGoal",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/appleStandHoursGoal",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleStandHour",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary/dateComponents(for:)"
              ],
              "title": "Accessing the summary’s data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HKQuantity",
                    "text": "HKQuantity"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "exerciseTimeGoal"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleStandHours/title",
          "value": "appleStandHours"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleStandHours/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleStandHours"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleExerciseTimeGoal/title",
          "value": "appleExerciseTimeGoal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleExerciseTimeGoal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleExerciseTimeGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1activityMoveMode/title",
          "value": "activityMoveMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1activityMoveMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityMoveMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleMoveTime/title",
          "value": "appleMoveTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleMoveTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleMoveTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/title",
          "value": "HKQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivityMoveMode/title",
          "value": "HKActivityMoveMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivityMoveMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivityMoveMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivityMoveMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivityMoveMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleExerciseTime/title",
          "value": "appleExerciseTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleExerciseTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleExerciseTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleStandHoursGoal/title",
          "value": "appleStandHoursGoal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleStandHoursGoal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleStandHoursGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary/title",
          "value": "HKActivitySummary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1activeEnergyBurnedGoal/title",
          "value": "activeEnergyBurnedGoal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1activeEnergyBurnedGoal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activeEnergyBurnedGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleMoveTimeGoal/title",
          "value": "appleMoveTimeGoal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1appleMoveTimeGoal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleMoveTimeGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1exerciseTimeGoal/title",
          "value": "exerciseTimeGoal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1exerciseTimeGoal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exerciseTimeGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleStandHour/title",
          "value": "HKCategoryValueAppleStandHour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleStandHour/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleStandHour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleStandHour/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleStandHour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1standHoursGoal/title",
          "value": "standHoursGoal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1standHoursGoal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "standHoursGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1dateComponents(for:)/title",
          "value": "dateComponentsForCalendar:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1dateComponents(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dateComponentsForCalendar:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1activeEnergyBurned/title",
          "value": "activeEnergyBurned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary~1activeEnergyBurned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activeEnergyBurned"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkactivitysummary/exercisetimegoal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkactivitysummary/exercisetimegoal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
