{
  "abstract": [
    {
      "text": "The mode in which to run the app when the action is performed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/activationMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIUserNotificationAction(py)activationMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "activationMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIUserNotificationActivationMode",
        "text": "UIUserNotificationActivationMode"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "activationMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "8.0",
        "message": "Use UserNotifications Framework's UNNotificationAction",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "8.0",
        "message": "Use UserNotifications Framework's UNNotificationAction",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use UserNotifications Framework's UNNotificationAction",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "activationMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "activationMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIUserNotificationActivationMode",
              "text": "UIUserNotificationActivationMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the value in this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode/foreground",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the value of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isAuthenticationRequired",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is assumed to be ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " regardless of its actual value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction": {
      "abstract": [
        {
          "text": "A custom action that your app can perform in response to a remote or local notification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserNotificationAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserNotificationAction"
        }
      ],
      "role": "symbol",
      "title": "UIUserNotificationAction",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/activationMode": {
      "abstract": [
        {
          "text": "The mode in which to run the app when the action is performed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserNotificationActivationMode",
          "text": "UIUserNotificationActivationMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/activationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activationMode"
        }
      ],
      "role": "symbol",
      "title": "activationMode",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/activationmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/behavior": {
      "abstract": [
        {
          "text": "The custom behavior (if any) that the action supports.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserNotificationActionBehavior",
          "text": "UIUserNotificationActionBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/behavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behavior"
        }
      ],
      "role": "symbol",
      "title": "behavior",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/behavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isAuthenticationRequired": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the user must unlock the device before the action is performed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAuthenticationRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isAuthenticationRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authenticationRequired"
        }
      ],
      "role": "symbol",
      "title": "isAuthenticationRequired",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/isauthenticationrequired"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isDestructive": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the action is destructive.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDestructive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isDestructive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destructive"
        }
      ],
      "role": "symbol",
      "title": "isDestructive",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/isdestructive"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/parameters": {
      "abstract": [
        {
          "text": "A dictionary of additional parameters to include with the action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/parameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parameters"
        }
      ],
      "role": "symbol",
      "title": "parameters",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/parameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode": {
      "abstract": [
        {
          "text": "Constants indicating whether the app should activate to the foreground or background.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserNotificationActivationMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserNotificationActivationMode"
        }
      ],
      "role": "symbol",
      "title": "UIUserNotificationActivationMode",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationactivationmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode/foreground": {
      "abstract": [
        {
          "text": "Activate the app and put it in the foreground.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foreground"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode/foreground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserNotificationActivationModeForeground"
        }
      ],
      "role": "symbol",
      "title": "UIUserNotificationActivationMode.foreground",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationactivationmode/foreground"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-actions-configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isAuthenticationRequired",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isDestructive",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/behavior",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/parameters"
      ],
      "title": "Getting the action’s configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "activationMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-actions-configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isAuthenticationRequired",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isDestructive",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/behavior",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/parameters"
              ],
              "title": "Getting the action’s configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UIUserNotificationActivationMode",
                    "text": "UIUserNotificationActivationMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "activationMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActivationMode/title",
          "value": "UIUserNotificationActivationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActivationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationActivationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActivationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationActivationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction/title",
          "value": "UIUserNotificationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1activationMode/title",
          "value": "activationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1activationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActivationMode~1foreground/title",
          "value": "UIUserNotificationActivationModeForeground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActivationMode~1foreground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationActivationModeForeground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1behavior/title",
          "value": "behavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1behavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1isAuthenticationRequired/title",
          "value": "authenticationRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1isAuthenticationRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authenticationRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1parameters/title",
          "value": "parameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1parameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1isDestructive/title",
          "value": "destructive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1isDestructive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destructive"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiusernotificationaction/activationmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiusernotificationaction/activationmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
