{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/uniformtypeidentifiers-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Uniform Type Identifiers"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "UniformTypeIdentifiers Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers": {
      "abstract": [
        {
          "text": "Provide uniform type identifiers that describe file types for storage or transfer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers",
      "kind": "symbol",
      "role": "collection",
      "title": "Uniform Type Identifiers",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeAHAP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeAHAP"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeAHAP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeAHAP",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypeahap"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_AVAILABLE_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UT_AVAILABLE_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_AVAILABLE_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "UT_AVAILABLE_BEGIN",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/ut_available_begin"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_AVAILABLE_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UT_AVAILABLE_END"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_AVAILABLE_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "UT_AVAILABLE_END",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/ut_available_end"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UT_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "UT_EXPORT",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/ut_export"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_EXPORT_CLASS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UT_EXPORT_CLASS"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_EXPORT_CLASS",
      "kind": "symbol",
      "role": "symbol",
      "title": "UT_EXPORT_CLASS",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/ut_export_class"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_SUBCLASSING_RESTRICTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UT_SUBCLASSING_RESTRICTED"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_SUBCLASSING_RESTRICTED",
      "kind": "symbol",
      "role": "symbol",
      "title": "UT_SUBCLASSING_RESTRICTED",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/ut_subclassing_restricted"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeAHAP"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_AVAILABLE_BEGIN",
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_AVAILABLE_END",
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_EXPORT",
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_EXPORT_CLASS",
                "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UT_SUBCLASSING_RESTRICTED"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uniformtypeidentifiers/uniformtypeidentifiers-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uniformtypeidentifiers/uniformtypeidentifiers-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
