{
  "abstract": [
    {
      "text": "A type that represents an Open Scripting Architecture script bundle.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeOSAScriptBundle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@UTTypeOSAScriptBundle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UTTypeOSAScriptBundle"
      }
    ],
    "modules": [
      {
        "name": "Uniform Type Identifiers"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UTTypeOSAScriptBundle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "UTTypeOSAScriptBundle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UTType",
              "text": "UTType"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UTTypeOSAScriptBundle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The identifier for this type is ",
              "type": "text"
            },
            {
              "code": "com.apple.applescript.script-bundle",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This type conforms to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeScript",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeBundle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePackage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers": {
      "abstract": [
        {
          "text": "Provide uniform type identifiers that describe file types for storage or transfer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers",
      "kind": "symbol",
      "role": "collection",
      "title": "Uniform Type Identifiers",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeAppleScript": {
      "abstract": [
        {
          "text": "A type that represents an AppleScript text-based script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeAppleScript"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeAppleScript",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeAppleScript",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypeapplescript"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeBundle": {
      "abstract": [
        {
          "text": "A base type that represents a directory that conforms to one of the bundle layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeBundle"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeBundle",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeBundle",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypebundle"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeJavaScript": {
      "abstract": [
        {
          "text": "A type that represents JavaScript source code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeJavaScript"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeJavaScript",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeJavaScript",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypejavascript"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeMakefile": {
      "abstract": [
        {
          "text": "A type that represents a Makefile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeMakefile"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeMakefile",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeMakefile",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypemakefile"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeOSAScript": {
      "abstract": [
        {
          "text": "A type that represents an Open Scripting Architecture binary script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeOSAScript"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeOSAScript",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeOSAScript",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypeosascript"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeOSAScriptBundle": {
      "abstract": [
        {
          "text": "A type that represents an Open Scripting Architecture script bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeOSAScriptBundle"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeOSAScriptBundle",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeOSAScriptBundle",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypeosascriptbundle"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePHPScript": {
      "abstract": [
        {
          "text": "A type that represents a PHP script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypePHPScript"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePHPScript",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypePHPScript",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypephpscript"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePackage": {
      "abstract": [
        {
          "text": "A base type that represents a packaged directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypePackage"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePackage",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypePackage",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypepackage"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePerlScript": {
      "abstract": [
        {
          "text": "A type that represents a Perl script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypePerlScript"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePerlScript",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypePerlScript",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypeperlscript"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePythonScript": {
      "abstract": [
        {
          "text": "A type that represents a Python script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypePythonScript"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePythonScript",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypePythonScript",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypepythonscript"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference": {
      "abstract": [
        {
          "text": "An object that represents a type of data to load, send, or receive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UTTypeReference"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTTypeReference"
        }
      ],
      "role": "symbol",
      "title": "UTTypeReference",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypereference"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeRubyScript": {
      "abstract": [
        {
          "text": "A type that represents a Ruby script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeRubyScript"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeRubyScript",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeRubyScript",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttyperubyscript"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeScript": {
      "abstract": [
        {
          "text": "A base type that represents any scripting language source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeScript"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeScript",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeScript",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypescript"
    },
    "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeShellScript": {
      "abstract": [
        {
          "text": "A base type that represents a shell script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UTTypeShellScript"
        }
      ],
      "identifier": "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeShellScript",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeShellScript",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttypeshellscript"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scripted-programming-language-sources",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeScript",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeAppleScript",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeJavaScript",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeOSAScript",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeMakefile",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeShellScript",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePythonScript",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeRubyScript",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePerlScript",
        "doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypePHPScript"
      ],
      "title": "Scripted programming language sources"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/title",
          "value": "UTType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UTType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UTType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uniformtypeidentifiers/uttypeosascriptbundle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
