{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeArchive","doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeZIP","doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeGZIP","doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeBZ2"],"generated":true,"title":"Compressed archives","anchor":"Compressed-archives"}],"identifier":{"url":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeAppleArchive","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"var","fragments":[{"kind":"identifier","text":"UTTypeAppleArchive"}],"roleHeading":"Global Variable","role":"symbol","externalID":"c:@UTTypeAppleArchive","navigatorTitle":[{"kind":"identifier","text":"UTTypeAppleArchive"}],"title":"UTTypeAppleArchive","platforms":[{"introducedAt":"14.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"14.0","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"14.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"11.0","unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"introducedAt":"14.0","unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false},{"beta":false,"name":"watchOS","deprecated":false,"introducedAt":"7.0","unavailable":false}],"modules":[{"name":"Uniform Type Identifiers"}]},"abstract":[{"type":"text","text":"A type that represents an Apple archive of files and directories."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference","preciseIdentifier":"c:objc(cs)UTType","text":"UTType","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UTTypeAppleArchive","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier for this type is "},{"code":"com.apple.archive","type":"codeVoice"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This type conforms to "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeData"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeArchive"},{"type":"text","text":"."}]}],"kind":"content"}],"variants":[{"paths":["/documentation/uniformtypeidentifiers/uttypeapplearchive"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference":{"title":"UTTypeReference","kind":"symbol","type":"topic","navigatorTitle":[{"text":"UTTypeReference","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UTTypeReference","kind":"identifier"}],"identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeReference","abstract":[{"text":"An object that represents a type of data to load, send, or receive.","type":"text"}],"url":"/documentation/uniformtypeidentifiers/uttypereference","role":"symbol"},"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeAppleArchive":{"fragments":[{"kind":"identifier","text":"UTTypeAppleArchive"}],"type":"topic","url":"/documentation/uniformtypeidentifiers/uttypeapplearchive","kind":"symbol","abstract":[{"text":"A type that represents an Apple archive of files and directories.","type":"text"}],"role":"symbol","title":"UTTypeAppleArchive","identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeAppleArchive"},"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeBZ2":{"fragments":[{"kind":"identifier","text":"UTTypeBZ2"}],"type":"topic","url":"/documentation/uniformtypeidentifiers/uttypebz2","kind":"symbol","abstract":[{"text":"A type that represents a bzip2 archive.","type":"text"}],"role":"symbol","title":"UTTypeBZ2","identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeBZ2"},"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeZIP":{"fragments":[{"kind":"identifier","text":"UTTypeZIP"}],"type":"topic","role":"symbol","url":"/documentation/uniformtypeidentifiers/uttypezip","kind":"symbol","identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeZIP","abstract":[{"text":"A type that represents a zip archive.","type":"text"}],"title":"UTTypeZIP"},"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeArchive":{"identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeArchive","title":"UTTypeArchive","abstract":[{"text":"A base type that represents an archive of files and directories.","type":"text"}],"fragments":[{"kind":"identifier","text":"UTTypeArchive"}],"role":"symbol","kind":"symbol","url":"/documentation/uniformtypeidentifiers/uttypearchive","type":"topic"},"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeData":{"title":"UTTypeData","role":"symbol","identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeData","url":"/documentation/uniformtypeidentifiers/uttypedata","kind":"symbol","type":"topic","abstract":[{"text":"A base type that represents any sort of byte stream, including files and in-memory data.","type":"text"}],"fragments":[{"text":"UTTypeData","kind":"identifier"}]},"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers":{"abstract":[{"text":"Provide uniform type identifiers that describe file types for storage or transfer.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers","role":"collection","title":"Uniform Type Identifiers","type":"topic","url":"/documentation/uniformtypeidentifiers"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","role":"overview","title":"Technologies","type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}]},"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeGZIP":{"fragments":[{"kind":"identifier","text":"UTTypeGZIP"}],"type":"topic","url":"/documentation/uniformtypeidentifiers/uttypegzip","abstract":[{"text":"A type that represents a GNU zip archive.","type":"text"}],"identifier":"doc://com.apple.uniformtypeidentifiers/documentation/UniformTypeIdentifiers/UTTypeGZIP","role":"symbol","title":"UTTypeGZIP","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"UTType","path":"/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/title"},{"op":"replace","value":[{"kind":"identifier","text":"UTType"}],"path":"/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UTType"}],"path":"/references/doc:~1~1com.apple.uniformtypeidentifiers~1documentation~1UniformTypeIdentifiers~1UTTypeReference/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}