{
  "abstract": [
    {
      "text": "The item collapses and expands using a constraint animation, with a constraint priority of the item’s holding priority.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/useConstraints"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSSplitViewItemCollapseBehavior@NSSplitViewItemCollapseBehaviorUseConstraints",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "useConstraints"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSplitViewItemCollapseBehaviorUseConstraints"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSSplitViewItem.CollapseBehavior.useConstraints"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "useConstraints"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This collapse behavior may result in a partial internal content resize and window resize, and doesn’t affect whether the window stays onscreen. You can use external constraints to adjust how the animation affects the item, its sibling items, and the window’s size and position.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem": {
      "abstract": [
        {
          "text": "An item in a split view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSplitViewItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewItem"
        }
      ],
      "role": "symbol",
      "title": "NSSplitViewItem",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the split view item’s collapsing behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CollapseBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CollapseBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSSplitViewItem.CollapseBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem/collapsebehavior-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/default": {
      "abstract": [
        {
          "text": "The item uses the default collapsing behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewItemCollapseBehaviorDefault"
        }
      ],
      "role": "symbol",
      "title": "NSSplitViewItem.CollapseBehavior.default",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem/collapsebehavior-swift.enum/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/preferResizingSiblingsWithFixedSplitView": {
      "abstract": [
        {
          "text": "The item’s preference is to resize the other split panes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferResizingSiblingsWithFixedSplitView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/preferResizingSiblingsWithFixedSplitView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewItemCollapseBehaviorPreferResizingSiblingsWithFixedSplitView"
        }
      ],
      "role": "symbol",
      "title": "NSSplitViewItem.CollapseBehavior.preferResizingSiblingsWithFixedSplitView",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem/collapsebehavior-swift.enum/preferresizingsiblingswithfixedsplitview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/preferResizingSplitViewWithFixedSiblings": {
      "abstract": [
        {
          "text": "The item’s preference is to keep the other panes at their current size and position onscreen, potentially growing or shrinking the window in the direction to best preserve that.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferResizingSplitViewWithFixedSiblings"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/preferResizingSplitViewWithFixedSiblings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewItemCollapseBehaviorPreferResizingSplitViewWithFixedSiblings"
        }
      ],
      "role": "symbol",
      "title": "NSSplitViewItem.CollapseBehavior.preferResizingSplitViewWithFixedSiblings",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem/collapsebehavior-swift.enum/preferresizingsplitviewwithfixedsiblings"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/useConstraints": {
      "abstract": [
        {
          "text": "The item collapses and expands using a constraint animation, with a constraint priority of the item’s holding priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useConstraints"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/useConstraints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewItemCollapseBehaviorUseConstraints"
        }
      ],
      "role": "symbol",
      "title": "NSSplitViewItem.CollapseBehavior.useConstraints",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewitem/collapsebehavior-swift.enum/useconstraints"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/default",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/preferResizingSplitViewWithFixedSiblings",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/preferResizingSiblingsWithFixedSplitView"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSplitViewItemCollapseBehaviorUseConstraints"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItemCollapseBehaviorUseConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/default",
                "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/preferResizingSplitViewWithFixedSiblings",
                "doc://com.apple.appkit/documentation/AppKit/NSSplitViewItem/CollapseBehavior-swift.enum/preferResizingSiblingsWithFixedSplitView"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSSplitViewItemCollapseBehaviorUseConstraints"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum~1preferResizingSplitViewWithFixedSiblings/title",
          "value": "NSSplitViewItemCollapseBehaviorPreferResizingSplitViewWithFixedSiblings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum~1preferResizingSplitViewWithFixedSiblings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItemCollapseBehaviorPreferResizingSplitViewWithFixedSiblings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum~1preferResizingSiblingsWithFixedSplitView/title",
          "value": "NSSplitViewItemCollapseBehaviorPreferResizingSiblingsWithFixedSplitView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum~1preferResizingSiblingsWithFixedSplitView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItemCollapseBehaviorPreferResizingSiblingsWithFixedSplitView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum/title",
          "value": "NSSplitViewItemCollapseBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItemCollapseBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItemCollapseBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum~1default/title",
          "value": "NSSplitViewItemCollapseBehaviorDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItemCollapseBehaviorDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum~1useConstraints/title",
          "value": "NSSplitViewItemCollapseBehaviorUseConstraints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem~1CollapseBehavior-swift.enum~1useConstraints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItemCollapseBehaviorUseConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem/title",
          "value": "NSSplitViewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssplitviewitem/collapsebehavior-swift.enum/useconstraints"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssplitviewitem/collapsebehavior-swift.enum/useconstraints"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
