{
  "abstract": [
    {
      "text": "The person has yet to choose whether to allow the browser app to access passkeys stored on the keychain, or managed by third-party credential managers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/notDetermined"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationState@ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notDetermined"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ASAuthorizationWebBrowserPublicKeyCredentialManager.AuthorizationState.notDetermined"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notDetermined"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authenticating-people-by-using-passkeys-in-browser-apps"
      ]
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager": {
      "abstract": [
        {
          "text": "A class that you use to request access to a person’s passkeys in a web browser, and that reports on the access status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationWebBrowserPublicKeyCredentialManager"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationWebBrowserPublicKeyCredentialManager"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationWebBrowserPublicKeyCredentialManager",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowserpublickeycredentialmanager"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState": {
      "abstract": [
        {
          "text": "An enumeration of values that indicate whether the browser app has access to a person’s passkeys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationState"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationState"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationWebBrowserPublicKeyCredentialManager.AuthorizationState",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowserpublickeycredentialmanager/authorizationstate"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/authorized": {
      "abstract": [
        {
          "text": "Someone allows the browser app to use passkeys stored in the keychain, and managed by third-party credential manager apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateAuthorized"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationWebBrowserPublicKeyCredentialManager.AuthorizationState.authorized",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowserpublickeycredentialmanager/authorizationstate/authorized"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/denied": {
      "abstract": [
        {
          "text": "Someone forbids the browser app to use passkeys stored in the keychain, and managed by third-party credential manager apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateDenied"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationWebBrowserPublicKeyCredentialManager.AuthorizationState.denied",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowserpublickeycredentialmanager/authorizationstate/denied"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/notDetermined": {
      "abstract": [
        {
          "text": "The person has yet to choose whether to allow the browser app to access passkeys stored on the keychain, or managed by third-party credential managers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationWebBrowserPublicKeyCredentialManager.AuthorizationState.notDetermined",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowserpublickeycredentialmanager/authorizationstate/notdetermined"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authenticating-people-by-using-passkeys-in-browser-apps": {
      "abstract": [
        {
          "text": "Provide a secure and convenient alternative to passwords.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/authenticating-people-by-using-passkeys-in-browser-apps",
      "kind": "article",
      "role": "article",
      "title": "Authenticating people by using passkeys in browser apps",
      "type": "topic",
      "url": "/documentation/authenticationservices/authenticating-people-by-using-passkeys-in-browser-apps"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Passkey-access-states",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/authorized",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/denied"
      ],
      "title": "Passkey access states"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Passkey-access-states",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/authorized",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPublicKeyCredentialManager/AuthorizationState/denied"
              ],
              "title": "Passkey access states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager~1AuthorizationState~1authorized/title",
          "value": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager~1AuthorizationState~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager~1AuthorizationState~1denied/title",
          "value": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager~1AuthorizationState~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager/title",
          "value": "ASAuthorizationWebBrowserPublicKeyCredentialManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserPublicKeyCredentialManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserPublicKeyCredentialManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager~1AuthorizationState~1notDetermined/title",
          "value": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager~1AuthorizationState~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationStateNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager~1AuthorizationState/title",
          "value": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager~1AuthorizationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPublicKeyCredentialManager~1AuthorizationState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserPublicKeyCredentialManagerAuthorizationState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationwebbrowserpublickeycredentialmanager/authorizationstate/notdetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationwebbrowserpublickeycredentialmanager/authorizationstate/notdetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
