{
  "abstract": [
    {
      "text": "Changes the enabled state of the trigger.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMTrigger"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/enable(_:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HMTrigger(im)enable:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "enable"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ((any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enable:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "enable(_:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "enable"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "enable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ((any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "enable"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "enable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "code": "TRUE",
                  "type": "codeVoice"
                },
                {
                  "text": " to enable the trigger, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to disable it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "enable"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block executed after the request is processed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " on success; otherwise, error object indicating the reason for failure.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "error",
                        "type": "text"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completion"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Triggers can only be enabled when they are in a home. You add triggers to a home using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome/addTrigger(_:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When a trigger is enabled its firing conditions are checked for validity and the system starts tracking the trigger and when it will next fire.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to having valid firing conditions, to be successfully enabled a trigger must have at least one action set associated with it, and every action set associated with the trigger must have at least one action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome": {
      "abstract": [
        {
          "text": "The primary unit of living space, typically composed of rooms organized into zones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "role": "symbol",
      "title": "HMHome",
      "type": "topic",
      "url": "/documentation/homekit/hmhome"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome/addTrigger(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Adds a trigger to the home.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMTrigger",
          "text": "HMTrigger"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome/addTrigger(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addTrigger:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "addTrigger(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhome/addtrigger(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTrigger": {
      "abstract": [
        {
          "text": "An abstract base class for triggering actions based on a set of conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMTrigger"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMTrigger"
        }
      ],
      "role": "symbol",
      "title": "HMTrigger",
      "type": "topic",
      "url": "/documentation/homekit/hmtrigger"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/enable(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Changes the enabled state of the trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/enable(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enable:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enable(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmtrigger/enable(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/isEnabled": {
      "abstract": [
        {
          "text": "State of the trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/homekit/hmtrigger/isenabled"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/lastFireDate": {
      "abstract": [
        {
          "text": "The last time this trigger fired.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastFireDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/lastFireDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastFireDate"
        }
      ],
      "role": "symbol",
      "title": "lastFireDate",
      "type": "topic",
      "url": "/documentation/homekit/hmtrigger/lastfiredate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/name": {
      "abstract": [
        {
          "text": "The name of the trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/homekit/hmtrigger/name"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/uniqueIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for this trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniqueIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/uniqueIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniqueIdentifier"
        }
      ],
      "role": "symbol",
      "title": "uniqueIdentifier",
      "type": "topic",
      "url": "/documentation/homekit/hmtrigger/uniqueidentifier"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/updateName(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Updates the name of the trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/updateName(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateName:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "updateName(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmtrigger/updatename(_:completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Triggers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/name",
        "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/updateName(_:completionHandler:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/isEnabled",
        "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/lastFireDate",
        "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/uniqueIdentifier"
      ],
      "title": "Managing Triggers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "enable:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enable:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMTrigger"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Triggers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/name",
                "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/updateName(_:completionHandler:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/isEnabled",
                "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/lastFireDate",
                "doc://com.apple.homekit/documentation/HomeKit/HMTrigger/uniqueIdentifier"
              ],
              "title": "Managing Triggers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "enable:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "enable"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "",
                        "type": "text"
                      },
                      {
                        "code": "TRUE",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to enable the trigger, ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to disable it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "enable"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The block executed after the request is processed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " on success; otherwise, error object indicating the reason for failure.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "error",
                              "type": "text"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completion"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1enable(_:completionHandler:)/title",
          "value": "enable:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1enable(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enable:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1uniqueIdentifier/title",
          "value": "uniqueIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1uniqueIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uniqueIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1lastFireDate/title",
          "value": "lastFireDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1lastFireDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastFireDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/title",
          "value": "HMHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger/title",
          "value": "HMTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome~1addTrigger(_:completionHandler:)/title",
          "value": "addTrigger:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome~1addTrigger(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addTrigger:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1updateName(_:completionHandler:)/title",
          "value": "updateName:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger~1updateName(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateName:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmtrigger/enable(_:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmtrigger/enable(_:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
