{
  "abstract": [
    {
      "text": "The zone, if any, from which this mesh buffer was created.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalkit/documentation/MetalKit",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/zone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTKMeshBuffer(py)zone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "zone"
      }
    ],
    "modules": [
      {
        "name": "MetalKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "zone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "zone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)MDLMeshBufferZone",
              "text": "id<MDLMeshBufferZone>"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "zone"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A single ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal/MTLBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is allocated for each zone, but each zone can have multiple ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects, each with its own ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/offset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Though there may be many ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects for a model, they are all backed with the same contiguous ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal/MTLBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is used, Model I/O attempts to load all vertex and index data of a single mesh into a single zone. This allows the GPU to achieve a higher cache hit rate when drawing the mesh.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Metal/MTLBuffer": {
      "abstract": [
        {
          "text": "A resource that stores data in a format defined by your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLResource",
          "text": "MTLResource"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLBuffer",
      "type": "topic",
      "url": "/documentation/Metal/MTLBuffer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalkit/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/metalkit"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer": {
      "abstract": [
        {
          "text": "A buffer that backs the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMeshBuffer"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMeshBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTKMeshBuffer",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbuffer"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/allocator": {
      "abstract": [
        {
          "text": "The allocator object used to create this mesh buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTKMeshBufferAllocator",
          "text": "MTKMeshBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/allocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allocator"
        }
      ],
      "role": "symbol",
      "title": "allocator",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbuffer/allocator"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/offset": {
      "abstract": [
        {
          "text": "The byte offset of the data within the Metal buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/offset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "offset"
        }
      ],
      "role": "symbol",
      "title": "offset",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbuffer/offset"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/type": {
      "abstract": [
        {
          "text": "The type of data contained in the originating Model I/O buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMeshBufferType",
          "text": "MDLMeshBufferType"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbuffer/type"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/zone": {
      "abstract": [
        {
          "text": "The zone, if any, from which this mesh buffer was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "zone"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/zone",
      "kind": "symbol",
      "role": "symbol",
      "title": "zone",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbuffer/zone"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator": {
      "abstract": [
        {
          "text": "An interface for allocating a MetalKit buffer that backs the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMeshBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMeshBufferAllocator"
        }
      ],
      "role": "symbol",
      "title": "MTKMeshBufferAllocator",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbufferallocator"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Originating-Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/allocator",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer/type"
      ],
      "title": "Originating Objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLBuffer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLBuffer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLResource",
              "text": "MTLResource"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer~1offset/title",
          "value": "offset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer~1offset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "offset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer~1allocator/title",
          "value": "allocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer~1allocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/title",
          "value": "MTKMeshBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/title",
          "value": "MTKMeshBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalkit/mtkmeshbuffer/zone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
