{
  "abstract": [
    {
      "text": "Grant access to user accounts and the keychain by creating a smart card app extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/authenticating-users-with-a-cryptographic-token"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CryptoTokenKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Authenticating Users with a Cryptographic Token"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A typical use of hardware-based cryptographic tokens is two-factor authentication. This kind of authentication enhances security by making users establish their identity in two ways: with something they have (like a token that’s a USB-based smart card) and with something they know (a password that unlocks the token). A misplaced token is useless without the password. A compromised password provides no access without the physical token.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS, you can write an app extension that enables the system to authenticate users possessing a token. A driver you supply allows the system to establish the presence of the token in the system and confirm that the user has a password or PIN that unlocks the token.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Ensure-the-Token-Meets-Minimum-Requirements",
          "level": 3,
          "text": "Ensure the Token Meets Minimum Requirements",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before writing the app extension, make sure the token you’re trying to support meets certain basic prerequisites. To do this, you may need to obtain technical documentation from the token’s manufacturer. The exact requirements depend on how you plan to use it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To authenticate user logins, the token must contain at least one cryptographic key. This key must be capable of creating a cryptographic signature using an algorithm from one of the following families:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Elliptic curve signature digest X962",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "RSA signature digest PSS",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "RSA signature digest PKCS1v15",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Additionally, to use the token for unlocking the keychain, make sure it contains at least one of the following keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A 256-bit elliptic curve key of type ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Security/kSecAttrKeyTypeECSECPrimeRandom",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". This key must support the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/ecdhKeyExchangeStandard",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " key exchange algorithm.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A 2048-, 3072-, or 4096-bit RSA key of type ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Security/kSecAttrKeyTypeRSA",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". This key must support decryption with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/rsaEncryptionOAEPSHA256",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " algorithm.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To support an RSA option in either of the above use cases, the token hardware must either implement the specific RSA signature or decryption algorithm that the key supports, or simply implement the raw variant (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/rsaSignatureRaw",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for login, or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/rsaEncryptionRaw",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for keychain unlock). When the hardware provides only the raw operation, macOS automatically handles any needed padding.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-the-Smart-Card-App-Extension",
          "level": 3,
          "text": "Create the Smart Card App Extension",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you’re ready to begin coding, use Xcode to create an app extension target inside a new, empty macOS host app. Xcode provides a smart card app extension template that produces both the target and a group of files to get you started.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, for a token extension that you name ",
              "type": "text"
            },
            {
              "code": "TokenExtension",
              "type": "codeVoice"
            },
            {
              "text": ", Xcode produces the target plus an entitlements file, an ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file, and the three source files in a new folder within the project:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2940047",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about working with app extensions in general, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/app-extensions/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The host app for this kind of extension typically contains no functionality. Instead, it exists only as a delivery mechanism for the extension.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "A smart card app extension has no UI component. The system handles all user interaction associated with authenticating the user. Instead, your ",
              "type": "text"
            },
            {
              "code": "TokenDriver",
              "type": "codeVoice"
            },
            {
              "text": " class—derived from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardTokenDriver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class—acts as the entry point for the extension. More precisely, the ",
              "type": "text"
            },
            {
              "code": "NSExtensionAttributes",
              "type": "codeVoice"
            },
            {
              "text": " subdictionary of the ",
              "type": "text"
            },
            {
              "code": "NSExtension",
              "type": "codeVoice"
            },
            {
              "text": " dictionary in the ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file has a key ",
              "type": "text"
            },
            {
              "code": "com.apple.ctk.driver-class",
              "type": "codeVoice"
            },
            {
              "text": " that names the entry point class. Xcode sets this for you as part of the template:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2940045",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You supply functionality for the ",
              "type": "text"
            },
            {
              "code": "Token",
              "type": "codeVoice"
            },
            {
              "text": " class (derived from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardToken",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class) and ",
              "type": "text"
            },
            {
              "code": "TokenSession",
              "type": "codeVoice"
            },
            {
              "text": " class (derived from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardTokenSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class) that is specific to the token hardware you are supporting. These pieces work together to form the app extension:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2940884",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Register-the-Extension-with-SecurityAgent",
          "level": 3,
          "text": "Register the Extension with SecurityAgent",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To activate the app extension and make the token available to the system for authentication, you launch the extension’s hosting app as the ",
              "type": "text"
            },
            {
              "code": "_securityagent",
              "type": "codeVoice"
            },
            {
              "text": " user:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "sudo -u _securityagent /Applications/HostApp.app/Contents/MacOS/HostApp"
          ],
          "syntax": "shell",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The system prompts for an administrative password before executing this call.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The hosting app may in fact do nothing more than exit cleanly, but the act of running it has the side effect of registering its app extension with the system. You only need to do this once, typically during a managed installation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit": {
      "abstract": [
        {
          "text": "Access security tokens and the cryptographic assets they store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CryptoTokenKit",
      "type": "topic",
      "url": "/documentation/cryptotokenkit"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardToken": {
      "abstract": [
        {
          "text": "A representation of a smart card based cryptographic token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKSmartCardToken"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKSmartCardToken"
        }
      ],
      "role": "symbol",
      "title": "TKSmartCardToken",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksmartcardtoken"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardTokenDriver": {
      "abstract": [
        {
          "text": "The driver that acts as an entry point for smart card app extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKSmartCardTokenDriver"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardTokenDriver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKSmartCardTokenDriver"
        }
      ],
      "role": "symbol",
      "title": "TKSmartCardTokenDriver",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksmartcardtokendriver"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardTokenSession": {
      "abstract": [
        {
          "text": "A token session that is based on a smart card token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKSmartCardTokenSession"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardTokenSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKSmartCardTokenSession"
        }
      ],
      "role": "symbol",
      "title": "TKSmartCardTokenSession",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksmartcardtokensession"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/configuring-smart-card-authentication": {
      "abstract": [
        {
          "text": "Set preferences for smart card authentication operations, including those on managed devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/configuring-smart-card-authentication",
      "kind": "article",
      "role": "article",
      "title": "Configuring Smart Card Authentication",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/configuring-smart-card-authentication"
    },
    "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/ecdhKeyExchangeStandard": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ecdhKeyExchangeStandard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/ecdhKeyExchangeStandard",
      "kind": "symbol",
      "role": "symbol",
      "title": "ecdhKeyExchangeStandard",
      "type": "topic",
      "url": "/documentation/Security/SecKeyAlgorithm/ecdhKeyExchangeStandard"
    },
    "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/rsaEncryptionOAEPSHA256": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rsaEncryptionOAEPSHA256"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/rsaEncryptionOAEPSHA256",
      "kind": "symbol",
      "role": "symbol",
      "title": "rsaEncryptionOAEPSHA256",
      "type": "topic",
      "url": "/documentation/Security/SecKeyAlgorithm/rsaEncryptionOAEPSHA256"
    },
    "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/rsaEncryptionRaw": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rsaEncryptionRaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/rsaEncryptionRaw",
      "kind": "symbol",
      "role": "symbol",
      "title": "rsaEncryptionRaw",
      "type": "topic",
      "url": "/documentation/Security/SecKeyAlgorithm/rsaEncryptionRaw"
    },
    "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/rsaSignatureRaw": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rsaSignatureRaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/SecKeyAlgorithm/rsaSignatureRaw",
      "kind": "symbol",
      "role": "symbol",
      "title": "rsaSignatureRaw",
      "type": "topic",
      "url": "/documentation/Security/SecKeyAlgorithm/rsaSignatureRaw"
    },
    "doc://com.apple.documentation/documentation/Security/kSecAttrKeyTypeECSECPrimeRandom": {
      "abstract": [
        {
          "text": "Elliptic curve algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrKeyTypeECSECPrimeRandom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/kSecAttrKeyTypeECSECPrimeRandom",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAttrKeyTypeECSECPrimeRandom",
      "type": "topic",
      "url": "/documentation/Security/kSecAttrKeyTypeECSECPrimeRandom"
    },
    "doc://com.apple.documentation/documentation/Security/kSecAttrKeyTypeRSA": {
      "abstract": [
        {
          "text": "RSA algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSecAttrKeyTypeRSA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/kSecAttrKeyTypeRSA",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSecAttrKeyTypeRSA",
      "type": "topic",
      "url": "/documentation/Security/kSecAttrKeyTypeRSA"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/app-extensions/": {
      "identifier": "https://developer.apple.com/app-extensions/",
      "title": "App Extensions",
      "titleInlineContent": [
        {
          "text": "App Extensions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/app-extensions/"
    },
    "media-2940045": {
      "alt": "Screenshot of Xcode showing the Info.plist file of the TokenExtension, highlighting the driver class item.",
      "identifier": "media-2940045",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fe4784f0d2bed0cb08f563bb05c4da01/media-2940045@2x.png"
        }
      ]
    },
    "media-2940047": {
      "alt": "Screenshot of Xcode showing the target and files generated from the smart card extension template.",
      "identifier": "media-2940047",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4e427754f0434c685963118474d91ad4/media-2940047@2x.png"
        }
      ]
    },
    "media-2940884": {
      "alt": "Diagram showing the interconnections between the user, authentication services, your app extension, and the external smart card.",
      "identifier": "media-2940884",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5a882b84cfef7b2dfdec6c940a5428cc/media-2940884@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Smart-Card-App-Extensions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/configuring-smart-card-authentication",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardTokenDriver",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardToken",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardTokenSession"
      ],
      "title": "Smart Card App Extensions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Smart-Card-App-Extensions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/configuring-smart-card-authentication",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardTokenDriver",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardToken",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardTokenSession"
              ],
              "title": "Smart Card App Extensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardToken/title",
          "value": "TKSmartCardToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardToken/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardTokenDriver/title",
          "value": "TKSmartCardTokenDriver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardTokenDriver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardTokenDriver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardTokenDriver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardTokenDriver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardTokenSession/title",
          "value": "TKSmartCardTokenSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardTokenSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardTokenSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardTokenSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardTokenSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1kSecAttrKeyTypeECSECPrimeRandom/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSecAttrKeyTypeECSECPrimeRandom"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecKeyAlgorithm~1rsaEncryptionOAEPSHA256/title",
          "value": "kSecKeyAlgorithmRSAEncryptionOAEPSHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecKeyAlgorithm~1rsaEncryptionOAEPSHA256/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeyAlgorithm",
              "text": "SecKeyAlgorithm"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSecKeyAlgorithmRSAEncryptionOAEPSHA256"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecKeyAlgorithm~1rsaEncryptionRaw/title",
          "value": "kSecKeyAlgorithmRSAEncryptionRaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecKeyAlgorithm~1rsaEncryptionRaw/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeyAlgorithm",
              "text": "SecKeyAlgorithm"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSecKeyAlgorithmRSAEncryptionRaw"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecKeyAlgorithm~1ecdhKeyExchangeStandard/title",
          "value": "kSecKeyAlgorithmECDHKeyExchangeStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecKeyAlgorithm~1ecdhKeyExchangeStandard/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeyAlgorithm",
              "text": "SecKeyAlgorithm"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSecKeyAlgorithmECDHKeyExchangeStandard"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecKeyAlgorithm~1rsaSignatureRaw/title",
          "value": "kSecKeyAlgorithmRSASignatureRaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1SecKeyAlgorithm~1rsaSignatureRaw/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecKeyAlgorithm",
              "text": "SecKeyAlgorithm"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSecKeyAlgorithmRSASignatureRaw"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1kSecAttrKeyTypeRSA/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSecAttrKeyTypeRSA"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cryptotokenkit/authenticating-users-with-a-cryptographic-token"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cryptotokenkit/authenticating-users-with-a-cryptographic-token"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
