{
  "abstract": [
    {
      "text": "An interface to all available smart card reader slots.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TKSmartCardSlotManager",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TKSmartCardSlotManager"
      }
    ],
    "modules": [
      {
        "name": "CryptoTokenKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TKSmartCardSlotManager"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "TKSmartCardSlotManager"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TKSmartCardSlotManager"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Get a list of all known smart card reader slots in the system using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/slotNames",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, and access individual slots by name using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/getSlot(withName:reply:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.smartcard",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " entitlement is required in order to use ",
                  "type": "text"
                },
                {
                  "code": "TKSmartCardSlotManager",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit": {
      "abstract": [
        {
          "text": "Access security tokens and the cryptographic assets they store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CryptoTokenKit",
      "type": "topic",
      "url": "/documentation/cryptotokenkit"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCard": {
      "abstract": [
        {
          "text": "A representation of a smart card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKSmartCard"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKSmartCard"
        }
      ],
      "role": "symbol",
      "title": "TKSmartCard",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksmartcard"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlot": {
      "abstract": [
        {
          "text": "A single smart card reader slot in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKSmartCardSlot"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKSmartCardSlot"
        }
      ],
      "role": "symbol",
      "title": "TKSmartCardSlot",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksmartcardslot"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager": {
      "abstract": [
        {
          "text": "An interface to all available smart card reader slots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKSmartCardSlotManager"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKSmartCardSlotManager"
        }
      ],
      "role": "symbol",
      "title": "TKSmartCardSlotManager",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksmartcardslotmanager"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/default": {
      "abstract": [
        {
          "text": "The shared singleton Smart Card reader slot manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TKSmartCardSlotManager",
          "text": "TKSmartCardSlotManager"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultManager"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksmartcardslotmanager/default"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/getSlot(withName:reply:)": {
      "abstract": [
        {
          "text": "Asynchronously calls a block with a Smart Card reader slot for a specified name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getSlot"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reply"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TKSmartCardSlot",
          "text": "TKSmartCardSlot"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/getSlot(withName:reply:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getSlotWithName:reply:"
        }
      ],
      "role": "symbol",
      "title": "getSlot(withName:reply:)",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksmartcardslotmanager/getslot(withname:reply:)"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/slotNamed(_:)": {
      "abstract": [
        {
          "text": "Returns the Smart Card slot with a given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slotNamed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TKSmartCardSlot",
          "text": "TKSmartCardSlot"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/slotNamed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "slotNamed:"
        }
      ],
      "role": "symbol",
      "title": "slotNamed(_:)",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksmartcardslotmanager/slotnamed(_:)"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/slotNames": {
      "abstract": [
        {
          "text": "A list of identifiers for all the Smart Card reader slots available to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slotNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/slotNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "slotNames"
        }
      ],
      "role": "symbol",
      "title": "slotNames",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksmartcardslotmanager/slotnames"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/using-cryptographic-assets-stored-on-a-smart-card": {
      "abstract": [
        {
          "text": "Access certificates, keys, and identities stored on a smart card as if they were part of the keychain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/using-cryptographic-assets-stored-on-a-smart-card",
      "kind": "article",
      "role": "article",
      "title": "Using Cryptographic Assets Stored on a Smart Card",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/using-cryptographic-assets-stored-on-a-smart-card"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.smartcard": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether your app has access to smart card slots and smart cards.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.smartcard",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.security.smartcard",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.smartcard"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Smart-Cards",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/using-cryptographic-assets-stored-on-a-smart-card",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlot",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCard"
      ],
      "title": "Smart Cards"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Card-Slot-Manager",
      "identifiers": [
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/default"
      ],
      "title": "Creating a Card Slot Manager"
    },
    {
      "anchor": "Accessing-Smart-Card-Slots",
      "identifiers": [
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/slotNames",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/getSlot(withName:reply:)",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/slotNamed(_:)"
      ],
      "title": "Accessing Smart Card Slots"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TKSmartCardSlotManager"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardSlotManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardSlotManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Card-Slot-Manager",
              "identifiers": [
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/default"
              ],
              "title": "Creating a Card Slot Manager"
            },
            {
              "anchor": "Accessing-Smart-Card-Slots",
              "identifiers": [
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/slotNames",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/getSlot(withName:reply:)",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlotManager/slotNamed(_:)"
              ],
              "title": "Accessing Smart Card Slots"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Smart-Cards",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/using-cryptographic-assets-stored-on-a-smart-card",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCardSlot",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSmartCard"
              ],
              "title": "Smart Cards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TKSmartCardSlotManager"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager~1getSlot(withName:reply:)/title",
          "value": "getSlotWithName:reply:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager~1getSlot(withName:reply:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getSlotWithName:reply:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager~1slotNames/title",
          "value": "slotNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager~1slotNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "slotNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager~1default/title",
          "value": "defaultManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCard/title",
          "value": "TKSmartCard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlot/title",
          "value": "TKSmartCardSlot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager/title",
          "value": "TKSmartCardSlotManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardSlotManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSmartCardSlotManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager~1slotNamed(_:)/title",
          "value": "slotNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSmartCardSlotManager~1slotNamed(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "slotNamed:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cryptotokenkit/tksmartcardslotmanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cryptotokenkit/tksmartcardslotmanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
