{
  "abstract": [
    {
      "text": "Cryptographic algorithms used by token keys.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TKTokenKeyAlgorithm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TKTokenKeyAlgorithm"
      }
    ],
    "modules": [
      {
        "name": "CryptoTokenKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TKTokenKeyAlgorithm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "TKTokenKeyAlgorithm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TKTokenKeyAlgorithm"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, the supported algorithm for a token key can be represented by a value of the ",
              "type": "text"
            },
            {
              "code": "SecKeyAlgorithm",
              "type": "codeVoice"
            },
            {
              "text": " enumeration. However, tokens such as Smart Cards require that input data for operations take the format of a more specific algorithm. For example, a token may accept raw data to generate a cryptographic signature, but require that raw data to be formatted according to PKCS1 padding rules. To express such a requirement, a ",
              "type": "text"
            },
            {
              "code": "TKTokenKeyAlgorithm",
              "type": "codeVoice"
            },
            {
              "text": " object defines a target algorithm and a set of other algorithms that were used. In the previous example, the target algorithm is ",
              "type": "text"
            },
            {
              "code": "kSecKeyAlgorithmRSASignatureRaw",
              "type": "codeVoice"
            },
            {
              "text": " and the ",
              "type": "text"
            },
            {
              "code": "kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1",
              "type": "codeVoice"
            },
            {
              "text": " algorithm is also reported as being  used.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit": {
      "abstract": [
        {
          "text": "Access security tokens and the cryptographic assets they store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CryptoTokenKit",
      "type": "topic",
      "url": "/documentation/cryptotokenkit"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKToken/ObjectID": {
      "abstract": [
        {
          "text": "A unique and persistent identifier of a particular token object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ObjectID"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKToken/ObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ObjectID"
        }
      ],
      "role": "symbol",
      "title": "TKToken.ObjectID",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tktoken/objectid"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm": {
      "abstract": [
        {
          "text": "Cryptographic algorithms used by token keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKTokenKeyAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKTokenKeyAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "TKTokenKeyAlgorithm",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tktokenkeyalgorithm"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm/isAlgorithm(_:)": {
      "abstract": [
        {
          "text": "Returns whether the specified algorithm is the target operation algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAlgorithm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm/isAlgorithm(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isAlgorithm:"
        }
      ],
      "role": "symbol",
      "title": "isAlgorithm(_:)",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tktokenkeyalgorithm/isalgorithm(_:)"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm/supportsAlgorithm(_:)": {
      "abstract": [
        {
          "text": "Whether the specified algorithm is the target operation algorithm, or one of the other algorithms used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsAlgorithm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecKeyAlgorithm",
          "text": "SecKeyAlgorithm"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm/supportsAlgorithm(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsAlgorithm:"
        }
      ],
      "role": "symbol",
      "title": "supportsAlgorithm(_:)",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tktokenkeyalgorithm/supportsalgorithm(_:)"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenOperation": {
      "abstract": [
        {
          "text": "Operations that can be performed with a token’s keys and certificates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKTokenOperation"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKTokenOperation"
        }
      ],
      "role": "symbol",
      "title": "TKTokenOperation",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tktokenoperation"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenSessionDelegate/tokenSession(_:supports:keyObjectID:algorithm:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether the token session supports a given operation using the specified key and algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TKTokenSession",
          "text": "TKTokenSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "supports"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TKTokenOperation",
          "text": "TKTokenOperation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "keyObjectID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TKToken",
          "text": "TKToken"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TKTokenObjectID",
          "text": "ObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "algorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TKTokenKeyAlgorithm",
          "text": "TKTokenKeyAlgorithm"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenSessionDelegate/tokenSession(_:supports:keyObjectID:algorithm:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenSession:supportsOperation:usingKey:algorithm:"
        }
      ],
      "role": "symbol",
      "title": "tokenSession(_:supports:keyObjectID:algorithm:)",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tktokensessiondelegate/tokensession(_:supports:keyobjectid:algorithm:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-Support-for-Operations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenSessionDelegate/tokenSession(_:supports:keyObjectID:algorithm:)",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenOperation",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKToken/ObjectID"
      ],
      "title": "Determining Support for Operations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-Algorithm-Usage",
      "identifiers": [
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm/isAlgorithm(_:)",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm/supportsAlgorithm(_:)"
      ],
      "title": "Determining Algorithm Usage"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TKTokenKeyAlgorithm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKTokenKeyAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKTokenKeyAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-Algorithm-Usage",
              "identifiers": [
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm/isAlgorithm(_:)",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenKeyAlgorithm/supportsAlgorithm(_:)"
              ],
              "title": "Determining Algorithm Usage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-Support-for-Operations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenSessionDelegate/tokenSession(_:supports:keyObjectID:algorithm:)",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKTokenOperation",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKToken/ObjectID"
              ],
              "title": "Determining Support for Operations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TKTokenKeyAlgorithm"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenSessionDelegate~1tokenSession(_:supports:keyObjectID:algorithm:)/title",
          "value": "tokenSession:supportsOperation:usingKey:algorithm:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenSessionDelegate~1tokenSession(_:supports:keyObjectID:algorithm:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenSession:supportsOperation:usingKey:algorithm:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenKeyAlgorithm~1isAlgorithm(_:)/title",
          "value": "isAlgorithm:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenKeyAlgorithm~1isAlgorithm(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isAlgorithm:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenKeyAlgorithm/title",
          "value": "TKTokenKeyAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenKeyAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKTokenKeyAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenKeyAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKTokenKeyAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKToken~1ObjectID/title",
          "value": "TKTokenObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKToken~1ObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKTokenObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKToken~1ObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKTokenObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenKeyAlgorithm~1supportsAlgorithm(_:)/title",
          "value": "supportsAlgorithm:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenKeyAlgorithm~1supportsAlgorithm(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsAlgorithm:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenOperation/title",
          "value": "TKTokenOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKTokenOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKTokenOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKTokenOperation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cryptotokenkit/tktokenkeyalgorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cryptotokenkit/tktokenkeyalgorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
