{
  "abstract": [
    {
      "text": "A localized description of the nature of the search.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.notificationcenter/documentation/NotificationCenter",
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController/searchDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NCWidgetSearchViewController(py)searchDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "searchDescription"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Notification Center"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "searchDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.10",
        "message": "Use WidgetKit instead. Today View extensions have been deprecated.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "searchDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "searchDescription"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The search description is displayed above the search field. If appropriate, the search display controller can change the description to reflect the current status of the search. The default value of this property is “Search”.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/WidgetKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter": {
      "abstract": [
        {
          "text": "Create and manage widgets for the Today view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter",
      "kind": "symbol",
      "role": "collection",
      "title": "Notification Center",
      "type": "topic",
      "url": "/documentation/notificationcenter"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController": {
      "abstract": [
        {
          "text": "An object that provides a default search view within a macOS Today widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NCWidgetSearchViewController"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NCWidgetSearchViewController"
        }
      ],
      "role": "symbol",
      "title": "NCWidgetSearchViewController",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetsearchviewcontroller"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController/searchDescription": {
      "abstract": [
        {
          "text": "A localized description of the nature of the search.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController/searchDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchDescription"
        }
      ],
      "role": "symbol",
      "title": "searchDescription",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetsearchviewcontroller/searchdescription"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController/searchResultsPlaceholderString": {
      "abstract": [
        {
          "text": "A localized phrase displayed in the results list when no search results are available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchResultsPlaceholderString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController/searchResultsPlaceholderString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchResultsPlaceholderString"
        }
      ],
      "role": "symbol",
      "title": "searchResultsPlaceholderString",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetsearchviewcontroller/searchresultsplaceholderstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Displaying-the-Search-Interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController/searchResultsPlaceholderString"
      ],
      "title": "Displaying the Search Interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "searchDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.notificationcenter/documentation/NotificationCenter",
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Displaying-the-Search-Interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetSearchViewController/searchResultsPlaceholderString"
              ],
              "title": "Displaying the Search Interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "searchDescription"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController~1searchDescription/title",
          "value": "searchDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController~1searchDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController/title",
          "value": "NCWidgetSearchViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetSearchViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetSearchViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController~1searchResultsPlaceholderString/title",
          "value": "searchResultsPlaceholderString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetSearchViewController~1searchResultsPlaceholderString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchResultsPlaceholderString"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/notificationcenter/ncwidgetsearchviewcontroller/searchdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/notificationcenter/ncwidgetsearchviewcontroller/searchdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
