{
  "abstract": [
    {
      "text": "The cubic timing parameters to use.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/cubicTimingParameters"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITimingCurveProvider(py)cubicTimingParameters",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cubicTimingParameters"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UICubicTimingParameters",
        "text": "UICubicTimingParameters"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cubicTimingParameters"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "cubicTimingParameters"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cubicTimingParameters"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UICubicTimingParameters",
              "text": "UICubicTimingParameters"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this property and use it to provide your custom cubic timing information. If the value of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/timingCurveType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType/builtin",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType/cubic",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType/composed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you must return an object from this property. The object you return can specify one of the built-in UIKit curves, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve/linear",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or it can specify a timing curve based on a custom Bézier path.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about configuring this object, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters": {
      "abstract": [
        {
          "text": "The timing information for animations in the form of a cubic Bézier curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICubicTimingParameters"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICubicTimingParameters"
        }
      ],
      "role": "symbol",
      "title": "UICubicTimingParameters",
      "type": "topic",
      "url": "/documentation/uikit/uicubictimingparameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider": {
      "abstract": [
        {
          "text": "An interface for providing the timing information needed to perform animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITimingCurveProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITimingCurveProvider"
        }
      ],
      "role": "symbol",
      "title": "UITimingCurveProvider",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurveprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/cubicTimingParameters": {
      "abstract": [
        {
          "text": "The cubic timing parameters to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cubicTimingParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICubicTimingParameters",
          "text": "UICubicTimingParameters"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/cubicTimingParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cubicTimingParameters"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cubicTimingParameters",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurveprovider/cubictimingparameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/springTimingParameters": {
      "abstract": [
        {
          "text": "The spring-based timing parameters to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "springTimingParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISpringTimingParameters",
          "text": "UISpringTimingParameters"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/springTimingParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "springTimingParameters"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "springTimingParameters",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurveprovider/springtimingparameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/timingCurveType": {
      "abstract": [
        {
          "text": "The type of timing information to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timingCurveType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITimingCurveType",
          "text": "UITimingCurveType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/timingCurveType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timingCurveType"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "timingCurveType",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurveprovider/timingcurvetype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType/builtin": {
      "abstract": [
        {
          "text": "Use the built-in UIKit timing curves. Specify this value when you want to use one of the constants in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " type. Specify the desired curve using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/cubicTimingParameters",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "builtin"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType/builtin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITimingCurveTypeBuiltin"
        }
      ],
      "role": "symbol",
      "title": "UITimingCurveType.builtin",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurvetype/builtin"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType/composed": {
      "abstract": [
        {
          "text": "Use a combination of timing parameters. This type of curve starts with the curve defined by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/cubicTimingParameters",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and modifies it using the spring information in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/springTimingParameters",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composed"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType/composed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITimingCurveTypeComposed"
        }
      ],
      "role": "symbol",
      "title": "UITimingCurveType.composed",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurvetype/composed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType/cubic": {
      "abstract": [
        {
          "text": "Use a custom cubic Bézier curve. Specify the curve information using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/cubicTimingParameters",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cubic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType/cubic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITimingCurveTypeCubic"
        }
      ],
      "role": "symbol",
      "title": "UITimingCurveType.cubic",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurvetype/cubic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve": {
      "abstract": [
        {
          "text": "Specifies the supported animation curves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationCurve"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationCurve"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationCurve",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationcurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve/linear": {
      "abstract": [
        {
          "text": "A linear animation curve causes an animation to occur evenly over its duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationCurveLinear"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationCurve.linear",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationcurve/linear"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-timing-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/timingCurveType",
        "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/springTimingParameters"
      ],
      "title": "Getting the timing information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "cubicTimingParameters"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cubicTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-timing-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/timingCurveType",
                "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/springTimingParameters"
              ],
              "title": "Getting the timing information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UICubicTimingParameters",
                    "text": "UICubicTimingParameters"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "cubicTimingParameters"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveType~1composed/title",
          "value": "UITimingCurveTypeComposed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveType~1composed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveTypeComposed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICubicTimingParameters/title",
          "value": "UICubicTimingParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICubicTimingParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICubicTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICubicTimingParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICubicTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1cubicTimingParameters/title",
          "value": "cubicTimingParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1cubicTimingParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cubicTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider/title",
          "value": "UITimingCurveProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1timingCurveType/title",
          "value": "timingCurveType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1timingCurveType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timingCurveType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1springTimingParameters/title",
          "value": "springTimingParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1springTimingParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "springTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/title",
          "value": "UIViewAnimationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveType~1builtin/title",
          "value": "UITimingCurveTypeBuiltin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveType~1builtin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveTypeBuiltin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve~1linear/title",
          "value": "UIViewAnimationCurveLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationCurveLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveType~1cubic/title",
          "value": "UITimingCurveTypeCubic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveType~1cubic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveTypeCubic"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitimingcurveprovider/cubictimingparameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitimingcurveprovider/cubictimingparameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
