{
  "abstract": [
    {
      "text": "A Boolean value that specifies whether Photos can download the requested image from iCloud.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/isNetworkAccessAllowed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHImageRequestOptions(py)networkAccessAllowed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isNetworkAccessAllowed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "networkAccessAllowed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "isNetworkAccessAllowed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isNetworkAccessAllowed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ", and the requested image is not stored on the local device, Photos downloads the image from iCloud. To be notified of the download’s progress, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/progressHandler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to provide a block that Photos calls periodically while downloading the image. If ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": " (the default), and the image is not on the local device, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageResultIsInCloudKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value in the result handler’s ",
              "type": "text"
            },
            {
              "code": "info",
              "type": "codeVoice"
            },
            {
              "text": " dictionary indicates that the image is not available unless you enable network access.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetImageProgressHandler": {
      "abstract": [
        {
          "text": "The signature for a block that Photos calls while downloading asset data from iCloud. Used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/progressHandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetImageProgressHandler"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetImageProgressHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetImageProgressHandler"
        }
      ],
      "role": "symbol",
      "title": "PHAssetImageProgressHandler",
      "type": "topic",
      "url": "/documentation/photos/phassetimageprogresshandler"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of still image representations of Photos assets you request from an image manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHImageRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/isNetworkAccessAllowed": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether Photos can download the requested image from iCloud.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNetworkAccessAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/isNetworkAccessAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkAccessAllowed"
        }
      ],
      "role": "symbol",
      "title": "isNetworkAccessAllowed",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptions/isnetworkaccessallowed"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/progressHandler": {
      "abstract": [
        {
          "text": "A block that Photos calls periodically while downloading the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progressHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHAssetImageProgressHandler",
          "text": "PHAssetImageProgressHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/progressHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "progressHandler"
        }
      ],
      "role": "symbol",
      "title": "progressHandler",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptions/progresshandler"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageResultIsInCloudKey": {
      "abstract": [
        {
          "text": "A key whose value indicates whether photo asset data is stored on the local device or must be downloaded from iCloud.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageResultIsInCloudKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageResultIsInCloudKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageResultIsInCloudKey"
        }
      ],
      "role": "symbol",
      "title": "PHImageResultIsInCloudKey",
      "type": "topic",
      "url": "/documentation/photos/phimageresultisincloudkey"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Fetching-Image-Data-from-iCloud",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/progressHandler",
        "doc://com.apple.photokit/documentation/Photos/PHAssetImageProgressHandler"
      ],
      "title": "Fetching Image Data from iCloud"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "networkAccessAllowed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkAccessAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Fetching-Image-Data-from-iCloud",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/progressHandler",
                "doc://com.apple.photokit/documentation/Photos/PHAssetImageProgressHandler"
              ],
              "title": "Fetching Image Data from iCloud"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "getter"
                  },
                  {
                    "kind": "text",
                    "text": "="
                  },
                  {
                    "kind": "identifier",
                    "text": "isNetworkAccessAllowed"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "networkAccessAllowed"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions/title",
          "value": "PHImageRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageResultIsInCloudKey/title",
          "value": "PHImageResultIsInCloudKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageResultIsInCloudKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageResultIsInCloudKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1isNetworkAccessAllowed/title",
          "value": "networkAccessAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1isNetworkAccessAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkAccessAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1progressHandler/title",
          "value": "progressHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1progressHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "progressHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetImageProgressHandler/title",
          "value": "PHAssetImageProgressHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetImageProgressHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetImageProgressHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetImageProgressHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetImageProgressHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phimagerequestoptions/isnetworkaccessallowed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phimagerequestoptions/isnetworkaccessallowed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
