{
  "abstract": [
    {
      "text": "The most likely language for the processed text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/dominantLanguage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NLLanguageRecognizer(py)dominantLanguage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dominantLanguage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NLLanguage",
        "text": "NLLanguage"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dominantLanguage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "dominantLanguage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dominantLanguage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NLLanguage",
              "text": "NLLanguage"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-the-language-in-text"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage": {
      "abstract": [
        {
          "text": "The languages that the Natural Language framework supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLLanguage"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLLanguage"
        }
      ],
      "role": "symbol",
      "title": "NLLanguage",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer": {
      "abstract": [
        {
          "text": "The language of a body of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLLanguageRecognizer"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLLanguageRecognizer"
        }
      ],
      "role": "symbol",
      "title": "NLLanguageRecognizer",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguagerecognizer"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/dominantLanguage": {
      "abstract": [
        {
          "text": "The most likely language for the processed text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dominantLanguage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLLanguage",
          "text": "NLLanguage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/dominantLanguage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dominantLanguage"
        }
      ],
      "role": "symbol",
      "title": "dominantLanguage",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguagerecognizer/dominantlanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/dominantLanguage(for:)": {
      "abstract": [
        {
          "text": "Finds the most likely language of a piece of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dominantLanguage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLLanguage",
          "text": "NLLanguage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/dominantLanguage(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dominantLanguageForString:"
        }
      ],
      "role": "symbol",
      "title": "dominantLanguage(for:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguagerecognizer/dominantlanguage(for:)"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/languageHypotheses(withMaximum:)": {
      "abstract": [
        {
          "text": "Generates the probabilities of possible languages for the processed text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "languageHypotheses"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMaximum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLLanguage",
          "text": "NLLanguage"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/languageHypotheses(withMaximum:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "languageHypotheses(withMaximum:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguagerecognizer/languagehypotheses(withmaximum:)"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/languageHypothesesWithMaximum:": {
      "abstract": [
        {
          "text": "Generates the probabilities of possible languages for the processed text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "languageHypothesesWithMaximum:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/languageHypothesesWithMaximum:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "languageHypothesesWithMaximum:"
        }
      ],
      "role": "symbol",
      "title": "languageHypothesesWithMaximum:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguagerecognizer/languagehypotheseswithmaximum:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/processString(_:)": {
      "abstract": [
        {
          "text": "Analyzes the piece of text to determine its dominant language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/processString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processString:"
        }
      ],
      "role": "symbol",
      "title": "processString(_:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguagerecognizer/processstring(_:)"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/reset()": {
      "abstract": [
        {
          "text": "Resets the recognizer to its initial state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reset"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/reset()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reset"
        }
      ],
      "role": "symbol",
      "title": "reset()",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguagerecognizer/reset()"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-the-language-in-text": {
      "abstract": [
        {
          "text": "Detect the language in a piece of text by using a language recognizer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-the-language-in-text",
      "kind": "article",
      "role": "article",
      "title": "Identifying the language in text",
      "type": "topic",
      "url": "/documentation/naturallanguage/identifying-the-language-in-text"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-the-language",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/dominantLanguage(for:)",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/processString(_:)",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/languageHypotheses(withMaximum:)",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/reset()"
      ],
      "title": "Determining the language"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dominantLanguage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dominantLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-the-language",
              "generated": true,
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/dominantLanguage(for:)",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/processString(_:)",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/languageHypothesesWithMaximum:",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguageRecognizer/reset()"
              ],
              "title": "Determining the language"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NLLanguage",
                    "text": "NLLanguage"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "dominantLanguage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer~1dominantLanguage/title",
          "value": "dominantLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer~1dominantLanguage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dominantLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer~1processString(_:)/title",
          "value": "processString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer~1processString(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "processString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer/title",
          "value": "NLLanguageRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLLanguageRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLLanguageRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguage/title",
          "value": "NLLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer~1dominantLanguage(for:)/title",
          "value": "dominantLanguageForString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer~1dominantLanguage(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "dominantLanguageForString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer~1reset()/title",
          "value": "reset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguageRecognizer~1reset()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reset"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nllanguagerecognizer/dominantlanguage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/naturallanguage/nllanguagerecognizer/dominantlanguage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
