{
  "abstract": [
    {
      "text": "A constant indicating that tick marks are displayed on the trailing side of the slider.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/trailing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTickMarkPosition@NSTickMarkPositionTrailing",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "trailing"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSSlider",
        "text": "NSSlider"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSTickMarkPosition",
        "text": "TickMarkPosition"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTickMarkPositionTrailing"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "trailing"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "trailing"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSlider",
              "text": "NSSlider"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTickMarkPosition",
              "text": "TickMarkPosition"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider": {
      "abstract": [
        {
          "text": "A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSlider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSlider"
        }
      ],
      "role": "symbol",
      "title": "NSSlider",
      "type": "topic",
      "url": "/documentation/appkit/nsslider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum": {
      "abstract": [
        {
          "text": "The position where a linear slider’s tick marks appear (above, below, leading, or trailing).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TickMarkPosition"
        }
      ],
      "role": "symbol",
      "title": "NSSlider.TickMarkPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/leading": {
      "abstract": [
        {
          "text": "A constant indicating that tick marks are displayed on the leading side of the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSlider",
          "text": "NSSlider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTickMarkPosition",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTickMarkPositionLeading"
        }
      ],
      "role": "symbol",
      "title": "leading",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum/leading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/trailing": {
      "abstract": [
        {
          "text": "A constant indicating that tick marks are displayed on the trailing side of the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSlider",
          "text": "NSSlider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTickMarkPosition",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTickMarkPositionTrailing"
        }
      ],
      "role": "symbol",
      "title": "trailing",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum/trailing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Vertical-Sliders",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/leading"
      ],
      "title": "Configuring Vertical Sliders"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTickMarkPositionTrailing"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPositionTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Vertical-Sliders",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/leading"
              ],
              "title": "Configuring Vertical Sliders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTickMarkPositionTrailing"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/title",
          "value": "NSTickMarkPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1leading/title",
          "value": "NSTickMarkPositionLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPositionLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1trailing/title",
          "value": "NSTickMarkPositionTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPositionTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title",
          "value": "NSSlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSlider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsslider/tickmarkposition-swift.enum/trailing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsslider/tickmarkposition-swift.enum/trailing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
