{
  "abstract": [
    {
      "text": "Display a 3D model that generates procedural textures in a reality view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.visionOS/documentation/visionOS",
        "doc://com.apple.visionOS/documentation/visionOS/introductory-visionOS-samples"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.visionOS/documentation/visionOS/generating-procedural-textures-in-visionos"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "images": [
      {
        "identifier": "sample-drawable-1-main-view-card.png",
        "type": "card"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Generating procedural textures"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample demonstrates how to create and display a 3D torus model that dynamically regenerates a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " texture at each render frame within a visionOS app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "At launch, the app starts a window group that contains:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A 3D torus model with a generated texture",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A button displaying the text “generate”",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "identifier": "sample-drawable-1-main-view.mp4",
          "type": "video"
        },
        {
          "anchor": "Generate-the-texture-of-the-model",
          "level": 3,
          "text": "Generate the texture of the model",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample constructs the ",
              "type": "text"
            },
            {
              "code": "ProceduralTextureGenerator",
              "type": "codeVoice"
            },
            {
              "text": " structure, which contains the ",
              "type": "text"
            },
            {
              "code": "generate()",
              "type": "codeVoice"
            },
            {
              "text": " method to generate and return a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/RealityKit/TextureResource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to apply to the torus model. The app uses  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GameplayKit/GKARC4RandomSource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to generate a number using the ARC4 algorithm, and assigns the ",
              "type": "text"
            },
            {
              "code": "seed",
              "type": "codeVoice"
            },
            {
              "text": " to the generator to determine the random source’s behavior:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import SwiftUI",
            "import RealityKit",
            "import GameplayKit",
            "",
            "struct ProceduralTextureGenerator {",
            "    static func generate(_ seed: Int) throws -> TextureResource {",
            "        let length = 1024",
            "        let bytesPerPixel = 1",
            "        let bitSize = 8",
            "",
            "        /// The generator to randomly generate numbers.",
            "        let generator = GKARC4RandomSource()",
            "",
            "        // Assign the generator seed that determines the random source’s behavior.",
            "        guard let setSeed = \"\\(seed)\".data(using: .ascii) else {",
            "            throw ProceduralTextureGeneratorError.convertSeedFailed",
            "        }",
            "        generator.seed = setSeed",
            "        ",
            "        // ...",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After creating the generator, the app creates a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgdataprovider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with pixels that the generator randomly assigns. Then it creates the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgimage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the procedural texture:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import SwiftUI",
            "import RealityKit",
            "import GameplayKit",
            "",
            "struct ProceduralTextureGenerator {",
            "    static func generate(_ seed: Int) -> TextureResource? {",
            "        // ...",
            "    ",
            "        /// The data provider with pixels that the generator randomly assigns.",
            "        guard let provider = CGDataProvider(",
            "            data: Data(bytes: &pixels, count: pixels.count * bytesPerPixel) as CFData",
            "        ) else {",
            "            throw ProceduralTextureGeneratorError.providerCreationFailed",
            "        }",
            "",
            "        // The source image for the texture.",
            "        guard let image = CGImage(",
            "            width: length,",
            "            height: length,",
            "            bitsPerComponent: bytesPerPixel * bitSize,",
            "            bitsPerPixel: bytesPerPixel * bitSize,",
            "            bytesPerRow: length * bytesPerPixel,",
            "            space: CGColorSpaceCreateDeviceGray(),",
            "            bitmapInfo: CGBitmapInfo(),",
            "            provider: provider,",
            "            decode: nil,",
            "            shouldInterpolate: true,",
            "            intent: .defaultIntent",
            "        ) else {",
            "            throw ProceduralTextureGeneratorError.imageCreationFailed",
            "        }",
            "",
            "        return try TextureResource(image: image, options: TextureResource.CreateOptions(semantic: .color))",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The app attempts to create and return a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/RealityKit/TextureResource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with the generated ",
              "type": "text"
            },
            {
              "code": "image",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Update-the-texture-in-real-time",
          "level": 3,
          "text": "Update the texture in real time",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample defines the custom system ",
              "type": "text"
            },
            {
              "code": "DrawableQueueSystem",
              "type": "codeVoice"
            },
            {
              "text": " to update the model’s texture in real time:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import RealityKit",
            "",
            "struct DrawableQueueSystem: System {",
            "    static let query = EntityQuery(where: .has(DrawableQueueComponent.self))",
            "",
            "    init(scene: RealityKit.Scene) { }",
            "",
            "    /// Update the results to attach delta time to the component.",
            "    func update(context: SceneUpdateContext) {",
            "        for entity in context.entities(matching: Self.query, updatingSystemWhen: .rendering) {",
            "            if var comp = entity.components[DrawableQueueComponent.self] {",
            "                comp.update(deltaTime: context.deltaTime)",
            "                entity.components[DrawableQueueComponent.self] = comp",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "update()",
              "type": "codeVoice"
            },
            {
              "text": " method iterates through all matching entities during the rendering phase and updates each entity’s ",
              "type": "text"
            },
            {
              "code": "DrawableQueueComponent",
              "type": "codeVoice"
            },
            {
              "text": " by passing the time difference between frames, allowing for smooth real-time updates in the scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The initializer registers the ",
              "type": "text"
            },
            {
              "code": "DrawableQueueSystem",
              "type": "codeVoice"
            },
            {
              "text": " within the component, establishing a Metal texture descriptor and a Metal texture. The app attempts to copy the input ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/RealityKit/TextureResource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " texture data into the Metal texture:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import SwiftUI",
            "import RealityKit",
            "",
            "struct DrawableQueueComponent: Component {",
            "    // ...",
            "",
            "    init(texture: TextureResource) throws {",
            "        DrawableQueueSystem.registerSystem()",
            "",
            "        // ...",
            "",
            "        /// The descriptor to configure new Metal texture objects.",
            "        let desc = MTLTextureDescriptor()",
            "        desc.width = texture.width",
            "        desc.height = texture.height",
            "        desc.usage = [.shaderWrite, .shaderRead]",
            "        desc.pixelFormat = .r16Float",
            "",
            "        guard let newTexture = mtlDevice.makeTexture(descriptor: desc) else {",
            "            throw DrawableComponentError.textureCreationFailed",
            "        }",
            "        self.mtlTexture = newTexture",
            "",
            "        try texture.copy(to: mtlTexture)",
            "",
            "        // ...",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/RealityKit/TextureResource/DrawableQueue-swift.class",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " makes it possible to update a texture resource dynamically. The app creates a descriptor and inserts it into the drawable queue to dynamically replace the texture:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import SwiftUI",
            "import RealityKit",
            "",
            "struct DrawableQueueComponent: Component {",
            "    // ...",
            "",
            "    init(texture: TextureResource) throws {",
            "        // ...",
            "",
            "        /// The descriptor for the drawable queue.",
            "        let queueDesc = TextureResource.DrawableQueue.Descriptor(",
            "            pixelFormat: .rgba16Float,",
            "            width: texture.width,",
            "            height: texture.height,",
            "            usage: [.shaderRead, .shaderWrite],",
            "            mipmapsMode: .none",
            "        )",
            "",
            "        // Replace the texture with the result of the drawable queue.",
            "        guard let queue = try? TextureResource.DrawableQueue(queueDesc) else {",
            "            throw DrawableComponentError.queueCreationFailed",
            "        }",
            "        texture.replace(withDrawables: queue)",
            "",
            "        /// The name of the shader function.",
            "        let shaderFunctionName: String = \"textureShader\"",
            "",
            "        // Assign the configuration with the shader function.",
            "        guard let library = mtlDevice.makeDefaultLibrary(), let function = library.makeFunction(name: shaderFunctionName) else {",
            "            throw DrawableComponentError.shaderFunctionCreationFailed",
            "        }",
            "        self.pipeState = try mtlDevice.makeComputePipelineState(function: function)",
            "",
            "        // Assign the Metal command queue.",
            "        guard let newQueue = mtlDevice.makeCommandQueue() else {",
            "            throw DrawableComponentError.commandQueueCreationFailed",
            "        }",
            "        self.mtlCommandQueue = newQueue",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The app attempts to load the shader function. Then it creates a compute pipeline state, which allows the GPU to execute the shader function. Additionally, the app creates a command queue to enable communication between the app and the GPU.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "update(deltaTime:)",
              "type": "codeVoice"
            },
            {
              "text": " method starts by incrementing the value of time, to track and allow contents to change over time:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import SwiftUI",
            "import RealityKit",
            "",
            "struct DrawableQueueComponent: Component {",
            "    // ...",
            "",
            "    mutating func update(deltaTime: TimeInterval) {",
            "        // Increment the value of time with amount of time.",
            "        time += deltaTime",
            "",
            "        // ...",
            "",
            "        let threadGroupCount = MTLSizeMake(8, 8, 1)",
            "        let threadGroups = MTLSizeMake(",
            "            texture.width / threadGroupCount.width,",
            "            texture.height / threadGroupCount.height,",
            "            1",
            "        )",
            "",
            "        encoder.dispatchThreadgroups(threadGroups, threadsPerThreadgroup: threadGroupCount)",
            "        encoder.endEncoding()",
            "",
            "        commandBuffer.commit()",
            "        drawable.present()",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The method sets up the encoder, then commits to the command buffer to submit the command buffer to run on the GPU. Lastly, it presents the updated texture to the renderer with the ",
              "type": "text"
            },
            {
              "code": "present()",
              "type": "codeVoice"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-up-the-torus-model",
          "level": 3,
          "text": "Set up the torus model",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "EntityView",
              "type": "codeVoice"
            },
            {
              "text": " attempts to create the torus model by calling the ",
              "type": "text"
            },
            {
              "code": "makeEntity()",
              "type": "codeVoice"
            },
            {
              "text": " method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct EntityView: View {",
            "    /// The value that controls which iteration of the texture the generator uses",
            "    var seed: Int",
            "",
            "    // ...",
            "",
            "    var body: some View {",
            "        RealityView { content in",
            "            do {",
            "                let entity = try makeEntity()",
            "                content.add(entity)",
            "            } catch {",
            "                print(\"Error creating entity: \\(error)\")",
            "            }",
            "        } update: { content in",
            "            for entity in content.entities {",
            "                if let modelEntitty = entity as? ModelEntity {",
            "                    try? updateEntity(modelEntitty)",
            "                } else {",
            "                    print(\"Entity is not a ModelEntity.\")",
            "                }",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "update",
              "type": "codeVoice"
            },
            {
              "text": " closure loops through all the entities in the reality view, and attempts to update the entity in scene updates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "makeEntity()",
              "type": "codeVoice"
            },
            {
              "text": " method marks the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/MainActor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to execute in the main dispatch queue:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@MainActor",
            "func makeEntity() throws -> ModelEntity {",
            "    let fileName: String = \"Torus\"",
            "    ",
            "    /// The 3D torus model.",
            "    let entity = try Entity.loadModel(named: fileName)",
            "    ",
            "    // Set the scale of the entity with the bounding radius of the model's visible bounds.",
            "    entity.scale /= entity.visualBounds(relativeTo: nil).boundingRadius",
            "",
            "    let scale: Float = 0.2",
            "    ",
            "    // Apply the scale factor with the value of the scale variable.",
            "    entity.scale *= scale",
            "    ",
            "    // Rotate the entity along the y-axis so that the entity faces the user.",
            "    entity.transform.rotation *= simd_quatf(from: SIMD3<Float>(0, 1, 0), to: SIMD3<Float>(0, 0, 1))",
            "",
            "    try updateEntity(entity)",
            "",
            "    return entity",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/RealityKit/Entity/loadModel(named:in:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method synchronously loads a 3D torus model, scales it to the proper size, and applies the ",
              "type": "text"
            },
            {
              "code": "updateEntity()",
              "type": "codeVoice"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "updateEntity()",
              "type": "codeVoice"
            },
            {
              "text": " method generates a new texture by passing the seed value into the ",
              "type": "text"
            },
            {
              "code": "generate()",
              "type": "codeVoice"
            },
            {
              "text": " method, and creates a material sampler for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/RealityKit/PhysicallyBasedMaterial",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@MainActor",
            "func updateEntity(_ entity: ModelEntity) throws {",
            "    /// The texture based on the seed values.",
            "    guard let texture = ProceduralTextureGenerator.generate(seed) else {",
            "        return",
            "    }",
            "",
            "    /// The texture of the sampler, to the nearest pixel.",
            "    var sampler = PhysicallyBasedMaterial.Texture.Sampler()",
            "    sampler.modify { $0.magFilter = .nearest }",
            "",
            "    /// The material that simulates the appearance of real-world objects.",
            "    var material = PhysicallyBasedMaterial()",
            "",
            "    /// The texture for the material.",
            "    let textureAndSampler = PhysicallyBasedMaterial.Texture(",
            "        texture,",
            "        sampler: sampler",
            "    )",
            "    material.baseColor = PhysicallyBasedMaterial.BaseColor(texture: textureAndSampler)",
            "",
            "    // Apply the material to the model of the entity.",
            "    entity.model?.materials = [material]",
            "",
            "    entity.components[DrawableQueueComponent.self] = try DrawableQueueComponent(texture: texture)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The method applies the material to the model of the entity, and attempts to set the ",
              "type": "text"
            },
            {
              "code": "DrawableQueueComponent",
              "type": "codeVoice"
            },
            {
              "text": " to initalize the texture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-up-the-parent-window",
          "level": 3,
          "text": "Set up the parent window",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "DrawableView",
              "type": "codeVoice"
            },
            {
              "text": " creates a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/State",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "seed",
              "type": "codeVoice"
            },
            {
              "text": " property to control the randomization of the texture generator:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import SwiftUI",
            "",
            "struct DrawableView: View {",
            "    @State var seed: Int = 0",
            "",
            "    var body: some View {",
            "        HStack {",
            "            EntityView(seed: seed)",
            "",
            "            Divider()",
            "",
            "            Button(\"Regenerate\") { seed += 1 }",
            "        }.padding()",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/HStack",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " makes it possible to call the ",
              "type": "text"
            },
            {
              "code": "EntityView",
              "type": "codeVoice"
            },
            {
              "text": " that accepts ",
              "type": "text"
            },
            {
              "code": "seed",
              "type": "codeVoice"
            },
            {
              "text": " and a button that increases the value of ",
              "type": "text"
            },
            {
              "code": "seed",
              "type": "codeVoice"
            },
            {
              "text": " on each press.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "8395d34a7ab2/GeneratingProceduralTexturesInVisionOS.zip": {
      "checksum": "8395d34a7ab282fa670f532636374a026b55b0ec38ec7f32cc3bbc0274bd269cdeaf12c097d219bc1a4f235e82b33a33ddd64e78fc3670a9a3fb7bbbb7db260e",
      "identifier": "8395d34a7ab2/GeneratingProceduralTexturesInVisionOS.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/8395d34a7ab2/GeneratingProceduralTexturesInVisionOS.zip"
    },
    "doc://com.apple.documentation/documentation/GameplayKit/GKARC4RandomSource": {
      "abstract": [
        {
          "text": "A basic random number generator implementing the ARC4 algorithm, which is suitable for most gameplay mechanics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKARC4RandomSource"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameplayKit/GKARC4RandomSource",
      "kind": "symbol",
      "role": "symbol",
      "title": "GKARC4RandomSource",
      "type": "topic",
      "url": "/documentation/GameplayKit/GKARC4RandomSource"
    },
    "doc://com.apple.documentation/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/Metal"
    },
    "doc://com.apple.documentation/documentation/RealityKit/Entity/loadModel(named:in:)": {
      "abstract": [
        {
          "text": "Synchronously loads a model entity from a bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadModel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "bundle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": "? = nil) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation11ModelEntityC",
          "text": "ModelEntity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/Entity/loadModel(named:in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadModel(named:in:)",
      "type": "topic",
      "url": "/documentation/RealityKit/Entity/loadModel(named:in:)"
    },
    "doc://com.apple.documentation/documentation/RealityKit/PhysicallyBasedMaterial": {
      "abstract": [
        {
          "text": "A material that simulates the appearance of real-world objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PhysicallyBasedMaterial"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/PhysicallyBasedMaterial",
      "kind": "symbol",
      "role": "symbol",
      "title": "PhysicallyBasedMaterial",
      "type": "topic",
      "url": "/documentation/RealityKit/PhysicallyBasedMaterial"
    },
    "doc://com.apple.documentation/documentation/RealityKit/TextureResource": {
      "abstract": [
        {
          "text": "A representation of a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextureResource"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/TextureResource",
      "kind": "symbol",
      "role": "symbol",
      "title": "TextureResource",
      "type": "topic",
      "url": "/documentation/RealityKit/TextureResource"
    },
    "doc://com.apple.documentation/documentation/RealityKit/TextureResource/DrawableQueue-swift.class": {
      "abstract": [
        {
          "text": "A drawable queue that may be used to update a texture resource dynamically",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DrawableQueue"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/TextureResource/DrawableQueue-swift.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "TextureResource.DrawableQueue",
      "type": "topic",
      "url": "/documentation/RealityKit/TextureResource/DrawableQueue-swift.class"
    },
    "doc://com.apple.documentation/documentation/Swift/MainActor": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/MainActor",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/HStack": {
      "abstract": [
        {
          "text": "A view that arranges its subviews in a horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HStack"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/HStack",
      "kind": "symbol",
      "role": "symbol",
      "title": "HStack",
      "type": "topic",
      "url": "/documentation/SwiftUI/HStack"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/State": {
      "abstract": [
        {
          "text": "A property wrapper type that can read and write a value managed by SwiftUI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@propertyWrapper"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/State",
      "kind": "symbol",
      "role": "symbol",
      "title": "State",
      "type": "topic",
      "url": "/documentation/SwiftUI/State"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgdataprovider": {
      "abstract": [
        {
          "text": "An abstraction for data-reading tasks that eliminates the need to manage a raw memory buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGDataProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgdataprovider",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGDataProvider",
      "type": "topic",
      "url": "/documentation/coregraphics/cgdataprovider"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgimage": {
      "abstract": [
        {
          "text": "A bitmap image or image mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgimage",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGImage",
      "type": "topic",
      "url": "/documentation/coregraphics/cgimage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.visionOS/documentation/visionOS": {
      "abstract": [
        {
          "text": "Create a new universe of apps and games for Apple Vision Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.visionOS/documentation/visionOS",
      "images": [
        {
          "identifier": "headset-orange.svg",
          "type": "icon"
        },
        {
          "identifier": "visionOS-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "visionOS",
      "type": "topic",
      "url": "/documentation/visionos"
    },
    "doc://com.apple.visionOS/documentation/visionOS/displaying-a-stereoscopic-image-in-visionos": {
      "abstract": [
        {
          "text": "Build a stereoscopic image by applying textures to the left and right eye in a shader graph material.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.visionOS/documentation/visionOS/displaying-a-stereoscopic-image-in-visionos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Displaying a stereoscopic image",
      "type": "topic",
      "url": "/documentation/visionos/displaying-a-stereoscopic-image-in-visionos"
    },
    "doc://com.apple.visionOS/documentation/visionOS/implementing-adjustable-material-in-visionos": {
      "abstract": [
        {
          "text": "Update the adjustable parameters of a 3D model in visionOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.visionOS/documentation/visionOS/implementing-adjustable-material-in-visionos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing adjustable material",
      "type": "topic",
      "url": "/documentation/visionos/implementing-adjustable-material-in-visionos"
    },
    "doc://com.apple.visionOS/documentation/visionOS/introductory-visionOS-samples": {
      "abstract": [
        {
          "text": "Learn the fundamentals of building apps for visionOS with beginner-friendly sample code projects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.visionOS/documentation/visionOS/introductory-visionOS-samples",
      "images": [
        {
          "identifier": "introductory-visionOS-samples.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Introductory visionOS samples",
      "type": "topic",
      "url": "/documentation/visionos/introductory-visionos-samples"
    },
    "headset-orange.svg": {
      "alt": "An icon representing visionOS.",
      "identifier": "headset-orange.svg",
      "type": "image",
      "variants": [
        {
          "svgID": "a",
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/77dc6a0821bfb2da8db4a3b2033e6f6b/headset-orange.svg"
        }
      ]
    },
    "introductory-visionOS-samples.png": {
      "alt": "A translucent window displaying five white, three-dimensional entities in a horizontal row. From left to right, the shapes are a box, a rounded box, a right sphere, a cone, and a cylinder that all top-align.",
      "identifier": "introductory-visionOS-samples.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3d386622a70e5f41179e6a4c98a125c7/introductory-visionOS-samples@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/58fa94f103305452c567401d648dedc5/introductory-visionOS-samples~dark@2x.png"
        }
      ]
    },
    "sample-drawable-1-main-view-card.png": {
      "alt": null,
      "identifier": "sample-drawable-1-main-view-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2b35928ee97847f8abb8441a454a5696/sample-drawable-1-main-view-card.png"
        }
      ]
    },
    "sample-drawable-1-main-view.mp4": {
      "alt": "A video of a visionOS app displaying a translucent window with a 3D torus model on the left and a button on the right.",
      "identifier": "sample-drawable-1-main-view.mp4",
      "poster": null,
      "type": "video",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/569607e5d93e80b3dc4f97643ff32309/sample-drawable-1-main-view.mp4"
        }
      ]
    },
    "visionOS-PageImage-card.png": {
      "alt": "A stylized illustration of an Apple Vision Pro with the word 'hello' written across the front in cursive.",
      "identifier": "visionOS-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/90294957b44e5508a55fe39373eea478/visionOS-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/90fe463571fd45badfabacbb07f30591/visionOS-PageImage-card~dark@2x.png"
        }
      ]
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "8395d34a7ab2/GeneratingProceduralTexturesInVisionOS.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Building-materials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.visionOS/documentation/visionOS/implementing-adjustable-material-in-visionos",
        "doc://com.apple.visionOS/documentation/visionOS/displaying-a-stereoscopic-image-in-visionos"
      ],
      "title": "Building materials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgdataprovider/title",
          "value": "CGDataProviderRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgimage/title",
          "value": "CGImageRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameplayKit~1GKARC4RandomSource/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKARC4RandomSource"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKRandomSource",
              "text": "GKRandomSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
