{
  "abstract": [
    {
      "text": "The total amount of any fees added to the payment record.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/feeAmount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INPaymentRecord(py)feeAmount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "feeAmount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
        "text": "INCurrencyAmount"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "feeAmount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "feeAmount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "feeAmount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
              "text": "INCurrencyAmount"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmount": {
      "abstract": [
        {
          "text": "An amount of money to transfer during a financial transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCurrencyAmount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCurrencyAmount"
        }
      ],
      "role": "symbol",
      "title": "INCurrencyAmount",
      "type": "topic",
      "url": "/documentation/intents/incurrencyamount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord": {
      "abstract": [
        {
          "text": "Detailed information about a financial transaction made between two users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentRecord"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentRecord"
        }
      ],
      "role": "symbol",
      "title": "INPaymentRecord",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/currencyAmount": {
      "abstract": [
        {
          "text": "The type of currency to transfer and the amount to transfer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currencyAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/currencyAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currencyAmount"
        }
      ],
      "role": "symbol",
      "title": "currencyAmount",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/currencyamount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/feeAmount": {
      "abstract": [
        {
          "text": "The total amount of any fees added to the payment record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "feeAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/feeAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "feeAmount"
        }
      ],
      "role": "symbol",
      "title": "feeAmount",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/feeamount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/note": {
      "abstract": [
        {
          "text": "A description of the payment to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "note"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/note",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "note"
        }
      ],
      "role": "symbol",
      "title": "note",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/note"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payee": {
      "abstract": [
        {
          "text": "The person receiving the funds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "payee"
        }
      ],
      "role": "symbol",
      "title": "payee",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/payee"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payer": {
      "abstract": [
        {
          "text": "The person providing the funds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "payer"
        }
      ],
      "role": "symbol",
      "title": "payer",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/payer"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/paymentMethod": {
      "abstract": [
        {
          "text": "The payment method used to supply the funds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPaymentMethod",
          "text": "INPaymentMethod"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/paymentMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentMethod"
        }
      ],
      "role": "symbol",
      "title": "paymentMethod",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/paymentmethod"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Payment-Record-Details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payee",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payer",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/currencyAmount",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/paymentMethod",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/note"
      ],
      "title": "Getting Payment Record Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "feeAmount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "feeAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Payment-Record-Details",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payee",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payer",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/currencyAmount",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/paymentMethod",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/note"
              ],
              "title": "Getting Payment Record Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmount",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
                    "text": "INCurrencyAmount"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "feeAmount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmount",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
                    "text": "INCurrencyAmount"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "feeAmount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1note/title",
          "value": "note"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1note/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "note"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord/title",
          "value": "INPaymentRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmount/title",
          "value": "INCurrencyAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCurrencyAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCurrencyAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1currencyAmount/title",
          "value": "currencyAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1currencyAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currencyAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1paymentMethod/title",
          "value": "paymentMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1paymentMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paymentMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1feeAmount/title",
          "value": "feeAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1feeAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "feeAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1payer/title",
          "value": "payer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1payer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "payer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1payee/title",
          "value": "payee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1payee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "payee"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inpaymentrecord/feeamount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inpaymentrecord/feeamount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
