{
  "abstract": [
    {
      "text": "Returns an initialized interface controller object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/init()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKInterfaceController(im)init",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "init"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The initialized interface controller object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.watchkit/documentation/WatchKit/navigating-between-scenes"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is the designated initializer for interface controller objects. Override this method as needed and use it to prepare your interface controller for use. In your implementation, call ",
              "type": "text"
            },
            {
              "code": "super",
              "type": "codeVoice"
            },
            {
              "text": " first and then perform your own initialization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If the interface controller has outlets connected to objects in your storyboard file, the super implementation creates those interface objects and assigns them to your declared properties; however, the system cannot guarantee that these objects are ready for use yet. Instead, defer any code that interacts with the user interface to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/awake(withContext:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "In a page-based interface, all interface controllers are initialized up front but only the first one is displayed initially. The others are not displayed until the user navigates to the corresponding page. If your interface controller displays information that can change between initialization and the display of the page, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/willActivate()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to refresh your content. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/didAppear()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to start animations or perform tasks that should wait until the interface appears onscreen.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController": {
      "abstract": [
        {
          "text": "A class that provides the infrastructure for managing the interface in a watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceController"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceController"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceController",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/awake(withContext:)": {
      "abstract": [
        {
          "text": "Initializes the interface controller with the specified context data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "awake"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/awake(withContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "awakeWithContext:"
        }
      ],
      "role": "symbol",
      "title": "awake(withContext:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/awake(withcontext:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/didAppear()": {
      "abstract": [
        {
          "text": "Tells the interface controller that its view is now onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didAppear"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/didAppear()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didAppear"
        }
      ],
      "role": "symbol",
      "title": "didAppear()",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/didappear()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/init()": {
      "abstract": [
        {
          "text": "Returns an initialized interface controller object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/init()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/setTitle(_:)": {
      "abstract": [
        {
          "text": "Sets the title of the interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTitle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/setTitle(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitle:"
        }
      ],
      "role": "symbol",
      "title": "setTitle(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/settitle(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/willActivate()": {
      "abstract": [
        {
          "text": "Tells the interface controller that the system is about to activate its view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willActivate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/willActivate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willActivate"
        }
      ],
      "role": "symbol",
      "title": "willActivate()",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacecontroller/willactivate()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/navigating-between-scenes": {
      "abstract": [
        {
          "text": "Help users navigate between interface controllers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/navigating-between-scenes",
      "kind": "article",
      "role": "article",
      "title": "Navigating Between Scenes",
      "type": "topic",
      "url": "/documentation/watchkit/navigating-between-scenes"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969",
      "title": "App Programming Guide for watchOS",
      "titleInlineContent": [
        {
          "text": "App Programming Guide for watchOS",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/didAppear()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/willActivate()"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Creating-the-interface-controller",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/awake(withContext:)",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/setTitle(_:)"
      ],
      "title": "Creating the interface controller"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/didAppear()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/willActivate()"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Creating-the-interface-controller",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/awake(withContext:)",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/setTitle(_:)"
              ],
              "title": "Creating the interface controller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "init"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The initialized interface controller object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1didAppear()/title",
          "value": "didAppear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1didAppear()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didAppear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController/title",
          "value": "WKInterfaceController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1willActivate()/title",
          "value": "willActivate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1willActivate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willActivate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1awake(withContext:)/title",
          "value": "awakeWithContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1awake(withContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "awakeWithContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1setTitle(_:)/title",
          "value": "setTitle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1setTitle(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTitle:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkinterfacecontroller/init()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkinterfacecontroller/init()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
