{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController"]]},"kind":"symbol","abstract":[{"type":"text","text":"Called to let you know that the user selected a row in the table."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/table(_:didSelectRowAt:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"table","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"table","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKInterfaceTable","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTable","text":"WKInterfaceTable","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelectRowAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rowIndex","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["watchOS"]}]},{"kind":"parameters","parameters":[{"name":"table","content":[{"inlineContent":[{"text":"The table object whose row was selected.","type":"text"}],"type":"paragraph"}]},{"name":"rowIndex","content":[{"type":"paragraph","inlineContent":[{"text":"The zero-based index of the row that was selected.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"text":"Use this method to respond to row selections in a table. You might use the selection of a row to display a new interface controller or update the state of your app. If you connected an action method to the table in your storyboard file, WatchKit does not call this method.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This method is called on your WatchKit extension’s main thread. Implementation of the method is optional."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/watchkit/wkinterfacecontroller/table(_:didselectrowat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/watchkit/wkinterfacecontroller/table(_:didselectrowat:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"c:objc(cs)WKInterfaceController(im)table:didSelectRowAtIndex:","navigatorTitle":[{"text":"table:didSelectRowAtIndex:","kind":"identifier"}],"role":"symbol","platforms":[{"deprecated":false,"name":"watchOS","beta":false,"unavailable":false,"introducedAt":"2.0"}],"roleHeading":"Instance Method","modules":[{"name":"WatchKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"table","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKInterfaceTable","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKInterfaceTable"},{"text":", ","kind":"text"},{"text":"didSelectRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"table(_:didSelectRowAt:)","symbolKind":"method"},"references":{"doc://com.apple.watchkit/documentation/WatchKit":{"kind":"symbol","abstract":[{"type":"text","text":"Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions."}],"role":"collection","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit","title":"WatchKit","url":"/documentation/watchkit"},"doc://com.externally.resolved.symbol/s:Si":{"role":"symbol","url":"/documentation/Swift/Int","type":"topic","kind":"symbol","title":"Int","abstract":[{"text":"A signed integer value type.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:Si","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"role":"symbol","fragments":[{"text":"@globalActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"actor"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainActor"}],"abstract":[{"type":"text","text":"A singleton actor whose executor is equivalent to the main dispatch queue."}],"url":"/documentation/Swift/MainActor","title":"MainActor","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:ScM","type":"topic"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController":{"url":"/documentation/watchkit/wkinterfacecontroller","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController","title":"WKInterfaceController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WKInterfaceController"}],"navigatorTitle":[{"kind":"identifier","text":"WKInterfaceController"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A class that provides the infrastructure for managing the interface in a watchOS app."}],"role":"symbol"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTable":{"role":"symbol","abstract":[{"text":"An object that creates and manages the contents of a single-column table interface.","type":"text"}],"type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTable","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WKInterfaceTable"}],"url":"/documentation/watchkit/wkinterfacetable","title":"WKInterfaceTable","kind":"symbol","navigatorTitle":[{"text":"WKInterfaceTable","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/table(_:didSelectRowAt:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"table"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKInterfaceTable","kind":"typeIdentifier","text":"WKInterfaceTable"},{"text":", ","kind":"text"},{"text":"didSelectRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"/documentation/watchkit/wkinterfacecontroller/table(_:didselectrowat:)","abstract":[{"type":"text","text":"Called to let you know that the user selected a row in the table."}],"role":"symbol","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController/table(_:didSelectRowAt:)","title":"table(_:didSelectRowAt:)","navigatorTitle":[{"text":"table:didSelectRowAtIndex:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"name":"watchOS","introducedAt":"2.0","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"table:didSelectRowAtIndex:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"table:didSelectRowAtIndex:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceController"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"table:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKInterfaceTable","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTable","text":"WKInterfaceTable","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"table","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didSelectRowAtIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rowIndex","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["watchOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The table object whose row was selected."}]}],"name":"table"},{"content":[{"inlineContent":[{"type":"text","text":"The zero-based index of the row that was selected."}],"type":"paragraph"}],"name":"rowIndex"}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"value":"WKInterfaceController","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController/title","op":"replace"},{"value":[{"kind":"identifier","text":"WKInterfaceController"}],"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController/fragments","op":"replace"},{"value":[{"text":"WKInterfaceController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController/navigatorTitle","op":"replace"},{"value":"WKInterfaceTable","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTable/title","op":"replace"},{"value":[{"text":"WKInterfaceTable","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTable/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"WKInterfaceTable"}],"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTable/navigatorTitle","op":"replace"},{"value":"table:didSelectRowAtIndex:","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1table(_:didSelectRowAt:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"table:didSelectRowAtIndex:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceController~1table(_:didSelectRowAt:)/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}