{
  "abstract": [
    {
      "text": "Returns a Boolean value that indicates whether the log can write messages with the specified log type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os",
        "doc://com.apple.os/documentation/os/OSLog"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/OSLog/isEnabled(type:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "os",
    "externalID": "c:@F@os_log_type_enabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isEnabled"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "type"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@os_log_type_t",
        "text": "OSLogType"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "os"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "os_log_type_enabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "isEnabled(type:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isEnabled"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.os/documentation/os/OSLogType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@os_log_type_t",
              "text": "OSLogType"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A log type constant, such as ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEFAULT",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_INFO",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEBUG",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_ERROR",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_FAULT",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", that specifies the level of logging to check.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "type"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if logging at the specified level is in an enabled state; otherwise, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OSLog": {
      "abstract": [
        {
          "text": "A container of related log messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLog"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLog"
        }
      ],
      "role": "symbol",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/os/oslog"
    },
    "doc://com.apple.os/documentation/os/OSLog/isEnabled(type:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the log can write messages with the specified log type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLog/isEnabled(type:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_log_type_enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled(type:)",
      "type": "topic",
      "url": "/documentation/os/oslog/isenabled(type:)"
    },
    "doc://com.apple.os/documentation/os/OSLogType": {
      "abstract": [
        {
          "text": "The various log levels that the unified logging system provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogType"
        }
      ],
      "role": "symbol",
      "title": "OSLogType",
      "type": "topic",
      "url": "/documentation/os/oslogtype"
    },
    "doc://com.apple.os/documentation/os/OS_LOG_DEFAULT": {
      "abstract": [
        {
          "text": "The shared default log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_DEFAULT"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_LOG_DEFAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_DEFAULT",
      "type": "topic",
      "url": "/documentation/os/os_log_default"
    },
    "doc://com.apple.os/documentation/os/os_log_create": {
      "abstract": [
        {
          "text": "Creates a custom log object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_create"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_create",
      "type": "topic",
      "url": "/documentation/os/os_log_create"
    },
    "doc://com.apple.os/documentation/os/os_log_debug_enabled": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether debug-level logging is in an enabled state for a specified log object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_debug_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_debug_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_debug_enabled",
      "type": "topic",
      "url": "/documentation/os/os_log_debug_enabled"
    },
    "doc://com.apple.os/documentation/os/os_log_info_enabled": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether info-level logging is in an enabled state for a specified log object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_info_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_info_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_info_enabled",
      "type": "topic",
      "url": "/documentation/os/os_log_info_enabled"
    },
    "doc://com.apple.os/documentation/os/os_log_t": {
      "abstract": [
        {
          "text": "A log object that you pass to logging functions to send messages to that log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_t",
      "type": "topic",
      "url": "/documentation/os/os_log_t"
    },
    "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEBUG": {
      "abstract": [
        {
          "text": "The debug log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TYPE_DEBUG"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEBUG",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_TYPE_DEBUG",
      "type": "topic",
      "url": "/documentation/os/os_log_type_t/os_log_type_debug"
    },
    "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEFAULT": {
      "abstract": [
        {
          "text": "The default log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TYPE_DEFAULT"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEFAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_TYPE_DEFAULT",
      "type": "topic",
      "url": "/documentation/os/os_log_type_t/os_log_type_default"
    },
    "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_ERROR": {
      "abstract": [
        {
          "text": "The error log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TYPE_ERROR"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_ERROR",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_TYPE_ERROR",
      "type": "topic",
      "url": "/documentation/os/os_log_type_t/os_log_type_error"
    },
    "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_FAULT": {
      "abstract": [
        {
          "text": "The fault log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TYPE_FAULT"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_FAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_TYPE_FAULT",
      "type": "topic",
      "url": "/documentation/os/os_log_type_t/os_log_type_fault"
    },
    "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_INFO": {
      "abstract": [
        {
          "text": "The informational log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TYPE_INFO"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_INFO",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_TYPE_INFO",
      "type": "topic",
      "url": "/documentation/os/os_log_type_t/os_log_type_info"
    },
    "doc://com.apple.os/documentation/os/os_signpost_enabled": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether signposts are in an enabled state for the specified log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_enabled",
      "type": "topic",
      "url": "/documentation/os/os_signpost_enabled"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "os_log_type_enabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.os/documentation/os"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Log-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_log_info_enabled",
                "doc://com.apple.os/documentation/os/os_log_debug_enabled",
                "doc://com.apple.os/documentation/os/os_signpost_enabled"
              ],
              "title": "Getting Log Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:b",
                    "text": "bool"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "os_log_type_enabled"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.os/documentation/os/os_log_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@os_log_t",
                    "text": "os_log_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "oslog"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.os/documentation/os/OSLogType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@EA@os_log_type_t",
                    "text": "os_log_type_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "type"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.os/documentation/os/OS_LOG_DEFAULT",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " constant or a custom log object that you create with the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.os/documentation/os/os_log_create",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "oslog"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A log type constant, such as ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEFAULT",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_INFO",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEBUG",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_ERROR",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_FAULT",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", that specifies the level of logging to check.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "type"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if logging at the specified level is in an enabled state; otherwise, ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/title",
          "value": "os_log_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLog~1isEnabled(type:)/title",
          "value": "os_log_type_enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLog~1isEnabled(type:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_enabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/oslog/isenabled(type:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/oslog/isenabled(type:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
