{
  "abstract": [
    {
      "text": "Rays that define which direction is outside for each face.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/normals"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARMeshGeometry(py)normals",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "normals"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARGeometrySource",
        "text": "ARGeometrySource"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "normals"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "normals"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "normals"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeometrySource",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARGeometrySource",
              "text": "ARGeometrySource"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeometryElement": {
      "abstract": [
        {
          "text": "A container for index data, such as vertex indices of a face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARGeometryElement"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeometryElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeometryElement"
        }
      ],
      "role": "symbol",
      "title": "ARGeometryElement",
      "type": "topic",
      "url": "/documentation/arkit/argeometryelement"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeometrySource": {
      "abstract": [
        {
          "text": "Mesh data in a buffer-based array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARGeometrySource"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeometrySource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeometrySource"
        }
      ],
      "role": "symbol",
      "title": "ARGeometrySource",
      "type": "topic",
      "url": "/documentation/arkit/argeometrysource"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification": {
      "abstract": [
        {
          "text": "Enumeration of different classes of real-world objects that ARKit can identify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARMeshClassification"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshClassification"
        }
      ],
      "role": "symbol",
      "title": "ARMeshClassification",
      "type": "topic",
      "url": "/documentation/arkit/armeshclassification"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry": {
      "abstract": [
        {
          "text": "Mesh information stored in an efficient, array-based format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARMeshGeometry"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMeshGeometry"
        }
      ],
      "role": "symbol",
      "title": "ARMeshGeometry",
      "type": "topic",
      "url": "/documentation/arkit/armeshgeometry"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/classification": {
      "abstract": [
        {
          "text": "Classification for each face in the mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARGeometrySource",
          "text": "ARGeometrySource"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/classification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "classification"
        }
      ],
      "role": "symbol",
      "title": "classification",
      "type": "topic",
      "url": "/documentation/arkit/armeshgeometry/classification"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/faces": {
      "abstract": [
        {
          "text": "An object that contains a buffer of vertex indices of the geometry’s faces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faces"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARGeometryElement",
          "text": "ARGeometryElement"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/faces",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "faces"
        }
      ],
      "role": "symbol",
      "title": "faces",
      "type": "topic",
      "url": "/documentation/arkit/armeshgeometry/faces"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/normals": {
      "abstract": [
        {
          "text": "Rays that define which direction is outside for each face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normals"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARGeometrySource",
          "text": "ARGeometrySource"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/normals",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "normals"
        }
      ],
      "role": "symbol",
      "title": "normals",
      "type": "topic",
      "url": "/documentation/arkit/armeshgeometry/normals"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Geometry-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/classification",
        "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification",
        "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/faces",
        "doc://com.apple.arkit/documentation/ARKit/ARGeometryElement"
      ],
      "title": "Getting Geometry Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "normals"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "normals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Geometry-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/classification",
                "doc://com.apple.arkit/documentation/ARKit/ARMeshClassification",
                "doc://com.apple.arkit/documentation/ARKit/ARMeshGeometry/faces",
                "doc://com.apple.arkit/documentation/ARKit/ARGeometryElement"
              ],
              "title": "Getting Geometry Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeometrySource",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ARGeometrySource",
                    "text": "ARGeometrySource"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "normals"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeometrySource/title",
          "value": "ARGeometrySource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeometrySource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeometrySource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeometrySource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeometrySource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshGeometry~1faces/title",
          "value": "faces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshGeometry~1faces/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "faces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeometryElement/title",
          "value": "ARGeometryElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeometryElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeometryElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeometryElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeometryElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshGeometry~1classification/title",
          "value": "classification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshGeometry~1classification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "classification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshGeometry/title",
          "value": "ARMeshGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshGeometry~1normals/title",
          "value": "normals"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshGeometry~1normals/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "normals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification/title",
          "value": "ARMeshClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMeshClassification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMeshClassification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/armeshgeometry/normals"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/armeshgeometry/normals"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
