{
  "abstract": [
    {
      "text": "Dismiss the notification interface and forward the notification to the app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/dismissAndForwardAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UNNotificationContentExtensionResponseOption@UNNotificationContentExtensionResponseOptionDismissAndForwardAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dismissAndForwardAction"
      }
    ],
    "modules": [
      {
        "name": "User Notifications UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UNNotificationContentExtensionResponseOptionDismissAndForwardAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UNNotificationContentExtensionResponseOption.dismissAndForwardAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dismissAndForwardAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Choose this option when you want the app to respond to the action or handle",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI": {
      "abstract": [
        {
          "text": "Customize the interface that displays local and remote notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications UI",
      "type": "topic",
      "url": "/documentation/usernotificationsui"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption": {
      "abstract": [
        {
          "text": "Constants indicating the preferred response to a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionResponseOption"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionResponseOption"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtensionResponseOption",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextensionresponseoption"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/dismiss": {
      "abstract": [
        {
          "text": "Dismiss the notification interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismiss"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/dismiss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionResponseOptionDismiss"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtensionResponseOption.dismiss",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextensionresponseoption/dismiss"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/dismissAndForwardAction": {
      "abstract": [
        {
          "text": "Dismiss the notification interface and forward the notification to the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismissAndForwardAction"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/dismissAndForwardAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionResponseOptionDismissAndForwardAction"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtensionResponseOption.dismissAndForwardAction",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextensionresponseoption/dismissandforwardaction"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/doNotDismiss": {
      "abstract": [
        {
          "text": "Don’t dismiss the notification interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doNotDismiss"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/doNotDismiss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionResponseOptionDoNotDismiss"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtensionResponseOption.doNotDismiss",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextensionresponseoption/donotdismiss"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Response-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/doNotDismiss",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/dismiss"
      ],
      "title": "Response Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UNNotificationContentExtensionResponseOptionDismissAndForwardAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionResponseOptionDismissAndForwardAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Response-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/doNotDismiss",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionResponseOption/dismiss"
              ],
              "title": "Response Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UNNotificationContentExtensionResponseOptionDismissAndForwardAction"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionResponseOption~1doNotDismiss/title",
          "value": "UNNotificationContentExtensionResponseOptionDoNotDismiss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionResponseOption~1doNotDismiss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionResponseOptionDoNotDismiss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionResponseOption~1dismiss/title",
          "value": "UNNotificationContentExtensionResponseOptionDismiss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionResponseOption~1dismiss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionResponseOptionDismiss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionResponseOption/title",
          "value": "UNNotificationContentExtensionResponseOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionResponseOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionResponseOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionResponseOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionResponseOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionResponseOption~1dismissAndForwardAction/title",
          "value": "UNNotificationContentExtensionResponseOptionDismissAndForwardAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionResponseOption~1dismissAndForwardAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionResponseOptionDismissAndForwardAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotificationsui/unnotificationcontentextensionresponseoption/dismissandforwardaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotificationsui/unnotificationcontentextensionresponseoption/dismissandforwardaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
