{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"]]},"abstract":[{"text":"Creates a document view controller with a document.","type":"text"}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Initializer","platforms":[{"introducedAt":"17.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"introducedAt":"17.0","deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"introducedAt":"17.0","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false,"beta":false}],"symbolKind":"init","externalID":"c:objc(cs)UIDocumentViewController(im)initWithDocument:","modules":[{"name":"UIKit"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocument","text":"UIDocument"},{"kind":"text","text":"?)"}],"role":"symbol","title":"init(document:)","navigatorTitle":[{"kind":"identifier","text":"initWithDocument:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/init(document:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIDocument","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocument","preciseIdentifier":"c:objc(cs)UIDocument"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document that the view controller presents."}]}],"name":"document"}]},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"A newly initialized ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The document view controller opens and displays the document that you specify. If you don’t provide custom values, the new view controller gets its title and other information from the document itself.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uidocumentviewcontroller/init(document:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uidocumentviewcontroller/init(document:)"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController":{"navigatorTitle":[{"text":"UIDocumentViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDocumentViewController","kind":"identifier"}],"title":"UIDocumentViewController","role":"symbol","type":"topic","url":"/documentation/uikit/uidocumentviewcontroller","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController","kind":"symbol","abstract":[{"text":"A view controller that manages and presents a document stored locally or in the cloud.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDocument":{"navigatorTitle":[{"kind":"identifier","text":"UIDocument"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocument","abstract":[{"type":"text","text":"An abstract base class for managing discrete portions of your app’s data."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIDocument"}],"url":"/documentation/uikit/uidocument","title":"UIDocument","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/init(document:)":{"type":"topic","title":"init(document:)","abstract":[{"type":"text","text":"Creates a document view controller with a document."}],"navigatorTitle":[{"text":"initWithDocument:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"/documentation/uikit/uidocumentviewcontroller/init(document:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDocument","text":"UIDocument","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/init(document:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"introducedAt":"17.0","deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"17.0","deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"17.0","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false,"name":"visionOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"initWithDocument:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocument:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDocument","preciseIdentifier":"c:objc(cs)UIDocument","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"op":"replace"},{"path":"/primaryContentSections/1","value":{"parameters":[{"name":"document","content":[{"type":"paragraph","inlineContent":[{"text":"The document that the view controller presents.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"value":{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A newly initialized "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"},{"type":"text","text":" object."}]}],"kind":"content"},"op":"replace","path":"/primaryContentSections/2"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/title","value":"UIDocumentViewController","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/fragments","value":[{"text":"UIDocumentViewController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/navigatorTitle","value":[{"kind":"identifier","text":"UIDocumentViewController"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/title","value":"UIDocument","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/fragments","value":[{"text":"UIDocument","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/navigatorTitle","value":[{"text":"UIDocument","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1init(document:)/title","value":"initWithDocument:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1init(document:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}