{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Provides an opportunity to customize the navigation items after the navigation bar updates."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uidocumentviewcontroller/navigationitemdidupdate()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uidocumentviewcontroller/navigationitemdidupdate()"]}],"metadata":{"navigatorTitle":[{"text":"navigationItemDidUpdate","kind":"identifier"}],"title":"navigationItemDidUpdate()","symbolKind":"method","externalID":"c:objc(cs)UIDocumentViewController(im)navigationItemDidUpdate","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigationItemDidUpdate","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","platforms":[{"deprecated":false,"name":"iOS","beta":false,"introducedAt":"17.0","unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"17.0","unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"17.0","unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false}],"modules":[{"name":"UIKit"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationItemDidUpdate"},{"kind":"text","text":"()"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The system calls ","type":"text"},{"code":"navigationItemDidUpdate()","type":"codeVoice"},{"text":" every time ","type":"text"},{"code":"UIDocumentViewController","type":"codeVoice"},{"text":" makes changes to the navigation item. Customize the navigation items in this method.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This example adds buttons to the navigation bar and customizes the toolbar:"}]},{"syntax":"swift","type":"codeListing","code":["class EditorViewController:","        UIDocumentViewController,","        UINavigationItemRenameDelegate {","","    override func navigationItemDidUpdate() {","        navigationItem.customizationIdentifier = \"editorViewCustomization\"","        configureCenterItemGroups()","        navigationItem.rightBarButtonItem = splitView.previewVisibilityBarButton","    }","","}"]}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/navigationItemDidUpdate()","interfaceLanguage":"swift"},"references":{"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/navigationItemDidUpdate()":{"kind":"symbol","type":"topic","abstract":[{"text":"Provides an opportunity to customize the navigation items after the navigation bar updates.","type":"text"}],"url":"/documentation/uikit/uidocumentviewcontroller/navigationitemdidupdate()","title":"navigationItemDidUpdate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationItemDidUpdate"},{"kind":"text","text":"()"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/navigationItemDidUpdate()","navigatorTitle":[{"kind":"identifier","text":"navigationItemDidUpdate"}]},"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController":{"navigatorTitle":[{"text":"UIDocumentViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDocumentViewController","kind":"identifier"}],"title":"UIDocumentViewController","role":"symbol","type":"topic","url":"/documentation/uikit/uidocumentviewcontroller","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController","kind":"symbol","abstract":[{"text":"A view controller that manages and presents a document stored locally or in the cloud.","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"17.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"17.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"17.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"navigationItemDidUpdate","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigationItemDidUpdate"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"navigationItemDidUpdate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1navigationItemDidUpdate()/title","value":"navigationItemDidUpdate","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1navigationItemDidUpdate()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigationItemDidUpdate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/title","value":"UIDocumentViewController","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/fragments","value":[{"text":"UIDocumentViewController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/navigatorTitle","value":[{"text":"UIDocumentViewController","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}