{"abstract":[{"type":"text","text":"Opens a document in a document view controller from outside the document view controller."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/openDocument(completionHandler:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uidocumentviewcontroller/opendocument(completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uidocumentviewcontroller/opendocument(completionhandler:)"]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"symbolKind":"method","modules":[{"name":"UIKit"}],"title":"openDocument(completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"openDocumentWithCompletionHandler:"}],"externalID":"c:objc(cs)UIDocumentViewController(im)openDocumentWithCompletionHandler:","platforms":[{"beta":false,"name":"iOS","introducedAt":"17.0","unavailable":false,"deprecated":false},{"beta":false,"name":"iPadOS","introducedAt":"17.0","unavailable":false,"deprecated":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"17.0","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openDocument","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]},{"parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"The function that executes after the document view controller opens the document","type":"text"}]}]}],"kind":"parameters"}],"seeAlsoSections":[{"generated":true,"anchor":"Managing-the-document-view","title":"Managing the document view","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/document","doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/documentDidOpen()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"]]},"sections":[],"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/document":{"title":"document","url":"/documentation/uikit/uidocumentviewcontroller/document","abstract":[{"text":"The document that the controller presents or edits.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"document"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/document","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIDocument","preciseIdentifier":"c:objc(cs)UIDocument"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController":{"navigatorTitle":[{"text":"UIDocumentViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDocumentViewController","kind":"identifier"}],"title":"UIDocumentViewController","role":"symbol","type":"topic","url":"/documentation/uikit/uidocumentviewcontroller","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController","kind":"symbol","abstract":[{"text":"A view controller that manages and presents a document stored locally or in the cloud.","type":"text"}]},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/documentDidOpen()":{"role":"symbol","navigatorTitle":[{"text":"documentDidOpen","kind":"identifier"}],"title":"documentDidOpen()","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/documentDidOpen()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDidOpen","kind":"identifier"},{"text":"()","kind":"text"}],"url":"/documentation/uikit/uidocumentviewcontroller/documentdidopen()","abstract":[{"text":"Provides an opportunity to configure the view after the system loads the controller’s document into memory.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:s4Voida":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Void"},{"kind":"text","text":" = ()"}],"abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}],"title":"Void","url":"/documentation/Swift/Void","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s4Voida"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/openDocument(completionHandler:)":{"title":"openDocument(completionHandler:)","url":"/documentation/uikit/uidocumentviewcontroller/opendocument(completionhandler:)","abstract":[{"text":"Opens a document in a document view controller from outside the document view controller.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"openDocumentWithCompletionHandler:"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/openDocument(completionHandler:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","introducedAt":"17.0","unavailable":false,"deprecated":false},{"beta":false,"name":"iPadOS","introducedAt":"17.0","unavailable":false,"deprecated":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"17.0","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"openDocumentWithCompletionHandler:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"openDocumentWithCompletionHandler:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Managing-the-document-view","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/document","doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/documentDidOpen()"],"title":"Managing the document view","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"openDocumentWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"success","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The function that executes after the document view controller opens the document"}]}],"name":"completionHandler"}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1document/title","value":"document"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1document/fragments","value":[{"kind":"identifier","text":"document"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/title","value":"UIDocumentViewController"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/fragments","value":[{"text":"UIDocumentViewController","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/navigatorTitle","value":[{"kind":"identifier","text":"UIDocumentViewController"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1documentDidOpen()/title","value":"documentDidOpen"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1documentDidOpen()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentDidOpen"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1openDocument(completionHandler:)/title","value":"openDocumentWithCompletionHandler:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1openDocument(completionHandler:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openDocumentWithCompletionHandler:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}