{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"undoRedoItemGroup","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBarButtonItemGroup","text":"UIBarButtonItemGroup","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"If you want undo and redo buttons to appear in your ","type":"text"},{"code":"UIDocumentViewController","type":"codeVoice"},{"text":", add an ","type":"text"},{"type":"codeVoice","code":"undoRedoItemGroup"},{"text":" to the navigation bar and ensure that your custom ","type":"text"},{"type":"codeVoice","code":"UIDocument"},{"text":" has an undo manager assigned to it. ","type":"text"},{"type":"codeVoice","code":"UIDocumentViewController"},{"text":" sets the hidden property of this group, depending on the availability of an undo manager. It automatically enables or disables the buttons inside the group, as necessary.","type":"text"}]}]}],"abstract":[{"text":"The group that contains the undo/redo buttons that this view controller adds to the navigation bar.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/undoRedoItemGroup"},"metadata":{"role":"symbol","symbolKind":"property","platforms":[{"introducedAt":"17.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"introducedAt":"17.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"17.0","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","deprecated":false,"unavailable":false}],"externalID":"c:objc(cs)UIDocumentViewController(py)undoRedoItemGroup","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"undoRedoItemGroup"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIBarButtonItemGroup","kind":"typeIdentifier","text":"UIBarButtonItemGroup"}],"navigatorTitle":[{"kind":"identifier","text":"undoRedoItemGroup"}],"title":"undoRedoItemGroup","roleHeading":"Instance Property","modules":[{"name":"UIKit"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["/documentation/uikit/uidocumentviewcontroller/undoredoitemgroup"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uidocumentviewcontroller/undoredoitemgroup"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController":{"navigatorTitle":[{"text":"UIDocumentViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDocumentViewController","kind":"identifier"}],"title":"UIDocumentViewController","role":"symbol","type":"topic","url":"/documentation/uikit/uidocumentviewcontroller","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController","kind":"symbol","abstract":[{"text":"A view controller that manages and presents a document stored locally or in the cloud.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup":{"url":"/documentation/uikit/uibarbuttonitemgroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIBarButtonItemGroup"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup","title":"UIBarButtonItemGroup","navigatorTitle":[{"kind":"identifier","text":"UIBarButtonItemGroup"}],"role":"symbol","kind":"symbol","abstract":[{"text":"A group of one or more bar button items for placement on a navigation bar or shortcuts bar.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/undoRedoItemGroup":{"abstract":[{"text":"The group that contains the undo/redo buttons that this view controller adds to the navigation bar.","type":"text"}],"type":"topic","title":"undoRedoItemGroup","navigatorTitle":[{"text":"undoRedoItemGroup","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/undoRedoItemGroup","url":"/documentation/uikit/uidocumentviewcontroller/undoredoitemgroup","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"undoRedoItemGroup","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIBarButtonItemGroup","preciseIdentifier":"c:objc(cs)UIBarButtonItemGroup","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"17.0"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"17.0"},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"17.0"},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"undoRedoItemGroup","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"undoRedoItemGroup","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup","text":"UIBarButtonItemGroup","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItemGroup"},{"text":" * ","kind":"text"},{"text":"undoRedoItemGroup","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/title","value":"UIDocumentViewController","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/fragments","value":[{"text":"UIDocumentViewController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/navigatorTitle","value":[{"text":"UIDocumentViewController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItemGroup/title","value":"UIBarButtonItemGroup","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItemGroup/fragments","value":[{"text":"UIBarButtonItemGroup","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItemGroup/navigatorTitle","value":[{"kind":"identifier","text":"UIBarButtonItemGroup"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1undoRedoItemGroup/title","value":"undoRedoItemGroup","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1undoRedoItemGroup/fragments","value":[{"kind":"identifier","text":"undoRedoItemGroup"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}