{
  "abstract": [
    {
      "text": "A style indicating that the system determines the type of separator.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/automatic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTitlebarSeparatorStyle@NSTitlebarSeparatorStyleAutomatic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "automatic"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTitlebarSeparatorStyleAutomatic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTitlebarSeparatorStyle.automatic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "automatic"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle": {
      "abstract": [
        {
          "text": "Styles that determine the type of separator displayed between the title bar and content of a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTitlebarSeparatorStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTitlebarSeparatorStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTitlebarSeparatorStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstitlebarseparatorstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/automatic": {
      "abstract": [
        {
          "text": "A style indicating that the system determines the type of separator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTitlebarSeparatorStyleAutomatic"
        }
      ],
      "role": "symbol",
      "title": "NSTitlebarSeparatorStyle.automatic",
      "type": "topic",
      "url": "/documentation/appkit/nstitlebarseparatorstyle/automatic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/line": {
      "abstract": [
        {
          "text": "A style indicating that the title bar separator is a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/line",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTitlebarSeparatorStyleLine"
        }
      ],
      "role": "symbol",
      "title": "NSTitlebarSeparatorStyle.line",
      "type": "topic",
      "url": "/documentation/appkit/nstitlebarseparatorstyle/line"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/none": {
      "abstract": [
        {
          "text": "A style indicating that there’s no title bar separator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTitlebarSeparatorStyleNone"
        }
      ],
      "role": "symbol",
      "title": "NSTitlebarSeparatorStyle.none",
      "type": "topic",
      "url": "/documentation/appkit/nstitlebarseparatorstyle/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/shadow": {
      "abstract": [
        {
          "text": "A style indicating that the title bar separator is a shadow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/shadow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTitlebarSeparatorStyleShadow"
        }
      ],
      "role": "symbol",
      "title": "NSTitlebarSeparatorStyle.shadow",
      "type": "topic",
      "url": "/documentation/appkit/nstitlebarseparatorstyle/shadow"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/line",
        "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/none",
        "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/shadow"
      ],
      "title": "Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTitlebarSeparatorStyleAutomatic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTitlebarSeparatorStyleAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/line",
                "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/none",
                "doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle/shadow"
              ],
              "title": "Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTitlebarSeparatorStyleAutomatic"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle/title",
          "value": "NSTitlebarSeparatorStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTitlebarSeparatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTitlebarSeparatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle~1shadow/title",
          "value": "NSTitlebarSeparatorStyleShadow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle~1shadow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTitlebarSeparatorStyleShadow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle~1none/title",
          "value": "NSTitlebarSeparatorStyleNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTitlebarSeparatorStyleNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle~1automatic/title",
          "value": "NSTitlebarSeparatorStyleAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTitlebarSeparatorStyleAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle~1line/title",
          "value": "NSTitlebarSeparatorStyleLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle~1line/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTitlebarSeparatorStyleLine"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstitlebarseparatorstyle/automatic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstitlebarseparatorstyle/automatic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
