{
  "abstract": [
    {
      "text": "The person is a parent of the current user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/parent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Intents",
    "externalID": "c:@INPersonRelationshipParent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "parent"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@INPersonRelationship",
        "text": "INPersonRelationship"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPersonRelationshipParent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "parent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "parent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@INPersonRelationship",
              "text": "INPersonRelationship"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship": {
      "abstract": [
        {
          "text": "Constants indicating the relationship between the person using the device and another person.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationship"
        }
      ],
      "role": "symbol",
      "title": "INPersonRelationship",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/assistant": {
      "abstract": [
        {
          "text": "The person is an assistant to the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assistant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/assistant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipAssistant"
        }
      ],
      "role": "symbol",
      "title": "assistant",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/assistant"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/brother": {
      "abstract": [
        {
          "text": "The person is the brother of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "brother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/brother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipBrother"
        }
      ],
      "role": "symbol",
      "title": "brother",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/brother"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/child": {
      "abstract": [
        {
          "text": "The person is a child of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "child"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/child",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipChild"
        }
      ],
      "role": "symbol",
      "title": "child",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/child"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/daughter": {
      "abstract": [
        {
          "text": "The person is the daughter of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daughter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/daughter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipDaughter"
        }
      ],
      "role": "symbol",
      "title": "daughter",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/daughter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/father": {
      "abstract": [
        {
          "text": "The person is the father of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "father"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/father",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipFather"
        }
      ],
      "role": "symbol",
      "title": "father",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/father"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/friend": {
      "abstract": [
        {
          "text": "The person is a friend of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/friend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipFriend"
        }
      ],
      "role": "symbol",
      "title": "friend",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/friend"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/manager": {
      "abstract": [
        {
          "text": "The person is the manager of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/manager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipManager"
        }
      ],
      "role": "symbol",
      "title": "manager",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/manager"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/mother": {
      "abstract": [
        {
          "text": "The person is the mother of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/mother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipMother"
        }
      ],
      "role": "symbol",
      "title": "mother",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/mother"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/parent": {
      "abstract": [
        {
          "text": "The person is a parent of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/parent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipParent"
        }
      ],
      "role": "symbol",
      "title": "parent",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/parent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/partner": {
      "abstract": [
        {
          "text": "The person is the partner of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/partner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipPartner"
        }
      ],
      "role": "symbol",
      "title": "partner",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/partner"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/sister": {
      "abstract": [
        {
          "text": "The person is the sister of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/sister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipSister"
        }
      ],
      "role": "symbol",
      "title": "sister",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/sister"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/son": {
      "abstract": [
        {
          "text": "The person is the son of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "son"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/son",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipSon"
        }
      ],
      "role": "symbol",
      "title": "son",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/son"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/spouse": {
      "abstract": [
        {
          "text": "The person is the spouse of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spouse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/spouse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipSpouse"
        }
      ],
      "role": "symbol",
      "title": "spouse",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/spouse"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Relationship-Type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/assistant",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/brother",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/child",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/father",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/friend",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/manager",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/mother",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/partner",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/sister",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/spouse",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/daughter",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/son"
      ],
      "title": "Relationship Type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPersonRelationshipParent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipParent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Relationship-Type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/assistant",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/brother",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/child",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/father",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/friend",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/manager",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/mother",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/partner",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/sister",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/spouse",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/daughter",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/son"
              ],
              "title": "Relationship Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@INPersonRelationship",
                    "text": "INPersonRelationship"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INPersonRelationshipParent"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1father/title",
          "value": "INPersonRelationshipFather"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1father/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipFather"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1son/title",
          "value": "INPersonRelationshipSon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1son/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipSon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1friend/title",
          "value": "INPersonRelationshipFriend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1friend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipFriend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1brother/title",
          "value": "INPersonRelationshipBrother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1brother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipBrother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship/title",
          "value": "INPersonRelationship"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1assistant/title",
          "value": "INPersonRelationshipAssistant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1assistant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipAssistant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1sister/title",
          "value": "INPersonRelationshipSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1sister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1child/title",
          "value": "INPersonRelationshipChild"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1child/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipChild"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1parent/title",
          "value": "INPersonRelationshipParent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1parent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipParent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1mother/title",
          "value": "INPersonRelationshipMother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1mother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipMother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1manager/title",
          "value": "INPersonRelationshipManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1manager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1partner/title",
          "value": "INPersonRelationshipPartner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1partner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipPartner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1daughter/title",
          "value": "INPersonRelationshipDaughter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1daughter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipDaughter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1spouse/title",
          "value": "INPersonRelationshipSpouse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1spouse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipSpouse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inpersonrelationship/parent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inpersonrelationship/parent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
