{
  "abstract": [
    {
      "text": "Any of the ",
      "type": "text"
    },
    {
      "code": "setNeedsDisplay",
      "type": "codeVoice"
    },
    {
      "text": " methods sent to the view will cause the view redraw the affected layer parts by invoking the view’s ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/draw(_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ", but neither the layer or the view are marked as needing display when the view’s size changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSView",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/onSetNeedsDisplay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSViewLayerContentsRedrawPolicy@NSViewLayerContentsRedrawOnSetNeedsDisplay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "onSetNeedsDisplay"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSViewLayerContentsRedrawOnSetNeedsDisplay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSView.LayerContentsRedrawPolicy.onSetNeedsDisplay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "onSetNeedsDisplay"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum": {
      "abstract": [
        {
          "text": "These constants specify the location of the layer content when the content is not rerendered in response to view resizing. For more information, see the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerContentsPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerContentsPlacement"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify how layer resizing is handled when a view is layer-backed or layer-hosting. For more information, see the  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerContentsRedrawPolicy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerContentsRedrawPolicy"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsRedrawPolicy",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/beforeViewResize": {
      "abstract": [
        {
          "text": "Resize the layer and redraw the view to the layer when the view’s size changes. This will be done just once at the beginning of a resize animation, not at each frame of the animation. Affected parts of the layer will also be redrawn when the view is marked as needing display. This mode is a superset of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/onSetNeedsDisplay",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeViewResize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/beforeViewResize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsRedrawBeforeViewResize"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsRedrawPolicy.beforeViewResize",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.enum/beforeviewresize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/crossfade": {
      "abstract": [
        {
          "text": "Redraw the layer contents at the new size and crossfade from the old contents to the new contents. Use this in conjunction with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " constants to get a nice crossfade animation for complex layer-backed views that cannot update correctly at each step of the animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crossfade"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/crossfade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsRedrawCrossfade"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsRedrawPolicy.crossfade",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.enum/crossfade"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/duringViewResize": {
      "abstract": [
        {
          "text": "Resize the view’s backing-layer and redraw the view to the layer when the view’s size changes. If the resize is animated, AppKit will drive the resize animation itself and will do this resize and redraw at each step of the animation. Affected parts of the layer will also be redrawn when the view is marked as needing display. This mode is a superset of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/onSetNeedsDisplay",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". This is the way that layer-backed views are currently treated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duringViewResize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/duringViewResize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsRedrawDuringViewResize"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsRedrawPolicy.duringViewResize",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.enum/duringviewresize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/never": {
      "abstract": [
        {
          "text": "Leave the layer’s contents alone. Never mark the layer as needing display, or draw the view’s contents to the layer. This is how developer created layers (layer-hosting views) are treated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "never"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/never",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsRedrawNever"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsRedrawPolicy.never",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.enum/never"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/onSetNeedsDisplay": {
      "abstract": [
        {
          "text": "Any of the ",
          "type": "text"
        },
        {
          "code": "setNeedsDisplay",
          "type": "codeVoice"
        },
        {
          "text": " methods sent to the view will cause the view redraw the affected layer parts by invoking the view’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/draw(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", but neither the layer or the view are marked as needing display when the view’s size changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onSetNeedsDisplay"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/onSetNeedsDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsRedrawOnSetNeedsDisplay"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsRedrawPolicy.onSetNeedsDisplay",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.enum/onsetneedsdisplay"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/draw(_:)": {
      "abstract": [
        {
          "text": "Overridden by subclasses to draw the view’s image within the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/draw(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawRect:"
        }
      ],
      "role": "symbol",
      "title": "draw(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/draw(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property": {
      "abstract": [
        {
          "text": "The contents redraw policy for the view’s layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerContentsRedrawPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSViewLayerContentsRedrawPolicy",
          "text": "LayerContentsRedrawPolicy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerContentsRedrawPolicy"
        }
      ],
      "role": "symbol",
      "title": "layerContentsRedrawPolicy",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/never",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/duringViewResize",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/beforeViewResize",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/crossfade"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSViewLayerContentsRedrawOnSetNeedsDisplay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawOnSetNeedsDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/never",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/duringViewResize",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/beforeViewResize",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum/crossfade"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSViewLayerContentsRedrawOnSetNeedsDisplay"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/title",
          "value": "NSViewLayerContentsPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum~1crossfade/title",
          "value": "NSViewLayerContentsRedrawCrossfade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum~1crossfade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawCrossfade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum~1onSetNeedsDisplay/title",
          "value": "NSViewLayerContentsRedrawOnSetNeedsDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum~1onSetNeedsDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawOnSetNeedsDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsRedrawPolicy-swift.property/title",
          "value": "layerContentsRedrawPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsRedrawPolicy-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layerContentsRedrawPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1draw(_:)/title",
          "value": "drawRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1draw(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum/title",
          "value": "NSViewLayerContentsRedrawPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum~1duringViewResize/title",
          "value": "NSViewLayerContentsRedrawDuringViewResize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum~1duringViewResize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawDuringViewResize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum~1never/title",
          "value": "NSViewLayerContentsRedrawNever"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum~1never/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawNever"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum~1beforeViewResize/title",
          "value": "NSViewLayerContentsRedrawBeforeViewResize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum~1beforeViewResize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawBeforeViewResize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.enum/onsetneedsdisplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.enum/onsetneedsdisplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
