{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(monoGlobalTapButExcludeProcesses:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreAudio",
    "externalID": "s:So16CATapDescriptionC9CoreAudioE32monoGlobalTapButExcludeProcessesABSays6UInt32VG_tcfc",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "monoGlobalTapButExcludeProcesses"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectID",
        "text": "AudioObjectID"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(monoGlobalTapButExcludeProcesses:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "monoGlobalTapButExcludeProcesses"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "processesIDsToExcludeFromTap"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectID",
              "text": "AudioObjectID"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectID"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectID",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATapDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATapDescription"
        }
      ],
      "role": "symbol",
      "title": "CATapDescription",
      "type": "topic",
      "url": "/documentation/coreaudio/catapdescription"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/coreaudio/catapdescription/init()"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(excludingProcesses:deviceUID:stream:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "excludingProcesses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "deviceUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "stream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(excludingProcesses:deviceUID:stream:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(excludingProcesses:deviceUID:stream:)",
      "type": "topic",
      "url": "/documentation/coreaudio/catapdescription/init(excludingprocesses:deviceuid:stream:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(monoGlobalTapButExcludeProcesses:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "monoGlobalTapButExcludeProcesses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(monoGlobalTapButExcludeProcesses:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(monoGlobalTapButExcludeProcesses:)",
      "type": "topic",
      "url": "/documentation/coreaudio/catapdescription/init(monoglobaltapbutexcludeprocesses:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(monoMixdownOfProcesses:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "monoMixdownOfProcesses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(monoMixdownOfProcesses:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(monoMixdownOfProcesses:)",
      "type": "topic",
      "url": "/documentation/coreaudio/catapdescription/init(monomixdownofprocesses:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(processes:deviceUID:stream:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "processes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "deviceUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "stream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(processes:deviceUID:stream:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(processes:deviceUID:stream:)",
      "type": "topic",
      "url": "/documentation/coreaudio/catapdescription/init(processes:deviceuid:stream:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(stereoGlobalTapButExcludeProcesses:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "stereoGlobalTapButExcludeProcesses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(stereoGlobalTapButExcludeProcesses:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(stereoGlobalTapButExcludeProcesses:)",
      "type": "topic",
      "url": "/documentation/coreaudio/catapdescription/init(stereoglobaltapbutexcludeprocesses:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(stereoMixdownOfProcesses:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "stereoMixdownOfProcesses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(stereoMixdownOfProcesses:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(stereoMixdownOfProcesses:)",
      "type": "topic",
      "url": "/documentation/coreaudio/catapdescription/init(stereomixdownofprocesses:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init()",
        "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(excludingProcesses:deviceUID:stream:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(monoMixdownOfProcesses:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(processes:deviceUID:stream:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(stereoGlobalTapButExcludeProcesses:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription/init(stereoMixdownOfProcesses:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapDescription/title",
          "value": "CATapDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATapDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATapDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/title",
          "value": "AudioObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapDescription~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapDescription~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/catapdescription/init(monoglobaltapbutexcludeprocesses:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
