{
  "abstract": [
    {
      "text": "An object for that conveys data during a collaboration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction/collaborationMetadata"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SWStartCollaborationAction(py)collaborationMetadata",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "collaborationMetadata"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SWCollaborationMetadata",
        "text": "SWCollaborationMetadata"
      }
    ],
    "modules": [
      {
        "name": "Shared With You Core"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "collaborationMetadata"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "collaborationMetadata"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "collaborationMetadata"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationMetadata",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SWCollaborationMetadata",
              "text": "SWCollaborationMetadata"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You Core",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationMetadata": {
      "abstract": [
        {
          "text": "A model object for conveying data during a collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationMetadata"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationMetadata"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationMetadata",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationmetadata"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction": {
      "abstract": [
        {
          "text": "An object that represents the first action sent to an app when the user shares a collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWStartCollaborationAction"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWStartCollaborationAction"
        }
      ],
      "role": "symbol",
      "title": "SWStartCollaborationAction",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swstartcollaborationaction"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction/collaborationMetadata": {
      "abstract": [
        {
          "text": "An object for that conveys data during a collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collaborationMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SWCollaborationMetadata",
          "text": "SWCollaborationMetadata"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction/collaborationMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collaborationMetadata"
        }
      ],
      "role": "symbol",
      "title": "collaborationMetadata",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swstartcollaborationaction/collaborationmetadata"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "collaborationMetadata"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collaborationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationMetadata",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SWCollaborationMetadata",
                    "text": "SWCollaborationMetadata"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "collaborationMetadata"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationMetadata/title",
          "value": "SWCollaborationMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWStartCollaborationAction~1collaborationMetadata/title",
          "value": "collaborationMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWStartCollaborationAction~1collaborationMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collaborationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWStartCollaborationAction/title",
          "value": "SWStartCollaborationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWStartCollaborationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWStartCollaborationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWStartCollaborationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWStartCollaborationAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyoucore/swstartcollaborationaction/collaborationmetadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sharedwithyoucore/swstartcollaborationaction/collaborationmetadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
