{
  "abstract": [
    {
      "text": "No media types require a user gesture to begin playing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/WKAudiovisualMediaTypeNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKAudiovisualMediaTypes@WKAudiovisualMediaTypeNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "WKAudiovisualMediaTypeNone"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKAudiovisualMediaTypeNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "WKAudiovisualMediaTypeNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "WKAudiovisualMediaTypeNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes": {
      "abstract": [
        {
          "text": "The media types that require a user gesture to begin playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAudiovisualMediaTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudiovisualMediaTypes"
        }
      ],
      "role": "symbol",
      "title": "WKAudiovisualMediaTypes",
      "type": "topic",
      "url": "/documentation/webkit/wkaudiovisualmediatypes"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/WKAudiovisualMediaTypeNone": {
      "abstract": [
        {
          "text": "No media types require a user gesture to begin playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WKAudiovisualMediaTypeNone"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/WKAudiovisualMediaTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKAudiovisualMediaTypeNone",
      "type": "topic",
      "url": "/documentation/webkit/wkaudiovisualmediatypes/wkaudiovisualmediatypenone"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/all": {
      "abstract": [
        {
          "text": "All media types require a user gesture to begin playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKAudiovisualMediaTypes",
          "text": "WKAudiovisualMediaTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudiovisualMediaTypeAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/webkit/wkaudiovisualmediatypes/all"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/audio": {
      "abstract": [
        {
          "text": "Media types that contain audio require a user gesture to begin playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKAudiovisualMediaTypes",
          "text": "WKAudiovisualMediaTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudiovisualMediaTypeAudio"
        }
      ],
      "role": "symbol",
      "title": "audio",
      "type": "topic",
      "url": "/documentation/webkit/wkaudiovisualmediatypes/audio"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/video": {
      "abstract": [
        {
          "text": "Media types that contain video require a user gesture to begin playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKAudiovisualMediaTypes",
          "text": "WKAudiovisualMediaTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudiovisualMediaTypeVideo"
        }
      ],
      "role": "symbol",
      "title": "video",
      "type": "topic",
      "url": "/documentation/webkit/wkaudiovisualmediatypes/video"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/audio",
        "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/video",
        "doc://com.apple.webkit/documentation/WebKit/WKAudiovisualMediaTypes/all"
      ],
      "title": "Media Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes~1audio/title",
          "value": "WKAudiovisualMediaTypeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes~1audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudiovisualMediaTypeAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes/title",
          "value": "WKAudiovisualMediaTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudiovisualMediaTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudiovisualMediaTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes~1video/title",
          "value": "WKAudiovisualMediaTypeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes~1video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudiovisualMediaTypeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes~1all/title",
          "value": "WKAudiovisualMediaTypeAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKAudiovisualMediaTypes~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudiovisualMediaTypeAll"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkaudiovisualmediatypes/wkaudiovisualmediatypenone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
