{
  "abstract": [
    {
      "text": "The pass’s serial number.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/serialNumberUserInfoKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "PassKit",
    "externalID": "c:@PKPassLibrarySerialNumberUserInfoKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "serialNumberUserInfoKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
        "text": "PKPassLibraryNotificationKey"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPassLibrarySerialNumberUserInfoKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "serialNumberUserInfoKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "serialNumberUserInfoKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
              "text": "PKPassLibraryNotificationKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey": {
      "abstract": [
        {
          "text": "The user info keys that a pass library notification uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryNotificationKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/addedPassesUserInfoKey": {
      "abstract": [
        {
          "text": "An array of added passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addedPassesUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/addedPassesUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryAddedPassesUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "addedPassesUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/addedpassesuserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/passTypeIdentifierUserInfoKey": {
      "abstract": [
        {
          "text": "The pass’s pass type identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passTypeIdentifierUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/passTypeIdentifierUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryPassTypeIdentifierUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "passTypeIdentifierUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/passtypeidentifieruserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/recoveredPassesUserInfoKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recoveredPassesUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/recoveredPassesUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryRecoveredPassesUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "recoveredPassesUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/recoveredpassesuserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/removedPassInfosUserInfoKey": {
      "abstract": [
        {
          "text": "An array of dictionaries that describes the removed passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removedPassInfosUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/removedPassInfosUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryRemovedPassInfosUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "removedPassInfosUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/removedpassinfosuserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/replacementPassesUserInfoKey": {
      "abstract": [
        {
          "text": "An array of replaced passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacementPassesUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/replacementPassesUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryReplacementPassesUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "replacementPassesUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/replacementpassesuserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/serialNumberUserInfoKey": {
      "abstract": [
        {
          "text": "The pass’s serial number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serialNumberUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
          "text": "PKPassLibraryNotificationKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/serialNumberUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibrarySerialNumberUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "serialNumberUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrarynotificationkey/serialnumberuserinfokey"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notification-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/addedPassesUserInfoKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/passTypeIdentifierUserInfoKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/recoveredPassesUserInfoKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/removedPassInfosUserInfoKey",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/replacementPassesUserInfoKey"
      ],
      "title": "Notification keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPassLibrarySerialNumberUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrarySerialNumberUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Notification-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/addedPassesUserInfoKey",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/passTypeIdentifierUserInfoKey",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/recoveredPassesUserInfoKey",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/removedPassInfosUserInfoKey",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey/replacementPassesUserInfoKey"
              ],
              "title": "Notification keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryNotificationKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@PKPassLibraryNotificationKey",
                    "text": "PKPassLibraryNotificationKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKPassLibrarySerialNumberUserInfoKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1removedPassInfosUserInfoKey/title",
          "value": "PKPassLibraryRemovedPassInfosUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1removedPassInfosUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryRemovedPassInfosUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1addedPassesUserInfoKey/title",
          "value": "PKPassLibraryAddedPassesUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1addedPassesUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryAddedPassesUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1serialNumberUserInfoKey/title",
          "value": "PKPassLibrarySerialNumberUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1serialNumberUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrarySerialNumberUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1passTypeIdentifierUserInfoKey/title",
          "value": "PKPassLibraryPassTypeIdentifierUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1passTypeIdentifierUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryPassTypeIdentifierUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey/title",
          "value": "PKPassLibraryNotificationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1replacementPassesUserInfoKey/title",
          "value": "PKPassLibraryReplacementPassesUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1replacementPassesUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryReplacementPassesUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1recoveredPassesUserInfoKey/title",
          "value": "PKPassLibraryRecoveredPassesUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryNotificationKey~1recoveredPassesUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryRecoveredPassesUserInfoKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpasslibrarynotificationkey/serialnumberuserinfokey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpasslibrarynotificationkey/serialnumberuserinfokey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
