{
  "abstract": [
    {
      "text": "A recipient for whom there is no valid handle.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noValidHandle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INSendMessageRecipientUnsupportedReason@INSendMessageRecipientUnsupportedReasonNoValidHandle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "noValidHandle"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSendMessageRecipientUnsupportedReasonNoValidHandle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INSendMessageRecipientUnsupportedReason.noValidHandle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "noValidHandle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason": {
      "abstract": [
        {
          "text": "Constants indicating the reason why a recipient is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/messagingServiceNotEnabledForRecipient": {
      "abstract": [
        {
          "text": "A recipient for whom messaging is not enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messagingServiceNotEnabledForRecipient"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/messagingServiceNotEnabledForRecipient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonMessagingServiceNotEnabledForRecipient"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.messagingServiceNotEnabledForRecipient",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/messagingservicenotenabledforrecipient"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noAccount": {
      "abstract": [
        {
          "text": "A recipient without an account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAccount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonNoAccount"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.noAccount",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/noaccount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noHandleForLabel": {
      "abstract": [
        {
          "text": "A recipient for whom there is no handle for the provided label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noHandleForLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noHandleForLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonNoHandleForLabel"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.noHandleForLabel",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/nohandleforlabel"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noValidHandle": {
      "abstract": [
        {
          "text": "A recipient for whom there is no valid handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noValidHandle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noValidHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonNoValidHandle"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.noValidHandle",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/novalidhandle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/offline": {
      "abstract": [
        {
          "text": "An offline recipient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offline"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/offline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonOffline"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.offline",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/offline"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requestedHandleInvalid": {
      "abstract": [
        {
          "text": "A recipient for whom the requested handle is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestedHandleInvalid"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requestedHandleInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonRequestedHandleInvalid"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.requestedHandleInvalid",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/requestedhandleinvalid"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requiringInAppAuthentication": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiringInAppAuthentication"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requiringInAppAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonRequiringInAppAuthentication"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.requiringInAppAuthentication",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/requiringinappauthentication"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noAccount",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/offline",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/messagingServiceNotEnabledForRecipient",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noHandleForLabel",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requestedHandleInvalid",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requiringInAppAuthentication"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSendMessageRecipientUnsupportedReasonNoValidHandle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonNoValidHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noAccount",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/offline",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/messagingServiceNotEnabledForRecipient",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noHandleForLabel",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requestedHandleInvalid",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requiringInAppAuthentication"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INSendMessageRecipientUnsupportedReasonNoValidHandle"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason/title",
          "value": "INSendMessageRecipientUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1requiringInAppAuthentication/title",
          "value": "INSendMessageRecipientUnsupportedReasonRequiringInAppAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1requiringInAppAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonRequiringInAppAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1offline/title",
          "value": "INSendMessageRecipientUnsupportedReasonOffline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1offline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonOffline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1requestedHandleInvalid/title",
          "value": "INSendMessageRecipientUnsupportedReasonRequestedHandleInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1requestedHandleInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonRequestedHandleInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noAccount/title",
          "value": "INSendMessageRecipientUnsupportedReasonNoAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonNoAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noValidHandle/title",
          "value": "INSendMessageRecipientUnsupportedReasonNoValidHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noValidHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonNoValidHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1messagingServiceNotEnabledForRecipient/title",
          "value": "INSendMessageRecipientUnsupportedReasonMessagingServiceNotEnabledForRecipient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1messagingServiceNotEnabledForRecipient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonMessagingServiceNotEnabledForRecipient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noHandleForLabel/title",
          "value": "INSendMessageRecipientUnsupportedReasonNoHandleForLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noHandleForLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonNoHandleForLabel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insendmessagerecipientunsupportedreason/novalidhandle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insendmessagerecipientunsupportedreason/novalidhandle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
