{
  "abstract": [
    {
      "text": "Obtain a Core ML model to use in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/getting-a-core-ml-model"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Getting a Core ML Model"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core ML supports a variety of machine learning models, including neural networks, tree ensembles, support vector machines, and generalized linear models. Core ML requires the Core ML model format (models with a ",
              "type": "text"
            },
            {
              "code": ".mlmodel",
              "type": "codeVoice"
            },
            {
              "text": " file extension).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and your own data, you can train custom models to perform tasks like recognizing images, extracting meaning from text, or finding relationships between numerical values. Models trained using Create ML are in the Core ML model format and are ready to use in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Apple also provides several popular, open source ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/machine-learning/models/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that are already in the Core ML model format. You can download these models and start using them in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Additionally, various research groups and universities publish their models and training data, which may not be in the Core ML model format. Use ",
              "type": "text"
            },
            {
              "identifier": "https://coremltools.readme.io/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to convert these models to use in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel": {
      "abstract": [
        {
          "text": "An encapsulation of all the details of your machine learning model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModel"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModel"
        }
      ],
      "role": "symbol",
      "title": "MLModel",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel"
    },
    "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app": {
      "abstract": [
        {
          "text": "Add a simple model to an app,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "pass input data to the model, and process the model’s predictions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating a Core ML Model into Your App",
      "type": "topic",
      "url": "/documentation/coreml/integrating-a-core-ml-model-into-your-app"
    },
    "doc://com.apple.coreml/documentation/CoreML/model-customization": {
      "abstract": [
        {
          "text": "Expand and modify your model with new layers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/model-customization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model Customization",
      "type": "topic",
      "url": "/documentation/coreml/model-customization"
    },
    "doc://com.apple.coreml/documentation/CoreML/model-personalization": {
      "abstract": [
        {
          "text": "Update your model to adapt to new data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/model-personalization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model Personalization",
      "type": "topic",
      "url": "/documentation/coreml/model-personalization"
    },
    "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package": {
      "abstract": [
        {
          "text": "Convert a Core ML model file into a model package in Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package",
      "kind": "article",
      "role": "article",
      "title": "Updating a Model File to a Model Package",
      "type": "topic",
      "url": "/documentation/coreml/updating-a-model-file-to-a-model-package"
    },
    "doc://com.apple.documentation/documentation/CreateML": {
      "abstract": [
        {
          "text": "Create machine learning models for use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML",
      "kind": "symbol",
      "role": "collection",
      "title": "Create ML",
      "type": "topic",
      "url": "/documentation/CreateML"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://coremltools.readme.io/": {
      "identifier": "https://coremltools.readme.io/",
      "title": "Core ML Tools",
      "titleInlineContent": [
        {
          "text": "Core ML Tools",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://coremltools.readme.io/"
    },
    "https://developer.apple.com/machine-learning/models/": {
      "identifier": "https://developer.apple.com/machine-learning/models/",
      "title": "models",
      "titleInlineContent": [
        {
          "text": "models",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/machine-learning/models/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Core-ML-models",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package",
        "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app",
        "doc://com.apple.coreml/documentation/CoreML/MLModel",
        "doc://com.apple.coreml/documentation/CoreML/model-customization",
        "doc://com.apple.coreml/documentation/CoreML/model-personalization"
      ],
      "title": "Core ML models"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Core-ML-models",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package",
                "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app",
                "doc://com.apple.coreml/documentation/CoreML/MLModel",
                "doc://com.apple.coreml/documentation/CoreML/model-customization",
                "doc://com.apple.coreml/documentation/CoreML/model-personalization"
              ],
              "title": "Core ML models"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/title",
          "value": "MLModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/getting-a-core-ml-model"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/getting-a-core-ml-model"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
