{
  "abstract": [
    {
      "text": "Returns an array that contains all of the compute devices that are accessible.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLAllComputeDevices"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MLAllComputeDevices",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MLAllComputeDevices"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLAllComputeDevices"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MLAllComputeDevices"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<id<MLComputeDeviceProtocol>>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "MLAllComputeDevices"
            },
            {
              "kind": "text",
              "text": "();"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLAllComputeDevices": {
      "abstract": [
        {
          "text": "Returns an array that contains all of the compute devices that are accessible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLAllComputeDevices"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLAllComputeDevices",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLAllComputeDevices",
      "type": "topic",
      "url": "/documentation/coreml/mlallcomputedevices"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLCPUComputeDevice": {
      "abstract": [
        {
          "text": "An object that represents a CPU compute device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPUComputeDevice"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLCPUComputeDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPUComputeDevice"
        }
      ],
      "role": "symbol",
      "title": "MLCPUComputeDevice",
      "type": "topic",
      "url": "/documentation/coreml/mlcpucomputedevice"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeDeviceProtocol": {
      "abstract": [
        {
          "text": "An interface that represents a compute device type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLComputeDeviceProtocol"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeDeviceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLComputeDeviceProtocol"
        }
      ],
      "role": "symbol",
      "title": "MLComputeDeviceProtocol",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputedeviceprotocol"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLGPUComputeDevice": {
      "abstract": [
        {
          "text": "An object that represents a GPU compute device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLGPUComputeDevice"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLGPUComputeDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLGPUComputeDevice"
        }
      ],
      "role": "symbol",
      "title": "MLGPUComputeDevice",
      "type": "topic",
      "url": "/documentation/coreml/mlgpucomputedevice"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLNeuralEngineComputeDevice": {
      "abstract": [
        {
          "text": "An object that represents a Neural Engine compute device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLNeuralEngineComputeDevice"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLNeuralEngineComputeDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLNeuralEngineComputeDevice"
        }
      ],
      "role": "symbol",
      "title": "MLNeuralEngineComputeDevice",
      "type": "topic",
      "url": "/documentation/coreml/mlneuralenginecomputedevice"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compute-devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLCPUComputeDevice",
        "doc://com.apple.coreml/documentation/CoreML/MLGPUComputeDevice",
        "doc://com.apple.coreml/documentation/CoreML/MLNeuralEngineComputeDevice",
        "doc://com.apple.coreml/documentation/CoreML/MLComputeDeviceProtocol"
      ],
      "title": "Compute devices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLGPUComputeDevice/title",
          "value": "MLGPUComputeDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLGPUComputeDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLGPUComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLGPUComputeDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLGPUComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCPUComputeDevice/title",
          "value": "MLCPUComputeDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCPUComputeDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPUComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCPUComputeDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPUComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLNeuralEngineComputeDevice/title",
          "value": "MLNeuralEngineComputeDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLNeuralEngineComputeDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLNeuralEngineComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLNeuralEngineComputeDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLNeuralEngineComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeDeviceProtocol/title",
          "value": "MLComputeDeviceProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeDeviceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeDeviceProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeDeviceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeDeviceProtocol"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlallcomputedevices"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
