{
  "abstract": [
    {
      "text": "An interface that represents a collection of feature providers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MLBatchProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLBatchProvider"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLBatchProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MLBatchProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLBatchProvider"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Similar to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", this interface allows you to define your own batch provider. If you collect your data asynchronously or it is memory intensive, implement this protocol on your data structure to optimize performance with batch processing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLArrayBatchProvider": {
      "abstract": [
        {
          "text": "A convenience wrapper for batches of feature providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLArrayBatchProvider"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLArrayBatchProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLArrayBatchProvider"
        }
      ],
      "role": "symbol",
      "title": "MLArrayBatchProvider",
      "type": "topic",
      "url": "/documentation/coreml/mlarraybatchprovider"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider": {
      "abstract": [
        {
          "text": "An interface that represents a collection of feature providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLBatchProvider"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLBatchProvider"
        }
      ],
      "role": "symbol",
      "title": "MLBatchProvider",
      "type": "topic",
      "url": "/documentation/coreml/mlbatchprovider"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider/count": {
      "abstract": [
        {
          "text": "The number of feature providers in this batch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider/count",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/coreml/mlbatchprovider/count"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider/features(at:)": {
      "abstract": [
        {
          "text": "Returns the feature provider at the given index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "features"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MLFeatureProvider",
          "text": "MLFeatureProvider"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider/features(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "featuresAtIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "features(at:)",
      "type": "topic",
      "url": "/documentation/coreml/mlbatchprovider/features(at:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLDictionaryFeatureProvider": {
      "abstract": [
        {
          "text": "A convenience wrapper for the given dictionary of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLDictionaryFeatureProvider"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLDictionaryFeatureProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLDictionaryFeatureProvider"
        }
      ],
      "role": "symbol",
      "title": "MLDictionaryFeatureProvider",
      "type": "topic",
      "url": "/documentation/coreml/mldictionaryfeatureprovider"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureProvider": {
      "abstract": [
        {
          "text": "An interface that represents a collection of values for either a model’s input or its output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLFeatureProvider"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureProvider"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureProvider",
      "type": "topic",
      "url": "/documentation/coreml/mlfeatureprovider"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureValue": {
      "abstract": [
        {
          "text": "A generic wrapper around an underlying value and the value’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLFeatureValue"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureValue"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureValue",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturevalue"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelAsset": {
      "abstract": [
        {
          "text": "An abstraction of a compiled Core ML model asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelAsset"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelAsset"
        }
      ],
      "role": "symbol",
      "title": "MLModelAsset",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelasset"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLSendableFeatureValue": {
      "abstract": [
        {
          "text": "A sendable feature value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLSendableFeatureValue"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLSendableFeatureValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLSendableFeatureValue"
        }
      ],
      "role": "symbol",
      "title": "MLSendableFeatureValue",
      "type": "topic",
      "url": "/documentation/coreml/mlsendablefeaturevalue"
    },
    "doc://com.apple.coreml/documentation/CoreML/making-predictions-with-a-sequence-of-inputs": {
      "abstract": [
        {
          "text": "Integrate a recurrent neural network model to process sequences of inputs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/making-predictions-with-a-sequence-of-inputs",
      "kind": "article",
      "role": "article",
      "title": "Making Predictions with a Sequence of Inputs",
      "type": "topic",
      "url": "/documentation/coreml/making-predictions-with-a-sequence-of-inputs"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLArrayBatchProvider"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Model-inputs-and-outputs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/making-predictions-with-a-sequence-of-inputs",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureValue",
        "doc://com.apple.coreml/documentation/CoreML/MLSendableFeatureValue",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureProvider",
        "doc://com.apple.coreml/documentation/CoreML/MLDictionaryFeatureProvider",
        "doc://com.apple.coreml/documentation/CoreML/MLArrayBatchProvider",
        "doc://com.apple.coreml/documentation/CoreML/MLModelAsset"
      ],
      "title": "Model inputs and outputs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Values",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider/features(at:)",
        "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider/count"
      ],
      "title": "Accessing Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLBatchProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLBatchProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLBatchProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Values",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider/features(at:)",
                "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider/count"
              ],
              "title": "Accessing Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLArrayBatchProvider"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Model-inputs-and-outputs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/making-predictions-with-a-sequence-of-inputs",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureValue",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureProvider",
                "doc://com.apple.coreml/documentation/CoreML/MLDictionaryFeatureProvider",
                "doc://com.apple.coreml/documentation/CoreML/MLArrayBatchProvider",
                "doc://com.apple.coreml/documentation/CoreML/MLModelAsset"
              ],
              "title": "Model inputs and outputs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLBatchProvider"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelAsset/title",
          "value": "MLModelAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureValue/title",
          "value": "MLFeatureValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLBatchProvider~1count/title",
          "value": "count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLBatchProvider~1count/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLBatchProvider/title",
          "value": "MLBatchProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLBatchProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLBatchProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLBatchProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLBatchProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLDictionaryFeatureProvider/title",
          "value": "MLDictionaryFeatureProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLDictionaryFeatureProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLDictionaryFeatureProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLDictionaryFeatureProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLDictionaryFeatureProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLBatchProvider~1features(at:)/title",
          "value": "featuresAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLBatchProvider~1features(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "featuresAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureProvider/title",
          "value": "MLFeatureProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLArrayBatchProvider/title",
          "value": "MLArrayBatchProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLArrayBatchProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLArrayBatchProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLArrayBatchProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLArrayBatchProvider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlbatchprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlbatchprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
