{
  "abstract": [
    {
      "text": "Compute devices for framework operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:6CoreML15MLComputeDeviceO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLComputeDevice"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLComputeDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MLComputeDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLComputeDevice"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLCPUComputeDevice": {
      "abstract": [
        {
          "text": "An object that represents a CPU compute device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPUComputeDevice"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLCPUComputeDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPUComputeDevice"
        }
      ],
      "role": "symbol",
      "title": "MLCPUComputeDevice",
      "type": "topic",
      "url": "/documentation/coreml/mlcpucomputedevice"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice": {
      "abstract": [
        {
          "text": "Compute devices for framework operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLComputeDevice"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLComputeDevice"
        }
      ],
      "role": "symbol",
      "title": "MLComputeDevice",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputedevice"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/allComputeDevices": {
      "abstract": [
        {
          "text": "Returns an array that contains all of the compute devices that are accessible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allComputeDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML15MLComputeDeviceO",
          "text": "MLComputeDevice"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/allComputeDevices",
      "kind": "symbol",
      "role": "symbol",
      "title": "allComputeDevices",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputedevice/allcomputedevices"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/cpu(_:)": {
      "abstract": [
        {
          "text": "A device that represents a CPU compute device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cpu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCPUComputeDevice",
          "text": "MLCPUComputeDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/cpu(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLComputeDevice.cpu(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputedevice/cpu(_:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/gpu(_:)": {
      "abstract": [
        {
          "text": "A device that represents a GPU compute device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gpu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLGPUComputeDevice",
          "text": "MLGPUComputeDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/gpu(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLComputeDevice.gpu(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputedevice/gpu(_:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/neuralEngine(_:)": {
      "abstract": [
        {
          "text": "A device that represents a Neural Engine compute device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "neuralEngine"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLNeuralEngineComputeDevice",
          "text": "MLNeuralEngineComputeDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/neuralEngine(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLComputeDevice.neuralEngine(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputedevice/neuralengine(_:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeDeviceProtocol": {
      "abstract": [
        {
          "text": "An interface that represents a compute device type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLComputeDeviceProtocol"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeDeviceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLComputeDeviceProtocol"
        }
      ],
      "role": "symbol",
      "title": "MLComputeDeviceProtocol",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputedeviceprotocol"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLGPUComputeDevice": {
      "abstract": [
        {
          "text": "An object that represents a GPU compute device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLGPUComputeDevice"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLGPUComputeDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLGPUComputeDevice"
        }
      ],
      "role": "symbol",
      "title": "MLGPUComputeDevice",
      "type": "topic",
      "url": "/documentation/coreml/mlgpucomputedevice"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLNeuralEngineComputeDevice": {
      "abstract": [
        {
          "text": "An object that represents a Neural Engine compute device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLNeuralEngineComputeDevice"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLNeuralEngineComputeDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLNeuralEngineComputeDevice"
        }
      ],
      "role": "symbol",
      "title": "MLNeuralEngineComputeDevice",
      "type": "topic",
      "url": "/documentation/coreml/mlneuralenginecomputedevice"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compute-devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLCPUComputeDevice",
        "doc://com.apple.coreml/documentation/CoreML/MLGPUComputeDevice",
        "doc://com.apple.coreml/documentation/CoreML/MLNeuralEngineComputeDevice",
        "doc://com.apple.coreml/documentation/CoreML/MLComputeDeviceProtocol"
      ],
      "title": "Compute devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Device-Types",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/cpu(_:)",
        "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/gpu(_:)",
        "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/neuralEngine(_:)"
      ],
      "title": "Device Types"
    },
    {
      "anchor": "Getting-All-Devices",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLComputeDevice/allComputeDevices"
      ],
      "title": "Getting All Devices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLNeuralEngineComputeDevice/title",
          "value": "MLNeuralEngineComputeDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLNeuralEngineComputeDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLNeuralEngineComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLNeuralEngineComputeDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLNeuralEngineComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLGPUComputeDevice/title",
          "value": "MLGPUComputeDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLGPUComputeDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLGPUComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLGPUComputeDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLGPUComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCPUComputeDevice/title",
          "value": "MLCPUComputeDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCPUComputeDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPUComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCPUComputeDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPUComputeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeDeviceProtocol/title",
          "value": "MLComputeDeviceProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeDeviceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeDeviceProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeDeviceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeDeviceProtocol"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlcomputedevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
