{
  "abstract": [
    {
      "text": "A list or range of sizes that augment an image constraint’s default size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLImageSizeConstraint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLImageSizeConstraint"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLImageSizeConstraint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MLImageSizeConstraint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLImageSizeConstraint"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use an ",
              "type": "text"
            },
            {
              "code": "MLImageSizeConstraint",
              "type": "codeVoice"
            },
            {
              "text": " to express what image sizes of an image feature a model will accept as input or produce as output.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/type",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to determine which properties describe what image sizes the model’s image feature expects as input or produces as output.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "code": "type",
              "type": "codeVoice"
            },
            {
              "text": " is:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType/range",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", the image feature accepts any image that has a width in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/pixelsWideRange",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and a height in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/pixelsHighRange",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType/enumerated",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", the image feature accepts any image size listed in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/enumeratedImageSizes",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType/unspecified",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", the ",
                      "type": "text"
                    },
                    {
                      "code": "MLImageSizeConstraint",
                      "type": "codeVoice"
                    },
                    {
                      "text": " instance is not configured and should be ignored. Instead, use the image feature’s default image size constraint, defined by ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint/pixelsWide",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint/pixelsHigh",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3027121",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint/pixelsHigh": {
      "abstract": [
        {
          "text": "The model’s default height for an image feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelsHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint/pixelsHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelsHigh"
        }
      ],
      "role": "symbol",
      "title": "pixelsHigh",
      "type": "topic",
      "url": "/documentation/coreml/mlimageconstraint/pixelshigh"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint/pixelsWide": {
      "abstract": [
        {
          "text": "The model’s default width for an image feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelsWide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint/pixelsWide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelsWide"
        }
      ],
      "role": "symbol",
      "title": "pixelsWide",
      "type": "topic",
      "url": "/documentation/coreml/mlimageconstraint/pixelswide"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint/sizeConstraint": {
      "abstract": [
        {
          "text": "Additional sizes this image feature supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeConstraint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLImageSizeConstraint",
          "text": "MLImageSizeConstraint"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint/sizeConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sizeConstraint"
        }
      ],
      "role": "symbol",
      "title": "sizeConstraint",
      "type": "topic",
      "url": "/documentation/coreml/mlimageconstraint/sizeconstraint"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageSize": {
      "abstract": [
        {
          "text": "The width and height of an image feature size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLImageSize"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLImageSize"
        }
      ],
      "role": "symbol",
      "title": "MLImageSize",
      "type": "topic",
      "url": "/documentation/coreml/mlimagesize"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint": {
      "abstract": [
        {
          "text": "A list or range of sizes that augment an image constraint’s default size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLImageSizeConstraint"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLImageSizeConstraint"
        }
      ],
      "role": "symbol",
      "title": "MLImageSizeConstraint",
      "type": "topic",
      "url": "/documentation/coreml/mlimagesizeconstraint"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/enumeratedImageSizes": {
      "abstract": [
        {
          "text": "An array of image sizes a model’s image feature accepts as input or produces as output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumeratedImageSizes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLImageSize",
          "text": "MLImageSize"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/enumeratedImageSizes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumeratedImageSizes"
        }
      ],
      "role": "symbol",
      "title": "enumeratedImageSizes",
      "type": "topic",
      "url": "/documentation/coreml/mlimagesizeconstraint/enumeratedimagesizes"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/pixelsHighRange": {
      "abstract": [
        {
          "text": "The range of heights a model’s image feature accepts as input or produces as output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelsHighRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/pixelsHighRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelsHighRange"
        }
      ],
      "role": "symbol",
      "title": "pixelsHighRange",
      "type": "topic",
      "url": "/documentation/coreml/mlimagesizeconstraint/pixelshighrange"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/pixelsWideRange": {
      "abstract": [
        {
          "text": "The range of widths a model’s image feature accepts as input or produces as output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelsWideRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/pixelsWideRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelsWideRange"
        }
      ],
      "role": "symbol",
      "title": "pixelsWideRange",
      "type": "topic",
      "url": "/documentation/coreml/mlimagesizeconstraint/pixelswiderange"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/type": {
      "abstract": [
        {
          "text": "Indicator of which properties to inspect for this image size constraint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLImageSizeConstraintType",
          "text": "MLImageSizeConstraintType"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/coreml/mlimagesizeconstraint/type"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType": {
      "abstract": [
        {
          "text": "The modes that determine how the model defines a feature’s image size constraint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLImageSizeConstraintType"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLImageSizeConstraintType"
        }
      ],
      "role": "symbol",
      "title": "MLImageSizeConstraintType",
      "type": "topic",
      "url": "/documentation/coreml/mlimagesizeconstrainttype"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType/enumerated": {
      "abstract": [
        {
          "text": "The image feature accepts image sizes listed in an array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerated"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType/enumerated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLImageSizeConstraintTypeEnumerated"
        }
      ],
      "role": "symbol",
      "title": "MLImageSizeConstraintType.enumerated",
      "type": "topic",
      "url": "/documentation/coreml/mlimagesizeconstrainttype/enumerated"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType/range": {
      "abstract": [
        {
          "text": "The image feature accepts image sizes defined by a range of widths and a range of heights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "range"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType/range",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLImageSizeConstraintTypeRange"
        }
      ],
      "role": "symbol",
      "title": "MLImageSizeConstraintType.range",
      "type": "topic",
      "url": "/documentation/coreml/mlimagesizeconstrainttype/range"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType/unspecified": {
      "abstract": [
        {
          "text": "The image size constraint is not configured and should be ignored.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLImageSizeConstraintTypeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MLImageSizeConstraintType.unspecified",
      "type": "topic",
      "url": "/documentation/coreml/mlimagesizeconstrainttype/unspecified"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-3027121": {
      "alt": "Graph diagram showing the constraint’s rectangle defined by the width and height ranges of the constraint, and a blue rectangle, representing a valid image size. The diagram’s X-axis spans from 0 to 250 pixels and the Y-axis spans from 0 to 200 pixels. The constraint rectangle, which has a dashed outline, has a width that spans from 50 to 250 pixels, and a height that spans from 100 to 200 pixels. The sample image size has its lower-left corner at the graph’s origin and its upper-right corner is within the bounds of the constraint rectangle, at 150 pixels wide by 180 pixels high.",
      "identifier": "media-3027121",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d99ccb61d4b994effa121d2a119b98ff/media-3027121@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/afe7b7918b6b468719cbceade898210e/media-3027121~dark@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Acceptable-Sizes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint/sizeConstraint"
      ],
      "title": "Inspecting Acceptable Sizes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-Relevant-Constraints",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/type",
        "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType"
      ],
      "title": "Determining Relevant Constraints"
    },
    {
      "anchor": "Accessing-the-Image-Size-Ranges",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/pixelsWideRange",
        "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/pixelsHighRange"
      ],
      "title": "Accessing the Image Size Ranges"
    },
    {
      "anchor": "Accessing-the-Enumerated-Image-Sizes",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/enumeratedImageSizes",
        "doc://com.apple.coreml/documentation/CoreML/MLImageSize"
      ],
      "title": "Accessing the Enumerated Image Sizes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLImageSizeConstraint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSizeConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSizeConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-Relevant-Constraints",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/type",
                "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraintType"
              ],
              "title": "Determining Relevant Constraints"
            },
            {
              "anchor": "Accessing-the-Image-Size-Ranges",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/pixelsWideRange",
                "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/pixelsHighRange"
              ],
              "title": "Accessing the Image Size Ranges"
            },
            {
              "anchor": "Accessing-the-Enumerated-Image-Sizes",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLImageSizeConstraint/enumeratedImageSizes",
                "doc://com.apple.coreml/documentation/CoreML/MLImageSize"
              ],
              "title": "Accessing the Enumerated Image Sizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-Acceptable-Sizes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint/sizeConstraint"
              ],
              "title": "Inspecting Acceptable Sizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLImageSizeConstraint"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraintType~1unspecified/title",
          "value": "MLImageSizeConstraintTypeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraintType~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSizeConstraintTypeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageConstraint~1pixelsWide/title",
          "value": "pixelsWide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageConstraint~1pixelsWide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelsWide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint~1enumeratedImageSizes/title",
          "value": "enumeratedImageSizes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint~1enumeratedImageSizes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enumeratedImageSizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraintType~1range/title",
          "value": "MLImageSizeConstraintTypeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraintType~1range/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSizeConstraintTypeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraintType/title",
          "value": "MLImageSizeConstraintType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraintType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSizeConstraintType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraintType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSizeConstraintType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSize/title",
          "value": "MLImageSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint~1pixelsWideRange/title",
          "value": "pixelsWideRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint~1pixelsWideRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelsWideRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageConstraint~1sizeConstraint/title",
          "value": "sizeConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageConstraint~1sizeConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sizeConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint~1pixelsHighRange/title",
          "value": "pixelsHighRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint~1pixelsHighRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelsHighRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageConstraint~1pixelsHigh/title",
          "value": "pixelsHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageConstraint~1pixelsHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelsHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraintType~1enumerated/title",
          "value": "MLImageSizeConstraintTypeEnumerated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraintType~1enumerated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSizeConstraintTypeEnumerated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint/title",
          "value": "MLImageSizeConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSizeConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageSizeConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageSizeConstraint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlimagesizeconstraint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlimagesizeconstraint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
