{
  "abstract": [
    {
      "text": "Information about a Core ML model error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC12MLModelErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLModelError"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLModelError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MLModelError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLModelError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct": {
      "abstract": [
        {
          "text": "Information about a Core ML model error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelError"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelError"
        }
      ],
      "role": "symbol",
      "title": "MLModelError",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Information about a Core ML model error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/customLayer": {
      "abstract": [
        {
          "text": "An error code for problems related to custom layers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/customLayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "customLayer",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/customlayer"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/customModel": {
      "abstract": [
        {
          "text": "An error code for problems related to custom models.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/customModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "customModel",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/custommodel"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/errordomain"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/featureType": {
      "abstract": [
        {
          "text": "An error code for problems related to model features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/featureType",
      "kind": "symbol",
      "role": "symbol",
      "title": "featureType",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/featuretype"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/generic": {
      "abstract": [
        {
          "text": "An error code for runtime issues that don’t apply to the other error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/generic",
      "kind": "symbol",
      "role": "symbol",
      "title": "generic",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/generic"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/io": {
      "abstract": [
        {
          "text": "An error code for problems related to the system’s input or output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "io"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/io",
      "kind": "symbol",
      "role": "symbol",
      "title": "io",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/io"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/modelCollection": {
      "abstract": [
        {
          "text": "An error code for problems related to retrieving a model collection from the deployment system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/modelCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "modelCollection",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/modelcollection"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/modelDecryption": {
      "abstract": [
        {
          "text": "An error code for problems related to decrypting models.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelDecryption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/modelDecryption",
      "kind": "symbol",
      "role": "symbol",
      "title": "modelDecryption",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/modeldecryption"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/modelDecryptionKeyFetch": {
      "abstract": [
        {
          "text": "An error code for problems related to retrieving a model’s decryption key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelDecryptionKeyFetch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/modelDecryptionKeyFetch",
      "kind": "symbol",
      "role": "symbol",
      "title": "modelDecryptionKeyFetch",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/modeldecryptionkeyfetch"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/parameters": {
      "abstract": [
        {
          "text": "An error code for problems related to model parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/parameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "parameters",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/parameters"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/predictionCancelled": {
      "abstract": [
        {
          "text": "An error code for problems related to cancelling the prediction before it completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictionCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/predictionCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "predictionCancelled",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/predictioncancelled"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/update": {
      "abstract": [
        {
          "text": "An error code for problems related to on-device model updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC12MLModelErrorLeV",
          "text": "MLModelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLModelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/update",
      "kind": "symbol",
      "role": "symbol",
      "title": "update",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/update"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Core ML errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MLModelErrorDomain",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Model-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code",
        "doc://com.apple.coreml/documentation/CoreML/MLModelErrorDomain"
      ],
      "title": "Model errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/featureType",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/parameters",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/modelCollection",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/modelDecryptionKeyFetch",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/modelDecryption",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/update",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/customLayer",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/customModel",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/io",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/predictionCancelled",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/generic",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Error-Domain",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelErrorDomain"
      ],
      "title": "Error Domain"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelErrorDomain/title",
          "value": "MLModelErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code/title",
          "value": "MLModelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlmodelerror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
