{
  "abstract": [
    {
      "text": "Information about a model, primarily the input and output format for each feature the model expects, and optional metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLModelDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLModelDescription"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLModelDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MLModelDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLModelDescription"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription": {
      "abstract": [
        {
          "text": "The name, type, and constraints of an input or output feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLFeatureDescription"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureDescription"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureDescription",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturedescription"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel/availableComputeDevices-42uzt": {
      "abstract": [
        {
          "text": "The list of available compute devices that the model’s prediction can use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "availableComputeDevices"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/availableComputeDevices-42uzt",
      "kind": "symbol",
      "role": "symbol",
      "title": "availableComputeDevices",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel/availablecomputedevices-42uzt"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel/availableComputeDevices-6klyt": {
      "abstract": [
        {
          "text": "The list of available compute devices that the model’s prediction methods use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableComputeDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML15MLComputeDeviceO",
          "text": "MLComputeDevice"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/availableComputeDevices-6klyt",
      "kind": "symbol",
      "role": "symbol",
      "title": "availableComputeDevices",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel/availablecomputedevices-6klyt"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel/configuration": {
      "abstract": [
        {
          "text": "The configuration of the model set during initialization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelConfiguration",
          "text": "MLModelConfiguration"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel/configuration"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel/modelDescription": {
      "abstract": [
        {
          "text": "Model information you use at runtime during development, which Xcode also displays in its Core ML model editor view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelDescription",
          "text": "MLModelDescription"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/modelDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modelDescription"
        }
      ],
      "role": "symbol",
      "title": "modelDescription",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel/modeldescription"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel/parameterValue(for:)": {
      "abstract": [
        {
          "text": "Returns a model parameter value for a key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/parameterValue(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parameterValueForKey:error:"
        }
      ],
      "role": "symbol",
      "title": "parameterValue(for:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel/parametervalue(for:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription": {
      "abstract": [
        {
          "text": "Information about a model, primarily the input and output format for each feature the model expects, and optional metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelDescription"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelDescription"
        }
      ],
      "role": "symbol",
      "title": "MLModelDescription",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/classLabels": {
      "abstract": [
        {
          "text": "An array of labels, which can be either strings or a numbers, for classifier models.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classLabels"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/classLabels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "classLabels"
        }
      ],
      "role": "symbol",
      "title": "classLabels",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription/classlabels"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/inputDescriptionsByName": {
      "abstract": [
        {
          "text": "A dictionary of input feature descriptions, which the model keys by the input’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputDescriptionsByName"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLFeatureDescription",
          "text": "MLFeatureDescription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/inputDescriptionsByName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputDescriptionsByName"
        }
      ],
      "role": "symbol",
      "title": "inputDescriptionsByName",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription/inputdescriptionsbyname"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/isUpdatable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can update the model with additional training.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isUpdatable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/isUpdatable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isUpdatable"
        }
      ],
      "role": "symbol",
      "title": "isUpdatable",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription/isupdatable"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/metadata": {
      "abstract": [
        {
          "text": "A dictionary of the model’s creation information, such as its description, author, version, and license.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MLModelMetadataKey",
          "text": "MLModelMetadataKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription/metadata"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/outputDescriptionsByName": {
      "abstract": [
        {
          "text": "A dictionary of output feature descriptions, which the model keys by the output’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputDescriptionsByName"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLFeatureDescription",
          "text": "MLFeatureDescription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/outputDescriptionsByName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputDescriptionsByName"
        }
      ],
      "role": "symbol",
      "title": "outputDescriptionsByName",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription/outputdescriptionsbyname"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/parameterDescriptionsByKey": {
      "abstract": [
        {
          "text": "A dictionary of the descriptions for the model’s parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterDescriptionsByKey"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterKey",
          "text": "MLParameterKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLParameterDescription",
          "text": "MLParameterDescription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/parameterDescriptionsByKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parameterDescriptionsByKey"
        }
      ],
      "role": "symbol",
      "title": "parameterDescriptionsByKey",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription/parameterdescriptionsbykey"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/predictedFeatureName": {
      "abstract": [
        {
          "text": "The name of the primary prediction feature output description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictedFeatureName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/predictedFeatureName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predictedFeatureName"
        }
      ],
      "role": "symbol",
      "title": "predictedFeatureName",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription/predictedfeaturename"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/predictedProbabilitiesName": {
      "abstract": [
        {
          "text": "The name of the feature output description for all probabilities of a prediction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictedProbabilitiesName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/predictedProbabilitiesName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predictedProbabilitiesName"
        }
      ],
      "role": "symbol",
      "title": "predictedProbabilitiesName",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription/predictedprobabilitiesname"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/stateDescriptionsByName": {
      "abstract": [
        {
          "text": "Description of the state features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateDescriptionsByName"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLFeatureDescription",
          "text": "MLFeatureDescription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/stateDescriptionsByName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stateDescriptionsByName"
        }
      ],
      "role": "symbol",
      "title": "stateDescriptionsByName",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription/statedescriptionsbyname"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/trainingInputDescriptionsByName": {
      "abstract": [
        {
          "text": "A dictionary of the training input feature descriptions, which the model keys by the input’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trainingInputDescriptionsByName"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLFeatureDescription",
          "text": "MLFeatureDescription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/trainingInputDescriptionsByName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trainingInputDescriptionsByName"
        }
      ],
      "role": "symbol",
      "title": "trainingInputDescriptionsByName",
      "type": "topic",
      "url": "/documentation/coreml/mlmodeldescription/traininginputdescriptionsbyname"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey": {
      "abstract": [
        {
          "text": "The set of keys the model uses to store values in its metadata dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "MLModelMetadataKey",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelmetadatakey"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterDescription": {
      "abstract": [
        {
          "text": "A description of a model parameter that includes a default value and a constraint, if applicable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLParameterDescription"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLParameterDescription"
        }
      ],
      "role": "symbol",
      "title": "MLParameterDescription",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterdescription"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLParameterKey": {
      "abstract": [
        {
          "text": "The keys for the parameter dictionary in a model configuration or a model update context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLParameterKey"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLParameterKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLParameterKey"
        }
      ],
      "role": "symbol",
      "title": "MLParameterKey",
      "type": "topic",
      "url": "/documentation/coreml/mlparameterkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-Model",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModel/availableComputeDevices-6klyt",
        "doc://com.apple.coreml/documentation/CoreML/MLModel/configuration",
        "doc://com.apple.coreml/documentation/CoreML/MLModel/modelDescription",
        "doc://com.apple.coreml/documentation/CoreML/MLModel/parameterValue(for:)",
        "doc://com.apple.coreml/documentation/CoreML/MLParameterKey"
      ],
      "title": "Inspecting a Model"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Feature-Descriptions",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/inputDescriptionsByName",
        "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/outputDescriptionsByName",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription"
      ],
      "title": "Accessing Feature Descriptions"
    },
    {
      "anchor": "Accessing-Metadata",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/classLabels",
        "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/metadata",
        "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey"
      ],
      "title": "Accessing Metadata"
    },
    {
      "anchor": "Accessing-Prediction-Names",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/predictedFeatureName",
        "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/predictedProbabilitiesName"
      ],
      "title": "Accessing Prediction Names"
    },
    {
      "anchor": "Accessing-Update-Descriptions",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/isUpdatable",
        "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/trainingInputDescriptionsByName",
        "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/parameterDescriptionsByKey",
        "doc://com.apple.coreml/documentation/CoreML/MLParameterDescription"
      ],
      "title": "Accessing Update Descriptions"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/stateDescriptionsByName"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLModelDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Feature-Descriptions",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/inputDescriptionsByName",
                "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/outputDescriptionsByName",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription"
              ],
              "title": "Accessing Feature Descriptions"
            },
            {
              "anchor": "Accessing-Metadata",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/classLabels",
                "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/metadata",
                "doc://com.apple.coreml/documentation/CoreML/MLModelMetadataKey"
              ],
              "title": "Accessing Metadata"
            },
            {
              "anchor": "Accessing-Prediction-Names",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/predictedFeatureName",
                "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/predictedProbabilitiesName"
              ],
              "title": "Accessing Prediction Names"
            },
            {
              "anchor": "Accessing-Update-Descriptions",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/isUpdatable",
                "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/trainingInputDescriptionsByName",
                "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/parameterDescriptionsByKey",
                "doc://com.apple.coreml/documentation/CoreML/MLParameterDescription"
              ],
              "title": "Accessing Update Descriptions"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLModelDescription/stateDescriptionsByName"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-Model",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLModel/availableComputeDevices-42uzt",
                "doc://com.apple.coreml/documentation/CoreML/MLModel/configuration",
                "doc://com.apple.coreml/documentation/CoreML/MLModel/modelDescription",
                "doc://com.apple.coreml/documentation/CoreML/MLModel/parameterValue(for:)",
                "doc://com.apple.coreml/documentation/CoreML/MLParameterKey"
              ],
              "title": "Inspecting a Model"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLModelDescription"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription/title",
          "value": "MLModelDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1classLabels/title",
          "value": "classLabels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1classLabels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "classLabels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1isUpdatable/title",
          "value": "isUpdatable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1isUpdatable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isUpdatable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1parameterValue(for:)/title",
          "value": "parameterValueForKey:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1parameterValue(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "parameterValueForKey:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1configuration/title",
          "value": "configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1configuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey/title",
          "value": "MLParameterKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLParameterKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLParameterKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey/title",
          "value": "MLModelMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelMetadataKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterDescription/title",
          "value": "MLParameterDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLParameterDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLParameterDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLParameterDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1outputDescriptionsByName/title",
          "value": "outputDescriptionsByName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1outputDescriptionsByName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputDescriptionsByName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1stateDescriptionsByName/title",
          "value": "stateDescriptionsByName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1stateDescriptionsByName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stateDescriptionsByName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription/title",
          "value": "MLFeatureDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1predictedProbabilitiesName/title",
          "value": "predictedProbabilitiesName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1predictedProbabilitiesName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "predictedProbabilitiesName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1modelDescription/title",
          "value": "modelDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1modelDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "modelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1parameterDescriptionsByKey/title",
          "value": "parameterDescriptionsByKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1parameterDescriptionsByKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parameterDescriptionsByKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1predictedFeatureName/title",
          "value": "predictedFeatureName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1predictedFeatureName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "predictedFeatureName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1trainingInputDescriptionsByName/title",
          "value": "trainingInputDescriptionsByName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1trainingInputDescriptionsByName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trainingInputDescriptionsByName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1inputDescriptionsByName/title",
          "value": "inputDescriptionsByName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelDescription~1inputDescriptionsByName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputDescriptionsByName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlmodeldescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlmodeldescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
