{
  "abstract": [
    {
      "text": "Constants that define the underlying element types a multiarray can store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLMultiArrayDataType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLMultiArrayDataType"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLMultiArrayDataType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MLMultiArrayDataType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "All elements of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance must be of the same type and must be defined in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray": {
      "abstract": [
        {
          "text": "A machine learning collection type that stores numeric values in an array with multiple dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMultiArray"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArray"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArray",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-3eqoq": {
      "abstract": [
        {
          "text": "Creates a multiarray from a collection of integers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-3eqoq",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(_:)-3eqoq"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-8bsfu": {
      "abstract": [
        {
          "text": "Creates a multiarray from a collection of doubles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-8bsfu",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(_:)-8bsfu"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-fh2x": {
      "abstract": [
        {
          "text": "Creates a multiarray from a collection of floats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-fh2x",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(_:)-fh2x"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-wk41": {
      "abstract": [
        {
          "text": "Creates a multiarray from a shaped array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "ShapedArray"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "ShapedArray"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-wk41",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(_:)-wk41"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(byConcatenatingMultiArrays:alongAxis:dataType:)": {
      "abstract": [
        {
          "text": "Merges an array of multiarrays into one multiarray along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byConcatenatingMultiArrays"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLMultiArray",
          "text": "MLMultiArray"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "alongAxis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMultiArrayDataType",
          "text": "MLMultiArrayDataType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(byConcatenatingMultiArrays:alongAxis:dataType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "multiArrayByConcatenatingMultiArrays:alongAxis:dataType:"
        }
      ],
      "role": "symbol",
      "title": "init(byConcatenatingMultiArrays:alongAxis:dataType:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(byconcatenatingmultiarrays:alongaxis:datatype:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(dataPointer:shape:dataType:strides:deallocator:)": {
      "abstract": [
        {
          "text": "Creates a multiarray from a data pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "dataPointer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "dataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMultiArrayDataType",
          "text": "MLMultiArrayDataType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "strides"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "deallocator"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(dataPointer:shape:dataType:strides:deallocator:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDataPointer:shape:dataType:strides:deallocator:error:"
        }
      ],
      "role": "symbol",
      "title": "init(dataPointer:shape:dataType:strides:deallocator:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(datapointer:shape:datatype:strides:deallocator:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(pixelBuffer:shape:)": {
      "abstract": [
        {
          "text": "Creates a multiarray sharing the surface of a pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "pixelBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(pixelBuffer:shape:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPixelBuffer:shape:"
        }
      ],
      "role": "symbol",
      "title": "init(pixelBuffer:shape:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(pixelbuffer:shape:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(shape:dataType:)": {
      "abstract": [
        {
          "text": "Creates a multidimensional array with a shape and type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "dataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMultiArrayDataType",
          "text": "MLMultiArrayDataType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(shape:dataType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithShape:dataType:error:"
        }
      ],
      "role": "symbol",
      "title": "init(shape:dataType:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray/init(shape:datatype:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType": {
      "abstract": [
        {
          "text": "Constants that define the underlying element types a multiarray can store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataType"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataType"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArrayDataType",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarraydatatype"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/double": {
      "abstract": [
        {
          "text": "Designates the multiarray’s elements as doubles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataTypeDouble"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArrayDataType.double",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarraydatatype/double"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float": {
      "abstract": [
        {
          "text": "Designates the multiarray’s elements as floats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMultiArrayDataType",
          "text": "MLMultiArrayDataType"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataTypeFloat"
        }
      ],
      "role": "symbol",
      "title": "float",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarraydatatype/float"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float16": {
      "abstract": [
        {
          "text": "Designates the multiarray’s elements as 16-bit floats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float16"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataTypeFloat16"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArrayDataType.float16",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarraydatatype/float16"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float32": {
      "abstract": [
        {
          "text": "Designates the multiarray’s elements as 32-bit floats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float32"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataTypeFloat32"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArrayDataType.float32",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarraydatatype/float32"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float64": {
      "abstract": [
        {
          "text": "Designates the multiarray’s elements as 64-bit floats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMultiArrayDataType",
          "text": "MLMultiArrayDataType"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataTypeFloat64"
        }
      ],
      "role": "symbol",
      "title": "float64",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarraydatatype/float64"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarraydatatype/init(rawvalue:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/int32": {
      "abstract": [
        {
          "text": "Designates the multiarray’s elements as 32-bit integers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int32"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/int32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArrayDataTypeInt32"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArrayDataType.int32",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarraydatatype/int32"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Multiarray",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-3eqoq",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-fh2x",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-8bsfu",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(shape:dataType:)",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(_:)-wk41",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(dataPointer:shape:dataType:strides:deallocator:)",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(byConcatenatingMultiArrays:alongAxis:dataType:)",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(pixelBuffer:shape:)"
      ],
      "title": "Creating a Multiarray"
    }
  ],
  "topicSections": [
    {
      "anchor": "Multiarray-Data-Types",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/int32",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float16",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float32",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/double",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float64"
      ],
      "title": "Multiarray Data Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLMultiArrayDataType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Multiarray-Data-Types",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/int32",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float16",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float32",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/double",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayDataType/float64"
              ],
              "title": "Multiarray Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Multiarray",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(shape:dataType:)",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(dataPointer:shape:dataType:strides:deallocator:)",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(byConcatenatingMultiArrays:alongAxis:dataType:)",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArray/init(pixelBuffer:shape:)"
              ],
              "title": "Creating a Multiarray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLMultiArrayDataType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(byConcatenatingMultiArrays:alongAxis:dataType:)/title",
          "value": "multiArrayByConcatenatingMultiArrays:alongAxis:dataType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(byConcatenatingMultiArrays:alongAxis:dataType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "multiArrayByConcatenatingMultiArrays:alongAxis:dataType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray/title",
          "value": "MLMultiArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1double/title",
          "value": "MLMultiArrayDataTypeDouble"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataTypeDouble"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(pixelBuffer:shape:)/title",
          "value": "initWithPixelBuffer:shape:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(pixelBuffer:shape:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPixelBuffer:shape:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1float64/title",
          "value": "MLMultiArrayDataTypeFloat64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1float64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataTypeFloat64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(shape:dataType:)/title",
          "value": "initWithShape:dataType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(shape:dataType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithShape:dataType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1float32/title",
          "value": "MLMultiArrayDataTypeFloat32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1float32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataTypeFloat32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1float/title",
          "value": "MLMultiArrayDataTypeFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataTypeFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1float16/title",
          "value": "MLMultiArrayDataTypeFloat16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1float16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataTypeFloat16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(dataPointer:shape:dataType:strides:deallocator:)/title",
          "value": "initWithDataPointer:shape:dataType:strides:deallocator:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray~1init(dataPointer:shape:dataType:strides:deallocator:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDataPointer:shape:dataType:strides:deallocator:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1int32/title",
          "value": "MLMultiArrayDataTypeInt32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType~1int32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataTypeInt32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType/title",
          "value": "MLMultiArrayDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayDataType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlmultiarraydatatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlmultiarraydatatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
