{
  "abstract": [
    {
      "text": "An interface that defines a shaped array type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:6CoreML21MLShapedArrayProtocolP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLShapedArrayProtocol"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLShapedArrayProtocol"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MLShapedArrayProtocol"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLShapedArrayProtocol"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/Scalar-swift.associatedtype",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
              "text": "Scalar"
            },
            {
              "kind": "text",
              "text": "> : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
              "text": "ExpressibleByArrayLiteral"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SM",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SM",
              "text": "MutableCollection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sk",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sk",
              "text": "RandomAccessCollection"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "Self"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sl5IndexQa",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sl5IndexQa",
              "text": "Index"
            },
            {
              "kind": "text",
              "text": " == "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureType": {
      "abstract": [
        {
          "text": "The possible types for feature values, input features, and output features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLFeatureType"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureType"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureType",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturetype"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArray": {
      "abstract": [
        {
          "text": "A machine learning collection type that stores numeric values in an array with multiple dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMultiArray"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArray"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArray",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarray"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLSequence": {
      "abstract": [
        {
          "text": "A machine learning collection type that stores a series of strings or integers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLSequence"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLSequence"
        }
      ],
      "role": "symbol",
      "title": "MLSequence",
      "type": "topic",
      "url": "/documentation/coreml/mlsequence"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArray": {
      "abstract": [
        {
          "text": "A machine learning collection type that stores scalar values in a multidimensional array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLShapedArray"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLShapedArray"
        }
      ],
      "role": "symbol",
      "title": "MLShapedArray",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarray"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol": {
      "abstract": [
        {
          "text": "An interface that defines a shaped array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLShapedArrayProtocol"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLShapedArrayProtocol"
        }
      ],
      "role": "symbol",
      "title": "MLShapedArrayProtocol",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/Scalar-swift.associatedtype": {
      "abstract": [
        {
          "text": "Represents the underlying scalar type of the shaped array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "associatedtype"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML19MLShapedArrayScalarP",
          "text": "MLShapedArrayScalar"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/Scalar-swift.associatedtype",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "Scalar",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/scalar-swift.associatedtype"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/count": {
      "abstract": [
        {
          "text": "The number of elements in the shaped array’s first dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/count",
      "kind": "symbol",
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/count"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/fill(with:)-6a5k1": {
      "abstract": [
        {
          "text": "Assigns the shaped array’s elements to the elements in a collection, repeatedly, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fill"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/fill(with:)-6a5k1",
      "kind": "symbol",
      "role": "symbol",
      "title": "fill(with:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/fill(with:)-6a5k1"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/fill(with:)-9qpes": {
      "abstract": [
        {
          "text": "Assigns the shaped array’s elements to a value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fill"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/fill(with:)-9qpes",
      "kind": "symbol",
      "role": "symbol",
      "title": "fill(with:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/fill(with:)-9qpes"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(_:)": {
      "abstract": [
        {
          "text": "Creates a shaped array type from a multiarray.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLMultiArray",
          "text": "MLMultiArray"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(_:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(bytesNoCopy:shape:deallocator:)": {
      "abstract": [
        {
          "text": "Creates a shaped array type from a data pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bytesNoCopy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "deallocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV11DeallocatorO",
          "text": "Deallocator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(bytesNoCopy:shape:deallocator:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(bytesNoCopy:shape:deallocator:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(bytesnocopy:shape:deallocator:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(bytesNoCopy:shape:strides:deallocator:)": {
      "abstract": [
        {
          "text": "Creates a shaped array type from a data pointer with memory strides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bytesNoCopy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "strides"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "deallocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV11DeallocatorO",
          "text": "Deallocator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(bytesNoCopy:shape:strides:deallocator:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "init(bytesNoCopy:shape:strides:deallocator:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(bytesnocopy:shape:strides:deallocator:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(converting:)-3d2eu": {
      "abstract": [
        {
          "text": "Creates a shaped array type by converting a multiarray.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "converting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLMultiArray",
          "text": "MLMultiArray"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(converting:)-3d2eu",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(converting:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(converting:)-3d2eu"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(converting:)-701ib": {
      "abstract": [
        {
          "text": "Creates a shaped array type by converting another shaped array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "converting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(converting:)-701ib",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(converting:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(converting:)-701ib"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(identityMatrixOfSize:)-1xx88": {
      "abstract": [
        {
          "text": "Initialize as an identity matrix.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Scalar",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "BinaryFloatingPoint",
            "type": "codeVoice"
          },
          {
            "text": " and ",
            "type": "text"
          },
          {
            "code": "Scalar.RawSignificand",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identityMatrixOfSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(identityMatrixOfSize:)-1xx88",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(identityMatrixOfSize:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(identitymatrixofsize:)-1xx88"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(identityMatrixOfSize:)-77y0e": {
      "abstract": [
        {
          "text": "Creates a shaped array type that’s an identity matrix of integers.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Scalar",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identityMatrixOfSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(identityMatrixOfSize:)-77y0e",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(identityMatrixOfSize:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(identitymatrixofsize:)-77y0e"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(randomScalarsIn:shape:)-4c8k1": {
      "abstract": [
        {
          "text": "Initialize the shaped array with random scalar values.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Scalar",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "BinaryFloatingPoint",
            "type": "codeVoice"
          },
          {
            "text": " and ",
            "type": "text"
          },
          {
            "code": "Scalar.RawSignificand",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "randomScalarsIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(randomScalarsIn:shape:)-4c8k1",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(randomScalarsIn:shape:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(randomscalarsin:shape:)-4c8k1"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(randomScalarsIn:shape:)-99fnn": {
      "abstract": [
        {
          "text": "Creates a shaped array type that initializes the elements to random integer values within a range.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Scalar",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "randomScalarsIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(randomScalarsIn:shape:)-99fnn",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(randomScalarsIn:shape:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(randomscalarsin:shape:)-99fnn"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(repeating:shape:)": {
      "abstract": [
        {
          "text": "Creates a shaped array type that initializes every element to the same value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "repeating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(repeating:shape:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(repeating:shape:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(repeating:shape:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(scalars:shape:)": {
      "abstract": [
        {
          "text": "Creates a shaped array type from an array of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "scalars"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(scalars:shape:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(scalars:shape:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(scalars:shape:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(unsafeUninitializedShape:initializingWith:)": {
      "abstract": [
        {
          "text": "Creates a shaped array type from a shape and a closure that initializes its memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "unsafeUninitializedShape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "initializingWith"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sr",
          "text": "UnsafeMutableBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ">, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(unsafeUninitializedShape:initializingWith:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "init(unsafeUninitializedShape:initializingWith:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/init(unsafeuninitializedshape:initializingwith:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/isScalar": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the shaped array lacks a shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isScalar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/isScalar",
      "kind": "symbol",
      "role": "symbol",
      "title": "isScalar",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/isscalar"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/scalar-swift.property": {
      "abstract": [
        {
          "text": "A computed property that returns the first element when the shape isn’t empty, or sets the shaped array’s underlying scalar type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scalar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/scalar-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "scalar",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/scalar-swift.property"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/scalarCount": {
      "abstract": [
        {
          "text": "The total number of elements in the shaped array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scalarCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/scalarCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "scalarCount",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/scalarcount"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/scalars": {
      "abstract": [
        {
          "text": "A computed property that generates a linear array that contains every element, or assigns the elements of an array to the shaped array’s elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scalars"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/scalars",
      "kind": "symbol",
      "role": "symbol",
      "title": "scalars",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/scalars"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/shape": {
      "abstract": [
        {
          "text": "An integer array in which each element represents the size of the corresponding dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/shape",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "shape",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/shape"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/strides": {
      "abstract": [
        {
          "text": "An integer array in which each element is the number of memory locations that spans the length of the corresponding dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strides"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/strides",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "strides",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/strides"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/subscript(_:)-1q1sr": {
      "abstract": [
        {
          "text": "Accesses a slice using a collection of integer ranges, in which each element is a range in the corresponding dimension.",
          "type": "text"
        }
      ],
      "defaultImplementations": 7,
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML18MLShapedArraySliceV",
          "text": "MLShapedArraySlice"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/subscript(_:)-1q1sr",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/subscript(_:)-1q1sr"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/subscript(_:)-zfw5": {
      "abstract": [
        {
          "text": "Accesses a slice using a collection of integers, in which each element is an index in the corresponding dimension.",
          "type": "text"
        }
      ],
      "defaultImplementations": 7,
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML18MLShapedArraySliceV",
          "text": "MLShapedArraySlice"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/subscript(_:)-zfw5",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/subscript(_:)-zfw5"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/subscript(scalarAt:)": {
      "abstract": [
        {
          "text": "Accesses an element and a multidimensional location.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "scalarAt"
        },
        {
          "kind": "text",
          "text": " _: "
        },
        {
          "kind": "typeIdentifier",
          "text": "C"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/subscript(scalarAt:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "subscript(scalarAt:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/subscript(scalarat:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/withUnsafeMutableShapedBufferPointer(_:)": {
      "abstract": [
        {
          "text": "Provides read-write access of the shaped array’s underlying memory to a closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withUnsafeMutableShapedBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sr",
          "text": "UnsafeMutableBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ">, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/withUnsafeMutableShapedBufferPointer(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "withUnsafeMutableShapedBufferPointer(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/withunsafemutableshapedbufferpointer(_:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/withUnsafeShapedBufferPointer(_:)": {
      "abstract": [
        {
          "text": "Provides read-only access of the shaped array’s underlying memory to a closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withUnsafeShapedBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6CoreML21MLShapedArrayProtocolP6ScalarQa",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ">, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/withUnsafeShapedBufferPointer(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "withUnsafeShapedBufferPointer(_:)",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayprotocol/withunsafeshapedbufferpointer(_:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayRangeExpression": {
      "abstract": [
        {
          "text": "An interface for a range expression, which you typically use with subscripts of shaped array types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLShapedArrayRangeExpression"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayRangeExpression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLShapedArrayRangeExpression"
        }
      ],
      "role": "symbol",
      "title": "MLShapedArrayRangeExpression",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayrangeexpression"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayScalar": {
      "abstract": [
        {
          "text": "A type that associates a scalar with a shaped array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLShapedArrayScalar"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayScalar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLShapedArrayScalar"
        }
      ],
      "role": "symbol",
      "title": "MLShapedArrayScalar",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayscalar"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLShapedArraySlice": {
      "abstract": [
        {
          "text": "A multidimensional subset of elements from a shaped array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLShapedArraySlice"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLShapedArraySlice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLShapedArraySlice"
        }
      ],
      "role": "symbol",
      "title": "MLShapedArraySlice",
      "type": "topic",
      "url": "/documentation/coreml/mlshapedarrayslice"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SK": {
      "abstract": [
        {
          "text": "A collection that supports backward as well as forward traversal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BidirectionalCollection"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl",
          "text": "Collection"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl7IndicesQa",
          "text": "Indices"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK",
          "text": "BidirectionalCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl11SubSequenceQa",
          "text": "SubSequence"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK",
          "text": "BidirectionalCollection"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SK",
      "kind": "symbol",
      "role": "symbol",
      "title": "BidirectionalCollection",
      "type": "topic",
      "url": "/documentation/Swift/BidirectionalCollection"
    },
    "doc://com.externally.resolved.symbol/s:SM": {
      "abstract": [
        {
          "text": "A collection that supports subscript assignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MutableCollection"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SM7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl",
          "text": "Collection"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl11SubSequenceQa",
          "text": "SubSequence"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SM",
          "text": "MutableCollection"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MutableCollection",
      "type": "topic",
      "url": "/documentation/Swift/MutableCollection"
    },
    "doc://com.externally.resolved.symbol/s:ST": {
      "abstract": [
        {
          "text": "A type that provides sequential, iterated access to its elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sequence"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ST",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sequence",
      "type": "topic",
      "url": "/documentation/Swift/Sequence"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    },
    "doc://com.externally.resolved.symbol/s:Sk": {
      "abstract": [
        {
          "text": "A collection that supports efficient random-access index traversal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RandomAccessCollection"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sk7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK",
          "text": "BidirectionalCollection"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl7IndicesQa",
          "text": "Indices"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sk",
          "text": "RandomAccessCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl11SubSequenceQa",
          "text": "SubSequence"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sk",
          "text": "RandomAccessCollection"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sk",
      "kind": "symbol",
      "role": "symbol",
      "title": "RandomAccessCollection",
      "type": "topic",
      "url": "/documentation/Swift/RandomAccessCollection"
    },
    "doc://com.externally.resolved.symbol/s:Sl": {
      "abstract": [
        {
          "text": "A sequence whose elements can be traversed multiple times, nondestructively, and accessed by an indexed subscript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Collection"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST",
          "text": "Sequence"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sl",
      "kind": "symbol",
      "role": "symbol",
      "title": "Collection",
      "type": "topic",
      "url": "/documentation/Swift/Collection"
    },
    "doc://com.externally.resolved.symbol/s:Sl5IndexQa": {
      "abstract": [
        {
          "text": "A type that represents a position in the collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "associatedtype"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SL",
          "text": "Comparable"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl5IndexQa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl7IndicesQa",
          "text": "Indices"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl7IndicesQa",
          "text": "Indices"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl7IndicesQa",
          "text": "Indices"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl5IndexQa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl7IndicesQa",
          "text": "Indices"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl5IndexQa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl11SubSequenceQa",
          "text": "SubSequence"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl5IndexQa",
          "text": "Index"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sl5IndexQa",
      "kind": "symbol",
      "role": "symbol",
      "title": "Index",
      "type": "topic",
      "url": "/documentation/Swift/Collection/Index"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SK",
        "doc://com.externally.resolved.symbol/s:Sl",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:SM",
        "doc://com.externally.resolved.symbol/s:Sk",
        "doc://com.externally.resolved.symbol/s:ST"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArray",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArraySlice"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureType",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArray",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArray",
        "doc://com.apple.coreml/documentation/CoreML/MLSequence"
      ],
      "title": "Supporting Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Shaped-Array-Type",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(scalars:shape:)",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(repeating:shape:)",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(identityMatrixOfSize:)-77y0e",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(randomScalarsIn:shape:)-99fnn",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(bytesNoCopy:shape:deallocator:)",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(bytesNoCopy:shape:strides:deallocator:)",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(unsafeUninitializedShape:initializingWith:)"
      ],
      "title": "Creating a Shaped Array Type"
    },
    {
      "anchor": "Creating-a-Shaped-Array-Type-from-Another-Type",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(_:)",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(converting:)-3d2eu",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(converting:)-701ib"
      ],
      "title": "Creating a Shaped Array Type from Another Type"
    },
    {
      "anchor": "Inspecting-a-Shaped-Array-Type",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/shape",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/strides",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/count",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/isScalar",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/scalarCount",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/scalar-swift.property",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/scalars",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/withUnsafeShapedBufferPointer(_:)"
      ],
      "title": "Inspecting a Shaped Array Type"
    },
    {
      "anchor": "Accessing-Elements",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/subscript(scalarAt:)",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/subscript(_:)-zfw5",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/subscript(_:)-1q1sr"
      ],
      "title": "Accessing Elements"
    },
    {
      "anchor": "Modifying-a-Shaped-Array-Type",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/fill(with:)-9qpes",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/fill(with:)-6a5k1",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/withUnsafeMutableShapedBufferPointer(_:)"
      ],
      "title": "Modifying a Shaped Array Type"
    },
    {
      "anchor": "Supporting-Types",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/Scalar-swift.associatedtype",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArraySlice",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayScalar",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayRangeExpression"
      ],
      "title": "Supporting Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(identityMatrixOfSize:)-1xx88",
        "doc://com.apple.coreml/documentation/CoreML/MLShapedArrayProtocol/init(randomScalarsIn:shape:)-4c8k1"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray/title",
          "value": "MLMultiArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLSequence/title",
          "value": "MLSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLSequence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType/title",
          "value": "MLFeatureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlshapedarrayprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
