{
  "abstract": [
    {
      "text": "Expand and modify your model with new layers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/model-customization"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Model Customization"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Customize your Core ML model to make it work better for your specific app. For instance, create one or more custom layers to improve accuracy by increasing the model’s capacity to capture information. You can also reduce the model’s size to optimize the contents of your app bundle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer": {
      "abstract": [
        {
          "text": "An interface that defines the behavior of a custom layer in your neural network model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCustomLayer"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCustomLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCustomLayer",
      "type": "topic",
      "url": "/documentation/coreml/mlcustomlayer"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLCustomModel": {
      "abstract": [
        {
          "text": "An interface that defines the behavior of a custom model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCustomModel"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLCustomModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCustomModel"
        }
      ],
      "role": "symbol",
      "title": "MLCustomModel",
      "type": "topic",
      "url": "/documentation/coreml/mlcustommodel"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel": {
      "abstract": [
        {
          "text": "An encapsulation of all the details of your machine learning model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModel"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModel"
        }
      ],
      "role": "symbol",
      "title": "MLModel",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel"
    },
    "doc://com.apple.coreml/documentation/CoreML/creating-and-integrating-a-model-with-custom-layers": {
      "abstract": [
        {
          "text": "Add models with custom neural-network layers to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/creating-and-integrating-a-model-with-custom-layers",
      "kind": "article",
      "role": "article",
      "title": "Creating and Integrating a Model with Custom Layers",
      "type": "topic",
      "url": "/documentation/coreml/creating-and-integrating-a-model-with-custom-layers"
    },
    "doc://com.apple.coreml/documentation/CoreML/getting-a-core-ml-model": {
      "abstract": [
        {
          "text": "Obtain a Core ML model to use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/getting-a-core-ml-model",
      "kind": "article",
      "role": "article",
      "title": "Getting a Core ML Model",
      "type": "topic",
      "url": "/documentation/coreml/getting-a-core-ml-model"
    },
    "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app": {
      "abstract": [
        {
          "text": "Add a simple model to an app,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "pass input data to the model, and process the model’s predictions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating a Core ML Model into Your App",
      "type": "topic",
      "url": "/documentation/coreml/integrating-a-core-ml-model-into-your-app"
    },
    "doc://com.apple.coreml/documentation/CoreML/model-personalization": {
      "abstract": [
        {
          "text": "Update your model to adapt to new data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/model-personalization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model Personalization",
      "type": "topic",
      "url": "/documentation/coreml/model-personalization"
    },
    "doc://com.apple.coreml/documentation/CoreML/reducing-the-size-of-your-core-ml-app": {
      "abstract": [
        {
          "text": "Reduce the storage used by the Core ML model inside your app bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/reducing-the-size-of-your-core-ml-app",
      "kind": "article",
      "role": "article",
      "title": "Reducing the Size of Your Core ML App",
      "type": "topic",
      "url": "/documentation/coreml/reducing-the-size-of-your-core-ml-app"
    },
    "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package": {
      "abstract": [
        {
          "text": "Convert a Core ML model file into a model package in Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package",
      "kind": "article",
      "role": "article",
      "title": "Updating a Model File to a Model Package",
      "type": "topic",
      "url": "/documentation/coreml/updating-a-model-file-to-a-model-package"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Core-ML-models",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/getting-a-core-ml-model",
        "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package",
        "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app",
        "doc://com.apple.coreml/documentation/CoreML/MLModel",
        "doc://com.apple.coreml/documentation/CoreML/model-personalization"
      ],
      "title": "Core ML models"
    }
  ],
  "topicSections": [
    {
      "anchor": "Model-File-Size",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/reducing-the-size-of-your-core-ml-app"
      ],
      "title": "Model File Size"
    },
    {
      "anchor": "Custom-Model-Layers",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/creating-and-integrating-a-model-with-custom-layers",
        "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer"
      ],
      "title": "Custom Model Layers"
    },
    {
      "anchor": "Custom-Models",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLCustomModel"
      ],
      "title": "Custom Models"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Model-File-Size",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/reducing-the-size-of-your-core-ml-app"
              ],
              "title": "Model File Size"
            },
            {
              "anchor": "Custom-Model-Layers",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/creating-and-integrating-a-model-with-custom-layers",
                "doc://com.apple.coreml/documentation/CoreML/MLCustomLayer"
              ],
              "title": "Custom Model Layers"
            },
            {
              "anchor": "Custom-Models",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLCustomModel"
              ],
              "title": "Custom Models"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Core-ML-models",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/getting-a-core-ml-model",
                "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package",
                "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app",
                "doc://com.apple.coreml/documentation/CoreML/MLModel",
                "doc://com.apple.coreml/documentation/CoreML/model-personalization"
              ],
              "title": "Core ML models"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/title",
          "value": "MLModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomModel/title",
          "value": "MLCustomModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCustomModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCustomModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomLayer/title",
          "value": "MLCustomLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCustomLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLCustomLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCustomLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/model-customization"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/model-customization"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
