{
  "abstract": [
    {
      "text": "Update your model to adapt to new data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/model-personalization"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Model Personalization"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On-device model updates provide your app the flexibility to personalize a user’s experience. For example, ordering a mocha at your favorite coffee shop every day increases a model’s ability to recommend that drink on subsequent visits. With the Core ML framework, you can adapt to incoming data with an updatable model at runtime on the user’s device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel": {
      "abstract": [
        {
          "text": "An encapsulation of all the details of your machine learning model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModel"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModel"
        }
      ],
      "role": "symbol",
      "title": "MLModel",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLTask": {
      "abstract": [
        {
          "text": "An abstract base class for machine learning tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLTask"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLTask"
        }
      ],
      "role": "symbol",
      "title": "MLTask",
      "type": "topic",
      "url": "/documentation/coreml/mltask"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask": {
      "abstract": [
        {
          "text": "A task that updates a model with additional training data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLUpdateTask"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLUpdateTask"
        }
      ],
      "role": "symbol",
      "title": "MLUpdateTask",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask"
    },
    "doc://com.apple.coreml/documentation/CoreML/getting-a-core-ml-model": {
      "abstract": [
        {
          "text": "Obtain a Core ML model to use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/getting-a-core-ml-model",
      "kind": "article",
      "role": "article",
      "title": "Getting a Core ML Model",
      "type": "topic",
      "url": "/documentation/coreml/getting-a-core-ml-model"
    },
    "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app": {
      "abstract": [
        {
          "text": "Add a simple model to an app,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "pass input data to the model, and process the model’s predictions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating a Core ML Model into Your App",
      "type": "topic",
      "url": "/documentation/coreml/integrating-a-core-ml-model-into-your-app"
    },
    "doc://com.apple.coreml/documentation/CoreML/model-customization": {
      "abstract": [
        {
          "text": "Expand and modify your model with new layers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/model-customization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model Customization",
      "type": "topic",
      "url": "/documentation/coreml/model-customization"
    },
    "doc://com.apple.coreml/documentation/CoreML/personalizing-a-model-with-on-device-updates": {
      "abstract": [
        {
          "text": "Modify an updatable Core ML model by running an update task with labeled data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/personalizing-a-model-with-on-device-updates",
      "kind": "article",
      "role": "sampleCode",
      "title": "Personalizing a Model with On-Device Updates",
      "type": "topic",
      "url": "/documentation/coreml/personalizing-a-model-with-on-device-updates"
    },
    "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package": {
      "abstract": [
        {
          "text": "Convert a Core ML model file into a model package in Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package",
      "kind": "article",
      "role": "article",
      "title": "Updating a Model File to a Model Package",
      "type": "topic",
      "url": "/documentation/coreml/updating-a-model-file-to-a-model-package"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Core-ML-models",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/getting-a-core-ml-model",
        "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package",
        "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app",
        "doc://com.apple.coreml/documentation/CoreML/MLModel",
        "doc://com.apple.coreml/documentation/CoreML/model-customization"
      ],
      "title": "Core ML models"
    }
  ],
  "topicSections": [
    {
      "anchor": "On-Device-Model-Updates",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLTask",
        "doc://com.apple.coreml/documentation/CoreML/personalizing-a-model-with-on-device-updates",
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask"
      ],
      "title": "On-Device Model Updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "On-Device-Model-Updates",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLTask",
                "doc://com.apple.coreml/documentation/CoreML/personalizing-a-model-with-on-device-updates",
                "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask"
              ],
              "title": "On-Device Model Updates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Core-ML-models",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/getting-a-core-ml-model",
                "doc://com.apple.coreml/documentation/CoreML/updating-a-model-file-to-a-model-package",
                "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app",
                "doc://com.apple.coreml/documentation/CoreML/MLModel",
                "doc://com.apple.coreml/documentation/CoreML/model-customization"
              ],
              "title": "Core ML models"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask/title",
          "value": "MLUpdateTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLTask/title",
          "value": "MLTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/title",
          "value": "MLModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/model-personalization"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/model-personalization"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
