{
  "abstract": [
    {
      "text": "Integrate tabular, image, and text classifcation models into your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/model-integration-samples"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "role": "collectionGroup",
    "title": "Model Integration Samples"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the provided Core ML sample code projects to learn how to classify numeric values, images, and text within applications. For example, you can detect poses of the human body, classify a group of images, and locate answers to questions in a text document.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/detecting-human-body-poses-in-an-image": {
      "abstract": [
        {
          "text": "Locate people and the stance of their bodies by analyzing an image with a PoseNet model.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/detecting-human-body-poses-in-an-image",
      "kind": "article",
      "role": "sampleCode",
      "title": "Detecting human body poses in an image",
      "type": "topic",
      "url": "/documentation/coreml/detecting-human-body-poses-in-an-image"
    },
    "doc://com.apple.coreml/documentation/CoreML/downloading-and-compiling-a-model-on-the-user-s-device": {
      "abstract": [
        {
          "text": "Install Core ML models on the user’s device dynamically at runtime.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/downloading-and-compiling-a-model-on-the-user-s-device",
      "kind": "article",
      "role": "article",
      "title": "Downloading and Compiling a Model on the User’s Device",
      "type": "topic",
      "url": "/documentation/coreml/downloading-and-compiling-a-model-on-the-user-s-device"
    },
    "doc://com.apple.coreml/documentation/CoreML/finding-answers-to-questions-in-a-text-document": {
      "abstract": [
        {
          "text": "Locate relevant passages in a document by asking the Bidirectional Encoder Representations from Transformers (BERT) model a question.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/finding-answers-to-questions-in-a-text-document",
      "kind": "article",
      "role": "sampleCode",
      "title": "Finding answers to questions in a text document",
      "type": "topic",
      "url": "/documentation/coreml/finding-answers-to-questions-in-a-text-document"
    },
    "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app": {
      "abstract": [
        {
          "text": "Add a simple model to an app,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "pass input data to the model, and process the model’s predictions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating a Core ML Model into Your App",
      "type": "topic",
      "url": "/documentation/coreml/integrating-a-core-ml-model-into-your-app"
    },
    "doc://com.apple.coreml/documentation/CoreML/using-core-ml-for-semantic-image-segmentation": {
      "abstract": [
        {
          "text": "Identify multiple objects in an image by using the DEtection TRansformer image-segmentation model.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/using-core-ml-for-semantic-image-segmentation",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using Core ML for semantic image segmentation",
      "type": "topic",
      "url": "/documentation/coreml/using-core-ml-for-semantic-image-segmentation"
    },
    "doc://com.apple.documentation/documentation/coreml/model_integration_samples/classifying_images_with_vision_and_core_ml": {
      "abstract": [
        {
          "text": "Crop and scale photos using the Vision framework and classify them with a Core ML model.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreml/model_integration_samples/classifying_images_with_vision_and_core_ml",
      "kind": "article",
      "role": "sampleCode",
      "title": "Classifying Images with Vision and Core ML",
      "type": "topic",
      "url": "/documentation/coreml/model_integration_samples/classifying_images_with_vision_and_core_ml"
    },
    "doc://com.apple.documentation/documentation/coreml/model_integration_samples/understanding_a_dice_roll_with_vision_and_object_detection": {
      "abstract": [
        {
          "text": "Detect dice position and values shown in a camera frame, and determine the end of a roll by leveraging a dice detection model.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreml/model_integration_samples/understanding_a_dice_roll_with_vision_and_object_detection",
      "kind": "article",
      "role": "sampleCode",
      "title": "Understanding a Dice Roll with Vision and Object Detection",
      "type": "topic",
      "url": "/documentation/coreml/model_integration_samples/understanding_a_dice_roll_with_vision_and_object_detection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-integration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/downloading-and-compiling-a-model-on-the-user-s-device"
      ],
      "title": "App integration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Tabular-Data-Models",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app"
      ],
      "title": "Tabular Data Models"
    },
    {
      "anchor": "Image-Classification-Models",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/using-core-ml-for-semantic-image-segmentation",
        "doc://com.apple.documentation/documentation/coreml/model_integration_samples/classifying_images_with_vision_and_core_ml",
        "doc://com.apple.coreml/documentation/CoreML/detecting-human-body-poses-in-an-image",
        "doc://com.apple.documentation/documentation/coreml/model_integration_samples/understanding_a_dice_roll_with_vision_and_object_detection"
      ],
      "title": "Image Classification Models"
    },
    {
      "anchor": "Text-Classification-Models",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/finding-answers-to-questions-in-a-text-document"
      ],
      "title": "Text Classification Models"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Tabular-Data-Models",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/integrating-a-core-ml-model-into-your-app"
              ],
              "title": "Tabular Data Models"
            },
            {
              "anchor": "Image-Classification-Models",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/using-core-ml-for-semantic-image-segmentation",
                "doc://com.apple.documentation/documentation/coreml/model_integration_samples/classifying_images_with_vision_and_core_ml",
                "doc://com.apple.coreml/documentation/CoreML/detecting-human-body-poses-in-an-image",
                "doc://com.apple.documentation/documentation/coreml/model_integration_samples/understanding_a_dice_roll_with_vision_and_object_detection"
              ],
              "title": "Image Classification Models"
            },
            {
              "anchor": "Text-Classification-Models",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/finding-answers-to-questions-in-a-text-document"
              ],
              "title": "Text Classification Models"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-integration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/downloading-and-compiling-a-model-on-the-user-s-device"
              ],
              "title": "App integration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/model-integration-samples"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/model-integration-samples"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
