{
  "abstract": [
    {
      "text": "A dictionary that contains a deep copy of the appearance characteristic key-value pairs.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/appearanceCharacteristicsKeyValues"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PDFAppearanceCharacteristics(py)appearanceCharacteristicsKeyValues",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "appearanceCharacteristicsKeyValues"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s11AnyHashableV",
        "text": "AnyHashable"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "appearanceCharacteristicsKeyValues"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "appearanceCharacteristicsKeyValues"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "appearanceCharacteristicsKeyValues"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s11AnyHashableV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s11AnyHashableV",
              "text": "AnyHashable"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics": {
      "abstract": [
        {
          "text": "An object that represents appearance characteristics of a widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristics"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristics"
        }
      ],
      "role": "symbol",
      "title": "PDFAppearanceCharacteristics",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/appearanceCharacteristicsKeyValues": {
      "abstract": [
        {
          "text": "A dictionary that contains a deep copy of the appearance characteristic key-value pairs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appearanceCharacteristicsKeyValues"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/appearanceCharacteristicsKeyValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appearanceCharacteristicsKeyValues"
        }
      ],
      "role": "symbol",
      "title": "appearanceCharacteristicsKeyValues",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/appearancecharacteristicskeyvalues"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/backgroundColor": {
      "abstract": [
        {
          "text": "The background color of the widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/backgroundcolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/borderColor": {
      "abstract": [
        {
          "text": "The border color of the widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/borderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderColor"
        }
      ],
      "role": "symbol",
      "title": "borderColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/bordercolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/caption": {
      "abstract": [
        {
          "text": "The text that the button widget annotation displays when the user isn’t interacting with it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/caption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "caption"
        }
      ],
      "role": "symbol",
      "title": "caption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/caption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/controlType": {
      "abstract": [
        {
          "text": "The type of button widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFWidgetControlType",
          "text": "PDFWidgetControlType"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/controlType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controlType"
        }
      ],
      "role": "symbol",
      "title": "controlType",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/controltype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/downCaption": {
      "abstract": [
        {
          "text": "The text that the button widget annotation displays when the user holds down on it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/downCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "downCaption"
        }
      ],
      "role": "symbol",
      "title": "downCaption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/downcaption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rolloverCaption": {
      "abstract": [
        {
          "text": "The text that the widget annotation displays when the user hovers the pointer over it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rolloverCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rolloverCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rolloverCaption"
        }
      ],
      "role": "symbol",
      "title": "rolloverCaption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/rollovercaption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rotation": {
      "abstract": [
        {
          "text": "The number of degrees, in multiples of 90, that the widget annotation rotates counterclockwise relative to the page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotation"
        }
      ],
      "role": "symbol",
      "title": "rotation",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/rotation"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey": {
      "abstract": [
        {
          "text": "Keys to control a widget’s appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristicsKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristicsKey"
        }
      ],
      "role": "symbol",
      "title": "PDFAppearanceCharacteristicsKey",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristicskey"
    },
    "doc://com.externally.resolved.symbol/s:s11AnyHashableV": {
      "abstract": [
        {
          "text": "A type-erased hashable value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnyHashable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s11AnyHashableV",
      "kind": "symbol",
      "role": "symbol",
      "title": "AnyHashable",
      "type": "topic",
      "url": "/documentation/Swift/AnyHashable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-a-Widgets-Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/backgroundColor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/borderColor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/caption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/controlType",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/downCaption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rolloverCaption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rotation",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey"
      ],
      "title": "Configuring a Widget’s Appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "appearanceCharacteristicsKeyValues"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appearanceCharacteristicsKeyValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-a-Widgets-Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/backgroundColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/borderColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/caption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/controlType",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/downCaption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rolloverCaption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rotation",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey"
              ],
              "title": "Configuring a Widget’s Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDictionary",
                    "text": "NSDictionary"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "appearanceCharacteristicsKeyValues"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1downCaption/title",
          "value": "downCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1downCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "downCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics/title",
          "value": "PDFAppearanceCharacteristics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1controlType/title",
          "value": "controlType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1controlType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1rolloverCaption/title",
          "value": "rolloverCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1rolloverCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rolloverCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1caption/title",
          "value": "caption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1caption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "caption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1rotation/title",
          "value": "rotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1rotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1borderColor/title",
          "value": "borderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1borderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey/title",
          "value": "PDFAppearanceCharacteristicsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1appearanceCharacteristicsKeyValues/title",
          "value": "appearanceCharacteristicsKeyValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1appearanceCharacteristicsKeyValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appearanceCharacteristicsKeyValues"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfappearancecharacteristics/appearancecharacteristicskeyvalues"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfappearancecharacteristics/appearancecharacteristicskeyvalues"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
