{
  "abstract": [
    {
      "text": "The element is an item. Items represent the main content of your collection view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/item"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSCollectionElementCategory@NSCollectionElementCategoryItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "item"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCollectionElementCategoryItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSCollectionElementCategory.item"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "item"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory": {
      "abstract": [
        {
          "text": "Constants specifying the type of element in the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionElementCategory"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionElementCategory"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionElementCategory",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionelementcategory"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/decorationView": {
      "abstract": [
        {
          "text": "The element is a decoration view. Decoration views represent visual adornments that do not contain any data of their own.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decorationView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/decorationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionElementCategoryDecorationView"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionElementCategory.decorationView",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionelementcategory/decorationview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/interItemGap": {
      "abstract": [
        {
          "text": "The element is an inter-item gap. An inter-item gap element is a custom visual indicator that is displayed between items when dropping items into the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interItemGap"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/interItemGap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionElementCategoryInterItemGap"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionElementCategory.interItemGap",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionelementcategory/interitemgap"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/item": {
      "abstract": [
        {
          "text": "The element is an item. Items represent the main content of your collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "item"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/item",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionElementCategoryItem"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionElementCategory.item",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionelementcategory/item"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/supplementaryView": {
      "abstract": [
        {
          "text": "The element is a supplementary view. Use supplementary views for single views that contain some data but are associated with an entire section. For example, use them to specify header or footer views for a section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supplementaryView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/supplementaryView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionElementCategorySupplementaryView"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionElementCategory.supplementaryView",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionelementcategory/supplementaryview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/supplementaryView",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/decorationView",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/interItemGap"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCollectionElementCategoryItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionElementCategoryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/supplementaryView",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/decorationView",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionElementCategory/interItemGap"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSCollectionElementCategoryItem"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory/title",
          "value": "NSCollectionElementCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionElementCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionElementCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory~1decorationView/title",
          "value": "NSCollectionElementCategoryDecorationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory~1decorationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionElementCategoryDecorationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory~1supplementaryView/title",
          "value": "NSCollectionElementCategorySupplementaryView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory~1supplementaryView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionElementCategorySupplementaryView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory~1interItemGap/title",
          "value": "NSCollectionElementCategoryInterItemGap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory~1interItemGap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionElementCategoryInterItemGap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory~1item/title",
          "value": "NSCollectionElementCategoryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionElementCategory~1item/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionElementCategoryItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscollectionelementcategory/item"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscollectionelementcategory/item"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
