{
  "abstract": [
    {
      "text": "Animates a row insertion by sliding from the right. Animates a row removal by sliding towards the right.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideRight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTableViewAnimationOptions@NSTableViewAnimationSlideRight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "slideRight"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTableView",
        "text": "NSTableView"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSTableViewAnimationOptions",
        "text": "AnimationOptions"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTableViewAnimationSlideRight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "slideRight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "slideRight"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTableView",
              "text": "NSTableView"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTableViewAnimationOptions",
              "text": "AnimationOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView": {
      "abstract": [
        {
          "text": "A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "role": "symbol",
      "title": "NSTableView",
      "type": "topic",
      "url": "/documentation/appkit/nstableview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions": {
      "abstract": [
        {
          "text": "Specifies the animation effects to apply when inserting or removing rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.AnimationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/animationoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/effectFade": {
      "abstract": [
        {
          "text": "Use a fade for row or column removal. The effect can be combined with any of the slide constants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectFade"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/effectFade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewAnimationEffectFade"
        }
      ],
      "role": "symbol",
      "title": "effectFade",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/animationoptions/effectfade"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/effectGap": {
      "abstract": [
        {
          "text": "Creates a gap for newly inserted rows. This is useful for drag and drop animations that animate to a newly opened gap and should be used in the delegate method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectGap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/effectGap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewAnimationEffectGap"
        }
      ],
      "role": "symbol",
      "title": "effectGap",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/animationoptions/effectgap"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideDown": {
      "abstract": [
        {
          "text": "Animates a row insertion or removal by sliding downward.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slideDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewAnimationSlideDown"
        }
      ],
      "role": "symbol",
      "title": "slideDown",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/animationoptions/slidedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideLeft": {
      "abstract": [
        {
          "text": "Animates a row insertion by sliding from the left. Animates a row removal by sliding towards the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slideLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewAnimationSlideLeft"
        }
      ],
      "role": "symbol",
      "title": "slideLeft",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/animationoptions/slideleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideRight": {
      "abstract": [
        {
          "text": "Animates a row insertion by sliding from the right. Animates a row removal by sliding towards the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slideRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewAnimationSlideRight"
        }
      ],
      "role": "symbol",
      "title": "slideRight",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/animationoptions/slideright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideUp": {
      "abstract": [
        {
          "text": "Animates a row insertion or removal by sliding upward.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slideUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewAnimationSlideUp"
        }
      ],
      "role": "symbol",
      "title": "slideUp",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/animationoptions/slideup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewAnimationOptions/NSTableViewAnimationEffectNone": {
      "abstract": [
        {
          "text": "Use no animation effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTableViewAnimationEffectNone"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewAnimationOptions/NSTableViewAnimationEffectNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTableViewAnimationEffectNone",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewanimationoptions/nstableviewanimationeffectnone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)": {
      "abstract": [
        {
          "text": "Called by ",
          "type": "text"
        },
        {
          "code": "aTableView",
          "type": "codeVoice"
        },
        {
          "text": " when the mouse button is released over a table view that previously decided to allow a drop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "acceptDrop"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSDraggingInfo",
          "text": "NSDraggingInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "row"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewDropOperation",
          "text": "DropOperation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource/tableView(_:acceptDrop:row:dropOperation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:acceptDrop:row:dropOperation:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:acceptDrop:row:dropOperation:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewdatasource/tableview(_:acceptdrop:row:dropoperation:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/effectFade",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/effectGap",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideUp",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideDown",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideLeft"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTableViewAnimationSlideRight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewAnimationSlideRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewAnimationOptions/NSTableViewAnimationEffectNone",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/effectFade",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/effectGap",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideUp",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideDown",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/AnimationOptions/slideLeft"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTableViewAnimationSlideRight"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1slideUp/title",
          "value": "NSTableViewAnimationSlideUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1slideUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewAnimationSlideUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title",
          "value": "NSTableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1slideDown/title",
          "value": "NSTableViewAnimationSlideDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1slideDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewAnimationSlideDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1slideRight/title",
          "value": "NSTableViewAnimationSlideRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1slideRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewAnimationSlideRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions/title",
          "value": "NSTableViewAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1effectFade/title",
          "value": "NSTableViewAnimationEffectFade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1effectFade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewAnimationEffectFade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1slideLeft/title",
          "value": "NSTableViewAnimationSlideLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1slideLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewAnimationSlideLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:acceptDrop:row:dropOperation:)/title",
          "value": "tableView:acceptDrop:row:dropOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource~1tableView(_:acceptDrop:row:dropOperation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:acceptDrop:row:dropOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1effectGap/title",
          "value": "NSTableViewAnimationEffectGap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1AnimationOptions~1effectGap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewAnimationEffectGap"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstableview/animationoptions/slideright"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstableview/animationoptions/slideright"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
