{
  "abstract": [
    {
      "text": "A constant that represents the F9 key.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F9"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "XCUIAutomation",
    "externalID": "c:@XCUIKeyboardKeyF9",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "F9"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@XCUIKeyboardKey",
        "text": "XCUIKeyboardKey"
      }
    ],
    "modules": [
      {
        "name": "XCUIAutomation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIKeyboardKeyF9"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.3",
        "name": "Xcode",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "F9"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "F9"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@XCUIKeyboardKey",
              "text": "XCUIKeyboardKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation": {
      "abstract": [
        {
          "text": "Replicate sequences of interactions and make sure that your app’s user interface behaves as intended.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
      "kind": "symbol",
      "role": "collection",
      "title": "XCUIAutomation",
      "type": "topic",
      "url": "/documentation/xcuiautomation"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey": {
      "abstract": [
        {
          "text": "Constants to represent keys that have no typewritten equivalent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKey"
        }
      ],
      "role": "symbol",
      "title": "XCUIKeyboardKey",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F1": {
      "abstract": [
        {
          "text": "A constant that represents the F1 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF1"
        }
      ],
      "role": "symbol",
      "title": "F1",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f1"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F10": {
      "abstract": [
        {
          "text": "A constant that represents the F10 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF10"
        }
      ],
      "role": "symbol",
      "title": "F10",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f10"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F11": {
      "abstract": [
        {
          "text": "A constant that represents the F11 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F11"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F11",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF11"
        }
      ],
      "role": "symbol",
      "title": "F11",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f11"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F12": {
      "abstract": [
        {
          "text": "A constant that represents the F12 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F12"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF12"
        }
      ],
      "role": "symbol",
      "title": "F12",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f12"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F13": {
      "abstract": [
        {
          "text": "A constant that represents the F13 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F13",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF13"
        }
      ],
      "role": "symbol",
      "title": "F13",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f13"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F14": {
      "abstract": [
        {
          "text": "A constant that represents the F14 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F14"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F14",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF14"
        }
      ],
      "role": "symbol",
      "title": "F14",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f14"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F15": {
      "abstract": [
        {
          "text": "A constant that represents the F15 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F15"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F15",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF15"
        }
      ],
      "role": "symbol",
      "title": "F15",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f15"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F2": {
      "abstract": [
        {
          "text": "A constant that represents the F2 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF2"
        }
      ],
      "role": "symbol",
      "title": "F2",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f2"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F3": {
      "abstract": [
        {
          "text": "A constant that represents the F3 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF3"
        }
      ],
      "role": "symbol",
      "title": "F3",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f3"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F4": {
      "abstract": [
        {
          "text": "A constant that represents the F4 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF4"
        }
      ],
      "role": "symbol",
      "title": "F4",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f4"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F5": {
      "abstract": [
        {
          "text": "A constant that represents the F5 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF5"
        }
      ],
      "role": "symbol",
      "title": "F5",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f5"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F6": {
      "abstract": [
        {
          "text": "A constant that represents the F6 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF6"
        }
      ],
      "role": "symbol",
      "title": "F6",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f6"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F7": {
      "abstract": [
        {
          "text": "A constant that represents the F7 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F7"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF7"
        }
      ],
      "role": "symbol",
      "title": "F7",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f7"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F8": {
      "abstract": [
        {
          "text": "A constant that represents the F8 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF8"
        }
      ],
      "role": "symbol",
      "title": "F8",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f8"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F9": {
      "abstract": [
        {
          "text": "A constant that represents the F9 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "F9"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyF9"
        }
      ],
      "role": "symbol",
      "title": "F9",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/f9"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/secondaryFn": {
      "abstract": [
        {
          "text": "A constant that represents the Function key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryFn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/secondaryFn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeySecondaryFn"
        }
      ],
      "role": "symbol",
      "title": "secondaryFn",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuikeyboardkey/secondaryfn"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Function-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/secondaryFn",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F1",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F2",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F3",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F4",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F5",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F6",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F7",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F8",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F10",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F11",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F12",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F13",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F14",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F15"
      ],
      "title": "Function keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.3",
              "name": "Xcode",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIKeyboardKeyF9"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF9"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Function-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/secondaryFn",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F1",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F2",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F3",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F4",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F5",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F6",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F7",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F8",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F10",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F11",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F12",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F13",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F14",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey/F15"
              ],
              "title": "Function keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIKeyboardKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@XCUIKeyboardKey",
                    "text": "XCUIKeyboardKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUIKeyboardKeyF9"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F13/title",
          "value": "XCUIKeyboardKeyF13"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F13/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF13"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F6/title",
          "value": "XCUIKeyboardKeyF6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F1/title",
          "value": "XCUIKeyboardKeyF1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F8/title",
          "value": "XCUIKeyboardKeyF8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F2/title",
          "value": "XCUIKeyboardKeyF2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1secondaryFn/title",
          "value": "XCUIKeyboardKeySecondaryFn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1secondaryFn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeySecondaryFn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey/title",
          "value": "XCUIKeyboardKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F5/title",
          "value": "XCUIKeyboardKeyF5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F15/title",
          "value": "XCUIKeyboardKeyF15"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F15/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF15"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F4/title",
          "value": "XCUIKeyboardKeyF4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F10/title",
          "value": "XCUIKeyboardKeyF10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F11/title",
          "value": "XCUIKeyboardKeyF11"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F11/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF11"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F9/title",
          "value": "XCUIKeyboardKeyF9"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF9"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F3/title",
          "value": "XCUIKeyboardKeyF3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F7/title",
          "value": "XCUIKeyboardKeyF7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F14/title",
          "value": "XCUIKeyboardKeyF14"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F14/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF14"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F12/title",
          "value": "XCUIKeyboardKeyF12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIKeyboardKey~1F12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyF12"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcuiautomation/xcuikeyboardkey/f9"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcuiautomation/xcuikeyboardkey/f9"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
