{
  "abstract": [
    {
      "text": "The default launch screen configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIDefaultLaunchScreen"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UILaunchScreens.UIDefaultLaunchScreen",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIDefaultLaunchScreen"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UIDefaultLaunchScreen"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "UIDefaultLaunchScreen",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Provide the identifier, stored in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key, of one of the launch screen definitions in your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array. The system displays the named launch screen when launching your app in response to a URL scheme that you don’t enumerate in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIURLToLaunchStoryboardAssociations",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " dictionary, or when the user launches your app directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens": {
      "abstract": [
        {
          "text": "The user interfaces to show while an app launches in response to different URL schemes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
      "kind": "symbol",
      "name": "UILaunchScreens",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreens"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreens",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIDefaultLaunchScreen": {
      "abstract": [
        {
          "text": "The default launch screen configuration.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIDefaultLaunchScreen",
      "kind": "symbol",
      "name": "UIDefaultLaunchScreen",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDefaultLaunchScreen"
        }
      ],
      "role": "symbol",
      "title": "UIDefaultLaunchScreen",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uidefaultlaunchscreen"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions": {
      "abstract": [
        {
          "text": "A collection of launch screen configuration dictionaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions",
      "kind": "symbol",
      "name": "UILaunchScreenDefinitions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreenDefinitions"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreenDefinitions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier": {
      "abstract": [
        {
          "text": "A unique name for the launch screen configuration.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier",
      "kind": "symbol",
      "name": "UILaunchScreenIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreenIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreenIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uilaunchscreenidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIURLToLaunchScreenAssociations": {
      "abstract": [
        {
          "text": "The mapping of URL schemes to launch screen configurations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIURLToLaunchScreenAssociations",
      "kind": "symbol",
      "name": "UIURLToLaunchScreenAssociations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIURLToLaunchScreenAssociations"
        }
      ],
      "role": "symbol",
      "title": "UIURLToLaunchScreenAssociations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uiurltolaunchscreenassociations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIURLToLaunchStoryboardAssociations": {
      "abstract": [
        {
          "text": "The user-defined storyboard identifiers that associate with supported schemes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIURLToLaunchStoryboardAssociations",
      "kind": "symbol",
      "name": "UIURLToLaunchStoryboardAssociations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIURLToLaunchStoryboardAssociations"
        }
      ],
      "role": "symbol",
      "title": "UIURLToLaunchStoryboardAssociations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards/uiurltolaunchstoryboardassociations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Associations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIURLToLaunchScreenAssociations"
      ],
      "title": "Associations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIDefaultLaunchScreen"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDefaultLaunchScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Associations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIURLToLaunchScreenAssociations"
              ],
              "title": "Associations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions/title",
          "value": "UILaunchScreenDefinitions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreenDefinitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UIURLToLaunchStoryboardAssociations/title",
          "value": "UIURLToLaunchStoryboardAssociations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UIURLToLaunchStoryboardAssociations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIURLToLaunchStoryboardAssociations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIDefaultLaunchScreen/title",
          "value": "UIDefaultLaunchScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIDefaultLaunchScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDefaultLaunchScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UILaunchScreenIdentifier/title",
          "value": "UILaunchScreenIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UILaunchScreenIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreenIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/title",
          "value": "UILaunchScreens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIURLToLaunchScreenAssociations/title",
          "value": "UIURLToLaunchScreenAssociations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIURLToLaunchScreenAssociations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIURLToLaunchScreenAssociations"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchscreens/uidefaultlaunchscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchscreens/uidefaultlaunchscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
