{
  "abstract": [
    {
      "text": "A collection of launch screen configuration dictionaries.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UILaunchScreens.UILaunchScreenDefinitions",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UILaunchScreenDefinitions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "UILaunchScreenDefinitions"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "UILaunchScreenDefinitions",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "dictionary "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each dictionary in the array resembles the one you might define for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key, with the addition of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key that provides a unique identifier for the dictionary. You use that identifier when associating to the dictionary with a URL scheme in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIURLToLaunchScreenAssociations",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array, or to indicate it as the default launch screen with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIDefaultLaunchScreen",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen": {
      "abstract": [
        {
          "text": "The user interface to show while an app launches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
      "kind": "symbol",
      "name": "UILaunchScreen",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreen"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreen",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreen"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens": {
      "abstract": [
        {
          "text": "The user interfaces to show while an app launches in response to different URL schemes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
      "kind": "symbol",
      "name": "UILaunchScreens",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreens"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreens",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIDefaultLaunchScreen": {
      "abstract": [
        {
          "text": "The default launch screen configuration.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIDefaultLaunchScreen",
      "kind": "symbol",
      "name": "UIDefaultLaunchScreen",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDefaultLaunchScreen"
        }
      ],
      "role": "symbol",
      "title": "UIDefaultLaunchScreen",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uidefaultlaunchscreen"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions": {
      "abstract": [
        {
          "text": "A collection of launch screen configuration dictionaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions",
      "kind": "symbol",
      "name": "UILaunchScreenDefinitions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreenDefinitions"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreenDefinitions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIColorName": {
      "abstract": [
        {
          "text": "The name of a color to use as the background color on the launch screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIColorName",
      "kind": "symbol",
      "name": "UIColorName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIColorName"
        }
      ],
      "role": "symbol",
      "title": "UIColorName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uicolorname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageName": {
      "abstract": [
        {
          "text": "The name of an image to display during app launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageName",
      "kind": "symbol",
      "name": "UIImageName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageName"
        }
      ],
      "role": "symbol",
      "title": "UIImageName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uiimagename"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageRespectsSafeAreaInsets": {
      "abstract": [
        {
          "text": "A Boolean that specifies whether the launch image should respect the safe area insets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageRespectsSafeAreaInsets",
      "kind": "symbol",
      "name": "UIImageRespectsSafeAreaInsets",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageRespectsSafeAreaInsets"
        }
      ],
      "role": "symbol",
      "title": "UIImageRespectsSafeAreaInsets",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uiimagerespectssafeareainsets"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier": {
      "abstract": [
        {
          "text": "A unique name for the launch screen configuration.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier",
      "kind": "symbol",
      "name": "UILaunchScreenIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreenIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreenIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uilaunchscreenidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UINavigationBar": {
      "abstract": [
        {
          "text": "Navigation bar visibility and configuration during launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UINavigationBar",
      "kind": "symbol",
      "name": "UINavigationBar",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINavigationBar"
        }
      ],
      "role": "symbol",
      "title": "UINavigationBar",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uinavigationbar"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UITabBar": {
      "abstract": [
        {
          "text": "Tab bar visibility and configuration during launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UITabBar",
      "kind": "symbol",
      "name": "UITabBar",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBar"
        }
      ],
      "role": "symbol",
      "title": "UITabBar",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uitabbar"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIToolbar": {
      "abstract": [
        {
          "text": "Toolbar visibility and configuration during launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIToolbar",
      "kind": "symbol",
      "name": "UIToolbar",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIToolbar"
        }
      ],
      "role": "symbol",
      "title": "UIToolbar",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uitoolbar"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIURLToLaunchScreenAssociations": {
      "abstract": [
        {
          "text": "The mapping of URL schemes to launch screen configurations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIURLToLaunchScreenAssociations",
      "kind": "symbol",
      "name": "UIURLToLaunchScreenAssociations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIURLToLaunchScreenAssociations"
        }
      ],
      "role": "symbol",
      "title": "UIURLToLaunchScreenAssociations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uiurltolaunchscreenassociations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Identity",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier"
      ],
      "title": "Identity"
    },
    {
      "anchor": "Main-Interface",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIColorName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageRespectsSafeAreaInsets"
      ],
      "title": "Main Interface"
    },
    {
      "anchor": "Border-Elements",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UINavigationBar",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UITabBar",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIToolbar"
      ],
      "title": "Border Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UILaunchScreenDefinitions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreenDefinitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Identity",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier"
              ],
              "title": "Identity"
            },
            {
              "anchor": "Main-Interface",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIColorName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageRespectsSafeAreaInsets"
              ],
              "title": "Main Interface"
            },
            {
              "anchor": "Border-Elements",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UINavigationBar",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UITabBar",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIToolbar"
              ],
              "title": "Border Elements"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIDefaultLaunchScreen/title",
          "value": "UIDefaultLaunchScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIDefaultLaunchScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDefaultLaunchScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UITabBar/title",
          "value": "UITabBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UITabBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UILaunchScreenIdentifier/title",
          "value": "UILaunchScreenIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UILaunchScreenIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreenIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UINavigationBar/title",
          "value": "UINavigationBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UINavigationBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIColorName/title",
          "value": "UIColorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIColorName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIToolbar/title",
          "value": "UIToolbar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIToolbar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIToolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIImageName/title",
          "value": "UIImageName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIImageName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIURLToLaunchScreenAssociations/title",
          "value": "UIURLToLaunchScreenAssociations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIURLToLaunchScreenAssociations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIURLToLaunchScreenAssociations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreen/title",
          "value": "UILaunchScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIImageRespectsSafeAreaInsets/title",
          "value": "UIImageRespectsSafeAreaInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIImageRespectsSafeAreaInsets/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageRespectsSafeAreaInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/title",
          "value": "UILaunchScreens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions/title",
          "value": "UILaunchScreenDefinitions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreenDefinitions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
