{"sections":[],"metadata":{"modules":[{"name":"Model I/O"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","title":"add(_:)","platforms":[{"beta":false,"introducedAt":"9.0","name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"9.0","name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"13.1","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"10.11","unavailable":false,"deprecated":false,"beta":false,"name":"macOS"},{"introducedAt":"9.0","unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"}],"navigatorTitle":[{"text":"addObject:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MDLObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MDLObject"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)MDLAsset(im)addObject:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MDLObject","preciseIdentifier":"c:objc(cs)MDLObject","kind":"typeIdentifier","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLObject"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"object","content":[{"inlineContent":[{"type":"text","text":"The object to add to the asset."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"An asset contains one or more top-level objects (instances of the ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLObject","type":"reference","isActive":true},{"text":" class or one of its subclasses, such as ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMesh"},{"text":"), each of which may contain a hierarchy of child objects.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Calling this method has no effect if the object is already in the asset’s list of top-level objects.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/add(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Adds the specified object to the asset’s list of top-level objects.","type":"text"}],"seeAlsoSections":[{"generated":true,"title":"Working with Asset Content","identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLAsset/object(at:)","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/subscript(_:)","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/count","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/childObjects(of:)","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/remove(_:)","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/boundingBox","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/boundingBox(atTime:)","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/url","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/bufferAllocator","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/vertexDescriptor","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/masters"],"anchor":"Working-with-Asset-Content"}],"variants":[{"paths":["/documentation/modelio/mdlasset/add(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/modelio/mdlasset/add(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAsset"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/object(at:)":{"title":"object(at:)","url":"/documentation/modelio/mdlasset/object(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"object"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MDLObject","preciseIdentifier":"c:objc(cs)MDLObject"}],"type":"topic","abstract":[{"type":"text","text":"Returns the top-level object at the specified index in the asset."}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/object(at:)","navigatorTitle":[{"kind":"identifier","text":"objectAtIndex:"}]},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/boundingBox(atTime:)":{"type":"topic","navigatorTitle":[{"text":"boundingBoxAtTime:","kind":"identifier"}],"url":"/documentation/modelio/mdlasset/boundingbox(attime:)","abstract":[{"text":"Returns the minimum region entirely enclosing the asset’s contents at the specified time sample.","type":"text"}],"title":"boundingBox(atTime:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boundingBox","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") -> ","kind":"text"},{"text":"MDLAxisAlignedBoundingBox","kind":"typeIdentifier","preciseIdentifier":"c:@SA@MDLAxisAlignedBoundingBox"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/boundingBox(atTime:)"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/bufferAllocator":{"abstract":[{"type":"text","text":"An object responsible for allocating mesh vertex data loaded from the asset."}],"navigatorTitle":[{"text":"bufferAllocator","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bufferAllocator","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MDLMeshBufferAllocator","text":"MDLMeshBufferAllocator","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/bufferAllocator","title":"bufferAllocator","url":"/documentation/modelio/mdlasset/bufferallocator"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/vertexDescriptor":{"kind":"symbol","abstract":[{"type":"text","text":"The description of the vertex data format to be used for loading mesh data from the asset."}],"title":"vertexDescriptor","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/vertexDescriptor","role":"symbol","type":"topic","url":"/documentation/modelio/mdlasset/vertexdescriptor","navigatorTitle":[{"text":"vertexDescriptor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vertexDescriptor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MDLVertexDescriptor","text":"MDLVertexDescriptor","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/subscript(_:)":{"abstract":[{"type":"text","text":"Returns the top-level object at the specified index in the asset, using subscript syntax."}],"navigatorTitle":[{"kind":"identifier","text":"objectAtIndexedSubscript:"}],"role":"symbol","type":"topic","fragments":[{"text":"subscript","kind":"keyword"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MDLObject","preciseIdentifier":"c:objc(cs)MDLObject"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/subscript(_:)","title":"subscript(_:)","url":"/documentation/modelio/mdlasset/subscript(_:)"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/remove(_:)":{"abstract":[{"type":"text","text":"Removes the specified object from the asset’s list of top-level objects."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"remove","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MDLObject","preciseIdentifier":"c:objc(cs)MDLObject"},{"kind":"text","text":")"}],"url":"/documentation/modelio/mdlasset/remove(_:)","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/remove(_:)","title":"remove(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeObject:"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/childObjects(of:)":{"abstract":[{"type":"text","text":"Returns all objects contained in the asset of the specified class."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"childObjects"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"MDLObject","preciseIdentifier":"c:objc(cs)MDLObject"},{"kind":"text","text":"]"}],"url":"/documentation/modelio/mdlasset/childobjects(of:)","navigatorTitle":[{"kind":"identifier","text":"childObjectsOfClass:"}],"title":"childObjects(of:)","role":"symbol","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/childObjects(of:)","type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/masters":{"abstract":[{"type":"text","text":"An array of objects that can be reused in the asset’s object hierarchy through instancing."}],"deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"masters","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"MDLObjectContainerComponent","preciseIdentifier":"c:objc(pl)MDLObjectContainerComponent","kind":"typeIdentifier"}],"url":"/documentation/modelio/mdlasset/masters","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/masters","title":"masters","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"masters","kind":"identifier"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/url":{"url":"/documentation/modelio/mdlasset/url","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/url","kind":"symbol","abstract":[{"type":"text","text":"The URL from which the asset was loaded, if available."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"URL","kind":"identifier"}],"title":"url","role":"symbol"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset":{"url":"/documentation/modelio/mdlasset","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset","kind":"symbol","abstract":[{"type":"text","text":"An indexed container for 3D objects and associated information, such as transform hierarchies, meshes, cameras, and lights."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLAsset","kind":"identifier"}],"navigatorTitle":[{"text":"MDLAsset","kind":"identifier"}],"title":"MDLAsset","role":"symbol"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/boundingBox":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boundingBox","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MDLAxisAlignedBoundingBox","preciseIdentifier":"c:@SA@MDLAxisAlignedBoundingBox","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"boundingBox","kind":"identifier"}],"type":"topic","url":"/documentation/modelio/mdlasset/boundingbox","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/boundingBox","title":"boundingBox","abstract":[{"type":"text","text":"The minimum region entirely enclosing the asset’s contents."}]},"doc://com.apple.modelio/documentation/ModelIO/MDLMesh":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMesh","kind":"identifier"}],"type":"topic","abstract":[{"text":"A container for vertex buffer data to be used in rendering a 3D object.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MDLMesh","kind":"identifier"}],"title":"MDLMesh","url":"/documentation/modelio/mdlmesh","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMesh"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/count":{"abstract":[{"type":"text","text":"The number of top-level objects in the asset."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"count","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"/documentation/modelio/mdlasset/count","navigatorTitle":[{"text":"count","kind":"identifier"}],"title":"count","role":"symbol","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/count","type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/add(_:)":{"abstract":[{"type":"text","text":"Adds the specified object to the asset’s list of top-level objects."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MDLObject","text":"MDLObject"},{"kind":"text","text":")"}],"url":"/documentation/modelio/mdlasset/add(_:)","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/add(_:)","title":"add(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"addObject:"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLObject":{"kind":"symbol","url":"/documentation/modelio/mdlobject","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MDLObject"}],"type":"topic","role":"symbol","title":"MDLObject","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLObject","abstract":[{"text":"The base class for objects that are part of a 3D asset, including meshes, cameras, and lights.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MDLObject"}]},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"9.0","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"9.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false},{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"10.11","unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"introducedAt":"9.0","unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"addObject:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addObject:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAsset"]]},"op":"replace","path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLAsset/object(at:)","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/subscript(_:)","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/count","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/childObjects(of:)","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/remove(_:)","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/boundingBox","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/boundingBox(atTime:)","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/url","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/bufferAllocator","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/vertexDescriptor","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/masters"],"title":"Working with Asset Content","generated":true,"anchor":"Working-with-Asset-Content"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"addObject:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MDLObject","preciseIdentifier":"c:objc(cs)MDLObject","kind":"typeIdentifier","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLObject"},{"text":" *) ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The object to add to the asset.","type":"text"}],"type":"paragraph"}],"name":"object"}]},"op":"replace"},{"op":"replace","value":"objectAtIndex:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1object(at:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"objectAtIndex:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1object(at:)/fragments"},{"op":"replace","value":"boundingBoxAtTime:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1boundingBox(atTime:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"boundingBoxAtTime:"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1boundingBox(atTime:)/fragments"},{"op":"replace","value":"bufferAllocator","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1bufferAllocator/title"},{"op":"replace","value":[{"text":"bufferAllocator","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1bufferAllocator/fragments"},{"op":"replace","value":"vertexDescriptor","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1vertexDescriptor/title"},{"op":"replace","value":[{"text":"vertexDescriptor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1vertexDescriptor/fragments"},{"op":"replace","value":"objectAtIndexedSubscript:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1subscript(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"objectAtIndexedSubscript:"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1subscript(_:)/fragments"},{"op":"replace","value":"removeObject:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1remove(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeObject:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1remove(_:)/fragments"},{"op":"replace","value":"childObjectsOfClass:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1childObjects(of:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"childObjectsOfClass:"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1childObjects(of:)/fragments"},{"op":"replace","value":"masters","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1masters/title"},{"op":"replace","value":[{"kind":"identifier","text":"masters"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1masters/fragments"},{"op":"replace","value":"URL","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1url/title"},{"op":"replace","value":[{"kind":"identifier","text":"URL"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1url/fragments"},{"op":"replace","value":"MDLAsset","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/title"},{"op":"replace","value":[{"kind":"identifier","text":"MDLAsset"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MDLAsset"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/navigatorTitle"},{"op":"replace","value":"boundingBox","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1boundingBox/title"},{"op":"replace","value":[{"text":"boundingBox","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1boundingBox/fragments"},{"op":"replace","value":"MDLMesh","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/title"},{"op":"replace","value":[{"text":"MDLMesh","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MDLMesh"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/navigatorTitle"},{"op":"replace","value":"count","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1count/title"},{"op":"replace","value":[{"kind":"identifier","text":"count"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1count/fragments"},{"op":"replace","value":"addObject:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1add(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addObject:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1add(_:)/fragments"},{"op":"replace","value":"MDLObject","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject/title"},{"op":"replace","value":[{"text":"MDLObject","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject/fragments"},{"op":"replace","value":[{"text":"MDLObject","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}