{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAsset"]]},"variants":[{"paths":["/documentation/modelio/mdlasset/endtime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/modelio/mdlasset/endtime"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/endTime"},"abstract":[{"text":"The timestamp for the last timed data sample in the asset.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Timed data in an asset is clamped to the start and end times—requesting sample data for a time sample after the start time returns the sample data at the end time."}],"type":"paragraph"},{"inlineContent":[{"text":"If the asset does not contain timed information, this property’s value is zero.","type":"text"}],"type":"paragraph"}]}],"metadata":{"title":"endTime","navigatorTitle":[{"text":"endTime","kind":"identifier"}],"externalID":"c:objc(cs)MDLAsset(py)endTime","roleHeading":"Instance Property","modules":[{"name":"Model I/O"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTime"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"symbolKind":"property","platforms":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"9.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"9.0","deprecated":false},{"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"introducedAt":"10.11","deprecated":false,"name":"macOS","beta":false,"unavailable":false},{"introducedAt":"9.0","deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false,"unavailable":false}],"role":"symbol"},"sections":[],"kind":"symbol","seeAlsoSections":[{"anchor":"Working-with-Timed-Information","title":"Working with Timed Information","identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLAsset/frameInterval","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/startTime"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/frameInterval":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frameInterval","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"navigatorTitle":[{"kind":"identifier","text":"frameInterval"}],"url":"/documentation/modelio/mdlasset/frameinterval","abstract":[{"text":"The time interval between data samples in the asset.","type":"text"}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/frameInterval","role":"symbol","kind":"symbol","type":"topic","title":"frameInterval"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset":{"url":"/documentation/modelio/mdlasset","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset","kind":"symbol","abstract":[{"type":"text","text":"An indexed container for 3D objects and associated information, such as transform hierarchies, meshes, cameras, and lights."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLAsset","kind":"identifier"}],"navigatorTitle":[{"text":"MDLAsset","kind":"identifier"}],"title":"MDLAsset","role":"symbol"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/endTime":{"title":"endTime","abstract":[{"text":"The timestamp for the last timed data sample in the asset.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"endTime"}],"type":"topic","url":"/documentation/modelio/mdlasset/endtime","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/endTime","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"kind":"symbol"},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval":{"role":"symbol","fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"TimeInterval"}],"type":"topic","title":"TimeInterval","abstract":[{"type":"text","text":"A number of seconds."}],"url":"/documentation/foundation/timeinterval","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval","kind":"symbol"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/startTime":{"title":"startTime","abstract":[{"text":"The timestamp for the first timed data sample in the asset.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"startTime"}],"type":"topic","url":"/documentation/modelio/mdlasset/starttime","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/startTime","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startTime","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"9.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"9.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.1","deprecated":false},{"introducedAt":"10.11","deprecated":false,"name":"macOS","beta":false,"unavailable":false},{"introducedAt":"9.0","deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"endTime"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"endTime","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAsset"]]}},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLAsset/frameInterval","doc://com.apple.modelio/documentation/ModelIO/MDLAsset/startTime"],"generated":true,"title":"Working with Timed Information","anchor":"Working-with-Timed-Information"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval"},{"text":" ","kind":"text"},{"text":"endTime","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1frameInterval/title","value":"frameInterval","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1frameInterval/fragments","value":[{"text":"frameInterval","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/title","value":"MDLAsset","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/fragments","value":[{"text":"MDLAsset","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/navigatorTitle","value":[{"text":"MDLAsset","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1endTime/title","value":"endTime","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1endTime/fragments","value":[{"text":"endTime","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title","value":"NSTimeInterval","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1startTime/title","value":"startTime","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1startTime/fragments","value":[{"kind":"identifier","text":"startTime"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}