{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/modelio/mdlasset/upaxis"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/modelio/mdlasset/upaxis"]}],"kind":"symbol","identifier":{"url":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/upAxis","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAsset"]]},"sections":[],"metadata":{"role":"symbol","title":"upAxis","symbolKind":"property","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"11.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"11.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","beta":false},{"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"10.13","beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"introducedAt":"11.0","beta":false},{"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upAxis","kind":"identifier"},{"text":": ","kind":"text"},{"text":"vector_float3","kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float3"}],"roleHeading":"Instance Property","modules":[{"name":"Model I/O"}],"externalID":"c:objc(cs)MDLAsset(py)upAxis","navigatorTitle":[{"text":"upAxis","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"upAxis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vector_float3","preciseIdentifier":"c:@T@vector_float3","identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float3"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/upAxis":{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset/upAxis","url":"/documentation/modelio/mdlasset/upaxis","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"upAxis"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"upAxis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vector_float3","preciseIdentifier":"c:@T@vector_float3"}],"role":"symbol","type":"topic","title":"upAxis"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@vector_float3":{"url":"/documentation/SpriteKit/vector_float3","title":"vector_float3","fragments":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:]3f","text":"float __attribute__((ext_vector_type(3)))","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"vector_float3"},{"text":";","kind":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float3","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"A floating point vector type used to perform physics calculations.","type":"text"}]},"doc://com.apple.modelio/documentation/ModelIO/MDLAsset":{"url":"/documentation/modelio/mdlasset","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAsset","kind":"symbol","abstract":[{"type":"text","text":"An indexed container for 3D objects and associated information, such as transform hierarchies, meshes, cameras, and lights."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLAsset","kind":"identifier"}],"navigatorTitle":[{"text":"MDLAsset","kind":"identifier"}],"title":"MDLAsset","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"11.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false},{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.13","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"11.0","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"upAxis","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"upAxis"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAsset"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"vector_float3","identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float3","preciseIdentifier":"c:@T@vector_float3"},{"kind":"text","text":" "},{"kind":"identifier","text":"upAxis"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1upAxis/title","value":"upAxis","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset~1upAxis/fragments","value":[{"text":"upAxis","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/title","value":"MDLAsset","op":"replace"},{"value":[{"kind":"identifier","text":"MDLAsset"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/fragments"},{"value":[{"text":"MDLAsset","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAsset/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}