{
  "abstract": [
    {
      "text": "Detects exposures using the configuration that you specify for controlling the scoring algorithm.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/detectExposures(configuration:diagnosisKeyURLs:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ENManager(im)detectExposuresWithConfiguration:diagnosisKeyURLs:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "detectExposures"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "configuration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ENExposureConfiguration",
        "text": "ENExposureConfiguration"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "diagnosisKeyURLs"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ENDetectExposuresHandler",
        "text": "ENDetectExposuresHandler"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSProgress",
        "text": "Progress"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "detectExposuresWithConfiguration:diagnosisKeyURLs:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "detectExposures(configuration:diagnosisKeyURLs:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "detectExposures"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "configuration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ENExposureConfiguration",
              "text": "ENExposureConfiguration"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "diagnosisKeyURLs"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDetectExposuresHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ENDetectExposuresHandler",
              "text": "ENDetectExposuresHandler"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSProgress",
              "text": "Progress"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The configuration to use for scoring.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "configuration"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of file URLs that contain downloaded diagnosis keys.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "diagnosisKeyURLs"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The completion handler that the framework calls when the method completes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The progress of the method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This method is available in iOS 12.5, and in iOS 13.5 and later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "diagnosisKeyURLs",
              "type": "codeVoice"
            },
            {
              "text": " parameter requires an array of file URLs that point to exposure key data files downloaded from an exposure notification (EN) server. For more information about the data format used to transmit diagnosis key data, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you retrieve diagnosis key data from an EN server, you receive it as a zip archive that you must decompress before use. Every archive you download from an EN server includes two files with the same base name, but with different file extensions: a key file with a ",
              "type": "text"
            },
            {
              "code": ".bin",
              "type": "codeVoice"
            },
            {
              "text": " extension, and a signature file with a ",
              "type": "text"
            },
            {
              "code": ".sig",
              "type": "codeVoice"
            },
            {
              "text": " extension. Decompress both files in the same directory, create a URL that points to each of the extracted files, and then pass both URLs as an array to ",
              "type": "text"
            },
            {
              "code": "diagnosisKeyURLs",
              "type": "codeVoice"
            },
            {
              "text": " argument in an array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If a diagnosis key has a rolling period greater than 144, the framework ignores it and will not consider it for key matching.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You may submit multiple file pairs in a single call to this method; however, each pair must use a unique base name. The order of the URLs passed in the ",
              "type": "text"
            },
            {
              "code": "diagnosisKeyURLs",
              "type": "codeVoice"
            },
            {
              "text": " array doesn’t matter. The file pairs will be matched up using the base name.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On iOS 13.7 and later, exposure keys that you submit to this method are automatically cached and used by the EN framework in calculations for up to 14 days. If you want to recalculate an ERV using different configuration values, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/detectExposures(configuration:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to recalculate a new ERV using only cached exposure keys.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "On iOS 13.6 and later, you’re limited to using this method a maximum of 15 times per 24-hour period. If you’re on iOS 13.7 and later and specify ",
                  "type": "text"
                },
                {
                  "code": "2",
                  "type": "codeVoice"
                },
                {
                  "text": " as the ",
                  "type": "text"
                },
                {
                  "code": "ENAPIVersion",
                  "type": "codeVoice"
                },
                {
                  "text": " in your app’s ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file, you’re limited to using this method a maximum of 6 times per 24-hour period.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "On iOS 13.5, you can only submit 15 uncached key files per 24-hour period, regardless of the number of API calls you make.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Log-Exposures",
          "level": 3,
          "text": "Log Exposures",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "ExposureNotification provides transparency for users at several points. For example, a user can choose Settings > Exposure Notifications to show the status of COVID-19 Exposure Logging, along with the currently active app, and its activity. This activity view shows the number of diagnostic key checks in the past 14 days, and the hash of the checked sets of keys.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To export the exposure checks, tap Export Exposure Checks. The resulting JSON file contains a ",
              "type": "text"
            },
            {
              "code": "Files",
              "type": "codeVoice"
            },
            {
              "text": " array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "  \"ExposureChecks\" : [",
            "    {",
            "      \"Timestamp\" : \"2020-08-24 05:06:28 -0700\",",
            "      \"Files\" : [",
            "        {",
            "          \"Hash\" : \"C0758C66350BB2875E438B52F73544AF3B91351365447E805B3548813E8086BD\",",
            "          \"KeyCount\" : 1082,",
            "          \"RegionCode\" : \"DR\",",
            "          \"Timestamp\" : \"2020-08-24 05:09:21 -0700\"",
            "        },",
            "      ],",
            "      \"RegionCode\" : \"DR\"",
            "    }",
            "  ]",
            "}"
          ],
          "syntax": "json",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Within the array are several properties, including the timestamp of the check (",
              "type": "text"
            },
            {
              "code": "Timestamp",
              "type": "codeVoice"
            },
            {
              "text": "), and how many positive keys the device downloaded and checked on the device (",
              "type": "text"
            },
            {
              "code": "KeyCount",
              "type": "codeVoice"
            },
            {
              "text": ") at that time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "iOS also provides a monthly notification to the user that reads, “Your iPhone continues to look for possible exposures on your behalf.” The notification occurs if the user has installed an EN app and enabled Exposure Logging, and the app has run a check for matched keys. The notification ensures that the app doesn’t continue to share proximity events without notifying the user. Users who tap the notification arrive at the transparency details in the Settings app, as described earlier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDetectExposuresHandler": {
      "abstract": [
        {
          "text": "The definition of a handler that returns exposure summaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENDetectExposuresHandler"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDetectExposuresHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDetectExposuresHandler"
        }
      ],
      "role": "symbol",
      "title": "ENDetectExposuresHandler",
      "type": "topic",
      "url": "/documentation/exposurenotification/endetectexposureshandler"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration": {
      "abstract": [
        {
          "text": "The object that contains parameters for configuring exposure notification risk scoring behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureConfiguration"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ENExposureConfiguration",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetExposureWindowsHandler": {
      "abstract": [
        {
          "text": "The handler the system invokes when the acquisition of windows completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENGetExposureWindowsHandler"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetExposureWindowsHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENGetExposureWindowsHandler"
        }
      ],
      "role": "symbol",
      "title": "ENGetExposureWindowsHandler",
      "type": "topic",
      "url": "/documentation/exposurenotification/engetexposurewindowshandler"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetUserTraveledHandler": {
      "abstract": [
        {
          "text": "The handler the system invokes when acquistiion of the user’s travel status completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENGetUserTraveledHandler"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetUserTraveledHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENGetUserTraveledHandler"
        }
      ],
      "role": "symbol",
      "title": "ENGetUserTraveledHandler",
      "type": "topic",
      "url": "/documentation/exposurenotification/engetusertraveledhandler"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager": {
      "abstract": [
        {
          "text": "A class that manages exposure notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENManager"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENManager"
        }
      ],
      "role": "symbol",
      "title": "ENManager",
      "type": "topic",
      "url": "/documentation/exposurenotification/enmanager"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/detectExposures(configuration:completionHandler:)": {
      "abstract": [
        {
          "text": "Detects exposures using the specified configuration to control the scoring algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectExposures"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ENExposureConfiguration",
          "text": "ENExposureConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENDetectExposuresHandler",
          "text": "ENDetectExposuresHandler"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/detectExposures(configuration:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detectExposuresWithConfiguration:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "detectExposures(configuration:completionHandler:)",
      "type": "topic",
      "url": "/documentation/exposurenotification/enmanager/detectexposures(configuration:completionhandler:)"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/detectExposures(configuration:diagnosisKeyURLs:completionHandler:)": {
      "abstract": [
        {
          "text": "Detects exposures using the configuration that you specify for controlling the scoring algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectExposures"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ENExposureConfiguration",
          "text": "ENExposureConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "diagnosisKeyURLs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENDetectExposuresHandler",
          "text": "ENDetectExposuresHandler"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/detectExposures(configuration:diagnosisKeyURLs:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detectExposuresWithConfiguration:diagnosisKeyURLs:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "detectExposures(configuration:diagnosisKeyURLs:completionHandler:)",
      "type": "topic",
      "url": "/documentation/exposurenotification/enmanager/detectexposures(configuration:diagnosiskeyurls:completionhandler:)"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureInfo(summary:userExplanation:completionHandler:)": {
      "abstract": [
        {
          "text": "Returns information about each exposure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getExposureInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "summary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ENExposureDetectionSummary",
          "text": "ENExposureDetectionSummary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userExplanation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENGetExposureInfoHandler",
          "text": "ENGetExposureInfoHandler"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureInfo(summary:userExplanation:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getExposureInfoFromSummary:userExplanation:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getExposureInfo(summary:userExplanation:completionHandler:)",
      "type": "topic",
      "url": "/documentation/exposurenotification/enmanager/getexposureinfo(summary:userexplanation:completionhandler:)"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureWindows(summary:completionHandler:)": {
      "abstract": [
        {
          "text": "Obtains information from the provided summary about the user’s exposure within a window of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getExposureWindows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "summary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ENExposureDetectionSummary",
          "text": "ENExposureDetectionSummary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENGetExposureWindowsHandler",
          "text": "ENGetExposureWindowsHandler"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureWindows(summary:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getExposureWindowsFromSummary:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getExposureWindows(summary:completionHandler:)",
      "type": "topic",
      "url": "/documentation/exposurenotification/enmanager/getexposurewindows(summary:completionhandler:)"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getUserTraveled(completionHandler:)": {
      "abstract": [
        {
          "text": "Obtains information about the user’s travel within an exposure period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getUserTraveled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENGetUserTraveledHandler",
          "text": "ENGetUserTraveledHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getUserTraveled(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getUserTraveledWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getUserTraveled(completionHandler:)",
      "type": "topic",
      "url": "/documentation/exposurenotification/enmanager/getusertraveled(completionhandler:)"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server": {
      "abstract": [
        {
          "text": "Ensure that your server meets the requirements for supporting Exposure Notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server",
      "kind": "article",
      "role": "article",
      "title": "Setting Up a Key Server",
      "type": "topic",
      "url": "/documentation/exposurenotification/setting-up-a-key-server"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress": {
      "abstract": [
        {
          "text": "An object that conveys ongoing progress to the user for a specified task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress",
      "kind": "symbol",
      "role": "symbol",
      "title": "Progress",
      "type": "topic",
      "url": "/documentation/foundation/progress"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Obtaining-Exposure-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/detectExposures(configuration:completionHandler:)",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureWindows(summary:completionHandler:)",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetExposureWindowsHandler",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getUserTraveled(completionHandler:)",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetUserTraveledHandler",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureInfo(summary:userExplanation:completionHandler:)"
      ],
      "title": "Obtaining Exposure Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Completion-Handlers",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDetectExposuresHandler"
      ],
      "title": "Completion Handlers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "detectExposuresWithConfiguration:diagnosisKeyURLs:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "detectExposuresWithConfiguration:diagnosisKeyURLs:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Completion-Handlers",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDetectExposuresHandler"
              ],
              "title": "Completion Handlers"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Obtaining-Exposure-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/detectExposures(configuration:completionHandler:)",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureWindows(summary:completionHandler:)",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetExposureWindowsHandler",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getUserTraveled(completionHandler:)",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENGetUserTraveledHandler",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureInfo(summary:userExplanation:completionHandler:)"
              ],
              "title": "Obtaining Exposure Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSProgress",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSProgress",
                    "text": "NSProgress"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "detectExposuresWithConfiguration:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ENExposureConfiguration",
                    "text": "ENExposureConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "configuration"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "diagnosisKeyURLs:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSURL *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "diagnosisKeyURLs"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDetectExposuresHandler",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ENDetectExposuresHandler",
                    "text": "ENDetectExposuresHandler"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The configuration to use for scoring.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "configuration"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of file URLs that contain downloaded diagnosis keys.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "diagnosisKeyURLs"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The completion handler that the framework calls when the method completes.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The progress of the method.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1getExposureWindows(summary:completionHandler:)/title",
          "value": "getExposureWindowsFromSummary:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1getExposureWindows(summary:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getExposureWindowsFromSummary:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDetectExposuresHandler/title",
          "value": "ENDetectExposuresHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDetectExposuresHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDetectExposuresHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDetectExposuresHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDetectExposuresHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1detectExposures(configuration:diagnosisKeyURLs:completionHandler:)/title",
          "value": "detectExposuresWithConfiguration:diagnosisKeyURLs:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1detectExposures(configuration:diagnosisKeyURLs:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "detectExposuresWithConfiguration:diagnosisKeyURLs:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/title",
          "value": "ENExposureConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetUserTraveledHandler/title",
          "value": "ENGetUserTraveledHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetUserTraveledHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENGetUserTraveledHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetUserTraveledHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENGetUserTraveledHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1getUserTraveled(completionHandler:)/title",
          "value": "getUserTraveledWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1getUserTraveled(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getUserTraveledWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1getExposureInfo(summary:userExplanation:completionHandler:)/title",
          "value": "getExposureInfoFromSummary:userExplanation:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1getExposureInfo(summary:userExplanation:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getExposureInfoFromSummary:userExplanation:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetExposureWindowsHandler/title",
          "value": "ENGetExposureWindowsHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetExposureWindowsHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENGetExposureWindowsHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENGetExposureWindowsHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENGetExposureWindowsHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSProgress/title",
          "value": "NSProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1detectExposures(configuration:completionHandler:)/title",
          "value": "detectExposuresWithConfiguration:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1detectExposures(configuration:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "detectExposuresWithConfiguration:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/title",
          "value": "ENManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/enmanager/detectexposures(configuration:diagnosiskeyurls:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/enmanager/detectexposures(configuration:diagnosiskeyurls:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
