{
  "abstract": [
    {
      "text": "The query uses the default search option that excludes Mail messages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext/SourceOptions-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuerySourceOptions/CSSearchQuerySourceOptionDefault"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CSSearchQuerySourceOptions@CSSearchQuerySourceOptionDefault",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CSSearchQuerySourceOptionDefault"
      }
    ],
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSSearchQuerySourceOptionDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "CSSearchQuerySourceOptionDefault"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "CSSearchQuerySourceOptionDefault"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext/SourceOptions-swift.struct": {
      "abstract": [
        {
          "text": "The query source options to allow or deny Mail messages in the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SourceOptions"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQueryContext/SourceOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SourceOptions"
        }
      ],
      "role": "symbol",
      "title": "CSSearchQueryContext.SourceOptions",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquerycontext/sourceoptions-swift.struct"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuerySourceOptions/CSSearchQuerySourceOptionDefault": {
      "abstract": [
        {
          "text": "The query uses the default search option that excludes Mail messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSSearchQuerySourceOptionDefault"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSSearchQuerySourceOptions/CSSearchQuerySourceOptionDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSearchQuerySourceOptionDefault",
      "type": "topic",
      "url": "/documentation/corespotlight/cssearchquerysourceoptions/cssearchquerysourceoptiondefault"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext~1SourceOptions-swift.struct/title",
          "value": "CSSearchQuerySourceOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext~1SourceOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuerySourceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSSearchQueryContext~1SourceOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSearchQuerySourceOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/cssearchquerysourceoptions/cssearchquerysourceoptiondefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
