{
  "abstract": [
    {
      "text": "Unknown event type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/unknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CWEventType@CWEventTypeUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknown"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CWEventTypeUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CWEventType.unknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType": {
      "abstract": [
        {
          "text": "Wi-Fi event types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWEventType"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventType"
        }
      ],
      "role": "symbol",
      "title": "CWEventType",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/bssidDidChange": {
      "abstract": [
        {
          "text": "Posts when the current BSSID of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bssidDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/bssidDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeBSSIDDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.bssidDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/bssiddidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/countryCodeDidChange": {
      "abstract": [
        {
          "text": "Posts when the adopted country code of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "countryCodeDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/countryCodeDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeCountryCodeDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.countryCodeDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/countrycodedidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkDidChange": {
      "abstract": [
        {
          "text": "Posts when the link state for any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeLinkDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.linkDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/linkdidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkQualityDidChange": {
      "abstract": [
        {
          "text": "Posts when the RSSI or transmit rate for any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkQualityDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkQualityDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeLinkQualityDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.linkQualityDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/linkqualitydidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/modeDidChange": {
      "abstract": [
        {
          "text": "Posts when the operating mode of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modeDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/modeDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeModeDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.modeDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/modedidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/none": {
      "abstract": [
        {
          "text": "No specified event type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeNone"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.none",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/none"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange": {
      "abstract": [
        {
          "text": "Posts when the power state of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "powerDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypePowerDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.powerDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/powerdidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/scanCacheUpdated": {
      "abstract": [
        {
          "text": "Posts when the scan cache of any Wi-Fi interface is updated with new scan results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scanCacheUpdated"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/scanCacheUpdated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeScanCacheUpdated"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.scanCacheUpdated",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/scancacheupdated"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/ssidDidChange": {
      "abstract": [
        {
          "text": "Posts when the current SSID of any Wi-Fi interface changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ssidDidChange"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/ssidDidChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeSSIDDidChange"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.ssidDidChange",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/ssiddidchange"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/unknown": {
      "abstract": [
        {
          "text": "Unknown event type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWEventTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "CWEventType.unknown",
      "type": "topic",
      "url": "/documentation/corewlan/cweventtype/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/none",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/ssidDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/bssidDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/countryCodeDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkQualityDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/modeDidChange",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/scanCacheUpdated"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CWEventTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/none",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/powerDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/ssidDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/bssidDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/countryCodeDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/linkQualityDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/modeDidChange",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWEventType/scanCacheUpdated"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CWEventTypeUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1bssidDidChange/title",
          "value": "CWEventTypeBSSIDDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1bssidDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeBSSIDDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/title",
          "value": "CWEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1scanCacheUpdated/title",
          "value": "CWEventTypeScanCacheUpdated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1scanCacheUpdated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeScanCacheUpdated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1countryCodeDidChange/title",
          "value": "CWEventTypeCountryCodeDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1countryCodeDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeCountryCodeDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1unknown/title",
          "value": "CWEventTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1none/title",
          "value": "CWEventTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1modeDidChange/title",
          "value": "CWEventTypeModeDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1modeDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeModeDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1ssidDidChange/title",
          "value": "CWEventTypeSSIDDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1ssidDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeSSIDDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1linkQualityDidChange/title",
          "value": "CWEventTypeLinkQualityDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1linkQualityDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeLinkQualityDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1powerDidChange/title",
          "value": "CWEventTypePowerDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1powerDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypePowerDidChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1linkDidChange/title",
          "value": "CWEventTypeLinkDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWEventType~1linkDidChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWEventTypeLinkDidChange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cweventtype/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cweventtype/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
