{
  "abstract": [
    {
      "text": "An Automator error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11AMErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AMError"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AMError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AMError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AMError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMActionErrorKey": {
      "abstract": [
        {
          "text": "A key to retrieve the action that caused an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMActionErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMActionErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionErrorKey"
        }
      ],
      "role": "symbol",
      "title": "AMActionErrorKey",
      "type": "topic",
      "url": "/documentation/automator/amactionerrorkey"
    },
    "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the Automator error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMAutomatorErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMAutomatorErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "AMAutomatorErrorDomain",
      "type": "topic",
      "url": "/documentation/automator/amautomatorerrordomain"
    },
    "doc://com.apple.automator/documentation/Automator/AMError": {
      "abstract": [
        {
          "text": "An Automator error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "role": "symbol",
      "title": "AMError",
      "type": "topic",
      "url": "/documentation/automator/amerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code": {
      "abstract": [
        {
          "text": "Automator error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code",
      "type": "topic",
      "url": "/documentation/automator/amerror/code"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationResourceError": {
      "abstract": [
        {
          "text": "An error that indicates an app required by the action is not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionApplicationResourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationResourceError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionApplicationResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionapplicationresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationVersionResourceError": {
      "abstract": [
        {
          "text": "An error that indicates an app required by the action is the wrong version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionApplicationVersionResourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationVersionResourceError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionApplicationVersionResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionapplicationversionresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionArchitectureMismatchError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s binary is not compatible with the current processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionArchitectureMismatchError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionArchitectureMismatchError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionArchitectureMismatchError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionarchitecturemismatcherror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionExceptionError": {
      "abstract": [
        {
          "text": "An error that indicates an action encounters an exception while running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionExceptionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionExceptionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionExceptionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionexceptionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionExecutionError": {
      "abstract": [
        {
          "text": "An error that indicates an action encounters an error while running (reason unknown).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionExecutionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionExecutionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionExecutionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionexecutionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionFailedGatekeeperError": {
      "abstract": [
        {
          "text": "An error that indicates the action doesn’t meet the Gatekeeper security policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionFailedGatekeeperError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionFailedGatekeeperError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionFailedGatekeeperError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionfailedgatekeepererror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionFileResourceError": {
      "abstract": [
        {
          "text": "An error that indicates a file required by the action is not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionFileResourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionFileResourceError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionFileResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionfileresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionInitializationError": {
      "abstract": [
        {
          "text": "An error that indicates Automator is unable to initialize an action (reason unknown).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionInitializationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionInitializationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionInitializationError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actioninitializationerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionInsufficientDataError": {
      "abstract": [
        {
          "text": "An error that indicates the action requires input data to run, but none was supplied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionInsufficientDataError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionInsufficientDataError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionInsufficientDataError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actioninsufficientdataerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionIsDeprecatedError": {
      "abstract": [
        {
          "text": "An error that indicates the action has been deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionIsDeprecatedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionIsDeprecatedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionIsDeprecatedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionisdeprecatederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionLicenseResourceError": {
      "abstract": [
        {
          "text": "An error that indicates a license required by the action was not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionLicenseResourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionLicenseResourceError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionLicenseResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionlicenseresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionLinkError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s executable failed to load due to linking issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionLinkError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionLinkError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionLinkError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionlinkerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionLoadError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s executable failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionLoadError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionLoadError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionLoadError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionloaderror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionMalwareError": {
      "abstract": [
        {
          "text": "An error that indicates the action has been identified as malware by XProtect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionMalwareError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionMalwareError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionMalwareError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionmalwareerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionNotLoadableError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s executable is of a type that is not loadable in the current process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionNotLoadableError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionNotLoadableError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionNotLoadableError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionnotloadableerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionPropertyListInvalidError": {
      "abstract": [
        {
          "text": "An error that indicates the property list for an action is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionPropertyListInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionPropertyListInvalidError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionPropertyListInvalidError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionpropertylistinvaliderror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionQuarantineError": {
      "abstract": [
        {
          "text": "An error that indicates action has been quarantined by XProtect, the antimalware system on the Mac.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionQuarantineError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionQuarantineError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionQuarantineError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionquarantineerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionRequiredActionResourceError": {
      "abstract": [
        {
          "text": "An error that indicates an action required by the action is not loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionRequiredActionResourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionRequiredActionResourceError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionRequiredActionResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionrequiredactionresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionRuntimeMismatchError": {
      "abstract": [
        {
          "text": "An error that indicates an attempt was made to load an action that is not compiled in a way that is compatible with the current app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionRuntimeMismatchError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionRuntimeMismatchError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionRuntimeMismatchError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionruntimemismatcherror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionSignatureCorruptError": {
      "abstract": [
        {
          "text": "An error that indicates developer signature for this action is corrupted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionSignatureCorruptError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionSignatureCorruptError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionSignatureCorruptError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionsignaturecorrupterror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionThirdPartyActionsNotAllowedError": {
      "abstract": [
        {
          "text": "An error that indicates the action is a third party action, and loading it has not been allowed by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionThirdPartyActionsNotAllowedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionThirdPartyActionsNotAllowedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionThirdPartyActionsNotAllowedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionthirdpartyactionsnotallowederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionXPCError": {
      "abstract": [
        {
          "text": "An error that indicates the remote process running the action has crashed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionXPCError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionXPCError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionXPCError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionxpcerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionXProtectError": {
      "abstract": [
        {
          "text": "An error that indicates XProtect is unable to successfully analyze the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionXProtectError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionXProtectError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionXProtectError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionxprotecterror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/conversionFailedError": {
      "abstract": [
        {
          "text": "An error that occurs when, for example, the converter encounters an error converting data from one type to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conversionFailedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/conversionFailedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "conversionFailedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/conversionfailederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/conversionNoDataError": {
      "abstract": [
        {
          "text": "An error that occurs when the converter determines that the conversion, though possible, would produce a nil result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conversionNoDataError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/conversionNoDataError",
      "kind": "symbol",
      "role": "symbol",
      "title": "conversionNoDataError",
      "type": "topic",
      "url": "/documentation/automator/amerror/conversionnodataerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/conversionNotPossibleError": {
      "abstract": [
        {
          "text": "An error that occurs when the converter determines that it is unable to convert from one data type to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conversionNotPossibleError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/conversionNotPossibleError",
      "kind": "symbol",
      "role": "symbol",
      "title": "conversionNotPossibleError",
      "type": "topic",
      "url": "/documentation/automator/amerror/conversionnotpossibleerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/noSuchActionError": {
      "abstract": [
        {
          "text": "An error that indicates the action could not be located on the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuchActionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/noSuchActionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "noSuchActionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/nosuchactionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/userCanceledError": {
      "abstract": [
        {
          "text": "An error that indicates the user cancelled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCanceledError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/userCanceledError",
      "kind": "symbol",
      "role": "symbol",
      "title": "userCanceledError",
      "type": "topic",
      "url": "/documentation/automator/amerror/usercancelederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowActionsNotLoadedError": {
      "abstract": [
        {
          "text": "An error that indicates one of the actions of the workflow couldn’t be loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowActionsNotLoadedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowActionsNotLoadedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowActionsNotLoadedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflowactionsnotloadederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerActionVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an action in a workflow is newer than the installed action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNewerActionVersionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerActionVersionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowNewerActionVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflowneweractionversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an attempt to open a workflow document that was saved with a newer version of Automator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNewerVersionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerVersionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowNewerVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflownewerversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowNoEnabledActionsError": {
      "abstract": [
        {
          "text": "An error that indicates there are no enabled actions in the workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNoEnabledActionsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowNoEnabledActionsError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowNoEnabledActionsError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflownoenabledactionserror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowOlderActionVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an action in a workflow is older than the installed action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowOlderActionVersionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowOlderActionVersionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowOlderActionVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflowolderactionversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowPropertyListInvalidError": {
      "abstract": [
        {
          "text": "An error that indicates an attempt to open a workflow document whose property list couldn’t be read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowPropertyListInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowPropertyListInvalidError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowPropertyListInvalidError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflowpropertylistinvaliderror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain",
        "doc://com.apple.automator/documentation/Automator/AMActionErrorKey",
        "doc://com.apple.automator/documentation/Automator/AMError/Code"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMError/workflowActionsNotLoadedError",
        "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerActionVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/workflowNoEnabledActionsError",
        "doc://com.apple.automator/documentation/Automator/AMError/workflowOlderActionVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/workflowPropertyListInvalidError",
        "doc://com.apple.automator/documentation/Automator/AMError/userCanceledError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationVersionResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionArchitectureMismatchError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionExceptionError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionExecutionError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionFailedGatekeeperError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionFileResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionInitializationError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionInsufficientDataError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionIsDeprecatedError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionLicenseResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionLinkError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionLoadError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionMalwareError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionNotLoadableError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionPropertyListInvalidError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionQuarantineError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionRequiredActionResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionRuntimeMismatchError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionSignatureCorruptError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionThirdPartyActionsNotAllowedError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionXPCError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionXProtectError",
        "doc://com.apple.automator/documentation/Automator/AMError/noSuchActionError",
        "doc://com.apple.automator/documentation/Automator/AMError/conversionFailedError",
        "doc://com.apple.automator/documentation/Automator/AMError/conversionNoDataError",
        "doc://com.apple.automator/documentation/Automator/AMError/conversionNotPossibleError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Error-Domain",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain"
      ],
      "title": "Error Domain"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMActionErrorKey/title",
          "value": "AMActionErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMActionErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/title",
          "value": "AMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAutomatorErrorDomain/title",
          "value": "AMAutomatorErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAutomatorErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAutomatorErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
