{
  "abstract": [
    {
      "text": "An object that lets you use an Automator workflow in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMWorkflow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AMWorkflow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AMWorkflow"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AMWorkflow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AMWorkflow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "workflow",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " consists of one or more actions, discrete tasks which together can perform complex automation tasks. Your app can use workflows to package its own features and to take advantage of features provided by other apps. You create actions with Xcode, while you create workflows with the Automator app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can load and run a workflow with minimal overhead by using the class method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/run(at:withInput:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". However, in situations where you need greater control, such as the ability to start and stop the workflow, you can use an instance of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class instead. In that case, you must create and initialize both the workflow and the workflow controller objects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In either case, the workflow runs in a separate process so that any actions it contains are executed in a separate memory space.  That helps to insulate your app from crashes, memory leaks, or exceptions that might occur from running the actions in the workflow.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can display a workflow with an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow": {
      "abstract": [
        {
          "text": "An object that lets you use an Automator workflow in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflow"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflow"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflow",
      "type": "topic",
      "url": "/documentation/automator/amworkflow"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/actions": {
      "abstract": [
        {
          "text": "An array of the workflow’s actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMAction",
          "text": "AMAction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/actions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "actions"
        }
      ],
      "role": "symbol",
      "title": "actions",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/actions"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/addAction(_:)": {
      "abstract": [
        {
          "text": "Adds the specified action at the end of the receiving workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMAction",
          "text": "AMAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/addAction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAction:"
        }
      ],
      "role": "symbol",
      "title": "addAction(_:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/addaction(_:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/fileURL": {
      "abstract": [
        {
          "text": "A URL that specifies the location of the workflow file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/fileURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileURL"
        }
      ],
      "role": "symbol",
      "title": "fileURL",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/fileurl"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/init()": {
      "abstract": [
        {
          "text": "Creates and initializes a workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/init()"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/init(contentsOf:)": {
      "abstract": [
        {
          "text": "Creates and initializes a workflow based on the contents of the specified file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/init(contentsOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentsOfURL:error:"
        }
      ],
      "role": "symbol",
      "title": "init(contentsOf:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/init(contentsof:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/input": {
      "abstract": [
        {
          "text": "The input data that is passed to the first action in the workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/input",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "input"
        }
      ],
      "role": "symbol",
      "title": "input",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/input"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/insertAction(_:at:)": {
      "abstract": [
        {
          "text": "Inserts the specified action at the specified position of the receiving workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMAction",
          "text": "AMAction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/insertAction(_:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertAction:atIndex:"
        }
      ],
      "role": "symbol",
      "title": "insertAction(_:at:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/insertaction(_:at:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/moveAction(at:to:)": {
      "abstract": [
        {
          "text": "Moves the action from the specified start position to the specified end position in the receiving workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/moveAction(at:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveActionAtIndex:toIndex:"
        }
      ],
      "role": "symbol",
      "title": "moveAction(at:to:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/moveaction(at:to:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/output": {
      "abstract": [
        {
          "text": "The output data that is provided by the last action in the workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/output",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "output"
        }
      ],
      "role": "symbol",
      "title": "output",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/output"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/removeAction(_:)": {
      "abstract": [
        {
          "text": "Removes the specified action from the workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMAction",
          "text": "AMAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/removeAction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAction:"
        }
      ],
      "role": "symbol",
      "title": "removeAction(_:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/removeaction(_:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/run(at:withInput:)": {
      "abstract": [
        {
          "text": "Loads and runs the specified workflow file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "run"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/run(at:withInput:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runWorkflowAtURL:withInput:error:"
        }
      ],
      "role": "symbol",
      "title": "run(at:withInput:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/run(at:withinput:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/setValue(_:forVariableWithName:)": {
      "abstract": [
        {
          "text": "Sets the value of the workflow variable with the specified name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forVariableWithName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/setValue(_:forVariableWithName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setValue:forVariableWithName:"
        }
      ],
      "role": "symbol",
      "title": "setValue(_:forVariableWithName:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/setvalue(_:forvariablewithname:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/valueForVariable(withName:)": {
      "abstract": [
        {
          "text": "Returns the value of the workflow variable with the specified name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueForVariable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/valueForVariable(withName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForVariableWithName:"
        }
      ],
      "role": "symbol",
      "title": "valueForVariable(withName:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/valueforvariable(withname:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow/write(to:)": {
      "abstract": [
        {
          "text": "Writes the workflow to the specified file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow/write(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeToURL:error:"
        }
      ],
      "role": "symbol",
      "title": "write(to:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflow/write(to:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowController": {
      "abstract": [
        {
          "text": "An object that lets you manage an Automator workflow in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflowController"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowController"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflowController",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontroller"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowView": {
      "abstract": [
        {
          "text": "An object that lets you view and edit Automator workflows in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflowView"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowView"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflowView",
      "type": "topic",
      "url": "/documentation/automator/amworkflowview"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkspace": {
      "abstract": [
        {
          "text": "A workspace for running an Automator workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkspace"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkspace"
        }
      ],
      "role": "symbol",
      "title": "AMWorkspace",
      "type": "topic",
      "url": "/documentation/automator/amworkspace"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Workflows",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
        "doc://com.apple.automator/documentation/Automator/AMWorkflowView",
        "doc://com.apple.automator/documentation/Automator/AMWorkspace"
      ],
      "title": "Workflows"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Workflow",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/init()",
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/init(contentsOf:)"
      ],
      "title": "Creating a Workflow"
    },
    {
      "anchor": "Running-a-Workflow",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/run(at:withInput:)"
      ],
      "title": "Running a Workflow"
    },
    {
      "anchor": "Saving-Changes-to-a-Workflow",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/write(to:)"
      ],
      "title": "Saving Changes to a Workflow"
    },
    {
      "anchor": "Getting-Information-About-a-Workflow",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/actions",
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/fileURL",
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/valueForVariable(withName:)"
      ],
      "title": "Getting Information About a Workflow"
    },
    {
      "anchor": "Working-with-the-Workflows-Input-and-Output",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/input",
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/output"
      ],
      "title": "Working with the Workflow’s Input and Output"
    },
    {
      "anchor": "Manipulating-the-Workflow",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/setValue(_:forVariableWithName:)"
      ],
      "title": "Manipulating the Workflow"
    },
    {
      "anchor": "Manipulating-the-Workflows-Actions",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/addAction(_:)",
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/insertAction(_:at:)",
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/moveAction(at:to:)",
        "doc://com.apple.automator/documentation/Automator/AMWorkflow/removeAction(_:)"
      ],
      "title": "Manipulating the Workflow’s Actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AMWorkflow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.automator/documentation/Automator"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Workflow",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/init()",
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/init(contentsOf:)"
              ],
              "title": "Creating a Workflow"
            },
            {
              "anchor": "Running-a-Workflow",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/run(at:withInput:)"
              ],
              "title": "Running a Workflow"
            },
            {
              "anchor": "Saving-Changes-to-a-Workflow",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/write(to:)"
              ],
              "title": "Saving Changes to a Workflow"
            },
            {
              "anchor": "Getting-Information-About-a-Workflow",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/actions",
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/fileURL",
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/valueForVariable(withName:)"
              ],
              "title": "Getting Information About a Workflow"
            },
            {
              "anchor": "Working-with-the-Workflows-Input-and-Output",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/input",
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/output"
              ],
              "title": "Working with the Workflow’s Input and Output"
            },
            {
              "anchor": "Manipulating-the-Workflow",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/setValue(_:forVariableWithName:)"
              ],
              "title": "Manipulating the Workflow"
            },
            {
              "anchor": "Manipulating-the-Workflows-Actions",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/addAction(_:)",
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/insertAction(_:at:)",
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/moveAction(at:to:)",
                "doc://com.apple.automator/documentation/Automator/AMWorkflow/removeAction(_:)"
              ],
              "title": "Manipulating the Workflow’s Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Workflows",
              "generated": true,
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
                "doc://com.apple.automator/documentation/Automator/AMWorkflowView",
                "doc://com.apple.automator/documentation/Automator/AMWorkspace"
              ],
              "title": "Workflows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AMWorkflow"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1fileURL/title",
          "value": "fileURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1fileURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fileURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1write(to:)/title",
          "value": "writeToURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1write(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeToURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1output/title",
          "value": "output"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1output/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1init(contentsOf:)/title",
          "value": "initWithContentsOfURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1init(contentsOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithContentsOfURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1run(at:withInput:)/title",
          "value": "runWorkflowAtURL:withInput:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1run(at:withInput:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "runWorkflowAtURL:withInput:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace/title",
          "value": "AMWorkspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkspace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1input/title",
          "value": "input"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1input/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1removeAction(_:)/title",
          "value": "removeAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1removeAction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1setValue(_:forVariableWithName:)/title",
          "value": "setValue:forVariableWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1setValue(_:forVariableWithName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setValue:forVariableWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/title",
          "value": "AMWorkflowController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1moveAction(at:to:)/title",
          "value": "moveActionAtIndex:toIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1moveAction(at:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "moveActionAtIndex:toIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/title",
          "value": "AMWorkflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1insertAction(_:at:)/title",
          "value": "insertAction:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1insertAction(_:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertAction:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1actions/title",
          "value": "actions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1actions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1valueForVariable(withName:)/title",
          "value": "valueForVariableWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1valueForVariable(withName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueForVariableWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowView/title",
          "value": "AMWorkflowView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1addAction(_:)/title",
          "value": "addAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow~1addAction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAction:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amworkflow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator/amworkflow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
