{
  "abstract": [
    {
      "text": "A set of optional methods that a delegate of a workflow controller implements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AMWorkflowControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AMWorkflowControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AMWorkflowControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "AMWorkflowControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AMWorkflowControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowController/delegate": {
      "abstract": [
        {
          "text": "The controller’s delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AMWorkflowControllerDelegate",
          "text": "AMWorkflowControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontroller/delegate"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods that a delegate of a workflow controller implements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflowControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflowControllerDelegate",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontrollerdelegate"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the workflow encounters an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workflowController:didError:"
        }
      ],
      "role": "symbol",
      "title": "workflowController(_:didError:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontrollerdelegate/workflowcontroller(_:diderror:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didRun:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the specified action finishes running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRun"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMAction",
          "text": "AMAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didRun:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workflowController:didRunAction:"
        }
      ],
      "role": "symbol",
      "title": "workflowController(_:didRun:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontrollerdelegate/workflowcontroller(_:didrun:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:willRun:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the specified action is about to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willRun"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMAction",
          "text": "AMAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:willRun:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workflowController:willRunAction:"
        }
      ],
      "role": "symbol",
      "title": "workflowController(_:willRun:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontrollerdelegate/workflowcontroller(_:willrun:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidRun(_:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the workflow controller object finishes running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowControllerDidRun"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidRun(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workflowControllerDidRun:"
        }
      ],
      "role": "symbol",
      "title": "workflowControllerDidRun(_:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontrollerdelegate/workflowcontrollerdidrun(_:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidStop(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the workflow controller object has stopped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowControllerDidStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidStop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workflowControllerDidStop:"
        }
      ],
      "role": "symbol",
      "title": "workflowControllerDidStop(_:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontrollerdelegate/workflowcontrollerdidstop(_:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillRun(_:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the workflow controller object is about to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowControllerWillRun"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillRun(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workflowControllerWillRun:"
        }
      ],
      "role": "symbol",
      "title": "workflowControllerWillRun(_:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontrollerdelegate/workflowcontrollerwillrun(_:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillStop(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the workflow controller object is about to stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowControllerWillStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillStop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workflowControllerWillStop:"
        }
      ],
      "role": "symbol",
      "title": "workflowControllerWillStop(_:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontrollerdelegate/workflowcontrollerwillstop(_:)"
    },
    "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the workflow encounters an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didError"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowController(_:didError:)",
      "type": "topic",
      "url": "/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)"
    },
    "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didRun:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the specified action finishes running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRun"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMAction",
          "text": "AMAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didRun:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowController(_:didRun:)",
      "type": "topic",
      "url": "/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didRun:)"
    },
    "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:willRun:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the specified action is about to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willRun"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMAction",
          "text": "AMAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:willRun:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowController(_:willRun:)",
      "type": "topic",
      "url": "/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:willRun:)"
    },
    "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidRun(_:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the workflow controller object finishes running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowControllerDidRun"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidRun(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowControllerDidRun(_:)",
      "type": "topic",
      "url": "/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidRun(_:)"
    },
    "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidStop(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the workflow controller object has stopped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowControllerDidStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidStop(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowControllerDidStop(_:)",
      "type": "topic",
      "url": "/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidStop(_:)"
    },
    "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillRun(_:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the workflow controller object is about to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowControllerWillRun"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillRun(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowControllerWillRun(_:)",
      "type": "topic",
      "url": "/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillRun(_:)"
    },
    "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillStop(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the workflow controller object is about to stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowControllerWillStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillStop(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowControllerWillStop(_:)",
      "type": "topic",
      "url": "/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillStop(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Delegate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflowController/delegate"
      ],
      "title": "Accessing the Delegate"
    }
  ],
  "topicSections": [
    {
      "anchor": "Preparing-to-Run",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:willRun:)",
        "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillRun(_:)"
      ],
      "title": "Preparing to Run"
    },
    {
      "anchor": "Running",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didRun:)",
        "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidRun(_:)"
      ],
      "title": "Running"
    },
    {
      "anchor": "Stopping",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillStop(_:)",
        "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidStop(_:)"
      ],
      "title": "Stopping"
    },
    {
      "anchor": "Handling-Errors",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)"
      ],
      "title": "Handling Errors"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:willRun:)",
        "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillRun(_:)",
        "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didRun:)",
        "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidRun(_:)",
        "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillStop(_:)",
        "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidStop(_:)",
        "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AMWorkflowControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.automator/documentation/Automator"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Preparing-to-Run",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:willRun:)",
                "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillRun(_:)"
              ],
              "title": "Preparing to Run"
            },
            {
              "anchor": "Running",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didRun:)",
                "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidRun(_:)"
              ],
              "title": "Running"
            },
            {
              "anchor": "Stopping",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillStop(_:)",
                "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidStop(_:)"
              ],
              "title": "Stopping"
            },
            {
              "anchor": "Handling-Errors",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)"
              ],
              "title": "Handling Errors"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:willRun:)",
                "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillRun(_:)",
                "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didRun:)",
                "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidRun(_:)",
                "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerWillStop(_:)",
                "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowControllerDidStop(_:)",
                "doc://com.apple.documentation/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-Delegate",
              "generated": true,
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMWorkflowController/delegate"
              ],
              "title": "Accessing the Delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AMWorkflowControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerWillStop(_:)/title",
          "value": "workflowControllerWillStop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerWillStop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workflowControllerWillStop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerDidRun(_:)/title",
          "value": "workflowControllerDidRun:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerDidRun(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "workflowControllerDidRun:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMWorkflowController",
              "text": "AMWorkflowController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:didRun:)/title",
          "value": "workflowController:didRunAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:didRun:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "workflowController:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMWorkflowController",
              "text": "AMWorkflowController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didRunAction:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMAction",
              "text": "AMAction"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "action"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerDidRun(_:)/title",
          "value": "workflowControllerDidRun:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerDidRun(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workflowControllerDidRun:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerDidStop(_:)/title",
          "value": "workflowControllerDidStop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerDidStop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workflowControllerDidStop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:willRun:)/title",
          "value": "workflowController:willRunAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:willRun:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workflowController:willRunAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerWillRun(_:)/title",
          "value": "workflowControllerWillRun:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerWillRun(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "workflowControllerWillRun:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMWorkflowController",
              "text": "AMWorkflowController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerWillRun(_:)/title",
          "value": "workflowControllerWillRun:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerWillRun(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workflowControllerWillRun:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerDidStop(_:)/title",
          "value": "workflowControllerDidStop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerDidStop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "workflowControllerDidStop:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMWorkflowController",
              "text": "AMWorkflowController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerWillStop(_:)/title",
          "value": "workflowControllerWillStop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowControllerWillStop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "workflowControllerWillStop:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMWorkflowController",
              "text": "AMWorkflowController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:didError:)/title",
          "value": "workflowController:didError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:didError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "workflowController:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMWorkflowController",
              "text": "AMWorkflowController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didError:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:didError:)/title",
          "value": "workflowController:didError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:didError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workflowController:didError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate/title",
          "value": "AMWorkflowControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:didRun:)/title",
          "value": "workflowController:didRunAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:didRun:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workflowController:didRunAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:willRun:)/title",
          "value": "workflowController:willRunAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:willRun:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "workflowController:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMWorkflowController",
              "text": "AMWorkflowController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "willRunAction:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMAction",
              "text": "AMAction"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "action"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amworkflowcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator/amworkflowcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
