{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionHangingMask"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A bit mask composed of one or more constants specifying the types of exceptions that","type":"text"},{"text":" ","type":"text"},{"text":"will halt execution for debugging. See ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants","type":"reference"},{"text":" ","type":"text"},{"text":"for information about the constants.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["/documentation/exceptionhandling/nsexceptionhandler/exceptionhangingmask()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/exceptionhandling/nsexceptionhandler/exceptionhangingmask()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Returns a bit mask representing the types of exceptions that will halt execution"},{"type":"text","text":" "},{"type":"text","text":"for debugging."}],"seeAlsoSections":[{"anchor":"Getting-and-setting-exception-masks","generated":true,"title":"Getting and setting exception masks","identifiers":["doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)"]}],"identifier":{"url":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Exception-Handling/documentation/ExceptionHandling","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"]]},"metadata":{"title":"exceptionHangingMask()","externalID":"c:objc(cs)NSExceptionHandler(im)exceptionHangingMask","navigatorTitle":[{"text":"exceptionHangingMask","kind":"identifier"}],"role":"symbol","platforms":[{"beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"introducedAt":"10.0","deprecated":false,"name":"macOS"}],"modules":[{"name":"Exception Handling"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exceptionHangingMask","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Method"},"references":{"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionHangingMask"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()","navigatorTitle":[{"kind":"identifier","text":"exceptionHangingMask"}],"title":"exceptionHangingMask()","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Returns a bit mask representing the types of exceptions that will halt execution"},{"type":"text","text":" "},{"text":"for debugging.","type":"text"}],"url":"/documentation/exceptionhandling/nsexceptionhandler/exceptionhangingmask()"},"doc://com.externally.resolved.symbol/s:Si":{"identifier":"doc://com.externally.resolved.symbol/s:Si","title":"Int","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"kind":"symbol","url":"/documentation/Swift/Int","type":"topic","abstract":[{"type":"text","text":"A signed integer value type."}],"role":"symbol"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)":{"url":"/documentation/exceptionhandling/nsexceptionhandler/setexceptionhangingmask(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setExceptionHangingMask:"}],"abstract":[{"text":"Sets the bit mask of constants specifying the types of exceptions that will halt","type":"text"},{"type":"text","text":" "},{"type":"text","text":"execution for debugging."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setExceptionHangingMask","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"setExceptionHangingMask(_:)"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler":{"kind":"symbol","url":"/documentation/exceptionhandling/nsexceptionhandler","role":"symbol","type":"topic","title":"NSExceptionHandler","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSExceptionHandler","kind":"identifier"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler","abstract":[{"text":"The ","type":"text"},{"code":"NSExceptionHandler","type":"codeVoice"},{"text":" class provides facilities for monitoring and debugging exceptional","type":"text"},{"type":"text","text":" "},{"type":"text","text":"conditions in Objective-C programs. It works by installing a special uncaught exception"},{"type":"text","text":" "},{"type":"text","text":"handler via the  "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler"},{"type":"text","text":" "},{"text":"function. Consequently, to use the services of ","type":"text"},{"code":"NSExceptionHandler","type":"codeVoice"},{"text":", you must not","type":"text"},{"text":" ","type":"text"},{"text":"install your own custom uncaught exception handler.","type":"text"}],"navigatorTitle":[{"text":"NSExceptionHandler","kind":"identifier"}]},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants":{"url":"/documentation/exceptionhandling/system-hang-constants","kind":"article","type":"topic","role":"collectionGroup","abstract":[{"text":"Use one or more of the following constants in the parameter of ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)","type":"reference"},{"type":"text","text":" "},{"type":"text","text":"to specify the types of exceptions that cause the exception to halt execution so"},{"type":"text","text":" "},{"type":"text","text":"a debugger can be attached."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants","title":"System Hang Constants"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)":{"url":"/documentation/exceptionhandling/nsexceptionhandler/setexceptionhandlingmask(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"setExceptionHandlingMask:","kind":"identifier"}],"abstract":[{"text":"Sets the bit mask of constants specifying the types of exceptions monitored by the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"receiver and its handling and logging behavior."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setExceptionHandlingMask"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setExceptionHandlingMask(_:)"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","kind":"technologies","role":"overview","type":"topic"},"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler":{"identifier":"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler","title":"NSSetUncaughtExceptionHandler(_:)","url":"/documentation/foundation/1409609-nssetuncaughtexceptionhandler","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Changes the top-level error handler."}],"type":"topic","fragments":[{"kind":"text","text":"func "},{"text":"NSSetUncaughtExceptionHandler","kind":"identifier"},{"text":"(((NSException) -> Void)?)","kind":"text"}]},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling":{"url":"/documentation/exceptionhandling","abstract":[{"text":"Monitor and debug exceptional conditions in code.","type":"text"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling","title":"Exception Handling","kind":"symbol","role":"collection","type":"topic"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()":{"abstract":[{"text":"Returns a bit mask representing the types of exceptions monitored by the receiver","type":"text"},{"text":" ","type":"text"},{"text":"and its handling and logging behavior.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exceptionHandlingMask","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"exceptionHandlingMask","kind":"identifier"}],"type":"topic","url":"/documentation/exceptionhandling/nsexceptionhandler/exceptionhandlingmask()","title":"exceptionHandlingMask()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.0"},{"name":"macOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"10.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"exceptionHangingMask"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"exceptionHangingMask"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Exception-Handling/documentation/ExceptionHandling","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"title":"Getting and setting exception masks","identifiers":["doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)"],"anchor":"Getting-and-setting-exception-masks"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"exceptionHangingMask"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"/primaryContentSections/1","value":{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"A bit mask composed of one or more constants specifying the types of exceptions that","type":"text"},{"text":" ","type":"text"},{"text":"will halt execution for debugging. See ","type":"text"},{"type":"reference","identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants","isActive":true},{"text":" ","type":"text"},{"text":"for information about the constants.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHangingMask()/title","value":"exceptionHangingMask","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHangingMask()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"exceptionHangingMask"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/title","value":"setExceptionHangingMask:","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setExceptionHangingMask:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/title","value":"NSExceptionHandler","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/fragments","value":[{"kind":"identifier","text":"NSExceptionHandler"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/navigatorTitle","value":[{"text":"NSExceptionHandler","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/title","value":"setExceptionHandlingMask:","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setExceptionHandlingMask:","kind":"identifier"}],"op":"replace"},{"value":"NSSetUncaughtExceptionHandler","path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~11409609-nssetuncaughtexceptionhandler/title","op":"replace"},{"value":"exceptionHandlingMask","path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHandlingMask()/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"exceptionHandlingMask","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHandlingMask()/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}