{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Exception-Handling/documentation/ExceptionHandling","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionHandlingMask"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"externalID":"c:objc(cs)NSExceptionHandler(im)exceptionHandlingMask","navigatorTitle":[{"text":"exceptionHandlingMask","kind":"identifier"}],"title":"exceptionHandlingMask()","platforms":[{"deprecated":false,"introducedAt":"13.0","unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"introducedAt":"10.0","unavailable":false,"name":"macOS","beta":false}],"roleHeading":"Instance Method","modules":[{"name":"Exception Handling"}]},"identifier":{"url":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a bit mask representing the types of exceptions monitored by the receiver"},{"type":"text","text":" "},{"type":"text","text":"and its handling and logging behavior."}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionHandlingMask"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A bit mask composed of one or more constants specifying the types of exceptions monitored"},{"type":"text","text":" "},{"type":"text","text":"and whether they are handled or logged (or both). See "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants"},{"type":"text","text":" "},{"type":"text","text":"for information about the constants."}],"type":"paragraph"}]}],"seeAlsoSections":[{"anchor":"Getting-and-setting-exception-masks","generated":true,"identifiers":["doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)"],"title":"Getting and setting exception masks"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/exceptionhandling/nsexceptionhandler/exceptionhandlingmask()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/exceptionhandling/nsexceptionhandler/exceptionhandlingmask()"]}],"references":{"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler":{"kind":"symbol","url":"/documentation/exceptionhandling/nsexceptionhandler","role":"symbol","type":"topic","title":"NSExceptionHandler","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSExceptionHandler","kind":"identifier"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler","abstract":[{"text":"The ","type":"text"},{"code":"NSExceptionHandler","type":"codeVoice"},{"text":" class provides facilities for monitoring and debugging exceptional","type":"text"},{"type":"text","text":" "},{"type":"text","text":"conditions in Objective-C programs. It works by installing a special uncaught exception"},{"type":"text","text":" "},{"type":"text","text":"handler via the  "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler"},{"type":"text","text":" "},{"text":"function. Consequently, to use the services of ","type":"text"},{"code":"NSExceptionHandler","type":"codeVoice"},{"text":", you must not","type":"text"},{"text":" ","type":"text"},{"text":"install your own custom uncaught exception handler.","type":"text"}],"navigatorTitle":[{"text":"NSExceptionHandler","kind":"identifier"}]},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)":{"url":"/documentation/exceptionhandling/nsexceptionhandler/setexceptionhandlingmask(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"setExceptionHandlingMask:","kind":"identifier"}],"abstract":[{"text":"Sets the bit mask of constants specifying the types of exceptions monitored by the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"receiver and its handling and logging behavior."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setExceptionHandlingMask"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setExceptionHandlingMask(_:)"},"doc://com.externally.resolved.symbol/s:Si":{"identifier":"doc://com.externally.resolved.symbol/s:Si","title":"Int","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"kind":"symbol","url":"/documentation/Swift/Int","type":"topic","abstract":[{"type":"text","text":"A signed integer value type."}],"role":"symbol"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionHangingMask"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()","navigatorTitle":[{"kind":"identifier","text":"exceptionHangingMask"}],"title":"exceptionHangingMask()","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Returns a bit mask representing the types of exceptions that will halt execution"},{"type":"text","text":" "},{"text":"for debugging.","type":"text"}],"url":"/documentation/exceptionhandling/nsexceptionhandler/exceptionhangingmask()"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()":{"abstract":[{"text":"Returns a bit mask representing the types of exceptions monitored by the receiver","type":"text"},{"text":" ","type":"text"},{"text":"and its handling and logging behavior.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exceptionHandlingMask","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"exceptionHandlingMask","kind":"identifier"}],"type":"topic","url":"/documentation/exceptionhandling/nsexceptionhandler/exceptionhandlingmask()","title":"exceptionHandlingMask()"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)":{"url":"/documentation/exceptionhandling/nsexceptionhandler/setexceptionhangingmask(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setExceptionHangingMask:"}],"abstract":[{"text":"Sets the bit mask of constants specifying the types of exceptions that will halt","type":"text"},{"type":"text","text":" "},{"type":"text","text":"execution for debugging."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setExceptionHangingMask","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"setExceptionHangingMask(_:)"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","kind":"technologies","role":"overview","type":"topic"},"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler":{"identifier":"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler","title":"NSSetUncaughtExceptionHandler(_:)","url":"/documentation/foundation/1409609-nssetuncaughtexceptionhandler","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Changes the top-level error handler."}],"type":"topic","fragments":[{"kind":"text","text":"func "},{"text":"NSSetUncaughtExceptionHandler","kind":"identifier"},{"text":"(((NSException) -> Void)?)","kind":"text"}]},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling":{"url":"/documentation/exceptionhandling","abstract":[{"text":"Monitor and debug exceptional conditions in code.","type":"text"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling","title":"Exception Handling","kind":"symbol","role":"collection","type":"topic"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants":{"url":"/documentation/exceptionhandling/logging-and-handling-constants","kind":"article","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"Use one or more of the following constants in the parameter of "},{"type":"reference","identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)","isActive":true},{"type":"text","text":" "},{"type":"text","text":"to specify the types of exceptions that the exception handler should monitor and"},{"type":"text","text":" "},{"type":"text","text":"whether it should handle or log them."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants","title":"Logging and Handling Constants"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"13.0","beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"10.0","beta":false,"deprecated":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"op":"replace","value":"exceptionHandlingMask","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"exceptionHandlingMask","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Exception-Handling/documentation/ExceptionHandling","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Getting-and-setting-exception-masks","generated":true,"identifiers":["doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)"],"title":"Getting and setting exception masks"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"exceptionHandlingMask"},{"kind":"text","text":";"}]}]}},{"path":"/primaryContentSections/1","value":{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"text":"A bit mask composed of one or more constants specifying the types of exceptions monitored","type":"text"},{"text":" ","type":"text"},{"text":"and whether they are handled or logged (or both). See ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants","type":"reference"},{"text":" ","type":"text"},{"text":"for information about the constants.","type":"text"}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/title","op":"replace","value":"NSExceptionHandler"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/fragments","op":"replace","value":[{"kind":"identifier","text":"NSExceptionHandler"}]},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/navigatorTitle","op":"replace","value":[{"text":"NSExceptionHandler","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/title","op":"replace","value":"setExceptionHandlingMask:"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setExceptionHandlingMask:"}]},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHangingMask()/title","op":"replace","value":"exceptionHangingMask"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHangingMask()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"exceptionHangingMask","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHandlingMask()/title","op":"replace","value":"exceptionHandlingMask"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHandlingMask()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"exceptionHandlingMask","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/title","op":"replace","value":"setExceptionHangingMask:"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setExceptionHangingMask:"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~11409609-nssetuncaughtexceptionhandler/title","op":"replace","value":"NSSetUncaughtExceptionHandler"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}