{"abstract":[{"text":"Sets the bit mask of constants specifying the types of exceptions that will halt","type":"text"},{"text":" ","type":"text"},{"text":"execution for debugging.","type":"text"}],"identifier":{"url":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Exception-Handling/documentation/ExceptionHandling","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)"],"generated":true,"title":"Getting and setting exception masks","anchor":"Getting-and-setting-exception-masks"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/exceptionhandling/nsexceptionhandler/setexceptionhangingmask(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/exceptionhandling/nsexceptionhandler/setexceptionhangingmask(_:)"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setExceptionHangingMask"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aMask"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A bit mask composed of one or more constants specifying the types of exceptions that"},{"type":"text","text":" "},{"type":"text","text":"will halt execution for debugging. You specify multiple constants by performing a"},{"type":"text","text":" "},{"type":"text","text":"bitwise-OR operation. See "},{"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants","type":"reference","isActive":true},{"text":" for","type":"text"},{"text":" ","type":"text"},{"text":"information about the constants.","type":"text"}],"type":"paragraph"}],"name":"aMask"}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"Exception Handling"}],"platforms":[{"name":"Mac Catalyst","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","introducedAt":"10.0","deprecated":false,"unavailable":false,"beta":false}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"setExceptionHangingMask:","kind":"identifier"}],"title":"setExceptionHangingMask(_:)","externalID":"c:objc(cs)NSExceptionHandler(im)setExceptionHangingMask:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setExceptionHangingMask","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"references":{"doc://com.externally.resolved.symbol/s:Si":{"identifier":"doc://com.externally.resolved.symbol/s:Si","title":"Int","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"kind":"symbol","url":"/documentation/Swift/Int","type":"topic","abstract":[{"type":"text","text":"A signed integer value type."}],"role":"symbol"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling":{"url":"/documentation/exceptionhandling","abstract":[{"text":"Monitor and debug exceptional conditions in code.","type":"text"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling","title":"Exception Handling","kind":"symbol","role":"collection","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","kind":"technologies","role":"overview","type":"topic"},"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler":{"identifier":"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler","title":"NSSetUncaughtExceptionHandler(_:)","url":"/documentation/foundation/1409609-nssetuncaughtexceptionhandler","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Changes the top-level error handler."}],"type":"topic","fragments":[{"kind":"text","text":"func "},{"text":"NSSetUncaughtExceptionHandler","kind":"identifier"},{"text":"(((NSException) -> Void)?)","kind":"text"}]},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()":{"abstract":[{"text":"Returns a bit mask representing the types of exceptions monitored by the receiver","type":"text"},{"text":" ","type":"text"},{"text":"and its handling and logging behavior.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exceptionHandlingMask","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"exceptionHandlingMask","kind":"identifier"}],"type":"topic","url":"/documentation/exceptionhandling/nsexceptionhandler/exceptionhandlingmask()","title":"exceptionHandlingMask()"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)":{"url":"/documentation/exceptionhandling/nsexceptionhandler/setexceptionhangingmask(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setExceptionHangingMask:"}],"abstract":[{"text":"Sets the bit mask of constants specifying the types of exceptions that will halt","type":"text"},{"type":"text","text":" "},{"type":"text","text":"execution for debugging."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setExceptionHangingMask","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"setExceptionHangingMask(_:)"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants":{"url":"/documentation/exceptionhandling/system-hang-constants","kind":"article","type":"topic","role":"collectionGroup","abstract":[{"text":"Use one or more of the following constants in the parameter of ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)","type":"reference"},{"type":"text","text":" "},{"type":"text","text":"to specify the types of exceptions that cause the exception to halt execution so"},{"type":"text","text":" "},{"type":"text","text":"a debugger can be attached."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants","title":"System Hang Constants"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionHangingMask"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()","navigatorTitle":[{"kind":"identifier","text":"exceptionHangingMask"}],"title":"exceptionHangingMask()","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Returns a bit mask representing the types of exceptions that will halt execution"},{"type":"text","text":" "},{"text":"for debugging.","type":"text"}],"url":"/documentation/exceptionhandling/nsexceptionhandler/exceptionhangingmask()"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler":{"kind":"symbol","url":"/documentation/exceptionhandling/nsexceptionhandler","role":"symbol","type":"topic","title":"NSExceptionHandler","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSExceptionHandler","kind":"identifier"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler","abstract":[{"text":"The ","type":"text"},{"code":"NSExceptionHandler","type":"codeVoice"},{"text":" class provides facilities for monitoring and debugging exceptional","type":"text"},{"type":"text","text":" "},{"type":"text","text":"conditions in Objective-C programs. It works by installing a special uncaught exception"},{"type":"text","text":" "},{"type":"text","text":"handler via the  "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler"},{"type":"text","text":" "},{"text":"function. Consequently, to use the services of ","type":"text"},{"code":"NSExceptionHandler","type":"codeVoice"},{"text":", you must not","type":"text"},{"text":" ","type":"text"},{"text":"install your own custom uncaught exception handler.","type":"text"}],"navigatorTitle":[{"text":"NSExceptionHandler","kind":"identifier"}]},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)":{"url":"/documentation/exceptionhandling/nsexceptionhandler/setexceptionhandlingmask(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"setExceptionHandlingMask:","kind":"identifier"}],"abstract":[{"text":"Sets the bit mask of constants specifying the types of exceptions monitored by the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"receiver and its handling and logging behavior."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setExceptionHandlingMask"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setExceptionHandlingMask(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"Mac Catalyst","introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false},{"deprecated":false,"beta":false,"name":"macOS","unavailable":false,"introducedAt":"10.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"setExceptionHangingMask:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setExceptionHangingMask:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Exception-Handling/documentation/ExceptionHandling","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"anchor":"Getting-and-setting-exception-masks","identifiers":["doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHandlingMask()","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/exceptionHangingMask()","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)"],"title":"Getting and setting exception masks"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setExceptionHangingMask:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"aMask","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A bit mask composed of one or more constants specifying the types of exceptions that"},{"type":"text","text":" "},{"type":"text","text":"will halt execution for debugging. You specify multiple constants by performing a"},{"type":"text","text":" "},{"type":"text","text":"bitwise-OR operation. See "},{"type":"reference","identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants","isActive":true},{"type":"text","text":" for"},{"type":"text","text":" "},{"type":"text","text":"information about the constants."}],"type":"paragraph"}],"name":"aMask"}]},"path":"/primaryContentSections/1","op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~11409609-nssetuncaughtexceptionhandler/title","value":"NSSetUncaughtExceptionHandler","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHandlingMask()/title","value":"exceptionHandlingMask","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHandlingMask()/fragments","value":[{"text":"- ","kind":"text"},{"text":"exceptionHandlingMask","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/title","value":"setExceptionHangingMask:","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setExceptionHangingMask:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHangingMask()/title","value":"exceptionHangingMask","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1exceptionHangingMask()/fragments","value":[{"text":"- ","kind":"text"},{"text":"exceptionHangingMask","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/title","value":"NSExceptionHandler","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/fragments","value":[{"text":"NSExceptionHandler","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/navigatorTitle","value":[{"kind":"identifier","text":"NSExceptionHandler"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/title","value":"setExceptionHandlingMask:"},{"op":"replace","path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setExceptionHandlingMask:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}