{
  "abstract": [
    {
      "text": "Invoked when the user finishes editing an event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkitui/documentation/EventKitUI",
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate/eventEditViewController(_:didCompleteWith:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)EKEventEditViewDelegate(im)eventEditViewController:didCompleteWithAction:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "eventEditViewController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)EKEventEditViewController",
        "text": "EKEventEditViewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didCompleteWith"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@EKEventEditViewAction",
        "text": "EKEventEditViewAction"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "EventKit UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "eventEditViewController:didCompleteWithAction:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "eventEditViewController(_:didCompleteWith:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "eventEditViewController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)EKEventEditViewController",
              "text": "EKEventEditViewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didCompleteWith"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "action"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@EKEventEditViewAction",
              "text": "EKEventEditViewAction"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The edit view controller presenting the event.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "controller"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The action the user took to end editing.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "action"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this method to dismiss the modal event edit view controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI": {
      "abstract": [
        {
          "text": "Display an interface for viewing, selecting, and editing calendar events and reminders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit UI",
      "type": "topic",
      "url": "/documentation/eventkitui"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction": {
      "abstract": [
        {
          "text": "The action taken by the user after editing an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventEditViewAction"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewAction"
        }
      ],
      "role": "symbol",
      "title": "EKEventEditViewAction",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewaction"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController": {
      "abstract": [
        {
          "text": "A view controller for creating, editing, and deleting calendar events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventEditViewController"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewController"
        }
      ],
      "role": "symbol",
      "title": "EKEventEditViewController",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewcontroller"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate": {
      "abstract": [
        {
          "text": "A notification sent to the delegate when the user finishes editing an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventEditViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "EKEventEditViewDelegate",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewdelegate"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate/eventEditViewController(_:didCompleteWith:)": {
      "abstract": [
        {
          "text": "Invoked when the user finishes editing an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventEditViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKEventEditViewController",
          "text": "EKEventEditViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didCompleteWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKEventEditViewAction",
          "text": "EKEventEditViewAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate/eventEditViewController(_:didCompleteWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eventEditViewController:didCompleteWithAction:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "eventEditViewController(_:didCompleteWith:)",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewdelegate/eventeditviewcontroller(_:didcompletewith:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Finishing-an-Edit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction"
      ],
      "title": "Finishing an Edit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "eventEditViewController:didCompleteWithAction:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "eventEditViewController:didCompleteWithAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkitui/documentation/EventKitUI",
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Finishing-an-Edit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction"
              ],
              "title": "Finishing an Edit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "eventEditViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)EKEventEditViewController",
                    "text": "EKEventEditViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "controller"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didCompleteWithAction:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@EKEventEditViewAction",
                    "text": "EKEventEditViewAction"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "action"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The edit view controller presenting the event.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "controller"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The action the user took to end editing.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "action"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewDelegate~1eventEditViewController(_:didCompleteWith:)/title",
          "value": "eventEditViewController:didCompleteWithAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewDelegate~1eventEditViewController(_:didCompleteWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "eventEditViewController:didCompleteWithAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction/title",
          "value": "EKEventEditViewAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController/title",
          "value": "EKEventEditViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewDelegate/title",
          "value": "EKEventEditViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkitui/ekeventeditviewdelegate/eventeditviewcontroller(_:didcompletewith:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkitui/ekeventeditviewdelegate/eventeditviewcontroller(_:didcompletewith:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
