{
  "abstract": [
    {
      "text": "Indicates that the browser has completed configuring the specified accessory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowserDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowserDelegate/accessoryBrowser(_:didFinishConfiguringAccessory:with:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)EAWiFiUnconfiguredAccessoryBrowserDelegate(im)accessoryBrowser:didFinishConfiguringAccessory:withStatus:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessoryBrowser"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)EAWiFiUnconfiguredAccessoryBrowser",
        "text": "EAWiFiUnconfiguredAccessoryBrowser"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didFinishConfiguringAccessory"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)EAWiFiUnconfiguredAccessory",
        "text": "EAWiFiUnconfiguredAccessory"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@EAWiFiUnconfiguredAccessoryConfigurationStatus",
        "text": "EAWiFiUnconfiguredAccessoryConfigurationStatus"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "External Accessory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accessoryBrowser:didFinishConfiguringAccessory:withStatus:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessoryBrowser(_:didFinishConfiguringAccessory:with:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessoryBrowser"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "browser"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowser",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)EAWiFiUnconfiguredAccessoryBrowser",
              "text": "EAWiFiUnconfiguredAccessoryBrowser"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didFinishConfiguringAccessory"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "accessory"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessory",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)EAWiFiUnconfiguredAccessory",
              "text": "EAWiFiUnconfiguredAccessory"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "status"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryConfigurationStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@EAWiFiUnconfiguredAccessoryConfigurationStatus",
              "text": "EAWiFiUnconfiguredAccessoryConfigurationStatus"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The instance of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowser",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that is generating the event.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "browser"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessory",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object whose configuration process has completed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "accessory"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The status of the completed configuration process. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryConfigurationStatus",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for possible values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "status"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called when the system-provided configuration view has been dismissed, revealing the part of the app’s user interface that was visible before the configuration process began. If the configuration was successful, the app can begin communicating with the accessory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory": {
      "abstract": [
        {
          "text": "Communicate with accessories that connect to a device with the Apple Lightning connector, or with Bluetooth wireless technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory",
      "kind": "symbol",
      "role": "collection",
      "title": "External Accessory",
      "type": "topic",
      "url": "/documentation/externalaccessory"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessory": {
      "abstract": [
        {
          "text": "An object that provides information about an unconfigured MFi Wireless Accessory Configuration accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAWiFiUnconfiguredAccessory"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAWiFiUnconfiguredAccessory"
        }
      ],
      "role": "symbol",
      "title": "EAWiFiUnconfiguredAccessory",
      "type": "topic",
      "url": "/documentation/externalaccessory/eawifiunconfiguredaccessory"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowser": {
      "abstract": [
        {
          "text": "An object you use to scan for wireless accessories and configure them for use with the user’s app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAWiFiUnconfiguredAccessoryBrowser"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAWiFiUnconfiguredAccessoryBrowser"
        }
      ],
      "role": "symbol",
      "title": "EAWiFiUnconfiguredAccessoryBrowser",
      "type": "topic",
      "url": "/documentation/externalaccessory/eawifiunconfiguredaccessorybrowser"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowserDelegate": {
      "abstract": [
        {
          "text": "A protocol you use to manage the search and configuration processes for an unconfigured accessory browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAWiFiUnconfiguredAccessoryBrowserDelegate"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowserDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAWiFiUnconfiguredAccessoryBrowserDelegate"
        }
      ],
      "role": "symbol",
      "title": "EAWiFiUnconfiguredAccessoryBrowserDelegate",
      "type": "topic",
      "url": "/documentation/externalaccessory/eawifiunconfiguredaccessorybrowserdelegate"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowserDelegate/accessoryBrowser(_:didFinishConfiguringAccessory:with:)": {
      "abstract": [
        {
          "text": "Indicates that the browser has completed configuring the specified accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryBrowser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EAWiFiUnconfiguredAccessoryBrowser",
          "text": "EAWiFiUnconfiguredAccessoryBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishConfiguringAccessory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EAWiFiUnconfiguredAccessory",
          "text": "EAWiFiUnconfiguredAccessory"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EAWiFiUnconfiguredAccessoryConfigurationStatus",
          "text": "EAWiFiUnconfiguredAccessoryConfigurationStatus"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowserDelegate/accessoryBrowser(_:didFinishConfiguringAccessory:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryBrowser:didFinishConfiguringAccessory:withStatus:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessoryBrowser(_:didFinishConfiguringAccessory:with:)",
      "type": "topic",
      "url": "/documentation/externalaccessory/eawifiunconfiguredaccessorybrowserdelegate/accessorybrowser(_:didfinishconfiguringaccessory:with:)"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryConfigurationStatus": {
      "abstract": [
        {
          "text": "Values that represent the state of the configuration process for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessory",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAWiFiUnconfiguredAccessoryConfigurationStatus"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryConfigurationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAWiFiUnconfiguredAccessoryConfigurationStatus"
        }
      ],
      "role": "symbol",
      "title": "EAWiFiUnconfiguredAccessoryConfigurationStatus",
      "type": "topic",
      "url": "/documentation/externalaccessory/eawifiunconfiguredaccessoryconfigurationstatus"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Updates-About-the-Configuration-Process",
      "generated": true,
      "identifiers": [
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryConfigurationStatus"
      ],
      "title": "Getting Updates About the Configuration Process"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "accessoryBrowser:didFinishConfiguringAccessory:withStatus:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessoryBrowser:didFinishConfiguringAccessory:withStatus:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowserDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Updates-About-the-Configuration-Process",
              "generated": true,
              "identifiers": [
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryConfigurationStatus"
              ],
              "title": "Getting Updates About the Configuration Process"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessoryBrowser:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowser",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)EAWiFiUnconfiguredAccessoryBrowser",
                    "text": "EAWiFiUnconfiguredAccessoryBrowser"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "browser"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didFinishConfiguringAccessory:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessory",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)EAWiFiUnconfiguredAccessory",
                    "text": "EAWiFiUnconfiguredAccessory"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "accessory"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withStatus:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryConfigurationStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@EAWiFiUnconfiguredAccessoryConfigurationStatus",
                    "text": "EAWiFiUnconfiguredAccessoryConfigurationStatus"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "status"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The instance of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryBrowser",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that is generating the event.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "browser"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessory",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object whose configuration process has completed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "accessory"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The status of the completed configuration process. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAWiFiUnconfiguredAccessoryConfigurationStatus",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for possible values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "status"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryConfigurationStatus/title",
          "value": "EAWiFiUnconfiguredAccessoryConfigurationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryConfigurationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAWiFiUnconfiguredAccessoryConfigurationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryConfigurationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAWiFiUnconfiguredAccessoryConfigurationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryBrowser/title",
          "value": "EAWiFiUnconfiguredAccessoryBrowser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryBrowser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAWiFiUnconfiguredAccessoryBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryBrowser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAWiFiUnconfiguredAccessoryBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryBrowserDelegate~1accessoryBrowser(_:didFinishConfiguringAccessory:with:)/title",
          "value": "accessoryBrowser:didFinishConfiguringAccessory:withStatus:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryBrowserDelegate~1accessoryBrowser(_:didFinishConfiguringAccessory:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessoryBrowser:didFinishConfiguringAccessory:withStatus:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessory/title",
          "value": "EAWiFiUnconfiguredAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAWiFiUnconfiguredAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAWiFiUnconfiguredAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryBrowserDelegate/title",
          "value": "EAWiFiUnconfiguredAccessoryBrowserDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryBrowserDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EAWiFiUnconfiguredAccessoryBrowserDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAWiFiUnconfiguredAccessoryBrowserDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EAWiFiUnconfiguredAccessoryBrowserDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/externalaccessory/eawifiunconfiguredaccessorybrowserdelegate/accessorybrowser(_:didfinishconfiguringaccessory:with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/externalaccessory/eawifiunconfiguredaccessorybrowserdelegate/accessorybrowser(_:didfinishconfiguringaccessory:with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
