{
  "abstract": [
    {
      "text": "Identifies the sound’s output device",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSound"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSound/playbackDeviceIdentifier-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSSound(py)playbackDeviceIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "playbackDeviceIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSSound",
        "text": "NSSound"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSSoundPlaybackDeviceIdentifier",
        "text": "PlaybackDeviceIdentifier"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "playbackDeviceIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "playbackDeviceIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "playbackDeviceIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSound",
              "text": "NSSound"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound/PlaybackDeviceIdentifier-swift.typealias",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSSoundPlaybackDeviceIdentifier",
              "text": "PlaybackDeviceIdentifier"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSound": {
      "abstract": [
        {
          "text": "A simple interface for loading and playing audio files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSound"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSound"
        }
      ],
      "role": "symbol",
      "title": "NSSound",
      "type": "topic",
      "url": "/documentation/appkit/nssound"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSound/Name-swift.typealias": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound/Name-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "role": "symbol",
      "title": "NSSound.Name",
      "type": "topic",
      "url": "/documentation/appkit/nssound/name-swift.typealias"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSound/PlaybackDeviceIdentifier-swift.typealias": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PlaybackDeviceIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound/PlaybackDeviceIdentifier-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PlaybackDeviceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSSound.PlaybackDeviceIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nssound/playbackdeviceidentifier-swift.typealias"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSound/currentTime": {
      "abstract": [
        {
          "text": "The sound’s playback progress, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound/currentTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentTime"
        }
      ],
      "role": "symbol",
      "title": "currentTime",
      "type": "topic",
      "url": "/documentation/appkit/nssound/currenttime"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSound/loops": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the sound restarts playback when it reaches the end of its content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound/loops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loops"
        }
      ],
      "role": "symbol",
      "title": "loops",
      "type": "topic",
      "url": "/documentation/appkit/nssound/loops"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSound/name-swift.property": {
      "abstract": [
        {
          "text": "The name assigned to the sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSound",
          "text": "NSSound"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSoundName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound/name-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/appkit/nssound/name-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSound/playbackDeviceIdentifier-swift.property": {
      "abstract": [
        {
          "text": "Identifies the sound’s output device",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackDeviceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSound",
          "text": "NSSound"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSoundPlaybackDeviceIdentifier",
          "text": "PlaybackDeviceIdentifier"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound/playbackDeviceIdentifier-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackDeviceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "playbackDeviceIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nssound/playbackdeviceidentifier-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSound/setName(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSound",
          "text": "NSSound"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSoundName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound/setName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setName:"
        }
      ],
      "role": "symbol",
      "title": "setName(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nssound/setname(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSound/volume": {
      "abstract": [
        {
          "text": "The volume of the sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "volume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound/volume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "volume"
        }
      ],
      "role": "symbol",
      "title": "volume",
      "type": "topic",
      "url": "/documentation/appkit/nssound/volume"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Sounds",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSound/name-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSSound/Name-swift.typealias",
        "doc://com.apple.appkit/documentation/AppKit/NSSound/setName(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSound/volume",
        "doc://com.apple.appkit/documentation/AppKit/NSSound/currentTime",
        "doc://com.apple.appkit/documentation/AppKit/NSSound/loops",
        "doc://com.apple.appkit/documentation/AppKit/NSSound/PlaybackDeviceIdentifier-swift.typealias"
      ],
      "title": "Configuring Sounds"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "playbackDeviceIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackDeviceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSound"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Sounds",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSound/name-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSSound/Name-swift.typealias",
                "doc://com.apple.appkit/documentation/AppKit/NSSound/setName(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSound/volume",
                "doc://com.apple.appkit/documentation/AppKit/NSSound/currentTime",
                "doc://com.apple.appkit/documentation/AppKit/NSSound/loops",
                "doc://com.apple.appkit/documentation/AppKit/NSSound/PlaybackDeviceIdentifier-swift.typealias"
              ],
              "title": "Configuring Sounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSound/PlaybackDeviceIdentifier-swift.typealias",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSSoundPlaybackDeviceIdentifier",
                    "text": "NSSoundPlaybackDeviceIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "playbackDeviceIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1currentTime/title",
          "value": "currentTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1currentTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1setName(_:)/title",
          "value": "setName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1setName(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound/title",
          "value": "NSSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1loops/title",
          "value": "loops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1loops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "loops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1playbackDeviceIdentifier-swift.property/title",
          "value": "playbackDeviceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1playbackDeviceIdentifier-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackDeviceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1PlaybackDeviceIdentifier-swift.typealias/title",
          "value": "NSSoundPlaybackDeviceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1PlaybackDeviceIdentifier-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSoundPlaybackDeviceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1PlaybackDeviceIdentifier-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSoundPlaybackDeviceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1name-swift.property/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1name-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1Name-swift.typealias/title",
          "value": "NSSoundName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1Name-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSoundName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1Name-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSoundName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1volume/title",
          "value": "volume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSound~1volume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "volume"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssound/playbackdeviceidentifier-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssound/playbackdeviceidentifier-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
