{
  "abstract": [
    {
      "text": "The operation failed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/failed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ASExtensionErrorCode@ASExtensionErrorCodeFailed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failed"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ASExtensionErrorCodeFailed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ASExtensionError.Code.failed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failed"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/upgrading-account-security-with-an-account-authentication-modification-extension"
      ]
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError": {
      "abstract": [
        {
          "text": "A credential provider extension error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASExtensionError"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASExtensionError"
        }
      ],
      "role": "symbol",
      "title": "ASExtensionError",
      "type": "topic",
      "url": "/documentation/authenticationservices/asextensionerror"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code": {
      "abstract": [
        {
          "text": "The codes for a credential provider extension error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ASExtensionError.Code",
      "type": "topic",
      "url": "/documentation/authenticationservices/asextensionerror/code"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/credentialIdentityNotFound": {
      "abstract": [
        {
          "text": "The credential identity was not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credentialIdentityNotFound"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/credentialIdentityNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASExtensionErrorCodeCredentialIdentityNotFound"
        }
      ],
      "role": "symbol",
      "title": "ASExtensionError.Code.credentialIdentityNotFound",
      "type": "topic",
      "url": "/documentation/authenticationservices/asextensionerror/code/credentialidentitynotfound"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/failed": {
      "abstract": [
        {
          "text": "The operation failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASExtensionErrorCodeFailed"
        }
      ],
      "role": "symbol",
      "title": "ASExtensionError.Code.failed",
      "type": "topic",
      "url": "/documentation/authenticationservices/asextensionerror/code/failed"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userCanceled": {
      "abstract": [
        {
          "text": "The user canceled the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCanceled"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASExtensionErrorCodeUserCanceled"
        }
      ],
      "role": "symbol",
      "title": "ASExtensionError.Code.userCanceled",
      "type": "topic",
      "url": "/documentation/authenticationservices/asextensionerror/code/usercanceled"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userInteractionRequired": {
      "abstract": [
        {
          "text": "User interaction is required.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInteractionRequired"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userInteractionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASExtensionErrorCodeUserInteractionRequired"
        }
      ],
      "role": "symbol",
      "title": "ASExtensionError.Code.userInteractionRequired",
      "type": "topic",
      "url": "/documentation/authenticationservices/asextensionerror/code/userinteractionrequired"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/upgrading-account-security-with-an-account-authentication-modification-extension": {
      "abstract": [
        {
          "text": "Automatically and transparently convert accounts to Sign in with Apple or to use strong passwords for improved security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/upgrading-account-security-with-an-account-authentication-modification-extension",
      "kind": "article",
      "role": "article",
      "title": "Upgrading Account Security With an Account Authentication Modification Extension",
      "type": "topic",
      "url": "/documentation/authenticationservices/upgrading-account-security-with-an-account-authentication-modification-extension"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/credentialIdentityNotFound",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userCanceled",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userInteractionRequired"
      ],
      "title": "Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ASExtensionErrorCodeFailed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASExtensionErrorCodeFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/credentialIdentityNotFound",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userCanceled",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASExtensionError/Code/userInteractionRequired"
              ],
              "title": "Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ASExtensionErrorCodeFailed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code~1userCanceled/title",
          "value": "ASExtensionErrorCodeUserCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code~1userCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASExtensionErrorCodeUserCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code~1failed/title",
          "value": "ASExtensionErrorCodeFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASExtensionErrorCodeFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code~1userInteractionRequired/title",
          "value": "ASExtensionErrorCodeUserInteractionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code~1userInteractionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASExtensionErrorCodeUserInteractionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code/title",
          "value": "ASExtensionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code~1credentialIdentityNotFound/title",
          "value": "ASExtensionErrorCodeCredentialIdentityNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASExtensionError~1Code~1credentialIdentityNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASExtensionErrorCodeCredentialIdentityNotFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/asextensionerror/code/failed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/asextensionerror/code/failed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
