{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mDeviceID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioDriverPlugInHostInfo@FI@mDeviceID",
    "fragments": [
      {
        "kind": "identifier",
        "text": "mDeviceID"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mDeviceID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "mDeviceID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioDeviceID",
              "text": "AudioDeviceID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mDeviceID"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceID"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInHostInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInHostInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginhostinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mDeviceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mDeviceID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mDeviceID",
      "kind": "symbol",
      "role": "symbol",
      "title": "mDeviceID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginhostinfo/mdeviceid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mDevicePropertyChangedProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mDevicePropertyChangedProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mDevicePropertyChangedProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "mDevicePropertyChangedProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginhostinfo/mdevicepropertychangedproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mIOAudioDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mIOAudioDevice"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mIOAudioDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "mIOAudioDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginhostinfo/mioaudiodevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mIOAudioEngine": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mIOAudioEngine"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mIOAudioEngine",
      "kind": "symbol",
      "role": "symbol",
      "title": "mIOAudioEngine",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginhostinfo/mioaudioengine"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mStreamPropertyChangedProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mStreamPropertyChangedProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mStreamPropertyChangedProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "mStreamPropertyChangedProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginhostinfo/mstreampropertychangedproc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mDevicePropertyChangedProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mIOAudioDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mIOAudioEngine",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo/mStreamPropertyChangedProc"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/title",
          "value": "AudioDeviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audiodriverpluginhostinfo/mdeviceid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
