{
  "abstract": [
    {
      "text": "The highness or lowness of the tone (fundamental frequency) in each frame of a transcription segment, expressed as a logarithm.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.speech/documentation/Speech",
        "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/pitch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFVoiceAnalytics(py)pitch",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pitch"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SFAcousticFeature",
        "text": "SFAcousticFeature"
      }
    ],
    "modules": [
      {
        "name": "Speech"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "pitch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "pitch"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pitch"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/SFAcousticFeature",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SFAcousticFeature",
              "text": "SFAcousticFeature"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value is a logarithm (base ",
              "type": "text"
            },
            {
              "code": "e",
              "type": "codeVoice"
            },
            {
              "text": ") of the normalized pitch estimate for each frame.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.speech/documentation/Speech": {
      "abstract": [
        {
          "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech",
      "kind": "symbol",
      "role": "collection",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/speech"
    },
    "doc://com.apple.speech/documentation/Speech/SFAcousticFeature": {
      "abstract": [
        {
          "text": "The value of a voice analysis metric.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAcousticFeature"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFAcousticFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAcousticFeature"
        }
      ],
      "role": "symbol",
      "title": "SFAcousticFeature",
      "type": "topic",
      "url": "/documentation/speech/sfacousticfeature"
    },
    "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics": {
      "abstract": [
        {
          "text": "A collection of vocal analysis metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFVoiceAnalytics"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFVoiceAnalytics"
        }
      ],
      "role": "symbol",
      "title": "SFVoiceAnalytics",
      "type": "topic",
      "url": "/documentation/speech/sfvoiceanalytics"
    },
    "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/jitter": {
      "abstract": [
        {
          "text": "The variation in pitch in each frame of a transcription segment, expressed as a percentage of the frame’s fundamental frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFAcousticFeature",
          "text": "SFAcousticFeature"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/jitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jitter"
        }
      ],
      "role": "symbol",
      "title": "jitter",
      "type": "topic",
      "url": "/documentation/speech/sfvoiceanalytics/jitter"
    },
    "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/pitch": {
      "abstract": [
        {
          "text": "The highness or lowness of the tone (fundamental frequency) in each frame of a transcription segment, expressed as a logarithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFAcousticFeature",
          "text": "SFAcousticFeature"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/pitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pitch"
        }
      ],
      "role": "symbol",
      "title": "pitch",
      "type": "topic",
      "url": "/documentation/speech/sfvoiceanalytics/pitch"
    },
    "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/shimmer": {
      "abstract": [
        {
          "text": "The variation in vocal volume stability (amplitude) in each frame of a transcription segment, expressed in decibels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shimmer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFAcousticFeature",
          "text": "SFAcousticFeature"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/shimmer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shimmer"
        }
      ],
      "role": "symbol",
      "title": "shimmer",
      "type": "topic",
      "url": "/documentation/speech/sfvoiceanalytics/shimmer"
    },
    "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/voicing": {
      "abstract": [
        {
          "text": "The likelihood of a voice in each frame of a transcription segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voicing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFAcousticFeature",
          "text": "SFAcousticFeature"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/voicing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "voicing"
        }
      ],
      "role": "symbol",
      "title": "voicing",
      "type": "topic",
      "url": "/documentation/speech/sfvoiceanalytics/voicing"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Analyzing-voice",
      "generated": true,
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFAcousticFeature",
        "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/voicing",
        "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/jitter",
        "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/shimmer"
      ],
      "title": "Analyzing voice"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "pitch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.speech/documentation/Speech",
                "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Analyzing-voice",
              "generated": true,
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFAcousticFeature",
                "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/voicing",
                "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/jitter",
                "doc://com.apple.speech/documentation/Speech/SFVoiceAnalytics/shimmer"
              ],
              "title": "Analyzing voice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.speech/documentation/Speech/SFAcousticFeature",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SFAcousticFeature",
                    "text": "SFAcousticFeature"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "pitch"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics/title",
          "value": "SFVoiceAnalytics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFVoiceAnalytics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFVoiceAnalytics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics~1voicing/title",
          "value": "voicing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics~1voicing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "voicing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics~1shimmer/title",
          "value": "shimmer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics~1shimmer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shimmer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics~1pitch/title",
          "value": "pitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics~1pitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFAcousticFeature/title",
          "value": "SFAcousticFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFAcousticFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAcousticFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFAcousticFeature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAcousticFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics~1jitter/title",
          "value": "jitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFVoiceAnalytics~1jitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jitter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/speech/sfvoiceanalytics/pitch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/speech/sfvoiceanalytics/pitch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
