{
  "abstract": [
    {
      "text": "Creates a search suggestion with the specified attributed label.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UISearchSuggestionItem(im)initWithLocalizedAttributedSuggestion:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "localizedAttributedSuggestion"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSAttributedString",
        "text": "NSAttributedString"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithLocalizedAttributedSuggestion:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(localizedAttributedSuggestion:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "localizedAttributedSuggestion"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "suggestion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSAttributedString",
              "text": "NSAttributedString"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An attributed label for the suggestion, usually the search term the suggestion represents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "suggestion"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem": {
      "abstract": [
        {
          "text": "A selectable search parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchSuggestionItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchSuggestionItem"
        }
      ],
      "role": "symbol",
      "title": "UISearchSuggestionItem",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedAttributedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedAttributedSuggestion:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedAttributedSuggestion:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedattributedsuggestion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label and accessibility description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedAttributedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedAttributedSuggestion:localizedDescription:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedAttributedSuggestion:localizedDescription:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedattributedsuggestion:localizeddescription:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:iconImage:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label, accessibility description, and image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedAttributedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "iconImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:iconImage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedAttributedSuggestion:localizedDescription:iconImage:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedAttributedSuggestion:localizedDescription:iconImage:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedattributedsuggestion:localizeddescription:iconimage:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedSuggestion:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedSuggestion:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedsuggestion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified label and accessibility description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedSuggestion:localizedDescription:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedSuggestion:localizedDescription:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedsuggestion:localizeddescription:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:iconImage:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified text and image attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "iconImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:iconImage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedSuggestion:localizedDescription:iconImage:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedSuggestion:localizedDescription:iconImage:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedsuggestion:localizeddescription:iconimage:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedAttributedSuggestion:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedattributedsuggestion:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label and accessibility description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:descriptionString:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:descriptionString:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedAttributedSuggestion:descriptionString:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedattributedsuggestion:descriptionstring:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label, accessibility description, and image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedattributedsuggestion:descriptionstring:iconimage:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedSuggestion:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedsuggestion:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified label and accessibility description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:descriptionString:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:descriptionString:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedSuggestion:descriptionString:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedsuggestion:descriptionstring:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:iconImage:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified text and image attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:descriptionString:iconImage:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:iconImage:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:descriptionString:iconImage:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedSuggestion:descriptionString:iconImage:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedsuggestion:descriptionstring:iconimage:"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString": {
      "abstract": [
        {
          "text": "A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-search-suggestion",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:iconImage:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:iconImage:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:)"
      ],
      "title": "Creating a search suggestion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithLocalizedAttributedSuggestion:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedAttributedSuggestion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-search-suggestion",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:iconImage:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:iconImage:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:iconImage:",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:"
              ],
              "title": "Creating a search suggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithLocalizedAttributedSuggestion:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSAttributedString",
                    "text": "NSAttributedString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "suggestion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An attributed label for the suggestion, usually the search term the suggestion represents.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "suggestion"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:localizedDescription:)/title",
          "value": "initWithLocalizedAttributedSuggestion:localizedDescription:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:localizedDescription:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedAttributedSuggestion:localizedDescription:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:)/title",
          "value": "initWithLocalizedSuggestion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedSuggestion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:localizedDescription:iconImage:)/title",
          "value": "initWithLocalizedSuggestion:localizedDescription:iconImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:localizedDescription:iconImage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedSuggestion:localizedDescription:iconImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:)/title",
          "value": "initWithLocalizedAttributedSuggestion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedAttributedSuggestion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem/title",
          "value": "UISearchSuggestionItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchSuggestionItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchSuggestionItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:localizedDescription:)/title",
          "value": "initWithLocalizedSuggestion:localizedDescription:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:localizedDescription:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedSuggestion:localizedDescription:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:localizedDescription:iconImage:)/title",
          "value": "initWithLocalizedAttributedSuggestion:localizedDescription:iconImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:localizedDescription:iconImage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedAttributedSuggestion:localizedDescription:iconImage:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisearchsuggestionitem/init(localizedattributedsuggestion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisearchsuggestionitem/init(localizedattributedsuggestion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
