{
  "abstract": [
    {
      "text": "Methods for monitoring drawing related changes in a canvas view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PKCanvasViewDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKCanvasViewDelegate"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKCanvasViewDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PKCanvasViewDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKCanvasViewDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIScrollViewDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIScrollViewDelegate",
              "text": "UIScrollViewDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement the methods of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol to monitor drawing events in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Specifically, determine the start- and end-of-event sequences using the currently selected tool, and determine when those events affect the drawn content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView": {
      "abstract": [
        {
          "text": "A view that captures Apple Pencil input and displays the rendered results in an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "role": "symbol",
      "title": "PKCanvasView",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/delegate": {
      "abstract": [
        {
          "text": "The object you use to respond to changes in the drawn content or with the selected tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PKCanvasViewDelegate",
          "text": "PKCanvasViewDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview/delegate"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate": {
      "abstract": [
        {
          "text": "Methods for monitoring drawing related changes in a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKCanvasViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKCanvasViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKCanvasViewDelegate",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasviewdelegate"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidBeginUsingTool(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user started a new drawing sequence with the currently selected tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canvasViewDidBeginUsingTool"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKCanvasView",
          "text": "PKCanvasView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidBeginUsingTool(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canvasViewDidBeginUsingTool:"
        }
      ],
      "role": "symbol",
      "title": "canvasViewDidBeginUsingTool(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasviewdelegate/canvasviewdidbeginusingtool(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidEndUsingTool(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user ended a drawing sequence with the tool they were using.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canvasViewDidEndUsingTool"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKCanvasView",
          "text": "PKCanvasView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidEndUsingTool(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canvasViewDidEndUsingTool:"
        }
      ],
      "role": "symbol",
      "title": "canvasViewDidEndUsingTool(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasviewdelegate/canvasviewdidendusingtool(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidFinishRendering(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the previously drawn content is ready to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canvasViewDidFinishRendering"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKCanvasView",
          "text": "PKCanvasView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidFinishRendering(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canvasViewDidFinishRendering:"
        }
      ],
      "role": "symbol",
      "title": "canvasViewDidFinishRendering(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasviewdelegate/canvasviewdidfinishrendering(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDrawingDidChange(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the contents of the current drawing changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canvasViewDrawingDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKCanvasView",
          "text": "PKCanvasView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDrawingDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canvasViewDrawingDidChange:"
        }
      ],
      "role": "symbol",
      "title": "canvasViewDrawingDidChange(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasviewdelegate/canvasviewdrawingdidchange(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIScrollViewDelegate": {
      "abstract": [
        {
          "text": "The interface for the delegate of a scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScrollViewDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIScrollViewDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIScrollViewDelegate",
      "type": "topic",
      "url": "/documentation/UIKit/UIScrollViewDelegate"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIScrollViewDelegate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-drawing-related-changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/delegate"
      ],
      "title": "Responding to drawing-related changes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-drawing-related-changes",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDrawingDidChange(_:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidFinishRendering(_:)"
      ],
      "title": "Responding to drawing-related changes"
    },
    {
      "anchor": "Responding-to-new-event-sequences",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidBeginUsingTool(_:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidEndUsingTool(_:)"
      ],
      "title": "Responding to new event sequences"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKCanvasViewDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pencilkit/documentation/PencilKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-drawing-related-changes",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDrawingDidChange(_:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidFinishRendering(_:)"
              ],
              "title": "Responding to drawing-related changes"
            },
            {
              "anchor": "Responding-to-new-event-sequences",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidBeginUsingTool(_:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDelegate/canvasViewDidEndUsingTool(_:)"
              ],
              "title": "Responding to new event sequences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                "doc://com.externally.resolved.symbol/c:objc(pl)UIScrollViewDelegate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-drawing-related-changes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/delegate"
              ],
              "title": "Responding to drawing-related changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKCanvasViewDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIScrollViewDelegate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)UIScrollViewDelegate",
                    "text": "UIScrollViewDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate~1canvasViewDidFinishRendering(_:)/title",
          "value": "canvasViewDidFinishRendering:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate~1canvasViewDidFinishRendering(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canvasViewDidFinishRendering:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIScrollViewDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIScrollViewDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/title",
          "value": "PKCanvasView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate~1canvasViewDidEndUsingTool(_:)/title",
          "value": "canvasViewDidEndUsingTool:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate~1canvasViewDidEndUsingTool(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canvasViewDidEndUsingTool:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate~1canvasViewDrawingDidChange(_:)/title",
          "value": "canvasViewDrawingDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate~1canvasViewDrawingDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canvasViewDrawingDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate~1canvasViewDidBeginUsingTool(_:)/title",
          "value": "canvasViewDidBeginUsingTool:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate~1canvasViewDidBeginUsingTool(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canvasViewDidBeginUsingTool:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate/title",
          "value": "PKCanvasViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pkcanvasviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pencilkit/pkcanvasviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
