{
  "abstract": [
    {
      "text": "A data structure that contains the drawing information captured by a canvas view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKDrawing",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKDrawingReference"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKDrawingReference"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKDrawingReference"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKDrawingReference"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object stores the user-drawn content from a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. You use drawing objects to store the data associated with your user’s drawings. You can save this data with the rest of your app’s content, and you can use that saved data to create a new drawing object later. You can also generate an image based on the drawn content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKAppleDrawingTypeIdentifier": {
      "abstract": [
        {
          "text": "The uniform type identifier for data associated with a drawing object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAppleDrawingTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKAppleDrawingTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAppleDrawingTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "PKAppleDrawingTypeIdentifier",
      "type": "topic",
      "url": "/documentation/pencilkit/pkappledrawingtypeidentifier"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView": {
      "abstract": [
        {
          "text": "A view that captures Apple Pencil input and displays the rendered results in an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "role": "symbol",
      "title": "PKCanvasView",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference": {
      "abstract": [
        {
          "text": "A data structure that contains the drawing information captured by a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDrawingReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDrawingReference"
        }
      ],
      "role": "symbol",
      "title": "PKDrawingReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/appending(_:)": {
      "abstract": [
        {
          "text": "Returns a new drawing created by appending the current drawing with another drawing you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appending"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit9PKDrawingV",
          "text": "PKDrawing"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit9PKDrawingV",
          "text": "PKDrawing"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/appending(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawingByAppendingDrawing:"
        }
      ],
      "role": "symbol",
      "title": "appending(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/appending(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/appendingStrokes(_:)": {
      "abstract": [
        {
          "text": "Returns a copy of the current drawing with the strokes you provide appended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendingStrokes"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit8PKStrokeV",
          "text": "PKStroke"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit9PKDrawingV",
          "text": "PKDrawing"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/appendingStrokes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawingByAppendingStrokes:"
        }
      ],
      "role": "symbol",
      "title": "appendingStrokes(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/appendingstrokes(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/applying(_:)": {
      "abstract": [
        {
          "text": "Returns a new drawing object by applying the specified transform to a copy of the current object’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applying"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit9PKDrawingV",
          "text": "PKDrawing"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/applying(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawingByApplyingTransform:"
        }
      ],
      "role": "symbol",
      "title": "applying(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/applying(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/bounds": {
      "abstract": [
        {
          "text": "The smallest rectangle used to represent the content’s bounds, taking into account line widths of that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/bounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bounds"
        }
      ],
      "role": "symbol",
      "title": "bounds",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/bounds"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/dataRepresentation()": {
      "abstract": [
        {
          "text": "Returns a representation of the rendered content as data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/dataRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataRepresentation"
        }
      ],
      "role": "symbol",
      "title": "dataRepresentation()",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/datarepresentation()"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/image(from:scale:)": {
      "abstract": [
        {
          "text": "Returns an image object that contains the specified portion of the drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/image(from:scale:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageFromRect:scale:"
        }
      ],
      "role": "symbol",
      "title": "image(from:scale:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/image(from:scale:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init()": {
      "abstract": [
        {
          "text": "Creates an empty drawing object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/init()"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init(data:)": {
      "abstract": [
        {
          "text": "Creates a drawing object and populates it with previously drawn content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init(data:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithData:error:"
        }
      ],
      "role": "symbol",
      "title": "init(data:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/init(data:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init(strokes:)": {
      "abstract": [
        {
          "text": "Creates a drawing object with the strokes you supply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "strokes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit8PKStrokeV",
          "text": "PKStroke"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init(strokes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithStrokes:"
        }
      ],
      "role": "symbol",
      "title": "init(strokes:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/init(strokes:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/requiredContentVersion": {
      "abstract": [
        {
          "text": "The version of PencilKit necessary to use the drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiredContentVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKContentVersion",
          "text": "PKContentVersion"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/requiredContentVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiredContentVersion"
        }
      ],
      "role": "symbol",
      "title": "requiredContentVersion",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/requiredcontentversion"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/strokes": {
      "abstract": [
        {
          "text": "An array of strokes used to represent the drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit8PKStrokeV",
          "text": "PKStroke"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/strokes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "strokes"
        }
      ],
      "role": "symbol",
      "title": "strokes",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference/strokes"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKFloatRange": {
      "abstract": [
        {
          "text": "A utility class that represents range components of a stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKFloatRange"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKFloatRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKFloatRange",
      "type": "topic",
      "url": "/documentation/pencilkit/pkfloatrange"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference": {
      "abstract": [
        {
          "text": "Provides a description of the creation and rendering of marks on a canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInkReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInkReference"
        }
      ],
      "role": "symbol",
      "title": "PKInkReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkinkreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePathReference": {
      "abstract": [
        {
          "text": "A class that captures the components of a stroke and provides methods to find and interpolate points along the stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePathReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePathReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePathReference"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePathReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepathreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference": {
      "abstract": [
        {
          "text": "A class that represents the properties of a specific point along a stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePointReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePointReference"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePointReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokeReference": {
      "abstract": [
        {
          "text": "A class that represents the paths, boundaries and other properties of a stroke drawn on a canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokeReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokeReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokeReference"
        }
      ],
      "role": "symbol",
      "title": "PKStrokeReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokereference"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-drawing-object",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init(data:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init(strokes:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init()"
      ],
      "title": "Creating a drawing object"
    },
    {
      "anchor": "Getting-the-canvas-bounds",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/bounds"
      ],
      "title": "Getting the canvas bounds"
    },
    {
      "anchor": "Generating-an-image",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/image(from:scale:)"
      ],
      "title": "Generating an image"
    },
    {
      "anchor": "Getting-the-drawing-data",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/strokes",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/dataRepresentation()",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKAppleDrawingTypeIdentifier"
      ],
      "title": "Getting the drawing data"
    },
    {
      "anchor": "Modifying-the-drawing",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/applying(_:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/appendingStrokes(_:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/appending(_:)"
      ],
      "title": "Modifying the drawing"
    },
    {
      "anchor": "Supporting-backward-compatibility",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/requiredContentVersion"
      ],
      "title": "Supporting backward compatibility"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKDrawing"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pencilkit/documentation/PencilKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-drawing-object",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init(data:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init(strokes:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/init()"
              ],
              "title": "Creating a drawing object"
            },
            {
              "anchor": "Getting-the-canvas-bounds",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/bounds"
              ],
              "title": "Getting the canvas bounds"
            },
            {
              "anchor": "Generating-an-image",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/image(from:scale:)"
              ],
              "title": "Generating an image"
            },
            {
              "anchor": "Getting-the-drawing-data",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/strokes",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/dataRepresentation()",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKAppleDrawingTypeIdentifier"
              ],
              "title": "Getting the drawing data"
            },
            {
              "anchor": "Modifying-the-drawing",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/applying(_:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/appendingStrokes(_:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/appending(_:)"
              ],
              "title": "Modifying the drawing"
            },
            {
              "anchor": "Supporting-backward-compatibility",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference/requiredContentVersion"
              ],
              "title": "Supporting backward compatibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Canvas",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokeReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePathReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKFloatRange"
              ],
              "title": "Canvas"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKDrawing"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1init(data:)/title",
          "value": "initWithData:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1init(data:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithData:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1appendingStrokes(_:)/title",
          "value": "drawingByAppendingStrokes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1appendingStrokes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawingByAppendingStrokes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1applying(_:)/title",
          "value": "drawingByApplyingTransform:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1applying(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawingByApplyingTransform:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1bounds/title",
          "value": "bounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1bounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1init(strokes:)/title",
          "value": "initWithStrokes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1init(strokes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithStrokes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1image(from:scale:)/title",
          "value": "imageFromRect:scale:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1image(from:scale:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageFromRect:scale:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1dataRepresentation()/title",
          "value": "dataRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1dataRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dataRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokeReference/title",
          "value": "PKStroke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokeReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStroke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokeReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStroke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/title",
          "value": "PKCanvasView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/title",
          "value": "PKDrawing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/title",
          "value": "PKInk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1strokes/title",
          "value": "strokes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1strokes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "strokes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/title",
          "value": "PKStrokePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1requiredContentVersion/title",
          "value": "requiredContentVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1requiredContentVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiredContentVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1appending(_:)/title",
          "value": "drawingByAppendingDrawing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference~1appending(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawingByAppendingDrawing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKAppleDrawingTypeIdentifier/title",
          "value": "PKAppleDrawingTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKAppleDrawingTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAppleDrawingTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePathReference/title",
          "value": "PKStrokePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePathReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePathReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePath"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pkdrawingreference"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pencilkit/pkdrawingreference"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
