{
  "abstract": [
    {
      "text": "A structure that represents an ink that specifies its type, color, and width.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9PencilKit5PKInkV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKInk"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKInk"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PKInk"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKInk"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.pencilkit/documentation/PencilKit/supporting-backward-compatibility-for-ink-types"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView": {
      "abstract": [
        {
          "text": "A view that captures Apple Pencil input and displays the rendered results in an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "role": "symbol",
      "title": "PKCanvasView",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct": {
      "abstract": [
        {
          "text": "A structure representing the drawing information captured by a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDrawing"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDrawing"
        }
      ],
      "role": "symbol",
      "title": "PKDrawing",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawing-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an ink that specifies its type, color, and width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInk"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInk"
        }
      ],
      "role": "symbol",
      "title": "PKInk",
      "type": "topic",
      "url": "/documentation/pencilkit/pkink-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/InkType-swift.typealias": {
      "abstract": [
        {
          "text": "A type alias referring to the ink type of an inking tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InkType"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/InkType-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InkType"
        }
      ],
      "role": "symbol",
      "title": "PKInk.InkType",
      "type": "topic",
      "url": "/documentation/pencilkit/pkink-swift.struct/inktype-swift.typealias"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/color-6lmjp": {
      "abstract": [
        {
          "text": "The color of this ink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/color-6lmjp",
      "kind": "symbol",
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/pencilkit/pkink-swift.struct/color-6lmjp"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/color-cg6f": {
      "abstract": [
        {
          "text": "The color of this ink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/color-cg6f",
      "kind": "symbol",
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/pencilkit/pkink-swift.struct/color-cg6f"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/init(_:color:)-2rx09": {
      "abstract": [
        {
          "text": "Creates a new ink, specifying its type and color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit5PKInkV",
          "text": "PKInk"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit5PKInkV7InkTypea",
          "text": "InkType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/init(_:color:)-2rx09",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:color:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkink-swift.struct/init(_:color:)-2rx09"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/init(_:color:)-7w46l": {
      "abstract": [
        {
          "text": "Creates a new ink, specifying its type and color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit5PKInkV",
          "text": "PKInk"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit5PKInkV7InkTypea",
          "text": "InkType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/init(_:color:)-7w46l",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:color:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkink-swift.struct/init(_:color:)-7w46l"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/inkType-swift.property": {
      "abstract": [
        {
          "text": "The line presentation to use for this Ink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inkType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit5PKInkV",
          "text": "PKInk"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit5PKInkV7InkTypea",
          "text": "InkType"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/inkType-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "inkType",
      "type": "topic",
      "url": "/documentation/pencilkit/pkink-swift.struct/inktype-swift.property"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/requiredContentVersion": {
      "abstract": [
        {
          "text": "The version of PencilKit necessary to use the ink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiredContentVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKContentVersion",
          "text": "PKContentVersion"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/requiredContentVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "requiredContentVersion",
      "type": "topic",
      "url": "/documentation/pencilkit/pkink-swift.struct/requiredcontentversion"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference": {
      "abstract": [
        {
          "text": "Provides a description of the creation and rendering of marks on a canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInkReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInkReference"
        }
      ],
      "role": "symbol",
      "title": "PKInkReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkinkreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents the paths, boundaries, and other properties of a stroke drawn on a canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStroke"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStroke"
        }
      ],
      "role": "symbol",
      "title": "PKStroke",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstroke-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct": {
      "abstract": [
        {
          "text": "A structure that captures the components of a stroke and provides methods to find and interpolate points along the stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePath"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePath"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePath",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepath-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents the properties of a specific point along a stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePoint"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePoint"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePoint",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/customizing-scribble-with-interactions": {
      "abstract": [
        {
          "text": "Enable writing on a non-text-input view by adding interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/customizing-scribble-with-interactions",
      "kind": "article",
      "role": "sampleCode",
      "title": "Customizing Scribble with Interactions",
      "type": "topic",
      "url": "/documentation/pencilkit/customizing-scribble-with-interactions"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/drawing-with-pencilkit": {
      "abstract": [
        {
          "text": "Add expressive, low-latency drawing to your app using PencilKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/drawing-with-pencilkit",
      "kind": "article",
      "role": "sampleCode",
      "title": "Drawing with PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit/drawing-with-pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/inspecting-modifying-and-constructing-pencilkit-drawings": {
      "abstract": [
        {
          "text": "Score users’ ability to match PencilKit drawings generated from text, by accessing the strokes and points inside PencilKit drawings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/inspecting-modifying-and-constructing-pencilkit-drawings",
      "kind": "article",
      "role": "sampleCode",
      "title": "Inspecting, Modifying, and Constructing PencilKit Drawings",
      "type": "topic",
      "url": "/documentation/pencilkit/inspecting-modifying-and-constructing-pencilkit-drawings"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/supporting-backward-compatibility-for-ink-types": {
      "abstract": [
        {
          "text": "Leverage the latest PencilKit features while providing a good user experience in earlier versions of the OS that don’t support those features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/supporting-backward-compatibility-for-ink-types",
      "kind": "article",
      "role": "article",
      "title": "Supporting backward compatibility for ink types",
      "type": "topic",
      "url": "/documentation/pencilkit/supporting-backward-compatibility-for-ink-types"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Canvas",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/drawing-with-pencilkit",
        "doc://com.apple.pencilkit/documentation/PencilKit/customizing-scribble-with-interactions",
        "doc://com.apple.pencilkit/documentation/PencilKit/inspecting-modifying-and-constructing-pencilkit-drawings",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct"
      ],
      "title": "Canvas"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-ink-object",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/init(_:color:)-2rx09",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/init(_:color:)-7w46l",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/InkType-swift.typealias"
      ],
      "title": "Creating an ink object"
    },
    {
      "anchor": "Getting-the-ink-attributes",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/color-cg6f",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/color-6lmjp",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/inkType-swift.property"
      ],
      "title": "Getting the ink attributes"
    },
    {
      "anchor": "Supporting-backward-compatibility",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct/requiredContentVersion"
      ],
      "title": "Supporting backward compatibility"
    },
    {
      "anchor": "Using-reference-types",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference"
      ],
      "title": "Using reference types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/title",
          "value": "PKCanvasView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/title",
          "value": "PKInk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInk"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pkink-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
