{
  "abstract": [
    {
      "text": "A structure that represents the properties of a specific point along a stroke’s path.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9PencilKit13PKStrokePointV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKStrokePoint"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKStrokePoint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PKStrokePoint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView": {
      "abstract": [
        {
          "text": "A view that captures Apple Pencil input and displays the rendered results in an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "role": "symbol",
      "title": "PKCanvasView",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct": {
      "abstract": [
        {
          "text": "A structure representing the drawing information captured by a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDrawing"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDrawing"
        }
      ],
      "role": "symbol",
      "title": "PKDrawing",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawing-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an ink that specifies its type, color, and width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInk"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInk"
        }
      ],
      "role": "symbol",
      "title": "PKInk",
      "type": "topic",
      "url": "/documentation/pencilkit/pkink-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents the paths, boundaries, and other properties of a stroke drawn on a canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStroke"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStroke"
        }
      ],
      "role": "symbol",
      "title": "PKStroke",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstroke-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct": {
      "abstract": [
        {
          "text": "A structure that captures the components of a stroke and provides methods to find and interpolate points along the stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePath"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePath"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePath",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepath-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents the properties of a specific point along a stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePoint"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePoint"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePoint",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/altitude": {
      "abstract": [
        {
          "text": "The altitude of this point in radians.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "altitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/altitude",
      "kind": "symbol",
      "role": "symbol",
      "title": "altitude",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct/altitude"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/azimuth": {
      "abstract": [
        {
          "text": "The azimuth of this point in radians.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/azimuth",
      "kind": "symbol",
      "role": "symbol",
      "title": "azimuth",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct/azimuth"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/force": {
      "abstract": [
        {
          "text": "The amount of force applied by the touch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "force"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/force",
      "kind": "symbol",
      "role": "symbol",
      "title": "force",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct/force"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/init(location:timeOffset:size:opacity:force:azimuth:altitude:)": {
      "abstract": [
        {
          "text": "Creates a new point with the provided properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "opacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "force"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "altitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/init(location:timeOffset:size:opacity:force:azimuth:altitude:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(location:timeOffset:size:opacity:force:azimuth:altitude:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct/init(location:timeoffset:size:opacity:force:azimuth:altitude:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "opacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "force"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "altitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "secondaryScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct/init(location:timeoffset:size:opacity:force:azimuth:altitude:secondaryscale:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/location": {
      "abstract": [
        {
          "text": "The location of this point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/location",
      "kind": "symbol",
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct/location"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/opacity": {
      "abstract": [
        {
          "text": "Opacity of the point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/opacity",
      "kind": "symbol",
      "role": "symbol",
      "title": "opacity",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct/opacity"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/secondaryScale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/secondaryScale",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryScale",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct/secondaryscale"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/size": {
      "abstract": [
        {
          "text": "The size of this point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/size",
      "kind": "symbol",
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct/size"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/timeOffset": {
      "abstract": [
        {
          "text": "The time offset since the start of the stroke path in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/timeOffset",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeOffset",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepoint-swift.struct/timeoffset"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference": {
      "abstract": [
        {
          "text": "A class that represents the properties of a specific point along a stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePointReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePointReference"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePointReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/customizing-scribble-with-interactions": {
      "abstract": [
        {
          "text": "Enable writing on a non-text-input view by adding interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/customizing-scribble-with-interactions",
      "kind": "article",
      "role": "sampleCode",
      "title": "Customizing Scribble with Interactions",
      "type": "topic",
      "url": "/documentation/pencilkit/customizing-scribble-with-interactions"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/drawing-with-pencilkit": {
      "abstract": [
        {
          "text": "Add expressive, low-latency drawing to your app using PencilKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/drawing-with-pencilkit",
      "kind": "article",
      "role": "sampleCode",
      "title": "Drawing with PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit/drawing-with-pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/inspecting-modifying-and-constructing-pencilkit-drawings": {
      "abstract": [
        {
          "text": "Score users’ ability to match PencilKit drawings generated from text, by accessing the strokes and points inside PencilKit drawings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/inspecting-modifying-and-constructing-pencilkit-drawings",
      "kind": "article",
      "role": "sampleCode",
      "title": "Inspecting, Modifying, and Constructing PencilKit Drawings",
      "type": "topic",
      "url": "/documentation/pencilkit/inspecting-modifying-and-constructing-pencilkit-drawings"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Canvas",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/drawing-with-pencilkit",
        "doc://com.apple.pencilkit/documentation/PencilKit/customizing-scribble-with-interactions",
        "doc://com.apple.pencilkit/documentation/PencilKit/inspecting-modifying-and-constructing-pencilkit-drawings",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct"
      ],
      "title": "Canvas"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-stroke-point-object",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/init(location:timeOffset:size:opacity:force:azimuth:altitude:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)"
      ],
      "title": "Creating a stroke point object"
    },
    {
      "anchor": "Getting-the-points-location",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/location",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/timeOffset"
      ],
      "title": "Getting the point’s location"
    },
    {
      "anchor": "Getting-the-points-touch-data",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/altitude",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/azimuth",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/force"
      ],
      "title": "Getting the point’s touch data"
    },
    {
      "anchor": "Getting-the-points-drawing-data",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/size",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/opacity",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePoint-swift.struct/secondaryScale"
      ],
      "title": "Getting the point’s drawing data"
    },
    {
      "anchor": "Using-reference-types",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference"
      ],
      "title": "Using reference types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/title",
          "value": "PKCanvasView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/title",
          "value": "PKStrokePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pkstrokepoint-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
