{
  "abstract": [
    {
      "text": "A class that represents the properties of a specific point along a stroke’s path.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKStrokePoint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKStrokePointReference"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKStrokePointReference"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKStrokePointReference"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKStrokePointReference"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView": {
      "abstract": [
        {
          "text": "A view that captures Apple Pencil input and displays the rendered results in an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "role": "symbol",
      "title": "PKCanvasView",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference": {
      "abstract": [
        {
          "text": "A data structure that contains the drawing information captured by a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKDrawingReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKDrawingReference"
        }
      ],
      "role": "symbol",
      "title": "PKDrawingReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkdrawingreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKFloatRange": {
      "abstract": [
        {
          "text": "A utility class that represents range components of a stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKFloatRange"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKFloatRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKFloatRange",
      "type": "topic",
      "url": "/documentation/pencilkit/pkfloatrange"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference": {
      "abstract": [
        {
          "text": "Provides a description of the creation and rendering of marks on a canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInkReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInkReference"
        }
      ],
      "role": "symbol",
      "title": "PKInkReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkinkreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePathReference": {
      "abstract": [
        {
          "text": "A class that captures the components of a stroke and provides methods to find and interpolate points along the stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePathReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePathReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePathReference"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePathReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepathreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference": {
      "abstract": [
        {
          "text": "A class that represents the properties of a specific point along a stroke’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokePointReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokePointReference"
        }
      ],
      "role": "symbol",
      "title": "PKStrokePointReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/altitude": {
      "abstract": [
        {
          "text": "The altitude of this point in radians.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "altitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/altitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "altitude"
        }
      ],
      "role": "symbol",
      "title": "altitude",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference/altitude"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/azimuth": {
      "abstract": [
        {
          "text": "The azimuth of this point in radians.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/azimuth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "azimuth"
        }
      ],
      "role": "symbol",
      "title": "azimuth",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference/azimuth"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/force": {
      "abstract": [
        {
          "text": "The amount of force applied by the touch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "force"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/force",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "force"
        }
      ],
      "role": "symbol",
      "title": "force",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference/force"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/init(location:timeOffset:size:opacity:force:azimuth:altitude:)": {
      "abstract": [
        {
          "text": "Creates a new point with the provided properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "opacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "force"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "altitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/init(location:timeOffset:size:opacity:force:azimuth:altitude:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocation:timeOffset:size:opacity:force:azimuth:altitude:"
        }
      ],
      "role": "symbol",
      "title": "init(location:timeOffset:size:opacity:force:azimuth:altitude:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference/init(location:timeoffset:size:opacity:force:azimuth:altitude:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "opacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "force"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "azimuth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "altitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "secondaryScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocation:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:"
        }
      ],
      "role": "symbol",
      "title": "init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference/init(location:timeoffset:size:opacity:force:azimuth:altitude:secondaryscale:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/location": {
      "abstract": [
        {
          "text": "The location of this point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference/location"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/opacity": {
      "abstract": [
        {
          "text": "Opacity of the point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/opacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opacity"
        }
      ],
      "role": "symbol",
      "title": "opacity",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference/opacity"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/secondaryScale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/secondaryScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secondaryScale"
        }
      ],
      "role": "symbol",
      "title": "secondaryScale",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference/secondaryscale"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/size": {
      "abstract": [
        {
          "text": "The size of the point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference/size"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/timeOffset": {
      "abstract": [
        {
          "text": "The time offset since the start of the stroke path in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/timeOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeOffset"
        }
      ],
      "role": "symbol",
      "title": "timeOffset",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokepointreference/timeoffset"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokeReference": {
      "abstract": [
        {
          "text": "A class that represents the paths, boundaries and other properties of a stroke drawn on a canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStrokeReference"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokeReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStrokeReference"
        }
      ],
      "role": "symbol",
      "title": "PKStrokeReference",
      "type": "topic",
      "url": "/documentation/pencilkit/pkstrokereference"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-stroke-point-object",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/init(location:timeOffset:size:opacity:force:azimuth:altitude:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)"
      ],
      "title": "Creating a stroke point object"
    },
    {
      "anchor": "Getting-the-points-location",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/location",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/timeOffset"
      ],
      "title": "Getting the point’s location"
    },
    {
      "anchor": "Getting-the-points-touch-data",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/altitude",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/azimuth",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/force"
      ],
      "title": "Getting the point’s touch data"
    },
    {
      "anchor": "Getting-the-points-drawing-data",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/size",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/opacity",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/secondaryScale"
      ],
      "title": "Getting the point’s drawing data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKStrokePoint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pencilkit/documentation/PencilKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-stroke-point-object",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/init(location:timeOffset:size:opacity:force:azimuth:altitude:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)"
              ],
              "title": "Creating a stroke point object"
            },
            {
              "anchor": "Getting-the-points-location",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/location",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/timeOffset"
              ],
              "title": "Getting the point’s location"
            },
            {
              "anchor": "Getting-the-points-touch-data",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/altitude",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/azimuth",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/force"
              ],
              "title": "Getting the point’s touch data"
            },
            {
              "anchor": "Getting-the-points-drawing-data",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/size",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/opacity",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePointReference/secondaryScale"
              ],
              "title": "Getting the point’s drawing data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Canvas",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKDrawingReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokeReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePathReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKFloatRange"
              ],
              "title": "Canvas"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKStrokePoint"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokeReference/title",
          "value": "PKStroke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokeReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStroke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokeReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStroke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1timeOffset/title",
          "value": "timeOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1timeOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/title",
          "value": "PKCanvasView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1altitude/title",
          "value": "altitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1altitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "altitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)/title",
          "value": "initWithLocation:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1init(location:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocation:timeOffset:size:opacity:force:azimuth:altitude:secondaryScale:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1force/title",
          "value": "force"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1force/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "force"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1secondaryScale/title",
          "value": "secondaryScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1secondaryScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secondaryScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/title",
          "value": "PKDrawing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKDrawingReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1azimuth/title",
          "value": "azimuth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1azimuth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "azimuth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1opacity/title",
          "value": "opacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1opacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePathReference/title",
          "value": "PKStrokePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePathReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePathReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1location/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/title",
          "value": "PKStrokePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStrokePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/title",
          "value": "PKInk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1init(location:timeOffset:size:opacity:force:azimuth:altitude:)/title",
          "value": "initWithLocation:timeOffset:size:opacity:force:azimuth:altitude:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKStrokePointReference~1init(location:timeOffset:size:opacity:force:azimuth:altitude:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocation:timeOffset:size:opacity:force:azimuth:altitude:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pkstrokepointreference"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pencilkit/pkstrokepointreference"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
