{
  "abstract": [
    {
      "text": "An interface you use to detect when the user changes the selected tools and drawing characteristics of a tool picker object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PKToolPickerObserver",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKToolPickerObserver"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKToolPickerObserver"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PKToolPickerObserver"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKToolPickerObserver"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement the methods of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to detect when the user changes the configuration of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " view. Each time the user changes the selected tool or other drawing characteristics, the tool picker notifies any registered observers. You use these notifications to update the configuration of the underlying canvas.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To register an observer with a tool picker, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/addObserver(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView": {
      "abstract": [
        {
          "text": "A view that captures Apple Pencil input and displays the rendered results in an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "role": "symbol",
      "title": "PKCanvasView",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker": {
      "abstract": [
        {
          "text": "A tool palette that displays a selection of drawing tools and colors for tools that a person can choose from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPicker"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPicker"
        }
      ],
      "role": "symbol",
      "title": "PKToolPicker",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpicker"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/addObserver(_:)": {
      "abstract": [
        {
          "text": "Adds the specified object to the list of objects to notify when the picker configuration changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addObserver"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PKToolPickerObserver",
          "text": "PKToolPickerObserver"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/addObserver(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addObserver:"
        }
      ],
      "role": "symbol",
      "title": "addObserver(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpicker/addobserver(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/removeObserver(_:)": {
      "abstract": [
        {
          "text": "Removes the specified object from the list of objects to notify when the picker configuration changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeObserver"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PKToolPickerObserver",
          "text": "PKToolPickerObserver"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/removeObserver(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeObserver:"
        }
      ],
      "role": "symbol",
      "title": "removeObserver(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpicker/removeobserver(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver": {
      "abstract": [
        {
          "text": "An interface you use to detect when the user changes the selected tools and drawing characteristics of a tool picker object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPickerObserver"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPickerObserver"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerObserver",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerobserver"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerFramesObscuredDidChange(_:)": {
      "abstract": [
        {
          "text": "Tells the observer when the area that the tool picker obscures changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolPickerFramesObscuredDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKToolPicker",
          "text": "PKToolPicker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerFramesObscuredDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolPickerFramesObscuredDidChange:"
        }
      ],
      "role": "symbol",
      "title": "toolPickerFramesObscuredDidChange(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerobserver/toolpickerframesobscureddidchange(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerIsRulerActiveDidChange(_:)": {
      "abstract": [
        {
          "text": "Tells the observer when a person shows or hides the ruler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolPickerIsRulerActiveDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKToolPicker",
          "text": "PKToolPicker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerIsRulerActiveDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolPickerIsRulerActiveDidChange:"
        }
      ],
      "role": "symbol",
      "title": "toolPickerIsRulerActiveDidChange(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerobserver/toolpickerisruleractivedidchange(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerSelectedToolDidChange(_:)": {
      "abstract": [
        {
          "text": "Tells the observer when a person selects a new tool.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolPickerSelectedToolDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKToolPicker",
          "text": "PKToolPicker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerSelectedToolDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolPickerSelectedToolDidChange:"
        }
      ],
      "role": "symbol",
      "title": "toolPickerSelectedToolDidChange(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerobserver/toolpickerselectedtooldidchange(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerSelectedToolItemDidChange(_:)": {
      "abstract": [
        {
          "text": "Tells the observer when a person selects a new tool item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolPickerSelectedToolItemDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKToolPicker",
          "text": "PKToolPicker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerSelectedToolItemDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolPickerSelectedToolItemDidChange:"
        }
      ],
      "role": "symbol",
      "title": "toolPickerSelectedToolItemDidChange(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerobserver/toolpickerselectedtoolitemdidchange(_:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerVisibilityDidChange(_:)": {
      "abstract": [
        {
          "text": "Tells the observer when a person shows or hides the tool picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolPickerVisibilityDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKToolPicker",
          "text": "PKToolPicker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerVisibilityDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolPickerVisibilityDidChange:"
        }
      ],
      "role": "symbol",
      "title": "toolPickerVisibilityDidChange(_:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerobserver/toolpickervisibilitydidchange(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Detecting-changes-to-the-picker",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/addObserver(_:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/removeObserver(_:)"
      ],
      "title": "Detecting changes to the picker"
    }
  ],
  "topicSections": [
    {
      "anchor": "Detecting-tool-configuration-changes",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerSelectedToolItemDidChange(_:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerIsRulerActiveDidChange(_:)"
      ],
      "title": "Detecting tool configuration changes"
    },
    {
      "anchor": "Monitoring-visibility-changes",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerVisibilityDidChange(_:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerFramesObscuredDidChange(_:)"
      ],
      "title": "Monitoring visibility changes"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerSelectedToolDidChange(_:)"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKToolPickerObserver"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pencilkit/documentation/PencilKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Detecting-tool-configuration-changes",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerSelectedToolItemDidChange(_:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerIsRulerActiveDidChange(_:)"
              ],
              "title": "Detecting tool configuration changes"
            },
            {
              "anchor": "Monitoring-visibility-changes",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerVisibilityDidChange(_:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerFramesObscuredDidChange(_:)"
              ],
              "title": "Monitoring visibility changes"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerObserver/toolPickerSelectedToolDidChange(_:)"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Detecting-changes-to-the-picker",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/addObserver(_:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/removeObserver(_:)"
              ],
              "title": "Detecting changes to the picker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKToolPickerObserver"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver~1toolPickerSelectedToolItemDidChange(_:)/title",
          "value": "toolPickerSelectedToolItemDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver~1toolPickerSelectedToolItemDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toolPickerSelectedToolItemDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver~1toolPickerFramesObscuredDidChange(_:)/title",
          "value": "toolPickerFramesObscuredDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver~1toolPickerFramesObscuredDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toolPickerFramesObscuredDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/title",
          "value": "PKCanvasView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1removeObserver(_:)/title",
          "value": "removeObserver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1removeObserver(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeObserver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker/title",
          "value": "PKToolPicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver~1toolPickerVisibilityDidChange(_:)/title",
          "value": "toolPickerVisibilityDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver~1toolPickerVisibilityDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toolPickerVisibilityDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1addObserver(_:)/title",
          "value": "addObserver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1addObserver(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addObserver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver~1toolPickerSelectedToolDidChange(_:)/title",
          "value": "toolPickerSelectedToolDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver~1toolPickerSelectedToolDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toolPickerSelectedToolDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver/title",
          "value": "PKToolPickerObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver~1toolPickerIsRulerActiveDidChange(_:)/title",
          "value": "toolPickerIsRulerActiveDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerObserver~1toolPickerIsRulerActiveDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toolPickerIsRulerActiveDidChange:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pktoolpickerobserver"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pencilkit/pktoolpickerobserver"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
