{
  "abstract": [
    {
      "text": "A configuration that specifies the appearance and behavior of a custom tool item and its contents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKToolPickerCustomItemConfiguration",
    "fragments": [
      {
        "kind": "identifier",
        "text": "PKToolPickerCustomItemConfiguration"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKToolPickerCustomItemConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKToolPickerCustomItemConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKToolPickerCustomItemConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/color": {
      "abstract": [
        {
          "text": "The current color of the custom tool item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitem/color"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/configuration-v7e5": {
      "abstract": [
        {
          "text": "The configuration of the custom tool item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/configuration-v7e5",
      "kind": "symbol",
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitem/configuration-v7e5"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/width": {
      "abstract": [
        {
          "text": "The current width of the custom tool item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/width",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "width"
        }
      ],
      "role": "symbol",
      "title": "width",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitem/width"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration": {
      "abstract": [
        {
          "text": "A configuration that specifies the appearance and behavior of a custom tool item and its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PKToolPickerCustomItemConfiguration"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "PKToolPickerCustomItemConfiguration",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/allowsColorSelection": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether to show the color selection UI for the tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "allowsColorSelection"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/allowsColorSelection",
      "kind": "symbol",
      "role": "symbol",
      "title": "allowsColorSelection",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration/allowscolorselection"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/defaultColor": {
      "abstract": [
        {
          "text": "The default color for the tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "defaultColor"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/defaultColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultColor",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration/defaultcolor"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/defaultWidth": {
      "abstract": [
        {
          "text": "The default width for the tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "defaultWidth"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/defaultWidth",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultWidth",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration/defaultwidth"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/identifier": {
      "abstract": [
        {
          "text": "A string that uniquely identifies the tool in the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/identifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration/identifier"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/imageProvider": {
      "abstract": [
        {
          "text": "A closure that provides an image for the tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imageProvider"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/imageProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageProvider",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration/imageprovider"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/initWithIdentifier:name:": {
      "abstract": [
        {
          "text": "Create a new configuration with an identifier and a name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithIdentifier:name:"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/initWithIdentifier:name:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:name:"
        }
      ],
      "role": "symbol",
      "title": "initWithIdentifier:name:",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration/initwithidentifier:name:"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/name": {
      "abstract": [
        {
          "text": "A short string to show as the name of the tool in the UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/name",
      "kind": "symbol",
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration/name"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/toolAttributeControls": {
      "abstract": [
        {
          "text": "Defines which attribute controls are available to be presented in UI such as the tool attributes popover, or inline in the picker presented from a pencil squeeze.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Controls for properties which the tool item does not support will not be presented. Excluding a control here does not hide all UI for adjusting that value.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "For example, excluding the opacity control here will not remove it from the color picker, if the color picker is otherwise available.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Defaults to all controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "toolAttributeControls"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/toolAttributeControls",
      "kind": "symbol",
      "role": "symbol",
      "title": "toolAttributeControls",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration/toolattributecontrols"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/viewControllerProvider": {
      "abstract": [
        {
          "text": "A closure to provide a view controller above the system controls in the tool attributes popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "viewControllerProvider"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/viewControllerProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewControllerProvider",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration/viewcontrollerprovider"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/widthVariants": {
      "abstract": [
        {
          "text": "A dictionary with UI options for selecting width, with each element containing a width value and its corresponding image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "widthVariants"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/widthVariants",
      "kind": "symbol",
      "role": "symbol",
      "title": "widthVariants",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitemconfiguration/widthvariants"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-custom-item",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/color",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/width",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem/configuration-v7e5"
      ],
      "title": "Configuring the custom item"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-configuration",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/initWithIdentifier:name:"
      ],
      "title": "Creating a configuration"
    },
    {
      "anchor": "Identifying-the-custom-item",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/identifier",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/name"
      ],
      "title": "Identifying the custom item"
    },
    {
      "anchor": "Customizing-color",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/defaultColor",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/allowsColorSelection"
      ],
      "title": "Customizing color"
    },
    {
      "anchor": "Customizing-width",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/defaultWidth",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/widthVariants"
      ],
      "title": "Customizing width"
    },
    {
      "anchor": "Providing-an-image-for-the-tool",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/imageProvider"
      ],
      "title": "Providing an image for the tool"
    },
    {
      "anchor": "Providing-a-custom-view-controller-for-the-tool",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/viewControllerProvider"
      ],
      "title": "Providing a custom view controller for the tool"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItemConfiguration/toolAttributeControls"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem~1color/title",
          "value": "color"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem~1color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem~1width/title",
          "value": "width"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem~1width/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "width"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pktoolpickercustomitemconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
