{
  "abstract": [
    {
      "text": "An item that represents a ruler tool in the tool picker.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerRulerItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKToolPickerRulerItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PKToolPickerRulerItem"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKToolPickerRulerItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKToolPickerRulerItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PKToolPickerRulerItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/init()": {
      "abstract": [
        {
          "text": "Creates a new tool picker with a default set of tools.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpicker/init()"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/init(toolItems:)": {
      "abstract": [
        {
          "text": "Creates a new tool picker with the tools you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toolItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKToolPickerItem",
          "text": "PKToolPickerItem"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/init(toolItems:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithToolItems:"
        }
      ],
      "role": "symbol",
      "title": "init(toolItems:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpicker/init(toolitems:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem": {
      "abstract": [
        {
          "text": "An item that represents a custom tool in the tool picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPickerCustomItem"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPickerCustomItem"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerCustomItem",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickercustomitem"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem": {
      "abstract": [
        {
          "text": "An item that represents an eraser tool in the tool picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPickerEraserItem"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPickerEraserItem"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerEraserItem",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickereraseritem"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerInkingItem": {
      "abstract": [
        {
          "text": "An item that represents an inking tool in the tool picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPickerInkingItem"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerInkingItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPickerInkingItem"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerInkingItem",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerinkingitem"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerItem": {
      "abstract": [
        {
          "text": "The base class for an item in the tool picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPickerItem"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPickerItem"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerItem",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickeritem"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerLassoItem": {
      "abstract": [
        {
          "text": "An item that represents a lasso tool in the tool picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPickerLassoItem"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerLassoItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPickerLassoItem"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerLassoItem",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerlassoitem"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerRulerItem": {
      "abstract": [
        {
          "text": "An item that represents a ruler tool in the tool picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPickerRulerItem"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerRulerItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPickerRulerItem"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerRulerItem",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerruleritem"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerRulerItem/init()": {
      "abstract": [
        {
          "text": "Creates a new ruler item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerRulerItem/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerruleritem/init()"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerScribbleItem": {
      "abstract": [
        {
          "text": "An item that represents a Scribble tool in the tool picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPickerScribbleItem"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerScribbleItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPickerScribbleItem"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerScribbleItem",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickerscribbleitem"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerItem"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-tool-picker",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/init()",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/init(toolItems:)",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerInkingItem",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerLassoItem",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerScribbleItem",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerItem"
      ],
      "title": "Creating a tool picker"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-ruler-item",
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerRulerItem/init()"
      ],
      "title": "Creating a ruler item"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKToolPickerRulerItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerRulerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerRulerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pencilkit/documentation/PencilKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-ruler-item",
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerRulerItem/init()"
              ],
              "title": "Creating a ruler item"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerItem"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-tool-picker",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/init()",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/init(toolItems:)",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerInkingItem",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerLassoItem",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerScribbleItem",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerCustomItem",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerItem"
              ],
              "title": "Creating a tool picker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKToolPickerRulerItem"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PKToolPickerItem",
                    "text": "PKToolPickerItem"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1init(toolItems:)/title",
          "value": "initWithToolItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1init(toolItems:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithToolItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerItem/title",
          "value": "PKToolPickerItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerScribbleItem/title",
          "value": "PKToolPickerScribbleItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerScribbleItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerScribbleItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerScribbleItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerScribbleItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerRulerItem~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerRulerItem~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem/title",
          "value": "PKToolPickerCustomItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerCustomItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerCustomItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerCustomItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerLassoItem/title",
          "value": "PKToolPickerLassoItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerLassoItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerLassoItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerLassoItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerLassoItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerInkingItem/title",
          "value": "PKToolPickerInkingItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerInkingItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerInkingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerInkingItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerInkingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerRulerItem/title",
          "value": "PKToolPickerRulerItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerRulerItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerRulerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerRulerItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerRulerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerEraserItem/title",
          "value": "PKToolPickerEraserItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerEraserItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerEraserItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerEraserItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerEraserItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pktoolpickerruleritem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pencilkit/pktoolpickerruleritem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
