{
  "abstract": [
    {
      "text": "The parameter is missing or incorrect.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badParameter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ENErrorCode@ENErrorCodeBadParameter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "badParameter"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ENErrorCodeBadParameter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ENError.Code.badParameter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "badParameter"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError": {
      "abstract": [
        {
          "text": "Errors that the exposure notification framework issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENError"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENError"
        }
      ],
      "role": "symbol",
      "title": "ENError",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code": {
      "abstract": [
        {
          "text": "Error codes that the exposure notification framework issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/apiMisuse": {
      "abstract": [
        {
          "text": "The API use is incorrect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiMisuse"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/apiMisuse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeAPIMisuse"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.apiMisuse",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/apimisuse"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badFormat": {
      "abstract": [
        {
          "text": "A file is formated incorrectly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badFormat"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeBadFormat"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.badFormat",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/badformat"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badParameter": {
      "abstract": [
        {
          "text": "The parameter is missing or incorrect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badParameter"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeBadParameter"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.badParameter",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/badparameter"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/bluetoothOff": {
      "abstract": [
        {
          "text": "Bluetooth is turned off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothOff"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/bluetoothOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeBluetoothOff"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.bluetoothOff",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/bluetoothoff"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/dataInaccessible": {
      "abstract": [
        {
          "text": "The user must unlock the device before it can access data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataInaccessible"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/dataInaccessible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeDataInaccessible"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.dataInaccessible",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/datainaccessible"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientMemory": {
      "abstract": [
        {
          "text": "The memory is insufficient to perform the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientMemory"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeInsufficientMemory"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.insufficientMemory",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/insufficientmemory"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientStorage": {
      "abstract": [
        {
          "text": "The storage is insufficient to enable notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientStorage"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeInsufficientStorage"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.insufficientStorage",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/insufficientstorage"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/internal": {
      "abstract": [
        {
          "text": "A bug in the internal notification framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/internal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeInternal"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.internal",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/internal"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/invalidated": {
      "abstract": [
        {
          "text": "A call to invalidate before the operation completes normally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidated"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/invalidated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeInvalidated"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.invalidated",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/invalidated"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notAuthorized": {
      "abstract": [
        {
          "text": "The user has denied access to the notification framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthorized"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.notAuthorized",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/notauthorized"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEnabled": {
      "abstract": [
        {
          "text": "Notification is not enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEnabled"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeNotEnabled"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.notEnabled",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/notenabled"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEntitled": {
      "abstract": [
        {
          "text": "Process of calling is not entitled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEntitled"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEntitled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeNotEntitled"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.notEntitled",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/notentitled"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/rateLimited": {
      "abstract": [
        {
          "text": "API calls are too frequent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rateLimited"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/rateLimited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeRateLimited"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.rateLimited",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/ratelimited"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/restricted": {
      "abstract": [
        {
          "text": "Exposure notification is disabled due to system policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeRestricted"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.restricted",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/restricted"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unknown": {
      "abstract": [
        {
          "text": "Failure has an unknown cause.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeUnknown"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.unknown",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/unknown"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unsupported": {
      "abstract": [
        {
          "text": "Operation is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeUnsupported"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.unsupported",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/unsupported"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/apiMisuse",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badFormat",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/restricted",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/bluetoothOff",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientMemory",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientStorage",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/internal",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/invalidated",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notAuthorized",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEnabled",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEntitled",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/rateLimited",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unknown",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unsupported",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/dataInaccessible"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ENErrorCodeBadParameter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeBadParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/apiMisuse",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badFormat",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/restricted",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/bluetoothOff",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientMemory",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientStorage",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/internal",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/invalidated",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notAuthorized",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEnabled",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEntitled",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/rateLimited",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unknown",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unsupported",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/dataInaccessible"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ENErrorCodeBadParameter"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1badParameter/title",
          "value": "ENErrorCodeBadParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1badParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeBadParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1invalidated/title",
          "value": "ENErrorCodeInvalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1invalidated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeInvalidated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1apiMisuse/title",
          "value": "ENErrorCodeAPIMisuse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1apiMisuse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeAPIMisuse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notEnabled/title",
          "value": "ENErrorCodeNotEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeNotEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1unsupported/title",
          "value": "ENErrorCodeUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1rateLimited/title",
          "value": "ENErrorCodeRateLimited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1rateLimited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeRateLimited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1restricted/title",
          "value": "ENErrorCodeRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1insufficientStorage/title",
          "value": "ENErrorCodeInsufficientStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1insufficientStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeInsufficientStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1unknown/title",
          "value": "ENErrorCodeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notAuthorized/title",
          "value": "ENErrorCodeNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notEntitled/title",
          "value": "ENErrorCodeNotEntitled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notEntitled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeNotEntitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1insufficientMemory/title",
          "value": "ENErrorCodeInsufficientMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1insufficientMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeInsufficientMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1internal/title",
          "value": "ENErrorCodeInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1internal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1bluetoothOff/title",
          "value": "ENErrorCodeBluetoothOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1bluetoothOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeBluetoothOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1dataInaccessible/title",
          "value": "ENErrorCodeDataInaccessible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1dataInaccessible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeDataInaccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1badFormat/title",
          "value": "ENErrorCodeBadFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1badFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeBadFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/title",
          "value": "ENErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/enerror/code/badparameter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/enerror/code/badparameter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
