{
  "abstract": [
    {
      "text": "The end date of the operation that the event represents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/endDate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPersistentCloudKitContainerEvent(py)endDate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "endDate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DateV",
        "text": "Date"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "endDate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "endDate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "endDate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DateV",
              "text": "Date"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer": {
      "abstract": [
        {
          "text": "A container that encapsulates the Core Data stack in your app, and mirrors select persistent stores to a CloudKit private database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainer"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainer"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentCloudKitContainer",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event": {
      "abstract": [
        {
          "text": "An object that represents activity in a persistent CloudKit container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Event"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentCloudKitContainer.Event",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer/event"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/endDate": {
      "abstract": [
        {
          "text": "The end date of the operation that the event represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/endDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endDate"
        }
      ],
      "role": "symbol",
      "title": "endDate",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer/event/enddate"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/error": {
      "abstract": [
        {
          "text": "An error that indicates why an operation fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "role": "symbol",
      "title": "error",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer/event/error"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/identifier": {
      "abstract": [
        {
          "text": "A unique identifier for the event in a container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer/event/identifier"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/startDate": {
      "abstract": [
        {
          "text": "The start date of the operation that the event represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/startDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDate"
        }
      ],
      "role": "symbol",
      "title": "startDate",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer/event/startdate"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/storeIdentifier": {
      "abstract": [
        {
          "text": "The associated store identifier in the container for the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/storeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "storeIdentifier",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer/event/storeidentifier"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/succeeded": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the operation the event represents is successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "succeeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/succeeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "succeeded"
        }
      ],
      "role": "symbol",
      "title": "succeeded",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer/event/succeeded"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/type": {
      "abstract": [
        {
          "text": "The type of event, either setup, import, or export.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentCloudKitContainer",
          "text": "NSPersistentCloudKitContainer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPersistentCloudKitContainerEventType",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer/event/type"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DateV": {
      "abstract": [
        {
          "text": "A specific point in time, independent of any calendar or time zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Date",
      "type": "topic",
      "url": "/documentation/foundation/date"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Event-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/type",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/identifier",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/storeIdentifier",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/succeeded",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/startDate",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/error"
      ],
      "title": "Inspecting Event Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "endDate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-Event-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/type",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/identifier",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/storeIdentifier",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/succeeded",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/startDate",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer/Event/error"
              ],
              "title": "Inspecting Event Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDate",
                    "text": "NSDate"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "endDate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1startDate/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1startDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1error/title",
          "value": "error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1storeIdentifier/title",
          "value": "storeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1storeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1succeeded/title",
          "value": "succeeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1succeeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "succeeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer/title",
          "value": "NSPersistentCloudKitContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1endDate/title",
          "value": "endDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event~1endDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event/title",
          "value": "NSPersistentCloudKitContainerEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer~1Event/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistentcloudkitcontainer/event/enddate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nspersistentcloudkitcontainer/event/enddate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
