{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/purple"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@UITextFormattingViewControllerHighlightPurple",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "purple"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
        "text": "UITextFormattingViewController"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@UITextFormattingViewControllerHighlight",
        "text": "Highlight"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextFormattingViewControllerHighlightPurple"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "purple"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "purple"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
              "text": "UITextFormattingViewController"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UITextFormattingViewControllerHighlight",
              "text": "Highlight"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextFormattingViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewController"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontAttributes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerFontAttributesComponentKey"
        }
      ],
      "role": "symbol",
      "title": "fontAttributes",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/fontattributes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontPicker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontPicker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerFontPickerComponentKey"
        }
      ],
      "role": "symbol",
      "title": "fontPicker",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/fontpicker"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontPointSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontPointSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontPointSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerFontPointSizeComponentKey"
        }
      ],
      "role": "symbol",
      "title": "fontPointSize",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/fontpointsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerFontSizeComponentKey"
        }
      ],
      "role": "symbol",
      "title": "fontSize",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/fontsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/formattingStyles": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formattingStyles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/formattingStyles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerFormattingStylesComponentKey"
        }
      ],
      "role": "symbol",
      "title": "formattingStyles",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/formattingstyles"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/highlight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/highlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerHighlightComponentKey"
        }
      ],
      "role": "symbol",
      "title": "highlight",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/highlight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/highlightPicker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlightPicker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/highlightPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerHighlightPickerComponentKey"
        }
      ],
      "role": "symbol",
      "title": "highlightPicker",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/highlightpicker"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/lineHeight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/lineHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerLineHeightComponentKey"
        }
      ],
      "role": "symbol",
      "title": "lineHeight",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/lineheight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/listStyles": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listStyles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/listStyles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerListStylesComponentKey"
        }
      ],
      "role": "symbol",
      "title": "listStyles",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/liststyles"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textAlignment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerTextAlignmentComponentKey"
        }
      ],
      "role": "symbol",
      "title": "textAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/textalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textAlignmentAndJustification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textAlignmentAndJustification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textAlignmentAndJustification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerTextAlignmentAndJustificationComponentKey"
        }
      ],
      "role": "symbol",
      "title": "textAlignmentAndJustification",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/textalignmentandjustification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textColor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerTextColorComponentKey"
        }
      ],
      "role": "symbol",
      "title": "textColor",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/textcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textIndentation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textIndentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerComponentKey",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textIndentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerTextIndentationComponentKey"
        }
      ],
      "role": "symbol",
      "title": "textIndentation",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey/textindentation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Highlight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Highlight"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.Highlight",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/highlight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/blue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerHighlight",
          "text": "Highlight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerHighlightBlue"
        }
      ],
      "role": "symbol",
      "title": "blue",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/highlight/blue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/default": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerHighlight",
          "text": "Highlight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerHighlightDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/highlight/default"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/purple": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextFormattingViewControllerHighlight",
          "text": "Highlight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/purple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerHighlightPurple"
        }
      ],
      "role": "symbol",
      "title": "purple",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/highlight/purple"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Global-variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontAttributes",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontPicker",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontPointSize",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontSize",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/formattingStyles",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/highlight",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/highlightPicker",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/lineHeight",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/listStyles",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textAlignment",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textAlignmentAndJustification",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textColor",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textIndentation",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/blue",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/default"
      ],
      "title": "Global variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextFormattingViewControllerHighlightPurple"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerHighlightPurple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Global-variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontAttributes",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontPicker",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontPointSize",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/fontSize",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/formattingStyles",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/highlight",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/highlightPicker",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/lineHeight",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/listStyles",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textAlignment",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textAlignmentAndJustification",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textColor",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey/textIndentation",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/blue",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight/default"
              ],
              "title": "Global variables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UITextFormattingViewControllerHighlight",
                    "text": "UITextFormattingViewControllerHighlight"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITextFormattingViewControllerHighlightPurple"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1formattingStyles/title",
          "value": "UITextFormattingViewControllerFormattingStylesComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1formattingStyles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerFormattingStylesComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight~1blue/title",
          "value": "UITextFormattingViewControllerHighlightBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight~1blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerHighlightBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/title",
          "value": "UITextFormattingViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1highlight/title",
          "value": "UITextFormattingViewControllerHighlightComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1highlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerHighlightComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1textColor/title",
          "value": "UITextFormattingViewControllerTextColorComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1textColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerTextColorComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1listStyles/title",
          "value": "UITextFormattingViewControllerListStylesComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1listStyles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerListStylesComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1textAlignment/title",
          "value": "UITextFormattingViewControllerTextAlignmentComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1textAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerTextAlignmentComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1fontPointSize/title",
          "value": "UITextFormattingViewControllerFontPointSizeComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1fontPointSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerFontPointSizeComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1lineHeight/title",
          "value": "UITextFormattingViewControllerLineHeightComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1lineHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerLineHeightComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1fontAttributes/title",
          "value": "UITextFormattingViewControllerFontAttributesComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1fontAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerFontAttributesComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight~1purple/title",
          "value": "UITextFormattingViewControllerHighlightPurple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight~1purple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerHighlightPurple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight/title",
          "value": "UITextFormattingViewControllerHighlight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1fontSize/title",
          "value": "UITextFormattingViewControllerFontSizeComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1fontSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerFontSizeComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight~1default/title",
          "value": "UITextFormattingViewControllerHighlightDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerHighlightDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1textAlignmentAndJustification/title",
          "value": "UITextFormattingViewControllerTextAlignmentAndJustificationComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1textAlignmentAndJustification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerTextAlignmentAndJustificationComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1textIndentation/title",
          "value": "UITextFormattingViewControllerTextIndentationComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1textIndentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerTextIndentationComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1fontPicker/title",
          "value": "UITextFormattingViewControllerFontPickerComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1fontPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerFontPickerComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1highlightPicker/title",
          "value": "UITextFormattingViewControllerHighlightPickerComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey~1highlightPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerHighlightPickerComponentKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextformattingviewcontroller/highlight/purple"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextformattingviewcontroller/highlight/purple"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
