{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/textAlignment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITextFormattingViewControllerChangeValue(py)textAlignment",
    "fragments": [
      {
        "kind": "identifier",
        "text": "textAlignment"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "textAlignment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "textAlignment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextAlignment",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTextAlignment",
              "text": "NSTextAlignment"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "textAlignment"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextAlignment": {
      "abstract": [
        {
          "text": "Constants that specify text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment",
      "type": "topic",
      "url": "/documentation/uikit/nstextalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerChangeValue"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewControllerChangeValue",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/textAlignment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/textAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "textAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue/textalignment"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextAlignment/title",
          "value": "NSTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextformattingviewcontrollerchangevalue/textalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
