{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/scenekit/scntechnique/setobject(_:forkeyedsubscript:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/scenekit/scntechnique/setobject(_:forkeyedsubscript:)"]}],"kind":"symbol","metadata":{"platforms":[{"unavailable":false,"introducedAt":"9.0","beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"introducedAt":"9.0","beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"13.1","beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"10.11","beta":false,"deprecated":false,"name":"macOS"},{"unavailable":false,"introducedAt":"9.0","beta":false,"deprecated":false,"name":"tvOS"},{"unavailable":false,"introducedAt":"1.0","beta":false,"deprecated":false,"name":"visionOS"},{"unavailable":false,"introducedAt":"2.0","beta":false,"deprecated":false,"name":"watchOS"}],"modules":[{"name":"SceneKit"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)SCNTechnique(im)setObject:forKeyedSubscript:","title":"setObject(_:forKeyedSubscript:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"forKeyedSubscript","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"NSCopying","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSCopying"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setObject:forKeyedSubscript:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Sets a value for the specified shader  variable or attribute name, using subscript syntax."}],"identifier":{"url":"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/setObject(_:forKeyedSubscript:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"obj","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"forKeyedSubscript","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"NSCopying","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","preciseIdentifier":"c:objc(pl)NSCopying"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"obj","content":[{"inlineContent":[{"type":"text","text":"An object containing a new value for the shader symbol."}],"type":"paragraph"}]},{"name":"key","content":[{"type":"paragraph","inlineContent":[{"text":"A shader variable or attribute name used in one of the technique’s shader programs.","type":"text"}]}]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"value","type":"codeVoice"},{"type":"text","text":" parameter should be an object appropriate to the type of the shader symbol being set. For example, use an "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsnumber","isActive":true},{"type":"text","text":" object to set the value of a "},{"code":"float","type":"codeVoice"},{"type":"text","text":" uniform variable, or use an "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsvalue","isActive":true},{"type":"text","text":" object containing an "},{"type":"reference","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3","isActive":true},{"type":"text","text":" structure to set the value of a GLSL "},{"code":"vec3","type":"codeVoice"},{"type":"text","text":" uniform variable or a Metal "},{"code":"float3","type":"codeVoice"},{"type":"text","text":" variable."}]},{"type":"paragraph","inlineContent":[{"text":"Use this method when you need to set a value infrequently or only once. To update a shader value every time SceneKit renders a frame, use the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/handleBinding(ofSymbol:using:)","type":"reference"},{"text":" method instead.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you use the "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/handleBinding(ofSymbol:using:)","isActive":true,"type":"reference"},{"type":"text","text":" method to associate a handler block for a symbol, SceneKit ignores values set for the symbol using the "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/setObject(_:forKeyedSubscript:)","isActive":true,"type":"reference"},{"type":"text","text":" method."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique"]]},"seeAlsoSections":[{"anchor":"Handling-Parameters-for-a-Techniques-Shader-Programs","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/handleBinding(ofSymbol:using:)","doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/subscript(_:)"],"title":"Handling Parameters for a Technique’s Shader Programs","generated":true}],"references":{"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/setObject(_:forKeyedSubscript:)":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/setObject(_:forKeyedSubscript:)","type":"topic","abstract":[{"type":"text","text":"Sets a value for the specified shader  variable or attribute name, using subscript syntax."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setObject"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"text":"forKeyedSubscript","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSCopying","text":"NSCopying","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"setObject(_:forKeyedSubscript:)","url":"/documentation/scenekit/scntechnique/setobject(_:forkeyedsubscript:)","role":"symbol","navigatorTitle":[{"text":"setObject:forKeyedSubscript:","kind":"identifier"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SCNTechnique","kind":"identifier"}],"title":"SCNTechnique","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique","navigatorTitle":[{"kind":"identifier","text":"SCNTechnique"}],"abstract":[{"text":"A specification for augmenting or postprocessing SceneKit’s rendering of a scene using additional drawing passes with custom Metal or OpenGL shaders.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"/documentation/scenekit/scntechnique"},"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/subscript(_:)":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/subscript(_:)","type":"topic","abstract":[{"type":"text","text":"Returns the value associated with the specified GLSL uniform variable or attribute name, using subscript syntax."}],"fragments":[{"kind":"keyword","text":"subscript"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"kind":"symbol","title":"subscript(_:)","url":"/documentation/scenekit/scntechnique/subscript(_:)","role":"symbol","navigatorTitle":[{"text":"objectForKeyedSubscript:","kind":"identifier"}]},"doc://com.apple.documentation/documentation/foundation/nsnumber":{"title":"NSNumber","kind":"symbol","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSNumber","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/foundation/nsnumber","url":"/documentation/foundation/nsnumber","abstract":[{"type":"text","text":"An object wrapper for primitive scalar numeric values."}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3":{"kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector3","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SCNVector3","kind":"identifier"}],"title":"SCNVector3","navigatorTitle":[{"text":"SCNVector3","kind":"identifier"}],"url":"/documentation/scenekit/scnvector3","abstract":[{"type":"text","text":"A representation of a three-component vector."}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/handleBinding(ofSymbol:using:)":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/handleBinding(ofSymbol:using:)","type":"topic","abstract":[{"type":"text","text":"Specifies a block to be called before rendering using programs with the specified GLSL uniform variable or attribute name."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleBinding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofSymbol"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@SCNBindingBlock","text":"SCNBindingBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"handleBinding(ofSymbol:using:)","url":"/documentation/scenekit/scntechnique/handlebinding(ofsymbol:using:)","role":"symbol","navigatorTitle":[{"text":"handleBindingOfSymbol:usingBlock:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"type":"topic","kind":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","url":"/documentation/foundation/nscopying","role":"symbol","title":"NSCopying","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}]},"doc://com.apple.documentation/documentation/foundation/nsvalue":{"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSValue"}],"title":"NSValue","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A simple container for a single C or Objective-C data item."}],"identifier":"doc://com.apple.documentation/documentation/foundation/nsvalue","url":"/documentation/foundation/nsvalue"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"9.0","beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"introducedAt":"9.0","beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"10.11","name":"macOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"9.0","name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"2.0","name":"watchOS","deprecated":false,"unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"setObject:forKeyedSubscript:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setObject:forKeyedSubscript:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/handleBinding(ofSymbol:using:)","doc://com.apple.scenekit/documentation/SceneKit/SCNTechnique/subscript(_:)"],"title":"Handling Parameters for a Technique’s Shader Programs","anchor":"Handling-Parameters-for-a-Techniques-Shader-Programs"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setObject:"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"obj","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forKeyedSubscript:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<NSCopying>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)NSCopying"},{"text":") ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"obj","content":[{"inlineContent":[{"type":"text","text":"An object containing a new value for the shader symbol."}],"type":"paragraph"}]},{"name":"key","content":[{"inlineContent":[{"text":"A shader variable or attribute name used in one of the technique’s shader programs.","type":"text"}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1"},{"op":"replace","value":"setObject:forKeyedSubscript:","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique~1setObject(_:forKeyedSubscript:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setObject:forKeyedSubscript:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique~1setObject(_:forKeyedSubscript:)/fragments"},{"op":"replace","value":"SCNTechnique","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique/title"},{"op":"replace","value":[{"text":"SCNTechnique","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique/fragments"},{"op":"replace","value":[{"text":"SCNTechnique","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique/navigatorTitle"},{"op":"replace","value":"objectForKeyedSubscript:","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique~1subscript(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"objectForKeyedSubscript:"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique~1subscript(_:)/fragments"},{"op":"replace","value":"SCNVector3","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/title"},{"op":"replace","value":[{"kind":"identifier","text":"SCNVector3"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/fragments"},{"value":[{"kind":"identifier","text":"SCNVector3"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/navigatorTitle"},{"value":"handleBindingOfSymbol:usingBlock:","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique~1handleBinding(ofSymbol:using:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleBindingOfSymbol:usingBlock:"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTechnique~1handleBinding(ofSymbol:using:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}