{
  "abstract": [
    {
      "text": "The number of tests in the run.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testCaseCount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTestRun(py)testCaseCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "testCaseCount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "testCaseCount"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "testCaseCount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "testCaseCount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun": {
      "abstract": [
        {
          "text": "A base class for collecting information about a specific execution of a test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestRun"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestRun"
        }
      ],
      "role": "symbol",
      "title": "XCTestRun",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/executionCount": {
      "abstract": [
        {
          "text": "The number of test executions during the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "executionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/executionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executionCount"
        }
      ],
      "role": "symbol",
      "title": "executionCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/executioncount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/failureCount": {
      "abstract": [
        {
          "text": "The number of test failures during the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/failureCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "failureCount"
        }
      ],
      "role": "symbol",
      "title": "failureCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/failurecount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasBeenSkipped": {
      "abstract": [
        {
          "text": "A Boolean value that indicates a skipped test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasBeenSkipped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasBeenSkipped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasBeenSkipped"
        }
      ],
      "role": "symbol",
      "title": "hasBeenSkipped",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/hasbeenskipped"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasSucceeded": {
      "abstract": [
        {
          "text": "A Boolean value that returns true if all tests in the run completed without recording any failures; otherwise, false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasSucceeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasSucceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasSucceeded"
        }
      ],
      "role": "symbol",
      "title": "hasSucceeded",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/hassucceeded"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/skipCount": {
      "abstract": [
        {
          "text": "The number of skipped tests during the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "skipCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/skipCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "skipCount"
        }
      ],
      "role": "symbol",
      "title": "skipCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/skipcount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/test": {
      "abstract": [
        {
          "text": "The test instance for the test run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "test"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTest",
          "text": "XCTest"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/test",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "test"
        }
      ],
      "role": "symbol",
      "title": "test",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/test"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testCaseCount": {
      "abstract": [
        {
          "text": "The number of tests in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCaseCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testCaseCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCaseCount"
        }
      ],
      "role": "symbol",
      "title": "testCaseCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/testcasecount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalFailureCount": {
      "abstract": [
        {
          "text": "The number of test failures and uncaught exceptions during the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalFailureCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalFailureCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalFailureCount"
        }
      ],
      "role": "symbol",
      "title": "totalFailureCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/totalfailurecount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/unexpectedExceptionCount": {
      "abstract": [
        {
          "text": "The number of uncaught exceptions during the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedExceptionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/unexpectedExceptionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unexpectedExceptionCount"
        }
      ],
      "role": "symbol",
      "title": "unexpectedExceptionCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/unexpectedexceptioncount"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Gathering-Test-Outcomes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasSucceeded",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasBeenSkipped",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/executionCount",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/failureCount",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/skipCount",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/test",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalFailureCount",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/unexpectedExceptionCount"
      ],
      "title": "Gathering Test Outcomes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "testCaseCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "testCaseCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Gathering-Test-Outcomes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasSucceeded",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasBeenSkipped",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/executionCount",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/failureCount",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/skipCount",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/test",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalFailureCount",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/unexpectedExceptionCount"
              ],
              "title": "Gathering Test Outcomes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "testCaseCount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1hasSucceeded/title",
          "value": "hasSucceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1hasSucceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasSucceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1failureCount/title",
          "value": "failureCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1failureCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "failureCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/title",
          "value": "XCTestRun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1totalFailureCount/title",
          "value": "totalFailureCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1totalFailureCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalFailureCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1test/title",
          "value": "test"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1test/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "test"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1skipCount/title",
          "value": "skipCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1skipCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "skipCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1hasBeenSkipped/title",
          "value": "hasBeenSkipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1hasBeenSkipped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasBeenSkipped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1testCaseCount/title",
          "value": "testCaseCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1testCaseCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "testCaseCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1executionCount/title",
          "value": "executionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1executionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "executionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1unexpectedExceptionCount/title",
          "value": "unexpectedExceptionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1unexpectedExceptionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unexpectedExceptionCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctestrun/testcasecount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctestrun/testcasecount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
