{"identifier":{"url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinates","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"For the available coordinate index constants, see Channel Coordinate Index Constants.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mCoordinates"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s7Float32a","preciseIdentifier":"s:s7Float32a","text":"Float32"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s7Float32a","preciseIdentifier":"s:s7Float32a","text":"Float32"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s7Float32a","preciseIdentifier":"s:s7Float32a","text":"Float32"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/audiotoolbox/audiopanninginfo/mcoordinates"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/audiotoolbox/audiopanninginfo/mcoordinates"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo"]]},"metadata":{"title":"mCoordinates","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"beta":false}],"navigatorTitle":[{"text":"mCoordinates","kind":"identifier"}],"externalID":"c:@S@AudioPanningInfo@FI@mCoordinates","role":"symbol","modules":[{"name":"Audio Toolbox"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mCoordinates"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:s7Float32a","text":"Float32"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s7Float32a","text":"Float32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s7Float32a","text":"Float32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPanningInfo"}],"navigatorTitle":[{"kind":"identifier","text":"AudioPanningInfo"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo","url":"/documentation/audiotoolbox/audiopanninginfo","abstract":[{"text":"Audio panning information.","type":"text"}],"title":"AudioPanningInfo"},"doc://com.externally.resolved.symbol/c:@T@Float32":{"title":"Float32","abstract":[{"text":"Convenience type that represent a 32-bit floating point number","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@Float32","url":"/documentation/kernel/float32","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.externally.resolved.symbol/s:s7Float32a":{"title":"Float32","abstract":[{"type":"text","text":"A 32-bit floating point type."}],"identifier":"doc://com.externally.resolved.symbol/s:s7Float32a","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Float32"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"type":"topic","role":"symbol","kind":"symbol","url":"/documentation/Swift/Float32"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinates":{"role":"symbol","type":"topic","url":"/documentation/audiotoolbox/audiopanninginfo/mcoordinates","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mCoordinates"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Float32","preciseIdentifier":"s:s7Float32a"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s7Float32a","text":"Float32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s7Float32a","text":"Float32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mCoordinates","kind":"symbol","abstract":[{"text":"For the available coordinate index constants, see Channel Coordinate Index Constants.","type":"text"}],"navigatorTitle":[{"text":"mCoordinates","kind":"identifier"}],"title":"mCoordinates"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"mCoordinates","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"mCoordinates"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"typeIdentifier","text":"Float32","identifier":"doc://com.externally.resolved.symbol/c:@T@Float32","preciseIdentifier":"c:@T@Float32"},{"kind":"text","text":" "},{"kind":"identifier","text":"mCoordinates"},{"kind":"text","text":"["},{"kind":"number","text":"3"},{"kind":"text","text":"];"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/title","op":"replace","value":"AudioPanningInfo"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioPanningInfo"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/navigatorTitle","op":"replace","value":[{"text":"AudioPanningInfo","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mCoordinates/title","op":"replace","value":"mCoordinates"},{"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mCoordinates/fragments","op":"replace","value":[{"kind":"identifier","text":"mCoordinates"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}