{"abstract":[{"text":"A multiplier for audio panning values, typically representing a volume value in the range from 0 to 1. A value of 1 results in audio panning at unity gain. A value of 0 silences all channels.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mGainScale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7Float32a","kind":"typeIdentifier","text":"Float32"}],"platforms":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false},{"beta":false,"deprecated":false,"name":"macOS","unavailable":false},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"deprecated":false,"name":"visionOS","unavailable":false}],"roleHeading":"Instance Property","title":"mGainScale","navigatorTitle":[{"kind":"identifier","text":"mGainScale"}],"symbolKind":"property","role":"symbol","externalID":"c:@S@AudioPanningInfo@FI@mGainScale","modules":[{"name":"Audio Toolbox"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo"]]},"kind":"symbol","identifier":{"url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mGainScale","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["/documentation/audiotoolbox/audiopanninginfo/mgainscale"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/audiotoolbox/audiopanninginfo/mgainscale"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mGainScale","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float32","identifier":"doc://com.externally.resolved.symbol/s:s7Float32a","kind":"typeIdentifier","preciseIdentifier":"s:s7Float32a"}]}],"kind":"declarations"}],"references":{"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.externally.resolved.symbol/c:@T@Float32":{"title":"Float32","abstract":[{"text":"Convenience type that represent a 32-bit floating point number","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@Float32","url":"/documentation/kernel/float32","type":"topic"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPanningInfo"}],"navigatorTitle":[{"kind":"identifier","text":"AudioPanningInfo"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo","url":"/documentation/audiotoolbox/audiopanninginfo","abstract":[{"text":"Audio panning information.","type":"text"}],"title":"AudioPanningInfo"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.externally.resolved.symbol/s:s7Float32a":{"title":"Float32","abstract":[{"type":"text","text":"A 32-bit floating point type."}],"identifier":"doc://com.externally.resolved.symbol/s:s7Float32a","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Float32"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"type":"topic","role":"symbol","kind":"symbol","url":"/documentation/Swift/Float32"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mGainScale":{"title":"mGainScale","abstract":[{"text":"A multiplier for audio panning values, typically representing a volume value in the range from 0 to 1. A value of 1 results in audio panning at unity gain. A value of 0 silences all channels.","type":"text"}],"identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo/mGainScale","url":"/documentation/audiotoolbox/audiopanninginfo/mgainscale","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mGainScale"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mGainScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float32","preciseIdentifier":"s:s7Float32a"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"name":"macOS","deprecated":false},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"mGainScale","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"mGainScale","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioPanningInfo"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"preciseIdentifier":"c:@T@Float32","identifier":"doc://com.externally.resolved.symbol/c:@T@Float32","kind":"typeIdentifier","text":"Float32"},{"kind":"text","text":" "},{"kind":"identifier","text":"mGainScale"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/title","value":"AudioPanningInfo"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/fragments","value":[{"text":"AudioPanningInfo","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo/navigatorTitle","value":[{"text":"AudioPanningInfo","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mGainScale/title","value":"mGainScale"},{"op":"replace","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioPanningInfo~1mGainScale/fragments","value":[{"kind":"identifier","text":"mGainScale"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}