{
  "abstract": [
    {
      "text": "A policy that doesn’t pass through alternate audio tracks from the source asset during export.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling/AVAssetTrackGroupOutputHandlingNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAssetTrackGroupOutputHandling@AVAssetTrackGroupOutputHandlingNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AVAssetTrackGroupOutputHandlingNone"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAssetTrackGroupOutputHandlingNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "AVAssetTrackGroupOutputHandlingNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackGroupOutputHandlingNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Setting this policy tells the session to disregard alternate track group assignments in the original asset.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling": {
      "abstract": [
        {
          "text": "A type that specifies policies for how an export session processes alternate tracks in a track group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetTrackGroupOutputHandling"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackGroupOutputHandling"
        }
      ],
      "role": "symbol",
      "title": "AVAssetTrackGroupOutputHandling",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrackgroupoutputhandling"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling/AVAssetTrackGroupOutputHandlingDefaultPolicy": {
      "abstract": [
        {
          "text": "The default track group output handling policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackGroupOutputHandlingDefaultPolicy"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling/AVAssetTrackGroupOutputHandlingDefaultPolicy",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetTrackGroupOutputHandlingDefaultPolicy",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrackgroupoutputhandling/avassettrackgroupoutputhandlingdefaultpolicy"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling/AVAssetTrackGroupOutputHandlingNone": {
      "abstract": [
        {
          "text": "A policy that doesn’t pass through alternate audio tracks from the source asset during export.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackGroupOutputHandlingNone"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling/AVAssetTrackGroupOutputHandlingNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetTrackGroupOutputHandlingNone",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrackgroupoutputhandling/avassettrackgroupoutputhandlingnone"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling/preserveAlternateTracks": {
      "abstract": [
        {
          "text": "A policy that passes through alternate audio tracks from the source asset during export.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preserveAlternateTracks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAssetTrackGroupOutputHandling",
          "text": "AVAssetTrackGroupOutputHandling"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling/preserveAlternateTracks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackGroupOutputHandlingPreserveAlternateTracks"
        }
      ],
      "role": "symbol",
      "title": "preserveAlternateTracks",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrackgroupoutputhandling/preservealternatetracks"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Policies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling/preserveAlternateTracks",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroupOutputHandling/AVAssetTrackGroupOutputHandlingDefaultPolicy"
      ],
      "title": "Policies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroupOutputHandling~1preserveAlternateTracks/title",
          "value": "AVAssetTrackGroupOutputHandlingPreserveAlternateTracks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroupOutputHandling~1preserveAlternateTracks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackGroupOutputHandlingPreserveAlternateTracks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroupOutputHandling/title",
          "value": "AVAssetTrackGroupOutputHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroupOutputHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackGroupOutputHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroupOutputHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackGroupOutputHandling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avassettrackgroupoutputhandling/avassettrackgroupoutputhandlingnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
