{
  "abstract": [
    {
      "text": "Stores a sample value at the specified index.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerArray"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerArray/setObject:atIndexedSubscript:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLRasterizationRateLayerArray(im)setObject:atIndexedSubscript:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "setObject:atIndexedSubscript:"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setObject:atIndexedSubscript:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setObject:atIndexedSubscript:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setObject:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MTLRasterizationRateLayerDescriptor",
              "text": "MTLRasterizationRateLayerDescriptor"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "layer"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "atIndexedSubscript:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "layerIndex"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The layer descriptor to set",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "layer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The index of the sample you want to set.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "layerIndex"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The method converts the value to a single precision floating point value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerArray": {
      "abstract": [
        {
          "text": "Descriptions for the rasterization rates to apply to the set of layers in a rate map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRasterizationRateLayerArray"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRasterizationRateLayerArray"
        }
      ],
      "role": "symbol",
      "title": "MTLRasterizationRateLayerArray",
      "type": "topic",
      "url": "/documentation/metal/mtlrasterizationratelayerarray"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerArray/setObject:atIndexedSubscript:": {
      "abstract": [
        {
          "text": "Stores a sample value at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setObject:atIndexedSubscript:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerArray/setObject:atIndexedSubscript:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:atIndexedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "setObject:atIndexedSubscript:",
      "type": "topic",
      "url": "/documentation/metal/mtlrasterizationratelayerarray/setobject:atindexedsubscript:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerArray/subscript(_:)": {
      "abstract": [
        {
          "text": "Retrieves the sample value at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLRasterizationRateLayerDescriptor",
          "text": "MTLRasterizationRateLayerDescriptor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerArray/subscript(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectAtIndexedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrasterizationratelayerarray/subscript(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerDescriptor": {
      "abstract": [
        {
          "text": "The minimum rasterization rates to apply to sections of a layer in the render target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRasterizationRateLayerDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRasterizationRateLayerDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRasterizationRateLayerDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrasterizationratelayerdescriptor"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Members-of-the-Array",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerArray/subscript(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLRasterizationRateLayerDescriptor"
      ],
      "title": "Accessing Members of the Array"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRasterizationRateLayerArray/title",
          "value": "MTLRasterizationRateLayerArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRasterizationRateLayerArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRasterizationRateLayerArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRasterizationRateLayerArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRasterizationRateLayerArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRasterizationRateLayerDescriptor/title",
          "value": "MTLRasterizationRateLayerDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRasterizationRateLayerDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRasterizationRateLayerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRasterizationRateLayerDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRasterizationRateLayerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRasterizationRateLayerArray~1subscript(_:)/title",
          "value": "objectAtIndexedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRasterizationRateLayerArray~1subscript(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectAtIndexedSubscript:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlrasterizationratelayerarray/setobject:atindexedsubscript:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
