{
  "abstract": [
    {
      "text": "Returns a new template from the provided text, fill fraction, and ring style.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText/templateWithTextProvider:fillFraction:ringStyle:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLKComplicationTemplateModularSmallRingText(cm)templateWithTextProvider:fillFraction:ringStyle:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "templateWithTextProvider:fillFraction:ringStyle:"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "templateWithTextProvider:fillFraction:ringStyle:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "templateWithTextProvider:fillFraction:ringStyle:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "templateWithTextProvider:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKTextProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLKTextProvider",
              "text": "CLKTextProvider"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "textProvider"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fillFraction:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "fillFraction"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ringStyle:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationRingStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CLKComplicationRingStyle",
              "text": "CLKComplicationRingStyle"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "ringStyle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A text provider for the text in the center of the template. For multicolor faces, like the Utility face, the system uses the text provider’s tint color for the text. For other faces, the system ignores the provided tint color, and uses a system color instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "textProvider"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A value between ",
                  "type": "text"
                },
                {
                  "code": "0.0",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "1.0",
                  "type": "codeVoice"
                },
                {
                  "text": " that indicates how much of the ring fills.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "fillFraction"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ring’s style. For a complete list of styles, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationRingStyle",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ringStyle"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationRingStyle": {
      "abstract": [
        {
          "text": "Constants indicating the appearance of a progress ring.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationRingStyle"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationRingStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationRingStyle"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationRingStyle",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationringstyle"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText": {
      "abstract": [
        {
          "text": "A template for displaying text encircled by a configurable progress ring.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallRingText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallRingText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateModularSmallRingText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatemodularsmallringtext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText/init(textProvider:fillFraction:ringStyle:)": {
      "abstract": [
        {
          "text": "Creates a new template from the provided text, fill fraction, and ring style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "textProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fillFraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ringStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLKComplicationRingStyle",
          "text": "CLKComplicationRingStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText/init(textProvider:fillFraction:ringStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTextProvider:fillFraction:ringStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(textProvider:fillFraction:ringStyle:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatemodularsmallringtext/init(textprovider:fillfraction:ringstyle:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText/templateWithTextProvider:fillFraction:ringStyle:": {
      "abstract": [
        {
          "text": "Returns a new template from the provided text, fill fraction, and ring style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "templateWithTextProvider:fillFraction:ringStyle:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText/templateWithTextProvider:fillFraction:ringStyle:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateWithTextProvider:fillFraction:ringStyle:"
        }
      ],
      "role": "symbol",
      "title": "templateWithTextProvider:fillFraction:ringStyle:",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatemodularsmallringtext/templatewithtextprovider:fillfraction:ringstyle:"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKTextProvider": {
      "abstract": [
        {
          "text": "The common behavior for displaying text-based data in a complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKTextProvider"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKTextProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKTextProvider"
        }
      ],
      "role": "symbol",
      "title": "CLKTextProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clktextprovider"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-the-Template",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText/init(textProvider:fillFraction:ringStyle:)"
      ],
      "title": "Creating the Template"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationRingStyle/title",
          "value": "CLKComplicationRingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationRingStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationRingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationRingStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationRingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKTextProvider/title",
          "value": "CLKTextProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKTextProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKTextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKTextProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKTextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingText/title",
          "value": "CLKComplicationTemplateModularSmallRingText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallRingText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallRingText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingText~1init(textProvider:fillFraction:ringStyle:)/title",
          "value": "initWithTextProvider:fillFraction:ringStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingText~1init(textProvider:fillFraction:ringStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTextProvider:fillFraction:ringStyle:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationtemplatemodularsmallringtext/templatewithtextprovider:fillfraction:ringstyle:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
