{
  "abstract": [
    {
      "text": "A ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " structure containing information on the Cb component of the buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoCb"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@CVPlanarPixelBufferInfo_YCbCrPlanar@FI@componentInfoCb",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "componentInfoCb"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CVPlanarComponentInfo",
        "text": "CVPlanarComponentInfo"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "componentInfoCb"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "componentInfoCb"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "componentInfoCb"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CVPlanarComponentInfo",
              "text": "CVPlanarComponentInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo": {
      "abstract": [
        {
          "text": "A structure for describing planar components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPlanarComponentInfo"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPlanarComponentInfo"
        }
      ],
      "role": "symbol",
      "title": "CVPlanarComponentInfo",
      "type": "topic",
      "url": "/documentation/corevideo/cvplanarcomponentinfo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar": {
      "abstract": [
        {
          "text": "A structure for describing YCbCr planar buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPlanarPixelBufferInfo_YCbCrPlanar"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVPlanarPixelBufferInfo_YCbCrPlanar"
        }
      ],
      "role": "symbol",
      "title": "CVPlanarPixelBufferInfo_YCbCrPlanar",
      "type": "topic",
      "url": "/documentation/corevideo/cvplanarpixelbufferinfo_ycbcrplanar"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoCb": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure containing information on the Cb component of the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "componentInfoCb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CVPlanarComponentInfo",
          "text": "CVPlanarComponentInfo"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoCb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "componentInfoCb"
        }
      ],
      "role": "symbol",
      "title": "componentInfoCb",
      "type": "topic",
      "url": "/documentation/corevideo/cvplanarpixelbufferinfo_ycbcrplanar/componentinfocb"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoCr": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure containing information on the Cr component of the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "componentInfoCr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CVPlanarComponentInfo",
          "text": "CVPlanarComponentInfo"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoCr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "componentInfoCr"
        }
      ],
      "role": "symbol",
      "title": "componentInfoCr",
      "type": "topic",
      "url": "/documentation/corevideo/cvplanarpixelbufferinfo_ycbcrplanar/componentinfocr"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoY": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure containing information on the Y component of the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "componentInfoY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CVPlanarComponentInfo",
          "text": "CVPlanarComponentInfo"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "componentInfoY"
        }
      ],
      "role": "symbol",
      "title": "componentInfoY",
      "type": "topic",
      "url": "/documentation/corevideo/cvplanarpixelbufferinfo_ycbcrplanar/componentinfoy"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoCr",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoY"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "componentInfoCb"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "componentInfoCb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoCr",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarPixelBufferInfo_YCbCrPlanar/componentInfoY"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVPlanarComponentInfo",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CVPlanarComponentInfo",
                    "text": "CVPlanarComponentInfo"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "componentInfoCb"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar/title",
          "value": "CVPlanarPixelBufferInfo_YCbCrPlanar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarPixelBufferInfo_YCbCrPlanar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarPixelBufferInfo_YCbCrPlanar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar~1componentInfoCr/title",
          "value": "componentInfoCr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar~1componentInfoCr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "componentInfoCr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarComponentInfo/title",
          "value": "CVPlanarComponentInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarComponentInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarComponentInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarComponentInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVPlanarComponentInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar~1componentInfoY/title",
          "value": "componentInfoY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar~1componentInfoY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "componentInfoY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar~1componentInfoCb/title",
          "value": "componentInfoCb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVPlanarPixelBufferInfo_YCbCrPlanar~1componentInfoCb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "componentInfoCb"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvplanarpixelbufferinfo_ycbcrplanar/componentinfocb"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvplanarpixelbufferinfo_ycbcrplanar/componentinfocb"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
