{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completion:",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter",
        "doc://com.apple.matter/documentation/Matter/MTRBaseClusterThermostatUserInterfaceConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterThermostatUserInterfaceConfiguration/readAttributeKeypadLockout(withAttributeCache:endpoint:queue:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Matter",
    "externalID": "c:objc(cs)MTRBaseClusterThermostatUserInterfaceConfiguration(cm)readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "readAttributeKeypadLockout"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withAttributeCache"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MTRAttributeCacheContainer",
        "text": "MTRAttributeCacheContainer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "endpoint"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "queue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@dispatch_queue_t",
        "text": "dispatch_queue_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "?, (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completion:",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completion:",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completion:",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.3",
        "introducedAt": "13.0",
        "message": "Please use readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completion:",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.4",
        "introducedAt": "16.1",
        "message": "Please use readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completion:",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please use readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completion:",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.4",
        "introducedAt": "9.1",
        "message": "Please use readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completion:",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "readAttributeKeypadLockout(withAttributeCache:endpoint:queue:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "readAttributeKeypadLockout"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withAttributeCache"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attributeCacheContainer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.matter/documentation/Matter/MTRAttributeCacheContainer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MTRAttributeCacheContainer",
              "text": "MTRAttributeCacheContainer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "endpoint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "?, (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "readAttributeKeypadLockout"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withAttributeCache"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attributeCacheContainer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.matter/documentation/Matter/MTRAttributeCacheContainer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MTRAttributeCacheContainer",
              "text": "MTRAttributeCacheContainer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "endpoint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can call this method from synchronous code using a completion handler, as shown on this page, or you can call it as an asynchronous method that has the following declaration:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "code": [
                "class func readAttributeKeypadLockout(withAttributeCache attributeCacheContainer: MTRAttributeCacheContainer, endpoint: NSNumber, queue: dispatch_queue_t) async throws -> NSNumber"
              ],
              "syntax": "swift",
              "type": "codeListing"
            },
            {
              "inlineContent": [
                {
                  "text": "For information about concurrency and asynchronous code in Swift, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Concurrency Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously": {
      "abstract": [
        {
          "text": "Learn how functions and methods that take a completion handler are converted to Swift asynchronous functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
      "kind": "article",
      "role": "article",
      "title": "Calling Objective-C APIs Asynchronously",
      "type": "topic",
      "url": "/documentation/Swift/calling-objective-c-apis-asynchronously"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRAttributeCacheContainer": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRAttributeCacheContainer"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRAttributeCacheContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRAttributeCacheContainer"
        }
      ],
      "role": "symbol",
      "title": "MTRAttributeCacheContainer",
      "type": "topic",
      "url": "/documentation/matter/mtrattributecachecontainer"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterThermostatUserInterfaceConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRBaseClusterThermostatUserInterfaceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterThermostatUserInterfaceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBaseClusterThermostatUserInterfaceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "MTRBaseClusterThermostatUserInterfaceConfiguration",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterthermostatuserinterfaceconfiguration"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseClusterThermostatUserInterfaceConfiguration/readAttributeKeypadLockout(withAttributeCache:endpoint:queue:completionHandler:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributeKeypadLockout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAttributeCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRAttributeCacheContainer",
          "text": "MTRAttributeCacheContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseClusterThermostatUserInterfaceConfiguration/readAttributeKeypadLockout(withAttributeCache:endpoint:queue:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readAttributeKeypadLockout(withAttributeCache:endpoint:queue:completionHandler:)",
      "type": "topic",
      "url": "/documentation/matter/mtrbaseclusterthermostatuserinterfaceconfiguration/readattributekeypadlockout(withattributecache:endpoint:queue:completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/Dispatch/dispatch_queue_t"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.3",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.4",
              "introducedAt": "16.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.4",
              "introducedAt": "9.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter",
                "doc://com.apple.matter/documentation/Matter/MTRBaseClusterThermostatUserInterfaceConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "readAttributeKeypadLockoutWithAttributeCache:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRAttributeCacheContainer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRAttributeCacheContainer",
                    "text": "MTRAttributeCacheContainer"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "attributeCacheContainer"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "endpoint:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSNumber",
                    "text": "NSNumber"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "endpoint"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "queue:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@dispatch_queue_t",
                    "text": "dispatch_queue_t"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "queue"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSNumber",
                    "text": "NSNumber"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completion:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeCacheContainer/title",
          "value": "MTRAttributeCacheContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeCacheContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAttributeCacheContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeCacheContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAttributeCacheContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue",
              "text": "NSObject<OS_dispatch_queue>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterThermostatUserInterfaceConfiguration~1readAttributeKeypadLockout(withAttributeCache:endpoint:queue:completionHandler:)/title",
          "value": "readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterThermostatUserInterfaceConfiguration~1readAttributeKeypadLockout(withAttributeCache:endpoint:queue:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readAttributeKeypadLockoutWithAttributeCache:endpoint:queue:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterThermostatUserInterfaceConfiguration/title",
          "value": "MTRBaseClusterThermostatUserInterfaceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterThermostatUserInterfaceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterThermostatUserInterfaceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseClusterThermostatUserInterfaceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseClusterThermostatUserInterfaceConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrbaseclusterthermostatuserinterfaceconfiguration/readattributekeypadlockout(withattributecache:endpoint:queue:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrbaseclusterthermostatuserinterfaceconfiguration/readattributekeypadlockout(withattributecache:endpoint:queue:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
