{
  "abstract": [
    {
      "text": "The pasteboard that stores data to move as the result of a drag operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/drag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSPasteboardNameDrag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "drag"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPasteboard",
        "text": "NSPasteboard"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSPasteboardName",
        "text": "Name"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPasteboardNameDrag"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "drag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "drag"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPasteboard",
              "text": "NSPasteboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPasteboardName",
              "text": "Name"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard": {
      "abstract": [
        {
          "text": "An object that transfers data to and from the pasteboard server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboard"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboard"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct": {
      "abstract": [
        {
          "text": "Constants that represent the standard pasteboard names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard.Name",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/name-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/drag": {
      "abstract": [
        {
          "text": "The pasteboard that stores data to move as the result of a drag operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/drag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardNameDrag"
        }
      ],
      "role": "symbol",
      "title": "drag",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/name-swift.struct/drag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/find": {
      "abstract": [
        {
          "text": "The pasteboard that holds information about the current state of the active application’s find panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "find"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/find",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardNameFind"
        }
      ],
      "role": "symbol",
      "title": "find",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/name-swift.struct/find"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/font": {
      "abstract": [
        {
          "text": "The pasteboard that holds font and character information and supports Copy Font and Paste Font commands that the text editor may implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "font"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/font",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardNameFont"
        }
      ],
      "role": "symbol",
      "title": "font",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/name-swift.struct/font"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/general": {
      "abstract": [
        {
          "text": "The pasteboard you use to perform ordinary cut, copy, and paste operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "general"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/general",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardNameGeneral"
        }
      ],
      "role": "symbol",
      "title": "general",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/name-swift.struct/general"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/ruler": {
      "abstract": [
        {
          "text": "The pasteboard that holds information about paragraph formats and supports the Copy Ruler and Paste Ruler commands that the text editor may implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ruler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/ruler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardNameRuler"
        }
      ],
      "role": "symbol",
      "title": "ruler",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/name-swift.struct/ruler"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Named-Pasteboards",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/find",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/font",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/general",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/ruler"
      ],
      "title": "Named Pasteboards"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPasteboardNameDrag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardNameDrag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Named-Pasteboards",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/find",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/font",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/general",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct/ruler"
              ],
              "title": "Named Pasteboards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/Name-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSPasteboardName",
                    "text": "NSPasteboardName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPasteboardNameDrag"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/title",
          "value": "NSPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct~1ruler/title",
          "value": "NSPasteboardNameRuler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct~1ruler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardNameRuler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct~1drag/title",
          "value": "NSPasteboardNameDrag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct~1drag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardNameDrag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct~1general/title",
          "value": "NSPasteboardNameGeneral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct~1general/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardNameGeneral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct~1font/title",
          "value": "NSPasteboardNameFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct~1font/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardNameFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct/title",
          "value": "NSPasteboardName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct~1find/title",
          "value": "NSPasteboardNameFind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1Name-swift.struct~1find/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardNameFind"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspasteboard/name-swift.struct/drag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nspasteboard/name-swift.struct/drag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
