{
  "abstract": [
    {
      "text": "An offset date style.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "On watchOS 9.0 or later, use WidgetKit instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/offset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLKRelativeDateStyle@CLKRelativeDateStyleOffset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "offset"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLKRelativeDateStyleOffset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "message": "On watchOS 9.0 or later, use WidgetKit instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CLKRelativeDateStyle.offset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "offset"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The resulting value gives the time offset using a single key unit. For example, values might be “10 hours”, or “9 minutes” depending on the total amount of time between the current date and the date you specified.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle": {
      "abstract": [
        {
          "text": "Constants indicating the formatting style for the relative date values.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKRelativeDateStyle"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKRelativeDateStyle"
        }
      ],
      "role": "symbol",
      "title": "CLKRelativeDateStyle",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatestyle"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/natural": {
      "abstract": [
        {
          "text": "A natural date style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "natural"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/natural",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKRelativeDateStyleNatural"
        }
      ],
      "role": "symbol",
      "title": "CLKRelativeDateStyle.natural",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatestyle/natural"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/naturalAbbreviated": {
      "abstract": [
        {
          "text": "An abbreviated, natural date style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalAbbreviated"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/naturalAbbreviated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKRelativeDateStyleNaturalAbbreviated"
        }
      ],
      "role": "symbol",
      "title": "CLKRelativeDateStyle.naturalAbbreviated",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatestyle/naturalabbreviated"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/naturalFull": {
      "abstract": [
        {
          "text": "A natural date style using unabbreviated units, when possible.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalFull"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/naturalFull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKRelativeDateStyleNaturalFull"
        }
      ],
      "role": "symbol",
      "title": "CLKRelativeDateStyle.naturalFull",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatestyle/naturalfull"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/offset": {
      "abstract": [
        {
          "text": "An offset date style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offset"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/offset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKRelativeDateStyleOffset"
        }
      ],
      "role": "symbol",
      "title": "CLKRelativeDateStyle.offset",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatestyle/offset"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/offsetShort": {
      "abstract": [
        {
          "text": "A short offset date style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offsetShort"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/offsetShort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKRelativeDateStyleOffsetShort"
        }
      ],
      "role": "symbol",
      "title": "CLKRelativeDateStyle.offsetShort",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatestyle/offsetshort"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/timer": {
      "abstract": [
        {
          "text": "A timer style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timer"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/timer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKRelativeDateStyleTimer"
        }
      ],
      "role": "symbol",
      "title": "CLKRelativeDateStyle.timer",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatestyle/timer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Date-Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/natural",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/naturalAbbreviated",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/naturalFull",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/offsetShort",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/timer"
      ],
      "title": "Date Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLKRelativeDateStyleOffset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyleOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Date-Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/natural",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/naturalAbbreviated",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/naturalFull",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/offsetShort",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle/timer"
              ],
              "title": "Date Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CLKRelativeDateStyleOffset"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "On watchOS 9.0 or later, use WidgetKit instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1offsetShort/title",
          "value": "CLKRelativeDateStyleOffsetShort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1offsetShort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyleOffsetShort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle/title",
          "value": "CLKRelativeDateStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1naturalAbbreviated/title",
          "value": "CLKRelativeDateStyleNaturalAbbreviated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1naturalAbbreviated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyleNaturalAbbreviated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1natural/title",
          "value": "CLKRelativeDateStyleNatural"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1natural/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyleNatural"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1timer/title",
          "value": "CLKRelativeDateStyleTimer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1timer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyleTimer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1offset/title",
          "value": "CLKRelativeDateStyleOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1offset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyleOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1naturalFull/title",
          "value": "CLKRelativeDateStyleNaturalFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle~1naturalFull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyleNaturalFull"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkrelativedatestyle/offset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkrelativedatestyle/offset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
