{
  "abstract": [
    {
      "text": "A measurement of the goal in feet.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/foot"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INWorkoutGoalUnitType@INWorkoutGoalUnitTypeFoot",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "foot"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INWorkoutGoalUnitTypeFoot"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INWorkoutGoalUnitType.foot"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "foot"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType": {
      "abstract": [
        {
          "text": "Describes the unit of measure with constants for a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitType"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/foot": {
      "abstract": [
        {
          "text": "A measurement of the goal in feet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foot"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/foot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeFoot"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.foot",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/foot"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/hour": {
      "abstract": [
        {
          "text": "A measurement of the goal in hours.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hour"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/hour",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeHour"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.hour",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/hour"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/inch": {
      "abstract": [
        {
          "text": "A measurement of the goal in inches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/inch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeInch"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.inch",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/inch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/joule": {
      "abstract": [
        {
          "text": "A measurement of the goal in joules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "joule"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/joule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeJoule"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.joule",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/joule"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/kiloCalorie": {
      "abstract": [
        {
          "text": "A measurement of the goal in kilo caleries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kiloCalorie"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/kiloCalorie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeKiloCalorie"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.kiloCalorie",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/kilocalorie"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/meter": {
      "abstract": [
        {
          "text": "A measurement of the goal in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meter"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/meter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeMeter"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.meter",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/meter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/mile": {
      "abstract": [
        {
          "text": "A measurement of the goal in miles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mile"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/mile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeMile"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.mile",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/mile"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/minute": {
      "abstract": [
        {
          "text": "A measurement of the goal in minutes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minute"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/minute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeMinute"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.minute",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/minute"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/second": {
      "abstract": [
        {
          "text": "A measurement of the goal in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "second"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/second",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeSecond"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.second",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/second"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/unknown": {
      "abstract": [
        {
          "text": "An unknown unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.unknown",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/unknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/yard": {
      "abstract": [
        {
          "text": "A measurement of the goal in yards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yard"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/yard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutGoalUnitTypeYard"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutGoalUnitType.yard",
      "type": "topic",
      "url": "/documentation/intents/inworkoutgoalunittype/yard"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/inch",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/meter",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/mile",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/yard",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/second",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/minute",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/hour",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/joule",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/kiloCalorie"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INWorkoutGoalUnitTypeFoot"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeFoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/inch",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/meter",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/mile",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/yard",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/second",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/minute",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/hour",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/joule",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutGoalUnitType/kiloCalorie"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INWorkoutGoalUnitTypeFoot"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1minute/title",
          "value": "INWorkoutGoalUnitTypeMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1minute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1unknown/title",
          "value": "INWorkoutGoalUnitTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1joule/title",
          "value": "INWorkoutGoalUnitTypeJoule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1joule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeJoule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1inch/title",
          "value": "INWorkoutGoalUnitTypeInch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1inch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeInch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType/title",
          "value": "INWorkoutGoalUnitType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1foot/title",
          "value": "INWorkoutGoalUnitTypeFoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1foot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeFoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1yard/title",
          "value": "INWorkoutGoalUnitTypeYard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1yard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeYard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1meter/title",
          "value": "INWorkoutGoalUnitTypeMeter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1meter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeMeter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1hour/title",
          "value": "INWorkoutGoalUnitTypeHour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1hour/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeHour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1kiloCalorie/title",
          "value": "INWorkoutGoalUnitTypeKiloCalorie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1kiloCalorie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeKiloCalorie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1mile/title",
          "value": "INWorkoutGoalUnitTypeMile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1mile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeMile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1second/title",
          "value": "INWorkoutGoalUnitTypeSecond"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutGoalUnitType~1second/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutGoalUnitTypeSecond"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inworkoutgoalunittype/foot"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inworkoutgoalunittype/foot"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
