{"identifier":{"url":"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerWillBeginPresenting(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","seeAlsoSections":[{"title":"Responding to continuity device events","identifiers":["doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidCancel(_:)","doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePicker(_:didConnect:)","doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidEndPresenting(_:)"],"generated":true,"anchor":"Responding-to-continuity-device-events"}],"metadata":{"symbolKind":"method","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"17.0"}],"role":"symbol","externalID":"c:objc(pl)AVContinuityDevicePickerViewControllerDelegate(im)continuityDevicePickerWillBeginPresenting:","roleHeading":"Instance Method","modules":[{"name":"AVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"continuityDevicePickerWillBeginPresenting"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVContinuityDevicePickerViewController","text":"AVContinuityDevicePickerViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"continuityDevicePickerWillBeginPresenting:"}],"title":"continuityDevicePickerWillBeginPresenting(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate/continuitydevicepickerwillbeginpresenting(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate/continuitydevicepickerwillbeginpresenting(_:)"]}],"abstract":[{"type":"text","text":"Informs the delegate that a continuity device picker is about to present its UI so that a person can select and connect a continuity device."}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"continuityDevicePickerWillBeginPresenting","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pickerViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController","text":"AVContinuityDevicePickerViewController","preciseIdentifier":"c:objc(cs)AVContinuityDevicePickerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["tvOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"pickerViewController","content":[{"type":"paragraph","inlineContent":[{"text":"The continuity device picker that’s informing the delegate.","type":"text"}]}]}],"kind":"parameters"}],"references":{"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController":{"title":"AVContinuityDevicePickerViewController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AVContinuityDevicePickerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A view controller that provides an interface to a person so they can select and connect a continuity device to the system."}],"url":"/documentation/avkit/avcontinuitydevicepickerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"AVContinuityDevicePickerViewController"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController","kind":"symbol","role":"symbol"},"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidCancel(_:)":{"kind":"symbol","navigatorTitle":[{"text":"continuityDevicePickerDidCancel:","kind":"identifier"}],"abstract":[{"type":"text","text":"Informs the delegate when a person declines to select a continuity device by dismissing an app’s continuity device picker."}],"type":"topic","url":"/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate/continuitydevicepickerdidcancel(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"continuityDevicePickerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVContinuityDevicePickerViewController","text":"AVContinuityDevicePickerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"continuityDevicePickerDidCancel(_:)","identifier":"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidCancel(_:)"},"doc://com.apple.avkit/documentation/AVKit":{"identifier":"doc://com.apple.avkit/documentation/AVKit","type":"topic","url":"/documentation/avkit","abstract":[{"type":"text","text":"Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions."}],"kind":"symbol","title":"AVKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","role":"overview"},"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate":{"navigatorTitle":[{"text":"AVContinuityDevicePickerViewControllerDelegate","kind":"identifier"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate","kind":"symbol","abstract":[{"type":"text","text":"An interface that responds to events from a continuity device picker view controller."}],"url":"/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate","role":"symbol","title":"AVContinuityDevicePickerViewControllerDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVContinuityDevicePickerViewControllerDelegate","kind":"identifier"}]},"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidEndPresenting(_:)":{"title":"continuityDevicePickerDidEndPresenting(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"continuityDevicePickerDidEndPresenting"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVContinuityDevicePickerViewController","preciseIdentifier":"c:objc(cs)AVContinuityDevicePickerViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Informs the delegate that a continuity device picker is no longer presenting its UI to a person."}],"url":"/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate/continuitydevicepickerdidendpresenting(_:)","navigatorTitle":[{"kind":"identifier","text":"continuityDevicePickerDidEndPresenting:"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidEndPresenting(_:)","kind":"symbol","role":"symbol"},"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePicker(_:didConnect:)":{"type":"topic","title":"continuityDevicePicker(_:didConnect:)","url":"/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate/continuitydevicepicker(_:didconnect:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"continuityDevicePicker:didConnectDevice:","kind":"identifier"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePicker(_:didConnect:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"continuityDevicePicker","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVContinuityDevicePickerViewController","text":"AVContinuityDevicePickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didConnect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVContinuityDevice","text":"AVContinuityDevice","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Informs the delegate when a person selects and connects a continuity device to the system with a continuity device picker."}]},"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerWillBeginPresenting(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"continuityDevicePickerWillBeginPresenting"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVContinuityDevicePickerViewController","text":"AVContinuityDevicePickerViewController"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","url":"/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate/continuitydevicepickerwillbeginpresenting(_:)","abstract":[{"text":"Informs the delegate that a continuity device picker is about to present its UI so that a person can select and connect a continuity device.","type":"text"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerWillBeginPresenting(_:)","navigatorTitle":[{"kind":"identifier","text":"continuityDevicePickerWillBeginPresenting:"}],"title":"continuityDevicePickerWillBeginPresenting(_:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"continuityDevicePickerWillBeginPresenting:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"continuityDevicePickerWillBeginPresenting:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidCancel(_:)","doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePicker(_:didConnect:)","doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidEndPresenting(_:)"],"title":"Responding to continuity device events","generated":true,"anchor":"Responding-to-continuity-device-events"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"platforms":["tvOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"continuityDevicePickerWillBeginPresenting:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVContinuityDevicePickerViewController","text":"AVContinuityDevicePickerViewController","identifier":"doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pickerViewController","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"pickerViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The continuity device picker that’s informing the delegate."}]}]}]},"path":"/primaryContentSections/1"},{"value":"AVContinuityDevicePickerViewController","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/title","op":"replace"},{"value":[{"text":"AVContinuityDevicePickerViewController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVContinuityDevicePickerViewController"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/navigatorTitle","op":"replace"},{"value":"continuityDevicePickerDidCancel:","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerDidCancel(_:)/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerDidCancel(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"continuityDevicePickerDidCancel:"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/title","op":"replace","value":"AVContinuityDevicePickerViewControllerDelegate"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/fragments","op":"replace","value":[{"text":"AVContinuityDevicePickerViewControllerDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AVContinuityDevicePickerViewControllerDelegate"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerDidEndPresenting(_:)/title","op":"replace","value":"continuityDevicePickerDidEndPresenting:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerDidEndPresenting(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"continuityDevicePickerDidEndPresenting:"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePicker(_:didConnect:)/title","op":"replace","value":"continuityDevicePicker:didConnectDevice:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePicker(_:didConnect:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"continuityDevicePicker:didConnectDevice:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerWillBeginPresenting(_:)/title","op":"replace","value":"continuityDevicePickerWillBeginPresenting:"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerWillBeginPresenting(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"continuityDevicePickerWillBeginPresenting:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}