{
  "abstract": [
    {
      "text": "An object that represents the state of the collaboration options for the document.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SWCollaborationShareOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SWCollaborationShareOptions"
      }
    ],
    "modules": [
      {
        "name": "Shared With You Core"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SWCollaborationShareOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SWCollaborationShareOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SWCollaborationShareOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-custom-collaboration-to-your-app"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-custom-collaboration-to-your-app": {
      "abstract": [
        {
          "text": "Integrate your custom collaboration app with Messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-custom-collaboration-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding custom collaboration to your app",
      "type": "topic",
      "url": "/documentation/sharedwithyou/adding-custom-collaboration-to-your-app"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You Core",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWAction": {
      "abstract": [
        {
          "text": "An object that represents a collaboration action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWAction"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAction"
        }
      ],
      "role": "symbol",
      "title": "SWAction",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swaction"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationActionHandler": {
      "abstract": [
        {
          "text": "A delegate to handle incoming collaboration actions from a collaboration coordinator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationActionHandler"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationActionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationActionHandler"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationActionHandler",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationactionhandler"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationCoordinator": {
      "abstract": [
        {
          "text": "An object that contains the shared collaboration coordinator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationCoordinator"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationCoordinator"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationCoordinator",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationcoordinator"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for a collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationIdentifier",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationidentifier"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationMetadata": {
      "abstract": [
        {
          "text": "A model object for conveying data during a collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationMetadata"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationMetadata"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationMetadata",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationmetadata"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOption": {
      "abstract": [
        {
          "text": "An object that determines how the system shares a document in a collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationOption"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationOption"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationOption",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationoption"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsGroup": {
      "abstract": [
        {
          "text": "An object that represents a group of collaboration options that the system displays together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationOptionsGroup"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationOptionsGroup"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationOptionsGroup",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationoptionsgroup"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsPickerGroup": {
      "abstract": [
        {
          "text": "An object that represents a group of collaboration options that the system displays together with mutually exclusive options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationOptionsPickerGroup"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsPickerGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationOptionsPickerGroup"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationOptionsPickerGroup",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationoptionspickergroup"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions": {
      "abstract": [
        {
          "text": "An object that represents the state of the collaboration options for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationShareOptions"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationShareOptions"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationShareOptions",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(coder:)": {
      "abstract": [
        {
          "text": "Creates and initializes a collaboration share options object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/init(coder:)"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:)": {
      "abstract": [
        {
          "text": "Creates and initializes a collaboration share options object with the array of groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "optionsGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SWCollaborationOptionsGroup",
          "text": "SWCollaborationOptionsGroup"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOptionsGroups:"
        }
      ],
      "role": "symbol",
      "title": "init(optionsGroups:)",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/init(optionsgroups:)"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:summary:)": {
      "abstract": [
        {
          "text": "Creates and initializes a collaboration share options object the array of groups and a summary string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "optionsGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SWCollaborationOptionsGroup",
          "text": "SWCollaborationOptionsGroup"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "summary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:summary:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOptionsGroups:summary:"
        }
      ],
      "role": "symbol",
      "title": "init(optionsGroups:summary:)",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/init(optionsgroups:summary:)"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/optionsGroups": {
      "abstract": [
        {
          "text": "An array of options group objects to customize how the system shares the collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionsGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SWCollaborationOptionsGroup",
          "text": "SWCollaborationOptionsGroup"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/optionsGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionsGroups"
        }
      ],
      "role": "symbol",
      "title": "optionsGroups",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/optionsgroups"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:": {
      "abstract": [
        {
          "text": "Creates and initializes a collaboration share options object with the array of groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "shareOptionsWithOptionsGroups:"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shareOptionsWithOptionsGroups:"
        }
      ],
      "role": "symbol",
      "title": "shareOptionsWithOptionsGroups:",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/shareoptionswithoptionsgroups:"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:summary:": {
      "abstract": [
        {
          "text": "Creates and initializes a collaboration share options object the array of groups and a summary string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "shareOptionsWithOptionsGroups:summary:"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:summary:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shareOptionsWithOptionsGroups:summary:"
        }
      ],
      "role": "symbol",
      "title": "shareOptionsWithOptionsGroups:summary:",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/shareoptionswithoptionsgroups:summary:"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/summary": {
      "abstract": [
        {
          "text": "A localized string to summarize the collaboration options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "summary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/summary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "summary"
        }
      ],
      "role": "symbol",
      "title": "summary",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/summary"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWLocalCollaborationIdentifier": {
      "abstract": [
        {
          "text": "A local identifier for a collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWLocalCollaborationIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWLocalCollaborationIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWLocalCollaborationIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SWLocalCollaborationIdentifier",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swlocalcollaborationidentifier"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWPerson": {
      "abstract": [
        {
          "text": "An object that tracks participants in a collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWPerson"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWPerson"
        }
      ],
      "role": "symbol",
      "title": "SWPerson",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swperson"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction": {
      "abstract": [
        {
          "text": "An object that represents the first action sent to an app when the user shares a collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWStartCollaborationAction"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWStartCollaborationAction"
        }
      ],
      "role": "symbol",
      "title": "SWStartCollaborationAction",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swstartcollaborationaction"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWUpdateCollaborationParticipantsAction": {
      "abstract": [
        {
          "text": "An action that contains the cryptographic identities the system uses to add to or remove from an existing collaboration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWUpdateCollaborationParticipantsAction"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWUpdateCollaborationParticipantsAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWUpdateCollaborationParticipantsAction"
        }
      ],
      "role": "symbol",
      "title": "SWUpdateCollaborationParticipantsAction",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swupdatecollaborationparticipantsaction"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SharedWithYouCoreVersionNumber": {
      "abstract": [
        {
          "text": "Project version number for Shared with You Core.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SharedWithYouCoreVersionNumber"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SharedWithYouCoreVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "SharedWithYouCoreVersionNumber",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/sharedwithyoucoreversionnumber"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SharedWithYouCoreVersionString": {
      "abstract": [
        {
          "text": "Project version string for Shared with You Core.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SharedWithYouCoreVersionString"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SharedWithYouCoreVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "SharedWithYouCoreVersionString",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/sharedwithyoucoreversionstring"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/UTCollaborationOptionsTypeIdentifier": {
      "abstract": [
        {
          "text": "A string constant for the options type identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UTCollaborationOptionsTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/UTCollaborationOptionsTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UTCollaborationOptionsTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UTCollaborationOptionsTypeIdentifier",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/utcollaborationoptionstypeidentifier"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWAction",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationActionHandler",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationCoordinator",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationIdentifier",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationMetadata",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOption",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsGroup",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsPickerGroup",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWLocalCollaborationIdentifier",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWPerson",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWUpdateCollaborationParticipantsAction",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/UTCollaborationOptionsTypeIdentifier"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-share-options",
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(coder:)",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:)",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:summary:)"
      ],
      "title": "Creating share options"
    },
    {
      "anchor": "Accessing-options-attributes",
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/optionsGroups",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/summary"
      ],
      "title": "Accessing options attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SWCollaborationShareOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationShareOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationShareOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-share-options",
              "identifiers": [
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(coder:)",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:)",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:summary:)",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:summary:"
              ],
              "title": "Creating share options"
            },
            {
              "anchor": "Accessing-options-attributes",
              "identifiers": [
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/optionsGroups",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/summary"
              ],
              "title": "Accessing options attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWAction",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationActionHandler",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationCoordinator",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationIdentifier",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationMetadata",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOption",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsGroup",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsPickerGroup",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWLocalCollaborationIdentifier",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWPerson",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWStartCollaborationAction",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWUpdateCollaborationParticipantsAction",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SharedWithYouCoreVersionNumber",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SharedWithYouCoreVersionString",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/UTCollaborationOptionsTypeIdentifier"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SWCollaborationShareOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWStartCollaborationAction/title",
          "value": "SWStartCollaborationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWStartCollaborationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWStartCollaborationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWStartCollaborationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWStartCollaborationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationActionHandler/title",
          "value": "SWCollaborationActionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationActionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationActionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationActionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationActionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOptionsGroup/title",
          "value": "SWCollaborationOptionsGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOptionsGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationOptionsGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOptionsGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationOptionsGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1optionsGroups/title",
          "value": "optionsGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1optionsGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "optionsGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(optionsGroups:summary:)/title",
          "value": "initWithOptionsGroups:summary:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(optionsGroups:summary:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOptionsGroups:summary:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationMetadata/title",
          "value": "SWCollaborationMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationIdentifier/title",
          "value": "SWCollaborationIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWLocalCollaborationIdentifier/title",
          "value": "SWLocalCollaborationIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWLocalCollaborationIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWLocalCollaborationIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWLocalCollaborationIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWLocalCollaborationIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOption/title",
          "value": "SWCollaborationOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWPerson/title",
          "value": "SWPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1UTCollaborationOptionsTypeIdentifier/title",
          "value": "UTCollaborationOptionsTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1UTCollaborationOptionsTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UTCollaborationOptionsTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOptionsPickerGroup/title",
          "value": "SWCollaborationOptionsPickerGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOptionsPickerGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationOptionsPickerGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOptionsPickerGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationOptionsPickerGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions/title",
          "value": "SWCollaborationShareOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationShareOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationShareOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWAction/title",
          "value": "SWAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1summary/title",
          "value": "summary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1summary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "summary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(optionsGroups:)/title",
          "value": "initWithOptionsGroups:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(optionsGroups:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOptionsGroups:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWUpdateCollaborationParticipantsAction/title",
          "value": "SWUpdateCollaborationParticipantsAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWUpdateCollaborationParticipantsAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWUpdateCollaborationParticipantsAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWUpdateCollaborationParticipantsAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWUpdateCollaborationParticipantsAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationCoordinator/title",
          "value": "SWCollaborationCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationCoordinator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyoucore/swcollaborationshareoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sharedwithyoucore/swcollaborationshareoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
