{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent/taskPriority"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INSearchForNotebookItemsIntent(py)taskPriority",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "taskPriority"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INTaskPriority",
        "text": "INTaskPriority"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "taskPriority"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "taskPriority"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "taskPriority"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskPriority",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INTaskPriority",
              "text": "INTaskPriority"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent": {
      "abstract": [
        {
          "text": "A request to search for notes, tasks, and reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForNotebookItemsIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForNotebookItemsIntent"
        }
      ],
      "role": "symbol",
      "title": "INSearchForNotebookItemsIntent",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent/taskPriority": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "taskPriority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INTaskPriority",
          "text": "INTaskPriority"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent/taskPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "taskPriority"
        }
      ],
      "role": "symbol",
      "title": "taskPriority",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintent/taskpriority"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent/temporalEventTriggerTypes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "temporalEventTriggerTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INTemporalEventTriggerTypeOptions",
          "text": "INTemporalEventTriggerTypeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent/temporalEventTriggerTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "temporalEventTriggerTypes"
        }
      ],
      "role": "symbol",
      "title": "temporalEventTriggerTypes",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintent/temporaleventtriggertypes"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTaskPriority": {
      "abstract": [
        {
          "text": "Constants indicating the priority for a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTaskPriority"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTaskPriority"
        }
      ],
      "role": "symbol",
      "title": "INTaskPriority",
      "type": "topic",
      "url": "/documentation/intents/intaskpriority"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTriggerTypeOptions": {
      "abstract": [
        {
          "text": "Constants indicating how often to trigger an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTemporalEventTriggerTypeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTriggerTypeOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTemporalEventTriggerTypeOptions"
        }
      ],
      "role": "symbol",
      "title": "INTemporalEventTriggerTypeOptions",
      "type": "topic",
      "url": "/documentation/intents/intemporaleventtriggertypeoptions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Searching-for-Tasks-by-Their-Priority",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INTaskPriority",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent/temporalEventTriggerTypes",
        "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTriggerTypeOptions"
      ],
      "title": "Searching for Tasks by Their Priority"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "taskPriority"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "taskPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Searching-for-Tasks-by-Their-Priority",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INTaskPriority",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent/temporalEventTriggerTypes",
                "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTriggerTypeOptions"
              ],
              "title": "Searching for Tasks by Their Priority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskPriority",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INTaskPriority",
                    "text": "INTaskPriority"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "taskPriority"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskPriority",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INTaskPriority",
                    "text": "INTaskPriority"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "taskPriority"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemporalEventTriggerTypeOptions/title",
          "value": "INTemporalEventTriggerTypeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemporalEventTriggerTypeOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTemporalEventTriggerTypeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemporalEventTriggerTypeOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTemporalEventTriggerTypeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntent/title",
          "value": "INSearchForNotebookItemsIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntent~1taskPriority/title",
          "value": "taskPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntent~1taskPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "taskPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntent~1temporalEventTriggerTypes/title",
          "value": "temporalEventTriggerTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntent~1temporalEventTriggerTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "temporalEventTriggerTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskPriority/title",
          "value": "INTaskPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskPriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskPriority"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insearchfornotebookitemsintent/taskpriority"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insearchfornotebookitemsintent/taskpriority"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
