{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDownOnCharacterIndex:atCoordinate:withModifier:client:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSInputServerMouseTracker(im)mouseDownOnCharacterIndex:atCoordinate:withModifier:client:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "mouseDownOnCharacterIndex:atCoordinate:withModifier:client:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mouseDownOnCharacterIndex:atCoordinate:withModifier:client:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.6",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "mouseDownOnCharacterIndex:atCoordinate:withModifier:client:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "mouseDownOnCharacterIndex:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "index"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "atCoordinate:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPoint",
              "text": "NSPoint"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "point"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withModifier:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "client:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "sender"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInputServerMouseTracker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInputServerMouseTracker"
        }
      ],
      "role": "symbol",
      "title": "NSInputServerMouseTracker",
      "type": "topic",
      "url": "/documentation/appkit/nsinputservermousetracker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDownOnCharacterIndex:atCoordinate:withModifier:client:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mouseDownOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDownOnCharacterIndex:atCoordinate:withModifier:client:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseDownOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "role": "symbol",
      "title": "mouseDownOnCharacterIndex:atCoordinate:withModifier:client:",
      "type": "topic",
      "url": "/documentation/appkit/nsinputservermousetracker/mousedownoncharacterindex:atcoordinate:withmodifier:client:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "role": "symbol",
      "title": "mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:",
      "type": "topic",
      "url": "/documentation/appkit/nsinputservermousetracker/mousedraggedoncharacterindex:atcoordinate:withmodifier:client:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseUpOnCharacterIndex:atCoordinate:withModifier:client:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mouseUpOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseUpOnCharacterIndex:atCoordinate:withModifier:client:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseUpOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "role": "symbol",
      "title": "mouseUpOnCharacterIndex:atCoordinate:withModifier:client:",
      "type": "topic",
      "url": "/documentation/appkit/nsinputservermousetracker/mouseuponcharacterindex:atcoordinate:withmodifier:client:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSPoint": {
      "abstract": [
        {
          "text": "A point in a Cartesian coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPoint",
      "type": "topic",
      "url": "/documentation/foundation/nspoint"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:",
        "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseUpOnCharacterIndex:atCoordinate:withModifier:client:"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/title",
          "value": "NSInputServerMouseTracker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsinputservermousetracker/mousedownoncharacterindex:atcoordinate:withmodifier:client:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
