{
  "abstract": [
    {
      "text": "Returns the required key descriptor for the name delimiter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts",
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForDelimiter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNContactFormatter(cpy)descriptorForRequiredKeysForDelimiter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "descriptorForRequiredKeysForDelimiter"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)CNKeyDescriptor",
        "text": "CNKeyDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "descriptorForRequiredKeysForDelimiter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "descriptorForRequiredKeysForDelimiter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "descriptorForRequiredKeysForDelimiter"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNKeyDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)CNKeyDescriptor",
              "text": "CNKeyDescriptor"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter": {
      "abstract": [
        {
          "text": "An object that you use to format contact information before displaying it to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactFormatter"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactFormatter"
        }
      ],
      "role": "symbol",
      "title": "CNContactFormatter",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeys(for:)": {
      "abstract": [
        {
          "text": "Returns the required key descriptor for the specified formatting style of the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeys"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNContactFormatterStyle",
          "text": "CNContactFormatterStyle"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CNKeyDescriptor",
          "text": "CNKeyDescriptor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeys(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeysForStyle:"
        }
      ],
      "role": "symbol",
      "title": "descriptorForRequiredKeys(for:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/descriptorforrequiredkeys(for:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForDelimiter": {
      "abstract": [
        {
          "text": "Returns the required key descriptor for the name delimiter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeysForDelimiter"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CNKeyDescriptor",
          "text": "CNKeyDescriptor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForDelimiter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeysForDelimiter"
        }
      ],
      "role": "symbol",
      "title": "descriptorForRequiredKeysForDelimiter",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/descriptorforrequiredkeysfordelimiter"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForNameOrder": {
      "abstract": [
        {
          "text": "Returns the required key descriptor for the display name order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeysForNameOrder"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CNKeyDescriptor",
          "text": "CNKeyDescriptor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForNameOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeysForNameOrder"
        }
      ],
      "role": "symbol",
      "title": "descriptorForRequiredKeysForNameOrder",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/descriptorforrequiredkeysfornameorder"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNKeyDescriptor": {
      "abstract": [
        {
          "text": "This protocol is reserved for Contacts framework usage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNKeyDescriptor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNKeyDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNKeyDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CNKeyDescriptor",
      "type": "topic",
      "url": "/documentation/contacts/cnkeydescriptor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-a-descriptor",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeys(for:)",
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForNameOrder"
      ],
      "title": "Getting a descriptor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "descriptorForRequiredKeysForDelimiter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "descriptorForRequiredKeysForDelimiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts",
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-a-descriptor",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeys(for:)",
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForNameOrder"
              ],
              "title": "Getting a descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)CNKeyDescriptor",
                    "text": "id<CNKeyDescriptor>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "descriptorForRequiredKeysForDelimiter"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNKeyDescriptor/title",
          "value": "CNKeyDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNKeyDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNKeyDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNKeyDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNKeyDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter/title",
          "value": "CNContactFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeysForDelimiter/title",
          "value": "descriptorForRequiredKeysForDelimiter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeysForDelimiter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "descriptorForRequiredKeysForDelimiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeys(for:)/title",
          "value": "descriptorForRequiredKeysForStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeys(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorForRequiredKeysForStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeysForNameOrder/title",
          "value": "descriptorForRequiredKeysForNameOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeysForNameOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "descriptorForRequiredKeysForNameOrder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cncontactformatter/descriptorforrequiredkeysfordelimiter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cncontactformatter/descriptorforrequiredkeysfordelimiter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
