{
  "abstract": [
    {
      "text": "A value that indicates whether the watch is on the user’s wrist.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/onWrist"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SRWristDetection(py)onWrist",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "onWrist"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "onWrist"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "onWrist"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "onWrist"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection": {
      "abstract": [
        {
          "text": "The configuration of a watch on the wearer’s wrist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRWristDetection"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristDetection"
        }
      ],
      "role": "symbol",
      "title": "SRWristDetection",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristdetection"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/CrownOrientation-swift.enum": {
      "abstract": [
        {
          "text": "Directions the Digital Crown can face with respect to the wearer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CrownOrientation"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/CrownOrientation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CrownOrientation"
        }
      ],
      "role": "symbol",
      "title": "SRWristDetection.CrownOrientation",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristdetection/crownorientation-swift.enum"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/WristLocation-swift.enum": {
      "abstract": [
        {
          "text": "Preferences for where a user wears a watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WristLocation"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/WristLocation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WristLocation"
        }
      ],
      "role": "symbol",
      "title": "SRWristDetection.WristLocation",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristdetection/wristlocation-swift.enum"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/crownOrientation-swift.property": {
      "abstract": [
        {
          "text": "A value that indicates the direction the Digital Crown faces with respect to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crownOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRWristDetection",
          "text": "SRWristDetection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRCrownOrientation",
          "text": "CrownOrientation"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/crownOrientation-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "crownOrientation"
        }
      ],
      "role": "symbol",
      "title": "crownOrientation",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristdetection/crownorientation-swift.property"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/offWristDate": {
      "abstract": [
        {
          "text": "The date and time that the user takes their Apple Watch off their wrist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offWristDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/offWristDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "offWristDate"
        }
      ],
      "role": "symbol",
      "title": "offWristDate",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristdetection/offwristdate"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/onWrist": {
      "abstract": [
        {
          "text": "A value that indicates whether the watch is on the user’s wrist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onWrist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/onWrist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "onWrist"
        }
      ],
      "role": "symbol",
      "title": "onWrist",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristdetection/onwrist"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/onWristDate": {
      "abstract": [
        {
          "text": "The date and time that the user puts their Apple Watch on their wrist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onWristDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/onWristDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "onWristDate"
        }
      ],
      "role": "symbol",
      "title": "onWristDate",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristdetection/onwristdate"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/wristLocation-swift.property": {
      "abstract": [
        {
          "text": "A value that indicates the wrist where the user wears the watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wristLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRWristDetection",
          "text": "SRWristDetection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRWristLocation",
          "text": "WristLocation"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/wristLocation-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wristLocation"
        }
      ],
      "role": "symbol",
      "title": "wristLocation",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristdetection/wristlocation-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Watch-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/crownOrientation-swift.property",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/CrownOrientation-swift.enum",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/onWristDate",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/offWristDate",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/wristLocation-swift.property",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/WristLocation-swift.enum"
      ],
      "title": "Inspecting Watch Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "onWrist"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "onWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-Watch-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/crownOrientation-swift.property",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/CrownOrientation-swift.enum",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/onWristDate",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/offWristDate",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/wristLocation-swift.property",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection/WristLocation-swift.enum"
              ],
              "title": "Inspecting Watch Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "onWrist"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1onWrist/title",
          "value": "onWrist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1onWrist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "onWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/title",
          "value": "SRWristDetection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1crownOrientation-swift.property/title",
          "value": "crownOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1crownOrientation-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "crownOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1wristLocation-swift.property/title",
          "value": "wristLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1wristLocation-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wristLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1onWristDate/title",
          "value": "onWristDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1onWristDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "onWristDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1WristLocation-swift.enum/title",
          "value": "SRWristLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1WristLocation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1WristLocation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1offWristDate/title",
          "value": "offWristDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1offWristDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "offWristDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1CrownOrientation-swift.enum/title",
          "value": "SRCrownOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1CrownOrientation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRCrownOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection~1CrownOrientation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRCrownOrientation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srwristdetection/onwrist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srwristdetection/onwrist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
