{
  "abstract": [
    {
      "text": "An error code that indicates the connection to the VPN server failed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/connectionFailed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC10NEVPNErrorLeV16connectionFailedSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "connectionFailed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC10NEVPNErrorLeV",
        "text": "NEVPNError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NEVPNError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "connectionFailed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "connectionFailed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC10NEVPNErrorLeV",
              "text": "NEVPNError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NEVPNError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct": {
      "abstract": [
        {
          "text": "Information about an error encountered while configuring or using a VPN.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNError"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Codes that indicate the source of an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError.Code",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/code"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationDisabled": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN configuration associated with the VPN manager isn’t enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationDisabled",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/configurationdisabled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationInvalid": {
      "abstract": [
        {
          "text": "An error code that indicates the VPN configuration associated with the VPN manager object is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationInvalid",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/configurationinvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationReadWriteFailed": {
      "abstract": [
        {
          "text": "An error code that indicates an error occurred while reading or writing the Network Extension preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationReadWriteFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationReadWriteFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationReadWriteFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/configurationreadwritefailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationStale": {
      "abstract": [
        {
          "text": "An error code that indicates another process modfied the VPN configuration since the last time the app loaded the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationStale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationStale",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationStale",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/configurationstale"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationUnknown": {
      "abstract": [
        {
          "text": "An error code that indicates that unspecified error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationUnknown",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/configurationunknown"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/connectionFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the connection to the VPN server failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10NEVPNErrorLeV",
          "text": "NEVPNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEVPNError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/connectionFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/connectionfailed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationDisabled",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationInvalid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationStale",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationReadWriteFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/configurationUnknown"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code/title",
          "value": "NEVPNError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnerror-swift.struct/connectionfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
