{"abstract":[{"type":"text","text":"The system displays a highlighted mode on the most recent item selected."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup","doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectOne","kind":"identifier"}]}]}],"metadata":{"platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.0","name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.0","name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"10.15","name":"macOS"}],"modules":[{"name":"AppKit"}],"externalID":"c:@E@NSToolbarItemGroupSelectionMode@NSToolbarItemGroupSelectionModeSelectOne","symbolKind":"case","title":"NSToolbarItemGroup.SelectionMode.selectOne","navigatorTitle":[{"text":"NSToolbarItemGroupSelectionModeSelectOne","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectOne","kind":"identifier"}],"roleHeading":"Case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["/documentation/appkit/nstoolbaritemgroup/selectionmode-swift.enum/selectone"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nstoolbaritemgroup/selectionmode-swift.enum/selectone"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/selectOne"},"seeAlsoSections":[{"anchor":"Selection-modes","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/momentary","doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/selectAny"],"title":"Selection modes"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/momentary":{"url":"/documentation/appkit/nstoolbaritemgroup/selectionmode-swift.enum/momentary","abstract":[{"text":"The system temporarily highlights the select group item when the user selects the item.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"NSToolbarItemGroupSelectionModeMomentary","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/momentary","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"momentary","kind":"identifier"}],"title":"NSToolbarItemGroup.SelectionMode.momentary"},"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/selectAny":{"url":"/documentation/appkit/nstoolbaritemgroup/selectionmode-swift.enum/selectany","abstract":[{"text":"The system toggles a highlight on any item selected.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"NSToolbarItemGroupSelectionModeSelectAny","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/selectAny","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectAny","kind":"identifier"}],"title":"NSToolbarItemGroup.SelectionMode.selectAny"},"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum":{"url":"/documentation/appkit/nstoolbaritemgroup/selectionmode-swift.enum","title":"NSToolbarItemGroup.SelectionMode","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum","navigatorTitle":[{"text":"SelectionMode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SelectionMode","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A value that indicates how a grouped toolbar item selects its subitems."}]},"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup":{"url":"/documentation/appkit/nstoolbaritemgroup","title":"NSToolbarItemGroup","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup","navigatorTitle":[{"text":"NSToolbarItemGroup","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSToolbarItemGroup","kind":"identifier"}],"type":"topic","abstract":[{"text":"A group of subitems in a toolbar item.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/selectOne":{"kind":"symbol","navigatorTitle":[{"text":"NSToolbarItemGroupSelectionModeSelectOne","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectOne","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/selectOne","role":"symbol","abstract":[{"type":"text","text":"The system displays a highlighted mode on the most recent item selected."}],"type":"topic","url":"/documentation/appkit/nstoolbaritemgroup/selectionmode-swift.enum/selectone","title":"NSToolbarItemGroup.SelectionMode.selectOne"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"10.15","name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"NSToolbarItemGroupSelectionModeSelectOne"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"NSToolbarItemGroupSelectionModeSelectOne"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Selection modes","anchor":"Selection-modes","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/momentary","doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum/selectAny"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"NSToolbarItemGroupSelectionModeSelectOne","kind":"identifier"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum~1momentary/title","op":"replace","value":"NSToolbarItemGroupSelectionModeMomentary"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum~1momentary/fragments","value":[{"kind":"identifier","text":"NSToolbarItemGroupSelectionModeMomentary"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum~1selectAny/title","value":"NSToolbarItemGroupSelectionModeSelectAny"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum~1selectAny/fragments","value":[{"text":"NSToolbarItemGroupSelectionModeSelectAny","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum/title","op":"replace","value":"NSToolbarItemGroupSelectionMode"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum/fragments","op":"replace","value":[{"kind":"identifier","text":"NSToolbarItemGroupSelectionMode"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum/navigatorTitle","op":"replace","value":[{"text":"NSToolbarItemGroupSelectionMode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup/title","op":"replace","value":"NSToolbarItemGroup"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup/fragments","op":"replace","value":[{"kind":"identifier","text":"NSToolbarItemGroup"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup/navigatorTitle","op":"replace","value":[{"text":"NSToolbarItemGroup","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum~1selectOne/title","op":"replace","value":"NSToolbarItemGroupSelectionModeSelectOne"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum~1selectOne/fragments","op":"replace","value":[{"kind":"identifier","text":"NSToolbarItemGroupSelectionModeSelectOne"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}