{
  "abstract": [
    {
      "text": "Creates a Core ML model instance asynchronously from a compiled model file, a custom configuration, and a completion handler.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML",
        "doc://com.apple.coreml/documentation/CoreML/MLModel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLModel/loadContentsOfURL:configuration:completionHandler:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLModel(cm)loadContentsOfURL:configuration:completionHandler:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "loadContentsOfURL:configuration:completionHandler:"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "loadContentsOfURL:configuration:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "loadContentsOfURL:configuration:completionHandler:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "loadContentsOfURL:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURL",
              "text": "NSURL"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "url"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configuration:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelConfiguration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLModelConfiguration",
              "text": "MLModelConfiguration"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "configuration"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "completionHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLModel",
              "text": "MLModel"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "model"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The path to a compiled model file (",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "ModelName",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "code": ".mlmodelc",
                  "type": "codeVoice"
                },
                {
                  "text": "), typically with the ",
                  "type": "text"
                },
                {
                  "code": "URL",
                  "type": "codeVoice"
                },
                {
                  "text": " that ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/compileModel(at:)-6442s",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " returns.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "url"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The runtime settings for the new model instance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "configuration"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A closure the method calls when it finishes loading the model.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "handler"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.coreml/documentation/CoreML/encrypting-a-model-in-your-app"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to load a model asynchronously. Core ML calls your completion handler after it successfully loads the model, or encounters an error attempting to load it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "MLModel.load(contentsOf: modelURL) { result in",
                    "    switch result {",
                    "    case .success(let loadedModel):",
                    "        print(\"Successfully loaded model `\\(loadedModel)`.\")",
                    "",
                    "        // Use the loaded model for predictions.",
                    "        // ...",
                    "",
                    "    case .failure(let error):",
                    "        print(\"Error loading model: \\(error).\")",
                    "    }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "[MLModel loadContentsOfURL:modelURL",
                    "             configuration:[[MLModelConfiguration alloc] init]",
                    "         completionHandler:^(MLModel *loadedModel,",
                    "                             NSError *error) {",
                    "    if (nil == loadedModel) {",
                    "        NSLog(@\"Error loading model`: %@\", (nil != error) ? error : modelURL);",
                    "        return;",
                    "    }",
                    "",
                    "    NSLog(@\"Successfully loaded model at: %@\", modelURL);",
                    "",
                    "    // Use the loaded model for predictions.",
                    "    // ...",
                    "}];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "In Swift, if the model loaded successfully, you can use the instance from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/Result/success(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " associated value; otherwise, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/Result/failure(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " associated value to address the error. In Objective-C, you can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance in your completion hander; otherwise, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance to address the error.  See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the list of error codes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel": {
      "abstract": [
        {
          "text": "An encapsulation of all the details of your machine learning model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModel"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModel"
        }
      ],
      "role": "symbol",
      "title": "MLModel",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel/compileModel(at:)-6442s": {
      "abstract": [
        {
          "text": "Compiles a model on the device to update the model in your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compileModel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/compileModel(at:)-6442s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compileModelAtURL:error:"
        }
      ],
      "role": "symbol",
      "title": "compileModel(at:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel/compilemodel(at:)-6442s"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel/init(contentsOf:)": {
      "abstract": [
        {
          "text": "Creates a Core ML model instance from a compiled model file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/init(contentsOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modelWithContentsOfURL:error:"
        }
      ],
      "role": "symbol",
      "title": "init(contentsOf:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel/init(contentsof:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel/init(contentsOf:configuration:)": {
      "abstract": [
        {
          "text": "Creates a Core ML model instance from a compiled model file and a custom configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelConfiguration",
          "text": "MLModelConfiguration"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/init(contentsOf:configuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modelWithContentsOfURL:configuration:error:"
        }
      ],
      "role": "symbol",
      "title": "init(contentsOf:configuration:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel/init(contentsof:configuration:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel/load(_:configuration:completionHandler:)": {
      "abstract": [
        {
          "text": "Construct a model asynchronously from a compiled model asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelAsset",
          "text": "MLModelAsset"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelConfiguration",
          "text": "MLModelConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModel",
          "text": "MLModel"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/load(_:configuration:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadModelAsset:configuration:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "load(_:configuration:completionHandler:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel/load(_:configuration:completionhandler:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModel/loadContentsOfURL:configuration:completionHandler:": {
      "abstract": [
        {
          "text": "Creates a Core ML model instance asynchronously from a compiled model file, a custom configuration, and a completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "loadContentsOfURL:configuration:completionHandler:"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModel/loadContentsOfURL:configuration:completionHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadContentsOfURL:configuration:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadContentsOfURL:configuration:completionHandler:",
      "type": "topic",
      "url": "/documentation/coreml/mlmodel/loadcontentsofurl:configuration:completionhandler:"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelConfiguration": {
      "abstract": [
        {
          "text": "The settings for creating or updating a machine learning model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelConfiguration"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelConfiguration"
        }
      ],
      "role": "symbol",
      "title": "MLModelConfiguration",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelconfiguration"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Information about a Core ML model error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code"
    },
    "doc://com.apple.coreml/documentation/CoreML/encrypting-a-model-in-your-app": {
      "abstract": [
        {
          "text": "Encrypt your app’s built-in model at compile time by adding a compiler flag.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/encrypting-a-model-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Encrypting a Model in Your App",
      "type": "topic",
      "url": "/documentation/coreml/encrypting-a-model-in-your-app"
    },
    "doc://com.apple.documentation/documentation/Swift/Result/failure(_:)": {
      "abstract": [
        {
          "text": "A failure, storing a `Failure` value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Failure"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Result/failure(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "Result.failure(_:)",
      "type": "topic",
      "url": "/documentation/Swift/Result/failure(_:)"
    },
    "doc://com.apple.documentation/documentation/Swift/Result/success(_:)": {
      "abstract": [
        {
          "text": "A success, storing a `Success` value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Success"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Result/success(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "Result.success(_:)",
      "type": "topic",
      "url": "/documentation/Swift/Result/success(_:)"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSURL": {
      "abstract": [
        {
          "text": "An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURL",
      "type": "topic",
      "url": "/documentation/foundation/nsurl"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Loading-a-Model",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModel/load(_:configuration:completionHandler:)",
        "doc://com.apple.coreml/documentation/CoreML/MLModel/init(contentsOf:)",
        "doc://com.apple.coreml/documentation/CoreML/MLModel/init(contentsOf:configuration:)"
      ],
      "title": "Loading a Model"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1init(contentsOf:)/title",
          "value": "modelWithContentsOfURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1init(contentsOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "modelWithContentsOfURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract",
          "value": [
            {
              "text": "An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1compileModel(at:)-6442s/title",
          "value": "compileModelAtURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1compileModel(at:)-6442s/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "compileModelAtURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelConfiguration/title",
          "value": "MLModelConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/title",
          "value": "MLModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code/title",
          "value": "MLModelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1init(contentsOf:configuration:)/title",
          "value": "modelWithContentsOfURL:configuration:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1init(contentsOf:configuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "modelWithContentsOfURL:configuration:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1load(_:configuration:completionHandler:)/title",
          "value": "loadModelAsset:configuration:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModel~1load(_:configuration:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "loadModelAsset:configuration:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlmodel/loadcontentsofurl:configuration:completionhandler:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
