{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/enteringFullscreen"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKFullscreenState@WKFullscreenStateEnteringFullscreen",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "enteringFullscreen"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKFullscreenStateEnteringFullscreen"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKWebView.FullscreenState.enteringFullscreen"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "enteringFullscreen"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView": {
      "abstract": [
        {
          "text": "An object that displays interactive web content, such as for an in-app browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "role": "symbol",
      "title": "WKWebView",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FullscreenState"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FullscreenState"
        }
      ],
      "role": "symbol",
      "title": "WKWebView.FullscreenState",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/fullscreenstate-swift.enum"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/enteringFullscreen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enteringFullscreen"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/enteringFullscreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKFullscreenStateEnteringFullscreen"
        }
      ],
      "role": "symbol",
      "title": "WKWebView.FullscreenState.enteringFullscreen",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/fullscreenstate-swift.enum/enteringfullscreen"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/exitingFullscreen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exitingFullscreen"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/exitingFullscreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKFullscreenStateExitingFullscreen"
        }
      ],
      "role": "symbol",
      "title": "WKWebView.FullscreenState.exitingFullscreen",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/fullscreenstate-swift.enum/exitingfullscreen"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/inFullscreen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inFullscreen"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/inFullscreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKFullscreenStateInFullscreen"
        }
      ],
      "role": "symbol",
      "title": "WKWebView.FullscreenState.inFullscreen",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/fullscreenstate-swift.enum/infullscreen"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/notInFullscreen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notInFullscreen"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/notInFullscreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKFullscreenStateNotInFullscreen"
        }
      ],
      "role": "symbol",
      "title": "WKWebView.FullscreenState.notInFullscreen",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/fullscreenstate-swift.enum/notinfullscreen"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/exitingFullscreen",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/inFullscreen",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/notInFullscreen"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKFullscreenStateEnteringFullscreen"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFullscreenStateEnteringFullscreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/exitingFullscreen",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/inFullscreen",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/FullscreenState-swift.enum/notInFullscreen"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKFullscreenStateEnteringFullscreen"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum~1exitingFullscreen/title",
          "value": "WKFullscreenStateExitingFullscreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum~1exitingFullscreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFullscreenStateExitingFullscreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum~1enteringFullscreen/title",
          "value": "WKFullscreenStateEnteringFullscreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum~1enteringFullscreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFullscreenStateEnteringFullscreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/title",
          "value": "WKWebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum/title",
          "value": "WKFullscreenState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFullscreenState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFullscreenState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum~1inFullscreen/title",
          "value": "WKFullscreenStateInFullscreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum~1inFullscreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFullscreenStateInFullscreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum~1notInFullscreen/title",
          "value": "WKFullscreenStateNotInFullscreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1FullscreenState-swift.enum~1notInFullscreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFullscreenStateNotInFullscreen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebview/fullscreenstate-swift.enum/enteringfullscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkwebview/fullscreenstate-swift.enum/enteringfullscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
