{
  "abstract": [
    {
      "text": "Lines render vertically, each line following the previous from right to left.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation/vertical"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextLayoutOrientation@NSTextLayoutOrientationVertical",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vertical"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutOrientationVertical"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSLayoutManager.TextLayoutOrientation.vertical"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vertical"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager": {
      "abstract": [
        {
          "text": "An object that coordinates the layout and display of text characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation": {
      "abstract": [
        {
          "text": "Constants that describe the text layout orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextLayoutOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextLayoutOrientation"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TextLayoutOrientation",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutmanager/textlayoutorientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation/horizontal": {
      "abstract": [
        {
          "text": "Lines render horizontally, each line following the previous from top to bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation/horizontal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutOrientationHorizontal"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TextLayoutOrientation.horizontal",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutmanager/textlayoutorientation/horizontal"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation/vertical": {
      "abstract": [
        {
          "text": "Lines render vertically, each line following the previous from right to left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertical"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation/vertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutOrientationVertical"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TextLayoutOrientation.vertical",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutmanager/textlayoutorientation/vertical"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation/horizontal"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextLayoutOrientationVertical"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientationVertical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation/horizontal"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTextLayoutOrientationVertical"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1TextLayoutOrientation~1horizontal/title",
          "value": "NSTextLayoutOrientationHorizontal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1TextLayoutOrientation~1horizontal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientationHorizontal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1TextLayoutOrientation~1vertical/title",
          "value": "NSTextLayoutOrientationVertical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1TextLayoutOrientation~1vertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientationVertical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/title",
          "value": "NSLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1TextLayoutOrientation/title",
          "value": "NSTextLayoutOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1TextLayoutOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1TextLayoutOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nslayoutmanager/textlayoutorientation/vertical"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nslayoutmanager/textlayoutorientation/vertical"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
