{
  "abstract": [
    {
      "text": "Creates a caption size with width and height values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSize"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSize/init(width:height:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So13AVCaptionSizeV5width6heightABSo0A9DimensionV_AFtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "width"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@AVCaptionDimension",
        "text": "AVCaptionDimension"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "height"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@AVCaptionDimension",
        "text": "AVCaptionDimension"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(width:height:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "width"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimension",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AVCaptionDimension",
              "text": "AVCaptionDimension"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "height"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimension",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AVCaptionDimension",
              "text": "AVCaptionDimension"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The caption width.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "width"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The caption height.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "height"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimension": {
      "abstract": [
        {
          "text": "A structure that defines a caption dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptionDimension"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptionDimension"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionDimension",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptiondimension"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSize": {
      "abstract": [
        {
          "text": "A structure that defines the height and width of a caption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptionSize"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptionSize"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionSize",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionsize"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSize/init(width:height:)": {
      "abstract": [
        {
          "text": "Creates a caption size with width and height values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AVCaptionDimension",
          "text": "AVCaptionDimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AVCaptionDimension",
          "text": "AVCaptionDimension"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSize/init(width:height:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(width:height:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionsize/init(width:height:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionDimension/title",
          "value": "AVCaptionDimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionDimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionDimension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionSize/title",
          "value": "AVCaptionSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcaptionsize/init(width:height:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
