{
  "abstract": [
    {
      "text": "Balance the appearance and performance of your AR experiences with modeling strategies.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Adding Visual Effects in AR Quick Look and RealityKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "AR Quick Look supports modeling features you can use to present your app’s virtual content at its most vivid and compelling. Make sure to optimize the performance of your AR experience by managing and testing the features you incorporate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "AR Quick Look uses RealityKit to display AR experiences, and you can design your models to take advantage of features in RealityKit available on iOS 13 and later. Roughness, for instance, is a property that affects how light diffuses on matte surfaces. RealityKit implements roughness using a multiscattering algorithm, enhancing the texture and realism of virtual content. Additionally, you can use the clearcoat option to add a glossy shine to your virtual content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3418297",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-Gloss-to-Your-3D-Content-with-Clearcoat",
          "level": 3,
          "text": "Add Gloss to Your 3D Content with Clearcoat",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can add shine and highlights to the models in your AR experience with the clearcoat option.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3405897",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "RealityKit renders clearcoat by adding a second specular lobe. To enable a clearcoat layer on your app’s virtual content, use the following inputs when designing your model:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A scalar float normalized between 0 and 1 that indicates the intensity of the clearcoat specular lobe.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "clearcoat",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A float normalized between 0 and 1 that indicates the perceived roughness of the clearcoat surface.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "clearcoatRoughness",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "The following figure shows the ",
              "type": "text"
            },
            {
              "code": "clearcoat",
              "type": "codeVoice"
            },
            {
              "text": " parameter varying between 0 and 1 vertically, and ",
              "type": "text"
            },
            {
              "code": "clearcoatRoughness",
              "type": "codeVoice"
            },
            {
              "text": " varying between 0 and 1 horizontally, with (0, 0) at the bottom left.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3405896",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Design-for-Lighting-and-Reflection-Accuracy",
          "level": 3,
          "text": "Design for Lighting and Reflection Accuracy",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "RealityKit’s multiscattering roughness affects how light reflects from––or diffuses on––the surface of models with a matte finish. By displaying virtual content using RealityKit, AR Quick Look realistically honors the roughness, metallic, and specular components of a model. Configure your 3D assets’ roughness, metallic, and specular inputs to create the right blend of reflection and diffusion.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The roughness component controls the texture of a surface. A roughness value of 0 (smooth) results in a mirror reflection, while a roughness value of 1 (rough) diffuses light to create a surface without shine. The following figure shows the ",
              "type": "text"
            },
            {
              "code": "roughness",
              "type": "codeVoice"
            },
            {
              "text": " parameter varying between 0 and 1, with 0 on the left.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3425157",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The metallic component defines whether your model appears dielectric (0) or metallic (1). The following figure shows the ",
              "type": "text"
            },
            {
              "code": "metallic",
              "type": "codeVoice"
            },
            {
              "text": " parameter varying from 0-1, with 0 on the left.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3425159",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For dielectrics, the specular component enables you to control the reflectiveness of a surface, ranging from 0 (nonreflective) to 1 (fully reflective). The following figure shows a roughness with the ",
              "type": "text"
            },
            {
              "code": "specular",
              "type": "codeVoice"
            },
            {
              "text": " parameter varying from 0-1, with 0 on the left.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3425158",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Environment lighting in AR Quick Look supports multiple models in iOS 13. To ensure your virtual content displays with the most realistic reflections in your app, check the iOS version at runtime and load multiple models only in iOS 13.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Optimize-Model-Geometry-and-Transparency",
          "level": 3,
          "text": "Optimize Model Geometry and Transparency",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While utilizing features to present virtual content effectively, take steps to keep the AR experience responsive. Because each model mesh results in a draw call, for best results, limit the number of meshes in a USDZ file to around 50. To reduce draw calls while maintaining the same amount of geometry, merge objects that share a material. However, be aware that merging may not afford performance gains in situations where the result prevents the renderer from culling.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The cost of projective and raytraced shadows depends on the complexity of your model’s geometry. To enhance performance and prevent excessive memory use relating to lighting, keep the polygon count of your 3D asset’s geometry below 100,000 polygons.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Transparency in models increases the number of times the fragment shader is run per pixel, which is expensive when the user views your model straight on or in full screen. To improve performance by reducing the time your app spends shading pixels, use transparency sparingly when authoring your app’s virtual content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Control-Texture-Memory",
          "level": 3,
          "text": "Control Texture Memory",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For best results, size your textures to 1024 x 1024 pixels or less, and don’t surpass a size of 2048 x 2048 pixels. If you have multiple small textures, combine them into one larger texture using texture coordinates to specify their location. To ensure your textures fit into memory as required for AR Quick Look to display your model, cap your total number of textures at six.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you observe any resolution discrepancies at runtime, switch to testing on a device with more memory and check for any differences. AR Quick Look automatically generates mipmaps for your model’s textures. AR Quick Look also scales down your texture at runtime if needed to keep its memory use under a certain budget depending on the device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-Features-on-Various-Devices",
          "level": 3,
          "text": "Test Features on Various Devices",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When developing your model for optimal performance, begin with a conservative configuration to ensure AR Quick Look supports your model on earlier iOS devices (iPhone 6s, and first-generation iPad Pro). By starting on the earliest devices that support AR Quick Look, you avoid having to prune back your virtual content’s features during the testing phase.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem": {
      "abstract": [
        {
          "text": "An object for customizing the AR Quick Look experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARQuickLookPreviewItem"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARQuickLookPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "ARQuickLookPreviewItem",
      "type": "topic",
      "url": "/documentation/arkit/arquicklookpreviewitem"
    },
    "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look": {
      "abstract": [
        {
          "text": "Provide a banner that users can tap to make a purchase or perform a custom action in an AR experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Adding an Apple Pay Button or a Custom Action in AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look"
    },
    "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios": {
      "abstract": [
        {
          "text": "Integrate iOS device camera and motion features to produce augmented reality experiences in your app or game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ARKit in iOS",
      "type": "topic",
      "url": "/documentation/arkit/arkit-in-ios"
    },
    "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look": {
      "abstract": [
        {
          "text": "Display a model or scene that the user can move, scale, and share with others.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Previewing a Model with AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/previewing-a-model-with-ar-quick-look"
    },
    "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look": {
      "abstract": [
        {
          "text": "Add metadata to your USDZ file to specify its lighting characteristics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Specifying a lighting environment in AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/specifying-a-lighting-environment-in-ar-quick-look"
    },
    "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar": {
      "abstract": [
        {
          "text": "Add augmented reality functionality to your 3D content using USDZ schemas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar",
      "kind": "article",
      "role": "article",
      "title": "USDZ schemas for AR",
      "type": "topic",
      "url": "/documentation/RealityKit/usdz-schemas-for-ar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3405896": {
      "alt": "Screenshot showing an array of 3D models, each with varying clearcoat parameters. clearcoat varys between 0 and 1 vertically, and clearcoatRoughness varys between 0 and 1 horizontally. The bottom-right model is dark and matte in appearance, whereas the upper-left model is glossy in appearance.",
      "identifier": "media-3405896",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/153f49c3e4caa0f7f6533dc47c513b48/media-3405896@2x.png"
        }
      ]
    },
    "media-3405897": {
      "alt": "Screenshot of two marbles side-by-side that demonstrate the effect of applying clearcoat. The image of the marble on the right shows a glossier finish and reflective highlights at the top.",
      "identifier": "media-3405897",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/dfec9ace6bd883183bb75f5b81395154/media-3405897@2x.png"
        }
      ]
    },
    "media-3418297": {
      "alt": "Screenshot of two wooden toys side-by-side to demonstrate the effect of adding the model features. The image of the toy on the left is pictured without multiscattering roughtness and clearcoat; the image of the toy on the right uses multiscattering roughness and clearcoat.",
      "identifier": "media-3418297",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/71c3befe9fb3fe94167a95a906ab9629/media-3418297@2x.png"
        }
      ]
    },
    "media-3425157": {
      "alt": "Screenshot showing an array of virtual objects with roughness varying from 0 to 1, with 0 on the left. ",
      "identifier": "media-3425157",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/902080f1c7ae1d48df0b95e412bd4a55/media-3425157@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/902080f1c7ae1d48df0b95e412bd4a55/media-3425157~dark@2x.png"
        }
      ]
    },
    "media-3425158": {
      "alt": "Screenshot showing an array of virtual objects with specular varying from 0 to 1, with 0 on the left. ",
      "identifier": "media-3425158",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/042ab492123ec827309f9733bde09f08/media-3425158@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/042ab492123ec827309f9733bde09f08/media-3425158~dark@2x.png"
        }
      ]
    },
    "media-3425159": {
      "alt": "Screenshot showing an array of virtual objects with metallic varying from 0 to 1, with 0 on the left. ",
      "identifier": "media-3425159",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/327025069d364bb1ce76b2498e646917/media-3425159@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/327025069d364bb1ce76b2498e646917/media-3425159~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "AR-Quick-Look",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
        "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look",
        "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem",
        "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar",
        "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look"
      ],
      "title": "AR Quick Look"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "AR-Quick-Look",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
                "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look",
                "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem",
                "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look"
              ],
              "title": "AR Quick Look"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/title",
          "value": "ARQuickLookPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/adding-visual-effects-in-ar-quick-look-and-realitykit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/adding-visual-effects-in-ar-quick-look-and-realitykit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
