{
  "abstract": [
    {
      "text": "Provide a banner that users can tap to make a purchase or perform a custom action in an AR experience.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Adding an Apple Pay Button or a Custom Action in AR Quick Look"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For AR experiences initiated through the web in iOS 13.3 or later, you can display an Apple Pay button so users can make purchases from your website.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3432381",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Alternatively, you can provide text in the banner that users can tap to invoke a custom action in your website, like adding a previewed item to a shopping cart.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3425396",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition, you can supply AR Quick Look with custom HTML that completely customizes the banner’s graphics.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3425393",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add an Apple Pay button or custom text or graphics in a banner, choose URL parameters to configure AR Quick Look for your website. Finally, detect and react to customer taps to the banner.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Choose-an-Apple-Pay-Button-Style",
          "level": 3,
          "text": "Choose an Apple Pay Button Style",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To select a style of Apple Pay button for your AR experience, append the ",
              "type": "text"
            },
            {
              "code": "applePayButtonType",
              "type": "codeVoice"
            },
            {
              "text": " parameter to your website URL.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "https://example.com/biplane.usdz#applePayButtonType=plain"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You can choose from the button options using the button type values shown here.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3421819",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Provide-Custom-Text",
          "level": 3,
          "text": "Provide Custom Text",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Instead of an Apple Pay button, you can supply text that AR Quick Look displays as a custom action button, as in the following image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3425397",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Append the ",
              "type": "text"
            },
            {
              "code": "callToAction",
              "type": "codeVoice"
            },
            {
              "text": " URL parameter with the custom text as the value. The following example URL renders a banner with the text “Add to cart”:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "https://example.com/biplane.usdz#callToAction=Add%20to%20cart"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Because URLs can’t contain spaces, be sure to URL-encode the custom text before appending it as a URL parameter. If your website supports multiple languages, localize the custom text before URL-encoding it for the URL parameter list.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Define-the-Item",
          "level": 3,
          "text": "Define the Item",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you add an Apple Pay button or a custom action button to AR Quick Look, set the description of the previewed items using the ",
              "type": "text"
            },
            {
              "code": "checkoutTitle",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "checkoutSubtitle",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "price",
              "type": "codeVoice"
            },
            {
              "text": " URL parameters. AR Quick Look displays the subtitle and price separated by a comma below the title.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3425394",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If AR Quick Look can’t fit the subtitle and price on one line, it truncates the subtitle with an ellipsis. The following example URL renders the banner.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "https://example.com/biplane.usdz#applePayButtonType=buy&checkoutTitle=Biplane%20Toy&checkoutSubtitle=Rustic%20finish%20with%20rotating%20propeller&price=$15"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If your website supports multiple languages, localize the item title, subtitle, and price before URL-encoding them for the URL parameter list.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Display-a-Custom-Banner",
          "level": 3,
          "text": "Display a Custom Banner",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To take full control of the banner’s graphics, supply a custom HTML file through the ",
              "type": "text"
            },
            {
              "code": "custom",
              "type": "codeVoice"
            },
            {
              "text": " URL parameter. The following example URL renders a banner from a custom file named ",
              "type": "text"
            },
            {
              "code": "comingSoonBanner",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "https://example.com/biplane.usdz#custom=https://example.com/customBanners/comingSoonBanner.html",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This example URL creates the AR experience illustrated below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3425395",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you use the ",
              "type": "text"
            },
            {
              "code": "custom",
              "type": "codeVoice"
            },
            {
              "text": " URL parameter, the value must be an absolute URL. To comply with AR Quick Look’s security standards, ensure the server sends the HTML resource over HTTPS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "AR Quick Look displays the contents of the HTML only. If you embed actions such as links or events, AR Quick Look ignores them.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Define-the-Custom-Banners-Height",
          "level": 3,
          "text": "Define the Custom Banner’s Height",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you display a custom banner, you can set the banner height using the ",
              "type": "text"
            },
            {
              "code": "customHeight",
              "type": "codeVoice"
            },
            {
              "text": " URL parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Supply a value of ",
              "type": "text"
            },
            {
              "code": "small",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "medium",
              "type": "codeVoice"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "large",
              "type": "codeVoice"
            },
            {
              "text": " to set the banner height to 81, 121, or 161 points, respectively. For example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "https://example.com/biplane.usdz#custom=https://example.com/my-custom-page.html&customHeight=large"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "AR Quick Look automatically scales the width of the banner to the size and orientation of the device on which it displays. The maximum width of the custom banner is 450 points. If you omit the ",
              "type": "text"
            },
            {
              "code": "customHeight",
              "type": "codeVoice"
            },
            {
              "text": " URL parameter, AR Quick Look uses the default value, ",
              "type": "text"
            },
            {
              "code": "small",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Detect-a-Tap",
          "level": 3,
          "text": "Detect a Tap",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the user taps the Apple Pay button or custom action button, WebKit sends a DOM message to the ",
              "type": "text"
            },
            {
              "code": "<a>",
              "type": "codeVoice"
            },
            {
              "text": " element of your code that references the 3D asset.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<a id=\"ar-link\" rel=\"ar\" href=\"https://example.com/cool-model.usdz#applePayButtonType=pay....etc\">  <img src=\"poster.jpg\"></a>"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To be notified of the tap, define a JavaScript listener for the ",
              "type": "text"
            },
            {
              "code": "message",
              "type": "codeVoice"
            },
            {
              "text": " event on your anchor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "const linkElement = document.getElementById(\"ar-link\");",
            "linkElement.addEventListener(\"message\", function (event) { ... }, false);"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When WebKit invokes your listener, check the ",
              "type": "text"
            },
            {
              "code": "data",
              "type": "codeVoice"
            },
            {
              "text": " property. A value of ",
              "type": "text"
            },
            {
              "code": "_apple_ar_quicklook_button_tapped",
              "type": "codeVoice"
            },
            {
              "text": " confirms the user tapped the banner in AR Quick Look.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "const linkElement = document.getElementById(\"ar-link\");",
            "linkElement.addEventListener(\"message\", function (event) {   ",
            "    if (event.data == \"_apple_ar_quicklook_button_tapped\") {",
            "        // Handle the user tap.   ",
            "    }",
            "}, false);"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "message",
              "type": "codeVoice"
            },
            {
              "text": " event follows normal DOM processing rules. Rather than adding a listener for a specific anchor, you can add a listener at the document root for all AR links, and use the ",
              "type": "text"
            },
            {
              "code": "event.target",
              "type": "codeVoice"
            },
            {
              "text": " to determine which anchor the user invoked.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "React-to-a-Tap",
          "level": 3,
          "text": "React to a Tap",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Define the actions your website takes in response to a user tap in your event listener. When the user taps the custom action button, you might add the previewed item to a shopping cart or take the user to a checkout page, depending on the banner’s text and custom action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your banner displays an Apple Pay button, bring up the Apple Pay prompt using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/apple_pay_on_the_web/apple_pay_js_api",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your banner displays an Apple Messages for Business button, send the user to Messages using your company’s custom Apple Messages for Business URL. For more infomation, see ",
              "type": "text"
            },
            {
              "identifier": "https://register.apple.com/resources/messages/messaging-documentation/chat-with-customers#starting-a-chat-from-a-url",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem": {
      "abstract": [
        {
          "text": "An object for customizing the AR Quick Look experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARQuickLookPreviewItem"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARQuickLookPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "ARQuickLookPreviewItem",
      "type": "topic",
      "url": "/documentation/arkit/arquicklookpreviewitem"
    },
    "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit": {
      "abstract": [
        {
          "text": "Balance the appearance and performance of your AR experiences with modeling strategies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit",
      "kind": "article",
      "role": "article",
      "title": "Adding Visual Effects in AR Quick Look and RealityKit",
      "type": "topic",
      "url": "/documentation/arkit/adding-visual-effects-in-ar-quick-look-and-realitykit"
    },
    "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios": {
      "abstract": [
        {
          "text": "Integrate iOS device camera and motion features to produce augmented reality experiences in your app or game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ARKit in iOS",
      "type": "topic",
      "url": "/documentation/arkit/arkit-in-ios"
    },
    "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look": {
      "abstract": [
        {
          "text": "Display a model or scene that the user can move, scale, and share with others.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Previewing a Model with AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/previewing-a-model-with-ar-quick-look"
    },
    "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look": {
      "abstract": [
        {
          "text": "Add metadata to your USDZ file to specify its lighting characteristics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Specifying a lighting environment in AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/specifying-a-lighting-environment-in-ar-quick-look"
    },
    "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar": {
      "abstract": [
        {
          "text": "Add augmented reality functionality to your 3D content using USDZ schemas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar",
      "kind": "article",
      "role": "article",
      "title": "USDZ schemas for AR",
      "type": "topic",
      "url": "/documentation/RealityKit/usdz-schemas-for-ar"
    },
    "doc://com.apple.documentation/documentation/apple_pay_on_the_web/apple_pay_js_api": {
      "abstract": [
        {
          "text": "Implement Apple Pay on the web using Apple's JavaScript API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple_pay_on_the_web/apple_pay_js_api",
      "kind": "article",
      "role": "article",
      "title": "Apple Pay JS API",
      "type": "topic",
      "url": "/documentation/apple_pay_on_the_web/apple_pay_js_api"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://register.apple.com/resources/messages/messaging-documentation/chat-with-customers#starting-a-chat-from-a-url": {
      "identifier": "https://register.apple.com/resources/messages/messaging-documentation/chat-with-customers#starting-a-chat-from-a-url",
      "title": "Starting a Chat from a URL",
      "titleInlineContent": [
        {
          "text": "Starting a Chat from a URL",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://register.apple.com/resources/messages/messaging-documentation/chat-with-customers#starting-a-chat-from-a-url"
    },
    "media-3421819": {
      "alt": "Figure showing each of the seven Apple Pay button options, annotated by the the button type value parameter associated with the button style.",
      "identifier": "media-3421819",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c17be74f46391236a827e7f35eb23947/media-3421819@2x.png"
        }
      ]
    },
    "media-3425393": {
      "alt": "Screenshot of a banner in which a custom HTML file rendered the contents.",
      "identifier": "media-3425393",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4ae350e30a26b60ba6778dc31898455c/media-3425393@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4ae350e30a26b60ba6778dc31898455c/media-3425393~dark@2x.png"
        }
      ]
    },
    "media-3425394": {
      "alt": "Screenshot of a banner with the item’s title, subtitle, and price highlighted.",
      "identifier": "media-3425394",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1b0c4551566c670f5c1b8c0c087babf2/media-3425394@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0a2c7f5116e2e846797f5597fe3bf228/media-3425394~dark@2x.png"
        }
      ]
    },
    "media-3425395": {
      "alt": "Screenshot of an AR experience that features a banner that AR Quick Look renders with your custom HTML file.",
      "identifier": "media-3425395",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d1207e7ba8e09fcdf7249486169581e2/media-3425395@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d1207e7ba8e09fcdf7249486169581e2/media-3425395~dark@2x.png"
        }
      ]
    },
    "media-3425396": {
      "alt": "Screenshot of a banner featuring a custom hyperlink that reads “Add to cart”.",
      "identifier": "media-3425396",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/33f2cfa8289f72df4263aa05f90ca3e9/media-3425396@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/33f2cfa8289f72df4263aa05f90ca3e9/media-3425396~dark@2x.png"
        }
      ]
    },
    "media-3425397": {
      "alt": "Screenshot of a banner that features a custom action button using text that you supply.",
      "identifier": "media-3425397",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/f00d882d960a5b4acf1ba1db8d481d53/media-3425397@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/128645a326a0301bd1ef5970874214b2/media-3425397~dark@2x.png"
        }
      ]
    },
    "media-3432381": {
      "alt": "Screenshot of an AR experience featuring a banner that contains an Apple Pay button.",
      "identifier": "media-3432381",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/24a6635aab8ced19bff58a3c4231d0aa/media-3432381@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/24a6635aab8ced19bff58a3c4231d0aa/media-3432381~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "AR-Quick-Look",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
        "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit",
        "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem",
        "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar",
        "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look"
      ],
      "title": "AR Quick Look"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "AR-Quick-Look",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
                "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit",
                "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem",
                "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look"
              ],
              "title": "AR Quick Look"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/title",
          "value": "ARQuickLookPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
