{
  "abstract": [
    {
      "text": "Creates a reference image from a pixel buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.arkit/documentation/ARKit/ar_reference_image_create_from_pixel_buffer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@ar_reference_image_create_from_pixel_buffer",
    "fragments": [
      {
        "kind": "identifier",
        "text": "ar_reference_image_create_from_pixel_buffer"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ar_reference_image_create_from_pixel_buffer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "ar_reference_image_create_from_pixel_buffer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_reference_image_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ar_reference_image_t",
              "text": "ar_reference_image_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ar_reference_image_create_from_pixel_buffer"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CVPixelBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVPixelBufferRef",
              "text": "CVPixelBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pixelBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@CGImagePropertyOrientation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CGImagePropertyOrientation",
              "text": "CGImagePropertyOrientation"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "orientation"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "physicalWidth"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_anchor_get_estimated_scale_factor": {
      "abstract": [
        {
          "text": "Gets the estimated scale factor between the tracked image’s physical size and the reference image’s size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_anchor_get_estimated_scale_factor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_anchor_get_estimated_scale_factor",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_anchor_get_estimated_scale_factor",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_anchor_get_estimated_scale_factor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_anchor_get_reference_image": {
      "abstract": [
        {
          "text": "Gets the reference image that this image anchor tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_anchor_get_reference_image"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_anchor_get_reference_image",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_anchor_get_reference_image",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_anchor_get_reference_image"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_anchors_enumerate_anchors": {
      "abstract": [
        {
          "text": "Enumerates a collection of image anchors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_anchors_enumerate_anchors"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_anchors_enumerate_anchors",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_anchors_enumerate_anchors",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_anchors_enumerate_anchors"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_anchors_enumerate_anchors_f": {
      "abstract": [
        {
          "text": "Enumerates a collection of image anchors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_anchors_enumerate_anchors_f"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_anchors_enumerate_anchors_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_anchors_enumerate_anchors_f",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_anchors_enumerate_anchors_f"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_anchors_get_count": {
      "abstract": [
        {
          "text": "Gets the number of image anchors in the collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_anchors_get_count"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_anchors_get_count",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_anchors_get_count",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_anchors_get_count"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_configuration_add_reference_images": {
      "abstract": [
        {
          "text": "Adds reference images to the set to be tracked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_tracking_configuration_add_reference_images"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_configuration_add_reference_images",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_tracking_configuration_add_reference_images",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_tracking_configuration_add_reference_images"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_configuration_create": {
      "abstract": [
        {
          "text": "Creates an image tracking configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_tracking_configuration_create"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_configuration_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_tracking_configuration_create",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_tracking_configuration_create"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_configuration_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_tracking_configuration_t"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_configuration_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_tracking_configuration_t",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_tracking_configuration_t"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_create": {
      "abstract": [
        {
          "text": "Creates an image tracking provider that tracks the reference images you supply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_tracking_provider_create"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_tracking_provider_create",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_tracking_provider_create"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_get_required_authorization_type": {
      "abstract": [
        {
          "text": "Gets the types of authorizations required to track images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_tracking_provider_get_required_authorization_type"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_get_required_authorization_type",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_tracking_provider_get_required_authorization_type",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_tracking_provider_get_required_authorization_type"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_is_supported": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the current runtime environment supports image tracking providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_tracking_provider_is_supported"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_is_supported",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_tracking_provider_is_supported",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_tracking_provider_is_supported"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_set_update_handler": {
      "abstract": [
        {
          "text": "Sets the handler for receiving image tracking updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_tracking_provider_set_update_handler"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_set_update_handler",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_tracking_provider_set_update_handler",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_tracking_provider_set_update_handler"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_set_update_handler_f": {
      "abstract": [
        {
          "text": "Sets the handler for receiving image tracking updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_image_tracking_provider_set_update_handler_f"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_set_update_handler_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_image_tracking_provider_set_update_handler_f",
      "type": "topic",
      "url": "/documentation/arkit/ar_image_tracking_provider_set_update_handler_f"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_reference_image_create_from_pixel_buffer": {
      "abstract": [
        {
          "text": "Creates a reference image from a pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_reference_image_create_from_pixel_buffer"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_reference_image_create_from_pixel_buffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_reference_image_create_from_pixel_buffer",
      "type": "topic",
      "url": "/documentation/arkit/ar_reference_image_create_from_pixel_buffer"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_reference_image_t": {
      "abstract": [
        {
          "text": "A 2D image the system uses as a reference to find the same image in a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_reference_image_t"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_reference_image_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_reference_image_t",
      "type": "topic",
      "url": "/documentation/arkit/ar_reference_image_t"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_reference_images_enumerator_t": {
      "abstract": [
        {
          "text": "A handler for enumerating a collection of reference images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_reference_images_enumerator_t"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_reference_images_enumerator_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_reference_images_enumerator_t",
      "type": "topic",
      "url": "/documentation/arkit/ar_reference_images_enumerator_t"
    },
    "doc://com.apple.arkit/documentation/ARKit/ar_reference_images_t": {
      "abstract": [
        {
          "text": "A collection of reference images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ar_reference_images_t"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ar_reference_images_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "ar_reference_images_t",
      "type": "topic",
      "url": "/documentation/arkit/ar_reference_images_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@CGImagePropertyOrientation": {
      "abstract": [
        {
          "text": "A value describing the intended display orientation for an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImagePropertyOrientation"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@CGImagePropertyOrientation",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGImagePropertyOrientation",
      "type": "topic",
      "url": "/documentation/ImageIO/CGImagePropertyOrientation"
    },
    "doc://com.externally.resolved.symbol/c:@T@CVPixelBufferRef": {
      "abstract": [
        {
          "text": "A reference to a Core Video pixel buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CVPixelBufferRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/CoreVideo/CVPixelBuffer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-tracking",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ar_image_anchor_get_estimated_scale_factor",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_anchor_get_reference_image",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_anchors_enumerate_anchors",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_anchors_enumerate_anchors_f",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_anchors_get_count",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_create",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_is_supported",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_get_required_authorization_type",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_set_update_handler",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_provider_set_update_handler_f",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_configuration_add_reference_images",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_configuration_create",
        "doc://com.apple.arkit/documentation/ARKit/ar_image_tracking_configuration_t",
        "doc://com.apple.arkit/documentation/ARKit/ar_reference_images_t",
        "doc://com.apple.arkit/documentation/ARKit/ar_reference_images_enumerator_t"
      ],
      "title": "Image tracking"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CVPixelBufferRef/title",
          "value": "CVPixelBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CVPixelBufferRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVImageBufferRef",
              "text": "CVImageBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVPixelBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@CGImagePropertyOrientation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/ar_reference_image_create_from_pixel_buffer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
