{
  "abstract": [
    {
      "text": "Information about the camera position and imaging characteristics for a given frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARCamera"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARCamera",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ARCamera"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARCamera"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ARCamera"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARCamera"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.arkit/documentation/ARKit/managing-session-life-cycle-and-tracking-quality",
        "doc://com.apple.arkit/documentation/ARKit/understanding-world-tracking"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You get camera information from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFrame/camera",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of each ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFrame",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ARKit delivers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera": {
      "abstract": [
        {
          "text": "Information about the camera position and imaging characteristics for a given frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARCamera"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARCamera"
        }
      ],
      "role": "symbol",
      "title": "ARCamera",
      "type": "topic",
      "url": "/documentation/arkit/arcamera"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum": {
      "abstract": [
        {
          "text": "Values for position tracking quality, with possible causes when tracking quality is limited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TrackingState"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TrackingState"
        }
      ],
      "role": "symbol",
      "title": "ARCamera.TrackingState",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/eulerAngles": {
      "abstract": [
        {
          "text": "The orientation of the camera, expressed as roll, pitch, and yaw values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eulerAngles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float3",
          "text": "simd_float3"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/eulerAngles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eulerAngles"
        }
      ],
      "role": "symbol",
      "title": "eulerAngles",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/eulerangles"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/exposureDuration": {
      "abstract": [
        {
          "text": "A value you use to effect motion blur when rendering your app’s virtual content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exposureDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/exposureDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exposureDuration"
        }
      ],
      "role": "symbol",
      "title": "exposureDuration",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/exposureduration"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/exposureOffset": {
      "abstract": [
        {
          "text": "A value you supply to your custom renderer to light your scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exposureOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/exposureOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exposureOffset"
        }
      ],
      "role": "symbol",
      "title": "exposureOffset",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/exposureoffset"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/imageResolution": {
      "abstract": [
        {
          "text": "The width and height, in pixels, of the captured camera image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/imageResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageResolution"
        }
      ],
      "role": "symbol",
      "title": "imageResolution",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/imageresolution"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/intrinsics": {
      "abstract": [
        {
          "text": "A matrix that converts between the 2D camera plane and 3D world coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intrinsics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/intrinsics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intrinsics"
        }
      ],
      "role": "symbol",
      "title": "intrinsics",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/intrinsics"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectPoint(_:orientation:viewportSize:)": {
      "abstract": [
        {
          "text": "Returns the projection of a point from the 3D world space detected by ARKit into the 2D space of a view rendering the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float3",
          "text": "simd_float3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "viewportSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectPoint(_:orientation:viewportSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "projectPoint:orientation:viewportSize:"
        }
      ],
      "role": "symbol",
      "title": "projectPoint(_:orientation:viewportSize:)",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/projectpoint(_:orientation:viewportsize:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectionMatrix": {
      "abstract": [
        {
          "text": "A transform matrix appropriate for rendering 3D content to match the image captured by the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectionMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectionMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "projectionMatrix"
        }
      ],
      "role": "symbol",
      "title": "projectionMatrix",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/projectionmatrix"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectionMatrix(for:viewportSize:zNear:zFar:)": {
      "abstract": [
        {
          "text": "Returns a transform matrix appropriate for rendering 3D content to match the image captured by the camera, using the specified parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectionMatrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "viewportSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "zNear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "zFar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectionMatrix(for:viewportSize:zNear:zFar:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "projectionMatrixForOrientation:viewportSize:zNear:zFar:"
        }
      ],
      "role": "symbol",
      "title": "projectionMatrix(for:viewportSize:zNear:zFar:)",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/projectionmatrix(for:viewportsize:znear:zfar:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingState-6i3pt": {
      "abstract": [
        {
          "text": "The general quality of position tracking available when the camera captured a frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARCamera",
          "text": "ARCamera"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8ARCameraC5ARKitE13TrackingStateO",
          "text": "TrackingState"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingState-6i3pt",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackingState",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-6i3pt"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingState-9pgmq": {
      "abstract": [
        {
          "text": "The general quality of position tracking available when the camera captured a frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "trackingState"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingState-9pgmq",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackingState",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-9pgmq"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingStateReason": {
      "abstract": [
        {
          "text": "A possible diagnosis for limited position-tracking quality as of when the camera captured a frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "trackingStateReason"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingStateReason",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackingStateReason",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstatereason"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/transform": {
      "abstract": [
        {
          "text": "The position and orientation of the camera in world coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/transform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transform"
        }
      ],
      "role": "symbol",
      "title": "transform",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/transform"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/unprojectPoint(_:ontoPlane:orientation:viewportSize:)": {
      "abstract": [
        {
          "text": "Returns the projection of a point from the 2D space of a view rendering the scene onto a plane in the 3D world space detected by ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unprojectPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ontoPlane"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "viewportSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float3",
          "text": "simd_float3"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/unprojectPoint(_:ontoPlane:orientation:viewportSize:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "unprojectPoint(_:ontoPlane:orientation:viewportSize:)",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/unprojectpoint(_:ontoplane:orientation:viewportsize:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/unprojectPoint:ontoPlaneWithTransform:orientation:viewportSize:": {
      "abstract": [
        {
          "text": "Returns the projection of a point from the 2D space of a view rendering the scene onto a plane in the 3D world space detected by ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "unprojectPoint:ontoPlaneWithTransform:orientation:viewportSize:"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/unprojectPoint:ontoPlaneWithTransform:orientation:viewportSize:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unprojectPoint:ontoPlaneWithTransform:orientation:viewportSize:"
        }
      ],
      "role": "symbol",
      "title": "unprojectPoint:ontoPlaneWithTransform:orientation:viewportSize:",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/unprojectpoint:ontoplanewithtransform:orientation:viewportsize:"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/viewMatrix(for:)": {
      "abstract": [
        {
          "text": "Returns a transform matrix for converting from world space to camera space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewMatrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/viewMatrix(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewMatrixForOrientation:"
        }
      ],
      "role": "symbol",
      "title": "viewMatrix(for:)",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/viewmatrix(for:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFrame": {
      "abstract": [
        {
          "text": "A video image captured as part of a session with position-tracking information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARFrame"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARFrame"
        }
      ],
      "role": "symbol",
      "title": "ARFrame",
      "type": "topic",
      "url": "/documentation/arkit/arframe"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFrame/camera": {
      "abstract": [
        {
          "text": "Information about the camera position, orientation, and imaging parameters used to capture the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "camera"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARCamera",
          "text": "ARCamera"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFrame/camera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "camera"
        }
      ],
      "role": "symbol",
      "title": "camera",
      "type": "topic",
      "url": "/documentation/arkit/arframe/camera"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARTrackingState": {
      "abstract": [
        {
          "text": "Possible values for position-tracking quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARTrackingState"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARTrackingState",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARTrackingState",
      "type": "topic",
      "url": "/documentation/arkit/artrackingstate"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARTrackingStateReason": {
      "abstract": [
        {
          "text": "Possible causes for limited position-tracking quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARTrackingStateReason"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARTrackingStateReason",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARTrackingStateReason",
      "type": "topic",
      "url": "/documentation/arkit/artrackingstatereason"
    },
    "doc://com.apple.arkit/documentation/ARKit/managing-session-life-cycle-and-tracking-quality": {
      "abstract": [
        {
          "text": "Keep the user informed on the current session state and recover from interruptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/managing-session-life-cycle-and-tracking-quality",
      "kind": "article",
      "role": "article",
      "title": "Managing Session Life Cycle and Tracking Quality",
      "type": "topic",
      "url": "/documentation/arkit/managing-session-life-cycle-and-tracking-quality"
    },
    "doc://com.apple.arkit/documentation/ARKit/understanding-world-tracking": {
      "abstract": [
        {
          "text": "Discover features and best practices for building rear-camera AR experiences.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/understanding-world-tracking",
      "kind": "article",
      "role": "article",
      "title": "Understanding World Tracking",
      "type": "topic",
      "url": "/documentation/arkit/understanding-world-tracking"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Handling-Tracking-Status",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingState-6i3pt",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum"
      ],
      "title": "Handling Tracking Status"
    },
    {
      "anchor": "Examining-Camera-Geometry",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/transform",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/eulerAngles"
      ],
      "title": "Examining Camera Geometry"
    },
    {
      "anchor": "Examining-Imaging-Parameters",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/imageResolution",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/intrinsics"
      ],
      "title": "Examining Imaging Parameters"
    },
    {
      "anchor": "Applying-Camera-Geometry",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectionMatrix",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectionMatrix(for:viewportSize:zNear:zFar:)",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/viewMatrix(for:)",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectPoint(_:orientation:viewportSize:)",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/unprojectPoint(_:ontoPlane:orientation:viewportSize:)"
      ],
      "title": "Applying Camera Geometry"
    },
    {
      "anchor": "Applying-Motion-Blur",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/exposureDuration"
      ],
      "title": "Applying Motion Blur"
    },
    {
      "anchor": "Applying-Post-Processed-Lighting",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/exposureOffset"
      ],
      "title": "Applying Post-Processed Lighting"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARCamera"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-Tracking-Status",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingState-9pgmq",
                "doc://com.apple.arkit/documentation/ARKit/ARTrackingState",
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingStateReason",
                "doc://com.apple.arkit/documentation/ARKit/ARTrackingStateReason"
              ],
              "title": "Handling Tracking Status"
            },
            {
              "anchor": "Examining-Camera-Geometry",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/transform",
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/eulerAngles"
              ],
              "title": "Examining Camera Geometry"
            },
            {
              "anchor": "Examining-Imaging-Parameters",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/imageResolution",
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/intrinsics"
              ],
              "title": "Examining Imaging Parameters"
            },
            {
              "anchor": "Applying-Camera-Geometry",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectionMatrix",
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectionMatrix(for:viewportSize:zNear:zFar:)",
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/viewMatrix(for:)",
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/projectPoint(_:orientation:viewportSize:)",
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/unprojectPoint:ontoPlaneWithTransform:orientation:viewportSize:"
              ],
              "title": "Applying Camera Geometry"
            },
            {
              "anchor": "Applying-Motion-Blur",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/exposureDuration"
              ],
              "title": "Applying Motion Blur"
            },
            {
              "anchor": "Applying-Post-Processed-Lighting",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARCamera/exposureOffset"
              ],
              "title": "Applying Post-Processed Lighting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARCamera"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFrame~1camera/title",
          "value": "camera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFrame~1camera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "camera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1eulerAngles/title",
          "value": "eulerAngles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1eulerAngles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eulerAngles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1projectionMatrix(for:viewportSize:zNear:zFar:)/title",
          "value": "projectionMatrixForOrientation:viewportSize:zNear:zFar:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1projectionMatrix(for:viewportSize:zNear:zFar:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "projectionMatrixForOrientation:viewportSize:zNear:zFar:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1exposureOffset/title",
          "value": "exposureOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1exposureOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exposureOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1projectionMatrix/title",
          "value": "projectionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1projectionMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "projectionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1imageResolution/title",
          "value": "imageResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1imageResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1projectPoint(_:orientation:viewportSize:)/title",
          "value": "projectPoint:orientation:viewportSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1projectPoint(_:orientation:viewportSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "projectPoint:orientation:viewportSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFrame/title",
          "value": "ARFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1exposureDuration/title",
          "value": "exposureDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1exposureDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exposureDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1transform/title",
          "value": "transform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1transform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1intrinsics/title",
          "value": "intrinsics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1intrinsics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "intrinsics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera/title",
          "value": "ARCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1viewMatrix(for:)/title",
          "value": "viewMatrixForOrientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera~1viewMatrix(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewMatrixForOrientation:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arcamera"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arcamera"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
