{
  "abstract": [
    {
      "text": "A set of callbacks you implement to be notified of coaching events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ARCoachingOverlayViewDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ARCoachingOverlayViewDelegate"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARCoachingOverlayViewDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "ARCoachingOverlayViewDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARCoachingOverlayViewDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement a delegate to coordinate your app’s actions with coaching overlay. For example, when the coaching overlay determines the user needs guidance, you hide your app’s UI to allow the user to focus on the coaching experience. When the coaching overlay determines the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView/goal-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is met, you show your app’s UI and begin your app’s AR experience.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView/delegate": {
      "abstract": [
        {
          "text": "An object you supply that implements coaching event callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)ARCoachingOverlayViewDelegate",
          "text": "ARCoachingOverlayViewDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/arkit/arcoachingoverlayview/delegate"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView/goal-swift.property": {
      "abstract": [
        {
          "text": "A field that indicates your app’s tracking requirements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARCoachingOverlayView",
          "text": "ARCoachingOverlayView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARCoachingGoal",
          "text": "Goal"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView/goal-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goal"
        }
      ],
      "role": "symbol",
      "title": "goal",
      "type": "topic",
      "url": "/documentation/arkit/arcoachingoverlayview/goal-swift.property"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate": {
      "abstract": [
        {
          "text": "A set of callbacks you implement to be notified of coaching events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARCoachingOverlayViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARCoachingOverlayViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "ARCoachingOverlayViewDelegate",
      "type": "topic",
      "url": "/documentation/arkit/arcoachingoverlayviewdelegate"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewDidDeactivate(_:)": {
      "abstract": [
        {
          "text": "Tells you when the coaching experience is completely deactivated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coachingOverlayViewDidDeactivate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARCoachingOverlayView",
          "text": "ARCoachingOverlayView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewDidDeactivate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coachingOverlayViewDidDeactivate:"
        }
      ],
      "role": "symbol",
      "title": "coachingOverlayViewDidDeactivate(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arcoachingoverlayviewdelegate/coachingoverlayviewdiddeactivate(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewDidRequestSessionReset(_:)": {
      "abstract": [
        {
          "text": "Tells you when the user taps the coaching overlay view’s Start Over button while the session is relocalizing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coachingOverlayViewDidRequestSessionReset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARCoachingOverlayView",
          "text": "ARCoachingOverlayView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewDidRequestSessionReset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coachingOverlayViewDidRequestSessionReset:"
        }
      ],
      "role": "symbol",
      "title": "coachingOverlayViewDidRequestSessionReset(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arcoachingoverlayviewdelegate/coachingoverlayviewdidrequestsessionreset(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewWillActivate(_:)": {
      "abstract": [
        {
          "text": "Tells you when the coaching overlay view activates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coachingOverlayViewWillActivate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARCoachingOverlayView",
          "text": "ARCoachingOverlayView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewWillActivate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coachingOverlayViewWillActivate:"
        }
      ],
      "role": "symbol",
      "title": "coachingOverlayViewWillActivate(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arcoachingoverlayviewdelegate/coachingoverlayviewwillactivate(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Delegating-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView/delegate"
      ],
      "title": "Delegating Events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enabling-Coaching",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewWillActivate(_:)",
        "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewDidDeactivate(_:)"
      ],
      "title": "Enabling Coaching"
    },
    {
      "anchor": "Restarting-the-Session",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewDidRequestSessionReset(_:)"
      ],
      "title": "Restarting the Session"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARCoachingOverlayViewDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCoachingOverlayViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCoachingOverlayViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enabling-Coaching",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewWillActivate(_:)",
                "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewDidDeactivate(_:)"
              ],
              "title": "Enabling Coaching"
            },
            {
              "anchor": "Restarting-the-Session",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayViewDelegate/coachingOverlayViewDidRequestSessionReset(_:)"
              ],
              "title": "Restarting the Session"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Delegating-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView/delegate"
              ],
              "title": "Delegating Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARCoachingOverlayViewDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayView~1goal-swift.property/title",
          "value": "goal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayView~1goal-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "goal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayView~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayView~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayViewDelegate~1coachingOverlayViewWillActivate(_:)/title",
          "value": "coachingOverlayViewWillActivate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayViewDelegate~1coachingOverlayViewWillActivate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "coachingOverlayViewWillActivate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayViewDelegate~1coachingOverlayViewDidRequestSessionReset(_:)/title",
          "value": "coachingOverlayViewDidRequestSessionReset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayViewDelegate~1coachingOverlayViewDidRequestSessionReset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "coachingOverlayViewDidRequestSessionReset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayViewDelegate~1coachingOverlayViewDidDeactivate(_:)/title",
          "value": "coachingOverlayViewDidDeactivate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayViewDelegate~1coachingOverlayViewDidDeactivate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "coachingOverlayViewDidDeactivate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayViewDelegate/title",
          "value": "ARCoachingOverlayViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCoachingOverlayViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCoachingOverlayViewDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arcoachingoverlayviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arcoachingoverlayviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
