{
  "abstract": [
    {
      "text": "An error reported by ARKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11ARErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ARError"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "ARError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError": {
      "abstract": [
        {
          "text": "An error reported by ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARError"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARError"
        }
      ],
      "role": "symbol",
      "title": "ARError",
      "type": "topic",
      "url": "/documentation/arkit/arerror"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code": {
      "abstract": [
        {
          "text": "Codes that identify errors in ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/cameraUnauthorized": {
      "abstract": [
        {
          "text": "An error that indicates the app lacks user permission for the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraUnauthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/cameraUnauthorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "cameraUnauthorized",
      "type": "topic",
      "url": "/documentation/arkit/arerror/cameraunauthorized"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/arkit/arerror/errordomain"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/fileIOFailed": {
      "abstract": [
        {
          "text": "An error that indicates a file access fails to read or write.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileIOFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/fileIOFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "fileIOFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/fileiofailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/geoTrackingFailed": {
      "abstract": [
        {
          "text": "An error that indicates when localization imagery fails to match the device’s camera captures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geoTrackingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/geoTrackingFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "geoTrackingFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/geotrackingfailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/geoTrackingNotAvailableAtLocation": {
      "abstract": [
        {
          "text": "An error that indicates a location lacks geotracking support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geoTrackingNotAvailableAtLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/geoTrackingNotAvailableAtLocation",
      "kind": "symbol",
      "role": "symbol",
      "title": "geoTrackingNotAvailableAtLocation",
      "type": "topic",
      "url": "/documentation/arkit/arerror/geotrackingnotavailableatlocation"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/highResolutionFrameCaptureFailed": {
      "abstract": [
        {
          "text": "An error that indicates a problem in the system’s capture pipeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highResolutionFrameCaptureFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/highResolutionFrameCaptureFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "highResolutionFrameCaptureFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/highresolutionframecapturefailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/highResolutionFrameCaptureInProgress": {
      "abstract": [
        {
          "text": "An error that indicates the system needs to finish a high-resolution frame request before accepting another request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highResolutionFrameCaptureInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/highResolutionFrameCaptureInProgress",
      "kind": "symbol",
      "role": "symbol",
      "title": "highResolutionFrameCaptureInProgress",
      "type": "topic",
      "url": "/documentation/arkit/arerror/highresolutionframecaptureinprogress"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/insufficientFeatures": {
      "abstract": [
        {
          "text": "An error that indicates the framework requires more features to complete a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientFeatures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/insufficientFeatures",
      "kind": "symbol",
      "role": "symbol",
      "title": "insufficientFeatures",
      "type": "topic",
      "url": "/documentation/arkit/arerror/insufficientfeatures"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/invalidCollaborationData": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to parse collaboration data the app receives over the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCollaborationData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/invalidCollaborationData",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidCollaborationData",
      "type": "topic",
      "url": "/documentation/arkit/arerror/invalidcollaborationdata"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/invalidConfiguration": {
      "abstract": [
        {
          "text": "An error that indicates the configuration contains ambiguous or erroneous data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/invalidConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidConfiguration",
      "type": "topic",
      "url": "/documentation/arkit/arerror/invalidconfiguration"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/invalidReferenceImage": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to process a reference image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidReferenceImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/invalidReferenceImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidReferenceImage",
      "type": "topic",
      "url": "/documentation/arkit/arerror/invalidreferenceimage"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/invalidReferenceObject": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to process a reference object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidReferenceObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/invalidReferenceObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidReferenceObject",
      "type": "topic",
      "url": "/documentation/arkit/arerror/invalidreferenceobject"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/invalidWorldMap": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to process a world map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidWorldMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/invalidWorldMap",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidWorldMap",
      "type": "topic",
      "url": "/documentation/arkit/arerror/invalidworldmap"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/locationUnauthorized": {
      "abstract": [
        {
          "text": "An error that indicates the app lacks user permission for the device’s current location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationUnauthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/locationUnauthorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "locationUnauthorized",
      "type": "topic",
      "url": "/documentation/arkit/arerror/locationunauthorized"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/microphoneUnauthorized": {
      "abstract": [
        {
          "text": "An error that indicates the app lacks user permission for the microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microphoneUnauthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/microphoneUnauthorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "microphoneUnauthorized",
      "type": "topic",
      "url": "/documentation/arkit/arerror/microphoneunauthorized"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/objectMergeFailed": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to merge a detected object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectMergeFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/objectMergeFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "objectMergeFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/objectmergefailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/requestFailed": {
      "abstract": [
        {
          "text": "An error that indicates a request fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/requestFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/requestfailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/sensorFailed": {
      "abstract": [
        {
          "text": "An error that indicates a sensor fails to provide required input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/sensorFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "sensorFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/sensorfailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/sensorUnavailable": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to access a required sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/sensorUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "sensorUnavailable",
      "type": "topic",
      "url": "/documentation/arkit/arerror/sensorunavailable"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/unsupportedConfiguration": {
      "abstract": [
        {
          "text": "An error that indicates the device lacks support for the session’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/unsupportedConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedConfiguration",
      "type": "topic",
      "url": "/documentation/arkit/arerror/unsupportedconfiguration"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/worldTrackingFailed": {
      "abstract": [
        {
          "text": "An error that indicates when world tracking experiences an unrecoverable problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "worldTrackingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ARErrorCodeLeV",
          "text": "ARError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/worldTrackingFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "worldTrackingFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/worldtrackingfailed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-error-information",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARError/errorDomain"
      ],
      "title": "Inspecting error information"
    },
    {
      "anchor": "Identifying-an-error-cause",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code",
        "doc://com.apple.arkit/documentation/ARKit/ARError/requestFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/cameraUnauthorized",
        "doc://com.apple.arkit/documentation/ARKit/ARError/fileIOFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/insufficientFeatures",
        "doc://com.apple.arkit/documentation/ARKit/ARError/invalidCollaborationData",
        "doc://com.apple.arkit/documentation/ARKit/ARError/invalidConfiguration",
        "doc://com.apple.arkit/documentation/ARKit/ARError/invalidReferenceImage",
        "doc://com.apple.arkit/documentation/ARKit/ARError/invalidReferenceObject",
        "doc://com.apple.arkit/documentation/ARKit/ARError/invalidWorldMap",
        "doc://com.apple.arkit/documentation/ARKit/ARError/microphoneUnauthorized",
        "doc://com.apple.arkit/documentation/ARKit/ARError/objectMergeFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/sensorFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/sensorUnavailable",
        "doc://com.apple.arkit/documentation/ARKit/ARError/unsupportedConfiguration",
        "doc://com.apple.arkit/documentation/ARKit/ARError/worldTrackingFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/geoTrackingFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/geoTrackingNotAvailableAtLocation",
        "doc://com.apple.arkit/documentation/ARKit/ARError/locationUnauthorized",
        "doc://com.apple.arkit/documentation/ARKit/ARError/highResolutionFrameCaptureFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/highResolutionFrameCaptureInProgress"
      ],
      "title": "Identifying an error cause"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code/title",
          "value": "ARErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
