{
  "abstract": [
    {
      "text": "The state, accuracy, and reason that are possible for geo-tracking’s current condition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARGeoTrackingStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ARGeoTrackingStatus"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARGeoTrackingStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ARGeoTrackingStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Geo tracking requires coordination with the user at various phases of the geo-tracking lifecycle. To elicit the right user actions, an app needs to provide clear instructions to the user based on the current frame’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFrame/geoTrackingStatus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Geo-tracking ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/state-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " most notably regards the important process in which ARKit acquires a better understanding of the user’s geographic location and orientation than is possible with GPS and the compass heading alone. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/State-swift.enum/localizing",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for more information.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Given a particular ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/state-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", the app needs to tailor its user messaging according to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/stateReason-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An app may need to monitor ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/accuracy-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " closely if it requires high-precision localization.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFrame/geoTrackingStatus": {
      "abstract": [
        {
          "text": "The session’s condition with respect to geographic tracking at the time the session captured the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geoTrackingStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARGeoTrackingStatus",
          "text": "ARGeoTrackingStatus"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFrame/geoTrackingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "geoTrackingStatus"
        }
      ],
      "role": "symbol",
      "title": "geoTrackingStatus",
      "type": "topic",
      "url": "/documentation/arkit/arframe/geotrackingstatus"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus": {
      "abstract": [
        {
          "text": "The state, accuracy, and reason that are possible for geo-tracking’s current condition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStatus"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStatus"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum": {
      "abstract": [
        {
          "text": "Values that are possible for the current accuracy of geo tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Accuracy"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Accuracy"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.Accuracy",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/accuracy-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/State-swift.enum": {
      "abstract": [
        {
          "text": "Values that are possible for the current state of geo-tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.State",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/state-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/State-swift.enum/localizing": {
      "abstract": [
        {
          "text": "Geo tracking is attempting to localize against a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizing"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/State-swift.enum/localizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStateLocalizing"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.State.localizing",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/state-swift.enum/localizing"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum": {
      "abstract": [
        {
          "text": "The reasons for the app’s geotracking status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StateReason"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StateReason"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.StateReason",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/accuracy-swift.property": {
      "abstract": [
        {
          "text": "The accuracy of geo tracking at the time the session captured the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARGeoTrackingStatus",
          "text": "ARGeoTrackingStatus"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARGeoTrackingAccuracy",
          "text": "Accuracy"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/accuracy-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accuracy"
        }
      ],
      "role": "symbol",
      "title": "accuracy",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/accuracy-swift.property"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/state-swift.property": {
      "abstract": [
        {
          "text": "A value that describes the session’s current geo-tracking state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARGeoTrackingStatus",
          "text": "ARGeoTrackingStatus"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARGeoTrackingState",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/state-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/state-swift.property"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/stateReason-swift.property": {
      "abstract": [
        {
          "text": "The reasons for the app’s geotracking status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARGeoTrackingStatus",
          "text": "ARGeoTrackingStatus"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARGeoTrackingStateReason",
          "text": "StateReason"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/stateReason-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stateReason"
        }
      ],
      "role": "symbol",
      "title": "stateReason",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/statereason-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Assessing-geo-tracking-condition",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARFrame/geoTrackingStatus"
      ],
      "title": "Assessing geo-tracking condition"
    }
  ],
  "topicSections": [
    {
      "anchor": "Checking-State",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/state-swift.property",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/State-swift.enum"
      ],
      "title": "Checking State"
    },
    {
      "anchor": "Determining-the-Reason",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/stateReason-swift.property",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum"
      ],
      "title": "Determining the Reason"
    },
    {
      "anchor": "Judging-Accuracy",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/accuracy-swift.property",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum"
      ],
      "title": "Judging Accuracy"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARGeoTrackingStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Checking-State",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/state-swift.property",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/State-swift.enum"
              ],
              "title": "Checking State"
            },
            {
              "anchor": "Determining-the-Reason",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/stateReason-swift.property",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/StateReason-swift.enum"
              ],
              "title": "Determining the Reason"
            },
            {
              "anchor": "Judging-Accuracy",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/accuracy-swift.property",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum"
              ],
              "title": "Judging Accuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Assessing-geo-tracking-condition",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARFrame/geoTrackingStatus"
              ],
              "title": "Assessing geo-tracking condition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARGeoTrackingStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1State-swift.enum~1localizing/title",
          "value": "ARGeoTrackingStateLocalizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1State-swift.enum~1localizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateLocalizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1State-swift.enum/title",
          "value": "ARGeoTrackingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1state-swift.property/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1state-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1stateReason-swift.property/title",
          "value": "stateReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1stateReason-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stateReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/title",
          "value": "ARGeoTrackingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1accuracy-swift.property/title",
          "value": "accuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1accuracy-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum/title",
          "value": "ARGeoTrackingAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum/title",
          "value": "ARGeoTrackingStateReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1StateReason-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStateReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFrame~1geoTrackingStatus/title",
          "value": "geoTrackingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFrame~1geoTrackingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "geoTrackingStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/argeotrackingstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/argeotrackingstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
