{
  "abstract": [
    {
      "text": "Integrate iOS device camera and motion features to produce augmented reality experiences in your app or game.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ARKit in iOS"
  },
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAnchor": {
      "abstract": [
        {
          "text": "An object that specifies the position and orientation of an item in the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARAnchor",
      "type": "topic",
      "url": "/documentation/arkit/aranchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView": {
      "abstract": [
        {
          "text": "A view that displays standardized onboarding instructions to direct users toward a specific goal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARCoachingOverlayView"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARCoachingOverlayView"
        }
      ],
      "role": "symbol",
      "title": "ARCoachingOverlayView",
      "type": "topic",
      "url": "/documentation/arkit/arcoachingoverlayview"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError": {
      "abstract": [
        {
          "text": "An error reported by ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARError"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARError"
        }
      ],
      "role": "symbol",
      "title": "ARError",
      "type": "topic",
      "url": "/documentation/arkit/arerror"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code": {
      "abstract": [
        {
          "text": "Codes that identify errors in ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARParticipantAnchor": {
      "abstract": [
        {
          "text": "An anchor for another user in multiuser augmented reality experiences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARParticipantAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARParticipantAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARParticipantAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARParticipantAnchor",
      "type": "topic",
      "url": "/documentation/arkit/arparticipantanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem": {
      "abstract": [
        {
          "text": "An object for customizing the AR Quick Look experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARQuickLookPreviewItem"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARQuickLookPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "ARQuickLookPreviewItem",
      "type": "topic",
      "url": "/documentation/arkit/arquicklookpreviewitem"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSCNView": {
      "abstract": [
        {
          "text": "A view that blends virtual 3D content from SceneKit into your augmented reality experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSCNView"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSCNView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSCNView"
        }
      ],
      "role": "symbol",
      "title": "ARSCNView",
      "type": "topic",
      "url": "/documentation/arkit/arscnview"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSKView": {
      "abstract": [
        {
          "text": "A view that blends virtual 2D content from SpriteKit into the 3D space of an augmented reality experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSKView"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSKView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSKView"
        }
      ],
      "role": "symbol",
      "title": "ARSKView",
      "type": "topic",
      "url": "/documentation/arkit/arskview"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSession": {
      "abstract": [
        {
          "text": "The object that manages the major tasks associated with every AR experience, such as motion tracking, camera passthrough, and image analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "role": "symbol",
      "title": "ARSession",
      "type": "topic",
      "url": "/documentation/arkit/arsession"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSession/CollaborationData": {
      "abstract": [
        {
          "text": "An object that holds information that a user has collected about the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CollaborationData"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession/CollaborationData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CollaborationData"
        }
      ],
      "role": "symbol",
      "title": "ARSession.CollaborationData",
      "type": "topic",
      "url": "/documentation/arkit/arsession/collaborationdata"
    },
    "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look": {
      "abstract": [
        {
          "text": "Provide a banner that users can tap to make a purchase or perform a custom action in an AR experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Adding an Apple Pay Button or a Custom Action in AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look"
    },
    "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit": {
      "abstract": [
        {
          "text": "Balance the appearance and performance of your AR experiences with modeling strategies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit",
      "kind": "article",
      "role": "article",
      "title": "Adding Visual Effects in AR Quick Look and RealityKit",
      "type": "topic",
      "url": "/documentation/arkit/adding-visual-effects-in-ar-quick-look-and-realitykit"
    },
    "doc://com.apple.arkit/documentation/ARKit/camera-lighting-and-effects": {
      "abstract": [
        {
          "text": "Determine the camera position and lighting for the current session, and apply effects, such as occlusion, to elements of the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/camera-lighting-and-effects",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Camera, Lighting, and Effects",
      "type": "topic",
      "url": "/documentation/arkit/camera-lighting-and-effects"
    },
    "doc://com.apple.arkit/documentation/ARKit/choosing-which-camera-feed-to-augment": {
      "abstract": [
        {
          "text": "Add visual effects to the user’s environment in an AR experience through the front or rear camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/choosing-which-camera-feed-to-augment",
      "kind": "article",
      "role": "article",
      "title": "Choosing Which Camera Feed to Augment",
      "type": "topic",
      "url": "/documentation/arkit/choosing-which-camera-feed-to-augment"
    },
    "doc://com.apple.arkit/documentation/ARKit/configuration-objects": {
      "abstract": [
        {
          "text": "Configure your augmented reality session to detect and track specific types of content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/configuration-objects",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Configuration Objects",
      "type": "topic",
      "url": "/documentation/arkit/configuration-objects"
    },
    "doc://com.apple.arkit/documentation/ARKit/content-anchors": {
      "abstract": [
        {
          "text": "Identify items in the physical environment, including planar surfaces, images, physical objects, body positions, and faces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/content-anchors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Content Anchors",
      "type": "topic",
      "url": "/documentation/arkit/content-anchors"
    },
    "doc://com.apple.arkit/documentation/ARKit/creating-a-collaborative-session": {
      "abstract": [
        {
          "text": "Enable nearby devices to share an AR experience by using a peer-to-peer multiuser strategy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/creating-a-collaborative-session",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a collaborative session",
      "type": "topic",
      "url": "/documentation/arkit/creating-a-collaborative-session"
    },
    "doc://com.apple.arkit/documentation/ARKit/creating-a-multiuser-ar-experience": {
      "abstract": [
        {
          "text": "Enable nearby devices to share an AR experience by using a host-guest multiuser strategy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/creating-a-multiuser-ar-experience",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a multiuser AR experience",
      "type": "topic",
      "url": "/documentation/arkit/creating-a-multiuser-ar-experience"
    },
    "doc://com.apple.arkit/documentation/ARKit/creating-an-immersive-ar-experience-with-audio": {
      "abstract": [
        {
          "text": "Use sound effects and environmental sound layers to create an engaging AR experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/creating-an-immersive-ar-experience-with-audio",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating an immersive ar experience with audio",
      "type": "topic",
      "url": "/documentation/arkit/creating-an-immersive-ar-experience-with-audio"
    },
    "doc://com.apple.arkit/documentation/ARKit/data-management": {
      "abstract": [
        {
          "text": "Obtain detailed information about skeletal and face geometry, and saved world data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/data-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Management",
      "type": "topic",
      "url": "/documentation/arkit/data-management"
    },
    "doc://com.apple.arkit/documentation/ARKit/displaying-an-ar-experience-with-metal": {
      "abstract": [
        {
          "text": "Control rendering of your app’s virtual content on top of a camera feed.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/displaying-an-ar-experience-with-metal",
      "kind": "article",
      "role": "article",
      "title": "Displaying an AR Experience with Metal",
      "type": "topic",
      "url": "/documentation/arkit/displaying-an-ar-experience-with-metal"
    },
    "doc://com.apple.arkit/documentation/ARKit/environmental-analysis": {
      "abstract": [
        {
          "text": "Analyze the video from the cameras and the accompanying data, and use ray-casting and depth-map information to determine the location of items.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/environmental-analysis",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Environmental Analysis",
      "type": "topic",
      "url": "/documentation/arkit/environmental-analysis"
    },
    "doc://com.apple.arkit/documentation/ARKit/managing-session-life-cycle-and-tracking-quality": {
      "abstract": [
        {
          "text": "Keep the user informed on the current session state and recover from interruptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/managing-session-life-cycle-and-tracking-quality",
      "kind": "article",
      "role": "article",
      "title": "Managing Session Life Cycle and Tracking Quality",
      "type": "topic",
      "url": "/documentation/arkit/managing-session-life-cycle-and-tracking-quality"
    },
    "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look": {
      "abstract": [
        {
          "text": "Display a model or scene that the user can move, scale, and share with others.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Previewing a Model with AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/previewing-a-model-with-ar-quick-look"
    },
    "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look": {
      "abstract": [
        {
          "text": "Add metadata to your USDZ file to specify its lighting characteristics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Specifying a lighting environment in AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/specifying-a-lighting-environment-in-ar-quick-look"
    },
    "doc://com.apple.arkit/documentation/ARKit/streaming-an-ar-experience": {
      "abstract": [
        {
          "text": "Control an AR experience remotely by transferring sensor and user input over the network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/streaming-an-ar-experience",
      "kind": "article",
      "role": "sampleCode",
      "title": "Streaming an AR experience",
      "type": "topic",
      "url": "/documentation/arkit/streaming-an-ar-experience"
    },
    "doc://com.apple.arkit/documentation/ARKit/verifying-device-support-and-user-permission": {
      "abstract": [
        {
          "text": "Check whether your app can use ARKit and respect user privacy at runtime.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/verifying-device-support-and-user-permission",
      "kind": "article",
      "role": "article",
      "title": "Verifying Device Support and User Permission",
      "type": "topic",
      "url": "/documentation/arkit/verifying-device-support-and-user-permission"
    },
    "doc://com.apple.documentation/documentation/RealityKit/ARView": {
      "abstract": [
        {
          "text": "A view that enables you to display an AR experience with RealityKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@objc"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/ARView",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARView",
      "type": "topic",
      "url": "/documentation/RealityKit/ARView"
    },
    "doc://com.apple.documentation/documentation/RealityKit/creating-usd-files-for-apple-devices": {
      "abstract": [
        {
          "text": "Generate 3D assets that render as expected.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/creating-usd-files-for-apple-devices",
      "kind": "article",
      "role": "article",
      "title": "Creating USD files for Apple devices",
      "type": "topic",
      "url": "/documentation/RealityKit/creating-usd-files-for-apple-devices"
    },
    "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar": {
      "abstract": [
        {
          "text": "Add augmented reality functionality to your 3D content using USDZ schemas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar",
      "kind": "article",
      "role": "article",
      "title": "USDZ schemas for AR",
      "type": "topic",
      "url": "/documentation/RealityKit/usdz-schemas-for-ar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "iOS",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/verifying-device-support-and-user-permission",
        "doc://com.apple.arkit/documentation/ARKit/ARSession",
        "doc://com.apple.arkit/documentation/ARKit/ARAnchor"
      ],
      "title": "iOS"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/verifying-device-support-and-user-permission",
        "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Setup",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/choosing-which-camera-feed-to-augment",
        "doc://com.apple.arkit/documentation/ARKit/managing-session-life-cycle-and-tracking-quality",
        "doc://com.apple.arkit/documentation/ARKit/displaying-an-ar-experience-with-metal",
        "doc://com.apple.arkit/documentation/ARKit/ARSession",
        "doc://com.apple.arkit/documentation/ARKit/configuration-objects"
      ],
      "title": "Setup"
    },
    {
      "anchor": "Views",
      "identifiers": [
        "doc://com.apple.documentation/documentation/RealityKit/ARView",
        "doc://com.apple.arkit/documentation/ARKit/ARSCNView",
        "doc://com.apple.arkit/documentation/ARKit/ARSKView",
        "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView"
      ],
      "title": "Views"
    },
    {
      "anchor": "Virtual-Content",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/content-anchors",
        "doc://com.apple.arkit/documentation/ARKit/environmental-analysis",
        "doc://com.apple.arkit/documentation/ARKit/camera-lighting-and-effects",
        "doc://com.apple.arkit/documentation/ARKit/data-management",
        "doc://com.apple.documentation/documentation/RealityKit/creating-usd-files-for-apple-devices"
      ],
      "title": "Virtual Content"
    },
    {
      "abstract": [
        {
          "text": "Add an AR experience to your app or website, or customize your content’s appearance in Quick Look.",
          "type": "text"
        }
      ],
      "anchor": "AR-Quick-Look",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
        "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit",
        "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look",
        "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem",
        "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar",
        "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look"
      ],
      "title": "AR Quick Look"
    },
    {
      "abstract": [
        {
          "text": "Communicate with other devices to create a shared AR experience.",
          "type": "text"
        }
      ],
      "anchor": "Shared-Experiences",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/streaming-an-ar-experience",
        "doc://com.apple.arkit/documentation/ARKit/creating-a-collaborative-session",
        "doc://com.apple.arkit/documentation/ARKit/creating-a-multiuser-ar-experience",
        "doc://com.apple.arkit/documentation/ARKit/ARParticipantAnchor",
        "doc://com.apple.arkit/documentation/ARKit/ARSession/CollaborationData"
      ],
      "title": "Shared Experiences"
    },
    {
      "anchor": "Audio",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/creating-an-immersive-ar-experience-with-audio"
      ],
      "title": "Audio"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARError",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/verifying-device-support-and-user-permission",
                "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Setup",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/choosing-which-camera-feed-to-augment",
                "doc://com.apple.arkit/documentation/ARKit/managing-session-life-cycle-and-tracking-quality",
                "doc://com.apple.arkit/documentation/ARKit/displaying-an-ar-experience-with-metal",
                "doc://com.apple.arkit/documentation/ARKit/ARSession",
                "doc://com.apple.arkit/documentation/ARKit/configuration-objects"
              ],
              "title": "Setup"
            },
            {
              "anchor": "Views",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARSCNView",
                "doc://com.apple.arkit/documentation/ARKit/ARSKView",
                "doc://com.apple.arkit/documentation/ARKit/ARCoachingOverlayView"
              ],
              "title": "Views"
            },
            {
              "anchor": "Virtual-Content",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/content-anchors",
                "doc://com.apple.arkit/documentation/ARKit/environmental-analysis",
                "doc://com.apple.arkit/documentation/ARKit/camera-lighting-and-effects",
                "doc://com.apple.arkit/documentation/ARKit/data-management",
                "doc://com.apple.documentation/documentation/RealityKit/creating-usd-files-for-apple-devices"
              ],
              "title": "Virtual Content"
            },
            {
              "abstract": [
                {
                  "text": "Add an AR experience to your app or website, or customize your content’s appearance in Quick Look.",
                  "type": "text"
                }
              ],
              "anchor": "AR-Quick-Look",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
                "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit",
                "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look",
                "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem",
                "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar",
                "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look"
              ],
              "title": "AR Quick Look"
            },
            {
              "abstract": [
                {
                  "text": "Communicate with other devices to create a shared AR experience.",
                  "type": "text"
                }
              ],
              "anchor": "Shared-Experiences",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/streaming-an-ar-experience",
                "doc://com.apple.arkit/documentation/ARKit/creating-a-collaborative-session",
                "doc://com.apple.arkit/documentation/ARKit/creating-a-multiuser-ar-experience",
                "doc://com.apple.arkit/documentation/ARKit/ARParticipantAnchor",
                "doc://com.apple.arkit/documentation/ARKit/ARSession/CollaborationData"
              ],
              "title": "Shared Experiences"
            },
            {
              "anchor": "Audio",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/creating-an-immersive-ar-experience-with-audio"
              ],
              "title": "Audio"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "iOS",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/verifying-device-support-and-user-permission",
                "doc://com.apple.arkit/documentation/ARKit/ARSession",
                "doc://com.apple.arkit/documentation/ARKit/ARAnchor"
              ],
              "title": "iOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARParticipantAnchor/title",
          "value": "ARParticipantAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARParticipantAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARParticipantAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARParticipantAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARParticipantAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayView/title",
          "value": "ARCoachingOverlayView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCoachingOverlayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCoachingOverlayView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCoachingOverlayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession/title",
          "value": "ARSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/title",
          "value": "ARQuickLookPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAnchor/title",
          "value": "ARAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNView/title",
          "value": "ARSCNView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSCNView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSCNView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code/title",
          "value": "ARErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1CollaborationData/title",
          "value": "ARCollaborationData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1CollaborationData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCollaborationData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1CollaborationData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCollaborationData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSKView/title",
          "value": "ARSKView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSKView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSKView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSKView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSKView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arkit-in-ios"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arkit-in-ios"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
