{
  "abstract": [
    {
      "text": "Create immersive augmented reality experiences.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ARKit in visionOS"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "ARKit in visionOS offers a new set of sensing capabilities that you adopt individually in your app, using data providers to deliver updates asynchronously. The available capabilities include:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Plane detection.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Detect surfaces in a person’s surroundings and use them to anchor content.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "World tracking.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Determine the position and orientation of Apple Vision Pro relative to its surroundings, and add world anchors to place content.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Hand tracking.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Use a person’s hand and finger positions as input for custom gestures and interactivity.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Scene reconstruction.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Build a mesh of a person’s physical surroundings and incorporate it into your immersive spaces to support interactions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Image tracking.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Look for known images in a person’s surroundings and use them as anchor points for custom content.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Object tracking.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Use 3D reference objects to find and track real-world objects in a person’s environment.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Barcode detection.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Detect and scan QR codes and barcodes in a variety of formats in a person’s surroundings.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Room tracking",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": ". Use room anchors to identify specific rooms and implement per-room experiences.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Light estimation.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Understand the lighting characteristics of a room to help improve the appearance of shiny or semi-reflective materials in your virtual content.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Camera frames.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Access camera frames from a device in several formats.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4330791",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Building-local-experiences-with-room-tracking-PageImage-card.png": {
      "alt": null,
      "identifier": "Building-local-experiences-with-room-tracking-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/af99ba5e2e307907caed07d89553f518/Building-local-experiences-with-room-tracking-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ecb2f88d37f7bba036c739568409febf/Building-local-experiences-with-room-tracking-PageImage-card@2x.png"
        }
      ]
    },
    "Happy-Beam-intro.png": {
      "alt": null,
      "identifier": "Happy-Beam-intro.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/52b497b6d705af322726d7371dee6ddd/Happy-Beam-intro@2x.png"
        }
      ]
    },
    "Object-Tracking-PageImage-card.png": {
      "alt": null,
      "identifier": "Object-Tracking-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2332d74827799a86de0261e14c5a61f5/Object-Tracking-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/dfd3696d1b7df884ded8407cef3e8045/Object-Tracking-PageImage-card@2x.png"
        }
      ]
    },
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARKitSession": {
      "abstract": [
        {
          "text": "The main entry point for receiving data from ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARKitSession"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARKitSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARKitSession"
        }
      ],
      "role": "symbol",
      "title": "ARKitSession",
      "type": "topic",
      "url": "/documentation/arkit/arkitsession"
    },
    "doc://com.apple.arkit/documentation/ARKit/Anchor": {
      "abstract": [
        {
          "text": "The identity, location, and orientation of an object in world space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Anchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/Anchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Anchor"
        }
      ],
      "role": "symbol",
      "title": "Anchor",
      "type": "topic",
      "url": "/documentation/arkit/anchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/BarcodeAnchor": {
      "abstract": [
        {
          "text": "A barcode’s position in a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BarcodeAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/BarcodeAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BarcodeAnchor"
        }
      ],
      "role": "symbol",
      "title": "BarcodeAnchor",
      "type": "topic",
      "url": "/documentation/arkit/barcodeanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/BarcodeDetectionProvider": {
      "abstract": [
        {
          "text": "An object that provides the real-time position of barcodes the framework detects in a person’s environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BarcodeDetectionProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/BarcodeDetectionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BarcodeDetectionProvider"
        }
      ],
      "role": "symbol",
      "title": "BarcodeDetectionProvider",
      "type": "topic",
      "url": "/documentation/arkit/barcodedetectionprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/CameraFrame": {
      "abstract": [
        {
          "text": "The representation of a camera frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CameraFrame"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/CameraFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CameraFrame"
        }
      ],
      "role": "symbol",
      "title": "CameraFrame",
      "type": "topic",
      "url": "/documentation/arkit/cameraframe"
    },
    "doc://com.apple.arkit/documentation/ARKit/CameraFrameProvider": {
      "abstract": [
        {
          "text": "An object that provides camera streams.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CameraFrameProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/CameraFrameProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CameraFrameProvider"
        }
      ],
      "role": "symbol",
      "title": "CameraFrameProvider",
      "type": "topic",
      "url": "/documentation/arkit/cameraframeprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/CameraVideoFormat": {
      "abstract": [
        {
          "text": "A structure that represents a camera video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CameraVideoFormat"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/CameraVideoFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CameraVideoFormat"
        }
      ],
      "role": "symbol",
      "title": "CameraVideoFormat",
      "type": "topic",
      "url": "/documentation/arkit/cameravideoformat"
    },
    "doc://com.apple.arkit/documentation/ARKit/DataProvider": {
      "abstract": [
        {
          "text": "A source of live data from ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/DataProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataProvider"
        }
      ],
      "role": "symbol",
      "title": "DataProvider",
      "type": "topic",
      "url": "/documentation/arkit/dataprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/DataProviderState": {
      "abstract": [
        {
          "text": "The possible states of a data provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataProviderState"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/DataProviderState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataProviderState"
        }
      ],
      "role": "symbol",
      "title": "DataProviderState",
      "type": "topic",
      "url": "/documentation/arkit/dataproviderstate"
    },
    "doc://com.apple.arkit/documentation/ARKit/DeviceAnchor": {
      "abstract": [
        {
          "text": "The position and orientation of Apple Vision Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DeviceAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/DeviceAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DeviceAnchor"
        }
      ],
      "role": "symbol",
      "title": "DeviceAnchor",
      "type": "topic",
      "url": "/documentation/arkit/deviceanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/EnvironmentLightEstimationProvider": {
      "abstract": [
        {
          "text": "A source of live data about lighting information in the environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EnvironmentLightEstimationProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/EnvironmentLightEstimationProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EnvironmentLightEstimationProvider"
        }
      ],
      "role": "symbol",
      "title": "EnvironmentLightEstimationProvider",
      "type": "topic",
      "url": "/documentation/arkit/environmentlightestimationprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/EnvironmentProbeAnchor": {
      "abstract": [
        {
          "text": "An environment probe in the world.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EnvironmentProbeAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/EnvironmentProbeAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EnvironmentProbeAnchor"
        }
      ],
      "role": "symbol",
      "title": "EnvironmentProbeAnchor",
      "type": "topic",
      "url": "/documentation/arkit/environmentprobeanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/GeometryElement": {
      "abstract": [
        {
          "text": "A container for vertex indices of lines or triangles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GeometryElement"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/GeometryElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GeometryElement"
        }
      ],
      "role": "symbol",
      "title": "GeometryElement",
      "type": "topic",
      "url": "/documentation/arkit/geometryelement"
    },
    "doc://com.apple.arkit/documentation/ARKit/GeometrySource": {
      "abstract": [
        {
          "text": "A container for geometrical vector data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GeometrySource"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/GeometrySource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GeometrySource"
        }
      ],
      "role": "symbol",
      "title": "GeometrySource",
      "type": "topic",
      "url": "/documentation/arkit/geometrysource"
    },
    "doc://com.apple.arkit/documentation/ARKit/HandAnchor": {
      "abstract": [
        {
          "text": "A hand’s position in a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HandAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/HandAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HandAnchor"
        }
      ],
      "role": "symbol",
      "title": "HandAnchor",
      "type": "topic",
      "url": "/documentation/arkit/handanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/HandSkeleton": {
      "abstract": [
        {
          "text": "A collection of joints in a hand.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HandSkeleton"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/HandSkeleton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HandSkeleton"
        }
      ],
      "role": "symbol",
      "title": "HandSkeleton",
      "type": "topic",
      "url": "/documentation/arkit/handskeleton"
    },
    "doc://com.apple.arkit/documentation/ARKit/HandTrackingProvider": {
      "abstract": [
        {
          "text": "A source of live data about the position of a person’s hands and hand joints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HandTrackingProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/HandTrackingProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HandTrackingProvider"
        }
      ],
      "role": "symbol",
      "title": "HandTrackingProvider",
      "type": "topic",
      "url": "/documentation/arkit/handtrackingprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/ImageAnchor": {
      "abstract": [
        {
          "text": "A 2D image’s position in a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImageAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ImageAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImageAnchor"
        }
      ],
      "role": "symbol",
      "title": "ImageAnchor",
      "type": "topic",
      "url": "/documentation/arkit/imageanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ImageTrackingProvider": {
      "abstract": [
        {
          "text": "A source of live data about a 2D image’s position in a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImageTrackingProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ImageTrackingProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImageTrackingProvider"
        }
      ],
      "role": "symbol",
      "title": "ImageTrackingProvider",
      "type": "topic",
      "url": "/documentation/arkit/imagetrackingprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/MeshAnchor": {
      "abstract": [
        {
          "text": "A volume of space that contains a mesh of a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MeshAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/MeshAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MeshAnchor"
        }
      ],
      "role": "symbol",
      "title": "MeshAnchor",
      "type": "topic",
      "url": "/documentation/arkit/meshanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ObjectAnchor": {
      "abstract": [
        {
          "text": "A reference object ARKit is tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ObjectAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ObjectAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ObjectAnchor"
        }
      ],
      "role": "symbol",
      "title": "ObjectAnchor",
      "type": "topic",
      "url": "/documentation/arkit/objectanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ObjectTrackingProvider": {
      "abstract": [
        {
          "text": "A source of real-time position of reference objects in a person’s environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ObjectTrackingProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ObjectTrackingProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ObjectTrackingProvider"
        }
      ],
      "role": "symbol",
      "title": "ObjectTrackingProvider",
      "type": "topic",
      "url": "/documentation/arkit/objecttrackingprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/PlaneAnchor": {
      "abstract": [
        {
          "text": "An anchor that represents horizontal and vertical planes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PlaneAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/PlaneAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PlaneAnchor"
        }
      ],
      "role": "symbol",
      "title": "PlaneAnchor",
      "type": "topic",
      "url": "/documentation/arkit/planeanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/PlaneDetectionProvider": {
      "abstract": [
        {
          "text": "A source of live data about planes in a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PlaneDetectionProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/PlaneDetectionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PlaneDetectionProvider"
        }
      ],
      "role": "symbol",
      "title": "PlaneDetectionProvider",
      "type": "topic",
      "url": "/documentation/arkit/planedetectionprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/ReferenceImage": {
      "abstract": [
        {
          "text": "A 2D image the system uses as a reference to find the same image in a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReferenceImage"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ReferenceImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReferenceImage"
        }
      ],
      "role": "symbol",
      "title": "ReferenceImage",
      "type": "topic",
      "url": "/documentation/arkit/referenceimage"
    },
    "doc://com.apple.arkit/documentation/ARKit/RoomAnchor": {
      "abstract": [
        {
          "text": "The representation of a room ARKit is currently tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoomAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/RoomAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomAnchor"
        }
      ],
      "role": "symbol",
      "title": "RoomAnchor",
      "type": "topic",
      "url": "/documentation/arkit/roomanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/RoomTrackingProvider": {
      "abstract": [
        {
          "text": "A source of real-time information about the room that a person is currently in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoomTrackingProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/RoomTrackingProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomTrackingProvider"
        }
      ],
      "role": "symbol",
      "title": "RoomTrackingProvider",
      "type": "topic",
      "url": "/documentation/arkit/roomtrackingprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/SceneReconstructionProvider": {
      "abstract": [
        {
          "text": "A source of live data about the shape of a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneReconstructionProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/SceneReconstructionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneReconstructionProvider"
        }
      ],
      "role": "symbol",
      "title": "SceneReconstructionProvider",
      "type": "topic",
      "url": "/documentation/arkit/scenereconstructionprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/TrackableAnchor": {
      "abstract": [
        {
          "text": "An anchor that can gain and lose its tracking state over the course of a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TrackableAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/TrackableAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TrackableAnchor"
        }
      ],
      "role": "symbol",
      "title": "TrackableAnchor",
      "type": "topic",
      "url": "/documentation/arkit/trackableanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/WorldAnchor": {
      "abstract": [
        {
          "text": "A fixed location in a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WorldAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/WorldAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WorldAnchor"
        }
      ],
      "role": "symbol",
      "title": "WorldAnchor",
      "type": "topic",
      "url": "/documentation/arkit/worldanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/WorldTrackingProvider": {
      "abstract": [
        {
          "text": "A source of live data about the device pose and anchors in a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WorldTrackingProvider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/WorldTrackingProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WorldTrackingProvider"
        }
      ],
      "role": "symbol",
      "title": "WorldTrackingProvider",
      "type": "topic",
      "url": "/documentation/arkit/worldtrackingprovider"
    },
    "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos-c-api": {
      "abstract": [
        {
          "text": "Integrate ARKit with low-level libraries and functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos-c-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ARKit in visionOS C API",
      "type": "topic",
      "url": "/documentation/arkit/arkit-in-visionos-c-api"
    },
    "doc://com.apple.arkit/documentation/ARKit/detecting-images-in-an-ar-experience": {
      "abstract": [
        {
          "text": "React to known 2D images in the user’s environment, and use their positions to place AR content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/detecting-images-in-an-ar-experience",
      "kind": "article",
      "role": "sampleCode",
      "title": "Detecting Images in an AR Experience",
      "type": "topic",
      "url": "/documentation/arkit/detecting-images-in-an-ar-experience"
    },
    "doc://com.apple.arkit/documentation/ARKit/tracking-and-altering-images": {
      "abstract": [
        {
          "text": "Create images from rectangular shapes found in the user’s environment, and augment their appearance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/tracking-and-altering-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Tracking and altering images",
      "type": "topic",
      "url": "/documentation/arkit/tracking-and-altering-images"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/visionOS/building_local_experiences_with_room_tracking": {
      "abstract": [
        {
          "text": "Use room tracking in visionOS to provide custom interactions with physical spaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/building_local_experiences_with_room_tracking",
      "images": [
        {
          "identifier": "Building-local-experiences-with-room-tracking-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "sampleCode",
      "title": "Building local experiences with room tracking",
      "type": "topic",
      "url": "/documentation/visionOS/building_local_experiences_with_room_tracking"
    },
    "doc://com.apple.documentation/documentation/visionOS/exploring_object_tracking_with_arkit": {
      "abstract": [
        {
          "text": "Find and track real-world objects in visionOS using reference objects trained with Create ML.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/exploring_object_tracking_with_arkit",
      "images": [
        {
          "identifier": "Object-Tracking-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "sampleCode",
      "title": "Exploring object tracking with ARKit",
      "type": "topic",
      "url": "/documentation/visionOS/exploring_object_tracking_with_arkit"
    },
    "doc://com.apple.documentation/documentation/visionOS/happybeam": {
      "abstract": [
        {
          "text": "Leverage a Full Space to create a fun game using ARKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/happybeam",
      "images": [
        {
          "identifier": "Happy-Beam-intro.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "sampleCode",
      "title": "Happy Beam",
      "type": "topic",
      "url": "/documentation/visionOS/happybeam"
    },
    "doc://com.apple.documentation/documentation/visionOS/incorporating-real-world-surroundings-in-an-immersive-experience": {
      "abstract": [
        {
          "text": "Create an immersive experience by making your app’s content respond to the local shape of the world.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/incorporating-real-world-surroundings-in-an-immersive-experience",
      "kind": "article",
      "role": "sampleCode",
      "title": "Incorporating real-world surroundings in an immersive experience",
      "type": "topic",
      "url": "/documentation/visionOS/incorporating-real-world-surroundings-in-an-immersive-experience"
    },
    "doc://com.apple.documentation/documentation/visionOS/placing-content-on-detected-planes": {
      "abstract": [
        {
          "text": "Detect horizontal surfaces like tables and floors, as well as vertical planes like walls and doors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/placing-content-on-detected-planes",
      "kind": "article",
      "role": "sampleCode",
      "title": "Placing content on detected planes",
      "type": "topic",
      "url": "/documentation/visionOS/placing-content-on-detected-planes"
    },
    "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data": {
      "abstract": [
        {
          "text": "Check whether your app can use ARKit and respect people’s privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data",
      "kind": "article",
      "role": "article",
      "title": "Setting up access to ARKit data",
      "type": "topic",
      "url": "/documentation/visionOS/setting-up-access-to-arkit-data"
    },
    "doc://com.apple.documentation/documentation/visionOS/tracking-images-in-3d-space": {
      "abstract": [
        {
          "text": "Place content based on the current position of a known image in a person’s surroundings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/tracking-images-in-3d-space",
      "kind": "article",
      "role": "article",
      "title": "Tracking preregistered images in 3D space",
      "type": "topic",
      "url": "/documentation/visionOS/tracking-images-in-3d-space"
    },
    "doc://com.apple.documentation/documentation/visionOS/tracking-points-in-world-space": {
      "abstract": [
        {
          "text": "Retrieve the position and orientation of anchors your app stores in ARKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/tracking-points-in-world-space",
      "kind": "article",
      "role": "sampleCode",
      "title": "Tracking specific points in world space",
      "type": "topic",
      "url": "/documentation/visionOS/tracking-points-in-world-space"
    },
    "media-4330791": {
      "alt": "An illustration showing a split view of someone using Apple Vision Pro; the left side shows a person’s perspective of the room and the right side depicts ARKit’s perspective of the room. The right side illustrates ARKit’s sensing capabilities, including the detected shape of the room and the individual joints of a person’s hand.",
      "identifier": "media-4330791",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1742d9029cfb818bd01ad8d395b7e7d/media-4330791@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "visionOS",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data",
        "doc://com.apple.arkit/documentation/ARKit/ARKitSession",
        "doc://com.apple.arkit/documentation/ARKit/DataProvider",
        "doc://com.apple.arkit/documentation/ARKit/Anchor"
      ],
      "title": "visionOS"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setup",
      "identifiers": [
        "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data",
        "doc://com.apple.arkit/documentation/ARKit/ARKitSession",
        "doc://com.apple.arkit/documentation/ARKit/DataProvider",
        "doc://com.apple.arkit/documentation/ARKit/DataProviderState",
        "doc://com.apple.arkit/documentation/ARKit/Anchor",
        "doc://com.apple.arkit/documentation/ARKit/TrackableAnchor"
      ],
      "title": "Setup"
    },
    {
      "anchor": "Barcode-detection",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/BarcodeDetectionProvider",
        "doc://com.apple.arkit/documentation/ARKit/BarcodeAnchor"
      ],
      "title": "Barcode detection"
    },
    {
      "anchor": "Camera-sampling",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/CameraFrameProvider",
        "doc://com.apple.arkit/documentation/ARKit/CameraFrame",
        "doc://com.apple.arkit/documentation/ARKit/CameraVideoFormat"
      ],
      "title": "Camera sampling"
    },
    {
      "anchor": "Plane-detection",
      "identifiers": [
        "doc://com.apple.documentation/documentation/visionOS/placing-content-on-detected-planes",
        "doc://com.apple.arkit/documentation/ARKit/PlaneDetectionProvider",
        "doc://com.apple.arkit/documentation/ARKit/PlaneAnchor"
      ],
      "title": "Plane detection"
    },
    {
      "anchor": "World-tracking",
      "identifiers": [
        "doc://com.apple.documentation/documentation/visionOS/tracking-points-in-world-space",
        "doc://com.apple.arkit/documentation/ARKit/WorldTrackingProvider",
        "doc://com.apple.arkit/documentation/ARKit/WorldAnchor",
        "doc://com.apple.arkit/documentation/ARKit/DeviceAnchor"
      ],
      "title": "World tracking"
    },
    {
      "anchor": "Hand-tracking",
      "identifiers": [
        "doc://com.apple.documentation/documentation/visionOS/happybeam",
        "doc://com.apple.arkit/documentation/ARKit/HandTrackingProvider",
        "doc://com.apple.arkit/documentation/ARKit/HandAnchor",
        "doc://com.apple.arkit/documentation/ARKit/HandSkeleton"
      ],
      "title": "Hand tracking"
    },
    {
      "anchor": "Scene-reconstruction",
      "identifiers": [
        "doc://com.apple.documentation/documentation/visionOS/incorporating-real-world-surroundings-in-an-immersive-experience",
        "doc://com.apple.arkit/documentation/ARKit/SceneReconstructionProvider",
        "doc://com.apple.arkit/documentation/ARKit/MeshAnchor"
      ],
      "title": "Scene reconstruction"
    },
    {
      "anchor": "Image-tracking",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/tracking-and-altering-images",
        "doc://com.apple.arkit/documentation/ARKit/detecting-images-in-an-ar-experience",
        "doc://com.apple.documentation/documentation/visionOS/tracking-images-in-3d-space",
        "doc://com.apple.arkit/documentation/ARKit/ImageTrackingProvider",
        "doc://com.apple.arkit/documentation/ARKit/ImageAnchor",
        "doc://com.apple.arkit/documentation/ARKit/ReferenceImage"
      ],
      "title": "Image tracking"
    },
    {
      "anchor": "Geometry",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/GeometryElement",
        "doc://com.apple.arkit/documentation/ARKit/GeometrySource"
      ],
      "title": "Geometry"
    },
    {
      "anchor": "Lighting-estimation",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/EnvironmentLightEstimationProvider",
        "doc://com.apple.arkit/documentation/ARKit/EnvironmentProbeAnchor"
      ],
      "title": "Lighting estimation"
    },
    {
      "anchor": "Object-tracking",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ObjectTrackingProvider",
        "doc://com.apple.arkit/documentation/ARKit/ObjectAnchor",
        "doc://com.apple.documentation/documentation/visionOS/exploring_object_tracking_with_arkit"
      ],
      "title": "Object tracking"
    },
    {
      "anchor": "Room-tracking",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/RoomTrackingProvider",
        "doc://com.apple.arkit/documentation/ARKit/RoomAnchor",
        "doc://com.apple.documentation/documentation/visionOS/building_local_experiences_with_room_tracking"
      ],
      "title": "Room tracking"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setup",
              "identifiers": [
                "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data"
              ],
              "title": "Setup"
            },
            {
              "anchor": "Plane-detection",
              "identifiers": [
                "doc://com.apple.documentation/documentation/visionOS/placing-content-on-detected-planes"
              ],
              "title": "Plane detection"
            },
            {
              "anchor": "World-tracking",
              "identifiers": [
                "doc://com.apple.documentation/documentation/visionOS/tracking-points-in-world-space"
              ],
              "title": "World tracking"
            },
            {
              "anchor": "Hand-tracking",
              "identifiers": [
                "doc://com.apple.documentation/documentation/visionOS/happybeam"
              ],
              "title": "Hand tracking"
            },
            {
              "anchor": "Scene-reconstruction",
              "identifiers": [
                "doc://com.apple.documentation/documentation/visionOS/incorporating-real-world-surroundings-in-an-immersive-experience"
              ],
              "title": "Scene reconstruction"
            },
            {
              "anchor": "Image-tracking",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/tracking-and-altering-images",
                "doc://com.apple.arkit/documentation/ARKit/detecting-images-in-an-ar-experience",
                "doc://com.apple.documentation/documentation/visionOS/tracking-images-in-3d-space"
              ],
              "title": "Image tracking"
            },
            {
              "anchor": "Object-tracking",
              "identifiers": [
                "doc://com.apple.documentation/documentation/visionOS/exploring_object_tracking_with_arkit"
              ],
              "title": "Object tracking"
            },
            {
              "anchor": "Room-tracking",
              "identifiers": [
                "doc://com.apple.documentation/documentation/visionOS/building_local_experiences_with_room_tracking"
              ],
              "title": "Room tracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "visionOS",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/arkit-in-visionos-c-api"
              ],
              "title": "visionOS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arkit-in-visionos"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arkit-in-visionos"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
