{
  "abstract": [
    {
      "text": "An object for customizing the AR Quick Look experience.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARQuickLookPreviewItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ARQuickLookPreviewItem"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARQuickLookPreviewItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ARQuickLookPreviewItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this class when you want to control the background, designate which content the share sheet shares, or disable scaling in case it’s not appropriate to allow the user to scale a particular model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem": {
      "abstract": [
        {
          "text": "An object for customizing the AR Quick Look experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARQuickLookPreviewItem"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARQuickLookPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "ARQuickLookPreviewItem",
      "type": "topic",
      "url": "/documentation/arkit/arquicklookpreviewitem"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/allowsContentScaling": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the user can scale your virtual content using pinch gestures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsContentScaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/allowsContentScaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsContentScaling"
        }
      ],
      "role": "symbol",
      "title": "allowsContentScaling",
      "type": "topic",
      "url": "/documentation/arkit/arquicklookpreviewitem/allowscontentscaling"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/canonicalWebPageURL": {
      "abstract": [
        {
          "text": "The web URL to share when the user invokes the share sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canonicalWebPageURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/canonicalWebPageURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canonicalWebPageURL"
        }
      ],
      "role": "symbol",
      "title": "canonicalWebPageURL",
      "type": "topic",
      "url": "/documentation/arkit/arquicklookpreviewitem/canonicalwebpageurl"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/init(fileAt:)": {
      "abstract": [
        {
          "text": "Initializes a new AR Quick Look preview item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fileAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/init(fileAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFileAtURL:"
        }
      ],
      "role": "symbol",
      "title": "init(fileAt:)",
      "type": "topic",
      "url": "/documentation/arkit/arquicklookpreviewitem/init(fileat:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look": {
      "abstract": [
        {
          "text": "Provide a banner that users can tap to make a purchase or perform a custom action in an AR experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Adding an Apple Pay Button or a Custom Action in AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look"
    },
    "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit": {
      "abstract": [
        {
          "text": "Balance the appearance and performance of your AR experiences with modeling strategies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit",
      "kind": "article",
      "role": "article",
      "title": "Adding Visual Effects in AR Quick Look and RealityKit",
      "type": "topic",
      "url": "/documentation/arkit/adding-visual-effects-in-ar-quick-look-and-realitykit"
    },
    "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look": {
      "abstract": [
        {
          "text": "Display a model or scene that the user can move, scale, and share with others.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Previewing a Model with AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/previewing-a-model-with-ar-quick-look"
    },
    "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look": {
      "abstract": [
        {
          "text": "Add metadata to your USDZ file to specify its lighting characteristics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look",
      "kind": "article",
      "role": "article",
      "title": "Specifying a lighting environment in AR Quick Look",
      "type": "topic",
      "url": "/documentation/arkit/specifying-a-lighting-environment-in-ar-quick-look"
    },
    "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar": {
      "abstract": [
        {
          "text": "Add augmented reality functionality to your 3D content using USDZ schemas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar",
      "kind": "article",
      "role": "article",
      "title": "USDZ schemas for AR",
      "type": "topic",
      "url": "/documentation/RealityKit/usdz-schemas-for-ar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)QLPreviewItem": {
      "abstract": [
        {
          "text": "A protocol that defines a set of properties you implement to make a preview of your application’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)QLPreviewItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "QLPreviewItem",
      "type": "topic",
      "url": "/documentation/QuickLookUI/QLPreviewItem"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)QLPreviewItem"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "AR-Quick-Look",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
        "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit",
        "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look",
        "doc://com.apple.documentation/documentation/RealityKit/usdz-schemas-for-ar",
        "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look"
      ],
      "title": "AR Quick Look"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Preview-Item",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/init(fileAt:)"
      ],
      "title": "Creating a Preview Item"
    },
    {
      "anchor": "Scaling-Content",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/allowsContentScaling"
      ],
      "title": "Scaling Content"
    },
    {
      "anchor": "Interacting-with-Content",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/canonicalWebPageURL"
      ],
      "title": "Interacting with Content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARQuickLookPreviewItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Preview-Item",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/init(fileAt:)"
              ],
              "title": "Creating a Preview Item"
            },
            {
              "anchor": "Scaling-Content",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/allowsContentScaling"
              ],
              "title": "Scaling Content"
            },
            {
              "anchor": "Interacting-with-Content",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARQuickLookPreviewItem/canonicalWebPageURL"
              ],
              "title": "Interacting with Content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)QLPreviewItem"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "AR-Quick-Look",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/previewing-a-model-with-ar-quick-look",
                "doc://com.apple.arkit/documentation/ARKit/adding-visual-effects-in-ar-quick-look-and-realitykit",
                "doc://com.apple.arkit/documentation/ARKit/adding-an-apple-pay-button-or-a-custom-action-in-ar-quick-look",
                "doc://com.apple.arkit/documentation/ARKit/specifying-a-lighting-environment-in-ar-quick-look"
              ],
              "title": "AR Quick Look"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARQuickLookPreviewItem"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/title",
          "value": "ARQuickLookPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARQuickLookPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)QLPreviewItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem~1canonicalWebPageURL/title",
          "value": "canonicalWebPageURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem~1canonicalWebPageURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canonicalWebPageURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem~1init(fileAt:)/title",
          "value": "initWithFileAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem~1init(fileAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFileAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem~1allowsContentScaling/title",
          "value": "allowsContentScaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARQuickLookPreviewItem~1allowsContentScaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsContentScaling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arquicklookpreviewitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arquicklookpreviewitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
