{
  "abstract": [
    {
      "text": "Options for drawing overlay content to aid debugging of AR tracking in a SceneKit view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARSCNDebugOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ARSCNDebugOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ARSCNDebugOptions"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARSCNDebugOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "ARSCNDebugOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARSCNDebugOptions"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@SCNDebugOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SCNDebugOptions",
              "text": "SCNDebugOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To use these debugging overlays, add them to the option set in the view’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/scenekit/scnscenerenderer/1523281-debugoptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property (inherited from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SceneKit/SCNView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSCNDebugOptionShowFeaturePoints": {
      "abstract": [
        {
          "text": "Display a point cloud showing intermediate results of the scene analysis that ARKit uses to track device position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARSCNDebugOptionShowFeaturePoints"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSCNDebugOptionShowFeaturePoints",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARSCNDebugOptionShowFeaturePoints",
      "type": "topic",
      "url": "/documentation/arkit/arscndebugoptionshowfeaturepoints"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSCNDebugOptionShowWorldOrigin": {
      "abstract": [
        {
          "text": "Display a coordinate axis visualization indicating the position and orientation of the AR world coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARSCNDebugOptionShowWorldOrigin"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSCNDebugOptionShowWorldOrigin",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARSCNDebugOptionShowWorldOrigin",
      "type": "topic",
      "url": "/documentation/arkit/arscndebugoptionshowworldorigin"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSCNDebugOptions": {
      "abstract": [
        {
          "text": "Options for drawing overlay content to aid debugging of AR tracking in a SceneKit view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSCNDebugOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSCNDebugOptions"
        }
      ],
      "role": "symbol",
      "title": "ARSCNDebugOptions",
      "type": "topic",
      "url": "/documentation/arkit/arscndebugoptions"
    },
    "doc://com.apple.documentation/documentation/SceneKit/SCNView": {
      "abstract": [
        {
          "text": "A view for displaying 3D SceneKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SceneKit/SCNView",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNView",
      "type": "topic",
      "url": "/documentation/SceneKit/SCNView"
    },
    "doc://com.apple.documentation/documentation/scenekit/scnscenerenderer/1523281-debugoptions": {
      "abstract": [
        {
          "text": "Options for drawing overlay content in a scene that can aid debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "debugOptions"
        },
        {
          "kind": "text",
          "text": ": SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/scenekit/scnscenerenderer/1523281-debugoptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "debugOptions",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/1523281-debugoptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@SCNDebugOptions": {
      "abstract": [
        {
          "text": "Options for drawing overlays with SceneKit content that can aid in debugging, used with the [`debugOptions`](doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/debugOptions) property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@SCNDebugOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNDebugOptions",
      "type": "topic",
      "url": "/documentation/SceneKit/SCNDebugOptions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARSCNDebugOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSCNDebugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSCNDebugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "AR-Debugging-Overlays",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARSCNDebugOptionShowWorldOrigin",
                "doc://com.apple.arkit/documentation/ARKit/ARSCNDebugOptionShowFeaturePoints"
              ],
              "title": "AR Debugging Overlays"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@SCNDebugOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@SCNDebugOptions",
                    "text": "SCNDebugOptions"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARSCNDebugOptions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SceneKit~1SCNView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSView",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@SCNDebugOptions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNDebugOptions"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNDebugOptions/title",
          "value": "ARSCNDebugOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNDebugOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSCNDebugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNDebugOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSCNDebugOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arscndebugoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arscndebugoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
