{
  "abstract": [
    {
      "text": "An object that describes the locations of a body’s joints in the camera feed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARSkeleton2D",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ARSkeleton2D"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARSkeleton2D"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ARSkeleton2D"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARSkeleton2D"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides you with a 2D body’s joints in a flat hierarchy so you can access them efficiently. The joint locations are normalized within the range [0..1] in the coordinate space of the current frame’s camera image, where 0 is the upper left, and 1 is the bottom right.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To access a skeleton’s joints by name, you use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/landmarkForJointNamed:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To access a named joint by index (for example, for performance reasons), you query the definition for the named joint index using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/index(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", then access ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/jointLandmarks-12vkw",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " using the resulting index.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARBody2D": {
      "abstract": [
        {
          "text": "The screen-space representation of a person ARKit recognizes in the camera feed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARBody2D"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARBody2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARBody2D"
        }
      ],
      "role": "symbol",
      "title": "ARBody2D",
      "type": "topic",
      "url": "/documentation/arkit/arbody2d"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton": {
      "abstract": [
        {
          "text": "The interface for the skeleton of a tracked body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSkeleton"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeleton"
        }
      ],
      "role": "symbol",
      "title": "ARSkeleton",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D": {
      "abstract": [
        {
          "text": "An object that describes the locations of a body’s joints in the camera feed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSkeleton2D"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeleton2D"
        }
      ],
      "role": "symbol",
      "title": "ARSkeleton2D",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton2d"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/jointLandmarks-12vkw": {
      "abstract": [
        {
          "text": "The joint landmarks in normalized coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jointLandmarks"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/jointLandmarks-12vkw",
      "kind": "symbol",
      "role": "symbol",
      "title": "jointLandmarks",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton2d/jointlandmarks-12vkw"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/jointLandmarks-3en0x": {
      "abstract": [
        {
          "text": "The joint landmarks in normalized coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "jointLandmarks"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/jointLandmarks-3en0x",
      "kind": "symbol",
      "role": "symbol",
      "title": "jointLandmarks",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton2d/jointlandmarks-3en0x"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/landmark(for:)": {
      "abstract": [
        {
          "text": "Returns the location of a joint with a given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landmark"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/landmark(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "landmark(for:)",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton2d/landmark(for:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/landmarkForJointNamed:": {
      "abstract": [
        {
          "text": "Returns the location of a joint with a given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "landmarkForJointNamed:"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/landmarkForJointNamed:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "landmarkForJointNamed:"
        }
      ],
      "role": "symbol",
      "title": "landmarkForJointNamed:",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton2d/landmarkforjointnamed:"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeleton3D": {
      "abstract": [
        {
          "text": "The skeleton of a human body that ARKit tracks in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSkeleton3D"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeleton3D"
        }
      ],
      "role": "symbol",
      "title": "ARSkeleton3D",
      "type": "topic",
      "url": "/documentation/arkit/arskeleton3d"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition": {
      "abstract": [
        {
          "text": "The hierarchy of joints and their names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSkeletonDefinition"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonDefinition"
        }
      ],
      "role": "symbol",
      "title": "ARSkeletonDefinition",
      "type": "topic",
      "url": "/documentation/arkit/arskeletondefinition"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/index(for:)": {
      "abstract": [
        {
          "text": "Returns the index for a given joint identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSkeleton",
          "text": "ARSkeleton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ARSkeletonJointName",
          "text": "JointName"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/index(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "index(for:)",
      "type": "topic",
      "url": "/documentation/arkit/arskeletondefinition/index(for:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/capturing-body-motion-in-3d": {
      "abstract": [
        {
          "text": "Track a person in the physical environment and visualize their motion by applying the same body movements to a virtual character.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/capturing-body-motion-in-3d",
      "kind": "article",
      "role": "sampleCode",
      "title": "Capturing Body Motion in 3D",
      "type": "topic",
      "url": "/documentation/arkit/capturing-body-motion-in-3d"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Body-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/capturing-body-motion-in-3d",
        "doc://com.apple.arkit/documentation/ARKit/ARBody2D",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton3D",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition"
      ],
      "title": "Body Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Joint-Landmarks",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/jointLandmarks-12vkw",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/landmark(for:)"
      ],
      "title": "Getting Joint Landmarks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARSkeleton2D"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Joint-Landmarks",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/jointLandmarks-3en0x",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton2D/landmarkForJointNamed:"
              ],
              "title": "Getting Joint Landmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Body-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/capturing-body-motion-in-3d",
                "doc://com.apple.arkit/documentation/ARKit/ARBody2D",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton3D",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeleton",
                "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition"
              ],
              "title": "Body Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARSkeleton2D"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeleton",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ARSkeleton",
                    "text": "ARSkeleton"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeletonDefinition/title",
          "value": "ARSkeletonDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeletonDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeletonDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/title",
          "value": "ARSkeleton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARBody2D/title",
          "value": "ARBody2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARBody2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBody2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARBody2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARBody2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton3D/title",
          "value": "ARSkeleton3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton3D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton2D/title",
          "value": "ARSkeleton2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeleton2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeleton2D"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arskeleton2d"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arskeleton2d"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
