{
  "abstract": [
    {
      "text": "Occlude your app’s virtual content where ARKit recognizes people in the camera feed by using matte generator.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios",
        "doc://com.apple.arkit/documentation/ARKit/camera-lighting-and-effects"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/effecting-people-occlusion-in-custom-renderers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Effecting People Occlusion in Custom Renderers"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC 2019 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc19/607/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "To run the app, use an iOS device with A12 chip or later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "4695583f8ba3/EffectingPeopleOcclusionInCustomRenderers.zip": {
      "checksum": "4695583f8ba3a68ef5020f1c4a0c5e4bbfe370eaf17558826bd205a13dac454cc4e3d64e0ad6860553b8bf997b5feca78d582837d4e3306976d7669c552489fb",
      "identifier": "4695583f8ba3/EffectingPeopleOcclusionInCustomRenderers.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/4695583f8ba3/EffectingPeopleOcclusionInCustomRenderers.zip"
    },
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARMatteGenerator": {
      "abstract": [
        {
          "text": "An object that creates matte textures you use to occlude your app’s virtual content with people, that ARKit recognizes in the camera feed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARMatteGenerator"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARMatteGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARMatteGenerator"
        }
      ],
      "role": "symbol",
      "title": "ARMatteGenerator",
      "type": "topic",
      "url": "/documentation/arkit/armattegenerator"
    },
    "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios": {
      "abstract": [
        {
          "text": "Integrate iOS device camera and motion features to produce augmented reality experiences in your app or game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/arkit-in-ios",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ARKit in iOS",
      "type": "topic",
      "url": "/documentation/arkit/arkit-in-ios"
    },
    "doc://com.apple.arkit/documentation/ARKit/camera-lighting-and-effects": {
      "abstract": [
        {
          "text": "Determine the camera position and lighting for the current session, and apply effects, such as occlusion, to elements of the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/camera-lighting-and-effects",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Camera, Lighting, and Effects",
      "type": "topic",
      "url": "/documentation/arkit/camera-lighting-and-effects"
    },
    "doc://com.apple.arkit/documentation/ARKit/occluding-virtual-content-with-people": {
      "abstract": [
        {
          "text": "Cover your app’s virtual content with people that ARKit perceives in the camera feed.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/occluding-virtual-content-with-people",
      "kind": "article",
      "role": "sampleCode",
      "title": "Occluding virtual content with people",
      "type": "topic",
      "url": "/documentation/arkit/occluding-virtual-content-with-people"
    },
    "doc://com.apple.arkit/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene": {
      "abstract": [
        {
          "text": "Estimate the shape of the physical environment using a polygonal mesh.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene",
      "kind": "article",
      "role": "sampleCode",
      "title": "Visualizing and interacting with a reconstructed scene",
      "type": "topic",
      "url": "/documentation/arkit/visualizing-and-interacting-with-a-reconstructed-scene"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/videos/play/wwdc19/607/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc19/607/",
      "title": "607: Bringing People into AR",
      "titleInlineContent": [
        {
          "text": "607: Bringing People into AR",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc19/607/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "4695583f8ba3/EffectingPeopleOcclusionInCustomRenderers.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Occlusion",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/occluding-virtual-content-with-people",
        "doc://com.apple.arkit/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene",
        "doc://com.apple.arkit/documentation/ARKit/ARMatteGenerator"
      ],
      "title": "Occlusion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Occlusion",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/occluding-virtual-content-with-people",
                "doc://com.apple.arkit/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene",
                "doc://com.apple.arkit/documentation/ARKit/ARMatteGenerator"
              ],
              "title": "Occlusion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMatteGenerator/title",
          "value": "ARMatteGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMatteGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMatteGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARMatteGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARMatteGenerator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/effecting-people-occlusion-in-custom-renderers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/effecting-people-occlusion-in-custom-renderers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
