{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/OS_ar_camera_video_formats"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)OS_ar_camera_video_formats",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OS_ar_camera_video_formats"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OS_ar_camera_video_formats"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "OS_ar_camera_video_formats"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OS_ar_camera_video_formats"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_anchor": {
      "abstract": [
        {
          "text": "The identity, location, and orientation of an object in world space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_anchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_anchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_anchor"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_anchor",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_anchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_authorization_result": {
      "abstract": [
        {
          "text": "An authorization result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_authorization_result"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_authorization_result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_authorization_result"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_authorization_result",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_authorization_result"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_authorization_results": {
      "abstract": [
        {
          "text": "A collection of authorization results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_authorization_results"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_authorization_results",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_authorization_results"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_authorization_results",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_authorization_results"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_camera_video_formats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_camera_video_formats"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_camera_video_formats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_camera_video_formats"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_camera_video_formats",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_camera_video_formats"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_data_provider": {
      "abstract": [
        {
          "text": "A source of live data from ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_data_provider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_data_provider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_data_provider"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_data_provider",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_data_provider"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_data_providers": {
      "abstract": [
        {
          "text": "A source of live data from ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_data_providers"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_data_providers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_data_providers"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_data_providers",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_data_providers"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_device_anchor": {
      "abstract": [
        {
          "text": "The position and orientation of Apple Vision Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_device_anchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_device_anchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_device_anchor"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_device_anchor",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_device_anchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_error": {
      "abstract": [
        {
          "text": "An error reported by ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_error"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_error"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_error",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_error"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_geometry_element": {
      "abstract": [
        {
          "text": "A container for vertex indices of lines or triangles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_geometry_element"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_geometry_element",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_geometry_element"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_geometry_element",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_geometry_element"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_geometry_source": {
      "abstract": [
        {
          "text": "A container for geometrical vector data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_geometry_source"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_geometry_source",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_geometry_source"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_geometry_source",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_geometry_source"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_anchor": {
      "abstract": [
        {
          "text": "A hand’s position in a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_hand_anchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_anchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_hand_anchor"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_hand_anchor",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_hand_anchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_skeleton": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_hand_skeleton"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_skeleton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_hand_skeleton"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_hand_skeleton",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_hand_skeleton"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_tracking_configuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_hand_tracking_configuration"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_tracking_configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_hand_tracking_configuration"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_hand_tracking_configuration",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_hand_tracking_configuration"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_tracking_provider": {
      "abstract": [
        {
          "text": "A source of live data about the position of a person’s hands and hand joints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_hand_tracking_provider"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_tracking_provider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_hand_tracking_provider"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_hand_tracking_provider",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_hand_tracking_provider"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_image_tracking_configuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_image_tracking_configuration"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_image_tracking_configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_image_tracking_configuration"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_image_tracking_configuration",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_image_tracking_configuration"
    },
    "doc://com.apple.arkit/documentation/ARKit/OS_ar_trackable_anchor": {
      "abstract": [
        {
          "text": "An anchor that can gain and lose its tracking state over the course of a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ar_trackable_anchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/OS_ar_trackable_anchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ar_trackable_anchor"
        }
      ],
      "role": "symbol",
      "title": "OS_ar_trackable_anchor",
      "type": "topic",
      "url": "/documentation/arkit/os_ar_trackable_anchor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Objective-C-compatibility-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_anchor",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_trackable_anchor",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_authorization_result",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_authorization_results",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_data_provider",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_device_anchor",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_error",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_data_providers",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_geometry_element",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_geometry_source",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_anchor",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_skeleton",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_tracking_provider",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_tracking_configuration",
        "doc://com.apple.arkit/documentation/ARKit/OS_ar_image_tracking_configuration"
      ],
      "title": "Objective-C compatibility types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OS_ar_camera_video_formats"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_camera_video_formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_camera_video_formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Objective-C-compatibility-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_anchor",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_trackable_anchor",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_authorization_result",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_authorization_results",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_data_provider",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_device_anchor",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_error",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_data_providers",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_geometry_element",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_geometry_source",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_anchor",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_skeleton",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_tracking_provider",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_hand_tracking_configuration",
                "doc://com.apple.arkit/documentation/ARKit/OS_ar_image_tracking_configuration"
              ],
              "title": "Objective-C compatibility types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OS_ar_camera_video_formats"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_trackable_anchor/title",
          "value": "OS_ar_trackable_anchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_trackable_anchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_trackable_anchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_trackable_anchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_trackable_anchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_data_providers/title",
          "value": "OS_ar_data_providers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_data_providers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_data_providers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_data_providers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_data_providers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_tracking_provider/title",
          "value": "OS_ar_hand_tracking_provider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_tracking_provider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_hand_tracking_provider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_tracking_provider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_hand_tracking_provider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_image_tracking_configuration/title",
          "value": "OS_ar_image_tracking_configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_image_tracking_configuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_image_tracking_configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_image_tracking_configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_image_tracking_configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_geometry_element/title",
          "value": "OS_ar_geometry_element"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_geometry_element/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_geometry_element"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_geometry_element/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_geometry_element"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_anchor/title",
          "value": "OS_ar_hand_anchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_anchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_hand_anchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_anchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_hand_anchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_camera_video_formats/title",
          "value": "OS_ar_camera_video_formats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_camera_video_formats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_camera_video_formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_camera_video_formats/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_camera_video_formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_geometry_source/title",
          "value": "OS_ar_geometry_source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_geometry_source/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_geometry_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_geometry_source/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_geometry_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_device_anchor/title",
          "value": "OS_ar_device_anchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_device_anchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_device_anchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_device_anchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_device_anchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_skeleton/title",
          "value": "OS_ar_hand_skeleton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_skeleton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_hand_skeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_skeleton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_hand_skeleton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_error/title",
          "value": "OS_ar_error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_error/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_authorization_results/title",
          "value": "OS_ar_authorization_results"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_authorization_results/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_authorization_results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_authorization_results/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_authorization_results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_tracking_configuration/title",
          "value": "OS_ar_hand_tracking_configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_tracking_configuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_hand_tracking_configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_hand_tracking_configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_hand_tracking_configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_authorization_result/title",
          "value": "OS_ar_authorization_result"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_authorization_result/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_authorization_result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_authorization_result/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_authorization_result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_anchor/title",
          "value": "OS_ar_anchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_anchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_anchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_anchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_anchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_data_provider/title",
          "value": "OS_ar_data_provider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_data_provider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_data_provider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1OS_ar_data_provider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ar_data_provider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/os_ar_camera_video_formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/os_ar_camera_video_formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
