{
  "abstract": [
    {
      "text": "Request permission to display alerts, play sounds, or badge the app’s icon in response to a notification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/asking-permission-to-use-notifications"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Asking permission to use notifications"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Local and remote notifications get a person’s attention by displaying an alert, playing sounds, or badging your app’s icon. These interactions occur when your app isn’t running or is in the background. They let people know that your app has relevant information for them to view. Because a person might consider notification-based interactions disruptive, you must obtain permission to use them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3559454",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Explicitly-request-authorization-in-context",
          "level": 3,
          "text": "Explicitly request authorization in context",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To ask for authorization, get the shared ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance and call its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Specify all of the interaction types that your app employs. For example, you can request authorization to display alerts, add a badge to the app icon, or play sounds:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let center = UNUserNotificationCenter.current()",
            "",
            "do {",
            "    try await center.requestAuthorization(options: [.alert, .sound, .badge])",
            "} catch {",
            "    // Handle the error here.",
            "}",
            "    ",
            "// Enable or disable features based on the authorization."
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The first time your app makes this authorization request, the system prompts the person to grant or deny the request and records that response. Subsequent authorization requests don’t prompt the person.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Make the request in a context that helps people understand why your app needs authorization. In a task-tracking app that sends reminder notifications, you might make the request after the person schedules a first task. Sending the request in context provides a better experience than automatically requesting authorization on first launch, because people can see the purpose your apps notifications serve.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Use-provisional-authorization-to-send-trial-notifications",
          "level": 3,
          "text": "Use provisional authorization to send trial notifications",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you explicitly ask for permission to send notifications, people must decide whether to allow or deny permission before they’ve seen a notification from your app. Even if you carefully set the context before requesting authorization, people may not have enough information to make a decision, and might reject the authorization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use provisional authorization to send notifications on a trial basis. People can then evaluate the notifications and decide whether to authorize them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system delivers provisional notifications quietly — they don’t interrupt the person with a sound or banner, or appear on the lock screen. Instead, they only appear in the notification center’s history. These notifications also include buttons that prompt the person to keep or turn off the notification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3544497",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If a person presses the Keep button, the system prompts them to choose between two options: Deliver Immediately or Deliver in Scheduled Summary. Deliver Immediately delivers future notifications quietly. The system authorizes your app to send notifications, but it doesn’t give your app permission to show alerts, play sounds, or badge the app icon. Your notification only appears in the notification center history unless they change their notification settings. Deliver in Scheduled Summary only appears if the person has Scheduled Summary toggled On in Settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the person presses the Turn Off button, the system confirms the selection before denying your app authorization to send additional notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To request provisional authorization, add the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/provisional",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " option when requesting permission to send notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let center = UNUserNotificationCenter.current()",
            "",
            "do {",
            "    try await center.requestAuthorization(options: [.alert, .sound, .badge, .provisional])",
            "} catch {",
            "    // Handle errors that may occur during requestAuthorization.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Unlike explicitly requesting authorization, this code doesn’t prompt the person for permission to receive notifications. Instead, the first time you call this method, it automatically grants authorization. However, until the person either explicitly keeps or turns off the notification, the authorization status is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationStatus/provisional",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Because people can change the authorization status at any point, check the status before scheduling local notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Additionally, if you request provisional authorization, you can request authorization when your app first launches. The person is only asked to keep or turn off notifications when they actually receive the notification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Customize-notifications-based-on-the-current-authorizations",
          "level": 3,
          "text": "Customize notifications based on the current authorizations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Always check your app’s authorization status before scheduling local notifications. People can change your app’s authorization settings at any time. They can also change the type of interactions allowed by your app — which may cause you to alter the number or type of notifications your app sends.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To provide the best experience for people, call the notification center’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenter/getNotificationSettings(completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to get the current notification settings. Then customize the notification based on these settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let center = UNUserNotificationCenter.current()",
            "",
            "// Obtain the notification settings.",
            "let settings = await center.notificationSettings()",
            "",
            "// Verify the authorization status.",
            "guard (settings.authorizationStatus == .authorized) ||",
            "      (settings.authorizationStatus == .provisional) else { return }",
            "",
            "if settings.alertSetting == .enabled {",
            "    // Schedule an alert-only notification.",
            "} else {",
            "    // Schedule a notification with a badge and sound.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The above example uses a guard condition to prevent the scheduling of notifications if the app isn’t authorized. The code then configures the notification based on the types of interactions allowed, preferring the use of an alert-based notification whenever possible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You might want to configure your notification with alert, sound, and badge information even if your app isn’t authorized for some of the interactions. The system still displays alerts in Notification Center if your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/notificationCenterSetting",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSetting/enabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Your notification center delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenterDelegate/userNotificationCenter(_:willPresent:withCompletionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method also receives notifications when your app is in the foreground, and can still access the alert, sound, or badge information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/Updates/UserNotifications": {
      "abstract": [
        {
          "text": "Learn about important changes in User Notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/UserNotifications",
      "kind": "article",
      "role": "article",
      "title": "User Notifications updates",
      "type": "topic",
      "url": "/documentation/Updates/UserNotifications"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/provisional": {
      "abstract": [
        {
          "text": "The ability to post noninterrupting notifications provisionally to the Notification Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provisional"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAuthorizationOptions",
          "text": "UNAuthorizationOptions"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationOptions/provisional",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAuthorizationOptionProvisional"
        }
      ],
      "role": "symbol",
      "title": "provisional",
      "type": "topic",
      "url": "/documentation/usernotifications/unauthorizationoptions/provisional"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationStatus/provisional": {
      "abstract": [
        {
          "text": "The application is provisionally authorized to post noninterruptive user notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provisional"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNAuthorizationStatus/provisional",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNAuthorizationStatusProvisional"
        }
      ],
      "role": "symbol",
      "title": "UNAuthorizationStatus.provisional",
      "type": "topic",
      "url": "/documentation/usernotifications/unauthorizationstatus/provisional"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSetting/enabled": {
      "abstract": [
        {
          "text": "The setting is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSetting/enabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationSettingEnabled"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationSetting.enabled",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsetting/enabled"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings": {
      "abstract": [
        {
          "text": "The object for managing notification-related settings and the authorization status of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationSettings"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationSettings"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationSettings",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsettings"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/notificationCenterSetting": {
      "abstract": [
        {
          "text": "The setting that indicates whether your app’s notifications appear in Notification Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationCenterSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNNotificationSetting",
          "text": "UNNotificationSetting"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSettings/notificationCenterSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationCenterSetting"
        }
      ],
      "role": "symbol",
      "title": "notificationCenterSetting",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsettings/notificationcentersetting"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenter": {
      "abstract": [
        {
          "text": "The central object for managing notification-related activities for your app or app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNUserNotificationCenter"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNUserNotificationCenter"
        }
      ],
      "role": "symbol",
      "title": "UNUserNotificationCenter",
      "type": "topic",
      "url": "/documentation/usernotifications/unusernotificationcenter"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenter/getNotificationSettings(completionHandler:)": {
      "abstract": [
        {
          "text": "Retrieves the authorization and feature-related settings for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getNotificationSettings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UNNotificationSettings",
          "text": "UNNotificationSettings"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenter/getNotificationSettings(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getNotificationSettingsWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getNotificationSettings(completionHandler:)",
      "type": "topic",
      "url": "/documentation/usernotifications/unusernotificationcenter/getnotificationsettings(completionhandler:)"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)": {
      "abstract": [
        {
          "text": "Requests a person’s authorization to allow local and remote notifications for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAuthorizationOptions",
          "text": "UNAuthorizationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAuthorizationWithOptions:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestAuthorization(options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/usernotifications/unusernotificationcenter/requestauthorization(options:completionhandler:)"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenterDelegate/userNotificationCenter(_:willPresent:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Asks the delegate how to handle a notification that arrived while the app was running in the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userNotificationCenter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UNUserNotificationCenter",
          "text": "UNUserNotificationCenter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UNNotification",
          "text": "UNNotification"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNNotificationPresentationOptions",
          "text": "UNNotificationPresentationOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNUserNotificationCenterDelegate/userNotificationCenter(_:willPresent:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userNotificationCenter:willPresentNotification:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "userNotificationCenter(_:willPresent:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/usernotifications/unusernotificationcenterdelegate/usernotificationcenter(_:willpresent:withcompletionhandler:)"
    },
    "media-3544497": {
      "alt": "A screenshot of a provisional notification in the notification center, with buttons to keep or turn off the notification.",
      "identifier": "media-3544497",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7ab9098dfb8cdbc554b7da2b7c7d3097/media-3544497@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7ab9098dfb8cdbc554b7da2b7c7d3097/media-3544497~dark@2x.png"
        }
      ]
    },
    "media-3559454": {
      "alt": "A screenshot showing the system prompting a person to allow or disallow the use of alerts, sounds, and badges when the app sends notifications.",
      "identifier": "media-3559454",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/09fe7bfb520668466145ef245b3c0a50/media-3559454@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/09fe7bfb520668466145ef245b3c0a50/media-3559454~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/Updates/UserNotifications"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNUserNotificationCenter~1getNotificationSettings(completionHandler:)/title",
          "value": "getNotificationSettingsWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNUserNotificationCenter~1getNotificationSettings(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getNotificationSettingsWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNUserNotificationCenter~1requestAuthorization(options:completionHandler:)/title",
          "value": "requestAuthorizationWithOptions:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNUserNotificationCenter~1requestAuthorization(options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestAuthorizationWithOptions:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNUserNotificationCenterDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)/title",
          "value": "userNotificationCenter:willPresentNotification:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNUserNotificationCenterDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "userNotificationCenter:willPresentNotification:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSetting~1enabled/title",
          "value": "UNNotificationSettingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSetting~1enabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSettingEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1provisional/title",
          "value": "UNAuthorizationOptionProvisional"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationOptions~1provisional/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationOptionProvisional"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings/title",
          "value": "UNNotificationSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationStatus~1provisional/title",
          "value": "UNAuthorizationStatusProvisional"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNAuthorizationStatus~1provisional/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNAuthorizationStatusProvisional"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNUserNotificationCenter/title",
          "value": "UNUserNotificationCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNUserNotificationCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNUserNotificationCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNUserNotificationCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNUserNotificationCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings~1notificationCenterSetting/title",
          "value": "notificationCenterSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSettings~1notificationCenterSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationCenterSetting"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/asking-permission-to-use-notifications"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotifications/asking-permission-to-use-notifications"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
