{
  "abstract": [
    {
      "text": "Secure your communications with APNs to send API requests.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications",
        "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-connection-to-apns"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Establishing a connection to Apple Push Notification service (APNs)"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "code": "HTTP/2",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "TLS 1.2",
              "type": "codeVoice"
            },
            {
              "text": " or later to establish a connection between your provider server and APNs server to send API requests. Based on the type of request you’re using, there’s a different development and production endpoint. If you’re shipping apps, use the production end points. If you’re testing, use the development endpoints. If you’re sending many remote notifications, you can establish multiple connections to these servers to improve performance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "APNs allows for multiple concurrent streams for each connection, but don’t assume a specific number of streams. The exact number varies based on server load and whether you use a provider certificate or an authentication token. For example, if you’re using an ",
              "type": "text"
            },
            {
              "code": "authentication",
              "type": "codeVoice"
            },
            {
              "text": " token, APNs allows only one stream until you post a request with a valid ",
              "type": "text"
            },
            {
              "code": "authentication",
              "type": "codeVoice"
            },
            {
              "text": " token. APNs ignores ",
              "type": "text"
            },
            {
              "code": "HTTP/2 PRIORITY",
              "type": "codeVoice"
            },
            {
              "text": " frames, so don’t send them on your streams.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you experience a revoked provider certificate, or if you revoke your authentication token, close all connections to APNs, fix the problem, and then open new connections. APNs may also terminate a connection by sending a ",
              "type": "text"
            },
            {
              "code": "GOAWAY",
              "type": "codeVoice"
            },
            {
              "text": " frame. The payload of the ",
              "type": "text"
            },
            {
              "code": "GOAWAY",
              "type": "codeVoice"
            },
            {
              "text": " frame includes ",
              "type": "text"
            },
            {
              "code": "JSON",
              "type": "codeVoice"
            },
            {
              "text": " data with a ",
              "type": "text"
            },
            {
              "code": "reason",
              "type": "codeVoice"
            },
            {
              "text": " key, indicating the reason for the connection termination. For a list of values for the ",
              "type": "text"
            },
            {
              "code": "reason",
              "type": "codeVoice"
            },
            {
              "text": " key, refer to the response error strings in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notification-responses-from-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-request-to-APNs",
          "level": 3,
          "text": "Create a request to APNs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To send a notification to a person’s device, construct and send a POST notification to APNs. Send this request over the connection you created using ",
              "type": "text"
            },
            {
              "code": "HTTP/2",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "TLS",
              "type": "codeVoice"
            },
            {
              "text": ". To create your POST notification, you must already have the following pieces of information:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you’re using device push, the device token that identifies the device to receive the notification; refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you’re using token-based authentication, your current authentication token; refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The notification’s payload, specified as JSON data; refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you’re using certificate-based authentication, your provider certificate. You send your provider certificate to APNs when setting up your ",
                      "type": "text"
                    },
                    {
                      "code": "TLS",
                      "type": "codeVoice"
                    },
                    {
                      "text": " connection. For more information, refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-certificate-based-connection-to-apns",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Depending on the connection you’re establishing with APNs, each request has a different path and header requirement.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Send-a-request-to-APNs",
          "level": 3,
          "text": "Send a request to APNs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "APNs requires the use of HPACK (header compression for HTTP/2), which prevents repeatedly storing header keys and values. APNs maintains a small dynamic table for HPACK. To avoid filling up that table, encode your headers in the following way—especially when using many streams:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The first time you send an APNs documented header name, encode them with incremental indexing and add the header fields to the dynamic table. Reuse the indexed header name for subsequent requests.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Index and reuse an APNs documented header value that doesn’t change frequently for your use-case.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If you are using token-based authentication, the ",
              "type": "text"
            },
            {
              "code": "authorization",
              "type": "codeVoice"
            },
            {
              "text": " header value shouldn’t change frequently and can be indexed. If you are using separate connections for different push types, ",
              "type": "text"
            },
            {
              "code": "apns-push-type",
              "type": "codeVoice"
            },
            {
              "text": " header value can also be indexed and reused. If you are using broadcast push notifications, the channel ID used for push notifications might not change often and can be indexed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Troubleshoot-problems-with-connecting-to-APNs",
          "level": 3,
          "text": "Troubleshoot problems with connecting to APNs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your provider server is unable to connect to APNs, examine the following possible causes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Make sure you have the needed certificates installed on your provider server. If your provider server doesn’t have the proper certificates for ",
                      "type": "text"
                    },
                    {
                      "code": "TLS/SS",
                      "type": "codeVoice"
                    },
                    {
                      "text": "L validation, it cannot connect to APNs. For certificate-based connections, your provider server must also have the certificate you obtained from Apple. Refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-certificate-based-connection-to-apns",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check how often your provider server connects to APNs. If your provider server opens and closes its connection to APNs repeatedly, APNs may treat it as a denial-of-service attack and temporarily block your server from connecting.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can verify the TLS handshake between your provider server and APNs by running the ",
              "type": "text"
            },
            {
              "code": "OpenSSL s_client",
              "type": "codeVoice"
            },
            {
              "text": " command from your server, as shown below. This command can also show if your ",
              "type": "text"
            },
            {
              "code": "TLS/SSL",
              "type": "codeVoice"
            },
            {
              "text": " certificates are expired or revoked.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The code listing below verifies the ",
              "type": "text"
            },
            {
              "code": "TLS",
              "type": "codeVoice"
            },
            {
              "text": " handshake with device push notifications sandbox endpoint",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "$ openssl s_client -connect api.development.push.apple.com:443 -cert YourSSLCertAndPrivateKey.pem -debug ",
            "-showcerts -CAfile server-ca-cert.pem"
          ],
          "syntax": "Other",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-certificate-based-connection-to-apns": {
      "abstract": [
        {
          "text": "Secure your communications with Apple Push Notification service (APNs) by installing a certificate on your provider server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-certificate-based-connection-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Establishing a certificate-based connection to APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/establishing-a-certificate-based-connection-to-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns": {
      "abstract": [
        {
          "text": "Secure your communications with Apple Push Notification service (APNs) by using stateless authentication tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Establishing a token-based connection to APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/establishing-a-token-based-connection-to-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification": {
      "abstract": [
        {
          "text": "Send notifications to the user’s device with a JSON payload.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification",
      "kind": "article",
      "role": "article",
      "title": "Generating a remote notification",
      "type": "topic",
      "url": "/documentation/usernotifications/generating-a-remote-notification"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notification-responses-from-apns": {
      "abstract": [
        {
          "text": "Respond to the status codes that the APNs servers return.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notification-responses-from-apns",
      "kind": "article",
      "role": "article",
      "title": "Handling notification responses from APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/handling-notification-responses-from-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/pushing-background-updates-to-your-app": {
      "abstract": [
        {
          "text": "Deliver notifications that wake your app and update it in the background.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/pushing-background-updates-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Pushing background updates to your App",
      "type": "topic",
      "url": "/documentation/usernotifications/pushing-background-updates-to-your-app"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns": {
      "abstract": [
        {
          "text": "Communicate with Apple Push Notification service (APNs) and receive a unique device token that identifies your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns",
      "kind": "article",
      "role": "article",
      "title": "Registering your app with APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/registering-your-app-with-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server": {
      "abstract": [
        {
          "text": "Generate notifications and push them to user devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting up a remote notification server",
      "type": "topic",
      "url": "/documentation/usernotifications/setting-up-a-remote-notification-server"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Server-tasks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns",
        "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification",
        "doc://com.apple.usernotifications/documentation/UserNotifications/pushing-background-updates-to-your-app"
      ],
      "title": "Server tasks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Server-tasks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns",
                "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification",
                "doc://com.apple.usernotifications/documentation/UserNotifications/pushing-background-updates-to-your-app"
              ],
              "title": "Server tasks"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/establishing-a-connection-to-apns"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotifications/establishing-a-connection-to-apns"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
