{
  "abstract": [
    {
      "text": "Secure your communications with Apple Push Notification service (APNs) by installing a certificate on your provider server.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications",
        "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-certificate-based-connection-to-apns"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Establishing a certificate-based connection to APNs"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With certificate-based authentication, you use a provider certificate to establish a secure connection between your provider server and APNs. You obtain this certificate from Apple through your developer account.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because you establish trust at the server level, individual notification requests contain only your payload and a device token. They don’t include an authentication token, which reduces the size of each notification request slightly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use a provider certificate to send notifications to a single app, the Apple Watch complication, or to background VoIP services associated with a single app. To send remote notifications to multiple apps, you must create separate certificates for each app. You must also manage separate APNs connections for each app’s notifications. As a result, it’s often simpler to use token-based authentication to support multiple apps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Obtain-a-provider-certificate-from-Apple",
          "level": 3,
          "text": "Obtain a provider certificate from Apple",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You obtain a provider certificate from your developer account when you sign in to ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In the Program resources section:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select Certificates under Certificates, IDs & Profiles.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add a new certificate.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Under Services, select Apple Push Notification service SSL (Sandbox & Production) for the type and click Continue.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the App ID (also known as Bundle ID) of your app and click Continue.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Generate a Certificate Signing Request (CSR) on your server.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click Continue.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Upload your CSR file and click Continue.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Download the resulting certificate.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Certificates must be tied to a specific app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Tie a different provider certificate to each app, whose App ID you specify when creating the certificate. You must also tie your certificate to a CSR, which is the private key used to encrypt the certificate. The certificate itself becomes the public key that you exchange with APNs. For more information on certificate creation, see ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/developer-account/#/deveedc0daa0",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Install-the-certificate-and-private-key",
          "level": 3,
          "text": "Install the certificate and private key",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Install both the certificate and the private key on your provider server. In macOS, double-clicking the certificate installs it in Keychain Access automatically. If you created your CSR file from your provider server, Keychain Access installs the key in your keychain automatically.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use a certificate generated by selecting VoIP Services Certificate to send Pushkit VOIP notifications. A WatchKit Services Certificate allows both PushKit VoIP and notifications for the watchOS complication. Use the command-line tool ",
              "type": "text"
            },
            {
              "code": "openssl",
              "type": "codeVoice"
            },
            {
              "text": " with command option ",
              "type": "text"
            },
            {
              "code": "x509",
              "type": "codeVoice"
            },
            {
              "text": " to inspect a certificate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can also use the Keychain Access app to inspect a certificate. In Keychain Access, you can find the Topic/Bundle ID under Details > Subject Name > Common Name. Also check for Extension 1.2.840.113635.100.6.3.4 and 1.2.840.113635.100.6.3.6 under Details > Public Key Info for additional Topics/Bundle IDs for Pushkit VoIP, watchOS complication, and Push to Talk. If a certificate doesn’t have the push topic for a specific push type, you can’t use the certificate to send a notification of that type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Check expiry of a certificate with Keychain Access. To avoid a disruption in service for your users, update your provider certificates before they expire. Provider certificates are valid for a year and you must update them to continue communicating with APNs.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Establish-trust-with-APNs",
          "level": 3,
          "text": "Establish trust with APNs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With your certificates installed, the following figure shows the sequence of steps to initiate a connection to the APNs server. After you request a secure connection using Transport Layer Security (TLS), APNs responds by sending a certificate for your provider server to validate. After validating that certificate, your provider certificate completes the secure connection. At this point, you can begin sending remote notification requests to APNs. An up-to-date version of macOS includes the appropriate trust store to validate the certificate presented by APNs. For other platforms, ensure you include a proper root certificate in your trust store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4286315",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The figure above has been simplified for the purpose of visualization. For a detailed flow, refer to ",
              "type": "text"
            },
            {
              "identifier": "https://datatracker.ietf.org/doc/html/rfc5246",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "https://datatracker.ietf.org/doc/html/rfc8446",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you think you have a compromised certificate or private key, you can revoke your certificate from your developer account. For more information, refer to ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/account/create-certificates/revoke-a-certificate/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". APNs maintains a list of revoked certificates, and it refuses TLS connections from servers with certificates on that list. If your server uses a revoked certificate, close all existing connections to APNs and configure a new provider certificate for your server before opening any new connections.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns": {
      "abstract": [
        {
          "text": "Secure your communications with Apple Push Notification service (APNs) by using stateless authentication tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Establishing a token-based connection to APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/establishing-a-token-based-connection-to-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server": {
      "abstract": [
        {
          "text": "Generate notifications and push them to user devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting up a remote notification server",
      "type": "topic",
      "url": "/documentation/usernotifications/setting-up-a-remote-notification-server"
    },
    "https://datatracker.ietf.org/doc/html/rfc5246": {
      "identifier": "https://datatracker.ietf.org/doc/html/rfc5246",
      "title": "RFC 5246",
      "titleInlineContent": [
        {
          "text": "RFC 5246",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://datatracker.ietf.org/doc/html/rfc5246"
    },
    "https://datatracker.ietf.org/doc/html/rfc8446": {
      "identifier": "https://datatracker.ietf.org/doc/html/rfc8446",
      "title": "RFC 8446",
      "titleInlineContent": [
        {
          "text": "RFC 8446",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://datatracker.ietf.org/doc/html/rfc8446"
    },
    "https://developer.apple.com": {
      "identifier": "https://developer.apple.com",
      "title": "developer.apple.com",
      "titleInlineContent": [
        {
          "text": "developer.apple.com",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com"
    },
    "https://developer.apple.com/help/account/create-certificates/revoke-a-certificate/": {
      "identifier": "https://developer.apple.com/help/account/create-certificates/revoke-a-certificate/",
      "title": "Revoke a certificate",
      "titleInlineContent": [
        {
          "text": "Revoke a certificate",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/account/create-certificates/revoke-a-certificate/"
    },
    "https://help.apple.com/developer-account/#/deveedc0daa0": {
      "identifier": "https://help.apple.com/developer-account/#/deveedc0daa0",
      "title": "Certificates overview",
      "titleInlineContent": [
        {
          "text": "Certificates overview",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/developer-account/#/deveedc0daa0"
    },
    "media-4286315": {
      "alt": "A wireframe diagram depicting the sequence of steps that occur when you open a connection to the APNs server. Starting from the left is the Provider that requests a secure connection using TLS. APNs validates the connection using an APNs certificate. The Provider Validates the APNs certificate and a TLS connection is established.",
      "identifier": "media-4286315",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/804bee02436d3b85e22f0d2a275f7c19/media-4286315@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d5577922a326842756ae19e00b728ee6/media-4286315~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Security",
      "generated": true,
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns"
      ],
      "title": "Security"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Security",
              "generated": true,
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns"
              ],
              "title": "Security"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/establishing-a-certificate-based-connection-to-apns"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotifications/establishing-a-certificate-based-connection-to-apns"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
