{
  "abstract": [
    {
      "text": "Transmit your remote notification payload and device token information to Apple Push Notification service (APNs).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications",
        "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/sending-notification-requests-to-apns"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Sending notification requests to APNs"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As a best-effort service, APNs may reorder notifications you send to the same device token. If APNs can’t deliver a notification immediately, it may store the notification for 30 days or less, depending on the date you specify in the ",
              "type": "text"
            },
            {
              "code": "apns-expiration",
              "type": "codeVoice"
            },
            {
              "text": " header. APNs attempts to deliver the notification the next time the device activates and is available online.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "APNs stores only one notification per bundle ID. When you send multiple notifications to the same device for a bundle ID, APNs selects only one notification to store in a non-deterministic way. Notifications with ",
              "type": "text"
            },
            {
              "code": "apns-priority",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "5",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": " might get grouped and delivered in bursts to the user’s device. Your notifications may also get throttled, saved in storage, and in some cases, not delivered. The way the user interacts with your application and the power state of the device determines the exact behavior. For more information about the factors that impact the delivery of a push notification, refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you have a notification to send to a user, your provider must construct a POST request and send it to Apple Push Notification service (APNs). Upon receiving your server’s POST request, APNs validates the request using either the provided authentication token or your server’s certificate. If validation succeeds, APNs uses the provided device token to identify the user’s device. It then tries to send your JSON payload to that device. For information on sending test notifications without setting up the environment, refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/testing-notifications-using-the-push-notification-console",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Establish-a-connection-to-APNs",
          "level": 3,
          "text": "Establish a connection to APNs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use HTTP/2 and TLS 1.2 or later to establish a connection between your provider server and one of the following servers:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Development server: ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://api.sandbox.push.apple.com:443",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Production server: ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://api.push.apple.com:443",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Use the production server for your shipping apps and the development server for testing. When sending many remote notifications, you can establish multiple connections to these servers to improve performance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can also use port 2197 (instead of port 443) on either server when communicating with APNs. You might use this port to allow APNs traffic through your firewall but to block other HTTPS traffic.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "APNs allows multiple concurrent streams for each connection, but don’t assume a specific number of streams. The exact number varies based on server load and whether you use a provider certificate or an authentication token. For example, when using an authentication token, APNs allows only one stream until you post a request with a valid authentication token. APNs ignores ",
              "type": "text"
            },
            {
              "code": "HTTP/2 PRIORITY",
              "type": "codeVoice"
            },
            {
              "text": " frames, so don’t send them on your streams.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you experience a revoked provider certificate, or if you revoke your authentication token, close all connections to APNs, fix the problem, and then open new connections. APNs may also terminate a connection by sending a ",
              "type": "text"
            },
            {
              "code": "GOAWAY",
              "type": "codeVoice"
            },
            {
              "text": " frame. The payload of the ",
              "type": "text"
            },
            {
              "code": "GOAWAY",
              "type": "codeVoice"
            },
            {
              "text": " frame includes JSON data with a ",
              "type": "text"
            },
            {
              "code": "reason",
              "type": "codeVoice"
            },
            {
              "text": " key, indicating the reason for the connection termination. For a list of values for the ",
              "type": "text"
            },
            {
              "code": "reason",
              "type": "codeVoice"
            },
            {
              "text": " key, refer to the response error strings in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notification-responses-from-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-POST-request-to-APNs",
          "level": 3,
          "text": "Create a POST request to APNs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To send a notification to a user’s device, construct and send a POST notification to APNs. Send this request over the connection you created using HTTP/2 and TLS. To create your POST notification, you must already have the following pieces of information:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The device token that identifies the user device to receive the notification; refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your current authentication token (only if you’re using token-based authentication); refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The notification’s payload, specified as JSON data; refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you’re using certificate-based authentication, you send your provider certificate to APNs when setting up your TLS connection. For more information, refer to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-certificate-based-connection-to-apns",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Send-a-POST-request-to-APNs",
          "level": 3,
          "text": "Send a POST request to APNs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To deliver the notifications, you’re required to have some header fields. In addition to the preceding data, add the following header fields in to your request. Other headers are optional or may depend on whether you’re using token-based or certificate-based authentication.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Header field",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Required",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": ":method",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Required",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The value ",
                      "type": "text"
                    },
                    {
                      "code": "POST",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": ":path",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Required",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The path to the device token. The value of this header is ",
                      "type": "text"
                    },
                    {
                      "code": "/3/device/<device_token>",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", where ",
                      "type": "text"
                    },
                    {
                      "code": "<device_token>",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is the hexadecimal bytes that identify the user’s device. Your app receives the bytes for this device token when registering for remote notifications. For more information, refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "authorization",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Required for token-based authentication",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The value of this header is ",
                      "type": "text"
                    },
                    {
                      "code": "bearer <provider_token>",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", where ",
                      "type": "text"
                    },
                    {
                      "code": "<provider_token>",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is the encrypted token that authorizes you to send notifications for the specified topic. APNs ignores this header if you use certificate-based authentication. For more information, refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "apns-push-type",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Required for watchOS 6 and later; recommended for macOS, iOS, tvOS, and iPadOS",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The value of this header must accurately reflect the contents of your notification’s payload. If there’s a mismatch, or if the header is missing on required systems, APNs may return an error, delay the delivery of the notification, or drop it altogether.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "apns-id",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Optional",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "A canonical UUID that’s the unique ID for the notification. If an error occurs when sending the notification, APNs includes this value when reporting the error to your server. Canonical UUIDs are 32 lowercase hexadecimal digits, displayed in five groups separated by hyphens in the form 8-4-4-4-12. For example: ",
                      "type": "text"
                    },
                    {
                      "code": "123e4567-e89b-12d3-a456-4266554400a0",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". If you omit this header, APNs creates a UUID for you and returns it in its response.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "apns-expiration",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Optional",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The date at which the notification is no longer valid. This value is a UNIX epoch expressed in seconds (UTC). If the value is nonzero, APNs stores the notification and tries to deliver it at least once, repeating the attempt as needed until the specified date. If the value is ",
                      "type": "text"
                    },
                    {
                      "code": "0",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", APNs attempts to deliver the notification only once and doesn’t store it. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " A single APNs attempt may involve retries over multiple network interfaces and connections of the destination device. Often these retries span over some time period, depending on the network characteristics. In addition, a push notification may take some time on the network after APNs sends it to the device. APNs uses best efforts to honor the expiry date without any guarantee. If the value is nonzero, the notification may deliver after the specified timestamp. If the value is ",
                      "type": "text"
                    },
                    {
                      "code": "0",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", the notification may deliver with some delay. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " If you omit this header, APNs stores the push according to APNs storage policy. For more information, refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/sending-notification-requests-to-apns",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "apns-priority",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Optional",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The priority of the notification. If you omit this header, APNs sets the notification priority to ",
                      "type": "text"
                    },
                    {
                      "code": "10",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " Specify ",
                      "type": "text"
                    },
                    {
                      "code": "10",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to send the notification immediately. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " Specify ",
                      "type": "text"
                    },
                    {
                      "code": "5",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to send the notification based on power considerations on the user’s device. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " Specify 1 to prioritize the device’s power considerations over all other factors for delivery, and prevent awakening the device.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "apns-topic",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Optional",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The topic for the notification. In general, the topic is your app’s bundle ID/app ID. It can have a suffix based on the type of push notification. If you’re using a certificate that supports PushKit VoIP or watchOS complication notifications, you must include this header with the bundle ID of your app and if applicable, the proper suffix. If you’re using token-based authentication with APNs, you must include this header with the correct bundle ID and suffix combination. To learn more about app ID, refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://help.apple.com/developer-account/#/dev1b35d6f83",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "apns-collapse-id",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Optional",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "An identifier you use to merge multiple notifications into a single notification for the user. Typically, each notification request displays a new notification on the user’s device. When sending the same notification more than once, use the same value in this header to merge the requests. The value of this key must not exceed 64 bytes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "APNs requires the use of HPACK (header compression for HTTP/2), which prevents repeatedly storing header keys and values. APNs maintains a small dynamic table for HPACK. To avoid filling up that table, encode your headers in the following way—especially when using many streams:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Encode the ",
                      "type": "text"
                    },
                    {
                      "code": ":path",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "authorization",
                      "type": "codeVoice"
                    },
                    {
                      "text": " values as ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "literal header fields without indexing",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Encode the ",
                      "type": "text"
                    },
                    {
                      "code": "apns-id",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "apns-expiration",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "code": "apns-collapse-id",
                      "type": "codeVoice"
                    },
                    {
                      "text": " values differently based on whether this is an initial or subsequent request.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The first time you send these headers, encode them with ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "incremental indexing",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " to add the header fields to the dynamic table.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For subsequent requests, encode these headers as ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "literal header fields without indexing",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Encode all other fields as literal header fields with ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "incremental indexing",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Put the JSON payload with the notification’s content into the body of your request. You must not use a compressed JSON payload, and it’s limited to a maximum size of 4 KB (4096 bytes). The maxiumum size for a Voice over Internet Protocol (VoIP) notification is 5 KB (5120 bytes).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The code snippet below shows a sample request constructed with an authentication token.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "HEADERS",
            "  - END_STREAM",
            "  + END_HEADERS",
            "  :method = POST",
            "  :scheme = https",
            "  :path = /3/device/00fc13adff785122b4ad28809a3420982341241421348097878e577c991de8f0",
            "  host = api.sandbox.push.apple.com",
            "  authorization = bearer eyAia2lkIjogIjhZTDNHM1JSWDciIH0.eyAiaXNzIjogIkM4Nk5WOUpYM0QiLCAiaWF0I",
            "\t\t jogIjE0NTkxNDM1ODA2NTAiIH0.MEYCIQDzqyahmH1rz1s-LFNkylXEa2lZ_aOCX4daxxTZkVEGzwIhALvkClnx5m5eAT6",
            "\t\t Lxw7LZtEQcH6JENhJTMArwLf3sXwi",
            "  apns-id = eabeae54-14a8-11e5-b60b-1697f925ec7b",
            "  apns-push-type = alert",
            "  apns-expiration = 0",
            "  apns-priority = 10",
            "  apns-topic = com.example.MyApp",
            "DATA",
            "  + END_STREAM",
            "  { \"aps\" : { \"alert\" : \"Hello\" } }",
            ""
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The code snippet below shows a sample request constructed for use with a certificate. APNs uses the app’s bundle ID as the default topic.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "HEADERS",
            "  - END_STREAM",
            "  + END_HEADERS",
            "  :method = POST",
            "  :scheme = https",
            "  :path = /3/device/00fc13adff785122b4ad28809a3420982341241421348097878e577c991de8f0",
            "  host = api.sandbox.push.apple.com",
            "  apns-id = eabeae54-14a8-11e5-b60b-1697f925ec7b",
            "  apns-push-type = alert",
            "  apns-expiration = 0",
            "  apns-priority = 10",
            "DATA",
            "  + END_STREAM",
            "  { \"aps\" : { \"alert\" : \"Hello\" } }",
            ""
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "anchor": "Know-when-to-use-push-types",
          "level": 3,
          "text": "Know when to use push types",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "apns-push-type",
              "type": "codeVoice"
            },
            {
              "text": " header field has the following valid values. The descriptions below describe when and how to use these values. Send an ",
              "type": "text"
            },
            {
              "code": "apns-push-type",
              "type": "codeVoice"
            },
            {
              "text": " header with each push. Recent and upcoming features may not work if this header is missing. See the table above to determine if this header is required or optional.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The push type for notifications that trigger a user interaction—for example, an alert, badge, or sound. If you set this push type, the ",
                        "type": "text"
                      },
                      {
                        "code": "apns-topic",
                        "type": "codeVoice"
                      },
                      {
                        "text": " header field must use your app’s bundle ID as the topic. For more information, refer to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "If the notification requires immediate action from the user, set notification priority to ",
                        "type": "text"
                      },
                      {
                        "code": "10",
                        "type": "codeVoice"
                      },
                      {
                        "text": "; otherwise use ",
                        "type": "text"
                      },
                      {
                        "code": "5",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "You’re required to use the ",
                        "type": "text"
                      },
                      {
                        "code": "alert",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type on watchOS 6 and later. It’s recommended on macOS, iOS, tvOS, and iPadOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "alert",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The push type for notifications that deliver content in the background, and don’t trigger any user interactions. If you set this push type, the ",
                        "type": "text"
                      },
                      {
                        "code": "apns-topic",
                        "type": "codeVoice"
                      },
                      {
                        "text": " header field must use your app’s bundle ID as the topic. Always use priority ",
                        "type": "text"
                      },
                      {
                        "code": "5",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". Using priority ",
                        "type": "text"
                      },
                      {
                        "code": "10",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is an error. For more information, refer to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/pushing-background-updates-to-your-app",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "You’re required to use the ",
                        "type": "text"
                      },
                      {
                        "code": "background",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type on watchOS 6 and later. It’s recommended on macOS, iOS, tvOS, and iPadOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "background",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The push type to reload and update a control. When someone interacts with a web server connected to your app, enable a control to update its state using the ",
                        "type": "text"
                      },
                      {
                        "code": "controls",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type. For more information, refer to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/WidgetKit/Updating-controls-locally-and-remotely#Use-push-notifications-to-reload-controls",
                        "isActive": true,
                        "type": "reference"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "controls",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The push type for notifications that request a user’s location. If you set this push type, the ",
                        "type": "text"
                      },
                      {
                        "code": "apns-topic",
                        "type": "codeVoice"
                      },
                      {
                        "text": " header field must use your app’s bundle ID wit",
                        "type": "text"
                      },
                      {
                        "code": "h.location-query",
                        "type": "codeVoice"
                      },
                      {
                        "text": " appended to the end. For more information, refer to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/CoreLocation/creating-a-location-push-service-extension",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "It’s recommended for iOS and iPadOS. If the location query requires an immediate response from the Location Push Service Extension, set notification ",
                        "type": "text"
                      },
                      {
                        "code": "apns-priority",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to ",
                        "type": "text"
                      },
                      {
                        "code": "10",
                        "type": "codeVoice"
                      },
                      {
                        "text": "; otherwise, use ",
                        "type": "text"
                      },
                      {
                        "code": "5",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". The ",
                        "type": "text"
                      },
                      {
                        "code": "location",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type supports only token-based authentication.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "code": "location",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type isn’t available on macOS, tvOS, and watchOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "location",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The push type for notifications that provide information about an incoming Voice-over-IP (VoIP) call. For more information, refer to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/PushKit/responding-to-voip-notifications-from-pushkit",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "If you set this push type, the ",
                        "type": "text"
                      },
                      {
                        "code": "apns-topic",
                        "type": "codeVoice"
                      },
                      {
                        "text": " header field must use your app’s bundle ID wit",
                        "type": "text"
                      },
                      {
                        "code": "h.voip",
                        "type": "codeVoice"
                      },
                      {
                        "text": " appended to the end. If you’re using certificate-based authentication, you must also register the certificate for VoIP services. The topic is then part of the 1.2.840.113635.100.6.3.4 or 1.2.840.113635.100.6.3.6 extension.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "code": "voip",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type isn’t available on watchOS. It’s recommended on macOS, iOS, tvOS, and iPadOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "voip",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The push type for notifications that contain update information for a watchOS app’s complications. For more information, refer to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/ClockKit/keeping-your-complications-up-to-date",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "If you set this push type, the ",
                        "type": "text"
                      },
                      {
                        "code": "apns-topic",
                        "type": "codeVoice"
                      },
                      {
                        "text": " header field must use your app’s bundle ID wit",
                        "type": "text"
                      },
                      {
                        "code": "h.complication",
                        "type": "codeVoice"
                      },
                      {
                        "text": " appended to the end. If you’re using certificate-based authentication, you must also register the certificate for WatchKit services. The topic is then part of the 1.2.840.113635.100.6.3.6 extension.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "code": "complication",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type isn’t available on macOS, tvOS, and iPadOS. It’s recommended for watchOS and iOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "complication",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The push type to signal changes to a File Provider extension. If you set this push type, the ",
                        "type": "text"
                      },
                      {
                        "code": "apns-topic",
                        "type": "codeVoice"
                      },
                      {
                        "text": " header field must use your app’s bundle ID wit",
                        "type": "text"
                      },
                      {
                        "code": "h.pushkit.fileprovider",
                        "type": "codeVoice"
                      },
                      {
                        "text": " appended to the end. For more information, refer to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/FileProvider/using-push-notifications-to-signal-changes",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "code": "fileprovider",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type isn’t available on watchOS. It’s recommended on macOS, iOS, tvOS, and iPadOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "fileprovider",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The push type for notifications that tell managed devices to contact the MDM server. If you set this push type, you must use the topic from the UID attribute in the subject of your MDM push certificate. For more information, refer to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/DeviceManagement",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "code": "mdm",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type isn’t available on watchOS. It’s recommended on macOS, iOS, tvOS, and iPadOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "mdm",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The push type to signal changes to a live activity session. If you set this push type, the apns-topic header field must use your app’s bundle ID wit",
                        "type": "text"
                      },
                      {
                        "code": "h.push-type.liveactivity",
                        "type": "codeVoice"
                      },
                      {
                        "text": " appended to the end. For more information, refer to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/ActivityKit/starting-and-updating-live-activities-with-activitykit-push-notifications",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "code": "liveactivity",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type isn’t available on watchOS, macOS, and tvOS. It’s recommended on iOS and iPadOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "liveactivity",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The push type for notifications that provide information about updates to your application’s push to talk services. For more information, refer to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/PushToTalk",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". If you set this push type, the apns-topic header field must use your app’s bundle ID wit",
                        "type": "text"
                      },
                      {
                        "code": "h.voip-ptt",
                        "type": "codeVoice"
                      },
                      {
                        "text": " appended to the end.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "code": "pushtotalk",
                        "type": "codeVoice"
                      },
                      {
                        "text": " push type isn’t available on watchOS, macOS, and tvOS. It’s recommended on iOS and iPadOS.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "pushtotalk",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Certificate-based connection supports only a subset of push types and token-based connection supports all push-types. For more information, refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-certificate-based-connection-to-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Check Extension 1.2.840.113635.100.6.3.6 and 1.2.840.113635.100.6.3.4 of your push certificate. These extensions list all the push topics allowed for your certificate. If a push topic for a specific push type isn’t listed, you can’t use the certificate to send a notification of that push type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Follow-best-practices-while-sending-push-notifications-with-APNs",
          "level": 3,
          "text": "Follow best practices while sending push notifications with APNs",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Below are some APNs best practices to consider:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Make an uncached DNS query to resolve the APNs server name, before each connection. This helps distribute push traffic from all providers across all APNs servers.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Avoid push bursts over selective connections. Diversifying push traffic over many connections distributes push traffic for your application across all APNs servers.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Reuse a connection as long as possible. In most cases, you can reuse a connection for many hours to days. If your connection is mostly idle, you may send a HTTP2 PING frame after an hour of inactivity. Reusing a connection often results in less bandwidth and CPU consumption.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a unique value for the ",
                      "type": "text"
                    },
                    {
                      "code": "apns-id",
                      "type": "codeVoice"
                    },
                    {
                      "text": " header to track your push notification. If you don’t provide one, APNs creates one and returns it as part of the response. Record this UUID to assist with debugging.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Pay attention to status returned by APNs for each push and take appropriate action for your application. For more information, refer to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notification-responses-from-apns",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you’re using a certificate to connect to APNs, remember to get a new certificate and deploy it with your service before the expiry of the current certificate.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Don’t make assumptions about device token size.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "APNs doesn’t support legacy binary protocol as of March 31, 2021. Update to the HTTP/2-based API as soon as possible.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/ActivityKit/starting-and-updating-live-activities-with-activitykit-push-notifications": {
      "abstract": [
        {
          "text": "Use ActivityKit to receive push tokens and to remotely start, update, and end your Live Activity with ActivityKit notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ActivityKit/starting-and-updating-live-activities-with-activitykit-push-notifications",
      "kind": "article",
      "role": "article",
      "title": "Starting and updating Live Activities with ActivityKit push notifications",
      "type": "topic",
      "url": "/documentation/ActivityKit/starting-and-updating-live-activities-with-activitykit-push-notifications"
    },
    "doc://com.apple.documentation/documentation/ClockKit/keeping-your-complications-up-to-date": {
      "abstract": [
        {
          "text": "Replace or extend the data in your complication’s timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClockKit/keeping-your-complications-up-to-date",
      "kind": "article",
      "role": "article",
      "title": "Keeping your complications up to date",
      "type": "topic",
      "url": "/documentation/ClockKit/keeping-your-complications-up-to-date"
    },
    "doc://com.apple.documentation/documentation/CoreLocation/creating-a-location-push-service-extension": {
      "abstract": [
        {
          "text": "Add and configure an extension to enable your location-sharing app to access a user’s location in response to a request from another user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreLocation/creating-a-location-push-service-extension",
      "kind": "article",
      "role": "article",
      "title": "Creating a location push service extension",
      "type": "topic",
      "url": "/documentation/CoreLocation/creating-a-location-push-service-extension"
    },
    "doc://com.apple.documentation/documentation/DeviceManagement": {
      "abstract": [
        {
          "text": "Manage your organization’s devices remotely.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/DeviceManagement",
      "kind": "symbol",
      "role": "collection",
      "title": "Device Management",
      "type": "topic",
      "url": "/documentation/DeviceManagement"
    },
    "doc://com.apple.documentation/documentation/FileProvider/using-push-notifications-to-signal-changes": {
      "abstract": [
        {
          "text": "Send push notifications to a device to signal changes from your server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/FileProvider/using-push-notifications-to-signal-changes",
      "kind": "article",
      "role": "article",
      "title": "Using push notifications to signal changes",
      "type": "topic",
      "url": "/documentation/FileProvider/using-push-notifications-to-signal-changes"
    },
    "doc://com.apple.documentation/documentation/PushKit/responding-to-voip-notifications-from-pushkit": {
      "abstract": [
        {
          "text": "Receive incoming Voice-over-IP (VoIP) push notifications and use them to display the system call interface to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit/responding-to-voip-notifications-from-pushkit",
      "kind": "article",
      "role": "article",
      "title": "Responding to VoIP Notifications from PushKit",
      "type": "topic",
      "url": "/documentation/PushKit/responding-to-voip-notifications-from-pushkit"
    },
    "doc://com.apple.documentation/documentation/PushToTalk": {
      "abstract": [
        {
          "text": "Display the system user interface for your app’s Push to Talk services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushToTalk",
      "kind": "symbol",
      "role": "collection",
      "title": "Push to Talk",
      "type": "topic",
      "url": "/documentation/PushToTalk"
    },
    "doc://com.apple.documentation/documentation/WidgetKit/Updating-controls-locally-and-remotely#Use-push-notifications-to-reload-controls": {
      "abstract": [
        {
          "text": "Update and reload controls from your app or using push notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit/Updating-controls-locally-and-remotely#Use-push-notifications-to-reload-controls",
      "kind": "article",
      "role": "article",
      "title": "Updating controls locally and remotely",
      "type": "topic",
      "url": "/documentation/WidgetKit/Updating-controls-locally-and-remotely"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-certificate-based-connection-to-apns": {
      "abstract": [
        {
          "text": "Secure your communications with Apple Push Notification service (APNs) by installing a certificate on your provider server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-certificate-based-connection-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Establishing a certificate-based connection to APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/establishing-a-certificate-based-connection-to-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns": {
      "abstract": [
        {
          "text": "Secure your communications with Apple Push Notification service (APNs) by using stateless authentication tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Establishing a token-based connection to APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/establishing-a-token-based-connection-to-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification": {
      "abstract": [
        {
          "text": "Send notifications to the user’s device with a JSON payload.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification",
      "kind": "article",
      "role": "article",
      "title": "Generating a remote notification",
      "type": "topic",
      "url": "/documentation/usernotifications/generating-a-remote-notification"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notification-responses-from-apns": {
      "abstract": [
        {
          "text": "Respond to the status codes that the APNs servers return.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notification-responses-from-apns",
      "kind": "article",
      "role": "article",
      "title": "Handling notification responses from APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/handling-notification-responses-from-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/pushing-background-updates-to-your-app": {
      "abstract": [
        {
          "text": "Deliver notifications that wake your app and update it in the background.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/pushing-background-updates-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Pushing background updates to your App",
      "type": "topic",
      "url": "/documentation/usernotifications/pushing-background-updates-to-your-app"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns": {
      "abstract": [
        {
          "text": "Communicate with Apple Push Notification service (APNs) and receive a unique device token that identifies your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns",
      "kind": "article",
      "role": "article",
      "title": "Registering your app with APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/registering-your-app-with-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/sending-notification-requests-to-apns": {
      "abstract": [
        {
          "text": "Transmit your remote notification payload and device token information to Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/sending-notification-requests-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Sending notification requests to APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/sending-notification-requests-to-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server": {
      "abstract": [
        {
          "text": "Generate notifications and push them to user devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting up a remote notification server",
      "type": "topic",
      "url": "/documentation/usernotifications/setting-up-a-remote-notification-server"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/testing-notifications-using-the-push-notification-console": {
      "abstract": [
        {
          "text": "Send test notifications and access delivery logs to test your app’s integration with Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/testing-notifications-using-the-push-notification-console",
      "kind": "article",
      "role": "article",
      "title": "Testing notifications using the Push Notification Console",
      "type": "topic",
      "url": "/documentation/usernotifications/testing-notifications-using-the-push-notification-console"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns": {
      "abstract": [
        {
          "text": "Monitor and interpret the status of your push notifications with Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns",
      "kind": "article",
      "role": "article",
      "title": "Viewing the status of push notifications using Metrics and APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns"
    },
    "https://api.push.apple.com:443": {
      "identifier": "https://api.push.apple.com:443",
      "title": "api.push.apple.com:443",
      "titleInlineContent": [
        {
          "text": "api.push.apple.com:443",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://api.push.apple.com:443"
    },
    "https://api.sandbox.push.apple.com:443": {
      "identifier": "https://api.sandbox.push.apple.com:443",
      "title": "api.sandbox.push.apple.com:443",
      "titleInlineContent": [
        {
          "text": "api.sandbox.push.apple.com:443",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://api.sandbox.push.apple.com:443"
    },
    "https://help.apple.com/developer-account/#/dev1b35d6f83": {
      "identifier": "https://help.apple.com/developer-account/#/dev1b35d6f83",
      "title": "Register an App ID",
      "titleInlineContent": [
        {
          "text": "Register an App ID",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/developer-account/#/dev1b35d6f83"
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Device-push-notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notification-responses-from-apns",
        "doc://com.apple.usernotifications/documentation/UserNotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns"
      ],
      "title": "Device push notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Device-push-notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notification-responses-from-apns",
                "doc://com.apple.usernotifications/documentation/UserNotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns"
              ],
              "title": "Device push notifications"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/sending-notification-requests-to-apns"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotifications/sending-notification-requests-to-apns"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
