{
  "abstract": [
    {
      "text": "Send test notifications and access delivery logs to test your app’s integration with Apple Push Notification service (APNs).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/testing-notifications-using-the-push-notification-console"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Testing notifications using the Push Notification Console"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Push notifications inform people about the most recent updates, news, or events from your app. A successful notification ensures that people get relevant information from your app, even when they’re not using it. Testing notifications before you send them can ensure functionality and reliability, and enhance the experience of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "https://icloud.developer.apple.com/dashboard",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is a web interface; use it to send tests both for device tokens and channels. The console lets you monitor delivery status for device push notifications in the development environment. It contains a delivery log, in which you can gain insight into your notification history. The Push Notification Console also provides status information about your notification, such as when APNs receives your notification, and if it goes to persistent storage.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Broadcast push notifications use channels to reach a large audience for updates on Live Activities. You can use the Push Notification Console to create channels and manage them; you can review channels, delete existing channels, and send push notifications on a channel.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The console also provides additional tooling to help debug and authenticate tokens used in Apple Push Notification service (APNs). You can determine the validity of your tokens to troubleshoot sending a notification and generate a JSON Web token (JWT).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Session 10025: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc2023/10025/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Session 9162: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc2024/9162/",
                  "isActive": true,
                  "type": "reference"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Related sessions from WWDC",
          "style": "note",
          "type": "aside"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Refer to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "anchor": "Create-and-send-a-test-push-notification",
          "level": 3,
          "text": "Create and send a test push notification",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Push Notification Console provides guidance on configuring various push notification parameters like push type, priority, and expiration as well as constructing the payload for the notification. Push Notification Console keeps a history of all the notifications sent from this page for 30 days. You can access the history in the sidebar on the left. All team members can access the console and view the history of the push notifications sent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the payload editor to input raw JSON directly or construct the payload using the editor’s interface. The payload format changes depending on the push type you select for the notification, and as a result, the layout of the editor may change accordingly. For more information about construction of the notification payload, refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The screenshot below is an example of using a test notification form to send a test notification to a device token in the Push Notification Console.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "devicepush",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The screenshot below is an example of a form used to send a test notification to a channel in the Push Notification Console.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "broadcastpush",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After entering the required information for a push notification request, you can generate the corresponding cURL command by clicking the Get cURL Command button. The generated cURL command includes the necessary headers, authentication information, and payload data for the request. Use this to send the same notification by connecting directly to APNs from the command line. For more information, refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/sending-push-notifications-using-command-line-tools",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the APNs production environment, only team members with the admin role can send push notifications. Nonadmins and admins can send pushes to the APNs development environment. For more information about the request parameters, refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/sending-notification-requests-to-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Manage-channels-for-broadcast-capability",
          "level": 3,
          "text": "Manage channels for broadcast capability",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the push notification console to manage your channels in the Channels tab. You can create new channels and delete existing channels that aren’t relevant. When you create a new channel, the console provides guidance on configuring parameters required for channel creation: environment and message storage policy. The parameters you specify can’t be changed later. For more information about message storage policy, refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/sending-channel-management-requests-to-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can also search a specific channel you created using the channel ID returned by APNs. The screenshot below is an example of a channel created using the Push Notification Console. At the top right corner, you can create a new channel, and underneath that, you can search for a specific channel with the channel ID.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "channel-list",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Verify-delivery-in-the-development-environment",
          "level": 3,
          "text": "Verify delivery in the development environment",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After APNs receives a push notification, it can undergo several state transitions before it reaches the device. The delivery of a push notification depends on a device’s battery, network connectivity, and other factors. APNs might deliver the notification immediately, defer delivery, make multiple attempts to deliver, or discard it based on those conditions. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the Delivery Log to monitor a notification’s delivery and give you insight into what happens to the notifications you send. To access this information, provide an “apns-unique-id”, an identifier that APNs returns in response to each notification request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4251168",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To view the delivery log for a particular push notification sent to APNs, you need to select the bundle ID that you used to send the notification from the dashboard. You can only query delivery logs of notifications sent for the selected bundle ID. Delivery logs are only available in the development environment. You can access the logs for up to seven days after you send the notification. Download and save the logs to retain them for future analysis or reference.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Debug-APNs-tokens",
          "level": 3,
          "text": "Debug APNs tokens",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The authentication token that you include with your notification requests uses the JSON Web Token (JWT) specification. You need a private key to sign the JWT. You can manage those keys through the developer portal. A team can have multiple signing keys. Each key is uniquely identified by a key ID. For more information about key management, see the “Manage keys” section in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/account/#/devcdfbb56a3",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can determine the validity of an authentication token by using the JWT Validator. Whether the token is valid depends on many factors, including but not limited to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Signature validity (public/private key match)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Team ID",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Expiration",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4238566",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the provided key is invalid, the tool gives the reason why it’s invalid. For debugging purposes, the validator parses and displays the key-value pairs that constitute the token’s header and payload. This helps identify any authentication problems you may face when using these credentials to initiate push notification requests. For more information on the token-based authentication that APNs uses, refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the Device Token Validator to determine the validity of the device token. To verify a device token associated with a bundle ID, you need to select the respective bundle ID in the dashboard. For more information on getting a device token, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4210015",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Generate-an-authentication-token",
          "level": 3,
          "text": "Generate an authentication token",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can generate an authentication token using the JWT generator by providing your private signing key and key ID. You need to get a private key before you can generate a JWT. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/account/manage-keys/create-a-private-key/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The screenshot below shows the JSON Web Token Generator with the correct information in the Private Key and Key ID fields. The generator tells you whether your key is valid.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The signing key isn’t uploaded anywhere, it’s only used in your browser.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4251167",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "broadcastpush": {
      "alt": "A screenshot of a form in the Push Notification console used as an example to send a test notification to a channel.",
      "identifier": "broadcastpush",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/922f07cd2d5f63c0419f4881ddc54fb2/broadcastpush@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/20fa8a1ea37d99ec00f4ff2f8fea804f/broadcastpush~dark@2x.png"
        }
      ]
    },
    "channel-list": {
      "alt": "A screenshot of a channel created using the Push Notification Console. Starting from left is a Channel ID, the push type, message storage policy, and the date that the channel was created. ",
      "identifier": "channel-list",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/51e9695cf7c721596dbc8aaf5db0fbd6/channel-list@2x.PNG"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/47602e7407c8815aa981a75949ba47fd/channel-list~dark@2x.PNG"
        }
      ]
    },
    "devicepush": {
      "alt": "A screenshot of a form in the Push Notification console used as an example to send a test notification to a device token.",
      "identifier": "devicepush",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1f5b0e7b92c57a93ee4501db26af91c4/devicepush@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/79fbc252a5699a1a9638a92196a726e6/devicepush~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns": {
      "abstract": [
        {
          "text": "Secure your communications with Apple Push Notification service (APNs) by using stateless authentication tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/establishing-a-token-based-connection-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Establishing a token-based connection to APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/establishing-a-token-based-connection-to-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification": {
      "abstract": [
        {
          "text": "Send notifications to the user’s device with a JSON payload.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification",
      "kind": "article",
      "role": "article",
      "title": "Generating a remote notification",
      "type": "topic",
      "url": "/documentation/usernotifications/generating-a-remote-notification"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns": {
      "abstract": [
        {
          "text": "Communicate with Apple Push Notification service (APNs) and receive a unique device token that identifies your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/registering-your-app-with-apns",
      "kind": "article",
      "role": "article",
      "title": "Registering your app with APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/registering-your-app-with-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/sending-channel-management-requests-to-apns": {
      "abstract": [
        {
          "text": "Manage channels that your application uses for broadcast push notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/sending-channel-management-requests-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Sending channel management requests to APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/sending-channel-management-requests-to-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/sending-notification-requests-to-apns": {
      "abstract": [
        {
          "text": "Transmit your remote notification payload and device token information to Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/sending-notification-requests-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Sending notification requests to APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/sending-notification-requests-to-apns"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/sending-push-notifications-using-command-line-tools": {
      "abstract": [
        {
          "text": "Use basic macOS command-line tools to send push notifications to Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/sending-push-notifications-using-command-line-tools",
      "kind": "article",
      "role": "article",
      "title": "Sending push notifications using command-line tools",
      "type": "topic",
      "url": "/documentation/usernotifications/sending-push-notifications-using-command-line-tools"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server": {
      "abstract": [
        {
          "text": "Generate notifications and push them to user devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting up a remote notification server",
      "type": "topic",
      "url": "/documentation/usernotifications/setting-up-a-remote-notification-server"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns": {
      "abstract": [
        {
          "text": "Monitor and interpret the status of your push notifications with Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns",
      "kind": "article",
      "role": "article",
      "title": "Viewing the status of push notifications using Metrics and APNs",
      "type": "topic",
      "url": "/documentation/usernotifications/viewing-the-status-of-push-notifications-using-metrics-and-apns"
    },
    "https://developer.apple.com/help/account/#/devcdfbb56a3": {
      "identifier": "https://developer.apple.com/help/account/#/devcdfbb56a3",
      "title": "Developer Account Help",
      "titleInlineContent": [
        {
          "text": "Developer Account Help",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/account/#/devcdfbb56a3"
    },
    "https://developer.apple.com/help/account/manage-keys/create-a-private-key/": {
      "identifier": "https://developer.apple.com/help/account/manage-keys/create-a-private-key/",
      "title": "Create a private key to access a service",
      "titleInlineContent": [
        {
          "text": "Create a private key to access a service",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/account/manage-keys/create-a-private-key/"
    },
    "https://developer.apple.com/videos/play/wwdc2023/10025/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2023/10025/",
      "title": "Meet Push Notifications Console",
      "titleInlineContent": [
        {
          "text": "Meet Push Notifications Console",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10025/"
    },
    "https://developer.apple.com/videos/play/wwdc2024/9162/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2024/9162/",
      "title": "Broadcast updates to your Live Activities",
      "titleInlineContent": [
        {
          "text": "Broadcast updates to your Live Activities",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2024/9162/"
    },
    "https://icloud.developer.apple.com/dashboard": {
      "identifier": "https://icloud.developer.apple.com/dashboard",
      "title": "Push Notification Console",
      "titleInlineContent": [
        {
          "text": "Push Notification Console",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://icloud.developer.apple.com/dashboard"
    },
    "media-4210015": {
      "alt": "A screenshot depicting an example of a valid Device Token.",
      "identifier": "media-4210015",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8a574dbc8c345c5a4a52d9fa4c93272e/media-4210015@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a77d63dd16bbb7363b855691b55294f2/media-4210015~dark@2x.png"
        }
      ]
    },
    "media-4238566": {
      "alt": "A screenshot depicting an example of a valid JSON Web Token. ",
      "identifier": "media-4238566",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9471d484d8ecb36f3b853891c276920d/media-4238566@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/36b6b52acca4da61129e2075987872ab/media-4238566~dark@2x.png"
        }
      ]
    },
    "media-4251167": {
      "alt": "A screenshot depicting an example of a valid Key ID used to generate a token.",
      "identifier": "media-4251167",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fdb0dc6b51ba64112c807b531447f462/media-4251167@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/abc2ce753b7c83b7b8a91d3ee0e1b282/media-4251167~dark@2x.png"
        }
      ]
    },
    "media-4251168": {
      "alt": "A screenshot of the details and metadata of a notification sent through the Push Notification Console.",
      "identifier": "media-4251168",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1734fcfb5424fd54c3aebed784f18f8c/media-4251168@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/16667e9b1c7cf2981a3604d805fde99c/media-4251168~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Remote-notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server",
        "doc://com.apple.usernotifications/documentation/UserNotifications/sending-push-notifications-using-command-line-tools"
      ],
      "title": "Remote notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Remote-notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/setting-up-a-remote-notification-server",
                "doc://com.apple.usernotifications/documentation/UserNotifications/sending-push-notifications-using-command-line-tools"
              ],
              "title": "Remote notifications"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/testing-notifications-using-the-push-notification-console"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotifications/testing-notifications-using-the-push-notification-console"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
