{
  "abstract": [
    {
      "text": "The sound played upon delivery of a notification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UNNotificationSound",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UNNotificationSound"
      }
    ],
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UNNotificationSound"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UNNotificationSound"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UNNotificationSound"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object when you want the system to play a specific sound when it delivers with your notification. To play the default system sound, create your sound object using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/default",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. If you want to play a custom sound, create a new sound object and specify the name of the audio file that you want to play.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For local notifications, assign the sound object to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNMutableNotificationContent/sound",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNMutableNotificationContent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. For a remote notification, assign the name of your sound file to the ",
              "type": "text"
            },
            {
              "code": "sound",
              "type": "codeVoice"
            },
            {
              "text": " key in the ",
              "type": "text"
            },
            {
              "code": "aps",
              "type": "codeVoice"
            },
            {
              "text": " dictionary. You can also use a notification service app extension to add a sound file to a notification shortly before delivery. In your extension, create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and add it to your notification content in the same way that you’d for a local notification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Audio files must already be on the user’s device before the system can play them. If you use a predefined set of sounds for your notifications, include the audio files in your app’s bundle. For all other sounds, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object looks only in the following locations:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "/Library/Sounds",
                      "type": "codeVoice"
                    },
                    {
                      "text": " directory of the app’s container directory.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "/Library/Sounds",
                      "type": "codeVoice"
                    },
                    {
                      "text": " directory of one of the app’s shared group container directories.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The main bundle of the current executable.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Prepare-Sound-Resources",
          "level": 3,
          "text": "Prepare Sound Resources",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system sound facility plays custom alert sounds, so they must be in one of the following audio data formats:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Linear PCM",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "MA4 (IMA/ADPCM)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "µLaw",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "aLaw",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can package the audio data in an ",
              "type": "text"
            },
            {
              "code": "aiff",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "wav",
              "type": "codeVoice"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "caf",
              "type": "codeVoice"
            },
            {
              "text": " file. Sound files must be less than 30 seconds in length. If the sound file is longer than 30 seconds, the system plays the default sound instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the ",
              "type": "text"
            },
            {
              "code": "afconvert",
              "type": "codeVoice"
            },
            {
              "text": " command-line tool to convert sounds. For example, to convert the system sound ",
              "type": "text"
            },
            {
              "code": "Submarine.aiff",
              "type": "codeVoice"
            },
            {
              "text": " to IMA4 audio in a CAF file, use the following command in Terminal:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "afconvert /System/Library/Sounds/Submarine.aiff ~/Desktop/sub.caf -d ima4 -f caff -v",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNMutableNotificationContent": {
      "abstract": [
        {
          "text": "The editable content for a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNMutableNotificationContent"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNMutableNotificationContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNMutableNotificationContent"
        }
      ],
      "role": "symbol",
      "title": "UNMutableNotificationContent",
      "type": "topic",
      "url": "/documentation/usernotifications/unmutablenotificationcontent"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNMutableNotificationContent/sound": {
      "abstract": [
        {
          "text": "The sound that plays when the system delivers the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UNNotificationSound",
          "text": "UNNotificationSound"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNMutableNotificationContent/sound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sound"
        }
      ],
      "role": "symbol",
      "title": "sound",
      "type": "topic",
      "url": "/documentation/usernotifications/unmutablenotificationcontent/sound"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationActionIcon": {
      "abstract": [
        {
          "text": "An icon associated with an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationActionIcon"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationActionIcon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationActionIcon"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationActionIcon",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationactionicon"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationAttachment": {
      "abstract": [
        {
          "text": "A media file associated with a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationAttachment"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationAttachment"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationAttachment",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationattachment"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationContent": {
      "abstract": [
        {
          "text": "The uneditable content of a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationContent"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContent"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContent",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationcontent"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationContentProviding": {
      "abstract": [
        {
          "text": "A protocol the system uses to provide context relevant to user notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationContentProviding"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationContentProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentProviding"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentProviding",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationcontentproviding"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound": {
      "abstract": [
        {
          "text": "The sound played upon delivery of a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationSound"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationSound"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationSound",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsound"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/criticalSoundNamed(_:)": {
      "abstract": [
        {
          "text": "Creates a custom sound object for critical alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "criticalSoundNamed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UNNotificationSoundName",
          "text": "UNNotificationSoundName"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/criticalSoundNamed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "criticalSoundNamed:"
        }
      ],
      "role": "symbol",
      "title": "criticalSoundNamed(_:)",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsound/criticalsoundnamed(_:)"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/criticalSoundNamed(_:withAudioVolume:)": {
      "abstract": [
        {
          "text": "Creates a custom sound object for critical alerts with the volume you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "criticalSoundNamed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UNNotificationSoundName",
          "text": "UNNotificationSoundName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withAudioVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/criticalSoundNamed(_:withAudioVolume:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "criticalSoundNamed:withAudioVolume:"
        }
      ],
      "role": "symbol",
      "title": "criticalSoundNamed(_:withAudioVolume:)",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsound/criticalsoundnamed(_:withaudiovolume:)"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/default": {
      "abstract": [
        {
          "text": "Returns an object representing the default sound for notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UNNotificationSound",
          "text": "UNNotificationSound"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultSound"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsound/default"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultCritical": {
      "abstract": [
        {
          "text": "The default sound used for critical alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultCritical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UNNotificationSound",
          "text": "UNNotificationSound"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultCritical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultCriticalSound"
        }
      ],
      "role": "symbol",
      "title": "defaultCritical",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsound/defaultcritical"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultCriticalSound(withAudioVolume:)": {
      "abstract": [
        {
          "text": "Creates a sound object that plays the default critical alert sound at the volume you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultCriticalSound"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAudioVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultCriticalSound(withAudioVolume:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultCriticalSoundWithAudioVolume:"
        }
      ],
      "role": "symbol",
      "title": "defaultCriticalSound(withAudioVolume:)",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsound/defaultcriticalsound(withaudiovolume:)"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultRingtone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultRingtone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UNNotificationSound",
          "text": "UNNotificationSound"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultRingtone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultRingtoneSound"
        }
      ],
      "role": "symbol",
      "title": "defaultRingtone",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsound/defaultringtone"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/init(named:)": {
      "abstract": [
        {
          "text": "Creates a sound object that represents a custom sound file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UNNotificationSoundName",
          "text": "UNNotificationSoundName"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/init(named:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "soundNamed:"
        }
      ],
      "role": "symbol",
      "title": "init(named:)",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsound/init(named:)"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/ringtoneSoundNamed(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ringtoneSoundNamed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UNNotificationSoundName",
          "text": "UNNotificationSoundName"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/ringtoneSoundNamed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ringtoneSoundNamed:"
        }
      ],
      "role": "symbol",
      "title": "ringtoneSoundNamed(_:)",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsound/ringtonesoundnamed(_:)"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSoundName": {
      "abstract": [
        {
          "text": "A string providing the name of a sound file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationSoundName"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSoundName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationSoundName"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationSoundName",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationsoundname"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification": {
      "abstract": [
        {
          "text": "Send notifications to the user’s device with a JSON payload.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/generating-a-remote-notification",
      "kind": "article",
      "role": "article",
      "title": "Generating a remote notification",
      "type": "topic",
      "url": "/documentation/usernotifications/generating-a-remote-notification"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/implementing-communication-notifications": {
      "abstract": [
        {
          "text": "Configure and display your app’s communication notifications by using intents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/implementing-communication-notifications",
      "kind": "article",
      "role": "article",
      "title": "Implementing communication notifications",
      "type": "topic",
      "url": "/documentation/usernotifications/implementing-communication-notifications"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notification-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/implementing-communication-notifications",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationContentProviding",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationActionIcon",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNMutableNotificationContent",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationContent",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationAttachment",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSoundName"
      ],
      "title": "Notification content"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Notification-Sounds",
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/default",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/init(named:)"
      ],
      "title": "Creating Notification Sounds"
    },
    {
      "anchor": "Getting-Critical-Sounds",
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultCritical",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultCriticalSound(withAudioVolume:)",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/criticalSoundNamed(_:)",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/criticalSoundNamed(_:withAudioVolume:)"
      ],
      "title": "Getting Critical Sounds"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultRingtone"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Type-Methods",
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/ringtoneSoundNamed(_:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UNNotificationSound"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.usernotifications/documentation/UserNotifications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Notification-Sounds",
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/default",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/init(named:)"
              ],
              "title": "Creating Notification Sounds"
            },
            {
              "anchor": "Getting-Critical-Sounds",
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultCritical",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultCriticalSound(withAudioVolume:)",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/criticalSoundNamed(_:)",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/criticalSoundNamed(_:withAudioVolume:)"
              ],
              "title": "Getting Critical Sounds"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/defaultRingtone"
              ],
              "title": "Type Properties"
            },
            {
              "anchor": "Type-Methods",
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSound/ringtoneSoundNamed(_:)"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Notification-content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/implementing-communication-notifications",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationContentProviding",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationActionIcon",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNMutableNotificationContent",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationContent",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationAttachment",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationSoundName"
              ],
              "title": "Notification content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UNNotificationSound"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1default/title",
          "value": "defaultSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1defaultCritical/title",
          "value": "defaultCriticalSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1defaultCritical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultCriticalSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1defaultCriticalSound(withAudioVolume:)/title",
          "value": "defaultCriticalSoundWithAudioVolume:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1defaultCriticalSound(withAudioVolume:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultCriticalSoundWithAudioVolume:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNMutableNotificationContent/title",
          "value": "UNMutableNotificationContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNMutableNotificationContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNMutableNotificationContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNMutableNotificationContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNMutableNotificationContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSoundName/title",
          "value": "UNNotificationSoundName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSoundName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSoundName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSoundName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSoundName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationContentProviding/title",
          "value": "UNNotificationContentProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationContentProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationContentProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1ringtoneSoundNamed(_:)/title",
          "value": "ringtoneSoundNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1ringtoneSoundNamed(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "ringtoneSoundNamed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationActionIcon/title",
          "value": "UNNotificationActionIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationActionIcon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationActionIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationActionIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationActionIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationAttachment/title",
          "value": "UNNotificationAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1criticalSoundNamed(_:withAudioVolume:)/title",
          "value": "criticalSoundNamed:withAudioVolume:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1criticalSoundNamed(_:withAudioVolume:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "criticalSoundNamed:withAudioVolume:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNMutableNotificationContent~1sound/title",
          "value": "sound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNMutableNotificationContent~1sound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationContent/title",
          "value": "UNNotificationContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1criticalSoundNamed(_:)/title",
          "value": "criticalSoundNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1criticalSoundNamed(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "criticalSoundNamed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound/title",
          "value": "UNNotificationSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1init(named:)/title",
          "value": "soundNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1init(named:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "soundNamed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1defaultRingtone/title",
          "value": "defaultRingtoneSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationSound~1defaultRingtone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultRingtoneSound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/unnotificationsound"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotifications/unnotificationsound"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
