{
  "abstract": [
    {
      "text": "Creates a 2D-depthwise convolution descriptor with given properties and default values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph",
        "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DOpDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DOpDescriptor/init(dataLayout:weightsLayout:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPSGraphDepthwiseConvolution2DOpDescriptor(cm)descriptorWithDataLayout:weightsLayout:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "dataLayout"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MPSGraphTensorNamedDataLayout",
        "text": "MPSGraphTensorNamedDataLayout"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "weightsLayout"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MPSGraphTensorNamedDataLayout",
        "text": "MPSGraphTensorNamedDataLayout"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Metal Performance Shaders Graph"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "descriptorWithDataLayout:weightsLayout:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(dataLayout:weightsLayout:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "dataLayout"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorNamedDataLayout",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MPSGraphTensorNamedDataLayout",
              "text": "MPSGraphTensorNamedDataLayout"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "weightsLayout"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorNamedDataLayout",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MPSGraphTensorNamedDataLayout",
              "text": "MPSGraphTensorNamedDataLayout"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "See ",
                  "type": "text"
                },
                {
                  "code": "dataLayout",
                  "type": "codeVoice"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "dataLayout"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "See ",
                  "type": "text"
                },
                {
                  "code": "weightsLayout",
                  "type": "codeVoice"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "weightsLayout"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The descriptor on autoreleasepool.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph": {
      "abstract": [
        {
          "text": "Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal Performance Shaders Graph",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DOpDescriptor": {
      "abstract": [
        {
          "text": "A class that defines the parameters for  a 2D-depthwise convolution operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSGraphDepthwiseConvolution2DOpDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DOpDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSGraphDepthwiseConvolution2DOpDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MPSGraphDepthwiseConvolution2DOpDescriptor",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraphdepthwiseconvolution2dopdescriptor"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DOpDescriptor/init(dataLayout:weightsLayout:)": {
      "abstract": [
        {
          "text": "Creates a 2D-depthwise convolution descriptor with given properties and default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "dataLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPSGraphTensorNamedDataLayout",
          "text": "MPSGraphTensorNamedDataLayout"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weightsLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPSGraphTensorNamedDataLayout",
          "text": "MPSGraphTensorNamedDataLayout"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DOpDescriptor/init(dataLayout:weightsLayout:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithDataLayout:weightsLayout:"
        }
      ],
      "role": "symbol",
      "title": "init(dataLayout:weightsLayout:)",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraphdepthwiseconvolution2dopdescriptor/init(datalayout:weightslayout:)"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorNamedDataLayout": {
      "abstract": [
        {
          "text": "The tensor layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSGraphTensorNamedDataLayout"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorNamedDataLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSGraphTensorNamedDataLayout"
        }
      ],
      "role": "symbol",
      "title": "MPSGraphTensorNamedDataLayout",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraphtensornameddatalayout"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "descriptorWithDataLayout:weightsLayout:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithDataLayout:weightsLayout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph",
                "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphDepthwiseConvolution2DOpDescriptor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "descriptorWithDataLayout:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorNamedDataLayout",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MPSGraphTensorNamedDataLayout",
                    "text": "MPSGraphTensorNamedDataLayout"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "dataLayout"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "weightsLayout:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorNamedDataLayout",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MPSGraphTensorNamedDataLayout",
                    "text": "MPSGraphTensorNamedDataLayout"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "weightsLayout"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "See ",
                        "type": "text"
                      },
                      {
                        "code": "dataLayout",
                        "type": "codeVoice"
                      },
                      {
                        "text": " property.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "dataLayout"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "See ",
                        "type": "text"
                      },
                      {
                        "code": "weightsLayout",
                        "type": "codeVoice"
                      },
                      {
                        "text": " property.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "weightsLayout"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The descriptor on autoreleasepool.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphDepthwiseConvolution2DOpDescriptor/title",
          "value": "MPSGraphDepthwiseConvolution2DOpDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphDepthwiseConvolution2DOpDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphDepthwiseConvolution2DOpDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphDepthwiseConvolution2DOpDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphDepthwiseConvolution2DOpDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphDepthwiseConvolution2DOpDescriptor~1init(dataLayout:weightsLayout:)/title",
          "value": "descriptorWithDataLayout:weightsLayout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphDepthwiseConvolution2DOpDescriptor~1init(dataLayout:weightsLayout:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithDataLayout:weightsLayout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensorNamedDataLayout/title",
          "value": "MPSGraphTensorNamedDataLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensorNamedDataLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphTensorNamedDataLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensorNamedDataLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphTensorNamedDataLayout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalperformanceshadersgraph/mpsgraphdepthwiseconvolution2dopdescriptor/init(datalayout:weightslayout:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalperformanceshadersgraph/mpsgraphdepthwiseconvolution2dopdescriptor/init(datalayout:weightslayout:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
