{
  "abstract": [
    {
      "text": "Returns the preferred orientation for presentation of the navigation controller, as determined by the delegate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationControllerPreferredInterfaceOrientationForPresentation(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UINavigationControllerDelegate(im)navigationControllerPreferredInterfaceOrientationForPresentation:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "navigationControllerPreferredInterfaceOrientationForPresentation"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UINavigationController",
        "text": "UINavigationController"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIInterfaceOrientation",
        "text": "UIInterfaceOrientation"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "navigationControllerPreferredInterfaceOrientationForPresentation:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "navigationControllerPreferredInterfaceOrientationForPresentation(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "navigationControllerPreferredInterfaceOrientationForPresentation"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "navigationController"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UINavigationController",
              "text": "UINavigationController"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIInterfaceOrientation",
              "text": "UIInterfaceOrientation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The navigation controller",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "navigationController"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The preferred orientation for presenting the navigation controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation": {
      "abstract": [
        {
          "text": "Constants that specify the orientation of the app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientation"
        }
      ],
      "role": "symbol",
      "title": "UIInterfaceOrientation",
      "type": "topic",
      "url": "/documentation/uikit/uiinterfaceorientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationController": {
      "abstract": [
        {
          "text": "A container view controller that defines a stack-based scheme for navigating hierarchical content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UINavigationController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINavigationController"
        }
      ],
      "role": "symbol",
      "title": "UINavigationController",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate": {
      "abstract": [
        {
          "text": "The interface for an object that serves as a navigation controller’s delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UINavigationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINavigationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UINavigationControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationController(_:animationControllerFor:from:to:)": {
      "abstract": [
        {
          "text": "Allows the delegate to return a noninteractive animator object for use during view controller transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationController",
          "text": "UINavigationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animationControllerFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationController",
          "text": "UINavigationController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UINavigationControllerOperation",
          "text": "Operation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerAnimatedTransitioning",
          "text": "UIViewControllerAnimatedTransitioning"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationController(_:animationControllerFor:from:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "navigationController:animationControllerForOperation:fromViewController:toViewController:"
        }
      ],
      "role": "symbol",
      "title": "navigationController(_:animationControllerFor:from:to:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationcontrollerdelegate/navigationcontroller(_:animationcontrollerfor:from:to:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationController(_:interactionControllerFor:)": {
      "abstract": [
        {
          "text": "Allows the delegate to return an interactive animator object for use during view controller transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationController",
          "text": "UINavigationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "interactionControllerFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerAnimatedTransitioning",
          "text": "UIViewControllerAnimatedTransitioning"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerInteractiveTransitioning",
          "text": "UIViewControllerInteractiveTransitioning"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationController(_:interactionControllerFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "navigationController:interactionControllerForAnimationController:"
        }
      ],
      "role": "symbol",
      "title": "navigationController(_:interactionControllerFor:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationcontrollerdelegate/navigationcontroller(_:interactioncontrollerfor:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationControllerPreferredInterfaceOrientationForPresentation(_:)": {
      "abstract": [
        {
          "text": "Returns the preferred orientation for presentation of the navigation controller, as determined by the delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationControllerPreferredInterfaceOrientationForPresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationController",
          "text": "UINavigationController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationControllerPreferredInterfaceOrientationForPresentation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "navigationControllerPreferredInterfaceOrientationForPresentation:"
        }
      ],
      "role": "symbol",
      "title": "navigationControllerPreferredInterfaceOrientationForPresentation(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationcontrollerdelegate/navigationcontrollerpreferredinterfaceorientationforpresentation(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationControllerSupportedInterfaceOrientations(_:)": {
      "abstract": [
        {
          "text": "Returns the complete set of supported interface orientations for the navigation controller, as determined by the delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationControllerSupportedInterfaceOrientations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationController",
          "text": "UINavigationController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientationMask",
          "text": "UIInterfaceOrientationMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationControllerSupportedInterfaceOrientations(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "navigationControllerSupportedInterfaceOrientations:"
        }
      ],
      "role": "symbol",
      "title": "navigationControllerSupportedInterfaceOrientations(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationcontrollerdelegate/navigationcontrollersupportedinterfaceorientations(_:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-custom-transition-animations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationController(_:animationControllerFor:from:to:)",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationController(_:interactionControllerFor:)",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationControllerSupportedInterfaceOrientations(_:)"
      ],
      "title": "Supporting custom transition animations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "navigationControllerPreferredInterfaceOrientationForPresentation:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "navigationControllerPreferredInterfaceOrientationForPresentation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-custom-transition-animations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationController(_:animationControllerFor:from:to:)",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationController(_:interactionControllerFor:)",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationControllerDelegate/navigationControllerSupportedInterfaceOrientations(_:)"
              ],
              "title": "Supporting custom transition animations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UIInterfaceOrientation",
                    "text": "UIInterfaceOrientation"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "navigationControllerPreferredInterfaceOrientationForPresentation:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UINavigationController",
                    "text": "UINavigationController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "navigationController"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The navigation controller",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "navigationController"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The preferred orientation for presenting the navigation controller.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate/title",
          "value": "UINavigationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController/title",
          "value": "UINavigationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation/title",
          "value": "UIInterfaceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate~1navigationControllerPreferredInterfaceOrientationForPresentation(_:)/title",
          "value": "navigationControllerPreferredInterfaceOrientationForPresentation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate~1navigationControllerPreferredInterfaceOrientationForPresentation(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "navigationControllerPreferredInterfaceOrientationForPresentation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate~1navigationController(_:animationControllerFor:from:to:)/title",
          "value": "navigationController:animationControllerForOperation:fromViewController:toViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate~1navigationController(_:animationControllerFor:from:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "navigationController:animationControllerForOperation:fromViewController:toViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate~1navigationController(_:interactionControllerFor:)/title",
          "value": "navigationController:interactionControllerForAnimationController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate~1navigationController(_:interactionControllerFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "navigationController:interactionControllerForAnimationController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate~1navigationControllerSupportedInterfaceOrientations(_:)/title",
          "value": "navigationControllerSupportedInterfaceOrientations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationControllerDelegate~1navigationControllerSupportedInterfaceOrientations(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "navigationControllerSupportedInterfaceOrientations:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uinavigationcontrollerdelegate/navigationcontrollerpreferredinterfaceorientationforpresentation(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uinavigationcontrollerdelegate/navigationcontrollerpreferredinterfaceorientationforpresentation(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
