{
  "abstract": [
    {
      "text": "Intializes an object for a rendering session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cinematic/documentation/Cinematic",
        "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-8yghc"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-8yghc/initWithCommandQueue:sessionAttributes:preferredTransform:quality:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNRenderingSession(im)initWithCommandQueue:sessionAttributes:preferredTransform:quality:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "initWithCommandQueue:sessionAttributes:preferredTransform:quality:"
      }
    ],
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithCommandQueue:sessionAttributes:preferredTransform:quality:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "initWithCommandQueue:sessionAttributes:preferredTransform:quality:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithCommandQueue:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)MTLCommandQueue",
              "text": "id<MTLCommandQueue>"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "commandQueue"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sessionAttributes:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSessionAttributes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CNRenderingSessionAttributes",
              "text": "CNRenderingSessionAttributes"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "sessionAttributes"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "preferredTransform:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGAffineTransform",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGAffineTransform",
              "text": "CGAffineTransform"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "preferredTransform"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "quality:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingQuality",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CNRenderingQuality",
              "text": "CNRenderingQuality"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "quality"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The command queue of a metal device that creates the command buffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "commandQueue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Rendering session attributes loaded from a Cinematic asset.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sessionAttributes"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The preferred transform of the rendered image for display purposes. Always the identity transform or a multiple of a 90ยบ rotation with no scaling.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "preferredTransform"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The quality of rendering desired for a session. Quality levels include thumbnail, preview, and three export quality levels. You can create more than one session for the same video with different quality levels.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "quality"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingQuality": {
      "abstract": [
        {
          "text": "The rendering quality, such as thumbnail, preview, export and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNRenderingQuality"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNRenderingQuality"
        }
      ],
      "role": "symbol",
      "title": "CNRenderingQuality",
      "type": "topic",
      "url": "/documentation/cinematic/cnrenderingquality"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-8yghc": {
      "abstract": [
        {
          "text": "An object representing the context in which rendering occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNRenderingSession"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-8yghc",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNRenderingSession",
      "type": "topic",
      "url": "/documentation/cinematic/cnrenderingsession-8yghc"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-8yghc/initWithCommandQueue:sessionAttributes:preferredTransform:quality:": {
      "abstract": [
        {
          "text": "Intializes an object for a rendering session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCommandQueue:sessionAttributes:preferredTransform:quality:"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSession-8yghc/initWithCommandQueue:sessionAttributes:preferredTransform:quality:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCommandQueue:sessionAttributes:preferredTransform:quality:"
        }
      ],
      "role": "symbol",
      "title": "initWithCommandQueue:sessionAttributes:preferredTransform:quality:",
      "type": "topic",
      "url": "/documentation/cinematic/cnrenderingsession-8yghc/initwithcommandqueue:sessionattributes:preferredtransform:quality:"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSessionAttributes": {
      "abstract": [
        {
          "text": "A structure for movie-wide attributes required for proper rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNRenderingSessionAttributes"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNRenderingSessionAttributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNRenderingSessionAttributes",
      "type": "topic",
      "url": "/documentation/cinematic/cnrenderingsessionattributes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGAffineTransform": {
      "abstract": [
        {
          "text": "An affine transformation matrix for use in drawing 2D graphics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGAffineTransform"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGAffineTransform",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGAffineTransform",
      "type": "topic",
      "url": "/documentation/corefoundation/cgaffinetransform"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNRenderingQuality/title",
          "value": "CNRenderingQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNRenderingQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNRenderingQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNRenderingQuality/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNRenderingQuality"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic/cnrenderingsession-8yghc/initwithcommandqueue:sessionattributes:preferredtransform:quality:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
