{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBox/setTitleWithMnemonic:","interfaceLanguage":"occ"},"sections":[],"abstract":[{"text":"Sets the title of the receiver with a character denoted as an access key.","type":"text"}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCell/setTitleWithMnemonic:"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBox/borderRect","doc://com.apple.appkit/documentation/AppKit/NSBox/boxType-swift.property","doc://com.apple.appkit/documentation/AppKit/NSBox/borderType","doc://com.apple.appkit/documentation/AppKit/NSBox/isTransparent","doc://com.apple.appkit/documentation/AppKit/NSBox/title","doc://com.apple.appkit/documentation/AppKit/NSBox/titleFont","doc://com.apple.appkit/documentation/AppKit/NSBox/titlePosition-swift.property","doc://com.apple.appkit/documentation/AppKit/NSBox/titleCell","doc://com.apple.appkit/documentation/AppKit/NSBox/titleRect"],"anchor":"Configuring-Boxes","generated":true,"title":"Configuring Boxes"}],"metadata":{"title":"setTitleWithMnemonic:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleWithMnemonic:"}],"roleHeading":"Instance Method","platforms":[{"deprecatedAt":"10.8","deprecated":false,"beta":false,"introducedAt":"10.0","unavailable":false,"name":"macOS"}],"modules":[{"name":"AppKit"}],"role":"symbol","externalID":"c:objc(cs)NSBox(im)setTitleWithMnemonic:","navigatorTitle":[{"kind":"identifier","text":"setTitleWithMnemonic:"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setTitleWithMnemonic:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"stringWithAmpersand","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"Mnemonics are not supported in macOS."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"By default, a box’s title is “Title.” The content view is not automatically resized, and the box is not marked for redisplay."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbox/settitlewithmnemonic:"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBox"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSBox/borderRect":{"url":"/documentation/appkit/nsbox/borderrect","kind":"symbol","abstract":[{"type":"text","text":"The rectangle in which the receiver’s border is drawn."}],"title":"borderRect","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"borderRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"borderRect","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/borderRect","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBox/titleRect":{"url":"/documentation/appkit/nsbox/titlerect","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/titleRect","navigatorTitle":[{"text":"titleRect","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"title":"titleRect","abstract":[{"text":"The rectangle in which the receiver’s title is drawn.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBox/titleFont":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSFont","preciseIdentifier":"c:objc(cs)NSFont","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The font object used to draw the receiver’s title."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/titleFont","navigatorTitle":[{"text":"titleFont","kind":"identifier"}],"title":"titleFont","url":"/documentation/appkit/nsbox/titlefont","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBox/borderType":{"url":"/documentation/appkit/nsbox/bordertype","deprecated":true,"kind":"symbol","abstract":[{"text":"The receiver’s border type.","type":"text"}],"title":"borderType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"borderType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSBorderType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSBorderType"}],"role":"symbol","navigatorTitle":[{"text":"borderType","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/borderType","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCell/setTitleWithMnemonic:":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/setTitleWithMnemonic:","title":"setTitleWithMnemonic:","navigatorTitle":[{"text":"setTitleWithMnemonic:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Sets the title of the receiver with one character in the string denoted as an access key.","type":"text"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"setTitleWithMnemonic:","kind":"identifier"}],"deprecated":true,"url":"/documentation/appkit/nscell/settitlewithmnemonic:"},"doc://com.apple.appkit/documentation/AppKit/NSBox/setTitleWithMnemonic:":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setTitleWithMnemonic:"}],"abstract":[{"type":"text","text":"Sets the title of the receiver with a character denoted as an access key."}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleWithMnemonic:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/setTitleWithMnemonic:","url":"/documentation/appkit/nsbox/settitlewithmnemonic:","title":"setTitleWithMnemonic:","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBox/titleCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/titleCell","title":"titleCell","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleCell","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}],"kind":"symbol","abstract":[{"text":"The cell used to display the receiver’s title.","type":"text"}],"url":"/documentation/appkit/nsbox/titlecell","role":"symbol","navigatorTitle":[{"text":"titleCell","kind":"identifier"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBox/titlePosition-swift.property":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/titlePosition-swift.property","navigatorTitle":[{"kind":"identifier","text":"titlePosition"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titlePosition"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSBox","kind":"typeIdentifier","text":"NSBox"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSTitlePosition","kind":"typeIdentifier","text":"TitlePosition"}],"kind":"symbol","abstract":[{"text":"A constant representing the title position.","type":"text"}],"type":"topic","title":"titlePosition","role":"symbol","url":"/documentation/appkit/nsbox/titleposition-swift.property"},"doc://com.apple.appkit/documentation/AppKit/NSBox/title":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/title","navigatorTitle":[{"text":"title","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","abstract":[{"text":"The receiver’s title.","type":"text"}],"type":"topic","title":"title","role":"symbol","url":"/documentation/appkit/nsbox/title"},"doc://com.apple.appkit/documentation/AppKit/NSBox/isTransparent":{"role":"symbol","url":"/documentation/appkit/nsbox/istransparent","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/isTransparent","title":"isTransparent","abstract":[{"type":"text","text":"A Boolean value that indicates whether the receiver is transparent."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"transparent"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTransparent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"title":"NSString","kind":"symbol","url":"/documentation/foundation/nsstring","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBox":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox","abstract":[{"text":"A stylized rectangular box with an optional title.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSBox"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSBox"}],"title":"NSBox","kind":"symbol","url":"/documentation/appkit/nsbox","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBox/boxType-swift.property":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"boxType"}],"url":"/documentation/appkit/nsbox/boxtype-swift.property","title":"boxType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/boxType-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"boxType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSBox","preciseIdentifier":"c:objc(cs)NSBox"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"BoxType","preciseIdentifier":"c:@E@NSBoxType"}],"abstract":[{"text":"The receiver’s box type.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1borderRect/title","op":"replace","value":"borderRect"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1borderRect/fragments","value":[{"kind":"identifier","text":"borderRect"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleRect/title","value":"titleRect","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleRect/fragments","value":[{"kind":"identifier","text":"titleRect"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleFont/title","value":"titleFont","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleFont/fragments","value":[{"kind":"identifier","text":"titleFont"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1borderType/title","value":"borderType","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1borderType/fragments","value":[{"text":"borderType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleCell/title","value":"titleCell","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleCell/fragments","value":[{"kind":"identifier","text":"titleCell"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titlePosition-swift.property/title","value":"titlePosition"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titlePosition-swift.property/fragments","value":[{"text":"titlePosition","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1title/title","value":"title"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1title/fragments","value":[{"text":"title","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1isTransparent/title","value":"transparent"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1isTransparent/fragments","value":[{"kind":"identifier","text":"transparent"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox/title","value":"NSBox"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox/fragments","value":[{"text":"NSBox","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox/navigatorTitle","value":[{"kind":"identifier","text":"NSBox"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1boxType-swift.property/title","value":"boxType"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1boxType-swift.property/fragments","value":[{"kind":"identifier","text":"boxType"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}