{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titlePosition"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox","preciseIdentifier":"c:objc(cs)NSBox","kind":"typeIdentifier","text":"NSBox"},{"kind":"text","text":"."},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/TitlePosition-swift.enum","preciseIdentifier":"c:@E@NSTitlePosition","kind":"typeIdentifier","text":"TitlePosition"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"A constant representing the position of the receiver’s title. See ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/TitlePosition-swift.enum","isActive":true,"type":"reference"},{"text":" for a list of these constants. If the new title position changes the size of the box’s border area, the content view is resized to absorb the difference, and the box is marked as needing redisplay.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["/documentation/appkit/nsbox/titleposition-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsbox/titleposition-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBox"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBox/titlePosition-swift.property","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Configuring Boxes","anchor":"Configuring-Boxes","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBox/borderRect","doc://com.apple.appkit/documentation/AppKit/NSBox/boxType-swift.property","doc://com.apple.appkit/documentation/AppKit/NSBox/borderType","doc://com.apple.appkit/documentation/AppKit/NSBox/isTransparent","doc://com.apple.appkit/documentation/AppKit/NSBox/title","doc://com.apple.appkit/documentation/AppKit/NSBox/titleFont","doc://com.apple.appkit/documentation/AppKit/NSBox/titleCell","doc://com.apple.appkit/documentation/AppKit/NSBox/titleRect"]}],"metadata":{"modules":[{"name":"AppKit"}],"platforms":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"title":"titlePosition","externalID":"c:objc(cs)NSBox(py)titlePosition","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"titlePosition","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titlePosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSBox","preciseIdentifier":"c:objc(cs)NSBox","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"TitlePosition","preciseIdentifier":"c:@E@NSTitlePosition","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"A constant representing the title position."}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSBox/title":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/title","navigatorTitle":[{"text":"title","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","abstract":[{"text":"The receiver’s title.","type":"text"}],"type":"topic","title":"title","role":"symbol","url":"/documentation/appkit/nsbox/title"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBox/borderType":{"url":"/documentation/appkit/nsbox/bordertype","deprecated":true,"kind":"symbol","abstract":[{"text":"The receiver’s border type.","type":"text"}],"title":"borderType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"borderType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSBorderType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSBorderType"}],"role":"symbol","navigatorTitle":[{"text":"borderType","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/borderType","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBox/titleFont":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSFont","preciseIdentifier":"c:objc(cs)NSFont","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The font object used to draw the receiver’s title."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/titleFont","navigatorTitle":[{"text":"titleFont","kind":"identifier"}],"title":"titleFont","url":"/documentation/appkit/nsbox/titlefont","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBox":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox","abstract":[{"text":"A stylized rectangular box with an optional title.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSBox"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSBox"}],"title":"NSBox","kind":"symbol","url":"/documentation/appkit/nsbox","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBox/titleCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/titleCell","title":"titleCell","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleCell","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"}],"kind":"symbol","abstract":[{"text":"The cell used to display the receiver’s title.","type":"text"}],"url":"/documentation/appkit/nsbox/titlecell","role":"symbol","navigatorTitle":[{"text":"titleCell","kind":"identifier"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBox/TitlePosition-swift.enum":{"role":"symbol","type":"topic","title":"NSBox.TitlePosition","url":"/documentation/appkit/nsbox/titleposition-swift.enum","navigatorTitle":[{"text":"TitlePosition","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/TitlePosition-swift.enum","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TitlePosition","kind":"identifier"}],"abstract":[{"text":"Specify the location of a box’s title with respect to its border.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBox/boxType-swift.property":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"boxType"}],"url":"/documentation/appkit/nsbox/boxtype-swift.property","title":"boxType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/boxType-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"boxType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSBox","preciseIdentifier":"c:objc(cs)NSBox"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"BoxType","preciseIdentifier":"c:@E@NSBoxType"}],"abstract":[{"text":"The receiver’s box type.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBox/borderRect":{"url":"/documentation/appkit/nsbox/borderrect","kind":"symbol","abstract":[{"type":"text","text":"The rectangle in which the receiver’s border is drawn."}],"title":"borderRect","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"borderRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"borderRect","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/borderRect","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBox/isTransparent":{"role":"symbol","url":"/documentation/appkit/nsbox/istransparent","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/isTransparent","title":"isTransparent","abstract":[{"type":"text","text":"A Boolean value that indicates whether the receiver is transparent."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"transparent"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTransparent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.apple.appkit/documentation/AppKit/NSBox/titleRect":{"url":"/documentation/appkit/nsbox/titlerect","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/titleRect","navigatorTitle":[{"text":"titleRect","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"title":"titleRect","abstract":[{"text":"The rectangle in which the receiver’s title is drawn.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSBox/setTitleWithMnemonic:":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setTitleWithMnemonic:"}],"abstract":[{"type":"text","text":"Sets the title of the receiver with a character denoted as an access key."}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleWithMnemonic:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/setTitleWithMnemonic:","url":"/documentation/appkit/nsbox/settitlewithmnemonic:","title":"setTitleWithMnemonic:","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBox/titlePosition-swift.property":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/titlePosition-swift.property","navigatorTitle":[{"kind":"identifier","text":"titlePosition"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titlePosition"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSBox","kind":"typeIdentifier","text":"NSBox"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSTitlePosition","kind":"typeIdentifier","text":"TitlePosition"}],"kind":"symbol","abstract":[{"text":"A constant representing the title position.","type":"text"}],"type":"topic","title":"titlePosition","role":"symbol","url":"/documentation/appkit/nsbox/titleposition-swift.property"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","path":"/metadata/title","value":"titlePosition"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"titlePosition","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBox"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBox/borderRect","doc://com.apple.appkit/documentation/AppKit/NSBox/boxType-swift.property","doc://com.apple.appkit/documentation/AppKit/NSBox/borderType","doc://com.apple.appkit/documentation/AppKit/NSBox/isTransparent","doc://com.apple.appkit/documentation/AppKit/NSBox/title","doc://com.apple.appkit/documentation/AppKit/NSBox/titleFont","doc://com.apple.appkit/documentation/AppKit/NSBox/setTitleWithMnemonic:","doc://com.apple.appkit/documentation/AppKit/NSBox/titleCell","doc://com.apple.appkit/documentation/AppKit/NSBox/titleRect"],"generated":true,"anchor":"Configuring-Boxes","title":"Configuring Boxes"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTitlePosition","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBox/TitlePosition-swift.enum","text":"NSTitlePosition"},{"kind":"text","text":" "},{"kind":"identifier","text":"titlePosition"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1title/title","value":"title"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1title/fragments","value":[{"text":"title","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1borderType/title","value":"borderType"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1borderType/fragments","value":[{"text":"borderType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleFont/title","value":"titleFont"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleFont/fragments","value":[{"text":"titleFont","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox/title","value":"NSBox"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox/fragments","value":[{"kind":"identifier","text":"NSBox"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox/navigatorTitle","value":[{"kind":"identifier","text":"NSBox"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleCell/title","value":"titleCell"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleCell/fragments","value":[{"text":"titleCell","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1TitlePosition-swift.enum/title","value":"NSTitlePosition"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1TitlePosition-swift.enum/fragments","value":[{"text":"NSTitlePosition","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1TitlePosition-swift.enum/navigatorTitle","value":[{"text":"NSTitlePosition","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1boxType-swift.property/title","value":"boxType"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1boxType-swift.property/fragments","value":[{"text":"boxType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1borderRect/title","value":"borderRect"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1borderRect/fragments","value":[{"kind":"identifier","text":"borderRect"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1isTransparent/title","value":"transparent"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1isTransparent/fragments","value":[{"kind":"identifier","text":"transparent"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleRect/title","value":"titleRect"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titleRect/fragments","value":[{"text":"titleRect","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titlePosition-swift.property/title","value":"titlePosition"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBox~1titlePosition-swift.property/fragments","value":[{"text":"titlePosition","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}