{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/notDetermined"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EPDeveloperToolStatus@EPDeveloperToolStatusNotDetermined",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notDetermined"
      }
    ],
    "modules": [
      {
        "name": "Execution Policy"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EPDeveloperToolStatusNotDetermined"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "EPDeveloperToolStatus.notDetermined"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notDetermined"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy": {
      "abstract": [
        {
          "text": "Provide functionality so developer tools can manage execution policy exceptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy",
      "kind": "symbol",
      "role": "collection",
      "title": "Execution Policy",
      "type": "topic",
      "url": "/documentation/executionpolicy"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EPDeveloperToolStatus"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPDeveloperToolStatus"
        }
      ],
      "role": "symbol",
      "title": "EPDeveloperToolStatus",
      "type": "topic",
      "url": "/documentation/executionpolicy/epdevelopertoolstatus"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/authorized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPDeveloperToolStatusAuthorized"
        }
      ],
      "role": "symbol",
      "title": "EPDeveloperToolStatus.authorized",
      "type": "topic",
      "url": "/documentation/executionpolicy/epdevelopertoolstatus/authorized"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/denied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPDeveloperToolStatusDenied"
        }
      ],
      "role": "symbol",
      "title": "EPDeveloperToolStatus.denied",
      "type": "topic",
      "url": "/documentation/executionpolicy/epdevelopertoolstatus/denied"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/notDetermined": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPDeveloperToolStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "EPDeveloperToolStatus.notDetermined",
      "type": "topic",
      "url": "/documentation/executionpolicy/epdevelopertoolstatus/notdetermined"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/restricted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPDeveloperToolStatusRestricted"
        }
      ],
      "role": "symbol",
      "title": "EPDeveloperToolStatus.restricted",
      "type": "topic",
      "url": "/documentation/executionpolicy/epdevelopertoolstatus/restricted"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/authorized",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/denied",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/restricted"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EPDeveloperToolStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperToolStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy",
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/authorized",
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/denied",
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus/restricted"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "EPDeveloperToolStatusNotDetermined"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus/title",
          "value": "EPDeveloperToolStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperToolStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperToolStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus~1notDetermined/title",
          "value": "EPDeveloperToolStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperToolStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus~1denied/title",
          "value": "EPDeveloperToolStatusDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperToolStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus~1authorized/title",
          "value": "EPDeveloperToolStatusAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperToolStatusAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus~1restricted/title",
          "value": "EPDeveloperToolStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperToolStatusRestricted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/executionpolicy/epdevelopertoolstatus/notdetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/executionpolicy/epdevelopertoolstatus/notdetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
