{
  "abstract": [
    {
      "text": "A Boolean indicating whether to enable or disable the defroster.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/enable-8tf0i"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INSetDefrosterSettingsInCarIntent(py)enable",
    "fragments": [
      {
        "kind": "identifier",
        "text": "enable"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "enable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "atomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "enable"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "enable"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the defroster settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetDefrosterSettingsInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetDefrosterSettingsInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetDefrosterSettingsInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/defroster": {
      "abstract": [
        {
          "text": "The defroster to enable or disable.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defroster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCarDefroster",
          "text": "INCarDefroster"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/defroster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defroster"
        }
      ],
      "role": "symbol",
      "title": "defroster",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintent/defroster"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/enable-8tf0i": {
      "abstract": [
        {
          "text": "A Boolean indicating whether to enable or disable the defroster.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "enable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/enable-8tf0i",
      "kind": "symbol",
      "role": "symbol",
      "title": "enable",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintent/enable-8tf0i"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Details-About-the-Defroster-Settings-to-Set",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/defroster"
      ],
      "title": "Getting Details About the Defroster Settings to Set"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/title",
          "value": "INSetDefrosterSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetDefrosterSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetDefrosterSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent~1defroster/title",
          "value": "defroster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent~1defroster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defroster"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insetdefrostersettingsincarintent/enable-8tf0i"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
