{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/intents/insetdefrostersettingsincarintent/init(enable:defroster:carname:)"]}],"abstract":[{"type":"text","text":"Initializes the intent object with the specified defroster information."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/init(enable:defroster:carName:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sirikit/documentation/Intents","doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent"]]},"metadata":{"platforms":[{"deprecatedAt":"15.0","deprecated":false,"message":"INSetDefrosterSettingsInCarIntent is deprecated. There is no replacement.","introducedAt":"12.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecatedAt":"15.0","beta":false,"deprecated":false,"message":"INSetDefrosterSettingsInCarIntent is deprecated. There is no replacement.","name":"iPadOS","unavailable":false,"introducedAt":"12.0"},{"deprecatedAt":"8.0","beta":false,"deprecated":false,"message":"INSetDefrosterSettingsInCarIntent is deprecated. There is no replacement.","name":"watchOS","unavailable":false,"introducedAt":"3.2"}],"symbolKind":"init","modules":[{"name":"Intents"}],"role":"symbol","externalID":"s:So33INSetDefrosterSettingsInCarIntentC7IntentsE6enable9defroster7carNameABSbSg_So05INCarB0VSo17INSpeakableStringCSgtcfc","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"defroster"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INCarDefroster","preciseIdentifier":"c:@E@INCarDefroster"},{"kind":"text","text":", "},{"kind":"externalParam","text":"carName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INSpeakableString","preciseIdentifier":"c:objc(cs)INSpeakableString"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","extendedModule":"Intents","title":"init(enable:defroster:carName:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"enable","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"defroster","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.sirikit/documentation/Intents/INCarDefroster","text":"INCarDefroster","preciseIdentifier":"c:@E@INCarDefroster","kind":"typeIdentifier"},{"text":" = .unknown, ","kind":"text"},{"text":"carName","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.sirikit/documentation/Intents/INSpeakableString","text":"INSpeakableString","preciseIdentifier":"c:objc(cs)INSpeakableString","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"},{"parameters":[{"name":"enable","content":[{"inlineContent":[{"type":"text","text":"A Boolean value indicating whether to enable or disable the defroster. Specify "},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":" to turn the defroster on or "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":" to turn it off."}],"type":"paragraph"}]},{"name":"defroster","content":[{"inlineContent":[{"type":"text","text":"The defroster to enable or disable."}],"type":"paragraph"}]},{"name":"carName","content":[{"inlineContent":[{"text":"The name of the car to apply the defroster setting to.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An initialized intent object or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the object could not be created."}]}],"kind":"content"},{"content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Normally, you don’t create instances of this class yourself. Instead, Siri creates instances when the user asks to change the vehicle’s defroster settings. However, you can use this method during testing to create intent objects in order to validate your intent handling code paths.","type":"text"}]}],"kind":"content"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"This intent is no longer available. You may define a custom intent instead. For more information, see "},{"isActive":true,"identifier":"https://developer.apple.com/support/deprecated-sirikit-intent-domains","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.sirikit/documentation/Intents/INCarDefroster":{"abstract":[{"type":"text","text":"Constants indicating the defroster type."}],"navigatorTitle":[{"kind":"identifier","text":"INCarDefroster"}],"kind":"symbol","role":"symbol","url":"/documentation/intents/incardefroster","identifier":"doc://com.apple.sirikit/documentation/Intents/INCarDefroster","type":"topic","title":"INCarDefroster","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"INCarDefroster"}],"deprecated":true},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/init(enable:defroster:carName:)":{"url":"/documentation/intents/insetdefrostersettingsincarintent/init(enable:defroster:carname:)","title":"init(enable:defroster:carName:)","role":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enable"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"defroster","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"INCarDefroster","preciseIdentifier":"c:@E@INCarDefroster","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"carName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INSpeakableString","preciseIdentifier":"c:objc(cs)INSpeakableString"},{"kind":"text","text":"?)"}],"kind":"symbol","deprecated":true,"identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/init(enable:defroster:carName:)","abstract":[{"type":"text","text":"Initializes the intent object with the specified defroster information."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"identifier":"doc://com.externally.resolved.symbol/s:Sb","type":"topic","title":"Bool","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"url":"/documentation/Swift/Bool"},"doc://com.apple.documentation/documentation/swift/true":{"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","title":"true"},"https://developer.apple.com/support/deprecated-sirikit-intent-domains":{"titleInlineContent":[{"text":"Deprecated SiriKit Intent Domains","type":"text"}],"identifier":"https://developer.apple.com/support/deprecated-sirikit-intent-domains","url":"https://developer.apple.com/support/deprecated-sirikit-intent-domains","type":"link","title":"Deprecated SiriKit Intent Domains"},"doc://com.apple.sirikit/documentation/Intents":{"role":"collection","identifier":"doc://com.apple.sirikit/documentation/Intents","url":"/documentation/intents","type":"topic","title":"Intents","abstract":[{"type":"text","text":"Empower people to customize interactions for your app on their device."}],"kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A false value."}],"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"topic","title":"false","url":"/documentation/swift/false"},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent":{"abstract":[{"text":"A request to change the defroster settings in a CarPlay-enabled vehicle.","type":"text"}],"type":"topic","identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntent"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntent"}],"role":"symbol","deprecated":true,"url":"/documentation/intents/insetdefrostersettingsincarintent","title":"INSetDefrosterSettingsInCarIntent"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.sirikit/documentation/Intents/INSpeakableString":{"type":"topic","url":"/documentation/intents/inspeakablestring","title":"INSpeakableString","identifier":"doc://com.apple.sirikit/documentation/Intents/INSpeakableString","navigatorTitle":[{"kind":"identifier","text":"INSpeakableString"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"INSpeakableString"}],"abstract":[{"text":"A custom phrase to be resolved by an Intents extension.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"INCarDefroster","path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarDefroster/title"},{"op":"replace","value":[{"kind":"identifier","text":"INCarDefroster"}],"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarDefroster/fragments"},{"op":"replace","value":[{"text":"INCarDefroster","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarDefroster/navigatorTitle"},{"op":"replace","value":"INSetDefrosterSettingsInCarIntent","path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/title"},{"op":"replace","value":[{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntent"}],"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntent"}],"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/navigatorTitle"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakableString/title","op":"replace","value":"INSpeakableString"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakableString/fragments","op":"replace","value":[{"text":"INSpeakableString","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakableString/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"INSpeakableString"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}