{"sections":[],"abstract":[{"type":"text","text":"Runs the pairing panel in a modal session to allow the user to select a Bluetooth device."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"runModal"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","text":"Int32"}],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"Returns kIOBluetoothUISuccess if a successful, validated device selection was made by the user and that device successfully paired. Returns kIOBluetoothUIUserCanceledErr if the user cancelled the panel. These return values are the same as NSRunStoppedResponse and NSRunAbortedResponse respectively. They are the standard values used in a modal session.","type":"text"}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The controller will use the panel attributes to filter what devices the user sees. The allowed UUIDs will be used to validate the selection the user makes. Only when a selection has been validated (or the panel cancelled) and the device paired, will this method return."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"NOTE: This method is only available in macOS 10.2.4 (Bluetooth v1.1) or later."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/runModal()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController"]]},"seeAlsoSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/addAllowedUUID(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/addAllowedUUIDArray(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/clearAllowedUUIDs()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getDescriptionText()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getOptions()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getPrompt()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getResults()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getSearchAttributes()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getTitle()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setDescriptionText(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setOptions(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setPrompt(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setSearchAttributes(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setTitle(_:)"],"generated":true}],"variants":[{"paths":["/documentation/iobluetoothui/iobluetoothpairingcontroller/runmodal()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/iobluetoothui/iobluetoothpairingcontroller/runmodal()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[{"unavailable":false,"introducedAt":"10.2","deprecated":false,"name":"macOS","beta":false}],"externalID":"c:objc(cs)IOBluetoothPairingController(im)runModal","title":"runModal()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"runModal"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"modules":[{"name":"IOBluetooth UI"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"runModal"}]},"kind":"symbol","references":{"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/addAllowedUUIDArray(_:)":{"abstract":[{"text":"Adds an array of UUIDs to the list of UUIDs that are used to validate the user’s selection.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAllowedUUIDArray","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"title":"addAllowedUUIDArray(_:)","role":"symbol","identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/addAllowedUUIDArray(_:)","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/addalloweduuidarray(_:)","navigatorTitle":[{"text":"addAllowedUUIDArray:","kind":"identifier"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"url":"/documentation/Swift/Int32","kind":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int32","kind":"identifier"}],"abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","role":"symbol","type":"topic","title":"Int32"},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getSearchAttributes()":{"abstract":[{"text":"Returns the search attributes that control the panel’s search/inquiry behavior.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSearchAttributes"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@IOBluetoothDeviceSearchAttributes","kind":"typeIdentifier","text":"IOBluetoothDeviceSearchAttributes"},{"kind":"text","text":">!"}],"title":"getSearchAttributes()","role":"symbol","identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getSearchAttributes()","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/getsearchattributes()","navigatorTitle":[{"kind":"identifier","text":"getSearchAttributes"}],"type":"topic"},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setDescriptionText(_:)":{"abstract":[{"text":"Sets the description text that appears in the device selector panel.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDescriptionText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"title":"setDescriptionText(_:)","role":"symbol","identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setDescriptionText(_:)","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/setdescriptiontext(_:)","navigatorTitle":[{"text":"setDescriptionText:","kind":"identifier"}],"type":"topic"},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/addAllowedUUID(_:)":{"abstract":[{"text":"Adds a UUID to the list of UUIDs that are used to validate the user’s selection.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAllowedUUID"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)IOBluetoothSDPUUID","kind":"typeIdentifier","text":"IOBluetoothSDPUUID"},{"kind":"text","text":"!)"}],"title":"addAllowedUUID(_:)","role":"symbol","identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/addAllowedUUID(_:)","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/addalloweduuid(_:)","navigatorTitle":[{"kind":"identifier","text":"addAllowedUUID:"}],"type":"topic"},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setSearchAttributes(_:)":{"navigatorTitle":[{"text":"setSearchAttributes:","kind":"identifier"}],"identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setSearchAttributes(_:)","title":"setSearchAttributes(_:)","kind":"symbol","type":"topic","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/setsearchattributes(_:)","abstract":[{"type":"text","text":"Sets the search attributes that control the panel’s search/inquiry behavior."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSearchAttributes","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@S@IOBluetoothDeviceSearchAttributes","text":"IOBluetoothDeviceSearchAttributes","kind":"typeIdentifier"},{"text":">!)","kind":"text"}]},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getTitle()":{"navigatorTitle":[{"text":"getTitle","kind":"identifier"}],"identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getTitle()","title":"getTitle()","kind":"symbol","type":"topic","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/gettitle()","abstract":[{"type":"text","text":"Returns the title of the device selector panel."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTitle","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getResults()":{"navigatorTitle":[{"text":"getResults","kind":"identifier"}],"identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getResults()","title":"getResults()","kind":"symbol","type":"topic","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/getresults()","abstract":[{"type":"text","text":"Returns an NSArray of the devices that were paired."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getResults","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}]},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setOptions(_:)":{"navigatorTitle":[{"text":"setOptions:","kind":"identifier"}],"identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setOptions(_:)","title":"setOptions(_:)","kind":"symbol","type":"topic","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/setoptions(_:)","abstract":[{"type":"text","text":"Sets the option bits that control the panel’s behavior."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOptions","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@IOBluetoothServiceBrowserControllerOptions","text":"IOBluetoothServiceBrowserControllerOptions","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","type":"topic"},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getDescriptionText()":{"abstract":[{"text":"Returns the description text that appears in the device selector panel.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getDescriptionText","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"title":"getDescriptionText()","role":"symbol","identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getDescriptionText()","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/getdescriptiontext()","navigatorTitle":[{"text":"getDescriptionText","kind":"identifier"}],"type":"topic"},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI":{"abstract":[{"text":"Present an interface through which users can pair their devices with other Bluetooth devices.","type":"text"}],"kind":"symbol","title":"IOBluetooth UI","role":"collection","identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI","url":"/documentation/iobluetoothui","type":"topic"},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setTitle(_:)":{"abstract":[{"text":"Sets the title of the panel when not run as a sheet.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitle"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!)"}],"title":"setTitle(_:)","role":"symbol","identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setTitle(_:)","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/settitle(_:)","navigatorTitle":[{"kind":"identifier","text":"setTitle:"}],"type":"topic"},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getOptions()":{"navigatorTitle":[{"text":"getOptions","kind":"identifier"}],"identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getOptions()","title":"getOptions()","kind":"symbol","type":"topic","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/getoptions()","abstract":[{"type":"text","text":"Returns the option bits that control the panel’s behavior."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getOptions","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@T@IOBluetoothServiceBrowserControllerOptions","text":"IOBluetoothServiceBrowserControllerOptions","kind":"typeIdentifier"}]},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getPrompt()":{"navigatorTitle":[{"text":"getPrompt","kind":"identifier"}],"identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getPrompt()","title":"getPrompt()","kind":"symbol","type":"topic","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/getprompt()","abstract":[{"type":"text","text":"Returns the title of the default/select button in the device selector panel."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getPrompt","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController":{"abstract":[{"text":"A NSWindowController subclass to display a window to initiate pairing to other bluetooth devices.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOBluetoothPairingController","kind":"identifier"}],"title":"IOBluetoothPairingController","role":"symbol","identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller","navigatorTitle":[{"text":"IOBluetoothPairingController","kind":"identifier"}],"type":"topic"},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/clearAllowedUUIDs()":{"abstract":[{"text":"Resets the controller back to the default state where it will accept any device the user selects.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearAllowedUUIDs","kind":"identifier"},{"text":"()","kind":"text"}],"title":"clearAllowedUUIDs()","role":"symbol","identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/clearAllowedUUIDs()","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/clearalloweduuids()","navigatorTitle":[{"text":"clearAllowedUUIDs","kind":"identifier"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","kind":"symbol","type":"topic","url":"/documentation/Swift/MainActor","abstract":[{"type":"text","text":"A singleton actor whose executor is equivalent to the main dispatch queue."}],"role":"symbol","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}]},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/runModal()":{"abstract":[{"text":"Runs the pairing panel in a modal session to allow the user to select a Bluetooth device.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"runModal"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"title":"runModal()","role":"symbol","identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/runModal()","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/runmodal()","navigatorTitle":[{"kind":"identifier","text":"runModal"}],"type":"topic"},"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setPrompt(_:)":{"navigatorTitle":[{"text":"setPrompt:","kind":"identifier"}],"identifier":"doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setPrompt(_:)","title":"setPrompt(_:)","kind":"symbol","type":"topic","url":"/documentation/iobluetoothui/iobluetoothpairingcontroller/setprompt(_:)","abstract":[{"type":"text","text":"Sets the title of the default/select button in the device selector panel."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPrompt","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!)","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"10.2","name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"runModal","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"runModal","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/addAllowedUUID(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/addAllowedUUIDArray(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/clearAllowedUUIDs()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getDescriptionText()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getOptions()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getPrompt()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getResults()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getSearchAttributes()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/getTitle()","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setDescriptionText(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setOptions(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setPrompt(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setSearchAttributes(_:)","doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController/setTitle(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"int","kind":"typeIdentifier","preciseIdentifier":"c:I"},{"text":") ","kind":"text"},{"text":"runModal","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"Returns kIOBluetoothUISuccess if a successful, validated device selection was made by the user and that device successfully paired. Returns kIOBluetoothUIUserCanceledErr if the user cancelled the panel. These return values are the same as NSRunStoppedResponse and NSRunAbortedResponse respectively. They are the standard values used in a modal session."}],"type":"paragraph"}]},"path":"/primaryContentSections/1"},{"op":"replace","value":"addAllowedUUIDArray:","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1addAllowedUUIDArray(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addAllowedUUIDArray:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1addAllowedUUIDArray(_:)/fragments"},{"op":"replace","value":"getSearchAttributes","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getSearchAttributes()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSearchAttributes"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getSearchAttributes()/fragments"},{"op":"replace","value":"setDescriptionText:","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1setDescriptionText(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setDescriptionText:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1setDescriptionText(_:)/fragments"},{"op":"replace","value":"addAllowedUUID:","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1addAllowedUUID(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addAllowedUUID:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1addAllowedUUID(_:)/fragments"},{"op":"replace","value":"setSearchAttributes:","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1setSearchAttributes(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setSearchAttributes:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1setSearchAttributes(_:)/fragments"},{"op":"replace","value":"getTitle","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getTitle()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getTitle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getTitle()/fragments"},{"op":"replace","value":"getResults","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getResults()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getResults","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getResults()/fragments"},{"op":"replace","value":"setOptions:","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1setOptions(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOptions:"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1setOptions(_:)/fragments"},{"op":"replace","value":"getDescriptionText","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getDescriptionText()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getDescriptionText","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getDescriptionText()/fragments"},{"op":"replace","value":"setTitle:","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1setTitle(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitle:"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1setTitle(_:)/fragments"},{"op":"replace","value":"getOptions","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getOptions()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getOptions"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getOptions()/fragments"},{"op":"replace","value":"getPrompt","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getPrompt()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getPrompt","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1getPrompt()/fragments"},{"op":"replace","value":"IOBluetoothPairingController","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController/title"},{"op":"replace","value":[{"kind":"identifier","text":"IOBluetoothPairingController"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController/fragments"},{"op":"replace","value":[{"text":"IOBluetoothPairingController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController/navigatorTitle"},{"op":"replace","value":"clearAllowedUUIDs","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1clearAllowedUUIDs()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"clearAllowedUUIDs","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1clearAllowedUUIDs()/fragments"},{"op":"replace","value":"runModal","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1runModal()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"runModal"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1runModal()/fragments"},{"op":"replace","value":"setPrompt:","path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1setPrompt(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setPrompt:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController~1setPrompt(_:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}