{
  "abstract": [
    {
      "text": "Notifies the JavaScriptCore virtual machine of an external object relationship.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine/addManagedReference(_:withOwner:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)JSVirtualMachine(im)addManagedReference:withOwner:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "addManagedReference"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "withOwner"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "addManagedReference:withOwner:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "addManagedReference(_:withOwner:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "addManagedReference"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "object"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "withOwner"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "owner"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The object to be referenced by the JavaScript memory management graph.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "object"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The other object responsible for the lifetime of the reference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "owner"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to make the JavaScript runtime aware of arbitrary external Objective-C or Swift object graphs. The runtime can then use this information to retain any JavaScript values that are referenced from somewhere in said object graph.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For correct behavior, clients must make their external object graphs reachable from within the JavaScript runtime. If an Objective-C or Swift object is reachable from within the JavaScript runtime, all managed references transitively reachable from it as recorded using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine/addManagedReference(_:withOwner:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method are scanned by the garbage collector.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine": {
      "abstract": [
        {
          "text": "A self-contained environment for JavaScript execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSVirtualMachine"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSVirtualMachine"
        }
      ],
      "role": "symbol",
      "title": "JSVirtualMachine",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvirtualmachine"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine/addManagedReference(_:withOwner:)": {
      "abstract": [
        {
          "text": "Notifies the JavaScriptCore virtual machine of an external object relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addManagedReference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "withOwner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine/addManagedReference(_:withOwner:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addManagedReference:withOwner:"
        }
      ],
      "role": "symbol",
      "title": "addManagedReference(_:withOwner:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvirtualmachine/addmanagedreference(_:withowner:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine/removeManagedReference(_:withOwner:)": {
      "abstract": [
        {
          "text": "Notifies the JavaScriptCore virtual machine that a previously registered object relationship no longer exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeManagedReference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "withOwner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine/removeManagedReference(_:withOwner:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeManagedReference:withOwner:"
        }
      ],
      "role": "symbol",
      "title": "removeManagedReference(_:withOwner:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvirtualmachine/removemanagedreference(_:withowner:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Memory-for-Bridged-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine/removeManagedReference(_:withOwner:)"
      ],
      "title": "Managing Memory for Bridged Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "addManagedReference:withOwner:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addManagedReference:withOwner:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Memory-for-Bridged-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSVirtualMachine/removeManagedReference(_:withOwner:)"
              ],
              "title": "Managing Memory for Bridged Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "addManagedReference:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "object"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withOwner:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "owner"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The object to be referenced by the JavaScript memory management graph.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "object"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The other object responsible for the lifetime of the reference.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "owner"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSVirtualMachine~1removeManagedReference(_:withOwner:)/title",
          "value": "removeManagedReference:withOwner:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSVirtualMachine~1removeManagedReference(_:withOwner:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeManagedReference:withOwner:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSVirtualMachine~1addManagedReference(_:withOwner:)/title",
          "value": "addManagedReference:withOwner:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSVirtualMachine~1addManagedReference(_:withOwner:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addManagedReference:withOwner:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSVirtualMachine/title",
          "value": "JSVirtualMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSVirtualMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSVirtualMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSVirtualMachine"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jsvirtualmachine/addmanagedreference(_:withowner:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/jsvirtualmachine/addmanagedreference(_:withowner:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
