{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SoundField"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUSpatializationAlgorithm@kSpatializationAlgorithm_SoundField",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "spatializationAlgorithm_SoundField"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSpatializationAlgorithm_SoundField"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AUSpatializationAlgorithm.spatializationAlgorithm_SoundField"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "spatializationAlgorithm_SoundField"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUSpatializationAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUSpatializationAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_EqualPowerPanning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_EqualPowerPanning"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_EqualPowerPanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_EqualPowerPanning"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_EqualPowerPanning",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_equalpowerpanning"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_HRTF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_HRTF"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_HRTF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_hrtf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SoundField": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_SoundField"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SoundField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_SoundField"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_SoundField",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_soundfield"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SphericalHead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_SphericalHead"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SphericalHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_SphericalHead"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_SphericalHead",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_sphericalhead"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_StereoPassThrough": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_StereoPassThrough"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_StereoPassThrough",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_StereoPassThrough"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_StereoPassThrough",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_stereopassthrough"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_VectorBasedPanning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatializationAlgorithm_VectorBasedPanning"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_VectorBasedPanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSpatializationAlgorithm_VectorBasedPanning"
        }
      ],
      "role": "symbol",
      "title": "AUSpatializationAlgorithm.spatializationAlgorithm_VectorBasedPanning",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_vectorbasedpanning"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_EqualPowerPanning",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTF",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SphericalHead",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_StereoPassThrough",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_VectorBasedPanning"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSpatializationAlgorithm_SoundField"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_SoundField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_EqualPowerPanning",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_HRTF",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_SphericalHead",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_StereoPassThrough",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUSpatializationAlgorithm/spatializationAlgorithm_VectorBasedPanning"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSpatializationAlgorithm_SoundField"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/title",
          "value": "AUSpatializationAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUSpatializationAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_EqualPowerPanning/title",
          "value": "kSpatializationAlgorithm_EqualPowerPanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_EqualPowerPanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_EqualPowerPanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_StereoPassThrough/title",
          "value": "kSpatializationAlgorithm_StereoPassThrough"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_StereoPassThrough/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_StereoPassThrough"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_VectorBasedPanning/title",
          "value": "kSpatializationAlgorithm_VectorBasedPanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_VectorBasedPanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_VectorBasedPanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_SphericalHead/title",
          "value": "kSpatializationAlgorithm_SphericalHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_SphericalHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_SphericalHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_SoundField/title",
          "value": "kSpatializationAlgorithm_SoundField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_SoundField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_SoundField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_HRTF/title",
          "value": "kSpatializationAlgorithm_HRTF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUSpatializationAlgorithm~1spatializationAlgorithm_HRTF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSpatializationAlgorithm_HRTF"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_soundfield"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auspatializationalgorithm/spatializationalgorithm_soundfield"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
