{
  "abstract": [
    {
      "text": "The local authentication context associated with the authentication view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI",
        "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView/context"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)LAAuthenticationView(py)context",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "context"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)LAContext",
        "text": "LAContext"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication Embedded UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "context"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "context"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)LAContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)LAContext",
              "text": "LAContext"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI": {
      "abstract": [
        {
          "text": "Present a standard local authentication view icon in a custom authentication view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication Embedded UI",
      "type": "topic",
      "url": "/documentation/localauthenticationembeddedui"
    },
    "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView": {
      "abstract": [
        {
          "text": "A graphical representation of the state of biometric authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAAuthenticationView"
        }
      ],
      "identifier": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAAuthenticationView"
        }
      ],
      "role": "symbol",
      "title": "LAAuthenticationView",
      "type": "topic",
      "url": "/documentation/localauthenticationembeddedui/laauthenticationview"
    },
    "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView/context": {
      "abstract": [
        {
          "text": "The local authentication context associated with the authentication view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)LAContext",
          "text": "LAContext"
        }
      ],
      "identifier": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView/context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "context"
        }
      ],
      "role": "symbol",
      "title": "context",
      "type": "topic",
      "url": "/documentation/localauthenticationembeddedui/laauthenticationview/context"
    },
    "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView/init(context:)": {
      "abstract": [
        {
          "text": "Creates a new authentication icon that reflects the current authentication state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)LAContext",
          "text": "LAContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView/init(context:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContext:"
        }
      ],
      "role": "symbol",
      "title": "init(context:)",
      "type": "topic",
      "url": "/documentation/localauthenticationembeddedui/laauthenticationview/init(context:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)LAContext": {
      "abstract": [
        {
          "text": "A mechanism for evaluating authentication policies and access controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAContext"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)LAContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "LAContext",
      "type": "topic",
      "url": "/documentation/LocalAuthentication/LAContext"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-local-authentication-view",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView/init(context:)"
      ],
      "title": "Creating a local authentication view"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "context"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI",
                "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-local-authentication-view",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAAuthenticationView/init(context:)"
              ],
              "title": "Creating a local authentication view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)LAContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)LAContext",
                    "text": "LAContext"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "context"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAAuthenticationView~1init(context:)/title",
          "value": "initWithContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAAuthenticationView~1init(context:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAAuthenticationView~1context/title",
          "value": "context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAAuthenticationView~1context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAAuthenticationView/title",
          "value": "LAAuthenticationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAAuthenticationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAuthenticationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAAuthenticationView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAuthenticationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)LAContext/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LAContext"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthenticationembeddedui/laauthenticationview/context"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthenticationembeddedui/laauthenticationview/context"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
