{
  "abstract": [
    {
      "text": "An error message that indicates a stream couldn’t update its configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToConfigState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC17SCStreamErrorCodeLeV20attemptToConfigStateSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "attemptToConfigState"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
        "text": "SCStreamError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SCStreamErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "attemptToConfigState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "attemptToConfigState"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
              "text": "SCStreamError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SCStreamErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError": {
      "abstract": [
        {
          "text": "An instance representing a ScreenCaptureKit framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamError"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamError"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code": {
      "abstract": [
        {
          "text": "Codes for user cancellation events and errors that can occur in ScreenCaptureKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToConfigState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream couldn’t update its configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToConfigState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToConfigState",
      "kind": "symbol",
      "role": "symbol",
      "title": "attemptToConfigState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/attempttoconfigstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToStartStreamState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream is already running or doesn’t exist when trying to start a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToStartStreamState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToStartStreamState",
      "kind": "symbol",
      "role": "symbol",
      "title": "attemptToStartStreamState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/attempttostartstreamstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToStopStreamState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream is already stopped or doesn’t exist when trying to stop a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToStopStreamState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToStopStreamState",
      "kind": "symbol",
      "role": "symbol",
      "title": "attemptToStopStreamState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/attempttostopstreamstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToUpdateFilterState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream couldn’t update its content filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToUpdateFilterState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToUpdateFilterState",
      "kind": "symbol",
      "role": "symbol",
      "title": "attemptToUpdateFilterState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/attempttoupdatefilterstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStart": {
      "abstract": [
        {
          "text": "An error message that indicates a stream failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStart",
      "kind": "symbol",
      "role": "symbol",
      "title": "failedToStart",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/failedtostart"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStartAudioCapture": {
      "abstract": [
        {
          "text": "An error message that indicates an audio stream failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStartAudioCapture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStartAudioCapture",
      "kind": "symbol",
      "role": "symbol",
      "title": "failedToStartAudioCapture",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/failedtostartaudiocapture"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStartMicrophoneCapture": {
      "abstract": [
        {
          "text": "An error message that indicates microphone capture failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStartMicrophoneCapture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStartMicrophoneCapture",
      "kind": "symbol",
      "role": "symbol",
      "title": "failedToStartMicrophoneCapture",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/failedtostartmicrophonecapture"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStopAudioCapture": {
      "abstract": [
        {
          "text": "An error message that indicates an audio stream failed to stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStopAudioCapture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStopAudioCapture",
      "kind": "symbol",
      "role": "symbol",
      "title": "failedToStopAudioCapture",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/failedtostopaudiocapture"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/internalError": {
      "abstract": [
        {
          "text": "An error message that indicates a stream can’t start due to a failure in ScreenCaptureKit’s internals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/internalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalError",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/internalerror"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/removingStream": {
      "abstract": [
        {
          "text": "An error message that indicates a stream wasn’t removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removingStream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/removingStream",
      "kind": "symbol",
      "role": "symbol",
      "title": "removingStream",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/removingstream"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/systemStoppedStream": {
      "abstract": [
        {
          "text": "An error message that indicates the system stopped the stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemStoppedStream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SCStreamErrorCodeLeV",
          "text": "SCStreamError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/systemStoppedStream",
      "kind": "symbol",
      "role": "symbol",
      "title": "systemStoppedStream",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/systemstoppedstream"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Stream-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToStartStreamState",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToStopStreamState",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/attemptToUpdateFilterState",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStart",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStartAudioCapture",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStopAudioCapture",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/failedToStartMicrophoneCapture",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/systemStoppedStream",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/internalError",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/removingStream"
      ],
      "title": "Stream management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/title",
          "value": "SCStreamErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit/scstreamerror/attempttoconfigstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
