{
  "abstract": [
    {
      "text": "Codes for user cancellation events and errors that can occur in ScreenCaptureKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCStreamErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SCStreamError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError": {
      "abstract": [
        {
          "text": "An instance representing a ScreenCaptureKit framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamError"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamError"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code": {
      "abstract": [
        {
          "text": "Codes for user cancellation events and errors that can occur in ScreenCaptureKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToConfigState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream couldn’t update its configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToConfigState"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToConfigState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorAttemptToConfigState"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.attemptToConfigState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/attempttoconfigstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStartStreamState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream is already running or doesn’t exist when trying to start a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToStartStreamState"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStartStreamState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorAttemptToStartStreamState"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.attemptToStartStreamState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/attempttostartstreamstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStopStreamState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream is already stopped or doesn’t exist when trying to stop a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToStopStreamState"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStopStreamState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorAttemptToStopStreamState"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.attemptToStopStreamState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/attempttostopstreamstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToUpdateFilterState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream couldn’t update its content filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToUpdateFilterState"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToUpdateFilterState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorAttemptToUpdateFilterState"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.attemptToUpdateFilterState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/attempttoupdatefilterstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInterrupted": {
      "abstract": [
        {
          "text": "An error message that indicates there was an interruption in a connection to an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedApplicationConnectionInterrupted"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInterrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedApplicationConnectionInterrupted"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedApplicationConnectionInterrupted",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedapplicationconnectioninterrupted"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInvalid": {
      "abstract": [
        {
          "text": "An error message that indicates the stream lost its connection to an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedApplicationConnectionInvalid"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedApplicationConnectionInvalid"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedApplicationConnectionInvalid",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedapplicationconnectioninvalid"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedNoMatchingApplicationContext": {
      "abstract": [
        {
          "text": "An error message that indicates there isn’t a matching app context for streaming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedNoMatchingApplicationContext"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedNoMatchingApplicationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedNoMatchingApplicationContext"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedNoMatchingApplicationContext",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failednomatchingapplicationcontext"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStart": {
      "abstract": [
        {
          "text": "An error message that indicates a stream failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStart"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedToStart"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedToStart",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedtostart"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartAudioCapture": {
      "abstract": [
        {
          "text": "An error message that indicates an audio stream failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStartAudioCapture"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartAudioCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedToStartAudioCapture"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedToStartAudioCapture",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedtostartaudiocapture"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartMicrophoneCapture": {
      "abstract": [
        {
          "text": "An error message that indicates microphone capture failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStartMicrophoneCapture"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartMicrophoneCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedToStartMicrophoneCapture"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedToStartMicrophoneCapture",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedtostartmicrophonecapture"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStopAudioCapture": {
      "abstract": [
        {
          "text": "An error message that indicates an audio stream failed to stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStopAudioCapture"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStopAudioCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedToStopAudioCapture"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedToStopAudioCapture",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedtostopaudiocapture"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/init(rawvalue:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/internalError": {
      "abstract": [
        {
          "text": "An error message that indicates a stream can’t start due to a failure in ScreenCaptureKit’s internals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorInternalError"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.internalError",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/internalerror"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/invalidParameter": {
      "abstract": [
        {
          "text": "An error message that indicates an operation failed because of an invalid parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameter"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/invalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.invalidParameter",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/invalidparameter"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/missingEntitlements": {
      "abstract": [
        {
          "text": "An error message that indicates missing entitlements in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlements"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/missingEntitlements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorMissingEntitlements"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.missingEntitlements",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/missingentitlements"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noCaptureSource": {
      "abstract": [
        {
          "text": "An error message that indicates a stream doesn’t have a source to capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCaptureSource"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noCaptureSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorNoCaptureSource"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.noCaptureSource",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/nocapturesource"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noDisplayList": {
      "abstract": [
        {
          "text": "An error message that indicates a stream doesn’t have displays available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noDisplayList"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noDisplayList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorNoDisplayList"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.noDisplayList",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/nodisplaylist"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noWindowList": {
      "abstract": [
        {
          "text": "An error message that indicates a stream doesn’t have windows available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noWindowList"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noWindowList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorNoWindowList"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.noWindowList",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/nowindowlist"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/removingStream": {
      "abstract": [
        {
          "text": "An error message that indicates a stream wasn’t removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removingStream"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/removingStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorRemovingStream"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.removingStream",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/removingstream"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/systemStoppedStream": {
      "abstract": [
        {
          "text": "An error message that indicates the system stopped the stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemStoppedStream"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/systemStoppedStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorSystemStoppedStream"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.systemStoppedStream",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/systemstoppedstream"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/userDeclined": {
      "abstract": [
        {
          "text": "An error message that indicates the user didn’t grant Screen Recording permission to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDeclined"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/userDeclined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorUserDeclined"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.userDeclined",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/userdeclined"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/userStopped": {
      "abstract": [
        {
          "text": "An error message that indicates the user stopped the stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userStopped"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/userStopped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorUserStopped"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.userStopped",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/userstopped"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamErrorDomain": {
      "abstract": [
        {
          "text": "A string representation of the error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SCStreamErrorDomain",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "User-cancellation",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/userStopped"
      ],
      "title": "User cancellation"
    },
    {
      "anchor": "Privacy-and-entitlements",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/userDeclined",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/missingEntitlements"
      ],
      "title": "Privacy and entitlements"
    },
    {
      "anchor": "Stream-management",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStartStreamState",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStopStreamState",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToUpdateFilterState",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToConfigState",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStart",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/removingStream",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartAudioCapture",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStopAudioCapture",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartMicrophoneCapture",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/systemStoppedStream",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/internalError"
      ],
      "title": "Stream management"
    },
    {
      "anchor": "Shareable-content",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noCaptureSource",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noDisplayList",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noWindowList",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInvalid",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInterrupted",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedNoMatchingApplicationContext"
      ],
      "title": "Shareable content"
    },
    {
      "anchor": "Invalid-parameters",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/invalidParameter"
      ],
      "title": "Invalid parameters"
    },
    {
      "anchor": "Creating-an-error",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/init(rawValue:)"
      ],
      "title": "Creating an error"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCStreamErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "User-cancellation",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/userStopped"
              ],
              "title": "User cancellation"
            },
            {
              "anchor": "Privacy-and-entitlements",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/userDeclined",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/missingEntitlements"
              ],
              "title": "Privacy and entitlements"
            },
            {
              "anchor": "Stream-management",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStartStreamState",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStopStreamState",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToUpdateFilterState",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToConfigState",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStart",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/removingStream",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartAudioCapture",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStopAudioCapture",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartMicrophoneCapture",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/systemStoppedStream",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/internalError"
              ],
              "title": "Stream management"
            },
            {
              "anchor": "Shareable-content",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noCaptureSource",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noDisplayList",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noWindowList",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInvalid",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInterrupted",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedNoMatchingApplicationContext"
              ],
              "title": "Shareable content"
            },
            {
              "anchor": "Invalid-parameters",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/invalidParameter"
              ],
              "title": "Invalid parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Stream-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamErrorDomain"
              ],
              "title": "Stream errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCStreamErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1missingEntitlements/title",
          "value": "SCStreamErrorMissingEntitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1missingEntitlements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorMissingEntitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1invalidParameter/title",
          "value": "SCStreamErrorInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1invalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noWindowList/title",
          "value": "SCStreamErrorNoWindowList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noWindowList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorNoWindowList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1removingStream/title",
          "value": "SCStreamErrorRemovingStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1removingStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorRemovingStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedApplicationConnectionInterrupted/title",
          "value": "SCStreamErrorFailedApplicationConnectionInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedApplicationConnectionInterrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedApplicationConnectionInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1systemStoppedStream/title",
          "value": "SCStreamErrorSystemStoppedStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1systemStoppedStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorSystemStoppedStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1userStopped/title",
          "value": "SCStreamErrorUserStopped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1userStopped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorUserStopped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1userDeclined/title",
          "value": "SCStreamErrorUserDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1userDeclined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorUserDeclined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noCaptureSource/title",
          "value": "SCStreamErrorNoCaptureSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noCaptureSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorNoCaptureSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToConfigState/title",
          "value": "SCStreamErrorAttemptToConfigState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToConfigState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorAttemptToConfigState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToStopStreamState/title",
          "value": "SCStreamErrorAttemptToStopStreamState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToStopStreamState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorAttemptToStopStreamState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedNoMatchingApplicationContext/title",
          "value": "SCStreamErrorFailedNoMatchingApplicationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedNoMatchingApplicationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedNoMatchingApplicationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noDisplayList/title",
          "value": "SCStreamErrorNoDisplayList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noDisplayList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorNoDisplayList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToStartStreamState/title",
          "value": "SCStreamErrorAttemptToStartStreamState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToStartStreamState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorAttemptToStartStreamState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1internalError/title",
          "value": "SCStreamErrorInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedApplicationConnectionInvalid/title",
          "value": "SCStreamErrorFailedApplicationConnectionInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedApplicationConnectionInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedApplicationConnectionInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStopAudioCapture/title",
          "value": "SCStreamErrorFailedToStopAudioCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStopAudioCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedToStopAudioCapture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStartMicrophoneCapture/title",
          "value": "SCStreamErrorFailedToStartMicrophoneCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStartMicrophoneCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedToStartMicrophoneCapture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStartAudioCapture/title",
          "value": "SCStreamErrorFailedToStartAudioCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStartAudioCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedToStartAudioCapture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/title",
          "value": "SCStreamErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamErrorDomain/title",
          "value": "SCStreamErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToUpdateFilterState/title",
          "value": "SCStreamErrorAttemptToUpdateFilterState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToUpdateFilterState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorAttemptToUpdateFilterState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStart/title",
          "value": "SCStreamErrorFailedToStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedToStart"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit/scstreamerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screencapturekit/scstreamerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
