{
  "abstract": [
    {
      "text": "Commission a Matter accessory onto a network.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/accessory-commissioning"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Accessory commissioning"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Commissioning is the act of providing an accessory with the network credentials it needs to join the local network and the initial configuration needed to control the accessory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/AttestationInfo": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AttestationInfo"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/AttestationInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AttestationInfo"
        }
      ],
      "role": "symbol",
      "title": "AttestationInfo",
      "type": "topic",
      "url": "/documentation/matter/attestationinfo"
    },
    "doc://com.apple.matter/documentation/Matter/CSRInfo": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSRInfo"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/CSRInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSRInfo"
        }
      ],
      "role": "symbol",
      "title": "CSRInfo",
      "type": "topic",
      "url": "/documentation/matter/csrinfo"
    },
    "doc://com.apple.matter/documentation/Matter/MTRCertificateInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRCertificateInfo"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRCertificateInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRCertificateInfo"
        }
      ],
      "role": "symbol",
      "title": "MTRCertificateInfo",
      "type": "topic",
      "url": "/documentation/matter/mtrcertificateinfo"
    },
    "doc://com.apple.matter/documentation/Matter/MTRCommissioningParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRCommissioningParameters"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRCommissioningParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRCommissioningParameters"
        }
      ],
      "role": "symbol",
      "title": "MTRCommissioningParameters",
      "type": "topic",
      "url": "/documentation/matter/mtrcommissioningparameters"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceAttestationDelegate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceAttestationDelegate"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceAttestationDelegate",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceattestationdelegate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationDeviceInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceAttestationDeviceInfo"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationDeviceInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceAttestationDeviceInfo"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceAttestationDeviceInfo",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceattestationdeviceinfo"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceAttestationInfo"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceAttestationInfo"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceAttestationInfo",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceattestationinfo"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceControllerDelegate",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicecontrollerdelegate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDevicePairingDelegate": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDevicePairingDelegate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDevicePairingDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDevicePairingDelegate"
        }
      ],
      "role": "symbol",
      "title": "MTRDevicePairingDelegate",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicepairingdelegate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDistinguishedNameInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDistinguishedNameInfo"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDistinguishedNameInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDistinguishedNameInfo"
        }
      ],
      "role": "symbol",
      "title": "MTRDistinguishedNameInfo",
      "type": "topic",
      "url": "/documentation/matter/mtrdistinguishednameinfo"
    },
    "doc://com.apple.matter/documentation/Matter/MTROnboardingPayloadParser": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROnboardingPayloadParser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROnboardingPayloadParser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROnboardingPayloadParser"
        }
      ],
      "role": "symbol",
      "title": "MTROnboardingPayloadParser",
      "type": "topic",
      "url": "/documentation/matter/mtronboardingpayloadparser"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCSRInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROperationalCSRInfo"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCSRInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCSRInfo"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCSRInfo",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcsrinfo"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCertificateChain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROperationalCertificateChain"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCertificateChain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCertificateChain"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCertificateChain",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcertificatechain"
    },
    "doc://com.apple.matter/documentation/Matter/MTROptionalQRCodeInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROptionalQRCodeInfo"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROptionalQRCodeInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROptionalQRCodeInfo"
        }
      ],
      "role": "symbol",
      "title": "MTROptionalQRCodeInfo",
      "type": "topic",
      "url": "/documentation/matter/mtroptionalqrcodeinfo"
    },
    "doc://com.apple.matter/documentation/Matter/MTRQRCodeSetupPayloadParser": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRQRCodeSetupPayloadParser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRQRCodeSetupPayloadParser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRQRCodeSetupPayloadParser"
        }
      ],
      "role": "symbol",
      "title": "MTRQRCodeSetupPayloadParser",
      "type": "topic",
      "url": "/documentation/matter/mtrqrcodesetuppayloadparser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRThreadOperationalDataset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRThreadOperationalDataset"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRThreadOperationalDataset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRThreadOperationalDataset"
        }
      ],
      "role": "symbol",
      "title": "MTRThreadOperationalDataset",
      "type": "topic",
      "url": "/documentation/matter/mtrthreadoperationaldataset"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Commissioning",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRCommissioningParameters",
        "doc://com.apple.matter/documentation/Matter/MTRThreadOperationalDataset",
        "doc://com.apple.matter/documentation/Matter/MTROptionalQRCodeInfo",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCertificateChain",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationInfo",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationDeviceInfo",
        "doc://com.apple.matter/documentation/Matter/MTRDistinguishedNameInfo",
        "doc://com.apple.matter/documentation/Matter/MTRCertificateInfo",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCSRInfo",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerDelegate",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationDelegate",
        "doc://com.apple.matter/documentation/Matter/MTROnboardingPayloadParser",
        "doc://com.apple.matter/documentation/Matter/MTRQRCodeSetupPayloadParser",
        "doc://com.apple.matter/documentation/Matter/AttestationInfo",
        "doc://com.apple.matter/documentation/Matter/CSRInfo",
        "doc://com.apple.matter/documentation/Matter/MTRDevicePairingDelegate"
      ],
      "title": "Commissioning"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Commissioning",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRCommissioningParameters",
                "doc://com.apple.matter/documentation/Matter/MTRThreadOperationalDataset",
                "doc://com.apple.matter/documentation/Matter/MTROptionalQRCodeInfo",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCertificateChain",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationInfo",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationDeviceInfo",
                "doc://com.apple.matter/documentation/Matter/MTRDistinguishedNameInfo",
                "doc://com.apple.matter/documentation/Matter/MTRCertificateInfo",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCSRInfo",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerDelegate",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceAttestationDelegate",
                "doc://com.apple.matter/documentation/Matter/MTROnboardingPayloadParser",
                "doc://com.apple.matter/documentation/Matter/MTRQRCodeSetupPayloadParser",
                "doc://com.apple.matter/documentation/Matter/AttestationInfo",
                "doc://com.apple.matter/documentation/Matter/CSRInfo",
                "doc://com.apple.matter/documentation/Matter/MTRDevicePairingDelegate"
              ],
              "title": "Commissioning"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCSRInfo/title",
          "value": "MTROperationalCSRInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCSRInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCSRInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCSRInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCSRInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1AttestationInfo/title",
          "value": "AttestationInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1AttestationInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AttestationInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1AttestationInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AttestationInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRQRCodeSetupPayloadParser/title",
          "value": "MTRQRCodeSetupPayloadParser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRQRCodeSetupPayloadParser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRQRCodeSetupPayloadParser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRQRCodeSetupPayloadParser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRQRCodeSetupPayloadParser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCommissioningParameters/title",
          "value": "MTRCommissioningParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCommissioningParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCommissioningParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCommissioningParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCommissioningParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceAttestationInfo/title",
          "value": "MTRDeviceAttestationInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceAttestationInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceAttestationInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceAttestationInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceAttestationInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerDelegate/title",
          "value": "MTRDeviceControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadOperationalDataset/title",
          "value": "MTRThreadOperationalDataset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadOperationalDataset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadOperationalDataset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRThreadOperationalDataset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRThreadOperationalDataset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceAttestationDeviceInfo/title",
          "value": "MTRDeviceAttestationDeviceInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceAttestationDeviceInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceAttestationDeviceInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceAttestationDeviceInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceAttestationDeviceInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1CSRInfo/title",
          "value": "CSRInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1CSRInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSRInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1CSRInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSRInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceAttestationDelegate/title",
          "value": "MTRDeviceAttestationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceAttestationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceAttestationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceAttestationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceAttestationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDistinguishedNameInfo/title",
          "value": "MTRDistinguishedNameInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDistinguishedNameInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDistinguishedNameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDistinguishedNameInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDistinguishedNameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCertificateChain/title",
          "value": "MTROperationalCertificateChain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCertificateChain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCertificateChain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCertificateChain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCertificateChain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCertificateInfo/title",
          "value": "MTRCertificateInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCertificateInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCertificateInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCertificateInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCertificateInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROptionalQRCodeInfo/title",
          "value": "MTROptionalQRCodeInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROptionalQRCodeInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROptionalQRCodeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROptionalQRCodeInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROptionalQRCodeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROnboardingPayloadParser/title",
          "value": "MTROnboardingPayloadParser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROnboardingPayloadParser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROnboardingPayloadParser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROnboardingPayloadParser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROnboardingPayloadParser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDevicePairingDelegate/title",
          "value": "MTRDevicePairingDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDevicePairingDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDevicePairingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDevicePairingDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDevicePairingDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/accessory-commissioning"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/accessory-commissioning"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
