{
  "abstract": [
    {
      "text": "Communicate with commissioned Matter accessories.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/accessory-control"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Accessory control"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Once you’ve commissioned a Matter accessory, use these methods to read and write data, subscribe to data updates, and send commands.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRAsyncCallbackQueueWorkItem": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRAsyncCallbackQueueWorkItem"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRAsyncCallbackQueueWorkItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRAsyncCallbackQueueWorkItem"
        }
      ],
      "role": "symbol",
      "title": "MTRAsyncCallbackQueueWorkItem",
      "type": "topic",
      "url": "/documentation/matter/mtrasynccallbackqueueworkitem"
    },
    "doc://com.apple.matter/documentation/Matter/MTRAsyncCallbackWorkQueue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRAsyncCallbackWorkQueue"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRAsyncCallbackWorkQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRAsyncCallbackWorkQueue"
        }
      ],
      "role": "symbol",
      "title": "MTRAsyncCallbackWorkQueue",
      "type": "topic",
      "url": "/documentation/matter/mtrasynccallbackworkqueue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRAttributeCacheContainer": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRAttributeCacheContainer"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRAttributeCacheContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRAttributeCacheContainer"
        }
      ],
      "role": "symbol",
      "title": "MTRAttributeCacheContainer",
      "type": "topic",
      "url": "/documentation/matter/mtrattributecachecontainer"
    },
    "doc://com.apple.matter/documentation/Matter/MTRAttributePath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRAttributePath"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRAttributePath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRAttributePath"
        }
      ],
      "role": "symbol",
      "title": "MTRAttributePath",
      "type": "topic",
      "url": "/documentation/matter/mtrattributepath"
    },
    "doc://com.apple.matter/documentation/Matter/MTRAttributeReport": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRAttributeReport"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRAttributeReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRAttributeReport"
        }
      ],
      "role": "symbol",
      "title": "MTRAttributeReport",
      "type": "topic",
      "url": "/documentation/matter/mtrattributereport"
    },
    "doc://com.apple.matter/documentation/Matter/MTRAttributeRequestPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRAttributeRequestPath"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRAttributeRequestPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRAttributeRequestPath"
        }
      ],
      "role": "symbol",
      "title": "MTRAttributeRequestPath",
      "type": "topic",
      "url": "/documentation/matter/mtrattributerequestpath"
    },
    "doc://com.apple.matter/documentation/Matter/MTRBaseDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRBaseDevice"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRBaseDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRBaseDevice"
        }
      ],
      "role": "symbol",
      "title": "MTRBaseDevice",
      "type": "topic",
      "url": "/documentation/matter/mtrbasedevice"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRClusterPath"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRClusterPath"
        }
      ],
      "role": "symbol",
      "title": "MTRClusterPath",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterpath"
    },
    "doc://com.apple.matter/documentation/Matter/MTRClusterStateCacheContainer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRClusterStateCacheContainer"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRClusterStateCacheContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRClusterStateCacheContainer"
        }
      ],
      "role": "symbol",
      "title": "MTRClusterStateCacheContainer",
      "type": "topic",
      "url": "/documentation/matter/mtrclusterstatecachecontainer"
    },
    "doc://com.apple.matter/documentation/Matter/MTRCommandPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRCommandPath"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRCommandPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRCommandPath"
        }
      ],
      "role": "symbol",
      "title": "MTRCommandPath",
      "type": "topic",
      "url": "/documentation/matter/mtrcommandpath"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDevice"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDevice"
        }
      ],
      "role": "symbol",
      "title": "MTRDevice",
      "type": "topic",
      "url": "/documentation/matter/mtrdevice"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerClientProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerClientProtocol"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerClientProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerClientProtocol"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceControllerClientProtocol",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicecontrollerclientprotocol"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerServerProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerServerProtocol"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerServerProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerServerProtocol"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceControllerServerProtocol",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicecontrollerserverprotocol"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceDelegate",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicedelegate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceErrorHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceErrorHandler"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceErrorHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceErrorHandler"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceErrorHandler",
      "type": "topic",
      "url": "/documentation/matter/mtrdeviceerrorhandler"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRError"
        }
      ],
      "role": "symbol",
      "title": "MTRError",
      "type": "topic",
      "url": "/documentation/matter/mtrerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code"
    },
    "doc://com.apple.matter/documentation/Matter/MTREventPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTREventPath"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREventPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREventPath"
        }
      ],
      "role": "symbol",
      "title": "MTREventPath",
      "type": "topic",
      "url": "/documentation/matter/mtreventpath"
    },
    "doc://com.apple.matter/documentation/Matter/MTREventReport": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTREventReport"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREventReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREventReport"
        }
      ],
      "role": "symbol",
      "title": "MTREventReport",
      "type": "topic",
      "url": "/documentation/matter/mtreventreport"
    },
    "doc://com.apple.matter/documentation/Matter/MTREventRequestPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTREventRequestPath"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREventRequestPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREventRequestPath"
        }
      ],
      "role": "symbol",
      "title": "MTREventRequestPath",
      "type": "topic",
      "url": "/documentation/matter/mtreventrequestpath"
    },
    "doc://com.apple.matter/documentation/Matter/MTRLogCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRLogCallback"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRLogCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRLogCallback"
        }
      ],
      "role": "symbol",
      "title": "MTRLogCallback",
      "type": "topic",
      "url": "/documentation/matter/mtrlogcallback"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAHeaderParser": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROTAHeaderParser"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAHeaderParser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAHeaderParser"
        }
      ],
      "role": "symbol",
      "title": "MTROTAHeaderParser",
      "type": "topic",
      "url": "/documentation/matter/mtrotaheaderparser"
    },
    "doc://com.apple.matter/documentation/Matter/MTRProductIdentity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRProductIdentity"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRProductIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRProductIdentity"
        }
      ],
      "role": "symbol",
      "title": "MTRProductIdentity",
      "type": "topic",
      "url": "/documentation/matter/mtrproductidentity"
    },
    "doc://com.apple.matter/documentation/Matter/MTRReadParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRReadParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRReadParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRReadParams"
        }
      ],
      "role": "symbol",
      "title": "MTRReadParams",
      "type": "topic",
      "url": "/documentation/matter/mtrreadparams"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSetLogCallback(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRSetLogCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTRLogType",
          "text": "MTRLogType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTRLogCallback",
          "text": "MTRLogCallback"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSetLogCallback(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSetLogCallback"
        }
      ],
      "role": "symbol",
      "title": "MTRSetLogCallback(_:_:)",
      "type": "topic",
      "url": "/documentation/matter/mtrsetlogcallback(_:_:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRSubscribeParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRSubscribeParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRSubscribeParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRSubscribeParams"
        }
      ],
      "role": "symbol",
      "title": "MTRSubscribeParams",
      "type": "topic",
      "url": "/documentation/matter/mtrsubscribeparams"
    },
    "doc://com.apple.matter/documentation/Matter/MTRWriteParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRWriteParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRWriteParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRWriteParams"
        }
      ],
      "role": "symbol",
      "title": "MTRWriteParams",
      "type": "topic",
      "url": "/documentation/matter/mtrwriteparams"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Controlling-accessories",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRAttributeRequestPath",
        "doc://com.apple.matter/documentation/Matter/MTREventRequestPath",
        "doc://com.apple.matter/documentation/Matter/MTRProductIdentity",
        "doc://com.apple.matter/documentation/Matter/MTRDevice",
        "doc://com.apple.matter/documentation/Matter/MTRBaseDevice",
        "doc://com.apple.matter/documentation/Matter/MTRClusterStateCacheContainer",
        "doc://com.apple.matter/documentation/Matter/MTRWriteParams",
        "doc://com.apple.matter/documentation/Matter/MTRReadParams",
        "doc://com.apple.matter/documentation/Matter/MTRSubscribeParams",
        "doc://com.apple.matter/documentation/Matter/MTRClusterPath",
        "doc://com.apple.matter/documentation/Matter/MTRAttributePath",
        "doc://com.apple.matter/documentation/Matter/MTREventPath",
        "doc://com.apple.matter/documentation/Matter/MTRCommandPath",
        "doc://com.apple.matter/documentation/Matter/MTRAttributeReport",
        "doc://com.apple.matter/documentation/Matter/MTREventReport",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceDelegate",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerClientProtocol",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerServerProtocol",
        "doc://com.apple.matter/documentation/Matter/MTRAsyncCallbackQueueWorkItem",
        "doc://com.apple.matter/documentation/Matter/MTRAsyncCallbackWorkQueue",
        "doc://com.apple.matter/documentation/Matter/MTRAttributeCacheContainer",
        "doc://com.apple.matter/documentation/Matter/MTROTAHeaderParser"
      ],
      "title": "Controlling accessories"
    },
    {
      "anchor": "Logging-information",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRLogCallback",
        "doc://com.apple.matter/documentation/Matter/MTRSetLogCallback(_:_:)"
      ],
      "title": "Logging information"
    },
    {
      "anchor": "Handling-errors",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDeviceErrorHandler",
        "doc://com.apple.matter/documentation/Matter/MTRError",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code"
      ],
      "title": "Handling errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Controlling-accessories",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRAttributeRequestPath",
                "doc://com.apple.matter/documentation/Matter/MTREventRequestPath",
                "doc://com.apple.matter/documentation/Matter/MTRProductIdentity",
                "doc://com.apple.matter/documentation/Matter/MTRDevice",
                "doc://com.apple.matter/documentation/Matter/MTRBaseDevice",
                "doc://com.apple.matter/documentation/Matter/MTRClusterStateCacheContainer",
                "doc://com.apple.matter/documentation/Matter/MTRWriteParams",
                "doc://com.apple.matter/documentation/Matter/MTRReadParams",
                "doc://com.apple.matter/documentation/Matter/MTRSubscribeParams",
                "doc://com.apple.matter/documentation/Matter/MTRClusterPath",
                "doc://com.apple.matter/documentation/Matter/MTRAttributePath",
                "doc://com.apple.matter/documentation/Matter/MTREventPath",
                "doc://com.apple.matter/documentation/Matter/MTRCommandPath",
                "doc://com.apple.matter/documentation/Matter/MTRAttributeReport",
                "doc://com.apple.matter/documentation/Matter/MTREventReport",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceDelegate",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerClientProtocol",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerServerProtocol",
                "doc://com.apple.matter/documentation/Matter/MTRAsyncCallbackQueueWorkItem",
                "doc://com.apple.matter/documentation/Matter/MTRAsyncCallbackWorkQueue",
                "doc://com.apple.matter/documentation/Matter/MTRAttributeCacheContainer",
                "doc://com.apple.matter/documentation/Matter/MTROTAHeaderParser"
              ],
              "title": "Controlling accessories"
            },
            {
              "anchor": "Logging-information",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRLogCallback",
                "doc://com.apple.matter/documentation/Matter/MTRSetLogCallback(_:_:)"
              ],
              "title": "Logging information"
            },
            {
              "anchor": "Handling-errors",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDeviceErrorHandler",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code"
              ],
              "title": "Handling errors"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventReport/title",
          "value": "MTREventReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREventReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREventReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerClientProtocol/title",
          "value": "MTRDeviceControllerClientProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerClientProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerClientProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerClientProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerClientProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceErrorHandler/title",
          "value": "MTRDeviceErrorHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceErrorHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceErrorHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceErrorHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceErrorHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerServerProtocol/title",
          "value": "MTRDeviceControllerServerProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerServerProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerServerProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerServerProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerServerProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCommandPath/title",
          "value": "MTRCommandPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCommandPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCommandPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRCommandPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRCommandPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAsyncCallbackWorkQueue/title",
          "value": "MTRAsyncCallbackWorkQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAsyncCallbackWorkQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAsyncCallbackWorkQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAsyncCallbackWorkQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAsyncCallbackWorkQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDevice/title",
          "value": "MTRDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterPath/title",
          "value": "MTRClusterPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceDelegate/title",
          "value": "MTRDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAsyncCallbackQueueWorkItem/title",
          "value": "MTRAsyncCallbackQueueWorkItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAsyncCallbackQueueWorkItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAsyncCallbackQueueWorkItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAsyncCallbackQueueWorkItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAsyncCallbackQueueWorkItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAHeaderParser/title",
          "value": "MTROTAHeaderParser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAHeaderParser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAHeaderParser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAHeaderParser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAHeaderParser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRProductIdentity/title",
          "value": "MTRProductIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRProductIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRProductIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRProductIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRProductIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeReport/title",
          "value": "MTRAttributeReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAttributeReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAttributeReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeCacheContainer/title",
          "value": "MTRAttributeCacheContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeCacheContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAttributeCacheContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeCacheContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAttributeCacheContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code/title",
          "value": "MTRErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRReadParams/title",
          "value": "MTRReadParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRReadParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRReadParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRReadParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRReadParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSetLogCallback(_:_:)/title",
          "value": "MTRSetLogCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSetLogCallback(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSetLogCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventPath/title",
          "value": "MTREventPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREventPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREventPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterStateCacheContainer/title",
          "value": "MTRClusterStateCacheContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterStateCacheContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterStateCacheContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRClusterStateCacheContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRClusterStateCacheContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeRequestPath/title",
          "value": "MTRAttributeRequestPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeRequestPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAttributeRequestPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributeRequestPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAttributeRequestPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventRequestPath/title",
          "value": "MTREventRequestPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventRequestPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREventRequestPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventRequestPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREventRequestPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLogCallback/title",
          "value": "MTRLogCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLogCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLogCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRLogCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRLogCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseDevice/title",
          "value": "MTRBaseDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRBaseDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRBaseDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSubscribeParams/title",
          "value": "MTRSubscribeParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSubscribeParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSubscribeParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRSubscribeParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRSubscribeParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributePath/title",
          "value": "MTRAttributePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributePath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAttributePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRAttributePath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRAttributePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWriteParams/title",
          "value": "MTRWriteParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWriteParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWriteParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRWriteParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRWriteParams"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/accessory-control"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/accessory-control"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
