{
  "abstract": [
    {
      "text": "Initialize the object that controls Matter accessories.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/controller-initialization"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Controller initialization"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These methods enable the creation and initialization of a device controller (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") on a specific Matter ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "fabric",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". A fabric is a set of accessories and device controllers that can communicate with each other. You use the device controller to commission and control accessories.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRControllerFactory": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRControllerFactory"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRControllerFactory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRControllerFactory"
        }
      ],
      "role": "symbol",
      "title": "MTRControllerFactory",
      "type": "topic",
      "url": "/documentation/matter/mtrcontrollerfactory"
    },
    "doc://com.apple.matter/documentation/Matter/MTRControllerFactoryParams": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRControllerFactoryParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRControllerFactoryParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRControllerFactoryParams"
        }
      ],
      "role": "symbol",
      "title": "MTRControllerFactoryParams",
      "type": "topic",
      "url": "/documentation/matter/mtrcontrollerfactoryparams"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceController"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceController"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceController",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicecontroller"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerFactory"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerFactory"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceControllerFactory",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicecontrollerfactory"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactoryParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerFactoryParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactoryParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerFactoryParams"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceControllerFactoryParams",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicecontrollerfactoryparams"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerStartupParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerStartupParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerStartupParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerStartupParams"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceControllerStartupParams",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicecontrollerstartupparams"
    },
    "doc://com.apple.matter/documentation/Matter/MTRFabricInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRFabricInfo"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRFabricInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRFabricInfo"
        }
      ],
      "role": "symbol",
      "title": "MTRFabricInfo",
      "type": "topic",
      "url": "/documentation/matter/mtrfabricinfo"
    },
    "doc://com.apple.matter/documentation/Matter/MTRKeypair": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRKeypair"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRKeypair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRKeypair"
        }
      ],
      "role": "symbol",
      "title": "MTRKeypair",
      "type": "topic",
      "url": "/documentation/matter/mtrkeypair"
    },
    "doc://com.apple.matter/documentation/Matter/MTRNOCChainIssuer": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRNOCChainIssuer"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRNOCChainIssuer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRNOCChainIssuer"
        }
      ],
      "role": "symbol",
      "title": "MTRNOCChainIssuer",
      "type": "topic",
      "url": "/documentation/matter/mtrnocchainissuer"
    },
    "doc://com.apple.matter/documentation/Matter/MTROTAProviderDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROTAProviderDelegate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROTAProviderDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROTAProviderDelegate"
        }
      ],
      "role": "symbol",
      "title": "MTROTAProviderDelegate",
      "type": "topic",
      "url": "/documentation/matter/mtrotaproviderdelegate"
    },
    "doc://com.apple.matter/documentation/Matter/MTROperationalCertificateIssuer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTROperationalCertificateIssuer"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTROperationalCertificateIssuer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTROperationalCertificateIssuer"
        }
      ],
      "role": "symbol",
      "title": "MTROperationalCertificateIssuer",
      "type": "topic",
      "url": "/documentation/matter/mtroperationalcertificateissuer"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPersistentStorageDelegate": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRPersistentStorageDelegate"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPersistentStorageDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPersistentStorageDelegate"
        }
      ],
      "role": "symbol",
      "title": "MTRPersistentStorageDelegate",
      "type": "topic",
      "url": "/documentation/matter/mtrpersistentstoragedelegate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRStorage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRStorage"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRStorage"
        }
      ],
      "role": "symbol",
      "title": "MTRStorage",
      "type": "topic",
      "url": "/documentation/matter/mtrstorage"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initialization",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactoryParams",
        "doc://com.apple.matter/documentation/Matter/MTRStorage",
        "doc://com.apple.matter/documentation/Matter/MTROTAProviderDelegate",
        "doc://com.apple.matter/documentation/Matter/MTRFabricInfo",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceController",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerStartupParams",
        "doc://com.apple.matter/documentation/Matter/MTRKeypair",
        "doc://com.apple.matter/documentation/Matter/MTROperationalCertificateIssuer",
        "doc://com.apple.matter/documentation/Matter/MTRControllerFactory",
        "doc://com.apple.matter/documentation/Matter/MTRControllerFactoryParams",
        "doc://com.apple.matter/documentation/Matter/MTRPersistentStorageDelegate",
        "doc://com.apple.matter/documentation/Matter/MTRNOCChainIssuer"
      ],
      "title": "Initialization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initialization",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactoryParams",
                "doc://com.apple.matter/documentation/Matter/MTRStorage",
                "doc://com.apple.matter/documentation/Matter/MTROTAProviderDelegate",
                "doc://com.apple.matter/documentation/Matter/MTRFabricInfo",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceController",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerStartupParams",
                "doc://com.apple.matter/documentation/Matter/MTRKeypair",
                "doc://com.apple.matter/documentation/Matter/MTROperationalCertificateIssuer",
                "doc://com.apple.matter/documentation/Matter/MTRControllerFactory",
                "doc://com.apple.matter/documentation/Matter/MTRControllerFactoryParams",
                "doc://com.apple.matter/documentation/Matter/MTRPersistentStorageDelegate",
                "doc://com.apple.matter/documentation/Matter/MTRNOCChainIssuer"
              ],
              "title": "Initialization"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRControllerFactory/title",
          "value": "MTRControllerFactory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRControllerFactory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRControllerFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRControllerFactory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRControllerFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactoryParams/title",
          "value": "MTRDeviceControllerFactoryParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactoryParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerFactoryParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactoryParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerFactoryParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNOCChainIssuer/title",
          "value": "MTRNOCChainIssuer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNOCChainIssuer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNOCChainIssuer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRNOCChainIssuer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRNOCChainIssuer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRControllerFactoryParams/title",
          "value": "MTRControllerFactoryParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRControllerFactoryParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRControllerFactoryParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRControllerFactoryParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRControllerFactoryParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAProviderDelegate/title",
          "value": "MTROTAProviderDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAProviderDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROTAProviderDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROTAProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPersistentStorageDelegate/title",
          "value": "MTRPersistentStorageDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPersistentStorageDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPersistentStorageDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPersistentStorageDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPersistentStorageDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFabricInfo/title",
          "value": "MTRFabricInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFabricInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFabricInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRFabricInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRFabricInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRKeypair/title",
          "value": "MTRKeypair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRKeypair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRKeypair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRKeypair/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRKeypair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceController/title",
          "value": "MTRDeviceController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerStartupParams/title",
          "value": "MTRDeviceControllerStartupParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerStartupParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerStartupParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerStartupParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerStartupParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCertificateIssuer/title",
          "value": "MTROperationalCertificateIssuer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCertificateIssuer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCertificateIssuer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTROperationalCertificateIssuer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTROperationalCertificateIssuer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactory/title",
          "value": "MTRDeviceControllerFactory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRStorage/title",
          "value": "MTRStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRStorage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/controller-initialization"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/controller-initialization"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
