{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/matter-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Matter Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDataVersionKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDataVersionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDataVersionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDataVersionKey"
        }
      ],
      "role": "symbol",
      "title": "MTRDataVersionKey",
      "type": "topic",
      "url": "/documentation/matter/mtrdataversionkey"
    },
    "doc://com.apple.matter/documentation/Matter/MTREventIsHistoricalKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTREventIsHistoricalKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTREventIsHistoricalKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTREventIsHistoricalKey"
        }
      ],
      "role": "symbol",
      "title": "MTREventIsHistoricalKey",
      "type": "topic",
      "url": "/documentation/matter/mtreventishistoricalkey"
    },
    "doc://com.apple.matter/documentation/Matter/MTRPreviousDataKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRPreviousDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRPreviousDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRPreviousDataKey"
        }
      ],
      "role": "symbol",
      "title": "MTRPreviousDataKey",
      "type": "topic",
      "url": "/documentation/matter/mtrpreviousdatakey"
    },
    "doc://com.apple.matter/documentation/Matter/MTR_ENABLE_PROVISIONAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTR_ENABLE_PROVISIONAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTR_ENABLE_PROVISIONAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTR_ENABLE_PROVISIONAL"
        }
      ],
      "role": "symbol",
      "title": "MTR_ENABLE_PROVISIONAL",
      "type": "topic",
      "url": "/documentation/matter/mtr_enable_provisional"
    },
    "doc://com.apple.matter/documentation/Matter/MTR_ENABLE_UNSTABLE_API": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTR_ENABLE_UNSTABLE_API"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTR_ENABLE_UNSTABLE_API",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTR_ENABLE_UNSTABLE_API"
        }
      ],
      "role": "symbol",
      "title": "MTR_ENABLE_UNSTABLE_API",
      "type": "topic",
      "url": "/documentation/matter/mtr_enable_unstable_api"
    },
    "doc://com.apple.matter/documentation/Matter/MTR_NO_AVAILABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTR_NO_AVAILABILITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTR_NO_AVAILABILITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTR_NO_AVAILABILITY"
        }
      ],
      "role": "symbol",
      "title": "MTR_NO_AVAILABILITY",
      "type": "topic",
      "url": "/documentation/matter/mtr_no_availability"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRDataVersionKey",
        "doc://com.apple.matter/documentation/Matter/MTREventIsHistoricalKey",
        "doc://com.apple.matter/documentation/Matter/MTRPreviousDataKey",
        "doc://com.apple.matter/documentation/Matter/MTR_ENABLE_PROVISIONAL",
        "doc://com.apple.matter/documentation/Matter/MTR_ENABLE_UNSTABLE_API",
        "doc://com.apple.matter/documentation/Matter/MTR_NO_AVAILABILITY"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRDataVersionKey",
                "doc://com.apple.matter/documentation/Matter/MTREventIsHistoricalKey",
                "doc://com.apple.matter/documentation/Matter/MTRPreviousDataKey",
                "doc://com.apple.matter/documentation/Matter/MTR_ENABLE_PROVISIONAL",
                "doc://com.apple.matter/documentation/Matter/MTR_ENABLE_UNSTABLE_API",
                "doc://com.apple.matter/documentation/Matter/MTR_NO_AVAILABILITY"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTR_ENABLE_UNSTABLE_API/title",
          "value": "MTR_ENABLE_UNSTABLE_API"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTR_ENABLE_UNSTABLE_API/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTR_ENABLE_UNSTABLE_API"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataVersionKey/title",
          "value": "MTRDataVersionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDataVersionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDataVersionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTR_ENABLE_PROVISIONAL/title",
          "value": "MTR_ENABLE_PROVISIONAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTR_ENABLE_PROVISIONAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTR_ENABLE_PROVISIONAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventIsHistoricalKey/title",
          "value": "MTREventIsHistoricalKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTREventIsHistoricalKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTREventIsHistoricalKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPreviousDataKey/title",
          "value": "MTRPreviousDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRPreviousDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRPreviousDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTR_NO_AVAILABILITY/title",
          "value": "MTR_NO_AVAILABILITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTR_NO_AVAILABILITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTR_NO_AVAILABILITY"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/matter-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/matter-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
